### ISSUE TITLE
spring-boot-sample-jta-jndi/

### ISSUE THREAD

**Issue by tannaalok** [spring-projects/spring-boot#10046]
In this Sample it say in the end 
Once running you can deploy the application by copying target/spring-boot-sample-jta-jndi.war
but from where can I find target/spring-boot-sample-jta-jndi.war ? this file.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
Most likely you haven't run `mvn` to build the project.
