### ISSUE TITLE
How to configure tomcat shutdown listener port in application.properties

### ISSUE THREAD

**Issue by langman** [spring-projects/spring-boot#10059]
Hi,
I already have one tomcat instance running on linux, its shutdown listener port is 11205,
`<Server port="11205" shutdown="SHUTDOWN">`
when I start spring boot,it causes an exception,
`Failed to start end point associated with ProtocolHandler ["http-nio-11205"]`
`java.net.BindException: Address already in use`
then, I modify the running tomcat instance shutdown listener port to 11204, it also causes an exception,like
`Failed to start end point associated with ProtocolHandler ["http-nio-11204"]`
`java.net.BindException: Address already in use`
so, I want to configure a tomcat shutdown listener port for spring boot, and then have a try.
thanks.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
