### ISSUE TITLE
A bug about springboot restful api

### ISSUE THREAD

**Issue by trying-cui** [spring-projects/spring-boot#10055]
I use spring-boot-starter-parent:1.5.6.RELEASE in my app, where I want to code restful api . But there is a bug when i write more than two api controller with same annotation.
For example,
in AxxController.java , there is a method test1 with annotation:
`@GetMapping(produces = "application/json")`
and also in BxxController.java , there is a method test2 with annotation:
`@GetMapping(produces = "application/json")`

Although  they have different RestController mapping, but throw an exception like "Ambiguous mapping...." , and the code is in the class AbstractHandlerMethodMapping, which is in the spring-webmvc:4.3.10.RELEASE
`
private void assertUniqueMethodMapping(HandlerMethod newHandlerMethod, T mapping) {
			HandlerMethod handlerMethod = this.mappingLookup.get(mapping);
			if (handlerMethod != null && !handlerMethod.equals(newHandlerMethod)) {
				throw new IllegalStateException(
						"Ambiguous mapping. Cannot map '" +	newHandlerMethod.getBean() + "' method \n" +
						newHandlerMethod + "\nto " + mapping + ": There is already '" +
						handlerMethod.getBean() + "' bean method\n" + handlerMethod + " mapped.");
			}
		}
`

and the bug is at `  this.mappingLookup.get(mapping);` , with the mapping don't contains the api class 's requestmapping to diff the two method mapping.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
