### ISSUE TITLE
The annotation @ComponentScan doesn't work.

### ISSUE THREAD

**Issue by SPRINGJICHUN** [spring-projects/spring-boot#10061]
I use Spring boot and spring data jpa in my project. 
The main method is in the class ccc.aaa.Application.
But some beans in the package ccc.bbb.
I try to use @ComponentScan on the org.aaa.Application.
But it doesn't work!
the code like this:
```java
package ccc.aaa;
@SpringBootApplication
@ComponentScan("ccc")
public class Application {
  /**Spring boot main method*/
}
```
```java
package ccc.bbb;
public interface UserRepository extends CrudRepository<User, Long> {
  Long countByLastname(String lastname);
}
```
I tried different version. But not useful!
Thanks very much!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by SPRINGJICHUN** [comment]
Ok, thank you
