### ISSUE TITLE
The key of Map is not correctly retrieved from MongoDB

### ISSUE THREAD

**Issue by shuitingjianle** [spring-projects/spring-boot#10067]
The issue happens on Spring Boot 2.0.0.M3. I have the Class below:
```
@Document(collection="note")
public class Note{
  String id;
  Map<String, Object> map;
}
```
I can successfully save the documents of note to MongoDB. And below is an example of the data in MongoDb.
```
{ "_id" : ObjectId("599e67352ec76354b611a931"), "map" : { "a" : 1, "ab" : 2, "abc": 3 },  "_class" : "cn.test.domain.Note" }
```

Everything looks fine. But when I retrieve the data from MongoDB using the REST API, the keys of the map are gone, and become some dots.
The code for the REST API to retrieve the data in Mongo is:
```
@GetMapping(value = "/{id}")
    public Mono<Note> getNote(@PathVariable String id){
        return noteRepository.findById(id);
    }
```
And the result the API returns:
```
{
  "id": "599e67352ec76354b611a931",
  "map": {
    ".": 1,
    "..": 2,
    "...": 3
  }
}
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by shuitingjianle** [comment]
I don't understand why this issue should be on Stack Overflow. It don't think this is any configuration related problem.
