### ISSUE TITLE
Env var for active profiles in config yaml

### ISSUE THREAD

**Issue by tusharm** [spring-projects/spring-boot#10063]
Spring Boot: 1.5.6.RELEASE
JDK: 1.8.0_121
OS: Mac OS X Sierra 10.12.5

Hi,

I have a REST resource like this:
```
@RestController
public class HelloResource {
  @Autowired private DepA depA;
  @Autowired private DepB depB;

  @RequestMapping("/hello")
  public String get(@RequestParam("user") String user) {
   // do something
  }
}
```
The dependencies `DepA` and `DepB` are conditionally loaded, based on active profiles:
```
@Component
@Profile("depa")
public class DepA {}
...
@Component
@Profile("depb")
public class DepB {}
```
My `application.yml` looks like this:
```
...
spring.profiles.active: ${PROFILES}
...
```

**Observation**
With env var `PROFILES` as `depa,depb`, application startup fails with:
```
Field depA in com.cm.resources.HelloResource required a bean of type 'com.cm.DepA' that could not be found.
```

However, if I set it like this, the app boots up and works as expected. 
```
spring.profiles.active: depa,depb
```

I'm wondering if there is an issue around env var parsing in config?  

Thanks!

**Comment by wilkinsona** [comment]
The problem is connected with the handling of lists in YAML configuration. When you use the indirection of `${PROFILES}` a single profile named `depa,depb` is activated. When the indirection is removed `depa,depb` is treated as a comma-separated list and profiles `depa` and `depb` are both activated.

This behaviour has been improved in 2.0 and the use of `${PROFILES}` will now behave as you'd like. You can try a snapshot (available from https://repo.spring.io/snapshot) or milestone (available from https://repo.spring.io/milestone) to try this for yourself.
