### ISSUE TITLE
Use log4j2 as the default logging instead of logback

### ISSUE THREAD

**Issue by beihaifeiwu** [spring-projects/spring-boot#10072]
The spring data elasticsearch has the direct dependency dependency on the log4j2, and I didn't see any direct dependency on the logback . So I think use log4j2 as default logging framework is better : )

**Comment by hantsy** [comment]
Personally I prefer Logback and Slf4j, it is more flexible and seamless to integrate with the existing Log4j, Log4j2, jcl etc, and more easy to use it with external logging analyst system.

**Comment by stepio** [comment]
As for me, while switching from `log4j` (old-school) I've compared both `logback` and `log4j2` and found 1 mandatory case (for me), which is supported in `log4j2`, but not in `logback`:
```
        <Async name="ASYNC">
            <AppenderRef ref="MainToFile"/>
            <AppenderRef ref="ErrorToFile"/>
            <AppenderRef ref="FatalToConsole"/>
        </Async>
```

I did not find a way to wrap multiple appenders into a single asynchronous appender in `logback`.

Hi @hantsy 

But you can still use `slf4j` backed with `log4j2`. Seamless integration is a feature of `slf4j`, which does not depend on `logback`. Not sure what is meant behind "external logging analyst system", but in `log4j2` you can configure the same logging patterns as you use in `logback`.

**Comment by hantsy** [comment]
@stepio I understand your situation.  

I have written some sample codes for configure logging in Spring 4 when it was released. https://github.com/hantsy/spring4-sandbox , check the `logging-` prefix samples.

Spring 5 will extract it's jcl to a standard `spring-jcl`,  and it will detect any logging framework you are using.  

In before experience, I would like use the neutral Slf4j  APIs(some bridge for other logging framework in dependencies),  thus I do not care about any backend logging framework.  In a Spring project, if the project dependencies use another logging frameworks, and finally in your projects, it could include several logging frameworks.

Slf4j can bridge all of them, and collect logging data in a form, such as logback config.

**"external logging analyst system**, I means I would like use some cloud platform or ELK to visualize the logging info instead of traditional Files, Email notification.

**Comment by stepio** [comment]
@hantsy 

I've just added another reason to make `log4j2` a default logging implementation for `spring-boot`.
I don't think that "use the same logging as in elastic search" is a really strong reason, but supported this issue as another `log4j2` user.

In your comment above you talk about `spring-framework`, which is a bit irrelevant.

Also I checked your repo, here is `logback` config:
https://github.com/hantsy/spring4-sandbox/blob/master/logging-logback/src/main/resources/logback.xml
No solution for the example which I showed, no appender with nested appenders there.

**Comment by wilkinsona** [comment]
Using Log4j2 instead of Logback should be straightforward. Exclude Logback and depend on Log4j2 instead. Thanks for the suggestion, but I haven't seen any arguments in this issue that justify the breaking change of switching to Log4j2 by default. We'll stick with Logback for now at least.

**Comment by rgoers** [comment]
Although this issue is closed I am adding this information for users who stumble upon this issue.

Log4j 2.12.0 added support for utilizing Spring Cloud Config to host the Log4j configuration with dynamic reconfiguration and added support for Docker. 

With the release of Log4j 2.13.0 Log4j has further integrated with Spring by providing a Spring Lookup so the Log4j configuration can access spring properties. In addition, some Log4j system properties can also be read from Spring's bootstrap.yml or application.yml files. 2.13.0 also provides a Kubernetes Lookup to allow Kubernetes attributes to be specified in the Log4j configuration as properties to include in the log events.

Log4j 2 will continue to try to improve its Spring integration as requested by users.

See [Logging in the Cloud](http://logging.apache.org/log4j/2.x/manual/cloud.html) and [Log4j Spring Cloud Config Client](http://logging.apache.org/log4j/2.x/log4j-spring-cloud-config/log4j-spring-cloud-config-client/index.html).
