### ISSUE TITLE
requestBody is missing when i post json with angular2 http 

### ISSUE THREAD

**Issue by 395779222** [spring-projects/spring-boot#10075]
1.angular psot json 
`this.http.post('http://localhost:8080/city/detail/1',{"city":"11111"},null).map((res: Response) => res.json()).subscribe(res => {
        observer.next(res.data);
      });
   `
2. 
`@Override
    public void doFilter(final ServletRequest request, final ServletResponse servletResponse, final FilterChain filterChain) throws IOException, ServletException {
        //解决此处读取request的流后 @RequestBody读取不到流的情况
        BodyReaderHttpServletRequestWrapper requestWrapper = new BodyReaderHttpServletRequestWrapper((HttpServletRequest) request);
        String reqBody = IOUtils.toString(requestWrapper.getReader());
        requestWrapper.resetInputStream();
        filterChain.doFilter(requestWrapper, servletResponse);
    }`

in my angular2 project,i sent my data to serve with angular http then in my springboot project , i  get my RequestBody is ' ' when i run  'String reqBody = IOUtils.toString(requestWrapper.getReader())'. 
but if i post json with postman ,everything works ok .

also everything works ok  in a new springMVC project when is post json with angular2 http.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
