### ISSUE TITLE
Unable to stop the MessageListenerContainer using stop() method

### ISSUE THREAD

**Issue by duggu9** [spring-projects/spring-boot#10097]
Hi,

I have two JMS subscribers in my application. I want to start and stop both the subscribers explicitly. I am able to start but not able stop. Below is the piece of code to stop a subscriber explicitly. Can someone help me in this regard. Thanks

JmsListenerEndpointRegistry jmsListenerEndpointRegistry = (JmsListenerEndpointRegistry) context.getBean(JmsListenerEndpointRegistry.class);
MessageListenerContainer messageListenerContainer = jmsListenerEndpointRegistry.getListenerContainer(subscriber);
messageListenerContainer.stop();

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
