### ISSUE TITLE
JpaEntityInformation could not be found

### ISSUE THREAD

**Issue by jlamasbr** [spring-projects/spring-boot#10095]
Question:

When I start my application with spring boot 2.0.0.M3 the application show the error message:

============================================================================

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in br.com.jetidea.core.commons.repository.JetRepositoryImpl required a bean of type 'org.springframework.data.jpa.repository.support.JpaEntityInformation' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.data.jpa.repository.support.JpaEntityInformation' in your configuration.

==============================================================================

But with spring boot 2.0.0.M1 My application run normaly without errors. 
Does anyone know why?

My Starter class :

**
@SpringBootApplication
@EnableTransactionManagement
@EnableScheduling
@EnableAutoConfiguration
@ComponentScan("br.com.jetidea")
@Import({ AuthConfig.class, JetConverterConfiguration.class, RestTemplateConfiguration.class,
        AspectConfig.class })
@EntityScan("br.com.jetidea")
@EnableJpaRepositories(repositoryBaseClass = JetRepositoryImpl.class, basePackages = "br.com.jetidea", includeFilters = @ComponentScan.Filter(value = Repository.class, type = FilterType.ANNOTATION))
public class ApiStarter {

    public static void main(String[] args) {
        SpringApplication.run(ApiStarter.class, args);
    }

    @Bean
    public TaskScheduler scheduler() {
        return new ThreadPoolTaskScheduler();

    }

}
**

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
