### ISSUE TITLE
Spring Boot cannot start web application, stopped after the logo

### ISSUE THREAD

**Issue by bangph** [spring-projects/spring-boot#10091]
I have a very weird problem with Spring Boot, I don't know why the web application which using Spring Boot cannot start and it has no output error even when I run it directly on terminal.

java -jar /var/lib/tomcat/webapps/rasdaman.war 
log4j:WARN No appenders could be found for logger (org.springframework.web.context.support.StandardServletEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.2.RELEASE)

[rasdaman@osboxes rasdaman]$ echo $?
1

Here is the application class https://pastebin.com/rinWbp9z, this web application uses Liquibase to populate database schema and Spring boot version 1.5.2. Can you please share some hint to debug?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by snicoll** [comment]
See [re-posted question on StackOverflow](https://stackoverflow.com/questions/45919310/spring-boot-1-5-2-web-application-stops-after-loading-logo)
