### ISSUE TITLE
Compile Error in Java6

### ISSUE THREAD

**Issue by chadwick521** [spring-projects/spring-boot#10108]
My JDK is Java6, so when i build this ant project, 
`bad class file: org/springframework/boot/SpringApplication.class(org/springframework/boot:SpringApplication.class)
    [javac] class file has wrong version 52.0, should be 50.0
    [javac] Please remove or make sure it appears in the correct subdirectory of the classpath.
    [javac] import org.springframework.boot.SpringApplication;`
could u tell me how tofix it?

**Comment by chadwick521** [comment]
my current project is org.springframework.boot.ant
this is my shell code:
`
ant build
`

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
