### ISSUE TITLE
Duplicate values should bind properly to List 

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#10106]
With a property such as `List<String> xyz = new ArrayList<>()`, the binder doesn't add duplicate values because we use `CollectionFactory.createCollection(type, 0)` in `CollectionBinder` which gives us a `LinkedHashSet`.

**Comment by santpandey** [comment]
Hi,

I saw the issue and was just trying to do some initial analysis out of curiosity.
I have not replicated this issue, so I might be wrong here.

CollectionFactory.createCollection(type, 0) in turn calls 
createCollection(collectionType, null, capacity);

If we see [this]( https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/CollectionFactory.java) at line 178,

the condition is explicitly mentioned that if CollectionType(which is being passed) is List, it would return ArrayList.

Since the property contains List, it should return ArrayList ideally.

Please free to correct me if I am missing something here.

**Comment by thombergs** [comment]
Right, CollectionFactory.createCollection() was passed the wrong type originating in `AggregateBinder.bind()`. 

I replaced `ResolvableType.forClass(AggregateBinder.class, getClass()).resolveGeneric())` with `target.getType().resolve()` since I couldn't really see the need for resolving the type from the generic type from `AggregateBinder` subclasses. And the unit tests are still green, so either there are no side effects (or there's a test missing ;)).
