### ISSUE TITLE
java.security.cert.CertificateException: No name matching xxx.com found

### ISSUE THREAD

**Issue by junneyang** [spring-projects/spring-boot#10127]
oauth2 client get userinfo from oauth2 server fails through https, but with http it has no problem:

log error:
```
Could not fetch user details: class org.springframework.web.client.ResourceAccessException, 
I/O error on GET request for "https://www.auth.xproject.com:9999/uaa/user": 
java.security.cert.CertificateException: No name matching www.auth.xproject.com found; 

nested exception is javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching www.auth.xproject.com found
```

but curl could work:
![curl](https://user-images.githubusercontent.com/6802322/29920344-ad0efe8a-8e7f-11e7-9e53-681ec21e0622.png)

thanks for your help!

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
