### ISSUE TITLE
Use Thymeleaf 3 ，SpringSecurityDialect can't work 

### ISSUE THREAD

**Issue by helloworldtang** [spring-projects/spring-boot#10151]
pom.xml add:
<properties>
    <thymeleaf.version>3.0.2.RELEASE</thymeleaf.version>
    <thymeleaf-layout-dialect.version>2.1.1</thymeleaf-layout-dialect.version>
</properties>

spring boot version:1.5.6.RELEASE
according :https://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/htmlsingle/#howto-use-thymeleaf-3
```xml
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity4</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
```

but  SpringSecurityDialect not work:
html:

···html
       <div sec:authorize="isAuthenticated()">
            This content is only shown to authenticated users.
        </div>
        <br/>
        welcome:<span sec:authentication="name">name</span>!
        <br/>

        <div sec:authorize="hasAnyRole('ADMIN')">
            This content is only shown to administrators.
        </div>
        <br/>
        <div sec:authorize="hasAnyRole('USER')">
            This content is only shown to users.
        </div>
        <br/>
        <div sec:authorize="isAnonymous()">
            This content is only shown to anonymous.
        </div>
```

del 

<properties>
    <thymeleaf.version>3.0.2.RELEASE</thymeleaf.version>
    <thymeleaf-layout-dialect.version>2.1.1</thymeleaf-layout-dialect.version>
</properties>


it works.


why?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
