### ISSUE TITLE
JettyEmbeddedErrorHandler depends on org.eclipse.jetty.http.HttpMethod

### ISSUE THREAD

**Issue by hadix-lin** [spring-projects/spring-boot#10175]
I'm using spring-boot-1.5.6.RELEASE with jetty8. According to the document, I set the jetty.version to 8.1.15.v20140411. But the class `org.springframework.boot.context.embedded.jetty.JettyEmbeddedErrorHandler` depends on `org.eclipse.jetty.http.HttpMethod`. the later class belongs to jetty9.

when running into JettyEmbeddedErrorHandler , throws java.lang.NoClassDefFoundError: org/eclipse/jetty/http/HttpMethod.

**Comment by wilkinsona** [comment]
Thanks for the bug report. `JettyEmbeddedErrorHandler` was introduced to fix https://github.com/spring-projects/spring-boot/issues/5367. The easiest fix would be to just make it Jetty 9 specific. It's been in place since 1.3.4 which tells me that very few people are using Jetty 8 so that might not be so bad.

@hadix-lin what's your reason for using Jetty 8?

**Comment by hadix-lin** [comment]
my production environment only support jdk7, while jetty9 need jdk8.
