### ISSUE TITLE
Make ConversionServiceOperationParameterMapper not use BinderConversionService

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10184]
It feels a bit odd that `ConversionServiceOperationParameterMapper` uses the `BinderConversionService`. Perhaps there is a good reason, but it feels like it might be better to use the regular one.

**Comment by snicoll** [comment]
It does that because we need relaxed binding. 

Simple example: you have an enum on your Endpoint's method signature. You can't feed an enum in JConsole so we expose the String. But we are used to be able to provide enums in lower case if we want (We used to have some manual logic in the `LoggersMBean`). Those manual steps are going away because the conversion service takes care of that for us. 

The name of the class may not be the right call and perhaps we should rename it but we need relaxed binding there.

**Comment by wilkinsona** [comment]
A specific example is `LogLevel` that's consumed by the loggers endpoint.
