### ISSUE TITLE
Drop WebEndpointHandlerMappingCustomizer

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10186]
Can we drop `WebEndpointHandlerMappingCustomizer`? I'm not sure there is anything to customize.

**Comment by wilkinsona** [comment]
I think we can. The introduction of the customizer was done in 1.2 (https://github.com/spring-projects/spring-boot/issues/1933) to allow the mapping to be customised even when a child management context is being used. Since then we have introduced `@ManagementContextConfiguration` (in 1.3) which provides a more general purpose solution.

**Comment by snicoll** [comment]
Did we remove it in the meantime? It looks like it got removed or renamed?

**Comment by philwebb** [comment]
Yeah, I removed it as part of the refactor.
