### ISSUE TITLE
management.context-path cannot work alone

### ISSUE THREAD

**Issue by xyq000** [spring-projects/spring-boot#10200]
For a Springboot application with actuator, config its `applicaton.properties` as below

```
server.port=8888
server.context-path=/app
management.context-path=/manage
```

Start up the application, but find that `localhost:8888/manage/info` returns a 404 error. Furthermore, the `/info` endpoint could be visited via `localhost:8888/app/manage/info`.

What is confusing is that if I add `management.port=9999` into `application.properties`, then the `/info` endpoint can be visited via `localhost:9999/manage/info`.

Is it an intentional design or a bug to compose the application's management uri  as `host:port/${server.context}/${management.context-path}` when `management.port` is not set explicitly?

springboot version：1.5.6.RELEASE

**Comment by wilkinsona** [comment]
It is intentional. Setting `server.context-path` moves everything in the same embedded web container beneath that path. When you set management.port a separate embedded web container is used for the management context so it's no longer affected by `server.context-path`.

In 2.0, I think we should consider renaming `management.context-path` as `context-path` is overloaded and don't refer to the same thing.

**Comment by xyq000** [comment]
@wilkinsona thanks. It would be better if this feature mentioned on the docs [https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-customizing-management-server-context-path](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-customizing-management-server-context-path)

**Comment by mbhave** [comment]
@wilkinsona I like your idea of renaming it in 2.0. Since `management.context-path` isn't really affecting the server, I wonder if it should be something like `endpoints.base-path`.

**Comment by wilkinsona** [comment]
I've opened #10230 for the possible rename of `management.context-path`.
