### ISSUE TITLE
org.springframework.boot plugin break the dependency management

### ISSUE THREAD

**Issue by Leo-Lei** [spring-projects/spring-boot#10227]
Hi, team

I have created a custom spring boot starter, and it is a Maven project.
In this starter, it include some existing official spring boot starters, for example, the spring-boot-starter-data-redis starter. In addition, I also add some my own class, some other 3rd-party library, and want to override the version of some library which is provided by spring boot. For example, the spring boot 1.5.4.RELEASE include the org.mockito:mockito-core library, and the version is 1.10.19. 
In my starter, I add exclusion in pom to exclude the mockito-core transitive dependency, and add a new version of mockito-core, that is 2.8.47.

In my another Gradle project, it have the above custom starter in the build.gradle: 
`compile("com.mycompany:my-starter:1.0.0.RELEASE")`
The version 2.8.47 of mockito-core is included, it works fine. But when I add the org.springframework.boot plugin to project, there are two versions of mockito in class path, 1.10.19 and 2.8.47, I don't know why.

I know inner spring boot gradle plugin, it include the io.spring.dependency-management plugin. If I use  io.spring.dependency-management plugin, instead of org.springframework.boot plugin, there is only 2.8.47 of mockito in class path.

Could you help to look into this, or if there is any other better solution for my scenario? Thanks.

**Comment by Leo-Lei** [comment]
I don't want to add additional exclusion in the build.gradle. As the custom starter is a common library, I want to manage the dependency and resolve the versions problem inner the starter, and the project which want to use this starter only need to simplify add it as a dependency in build.gradle, no other configuration is needed.

**Comment by wilkinsona** [comment]
Gradle should never give you two different versions of the same dependency on the class path. If you'd like us to investigate, you'll need to provide a sample project that reproduces the problem.

**Comment by Leo-Lei** [comment]
Sorry for delay, I will prepare a sample project and then let you know ASAP, thanks a lot.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by phstudy** [comment]
I also faced this problem. I have created a [sample project](https://github.com/spring-projects/spring-boot/files/1313193/gradle-dep.zip). The cassandra library version in subproject `component-1` is not the defined version `2.1.10.3`, but `3.1.4`.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by snicoll** [comment]
It's been a while now, let's reopen if you manage to provide a sample.

**Comment by thelmstedt** [comment]
Hi @snicoll 

I've run into the same/similar issue (with gradle instead of maven). The presence of the `spring-boot-gradle-plugin` definition changes my dependencies, and in a way which seems impossible to override. See the following minimal build.gradle, where the transitive dependencies of my declared dependency have been overridden.

    plugins {
        id 'org.springframework.boot' version '1.5.8.RELEASE'
    }

    apply plugin: 'java'
    repositories {
        jcenter()
    }

    dependencies {
        compile "org.elasticsearch.client:elasticsearch-rest-high-level-client:5.6.1"
    }

Note while it's possible to work around this specific example by declaring the transitive dependencies directly, this a) doesn't scale to many dependencies and b) doesn't seem to work across multi module builds.

I would expect adding compile dependencies on the `spring-boot-*` packages to result in changed dependencies, but never a plugin! This is terrifying - when I diffed my production dependencies in this manner I got a 370 line diff!

**Comment by thelmstedt** [comment]
It's possible this is caused by #3164 - but I can't tell b1f9123311e0579d6b4c01f375611e0c0086a5d6 is applied to 1.5.8 yet - or if there's plans to backport it if not?

**Comment by thelmstedt** [comment]
Backported it here: https://github.com/spring-projects/spring-boot/pull/10766

**Comment by snicoll** [comment]
@thelmstedt this issue has nothing to do with Gradle.

**Comment by thelmstedt** [comment]
Ahh, the initial report was hard to read sorry. I was concentrating on 

> In my another Gradle project, it have the above custom starter in the build.gradle:
compile("com.mycompany:my-starter:1.0.0.RELEASE")
The version 2.8.47 of mockito-core is included, it works fine. But when I add the org.springframework.boot plugin to project, there are two versions of mockito in class path, 1.10.19 and 2.8.47, I don't know why.

This is the exact problem that I am having (and have verified that b1f9123 fixes in my pull request https://github.com/spring-projects/spring-boot/pull/10766).

I'm gonna just guess that the maven issues he was having was also due to the dependency management being misapplied (as fixed in gradle in b1f9123)
