### ISSUE TITLE
error using kundera

### ISSUE THREAD

**Issue by publicocean0** [spring-projects/spring-boot#10237]
```
	... 21 more
Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/META-INF/persistence.xml]
```

related to 
`@Configuration
public class KunderaConfig {

    @Bean
    protected LocalContainerEntityManagerFactoryBean post() {
        LocalContainerEntityManagerFactoryBean emf = new LocalContainerEntityManagerFactoryBean();
        emf.setLoadTimeWeaver(new org.springframework.instrument.classloading.InstrumentationLoadTimeWeaver());
        emf.setPersistenceUnitName("cassandra_pu");

        return emf;
    }

    @Bean
    protected org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor pp() {
        return new org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor();
    }
    @Bean
    protected org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager dd(){
        org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager d=new org.springframework.orm.jpa.persistenceunit.DefaultPersistenceUnitManager();
        d.setPersistenceXmlLocation("META-INF/persistence.xml");
        return d;
    }

}`

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by publicocean0** [comment]
ok a suggestion :   
LocalContainerEntityManagerFactoryBean might not receive xml or other specific inplementation of the persistent layer: it might receive a implementation class of the persistence . In this way it is more simple to realize a version receiving a xml , another a map ,.... another a composition of many persistent units .... Also kundera could be integrated better.
