### ISSUE TITLE
How to do the following tasks in a WebFilter?

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#10242]
I've a `WebFilter` in a functional web app where I want to do the following. Unfortunately, the Javadoc is reminiscent of [this](https://twitter.com/jeranfox/status/904135744913940480), and the more I try, the more I get the application messed up.

1. **Session management** - Create if one doesn't already exist. I'm getting the session out of `ServerWebExchange` and calling `isStarted` on it - is this the way?
2. **Send redirect without processing rest of the filter chain** - I'm setting a `Location` header in the response and status `307`, then calling `setComplete`, but the desired endpoint is never invoked.
3. **Set request headers** - I want to set a request header. Following is how I'm doing it which seems overly complicated for such a simple task.
```
val modifiedExchange = exchange.mutate().request(
     exchange.request.mutate().header(SESSION_ID, sessionId).build())
    .build()
    .also { it.response.beforeCommit { session.save() } }

chain.filter(modifiedExchange)
```

1 and 2 are suited for Spring security, but then, I couldn't find any docs for using that with the functional model.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by asarkar** [comment]
https://stackoverflow.com/q/46170274/839733
