### ISSUE TITLE
Remove existing OAuth auto-configuration support

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10255]
Spring Security 5.0 will have some OAuth auto-configuration and 5.1 will add some more. See [this comment](https://github.com/spring-projects/spring-boot/pull/10235#issuecomment-328564170) from @jgrandja. We need to figure out how to adopt this new functionality while also phasing out the old stuff.

I think we have three options:

1.  Removing all of the old OAuth auto-configuration in 2.0 (as it's the time for breaking changes) and then phasing in auto-configuration for the support in Spring Security 5.x as it becomes available. This will require people to configure somethings manually in 2.0 that were auto-configured in 1.5.
2. Keep our current OAuth configuration in 2.0 and make a breaking change in 2.1 when an equivalent is available in Spring Security 5.1
3. Keep our current OAuth auto-configuration in 2.0. Support Spring Security 5.1's new stuff in 5.1 (so we now have two ways of doing the same thing) and remove the old, now overlapping stuff in Boot 3.0

I am currently in favour of 1.

**Comment by snicoll** [comment]
Definitely not in favour of the third. Perhaps 1 could be mitigated a bit by providing some helper classes? Or move that code outside of the main support?

**Comment by rwinch** [comment]
Perhaps a good compromise would be to move the old OAuth auto-configuration from Boot into a module within [spring-security-oauth](https://github.com/spring-projects/spring-security-oauth). Given Boot 2.0 will no longer depend on Spring Security OAuth I do not think we would have any dependency cycles. If we did encounter cycles, we could also release the old OAuth auto configuration as a separate project.

**Comment by philwebb** [comment]
My take is that we remove all our existing OAuth code and focus on merging client support (#10235) with a clean slate. We can then look at what should happen with the server support.

I personally don't think any module in `spring-security-oauth` should depend on `spring-boot`.

We probably need to take some tough decisions with OAuth. I really don't feel like anything other then auto-configuration should be in Boot 2.0. We might have to accept that existing users will need to stick with Boot 1.x (or roll their own solution) until Spring Security 5.1 and Boot 2.1 are released.

**Comment by jgrandja** [comment]
I'm in agreement with @philwebb proposal  ..remove all existing OAuth code and focus on merging the new client support.

Auto-config for Authorization Server IMO is not a good idea anyway as it's too risky and the user really should be responsible for tightly configuring an Authorization Server with all the security constraints based on requirements. 

As far as Resource Server configuration goes, it's doesn't take much for the user to manual configure via `@EnableResourceServer` so I don't think this will be much of an issue. As well, we're planning on bringing new Resource Server support and auto-config by Mar-Apr so there will be a gap of about 4-5 months only.

Lastly, they can always stay on Boot 1.x if they don't want to lose the auto-config and then migrate to Boot 2.1 after Spring Security 5.1 is released with the Resource Server support.

**Comment by snicoll** [comment]
I'd like that too as long as we make sure Spring Cloud (and other modules in the portfolio) aren't using any of that support. We can't afford to leave them with 1.x

**Comment by dsyer** [comment]
Seems like a bit of a rock and a hard place. FWIW I'd rather see the existing behaviour supported through a separate module, even if it has to live in its own (temporary) github project, than drop it all on the floor.

Some of the Boot features in OAuth2 should have been in Spring Security already (`UserInfoTokenServices` and friends mostly). But we have dropped the ball on that. Those bits still probably could be cleanly lifted into Spring Security OAuth2, at least so they have a home while Spring Security 5.x gets its act together. The equivalent feature (a resource server filter that uses a user token) could be implemented for Spring Security 5.0 clients quite quickly. Maybe we should do that, and if we did it would make it more compelling to have a separate, temporary project to give it a home.

There are 3 aspects to OAuth2 configuration, representing 3 roles of the actors in the protocols: client, resource server and authserver. The vast majority of Spring Boot users who need OAuth2 are clients, and quite a lot of those are also resource servers. More opinions follow...

* Spring Security 5.0 has new support for clients, if I understand correctly, so we should adopt that somewhere that Spring Boot users can reach. I don't much care if it is Spring Boot 2.0 or some other thing. The only reason I can think of for it not being Spring Boot 2.0 is if is complicates the resource server configuration (because some of the configuration can be shared between resource and client when a service plays both roles).

* Spring Security 5.1 aims to have support for resource servers. Is it going to match the features of the existing project, or just cover some of them, leaving gaps? It would help to know, but even so, we would need to support autoconfiguration somewhere in the transition period.

* Authserver autoconfig is a minority constituency (I guess), but I don't think we should abandon it completely (even temporarily). OAuth2 is popular and a little but tricky to get right, so people need a way to try it out and get it working quickly, so they can understand it and customize it. Having a native authserver is essential to that, and making it easy to get started with convention over configuration is a Boot feature, not a Security feature.

**Comment by wilkinsona** [comment]
- Auto-configuration for Spring Security 5's OAuth client support is coming in Boot M5 (#10235).
- No objections to auto-configuration for resource server "stuff" during the transition period. The auto-configuration needs to be owned by someone with Security and OAuth expertise and it needs to live outside of Boot so that it's clear that it's transitionary
- The Security team's [opinion](https://github.com/spring-projects/spring-boot/issues/10255#issuecomment-330679837) is that "auto-config for Authorization Server IMO is not a good idea anyway as it's too risky and the user really should be responsible for tightly configuring an Authorization Server". Perhaps there's something to be done to make the configuration easier while also requiring explicit configuration. If so, that code belongs somewhere other than Boot.
