### ISSUE TITLE
Problems with communicate to the Angular frontend

### ISSUE THREAD

**Issue by lukecorf** [spring-projects/spring-boot#10252]
Node.js Version: 8.2.1
Windows 10
IDE: Intellij
Frameworks: Spring Boot & Angular 4

Well... I need get data from my backend (Java). But Angular terminal show this message error:

[HPM] Error occurred while trying to proxy request /api/dados from localhost:4500 to http:/localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

This is my Angular code:

![a](https://user-images.githubusercontent.com/22321349/30277286-b91f5cae-96dd-11e7-87f6-b4af4439a579.jpg)

And this is my Java Code:

![as](https://user-images.githubusercontent.com/22321349/30277310-c192de74-96dd-11e7-8957-76a0dd7d852a.jpg)

My Tomcat is configurated to 8080 port

![sem titulo](https://user-images.githubusercontent.com/22321349/30277321-cb017f38-96dd-11e7-961a-22e917833926.jpg)

And my proxy in angular is configurated like this image:

![asd](https://user-images.githubusercontent.com/22321349/30277351-e44be2f8-96dd-11e7-9c53-0eafb0127925.jpg)

Someone can help me please? This is important

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
