### ISSUE TITLE
Spring executable jar inside the JS file garbled

### ISSUE THREAD

**Issue by j2eegis** [spring-projects/spring-boot#10269]
Local operation is normal, put on the Linux will appear garbled
spring boot version 1.5.6.RELEASE
`thymeleaf:` 
    &nbsp; &nbsp;` cache: true`
    &nbsp; &nbsp;` mode: html`
Written in HTML Chinese showed normal ,in JS Chinese will be garbled, as for ‘И║╣‘

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
