### ISSUE TITLE
Add tests to ensure EndpointRequest security matchers work with a context path and different port

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10260]
The `EndpointRequest` class might not work when a servlet context path is set (with and without a different port). We should add additional tests.

**Comment by mbhave** [comment]
let's wait for #10230 to add these tests.

**Comment by mbhave** [comment]
Moving to M6 as #10230 is scheduled for M6.

**Comment by mbhave** [comment]
I don't think adding a unit test for this will test this since we just just create an `AntPathRequestMatcher` from the `endpoints.web.base-path`. [These tests](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-actuator-custom-security/src/test/java/sample/actuator/customsecurity/ManagementPortAndPathSampleActuatorApplicationTests.java) for the sample with custom security should take care of this.
