### ISSUE TITLE
How to encrypt server.ssl.key-store-password value and use it in SpringBoot

### ISSUE THREAD

**Issue by nagraj321** [spring-projects/spring-boot#10283]
Question

I would like to know is there anyway we can encrypt the **_server.ssl.key-store-password_** value and store it in application.properties file instead of storing it in plain text.

Thanks
Nagaraju

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by uythoang** [comment]
@nagraj321 I have this same question and was wondering if you ever ended up getting an answer in Stack Overflow or elsewhere. Thanks.

**Comment by nagraj321** [comment]
@uythoang No i haven't received any information on this thread.

**Comment by neuzxy** [comment]
@nagraj321 @nagraj321  Hi, Have you solved the problem?   I have this same problem.

@wilkinsona  Does spring boot provide custom server-side ssl configuration method？  Thanks.
