### ISSUE TITLE
spring boot project, the controller method is executed, the filter intercepted the view information

### ISSUE THREAD

**Issue by liudaze** [spring-projects/spring-boot#10324]
Hi, In my spring boot project, the Filter had intercepted my controller method executed result when the result info is a ModelAndView. 
My Filter code:

> @Component
> public class MyFilter implements Filter {
>      @Override
> 	public void init(FilterConfig filterConfig) throws ServletException {
> 	}
> 	@Override
> 	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
> 			throws IOException, ServletException {
> 		String url = ((HttpServletRequest) request).getRequestURI();
> 		System.out.println(url);
> 		chain.doFilter(request, response);
> 	}
> 	@Override
> 	public void destroy() {
> 	}
> }

Controller Code:

> @Controller
> public class IndexController {
>     @RequestMapping("/index")
>     public String index() {
>         // nothing need to do
>     	return "index";
>     }
> }

   when i request the _/index_，the filter executed result is:
```
/index
/WEB-INF/view/index.jsp
```
why interceped the request of return view？

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
