### ISSUE TITLE
@docoument  model  如何配置不同的bucket

### ISSUE THREAD

**Issue by Ssunnyy** [spring-projects/spring-boot#10356]

**Comment by Ssunnyy** [comment]
spring data couchbase 配置多个bucket 后
@docoument  model  如何配置不同的bucket

**Comment by wilkinsona** [comment]
Google translate tells me that the above says:

> spring data couchbase After configuring multiple bucket
@docoument model How to configure a different bucket

Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
