### ISSUE TITLE
Document expected format for commit.time and build.time in git.properties

### ISSUE THREAD

**Issue by allnightlong** [spring-projects/spring-boot#10392]
For this specific date format GitProperties converting it back to timestamp, so it's not possible to format my git commit date with this template.
https://github.com/spring-projects/spring-boot/blob/4a8d3532631d593f98885723ddcdafcd5fdb4243/spring-boot/src/main/java/org/springframework/boot/info/GitProperties.java#L106

**Comment by wilkinsona** [comment]
Sorry, I don't understand the problem that you're trying to report. 

The time is deliberately converted to epoch time so that it's in a consistent format. This time is then exposed as a `Date`. Typically, this `Date` will be serialised to JSON by Jackson when locking at Actuator's info endpoint. The formatting can then be controlled by Jackson's configured (serialisation of dates as timestamps, date format, etc).

Can you please describe you problem in more details. A detailed description of the behaviour that you are seeing and the behaviour that you expect to see would be useful. A failing test case would be even better.

**Comment by allnightlong** [comment]
Sure, I can describe the case.
I'm using 'com.gorylenko.gradle-git-properties' gradle plugin (https://github.com/n0mer/gradle-git-properties) to add git.properties to my jar.
This plugin provides 2 params: 'dateFormat' and 'dateFormatTimeZone' (names are self-explanatory)

So if I provide any correct dateFormat to my gradle.properties file, I'm basically getting what I'm expecting. For example, for  dateFormat = "yyyy-MM-dd'T'HH:mmZ", I've got such json from my /info endpoint:
![2017-09-23_22-27-20](https://user-images.githubusercontent.com/360961/30776401-6f4cf354-a0ae-11e7-9001-cfe4b2b20457.png)
Hence, there is no seconds in this date format.

But for one specific dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ", spring-boot formats my time to currentTimeMillis:
![2017-09-23_22-30-05](https://user-images.githubusercontent.com/360961/30776419-cad0ebb8-a0ae-11e7-966a-474c1b82f8b1.png)
First of all, this is counter-intuitive (honestly, I've spend quite some time to get to the very reason of that). I would ignore this date format, but, apparently, it's ISO 8601 format, which is kinda useful for my purposes.

If it is difficult to change this behavior to more predictable due to compatibility issues, may be it is possible to provide 2 fields in resulting json: 1st is changed and 2nd - unchanged?

**Comment by wilkinsona** [comment]
Thanks, I think I understand what's happening now.

Boot's `GitProperties` expects the commit time to be formatted with `yyyy-MM-dd'T'HH:mm:ssZ`. When it is, that value is coerced into a long (epoch time) and then exposed as a `Date`. This is what's happening in your second example. Jackson has formatted the `Date` as a timestamp (presumably because that's what you've configured it to do).

When the commit time doesn't match the expected format it's left as-is and as a String. With `management.info.git.mode=full` enabled it's then exposed as a String in that format and won't be affected by Jackson's date formatting configuration as Jackson has no way of knowing that it's a date.

We you use ``yyyy-MM-dd'T'HH:mm:ssZ` as the format for the time in `git.properties`, Boot is currently working as designed and you need to configure Jackson to serialise the Date into your desired format. This is the recommended approach as it means that the date will be formatted the same as any other date that your application serialises to JSON.

Given that both the Maven and Gradle plugins for generating `git.properties` allow the date format for the commit time to be configured, we should document the expected format for the commit time in `git.properties` so that users can configure it as required.
