### ISSUE TITLE
Crash log of spring boot embedded Tomcat

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-boot#10433]
I am using Spring boot 1.5.7 with its embedded Tomcat container. 
I am new to Spring boot. I run with as a standalone `jar via java -jar myApp.jar`
I set the log file and tomcat location in the `application.properties`:
```
logging.file=myApp.log
server.tomcat.basedir=./tomcat
```
However, the app exits quite often QUIETLY. In the log file nothing informative of the exit.
So my question is how to enable some more detailed logging of the application, or is there some method can be used to trouble shooting in this situation?
Thanks!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by raderio** [comment]
https://stackoverflow.com/questions/34932368/where-is-the-crash-log-of-spring-boot-embedded-tomcat
