### ISSUE TITLE
Test class Reinstantiating per @Test case

### ISSUE THREAD

**Issue by tranhungt** [spring-projects/spring-boot#10441]
I am using `@PostConstruct` to do some initial setup before running tests, but it seems like the `@PostConstruct` method is running on each and every test, instead of only once after the test class is called. I also see that the constructor is being called before each and every test before the `@PostConstruct`. Is this a bug?

I am using `spring-boot-starter-test:1.5.7.RELEASE`

Sample test setup:

```
@RunWith(SpringRunner.class)
public class TestClass {

    public TestClass() {
        System.out.println("constructor");
    }

    @PostConstruct
    public void setup() {
        System.out.println("setting up");
    }

    @Test
    public void test1() {
        System.out.println("test 1");
    }

    @Test
    public void test2() {
        System.out.println("test 2");
    }
}

In the output, 'constructor' is printed twice, and 'setting up' is printed twice. 'test 1' and 'test 2' are printed once each.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by tranhungt** [comment]
I can't find the reason why the class is initialized upon each new @Test instead of once for all tests.
https://stackoverflow.com/questions/46480775/why-does-springrunner-test-reinitialize-the-class-on-each-test
