### ISSUE TITLE
Upgrade to a Cassandra version that works with Java 9

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#10453]
See [CASSANDRA-9608](https://issues.apache.org/jira/browse/CASSANDRA-9608). Our sample is disabled on Java 9 at the moment.

See also https://github.com/jsevellec/cassandra-unit/issues/249

**Comment by umangsingh123** [comment]
Do we have any update on this issue ..

Hi ,
i am in the process of Migrating our App to JDK 11 and we are using this API as our Unit testing framework for Cassandra .
It gives me the below exception which i think aligns as per the thread.
Could you let me know when are you planning to have a fix for this .

java.lang.ExceptionInInitializerError at org.cassandraunit.utils.EmbeddedCassandraServerHelper.rmdir(EmbeddedCassandraServerHelper.java:294) at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:105) at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:88) at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:80) at com.bestbuy.esp.dao.TestActivationPackageDAO.startCassandraEmbedded(TestActivationPackageDAO.java:98) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) at org.junit.runners.ParentRunner.run(ParentRunner.java:363) at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191) at org.junit.runner.JUnitCore.run(JUnitCore.java:137) at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) Caused by: java.lang.NullPointerException at org.apache.cassandra.config.DatabaseDescriptor.getDiskFailurePolicy(DatabaseDescriptor.java:1881) at org.apache.cassandra.utils.JVMStabilityInspector.inspectThrowable(JVMStabilityInspector.java:82) at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:79) ... 22 more

Version Details -->
Spring MVC 4
Java 11 .
Gradle 5
Using Spring data cassandra.
Datastax Core and mapper APIs

**Comment by wilkinsona** [comment]
https://issues.apache.org/jira/browse/CASSANDRA-9608 has been fixed in Cassandra 4.0. We may want to consider switching from Cassandra Unit to Testcontainers in the smoke test.

**Comment by dreis2211** [comment]
Given that the smoke test was removed in ca1710ee56d327e46a76f028f7bbc12dc974ee5e and we're on Cassandra 4+ I guess this can be closed.

**Comment by snicoll** [comment]
Indeed :)

**Comment by skyhirider** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above notes java 9 is not fully supported, is the documentation outdated?

**Comment by snicoll** [comment]
@skyhirider good catch, I've updated the wiki page as well. Thanks for reporting it!
