### ISSUE TITLE
Why logback console appender using 'UTF-8' as default charest?

### ISSUE THREAD

**Issue by otyyyywangwenbin** [spring-projects/spring-boot#10461]
I run spring boot as a tomcat war, and having problems that is log console output looks is not correct (Chinese character). 
My env is windows, and chcp=936(GBK).
I found spring boot using 'UTF-8' as logback console appender charest,  but i donot kown that's why? why donnot use JVM file.encoding as default charest?  can anyone explain it? 
thanks!

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
