### ISSUE TITLE
Ensure that configuration property binding is thread-safe and provide an API for changing the property sources from which it binds

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#10460]
The CPBPP can be called by Spring after the application has started (e.g. for `@ConfigurationProperties` beans that are scoped proxies). In that case the cached values of the property sources and rebinder that it created on startup can be stale. It would be great if it "just worked", but if that isn't easy, a public API to reset those things would make it possible to fix the `@RefreshScope` in Spring Cloud. Currently (since 1.0) we have a hack that sets fields in CPBPP using reflection.

**Comment by wilkinsona** [comment]
It's difficult to propose a solution without knowing more about the use case. Can you please describe in detail what changes are being made that lead to the property sources and rebinder being stale? We'd also need to know precisely how those changes are being made. For example are they happening on the same thread that honours`@RefreshScope` or are multiple threads potentially involved here?

**Comment by spencergibb** [comment]
This is the change (ie the "hack") https://github.com/spring-cloud/spring-cloud-commons/commit/9639787b03f36debf4a665d040e8158cb86500b8

**Comment by dsyer** [comment]
All we need is a public `reset()` to prevent us from having to hack the internal state. I don't think it's relevant how the changes are being made, and we don't really control that anyway (any user can open up the `Environment` at any time and add new `PropertySources`).

**Comment by wilkinsona** [comment]
>  I don't think it's relevant how the changes are being made

It's completely relevant. Without considering how the change can be made and how that change is consumed, there's no guarantee that it will be thread-safe. Your current hack illustrates the problem perfectly:

- If the post-processor tries to perform configuration property binding on one thread while the hack is running on another there's a window where a `NullPointerException` will occur
- If the reset is performed on one thread and the binder is recreated on another, there's no guarantee that the changes performed by the reset will be visible as there's no locking and none of the fields involved are volatile

What you're really asking for here is for configuration property binding to be made completely thread-safe and to support thread-safe mutation of its state. It works now for Boot itself because binding is performed exclusively on the main thread during application context refresh and the binder is created once and it's then reused.

**Comment by dsyer** [comment]
We never had anyone complain about race conditions, so it seems likely that they are a corner case. But, of course if it turns out to be important, then we'd be more than happy to see an implementation which takes it into account somehow.

**Comment by wilkinsona** [comment]
You may be happy dismissing thread-safety in Spring Cloud as a corner case that can be ignored until people complain, but I am not happy doing so in Boot. IMO, we can only consider implementing this if we're certain that it's thread-safe and won't lead to obscure and hard-to-track-down bugs. I haven't looked much below the surface, but my gut feel is that this could be a surprisingly large piece of work, and may not make the cut for 2.0.

**Comment by dsyer** [comment]
FWIW I've tried pretty hard to break this with concurrent changes in tests, but (aside from finding an unrelated bug in RefreshScope) I haven't been able to see a race. Possibly that was luck, because I admit that there is the potential for problems as long as CPBPP is not thread safe. Visibility issues often only surface under heavy load, right? So maybe I didn't hit it hard enough yet. The window for the NPE is very narrow (the private method `getBinder()` would have to see it not null in line 1 and then return null in line 2).

I also realized, incidentally, that there are already public method on CPBPP that do what we need (`destroy()` and `setPropertySourecs()`) so I replaced the hack with calls to those methods.

**Comment by wilkinsona** [comment]
> I also realized, incidentally, that there are already public method on CPBPP that do what we need (destroy() and setPropertySourecs()) so I replaced the hack with calls to those methods.

That's really still a hack as those methods, particularly `destroy()` are being called outside their intended lifecycle. We've had problems with that before so it'd be nice not to make the same mistake twice.

**Comment by wilkinsona** [comment]
All it takes to break this is to have one thread calling `postProcessBeforeInitialization` while another's calling `destroy`. This code added to `ConfigurationPropertiesBindingPostProcessorTests` will NPEs almost immediately:

```java
	@Test
	public void threadSafety() throws InterruptedException {
		this.context = new AnnotationConfigApplicationContext(TestConfiguration.class);
		ConfigurationPropertiesBindingPostProcessor cpbpp = this.context
				.getBean(ConfigurationPropertiesBindingPostProcessor.class);
		for (int i = 0; i < 1; i++) {
			new Thread(() -> {
				while (true) {
					cpbpp.postProcessBeforeInitialization(new TestConfiguration(),
							"whatever");
				}
			}).start();
		}
		for (int i = 0; i < 1; i++) {
			new Thread(() -> {
				while (true) {
					cpbpp.destroy();
				}
			}).start();
		}
		Thread.sleep(Long.MAX_VALUE);
	}
```

**Comment by dsyer** [comment]
That's good then, right, because it means there is an easy fix potentially (just 2 private methods to synchronize, `destroy()` and `getBinder()`). However, I'm not sure, but it seems like there is another code path in Spring Cloud because whatever I do I can't get the thing to NPE, as long as the calls to the cpbpp are wrapped in the `ApplicationContext` lifecycle, and the `RefreshScope`. So maybe it's already safe, and only need to analyse it a bit more to figure out why. Here's the test I wrote, which is identical structurally to yours, but doesn't call the cpbpp directly:

```java
		// overload the thread pool and try to force Spring to create too many instances
		int n = 800;
		TestPropertyValues.of("message=Foo").applyTo(environment);
		this.scope.refreshAll();
		final CountDownLatch latch = new CountDownLatch(n);
		final List<String> results = new ArrayList<>();
		this.executor.submit(new Runnable() {
			@Override
			public void run() {
				for (int i = 0; i < n; i++) {
					logger.debug("Background started.");
					try {
						results.add(RefreshScopeConfigurationScaleLoopTests.this.service
								.getMessage());
					}
					finally {
						latch.countDown();
						logger.debug("Background done.");
					}
				}
			}
		});
		this.executor.submit(new Runnable() {
			@Override
			public void run() {
				for (int i = 0; i < n; i++) {
					logger.debug("Refreshing.");
					RefreshScopeConfigurationScaleLoopTests.this.scope.refreshAll();
				}
			}
		});
		assertTrue(latch.await(15000, TimeUnit.MILLISECONDS));
		assertEquals("Foo", this.service.getMessage());
		for (String result : results) {
			assertEquals("Foo", result);
		}
```

**Comment by wilkinsona** [comment]
> So maybe it's already safe, and we only need to analyse it a bit more to figure out why

I don't think that will be sufficient. If we go down this path we'll want to be able to state that CPBPP is thread-safe, irrespective of what a client does I don't want us to get into a situation where we claim that something's thread-safe but only if you use it in a particular way, or if you rely on the locking that's performed by something else.

I think we should actually take a step back here and try to avoid abusing CPBPP and its intended lifecycle by looking more closely at how refresh scope is implemented. Right now, CPBPP makes assumption about how and when it's used that seem to hold true for everything other than refresh scope. Rather than allowing refresh scope to invalidate all those assumptions and requiring changes to CPBPP, I'd rather explore implementing refresh scope differently.

My understanding at the moment is that when a refresh is triggered it's actually the Framework that's driving CPBPP. Before it's driven, you make some calls to it to try to get it to use modified or additional property sources for binding. It feels like it would be simpler to, instead, somehow no-op CPBPP during refresh and then allow Spring Cloud to create its own binder and with whatever property sources it wants to bind the refreshed bean. This was certainly the intent when the `ConfigurationPropertiesBinder` API was introduced.

**Comment by dsyer** [comment]
> It feels like it would be simpler to, instead, somehow no-op CPBPP during refresh and then allow Spring Cloud to create its own binder and with whatever property sources it wants to bind the refreshed bean.

Perfect. We'd still need a way to do that via Spring Boot, wouldn't we?

**Comment by wilkinsona** [comment]
I think we either need some way in Boot of marking a bean as one that should be ignored by CPBPP, or we need a way in Framework for a scope to indicate that a BPP shouldn't be used when creating a bean in that scope.

**Comment by dsyer** [comment]
There's a danger of subverting the bean lifecycle (much of the value of which is its more or less constant behaviour). I.e. I think I prefer on balance if all scoped proxies go through the same set of callbacks. CPBPP ignoring a bean that is marked as `@ConfigurationProperties` sounds like a confusing thing to have to describe and justify (and hence maintain).

I suppose if push comes to shove we can just accept the fact that the CPBPP is going to run on refresh-scoped beans, and the result isn't going to be an accurate picture of what's in the `Environment`. Then we can maybe simply rebind it to the right properties. I haven't tried this, but it was one of the approaches that @snicoll originally suggested (I rejected it because it binds the same bean twice which seems dumb).

**Comment by wilkinsona** [comment]
How about `@RefreshableConfigurationProperties` that's specific to Spring Cloud? You can use `ConfigurationPropertiesBinder` to do the binding (so you get the same binding behaviour as `@ConfigurationProperties`) but it'll be ignored by CPBPP leaving you complete control over what gets bound and when.

**Comment by spencergibb** [comment]
That's an interesting idea. Glancing at `ConfigurationPropertiesBinder` the `bind()` methods have `ConfigurationProperties.class` hardcoded there. Would there need to be a change to allow a custom annotation?

**Comment by dsyer** [comment]
"So why does Spring Cloud have its own `@ConfigurationProperties` annotation?" "Because there's this issue in Spring Boot about thread safety." I'm not sure I want to have that conversation. I'd rather work around it (e.g. by binding the beans again). It should be opaque to users.

**Comment by wilkinsona** [comment]
That's certainly one way to answer that question. I'd prefer to answer it something like this:

Spring Cloud has `@RefreshableConfigurationProperties` to clearly denote which configuration properties can be rebound by a refresh. It indicates that those configuration properties are consumed in such a way that rebinding will have an effect.

If we "fixed" this in Spring Boot, how would you answer "Why can some `@ConfigurationPropeties` be refreshed and others cannot"?

**Comment by wilkinsona** [comment]
> Would there need to be a change to allow a custom annotation?

There would. Perhaps a `Function<Object, BindingSettings>` that takes the target of the binding and produces `BindingSettings` that encapsulate the `prefix`, `ignoreInvalidFields` and `ignoreUnknownProperties` configuration.

**Comment by wilkinsona** [comment]
We discussed this in today's team meeting. Rather than trying to officially support abuse of the configuration properties binding post-processor, our current preferred course is described in the two issues referenced above (#10598 and #10599). This will allow Spring Cloud to take complete control over the binding of refreshable configuration properties, while also getting the same binding semantics as standard configuration properties. Separating the two will provide a clear indication to users which configuration properties beans can be refreshed and which cannot. Assuming we can reach agreement on our preferred course I think it makes sense to close this one.

**Comment by wilkinsona** [comment]
Following a discussion with @snicoll, @spencergibb, and @dsyer we have an alternative plan now. Closing.
