### ISSUE TITLE
How to pass basic authentication headers to legacy servlet 

### ISSUE THREAD

**Issue by sudheerkosuru** [spring-projects/spring-boot#10499]
Hi I have been trying out to migrate a existing legacy application to spring boot application.

I have a legacy servlets which are registering using ServletRegistraionBean,My internal servlets are using basic authentication to validate resturl.How can i add basic auth while registering the servlet.below is my code snippet for registering servlet.
@Bean
public ServletRegistrationBean discoveryServletRegistration(DiscoveryServlet discoveryServlet) {
    ServletRegistrationBean registration = new ServletRegistrationBean(
    		discoveryServlet);
    registration.addUrlMappings("/discoveryapi/*", "/pooldiscoveryapi/*");
     return registration;
}

Thanks
Sudheer

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
