### ISSUE TITLE
Which way is correct for setting CORS in new Spring?

### ISSUE THREAD

**Issue by LionZXY** [spring-projects/spring-boot#10503]
Hello.

I did not find the answer to my question on the Internet. What is the correct way to set up a global CORS for non-web application (json api only)? 
I found org.springframework.web.cors.CorsConfiguration but i can't find where it use. Please, help me. I do not know what to do.
My spring version: 2.0.0.M4

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
