### ISSUE TITLE
Allow WebTestClientContextCustomizerFactory to back off

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10556]
Whilst working on #10555 I was confused as to why my custom timeout wasn't applied to the `WebTestClient`. After some digging it appears that `WebTestClientContextCustomizerFactory` is always adding one, which causes the `WebTestClientAutoConfiguration` to always back off. Given that there's no easy way to customize the client created by `WebTestClientContextCustomizerFactory` I wonder if we should remove it?

**Comment by philwebb** [comment]
Perhaps we should also change `@SpringBootTest`/`SpringBootTestContextCustomizer` in 2.0 and register it only via auto-configuration?

**Comment by snicoll** [comment]
@philwebb this is an exact mirror of `SpringBootTestContextCustomizer` so if we drop this we should drop it for `TestRestTemplate` as well. Perhaps `TestRestTemplate` is not affected by the issue you're describing and it's a bug in `WebTestClientContextCustomizerFactory`?

**Comment by snicoll** [comment]
A bit of a brain dump sorry.

`@SpringBootTest` creates a `TestRestTemplate` and `@AutoConfigureWebClient` creates a `RestTemplate`. `TestRestTemplate` exists to avoid clashing with an existing `RestTemplate` in the context (so you have the guarantee you can inject it and it won't shadow any user-defined `RestTemplate`).

`@SpringBootTest` in a reactive web app creates a `WebTestClient` and `@AutoConfigureWebTestClient` creates a `WebTestClient`. The constraints here are different as Spring Boot does not auto-configure a `WebClient` at the moment (but that's something that could very well be added in the future). Because the type matches, you can't use `@AutoConfigureWebTestClient` on `@SpringBootTest` as the auto-configuration will immediately back-off (`@SpringBoot` has already created such a bean).

Looking a bit more closely to how this annotation is meant to be used, `@AutoConfigureWebTestClient` should create a `WebClient` (that's the thing we want to create for `@RestCientTest` once we have support for that in reactive).

But, that's not the end of it.

* If we do this, we should probably merge `@AutoConfigureWebTestClient` and `@AutoConfigureWebClient`. This would help, probably, to consolidate `@RestClientTest` once such support is added for reactive
* `TestRestTemplate` and `WebTestClient` are very different. The former has an identical API while the latter is quite different. Taking Phil's sample, if we change this and we inject a `WebClient` in `SampleSecureWebFluxApplicationTests`, the test will definitely no read as nicely. 

Perhaps the problem is the related feature, actually. If you put a timeout on the annotation in the servlet world, you have zero guarantee that it's going to be taken into account (Actually it won't by default, `registerRestTemplate` is `false` by default). That difference of behaviour alone is the kicked IMO. If we need a different timeout, we should either tune a property that does that on the builder or create a `@TestConfiguration` that tunes the builder.

**Comment by snicoll** [comment]
@philwebb ping

**Comment by philwebb** [comment]
I've got a fix that changes both customizers so that only the bean if one isn't already configured. That should mean that existing code keeps working but we can still apply auto-configuration if we want to.

I'm not confident enough to close the issue yet as I still think there might be a few more things to consider. The `WebTestClient` created by the auto-configuration and the cusomizer are subtly different. The auto-configuration bind it to the context, where as the customizer creates a real connection. We might need extend the auto-configuration to also support read server binding.

**Comment by philwebb** [comment]
Since we've dropped the timer support I think this one can be closed. If we have issues with the auto-configuration we can deal with them later.
