### ISSUE TITLE
Allow ConfigurationPropertiesBinder to use binding settings from sources other than @ConfigurationProperties

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10599]
ConfigurationPropertiesBinder is currently tightly coupled to `@ConfigurationProperties`. It would potentially be useful for Spring Cloud to break that coupling with a strategy interface that takes a target object and returns the binding settings that should be used to being the configuration properties to the target. Those settings would be the prefix, and the ignoring of unknown or invalid fields

See #10460 and #10598.

**Comment by snicoll** [comment]
There is one problem with that approach. If you don't specify `@ConfigurationProperties` the metadata for the POJO will no longer be generated as the annotation processor uses the presence of that specific annotation to kick-in. 

We can think of many alternatives (including a configuration option for the AP) but none of them look very user friendly IMO.

**Comment by wilkinsona** [comment]
I agree that's not ideal, but I the metadata problem is heavily outweighed by separating refreshable configuration properties from normal configuration properties. The two have very different lifecycles and very different breadth of support so I think that separation is vital to improving the robustness and user-friendliness of the feature. A configuration option on the annotation processor to tell it what annotation(s) to look for feels like a small price to pay.

**Comment by snicoll** [comment]
> A configuration option on the annotation processor to tell it what annotation(s) to look for feels like a small price to pay.

I agree if that's the only option we have and perhaps there's another way. 

`@ConfigurationProperties` is front and center in three use cases:

1. Properties binding
2. Metadata generation
3. IDE support (IntelliJ IDEA recognizes such annotated class and provides additional support such as link to where a matching property is defined)

We are really discussing 1 here and the current proposal will immediately break 2 and 3. As our goal here is to change the way configuration properties are bound, how about offering a way for an ecosystem to override that for the entire application. 

Concretely:

1. Improve/expand the public API so that `ConfigurationPropertiesBindingPostProcessor` is either reusable or just calling something that can be reused
2. Have integration tests that validates `ConfigurationPropertiesBindingPostProcessor` can be fully replaced

Based on this, the Spring Cloud team can implement the solution they're after.

Thoughts?

**Comment by wilkinsona** [comment]
I like it. What you've proposed covers all three use cases for `@ConfigurationProperties` while allowing :

1. `ConfigurationPropertiesBindingPostProcessor` to retain its current focus
2. The Spring Cloud team to take complete control of binding when they need to do so

A downside is that, without a specific `@RefreshableConfigurationProperties` annotation, it will be unclear which `@ConfigurationProperties` beans can be refreshed and which cannot. However, that's the current situation and giving the Cloud team complete control over binding would allow them to make that distinction if they chose to do so.

**Comment by spencergibb** [comment]
From our conversation, @wilkinsona and @snicoll will look at updating `ConfigurationPropertiesBindingPostProcessor` to use a delegate object that users (such as spring cloud) can replace, rather than trying to replace the whole post-processor.

**Comment by wilkinsona** [comment]
Following a discussion with @snicoll, @spencergibb, and @dsyer we have an alternative plan now. Closing.
