### ISSUE TITLE
Unable to Load Mock Authenticated User to test End points

### ISSUE THREAD

**Issue by kavithaLK** [spring-projects/spring-boot#10605]
Unable to load MockUser in the in the SecurityContext to perform endpoint tests.
Question:

How does Spring Boot support mocking authenticated user in the SecurityContext?
I am trying to test my REST Endpoints, I tried using @WithMockUser , @WithMockCustomuser but both these annotations fail to work. Instead of 200 OK response i get 401 UnAuthenticated while trying to call secured endpoints.

I followed the steps described here.
https://docs.spring.io/spring-security/site/docs/4.0.1.RELEASE/reference/htmlsingle/#running-as-a-user-in-spring-mvc-test-with-annotations

My Configurations : 
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment= SpringBootTest.WebEnvironment.MOCK)
@ContextConfiguration(classes={SpringbootSecurityJwtApplication.class})
@AutoConfigureMockMvc
@TestExecutionListeners(
        mergeMode = MERGE_WITH_DEFAULTS
)
//////////////////////////////////
In my ControllerTests:

    @Autowired
    private WebApplicationContext context;
    @Autowired
    private MockMvc mockMvc;

    @Before
    public void setup() {
        this.mockMvc = MockMvcBuilders.webAppContextSetup(context)
                .alwaysDo(print())
                .apply(SecurityMockMvcConfigurers.springSecurity())
                .build();

    }
@Test
    @WithMockCurrentlyLoggedUser(userId = "dsfdsf", accountId = "dsf", name = "dsf df", permissions = {"Edit", "Read"})
    public void testCreatePreApproval() throws Exception
    {
        String appId = "MyApp1";
        mockMvc.perform(post("/market/preapprovals", appId)
                .accept(MediaType.ALL));//

    }
I appreciate a proper working example for testing endpoints.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
