### ISSUE TITLE
Tomcat fails to start with "factory already defined" error if two integration test harnesses start spring boot as part of the same maven multi-module build (JVM instance)

### ISSUE THREAD

**Issue by jamiecramb** [spring-projects/spring-boot#10617]
We use spring boot as a way to run an embedded tomcat / spring app inside of a JBehave integration test harness.

When in a multi-module maven reactor build we have noticed that if there are 2 modules with integration tests (and therefore 2 tomcat instances embedded within spring boot apps) that the second module will fail to run even though it runs fine if the module is built by itself.

I have tracked the problem down to the org.apache.catalina.webresources.TomcatURLStreamHandlerFactory calling URL.setURLStreamHandlerFactory(..) for each spring boot app startup; all after the first call in the same JVM will fail with a "factory already defined" Error being thrown.

The workaround has been to clone and override the org.apache.catalina.webresources.TomcatURLStreamHandlerFactory private constructor so that it wraps the call to URL.setURLStreamHandlerFactory(..) in a try/catch which ignores the "factory already defined" Error.

I have created a sample multi-module maven build to demonstrate the issue: 
[spring-boot-tomcat-chain-issue.zip](https://github.com/spring-projects/spring-boot/files/1379528/spring-boot-tomcat-chain-issue.zip). Note that the README.txt explains how to apply the workaround which is off by default.

**Comment by wilkinsona** [comment]
I don't think this really has anything to do with Spring Boot.

`TomcatURLStreamHandlerFactory` uses a static to ensure that `setURLStreamHandlerFactory` is only called once. If `setURLStreamHandlerFactory` is being called multiple times, there must be multiple class loaders in the same JVM, each of which has loaded `TomcatURLStreamHandlerFactory`. That's something that is out of the control of Spring Boot and Tomcat.

I'm not familiar with JBehave, but I would recommend looking at its class loading to see if it can be configured so that it doesn't load the same classes multiple times with different class loaders.

**Comment by bakersemail** [comment]
Have the same problem reported here.

**Comment by snicoll** [comment]
@bakersemail I am not sure I got that. Saying you have the same problem on a closed issue is not a great way to get support. As @wilkinsona indicated in the comment above yours, there is not much we can do here. If you're looking for help, please ask on StackOverflow.
