### ISSUE TITLE
Field null with aop

### ISSUE THREAD

**Issue by xiviu123** [spring-projects/spring-boot#10614]
I want to log response of restcontroller with aop.
here is the aop class config:

@Component
@Aspect
public class LoggingHandler {

    Logger log = LoggerFactory.getLogger(this.getClass());

    
    @Pointcut("within(@org.springframework.stereotype.Controller *)")
    public void controller() {
    }
    

    @Pointcut("execution(* *.*(..))")
    protected void allMethod() {
    }

    @Before("controller() && allMethod() && args(..,request)")
    public void logBefore(JoinPoint joinPoint, HttpServletRequest request) {

        log.debug("Entering in Method :  " + joinPoint.getSignature().getName());
        log.debug("Class Name :  " + joinPoint.getSignature().getDeclaringTypeName());
        log.debug("Arguments :  " + Arrays.toString(joinPoint.getArgs()));
        log.debug("Target class : " + joinPoint.getTarget().getClass().getName());

    }

    @AfterReturning(pointcut = "controller() && allMethod()", returning = "result")
    public void logAfter(JoinPoint joinPoint, Object result) {
        String returnValue = this.getValue(result);
        log.debug("Method Return value : " + returnValue);
    }
}

and the controller:

@Controller
@ResponseBody
@RequestMapping("/api")
public class ApiController {
    
    @Autowired
    AccountService accountService;
    
    @RequestMapping(value = "/{version}/me", method = {RequestMethod.GET, RequestMethod.POST})
    private Account me(@PathVariable final String version, Principal p) {
        
        return accountService.findByUsername(p.getName());
    }
}

When my run above code with embed tomcat server field 'accountService' null, so NullPointException appear .
Please help me, thank you.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
