### ISSUE TITLE
HTTP to HTTPS URL Redirection using Spring Boot and Tomcat

### ISSUE THREAD

**Issue by parmarkaushik15** [spring-projects/spring-boot#10639]
Hi All,

We have an issue regarding http to https force redirection without port changing using Spring Boot and Tomcat. So, please help us to resolve the issue.
Please find the below detail for detail case:

Used Environment : Spring Boot, Tomcat
Server Environment : AWS 

We have used the ELB on AWS server and applied SSL certificate on Load Balancer.

We are building a war file using maven and deploy on AWS server. Whenever we have not applied SSL certificate on LB, it working perfectly because the URL is like : http://sitename.com
After applying SSL certificate on LB, the server can't handle https://sitename.com.

How can i do with AWS. I want to force redirection without port changing.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
