### ISSUE TITLE
Is it possible to make spring boot app executable without JRE installed with Java 9?

### ISSUE THREAD

**Issue by smartwjw** [spring-projects/spring-boot#10644]
Spring boot make it possible for running  Java web applications without containers( tomcat, jetty) preinstalled.

As the release of Java 9, which introduced a modular system, is it possible to package a minimized JRE into a jar package, so that it can run in any platform without JRE preinstalled?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by smartwjw** [comment]
@wilkinsona IMHO, it's not only a question, but a enhancement suggest,  just like #519 .

After spring boot 1.3, we can package a spring boot application to a runnable java file and it also a `sysv init script`, so I can use `service xxx start` or `service xxx stop` to start or stop my application.

But, it still need JRE preinstall in the OS, what I want is, the packaged is **SELF CONTAINED** with JRE(Just like static linked golang executable binary).

**Comment by wilkinsona** [comment]
What you're asking for is out of the scope of Spring Boot. Unlike Go, there's no support in Java itself for building a cross-platform standalone binary. There are some tools that will create a binary with an embedded JRE. Google and existing Stack Overflow questions will provide you with some pointers.
