### ISSUE TITLE
Does static resource path not support shortcuts?

### ISSUE THREAD

**Issue by jay763190097** [spring-projects/spring-boot#10640]
I  would like to use shortcuts to introduce static resources, but no effect, the path can not access.
I was on the linux system test

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
