### ISSUE TITLE
RabbitHealthIndicator shows ok on updating the user credentials.

### ISSUE THREAD

**Issue by ShanthkumarKhandre** [spring-projects/spring-boot#10660]
RabbitHealthIndicator shows healthStatus as OK on updating the user credentials in RabbitMQ Server.

Question

Why RabbitHealthIndicator is showing healthStatus as OK even when credentials are not valid ?

Bug report

I am using the Spring Boot 1.5.2.RELEASE version.

1.  Started the spring boot application and provided the valid RabbitMQ Credentials

2. As expected, RabbitHealthIndicator showing healthStatus as OK

3. Changed the user credentials by logging into RabbitMQ Server

4. Expecting the RabbitHealthIndicator to show healthStatus as FAILURE but showing as OK

**Comment by snicoll** [comment]
I can only assume that the connection pool still has open sessions with the server and didn't reconnect to validate the credentials. In any case, it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
