### ISSUE TITLE
Override Method in RestController with same request-mapping-path

### ISSUE THREAD

**Issue by marcelolucio1982** [spring-projects/spring-boot#10662]
Good nigth,

I am having the same problem described in the link below with version 1.5.7.RELEASE of spring boot that uses version 2.6.7.RELEASE of spring-data-rest-core. 

In summary, i'm can not override the POST method. When I override, the GET method returns 405

`
@RepositoryRestController
@RequestMapping(value="/estabelecimentos",consumes=MediaType.APPLICATION_JSON_VALUE, 
produces=MediaType.APPLICATION_JSON_VALUE)
public class EstabelecimentoRecurso {
	
	@Autowired
	EntityLinks entityLinks;
	
	@Autowired
	EstabelecimentoServico estabelecimentoServico;

	
	@RequestMapping(method = RequestMethod.POST)
	public @ResponseBody ResponseEntity<Resource<Estabelecimento>> salvar(
			@RequestBody Estabelecimento estabelecimentoEnviado) {

		Estabelecimento estabelecimento = estabelecimentoServico.salvar(estabelecimentoEnviado);
		
		Resource<Estabelecimento> resource = criarLinks(estabelecimento);

		return ResponseEntity.ok(resource);
	}
`

https://stackoverflow.com/questions/28455208/spring-data-rest-override-method-in-restcontroller-with-same-request-mapping-pa

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
