### ISSUE TITLE
ConfigurationPropertiesBindingPostProcessor should always use an up-to-date view of the Environment for binding

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10685]
**Note:** Our understand of the problem has changed considerably since the original description below was written. Please read the whole issue to learn how things have evolved.

This issue supersedes #10460 and #10599.

Primarily in support of Spring Cloud's refreshable configuration feature, we need to rework `ConfigurationPropertiesBindingPostProcessor` so that it uses a pluggable delegate for almost all of its logic.

The current plan is for the post-processor to check for the presence of the `@ConfigurationProperties` annotation and, if it's found, call the delegate. This delegate must be configurable. To that end, the post-processor will look in the context for a well-known bean name and use delegate to that bean if present. If no such bean is present, the post-processor will instantiate and use its default delegate.

The default delegate will be a public API. This will allow Spring Cloud's own delegate to compose its custom functionality on top of the default behaviour by delegating to the default delegate when appropriate.

We need to figure out the relationship between the delegate proposed above and the `ConfigurationPropertiesBinder`. It may be that they become the same thing, or there may be another layer in between the post-processor and the binder.

/cc @dsyer @spencergibb

**Comment by snicoll** [comment]
Most of the logic is now shared in `ConfigurationPropertiesBinderBuilder` except the property sources to use and the `ConversionService` and `Validator` that can be specified via the setters we're about to deprecate.

So, if the post processor could retrieve a `ConfigurationPropertiesBinderBuilder`, it could configure it (passing the property sources and whatever the post processor is configured for) and then the builder on `build()` is free to:

1. Override some of those parameters
2. Use the internal state of the builder to create the default `ConfigurationPropertiesBinder`: it is [quite straighforward at the moment](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesBinderBuilder.java#L136), the only constraint is to make the `determine*` methods protected and give an accessor to the configured property sources.
3. Return a completely different implementaion, wrapping or not the default one

As for the binder itself, we are ["cheating" a bit with a protected method call](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesBinder.java#L93) to avoid performing the look-up of the `@ConfigurationProperties` twice. Looking at the code, perhaps a `ConfigurationPropertiesOptions` POJO could mirror the annotation and we could make that one public. This also allows to bind any arbitrary object without a reference to the annotation.

Exposing the builder as a bean means that we should probably go the same route a `RestTemplateBuilder` (returning a new immutable instance at each call).

I don't know if that's enough to let Spring Cloud replaces the property sources at the appropriate time but the binder would be theirs so I guess that should work.

WDYT @wilkinsona?

**Comment by snicoll** [comment]
@wilkinsona @dsyer @spencergibb I have a proposal available in my fork (see https://github.com/snicoll/spring-boot/commit/eb96d47c226d726773b7731b7c6f4bdfc7e51490). You can see a concrete usage [in the integration test](https://github.com/snicoll/spring-boot/blob/eb96d47c226d726773b7731b7c6f4bdfc7e51490/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/context/properties/ConfigurationPropertiesBindingPostProcessorIntegrationTests.java#L119-L146).

I am going to bug Andy for an extra pass and I'll merge that early next week. It would be nice if you could have a quick look in case I've missed something fundamental.

Thanks!

**Comment by dsyer** [comment]
I tried out the new code from Stephane's fork and got something working with Spring Cloud Context. There was an issue with internal state in the CBPP being reset on context refresh, and I think I convinced Stephane that was unnecessary (because it would break vanilla Spring Boot apps with `@ConfigurationProperties` that were, for example, in `@RequestScope`). With things as they are now, it turns out the only thing I need to change is that one line in CBPP where it creates the binder context from the wrong property sources. So rather than wrap the existing binder, I decided to extend `DefaultConfigurationPropertiesBinder` and change the property sources, which has the desired effect. I’m kind of unconvinced that the defaults are what people really need or want actually, so I guess we need a scenario where the default behaves differently to my override to decide (I can't think of one).

**Comment by wilkinsona** [comment]
@dsyer That doesn't really sound like it's in the spirit of what's intended in this issue. Can you explain why you consider the property sources to be wrong and why changing them only on the binder is the right thing to do? I would expect an `EnvironmentPostProcessor` to be used to change the property sources so that the default binder, the env endpoint, anyone using the environment directly etc, will benefit.

**Comment by dsyer** [comment]
We must be at cross purposes because an `EnvironmentPostProcessor` only runs once on startup, and we are explicitly trying to support changes to the `Environment` after that. Naturally the `Environment` is the shared state that all interested parties should try to agree on, and the fact that it is mutable is either a bone of contention, or something really useful to be taken advantage of. I think arguably CPBPP breaks that (implied) contract already because it explicitly chooses to use a different set of property sources. IIRC it was written that way (by me) from Day 1, so I'm tempted to think it's more of a historical accident, and not necessarily all that well thought through to start with.

**Comment by wilkinsona** [comment]
I wonder if we need to take a bigger step back. My current understanding is that Spring Cloud needs to specifically manipulate the binder's view of the property sources rather than manipulating the environment's property sources but I don't understand the reasons for it needing to do so.

The `Iterable<ConfigurationPropertySource>` that's created from `MutablePropertySources` sources will automatically track updates to the mutable sources. I believe that means that if Spring Cloud can stick to just manipulating the environment's mutable property sources, this will work without any other changes. That's certainly what's promised by `ConfigurationPropertySources.from(MutablePropertySources)` and, AFAIK, the implementation is true to that promise. It certainly works when the servlet environment's stub property sources are replaced with the actual instances populated using the servlet context and servlet config.

**Comment by dsyer** [comment]
> Spring Cloud needs to specifically manipulate the binder's view of the property sources rather than manipulating the environment's property sources

Not really. I would far rather just manipulate the environment and have everything flow from there. We only needed a customization to work around the fact that CPBPP doesn't use the environment property sources by default. At least that was my analysis (I might still be wrong).

Maybe we just agreed we should remove [that line in the CPBPP](https://github.com/spring-projects/spring-boot/blob/35c6b83fce86a83e4b2b9ec9fb5cbe0646eb23a5/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/ConfigurationPropertiesBindingPostProcessor.java#L155), since it actually prevents what you just described from happening? I think if we did we'd all agree that the property sources used to bind to configuration properties were well aligned with what we and our users assumed they would be.

**Comment by wilkinsona** [comment]
I don't think it does prevent it as one of the property sources from the `PropertySourcesPlaceholderConfigurer` is the `Environment`.

**Comment by dsyer** [comment]
I think something changed in Spring 5.0. This test passes with Boot 1.5.x and fails with 2.0 snapshots:

```java
@RunWith(SpringRunner.class)
@SpringBootTest
public class LazyApplicationTests {

	@Autowired
	private ApplicationContext context;

	@Test
	public void contextLoads() {
		assertThat(context.getBean(ValidProperties.class).getName()).isEqualTo("foo");
		((ConfigurableEnvironment) context.getEnvironment()).getPropertySources()
				.addFirst(new MapPropertySource("custom",
						Collections.singletonMap("valid.name", "bar")));
		assertThat(context.getBean(ValidProperties.class).getName()).isEqualTo("bar");
	}

}

@SpringBootApplication
class LazyApplication {
	
	@Bean
	@Scope("prototype")
	public ValidProperties valid() {
		return new ValidProperties();
	}
	
	@Bean
	public CommandLineRunner runner(ValidProperties valid) {
		return args -> System.err.println(valid.getName());
	}

	public static void main(String[] args) {
		SpringApplication.run(LazyApplication.class, args);
	}
}

@ConfigurationProperties("valid")
class ValidProperties {
	private String name;
	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
```

**Comment by wilkinsona** [comment]
That’s an interesting discovery. Thanks. It could be the binder too. I’ll dig a bit and see if I can figure out where the change in behaviour has a been made.

**Comment by dsyer** [comment]
There's some tension between the mutable environment and the fact that `@Value` processing is done in a `BeanFactoryPostProcessor`. So Spring modifies the `BeanDefinitions` once on startup, and never knows about changes in the `Environment` after that. Hence it takes a copy of the property sources in the `PropertySourcesPlaceholderConfigurer` and makes it immutable, so anyone who needs to know what the `@Values` are can find out through a public API. But in Spring Boot we care more about `@ConfigurationProperties` and those used to respond to changes in the `Environment` and now don't. Using some property sources from `PropertySourcesPlaceholderConfigurer` is a good idea because it is the only place that `@PropertySource` values show up (so that explains why I did it that way in the beginning), but it has it's downside, which we are only seeing now that Spring is being more precise about what is bound to `@Values`.

**Comment by dsyer** [comment]
Although, to be honest, I can't see the difference in Spring 5.0. Must be something else going on.

**Comment by wilkinsona** [comment]
This works:

```java
		assertThat(this.context.getBean(ValidProperties.class).getName())
				.isEqualTo("foo");
		((MutablePropertySources)this.context.getBean(PropertySourcesPlaceholderConfigurer.class).getAppliedPropertySources())
				.addFirst(new MapPropertySource("custom",
						Collections.singletonMap("valid.name", "bar")));
		assertThat(this.context.getBean(ValidProperties.class).getName())
				.isEqualTo("bar");
```

It works because `org.springframework.boot.context.properties.source.SpringConfigurationPropertySources.checkForChanges()` notices the new property source when it's added to the top-level property sources. It does not notice the new property source when it's added to the `Environment` that `PropertySourcesPlaceholderConfigurer` has wrapped into a `PropertySource`.

**Comment by dsyer** [comment]
I see. How about if `TestPropertyValues` did that as well? That would fix a lot of our tests. And then we can try and decide whether to fix `SpringConfigurationPropertySources` to be aware of the nesting, or harmonize Spring Cloud to use the "applied" property sources for mutating the environment (possibly via a new API in Boot?).

**Comment by wilkinsona** [comment]
Changing `TestPropertyValues` wouldn't solve the underlying problem so I don't want to do that. We agreed above that we'd like to be able to manipulate the environment and have everything flow from there so let's try to make that work.

This issue has really become a variant of #9160. The problem is that the fix for #9160 didn't consider the case where there was a `PropertySourcesPlaceholderConfigurer` in the context. It's a shame that wasn't pursued at the time and the reflective hack was added instead. I think a better fix for #9160 is possible although there may be some performance implications. Here's [a possible fix](https://github.com/wilkinsona/spring-boot/tree/rebindable-configuration-properties) that seems to function as required. I haven't checked how it performs.

**Comment by wilkinsona** [comment]
If my possible fix works, I believe there's no need for the pluggable delegate proposed here or the API that was added in https://github.com/spring-projects/spring-boot/commit/67fc5ca4335d5692707a25d22fc0045d9237bccf.

**Comment by dsyer** [comment]
Looks promising. The pluggable delegate probably isn't needed at least by the current features we support in Spring Cloud but I think we still need `ConfigurationPropertiesBinder` from 67fc5ca because we don't want to re-use the CPBPP out of its normal lifecycle.

**Comment by wilkinsona** [comment]
> we don't want to re-use the CPBPP out of its normal lifecycle

What are the remaining uses cases for needing to do that? My understanding was that you used it for refresh scope which, with the change proposed above, will just work without you needing to explicitly perform any binding.

**Comment by dsyer** [comment]
> My understanding was that you used it for refresh scope

We use it in a `ConfigurationPropertiesRebinder` which operates independent of `RefreshScope`. `RefreshScope` never needed the `ConfigurationPropertiesBinder` because it operates just as part of the normal bean instantiation lifecycle. There are really 2 use cases, one of which was solved by `ConfigurationPropertiesBinder` and one that can be solved by fixing the bean lifecycle (and making the test above pass).

**Comment by dsyer** [comment]
I tried that latest change from @wilkinsona and it works great in Spring Cloud. Maybe we should just do that (given that it fixes the failing test above as well).

**Comment by wilkinsona** [comment]
I'd like to do it. I just need to check it doesn't tank startup times

**Comment by wilkinsona** [comment]
Good news, the proposed changes don't seem to have any discernible effect on startup time. Across 10 starts of the WebFlux sample the average time with the proposed changes was 3.052 seconds and without was 3.105 seconds. 0.053 seconds is well within the error bars.

**Comment by wilkinsona** [comment]
Fixed by https://github.com/spring-projects/spring-boot/commit/85b1511085bc395ce4ffa0d20287372f9e3100c3.
