### ISSUE TITLE
Failing to load class in jar (SpringBoot+Hibernate)

### ISSUE THREAD

**Issue by nfedyk** [spring-projects/spring-boot#10690]
Hi, 

I'm working on the upgrade of an old application and I upgraded my spring boot from version 1.2.x to 1.5.8.  I use JPA and JAXB in my project. It seems like there is issue loading `package-info` annotated classed inside compiled jar. This doesn't happen while debugging/running inside IDE or using `bootRun` command.

I've created a sample project that reproduces mentioned issue - https://github.com/nfedyk/spring-boot-jpa-issue-01

Versions:
* java - 1.8.0_51
* spring-boot - 1.5.8
* hibernate - 5.0.12 

Please advise.

**Comment by bmudda** [comment]
+1

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by wilkinsona** [comment]
You may also want to read the [relevant section of the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-extract-specific-libraries-when-an-executable-jar-runs).

**Comment by bitsofinfo** [comment]
@wilkinsona We've reviewed that section (previously and yet again...) of the docs does not seem to help

Did you run the sample project that @nfedyk linked above? 

Is this not a bug? 

Is having JAXB classes within the source-base no longer supported in a spring-boot project? 

There are already numerous dead-end questions on stack overflow pertaining to this exact issue that they have all been asked roughly within the past 4-6 months... so something in spring has changed whereby projects that contain JAXB classes within their source tree are no longer runnable in a executable jar generated by spring boot.

One suggestion is to extract all JAXB code into separate jars then re-include them? This is not practical and I don't see anything in the spring change logs about this requirement since 1.2.5 forward.

When was this change made regarding JAXB classes w/ package-info supported in spring-boot?

https://stackoverflow.com/questions/44441129/java-lang-noclassdeffounderror-with-package-info

https://stackoverflow.com/questions/45545445/spring-boot-classnotdef-error-with-jaxb-package-info-java

https://stackoverflow.com/questions/43782191/spring-boot-runnable-jar-cant-load-package-info-class/

**Comment by wilkinsona** [comment]
The layout of executable jars changed in 1.4. This is [documented in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#executable-jar-layout). The change in layout causes problem with libraries that make faulty assumptions about the structure of a jar file and the class path. The ideal solution to the problem is for the library to be fixed so that it doesn't make those assumptions. If that's not possible, then Spring Boot provides an escape hatch in the form of packaging the affected classes in a separate jar within `BOOT-INF/lib` and configuring that jar to be automatically unpacked from the fat jar during startup. That is the documentation to which I linked above.
