### ISSUE TITLE
It's not possible to override exit code for web applications

### ISSUE THREAD

**Issue by erard22** [spring-projects/spring-boot#10697]
Request for Enhancement

For command line applications it is possible to override the exit code by using the `ExitCodeGenerator` but for web applications starting a container this seems not feasible.

I'm asking for this enhancement because when running your services in docker it's easier to make use of dockers restart policies where containers with an exitcode != 0 are handled as failed ones.  Currently a spring boot application get's exit code 143 when it was stopped with `docker stop`.  If you are using the restart policy `on-failure` this container gets started by docker if the deamon or the host get's restarted. This can lead to side effects.

**Comment by wilkinsona** [comment]
This is out of Boot's control. `docker stop` sends `SIGTERM` to the root process in the container. Ultimately, this means that the JVM running your Spring Boot application receives the `SIGTERM`signal and shuts down. When the JVM exits due to a signal, its exit code is 128 plus the signal. `SIGTERM` is 15 so the exit code is 143. To my knowledge, there's no way for an application running on the JVM to change this exit code so you'll have to explore an alternative such as changing the restart policy so that an exit code of 143 is not considered to be a failure.

**Comment by aijanai** [comment]
A workaround (we ran into same issue with OpenShift complainig about it) would be to use a bash script in CMD line and use that script to run java AND catch TERM signals.

In the script you add something like
```
#!/bin/bash
cleanup() {
    killall java # this sends TERM to java
    exit 0 # this exits cleanly
}
trap cleanup TERM # this runs when TERM signal is sent by docker, you can replace with EXIT for any signal

mvn spring-boot:run # this runs when the script starts
```
