### ISSUE TITLE
Can I disable CSRF check for requests that is coming from a native mobile application?

### ISSUE THREAD

**Issue by bfwg** [spring-projects/spring-boot#10718]
Hello,

I'm writing a spring-boot JWT authentication for both my web application and mobile application. For web application authentication, it is simple, the server takes in a cookie with contains the JWT and use a filter to verify the token.

However, for the mobile app, I need to pass in the token in each request. It is all working fine until I make a POST request.  My server takes csrf token from cookie by default and there is no csrf token needed for the mobile app. Can I disable csrf protection if the header of the request contains something like: `Bearer xxxxxxx`?

Thanks in Advance

**Comment by bfwg** [comment]
I'm using the below code as a walk around. 
```
        http.csrf().requireCsrfProtectionMatcher(new RequestMatcher() {

            @Override
            public boolean matches(HttpServletRequest request) {
                // No CSRF due to JWT in header
                String authHeader = tokenHelper.getAuthHeaderFromHeader( request );
                if ( authHeader != null && authHeader.startsWith("Bearer ")) {
                    return false;
                }
                // CSRF for everything else that is not an API call or an allowedMethod
                return true;
            }
        });
```
Is this correct?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
