### ISSUE TITLE
Remove Http401AuthenticationEntryPoint

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#10715]
As far as I can tell it is not being used in the Spring Boot code base, so it might be good to remove `Http401AuthenticationEntryPoint`.

**Comment by workmanw** [comment]
Out of curiosity, what would the advice be for users of 1.x who were using this manually? Ex:

```java
public class MySecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {
  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http.exceptionHandling().authenticationEntryPoint(new Http401AuthenticationEntryPoint("Unauthorized"));
  }
}
```

Should we just create our own `Http401AuthenticationEntryPoint`?

**Comment by rwinch** [comment]
There is also the `BasicAuthenticationEntryPoint`

**Comment by mdvorak** [comment]
Note that with 401 header `WWW-Authenticate` is mandatory due to HTTP specification.
`Http401AuthenticationEntryPoint` was convenient to provide it. I had real trouble finding this issue. 

Please add it to CHANGELOG somewhere. A lot of people will depend on it manually.

I would actually welcome this utility class to be present in Spring Security, alongside with `Http403ForbiddenEntryPoint`.
