### ISSUE TITLE
Adding spring cloud dependency breaks logback configuration

### ISSUE THREAD

**Issue by sachinladsonos** [spring-projects/spring-boot#10722]
[demo-2.zip](https://github.com/spring-projects/spring-boot/files/1403208/demo-2.zip)
Spring-Boot Version 1.5.1

I have been trying to chase down problem related to application log not rotating on our AWS deployed instance. As part of trying to reproduce this on local, I noticed that our application has stopped creating log files on local. All efforts to tweak the configuration and debugging did not lead to anything obvious. 

So, I tried to start over by creating new demo application with Spring Initializer to reproduce but that created log file properly. Next I tried to add one dependency at a time and it seems like spring-cloud dependency is offending dependency. 

Please see attached project -
1) if you start the service, it creates log file in target/ with name test-service.log
2) if you uncomment "spring-cloud-starter-config" dependency in pom, you will see that no log file gets generated

It is weird though that on our AWS hosted services, log files are generated correctly but we do not see them getting rotated. I have not debugged through to find root cause, but it seems like this is unexpected outcome by adding cloud dependency and should be treated as bug.

EDIT: Upgrading spring cloud version to Dalston.SR4 seems to give expected result. But I am still confused as to why the behavior is different on local vs deployed env.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by snicoll** [comment]
@sachinladsonos in general if you've noticed that adding a module from another project causes the issue, it is better to start reporting the issue there. We can come back here if necessary.
