### ISSUE TITLE
TestRestTemplate + Jackson Kotlin module break ResponseEntity error handling

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#10761]
`TestRestTemplate` throws a `RestClientException` with a nested `HttpMessageNotReadableException` when used with Kotlin. [See the related test](https://github.com/sdeleuze/test-rest-template-issue/blob/f0019afcd597705c063ed591630fbb4b4ea83262/src/test/kotlin/com/example/testresttemplateissue/KotlinApplicationTests.kt#L40).

The same code using a injected `RestTemplateBuilder` works correctly. [See the related test](https://github.com/sdeleuze/test-rest-template-issue/blob/f0019afcd597705c063ed591630fbb4b4ea83262/src/test/kotlin/com/example/testresttemplateissue/KotlinApplicationTests.kt#L46).

[Both use cases works correctly in Java](https://github.com/sdeleuze/test-rest-template-issue/).

It seems `TestRestTemplate.NoOpResponseErrorHandler` and Jackson Kotlin module generates this strange behavior.

In order to fully understand the issue, I would be interested to know why such `NoOpResponseErrorHandler` is configured by default, because I was surprised by the difference of behavior between `TestRestTemplate` and `RestTemplate`.

**Comment by wilkinsona** [comment]
The difference is described (briefly) in the javadoc:

```
Convenient alternative of RestTemplate that is suitable for integration tests. They are fault tolerant, and optionally can carry Basic authentication headers. If Apache Http Client 4.3.2 or better is available (recommended) it will be used as the client, and by default configured to ignore cookies and redirects.
```

The fault tolerance (provided by `NoOpResponseErrorHandler`) makes it easier to test that error scenarios produce the expected 4xx or 5xx response without having to catch an exception.

**Comment by sdeleuze** [comment]
Ok thanks for the feedback.

**Comment by wilkinsona** [comment]
Thanks for the sample, @sdeleuze. I found this one quite interesting. The problem is that the Kotlin Jackson module cannot create a `Post` instance from the 500 response that has no content. That's because your `Post` type doesn't allow `title` to be `null`. The Java equivalent has no such restriction so it doesn't fail.

You can avoid the problem with Kotlin by making this change:

```diff
diff --git a/src/test/kotlin/com/example/testresttemplateissue/KotlinApplicationTests.kt b/src/test/kotlin/com/example/testresttemplateissue/KotlinApplicationTests.kt
index c832964..e398745 100644
--- a/src/test/kotlin/com/example/testresttemplateissue/KotlinApplicationTests.kt
+++ b/src/test/kotlin/com/example/testresttemplateissue/KotlinApplicationTests.kt
@@ -38,7 +38,7 @@ class KotlinApplicationTests {
     // Here is the issue with a low level HttpMessageNotReadableException thrown unlike in Javan seems to occur when Jackson Kotlin module + TestRestTemplate.NoOpResponseErrorHandler are used
     @Test
     fun errorHandlingWithTestRestTemplate() {
-        val entity = restTemplate.getForEntity("/foo?converter=bar", Post::class.java)
+        val entity = restTemplate.getForEntity("/foo?converter=bar", Object::class.java)
         assertThat(entity.statusCode).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR)
     }
```

**Comment by sdeleuze** [comment]
I think my question is why should `TestRestTemplate` try to create a `Post`  instance when there is an exception raised. `RestTemplate` does not, including in Kotlin, I am not sure to understand why `TestRestTemplate` should parse the error body which is unlikely to have the same format than the success one.  Any thoughts?

**Comment by bclozel** [comment]
I think Andy already replied to that. 
To put it in another way, how would you prefer to test things with `TestRestTemplate`:

1. when the server sends an error response, you can use `TestRestTemplate` to deserialize the actual error response and check that it is what you expect
2. when the server sends an error response, `TestRestTemplate` throws an exception and it's harder for you to assert what was in the original error response

Right now `TestRestTemplate` behave like 1. because it's easier to test things. Of course the downside is that if something bad happens (getting an error response when you were not supposed to get one) you can't properly deserialize the response. But in that case, the test fails, which is what you'd like anyway.

How would you like `TestRestTemplate` to work in this case?

**Comment by sdeleuze** [comment]
Okay, thanks for the additional detail, I guess I was mainly surprise by this big behavior change compared to `RestTemplate`. I can certainly understand that some people want that, but I tend to think some others could just want to leverage `TestRestTemplate`  automatic base URI and auth configuration while keeping `RestTemplate` behavior in order to validate client + server with an integration test end to end. I guess that could be done by providing a way to not set the `NoOpResponseErrorHandler` by I am not sure how to do that currently.

Do you think this could be a valid use case for `TestRestTemplate`?

**Comment by sdeleuze** [comment]
Note: I have just found https://github.com/spring-projects/spring-boot/issues/7265 which may be related.

**Comment by sdeleuze** [comment]
I have discussed that with @bclozel, and I think I am fine between choosing between `@LocalServerPort` + `RestTemplateBuilder` and have true webservices + `RestTemplate`  integration tests or using `TestRestTemplate`  and specify the relevant type to parse the error body. Thanks for your feedback.
