### ISSUE TITLE
Spring Boot and Spring Security, Spring WebFlux control URL permissions

### ISSUE THREAD

**Issue by dcxy0** [spring-projects/spring-boot#10767]
Spring Boot and Spring Security, Spring WebFlux control URL permissions

The code that controls on Spring MVC is as follows:

    @Override  
    protected void configure(HttpSecurity http) throws Exception {  
        http  
                .authorizeRequests()  
                .antMatchers("/application/shutdown").access("hasRole('ADMIN')")  
                .antMatchers("/**").permitAll();  
    }

But in the Spring WebFlux how to achieve?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
