### ISSUE TITLE
[2.0.0.M5] Can't access static resources

### ISSUE THREAD

**Issue by xxMikhailx** [spring-projects/spring-boot#10799]
Hey
Sorry if I'm doing something wrong, but I have no spring-security dependencies in my classpath, but I can't access static resources. BTW it works fine with the versions of spring boot lower than 2.0.0.M4.

Spring boot v2.0.0.M5

Thank you in advance

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by xxMikhailx** [comment]
Link to Stack Overflow:
https://stackoverflow.com/questions/46990441/spring-boot-2-0-0-m5-cant-access-static-resources
