### ISSUE TITLE
Java 9, Spring boot 2.0.0.M5, JUnit5

### ISSUE THREAD

**Issue by ssnmworld** [spring-projects/spring-boot#10816]
Is there a way to completely disable spring-boot-admin since it is not ready for the 2.0.0.M5 release?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
