### ISSUE TITLE
Binding and environment.getProperty(String) produce different values with additional SystemEnvironmentPropertySource

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10840]
Here's a couple of tests from @dsyer that illustrate the problem:

```java
@Test
public void propertyValues() {
    StandardEnvironment environment = new StandardEnvironment();
    Map<String, Object> overrides = new LinkedHashMap<>();
    overrides.put("foo.password", "test");
    environment.getPropertySources()
            .addFirst(new SystemEnvironmentPropertySource("override", overrides));
    assertEquals("test", environment.getProperty("foo.password"));
}

@Test
public void configurationProperties() {
    StandardEnvironment environment = new StandardEnvironment();
    Map<String, Object> overrides = new LinkedHashMap<>();
    overrides.put("foo.password", "test");
    environment.getPropertySources()
            .addFirst(new SystemEnvironmentPropertySource("override", overrides));
    PasswordProperties instance = new PasswordProperties();
    Binder.get(environment).bind("foo", Bindable.ofInstance(instance));
    assertEquals("test", instance.getPassword());
}

protected static class PasswordProperties {
    private String password;

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
```

`propertyValues` passes and `configurationProperties` fails.

**Comment by dsyer** [comment]
It might be worth pointing out that this isn't really a corner case: any `EnviromentPostProcessor ` (for instance) that wishes to transform OS env vars might fall foul of this inconsistency because `SystemEnvironmentPropertySource` has some logic in it that isn't mirrored in the Spring Boot `SystemEnvironmentPropertyMapper`. The problem was identified by a Spring Cloud user who was trying to decrypt an env var.

**Comment by dsyer** [comment]
Here's the failing test in Spring Cloud: https://github.com/spring-cloud/spring-cloud-commons/blob/2.0.x/spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EncryptionIntegrationTests.java#L28.

**Comment by dsyer** [comment]
I should clarify that last (but one) comment. There must be a way for an `EnviromentPostProcessor` to transform OS env vars, but the problem is it has to do it differently to the way it does "normal" property values. In Spring Cloud we have so far been able to rely on the behaviour of `SystemEnvironmentPropertySource` to smooth things out because any property you put in there automatically has aliases. It's much harder now to do what we need to.

**Comment by dsyer** [comment]
That seems to fix our tests. Thanks.
