### ISSUE TITLE
Confusing Cache-control Response Header

### ISSUE THREAD

**Issue by mrgrew** [spring-projects/spring-boot#10864]
When an application that depends on Spring Security uses a ResponseEntity to specify the Cache-control, the resulting response header is hard to interpret and can be confusing.

See https://github.com/mrgrew/cache-control-demo.git for a Spring Boot application that demonstrates the issue.

This is the cache-control response header that is returned:
```
"cache-control": "no-cache, no-store, max-age=0, must-revalidate, max-age=3600, no-transform, public"
```

**Comment by wilkinsona** [comment]
Thanks for the sample. It appears to be the client that you're using that's producing the confusing, combined header. When queried with curl, this is the response:

```
HTTP/1.1 204
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Cache-Control: max-age=3600, no-transform, public
Date: Wed, 01 Nov 2017 14:37:15 GMT
```

Note that the `Cache-Control` headers appears twice. It's first added by Spring Security's `CacheControlHeadersWriter` before the request is handled. The second occurrence is added by Spring MVC's `ServletServerHttpResponse` when the response is being flushed. In both cases `addHeader` is called rather than `setHeader` which explains why the header appears twice rather than the header from Spring MVC overwriting the header from Spring Security.

The behaviour of Spring MVC (calling addHeader rather than setHeader) is out of Spring Boot's control. If you'd like to pursue this, you'll have to open a Spring Framework JIRA ticket.

/cc @rwinch @bclozel

**Comment by mrgrew** [comment]
Thank you @wilkinsona for taking a look. I see a related issue in the Spring Framework JIRA: [Cache-control overriding not possible](https://jira.spring.io/browse/SEC-2728). I'll research further there.
