### ISSUE TITLE
is spring boot can start with web.xml

### ISSUE THREAD

**Issue by battlesteed** [spring-projects/spring-boot#10951]
the old project of my company is used web.xml to config servlect and web filter,i want to add spring boot project to the old project, but the  spring boot document is too much and my English is  not good so i can not find the document  of  start spring boot with web.xml, so i do not know if spring boot can start with web.xml. thank you.

**Comment by battlesteed** [comment]
i mean i want to run spring-boot on the main methond and using web.xml,i do not want to run spring-boot on the tomcat.sorry  my English is not good.

**Comment by qiuxiaoj** [comment]
All of config in web.xml can using java config instead.

**Comment by battlesteed** [comment]
@qiuxiaoj i know ,so i want to know is spring boot can start with web.xml? if it can ,i do not have to convert web.xml to  java config

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
