### ISSUE TITLE
Update to Thymeleaf 3.0.9.RELEASE

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#10954]
I'd like Reactive Thymeleaf support for `RequestDataValueProcessor` which was fixed in 3.0.9.RELEASE via https://github.com/thymeleaf/thymeleaf-spring/issues/166 It would be nice if this was working without manually updating the Thymeleaf version

**Comment by snicoll** [comment]
@rwinch we have a semi automated process to upgrade dependencies so there is no need to create such issue as it would have been taken care of anyway.

**Comment by rwinch** [comment]
Thanks for the information and pushing a fix.

I'm curious that if I'm not suppose to create a ticket and the change isn't in place, what do I follow to know when the change is being tacked and how do I get notified when the change is made?

**Comment by snicoll** [comment]
The process I mentioned is part of the "pre-release" checklist. If there is a new version, we will upgrade to it prior to the next release.

**Comment by danielfernandez** [comment]
@snicoll I'm curious about this process, if it is info you can give me... how many days before the actual release does such check take place? I mean, for example in this case Thymeleaf 3.0.9 was pushed to Central  a bit more than one day before Spring Boot 2.0.0.M6 was pushed to `repo.spring.io` ... should it have detected the new version or that was late already? Just in case I need to notify you of new bugfixing versions with a very tight timeline (like already happened before :$)

And also... does this process work for Spring Boot 1.5.x too? because I published Thymeleaf 2.1.6 too 6 days ago... should I expect this to be updated automatically?

**Comment by snicoll** [comment]
> how many days before the actual release does such check take place?

It depends. If the cycle of the release is long we may have an intermediate round. We try to avoid doing it at the very late minute to make sure that downstream projects can run their own ITs against our snapshot. We released on a Sunday evening so I am afraid that running the dependency upgrades on a Saturday was not an option.

> does this process work for Spring Boot 1.5.x too

Yes.

> should I expect this to be updated automatically?

Yes.
