### ISSUE TITLE
Consider making the default user's username and password configurable

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10963]
Please see the discussion that starts [here](https://github.com/spring-projects/spring-boot/issues/7958#issuecomment-343102936) for details.

`AuthenticationManagerConfiguration` could consume some properties for configuring the default user's username and password. I'm not sure how useful it would be as it'll quickly back off when the user sets up their own security. Perhaps it's still of sufficient value for demos and the out-of-the-box experience as users are finding their feet?

**Comment by mbhave** [comment]
I agree that it's only useful for demos/OOTB since real-world use-cases wouldn't use a single user. I don't particularly see any harm in bringing the property back but we should be careful about naming it since `security.basic.user` is no longer applicable.

**Comment by rwinch** [comment]
Perhaps we could allow more than one user to be created? Boot would just create a `Map<String,String>` and then delegate to a Spring Security's `UserDetailsMapFactoryBean` that creates a `Collection<UserDetails>` from that `Map<String,String>`.

That would mean users could provide something like this:

```
spring:
  security:
    users:
        user: {noop}password,ROLE_USER
        admin: {noop}password,ROLE_USER,ROLE_ADMIN
```

This has the advantage of being able to provide multiple users and configure any User property. The disadvantage is that it might be more difficult to remember the syntax and the username and roles must be provided.

**Comment by mbhave** [comment]
There was a similar discussion [here](#10349)

**Comment by snicoll** [comment]
Thanks @mbhave, that discussion summarizes our concerns with map-based binding and magic strings breaking IDE support. 

I know @michael-simons has built a starter to bring back the single user configuration. Perhaps he can chime in and share his use cases?

**Comment by michael-simons** [comment]
Hi.
My starter is [here](https://github.com/michael-simons/configurable-single-user-spring-boot-starter), still on M5. 

My use case is actually the single user, in several applications. For those it's enough to configure username, password and roles.

@dasniko had another production use case he described to me… I think it was passing the user properties from an external service during startup or something like that.

**Comment by philwebb** [comment]
I don't mind properties to allow a single user to be configured quickly. It's going to help with migration, give us a nicer learning experience and it seems like it could be useful for demos. I'm tempted to say we should steer clear of the full `Map` based approach since it complicates things quite a bit.

**Comment by philwebb** [comment]
We'll add properties back for single user support.

**Comment by wilkinsona** [comment]
When we add this back, we need to update [this section of the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#default-user).

**Comment by rwinch** [comment]
@mbhave Thanks for the updates. Right now the changes mean that the user cannot provide an encoded password which decreases the security. From a security perspective, only the generated password would be encoded and the user provided one would already be encoded (so that if the password is compromised it is only the encoded password).

**Comment by mbhave** [comment]
Reopening this issue to discuss password encoding. It makes sense that the password specified through properties files or environment variables is encoded. However, the purpose of adding a single user was for ease of configuring the username/password for demos. Encoding the password for those use-cases might be a little tedious. Those who don't want password encoding can add a bean of `NoOpPasswordEncoder`, but that almost seems as much effort as configuring your own `UserDetailsService`. The other option is to specify `{noop}mypassword`.

**Comment by snicoll** [comment]
+1 to what @mbhave said.

**Comment by philwebb** [comment]
I very much dislike the `{noop}password` syntax for properties files, I think it's a little unintuitive. If we need to support encoded properties could we consider an additional property? That would be a little more discoverable and we'd be able to provide meta-data hints:

```
spring.security.user.password-encoding=bcrypt
spring.security.user.password=$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
```

**Comment by mbhave** [comment]
I'm not sure about adding more properties for the single user use-case. From what I can tell, it seems useful only for demos and I think we should document it as such. If someone wants to use a single user in production and encode the password, they should consider adding their own `UserDetailsService` with an encoded password.

**Comment by rwinch** [comment]
> spring.security.user.password-encoding=bcrypt # default is noop

@philwebb We really should not have an insecure default of `noop`.

**Comment by michael-simons** [comment]
Current state is plain text passwords for the single user in config files.  Seems to have been fine so far. I wouldn’t change that / open a box.

**Comment by rwinch** [comment]
@michael-simons The old behavior was an insecure default that has been fixed in Spring Security 5. 
If users really want plain text passwords they can still do so by exposing a single Bean. However, we should not make insecure defaults as it leads users into thinking that using plain text passwords is a good idea.

**Comment by michael-simons** [comment]
So the reasoning is that the insecure configuration has not been Spring Boots result but Spring Securitys. In 5 that changed so in Boot that should adapt, too? Understandable.

**Comment by rwinch** [comment]
> So the reasoning is that the insecure configuration has not been Spring Boots result but Spring Securitys. In 5 that changed so in Boot that should adapt, too? Understandable.

@michael-simons Correct

**Comment by philwebb** [comment]
> We really should not have an insecure default of noop. We want to make it somewhat painful to do the wrong thing (i.e. noop) because it is not considered best practice.

Defining a user/password in a properties file isn't really best practice either. I assume the usual reason that you don't want to use `{noop}` is because a compromised database would contain cleartext passwords? If your `.properties` file gets compromised a lot of information is potentially leaked (DB creds etc).

I feel like we're moving away from the point of this feature. The original goal (as I understood it) was to allow demos to quickly configure a single user. With that in mind, we should probably not make it at all painful to configure the password.

If a user sets:
```
spring.security.user.password=mysecret
```

It's not great if they get an error because the values isn't supported by `bcrypt`.

I think we need to either add this feature and make it clear that we don't recommend it for production, or just not bother and insist that every developer configures things on their own.

**Comment by rwinch** [comment]
I'm open to it being resolved in a way that ensures we have secure defaults. So if that means using hashed passwords by default or not supporting this feature, it gets my +1.

**Comment by philwebb** [comment]
Perhaps @dsyer wants to comment on this one since he was involved in the initial discussion. My current stance is that since we're currently secure by default, abd the `spring.security.user.password` is just a convenience for demos, to should keep it as is and add a "not for production" warning.

**Comment by dsyer** [comment]
I think `{algorithm}password` is fine as a format for properties - the main thing is that I can do it in one line in a config file. I also echo Michael’s comment that it’s not just for demos (there’s a large enough class of simple apps that only need one user, even in production).

**Comment by dsyer** [comment]
Corollary to that last point: we should document how to do the production grade thing (with e.g. `{bcrypt}...`) and make sure it works OOTB.

**Comment by vpavic** [comment]
IMO Spring (and by that I mean Spring in whole, not just individual projects like Security or Boot) should steer users towards what's considered a best practice, especially in the domain of security. Having users configure a cleartext password in application properties isn't quite a best practice.

Regarding the approach to document this as a demo only thing, how much would that actually help in practice? I mean, Boot's pretty good at documenting release notes and uses GitHub issue template that clearly states issues are not used for general questions, and yet how many of the opened issues are invalid due to people not bothering to read the release notes or issue template?

The point is, once the feature is out there, people are going to use it the way they see it fit, not only the way it's documented. I pretty much like the approach Boot 2.0 has taken to Spring Security configuration, and this feels like going back to the old way a bit.

**Comment by mbhave** [comment]
> IMO Spring (and by that I mean Spring in whole, not just individual projects like Security or Boot) should steer users towards what's considered a best practice, especially in the domain of security. 

Agreed. 

The issue was originally intended to do provide an easy way (preferably a one-liner) to specify a single username/password via properties. If we make the encoded password the default, I think most users using these properties will end up specifying `{noop}` but maybe that's not such a bad trade-off.

**Comment by philwebb** [comment]
Thanks everyone for the input. For better or worse, I'm going to take the decision that we will support the `{algorithm}password` format but `password` alone should be `{noop}`. We'll document that this isn't best practice and you probably want your own `UserDetailsService`.

Reasons:
* Properties files can only configure a single user. Most real apps will need a `UserDetailsService` anyway.
* Other passwords in the properties (DB connections etc) all use clear-text. I don't want to confuse users by needing them to add `{noop}` for just this one.
* On the off-chance that a real production app only needs a single user and has decided the properties file is the way to go, they can still use the `{algorithm}password` format.

**Comment by rwinch** [comment]
> I'm going to take the decision that we will support the {algorithm}password format but password alone should be {noop}

I'm not sure I understand. Can you go into more detail about what you plan to do and how it would work?

**Comment by philwebb** [comment]
Sorry if it wasn't clear:

Users will be able to specify the password like this out of the box:

```
spring.security.user.password=mysecret
```

They'll also be able to do this if they want a single property file based password that's more secure:

```
spring.security.user.password={bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
```

We'll document this is a convenience and what they probably want to do is add their own Java configuration.

**Comment by rwinch** [comment]
Thanks for the clarification on what users can do. Do you have plans for how this would be implemented? I wanted to point out that defaulting a password prefix of `{noop}` would break things if a user provides a custom `PasswordEncoder` bean. Perhaps defaulting the prefix would only occur if no `PasswordEncoder` bean is provided?

**Comment by philwebb** [comment]
@rwinch I'm not sure yet, but prefixing `{noop}` if there is no user defined `PasswordEncoder` bean seems like the best option.
