### ISSUE TITLE
boot spring jersey config

### ISSUE THREAD

**Issue by Rasa149** [spring-projects/spring-boot#10973]
Hi
I've upgraded my jersey project to use boot spring but
wherever I used spring annotations, my 
@Context
SecurityContext context;

not working and it is null.
 any suggestion?

my code is like this:

@Service
@RequestScope
public class GLSMResource extends PegasusBaseResource implements GLSMService {
	@Context
	SecurityContext context;
	
	@Autowired(required=true)
	private GLSuffixRepository repository;

Thanks,
Rasa

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
