### ISSUE TITLE
Spring boot service fails to stop

### ISSUE THREAD

**Issue by ahirsh** [spring-projects/spring-boot#10981]
Hi (I'm using Spring boot 1.5.8 installed as a service [init.d] on amazon linux EC2 )

I am  trying to resolve a problem when upgrading our spring boot app,
we now use it as a service , and after installation i found that sometimes it is impossible to stop the service , and i see the below message with (service myapp stop):
Unable to kill process 2509

while i see it running with (service myapp status):
Running 2509

A subsequent attempt to stop the service does not succeed and returns the Unable to kill process message (the response is intantly).

i have my machine now stuck in this status and i can provide more information if needed for further analysis.

can you please help ? thank you !
(i saw some case: 
https://github.com/spring-projects/spring-boot/issues/4941 , so i see the problem is known but maybe it still happens ?)

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by ahirsh** [comment]
@wilkinsona i would gladly add more details but currently i am using the product as described in the docs and it is behaving wrongly , is there anything else i can provide ?

**Comment by wilkinsona** [comment]
From little information that you have provided it's unclear why you think that Spring Boot is behaving incorrectly, rather than code in your application. For example, there could be something in your application that has caused the JVM to deadlock and prevent it from shutting down. If you need some help diagnosing why the JVM cannot be killed then Stack Overflow is the best place to ask.

If you believe this is a bug in Spring Boot, then please provide the information that you used to determine that's the case.

**Comment by ahirsh** [comment]
I see my endpoints return responses , and i have thread that refreshes its cache from SQL DB performing the job each 60 seconds and prints to console each time .... so could it be that the JVM is in deadlock while my app is still running and responding ?

**Comment by ahirsh** [comment]
@wilkinsona the problem was embarassing , i was trying to stop the app from a different user , maybe the running script log could different error message in such case.... if not i understand.... thank you @wilkinsona
