### ISSUE TITLE
关于spring-boot构建的工程运行需要的最低配置

### ISSUE THREAD

**Issue by avalonyzhily** [spring-projects/spring-boot#11043]
您好，我使用spring-boot构建了一个web工程，因为设计需要，使用maven将项目拆分成了多个模块，其中web应用通过jar的形式依赖其他模块。
这样，我打包成可执行jar之后，在服务器上运行，服务器环境是windows server 2008，内存4g，当命令行输入java -jar 运行指令后，无响应；然后我再次增加参数-verbose，发现启动过程中，会卡在加载spring-boot的jar包下的某个类的时候，具体是哪个类是不确定的。当我采用8g以上内存的机器运行时，才能正常启动项目；
我使用任务管理器，查看了启动时的cpu占用不到10%，内存占用不到60%。
也尝试增加启动参数调高jvm的初始内存，均无效果。

**Comment by snicoll** [comment]
Courtesy of Google translate

> Hello, I used spring-boot to build a web project that uses maven to split the project into modules because of the design needs, and web applications rely on other modules in the form of a jar.
In this way, I packaged into executable jar, run on the server, the server environment is windows server 2008, memory 4g, when the command line input java-jar run command, no response; then I again increase the parameter -verbose, found the startup process In the card will be loaded in the spring-boot jar package under a class, specifically which class is not sure. When I use more than 8g memory machine running, to start the project normally;
I use the Task Manager, view the startup cpu occupy less than 10% of the memory footprint less than 60%.
Also try to increase the startup parameters to increase the initial memory jvm, no effect.



Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by avalonyzhily** [comment]
thx~
