### ISSUE TITLE
About annotation Mapping issue

### ISSUE THREAD

**Issue by witpool** [spring-projects/spring-boot#11060]
Use GetMapping as below: 

`@GetMapping(value = "/{userId}/")`

When start spring boot application and test API with [WisdomTool RESTClient](https://github.com/wisdomtool/rest-client) 

Get the below error messages:
`
== REQUEST  ==

GET http://127.0.0.1:8080/users/20

-- HEADERS  --
Content-Type : application/json; charset=UTF-8
Accept : application/json

== RESPONSE ==

HTTP/1.1 200 

-- HEADERS  --
Date : Fri, 17 Nov 2017 09:14:38 GMT
Transfer-Encoding : chunked
Content-Type : application/json;charset=UTF-8

--   BODY   --
{"instance":null,"instances":null,"code":1006,"msg":"**Request method 'GET' not supported**"}

`

If change _**users/20**_ to  _**users/20/**_ it no error occurs.

Both '/{userId}/' and '/{userId}' should have the same behavior. 
Why using /{userId} will be failed?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
