### ISSUE TITLE
Improve OnClassCondition report to only mention the condition that has been configured

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/spring-boot#11086]
I have this class:

```java
@Component
@ConditionalOnClass(name="java.lang.String")
public class MyConditionalComponent {
}
```

and the auto-config report for this looks like:

```json
       "MyConditionalComponent": [
            {
                "condition": "OnClassCondition",
                "message": "@ConditionalOnClass found required class 'java.lang.String'; @ConditionalOnMissingClass did not find unwanted class"
            }
        ]
```

why does the `@ConditionalOnMissingClass` message appears?
And it seems to append the same message quite often for conditionals. Any idea why that happens?

**Comment by snicoll** [comment]
> ConditionalOnMissingBean

What `ConditionalOnMissingBean`? I see `@ConditionalOnMissingClass`

**Comment by martinlippert** [comment]
@snicoll My fault, you are right, I meant the `ConditionalOnMissingClass`, let me fix this here,

**Comment by jorgefr** [comment]
I just stepped into this too and the reason is that OnClassCondition#getCandidates returns an empty list even when the annotation is not present:

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/OnClassCondition.java#L162

So the next condition evaluates to true and prints the information:

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/OnClassCondition.java#L140

And the same applies to when `ConditionalOnMissingClass` is specified but no `ConditionalOnClass` is specified

**Comment by martinlippert** [comment]
Awesome, thanks @mbhave for the fix !!!
