### ISSUE TITLE
set ReturnValueHandlers throw OoutBoundException,i use HandlerMethodReturnValueHandler

### ISSUE THREAD

**Issue by zxj19951029** [spring-projects/spring-boot#11124]
This is code
```java
@Configuration
public class WebConfiguration extends WebMvcConfigurerAdapter {
    @Autowired
    private HandlerValue handlerValue;
    @Override
    public void addReturnValueHandlers(List<HandlerMethodReturnValueHandler> returnValueHandlers) {
        super.addReturnValueHandlers(returnValueHandlers);
        returnValueHandlers.add(1,handlerValue);
    }
}
```
I wan't to set my handler to first,but,set 0 is invalid,set 1 while throw a OoutBoundException~
How can i set it first? Because it while adapter an other handler

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
