### ISSUE TITLE
vulnerability in 1.5.8 

### ISSUE THREAD

**Issue by ammy1999** [spring-projects/spring-boot#11127]
Hello, 
I have a vulnerability in spring-boot-starter-data-mongodb-1.5.8.RELEASE.jar
i am using OWASP dependency check to validate that my dependencies dont contain any known vulnerability 
The report has came with several vulnerabilities, which i will detail below: 
CVE-2012-6619 
CVE-2013-1892 
CVE-2013-2132 
CVE-2014-8180 
CVE-2015-1609 
CVE-2016-6494

> 
[INFO] +- org.springframework.boot:spring-boot-starter-data-mongodb:jar:1.5.8.RELEASE:compile
[INFO] |  +- org.mongodb:mongodb-driver:jar:3.4.2:compile
[INFO] |  |  \- org.mongodb:mongodb-driver-core:jar:3.4.2:compile
[INFO] |  \- org.springframework.data:spring-data-mongodb:jar:1.10.3.RELEASE:compile
[INFO] |     \- org.springframework:spring-tx:jar:4.3.8.RELEASE:compile

is there any plan to release a new version with those issues resolved?

Thanks

**Comment by wilkinsona** [comment]
Unfortunately, the OWASP dependency check regularly produces false positives. This is another example of it doing so:

- CVE-2012-6619 is a vulnerability in MongoDB server (not the driver) before 2.3.2
- CVE-2013-1892 is a vulnerability in MongoDB server before 2.0.9 and 2.2.x before 2.2.4
- CVE-2013-2132 is a vulnerability in MongoDB's Python driver before 2.5.2
- CVE-2014-8180 is specific to MongoDB as installed by RedHat Satellite 6
- CVE-2015-1609 is a vulnerability in MongoDB server before 2.4.13 and 2.6.x before 2.6.8
- CVE-2016-6494 is a vulnerability in MongoDB server that is fixed in 3.0.15, 3.2.14 and 3.3.14
