### ISSUE TITLE
IllegalArgumentException: Unable to locate persister when running a spring-boot fat jar

### ISSUE THREAD

**Issue by mabbas85** [spring-projects/spring-boot#11144]
Hello,

I've created a sample project with 2 modules: 
- The first module "**example-project**" is a spring project that contains a JPA entity + a service class and a DAO class for this entity. (I've declared this entity inside an `orm.xml` file + the configuration of the persistence unit inside a `persist.xml` file).
- The second module "**example-project-boot**" is a simple spring-boot that call the service class of the first module.

Please find below the codebase of this project (you can also find it here https://github.com/mabbas85/example-project-parent).

When I run this project with IntelliJ or Eclipse, everything works as expected.

When I package this same project as a fat jar, then I try to run it, I am getting an `IllegalArgumentException: Unable to locate persister.`

I noticed that, on startup, a call is made to method `org.springframework.orm.jpa.persistenceunit.PersistenceUnitReader#determinePersistenceUnitRootUrl `    
with    `/Users/mabbas/example-project-parent/example-project-boot/target/example-project-boot-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/example-project.jar!/META-INF/persist.xml`

and this method is returning       /`Users/mabbas/example-project-parent/example-project-boot/target/example-project-boot-0.0.1-SNAPSHOT.jar`

instead of 

`/Users/mabbas/example-project-parent/example-project-boot/target/example-project-boot-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/example-project.jar` (the root of `persist.xml` is **example-project** and not **example-project-boot**). 

Because of this result, i think that the entity defined inside `example-project.jar` is never loaded and then the exception is thrown.

I am using spring-boot 1.5.8.RELEASE.

Am i doing something wrong or is it a bug in spring?

Thanks in advance,

[example-project-parent.zip](https://github.com/spring-projects/spring-boot/files/1502641/example-project-parent.zip)

**Comment by wilkinsona** [comment]
I'm not sure that you're doing anything wrong, but your app is a rather unusual Spring Boot application. 

You're configuring lots of things manually and doing so with XML in some cases. A typical Boot application would allows Boot's auto-configuration to configure Hibernate, its DataSource, etc, and where it wanted to customise the configuration would use Java `@Configuration` rather than XML.

That said, I'm not sure that making more use of auto-configuration would fix your specific problem as the determination of the persistence unit root is done by Spring Framework. You should open a [SPR JIRA ticket](https://jira.spring.io/browse/SPR) if you believe it's incorrectly determining the persistence unit's root URL. If you do that, please comment here with a link to the JIRA ticket so that we can watch it and assist as needed.

**Comment by mabbas85** [comment]
Thank you for your answer. I've just created the [SPR JIRA ticket](https://jira.spring.io/browse/SPR-16233).
I agree that it is an unusual spring-boot application, but unfortunately, in my real spring-boot project I have a dependency to a legacy jar with all the ugly XML stuff inside, and this legacy jar cannot be modified.
