### ISSUE TITLE
Spring Boot does not follow HTTP RFC

### ISSUE THREAD

**Issue by voronaam** [spring-projects/spring-boot#11173]
This is a 3rd ticket in the chain. The links to the first two are in the footer.

Spring Boot doesnt appear to honor `accept-encoding: gzip;q=0,deflate,sdch`. If you create a plain Boot app and enable

```
server.compression.enabled=true
server.compression.min-response-size=1
```

Then send a request with the above accept-encoding header the content still comes back gziped. While RFC clearly states it should not be.

According to RFC https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3 the qvalue zero means "not acceptable".

Other issues in the chain:
https://github.com/spring-cloud/spring-cloud-netflix/issues/2343
https://github.com/Netflix/zuul/issues/365
Reason for this issues being on Spring Boot: https://github.com/spring-cloud/spring-cloud-netflix/issues/2343#issuecomment-347239185

**Comment by wilkinsona** [comment]
Unfortunately, I think you may have been pointed in the wrong direction.

Boot itself doesn’t deal with response compression. Instead, we just configure the underlying container’s compression support. You haven’t said which container you’re using so there’s not much we can do at this point.

Can you provide a sample that reproduces the problem you’ve described?

**Comment by wilkinsona** [comment]
I had a little more time to investigate. Both Undertow and Jetty honour `;q=0` in the `Accept-Encoding` header but Tomcat does not. If you'd like to pursue this, please open an issue in [Tomcat's Bugzilla](https://bz.apache.org/bugzilla/).

In the meantime, I think you have a couple of options:

1. Switch to Jetty or Undertow
2. Rather than using `;q=0`, omit `gzip;q=0` from the `Accept-Encoding` header entirely
