### ISSUE TITLE
Why is testing a rest client with multiple rest templates considered not valid?

### ISSUE THREAD

**Issue by hadjiski** [spring-projects/spring-boot#11185]
https://github.com/spring-projects/spring-boot/blob/abe010aba8777272e0e0a57610242bf6d09cbfbe/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/web/client/MockServerRestTemplateCustomizer.java#L105

With spring boot 1.5.8 I am using a @Component class with @Autowired rest template builder, which builds multiple rest templates and puts them in a map. Later I am using templates from the map depending on some input. In my @RestClientTest marked test I am not able to test the client because of the exception thrown:

> @Component
public class RestClientBean implements RestClient {
  private Map<String, RestTemplate> restTemplates = new HashMap<>();
  @Autowired
  public RestClientBean(RestTemplateBuilder builder) {
    restTemplates.put("first", builder.rootUri("first").build();
    restTemplates.put("second", builder.rootUri("second").build();
  }
}
@RunWith(SpringRunner.class)
@RestClientTest(RestClient.class)
public class RestClientTest {
  @Autowired
  private RestClient client;
  @Autowired
  private MockRestServiceServer server;
  @Before
  public void setUp() throws Exception {
    server.expect(requestTo("/somePath")) // here an exception is thrown
          .andRespond(withSuccess("<valid json>", MediaType.APPLICATION_JSON));
  }
}

Exception:

> java.lang.IllegalStateException: Unable to use auto-configured 
MockRestServiceServer since MockServerRestTemplateCustomizer has been bound to 
more than one RestTemplate

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by hadjiski** [comment]
@wilkinsona why not considering this as enhancement? It is obvious that there is an assertion for multiple rest templates. I am wondering why not supporting multiple rest templates in one rest client class

**Comment by wilkinsona** [comment]
I closed the issue because you asked a question ("Why is testing a rest client with multiple rest templates considered not valid?") and the contribution guidelines explain that GitHub issues are not the right place to ask questions.

`MockServerRestTemplateCustomizer` already supports multiple servers and REST templates, it's only `@RestClientTest` that does not. It only supports a single `RestTemplate` and `MockRestServiceServer` as that's the only way it can provide a single injection candidate for auto-wiring into your test.

**Comment by hadjiski** [comment]
Well, an enhancement could be to introduce a new "expect" method to MockRestServiceServer, which should allow specification for a concrete template, so that auto-configure of multiple templates would be possible, right?

**Comment by wilkinsona** [comment]
I’m not sure how that would work and, more importantly, `MockRestServiceServer` is part of Spring Framework.

I think you should drop your use of `@RestTestClient` and use ‘MockServerRestTemplateCustomizer’ and its `getServers()` or `getServer(RestTemplate)` methods directly. If you need further guidance, please follow up on Stack Overflow or Gitter.
