### ISSUE TITLE
Cache metrics are no longer available

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#11221]
While micrometer does provide support for cache providers, there is no auto-configuration support for it anymore. We should add that so that users get those metrics automatically again.

See https://github.com/micrometer-metrics/micrometer/issues/256

**Comment by snicoll** [comment]
Looking at the code, we could easily restore an auto-configuration that loops over all cache managers of the supported type to add the cache they define but the problem is that we would do so only for the caches that are available on startup. 

That's really annoying as caches may be added during the lifecycle of the app and we have no way to intercept that (the cache abstraction, rightfully so, doesn't have a contract for it).

`PublicMetrics` in `1.x` was quite handy for this. Perhaps @jkschneider has an idea?

**Comment by jkschneider** [comment]
It's easy enough to create a `CacheManagerMetrics` binder that we can add to the autoconfigured set of binders in `MeterBindersConfiguration` in Boot. This would essentially mirror what was done in `CachePublicMetrics` (as far as I can tell, `PublicMetrics` has essentially the same function as `MeterBinder`).

For caches that are created outside of a Spring context, I think it is easy enough to do:

```java
LoadingCache<Integer, String> cache = CaffeineCacheMetrics.monitor(
   registry, 
   Caffeine.newBuilder().recordStats().build(key -> { /*  build a value */ }), 
   "my.cache", userTags);
```

There was no built-in facility for this in 1.5 right?

**Comment by snicoll** [comment]
Registering the caches on startup is easy but this is not what PublicMetrics does at all. It is called on every request to get metrics so you always get a fresh view of your caches. 

The example you gave is user code. It didn't have to worry about metrics so far (the next request would automatically include it). Am I missing something?

**Comment by jkschneider** [comment]
I still don't get it. It looks like `CachePublicMetrics` iterates over an `@Autowired` map of `CacheManager`s on each call to get metrics. I don't see how `CacheManager` instances that are created after `CachePublicMetrics` is autowired get metrics collected.

Regardless of how this shapes up, don't worry -- we can make it work. At this point we can't be too nostalgic about `PublicMetrics`. That specific abstraction doesn't stand up to differences in push/pull semantics and other differences in monitoring systems. But that doesn't mean we can't accomplish the same ends in a different way. Everything's easier when you're just stuffing hierarchical metrics in Dropwizard ;)

Worst case we can make `MeterBinder` two-phase: (1) bind on create and (2) bind on each publish. We've avoided (2) to this point simply because there hasn't been a need and it has a greater potential for misuse, but we've made changes like this before.

**Comment by jkschneider** [comment]
Separately, I think we may need to talk about getting stats out of the `CacheManager` abstraction. Boot 1.5 was only reporting stats on size, hit ratio, and miss ratio. Our implementation-specific cache binders for Guava, Caffeine, Hazelcast, etc report much more specific metrics that are unique to each implementation. There is no `CacheStatistics`-like abstraction that can cover their idiosyncracies.

Maybe we can sit down and talk about this at S1P next week?
