### ISSUE TITLE
Slice tests don't work with WebFlux/reactive model

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#11230]
**Problem Description**
Looks like most of the "slice" tests described in section [41.3.5 Auto-configured tests](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-testing-autoconfigured-tests) don't work with the WebFlux or reactive model. 

`@WebMvcTest` looks for controllers, and doesn't find `RouterFunction` and `RouterFunction`. Even if a `@RestController` is made for WebFlux, it fails looking for Servlet-specific classes (I don't remember the exact error).

`@DataMongoTest` has no knowledge of `ReactiveCrudRepository` and such.

`@RestClientTest` only configures `RestTemplateBuilder`, not `WebClient`.

**Rant**
_Matter of fact, I've seen this problem with every major release. When Spring 3 was released, Java config was not fully ready, but was announced as a game changer. With Spring 4, Groovy support was a biggie, but it took couple of minor versions to get it working in idiomatic manner (like bean definitions in Groovy). With Spring 5, reactive model is hyped, but existing test framework doesn't fully support it. I understand why new features may be good fodder for elevator pitches, but it's very frustrating when the shiny new things actually have rust underneath._

**Comment by philwebb** [comment]
@asarkar Your rant is unhelpful and unwelcome in the issue tracker. Like most software projects we have limited time and resources. We're doing the best that we can.

---

To address your issues:

> @WebMvcTest looks for controllers, and doesn't find RouterFunction and RouterFunction. Even if a `@RestController` is made for WebFlux, it fails looking for Servlet-specific classes (I don't remember the exact error).

`@WebMvcTest` is indeed tied to the Servlet API and it won't find `RouterFunction` beans since they are part of WebFlux. You probably want to try `@WebFluxTest` rather than `@WebMvcTest`. I'm not sure if we have `RouterFunction` support with that annotation or not. If you find it doesn't work, please open a new dedicate issue (we prefer that each issue focuses on a single problem, rather than have one issue reporting several things).

> `@DataMongoTest` has no knowledge of `ReactiveCrudRepository` and such.

I don't know what this means, please open a new issue with a more complete description along with a sample application that we can clone and run.

> `@RestClientTest` only configures `RestTemplateBuilder`, not `WebClient`.

Correct, this annotation is designed to mock server calls for `RestTemplateBuilder`. It makes no sense for it to configure a `WebClient`.

**Comment by snicoll** [comment]
>  I'm not sure if we have RouterFunction support with that annotation or not. 

We don't and there is #10683 for that

> @RestClientTest only configures RestTemplateBuilder, not WebClient.

What Phil said. There is also a issue in Spring Framework to update `RestTemplateBuilder` to work with the web client. Once we have that, we'll be able to offer support  in `@RestTestClient` and we have #8404 for that.

@asarkar a more positive way would be to come up with pull requests or dedicated issues with a technical analysis rather than dumping the stuff you want that doesn't work.

**Comment by asarkar** [comment]
@philwebb, allow me to elaborate. As a heavily-invested user and sometimes contributor, if I feel that one of the best frameworks in Java has a long standing history of shipping major versions that break support for existing features, where should I have that conversation? Am I supposed to fill up a grievances form and mail it by registered post? Shutting down a valid but uncomfortable discussion is the opposite of helpful.

@snicoll I’m all for PRs, but if the people who are dedicated to the project can’t find time, how much time can outsiders spend? And in case, shouldn’t they raise a concern first?

I appreciate what you do for the Spring framework. I hope my original post didn’t run off the wrong way.
