### ISSUE TITLE
Exception logged on startup with spring data JPA and postgres driver with 2.0.0M7

### ISSUE THREAD

**Issue by seanjreilly** [spring-projects/spring-boot#11260]
When starting a spring boot application using
- spring boot 2.0.0M7
- spring data boot JPA starter
- The postgres JDBC driver v42.1.4

as well as a few other things which hopefully aren't relevant

The following warning and stack trace is emitted on startup:

https://gist.github.com/seanjreilly/623f93624c4c5f8e02f5c59e891d979b

This happens with 2.0.0M6, 2.0.0M5, and the latest snapshot as well, but does not happen with 2.0.0M4.
Is it possible that there's some sort of regression?

**Comment by wilkinsona** [comment]
I think this is due to the upgrade to Hibernate 5.2.11 in M5. 5.2.11 made a number of changes to clob handling with Postgres. Please see the Hibernate [release notes](http://in.relation.to/2017/09/13/hibernate-orm-5211-final-release/) for further information. As I understand it, the message is purely informational.
