### ISSUE TITLE
Spring Zuul Oauth2 JWT flow using curl

### ISSUE THREAD

**Issue by neildcruz** [spring-projects/spring-boot#11265]
I am using a ZuulProxy with @EnableOauth2Sso and @EnableResourceServer which points to an Auth Server with form based authentication.

This flow works correctly when I use a browser which redirects to the login form in my auth server and then redirects back to Zuul, performs the Oauth dance and then redirects to my intended URL.

I am not able to simulate this flow using a curl command or a non-browser utility to make it work? Is this posible with Oauth JWT tokens with spring scurity?

curl --request POST -u clien:cliensecret "http://server:9999/uaa/oauth/token?grant_type=password&username=user&password=pass"
Returns the access_token, refresh_token but a subsequent call with the Header "Bearer token" does not seem to work.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by neildcruz** [comment]
Thanks @wilkinsona, have posted the same question on SO. Sharing the link here as suggested:

https://stackoverflow.com/questions/47649672/spring-zuul-oauth2-jwt-flow-using-curl
