### ISSUE TITLE
How to use graphic verification code and token for login verification in spring boot by spring security?

### ISSUE THREAD

**Issue by shawn-show** [spring-projects/spring-boot#11268]
I intend to use a graphical authentication code on the page to do login verification, but I do not know how to do it in spring boot by spring security.
In addition, I'm going to plug in token in cookie to remember the logined account, but how to let spring security parse the token?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
