### ISSUE TITLE
JDBCTemplate Bug in version 1.5.9

### ISSUE THREAD

**Issue by feng-junbb** [spring-projects/spring-boot#11281]
After upgrade from version 1.3.3 to 1.5.9, the JDBCTemplate.queryForList does not work properly. Before the query can return the result, not only the empty list. Can someone help me out?

Thanks!
Feng

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
