### ISSUE TITLE
spring boot logging not working with macOS High Sierra

### ISSUE THREAD

**Issue by vasumtech** [spring-projects/spring-boot#11297]
I have upgraded to macOS High Sierra today and I tried to start the Spring Boot (v1.4.2.RELEASE) application using Tomcat (tried on versions 8.0.36 & 9.0.2) & Jetty (version-9.4.6) servers, I could notice that there is no logging either to console or to the file. However, the System.out.println() works fine.

Just to be clear, Spring boot logging was working perfectly fine before upgrading to macOS High Sierra 10.13.2 (from macOS 10.12 Sierra).

Could you please help with this issue on how to fix it? Please let me know if you need any additional information on this.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
