### ISSUE TITLE
What is the meaning of Spring Logo?

### ISSUE THREAD

**Issue by tbwork** [spring-projects/spring-boot#11323]
I bet with my friend on what the kind of the leaf in Spring Logo.
Is it a thyme leaf?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by tbwork** [comment]
Gatta, hah, take it easy, thanks for your response anyway.
