### ISSUE TITLE
Support Tomcat specific properties for Reactive server setup

### ISSUE THREAD

**Issue by sjkim2322** [spring-projects/spring-boot#11334]
i cloned [spring-boot-sample-webflux](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-webflux).
in spring-boot-starter-webflux,
netty is a default
so i added this dependency to use tomcat container
```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-tomcat</artifactId>
</dependency>
```
then it runs on the tomcat container.
i configured in `application.properites` `server.tomcat.max-threads= 10`
but it didn\`t work.
but another tomcat configure options like `server.port` works fine.
am i missing something? or is it bug?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by bclozel** [comment]
After chatting a bit with @snicoll, we've found something missing in our Tomcat reactive support. It's sometimes hard to make the difference between pilot error and bugs - this is why we often ask for repro samples.

We're reopening this issue.
