### ISSUE TITLE
ServletListenerRegistrationBean should not extends RegistrationBean

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11344]
See #11342

**Comment by snicoll** [comment]
@philwebb I tried to give this a quick try and got stuck because `ServletContextInitializerBeans` [expects it to be a `RegistrationBean`](https://github.com/spring-projects/spring-boot/blob/0aedd3f11de9fe2fff927d3f3c921ae40feded95/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/servlet/ServletContextInitializerBeans.java#L163-L165). And there is an [adapter that would be useless/invalid now](https://github.com/spring-projects/spring-boot/blob/0aedd3f11de9fe2fff927d3f3c921ae40feded95/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/servlet/ServletContextInitializerBeans.java#L301-L313)

**Comment by philwebb** [comment]
@snicoll Good point. I've kept `RegistrationBean` but extracted dynamic registration concerns to a new `DynamicRegistrationBean` subclass.
