### ISSUE TITLE
application.yml Configuration file cannot be scanned AtomikosProperties

### ISSUE THREAD

**Issue by nessary** [spring-projects/spring-boot#11347]
I use spring boot ,  but i find  some configure have no effect

after 
application.yml Configuration file cannot be scanned AtomikosProperties
 
please help me 
@qerub 
@jkutner 
@rtack 
thanks 

this is my configure 

spring:
  jta:
    atomikos:
      properties:
        log-base-dir: ${java.io.tmp}
        log-base-name: test
        console-log-level: info

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
