### ISSUE TITLE
How to add associated user for client_credentails grant_type

### ISSUE THREAD

**Issue by mrshawn191** [spring-projects/spring-boot#11351]
Hi I'm bit stuck and would appreciate some tips.

This is my usecase. 

Our app supports both password and client_credentials granttype.

In case user choose to go with client_credentials I want to generate a jwt token with the associated user, basically i want the same behaviour in spring security when using password granttype. 

Where can I add my custom logic so that i add the user context when issuing the token?

Is is possible to customize the behaviour during client_credentials granttype? Is it something with tokenenhancer?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
