### ISSUE TITLE
Spring boot 2 actuator (BUILD-SNAPSHOT) - class EndpointHandlerMapping has been removed

### ISSUE THREAD

**Issue by thaingo** [spring-projects/spring-boot#11363]
The class EndpointHandlerMapping has been removed from the Spring boot actuator 2.0.0.BUILD-SNAPSHOT. What is the alternative?

Thanks.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by snicoll** [comment]
Actually, maybe you have a use case that would be of interest in case we've missed something. The actuator has changed quite significantly in 2.0. Please [read the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#spring-boot-actuator). Can you expand why you need to use `EndpointHandlerMapping`  directly?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Sarvesh-D** [comment]
Hi i have the same issue, i am unable to find `EndpointHandlerMapping` or `EndpointHandlerMappingCustomizer` in spring actuator 2.0. My use-case is to intercept the requests coming to actuator endpoints to perform some authorization and event logging when some one calls the actuator endpoints. Please see the [stack overflow post answer](https://stackoverflow.com/questions/30839350/how-to-apply-handlerinterceptor-to-spring-boot-actuator-endpoints). I think the use-case is valid.

**Comment by wilkinsona** [comment]
Please see https://github.com/spring-projects/spring-boot/issues/11234. Our recommendation is that you use a Servlet Filter instead.
