### ISSUE TITLE
Interceptor workes for only few request, not every

### ISSUE THREAD

**Issue by wangyinsheng** [spring-projects/spring-boot#11377]
hi，there
    I tried to add a interceptor and  add path pattern like this `/**`,  then i found that this interceptor works for only few request, not every request.
   I made an example for you guys,  [demo.zip](https://github.com/spring-projects/spring-boot/files/1570143/demo.zip)
   in the interceptor , it record time usage of every request, and i add a demo controller  with request mapping like this `/demo/list`.  While, when i send a request `http://localhost:8080/demo/list`, i found the interceptor works.  and when i send other request which dose not exist, like `http://localhost:8080/demo/list1111`, the interceptor does not work
     I need a interceptor works for every request, what should i do?
    spring-boot version : 1.5.9.RELEASE

**Comment by wangyinsheng** [comment]
I tried to use xml config file instead， it works。
![image](https://user-images.githubusercontent.com/13392313/34139835-eb59bd3c-e4b1-11e7-8d3a-06b96292334d.png)


so why it does not work in springboot way?

**Comment by bclozel** [comment]
I cannot reproduce this behaviour with the project you provided.
Registering interceptors through JavaConfig or XML should make not difference to Spring MVC.

Note that the interceptors approach for timing requests has a lot of caveats - you're basically skipping all the processing happening in Servlet Filters and measuring in a brittle way. For this use case, you should take a look at the Actuator Metrics feature in Boot and especially in the upcoming support of Micrometer in Spring Boot 2.0.

**Comment by wangyinsheng** [comment]
@bclozel    It really happens， request the following url， and see the difference

>http://localhost:8080/demo
 http://localhost:8080/demo/list

I get this
![image](https://user-images.githubusercontent.com/13392313/34152708-7e9a432c-e4ea-11e7-8f3d-338315baf6da.png)
the first line was printed when request `http://localhost:8080/demo`, and the second line was printed when request `http://localhost:8080/demo/list`
see the difference?
it got `/error` in the interceptor when request the first url,  not  `/demo`

by the way,  timing is just example, what if approach for logining?  the `/demo` request would not redirect to the login page

**Comment by bclozel** [comment]
Still, this is the expected behaviour.

`HandlerInterceptors` provide an interception mechanism around Spring MVC handlers. If a request is handled directly by a Servlet Filter or another Servlet (say, the Default Servlet when serving files with your container), `HandlerInterceptors` are never called.

In the case of HTTP 404, Spring Boot provides [an error handling mechanism](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-error-handling). Spring Boot dispatches errors (handler not found or handler exceptions) back to an `ErrorController`. This is why your interceptor is called with the `/error` path. If you try the same thing with vanilla Spring Framework, your interceptor might not be called at all.

Again, the `HandlerInterceptor` infrastructure is probably not the right one for your use case and a Servlet filter might be a better fit.

**Comment by wangyinsheng** [comment]
so, why the result is different with XML way? 
![image](https://user-images.githubusercontent.com/13392313/34153800-500b9d86-e4ee-11e7-956f-4c81bfa1ca6a.png)

The first two line printed when request `http://localhost:8080/demo`, it really works, that is what i expected . And the last lien printed when request `http://localhost:8080/demo/list`, still expected.

**Comment by bclozel** [comment]
When you declare an interceptor like this:

```
<mvc:interceptors>
  <bean class="com.example.demo.inteceptor.TimeInterceptor"/>
</mvc:interceptors>
```

Its JavaConfig equivalent is:

```java
@Configuration
public class MyConfig {
  @Bean
  public MappedInterceptor timeInterceptor() {
    String[] mappings = {"/**"};
    return new MappedInterceptor(mappings, new TimeInterceptor());
  }
}
```

Mapped interceptors declared as beans in the context are applied globally to all registered `HandlerMapping`, whereas `HandlerInterceptors` added with `WebMvcConfigurerAdapter` are applied to most, but not all. For example, they're not applied to the handler mapping that serves static resources. This is done because the primary goal of interceptors is to give you an interception mechanism for handlers (usually, controllers) and there's little value in intercepting requests for static resources.

Now in the case of the `/demo` request, since nothing else matches that route, the resource handler matches (it is mapped to `"/**"`) and interceptors are applied.

Again, using interceptors for this use case is not ideal; if you were to change the resource handling configuration, this wouldn't work anymore. Try adding the following configuration to your application: `spring.mvc.static-path-pattern=/static/**`.

If you've got further questions, please ask on StackOverflow - the issue tracker is meant for bugs and enhancement requests on Spring Boot only.

**Comment by wangyinsheng** [comment]
Thanks a lot  @bclozel
