### ISSUE TITLE
How to use the mvc attribute configured in xml, do not use springboot embedded mvc attribute

### ISSUE THREAD

**Issue by jidianxiake** [spring-projects/spring-boot#11389]

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Also, please add more details about this in your StackOverflow question:
* what are you trying to achieve?
* what did you try (provide your configuration code)?
* what is the expected behaviour and what did you get instead?

Thanks!
