### ISSUE TITLE
Add @WebEndpointTest for testing custom actuator web points

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-boot#11399]
It would be convenient if, similar to `@WebMvcTest`, there was a `@WebEndpointTest` annotation to support testing custom `@WebEndpoint` implementations.

**Comment by snicoll** [comment]
@manderson23 can you expand on what you are expecting exactly? Is that an web-specific test style where you could use `MockMvc` to contact the endpoint? You can't use `MockMvc` with a reactive-based app so that's not really realistic. 

We use [a custom rule](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/endpoint/web/test/WebEndpointRunners.java) to make sure each endpoint runs consistently with MVC, WebFlux and Jersery. I am not sure that's what you're after.

**Comment by manderson23** [comment]
@snicoll OK in my case I'm MVC only so I'd be happy to make my own rule. I did look at your tests and seen the custom rule there. Would it be feasible and/or useful to make that part of the public API?

**Comment by wilkinsona** [comment]
I'm reluctant to make `WebEndpointRunners` public as I don't want to be affected by the constraints that it would introduce. Being able to make breaking changes to the runner whenever we like is rather useful. Unfortunately, I don't think we have time in 2.0 to revisit our runner to get it into a state where it's ready to be public.

**Comment by wilkinsona** [comment]
We discussed this a bit more today, and our feeling is that you should either just unit test your endpoint and trust the infrastructure to do what it claims to do, or you can create a full-blown integration test and call the endpoint using `TestRestTemplate`, for example.
