### ISSUE TITLE
RequestBodyAdvice  not work 

### ISSUE THREAD

**Issue by zld406504302** [spring-projects/spring-boot#11421]
I want to use RequestBodyAdvice   to  log something ,but it doesn't work.

this flow is my code .

@SpringBootApplication
@EnableWebMvc
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}

@ControllerAdvice
public class CustomerRequestBodyAdvice extends JsonViewRequestBodyAdvice {
    private static final Logger logger = LoggerFactory.getLogger(CustomerRequestBodyAdvice.class);
    public boolean supports(MethodParameter methodParameter, Type targetType, Class<? extends HttpMessageConverter<?>> converterType) {
        return super.supports(methodParameter,targetType,converterType);
    }

    public HttpInputMessage beforeBodyRead(HttpInputMessage inputMessage, MethodParameter methodParameter, Type targetType, Class<? extends HttpMessageConverter<?>> selectedConverterType) throws IOException {
        logger.info("+++++++++++beforeBodyRead++++++++++++");
        return super.beforeBodyRead(inputMessage,methodParameter,targetType,selectedConverterType);
    }

}

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Also, you  may want  to read [this section of the doc before posting a new thread on SO](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-auto-configuration)
