### ISSUE TITLE
Customize default metric names for actuator

### ISSUE THREAD

**Issue by thinkernalla** [spring-projects/spring-boot#1143]
Hi - I need to customize the metric name for http requests.

I figured that actuator by default uses `var` in the uri `http://example.com/context/{var}/**` and creates `counter.status.200.context.{var}` as the metric name.

However, unfortunately, my {var} names are very request specific and very soon it can flood the inmemoryrepository with millions of counters

ex: my `var` can be `user(id="xxxxxxxx", ctx="xxxxx")`

How can I customize the default metrics counter service to truncate the metric name until the "parenthesis"?

please help, I'm going to production with this in another 2 weeks.

**Comment by trav** [comment]
I too would like to customize the metric names.  

The issue is that my RESTful controller has many methods for a given URL (GET, DELETE, POST), each of which has very different performance characteristics.  It looks like the HTTP method is not taken into consideration in the metric filter, thus the metrics become less useful.

**Comment by snicoll** [comment]
@trav this issue is now closed and it feels like you're asking two unrelated things. Please create separate issue(s). Thanks!
