### ISSUE TITLE
Spring Scheduler not working when used on the Interface method

### ISSUE THREAD

**Issue by bhagathk** [spring-projects/spring-boot#11441]
I am trying to implement a interface method annotated with @scheduled annotation with a cron expression. I am expecting the class that implements the interface and overrides the method should have the scheduler functionality from the interface but that's not the case? Can anyone explain me why? Is there another solution to achieve this functionality?

**Interface:**
```
@Component
public interface TestInterface {

	@Scheduled(cron = "0 0/1 * 1/1 * *")
	public void testScheduler();
}
```
**Implementation Class:**
```
@RestController
public class Controller implements TestInterface {

	@Override
	public void testScheduler() {
		System.out.println("Test Scheduler implemented");	
	}

}
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
