### ISSUE TITLE
Spring AOP: Advice not executing for method with custom annotation

### ISSUE THREAD

**Issue by prashant-chaturvedi** [spring-projects/spring-boot#11496]
I have created a custom annotation:
```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ValidateBeforeBuild {
}
```
And an aspect as:
```
@Aspect
@Component
public class AspectForBuildInBuilders {

    private static final Logger LOGGER = LoggerFactory.getLogger(AspectForBuildInBuilders.class);

    @Before("@annotation(validateBeforeBuild )")
    public void validateBusinessModelAdvice(JoinPoint jp, ValidateBeforeBuild validateBeforeBuild ) throws Throwable {
        LOGGER.info("Executing class: {}", jp);
    }
}
```
I have a class called `PersonBuilder` that implements an interface `IBuilder<T>`. This interface has a single  `build()` that returns the instance of `Person` class. The `build()` in the `PersonBuilder` is marked with the custom annotation `@ValidateBeforeBuild `. When the build method is called from the `ApplicationRunner`, `validateBusinessModelAdvice` is not executed.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
