### ISSUE TITLE
Actuator "http.server.requests" metric has wrong "status" tag for error responses

### ISSUE THREAD

**Issue by i-kaplin** [spring-projects/spring-boot#11514]
Actuator reports a metric with status = 200, but controller actually responds with bad request.

MetricsWebFilter.error(ServerWebExchange exchange, long start, Throwable cause) is called with cause:

org.springframework.web.server.ServerWebInputException: Response status 400 with reason "Type mismatch."; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.util.List'; nested exception is java.lang.NumberFormatException: For input string: "invalidSkuId"

However DefaultWebFluxTagsProvider resolves status tag with 200 because of it gets status from exchange (which is null in this case) and doesn't take exception cause into consideration.

	public static Tag status(ServerWebExchange exchange) {
		HttpStatus status = exchange.getResponse().getStatusCode();
		if (status == null) {
			status = HttpStatus.OK;
		}
		return Tag.of("status", status.toString());
	}

**Actual metric name**
httpServerRequests.exception.ServerWebInputException.method.POST.status.**200**.uri./GoodsService/getActiveGoods.do

**Expected metric name**
httpServerRequests.exception.ServerWebInputException.method.POST.status.**400**.uri./GoodsService/getActiveGoods.do

**Comment by wilkinsona** [comment]
Thanks for the bug report

 IMO, the tag provider is correct in not taking the exception cause into consideration. For it to do so would require it to have knowledge of WebFlux's exception to status mapping logic. Instead, it would be preferable for the tag provider to be called after `ExceptionHandlingWebHandler` has been called and has set the response status on the exchange.  However, I'm not sure that is possible as, currently, `WebHttpHandlerBuilder` decorates `FilteringWebHandler` with `ExceptionHandlerWebHandler` so exception handling is performed after filtering.

@rstoyanchev @sdeleuze Is there a way for us to hook into the web handling pipeline so that we can reliably get the status that will be returned to the client?

**Comment by jkschneider** [comment]
There was a related issue on the servlet side a while back https://github.com/micrometer-metrics/micrometer/pull/264. We wound up having to do this rather [ugly hack](https://github.com/micrometer-metrics/micrometer/commit/a6a667418ff4c5ca205d4c49ab2b3de4338cfae4) because ultimately the servlet container winds up being the thing that sets the response code, well after it leaves Spring Boot's control.

I checked with @adriancole, and we do the same thing in openzipkin/brave.

**Comment by rstoyanchev** [comment]
@wilkinsona the only thing that comes to mind is [decorating the HttpHandler](https://github.com/spring-projects/spring-boot/blob/d3c34ee3d1bfd3db4a98678c524e145ef9bca51c/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/HttpHandlerAutoConfiguration.java#L59) itself to check the response status after all handling is complete. 

Keep in mind though that there is a small number of remaining cases, specifically when `ServerHttpResponse#isCommitted` returns true at the time of exception handling, where the status may yet change to 500 deeper in server adapter code (Servet containers, Undertow) or in the server itself (Reactor Netty). In those cases the `HttpHandler` will be returning an error signal, and you can pretty much assume a 500 response will result.

**Comment by rstoyanchev** [comment]
@jkschneider I had no idea you were using the `HandlerMappingIntrospector`. It seems a little wasteful to do the entire request mapping to get the handler ahead of time. Intuitively it would make sense to start the metrics and fill in the handler later once it's actually been chosen. Have you considered using `WebMvcConfigurer` to install a global interceptor?

**Comment by jkschneider** [comment]
> It seems a little wasteful to do the entire request mapping to get the handler ahead of time

I don't quite understand this. Are you saying that `matchableHandlerMapping.getHandler(request)` is wasteful?

**Comment by rstoyanchev** [comment]
You're essentially performing an extra run of the complete handler matching algorithm -- go through every `HandlerMapping`, checks every `@RequestMapping`, look for static resources, and so on.

**Comment by jkschneider** [comment]
IIRC spring-security and Sleuth are doing much the same. Seems like if this a wasteful operation we would be better served with a cache in `HandlerMappingIntrospector`, if nothing else for subsequent requests to the same URI?

**Comment by jkschneider** [comment]
Also, it is crucial that observability code (metrics/tracing) gets a chance to intercept the request before spring-security which is using a servlet filter. Not sure if the `WebMvcConfigurer`-based interceptors are ordered ahead of all servlet filters.

**Comment by dsyer** [comment]
`WebMvcConfigurer`-based interceptors are (by definition) ordered after all servlet filters (they are applied by a servlet).

**Comment by bclozel** [comment]
I've created [SPR-16693](https://jira.spring.io/browse/SPR-16693) as the right abstraction level for that is a `WebHandlerDecorator`. This issue would ne bow about turning the `MetricsWebFilter` into a `MetricsWebHandlerDecorator` once SPR-16693 is fixed.

**Comment by bclozel** [comment]
Actually, I've fixed this without any change required in the Spring Framework; I might create a new Spring Boot issue to update the `MetricsWebFilter` implementation depending on the outcome of [SPR-16693](https://jira.spring.io/browse/SPR-16693).

**Comment by rstoyanchev** [comment]
@bclozel looks good. One extra case for #77be10e in `doOnError` -- if the response is already committed, then call the error method immediately since `beforeCommit` won't be invoked in that case. The combination of non-error status code + `Throwable` would indicate an error occurred after the response was committed, which in most cases would result in closing the connection, or in some cases (Servlet API before buffer fills up) it may lead to a 500 still.

That makes the resolution pretty completely, and I think we can close SPR-16693 for now. Hooks on `HttpWebHandlerAdapter` would not provide anything more. To go further would require going deeper at the server adapter, or server level.

**Comment by bclozel** [comment]
Thanks @rstoyanchev , I've improved that in b2e7be1.
