### ISSUE TITLE
Ability to define custom Main-Class (Launcher) in spring-boot-gradle-plugin

### ISSUE THREAD

**Issue by dkublik** [spring-projects/spring-boot#11523]
Hi,
I'm trying to use custom JarLauncher for my spring-boot app to play a little with archives loading. This is easy from launcher perspective, as ExecutableArchiveLauncher provides postProcessClassPathArchives(List<Archive> archives).

I cannot however force spring boot gradle plugin to use custom launcher.
There is 
```groovy
bootJar {
    loaderMainClass = 'foo.bar.CustomJarLauncher'
}
```
option in the plugin, but it changes the start class, not the main class in MANIFEST.FM

```
Manifest-Version: 1.0
Start-Class: foo.bar.CustomJarLauncher'
Main-Class: org.springframework.boot.loader.JarLauncher
```
After inspecting the plugin I can't see any way to change the main-class.

Also - namings in the dsl/plugin are a bit vague - it's hard to say when the code / dsl is about Main-Class and when abour Start-Class.

**Comment by dkublik** [comment]
ok,
got it, sorry :)
```
bootJar {
    manifest {
        attributes 'Main-Class': 'tech.viacom.arc.util.ClassesFirstJarLauncher'
    }
}
```

**Comment by wilkinsona** [comment]
You closed the issue while I was writing the below. I'll comment with it anyway as it may provide some useful background.

> option in the plugin, but it changes the start class, not the main class in MANIFEST.FM

You haven't said what version of the plugin you're using, but I can infer that you're using 2.0 from the reference to `bootJar`. In 2.0 M7 (and in earlier versions to my recollection) there's no `loaderMainClass` property on `BootJar`.

```groovy
buildscript {
	repositories {
		maven { url 'https://repo.spring.io/milestone'}
		mavenCentral()
	}
	dependencies {
		classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.0.0.M7'
	}
}

apply plugin: 'org.springframework.boot'
apply plugin: 'java'

bootJar {
	loaderMainClass = 'foo.bar.CustomJarLauncher'
}
```

As expected based on the above, this fails due to an unknown property:

```
> Could not set unknown property 'loaderMainClass' for task ':bootJar' of type org.springframework.boot.gradle.tasks.bundling.BootJar.
```

> Also - namings in the dsl/plugin are a bit vague - it's hard to say when the code / dsl is about Main-Class and when abour Start-Class.

The `mainClassName` property on `BootJar`, `BootWar`, `BootRun`, and `SpringBootExtension` is the name of the main class of the application. The start class isn't exposed anywhere as a property on a task or by the DSL as it's largely intended to be an implementation detail of the archive and launcher mechanism.

By dropping down to manipulating the manifest and its `Main-Class` and `Start-Class` attributes you're working at a different level of abstraction and need to understand that the JVM calls the class pointed to by `Main-Class` and then the launcher, having set up the class loader, starts the application by calling the class pointed to by the `Start-Class` attribute.

You can configure the use of a custom launcher by setting the `Main-Class` attribute of the archive's manifest. The plugin will then continue to set the `Start-Class` attribute to point to the application's main class so that you can reference it in your custom launcher. There are [tests that verify this behaviour](https://github.com/spring-projects/spring-boot/blob/04ae0cd62c5be59b1e5c9a0a4a4fa5e5ad2753e0/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/java/org/springframework/boot/gradle/tasks/bundling/AbstractBootArchiveTests.java#L223-L239) for both jar and war archives.

**Comment by dkublik** [comment]
Right - I'm using 2.0 M7,

Explanation with not exposing it, as working on meta-level makes a lot of sense to me.

Thanks a lot!
