### ISSUE TITLE
Add human readable date for `commit.time` and `build.time`

### ISSUE THREAD

**Issue by Hronom** [spring-projects/spring-boot#11521]
Some times our devs needs human readable version of date for `commit.time` and `build.time` in `/info`.

As far as I understand need to modify `GitInfoContributor` correct?
What the Time Zone of `commit.time` and `build.time`?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
