### ISSUE TITLE
Transaction inside transaction support? (multi database)

### ISSUE THREAD

**Issue by deverlex** [spring-projects/spring-boot#11535]
Hi,
I have DB1, DB2. I config two DataSource and two PlatformTransactionManager for two database (Same physical machine).
I have this code:
```
@Transaction("DB1")
public void A() {
    B();
}

@Transaction("DB2")
public void B() {
}
```
When B() has an Sql exception, data in DB1 did not rollback. How to implement rollback DB1? 
Thank very much.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
