### ISSUE TITLE
Review all data properties

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#11574]
Redis properties are under `spring.redis` currently. This seems to be inconsistent with other stores that have properties under `spring.data` (eg, couchbase, cassandra, neo4j).

**Comment by philwebb** [comment]
For java packages we have a split for some technologies. For example, the `org.springframework.boot.autoconfigure.mongo` package contains no Spring Data bits those are only in `org.springframework.boot.autoconfigure.data.mongo`.

**Comment by snicoll** [comment]
Redis is a different beast in the sense that even the low-level connection stuff relies on Spring Data. In that sense the package is ok (since there _is_ a dependency on Spring Data.

There is no reason however to bring the `data` part in the namespace since those keys aren't related to the Spring Data part. 

I am not saying the situation is perfectly fine (I am sure we can find inconsistencies easily) but this one looks ok to me.

**Comment by philwebb** [comment]
There's a lot of inconsistency with all our data properties. We should expand the scope of this to look at them all.

**Comment by snicoll** [comment]
Note that the package structure also affects the actuator. We don't have any `data` package at all there and a number of support classes are effectively Spring Data specific. The current [health indicator for Cassandra](https://github.com/spring-projects/spring-boot/blob/a6efe77a0c19f935af83abe18cd5171997b881a7/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/cassandra/CassandraHealthIndicator.java#L41) is a good example.
