### ISSUE TITLE
Spring error handler calls getOutputStream twice if writing to http response stream causes an error

### ISSUE THREAD

**Issue by maczikasz** [spring-projects/spring-boot#11580]
Hi,

I have an endpoint that allows users to download files. This endpoint gets its input from an S3 like datasource in an input stream.

I return an InputStreamResource and it will throw a SocketException upon reading.

It only happens from a browser I assume spring error page is not shown to curl.

Repro case:
https://gist.github.com/maczikasz/7f0db2769b3da3c6418642a3eafc2742

Exception:

https://gist.github.com/maczikasz/e84f8f6cea788af54985c77b1258d0fc

The users downloading will get a partialy downloaded file and a http 200, which is I guess normal, I am not sure if it's possible to somehow forcibly break the connection to stop that from happening

**Comment by bclozel** [comment]
Because the exception happens after we've written some content to the HTTP response, the Servlet response might be already committed. At that point, it's impossible for us to change the HTTP status or the response body as they might have been already written to the network.

I see that the white label error view tries to render itself even if the response is already committed, hence the stacktrace you're seeing. This is something we could improve, but it would only remove the current log and possibly add a new one stating that we couldn't change the response (see [this Spring Framework commit](https://github.com/spring-projects/spring-framework/commit/dd0d270ba26e163d41fd2b06e1ea13afe1ca6aac), this is how we deal with this currently with WebFlux).

I'm not sure I understand the part of this issue that you consider a bug. Could you maybe explain what is the behavior you expected?

**Comment by maczikasz** [comment]
From me the thing that I consider a bug is the fact that the Error handler tries to write the error to the already opened and used stream and throws an IllegalStateException, this at least causes some clutter in the logs and it's kindof misleading as to the root cause of the issue.

There was though a bit of ulterior motive to raising this here, but I can move it over to SO, is that I was wondering if there was any kind of error handler where I could forcibly close the connection to the client causing a socket error on the other side, that would be still better than a fully successful response with partial content
