### ISSUE TITLE
resources/profiles/application-*.properties

### ISSUE THREAD

**Issue by petersn-github** [spring-projects/spring-boot#11596]
hi, I have a lot of profiles, I want to put it to `/profiles` folder, I do not want to put it to `classpath:/,classpath:/config/,file:./,file:./config/`, I saw the Class `ConfigFileApplicationListener`, Is there any other way? thanks.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
