### ISSUE TITLE
Passing jvmArgs in  sprint boot m7 with  gradle

### ISSUE THREAD

**Issue by eduardoperez2151** [spring-projects/spring-boot#11628]
I am trying to run a sprint boot 2 m7 application passing properties in this way  gradle -Dspring.config.name=application,database,security,ssl -Dspring.config.location=file:////homeduardo/Documents/workspace-sts-3.9.2.RELEASE/GradleRestTemplate/config/dev bootrun.  But i have not been succsess

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
