### ISSUE TITLE
WebCient doesn't add a content length http header  automatically when post a json body

### ISSUE THREAD

**Issue by lisirrx** [spring-projects/spring-boot#11647]
I'm trying to use the `WebClient` to post some like this:
`WebClient.builder().build().post().uri("http://localhost:7000/")
//                .contentLength(len)
                .contentType(MediaType.APPLICATION_JSON)
                .syncBody(person)
                .retrieve()
                .bodyToMono(String.class);
`
If contentLength is not called, there is no content-length header.

Thanks.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
`WebClient` is also part of the Spring Framwork and not code maintained directly by Spring Boot. Regardless, I think not adding the content-length is by design, but stackoverflow.com is the place to ask.
