### ISSUE TITLE
Add ! after /WEB-INF/classes bring issue when using apache olingo-odata2 with spring-boot

### ISSUE THREAD

**Issue by ljheric** [spring-projects/spring-boot#11664]
I am using olingo-odata2 and spring-boot to build a web application. When I use java -jar command to run the spring-boot application, an error occur prompting that **java.lang.IllegalArgumentException: Illegal jar file path '/Users/abc/git/mmm/service-modules/test/target/myapp.war!/WEB-INF/classes!/com/erc/test/odata/edm'** , I found the root cause is that spring-boot add '!' after /WEB-INF/classes, and olingo-odata2 only support file path which have one '!' inside, please refer to the code **https://github.com/apache/olingo-odata2/blob/master/odata2-annotation-processor/annotation-processor-core/src/main/java/org/apache/olingo/odata2/annotation/processor/core/util/ClassHelper.java**, the exception is located at line 154. 

But when I run my application through eclipse, it works. I am wondering how eclipse launch spring-boot application, maybe there is some difference between launching from java -jar and eclipse. Is there any hint provided? Any help is appreciated! Thank you!

**Comment by wilkinsona** [comment]
This will need to be fixed in olingo-odata2. It's valid for a `jar:` URL to contain multiple `!` characters.

>  maybe there is some difference between launching from java -jar and eclipse

There's a fundamental difference. When you launch the application from Eclipse, the application's classes and its dependencies are available directly on the filesystem. When you run with `java -jar`, they're nested inside the jar file. As a result the URLs are completely different.
