### ISSUE TITLE
/env endpoint showing unexpected values

### ISSUE THREAD

**Issue by Sghazzawi** [spring-projects/spring-boot#11662]
Question

I am using spring boot 1.5.2.RELEASE and using consul to manage environment variables/application properties.  I am seeing the following behavior and was wondering if it was by design and if there was any way to change it.

I start up an application w/ e.g the following properties:
arbitrary.property: foo
datasource.url: some-valid-url

when I hit the /env endpoint I see those values and can verify they are what the application is using.  I then update the properties in consul to this:

arbitrary.property: bar
datasource.url: another-valid-url

when I query the /env endpoint I see both properties updated in the /env endpoint response.
I can verify the arbitrary.property is indeed the "foo" value the app is using.  The app however continues to use the original "some-valid-url" value for it's db connection even though the /env endpoint shows "another-valid-url".

We don't really have a use-case to update datasource's dynamically, but I would like the /env endpoint to always display the value(s) being used.  Is there some way to ensure that the /env endpoint always display this (besides disabling dynamic property/application-context updates)? is this by design?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Sghazzawi** [comment]
Stack Overflow link

https://stackoverflow.com/questions/48345618/spring-boot-env-endpoint-showing-unexpected-values
