### ISSUE TITLE
Embedded launch script does not pick up the JVM of the user

### ISSUE THREAD

**Issue by vforchi** [spring-projects/spring-boot#11675]
I am trying to deploy a Spring Boot 2 application using the procedure described in the [documentation](https://docs.spring.io/spring-boot/docs/2.0.0.M7/reference/htmlsingle/#deployment-initd-service).

When executed by root, the script executes the application as the user owning the jar file, but it identifies the JVM before dropping to the unprivileged user.

The problem is that, if I start the service as the unprivileged user, the script picks up the JAVA_HOME of the user, which means that the application can run with different JVMs depending on how it is started.

Is this intentional? Or should the script use the JVM that the unprivileged user would use based on its environment?

**Comment by wilkinsona** [comment]
It is intentional. The script verifies the presence of the `java` binary (possibly via `JAVA_HOME`) before passing its path to `start-stop-daemon` and asking it to run the binary as the required user.

If you don't want the environment of the user that runs the script to influence that `java` binary that's used, I would recommend setting `JAVA_HOME` in a `.conf` file that sits alongside your application.

**Comment by vforchi** [comment]
Thanks for the answer, I would maybe make it clearer in the documentation.

**Comment by wilkinsona** [comment]
A pull request would be welcome.
