### ISSUE TITLE
Spring @Scheduled stops running when system time set back

### ISSUE THREAD

**Issue by heikehuan** [spring-projects/spring-boot#11689]
I have Spring Boot based cron job running:
```
@Scheduled(cron = "30 * * * * *}")
public void cronCheck()
{
    logger.debug("now is {}", DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").format(LocalDateTime.now()));
}
```
Most of the cases, it's running perfect. But when I changed the system time back , for example one month, it would run one single time and never run again. However, if I change system back forward, it would run as scheduled. Anyone has any idea why this is happening and maybe a solution? Highly appreciate it!

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
