### ISSUE TITLE
JettyEmbeddedServletContainerFactory implements ResourceLoaderAware but does not use it to resolve resources

### ISSUE THREAD

**Issue by aaronjwhiteside** [spring-projects/spring-boot#11682]
Spring Boot: 1.5.9

`JettyEmbeddedServletContainerFactory` implements `ResourceLoaderAware` but does not use it to resolve resources. The same is true of all classes that extend `AbstractEmbeddedServletContainerFactory`.

`JettyEmbeddedServletContainerFactory.configureSslKeyStore`
`JettyEmbeddedServletContainerFactory.configureSslTrustStore`

use `ResourceUtils.getURL()` when they could/should be using `resourceLoader.getResource()` instead.

This would allow loading of key and trust stores via custom `ProtocolResolver`'s, like those that exist in Spring Cloud Config: `s3://`, `gs://` etc.

**Comment by wilkinsona** [comment]
Unfortunately, this isn't as simple as it may appear.

In the case of Jetty, the key thing is that we aren't dealing with a `org.springframework.core.io.Resource` but with a `org.eclipse.jetty.util.resource.Resource`. To be able to use the `ResourceLoader` we'd need to implement an adapter class that turns a Spring Framework `Resource` into a Jetty `Resource`.

Undertow could be made to work as you suggest as it's directly configured with a `KeyStore` rather than being configured with something from which the store can be read.

Tomcat can't be made to work as you suggest as all we can pass it is a `String` which it then, IIRC, turns into a URL and reads its input stream.

We aim for a consistent experience across all three containers so, rather than us making things work as you've suggested for Undertow and possibly Jetty but not for Tomcat, you should use an `org.springframework.boot.context.embedded.SslStoreProvider` instead.

**Comment by aaronjwhiteside** [comment]
I think we might be talking about different things.

`JettyEmbeddedServletContainerFactory::configureDocumentRoot()` calls `JettyEmbeddedServletContainerFactory::createResource()` which deals with `org.eclipse.jetty.util.resource.Resource`'s for the purpose of setting the document root when configuring the web app context in `configureWebAppContext()`.

This is independent of how Spring Boot resolves resources, currently in `JettyEmbeddedServletContainerFactory.configureSslKeyStore` and `JettyEmbeddedServletContainerFactory.configureSslTrustStore` it uses `org.springframework.util.ResourceUtils` which is an old school way to resolve `URI`'s to `File`'s, it's even mentioned in the Javadoc for `ResourceUtils` that one should probably use the `ResourceLoader` abstraction instead.

Quote:
>  * <p>Consider using Spring's Resource abstraction in the core package
> * for handling all kinds of file resources in a uniform manner.
> * {@link org.springframework.core.io.ResourceLoader}'s {@code getResource()}
> * method can resolve any location to a {@link org.springframework.core.io.Resource}
> * object, which in turn allows one to obtain a {@code java.io.File} in the
> * file system through its {@code getFile()} method.

I think it would make sense to have a uniformed handling of resource loading for internal spring things (key/trust stores is a good example in this case), instead of some bits of the code base using `ResourceUtils` and others using `ResourceLoader`.

Thanks for pointing out the `SslStoreProvider`, I think I can use that as a work around.
