### ISSUE TITLE
Provide convenience methods for Headers in RestTemplateBuilder

### ISSUE THREAD

**Issue by chtinnes** [spring-projects/spring-boot#11708]
Currently, it is kind of cumbersome to add Headers to the `RestTemplate` The could be provided in an `HttpEntity `wrapping the content of the Request or one can use a `ClientHttpRequestInterceptor`. 
Only for Basic Authentication, there is a convenience method.
As for the Basic Authentication, there should be at least convenience methods for the "Accept" and "Content-Type" headers.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I’m not sure that having convenience methods for `Accept` and `Content-Type` makes sense. Any configuration on the builder would apply to every request sent by the template that it builds. That works well for authentication where you are unlikely to want to change credentials between requests. I don’t think it works so well for `Accept` and `Content-Type` headers that are more likely to vary from request to request.

How had you imagined this might work?

**Comment by chtinnes** [comment]
Well, my idea would be provide respective implementations of `ClientHttpRequestInterceptor` for this and to add them by using e.g. `additionalInterceptors(new ContentTypeJsonRequestInterceptor())`. So the convenience method would just call `additionalInterceptors` and add the respective Interceptors.

You are right in that there are REST-Services that change the Content-Type but I am feeling like most of the services using fixed `Content-Type`, e.g. `application/json`. My argument would be that it is just a convenience method. One does not need to set the type but on has the possibility to do it in a convenient manner. Just for setting `Content-Type` to have a wrapper or self implement the `ClientHttpRequestInterceptor` is quite a hassle. If not in the Builder, then there should be convenience methods in the `RestTemplate`.  What to you think? Or is there already a way to set these headers in a convenient way that I don't know at the moment?

>

**Comment by philwebb** [comment]
I think the easiest way at the moment is to do something like this:

```java
RequestEntity<Void> request = RequestEntity.post(url)
		.accept(MediaType.APPLICATION_JSON).header("foo", "bar").build();
restTemplate.exchange(request, String.class);
```

I'm inclined to agree with @wilkinsona that adding extra convince methods might not as useful as the current `basicAuthorization` method. That one is quite common, and when it was added was super painful to code yourself (it's now easier since Spring 4.3.1 added the `BasicAuthorizationInterceptor` class).

We need to balance the convenience of any new convenience methods against the complexity of having too many ways to do the same thing. Since it's relatively easy to plug in a `RestTemplateCustomizer` for any application that want this behavior, I think we shouldn't add these.

Thanks anyway for the suggestion, and we'll happily reconsider if there's a really strong use-case that we're missing, or if more people tell us they'd be useful.
