### ISSUE TITLE
Only generate cache meta-data for endpoints with operations

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11703]
See #10257

> The caching feature would feel awkward: we provide a cache property automatically but it has no effect. That could be fixed by moving the cache configuration at management.endpoints.cache like we did for web path customization. The annotation processor would only generate an enabled flag and we should not be able to add any extra property to that namespace then. We need to figure out if we are ready to pay that price.

**Comment by snicoll** [comment]
Looking for options there.  The current setup is kind of  flawed already as we only cache `@ReadOperation` without parameters at the moment (there is no concept of "cache key"). We don't evict on write and/or read.  So perhaps one way around it would be to simplify the current solution rather than implying it is a full cache solution. It may very well be a different problem that we can fix  using documentation though.

My preferred option would be to detect `@ControllerEndpoint` and, in the presence of that annotation, not generate the property. If we did this, I think `@RestControllerEndpoint` and `@ControllerEndpoint` should look alike (why isn't the former meta-annotated with the latter?). If we go further with this "special endpoint approach", i.e. flagging a servlet as a specific endpoint, we'd need some kind of signal to let the AP knows what it has to do.

**Comment by snicoll** [comment]
> We could even get the cache advisor to back off if the user doesn't want to support caching for one specific endpoint.

This  turned out to be significantly hard to do unless I am missing something. The `OperationInvokerAdvisor` is applied when the operation itself is created. At that point, all we have at our disposal is the `id` of the endpoint. There are no endpoints yet. We do have an internal `EndpointBean` that we could carry around rather than the endpoint but it makes testing harder and we need some high-level public concept for what the `Endpoint`  annotation represents. That would be `ExposableEndpoint` except we are in the process of creating the operations and that very instance so we can't do that. IMO we have two choices:

1. We change the AP to detect operations on the target model (that's basically reading `ExecutableElement` and checking for the presence of `[Read|Write|Delete]Operation`.
2. We create a marker annotation that indicates the endpoint has no operation. It doesn't have to be named like but something like "Custom endpoint, no operations here". The AP can read that as a signal that caching is useless since there are no operations.

**Comment by snicoll** [comment]
@wilkinsona and I brainstormed and I am using a different approach. Our cache strategy is working for the main read operation (that is a `@ReadOperation`) that doesn't use any specific argument. Detecting that is easy enough so I've implemented it pretty easily but, unfortunately, the `@Nullable` support makes it so that such operation can be disguised, i.e.

```
@ReadOperation
public Env env(@Nullable String pattern) { ... }
```

If this method is invoked without a pattern, it is matching our target for the cache. That makes the job of discovering  the main read operation a bit harder (but still doable). Howerver, caching doesn't work at all at the moment so we should address that.
