### ISSUE TITLE
how to use slf4j 1.5x wih spring boot

### ISSUE THREAD

**Issue by hwck** [spring-projects/spring-boot#11713]
i use spring boot 1.5.9  with slf4j 1.5x has error
how to use slf4j 1.5x with spring boot

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
