### ISSUE TITLE
Schema generation properties not well documented

### ISSUE THREAD

**Issue by ghost** [spring-projects/spring-boot#11721]
Unfortunately my previous issue #11678 was closed as duplicate, though I don't think it is one.

In the issue I argued that the documentation is not entirely clear on which of several similar properties have precedence.

The referenced issue suggest other default values of certain properties in some contexts.

I would be glad if the documentation could be improved.

**Comment by snicoll** [comment]
@FelixRiemann you were referring to several issues into one and the problem of not enabling `create-drop` with Flyway/Liquibase has been  addressed already (which means you don't have to set that `ddl.auto` either.

As for the documentation, it is not  clear what you're asking really. So please clarify and we can see what can be improved in the documentation.

In the future, please comment on the issue rather than creating another one. We can always refine and  reopen.

**Comment by FelixRiemann** [comment]
There are four properties I am interested in:
* (1) `spring.jpa.generate-ddl` (boolean)
* (2) `spring.jpa.properties.javax.persistence.schema-generation.database.action` (one of `none`, `drop`, `create`, `drop-and-create`)
* (3) `spring.jpa.hibernate.ddl-auto` (one of `none`, `validate`, `update`, `create`, `create-drop`)
* (4) `spring.datasource.initialize` (boolean)

From the documentation, the following is unclear to me:
1. Both (1) and (2) exist to enable/disable schema generation. I would like to know which of both has precedence.
1. Property (4) governs whether the schema should be generated from DML scripts. What happens if this is enabled together with one of (1) or (2)?
1. Then there is (3), which is similar to (2). What happens if they contradict each other?
1. What happens if (1) and (3) contradict each other (and here by *contradict* I mean any combination other than (none, none) and (true, create))?
1. If I do not set (3) specifically, will its default value override (1)? In Spring Boot 1.5.9 this is the case, as I pointed out in #11678. But even if the default value of (3) will be `none` when Flyway/Liquibase is detected, as suggested in #9262, the question remains whether (3) overrides (1) if I do not use (3).

> In the future, please comment on a declined issue rather than creating another one. We can always refine and reopen.

Will keep that in mind.

**Comment by matthiasstock** [comment]
Even if the questions are interesting, different approaches of schema creation are unnecessarily mixed here. A documentation of their correlation would be confusing and sometimes beyond the control of Spring Boot itself:

> Both (1) and (2) exist to enable/disable schema generation. I would like to know which of both has precedence.

`spring.jpa.generate-ddl` applies properties to the JPA implementation directly, i.e. `hibernate.hbm2ddl.auto` [becomes "update"](https://github.com/spring-projects/spring-framework/blob/95a56cd28dd2feb78d1f5d670a8e5f9a118a41e4/spring-orm/src/main/java/org/springframework/orm/jpa/vendor/HibernateJpaVendorAdapter.java#L149) when `spring.jpa.generate-ddl` is true. Later, JPA 2.1 [schema creation properties](https://javaee.github.io/tutorial/persistence-intro006.html) are evaluated by Hibernate and `javax.persistence.schema-generation.database.action` [takes precedence](https://github.com/hibernate/hibernate-orm/blob/5.3.7/hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java#L487) over `hibernate.hbm2ddl.auto` unless it is unset or set to `none`.

Therefore, I referenced a commit that adds general notes to the documentation.

**Comment by wilkinsona** [comment]
Superseded by #15859.
