### ISSUE TITLE
How to add spring4 in spring-boot-sample-jersey?

### ISSUE THREAD

**Issue by losthua** [spring-projects/spring-boot#11748]
Currently, in spring-boot-sample-jersey, jersey does not support spring4, and spring4 support is required in the use of tk_mybatis generics.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
