### ISSUE TITLE
Review reference documentation on enabling and exposing endpoints

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11755]
I think it's a bit out of date. For example, I don't think the following properties are used any more:

- `management.endpoints.jmx.enabled`
- `management.endpoints.web.enabled`

They've been replaced by `management.endpoints.*.expose` and `management.endpoints.*.exclude`.

The web one is only mentioned in the appendix.

There's a [small section](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-disable-jmx-endpoints) for the JMX one. I think the equivalent would now be `management.endpoints.jmx.exclude=*`.

**Comment by wilkinsona** [comment]
It'd be good to provide an example in the migration guide that shows some 1.5.x configuration and the equivalent in 2.0.

**Comment by snicoll** [comment]
`management.endpoints.web.enabled` is still used in `WebEndpointAutoConfiguration`. I think that's the naming of those properties is weird so I am with you we should probably remove them.

**Comment by mbhave** [comment]
@olivergierke suggested explicitly mentioning which endpoints are available by default in [this section](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints) so that users who don't read further aren't left wondering why most actuators don't appear as per the mappings.

**Comment by wilkinsona** [comment]
I inadvertently removed a paragraph. Thanks to @olivergierke for spotting my mistake.
