### ISSUE TITLE
How to find out the total number of connections to an ActiveMQ broker by JMS?

### ISSUE THREAD

**Issue by lynings** [spring-projects/spring-boot#11765]
# Question
I need to know which IoT devices are online or offline, and these devices are already connected to activemq.
My idea: find out all connected to the activemq connection broker, and then get the connection information, such as: ip, clientId, etc., and finally determine which devices are not online.
**Is there any way to use JMS?**
Thank you!!!

**Comment by wilkinsona** [comment]
- [ ] 
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bugs .

**Comment by lynings** [comment]
@wilkinsona Thank you for your advice .
