### ISSUE TITLE
DefaultUriBuilderFactory does not expand correctly

### ISSUE THREAD

**Issue by sachinlad** [spring-projects/spring-boot#11781]
It looks like with Spring Boot 2.0 (M7), DefaultUriBuilderFactory does not expand correctly if uriTemplate contains "protocol + hostname" as templated. This UriBuilder is used in RestTemplate to expand the templatedUris. Such templatedUri works well with Spring 1.5.x.

Looks like DefaultUriBuilderFactory is newly introduced in Spring-Boot 2.x so may be this is not bug but the functionality has changed? But this breaks bunch of test code so I am considering this as regression. 

Here is the unit test to reproduce it -

```
@Test
    public void testUrlBuilder() throws URISyntaxException {
        String uriTemplate = "{baseUrl}/info";
        String[] vars = new String[]{"http://localhost:8085"};

        DefaultUriBuilderFactory factory = new DefaultUriBuilderFactory();

        URI uri = factory.expand(uriTemplate, vars);

        assertEquals(new URI("http://localhost:8085/info"), uri);
    }
```

**Comment by philwebb** [comment]
I think that might be intentional but the class is actually [part of Spring Framework](https://github.com/spring-projects/spring-framework/blob/13c735442cc126ba2cc2c8b7518f6246afffc6b3/spring-web/src/main/java/org/springframework/web/util/DefaultUriBuilderFactory.java). You might want to raise an issue on their [JIRA](https://jira.spring.io/browse/SPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).

**Comment by sachinlad** [comment]
Duh! I forgot to check that. Thanks I will post it there.
