### ISSUE TITLE
bootJar/bootWar Gradle tasks in Boot 2

### ISSUE THREAD

**Issue by edeandrea** [spring-projects/spring-boot#11791]
This is in relation to #8824 (https://github.com/spring-projects/spring-boot/issues/8824#issuecomment-298327642) where @dorongold commented about the `artifactoryPublish` task failing due to the new `bootJar`/`bootWar` tasks. I didn't want to add on to a closed thread so I thought I would open a new thread.

Like @dorongold states in his comment he is applying the `artifactory-publish` plugin which is configured to look for the `jar`/`war` task as an artifact to publish (under the hood this facility uses the `maven-publish` plugin and configures publications as `MavenPublication`s).

What we do here in our organization (very large organization with hundreds of development teams & thousands of developers) is we have a customized distribution of Gradle that is distributed amongst all of our teams. All common build logic is pre-packaged as a set of plugins that mirror Gradle's out-of-the-box plugins but also adds additional capabilities/configuration. Publishing built artifacts to Artifactory is one of those concerns.

As it stands now these global plugins don't know/understand anything about the kinds of projects its building (a Java project is a Java project) and it creates/configures different publications whether you are applying the `java`, `war`, or `ear` plugins. The artifact it uses in those publications are the outputs of the standard Gradle `jar`/`war`/`ear` tasks.

We've found now that teams internally are starting to experiment with Boot 2.x that their projects are no longer publishing their artifacts during their CI pipeline & as @dorongold states the `artifactoryPublish` task is failing due to the `jar`/`war` task being disabled.

So in order to fix this we now have to build something into our generic `java`/`war` plugins which knows specifically about specific spring boot versions, whether its there, and performs custom logic. Something about it just "feels" wrong to me. We can't be putting this kind of responsibility into each & every project in an organization of our size.

We could build a separate plugin outside of our custom distro that would fix this only for Boot 2.x users, but then we have all the headaches of managing/versioning/distributing that plugin, educating our users about it, and getting them to use it. The whole point of our custom distro is to eliminate the need to know about any of these generic concerns on a per-project basis. The majority of our app teams build files is simply apply a few plugins and declare dependencies. Everything else is taken care of for them by the internal plugins shipped with the distro.

I'm not sure this post is going to change how you've already built things in the boot 2.0 plugins as I totally understand I'm getting to this pretty late in the game. I just wanted to bring this to your attention and also ask for advice as to what the best approach for getting around this is, as we're going to have to do something and we're not going to leave it up to each individual development team to solve.

Thanks in advance!

**Comment by wilkinsona** [comment]
Thanks for the detailed description of the problem. I'm not opposed to making changes, but I'm not sure what they would be. Also, as you've noted, it's rather late in the game for 2.0 (RC1 is early next week).

It's clear from your description that the plugin's current behaviour is creating a problem for you. It's not completely clear, to me at least, what you'd like it to do instead. It sounds like your plugin infrastructure would like the jar task to be enabled so that its output can be published. Unfortunately, I don't think that makes sense in a Spring Boot application. The `jar` task only contains the application's own classes and none of its dependencies, i.e. it's not a fat jar. This is analogous to the `jar` task in a `war` project which is rarely used although it's still there if you want to use it. What does make sense, IMO, is to publish the output of the `bootJar` task just as it makes sense to publish the output of the `war` task.

I think you may need to bite the bullet and give special treatment to a Spring Boot project just as you already give special treatment to a war project.

**Comment by edeandrea** [comment]
Thanks @wilkinsona for the quick response.

My thoughts as to how to handle this are in-line with what you mention. If we were to do that how would it be best to detect the fact that this is a Spring Boot 2 app? Would it be simply to detect the presence of a `bootJar`/`bootWar` task that is enabled?

Inside our global plugin suite we are already creating the `MavenPublication` inside of an `afterEvaluate` block, so detecting presence of tasks should be pretty easy. Something like this is what I'm thinking. Would this be a good approach in your opinion?

(inside our custom java plugin - war plugin would look similar):

```groovy
project.afterEvaluate { proj ->
  def bootJarTask = proj.tasks.findByName 'bootJar'
  def jarTask = bootJarTask?.enabled ? bootJarTask : proj.tasks['jar']

  proj.configure(proj.publishing) {
    publications {
      mainJava(MavenPublication) {
        artifact jarTask
      }
    }
  }
}
```

**Comment by wilkinsona** [comment]
Yes, that looks like a reasonable approach to me. If you wanted to cope with more sophisticated projects with multiple `BootJar` tasks, you could also find the tasks by type but if you just care about the default `BootJar` task it'll always be called `bootJar` and what you've proposed above should be sufficient.

It sounds like nothing's going to change in Spring Boot as a result of this issue so I'm going to close it. Feel free to comment further, though. If it turns out that some changes are warranted we can re-open it.

**Comment by edeandrea** [comment]
Thank you @wilkinsona for the help/advice.
