### ISSUE TITLE
@Scheduled

### ISSUE THREAD

**Issue by RedCollarPanda** [spring-projects/spring-boot#11824]
Good day! I have a question, asked on 

https://stackoverflow.com/questions/48467709/spring-scheduled-leak

For several days - no answer. I guess no one knows what to do with it.
Can you help?

In short - after enabling @Scheduled and ./startup.sh  /   ./shutdown.sh I have a warning of a memory leak. Leak is about 600 Mb.

If you need - I can provide simple demo project.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by wilkinsona** [comment]
@RedCollarPanda If you have a sample project, please add it to your question on Stack Overflow. It'll make it much easier for someone who may be able to answer your question to see exactly what you've done.

**Comment by RedCollarPanda** [comment]
Sorry for long w8ing - here is a repo. Also updated my stackoverflow question.

https://github.com/RedCollarPanda/spring-sheduled-bug-test

**Comment by RedCollarPanda** [comment]
Good day! Any news ?
