### ISSUE TITLE
DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS not working

### ISSUE THREAD

**Issue by ashishb888** [spring-projects/spring-boot#11842]
<pre> 
@Bean
public Jackson2ObjectMapperBuilder jacksonBuilder() {
        Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
        builder.indentOutput(true);
        builder.featuresToEnable(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS);
        return builder;
}
</pre>
AND/OR
<pre>
spring.jackson.deserialization.USE_BIG_DECIMAL_FOR_FLOATS: true
</pre>
I have written above code to use USE_BIG_DECIMAL_FOR_FLOATS to preserve trailing zeros. But unfortunately it did not work. Then I used below for a specific method (locally), it worked
<pre>
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.configure(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS, true);
result = objectMapper.readValue("someString", Klass.class);
</pre>

Please help me to sort out this.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
