### ISSUE TITLE
ElasticSearch Springboot NativeSearchQueryBuilder issue 

### ISSUE THREAD

**Issue by monarchpedo** [spring-projects/spring-boot#11851]
Question
I am not getting any function call as mentioned below in all website for calling NativeSearchQueryBuilder() as follows 
   SearchQuery searchQuery = new NativeSearchQueryBuilder()
  .withQuery(matchQuery("title", "spring date elasticsearch")
  .operator(AND)
  .fuzziness(Fuzziness.ONE)
  .prefixLength(3))
  .build();

When i start calling NativeSearchQueryBuilder().withQuery(matchQuery()),  matchQuery does not come. MatchQuery, MatchQueryBuilder all these are coming instead of it. So can you please tell me how can create fuzzy search with NativeSearchQueryBuilder().

SpringBoot version - 1.5.4
spring-boot-starter-data-elasticsearch - 1.5.4.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
