### ISSUE TITLE
Transaction lost between multiple transactionManager

### ISSUE THREAD

**Issue by jkeruzec** [spring-projects/spring-boot#11862]
Dear all,

I have a problem with Spring-Boot-starter version 1.5.9-RELEASE
I declare multiple transaction manager with different CrudRepository and services.
Then I declare @Transactionnal method with this order : 

First Main transaction
```
Transactional(value = "innolaTransactionManager", readOnly = false, propagation = Propagation.REQUIRED)
 public void integrateLdFilesData() {
```

Then call this method in it : 

```
// Create transaction   
   DmTransaction transaction = transactionService.processTransaction(jacket.getTransactionNumber());
```

Then we enter a new method :

```
@Transactional(readOnly = false, propagation = Propagation.REQUIRED, transactionManager = "dcToolTransactionManager")
 public DmTransaction processTransaction(String transactionNumber) {
  Transaction t = this.transactionRepository.findTransactionBytransactionNumber(transactionNumber);
  return this.createTransaction(t);
 }
```

Then I want to have a requires_new propagation but here my transaction will never commit at the end of this method

```
@Override
 @Transactional(readOnly = false, propagation = Propagation.REQUIRES_NEW, transactionManager = "innolaTransactionManager")
 public DmTransaction createTransaction(Transaction transaction) {
(...)
dmTransaction = dmTransactionRepository.save(dmTransaction);
  // Create objects in database
  return dmTransaction;
```

We debug this situation with log on jpa orm. 

The only solution we came up with was to directly make change method processTransaction  with requires_new after integrateLdFilesData method and delete third method createTransaction.

I think because we are using 2 transactionManager Spring lost transaction lifecycle somehow and don't commit even if we put a requires_new.

What do you think about that ?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
