### ISSUE TITLE
TestRestTemplate constructor with RestTemplate param should not change error handler

### ISSUE THREAD

**Issue by jeffjensen** [spring-projects/spring-boot#11872]
Using Spring Boot 2.0 M7.

Similar to https://github.com/spring-projects/spring-boot/issues/7441 , the main `TestRestTemplate` constructor replaces the `RestTemplate`'s configured error handler with `NoOpResponseErrorHandler` (constructor signature is `TestRestTemplate(RestTemplate restTemplate, String username, String password, HttpClientOption... httpClientOptions)`)

`RestTemplate` is a parameter and therefore the constructor should respect its configuration and not change it.

The other `TestRestTemplate` constructors internally instantiate a `RestTemplate` so can replace the default error handler without issue.

**Comment by bclozel** [comment]
I've got a commit ready for that change but I've also changed my mind about this. I don't think we should make this change anymore and we should probably reconsider several constructors in this class.

`TestRestTemplate` is documented as "fault tolerant" (meaning the default response error handler is replaced with a no-op one) and provides several testing features on top of the Apache client.

Applying the suggested change means that the resulting `TestRestTemplate` is not fault tolerant anymore. Also, we could argue for the same reason (re: constructor parameter contract, not mutating the given `RestTemplate`) that we should:
* not apply `HttpClientOption` (because it replaces the underlying factory)
* nor apply authentication (because it replaces any existing `BasicAuthorizationInterceptor`).

So I'd be in favor of leaving this behavior as it is.
Also, we could remove all constructors accepting `RestTemplate` arguments, as they don't really make sense here and only keep the ones using `RestTemplateBuilder`.

If this class should not mutate the given `RestTemplate`, then developers should not use `TestRestTemplate` but rather use `RestTemplate` directly. But I can see the confusion given the existing contracts. 

Marking this as team-attention to discuss that.

**Comment by wilkinsona** [comment]
Good points, @bclozel. Having read your analysis, I'm now wondering what behaviour @jeffjensen expected when passing an existing `RestTemplate` into `TestRestTemplate`.

@jeffjensen, if you didn't expect the passed-in `RestTempplate` to be mutated, what behaviour did you expect? What were you hoping to gain by creating a `TestRestTemplate` from your existing `RestTemplate`?

My feeling at the moment is that we should drop both of the constructors that take a `RestTemplate`:

- `org.springframework.boot.test.web.client.TestRestTemplate.TestRestTemplate(RestTemplate)`
- `org.springframework.boot.test.web.client.TestRestTemplate.TestRestTemplate(RestTemplate, String, String, HttpClientOption...)`

**Comment by jeffjensen** [comment]
We have a `RestTemplate` correctly configured for the app and want to use the other benefits of `TestRestTemplate` in tests.

I expect mutation methods, such as `addAuthentication`, to change it, but not a constructor.  If `RestTemplate` was immutable, the constructor couldn't alter it.

With accepting only `RestTemplateBuilder` instances, will it set objects on the builder only when null or the default, or always?  We need ability to specify something and not have it replaced (an unexpected replacement consumes time determining why something isn't working).  Since `RestTemplate` is mutable, a current workaround is to set it again afterwards.

**Comment by wilkinsona** [comment]
Thanks.

> We have a RestTemplate correctly configured for the app and want to use the other benefits of TestRestTemplate in tests.

Those benefits cannot be obtained without mutating the `RestTemplate`. I think this adds further weight to Brian's argument that the constructors that take a `RestTemplate` should be removed.

> With accepting only RestTemplateBuilder instances, will it set objects on the builder only when null or the default, or always?

`RestTemplateBuilder` is immutable. Any time a mutating method is called, a new builder instance is created and returned.
