### ISSUE TITLE
Test fail: StringToInetAddressConverterTests relies on NSLookup

### ISSUE THREAD

**Issue by eiselems** [spring-projects/spring-boot#11897]
Bug Report
Got a Test fail when building the current master.

StringToInetAddressConverterTests fails on my machine because it relies on the local nslookup.
The test assumes that the host `ireallydontexist.example.com` is not known and therefore does throw an exception in `InetAddress.getByName(source);`.

Sadly my ISP's has a strange default error page for DNS lookup errors and therefore that host does exist for me => I got a test fail.

Last screenshot is of a watch of the command which should throw that exception instead of returning the shown object.

<img width="299" alt="bildschirmfoto 2018-02-03 um 21 49 15" src="https://user-images.githubusercontent.com/5188694/35771363-e4f845d2-092b-11e8-93f9-dfd1a050c777.png">

<img width="884" alt="bildschirmfoto 2018-02-03 um 21 53 34" src="https://user-images.githubusercontent.com/5188694/35771403-8068ee0e-092c-11e8-8a6a-aef6c8c3f773.png">

Switching off my internet or changing the DNS to e.g. 8.8.8.8 does solve that issue.

Not sure if this is a real bug per se, just wanted to point it out.
Would have liked to update it myself but I am a bit clueless since InetAddress is a system class and until now I know no possibility to update the nslookup from java directly for a specific hostname.

Any ideas / suggestions?

**Comment by philwebb** [comment]
I'm not sure there's much we should do for this. ISP's that replace default error pages are really annoying. It might be worth making google your permanent DNS.

**Comment by eiselems** [comment]
Also something I can live with 😉
Thanks for taking your time.

**Comment by neilstevenson** [comment]
You shouldn't need to change your set-up (DNS provider) to make the build succeed.

However, the wider point here is when the Spring Boot application is deployed, the DNS provider there is not under your control. The `ConversionService` string to InetAddress call may or may not throw an error.

So the test is expecting only one of two possible behaviours, which makes it an invalid test.

**Comment by philwebb** [comment]
@neilstevenson As Spring Boot 2.0 the test is in `InetAddressFormatterTests`. The test in question is:

```java
@Test
public void convertFromStringToInetAddressWhenHostDoesNotExistShouldThrowException() {
	this.thrown.expect(ConversionFailedException.class);
	this.conversionService.convert("ireallydontexist.example.com", InetAddress.class);
}
```

What we're really testing here is if `InetAddress.getByName(text)` throws an exception, we should get a `ConversionFailedException`. I can't really think of a consistent way to get `InetAddress.getByName(text)` to always throw an exception. It's not even that easy to mock because it's a static method of a JVM class. I guess we could add another layer of indirection, but that seems like a lot of effort when most DNS resolvers don't return a default error page. 

In terms of the converter behavior, I don't see what else we can do. If you have a DNS provider that returns an IP for a host that doesn't usually resolve, then how do we detect that?

**Comment by neilstevenson** [comment]
@philwebb Personally, I'd remove the test since it makes the build unreliable.

In terms of detection, that's tricky. Best I could think of would be to test two domains that shouldn't exist. Then you should get two exceptions or the same IP both times (the handler page)

**Comment by philwebb** [comment]
Removing it doesn't seem wise, but we could add an assume to ensure resolve will fail.

**Comment by eiselems** [comment]
Love the title of the commit message 😊
Well done
