### ISSUE TITLE
How the custom endpoint is compatible with spring boot 1.5.9 and spring boot 2.0

### ISSUE THREAD

**Issue by cvictory** [spring-projects/spring-boot#11907]
We create some spring boot starters and also create some custom endpoint base on spring boot 1.5.9.RELEASE AND 1.4.7.RELEASE.

But now , spring boot 2.0 GA will be released in the future, so we must also support spring boot 2. But in spring boot 2, the endpoint infrastructure is so different with that in the preview version.

I have two ways to overcome this issue:

1. Use two branchs. One is master for spring boot 1.5.9.RELEASE, the other one is for spring boot 2.

2. We must divide the starter into two project, the one aims to support spring boot 1.5.9, the another project aims to support spring boot2. And in this two project, we must use some @Conditonal to make some configuration disabled.

Any one can give me some suggestion? or you have more effective solution.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by cvictory** [comment]
ok
