### ISSUE TITLE
can not get parameter name?

### ISSUE THREAD

**Issue by iPhotoner** [spring-projects/spring-boot#11919]
request.getParameterNames() can not get value:
i using spirng boot 2.0.0.RC1,and springmvc 5.0.2.RELEASE,
i can get parameter name enumeration via traditional way:
http://ip:port/contextPath/user/updateUser?userName=spring&age=18
but null if using such as @PutMapping,transfer json data to backend(Postman),return null?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
