### ISSUE TITLE
looks like MatrixVariable is broken between 2.0.0 M7 and RC1

### ISSUE THREAD

**Issue by rhehl** [spring-projects/spring-boot#11911]
Since upgrading from M7 to RC1 it's not possible to access urls with matrix values.

Example:

I try to access http://localhost:8080/service/xyz/invoices;interval=2015-06-01_2015-07-01

and my `RequestMapping` looks like this:

```java
@RequestMapping(value = "/service/xyz/invoices{matrix}", method = RequestMethod.GET)
    public ResponseEntity<?> getInvoiceOverview(@MatrixVariable(value="interval", pathVar="matrix") String interval,
                                                HttpServletRequest request) { ....
```

Since RC1 i have to remove the semicolon (http://localhost:8080/service/xyz/invoicesinterval=2015-06-01_2015-07-01) and it works.

**Comment by wilkinsona** [comment]
I can't reproduce the behaviour that you've described. Both URLs work for me:

```
$: curl -i 'localhost:8080/service/xyz/invoices;interval=abc'
HTTP/1.1 200
Content-Length: 0
Date: Mon, 05 Feb 2018 17:00:52 GMT

$: curl -i 'localhost:8080/service/xyz/invoicesinterval=abc'
HTTP/1.1 200
Content-Length: 0
Date: Mon, 05 Feb 2018 17:00:55 GMT
```

I can reproduce a 400 response if I don't quote the URL properly in my shell:

```
$: curl -i localhost:8080/service/xyz/invoices;interval=abc
HTTP/1.1 400
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Mon, 05 Feb 2018 17:01:44 GMT
Connection: close

{"timestamp":1517850104801,"status":400,"error":"Bad Request","message":"Missing matrix variable 'interval' for method parameter of type String","path":"/service/xyz/invoices"}
```

Can you please provide a minimal sample that reproduces the behaviour you have described, including precise details of how you are making the requests?

**Comment by philwebb** [comment]
@rhehl Are you my any chance using suffix matching? If so, see [this section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-RC1-Release-Notes#spring-mvc-path-matching-default-behavior-change) of the release notes.

**Comment by rhehl** [comment]
@philwebb i've tried setting spring.mvc.content-negotiation.favor-path-extension=true, but this doesn't change anything.

@wilkinsona I'm trying to create a sample but, in a fresh spring boot 2.0.0 rc1 it work's.

Looks like it doesn't find the path if the semicolon is included, I tried to debug the dispatcherServlet, but I cannot see my request, I just see 404 response.

**Comment by wilkinsona** [comment]
Unfortunately, it’s impossible to diagnose a problem that we can’t reproduce as there’s no way to know what the cause is. We’re going to need a reproducible example to make any progress on this one.

**Comment by BaptisteCyrill** [comment]
I observed a similar problem after updating spring-boot-starter-parent from 1.5.9.RELEASE to 1.5.10.RELEASE. Further information:

pom.xml
```
<parent>
    <groupId>org.springframework.boot</groupId> \
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.5.10.RELEASE</version>
    <relativePath/>
</parent>
```
 Configuration:
```
@Configuration
public class WebConfiguration extends WebMvcConfigurerAdapter {

    @Override
    public void configurePathMatch(PathMatchConfigurer configurer) {
        UrlPathHelper urlPathHelper = new UrlPathHelper();
        urlPathHelper.setRemoveSemicolonContent(false);
        configurer.setUrlPathHelper(urlPathHelper);
    }
}
```
RestController
```
@RequestMapping(path = "/ranges{makeId}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    public List<VtRange> getVtRangeList(
            @MatrixVariable(required = true) final Integer makeId
            , @RequestParam ... ) {
        ...
    }
```
Response in JMeter
```
{"timestamp":1518038503824,"status":500,"error":"Internal Server Error","exception":"org.springframework.security.web.firewall.RequestRejectedException","message":"The request was rejected because the URL contained a potentially malicious String \";\"","path":"/v1/vehicle-tree/ranges;makeId=45"}
```

After a rollback to spring-boot-starter-parent:1.5.9.RELEASE it works.

**Comment by wilkinsona** [comment]
@BaptisteCyrill Thanks, but I believe that's unrelated to this issue. @rhehl is [getting a 404 response](https://github.com/spring-projects/spring-boot/issues/11911#issuecomment-363507409).

**Comment by wilkinsona** [comment]
@BaptisteCyrill The change you have seen is due to a change in Spring Security 4.2.4 that makes the new `StrictHttpFirewall` the default. It rejects requests that contain a `;` by default. There's a [method](https://github.com/spring-projects/spring-security/blob/4.2.4.RELEASE/web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java#L66) that can be used to change that.

**Comment by bclozel** [comment]
@rhehl The request mapping you're using looks a bit odd `"/service/xyz/invoices{matrix}"` (matching a path variable within a path segment). I don't guarantee this will work in the future.

Please update this question once you've reproduced this issue.

**Comment by BaptisteCyrill** [comment]
@wilkinsona: Thank you for your support

**Comment by rhehl** [comment]
@wilkinsona  thank's a lot, that was the problem, setting  firewall.setAllowUrlEncodedSlash(true); fixed my problem, like it's described here:
https://stackoverflow.com/questions/48580584/stricthttpfirewall-in-spring-security-4-2-vs-spring-mvc-matrixvariable/48636757#48636757

**Comment by wilkinsona** [comment]
Thanks for letting us know.

**Comment by wilkinsona** [comment]
@rwinch It seems that the introduction of `StrictHttpFirewall` in 4.2.x and 5.0.x has caught out a few people now. I looked for and failed to find any documentation of the change. Could it be mentioned in the [release announcement](https://spring.io/blog/2018/01/30/cve-2018-1199-spring-security-5-0-1-4-2-4-4-1-5-released) and perhaps in the references docs too please?

**Comment by rwinch** [comment]
@rhehl Can I ask why you are needing to support URL encoded semi colons? I'm also curious in general your choice to use matrix variables. My impression, although could be incorrect, was that very few users leverage matrix variables. Instead, I would expect most users leverage query parameters.

The StrictHttpFirewall blocks the request because it is dangerous to allow them. Due to ambiguities in the Servlet specification and inconsistent behavior between Servlet Containers short of rejecting URL encoded semicolons we haven't been able to find a good way to protect against such exploits.

@wilkinsona Thanks for bringing this to my attention. We are already working on cleaning up the documentation for the subsequent releases.

**Comment by spencergibb** [comment]
Note, a number of spring cloud users are having the same problems. Doc updates would be helpful to refer them to.

**Comment by wilkinsona** [comment]
@rwinch The release notes haven't been updated, and this is still causing people trouble. Can something be done please?

**Comment by edeandrea** [comment]
We've just hit this same problem upon upgrading from boot 1.5.9 to 1.5.10 as well.

@rwinch - Are you saying that there is simply no use case for using matrix variables at all based on the fact that it introduces various security exploits? Even if it is, we have lots of legacy stuff here that is very inter-connected with other applications, so it would be near impossible to change from matrix variables to some other mechanism. Seems a change like this in a minor release is more than a minor change in backwards-compatibility. Grateful there is a workaround though, although if Boot were doing something else with the StrictHttpFirewall bean before my own config then I would also loose the boot auto-configuration.

To get around this (for now) we are doing the following (we have other internal frameworks that are "in-control" of the security configuration for our applications, so this defines an order so that our framework config comes first before this).

```java
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.security.config.annotation.web.builders.WebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.web.firewall.HttpFirewall;
import org.springframework.security.web.firewall.StrictHttpFirewall;

@Configuration
@Order(101)
public class SecurityConfig extends WebSecurityConfigurerAdapter {
	private HttpFirewall allowUrlEncodedSlashHttpFirewall() {
		StrictHttpFirewall firewall = new StrictHttpFirewall();
		firewall.setAllowSemicolon(true);

		return firewall;
	}

	@Override
	public void configure(WebSecurity webSecurity) throws Exception {
		webSecurity.httpFirewall(allowUrlEncodedSlashHttpFirewall());
	}
}
```

**Comment by rwinch** [comment]
@wilkinsona Thanks for the ping.

> The release notes haven't been updated, and this is still causing people trouble. Can something be done please?

The reference has explicit documentation on the `StrictHttpFirewall` and documents how to allow [matrix variables](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#request-matching). Is there something else that you feel should be done?

@edeandrea 

>  Seems a change like this in a minor release is more than a minor change in backwards-compatibility

This was necessary to fix a security vulnerability. For that reason, the breaking change is necessary.

> Grateful there is a workaround though, although if Boot were doing something else with the StrictHttpFirewall bean before my own config then I would also loose the boot auto-configuration.

To override the defaults just expose an `HttpFirewall` bean as outlined in [the reference](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#request-matching)

**Comment by wilkinsona** [comment]
> Is there something else that you feel should be done?

I think it would be good to mention it in the [release announcement](https://spring.io/blog/2018/01/30/cve-2018-1199-spring-security-5-0-1-4-2-4-4-1-5-released) as well please.

**Comment by rwinch** [comment]
@wilkinsona Thanks. Done

**Comment by wilkinsona** [comment]
Thanks, @rwinch!
