### ISSUE TITLE
Tomcat metrics are not exposed

### ISSUE THREAD

**Issue by shakuzen** [spring-projects/spring-boot#11916]
Micrometer's `micrometer-spring-legacy` project has `TomcatMetricsConfiguration` to provide Tomcat-specific metrics (which were available in Spring Boot 1.5 in some form). This is currently (Spring Boot 2.0.0.RC1) missing in Spring Boot 2 code, so no Tomcat metrics are available.

https://github.com/micrometer-metrics/micrometer/blob/fadd1ee0b758f983841bbef3235d10f3ada86fb4/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/web/tomcat/TomcatMetricsConfiguration.java

**Comment by shakuzen** [comment]
@wilkinsona I think there might be an ordering issue. When I debug the auto-configuration, I'm seeing `WebServerApplicationContext#getWebServer` always returning `null` here, which results in all the Tomcat session metrics not being available. When I was trying to implement this issue myself, I couldn't figure out what to change to get this to run after the `WebServer` is available.

**Comment by wilkinsona** [comment]
@shakuzen Interesting finding, thanks. Can you share some more details about your app where you saw that this was a problem? The tests for the auto-configuration check that a session-related metric is available and don't suffer from the problem that you've described. I suspect something in your case is triggering earlier instantiation of the `TomcatMetrics` bean and I'd like to know what.

**Comment by wilkinsona** [comment]
It’s the `MeterRegistryPostProcessor` that’s triggering it. A `MeterRegistry` is created before the WebServer has been created. The creation of the `MeterRegistry` causes the post processor to initialize all `MeterBinder` beans so that they can be bound to the registry.

The early creating of a `MeterRegistry` is triggered by its injection into `WebMvcMetricsFilter`. It's a servlet `Filter` and therefore tied to the self initialisation of `ServletWebServerApplicationContext` which occurs before the underlying web server has been created.

While we could perhaps change `WebMvcMetricsFilter` so that it's bound to a `MeterRegistry` rather than taking it as a constructor argument, there's nothing to stop a user doing what we're currently doing and reintroducing the problem. I think we need a more robust way for `TomcatMetrics` to obtain the Tomcat `Context`. Capturing it via a `TomcatContextCustomizer` might work.
