### ISSUE TITLE
Unable to avoid job triggering at Start up

### ISSUE THREAD

**Issue by ppanigrahi02** [spring-projects/spring-boot#11957]
#Hi Team. I am using a batch process and i want it to run at a specific cron scheduled time. However, the job is getting triggered at the start up and again triggering at the scheduled time. I am trying to avoid the former however failing to do so. This is a sample repository which reproduces the same issue: [https://github.com/ppanigrahi02/BatchJobWithScheduler](url). i am using the spring guide example [https://github.com/spring-guides/gs-batch-processing](url) and added a scheduler on top of it. I will really appreciate any leads.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by ppanigrahi02** [comment]
Actually i did some digging before posting here and found out that `spring.batch.job.enabled=false` property alone is sufficient to avoid the start up batch process. However its not working in this sample code. So i was wondering if there is any issue with my dependencies or configurations. Let me post it in stackoverflow as well. I will update the link if i manage to resolve it.

**Comment by snicoll** [comment]
@ppanigrahi02 I just tried that in our own sample and it worked. Asking for help about your sample is exactly what StackOverflow is for.
