### ISSUE TITLE
Embedded MongoDb with random port - does not work

### ISSUE THREAD

**Issue by Marek00Malik** [spring-projects/spring-boot#11966]
I have this problem when trying to run tests on an Embedded MongoDb, class annotated with @DataMongoTest and no configuration for mongo in application.properties. Spring Boot will try to setup a connection to embedded mongo db on a random port but the actual embedded mongo instance is on the default port.
Only by directly setting port to mongo and connection property with that port being used will allow SpringBoot to work.

Shouldn't the annotation set the embedded instance to one similar random port like it is done for the connection ?

I created a small sample app for presentation purpose. 
https://github.com/Marek00Malik/embedded-mongo-app

**Comment by wilkinsona** [comment]
You are creating the `MongoClient` yourself in your `MongoConfig` class rather than using the auto-configured client. As a result, you're losing the logic that configures the client to use embedded Mongo's port. That logic is in `org.springframework.boot.autoconfigure.mongo.MongoClientFactory` which you should be able to use.

As a slight aside, sub-classing `AbstractMongoConfiguration` is rather unusual for a Spring Boot app. A more typical setup would be to use the auto-configuration as much as possible, and only override individual beans when you need to do so.

If you need any further guidance, please ask on Stack Overflow or Gitter.
