### ISSUE TITLE
Suggestions to improve documentation about Dependencies detailed information

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-boot#11983]
I am writing this post with the best intentions. I have a huge respect for this project.

I have the following situation, when I create a new `Spring Boot` project either through 

* `https://start.spring.io` 
* `STS` (Spring Starter Project) 

I am able to select the `dependencies` and get them in my `build.gradle` file.

Normally or usually many of them all have the following pattern:

* `compile('org.springframework.boot:spring-boot-starter-aop')`
*  `compile('org.springframework.boot:spring-boot-starter-data-jpa')`

In this case `compile`, other situation is for example:

* `runtime('com.h2database:h2')`
*  `runtime('mysql:mysql-connector-java')`

Now both are `runtime`.

**Alpha**

My point and suggestion is that through the `Reference Documentation`, perhaps a new appendix,  show how would be added/generated a dependency for both `Gradle` and `Maven`. For example if I want add **later** the `lombok` dependency I must create a new project to see how was generated and then add manually to the main project.

**Gradle**

`compileOnly('org.projectlombok:lombok')`

(Observe that for `lombok` it is not neither `compile` nor `runtime`)

**Maven**

```
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<optional>true</optional>
</dependency>
```

I hope you see my point, thus time is saved for the developer when it needs add a new dependency to an already created project.

**Beta**

For `Spring Boot` in general we have the [Starters](https://docs.spring.io/spring-boot/docs/2.0.0.RC1/reference/htmlsingle/#using-boot-starter) section. There exists an important table named `Spring Boot application starters` where I am able to see through the `Pom` link what dependencies are behind.

I did check many of them and for example I did not find the following:  `jackson-dataformat-xml`
I did realize I must add manually in the `build.gradle` file.  Even more when `Jackson` term does not match to some `Starter` when I write that to find some dependency with that name.

Thus I want *suggest* that for the current Appendix named `Dependency versions` add a new column showing in what `Starter` is included. 

For example for:

```
com.fasterxml.jackson.datatype | jackson-datatype-jdk8 | 2.9.2
```
It is included within `spring-boot-starter-json`

Thus for `jackson-dataformat-xml`

```
com.fasterxml.jackson.dataformat | jackson-dataformat-xml | 2.9.2
```

 should be indicated through this new column that must be added manually, it means it is **not** included within some starter (`spring-boot-starter-XXX`)

Again these two alpha and beta are just suggestions.

**Comment by philwebb** [comment]
> My point and suggestion is that through the Reference Documentation, perhaps a new appendix, show how would be added/generated a dependency for both Gradle and Maven.

I think the Spring Boot documentation is the wrong place to put this. The decision about what scope a dependency should be in is really up to the user. In this case you're taking your cue from start.spring.io, but there's nothing really set in stone that says `mysql:mysql-connector-java` must be in the `runtime` scope. Lombock also covers this [in their own documentation](https://projectlombok.org/setup/maven) and I'm not keen to duplicate that.

> Thus I want suggest that for the current Appendix named Dependency versions add a new column showing in what Starter is included.

I can't really see how we can add this additional information without overwhelming the user. I also feel like the point of the starters is to provide the common dependencies that are needed. Searching for a starter that _contains_ a specific dependency seems a bit backwards to me.

Taking `jackson-dataformat-xml` as an example. We don't have any starters to help with XML, and it seems logical that the Jackson binding support we have to support JSON wouldn't want to bring in `jackson-dataformat-xml`. If I user knows that they want `jackson-dataformat-xml` specifically, they should just add that dependency, rather than looking for a starter that happens to contain it.
