### ISSUE TITLE
mvn spring-boot:run results in Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by muttalipkucuk** [spring-projects/spring-boot#11999]
Using XAMPP, I have a running a MySQL database and a Apacha web server running on my local machine.

I am executing the following Maven-command on my Spring boot based source code:
`mvn spring-boot:run
`

Then I am facing the following error message:
```
Unable to obtain Jdbc connection from DataSource
------------------------------------------------
SQL State  : 28000
Error Code : 1045
Message    : Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
