### ISSUE TITLE
Issue with loading welcome file in Spring Boot Application

### ISSUE THREAD

**Issue by Supriya-bansal** [spring-projects/spring-boot#12039]
I am getting below issue while loading welcome page of application:

**2018-02-14 13:37:30.728 ERROR 5852 --- [io-9000-exec-11] o.s.boot.web.support.ErrorPageFilter     : Cannot forward to error page for request [/] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false**

Spring Boot : v1.5

Thanks in advance.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
