### ISSUE TITLE
Documentation for configuration of the Actuator Health endpoint is wrong

### ISSUE THREAD

**Issue by sazzer** [spring-projects/spring-boot#12062]
This might be my misunderstanding, in which case I apologise in advance.

In the documentation, there is a description of how to get the Health Actuator endpoint to return verbose details. Specifically it says to set:

```
management.endpoints.health.show-details=true
```

I'm using YML configuration, and I've found that I need to use "endpoint" instead of "endpoints":

```
management:
  endpoint:
    health:
      show-details: true
```

I actually only realised this from IntelliJ auto-complete as well, not from the documentation in any way.

This is running entirely on Spring Boot 2.0.0.RC1 with Spring 5.0.3.RELEASE, running on Java 8.

Cheers

**Comment by wilkinsona** [comment]
I can't find "endpoints.health" in the [2.0.0.RC1 documentation](https://docs.spring.io/spring-boot/docs/2.0.0.RC1/reference/htmlsingle). Can you please link to the offending section? It may have already been corrected in the snapshot documentation as part of https://github.com/spring-projects/spring-boot/issues/11869, but I'd like to know where it was in the RC1 docs so that we can be sure it has been.

**Comment by sazzer** [comment]
You're right. My link - and the one that comes up in Google right now - is to the M7 documentation instead. Sorry!
