### ISSUE TITLE
Auto-configure JettyMetrics

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#12090]
We have metrics support for Tomcat  and micrometer has [support for Jetty](https://github.com/micrometer-metrics/micrometer/blob/553f20679b163d7d6da3603a1d1e6a4486e06bcd/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyStatisticsMetrics.java) so we should configure that  as well for consistency.

**Comment by wilkinsona** [comment]
I looked at this briefly when I was adding support for Tomcat's metrics. It's not completely straightforward as it relies on Jetty being configured with a `StatisticsHandler` which is isn't by default. I wondered if the Jetty metrics auto-configuration should customise Jetty with a `StatisticsHandler` but didn't manage to convince myself it was the right thing to do.

**Comment by wilkinsona** [comment]
Given the potential complications with `StatisticsHandler`, we decided that this can wait until 2.1.

**Comment by evenh** [comment]
In my mind this sounds pretty useful. If I were to have a look at this, where would one start?

**Comment by snicoll** [comment]
@evenh we've decided to postpone this to 2.1 (it's not a matter of a lack of time working on it). Thanks anyway.

**Comment by davidkarlsen** [comment]
Should this be picked up again? https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/TimedHandler.java

**Comment by wilkinsona** [comment]
Thanks, @davidkarlsen. Unfortunately, `TimedHandler` makes things more complicated rather than less. We now use Jetty's `StatisticsHandler` when graceful shutdown is enabled and we would not want to use both when Micrometer's on the classpath as well.

@jkschneider @shakuzen What was the motivation for creating `TimedHandler` rather than using Jetty's `StatisticsHandler`?

**Comment by jkschneider** [comment]
@wilkinsona `TimedHandler` is like `StatisticsHandler`, but much higher resolution. Rather than relying on `StatisticsHandler`'s pre-aggregation of request throughput, etc. which are lossy it uses Micrometer timers.

`StatisticsHandler` is like a poor version of WebMvc and Webflux metrics (`http.server.requests`).

`TimedHandler` was designed for projects that are using the Jetty API more directly, like Javalin to get a request-level metrics experience similar to Spring Boot's WebMvc and WebFlux metrics.

For Spring Boot, I think just stick with what you've already got for `http.server.requests` and maybe autoconfigure the `JettyServerThreadPoolMetrics`, `JettyConnectionMetrics`, and `JettySslHandshakeMetrics` binders?

**Comment by nyilmaz** [comment]
@wilkinsona `JettyServerThreadPoolMetrics` is now supported by `JettyMetricsAutoConfiguration`. Would `*Metrics` which @jkschneider mentioned, be considered for further auto configuration?

**Comment by wilkinsona** [comment]
@nyilmaz Yes, we can consider them. I think, although can't remember for certain, that's why I left this issue open when https://github.com/spring-projects/spring-boot/issues/14591 was implemented.

**Comment by nyilmaz** [comment]
oh nice, any plans or target release candidates for this issue?

**Comment by wilkinsona** [comment]
The issue's assigned to the general backlog milestone which means we don't have any concrete plans for it at the moment.

**Comment by wilkinsona** [comment]
We now bind connection and SSL handshake metrics in addition to the existing thread pool metrics binding so I think we're done here thanks to @bono007.
