### ISSUE TITLE
Spring boot validation with DB

### ISSUE THREAD

**Issue by yarabsyp** [spring-projects/spring-boot#12101]
I have a requirement which need to do a custom validation with bean . The validated metadata can be received from Oracle DB. so based on the DB metadata I want to make bean properties as optional or required , apply patterns and do a cross field validation. Can anyone suggest best practices for these requirements. I want do do all this in spring boot Better if you could share some sample code for reference

Thanks

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
