### ISSUE TITLE
Correct and complete configuration for Spring Boot 1.5.x/2.0.x for Hibernate 5

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-boot#12100]
Hello

Please read the following post for all the detail

* [Correct and complete configuration for Spring Boot 1.5.x for Hibernate 5](https://stackoverflow.com/questions/48843696/correct-and-complete-configuration-for-spring-boot-1-5-x-for-hibernate-5)

Consider the scenario to migrate a complete project working through `Spring Framework` to `Spring Boot` working both with `Hibernate`

Assuming there is an answer, consider include that in the current `Spring Boot Reference Guide` for the `1.5.x` and `2.0.x` versions. I already did a research in these both `Spring Boot Reference Guide` and .... without be rude, there is no detailed instructions (let me know If I am wrong or missing something).

Thanks by your understanding

**Comment by bclozel** [comment]
Thanks for getting in touch, but there's no need to cross post, the Spring Boot team+community are monitoring Stack Overflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

Note that in its current state, your question does not really describe what you were trying to achieve and the setup that reproduces the issue. Spring Boot already works with Hibernate 5 out-of-the-box, and your question seem to describe your analysis of the issue rather than the issue itself.

[Check out this StackOverflow page about asking questions](https://stackoverflow.com/help/how-to-ask). Thanks!

**Comment by wilkinsona** [comment]
Your question on Stack Overflow, which you only posted an hour ago, is the right place for this. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

You may also want to refer to our [JPA sample](https://github.com/spring-projects/spring-boot/tree/v1.5.10.RELEASE/spring-boot-samples/spring-boot-sample-jpa).

**Comment by manueljordan** [comment]
Thanks @wilkinsona for your explanation, I think my question in SO is correct. Please check again the SO post, starting from `How a summary` text. I hope the situation be complete now. 

I have create _here_ the post because in case there is a reply from you (I mean from spring boot team) to SO, that answer would be valuable for the `Spring Boot Reference Guide`, because 'seems' there is no a specific section in the `Spring Boot Reference Guide` to integrate Spring Boot with _plain_ Hibernate how I am reporting through my experience. It is the `enhancements` _in some way_ requested

Thanks by your understanding
