### ISSUE TITLE
spring webflux (netty) handler can't parse ServerRequest containing json larger than 750 bytes

### ISSUE THREAD

**Issue by NimrodTicotzner** [spring-projects/spring-boot#12112]
Hi, 

We recently started experimenting with spring boot 2.0.
Having the following handler code:

```
@Component
public class DataStreamHandler {
   
    public Mono<ServerResponse> pipeEvent(ServerRequest request) {
        Mono<String> reqBody = request.bodyToMono(String.class);
        String body = reqBody.block();
        System.out.println(body);
        return ServerResponse.ok().body(fromObject("OK"));
    }
}
```
```
@Configuration
public class RouterConfig {

    @Bean
    public RouterFunction<ServerResponse> monoRouterFunction(DataStreamHandler dataStreamHandler) {
        return route(POST("/pipeEvent"), dataStreamHandler::pipeEvent);
    }

}
```

It seems that the handler can't parse request containing json larger than 750 bytes.
when i searched how to configure max-http-post-size i found solutions only for tomcat,jetty and undertow.

How can i configure it for underlying netty?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by NimrodTicotzner** [comment]
Thanks for your reply, here s the link to stackoverflow:

https://stackoverflow.com/questions/48867886/spring-webflux-netty-handler-cant-parse-serverrequest-containing-json-larger

would be very glad if someone could answer there..
