### ISSUE TITLE
Evaluate order of classes in @ConditionalOn[Missing]Class

### ISSUE THREAD

**Issue by YannCebron** [spring-projects/spring-boot#12131]
Listed classes/names are evaluated in given order. Evaluate "likeliness" of (non-)availability of listed classes to optimize evaluation run times.

Sample: it might be more likely for a listed Spring framework class to be available than the listed class from the actual 3rd party framework.

**Comment by snicoll** [comment]
@philwebb I had a try to this one in bf6101b but writing a test shows that we don't stop if we find a missing class so even if those are ordered as described here, we'll still check for whatever other value is defined.

This makes a rather useless optimization. We should backoff as first as one item makes the outcome negative for this to really have any sort of effect. Thoughts?

**Comment by philwebb** [comment]
I'm doubtful this change would make that much of an impact anyway. We're not creating a List and doing a sort which might itself cause a performance hit.

**Comment by philwebb** [comment]
I've applied a fix, but it only happens with the early class filtering, not with regular condition evaluation. The means we can do the sorting in the annotation processor rather than at runtime.

I added some logging for a typical Boot app and the early filter call handles 168 distinct `@ConditionalOnClass`. Of those, 93 contain more than one class to consider. The ordering, along with a few tweaks to prevent unnecessary `Set` creation saves a few milliseconds (unscientifically ~20-30).
