### ISSUE TITLE
Custom HttpMessageReader with WebFlux and Netty

### ISSUE THREAD

**Issue by RyanHoldren** [spring-projects/spring-boot#12164]
There seems to be an issue using custom `HttpMessageReader` with WebFlux on top of Netty. I have put together a small sample application to demonstrate.

[ReactiveDemo.zip](https://github.com/spring-projects/spring-boot/files/1745998/ReactiveDemo.zip)

In particular, it contains a simple custom HttpMessageReader:
```
package com.beanworks.demo;

import java.math.BigInteger;
import static java.util.Collections.singletonList;
import java.util.List;
import java.util.Map;
import org.springframework.core.ResolvableType;
import static org.springframework.core.io.buffer.DataBufferUtils.join;
import org.springframework.http.MediaType;
import static org.springframework.http.MediaType.TEXT_PLAIN;
import org.springframework.http.ReactiveHttpInputMessage;
import org.springframework.http.codec.HttpMessageReader;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@Service
public class DemoReader implements HttpMessageReader<BigInteger> {

	@Override
	public List<MediaType> getReadableMediaTypes() {
		return singletonList(TEXT_PLAIN);
	}

	@Override
	public boolean canRead(ResolvableType elementType, MediaType mediaType) {
		return TEXT_PLAIN.includes(mediaType)
			&& ResolvableType.forClass(BigInteger.class).isAssignableFrom(elementType);
	}

	@Override
	public Flux<BigInteger> read(ResolvableType elementType, ReactiveHttpInputMessage message, Map<String, Object> hints) {
		throw new UnsupportedOperationException("Reading a Flux is not supported!");
	}

	@Override
	public Mono<BigInteger> readMono(ResolvableType elementType, ReactiveHttpInputMessage message, Map<String, Object> hints) {
		return join(message.getBody()).map(buffer -> {
			int index = buffer.readableByteCount();
			BigInteger result = BigInteger.valueOf(0);
			while (--index >= 0) {
				result = result.add(BigInteger.valueOf(buffer.read()));
			}
			return result;
		}).log("DemoReader.readMono()");
	}

}
```

If I hit this endpoint with a body that fits in one packet, everything works as expected:
```
curl --data "Test" http://localhost:8080/demo --header "Content-Type: text/plain"
```
```
2018-02-21 14:36:36.917  INFO 27622 --- [ctor-http-nio-5] DemoReader.readMono()                    : | onSubscribe([Fuseable] FluxOnAssembly.OnAssemblySubscriber)
2018-02-21 14:36:36.918  INFO 27622 --- [ctor-http-nio-5] DemoReader.readMono()                    : | request(unbounded)
2018-02-21 14:36:36.918  INFO 27622 --- [ctor-http-nio-5] DemoReader.readMono()                    : | onNext(416)
2018-02-21 14:36:36.923  INFO 27622 --- [ctor-http-nio-5] DemoReader.readMono()                    : | onComplete()
```

But as soon as the body spans multiple packets, something - it looks like Netty - is calling cancel(), and the request never completes.
```
curl --data @BigFile.jpg http://localhost:8080/demo --header "Content-Type: text/plain"
```
```
2018-02-21 14:39:18.111  INFO 27622 --- [ctor-http-nio-6] DemoReader.readMono()                    : | onSubscribe([Fuseable] FluxOnAssembly.OnAssemblySubscriber)
2018-02-21 14:39:18.111  INFO 27622 --- [ctor-http-nio-6] DemoReader.readMono()                    : | request(unbounded)
2018-02-21 14:39:18.113  INFO 27622 --- [ctor-http-nio-6] DemoReader.readMono()                    : | cancel()
```

I have also tried accomplishing the same goal by extending `DecoderHttpMessageReader` but it exhibits the same behaviour.

**Comment by RyanHoldren** [comment]
I should add that I believe this to be an RC1 regression. It works properly in M7, but starts failing when I try to upgrade to RC1 or RC2.

**Comment by bclozel** [comment]
This definitely looks like an issue in Spring Framework buffer utils, or Reactor Netty, or your custom codec. I don’t think Spring Boot is involved in any of this. I’ll take a look still to narrow down the issue.

**Comment by RyanHoldren** [comment]
Yeah, I wasn't sure which project "owned" this kind of thing. I appreciate you taking the time to investigate.

**Comment by bclozel** [comment]
Hey @RyanHoldren !

## Reactor Netty issue and workaround

Thanks for reporting this, I believe you've found a bug in Reactor Netty. I've opened reactor/reactor-netty#293 with more details on the actual issue. TL;DR; it's got nothing to do with your `HttpMessageReader` nor Spring, but some HTTP protocol detail (the `"Expect: 100-continue"` support).

There are two ways to work around this problem. First, you can use Tomcat instead of Reactor Netty by adding the `spring-boot-starter-tomcat` dependency to your build. You can also artificially avoid this issue by adding `--header "Expect: "` to your curl command.

## Feedback on `HttpMessageReader` implementation

I don't know if the `HttpMessageReader` implementation you've shown has been tailored for this issue, but just in case I'm giving you a bit of feedback about it.

`HttpMessageReader` should be about reading inbound data, decoding it and converting it - without data loss nor application logic. The sum operation you're doing on `BigInteger` definitely belongs to a `Controller` or some other infrastructure part.

Your message reader could instead decode to `Flux<BigInteger>` and let your controller do something like this:

```java
@PostMapping("/test")
public Mono<BigInteger> test(@RequestBody Flux<BigInteger> value) {
	return value.reduce(BigInteger.ZERO, (a, b) -> a.add(b));
}
```

Also, I wouldn't advise using the `DataBufferUtils.join` operator on a big chunk of data, especially not the whole request body. Doing that will buffer the whole request body in memory and will work against backpressure in your application.

The `HttpMessageReader` could look like this:

```
@Override
public Flux<BigInteger> read(ResolvableType elementType, ReactiveHttpInputMessage message, Map<String, Object> hints) {
	return message.getBody().flatMap(buffer -> {
		List<BigInteger> bigIntegers = new ArrayList<>(buffer.readableByteCount());
		do {
			bigIntegers.add(BigInteger.valueOf(buffer.read()));
		}
		while (buffer.readableByteCount() > 0);
		return Flux.fromIterable(bigIntegers);
	});
}
```

This will limit the amount of in-flight data and work better with backpressure in your application.

I'm closing this issue as invalid, since there's nothing we can do in Spring Boot to fix this - we'll pick up the fix from Reactor Netty when it's shipped.

Thanks again for the report!

**Comment by RyanHoldren** [comment]
Thanks @bclozel, I should be able to add `--header "Expect: "` to my project until the bug is fixed.

Also, thank you for your feedback of my `HttpMessageReader`. It was just for demonstration purposes though, and bears little resemblance to my real reader.
