### ISSUE TITLE
Customize Jackson mapper implicitly in spring boot is not working 

### ISSUE THREAD

**Issue by yarabsyp** [spring-projects/spring-boot#12207]
I have below code in my spring boot config 
Also m trying to add skip case sensitive true this configuration is not working in spring boot 

During the object conversion this mapper configuration is not applying plz help or let me know wat is the issue with this code 

@Bean
public Jackson2ObjectMapperBuilder objectMapperBuilder() {
    Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
    builder.serializationInclusion(JsonInclude.Include.NON_NULL);
    return builder;
}

**Comment by yarabsyp** [comment]
Even I tried with application.prop
spring.jackson.serialization-inclusion=non_null
It is not working version 1.5

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
