### ISSUE TITLE
Out of the box error when instanciating PreBuiltXPackTransportClient using Elastic

### ISSUE THREAD

**Issue by Rorschachdb** [spring-projects/spring-boot#12242]
Hi,

Switched to RC2
Overriding default 5.5.0 elastic client for 5.6.8

Using elastic search I get this netty error

> Failed to instantiate [org.elasticsearch.client.Client]: Factory method 'client' threw exception; nested exception is java.lang.IllegalStateException: availableProcessors is already set to [8], rejecting [8]

The code for instantiating the client is :
```java
@Bean
  public Client client() throws Exception {

    Settings esSettings = Settings.builder().put("cluster.name", clusterName)
        .put("xpack.security.user", userName + ":" + password)
        .build();
    TransportClient client = new PreBuiltXPackTransportClient(esSettings, Collections.emptySet());
    client.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(host), port));
    return client;
  }
```

The workaround I found is to set "es.set.netty.runtime.available.processors" system property to "false". Not so much bothering thought but annoying for the out of the box experience.

Cheers,

R.

**Comment by wilkinsona** [comment]
Thanks for the report. This failure means that something else has already configured the available processors. I can't tell from the little you have shared what that something may be and if it can be avoided. Can you please provide a small sample that reproduces the problem?

> Switched to RC2
> Overriding default 5.5.0 elastic client for 5.6.8

Are you sure about the default? Boot's dependency management has used 5.6.x since RC1.

**Comment by Rorschachdb** [comment]
OK I will investigate but I have honestly no clue what did configure the processor count beforehand. Code exemple is a bit complicated... working from a private company. If I can't find the guilty settup, I'll try to setup some reproducing code.

For the client version...

Here's what I get from gradle dependencies ommiting the forced 5.6.8 version:
```
+--- org.springframework.boot:spring-boot-starter-data-elasticsearch:2.0.0.RC2
|    +--- org.springframework.boot:spring-boot-starter:2.0.0.RC2 (*)
|    \--- org.springframework.data:spring-data-elasticsearch:3.0.4.RELEASE
|         +--- org.springframework:spring-context:5.0.4.RELEASE (*)
|         +--- org.springframework:spring-tx:5.0.4.RELEASE
|         |    +--- org.springframework:spring-beans:5.0.4.RELEASE (*)
|         |    \--- org.springframework:spring-core:5.0.4.RELEASE (*)
|         +--- org.springframework.data:spring-data-commons:2.0.4.RELEASE
|         |    +--- org.springframework:spring-core:5.0.4.RELEASE (*)
|         |    +--- org.springframework:spring-beans:5.0.4.RELEASE (*)
|         |    \--- org.slf4j:slf4j-api:1.7.25
|         +--- commons-lang:commons-lang:2.6
|         +--- joda-time:joda-time:2.9.9
|         +--- org.elasticsearch:elasticsearch:5.5.0

```

**Comment by Rorschachdb** [comment]
OK found out, the submitted code was called twice sorry for bothering but thanks helping cleaning up my poor code

**Comment by wilkinsona** [comment]
Thanks for letting us know.

**Comment by wilkinsona** [comment]
> Here's what I get from gradle dependencies ommiting the forced 5.6.8 version

It looks to me like you haven't applied the dependency management plugin to your project:

```
apply plugin: 'io.spring.dependency-management'
```

**Comment by Rorschachdb** [comment]
You are right when applying the pluging dependencies change to 5.6.7

Back to my original problem I was wrong the code is not called twice and it seems that the number of processor is set during server startup (using reactive starter and undertow) by NettyRuntime class (line 70). I'll try to set a small project up for reproduction ASAP

**Comment by Rorschachdb** [comment]
[springboot12242.tar.gz](https://github.com/spring-projects/spring-boot/files/1762991/springboot12242.tar.gz)
here is a gradle project with a little bash script to install and run the docker image I'm using.

**Comment by wilkinsona** [comment]
Thanks. The only code that's attempting to set the available processor is Elasticsearch. Reactor Netty uses Netty's `PooledByteBufAllocator` and it makes the following call in its static initializer:

```java
final int defaultMinNumArena = NettyRuntime.availableProcessors() * 2;
```

This call to `availableProcessors()` prevents any future attempts to configure the number of available processors. In short, the only way to avoid the problem is to either make sure that the Elasticsearch code that tries to set the available processors runs first, or to disable or change that code.

As you've noted, the code can be disabled by setting the `es.set.netty.runtime.available.processors` system property. Unfortunately, I don't think it would be appropriate for Boot to set the property for you as its scope is JVM-wide. I think the ideal here would be for Elasticsearch's client to either stop trying to configure the number of available processors or to do so defensively so that the exception doesn't break your app. If you'd like to pursue this suggestion you'll need to take it up with the Elasticsearch team. You could comment on [this issue](https://github.com/elastic/elasticsearch/issues/25741).

**Comment by Rorschachdb** [comment]
Ok thanks, I'll had a comment but I suspect they won't do much as if I remember well they are planning on deprecating the TransportClient in favor of their RestHighLevelClient.

Thank you for your time.

**Comment by javmain** [comment]
when use spring-boot-starter-data-redis and spring-boot-starter-data-elasticsearch together, I got this issue again. I found that it causes by  Lettuce, Lettuce use Netty and elasticsearch use Netty too。

**Comment by snicoll** [comment]
@javmain this issue is closed and we've already concluded there is nothing we can do here. Please open an issue in the [Spring Data Elasticsearch project](https://jira.spring.io/projects/DATAES)

**Comment by wilkinsona** [comment]
> Please open an issue in the Spring Data Elasticsearch project

I don't think that will help as the problem's in Elasticsearch. I'd recommend commenting on [this Elasticsearch issue](https://github.com/elastic/elasticsearch/issues/25741) if you don't consider Elasticsearch's existing system property-based solution to be adequate.
