### ISSUE TITLE
EndpointRequest shouldn't 500 if management.endpoints.web.exposure.exclude=*

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#12240]

**Comment by 72MiguelGomes** [comment]
@mbhave Could you please provide more information regarding this issue?

Assumed the problem was with the actuator and I tested the following:

1. Start spring boot application
2. Add actuator starter
3. Call `http://localhost:8080/actuator/health`
3.1 returned 200.
4. Stop application
5. Add `management.endpoints.web.exposure.exclude=*`
6. Start application
7. Call `http://localhost:8080/actuator/health`
7.1 returned 404.

It seems fine.

**Version Tested:** 2.1.0.BUILD-SNAPSHOT

**Comment by mbhave** [comment]
We no longer get a 500. Going to close this in favor of #13749.
