### ISSUE TITLE
spring data elasticsearch 中使用多条件分页查询有问题，分页查询返回Page<T>对象的时候

### ISSUE THREAD

**Issue by DeepRedApple** [spring-projects/spring-boot#12277]

**Comment by DeepRedApple** [comment]
在Spring data elastisSearch 中 使用ElasticsearchRepository接口的实现类去做分页查询的时候，返回的Page<T>，page.gettotalPages() always 1

**Comment by snicoll** [comment]
Courtesy of Google translate:

>Page, page.gettotalPages () always 1 when using Spring's ElasticsearchSepository implementation class to do paging query

Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
