### ISSUE TITLE
application.properties is ok,but application.yml  use bad.

### ISSUE THREAD

**Issue by lovemoganna** [spring-projects/spring-boot#12283]
When I create a global configuration file "application.properties",

In theory, it's ok to use "application.yml",

but When I configure this "application.yml" is bad.

Looks like below,
```
one : application.properties:
                    server.port=8088
                    server.servlet-path=*.html

Two: application.yml :
                    port: 8088
                    servlet-path: *.html
```
but in fact ,These two configurations,One is Ok.Two is Bad. 

I try to use @EnableAutoConfiguration in MyProjectApplication.java  class,Try to start in their own way, but still can not run successfully.

**Comment by wilkinsona** [comment]
Sorry, I don't think I understand your description of the problem. There are a few things that don't look quite right though:

1. The servlet-path is the path of the main `DispatcherServlet`. Only mapping it to `*.html` is unusual.
2. The `server` prefix is missing in your YAML. It should be:

```yaml
server:
  port: 8088
```

If you need some further help, please come and chat on [Gitter](https://gitter.im/spring-projects/spring-boot) or ask a question on [Stack Overflow](https://stackoverflow.com). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
