### ISSUE TITLE
spring boot 2.0 ResourceHttpRequestHandler

### ISSUE THREAD

**Issue by z589533** [spring-projects/spring-boot#12294]
![image](https://user-images.githubusercontent.com/12063612/36841350-00b9f30e-1d83-11e8-8aa4-cf573ee00aaa.png)
How do I use ResourceHttpRequestHandler to get Authority annotation exists? Same as HandlerMethod class

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/36842041-5810f830-1d85-11e8-9c8a-06628c00a01b.png)
I can not get the runtime method from ResourceHttpRequestHandler

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
