### ISSUE TITLE
AbstractRoutingDataSource not working

### ISSUE THREAD

**Issue by linyongfu2013** [spring-projects/spring-boot#12310]
I am using spring-data-jpa, I configure two datasource, I try to use AbstractRoutingDataSource to dynamically switch datasource , but it just won't work , all requests were routing to the slaveDataSource. is there anyone can give me some advice ? 

here is my project : https://github.com/linyongfu2013/spring-multi-datasource.git

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
