### ISSUE TITLE
Recommend the use of the compileOnly or annotationProcessor configurations for spring-boot-configuration-processor

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#12316]

**Comment by snicoll** [comment]
`annotationProcessor` is not detected by IntelliJ IDEA last time I checked. My preference is that whatever we recommend is supported OOB by the IDEs.

**Comment by vpavic** [comment]
As of Gradle 4.6 using `compileOnly` generates the following warning:

> Putting annotation processors on the compile classpath has been deprecated and is scheduled to be removed in Gradle 5.0. Please add them to the processor path instead. If these processors were unintentionally leaked on the compile classpath, use the -proc:none compiler option to ignore them..

**Comment by wilkinsona** [comment]
> As of Gradle 4.6 using compileOnly generates the following warning

Indeed. I've worded the documentation update to recommend `compileOnly` with Gradle 4.5 and earlier and `annotationProcessor` with Gradle 4.6.

> annotationProcessor is not detected by IntelliJ IDEA last time I checked. My preference is that whatever we recommend is supported OOB by the IDEs.

Unfortunately, our detection of the presence of the configuration processor doesn't work with Gradle 4.6 unless it's declared in the `annotationProcessor` configuration.

**Comment by snicoll** [comment]
@wilkinsona apologizes, I was referring to Maven (the compiler plugin has a notion of `annotationProcessor` as well).

**Comment by jezovuk** [comment]
> Unfortunately, our detection of the presence of the configuration processor doesn't work with Gradle 4.6 unless it's declared in the annotationProcessor configuration.

In Eclipse with Spring IDE (with Gradle 4.6), configuration processor is detected when using `compile` or `compileOnly` (in which case Gradle complains upon build), but there is a warning if `annotationProcessor` is used (in order to make Gradle happy).

I'm posting in this issue since I'm not sure if I'm doing something wrong or this is a bug in Spring Boot / Spring IDE for Eclipse (in which case I guess this should be a separate issue).

Screenshots for clarification:

`compileOnly`

![spring-boot-12316-co](https://user-images.githubusercontent.com/1548456/38374021-f6f6f890-38f2-11e8-8721-9450041e4e71.PNG)

`annotationProcessor`

![spring-boot-12316-ap](https://user-images.githubusercontent.com/1548456/38374031-fd6d92c4-38f2-11e8-8136-b8e79928714b.PNG)

**Comment by wilkinsona** [comment]
Thanks, @jezovuk. That's a bug in Spring IDE. I've opened https://github.com/spring-projects/spring-ide/issues/266.

**Comment by jezovuk** [comment]
Thanks a lot.
