### ISSUE TITLE
Could not expand `static-locations` array

### ISSUE THREAD

**Issue by pkptzx** [spring-projects/spring-boot#12360]
in  1.5.2 project is working~
up to 1.5.10 not work...

Reason: Property 'staticLocations' threw exception; nested exception is java.lang.NullPointerException

I test found if 5 path ,is ok, 
more than 5 is not working

**Comment by bclozel** [comment]
To be able to help you, we need some more information. Please provide a [complete, minimal example](https://stackoverflow.com/help/mcve) (something we can unzip or git clone) that we can run to reproduce the problem.

**Comment by pkptzx** [comment]
@bclozel ok , I uploaded . 
see [github](https://github.com/pkptzx/springbootstatictest.git)

see [README](https://github.com/pkptzx/springbootstatictest/blob/master/README.md)

**Comment by snicoll** [comment]
This regression has been introduced by #9360

Unfortunately the binder is mutating the array once it has expanded so we're trying to append a slash on a `null` String and that cleanup code isn't called at all (since the binder sets the value on the array _after_ the setter has been invoked. 

Not sure yet how to fix that one.

**Comment by snicoll** [comment]
2.0 uses another binder mechanism that works properly.
