### ISSUE TITLE
log4j-core-2.7.jar: CVE-2017-5645

### ISSUE THREAD

**Issue by nitrocode** [spring-projects/spring-boot#12394]
CVE-2017-5645 [ndist](https://nvd.nist.gov/vuln/detail/CVE-2017-5645)

I ran the maven dependency checker

    mvn dependency-check:check

And it returned

    [ERROR] log4j-core-2.7.jar: CVE-2017-5645

Vulnerable version is any version before `2.8.2` and current version is [2.10.0](https://logging.apache.org/log4j/2.x/download.html)

Due to these springboot dependencies in my `pom.xml` file

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>

It appears the dependency is in [6 spring boot packages](https://github.com/spring-projects/spring-boot/search?utf8=%E2%9C%93&q=log4j-core&type=). 

I was hoping that this was a false positive or an easy upgrade but when I searched the CVE in github or online, I couldn't find any reference to it.

**Comment by wilkinsona** [comment]
Log4j 2 is only vulnerable if you're "using the TCP socket server or UDP socket server to receive serialized log events from another application". Spring Boot's default Log4j 2 configuration does not do so. If you're using Spring Boot 1.5.x and your Log 4j configuration does use the TCP or UDP socket servers, you can use the `log4j2.version` property to override the version of Log 4j 2 that's used. Spring Boot 2.0 already uses Log 4j 2.10.0.

**Comment by nitrocode** [comment]
@wilkinsona Thank you for the quick response. We're currently on the 1.5.x branch. Do you recommend upgrading to 2?

**Comment by wilkinsona** [comment]
That’s really up to you. If you are using Log4j 2 is a way that means you are vulnerable, upgrading to Spring Boot 2.0 or overriding the version of Log4j 2 that’s used will fix the problem. Depending on your application, the latter is probably the easier of the two.

**Comment by nitrocode** [comment]
Thank you very much! We'll suppress for now and look into upgrading later.

**Comment by jmpavlec** [comment]
For anyone that might stumble upon this ticket because of the CVE. Please look at https://github.com/spring-projects/spring-boot/issues/9172 as well which states that Spring Boot 1.5.x is not compatible with log4j 2.8.x and above. We tried updating the version in our 1.5.x app (to use 2.11.1) and got the same error. It seems we must upgrade to Sprint Boot 2.x to avoid this CVE

**Comment by jmpavlec** [comment]
That is correct, but it does not stop our automated dependency checkers from flagging this as a HIGH CVE. We have had at least a few customers who have asked about this particular one. To a non-technical person, it is not so nice to see a HIGH CVE in an application that they are using. We have of course explained that our use is not actually vulnerable but from an outsiders perspective, all they see is that the CVE was flagged.

Thanks for the clarification for others who may stumble upon this post.

**Comment by wilkinsona** [comment]
> it does not stop our automated dependency checkers from flagging this as a HIGH CVE

Have you raised this with the dependency checker vendor? While it's understandable for them to err on the side of false positives when identifying vulnerabilities it does waste a considerable amount of time and too many false positives runs the risk of people disabling the checks altogether. A checker that is more sophisticated than simply flagging any use of version X of dependency Y would be a big improvement for all concerned.

**Comment by DCKcode** [comment]
I completely agree - the technology and process around this is quite imperfect and much too simplistic. As with many of these things however these tools commonly are quite useful until they get very annoying, as is the case here.

This vulnerability is a particularly bad example of how these simplistic dependency scanners misfire, since it's an extremely common dependency and the CVE rating of 7.5 is just on the "high" threshold. This is the threshold at which one will typically block builds or block moving software to production environments (at least until further review). In the context of Spring Boot it is particularly inconvenient since it requires doing a major version upgrade (and processing breaking changes) in order to keep this process clean for any further customers you ship your software to.

Just to be clear I'm not suggesting Spring/Pivotal should do things differently here - the problem is already solved in Spring Boot 2.0 and therefore the "fix" is to simply upgrade. But it's good to be aware that these simplistic vulnerability scanners are unfortunately becoming more common as part of container vulnerability scanners in secure devops environments. As a result this will not be the last issue of its sort...

**Comment by nitrocode** [comment]
Hi all, just add a `suppressionFile`, [see example 7](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/) if you're using the mvn dependency checker.
