### ISSUE TITLE
Mention in docs that WebFlux is not supported in WAR deployment mode

### ISSUE THREAD

**Issue by vikas-parihar** [spring-projects/spring-boot#12455]

**Comment by vikas-parihar** [comment]
This is my main class 

@SpringBootApplication
public class BookServiceApplication extends AbstractReactiveWebInitializer {

    public static void main(String[] args) {
        SpringApplication.run(BookServiceApplication.class, args);
    }

    @Override
    protected Class<?>[] getConfigClasses() {
        return new Class[]{
                RoutingConfiguration.class,
                BookServiceHandler.class,
                BookService.class
            };
    }


These are routing configuration


package com.pearson.ltg.book.config.routing;

import static org.springframework.web.reactive.function.server.RequestPredicates.GET;
import static org.springframework.web.reactive.function.server.RouterFunctions.route;
import static org.springframework.web.reactive.function.server.RouterFunctions.toWebHandler;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.server.reactive.HttpHandler;
import org.springframework.http.server.reactive.TomcatHttpHandlerAdapter;
import org.springframework.web.reactive.config.CorsRegistry;
import org.springframework.web.reactive.config.EnableWebFlux;
import org.springframework.web.reactive.config.WebFluxConfigurer;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.ServerResponse;
import org.springframework.web.server.adapter.WebHttpHandlerBuilder;

import com.pearson.ltg.book.exception.ErrorHandler;
import com.pearson.ltg.book.handlers.BookServiceHandler;

@Configuration
@EnableWebFlux
public class RoutingConfiguration implements WebFluxConfigurer {

    @Autowired
    private ApplicationContext appContext;

    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**").allowedMethods("GET", "POST", "DELETE", "PUT", "HEAD");
    }

    @Bean
    public RouterFunction<ServerResponse> bookRoutes() {
      BookServiceHandler bookServiceHandler =  appContext.getBean(BookServiceHandler.class);
    return route (GET("/v1/books/{bookId}/metadata"), bookServiceHandler :: getBookMatadata)
         .andRoute (GET("/v1/books/{bookId}/details"), bookServiceHandler :: getBookDetails)
         .andRoute (GET("/v1/books/{bookId}/profile"), bookServiceHandler :: getBookProfile);
    }

    @Bean
    ErrorHandler errorHandler() {
        return new ErrorHandler();
    }

    @Bean WebClient webClient() {
      return WebClient.create();
    }


    @Bean
    public ServletRegistrationBean<TomcatHttpHandlerAdapter> servletRegistrationBean() {
        HttpHandler httpHandler = WebHttpHandlerBuilder
          .webHandler(toWebHandler(bookRoutes()))
          .build();
        ServletRegistrationBean<TomcatHttpHandlerAdapter> registrationBean
          = new ServletRegistrationBean<>(new TomcatHttpHandlerAdapter(httpHandler), "/");
        registrationBean.setLoadOnStartup(1);
        registrationBean.setAsyncSupported(true);
        return registrationBean;
    }

}

The application runs fine on  spring boot embedded tomcat  (gradle bootRun) but when I create the war and put the same in stand alone tomcat server the application always throws 404 for any of the routes configured.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by wilkinsona** [comment]
I’m going to re-open this as I think the documentation could be improved. It does state that WebFlux isn’t supported in a war deployment, but it only does so in a [section on static resources](https://docs.spring.io/spring-boot/docs/2.0.0.RELEASE/reference/htmlsingle/#boot-features-webflux-static-content). I think it should be stated more prominently.

**Comment by vikas-parihar** [comment]
I saw the comment that war deployment is not support with Spring boot 2.0.0. Is that something we expect down the line and have war deployment support with spring webflux.

**Comment by spencergibb** [comment]
> WebFlux isn’t supported in a war deployment

Boot 2 spring mvc and jersey still support war deployment.

**Comment by bclozel** [comment]
Cross posted on Stack Overflow here: https://stackoverflow.com/questions/49263561/spring-boot-2-with-webflux-and-router-functions-war-does-not-work-with-standalon

Mentioning this in the How To section about WAR deployment should work better.

**Comment by marioja** [comment]
@bclozel, @wilkinsona @snicoll This issue is closed but I would like to either re-open it or create a new one (you guys tell me).  The reason is that WebFlux is touted as the future and SpringBoot 2.0 the current Spring flag horse does not support it.  This means that people(me) who want to deploy the latest web technology are unable to do it on the open source web container of choice Tomcat.

**Comment by wilkinsona** [comment]
@marioja Thanks for the suggestion, but we have no plans to support WebFlux when deploying a war to an application server or servlet container. It you want to build a reactive web application, our recommendation is that you package it as a jar file with an embedded container (Netty by default) and deploy the self-contained jar without the need for a separately maintained application server or servlet container.

**Comment by marioja** [comment]
@bclozel, @wilkinsona @snicoll Alan, I know clearly that you guys do not have plans to support the deployment of a webflux war to a servlet container.  My point is precisely to request that such a feature is provided for the reason I mentioned in my April 30 comment.  You currently support a webflux WAR using springframework only (not spring boot).  My question is how to make that request and at the very least, maybe a rationale for not having plans to do this.

**Comment by bclozel** [comment]
First, I'd like to say that WebFlux is not the only future for web applications with Spring, but just a new alternative that Spring supports for specific use cases. Spring MVC is equally supported and important; in many cases, Spring MVC is still very relevant. You can also use `WebClient` within a war application with all the benefits of async handling and parallelization.

Now Spring Boot supports both war and jar deployments for Servlet-based applications. This allows Spring Boot applications to be deployed on all Servlet containers checking the minimum requirements. In the case of WebFlux applications, Servlet is not part of the contract. In some cases, Spring Framework relies on a Servlet adapter with the reactive HTTP layer, but we can also rely on native adapters (i.e. adapting directly to the native HTTP layer provided by the server).

Deploying a WebFlux application on a Servlet container means that the container must be Servlet 3.1+ (with async I/O enabled) and the deployment must not use blocking I/O APIs on Servlet. [Both contracts are exposed at the same level and are not obvious](https://www.youtube.com/watch?v=uGXsnB2S_vc). What it means for developers is that it's really easy to mix blocking infrastructure with the reactive application, or just misconfigure your deployment.

One of the main reasons behind war deployments is the ability to deploy several applications on the same container (and share resources, libraries, etc). Mixing blocking and non-blocking applications on the same server/resources is likely to cancel (or worse) the runtime benefits you're expecting from a non-blocking model.

Given that: 

* jar is the primary deployment target these days
* the default server of choice for WebFlux is Netty (which is not Servlet based)
* reactive and modern protocols like http/2 and RSocket work well together
* war deployments are more likely to be misconfigured in this case
* performance issues when multiple apps are deployed on the same container
* in my experience, the vast majority of developers willing to embrace the reactive paradigm already adopted the embedded server as a deployment model

With all that in mind, the cost/benefit analysis for this is just not worth it.

**Comment by marioja** [comment]
Brian, thanks for this very thorough explanation. If I may, I would like to add the following:

Even though WebFlux/Reactive is not the only future of web application it is certainly touted as the better choice for highly scalable workloads (according to Rossen Stoyanchev at QCon SF 2017).


One other big reason for WAR deployment is because most cloud services (except perhaps Pivotal understandably) have provided over the years extensive configurability for web application in containers.  Deploying an embedded container as a JAR does not expose the same level of support from the cloud providers.  See the amount of configuration you have available for an elastic beanstalk application in AWS and you will quickly see what I mean.

As for the issue of misconfiguring a tomcat container using blocking/non blocking at the same, this issue is in the hands of the users, not the framework and it is equally applicable to the spring framework which does support jetty and tomcat deployments.

I would propose that for all users and all use case, the cost/benefit is certainly worth it and since the underlying spring framework does support it, it is probably not such a big deal to add the correct autoconfiguration classes to support this.  Any thoughts?  Anyone?

**Comment by marioja** [comment]
@bclozel I just realized a) you were not cited so you may not have seen the previous post and b) it just dawn on me that although Spring framework does support webflux servlet deployment but since Spring boot is an opinionated framework I was just wondering if I could alter this opinion! :smirk:. I started a [Stackoverflow](https://stackoverflow.com/questions/56011850/webflux-and-spring-boot-on-servlet-3-1-container-like-tomcat) on that topic.
