### ISSUE TITLE
Support AND operator in yml profile matching

### ISSUE THREAD

**Issue by twicksell** [spring-projects/spring-boot#12469]
Similar to https://jira.spring.io/browse/SPR-12458, we would like ability for the yaml profile matching to follow AND semantics instead of OR. 

To disambiguate from the current behavior and not create a behavior change, it may be helpful to introduce a new name. Something like:

```
---
spring.allProfiles: profile1, profile2  #would like these applied only when both profiles are set
someProp: someValue
```

**Comment by philwebb** [comment]
In 2.0 we changed the way that YAML profiles are handled. We [now delegate](https://github.com/spring-projects/spring-boot/blob/efeede9f56b00a6cdab1aa5125c72c8e739d382f/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigFileApplicationListener.java#L411) to `Environment.acceptsProfiles` to determine when the document is include. I think as a result of this change, if SPR-12458 is fixed then Boot should just work.

I'll leave this one open since we should add some tests, but getting SPR-12458 fixed should be the priority.

**Comment by philwebb** [comment]
I missed the JIRA update from May 7. I've [added a comment to the Spring issue](https://jira.spring.io/browse/SPR-12458?focusedCommentId=158137&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-158137)

**Comment by twicksell** [comment]
Thanks, I also wouldn't oppose the `p2+p3` approach FWIW. Appreciate your help with this issue.
