### ISSUE TITLE
Binding failure with cloned arrays

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#12478]
This [sample](https://github.com/snicoll-scratches/ldap-urls-test) reproduces the [issue raised on SO](https://stackoverflow.com/questions/49276037/springboot-2-migration-configurationproperties-failed-to-bind-property-to-string).

Binding works fine if the array isn't cloned and breaks when it is.

**Comment by mbhave** [comment]
If there is a bound value, the `AggregateBinder` tries to get the existing value so that it can merge that with the bound value. The getter in the sample throws a NPE since `this.urls` is null. 

For Array types the merge just returns the bound value so getting the existing value is unnecessary. Maybe if we skip [this get](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/AggregateBinder.java#L63) for Array types this will work.
