### ISSUE TITLE
Spring Boot 2.0.0.Release won't generate foreign keys with JPA

### ISSUE THREAD

**Issue by jonathanborenstein** [spring-projects/spring-boot#12484]
In pre 2.0 Spring Boot, when you would use JPA and use annotations to map entities, using `spring.jpa.generate-ddl=true` would generate the schema.

It still generates the schema but no foreign keys are created.

When you take a look at MySQL workbench you see that no actual constraints exist. I tested the same sample project with 2.0 and 1.5.9. In 1.5.x the foreign keys are created.

**Comment by wilkinsona** [comment]
I think this is unlikely to be a Spring Boot bug as the schema is generated by Hibernate. Please provide a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) and we can take things from there.

**Comment by jonathanborenstein** [comment]
It appears to be a problem with some of the newer versions of hibernate. When using Spring Boot 2.0 and overriding the dependency to 5.0.12.Final (used in Spring Boot 1.5.9), the problem is fixed.

**Comment by wilkinsona** [comment]
Thanks for following up. I would guess the difference is related to MyISAM (which doesn't support foreign key constraints) and InnoDB (which does). Perhaps the default dialect that Hibernate uses with MySQL has changed? I'm going to close this as, as suspected, it appears to be due to Hibernate and not Spring Boot.

**Comment by llyer** [comment]
mark it.  same problem
