### ISSUE TITLE
How to generate description attribute from @ConfigurationProperties Class field

### ISSUE THREAD

**Issue by mercyblitz** [spring-projects/spring-boot#12505]
Question

How to generate description attribute from @ConfigurationProperties Class field？

As [Appendix B. Configuration Metadata](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor) mentioned :
> The processor picks up both classes and methods that are annotated with @ConfigurationProperties. The Javadoc for field values within configuration classes is used to populate the description attribute.

There is a class named `User` :
```java
public class User {

    /**
     * User Id
     */
    private Long id; 

    // other fields and setter/getter
}
```

and then exposes it as `@Bean` on method:
```java
    @Bean
    @Validated
    @ConfigurationProperties(value = "user", ignoreUnknownFields = false)
    public User user() {
        return new User();
    }
```

later `spring-boot-configuration-processor` will be added in pom.xml:
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
```

finally, to execute Maven compilation :
```
$ mvn clean compile
```

`META-INF/spring-configuration-metadata.json` file was generated , however `description` attribute can't be found in `properties` item ：
```json
{
  "hints": [],
  "groups": [
    // ...
  ],
  "properties": [
    // ...
    {
      "sourceType": "thinking.in.spring.boot.samples.api.domain.User",
      "name": "user.id",
      "type": "java.lang.Long"
    },
    // ...
}
```

Current project depends on Spring Boot 2.0.0.RELEASE, and bases on Java 8 and Maven 3.2.5. Is it an issue on `spring-boot-configuration-processor` ? If not , please tell me how to do , thanks in advance !

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
