### ISSUE TITLE
compile scope in spring boot 2 starter poms.

### ISSUE THREAD

**Issue by satishbotla** [spring-projects/spring-boot#12524]
Hello,

I am seeing that starting spring-boot 2.0, spring-boot-starter-aop pom has dependencies scoped "compile". While previous version(1.5.10) has them as default scope. Any specific reason why this is done?

**Comment by wilkinsona** [comment]
The default scope is compile so, semantically, there's no difference between the two. The actual pom files have changed due to, I think, our use of the Maven Flatten Plugin in the 2.0 build.

In the future, please ask this sort of question on Stack Overflow or Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
