### ISSUE TITLE
Conflicting load of properties file related to classpath

### ISSUE THREAD

**Issue by jcarbad** [spring-projects/spring-boot#12543]
In my Spring Boot 2 application I need to read a certain `Supranet.properties`  from where I should read a properties `Supranet.customField` if it is set, which will make reference to a package from where I'll later try to load some classes. 
By default, the properties file mentioned is under `src\main\resources` and the property is not set. When I try to load another external  `Supranet.properties` props file, located at the root of the project, with the variable set, it just would not work.
So far, I've tried: 
- passing it as argument (`--supranet.path=file:./Supranet.properties`)
- as @PropertySource
- adding it as an additional config location (`--spring.config.additional-location`)
- explicitly adding it to the classpath (through `java -cp`) 

The file does get read, and other related properties do get overwritten, nevertheless, that specific property won't work.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
