### ISSUE TITLE
my Aspect has two Pointcuts have Too bad 

### ISSUE THREAD

**Issue by SoberChina** [spring-projects/spring-boot#12570]
All right, I have a problem ,This is my logs Aspect. It's true that he has two Pointcuts .But every time I request the interface, I repeat 4 times. 
![image](https://user-images.githubusercontent.com/10227558/37704682-75916f34-2d34-11e8-9c61-3774259da65d.png)
![image](https://user-images.githubusercontent.com/10227558/37704896-387aae34-2d35-11e8-978b-6aae1ce3bc3d.png)
Thank you for pointing out the mistake.
This is my code 
![image](https://user-images.githubusercontent.com/10227558/37705200-323f8520-2d36-11e8-84e3-6ef92bd00247.png)
spring boot version 1.5.10.RELEASE

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by SoberChina** [comment]
all right. thanks
