### ISSUE TITLE
Deprecate @ConfigurationProperties#ignoreUnknownFields

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#12601]
`ignoreUnknownFields` allows to spot cases where a property on the target namespace was left unbound. It is an interesting feature with a serious limitation (#3445) that means we hardly use it in practice. 

We should consider deprecating it in the next feature release.

**Comment by snicoll** [comment]
Trying to come up with a deprecated message for this, I think it would be more fair to deprecate it when we tackle #10030

**Comment by thombergs** [comment]
I noticed that `ignoreUnknownFields=false` does not work when `ignoreInvalidFields` is set to `true`.

It seems that as soon as invalid fields are ignored, unknown fields are also ignored, no matter what the value of `ignoreUnknownFields`, which is not what I would expect.

Since `ignoreUnknownFields` will be deprecated, I didn't want to raise a new issue, but wanted to document it here in case anyone else stumbles upon this.

**Comment by philwebb** [comment]
@thombergs We're going to fix the issue you mention in #22308
