### ISSUE TITLE
actuator -> http trace -> timestamp is coming as json.  what could be the issue with code. 

### ISSUE THREAD

**Issue by saty-tech-master** [spring-projects/spring-boot#12610]
"timestamp": {
        "epochSecond": 1521839462,
        "nano": 180000000
      },

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
