### ISSUE TITLE
springboot tomcat is blocked when the tomcat running for some period of time?

### ISSUE THREAD

**Issue by 511098425** [spring-projects/spring-boot#12632]
in my server .I found tomcat running for some period of time ,it will blocked and log is missing. detail like this :  
Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in the request target...

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
