### ISSUE TITLE
Request timeout when Publisher that has subscribeOn(...) is returned from the controller (tomcat + WebTestClient)

### ISSUE THREAD

**Issue by myhau** [spring-projects/spring-boot#12647]
I think the best description of this issue is code, so please take a look at example project here: https://github.com/myhau/spring-boot-2-reactor-tomcat-issue
All you need to do is run `MainControllerTest`, all tests will fail with timeout, but when you change dependency `spring-boot-starter-tomcat` to `spring-boot-starter-jetty` in `pom.xml` it'll work.
Also, running application and doing requests from postman works (`200`, no timeouts) so this might be some problem with `WebTestClient`.

**Comment by myhau** [comment]
I've also added some logs (`tomcat.log` and `jetty.log`) with log level `TRACE` for `reactor.ipc.netty` and for `org.springframework.http` packages.
Also, I've been debugging this issue some time ago and I'm sure that (and after comparing logs one can easily see that) `RequestBodyPublisherReadListener.onAllDataRead` is never called in tomcat case.

**Comment by bclozel** [comment]
Hi @myhau and thanks for the very detailed report (and repro project).

A few interesting facts here:

1. This is only happening with Tomcat and not Jetty
2. This doesn't not happen anymore (or less often) if you remove the scheduling operator in your controllers
3. As the logs show, the request body is read but not fully consumed by WebFlux, so the `Mono<Void>` is never completed by the state machine

This leads me to think that this issue has to do with the Servlet adapter layer with Servlet 3.1 async I/O (or, a bug in Tomcat). The exact class that you were debugging. So your were on the right track!

At that point this definitely rang a bell and I found the following Spring Framework issue: [SPR-16521](https://jira.spring.io/browse/SPR-16521).

More specifically, here's what happened:
* the adapter reads the request body in one shot since it's not very large
* the "all data is read" callback is not called in that case by Tomcat, triggering this issue

Updating the repro project to `2.0.0.BUILD-SNAPSHOT` fixes the issue, and it will be released with Spring Framework 5.0.5.RELEASE and Spring Boot 2.0.1.RELEASE.

Again, thanks for the report and sorry you had to dig into this for quite a long time :-(

**Comment by myhau** [comment]
@bclozel For me updating to `2.0.1-BUILD-SNAPSHOT` does not fix the issue (neither to `2.0.0-BUILD-SNAPSHOT`) (I'm using `https://repo.spring.io/snapshot`). Should I also add some other dependency ?
