### ISSUE TITLE
@Autowired is still performed even though the configuration is conditional

### ISSUE THREAD

**Issue by czubin** [spring-projects/spring-boot#12670]
Currently using spring boot 1.5.10.

When using a conditional configuration class, as shown below. Then the
autowired bean will always be injected.

I have to put  `@Autowired(required=false)` when mocking is turned off. Otherwise spring will fail to load the application context. 

Note: The bean, `mockService`, will not be instantiated when mock property is turned off. Only the autowiring stays active.

```java
@Configuration
@ConditionalOnProperty(prefix = "backend", name = "mock", havingValue = "true")
public class MockConfiguration {
     @Autowired
     private MockRepo mock;
 
     @Bean
     public MockService mockService() {
         return new MockService(mock);
     }
}
 ```

**Comment by snicoll** [comment]
@czubin that's working as expected. Conditions impact the creation of beans and does not disable the request to inject dependencies. Unrelated but you're creating a cycle in your configuration here.

**Comment by czubin** [comment]
@snicoll Thanks for the quick response. The code is just an example

**Comment by wilkinsona** [comment]
@snicoll If `backend.mock=false`, I’d expect `MockConfiguration` to back off and for there to be no injection of `MockRepo` or creation of `MockService`. What have I missed?

@czubin Your example and description aren’t clear to me. @snicoll will probably be able to explain what I’ve missed, but providing a minimal and complete example (rather than just a single snippet of code) is a good way to avoid this sort of confusion.

**Comment by snicoll** [comment]
> What have I missed?

Nothing, I can easily blame my lack of sleep/coffee. The conditions should indeed prevent the class to be processed at all. @czubin please share a sample that we can run ourselves that demonstrates the behaviour you've described.

**Comment by czubin** [comment]
[Archive.zip](https://github.com/spring-projects/spring-boot/files/1859339/Archive.zip)

I have narrowed down the problem. We're using xml configuration to load java configuration beans (legacy project). This will behave almost the same as pure javaconfig. Except the @Configuration class will also be treated like a bean.

Javaconfig will either allow the configuration class as a bean or a proper configuration. The behaviours won't be mixed.

I attached all the testcases in a zip. I don't know if this even applies to spring boot or just spring in general.

**Comment by philwebb** [comment]
I'm pretty sure that `@Condition` annotations aren't considered when a `@Configuration` is imported via XML. You could try adding an extra layer of indirection so that conditions are only on configurations imported via `@Import`:

```xml
<beans>
    <bean class="tpack.ConfigOneXml"/>
</beans>
```

```java
@Configuration
@Import(ConfigOne.class)
public class ConfigOneXml {
}
```

You might also want to [raise a bug with Spring Framework](http://jira.spring.io) to see if they can fix the underlying issue.

To be honest, I think you'd be best off removing the `@Configuration` class imports from your XML. It's generally best to start from `@Configuration` classes and import specific bits of XML when needed. Longer term, you should try to move away from XML entirely because it doesn't work as well as Java configuration in Spring Boot apps.
