### ISSUE TITLE
how to pass environment variable spring.main.web-application-type=SERVLET to run docker image

### ISSUE THREAD

**Issue by imwower** [spring-projects/spring-boot#12673]
when I use docker run command, the variable "SPRING_PROFILES_ACTIVE" is right, but "SPRING_MAIN_WEB-APPLICATION-TYPE" does not work, how to pass "SPRING_MAIN_WEB-APPLICATION-TYPE" to dokcer image?

sample shell is:

`sudo docker run -d -e SPRING_PROFILES_ACTIVE=product -e SPRING_MAIN_WEB-APPLICATION-TYPE=SERVLET -e SERVER_PORT=6789 --network mongo_network`

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by imwower** [comment]
here is Stack Overflow link, FYI:
[](https://stackoverflow.com/questions/49551377/how-to-pass-environment-variable-spring-main-web-application-type-servlet-to-run)
