### ISSUE TITLE
server.servlet.path Configuration is invalid

### ISSUE THREAD

**Issue by lailaiququ** [spring-projects/spring-boot#12747]
Question:

Spring-boot 2.0.0.RELEASE Version
1、server.servlet.path=*.html   Configuration is invalid
2、server.servlet.path=/  The default is no problem

thank you very much to solve my confusion

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
