### ISSUE TITLE
Bean Validation not working on kotlin projects

### ISSUE THREAD

**Issue by giovannicandido** [spring-projects/spring-boot#12752]
Using a class with bean validation and kotlin is not working

The class:

```
class TestClass(
        @NotEmpty
        @Email
        val email: String
) {
    override fun toString(): String {
        return email
    }
}
```

With the controller:

```
@RestController
@RequestMapping("/test")
class TestCtrl {
    val logger = LoggerFactory.getLogger(TestCtrl::class.java)

    @RequestMapping(method = [RequestMethod.POST])
    fun test(@RequestBody @Valid test: TestClass) {
         logger.info(test.toString())
    }
}
```

Should validate and not call the function. This test should pass:

```
@RunWith(SpringRunner::class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
internal class TestCtrlTestClass {
    @Autowired
    lateinit var objectMapper: ObjectMapper

    @Autowired
    lateinit var restTemplate: TestRestTemplate

    @LocalServerPort
    private val port: Int = 0

    var headers = HttpHeaders()


    @Test
    fun test1() {
        val test = TestClass("shouldnotpass")
        val string = objectMapper.writeValueAsString(test)

        val entity = HttpEntity<TestClass>(test, headers)

        val response = restTemplate.exchange(
                createURLWithPort("/test"),
                HttpMethod.POST,
                entity,
                TestClass::class.java
        )

        assertThat(response.statusCode).`isEqualTo`(404)

    }

    private fun createURLWithPort(uri: String): String {
        return "http://localhost:$port$uri"
    }
}
```

**Expected behavior:**  Controller validates json
**Current behavior:** Method is called

Project to test: https://github.com/giovannicandido/restvalidationtest

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

A [quick search on StackOverflow pointed to a similar issue](https://stackoverflow.com/questions/35847763/kotlin-data-class-bean-validation-jsr-303); I don't think this has anything to do with Spring Boot.

**Comment by giovannicandido** [comment]
Looks like a bug to me. Anyway, I will try stack-overflow fist.
