### ISSUE TITLE
how to use webflux fileupload

### ISSUE THREAD

**Issue by mylovetop** [spring-projects/spring-boot#12754]
hi, i use spring-boot-starter-webflux of spring boot 2.0  ,  how to fileupload in webflux.

other ,  i only  use flux  in controller ,  the servcie the same as before not use flux , what 's wrong with thar?

thanks!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
