### ISSUE TITLE
Clarify that @QuartzDataSource is the preferred mechanism for customizing Quartz's DataSource

### ISSUE THREAD

**Issue by asakchris** [spring-projects/spring-boot#12780]
When I try to inject non primary data source to scheduler factory using SchedulerFactoryBeanCustomizer, Quartz auto configuration overrides this customization with primary data source. Refer this [stack overflow qusetion](https://stackoverflow.com/questions/49637490/spring-boot-2-0-quartz-use-non-primary-datasource#)

**Comment by wilkinsona** [comment]
Thanks for the report. I think the problem is that Boot itself is setting the `DataSource` using a `SchedulerFactoryBeanCustomizer` and, as it's unordered, there's nothing to stop it running after you customiser and overwriting its changes.

I think you can work around the problem by not setting `spring.quartz.job-store-type` and then configuring the `DataSource` and `PlatformTransactionManager` in your customiser.

**Comment by mbhave** [comment]
> I think you can work around the problem by not setting spring.quartz.job-store-type and then configuring the DataSource and PlatformTransactionManager in your customiser.

@wilkinsona Would that be sufficient? The `DataSource` in [QuartzDataSourceInitializer](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.java#L153) might also be a problem.

**Comment by asakchris** [comment]
@mbhave this is working, already verified. Let me update it in stack overflow.

**Comment by mbhave** [comment]
Thanks for verifying, @asakchris.

**Comment by wilkinsona** [comment]
Well spotted, @mbhave. You're right, the data source initialiser will be a problem unless schema initialisation has been disabled. The question on Stack Overflow has initialise-schema set to `never` which, I think, explains why my suggestion works.

It's an interesting problem with the customiser as it means that, even if we fix the ordering problem, it can only be used to configure a custom DataSource in some scenarios.

**Comment by mbhave** [comment]
Thanks for clarifying that, @wilkinsona. I had missed the `never` in the SO post. It does look like there are a few cases we'd need to consider when fixing this bug.

**Comment by mbhave** [comment]
@wilkinsona It seems like #12755 should solve this?

**Comment by wilkinsona** [comment]
I'm not sure. I'm struggling to remember what I'd figured out when I wrote "even if we fix the ordering problem, it can only be used to configure a custom DataSource in some scenarios" about the customiser.

**Comment by wilkinsona** [comment]
A problem with using the customiser to configure that `DataSource` is that, as @mbhave mentioned above, the initialiser will still be a problem as it'll use the wrong `DataSource`. I think this is what I meant when I said it would only work in some scenarios.

There are a few thinks that I think we should do here:

1. Order Boot's `SchedulerFactoryBeanCustomizer` so that users' customizers can be position before and after it.
2. Update the javadoc of `SchedulerFactoryBeanCustomizer` to recommend the use of `QuartzDataSource` for `DataSource` customisation.
3. Update the documentation to mention `@QuartzDataSource` as the preferred mechanism for configuring Quartz's data source.
