### ISSUE TITLE
After adding the @RequestMapping(value = "/**") controller does not match the resource file correctly

### ISSUE THREAD

**Issue by xiaomei1029** [spring-projects/spring-boot#12798]

**Comment by bclozel** [comment]
(just updated the title, courtesy of Google Translate).

In your case (if I understand correctly), adding a Controller mapping to `/**` prevents regular resource handling from working. This is working as expected, since the resource handler mapping (see `ResourceHandlerRegistry `) is ordered after the one for `@RequestMapping` annotations (see `WebMvcConfigurationSupport::requestMappingHandlerMapping`.

Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/) anyway. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
