### ISSUE TITLE
@Validated as default

### ISSUE THREAD

**Issue by jjangga0214** [spring-projects/spring-boot#12795]
`@Validated` is required to make validators (such as `javax.validation.constraints.*`) works. However, in my opinion, it might be more natural that `@Validated` is set as default, for example, to controllers. I think the `@Validated` should be implicit default and way to deactivate it should be explicit.

**Comment by bclozel** [comment]
Thanks for the report, but this is the Spring Boot issue tracker.
The point you're referring to (validation support in Spring MVC) belongs in the [Spring Framework issue tracker](https://jira.spring.io/).

Anyway I doubt the Spring community will agree on that as this would mean 1) changing a default that's been there for quite a long time 2) requiring a validation library as a mandatory dependency for all Spring MVC applications 3) forcing an opinion on everybody. Spring Boot already has an opinion about this, since we do bring a validation dependency with the `spring-boot-starter-web`.

I'm closing this issue as Spring Boot can't change this behavior.
Thanks!
