### ISSUE TITLE
I can't get http sevlet response from backend

### ISSUE THREAD

**Issue by Bryanjss** [spring-projects/spring-boot#12845]
Question

Hello, I am using springboot 2.0.0.RELEASE, I just migrate from springboot 1.5.1

I have below code like:
public class CustomAuthenticationEntryPoint
        extends BasicAuthenticationEntryPoint
{
    public void commence(HttpServletRequest request,
            HttpServletResponse response, AuthenticationException authException)
                    throws IOException, ServletException
    {
    	response.sendError(HttpServletResponse.SC_UNAUTHORIZED,
               authException.getMessage());
    }
}

above code will filter the bad login and send error to frontend WEB client. in springboot 1.5.1, the error in the response will contain JSON body, such as:  

{"timestamp":1523253790780,"status":401,"error":"Unauthorized","message":"Autentication failed.","path":"/login"}

but when I use springboot 2.0, I can't get HTTP response, and I got error complain the error= null from the web client, I don't know where to cause the problem.
the I use tomcat-embed 8.5.28 and jackson jar version for 2.9.4

thanks in advance.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Bryanjss** [comment]
Thank you bclozel,
I have posted this in StackOverflow with link:
https://stackoverflow.com/questions/49793684/i-cant-get-http-sevlet-response-from-backend-with-springboot-2-0
