### ISSUE TITLE
When a WebSocket handler path matches a RequestMapping, WS connection is not established.

### ISSUE THREAD

**Issue by nagyzsolthun** [spring-projects/spring-boot#12840]
If I have both a RequestMapping and a WebSocket endpoint set for the same path, WS connection is not established. Example project: https://github.com/nagyzsolthun/spring-websocket-requestmapping-error

Is there a way to ignore WS connection requests in a RequestMapping?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
