### ISSUE TITLE
Validation on controllers with BasePathAware is not working

### ISSUE THREAD

**Issue by giovannicandido** [spring-projects/spring-boot#12863]
springBootVersion = '2.0.0.RELEASE'

I'm not sure where to post this bug report, maybe a spring data rest bug.

Example in https://github.com/giovannicandido/restvalidationtest

Suppose we have two almost identical controllers:

```java
@RestController
@RequestMapping("/test")
class TestCtrl {
    val logger = LoggerFactory.getLogger(TestCtrl::class.java)

    @RequestMapping(method = [RequestMethod.POST])
    fun test(@RequestBody @Valid test: TestClass) {
         logger.info(test.toString())
    }
}
```

And

```java
@RestController
@BasePathAwareController
@RequestMapping("/test-bug")
class TestCtrlBug {

    val logger = LoggerFactory.getLogger(TestCtrl::class.java)

    @RequestMapping(method = [RequestMethod.POST])
    fun test(@RequestBody @Valid test: TestClass) {
        logger.info(test.toString())
    }
}
```

The only difference is the use of `@BasePathAwareController` 

For completeness `TestClass` has a Email validation:

```java
class TestClass(
        @get:NotEmpty
        @get:Email
        val email: String
) {
    override fun toString(): String {
        return email
    }
}
```

Validation trigges only without `@BaseAwareController` annotation.

The repository has Test cases

Examples are in kotlin lang

**Comment by wilkinsona** [comment]
Thanks for the sample.

The difference in behaviour is due to Spring Data REST. It creates a `ConfigurableWebBindingInitializer` and does not configure it with a `Validator`:

https://github.com/spring-projects/spring-data-rest/blob/3438d168dfe962c82c30aa444c1fdaee6578066b/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.java#L582-L583

By contrast, Spring MVC creates the initializer and configures it with a `Validator`:

https://github.com/spring-projects/spring-framework/blob/19ac212868a97eea66d7057078f2e304eaf01b3b/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java#L603-L605

The lack of validator in the Spring Data REST case means that, as you have observed, the `@Valid` annotation has no effect. I'm not sure if it's intentional that Spring Data REST does not configure a validator, but this will need to be addressed by them rather than Spring Boot.

@giovannicandido If you would like to pursue this, please chat with the Spring Data team in Gitter or open a [Spring Data REST JIRA ticket](https://jira.spring.io/browse/DATAREST).
