### ISSUE TITLE
Document that default property values for certain types are not detected by the annotation processor

### ISSUE THREAD

**Issue by lchayoun** [spring-projects/spring-boot#12874]
When using properties class which contains list with 2+ items the default value is null

**Comment by snicoll** [comment]
@lchayoun as I've indicated on #12873, that description is not precise enough to figure out what you're reporting. I am not sure I understand the 2+ items so sharing a sample would be ideal. Thanks.

**Comment by snicoll** [comment]
Thanks for the sample (though what I mean is something I can run rather than something I have to copy/paste from some comment. I misread your original comment (I read it was working with 2 elements but not more than 2). 

We don't support everything as we need to figure out what the type is. You'll have to [write manual meta-data for the time being](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-additional-metadata).

**Comment by wilkinsona** [comment]
The annotation processor would need to understand things like `new ArrayList<>(Arrays.asList("a", "b"))` or, if using something outside of the standard library, things like Guava's `newArrayList` as shown above. It would be quite complex to support even the JDK's standard possibilities and this would then further raise expectations that things like Guava, Apache Commons, etc would be supported too. Having consider this, unfortunately we think that the complexity that would be introduced to fix this will outweigh the benefit. Instead, manual metadata should be provided in the cases where a list or set property has a non-empty default value.

**Comment by wilkinsona** [comment]
On seconds thoughts, this should become a documentation issue.

**Comment by snicoll** [comment]
As @mbhave suggested, let's broaden the scope of this issue to document that default values for Enums aren't detected either. We should explain the fallback strategy of documenting this in manual metadata with a concrete example.

**Comment by snicoll** [comment]
The default value for the collection should be a json array.
