### ISSUE TITLE
Spring 2.0.1 - Rest Service - Getting random HTTP status 400

### ISSUE THREAD

**Issue by jgarbora** [spring-projects/spring-boot#12913]
I could not find why is the cause ... but I am getting randomly Http 400, param not present:

`Required String parameter 'id' is not present. `

I am getting this in Postman and different Rest Client,

this is my code :

 ```
@RequestMapping(path = "/borrower", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
   @CrossOrigin(origins = "*")
    public ResponseEntity<?> borrower(@RequestParam(value = "id") String id, @RequestHeader("Authorization") String token)  throws Exception {

           // some business code
       return ResponseEntity.ok().build();
    }
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
