### ISSUE TITLE
Spring Boot with DB2 HADR ACR config

### ISSUE THREAD

**Issue by walkwolf** [spring-projects/spring-boot#12917]
Question

Is there a solution that is configured in the application.properties file?

DB2 HADR using ```clientRerouteAlternateServerName, clientRerouteAlternatePortNumber,  enableClientAffinitiesList``` to indicate alternate server info.

I tried use below code to config datasource.
```
	@Bean
	public DataSource initds(){
		Properties p = new Properties();
		p.setProperty("user", "user");
		p.setProperty("password", "password");
		p.setProperty("clientRerouteAlternateServerName", "172.30.1.60,172.30.1.61");
		p.setProperty("clientRerouteAlternatePortNumber", "53000,53000");
		p.setProperty("enableClientAffinitiesList", "1");

		DriverManagerDataSource dmds  = new DriverManagerDataSource();
		dmds.setDriverClassName("com.ibm.db2.jcc.DB2Driver");
		dmds.setConnectionProperties(p);
		dmds.setUrl("jdbc:db2://172.30.1.60:53000/dbsam");

		return dmds;
	}
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
