### ISSUE TITLE
How can a queue be bound to a thread by use @RabbitListener ?

### ISSUE THREAD

**Issue by qyvlik** [spring-projects/spring-boot#12954]
# Q: How can a queue be bound to a thread by use @RabbitListener ?

```
@RabbitListener(queues = {"queue1", "queue2"})
public void receive(String message) {
    logger.info("thread id:{}, message:{}", Thread.currentThread().getId(), message);
}
```

I found that `queue1` and `queue2` use the **same thread**.

I want to do the `queue1` and `queue2`, which occupy **different threads**.

Tx.

**Comment by qyvlik** [comment]
spring-boot version:

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.0.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>
    </dependencies>
```

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by qyvlik** [comment]
look here https://stackoverflow.com/questions/49992279/spring-boot-rabbitlistener-how-can-a-single-queue-be-bound-to-a-single-thread
