### ISSUE TITLE
stomp info call interception

### ISSUE THREAD

**Issue by am-kram** [spring-projects/spring-boot#12959]
I am using springboot 2 (same thing applies to earlier versions of spring boot)
How can one intercept the "/info" call referenced here?
https://docs.spring.io/spring/docs/5.0.4.RELEASE/spring-framework-reference/web.html#websocket-fallback-sockjs-overview

Things like the HandshakeInterceptor occur on the websocket call which occurs after the "/info" call and I would like to understand how to have an interceptor for that. I've tried the classic webmvc interceptor - it does not seem to execute for the /info calls.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by am-kram** [comment]
@bclozel  : thanks - I tried looking at other places this looks like a genuine bug - i'll try and create a repo with a sample project to show case this issue and make it reproducible.
