### ISSUE TITLE
Spring boot Maven MultiModule Rest api Call

### ISSUE THREAD

**Issue by NABEEL-AHMED-JAMIL** [spring-projects/spring-boot#12969]
Hi!
All I'm new on Spring boot i have a question currently i'm working with the spring boot multi modeule project.
I have 3 spring boot project.

like a,b,c
each have rest-controller like below
--------------------Project-A----------------------------------
	@RequestMapping(value = "/demoa")
	public String demoa() {
		return "demoa";
	}
--------------------Project-B----------------------------------
	@RequestMapping(value = "/demob")
	public String demob() {
		return "demob";
	}
--------------------Project-C----------------------------------
	@RequestMapping(value = "/democ")
	public String democ() {
		return "democ";
	}
--------------------------------------------------------------------
I add the both (B, C) project as a mavend dependency in Project(a) and compiler all
<dependency>
        <groupId>com.b</groupId>
	<artifactId>demob</artifactId>
	<version>0.0.1-SNAPSHOT</version>
</dependency>
<dependency>
	<groupId>com.c</groupId>
	<artifactId>democ</artifactId>
	<version>0.0.1-SNAPSHOT</version>
</dependency>
----------------------------------------------------------------------
after that i run my project like "mvn Spring-boot run" it run on 8080.
When i call the "Rest /demoa" it give me the response while when i try to call other rest it show these
error below 
    "timestamp": "2018-04-25T14:47:56.816+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/demob"
}
-----------------------------------
My Question is how i get the response of both 2 api while runing the proejct "A"

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by NABEEL-AHMED-JAMIL** [comment]
Hi! @snicoll thanks for replay. I found the solution actually i miss the dependency in **web module pom**
look this blow:- link
https://github.com/NABEEL-AHMED-JAMIL/pdftest/tree/master/multi-mudule  
basically maven multi module pattern same like **onion multi layer**
