### ISSUE TITLE
I am new in spring boot. How to signup with facebook and gmail using spring boot 2.0.1.RELEASE, Please reply, if having any example please share

### ISSUE THREAD

**Issue by varunReactiveworks** [spring-projects/spring-boot#12967]

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
