### ISSUE TITLE
Spring initializer Kotlin Project Compile Error

### ISSUE THREAD

**Issue by qualityking** [spring-projects/spring-boot#12978]
Hi Team,
I have used a very simple option like 

Gradle Project 
Kotlin 
2.01

Rest everything else is same 

I did import this project in intellij latest community edition gradle build is working fine 
but when i am trying to run this project it is giving error 

Error:(11, 5) Kotlin: Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

I am no where using Java 1.6, 

please help, the spring boot, does not boot

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
