### ISSUE TITLE
spring.resources.* doesn't work when customize RequestMapping

### ISSUE THREAD

**Issue by h920526** [spring-projects/spring-boot#13009]
Hi team:

Spring Boot 2.0.1
JDK 1.8.0_111
OS: Win7 64bit

I need to customize my own request mapping
```
@Configuration
public class WebConfig extends WebMvcConfigurationSupport {
    @Override
    protected RequestMappingHandlerMapping createRequestMappingHandlerMapping() {
        return new ApiVersionRequestMappingHandlerMapping();
    }
}
```
but spring.resources.* and spring.mvc.* doesn't not work anymore
```
application.properties
    spring.resources.static-locations=file:public/
    spring.mvc.async.request-timeout=1800000
    ...etc
```
log => No mapping found for HTTP request with URI [/hihi.htm]

I think the problem is
```
org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration.java
@ConditionalOnMissingBean(WebMvcConfigurationSupport.class)
```
but I want to auto configure by spring boot it's self

And then, I try this, but It still not work, too.
```
@Primary
@Order(0)
@Configuration
public class WebConfig extends EnableWebMvcConfiguration {

    public WebConfig(ObjectProvider<WebMvcProperties> mvcPropertiesProvider, ObjectProvider<WebMvcRegistrations> mvcRegistrationsProvider,
            ListableBeanFactory beanFactory) {
        super(mvcPropertiesProvider, mvcRegistrationsProvider, beanFactory);
    }

    @Bean
    @Primary
    @Order(0)
    @Override
    public RequestMappingHandlerMapping requestMappingHandlerMapping() {
        return new ApiVersionRequestMappingHandlerMapping();
    }

    @Override
    protected RequestMappingHandlerMapping createRequestMappingHandlerMapping() {
        return new ApiVersionRequestMappingHandlerMapping();
    }
}
```
thanks a lot

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Also, please take a look at [the reference docs for Spring MVC auto-configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-auto-configuration).
