### ISSUE TITLE
Presence of persistence.xml prevents from named queries being found in orm.xml during testing

### ISSUE THREAD

**Issue by desmethans** [spring-projects/spring-boot#13024]
When a (even minimal) persistence.xml is present, a test does not find a named query in orm.xml.
You can find a project which demonstrates the problem on https://github.com/desmethans/ormxml.git

Remarks:

1. Production code finds the named query (see class OrmxlApplication).
2. When you remove persistence.xml, the test runs fine.
3. When you create a META-INF folder in src/test/java, and you copy orm.xml in this folder, the test runs fine. This is of course not the good way to fix the problem.
4. I have tested this with with Maven 3.5.3, also with Eclipse Oxygen.3a Release (4.7.3a) and also with NetBeans 8.2, on a Windows 10 machine.

**Comment by wilkinsona** [comment]
Thanks for the sample.

The difference in behaviour is due to different root URLs for the persistence units that are involved. There are two persistence units: `test` and `default`. In both cases, the root URL of `test` points to `target/classes`. In the application case, the root URL of `default` points to `target/classes`, but in the test case it points to `target/test-classes`. This happens because of the logic in `DefaultPersistenceUnitManager.determineDefaultPersistenceUnitRootUrl()`. It uses the root of the classpath which is `target/test-classes` when running a test.

The problem can be avoided by renaming your persistence unit so that it's called `default` rather than `test`.

It may be possible to do something more to improve this so that a persistence unit named `test` will also work, however all the code that is involved is part of Spring Framework rather than Spring Boot. If you would like to pursue this, please open a [Spring Framework JIRA](https://jira.spring.io/browse/SPR) ticket.
