### ISSUE TITLE
Jackson Mapper doesnt preserve LinkedHashMap insertion order 

### ISSUE THREAD

**Issue by Canos** [spring-projects/spring-boot#13096]
I'm trying to get a json Map preserving the insertion order
Spring Boot version 1.5.12

```java
@GetMapping(value="/")
public ResponseEntity<Map<Integer,String>> getFooTest(){
		
	Map<Integer,String> map = new LinkedHashMap<>();		
	map.put(3, "3");
	map.put(2, "2");
	map.put(1, "1");

	return new ResponseEntity<>(map, HttpStatus.OK);	
}
```
Response is wrongly ordered asc:
```json
{
    "1": "1",
    "2": "2",
    "3": "3"
}
```

As far as I know, is not jackson related issue since that example is working:
```java
@Test
public void test_LinkedHashMap() throws JsonProcessingException{
	Map<Integer,String> map = new LinkedHashMap<>();
	
	map.put(3, "3");
	map.put(2, "2");
	map.put(1, "1");
	String res = new ObjectMapper().writeValueAsString(map);

	log.info("res:"+res);
}
```

My Jackson configuration is
```
spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.mapper.sort-properties-alphabetically=false
spring.jackson.serialization.order-map-entries-by-keys=false
```

**Comment by Canos** [comment]
Excuse me it's a matter of javascript / browser, i was using postman (which use Chrome behind the curtains)

```bash
$ curl http://localhost:7788/
{"3":"3","2":"2","1":"1"}
```

**Comment by ganeshbhargav** [comment]
This problem is not related to Jackson Mapper
Postman gives the return JSON in the body tab, which is returned in the same order as LinkedHashMap, but while printing it on the screen, postman does pretty print by default which changes the order. You can see the actual output by clicking on raw in the result box in postman
This is output for my case using pretty print.
![image](https://user-images.githubusercontent.com/19564121/60839190-26d06700-a192-11e9-890c-64429d2b27d2.png)

The is output in order(click on raw)
![image](https://user-images.githubusercontent.com/19564121/60839222-3d76be00-a192-11e9-915a-e2ad99b000b7.png)
 
The result is in order as expected in raw. You can use it for furthur processing
