### ISSUE TITLE
User new Springboot version 2.0.1. The old method is can not work anymore!

### ISSUE THREAD

**Issue by hanzhenchaoGit** [spring-projects/spring-boot#13111]
After the spring boot version is upgraded to 2.0.1, it is found that the code of the mongodb has changed, so that you can use GridFsTemplate.find () to get a file, and the returned GridFsFile can be written to OutPutStream in writeTo, and with <img/> in HTML, how to implement the new version of the picture taken in the display mongodb. What? The GridFSFile returned by the new version of find method can only get some information such as the size of the file object, and so on, and do not know how to return to the front page to display it.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
