### ISSUE TITLE
Status code 404 turns into status code 406 when accept header is put to application/xml

### ISSUE THREAD

**Issue by desmethans** [spring-projects/spring-boot#13163]
When your application gets a request and throws a `ResponseStatusException(HttpStatus.NOT_FOUND)` the response has a status code `404` and a JSON body when no accept header is provided.

When your application gets a request and throws a `ResponseStatusException(HttpStatus.NOT_FOUND)` the response has a status code `404` and a JSON body when the accept header is put to `application/json`

When your application gets a request and throws a `ResponseStatusException(HttpStatus.NOT_FOUND)` the response has a status code `406` and no body when the accept header is put to `application/xml`.

A demo can be found on https://github.com/desmethans/responsestatusexceptionboot.git
and can be seen with `curl http://localhost:8080/persons/2 --header "accept:application/xml" -i`

A Spring application without Spring boot does not have this problem as demoed on https://github.com/desmethans/responsestatusexception.git

**Comment by wilkinsona** [comment]
Thanks for the sample. The difference in behaviour is caused by Spring Boot's white label error page which aims to return something more useful out of the box than the empty body that you get with your Spring Framework-based example. With no `Accept` header, Boot's error controller will return JSON:

```
{"timestamp":"2018-05-14T13:28:46.854+0000","status":404,"error":"Not Found","message":"Response status 404","path":"/persons/2"}
```

It can also return HTML:

```
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon May 14 14:30:24 BST 2018</div><div>There was an unexpected error (type=Not Found, status=404).</div><div>Response status 404</div></body></html>
```

When you ask for XML, an attempt is made to convert the same POJO that produces the above JSON response into XML. You application does not include any dependencies that are capable of producing XML from a POJO so Spring MVC deems the requested media type to be unacceptable and responds with a 406.

You can disable `ErrorMvcAutoConfiguration` to restore embedded Tomcat's default behaviour. This will leave you with a 404 response to a request that only accepts `application/xml` but it will have an HTML body.

The ideal would, perhaps, be to respond with an empty body if the error controller's response cannot be written in an acceptable media type. However, I'm not sure that it's possible with Spring MVC.

@bclozel knows more about this than I do so he may have some suggestions.

**Comment by wilkinsona** [comment]
Thank you, @bclozel.

**Comment by TobiasPfeifer** [comment]
@bclozel I have a similar problem.
A Controller is registered for path `/api/test` that produces `text/csv`. It has a GET-mapping to `/existing`
When a client calls `/api/test/non_existing` the response has a status code 406 and no body.
In this case I would expect to get a response with status code 404 and no body.

I can follow the points you gave if a client queries an url that is mapped, but the accept-header isn't matching. However I think in this case when there is no mapping the 404 should take precedence with an empty body.

Is there a way to work around this issue without getting a html body but maybe an empty body?

**Comment by bclozel** [comment]
@TobiasPfeifer I you believe this is a bug, please create a new issue with a project reproducing the problem. If this is more of a question, please create a StackOverflow question and feel free to point to it from here. In all cases, a description is not enough and a working sample is always better.

**Comment by wangjingfei** [comment]
> @TobiasPfeifer I you believe this is a bug, please create a new issue with a project reproducing the problem. If this is more of a question, please create a StackOverflow question and feel free to point to it from here. In all cases, a description is not enough and a working sample is always better.

@bclozel I've encountered the same problem. Is there any issues or StackOverflow pointing here? I'd like to know if it is fixed and when. Thanks

**Comment by bclozel** [comment]
@wangjingfei do you have a sample I can take a look at? If you believe this is a bug, please create a new issue with a sample application reproducing the problem.
