### ISSUE TITLE
SpringBootTest javax.validation.ValidationException

### ISSUE THREAD

**Issue by ekafeel** [spring-projects/spring-boot#13228]
I am testing my annotated javax validations. They work fine in the application with `@Valid` annotation on the method argument. but when I try to test them by manually build the validation factory using

```JAVA
Validation.buildDefaultValidatorFactory()
```

I get the following error.

> javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead

After getting this error I added `compile "org.glassfish:javax.el:3.0.0"` in my gradle file and it started working. Why, the validations are working in the application without requiring the `org.glassfish:javax.el` but requires when manually building the Validation factory?

**Comment by wilkinsona** [comment]
I suspect it’s due to a difference between your runtime classpath and test runtime classpath. Unfortunately I can’t tell for sure as you haven’t described your application in that level of detail. If you’d like to follow up on this, please ask a question on Stack Overflow or come and chat on Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
