### ISSUE TITLE
Why spring task:annotation-driven's exception-handler is not configured on the task:executor annotation

### ISSUE THREAD

**Issue by zui-coding** [spring-projects/spring-boot#13220]
I have two task:executor annotation:
  `
    
    <task:executor id="asyncExecutor"
                   pool-size="5-100"
                   keep-alive="120"
                   rejection-policy="CALLER_RUNS"
                   queue-capacity="1000"/>

    <task:executor id="otherExecutor"
               pool-size="5-20"
               keep-alive="120"
               rejection-policy="CALLER_RUNS"
               queue-capacity="100"/>
    <bean id="asyncExceptionHandler" class="com.xx.xx.xx.xx.common.AsyncExceptionHandler"/>

    <task:annotation-driven executor="asyncExecutor" exception-handler="asyncExceptionHandler"/>
`

I want two `task:executors` to use the same `exception-handler`. How can i do?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by zui-coding** [comment]
I think this design is not reasonable

**Comment by wilkinsona** [comment]
If you have a proposal for how the design could be improved, please open a Spring Framework [JIRA ticket](https://jira.spring.io/browse/SPR).
