### ISSUE TITLE
Getting git.properties data to '/info'

### ISSUE THREAD

**Issue by mario560lukec** [spring-projects/spring-boot#13253]
Hi,
I generated git.properties file with data, but I can't access it using '/info'. How do I access that data?
git.properties file is generated in build/resources/main

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
