### ISSUE TITLE
Error uploading multiple files on a multipart request using webflux

### ISSUE THREAD

**Issue by fjavierjimenez** [spring-projects/spring-boot#13268]
I'm migrating a rest service developed with spring-boot 2 to use webflux. This rest service is used to upload 2 files using multipart. The first part "file" is usually a PDF file, and the second part "metadata" is a json file with metadata. Here is an example of this webservice: 

```java
package com.sngular.controller;

import com.sngular.model.Metadata;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@RestController
public class MultipartController {

    @PostMapping(value = "/upload", consumes = {"multipart/form-data"})
    public String fileUpload(@RequestPart(value = "metadata", required = true) Metadata metadata,
                             @RequestPart(value = "file", required = true) MultipartFile file) {
        return "ok";
    }
}
```

this REST service works fine when I use the dependency _spring-boot-starter-web_, when I change it to use _spring-boot-starter-webflux_ It give me the following error when trying to upload the files:

```
{
    "timestamp": "2018-05-25T20:36:03.505+0000",
    "path": "/upload",
    "status": 415,
    "error": "Unsupported Media Type",
    "message": "Content type 'application/pdf' not supported"
}
```

this example can be found on the following repository:

> https://github.com/fjavierjimenez/springboot-multipart-test

And the postman request Im executing..
![multipart](https://user-images.githubusercontent.com/8530507/40565451-aa291632-603a-11e8-8413-7bc8541d4a3f.png)

Any thoughts on why this gives me the error _Content type 'application/pdf' not supported_ or how to solve this?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In this case, you should use `FilePart` instead of `MultipartFile` - I've checked that replacing this in your project works. This is documented in the [Spring Framework reference documentation](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web-reactive.html#webflux-multipart-forms). If you've got ideas to improve the documentation in any way there, please create an issue against jira.spring.io (project: Spring Framework).

Thanks!
