### ISSUE TITLE
After passing the interceptor, the user is still not logged in to the problem of storing session data in redis

### ISSUE THREAD

**Issue by 270034480** [spring-projects/spring-boot#13272]
The login Interceptor uses only the getSession method and does not log in, but session data appears in redis. Simply comment out the getSession line of code and it won't appear in redis.

Interceptor method:

	@Override
	public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
		HttpSession logininfo = request.getSession();
		response.sendRedirect("/loginRedirect");
		return true;
	}

Session data does not appear in the intermediate process without any login method, and if the line is removed: "HttpSession logininfo = request.getSession.", it will not appear. Is this spring-sesssion-redis 's bug?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
