### ISSUE TITLE
Autoconfigure to support com.rabbitmq.jms.admin.RMQConnectionFactory

### ISSUE THREAD

**Issue by typekpb** [spring-projects/spring-boot#13309]
I'd love to use the RabbitMQ with JMS plugin enabled (https://www.rabbitmq.com/jms-client.html) using spring boot autoconfiguration feature. 

Similar to activemq or artemis (https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-messaging.html).

**Comment by eddumelendez** [comment]
Hi, I am working on this, and I would like to discuss about some points:

* Package
   Currently implementing under `org.springframework.boot.autoconfigure.jms.rabbitmq`
* Configuration Properties
   It already exist `spring.rabbitmq` in `RabbitProperties`. So, I was thinking about renaming the existing one into `spring.rabbitmq.amqp` and the new one for jms `spring.rabbitmq.jms` in order to avoid clashing. Or keeping the existing one as is.

**Comment by snicoll** [comment]
@eddumelendez thanks for this. Looking at the list of limitations (and the fact this doesn't support JMS 2.0, I am nervous at the idea of adding auto-configuration for this). Please hold off as I've flagged this one for team attention to discuss it further.

**Comment by eddumelendez** [comment]
Thanks for the quick reply @snicoll I will be looking forward for news.

**Comment by wilkinsona** [comment]
I do not think that we should be put off by the limitations if the functionality that is available is of use to people. Equally, I don't think we should support this in Boot itself until there is sufficient interest. As things stand, @typekpb is the only person I have seen express an interest in this.

Perhaps we could talk to the Rabbit team and see if they have a feel for how widely the JMS plugin is used?

**Comment by snicoll** [comment]
@typekpb we've discussed this at the call and we're not keen to add out-of-the-box support for this. This would vastly increase the complexity of the semantic of the RabbitMQ support and the `spring.rabbitmq.*` namespace as well.

**Comment by typekpb** [comment]
Ok, no problem. Thanks for info. We've anyway implemented it in the
meantime internally with the support for the multiple broker connections.
