### ISSUE TITLE
Does Springboot webflux support send Flux<Object> request from client to server?

### ISSUE THREAD

**Issue by AaronLiang** [spring-projects/spring-boot#13313]
Does Springboot webflux support send Flux request from client to server?

From my test, I can get Flux response from server, but how can I sent Flux request to server?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
