### ISSUE TITLE
Binding to immutable Map fails with UnsupportedOperationException

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#13323]
It works for Collections. See #9290

**Comment by mbhave** [comment]
Actually, maybe this is expected behavior since for collections we replace the entire collection but for Maps we merge.

**Comment by philwebb** [comment]
Feels like we should be able to do something similar to the #9290 fix.

**Comment by bismaya123** [comment]
Hi, I was trying to upgrade my application to spring boot 2.3.1, git similar issues -java.lang.UnsupportedOperationException: null
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1459) in my postprocessenvironment class.  please give me some insight.

**Comment by wilkinsona** [comment]
@bismaya123 It's difficult to offer any insight based on a single line from a stack trace, but you appear to be trying to add an entry to an immutable map. Without knowing more that map – whether you created it or retrieved it from somewhere else – I can't say what you need to do to fix your problem. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements so please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot).

**Comment by bismaya123** [comment]
@wilkinsona thanks for quick response, yes it is retrieved.
java.lang.UnsupportedOperationException: null
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1459), i'm using MapPropertySource, which internally is generating an immutable map, where as in 2.0.0 is internall y generating LinkedHashMap.

**Comment by wilkinsona** [comment]
Knowing that it's a `MapPropertySource` doesn't help I'm afraid. A `MapPropertySource` uses whatever `Map` it is created with. Without knowing which `MapPropertySource` you are trying to mutate, we can only guess at what is happening and why.

This issue is about binding properties from the environment to a `@ConfigurationProperties` class that contains an immutable map whereas the problem that you are seeing is to do with mutating a property source in the environment. As such, this issue isn't the right place to discuss the problem. As I said above, please follow up on Stack Overflow or Gitter. Or, if you believe you have found a bug, please open a new issue and provide a complete and minimal example that reproduces the problem.
