### ISSUE TITLE
❓Question how to use two or more datasources in one request

### ISSUE THREAD

**Issue by DreamUFO** [spring-projects/spring-boot#13346]
I can change datasource through AbstractRoutingDataSource determineCurrentLookupKey by change threadlocal value. but can only change once.
I have a request,need different datasources.
such as in one request.
list 1 query in database A,
list 2 query in database B,
list 3 query in database C
...
in the end rebuild these lists in one result to return.
now ThreadLocal can only work first time.
second time ThreadLocal set datasourceId not working 

Do I need refreshing something or do something other stuff?
or I do something wrong ?
can anyone help me?
 maybe post some key codes. thank you.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by DreamUFO** [comment]
sry.I'll try Stack Overflow. 
thank you for your respones.
