### ISSUE TITLE
how to custom user in springboot websocket without spring security

### ISSUE THREAD

**Issue by qinkaiyuan** [spring-projects/spring-boot#13340]
I want to use org.springframework.messaging.simp.SimpMessagingTemplate.convertAndSendToUser(String user, String destination, Object payload) method

but I don't Know Where does this user come from，

I searched all the spring documents，But the result was disappointing to me，

They are all talking about spring security，But I don't want to use spring security

I didn't find any documents and APIs telling me what to do

I found a similar question：

Where "user" comes from in convertAndSendToUser works in SockJS+Spring Websocket?

But this is not the official document

I want to know where springboot websocket does not use spring security and uses custom user documentation

If you know, can you tell me, thank you very much. I was troubled by this problem for two days.

thanks！thanks！thanks！ Three important things to say

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by qinkaiyuan** [comment]
sorry,
I don't think this is a bug,
Just because I can't find the corresponding document，
I have already asked Stack Overflow（https://stackoverflow.com/questions/50663091/how-to-custom-user-in-springboot-websocket-without-spring-security） before coming here for new issues, 
but I haven’t found the answer，
I hope you can help me to answer this question, be grateful
