### ISSUE TITLE
Hikari metrics not emitted when HikariDataSource bean is created after application initialization

### ISSUE THREAD

**Issue by 730alchemy** [spring-projects/spring-boot#13379]
Using Spring Boot 2.0.2.Release

Our Spring Boot application is not emitting Hikari connection pool metrics under the following conditions:

- A HikariDataSource bean is not created during application context initialization
- The first HikariDataSource bean is created after the application context is initialized

This attached project illustrates the problem.

[issue-hikari-metrics.zip](https://github.com/spring-projects/spring-boot/files/2073799/issue-hikari-metrics.zip)

If the active profiles do not include `DynamicDB`, the application emits Hikari metrics (verified by hitting the `metrics` endpoint).  If the active profiles includes `DynamicDB`, the application does not emit Hikari metrics.  You will not be able to run the attached application under the `DynamicDB` profile because the feature that this profile enables requires an OAuth server to verify a JWT that includes fields the feature requires.

However, the code may enable you to analyze the root of our problem, which I think is the following.  When the application runs with the `DynamicDB` profile, a `HikariDataSource` bean is not created at application startup.  It looks like this causes the `HikariDataSourceMetricsPostProcessor` bean to not get created, because the `@ConditionalOnClass(HikariDataSource.class)` condition is not satisfied for the configuration class `HikariDataSourceMetricsConfiguration`.  We tried explicitly creating the `HikariDataSourceMetricsPostProcessor` bean, but we can't do this because the class is not public.

We might be able to work around this issue by setting a metrics tracker factory on each `HikariDataSource` that the application creates after application startup.  However, I think what would work better is having the option to explicitly load a `HikariDataSourceMetricsPostProcessor` bean at application startup.

This problem is related to issue https://github.com/spring-projects/spring-boot/issues/13295

**Comment by wilkinsona** [comment]
>  It looks like this causes the HikariDataSourceMetricsPostProcessor bean to not get created, because the @ConditionalOnClass(HikariDataSource.class) condition is not satisfied for the configuration class HikariDataSourceMetricsConfiguration

`ConditionalOnClass` isn't affected by the presence of beans. It's only affected by what is and is not on the class path. In this case, HIkari is on the class path so the condition will match.

> However, I think what would work better is having the option to explicitly load a HikariDataSourceMetricsPostProcessor bean at application startup.

I don't think this will help as I believe that post-processor is there. I think the problem is in your `DynamicRoutingDataSource` class. When you create a `DataSource` you are registering the bean using `registerSingleton`. As per its javadoc, the given instance is supposed to be fully initialized. This means that, among other things, the bean is not post-processed.

> We might be able to work around this issue by setting a metrics tracker factory on each HikariDataSource that the application creates.

I don't consider this to be a workaround and it is what I would recommend that you do. There's no need to use a post-processor as you already have a single place that will create the data sources and can perform the necessary registration. Once you have the `MeterRegistry`, it's a one-liner:

```java
dataSource.setMetricsTrackerFactory(new MicrometerMetricsTrackerFactory(registry));
```

**Comment by 730alchemy** [comment]
Setting a metrics tracker factory on the HikariDataSource enabled the desired behavior.  Thank you Andy for providing not just a solution, but also explanations and insights.
