### ISSUE TITLE
Spying on autowired attribute does not work anymore in a Spring Boot based test class

### ISSUE THREAD

**Issue by jleberre** [spring-projects/spring-boot#13374]
Using Spring Boot v2.0.2.RELEASE and something like this 
```java
@RunWith(SpringRunner.class)
@SpringBootTest
public class SpyingOnAutowiredTest {

	@Spy
	@Autowired
	private Dummy dummy;

	@Test
	public void test() {
		dummy.someMethod();

		Mockito.verify(dummy).someMethod();
	}

	@Configuration
	static class config {

		@Bean
		public Dummy dummy() {
			return new Dummy();
		}
	}

	static class Dummy {

		public void someMethod() {
		}
	}

}
```
I end up with the following error : 
```
org.mockito.exceptions.misusing.NotAMockException: 
Argument passed to verify() is of type Dummy and is not a mock!
```
The problem occurs because the ``DependencyInjectionTestExecutionListener`` is executed after the ``MockitoTestExecutionListener``.

There was a previous [commit ](https://github.com/spring-projects/spring-boot/commit/458dde63a80939d06502c1271591f477642b43fb#diff-03a030b433e9fe21996a7b510eb2c8fdR46) explicitly defining the *correct* order between ``DependencyInjectionTestExecutionListener``and  ``MockitoTestExecutionListener`` for this test case to work but it has been overridden during the [merge](https://github.com/spring-projects/spring-boot/commit/886f782b20b501d8d63ebc47bf4d32743b3c7b08#diff-03a030b433e9fe21996a7b510eb2c8fdR48) of another [fix](https://github.com/spring-projects/spring-boot/commit/aac88502c8e05e1c92229838e34eda0043255f3d#diff-c6d53b697f2cd45feec1399efb317facR62) from branch 1.5.x

**Comment by philwebb** [comment]
Thanks for the detailed report. I'll target this to 1.5.x to make sure we put a test there, even if the fix itself is only needed in 2.0.x.

**Comment by philwebb** [comment]
@jleberre Running the test with both 1.5.x and 2.0.x results in the same exception, however, I believe that this is because your test is using `@Spy`. You should be using `@SpyBean`. Please let me know if you can reproduce the error once you've switched to `@SpyBean`

**Comment by jleberre** [comment]
This test case worked with previous version (1.4.7.RELEASE for example) but you're right, it works with ``@SpyBean`` which seems better suited.
Anyway since ``MockitoTestExecutionListener`` is one of the default ``TestExecutionListener`` shouldn't this particular case be supported ?

**Comment by philwebb** [comment]
It looked like it worked by accident rather than design in 1.4. The `MockitoTestExecutionListener` was primarily designed to allow `@Captor` annotated fields to work correctly. There are actually some very subtle problems caused by using `@Spy` since it's only spying on the instance in the test class and not on the one that's actually being used by Spring.

In other words Spring is creating an instance of `Dummy` and injecting it in the test. Mockito is then replacing _that_ instance with a spy. If you have another Spring bean that's trying to use `Dummy` it will get the non-spy version.

I think, all things considered, I prefer the hard failure which will hopefully drive people towards `@SpyBean`.

**Comment by jleberre** [comment]
Thank you for your time and the detailed explanation.
