### ISSUE TITLE
Hey friends,Can I config a init parameter in DispatcherServlet?

### ISSUE THREAD

**Issue by LonelyPm** [spring-projects/spring-boot#13432]
I want to set detectAllHandlerExceptionResolvers to false,but I search for sources , seen not to find anywhere to config it.

```
<servlet>
		<servlet-name>springMVCServlet</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>	
		<init-param>
			<param-name>detectAllHandlerExceptionResolvers</param-name>
			<param-value>false</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>
```

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
