### ISSUE TITLE
How to achieve the maximum performance of the current machine cpu and memory?

### ISSUE THREAD

**Issue by z8z87878** [spring-projects/spring-boot#13439]
For example, I'm currently testing 10,000 throughputs on a CPU 8-core, 10G RAM machine, but I configured the machine to be 24 cores, 20G RAM, throughput is still 10,000, and the CPU usage of the running program is still 8 cores. . I want to know why this is? There is also how to configure springboot to play the maximum performance of the machine.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by z8z87878** [comment]
ok
