### ISSUE TITLE
How to get basePackages of @ComponentScan?

### ISSUE THREAD

**Issue by EdwardLee03** [spring-projects/spring-boot#13440]
The scanBasePackages of `@SpringBootApplication` configured as follow:
```java
package com.xxx.boot.sample;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication(scanBasePackages = { "com.xxx.boot.sample", "com.xxx.boot.service" })
public class DemoApplication {

  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }

}
```

But `AutoConfigurationPackages#get(BeanFactory)` only return `"com.xxx.boot.sample"`, not include `"com.xxx.boot.service"`.
```java
  List<String> packagesToScan = AutoConfigurationPackages.get(beanFactory);
```

By debug, I found the `@SpringBootApplication` instance is a proxy class instance. I try to get Annotation use `Class#getAnnotations`, then get scanBasePackages field by reflection. But not success.

❓Question
How to get `scanBasePackages of @SpringBootApplication` or `basePackages of @ComponentScan` programatically?

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
Just as a quick hint. `scanBasePackages` is an `@AliasFor` for `ComponentScan.basePackages`. You can use `AnnotationUtils` to get the value I think. For further discussion, please raise a stack overflow question and paste the link here.

**Comment by EdwardLee03** [comment]
@philwebb OK, thx

**Comment by EdwardLee03** [comment]
@philwebb I moved this question to Stack Overflow.
https://stackoverflow.com/questions/50808941/how-to-get-basepackages-of-componentscan-programatically-at-runtime
