### ISSUE TITLE
config option to disable security for a particular endpoint

### ISSUE THREAD

**Issue by kycrow32** [spring-projects/spring-boot#13474]
I need to completely bypass security (authentication / authorization) for certain endpoints in my spring boot app, like "/version" and "/robots.txt", but keep security in place for all other endpoints.

To complicate matters, I'm working in a project that's a part of a much larger project.  My company has another group that has supplied a library that makes use of spring security.  This is only relevant because it means I cannot simply override a spring security class to make this work--those classes have already been overridden.

Is there a way to configure spring boot 2.0 to bypass authentication for certain endpoints?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by kycrow32** [comment]
Posted here:
https://stackoverflow.com/questions/50858423/spring-boot-2-0-how-to-disable-security-for-a-particular-endpoint

Sorry, I saw the "ask a question" among the list in the "New Issue" page, and failed to see the reference to "ask it on stackoverflow".  My bad!
