### ISSUE TITLE
Micrometer integration with new relic for Spring boot 2 not working

### ISSUE THREAD

**Issue by mghildiy** [spring-projects/spring-boot#13488]
Hi,

I am following [link](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-export-newrelic) on configuring newrelic and micrometer in Spring boot 2.

I get error as:

**"message": "failed to send metrics: {"error":"Invalid insert key or the account does not have access to Insights."}"**

All confg details are correct. Micrometer developer says its probably related to Spring boot 2.
What can be wrong here?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
