### ISSUE TITLE
use redis and mongodbb get a NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by Comup-X** [spring-projects/spring-boot#13518]
when the spring-boot-starter-data-redis and spring-boot-starter-data-mongodb in my project I will get a NoSuchBeanDefinitionException No qualifying bean of type 'com.comup.ownsite.authserver.repository.UserRepository' available

my spring boot version is 2.0.3.RELEASE

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
