### ISSUE TITLE
Fail to build spring starter web dependency

### ISSUE THREAD

**Issue by vivekranjan92** [spring-projects/spring-boot#13519]
Hi all,

I am creating a Gradle Project to perform CRUD operation using MongoDB. I am following a YouTube link to complete my learning and added two dependencies accordingly. After adding the dependencies 
when refreshing the Gradle project I am getting this message in the console : 
CONFIGURE SUCCESSFUL in 0s
Could not resolve: org.springFramework.boot:spring-boot-starter-web:2.0.3.RELEASE

Below are the dependencies which I have added:
1.    compile("org.springFramework.boot:spring-boot-starter-web:2.0.3.RELEASE")
2.    compile 'org.springframework.data:spring-data-mongodb:2.0.8.RELEASE'

Kindly, help me with this. Any help would be appreciated

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
