### ISSUE TITLE
Spring boot test context is loading for every test class separately

### ISSUE THREAD

**Issue by vskrahul** [spring-projects/spring-boot#13548]
❓Question
I am using spring boot version#2.0.1.RELEASE.

I have 6 test classes, 4 are annotated with @SpringBootTest and 2 are annotated with @WebMvcTest.
Spring test context is loading every time for every test class.

Any idea why this is happening.

**Comment by mbhave** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
