### ISSUE TITLE
Overridden bean definitions may cause incorrect bean condition evaluation due to stale information being held by BeanTypeRegistry

### ISSUE THREAD

**Issue by prasenjit-net** [spring-projects/spring-boot#13588]
I have an interface `AuditEventRepository` in my project which is definitely not same as `org.springframework.boot.actuate.audit.AuditEventRepository` and also has a different purpose. but this is clashing with the bean declared in `org.springframework.boot.actuate.autoconfigure.audit.AuditEventsEndpointAutoConfiguration#auditEventsEndpoint`

```java
@Bean
@ConditionalOnMissingBean
@ConditionalOnBean(AuditEventRepository.class)
@ConditionalOnEnabledEndpoint
public AuditEventsEndpoint auditEventsEndpoint(
		AuditEventRepository auditEventRepository) {
	return new AuditEventsEndpoint(auditEventRepository);
}
```

Reproduction step:
Have a bean with class simple name `AuditEventRepository`.

**Comment by philwebb** [comment]
We perhaps should try to find a way to make the names of our auto-configured beans more unique but that will need some thought on our part. For now, I'd suggest using naming your `AuditEventRepository` bean differently. You can change the bean name without changing the class name by using the `value` attribute of `@Component`.

**Comment by prasenjit-net** [comment]
Hi, @philwebb does @ConditionalOnBean searches by bean name? Shouldn't it search with the 'type'?

**Comment by philwebb** [comment]
It searches by type. What's the actual problem that you get? Can you attach a stack trace?

**Comment by prasenjit-net** [comment]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method auditEventsEndpoint in org.springframework.boot.actuate.autoconfigure.audit.AuditEventsEndpointAutoConfiguration required a bean of type 'org.springframework.boot.actuate.audit.AuditEventRepository' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.boot.actuate.audit.AuditEventRepository' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:63630', transport: 'socket'

Process finished with exit code 0

**Comment by prasenjit-net** [comment]
This above method has a condition @ConditionalOnBean(AuditEventRepository.class) so this method should not be executed on the first hand.

**Comment by philwebb** [comment]
Thanks. That's pretty interesting because I would have thought `@ConditionalOnBean` would kick-in. We'll have to investigate a little more.

**Comment by prasenjit-net** [comment]
@philwebb thanks, your workaround works for now

**Comment by wilkinsona** [comment]
> We perhaps should try to find a way to make the names of our auto-configured beans more unique

See #4667

**Comment by wilkinsona** [comment]
I can't reproduce the exact behaviour that's described here, but I have identified a bug in `BeanTypeRegistry`.

I would expect the user-provide bean named `auditEventRepository` to be overridden by the auto-configured bean of the same name. This is what happens when I try to reproduce the described problem. `BeanTypeRegistry` doesn't notice that the bean has been overridden (`lastDefinitionBeanCount == beanFactory.getBeanDefinitionCount()`) so its view of the types of the beans in the bean factory is stale. As a result, conditions that match on the presence of an `org.springframework.boot.actuate.audit.AuditEventRepository` fail to match even though the bean is actually present.

`BeanTypeRegistry` needs to update `beanTypes` when an override occurs.

**Comment by wilkinsona** [comment]
@prasenjit-net I think that the problem you have reported has the same root cause as the problem that I have described above. My suspicion is that `BeanTypeRegistry` has an out of date view of the types of the beans in the bean factory so that a conditional on bean is matching when it should not. So that we can be sure that both problems have the same underlying cause, can you please provide a small sample (something that we can unzip or git clone and run) that reproduces the behaviour you have described?

**Comment by prasenjit-net** [comment]
Hi @wilkinsona please check the repo [Identity](https://github.com/identityOrg/identity.git) and if you rename the following class to AuditEventRepository the reported behavior will become pronounce.
`identity/src/main/java/net/prasenjit/identity/repository/AuditEvent1Repository.java`

I am also trying to create a lighter repo, will post when done.

**Comment by prasenjit-net** [comment]
@wilkinsona [This](https://github.com/prasenjit-net/boot-bug-reproduction-code.git) is a minimum repo to reproduce the issue.

**Comment by prasenjit-net** [comment]
I have checked it further, the problem is in `org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanType(String)`. 

And in this case of evaluation of `@ConditionalOnBean(AuditEventRepository.class)` InMemoryAuditEventRepository is considered but by the time the AuditEventsEndpoint is created, the bean name is overridden by the custom bean.

**Comment by wilkinsona** [comment]
Thanks for the sample, @prasenjit-net. That's given me enough for a minimal recreation. All you need is a `JpaRepository` extension named `AuditEventRepository`. The dependencies that you have on Spring Cloud, etc are unnecessary.

The key difference between this and what I had managed to reproduce is that the override has been reversed. Now, rather than the user-provided bean being overriden by the auto-configured bean, the auto-configured bean is being overridden by the user-provided bean:

```
2018-06-28 15:29:52.587  INFO 69793 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'auditEventRepository' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration$AuditEventRepositoryConfiguration; factoryMethodName=auditEventRepository; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/actuate/autoconfigure/audit/AuditAutoConfiguration$AuditEventRepositoryConfiguration.class]] with [Root bean: class [org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null]
```

This happens because the bean definitions for JPA repositories aren't created until `JpaRepositoriesAutoConfiguration` is processed and `JpaRepositoriesAutoConfigureRegistrar` calls `RepositoryConfigurationDelegate.registerRepositoriesIn(BeanDefinitionRegistry, RepositoryConfigurationExtension)`. If support for JPA repositories is enabled explicitly (with `@EnableJpaRepositories`) rather than it being auto-configured, the app starts successfully with this info-level message in the logs:

```
2018-06-28 15:34:19.869  INFO 69830 --- [           main] a.ConfigurationClassBeanDefinitionReader : Skipping bean definition for [BeanMethod:name=auditEventRepository,declaringClass=org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration$AuditEventRepositoryConfiguration]: a definition for bean 'auditEventRepository' already exists. This top-level bean definition is considered as an override.
```

Interestingly, `ConfigurationClassPostProcessor` backs off in this case as the bean definition for the repository wasn't created by a `@Bean` method in a `@Configuration` class.

When the app fails to start, the underlying problem is the same as the scenario [I described above](https://github.com/spring-projects/spring-boot/issues/13588#issuecomment-400581377) with bean type registry failing to notice that the bean has been overridden and that its type has changed.

**Comment by wilkinsona** [comment]
> When the app fails to start, the underlying problem is the same as the scenario I described above with bean type registry failing to notice that the bean has been overridden and that its type has changed.

I was mistaken and , unfortunately, changing `BeanTypeRegistry` so that it detects the override and updates it cached type for the bean does not help. It does not help because the registration order has been inverted with the user-provided `JpaRepository` being defined and registered after the conditions on `AuditAutoConfiguration` have been evaluated. When the conditions on `AuditAutoConfiguration` are evaluated, `BeanTypeRegistry` correctly sees the bean's type as being actuator's `AuditEventRepository` so the definition for the endpoint bean is registered. Subsequently, this definition is overridden by the user-provide `JpaRepository` audit event repository. This results in the context failing to start because a required dependency of `AuditEventRepository` could not be injected.

**Comment by wilkinsona** [comment]
If the auto-configuration order is adjusted such that `AuditAutoConfiguration` goes after `JpaRepositoriesAutoConfiguration`, we get into the same situation as if `@EnableJpaRepositories` had been specified manually. `ConfigurationClassBeanDefinitionReader` skips the definition of Actuator's `AuditEventRepository`:

```
2018-06-28 16:19:02.186  INFO 69911 --- [           main] a.ConfigurationClassBeanDefinitionReader : Skipping bean definition for [BeanMethod:name=auditEventRepository,declaringClass=org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration$AuditEventRepositoryConfiguration]: a definition for bean 'auditEventRepository' already exists. This top-level bean definition is considered as an override.
```

**Comment by wilkinsona** [comment]
One piece of good news is that the change to `BeanTypeRegistry` to notice that a definition has been overridden is surprisingly inexpensive. It is sub-millisecond most of the time. [This](https://github.com/wilkinsona/spring-boot/tree/gh-13588) is the possible change.

**Comment by prasenjit-net** [comment]
@wilkinsona thanks for your comments and solution. One suggestion from me can you change the bean override log level to WARN. This way it will be more noticeable. and will sometime help a lot.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but the code that logs the info message is in Spring Framework. You can make the suggestion to the Framework team by opening a [JIRA](https://jira.spring.io/browse/SPR).

**Comment by wilkinsona** [comment]
We're going to see if the change [linked to above](https://github.com/wilkinsona/spring-boot/tree/gh-13588) can be made without hurting performance unduly.

**Comment by wilkinsona** [comment]
The proposed change makes no discernible difference to the startup time of a number of our sample apps. I think we can use it.
