### ISSUE TITLE
Activiti 6 with spring boot 2.0.3 

### ISSUE THREAD

**Issue by sunthak** [spring-projects/spring-boot#13587]
I am trying to integrate activiti version 6 work flow in spring boot 2.0.3 and I am running into lots of compatibility issues? does not spring supports activiti workflow anymore?  spring boot 1.3 and activiti version 5 works fine.  Is there any other jbpm engines work with spring boot 2.0.3?

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
