### ISSUE TITLE
PropertySource ConfigurationProperties use together

### ISSUE THREAD

**Issue by luguohong** [spring-projects/spring-boot#13598]
Question:

spring-boot 1.5.10.RELEASE
i use PropertySource and ConfigurationProperties like this

@Component
@PropertySource("file:${config.path}")
@ConfigurationProperties(prefix="oss")
public class OssConfig {
    private String appId;
    public getAppId() {
        ......
    }
    public setAppId(String appId) {
        ......
    }
}

and config.path is "/user/svr/config/bus.yml"
and the file content is 
oss: 
  appId: 123123

the problem is that i can not get appId from OssConfig
but i take the config to the default config file(application.yml), OssConfig works

ConfigurationProperties only work with application.yml, it's that rigth???

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
