### ISSUE TITLE
Failure analysis for NoSuchBeanDefinitionException does not include information about qualifiers or the class on which auto-configured bean methods are declared

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13594]
See #13592 for an example.

**Comment by dnl50** [comment]
Hi there,

I built a very simple spring boot application with a single component, which gets a named bean injected in its constructor, which is not present to recreate the situation in #13592. Getting the name of the missing bean (the value of the `Qualifier` annotation) inside the `NoSuchBeanDefinitionFailureAnalyzer` would require a lot of string analysis of the `NoSuchBeanDefinitionException`'s message, because the [`DefaultListableBeanFactory#raiseNoMatchingBeanFound(...)`](https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/java/org/springframework/beans/factory/support/DefaultListableBeanFactory.java#L1602) method of spring just throws a `NoSuchBeanDefinitionException` with the _resolveType_ and a _message_ set, but not the _beanName_. Because of this, the only way of getting the bean name would be by scanning the message string for something like:

... Dependency annotations: @org.springframework.beans.factory.annotation.Qualifier(value=_beanName_)} ...

which is a bit hacky and error-prone imo. Wouldn't it be a better idea to call a different constructor of `NoSuchBeanDefinitionException` when there is a `Qualifier` annotation present? But that would be more of a issue in spring itself, and not spring boot.

Kind regards,
Daniel

**Comment by wilkinsona** [comment]
The new test is failing on Java 9 and 10 due to a difference in the output of calling `toString()` on the `@Qualifier` annotation:
    
    @org.springframework.beans.factory.annotation.Qualifier(value=alpha)

vs

    @org.springframework.beans.factory.annotation.Qualifier(value="alpha")
