### ISSUE TITLE
Show Banner again

### ISSUE THREAD

**Issue by KroneckerDelta** [spring-projects/spring-boot#13599]
My hardcoded (ASCII)-banner is showing at start. Standard! If the Application successfully startet, I repeat showing my banner with extension 'is running' or 'is not running' after problems (like database not reachable). Admins oder Devops see my banner twice, one at start and one after init all technical stuff.
Now I change to a colored (ascii) banner from banner.txt file. But I can not show it again. I want a method to show the Banner.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by KroneckerDelta** [comment]
I asked this in Stack Overflow. Thank you.
https://stackoverflow.com/questions/51113265/springboot-how-to-show-banner-programmtically-at-start-again
