### ISSUE TITLE
Servlet filter registration behaves differently between application startup and tests with @AutoConfigureMockMvc

### ISSUE THREAD

**Issue by MenschNestor** [spring-projects/spring-boot#13605]
The sample project https://github.com/MenschNestor/mockmvc-filter-registration attempts to highlight an issue I came across while trying to override the filter order of a filter from Spring Cloud Sleuth. Upon investigation, it seems to me that there is an unexpected difference in the way that servlet filters are registered for the MockMvc filter chain with `@AutoConfigureMockMvc` and the way they are registered during normal application startup.

The project mentioned above contains a README trying to explain the issue in more detail. The short of it is that I think `SpringBootMockMvcBuilderCustomizer` should not add the same filter instance to the filter chain twice. This is what `AbstractFilterRegistrationBean` does when `ServletFilter#addFilter` returns null because the filter has already been defined.

If I'm wrong in this, I'd appreciate a pointer as to how I can properly change the order of a filter registered by a library.

**Comment by wilkinsona** [comment]
> I'd appreciate a pointer as to how I can properly change the order of a filter registered by a library.

Assuming that the library is targeted at Spring Boot, I'd expect it to do one or both of the following:

1. Provide a property for setting the filter's order as Boot does for Jersey and Spring Security's filters
2. Make the filter registration bean `@ConditionalOnMissingBean` so that it backs off when a user provides a registration bean.

With that said, I think we should align the behaviour of `SpringBootMockMvcBuilderCustomizer` with `ServletContext.addFilter(String, Filter)`

**Comment by MenschNestor** [comment]
@wilkinsona Thanks, I'll think about bringing it up as an enhancement for Spring Cloud Sleuth (which is the library in question – I want to bring the trace filter in before Spring Security filters apply).

**Comment by wilkinsona** [comment]
Sorry, you mentioned that it was Sleuth in the description. I think opening an enhancement request would be worthwhile. If it's a common thing to want to do with Sleuth, it would make sense to make it a bit easier. /cc @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Yup, we don't allow overriding the order for now

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebServletAutoConfiguration.java#L84-L99

Opening an enhancement request makes perfect sense

**Comment by MenschNestor** [comment]
@marcingrzejszczak Ok, thanks for confirming. I have opened the request, see above.

**Comment by wilkinsona** [comment]
Unfortunately, there's no easy way for us to give this. `FilterRegistrationBean` does not expose the name (either explicitly configured or deduced) of the filter and, unlike `ServletContext`, `ConfigurableMockMvcBuilder.addFilter(Filter, String[])` does not differentiate by filter name (as it doesn't know the filter's name).

All is not lost, though. @MenschNestor, rather than creating a duplicate registration for the Sleuth filter that duplicates its name, I'd use a `BeanPostProcessor` to change the order of the existing registration. You should be able to identify the right registration(s) to customize by bean name.

**Comment by marcingrzejszczak** [comment]
So do we want to do the new feature in Spring Cloud Sleuth or not? :P

**Comment by MenschNestor** [comment]
@marcingrzejszczak I still think it would be useful, but it's no longer a priority for me. FWIW, I did try the `BeanPostProcessor` route and that worked as well for my (flawed) scenario.
