### ISSUE TITLE
Error creating bean with name 'sessionRepositoryFilterRegistration' defined in class path resource [org/springframework/boot/autoconfigure/session/SessionRepositoryFilterConfiguration.class]: Unsatisfied dependency expressed through method 'sessionRepositoryFilterRegistration' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.session.RedisSessionConfiguration$SpringBootRedisHttpSessionConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.session.RedisSessionConfiguration$SpringBootRedisHttpSessionConfiguration.setCleanupCron(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by hxiugangxh** [spring-projects/spring-boot#13604]
update to 2.x 
spring-session is wrong

**Comment by wilkinsona** [comment]
You have mismatched versions of Spring Boot and, I think, Spring Data Redis. That won’t happen if you use and do not override Boot’s dependency management. I can’t tell why it is happening as you have not provided any information about your application.

If you need some help figuring it out, please ask a question on Stack a Overflow and provide a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question so that other people can find it.

**Comment by loupipalien** [comment]
Update spring-session to 2.x.x (org.springframework.session:spring-session-data-redis:2.x.x.RELEASE)
