### ISSUE TITLE
Disable bean overriding by default and provide a configuration property to enable it

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#13609]
From what we've seen, overriding one bean definition with another (by providing two definitions with the same name) is most often done accidentally. When it is done, the info log message is almost always missed, leading to hard to diagnose behaviour. We should disable bean overriding by default and provide a configuration property to turn it back on along with failure analysis of the exception that clearly describes the problem and suggests setting the property as a possible action.

**Comment by wilkinsona** [comment]
Currently, a rejected override attempt results in a `BeanDefinitionStoreException`. It would be very useful for failure analysis if a specific exception was thrown that provided access to both the existing and the overriding bean definitions. I've opened https://jira.spring.io/browse/SPR-16982.

**Comment by spencergibb** [comment]
We've similarly dealt with some issues with this in spring cloud

**Comment by wilkinsona** [comment]
This broke the build and fixing it is blocked by #13737.

**Comment by wilkinsona** [comment]
With #13737 fixed, this is still blocked but by Spring Data REST now. It tries to [override](https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.java#L616-L619) a bean that's already been [defined](https://github.com/spring-projects/spring-framework/blob/d5df097e0e3afe7ae36622ad275b39631ee38c3b/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java#L871-L874) by Spring MVC.

**Comment by wilkinsona** [comment]
The problem in Spring Data REST has been fixed in its latest snapshots.

**Comment by duke-cliff** [comment]
@wilkinsona Hi Andy, just noticed this changed. We often use the Primary annotation to override some bean for integration test(I guess it's a normal approach). Took me hours to figure out this was disabled by default from 2.1.0. : (

**Comment by wilkinsona** [comment]
I'm sorry to hear that. The change to the default is one of the first things that is described in the [release notes for 2.1](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding). They're always worth reading before upgrading and again if you hit a problem when you do.

**Comment by maccac** [comment]
It's nice to know when you are accidentally overriding beans, but it would also be nice to be able to specifically mark specific beans as deliberately overriding others so they will be allowed. 

When I've made heavy use of spring auto-configuration I've often find that there are beans that need customisation so I get the benefits of it being mostly auto-configured with only a few variations. In these situations it's pretty useful for it to error out when I accidently 'override' a bean, but it would be nice to be able to deliberately tell the framework that this particular bean is still something I want to override. That way, this feature could catch future mistakes I make whilst letting me retain the earlier decisions I made. 

Perhaps I'm making a feature request or suggestion... maybe a new annotation like @OverridesExistingBean or an additional parameter on @Bean with a similar name.

**Comment by inletfetch** [comment]
This issue is causeing a problem for me because I broke my single bean definition XML file into muliptle files many months ago.  I'm getting the error because I'm redefining THE SAME BEAN multiple times.  This happens because multiple XML files including the same other XML file to get the definitions of the beans it references.  I do this so that can use different mixes of my bean definition files and be sure that the dependent bean definitions are always available for reference.  This has always worked fine until 2.1. 

My work-around is to set spring.main.allow-bean-definition-overriding=true.  This fixes the problem.   But I'd love to have the benefit of being warned if I'm truly overriding one bean with a DIFFERENT bean.  I am going to look to see if I can reorganize my bean files to avoid this issue and still get the functionality I want, but it's a pain.  I just wanted to put this particular problem on record.  I'm not saying it's a proper practice.

I wonder if an exception could be made if the offending overriding bean has the same source coordinates as the original, or if the framework can otherwise recognize this situation...a duplicate definition of the same bean.

**Comment by snicoll** [comment]
If your bean definition has an `id` the framework should not redefine the same bean definition multiple times, which should automatically fix your problem. If that does not fix it, please consider creating a Spring Framework issue with a small sample that reproduces the behavior you've described.

**Comment by snicoll** [comment]
@inletfetch thanks for the feedback. It looks odd to me that the core container throws a `BeanDefinitionOverrideException` in such a case. Could you please create a [Spring Framework issue](https://jira.spring.io/projects/SPR)?

**Comment by inletfetch** [comment]
will do
