### ISSUE TITLE
Disable security on springboot2

### ISSUE THREAD

**Issue by mat-613** [spring-projects/spring-boot#13608]
i'm trying to disable default security in Springboot 2, but i can't.

In sprinboot 1.5 i have used security.basic.enabled=false, but now it's deprecated.

I'm trying to create a configuration class that extends WebConfigurationAdapter overriding the configure method like this:

    @Configuration
    public class StackWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.httpBasic().disable();
        // http.authorizeRequests().anyRequest().permitAll(); // Also doesn't work.
    }
   }

Can you help me?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
