### ISSUE TITLE
Can not access InputStream on a GridFSFile which is the only queryable thing on org.springframework.data.mongodb.gridfs.GridFsTemplate

### ISSUE THREAD

**Issue by nhh** [spring-projects/spring-boot#13698]
🐞 Bug report

Hi all,

I started using the spring-boot-starter-data-mongodb and noticed, that the GridFSFile does not has access to it's "InputStream"

In Detail:

The "GridFSTemplate" only provides a queryable method "findOne" which returns a "GridFSFile". Not a "GridFSDBFile" which actually contains the "getInputStream" method.

Can someone clarify that this is an issue? This behavior actually prevents me from working with queried documents on a file basis. I can only access it's meta data.

There is a StackOverflow question which describes this missing behavior too.
https://stackoverflow.com/questions/49153910/how-to-get-a-binary-stream-by-gridfs-objectid-with-spring-data-mongodb?rq=1

All the provided solutions are workarounds. So i thought opening a issue would be helpful.

Thank you for your efforts!
Niklas Hanft

**Comment by ehhc** [comment]
I would like to point out that the solution proposed by @nhh might lead to a missleading understanding of the problem. I had a problem with downloading files stored in a mongodb through a REST-Controller and found this issue. Unfortunately simply wrapping the file in a GridFsResource might lead to problems in that context. 
Maybe, if somebody else, like me, stumbles over this issue in search for a solution for his problem, it might be interesting, what i found out (maybe it' common knowledge but i searched a long time without finding it).

If someone wants to download files stored in the mongodb and therefore needs a GridFsResource as return value of the rest-controller-method, simply wrapping it with a new GridFsResource does **not** work. Instead you have to use `gridFsOperations.getResource(file)` to wrap it into a GridFsResource. Otherwise the file could not be retrieved.

Downloading files through a rest method from a mongodb can therefore be done like this:
```@RestController
@RequestMapping(value = "/api ")
public class AttachmentController {

    private final GridFsOperations gridFsOperations;
    
    @Autowired
    public AttachmentController(GridFsOperations gridFsOperations) {
        this.gridFsOperations = gridFsOperations;
    }

    @GetMapping("/file/{fileId}")
    public ResponseEntity<Resource> getFile(@PathVariable String fileId) {
        GridFSFile file = gridFsOperations.findOne(Query.query(Criteria.where("_id").is(fileId)));

        return ResponseEntity.ok()
                .contentLength(file.getLength())
                .body(gridFsOperations.getResource(file));
    }
```
