### ISSUE TITLE
HandlerInterceptorAdapter is called twice when controller returns Mono.

### ISSUE THREAD

**Issue by han1448** [spring-projects/spring-boot#13708]
I've created interceptor class for checking request parameters. My controller returns Mono object. But I found Interceptor `preHandle()` is calling twice.

```java
@ResponseStatus(HttpStatus.OK)
@GetMapping("/myapi/id")
public Mono<List<String>> myapi()  {
	return Mono.just(new ArrayList<>());
}
```

Interceptor class
```java
@Component
@Slf4j
public class ValidateInterceptor extends HandlerInterceptorAdapter {

	@Override
	public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
		log.info("Pre handle......");
		return true;
	}
}
```

The log is
```
2018-07-05 14:31:50.043  INFO [test,1c697b8fbfe9844b,1c697b8fbfe9844b,false,] 22731 --- [nio-8080-exec-3] r.t.p.ui.ValidateInterceptor             : Pre handle......
2018-07-05 14:31:50.047  INFO [test,1c697b8fbfe9844b,1c697b8fbfe9844b,false,] 22731 --- [nio-8080-exec-3] r.t.p.ui.ValidateInterceptor             : Pre handle......
```

When I change the code not to return the `Mono` but `List`, It works.

I'm using 
```
org.springframework.boot:spring-boot-starter-aop:2.0.2.RELEASE
org.springframework.boot:spring-boot-starter-webflux:2.0.2.RELEASE
org.springframework.boot:spring-boot-starter:2.0.2.RELEASE
```

**Comment by wilkinsona** [comment]
If you are using WebFlux, you can’t use `HttpServletRequest` and `HttpServletResponse`. In fact, if your dependencies are exactly as you say they are, your interceptor would not compile.

Can you please provide a minimal sample (something that we can unzip or git clone and run) that reproduces the behaviour you have described?

**Comment by han1448** [comment]
Thank you very much.
Here is my sample code. 
[sample-code](https://github.com/han1448/reactive-interceptor)

**Comment by wilkinsona** [comment]
As I suspected, you're trying to use WebFlux, but are in fact using Spring MVC. In addition to the dependencies you list above, you also have a dependency on `spring-boot-starter-web` so you're using Tomcat's Servlet stack.

As I mentioned above, you can't use `HttpServletRequest` or `HttpServlerResponse` in a WebFlux app. You also can't use `org.springframework.web.servlet.config.annotation.WebMvcConfigurer` or `org.springframework.web.servlet.handler.HandlerInterceptorAdapter`. As indicated by the `servlet` in their package names, they require the use of a Servlet container.

As for why your interceptor is being called twice, that's due to the use of Mono in a Servlet-based application. It's mapped onto Servlet's async support which means that the initial request is dispatched and it's then dispatched again for asynchronous processing. You would see the same behaviour if you used Framework's `DeferredResult`.

If you want to use WebFlux, you should remove the dependency on `spring-boot-starter-web` and convert your interceptor into a `org.springframework.web.server.WebFilter`. If you need some further guidance on how to do that, please ask on Stack Overflow.
