### ISSUE TITLE
Register SpringBeanContainer with default Hibernate setup

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#13717]
Spring Framework has added integration with Hibernate's `BeanContainer` API (see [this ticket](https://jira.spring.io/browse/SPR-16305) for details. It would be nice to see that `SpringBeanContainer` registered in the default Hibernate setup, so that converters and entity listeners can be managed via Spring beans.

**Comment by netmikey** [comment]
I've been waiting for the 2.1.0.RC1 to use that feature but I can't seem to make it work. I've been looking through Spring and Hibernate documentations but couldn't find an example.

With an entity declaration like this:
```java
@Entity
@EntityListeners(SomeEntityListener.class)
public class SomeEntity extends AbstractPersistable<Integer> {
...
```
Just adding `@Component` to EntityListener-classes doesn't seem to do the trick:
```java
@Component
public class SomeEntityListener {
    	@Autowired
	private SomeOtherRepository someOtherRepository;
...
```
In the above code, `someOtherRepository` is not injected (it's `null` when the EntityListener methods are invoked), so I guess `SomeEntityListener` is still managed by Hibernate instead of it delegating to Spring.

What am I doing wrong?

**Comment by snicoll** [comment]
> I've been waiting for the 2.1.0.RC1 to use that feature

That's really too bad. Please consider testing a snapshot next time.

`SomeEntityListener` is still managed by Hibernate and it delegates to the container API for the instantiation so adding `@Component` is unnecessary (and quite misleading I'd say so please don't do that). We have an [integration test](https://github.com/spring-projects/spring-boot/blob/2a0451c4619c7ccc0ed9be2757949b8ffad846c0/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/orm/jpa/test/City.java#L28) with such [a listener](https://github.com/spring-projects/spring-boot/blob/2a0451c4619c7ccc0ed9be2757949b8ffad846c0/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/orm/jpa/test/CityListener.java#L24).

Having said that, your listener will not work. You're asking for a Spring Data JPA repository (I assume) while JPA is boostraping. Of course, JPA repositories are not available yet and the fact you got null is a best effort of field injection. You'd probably get a cycle if you used constructor injection. 

Having said all that, this issue is closed. If you have more questions about this feature, please ask on StackOverflow. If you believe you've found a bug (i.e. it doesn't work injecting a reasonable dependency such as the `Environment`) please open a separate issue with a reference to a sample we can unzip/clone and run.
