### ISSUE TITLE
Make /health and /info insecure by default

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#13722]
Applications running on Kubernetes tend to use the health endpoint as the liveliness probe (to know when to restart a container). With Spring Security on the classpath, additional configuration is required to allow unauthenticated access to this endpoint. Maybe we could make this easier by opening up the health endpoint unless any custom configuration is provided.

**Comment by markpollack** [comment]
This is not a kunernetes specific issue.  Cloud foundry also has a health check that is http based and there is no way to specify security for it.  That said, even if there was, having the user manage passwords for health is not a best practice.  ATM on cf, -app manager can show the app has bad health yet the cf command line shows it has good health for app, since one the cf platform can only use the port based health check.

**Comment by mbhave** [comment]
Also, `/info`.
