### ISSUE TITLE
Can you tell me how to configure  session timeout in spring boot 1.5.9.RELEASE?

### ISSUE THREAD

**Issue by kri1249** [spring-projects/spring-boot#13733]
For my application after specific time the application session has to be expired...
i am using spring boot 1.5.9.RELEASE
 i tried this way in application.properties file
server.session.timeout=120
But i didn't find it working....

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by kri1249** [comment]
ok sure

**Comment by kri1249** [comment]
i have raised a question in stack overflow and the link is
https://stackoverflow.com/questions/51248031/can-you-tell-me-how-to-configure-session-timeout-in-spring-boot-1-5-9-release
