### ISSUE TITLE
The reference documentation should provide more cross-links to examples, other sections of the documentation, etc.

### ISSUE THREAD

**Issue by asmith2306** [spring-projects/spring-boot#13743]
The reference documentation should have a "wiki" style, where topics relevant to the current item are linked to (whether linked to somewhere else in the doc, or externally).  For example:

![image](https://user-images.githubusercontent.com/1416788/42517233-28d03e30-8457-11e8-9dfd-a7bf61728961.png)

In the image above, the highlighted text "add your own DataSource bean" should link to a section or external reference about what a DataSource bean is and/or an example of how to add one yourself.

The highlighed text "start your application with the --debug switch" should link to a section or external reference about how to specifically use the debug switch and/or an example of how/why it's used.

Being new to Spring/Spring Boot, it would be great if I could remain within the official Spring reference material or linked to official Spring team recommended examples when using the reference material to learn.

Thanks.

**Comment by philwebb** [comment]
I feel like this is really a bigger issue than just the Spring Boot documentation and it's something we can't solve in isolation. Adding links might be useful in some situations, but it might also add a lot of noise the reference docs. It's certainly going to be hard for us to maintain relevant links.

Ideally I think we need start thinking about how to document Spring as a complete thing, rather than a discrete set of projects. Perhaps creating [different types of documentation](https://www.divio.com/blog/documentation/) as well.

I'm going to close this one here because practically I don't think there's much we can do in isolation.
