### ISSUE TITLE
Can not catch the exception( Multipart Mime part file exceeds max filesize)

### ISSUE THREAD

**Issue by friends110110** [spring-projects/spring-boot#13752]
My springboot version is 2.0.2, And I create the global Exception in the controller class, likes :
```
    @ExceptionHandler(Exception.class)
    @ResponseBody
    public Result handleException(Exception e, HttpSession session, HttpServletRequest request) {
        LOGGER.error(e.getMessage());
```
But I could not catch the  exception, it seems I should catch the exception before controller, How?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
