### ISSUE TITLE
Why the test case run twice

### ISSUE THREAD

**Issue by Mr-LiuDC** [spring-projects/spring-boot#13750]
Environment：`Java 8`, `spring-boot 1.5.14.RELEASE`, `Windows 10`, `Eclipse 4.7`, `Maven 3.3.9`, `Gradle 4.4`
source code on github：https://github.com/codpra/spring-boot-tech

I run a spring boot web project with spring data jpa，all test classes can be executed successfully one by one in the IDE, and also executed in tandem(expected), but when I run maven command `package` some test case failed. 

Then I changed to gradle project and executed `gradle build` also some test case failed, I checked the gradle report find that all the test case executed twice. How can I workout this issue both maven project and gradle project?

Extremely grateful.

The gradle test report：
![yy hl30 7r16b ipr hfu](https://user-images.githubusercontent.com/18117854/42547679-efafd102-84f5-11e8-8dd4-51baba16702c.png)

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by wilkinsona** [comment]
With that said, you have some test suites in your tests. Test classes that are included in a suite will be run once as part of the suite and once individually.

**Comment by Mr-LiuDC** [comment]
@wilkinsona Thanks for your reply. 

These two links helped me：

[Stack Overflow](https://stackoverflow.com/questions/34720745/why-are-junit-tests-run-twice-from-within-eclipse/34722465#34722465) and [maven-surefire-plugin](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html)

As for the gradle project, just add this in the `build.gradle` file.
`test {
    include "package/path/to/YourSuiteTest.class"
}`
