### ISSUE TITLE
@PostConstruct runs before @Sql

### ISSUE THREAD

**Issue by markgeek** [spring-projects/spring-boot#13761]
```java
@RunWith(SpringRunner.class)
@Sql("classpath:/import_data.sql")
@TestPropertySource({"classpath:/application-test.properties"})
@SpringBootTest(classes = {TestConfiguration.class})
public class ATests {

  @Autowired
  MyBean myBean;

}

@Component
class MyBean {

  @PostConstruct
  public void init() {
    // here some db operations
  }

}
```

when I test it, it throws exception which tells me that there is not any table structure there, but in `import_data.sql` I do create the table and insert some data, if I do the db operations later, it will success

**Comment by wilkinsona** [comment]
Both `@Sql` and the calling of `@PostConstruct` are handled by Spring Framework rather than Spring Boot. Also, I believe this is working as designed. The default execution phase for `@Sql` is `BEFORE_TEST_METHOD` (the other option is `AFTER_TEST_METHOD`). The application context is refreshed, and therefore `@PostConstruct` is called, once for the whole test class (in fact it could be once for multiple test classes if they share the same configuration) which happens before individual test methods are called. In other words, you cannot use `@Sql` as a means of preparing the database for calls that are made in `@PostConstruct`.

**Comment by dantebarba** [comment]
Whats the use of @Sql if I can't manage to control the execution phase for schema configuration before tests?.
Sounds like an option like BEFORE_CONTEXT_INIT should exist.

**Comment by wilkinsona** [comment]
@dantebarba As I said above, `@Sql` and `@PostConstruct` are handled by Spring Framework rather than Spring Boot. Suggestions for changes to Spring Framework should be made via their [JIRA](https://jira.spring.io/browse/SPR).
