### ISSUE TITLE
@ExceptionHandler could not catch business exception bug?

### ISSUE THREAD

**Issue by friends110110** [spring-projects/spring-boot#13763]
My springboot version is 2.0.2, and 
My code is :
```
@RequestMapping("/bde")
@RestController
@RestControllerAdvice
public class BDEApi {
    @RequestMapping(value = "/xx",method = RequestMethod.POST)
    public ResponseEntity storageHash( ) {
        LOGGER.info("enter in --------------->");
            int i=1/0; // here will throw exception, but could not be catched by below handleException method
  }

    @ExceptionHandler(Exception.class)
    @ResponseBody
    public Result handleException(Exception e, HttpSession session, HttpServletRequest request, HttpServletResponse response) {
        LOGGER.error(e.getMessage());
  }
}
```
handleException could not catch my defined business exception(which extends RuntimeException) in springboot 2.0.2 version ?

**Comment by wilkinsona** [comment]
It’s difficult to suggest what the problem may be as the code above does not compile (`handleException` isn’t returning anything). Also, support for `@ExceptionHandler` is provided by Spring Framework rather than Spring Boot so this isn’t the right place to report a bug (assuming there is one).

I recommend asking a question on Stack Overflow with a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).
