### ISSUE TITLE
Check and remove any `@Lazy` injection

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#13785]
`@Lazy` on injection can cause problems such as [SPR-16990](https://jira.spring.io/browse/SPR-16990). It would be better if we use an explicit `ObejctProvider`.

**Comment by bclozel** [comment]
I've tried updating the `HttpMessageConverters` injection point in `WebMvcAutoConfiguration` into an `ObjectProvider` instead of a lazy injection point.

It seems this was done on purpose as the following test fails locally after that change: `WebMvcAutoConfigurationTests#httpMessageConverterThatUsesConversionServiceDoesNotCreateACycle`

This test is checking that a user-defined `HttpMessageConverter` bean requiring a `ConversionService` does not create a cycle. This lazy injection point is fixxing gh-9409 (the commit message describes well the situation).

Is there another way to break that cycle without involving proxies?

**Comment by bclozel** [comment]
I thought I did, but of course, I didn't. Thanks a lot @wilkinsona

**Comment by bclozel** [comment]
Still one `@Lazy` left in `ValidationAutoConfiguration`, got to check that one first before closing this issue.

**Comment by bclozel** [comment]
It looks like we need to let that last one in.
