### ISSUE TITLE
JdbcTemplateAutoConfiguration imports JdbcTemplateConfiguration twice

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#13806]
It gets included as a nested class anyway, and then also `@Imported` unconditionally. I'm surprised it doesn't generate an exception in Spring Boot 2.1. It doesn't, but probably could be tidied up anyway.

```java
public class JdbcTemplateAutoConfiguration {

	@Configuration
	static class JdbcTemplateConfiguration {
		...
	}

	@Configuration
	@Import(JdbcTemplateConfiguration.class)
	static class NamedParameterJdbcTemplateConfiguration {
		...
	}
}
```

**Comment by snicoll** [comment]
That's on purpose to teach the context in which order it has to load those two nested configurations. I've applied that after a chat on that problem with [~jhoeller]. What's the concern?

**Comment by wilkinsona** [comment]
My understanding is that it'll only import it once as well. However, I find the current arrangement rather confusing and it feels like a problem similar to the one fixed in https://github.com/spring-projects/spring-boot/commit/73a08dd6689dcb420541b13701aa448a995c95a5 waiting to happen again.

Could we move `JdbcTemplateConfiguration` out into a separate top-level class?

**Comment by wilkinsona** [comment]
Unrelated, but we should probably make `JdbcTemplateConfiguration` itself `@ConditionalOnMissingBean(JdbcOperations.class)`. While it'll still be processed as a configuration class, it would avoid it being registered as a bean when the use provides their own `JdbcOperations`.
