### ISSUE TITLE
ZipInflaterInputStream  native memory leak

### ISSUE THREAD

**Issue by zhujibing** [spring-projects/spring-boot#13935]
`ZipInflaterInputStream` constructor function will create Inflater object where use native memory，but Memory is not freed。

**Comment by wilkinsona** [comment]
We can't set `usesDefaultInflater` as it's a package-private field. We also aren't using the default `Inflater`; we're creating one with `new Inflater(true)`.

> wo should not depend on gc. native memory is hard to release , because Inflater enter old generation.

The GC generation of the object should not make any difference. AFAIK, its memory (and any associated native memory) will be freed when it is eligible for garbage collection.

Rather than describing a theoretical problem, perhaps you can provide a small sample that shows a failure due to memory being leaked?

**Comment by izeye** [comment]
I guess @zhujibing tried to say a general rule that releasing resources explicitly whenever possible is better than resorting to GC, so I just created #14001 to resolve the concern.

**Comment by wilkinsona** [comment]
Closing in favour of #14001.
