### ISSUE TITLE
build spring-boot-2.0.3.RELEASE

### ISSUE THREAD

**Issue by amoswxz** [spring-projects/spring-boot#13954]
[INFO] Build Summary:
[INFO]   Passed: 36, Failed: 2, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  start-stop-automatic-fork/pom.xml
[ERROR] *  start-stop-fork/pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:28 min
[INFO] Finished at: 2018-07-31T16:05:18+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.1.0:run (integration-test) on project spring-boot-maven-plugin: 2 builds failed. See console output above for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by amoswxz** [comment]
[INFO] Running post-build script: /Users/mujourney/Study/spring-boot-2.0.3.RELEASE/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/target/it/start-stop-fork/verify.groovy
[INFO]           start-stop-fork/pom.xml .......................... FAILED (7.5 s)
[INFO]   The post-build script did not succeed. Start should have waited for application to be ready

**Comment by wilkinsona** [comment]
The build works fine for everyone on the team and on CI so I suspect the problem is in your environment or that you haven't run the right command. If you'd like some help with building the project, please come and chat [on Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
