### ISSUE TITLE
 How can I change the default endpoint path of SpringBoot Admin

### ISSUE THREAD

**Issue by nvtrung12** [spring-projects/spring-boot#13953]
Dear team,
Firstly i want to say thank you for your good idea to monitor springboot App .
I use jhipster framwork (it's including springboot 1.5.9, angularjs,..) for developing 4 my web applications on the different linux servers  .
My issues happend when i use SpringBoot Admin to monitor these appications. All these applications have endpoint api path which is /management/health,   /management/logger ,/management/metrics ,/management/..
So my question is how can i change default endpoint path in Springboot Admin ?

Thank you so much for your help !

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by nvtrung12** [comment]
**
![image](https://user-images.githubusercontent.com/9255479/43446571-6f2d55ca-94d3-11e8-8884-c4ee148892e5.png)
**
I dont know it's bug or not . My divine presence is the endpoint path issue . but i'm not sure . You can see the photo which i send to you

**Comment by wilkinsona** [comment]
I haven't seen anything to suggest it's a bug. Furthermore, Spring Boot Admin is a [separate project](https://github.com/codecentric/spring-boot-admin/).
