### ISSUE TITLE
springboot can not obtain  body information of HttpServletRequest

### ISSUE THREAD

**Issue by qianhen-hf** [spring-projects/spring-boot#13978]
i want to  get  body information of HttpServletRequest ,but i find  the  body information of HttpServletRequest is null.
if you use primordial of spring ,you can get   body information of HttpServletRequest ,
i thinks   Built-in container of  springboot  have   issue。Please give a solution。

![1234](https://user-images.githubusercontent.com/21163870/43559939-d4febda6-9642-11e8-8eb6-2a04bc0a34b0.png)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
