### ISSUE TITLE
How can I add custom message after HTTP status code?

### ISSUE THREAD

**Issue by ajianzheng** [spring-projects/spring-boot#14048]
https://stackoverflow.com/questions/51762481/how-can-i-add-custom-message-after-http-status-code/51815387#51815387

**Comment by ajianzheng** [comment]
https://stackoverflow.com/questions/51762481/how-can-i-add-custom-message-after-http-status-code/51815387#51815387

**Comment by snicoll** [comment]
Thanks for getting in touch, but as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Rather than asking a question in an answer, please open a separate SO thread.

**Comment by ajianzheng** [comment]
Sorry for asking question here, but no suitable answer has been found on stackoverflow.
