### ISSUE TITLE
spring boot ssl with standalone tomcat (not embedded tomcat)

### ISSUE THREAD

**Issue by BigGitWorld** [spring-projects/spring-boot#14135]
I have read several tutorials about enabling https in spring boot project with embedded tomcat.
But I couldn't find any tutorial about standalone tomcat too.
is there anyone who can help me?
How do I configure spring boot project to enable ssl with standalone tomcat?
thank you...

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
