### ISSUE TITLE
Spring Boot Security : Exception thrown in custom filter not working

### ISSUE THREAD

**Issue by sharmmoh1983** [spring-projects/spring-boot#14179]
I am using spring boot security and creating JWTCustomer filter to validate the token and a custom voter to do authorization logic. In case of any issue with the token , I am throwing user defined exception which will be handled by exception handler to generate Error json message

But in actual , after throwing exception I am getting following :

```
Request received for POST '/error':

Request(POST //localhost:8080/error)@10fce0

servletPath:/error
```

I am using following configuration:

```
http.cors()
    .and()
    .csrf()
    .disable()
   .authorizeRequests()
   .anyRequest()
   .authenticated();

http.addFilterBefore(authenticationTokenFilterBean(), UsernamePasswordAuthenticationFilter.class);

        http.authorizeRequests().accessDecisionManager(accessDecisionManager());
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by sharmmoh1983** [comment]
I have posted it on stackoverflow but there seems to be no response.Please assist me in knowing the cause of the issue as I am struggling to get  through it
