### ISSUE TITLE
Unit test using WebTestClient (POST with empty body, check status 400) fails with 2.0.4.RELEASE but ok with 2.0.2.RELEASE

### ISSUE THREAD

**Issue by marcpa00** [spring-projects/spring-boot#14174]
Sample project showing the issue available at https://github.com/marcpa00/verify-400-with-empty-body

With Spring Boot 2.0.2.RELEASE, doing a POST with an empty body and asserting the response code is 400 works, changing for Spring Boot 2.0.4.RELEASE, the same test fails.
Currently, this is also using spring rest docs, I will try to remove that from the equation.

**Comment by marcpa00** [comment]
FYI : Removing spring restdocs gives same outcome.

**Comment by marcpa00** [comment]
I've simplified as much as I could the code to reproduce the problem : no more lombok, no UUID nor DTO (payload is simply a String), no ExceptionHandler, no boot actuator.
Outcome hasn't changed.
Tell me if there is anything else I can try.

**Comment by marcpa00** [comment]
For the record, same results with Spring Boot 2.1.0.M2

**Comment by bclozel** [comment]
Overriding the Spring Framework version to 5.0.7 instead of 5.0.8 works around that problem. This shows that this is likely to be a Spring Framework problem in the first place.

I tracked the issue down to a change in Spring Framework 5.0.8, namely [SPR-16949](https://jira.spring.io/browse/SPR-16949). I've created [SPR-17220](https://jira.spring.io/browse/SPR-17220) to fix that.

In the meantime, you can work around this problem by replacing `Mono.empty()` with `Flux.empty()`; the effect is the same but you're not going through the same code path.

I'm marking this issue as invalid as it's a Spring Framework problem, but it doesn't mean your report was not useful, quite the opposite. Thanks for the repro project, as usual they help a lot!
