### ISSUE TITLE
AutoConfigure Disable at Not working if Configured in Class.

### ISSUE THREAD

**Issue by SanjayGautam** [spring-projects/spring-boot#14229]
I have included the quartz starter , but this is in one jar , this jar is a generic framework and I use with different application, when I include some application really don't need Quartz starter, `SchedularFactory` being getting instantiated.  Below is the step to disable auto-configure. 

**1.  Java Configuration  : DOES NOT WORK** 

```java
@Configuration
@EnableWs
@EnableAutoConfiguration(exclude= {QuartzAutoConfiguration.class})
@EnableTransactionManagement
@ComponentScan(basePackages = { "com.caiso.*" })
@EnableAsync
@EnableAspectJAutoProxy
```

**i.e. quartz scheduler still get instantiated not expected**

**2. Properties file declaration WHEN I USE IN PROPERTIES FILE IT WORKS.** 

```
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
```

**i.e. quartz schedular does not get instantiated as expected**  

Thanks
Sanjay Gautam

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by SanjayGautam** [comment]
I feel that this is a defect , why would the property or java exclude annotation should working just wondering. ?

**Comment by philwebb** [comment]
@SanjayGautam Can you share a project that demonstrates the problem.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
