### ISSUE TITLE
Allow to disable TaskExecutor creation

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#14233]
Spring Boot 2.1 added auto-configuration for a `TaskExecutor` and `TaskScheduler`, however these re always created even if we don't want it. It would be nice if we could easily enable/disable this features. 

So this is a request to add an `enabled` property on both `TaskExecutionProperties` and `TaskSchedulingProperties` (defaulting to `true`) and honor the settings when switched to `false`.

**Comment by snicoll** [comment]
Thanks but you haven't really explained what the problem is. As you're probably aware, we are not keen to add `enabled` flags for auto-configurations so that's likely not to happen.

What is the problem?

**Comment by snicoll** [comment]
> these re always created even if we don't want it.

That statement is wrong for `TaskSchduler`: it should only be created if `@EnableScheduling` has been set somewhere. `TaskExecutor` costs zero (doesn't start a thread and is fully lazy) which is why we thought it was affordable to create it.

**Comment by mdeinum** [comment]
Well generally I don't like beans that get created that I don't need. And I noticed a changed output when running a sample:

```
2018-08-29 09:15:17.102  INFO 72121 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService  'applicationTaskExecutor'
```

This was basically the trigger for creating this issue (or feature request rather I guess). 

Also nothing is for free, creating an object costs time and memory although maybe not that much it still adds to the memory (and a lot of small ones make a large one eventually). 

However I'm also aware that this might not be as simple as requesting to easily disable this feature. The `applicationTaskExecutor` is also used for the async web part. Which might lead to confusing results for users to expect that to work and suddenly that stops working by disabling regular task execution. 

Didn't realize that `TaskScheduler` was bound to `@EnableScheduling` being added (didn't check that deep, but rather assumed things, again those pesky assumptions).

**Comment by snicoll** [comment]
I don't think relying on a log entry is very rational. An `AsyncTaskExecutor` may just as well be created behind your back with no log at all because no alternative exists. 

> Also nothing is for free

I agree with that but there is nothing particular with that `@Bean` with regards to other beans that could be created unconditionally. I agree however this one is a bit special as we can't restrict by classpath scanning (since the required dependency is "always" there).

Just to give a bit more background, we were two ways about this one and found out that the cost of creating the object was so small than it wasn't worth creating complex conditions. Also, the more support we add that requires task execution, the more complex that condition is going to be. 

If you're happy with an `enabled` flag, you should exclude the auto-configuration. That's by no mean a recommendation though as I always have a feeling we've done something wrong when someone does that.

**Comment by snicoll** [comment]
We've discussed this one in the team meeting and we don't see a compelling reason to change the current arrangement.
