### ISSUE TITLE
How to get actuator health information in spring boot application self。

### ISSUE THREAD

**Issue by renkang** [spring-projects/spring-boot#14245]
@philwebb I what get actuator health after spring boot application start. not get the health information by http request. how can i do?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
