### ISSUE TITLE
can not resolve configuration properties "spring.data.maxActive"

### ISSUE THREAD

**Issue by yueru-mylove** [spring-projects/spring-boot#14272]
When I building my application with spring-boot  1.5.9 or 1.5.3. The yml config file always can only resolve 
spring.datasource.type/username/password/driver-class-name/url and can not resolve any other datasource properties. Could you tell me why?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by yueru-mylove** [comment]
So sorry about that sir. I will do that.
