### ISSUE TITLE
Only the last RouterFunction<> is available with the Kotlin bean DSL

### ISSUE THREAD

**Issue by tgirard12** [spring-projects/spring-boot#14295]
I have an app that add several `RouterFunction<ServerResponse>` with the Kotlin bean DSL and
only the routes from the latest bean of type `RouterFunction<>` is available on the server.

I have test this app with Spring-boot **2.0.4** and **2.1.0.M2** on Netty.

This is a sample app. You can change the order of the two router declaration and re-run the Unit test.

[spring-boot_several-router.zip](https://github.com/spring-projects/spring-boot/files/2347886/spring-boot_several-router.zip)

**Comment by bclozel** [comment]
Hi @tgirard12 , thanks for the repro project.

This looks like a usability/implementation/documentation issue in the bean registration DSL. I've created [SPR-17242](https://jira.spring.io/browse/SPR-17242) for that. It seems defining multiple beans of the same types without providing a bean name is the source of the problem here.

In the meantime, you can use the `@Bean` variant when registering beans, or add bean names like this:

```kotlin
val beans = beans {
    // TODO Change the order of the declaration
    bean("fooRouter") { fooRouter() }
    bean("barRouter") { barRouter() }
}
```
I'm closing this issue as there's nothing we can do in Spring Boot.

**Comment by tgirard12** [comment]
Thanks for the quick reply and creating this issue, it fixed my problem.
