### ISSUE TITLE
Move 'spring.insights.web' properties to 'spring.http'

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#14313]
I'm not sure if we should move the `spring.insights.web.log-request-details` property elsewhere. It feels like it could become a central dependency that lots of packages start to use.

**Comment by bclozel** [comment]
We could split it back and have both `spring.mvc.log-request-details` and `spring.webflux.log-request-details`. We already have `spring.mvc.log-resolved-exception` so it's not unusual.

It's just duplicating things a bit but maybe at this time, we don't have enough visibility about such features and it's not worth creating a new namespace at that point.

**Comment by philwebb** [comment]
I think I prefer the duplication at this point, but lets see if anyone else has an opinion.

**Comment by snicoll** [comment]
It really depends what we're trying to build. At this stage it is very limited so I agree a single "web" property would be enough (I am really not keen to have a "webflux" and "webmvc" property for this). 

The intention was that we may want to improve this support in the future so that non-web components would also be taken into account (or other tuning options). But that's still vague so +1 for nuking it as long as we have a single web-related property.
