### ISSUE TITLE
In some cases, @ConfigurationProperties may not work

### ISSUE THREAD

**Issue by kiansoung** [spring-projects/spring-boot#14334]
This problem has been bothering me for a long time, and I have found many websites that have not been resolved. I don't know if this is a problem.

I wanted to configure a data source with the following code:
```
@Configuration
@EnableTransactionManagement
Public class MysqlConfig {

    @Bean
    @ConfigurationProperties(prefix = "mybatis.config")
    Public MybatisConfigProperties mybatisConfigProperties() {
        return new MybatisConfigProperties();
    }
}
```

If I use the above code, MybatisConfigProperties is not injected with the property successfully!

Please don't doubt, there is no task problem in my properties file, it has the corresponding value, because the MybatisConfigProperties injection property is successful in the startup class, yes, you are not mistaken.

```
@Slf4j
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class,
        DruidDataSourceAutoConfigure.class, MybatisAutoConfiguration.class})
Public class HouseDrawServiceProvider {

    @Bean
    @ConfigurationProperties(prefix = "mybatis.config")
    Public MybatisConfigProperties mybatisConfigProperties() {
        return new MybatisConfigProperties();
    }

    Public static void main(String[] args) {
        ApplicationContext ctx = new SpringApplicationBuilder()
                .sources(HouseDrawServiceProvider.class)
                .web(false)
                .run(args);
        // mybatisConfigProperties injected successfully, with value
        log.info("mybatisConfigProperties => {}", ctx.getBean("mybatisConfigProperties"));
    }
}
```

I don't know why this is, I hope you can help me, I will be very grateful.

**Comment by snicoll** [comment]
I see no difference between the first and the second example and no explanation as how we could reproduce the problem concretely. Can you share a sample that we can run ourselves that demonstrates the problem you are experiencing?

**Comment by wilkinsona** [comment]
`MapperScannerConfigurer` is a `BeanDefinitionRegistryPostProcessor` which is a special type of `BeanFactoryPostProcessor`. Bean post-processors are created very early in the application's lifecycle so that they can post-process all of the application's beans. The definition of your `MapperScannerConfigurer` bean depends on your `MyBatisConfigProperties` bean. The means that `MyBatisConfigProperties` is created very early and before configuration property binding is possible. Generally speaking, injecting any dependencies into a `BeanDefinitionRegistryPostProcessor` is to be avoided for exactly this sort of reason.

If you'd like some further guidance on how to rework your application to avoid the problem described above, please ask a question on Stack Overflow or chat with the community on Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
