### ISSUE TITLE
SimpleXsdSchema - NullPointerException

### ISSUE THREAD

**Issue by esfomeado** [spring-projects/spring-boot#14410]
When creating a SimpleXsdSchema i get an NullPointerException.

    @Bean
    public DefaultWsdl11Definition defaultWsdl11Definition() throws Exception
    {
        SimpleXsdSchema userschema = new SimpleXsdSchema();

       ...
    }

> Method threw 'java.lang.NullPointerException' exception. Cannot evaluate org.springframework.xml.xsd.SimpleXsdSchema.toString()

Using spring-boot 2.0.4

**Comment by wilkinsona** [comment]
Thanks for the report, but `SimpleXsdSchema` is part of Spring Web Services. Its issue tracker is [here](https://jira.spring.io/projects/SWS).

The `toString()` of `SimpleXsdSchema` relies on its `schemeElement` having been initialised. This happens when `afterPropertiesSet()` is called as part of the standard bean lifecycle. If you call `toString()` before then, for example within your `@Bean` method an NPE will occur. It's probably worth raising a Spring Web Services issue to make this more robust.

**Comment by gregturn** [comment]
Thanks @wilkinsona. I opened https://jira.spring.io/browse/SWS-1037 to track this.
