### ISSUE TITLE
freemarker

### ISSUE THREAD

**Issue by WangLei2016** [spring-projects/spring-boot#14457]
```java
	@RequestMapping("a/b")
	 public String getHome( ModelMap modelMap) throws JsonParseException, JsonMappingException, IOException {
		
		homeService.getHostInfo(modelMap);
		return "/pc/index";
	}
```

If there are more than 2 interface access paths, I will automatically add a path to css in static.

For example, the above code, my css access path will become

http://127.0.0.1:8080/a/css/index.css

I don't want him to give me this path.

But if it is

```java
	@RequestMapping("/b")
	 public String getHome( ModelMap modelMap) throws JsonParseException, JsonMappingException, IOException {
		
		homeService.getHostInfo(modelMap);
		return "/pc/index";
	}
```

This is what I want
what should I do

http://127.0.0.1:8080/css/index.css

pom.xml

```xml
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-freemarker</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
```
		
application.properties

all  default

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
