### ISSUE TITLE
Use ObjectProvider<T> with ordered list access instead of ObjectProvider<List<T>>

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#14467]
As discussed in [SPR-17272](https://jira.spring.io/browse/SPR-17272) (which is now fixed on Spring Framework `master`), `ObjectProvider` now provides ordered list access, superseding `ObjectProvider<List>`.

In addition to follow best practices, updating Boot auto-configuration classes to use `ObjectProvider<T>` parameters with ordered list access instead of `ObjectProvider<List<T>>` would make it usable with `BeanFactory.getBeanProvider()`, required with functional bean registration like in [Kofu configuration](https://github.com/spring-projects/spring-fu#kofu-configuration) or @dsyer work in [spring-boot-micro-apps](https://github.com/dsyer/spring-boot-micro-apps).

**Comment by wilkinsona** [comment]
I've got an attempt at this in [this branch](https://github.com/wilkinsona/spring-boot/tree/object-provider). Unfortunately, `CustomHibernateJpaAutoConfigurationTests.hibernatePropertiesCustomizersAreAppliedInOrder()` is currently failing due to the customisers being applied in the wrong order. The customizers are being retrieved using the following code:

```
hibernatePropertiesCustomizers.orderedStream().collect(Collectors.toList())
```

`hibernatePropertiesCustomizers` is an `ObjectProvider<HibernatePropertiesCustomizer>`. Injecting `ObjectProvider<List<HibernatePropertiesCustomizer>>` into the same place and calling `getIfAvailable()` produces a list with the same two customisers but in the reverse order. This looks like a Framework bug but I've yet to reproduce it in a standalone test. /cc @jhoeller for awareness just now. I'll dig some more tomorrow.

**Comment by jhoeller** [comment]
Let's try to sort this out tomorrow morning if we can. This is important enough for 5.1 GA still.

**Comment by wilkinsona** [comment]
The problem's occurring because the ordering information isn't available. It isn't available as the order source provider doesn't have the right information. In `resolveMultipleBeans`, the matching beans returned by `findAutowireCandidates(String, Class<?>, DependencyDescriptor)` is a `Map<String, Class>` with the following contents:

```
{sampleCustomizer=interface org.springframework.boot.autoconfigure.orm.jpa.HibernatePropertiesCustomizer, anotherCustomizer=interface org.springframework.boot.autoconfigure.orm.jpa.HibernatePropertiesCustomizer}
```

In `createFactoryAwareOrderSourceProvider(Map<String, ?>)` the `instancesToBeanNames` map ends up with a single entry as the keys clash. When the order is being looked up, the key that's used is the lambda that implements `HibernatePropertiesCustomizer` so nothing's found and `LOWEST_PRECEDENCE` is used in each case.

Despite figuring this much out, I'm not yet able to reproduce it in a standalone test. In my attempt at doing so, the map returned from `findAutowireCandidates` contains actual instances rather than just the `Class` and everything works as expected from there.

**Comment by jhoeller** [comment]
This is sorted out on master now. Please give it a try!

**Comment by wilkinsona** [comment]
@sdeleuze has identified some cases with Spring Fu where a failure occurs due to a `Stream` being used more than use. It's probably too brittle to assume single-use, even in places where the annotation-based configuration model guarantees that'll be the case.

**Comment by jhoeller** [comment]
Definitely hold on to the `ObjectProvider` in general. This reuse problem is also a reason why we don't support the injection of `Stream` as a direct autowiring argument but rather force people to go through `ObjectProvider` as a factory for it.
