### ISSUE TITLE
spring data mongo  transition

### ISSUE THREAD

**Issue by jameswangAugmentum** [spring-projects/spring-boot#14488]
- No collection  was created in Mongo（No user collection）, Using template to save objects(save user object)
```java
@Transactional
public void saveSingleObject() {
    template.save(new User("james", "james", 'ddd'));
}
```
- exception : Command failed with error 263 (OperationNotSupportedInTransaction): 'Cannot create namespace test-mongo.processes in multi-document transaction.

-   but  User collection  in mongo , no  exception

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by jameswangAugmentum** [comment]
- [this question StackOverflow. ](https://stackoverflow.com/questions/52365761/spring-data-mongo-transition)
