### ISSUE TITLE
Session time out is not working when I used @EnableSpringHttpSession 

### ISSUE THREAD

**Issue by Raghavender** [spring-projects/spring-boot#14500]
Previously I have used Session management with type JDBC with this Session timeout was working, which is configured in application.yml as sesrver.session.timeout:120, the session will expire after 2 minutes. 

Due to some performance issues, we have implemented Spring session management with Ignite cache using MapSessionRepository and annotated my configured class @EnableSpringHttpSession. With this approach, the session timeout is not working.

**Comment by vpavic** [comment]
If you're using `@EnableSpringHttpSession` (or any other `@Enable*Session` for that matter), Spring Boot isn't in control as you're configuring Spring Session by yourself and therefore any related configuration properties will not be applied.

Other than that, `MapSessionRepository` is really more of a convenience or testing solution, rather than full-blown `SessionRepository` implementation intended for production use. But if you do use it you need to be aware of its limitations - one of those is session expiry, which is a concern that's highly dependent on the underlying data store. This means that you should handle expirations (and session events, if you need them) by yourself at Ignite cache level.

Also note that these concerns are documented both in [`MapSessionRepository` javadoc](https://github.com/spring-projects/spring-session/blob/12bb0741bb48ace9ff9c448abd4de21593c6ce23/spring-session-core/src/main/java/org/springframework/session/MapSessionRepository.java#L26-L34) and Spring Session's [reference manual](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-enablespringhttpsession).

**Comment by wilkinsona** [comment]
Thank you, @vpavic.

**Comment by Raghavender** [comment]
Thanks, Vpavic and Wilkinsona for the response, now I understood the issue.
