### ISSUE TITLE
Create configuration property to enable/disable HiddenHttpMethodFilter with WebFlux

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#14520]
Quoting @rstoyanchev 
> `HiddenHttpMethodFilter` is for use with browsers, and having it on by default in WebFlux where the body isn't automatically parsed is debatable I think. So perhaps a Boot ticket is worth creating still.

See https://github.com/spring-cloud/spring-cloud-gateway/issues/541#issuecomment-422634564 for the discussion and workaround.

**Comment by spencergibb** [comment]
See also https://jira.spring.io/browse/SPR-17291

**Comment by bclozel** [comment]
It was introduced in gh-14008 - @rstoyanchev makes a good argument about that. It would still require us to disable that by default after enabling it in 2.0.5, and this would also be at odds with the current Spring MVC auto-configuration.

**Comment by bclozel** [comment]
We've discussed this and we think we should remain consistent here and register it still, because that's what we're doing for Spring MVC. 

Let's turn this issue into an enhancement and add property that enables/disables this filter, since we've got the equivalent for Spring MVC with `spring.mvc.hiddenmethod.filter.enabled`.

**Comment by spencergibb** [comment]
So I guess my temporary workaround will be permanent. https://github.com/spring-cloud/spring-cloud-gateway/commit/58834daf6271c3ae379f5eb0939689ad6a14036e

**Comment by bclozel** [comment]
Instead of relying on the bean name (and overriding a bean), couldn't you create an `EnvironmentPostProcessor` that adds a `PropertySource` to the environment as the last one and sets `spring.mvc.hiddenmethod.filter.enabled=false`?

This wouldn't be a workaround, since Spring Cloud Gateway is not a typical web application and needs some features to be disabled by default.

**Comment by spencergibb** [comment]
Sure, that works too.
