### ISSUE TITLE
HikariCP micrometer with multiple datasources

### ISSUE THREAD

**Issue by Allsimon** [spring-projects/spring-boot#14547]
I cannot get the HikariCP metrics when using a DataSourceLookup bean. 

Do we need to do 
```
  dataSource.setMetricRegistry(registry);
  addDataSource(dataSourceName, dataSource);
```
or is there a way to do it automagically ?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Allsimon** [comment]
I mean is this an oversight of the documented way to do it (see  https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/metadata/DataSourcePoolMetadataProvidersConfiguration.java and friends) and do you need a PR ?

**Comment by snicoll** [comment]
@Allsimon your original description is a question (that I am not sure I understood so you may want to take a bit more time to describe what you're after before asking on SO). The documentation is [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-jdbc) and states that all available `DataSource` beans will be automatically instrumented. If that's not what you're seeing, please share a sample we can run ourselves (github repo or link to a zip) and we can reconsider.

**Comment by Allsimon** [comment]
Sure that wasn't clear at all. It's exactly what you say:

I'm using the [DataSourceLookup](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/datasource/lookup/DataSourceLookup.html) class to register manually created DataSources.
They aren't instrumented.

Repro project is here: https://github.com/Allsimon/spring-boot-issue-14547-repro

**Comment by wilkinsona** [comment]
Any `DataSource` that isn't a bean will need to be registered manually.
