### ISSUE TITLE
Integration test fails when executing "mvn test" in a web project with JPA that has a schema.sql file

### ISSUE THREAD

**Issue by matsev** [spring-projects/spring-boot#1454]
When having a web-based project with a JPA based repository, `@WebAppConfiguration` integration test fails when executing `mvn clean test` when there is a `schema.sql` file present , despite setting `spring.jpa.hibernate.ddl-auto=` as described in chapter [63.3 Initialize a database using Spring JDBC](http://docs.spring.io/spring-boot/docs/1.1.x/reference/htmlsingle/#howto-intialize-a-database-using-spring-jdbc):

> If you want to use the schema.sql initialization in a JPA app (with Hibernate) then ddl-auto=create-drop will lead to errors if Hibernate tries to create the same tables. To avoid those errors set ddl-auto explicitly to "" (preferable) or "none".

---

Step by step:
1. Clone the reference project from GitHub: https://github.com/matsev/springboot.sql.jpa.bug
2. Execute `mvn clean test`

Expected result:
- All tests should pass

Actual result:

```
BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration' 
[...]
BeanCreationException: Could not autowire field: private javax.sql.DataSource org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.dataSource;
[...]
BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Initialization of bean failed;
[...]
BeanCreationException: Error creating bean with name 'dataSourceInitializer': Invocation of init method failed;
[...]
ScriptStatementFailedException: Failed to execute SQL script statement at line 1 of resource URL [[...]/target/classes/schema.sql]: CREATE TABLE person ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) ); nested exception is java.sql.SQLSyntaxErrorException: object name already exists: PERSON in statement [CREATE TABLE person ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) )]
```

---

Comments:
- The test pass the `schema.sql` file is deleted and the `spring.jpa.hibernate.ddl-auto=` is removed from the `application.properties` file
- The test pass if executed from within IntelliJ
- The test pass if `@WebAppConfiguration` is removed from the `PersonControllerTest` class.
- Changing the value of `spring.jpa.hibernate.ddl-auto` to `none` does not prevent the test from failing

Environment:
- Spring Boot 1.1.5.RELEASE
- Maven 3.2.3
- Java 1.8.0_20

**Comment by savinov** [comment]
I've faced with the same problem: due to twice schema.sql execution one of my tests failed when I run all tests (with IDE or Maven). But if I run this single test alone, there is no problems.
I use spring-boot 1.4.1, spring-data-jpa, hsqldb (for tests). There is schema.sql and data.sql in test resources folder. Test class is annotated with @RunWith(SpringRunner.class), @RunWith(SpringRunner.class) and @Sql. @Sql is placed at the class level. Actually, the problem appeared right after I started to use @Sql with additional script. If I remove it from the test class, or place it to the test method level there is no problems.

Workarond with spring.datasource.continueOnError=true makes all tests pass, but it's not a solution.
Unfortunatly I can't reproduce this problem with a sample project, maybe sample scripts or tests are executed differently from my project.

Could you reopen this issue to ivestigate and solve this problem please?

**Comment by wilkinsona** [comment]
The sample the reproduces the problem that this issue is about doesn't use `@Sql` so it's not clear that you actually do have the same problem.

If you do, then we've already investigated and offered three different solutions:

- Use `spring-datasource.continueOnError` (this is a solution if you can't write an idempotent script)
- Use Flyway or Liquibase
- Use profiles to avoid clashes

Unfortunately, re-opening the issue isn't going to change that.

**Comment by savinov** [comment]
I've found the source of my problem, made sample to reproduce and created new issue: https://github.com/spring-projects/spring-boot/issues/7416

Problem is the same: schema.sql executes twice, but the source of the problem maybe different, so take a look to the new issue.

**Comment by sunkuet02** [comment]
I am facing this problem as of now. Is there any work around solutions ?

**Comment by snicoll** [comment]
@sunkuet02 this issue is four years old so I am not sure what exact problem you're facing. If you think you've found a bug in Spring Boot, please create a new issue with a small sample we can run ourselves to reproduce the problem.
