### ISSUE TITLE
Make it easier to configure a JOOQ Execution Listener Provider that runs after Boot's default

### ISSUE THREAD

**Issue by aleksandar78** [spring-projects/spring-boot#14598]
Hi, 

I'm using spring boot 2.0.4 to config JOOQ DSLContext as it uses JOOQAutoConfiguration class. 
My problem is that provided translation to spring dao exceptions doesn't fit well with already created application error handling.
I need a custom ExecuteListener to translate JOOQ exception into application custom exceptions. 

I've tried to expose default listener provider as bean:
```java
@Bean
public DefaultExecuteListenerProvider applicationExceptionTranslatorExecuteListenerProvider() {
	return new DefaultExecuteListenerProvider(new ApplicationExceptionTranslator());
}
```
but JOOQ configuration doesn't pick up provider.

While searching around for other issues I've found in  #13329 the solution that works.  

```java
@Bean
public static BeanPostProcessor jooqConfigurationPostProcessor() {
	return new BeanPostProcessor() {

		@Override
		public Object postProcessBeforeInitialization(Object bean, String beanName)
				throws BeansException {
			return bean;
		}

		@Override
		public Object postProcessAfterInitialization(Object bean, String beanName)
				throws BeansException {
			if (bean instanceof DefaultConfiguration) {
				((DefaultConfiguration) bean).set(new JOOQExceptionTranslator());
			}
			return bean;
		}

	};
}
```
I need to know if this is the right way of doing it or there is some other way to provide ExecuteListenerProvider with custom ExecuteListener? 
Why exposing listenere provider as bean doesn't work, what am I missing?

Thanks

**Comment by wilkinsona** [comment]
Unfortunately, it's going to be difficult to diagnose exactly what's happening without a small sample that reproduces the problem. Hopefully you'll be able to provide one soon as we can't afford to spend the time that it would take to piece things together from a few code snippets. The risk of not reproducing the problem that you're actually seeing is too high for it to be worthwhile.

**Comment by aleksandar78** [comment]
Hi,

I've created the [github project sample](https://github.com/aleksandar78/spring-boot-jooq-demo)
with README and comments on how to reproduce the unexpected behavior.

Thanks again for your feedback.

**Comment by lukaseder** [comment]
I don't fully understand the idea behind calling `sqlException(null)`. What exactly do you want to prevent?

**Comment by wilkinsona** [comment]
The hope was to prevent any subsequent exception translation from occurring. I wondered if this could be done by nulling out the SQL exception so that subsequent translation doesn’t happen as there’s nothing to translate any more.

**Comment by lukaseder** [comment]
Hmm, that sounds too "clever". Besides, you're not really interested in overriding the `ExecuteContext.sqlException()`, but the `ExecuteContext.exception()`, which is the one that is being thrown by jOOQ... So I'm curious if there's really anything that would need to be changed in jOOQ?

**Comment by wilkinsona** [comment]
The `exception` is already being successfully overridden. The problem is that a subsequent translator contains logic like this:

```
SQLException exception = context.sqlException();
while (exception != null) {
	handle(context, translator, exception);
	exception = exception.getNextException();
}
```

`handle` makes the call to `ExecuteContext.exception(RuntimeException)`.

At this point, the SQL exception has already been translated and `ExecuteException.exception(RuntimeException)` has already been called. What we're looking for is a way to indicate that to subsequent translators so that they do not override the already overridden exception.

We could rely on ordering of translators, but that's a little wasteful as translation will then be performed multiple times but only used once. It's also a little less flexible in terms of being able to override a translator's behaviour in some cases while falling back in others.

It sounds like the above is what jOOQ offers, I just wanted to be sure that I hadn't missed a capability of the API. We can order our translator in the middle so that a user's translator to go before or after it depending on their needs. In the current arrangement they can only go before the default translator.

**Comment by lukaseder** [comment]
I see, thanks a lot for the explanation. Well, while I still don't fully recommend passing `null` around here, and abusing `null` as this "special value", I guess it wouldn't hurt to still accept `null` as a value for whatever reason the user might have. I have created an issue for this: https://github.com/jOOQ/jOOQ/issues/7909. It will be backported to 3.11 and 3.10

As a workaround, you can use a dummy `SQLException` singleton instance as a "signal" between translators, instead of this `null` value. It should have the same effect:

```java
private static final SQLException STOP_TRANSLATING = new SQLException();

// Later:
if (ctx.sqlException() != STOP_TRANSLATING)
  translate();
```

Hope this helps

**Comment by wilkinsona** [comment]
It does indeed. Thank you.

**Comment by wilkinsona** [comment]
I think we should still give our `jooqExceptionTranslatorExecuteListenerProvider` bean an order of 0 so that other providers can easily go after it. I'm not sure what version we should make that change in though.

**Comment by lukaseder** [comment]
Hi there, folks. https://github.com/jOOQ/jOOQ/issues/7909 has now been released in jOOQ 3.11.6, which will hit Maven Central soon.

Hope this helps

**Comment by aleksandar78** [comment]
Hi,

great job, everyone. 
I'll try it next week with Spring Boot 2.1. 

Thanks a lot

**Comment by aleksandar78** [comment]
Hi,

I've upgraded project dependencies with spring boot 2.1 and JOOQ 3.11.7. ( demo project is updated )
By adding Ordered.LOWEST_PRECEDENCE to custom ExecuteListenerProvider bean factory method the custom application exception is handled by the ControllerAdvice exception handler, behavior expected. 
If I've understood correctly @wilkinsona that is all I need to do to get the custom exception propagation. 
Stopping multiple exceptions translation will be done at a low level ( spring jooq integration ) or there is something that I should do at the application level? 

Thanks
