### ISSUE TITLE
Property Sources from config client not available to EnvironmentPostProcessor

### ISSUE THREAD

**Issue by edeandrea** [spring-projects/spring-boot#14607]
I'm not sure whether this is an issue with Spring Boot or Spring Cloud Config, so I'm going to post to both to try and get an answer and/or this resolved (see spring-cloud/spring-cloud-config#1149).

Spring Boot Version: `2.0.4.RELEASE` (same issue with `2.0.5.RELEASE` - haven't tested with prior versions)
Spring Cloud Config Client: `2.0.1.RELEASE`

When building a Spring Boot application and building an `EnvironmentPostProcessor` (& appropriately registering it within `spring.factories`) I'm noticing that properties coming from a `configService` property source are not available when the `EnvironmentPostProcessor` runs. When I'm stepping through in the debugger I don’t see the `configService` property source in the `ConfigurableEnvironment.getPropertySources()`.

Is this a bug? Is it by design? If its a bug, is the bug with spring-cloud-config or spring boot? I was expecting all properties to have been resolved from all sources so that an `EnvironmentPostProcessor` would have access to all properties to then make decisions.

**Comment by wilkinsona** [comment]
Please don't deliberately post duplicate issues.

An `EnvironmentPostProcessor` is intended to enable post-processing of the environment once it has been created. There's no guarantee that all properties will be available when a particular post-processor runs as other post-processors may not have run. This is true even if your post-processor is ordered with lowest precedence as other post-processors with the same order may still run after it.

I think this is either a misunderstanding of how environment post-processors are intended to be used or how Spring Cloud adds the property source for the config server to the environment. As such I think it's best diagnosed in the Spring Cloud issue. We can re-open this issue if that turns out to be necessary, but I'm going to close this one to avoid wasting people's time due to duplicated effort.

**Comment by edeandrea** [comment]
Thank you @wilkinsona for the quick response - it is much appreciated. I tried to post in the Spring Boot & Spring Cloud Gitter channels a few times over the last week but never got a response - so figured this was the next best option.

To your point
   
   > I think this is either a misunderstanding of how environment post-processors are intended to be used

My understanding (whether my understanding is/was correct or not is a different question :)) was simply that my post processor checked for the presence of a property (or that a property had a certain value) and based on that, would set another property to a particular value.

In the specific case where I found this, I have a post processor which is looking for the presence of the `spring.boot.admin.client.url` property. If not found then it sets `spring.boot.admin.client.enabled=false`.

On the config server side we have different configurations for different apps with different profiles, some of which set  `spring.boot.admin.client.url` to a value and some which don't. The application itself bundles the `spring-boot-admin-starter-client` dependency regardless. Whether or not to enable it is simply driven by the application's runtime target.

In your opinion would you classify that usage as a correct usage of how a post-processor is intended to be used?

**Comment by wilkinsona** [comment]
No. A post-processor the examines the existing environment and queries its properties to control its behaviour is brittle and is prone to ordering problems as you have seen here. If you have any further questions, please ask on Stack Overflow. 
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
