### ISSUE TITLE
Enhancement: RequestContextFilter ordering before SpringSessionFilter

### ISSUE THREAD

**Issue by pbialonc** [spring-projects/spring-boot#14623]
In current implementation request scoped beans cannot be injected into custom `SessionRepository` implementation, only option to do that is to change default `RequestContextFilter` ordering to be 
`SessionRepositoryFilter.DEFAULT_ORDER` `- 1`, if there is no reason why it should not be before `SpringSessionFilter` by default maybe we should change this ordering (I can't see such reason).

**Comment by philwebb** [comment]
It looks like we've refined the ordering previously in commit d9d4cc2ef5ab40f55e7a0cde68b1a5e78aefb4b3 (but that was related to security).

There's [a comment](https://github.com/spring-projects/spring-boot/blob/5863e6f78c78f840127b2ae64ea9c422a06df9f3/spring-boot/src/main/java/org/springframework/boot/context/web/OrderedRequestContextFilter.java#L31) in the existing code that makes me think the current order was intentional, but it's been there since the class was introduced and it's not immediately obvious to me why.

I'll flag this one to see if anyone else on the team has a better memory than me.

**Comment by mbhave** [comment]
#4331 seems to have some discussion around this.

**Comment by philwebb** [comment]
Unfortunately I think [this comment](https://github.com/spring-projects/spring-boot/issues/4331#issuecomment-242325652) in #4331 still stands and we shouldn't change the default ordering.
