### ISSUE TITLE
RedisHealthIndicatorConfiguration forces lazy beans initialization 

### ISSUE THREAD

**Issue by antonysychov** [spring-projects/spring-boot#14659]
autoconfiguration RedisHealthIndicatorConfiguration initiates lazy beans of type RedisConnectionFactory

**Comment by wilkinsona** [comment]
This issue is really just describing the current behaviour without saying if it's causing a problem and, if it is, what the problem may be. To justify spending some time on this and to consider changing something we'll need to know what the problem is that you're facing. Can you please provide some more details?

**Comment by antonysychov** [comment]
Thanks for reply 

We expect lazy beans to be initialized only when explicitly requested according to official documentation
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Lazy.html. 
In our case, we have some shared lib that declares multiple lazy beans that are supposed to be initialized only when requested (autowired, etc) by applications that use this lib.
Mentioned autoconfiguration adds kind of side effect, as it requests initialization of beans, that are not needed in an application.

**Comment by wilkinsona** [comment]
The beans are needed if health checking of Redis is enabled. If you don't want `RedisConnectionFactory` beans to be initialised so that Redis's health can be checked, you should set `management.health.redis.enabled=false`. If you want some `RedisConnectionFactory` beans to be health checked, but not all, you can create your own `HealthIndicator` bean named `redisHealthIndicator` configured with just the factories that you want to be health checked.

You may also be interested in a somewhat related issue on making the entire Actuator initialize lazily. Please see https://github.com/spring-projects/spring-boot/issues/7578 for details.
