### ISSUE TITLE
Provide dependency management for Yasson

### ISSUE THREAD

**Issue by juliovalcarcel** [spring-projects/spring-boot#14664]
Recently while updating an app from Spring Boot 1 to 2 and additionally updating Java EE from 7 to 8 I ran into an issue with the `JsonbAutoConfiguration` getting setup but it failing to find classes from Yasson.

Upon further research it looks like in order to get JSON-B to work with spring you have to pull in yasson and javax.json from glassfish according to https://www.e4developer.com/2018/03/04/introducing-json-b-with-spring-boot-2-0/

Would it not make sense to include either JavaEE in dependency management as well as Yasson or is there a longer term plan for how to prevent this in the future?

**Comment by philwebb** [comment]
I guess your original application had a `javax.json.bind-api` JAR but not an actual implementation? Can you describe a little more about your setup? Are you deploying to a Java EE 8 application server, or just trying to make use of Java EE 8 APIs in stand-alone Spring Boot application?

> Upon further research it looks like in order to get JSON-B to work with spring you have to pull in yasson

You need to have and API and an implementation, but I don't think it necessarily needs to be Yasson. We provide dependency management for [Apache Johnzon](https://johnzon.apache.org/) currently.

> Would it not make sense to include either JavaEE in dependency management as well as Yasson

I'm not keen on adding a managed JavaEE dependency since most typical Spring Boot developers need implementations as well as APIs. I prefer our current approach of pulling in individual spec APIs, rather than using the full JavaEE API JAR.

We could consider adding a Yasson dependency, but we typically only try to manage dependencies that are used directly in Spring Boot (or the Spring Boot tests).

I'll flag this issue to see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
I think we probably made a mistake when we [added the dependency management for Johnzon](https://github.com/spring-projects/spring-boot/commit/97aeaa4a32b244a2f7ff820cf37fbf788863ba3b). We only use it as a test-scoped dependency so it probably should have been managed in `spring-boot-parent`.

That said, it does make things a bit easier for those wanting to use JSON-B. Perhaps we should add dependency management for Yasson and update the tests to verify that things work as expected with either Yasson or Johnzon.

**Comment by juliovalcarcel** [comment]
@philwebb  We **were** using the Java EE 7 APIs in a standalone spring-boot app.... I was actually able to remove that dependency as whole, but before I realized we were no longer using the API I tried updating it from Java EE 7 to Java EE 8 (Just the API) and at that point the autoconfigure picked up that javax.json.bind.Jsonb was on the class path even though no implementation was available.   

I am not sure what pulled in Yasson specifically (If you would like I can try to reproduce the issue to get more details).

**Comment by wilkinsona** [comment]
> at that point the autoconfigure picked up that javax.json.bind.Jsonb was on the class path even though no implementation was available.

That sounds like a bug. What was the consequence of that set of dependencies?

**Comment by snicoll** [comment]
@wilkinsona the auto-configuration looks for `Jsonb` and uses the API hook-point to grab an instance. In retrospect, I agree it's probably too agressive.

**Comment by wilkinsona** [comment]
Answering [my own question](
https://github.com/spring-projects/spring-boot/issues/14664#issuecomment-426632928), the application fails to start. I've opened https://github.com/spring-projects/spring-boot/issues/14675.

**Comment by juliovalcarcel** [comment]
@wilkinsona Yup that is exactly what I was getting

**Comment by wilkinsona** [comment]
I'm in two minds about this now. Unlike Johnzon, Yasson is only an implementation of JSON-B. It does not implement JSON-P. It also doesn't have a transitive dependency on a JSON-P implementation so, if you only depend on Yasson, a failure will occur due to the lack of a concrete `javax.json.spi.JsonProvider` implementation. The default that the official JSON-P API jar looks for is `org.glassfish.json.JsonProviderImpl`.

I think we have two choices:

1. Add dependency management for Yasson and `org.glassfish:javax.json`
2. Do nothing

**Comment by jhoeller** [comment]
I wouldn't bother with Yasson since it is literally just the reference implementation of JSON-B, leaving other pieces up to other RIs. In contrast, Apache Johnzon is an actively developed standalone provider and seems much more recommendable for our purposes. Technically we can integrate with both, of course, but in terms of dependency management I'd rather only care for Johnzon.

**Comment by snicoll** [comment]
My vote is 2.

**Comment by wilkinsona** [comment]
Sold. Thanks, both.
