### ISSUE TITLE
log4j2 with spring-data-redis cannot disable netty logs in lettuce

### ISSUE THREAD

**Issue by Andreby42** [spring-projects/spring-boot#14706]
I use log4j2 with springBoot2.0.5, also use spring-data-redis

but the console always print some debug or trace log with netty;

so I check my dependencies; I found that spring-data-redis  has the lettuce but lettuce depends on

netty, 

I write codes like this in log4j2.xml
` <logger name="org.apache.http" level="WARN" />
   	<logger name="io.netty" level="WARN" />`
but it does not work

so  how should I do?

**Comment by Andreby42** [comment]
logs like this 
`[13:15:34:890] [DEBUG] - io.netty.util.internal.logging.Slf4JLogger.debug(Slf4JLogger.java:81) - Resolved SocketAddress 127.0.0.1:6379 using RedisURI [host='127.0.0.1', port=6379]
[13:15:34:891] [DEBUG] - io.netty.util.internal.logging.Slf4JLogger.debug(Slf4JLogger.java:76) - Connecting to Redis at 127.0.0.1:6379`
I do not find some log properties  with spring-data-redis

**Comment by Andreby42** [comment]
guys u know that, useless log will delay the software

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
