### ISSUE TITLE
When using WebFlux, having Jersey on the classpath without an embedded servlet container causes the web application type to be deduced as none

### ISSUE THREAD

**Issue by myninjagos** [spring-projects/spring-boot#14701]
since 2.0.4 if jersey is present on classpath application starts and stops immediately.

**Comment by wilkinsona** [comment]
This is intentional. When both WebFlux and Spring MVC are on the classpath, we prefer Spring MVC. We've now prefer Jersey in the same way. See https://github.com/spring-projects/spring-boot/issues/13521 for details.

It's a little surprising that the application stops, rather than launching Jersey on top of an embedded servlet container. Do you just have Jersey on the classpath, but without an embedded servlet container also being there?

**Comment by myninjagos** [comment]
yeap:)

**Comment by wilkinsona** [comment]
Ok, thanks for the confirmation. I'm not sure there's much we can do about that. You'll get the same behaviour if you have WebFlux, Spring MVC, and the Servlet API on the container but no embedded servlet container

I'll leave this open for now as we might be able to come up with something. In the meantime, you can just set the web application type on your `SpringApplication`:

```
new SpringApplicationBuilder(Gh14701Application.class)
	.web(WebApplicationType.REACTIVE)
	.run(args);
```

**Comment by myninjagos** [comment]
great:):)
thanks a lot

**Comment by wilkinsona** [comment]
Let's keep this open for now. There might be a refinement that we can make. For example, we using `DispatcherServlet` to check for the presence of Spring MVC. That has the side-effect of also requiring the Servlet API to be on the classpath. There may be a similar class in Jersey that we could use to even more closely align the behaviour.

**Comment by wilkinsona** [comment]
`org.glassfish.jersey.servlet.ServletContainer` looks like a good option, it's both a `javax.servlet.http.HttpServlet` and a `javax.servlet.Filter`.
