### ISSUE TITLE
Add modelmapper to spring dependencies

### ISSUE THREAD

**Issue by sylvainmouquet** [spring-projects/spring-boot#14704]
Hello,

ModelMapper is a tool to simplify the mapping between 2 models (by example between a POJO and a DTO)

http://modelmapper.org

It's possible to add this dependency in the spring dependencies? 
What is the process to add a new dependency ? 

Thanks
Sylvain

**Comment by philwebb** [comment]
In order to keep the dependencies POM manageable on our end we try to only add dependencies that we directly support ourselves. Since we don't directly integrate with ModelMapper, we'd rather not add it to the dependencies POM.

We previously referenced a [3rd party starter for ModelMapper](https://github.com/jmnarloch/modelmapper-spring-boot-starter) but it was removed when Boot 2.0 was released because [of this issue](https://github.com/jmnarloch/modelmapper-spring-boot-starter/issues/5). It looks like that project might now be abandoned. We'd be happy to add an alternative starter back to the list if some makes a Spring Boot 2.0 compatible version.
