### ISSUE TITLE
Spring boot web services Error 404

### ISSUE THREAD

**Issue by achemlalayoub10** [spring-projects/spring-boot#14710]
I have deployed my spring boot application by extracting the WAR file into a shared TOMCAT server, the database has been successfully created but i can not access my web services (Error 404) when i type exp : www.saidcar.com (whitelabel error page 403) 👍  but when I type www.saidcar.com/homeM I get 404 from my hosting 👎 

![image](https://user-images.githubusercontent.com/24244992/46572937-07e44080-c986-11e8-9e66-8b2de534886a.png)

my app works very well in tomcat on my machine

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
