### ISSUE TITLE
WebFlux: @ResponseStatus does not work out of the box, but ResponseStatusException does

### ISSUE THREAD

**Issue by mmanciop** [spring-projects/spring-boot#14742]
As documented in https://github.com/mmanciop/response-status-repro, `@ResponseStatus` does not work out of the box with WebFlux applications, but `ResponseStatusException` does.

I think `ResponseStatusException` works and not `@ResponseStatus` due to `org.springframework.boot.web.reactive.error.DefaultErrorAttributes#determineHttpStatus` and other methods.

I truly cannot tell if this is by design or by oversight. Would it make sense for me to open a PR and add `@ResponseStatus` support to `org.springframework.boot.web.reactive.error.DefaultErrorAttributes`?

**Comment by philwebb** [comment]
I've dug into this a bit after upgrading the demo application to 2.1 and I think we have an ordering issue. Our `DefaultErrorWebExceptionHandler` is currently [ordered -1](https://github.com/spring-projects/spring-boot/blob/37c60b6603536b96cfe40c89f3bcb6f6e636a8c9/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/error/ErrorWebFluxAutoConfiguration.java#L83) which means it ends up running before `WebFluxResponseStatusExceptionHandler`. This means the [status detection logic](https://github.com/spring-projects/spring-boot/blob/37c60b6603536b96cfe40c89f3bcb6f6e636a8c9/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/error/DefaultErrorWebExceptionHandler.java#L173) never finds the correct code.

@bclozel What's the impact if we change the order at this stage?

**Comment by mmanciop** [comment]
Created a PR just in case it turns out it is better to just implement the support for `@ResponseStatus` in `DefaultErrorWebExceptionHandler` side-by-side with the support for `ResponseStatusException`.

**Comment by bclozel** [comment]
@philwebb The ordering issue is actually intentional. 
Our own `org.springframework.web.server.WebExceptionHandler` implementation, `DefaultErrorWebExceptionHandler` is ordered before the WebFlux one, because it has to handle all errors and render views/payloads for them and not delegate to the following ones.

This means we have to keep in sync and replicate what happens in Spring WebFlux - in this case, I missed [SPR-16567](https://jira.spring.io/browse/SPR-16567) and we have to backport that into our own implementation.

I'm closing this issue in favor of #14744

Thanks @mmanciop !
