### ISSUE TITLE
Configure Cassandra JMX Reporting

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#14778]
The upgrade to Dropwizard 4 means that we need to customize Cassandra to disable JMX reporting. We should also offer the user a way to re-enable it, if they wish.

**Comment by philwebb** [comment]
Reopening to rename property to `jmx-enabled` to align with existing properties.

**Comment by snicoll** [comment]
Note: the new property should be added to the appendix as well

**Comment by thrashermaq** [comment]
Hello

I Just updated my project to version 2.1.0.RELEASE.
But i still get the following error:
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.cassandra.ReactiveSession]: Factory method 'reactiveSession' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'session' defined in class path resource [CassandraConfig.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter

Am I missing something? M4 worked properly with autoconfiguration.

**Comment by wilkinsona** [comment]
@thrashermaq I'm guessing [this](https://stackoverflow.com/questions/53101753/spring-boot-data-cassandra-reactive-jmxreporter-problem) is your question on Stack Overflow? If so, let's keep the discussion there please.

**Comment by hookumsnivy** [comment]
I think this is bigger than just disabling jmx. The spring boot bom for 2.1.0 lists incompatible dependencies:
com.datastax.cassandra:cassandra-driver-core:3.6.0
io.dropwizard.metrics:metrics-jmx:4.0.3

The problem is that cassandra-driver-core 3.6.0 depends on dropwizard version 3.2.2. Version 4.0.3 includes a breaking change which causes class not found errors.

**Comment by wilkinsona** [comment]
@hookumsnivy As far as we know, Cassandra's driver only uses Dropwizard for JMX-based reporting. With reporting disabled, we are not aware of any incompatibilities with Boot's default version of Dropwizard Metrics. If you have evidence to the contrary, please open a new issue with an sample project that reproduces the problem.

**Comment by ramchris** [comment]
So there is no way for us to enable jmx-reporting in spring boot2 for Datastax Cassandra?
