### ISSUE TITLE
springboot-dubbo

### ISSUE THREAD

**Issue by yexua** [spring-projects/spring-boot#14853]
Through the 'properties' injection should be the name of' dubbo. Scan. BasePackages' (actual 'dubbo. Scan. Base - packages'), lead to can't scan to' basePackages', thus not exposed to the service.Amend the 'base - packages' to' basePackages found success after exposed service
![q 51u02xe 0osvdc7d6](https://user-images.githubusercontent.com/44164267/47016469-5661be00-d182-11e8-97a5-bc270c528922.png)

**Comment by wilkinsona** [comment]
Dubbo integration is an [external project](https://github.com/apache/incubator-dubbo-spring-boot-project). It looks like they're retrieving configuration from the environment directly and they are using `basePackage` rather than `base-package` which is the required canonical form for this sort of lookup. Alternatively, they could change their implementation to use `@ConfigurationProperties`.
