### ISSUE TITLE
Servlet endpoints on Jersey do not take application path property into account

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#14895]
Reproduced by setting `spring.jersey.application-path=/admin`. The Jolokia endpoint was still available under `/actuator/jolokia` while all other actuators were under `/admin/actuator`.

**Comment by isank** [comment]
Hi @mbhave,
I'm interested in working on this issue and also did some analysis

I think the problem lies in class `org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration` at
```
@Configuration
    @ConditionalOnClass({ResourceConfig.class})
    @ConditionalOnMissingClass({"org.springframework.web.servlet.DispatcherServlet"})
    public static class JerseyServletEndpointManagementContextConfiguration {
        public JerseyServletEndpointManagementContextConfiguration() {
        }

        @Bean
        public ServletEndpointRegistrar servletEndpointRegistrar(WebEndpointProperties properties, ServletEndpointsSupplier servletEndpointsSupplier) {
            return new ServletEndpointRegistrar(properties.getBasePath(), servletEndpointsSupplier.getEndpoints());
        }
    }
```
`properties.getBasePath()` results into `/actuator` which actually comes from `private String basePath = "/actuator";` in `org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointProperties`

And thus, in `org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar`

```
private void register(ServletContext servletContext, ExposableServletEndpoint endpoint) {
        String name = endpoint.getEndpointId().toLowerCaseString() + "-actuator-endpoint";
        String path = this.basePath + "/" + endpoint.getRootPath();
        String urlMapping = path.endsWith("/") ? path + "*" : path + "/*";
        EndpointServlet endpointServlet = endpoint.getEndpointServlet();
        Dynamic registration = servletContext.addServlet(name, endpointServlet.getServlet());
        registration.addMapping(new String[]{urlMapping});
        registration.setInitParameters(endpointServlet.getInitParameters());
        logger.info("Registered '" + path + "' to " + name);
    }
```
gives us `/actuator/jolokia` instead of `/admin/actuator/jolokia` (considering the example you provided)

This is the first time I'm trying to contribute to a Spring project and request your help to check if I'm in the right direction. 😊

**Comment by mbhave** [comment]
@isank Thanks for offering to help and the detailed analysis. I've already started looking at this one though. Your analysis is correct. We need a way to get the application path when creating the `ServletEndpointRegistrar ` for Jersey. I'm not sure what the fix will look like yet because this can be set via the property `spring.jersey.application-path` as well as the `@ApplicationPath` annotation.

If you're looking to contribute, most open issues are open to contribution unless they're already assigned to someone. You can also take a look at issues tagged with [`ideal-for-contribution`](https://github.com/spring-projects/spring-boot/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+ideal-for-contribution%22). If you find something you'd like to work on, please comment on the issue and we'll be happy to answer any questions you have.
