### ISSUE TITLE
Does the i18n configuration not support this format?

### ISSUE THREAD

**Issue by ruibaby** [spring-projects/spring-boot#14905]
For example:
```yaml
  messages:
    basename: i18n/messages,templates/themes/*/i18n/messages
```
I need to load multiple i18n files,but the files below `templates/themes` are not loaded,Doesn't support Ant expressions?
So,How can I solve it?
Thanks!

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

With that said, and before you ask on Stack Overflow, I believe that the documentation answers your question about whether or not Ant expressions are supported.

The `spring.messages.basename` property is described as follows:

```
Comma-separated list of basenames (essentially a fully-qualified classpath location), each following the ResourceBundle convention with relaxed support for slash based locations. If it doesn't contain a package qualifier (such as "org.mypackage"), it will be resolved from the classpath root.
```

Java's [ResourceBundle](https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html) does not support Ant expressions. To support Ant expressions you could perhaps write a custom `ResourceBundleMessageSource` sub-class that overrides `doGetBundle`.
