### ISSUE TITLE
Adding build.gradle to springboot samples

### ISSUE THREAD

**Issue by d1231** [spring-projects/spring-boot#14923]
Hi,

All the [spring-boot-samples](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples) includes maven example (pom.xml) but not a gradle one (build.gradle). Working with gradle, it would been helpful to me if each sample had such example.

I would have no problem working on it and doing that for each of the sample.

**Comment by philwebb** [comment]
The samples in our repository are primarily to help us test applications. We used to have a few that included `build.gradle` files but because they weren't used as part of the build we decided to remove them. If you're looking for actual sample that include Gradle files you can look at https://spring.io/guides. You can also generate projects than include Gradle builds from start.spring.io.

**Comment by d1231** [comment]
Thanks for the detailed answer.
I think a new guide using junit5 would be helpful as my experience trying to use it in a new project included a lot of googling and piecing together dependencies from a lot of different guides.

**Comment by philwebb** [comment]
@d1231 That's a good idea. The guides have an issue tracker [here](https://github.com/spring-guides/getting-started-guides/issues) if you'd like to raise an issue. We're also planning to look at JUnit5 in more detail for Spring Boot 2.2.
