### ISSUE TITLE
Multiple properties file

### ISSUE THREAD

**Issue by mlabarre** [spring-projects/spring-boot#14942]
Hi
I use Spring boot 2.0.4.RELEASE version in a stand Maven project.
Running environment is Tomcat 9
I created an WAR application containing (in others) 2 customs jars :
- jar1 which contains application core (@SpringBootApplication). At root level in classes, it contains a file named application.yml (build from java/main/resources... classic !)
- jar2, a service jar, which contains some utilities. As jar1 it contains an application properties file named filter.yml
At Tomcat boot, fields referenced in a @Configuration class (in jar2) does not found corresponding values in filter.yml ("Could not resolve placeholder...."). Fields in application.yml (jar1) are set.
I tried "@PropertySource", "-Dspring.config.additional-location=classpath:/filter.yml" in setenv script.
No effect.
Since yesterday I read the documents on the subject but I have not find the solution.
Can you help me?
Thank you very much

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
