### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.transaction.support.ResourceTransactionDefinition

### ISSUE THREAD

**Issue by zhou27** [spring-projects/spring-boot#14941]
has a error when I use updete with \@Transactional  but use HibernateTemplate.get normal.
i can't find class "ResourceTransactionDefinition" at package org.springframework.transaction.support.

![image](https://user-images.githubusercontent.com/24773754/47400391-8525f880-d76f-11e8-94d4-91d916793024.png)

![image](https://user-images.githubusercontent.com/24773754/47400365-74758280-d76f-11e8-88e2-10f694eb2afe.png)

![image](https://user-images.githubusercontent.com/24773754/47400292-2c566000-d76f-11e8-8a5e-d50eb59cde69.png)

CONFIG：
![image](https://user-images.githubusercontent.com/24773754/47400406-97a03200-d76f-11e8-8a09-da0fd98bf80d.png)
![image](https://user-images.githubusercontent.com/24773754/47400421-a8e93e80-d76f-11e8-9e48-50e9b1043251.png)
![image](https://user-images.githubusercontent.com/24773754/47400429-b1417980-d76f-11e8-9198-e4e06a3ba03a.png)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
