### ISSUE TITLE
Allow early ServletRequest Autowiring with embedded containers

### ISSUE THREAD

**Issue by pfoermer** [spring-projects/spring-boot#14990]
Spring Boot Version: 1.5.13.RELEASE

*Setup*
ApplicationContext with a Bean declared with an autowire dependency to `HttpServletRequest` (the used ApplicationContext is a little bit more complex).

*Problem*
For a non embedded environment (Tomcat deployment) the application context boots successfully. For an embedded environment, the application context fails to start with the exception:
> ....NoSuchBeanDefinitionException: No qualifying bean of type 'javax.servlet.http.HttpServletRequest' available: expected at least 1 bean which qualifies as autowire candidate.

*Reason*
The `HttpServletRequest` substitution is performed by an `ObjectFactory` registered by `org.springframework.web.context.support.WebApplicationContextUtils.registerWebApplicationScopes(...)`. The `registerWebApplicationScopes(...)` call is performed by `EmbeddedWebApplicationContext.selfInitialize(...)`. For an embedded environment the method `EmbeddedWebApplicationContext.createEmbeddedServletContainer()` is invoked previous to the initializer which causes Eager Bean creation of the ApplicationContext.

*Expected*
`HttpServletRequest` is resolved, no matter if it is an embedded or non embedded environment.

**Comment by pfoermer** [comment]
Hi @philwebb, 

I can not provide you the real business application, as it is closed source, but here is a sample Maven application which should show the problem:
[issue-14990.zip](https://github.com/spring-projects/spring-boot/files/2526248/issue-14990.zip)

Please start "sample.App".

Like noted in "sample.Config" in my opinion FactoryBean, Advisor or similar things seem to force eager bean creation, as spring is otherwise unable to determine target bean type for query operations of `org.springframework.beans.factory.support.DefaultListableBeanFactory`. See also workarounds for this eager bean creation issue in `org.springframework.boot.autoconfigure.condition.BeanTypeRegistry` used for Condition evaluation.

**Comment by philwebb** [comment]
Thanks @pfoermer

**Comment by philwebb** [comment]
> For a non embedded environment (Tomcat deployment) the application context boots successfully. For an embedded environment, the application context fails to start with the exception

I quite surprised that the application context boots when running under Tomcat. I've not really had a chance to dig into why that might be. I think the real issue here is that the `HttpServletRequest` can only be obtained when a request is in progress.

Although `WebApplicationContextUtils.registerWebApplicationScopes` does call `beanFactory.registerResolvableDependency(ServletRequest.class, new RequestObjectFactory());`, resolving a `ServletRequest` only really makes sense in a `@Scope("request")` bean. In your case, your `Interceptor` is a singleton bean and Spring will try to initialize early (before any request is happening).

I would suggest refactoring your code to use an `javax.inject.Provider<HttpServletRequest>` which you then call to get the request when needed (assuming you are only intercepting methods that are invoked when a request is active).

Alternatively you could call `RequestContextHolder` directly.

**Comment by pfoermer** [comment]
Hi @philwebb,

thank you for suggestions.

I would like to please you to take also a look at https://docs.spring.io/spring/docs/4.3.20.RELEASE/spring-framework-reference/htmlsingle/#beans-factory-scopes-other-injection and `org.springframework.beans.factory.support.AutowireUtils.resolveAutowiringValue(...)`.

For `HttpServletRequest` Spring Core creates out of the box a Proxy Handler, like for `EntityManager` injection.

Here is also a remote debug screenshot where you can see, that Spring created a proxy object for the `HttpServletRequest`.
![debug-http-servlet-request-proxy](https://user-images.githubusercontent.com/2022146/47705891-1beb2d00-dc28-11e8-8b5f-9e3d455b2b57.jpg)

**Comment by philwebb** [comment]
Thanks @pfoermer, I totally missed that Spring Framework did that.
