### ISSUE TITLE
How to make springboot configuration module independent of springboot version?

### ISSUE THREAD

**Issue by liudaomanbu** [spring-projects/spring-boot#15069]
I wanto to develop a my springboot configuration module. 

For example,i want to the behaviors of serialization and deserializion consistent in the Spring ConverterSPI and JsonHttpMessageConverter/XmlHttpMessageConverter. 

So,i try to register all converters in Spring ConverterSPI to global configuration JsonHttpMessageConverter/XmlHttpMessageConverter provides. And decide whether to open by configuration.

For this springboot configuration module,i don't want to rely on springboot version. 
Otherwise,the actual springboot project need to exclusion the transitive dependenced spring boot when introduce this module.

How to achieve this goal?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
