### ISSUE TITLE
Incompatible versions of solr and dropwizard metrics in spring boot 2.1.0

### ISSUE THREAD

**Issue by jboix** [spring-projects/spring-boot#15110]
I've recently upgraded one of my projects to spring boot `2.1.0` and I'm facing the following error whenever I try to initialize an embedded solr server:
````
java.lang.NoClassDefFoundError: com/codahale/metrics/Clock$CpuTimeClock

	at org.apache.solr.metrics.SolrMetricManager.<init>(SolrMetricManager.java:118)
	at org.apache.solr.core.CoreContainer.load(CoreContainer.java:530)
        ...
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.Clock$CpuTimeClock
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
````
The root of this problem seems to be this dependency:
````xml
<dependency>
   <groupId>io.dropwizard.metrics</groupId>
   <artifactId>metrics-core</artifactId>
   <version>${dropwizard-metrics.version}</version>
</dependency>
````
Its version is explicitly set to `4.0.3` by spring boot, but solr depends on the `3.2.6` version of this same library.

I didn't have this problem with the previous version (`2.0.3`).

Thanks.

**Comment by wilkinsona** [comment]
Thanks for the report, but this is out of the scope of Spring Boot's Solr support.

We provide auto-configuration for Solr's client and this works with the default dependency versions. We don't do anything with Solr's server and generally recommend not trying to embed the server in your application due to the large number of dependencies that it pulls in with it.

If you don't want to use Dropwizard Metrics elsewhere in your application, you may be able to continue to embed Solr by overriding the version of Dropwizard Metrics to 3.2.6 using the `dropwizard-metrics.version` property. Alternatively, it may be possible to configure Solr's server to disable its Dropwizard integration until they have a change to bring their dependencies up-to-date.
