### ISSUE TITLE
How to get all converters and formatters information that register in spring?

### ISSUE THREAD

**Issue by liudaomanbu** [spring-projects/spring-boot#15111]
Sorry,I know that this problem is more suitable for stackoverflow.
But,my question in stackoverflow didn't get the expect answer.
https://stackoverflow.com/questions/53117769/how-to-get-all-converters-and-formatters-that-register-in-spring

I want to the behaviors of serialization and deserializion consistent in the Spring ConverterSPI/Formatter and JsonHttpMessageConverter/XmlHttpMessageConverter.

So,i try to register all converters in Spring ConverterSPI to global configuration JsonHttpMessageConverter/XmlHttpMessageConverter provides.

How to get all converters and formatters information that register in spring?
The most serious problem is that some formatters based on FieldAnnotation. I need get Relevant information for this part of formatters.
And i need to get converters and formatters from target type is String or Number class.

Is this possible?

**Comment by wilkinsona** [comment]
Please don't cross-post questions from Stack Overflow here, particularly when you're already aware that it contravenes our guidelines for contributing.

It looks like two people have already answered your question. If those answers haven't helped, may I suggest that you time would be spent commenting on the answers explaining why and improving the question so that people have whatever information they need to be able to provide whatever answer you're looking for.
