### ISSUE TITLE
SecurityContextHolder.getContext().getAuthentication() always return 'anonymousUser'

### ISSUE THREAD

**Issue by bhagyaperera123** [spring-projects/spring-boot#15129]
hello,
I have rest Controller in my project. the rest controller class look like below.
with ' SecurityContextHolder.getContext().getAuthentication() ' always return 'anonymousUser'

`@RestController
@RequestMapping("/history")
public class HistoryEndpoint {

    private final HistoryFacadeSerive historyFacadeSerive;

    public HistoryEndpoint(@NotNull HistoryFacadeSerive historyFacadeSerive) {
        this.historyFacadeSerive = historyFacadeSerive;
    }

    @RequestMapping(value = "/username", method = RequestMethod.GET)
    @ResponseBody
    public String currentUserName() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        return auth.getName();
    }
}`

but below code return correct user name.

`@RestController
@RequestMapping("/history")
public class HistoryEndpoint {

    private final HistoryFacadeSerive historyFacadeSerive;

    public HistoryEndpoint(@NotNull HistoryFacadeSerive historyFacadeSerive) {
        this.historyFacadeSerive = historyFacadeSerive;
    }

    @RequestMapping(value = "/username", method = RequestMethod.GET)
    @ResponseBody
    public String currentUserName(Principal principal) {
        return principal.getName();
    }
}`

i want to use 'SecurityContextHolder.getContext().getAuthentication();' in audit configuration class. how can i fix this issue? ( I used SecurityContextHolder in my rest controller for testing)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by bhagyaperera123** [comment]
I understand. thanks! :+1:
