### ISSUE TITLE
JPA Data saving very slow after upgrade to 2.1.0.RELEASE

### ISSUE THREAD

**Issue by bhagyaperera123** [spring-projects/spring-boot#15120]
Yesterday i upgraded Java version and spring boot version.
- OpenJdk 11 
- Spring boot 2.1.0.RELEASE

I have saving function in my project. previously this method are worked well. but right now saving function are really slow. saving duration like 10 seconds.

**Comment by wilkinsona** [comment]
Thanks for the report. Given that you've changed more than one thing, can you please explain why you believe this to be an issue in Spring Boot itself? It could also be due to a change in Java 11, Spring Data JPA, the JDBC driver to name just a few.

**Comment by wilkinsona** [comment]
It’s impossible for us to say for certain with no information about the queries involved or the database that you are using. However, I think it’s unlikely that it is Spring Boot itself causing the problem as it’s not really involved beyond the initial configuration of the various components.

I think it would be worth taking a step back and profiling your application, looking at your database’s performance, looking at what Hibernate is doing by enabling it’s SQL logging, etc. That should hopefully allow you to identify the cause and, if it turns out that it is Spring Boot itself, we can re-open this issue.

**Comment by bhagyaperera123** [comment]
i understand! thank you so much for your consideration!
