### ISSUE TITLE
Cookie http-only setting has no effect when using Spring Session

### ISSUE THREAD

**Issue by hellowenqi** [spring-projects/spring-boot#15139]
Hi, Cookie http-only setting has no effect when using spring boot 2.1.0.RELEASE.
I also tried the method of @wilkinsona in https://github.com/spring-projects/spring-boot/issues/12580!

_Originally posted by @hellowenqi in https://github.com/spring-projects/spring-boot/issues/12580#issuecomment-437268881_

**Comment by hellowenqi** [comment]
Hi, @wilkinsona 
this is my git repo: https://github.com/hellowenqi/HttpOnly.git

**Comment by wilkinsona** [comment]
Thanks for the sample. The key piece that you hadn't described in your original description is that you are using Spring Session. When you're using Spring Session, it's responsible for creating session cookies, not the underlying servlet container. This means that the problem fixed in #15139 isn't relevant.

I believe the behaviour you're seeing is due to Spring Session ignoring `SessionCookieConfig.isHttpOnly()` when [it is configuring its cookie serializer](https://github.com/spring-projects/spring-session/blob/3bfdb9be9323e377086ee2df86d987338466bf7c/spring-session-core/src/main/java/org/springframework/session/config/annotation/web/http/SpringHttpSessionConfiguration.java#L166-L191) so I am going to transfer this issue to spring-projects/spring-session.

**Comment by wilkinsona** [comment]
I was going to transfer this issue to spring-projects/spring-session but I am unable to do so (I don't quite understand when issues can and cannot be transferred). @hellowenqi Please open [Spring Session issue](https://github.com/spring-projects/spring-session/issues), referencing this one.

**Comment by hellowenqi** [comment]
But if you do not use Spring Session, what do you use for session?

**Comment by wilkinsona** [comment]
All Servlet containers have built-in session support. If you have further questions, please follow up on Stack Overflow or Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by wilkinsona** [comment]
Spring Session’s`SessionCookieConfig`-based approach is limited and can’t be improved to fix this. We’ll need to switch to auto-configuring the cookie serializer. There are some potential gotchas to be aware of. See https://github.com/spring-projects/spring-boot/pull/10440 for some details.

**Comment by wilkinsona** [comment]
Tentatively scheduling for 2.0.x. Depending on the nature of the fix, it may have to move to a later milestone.

**Comment by vpavic** [comment]
Thanks for re-opening this @wilkinsona - I was about to open a new issue to describe the limitations of Spring Session's capabilities to configure off `SessionCookieConfig` and propose we do auto-configuration of `DefaultCookieSerializer`. See the discussion on spring-projects/spring-session#1253

I should be able to provide the PR for this soon.

**Comment by philwebb** [comment]
Closing in favor of PR #15163
