### ISSUE TITLE
constructor executed twice

### ISSUE THREAD

**Issue by zhangtianxiao** [spring-projects/spring-boot#15148]
```
@Component
@ConfigurationProperties(prefix = "datasource")
open class DataSourceInitialize : ArrayList<JSONObject>() {

    val logger = LogFactory.get(DataSourceInitialize::class.java)

    //it is  Kotlin's constructor 
    init {
        println("springboot init DataSourceInitialize") // Miraculous, it   executed twice
    }

    @PostConstruct
    open fun init() {
        println(this) //it executed once
    }
}

```
I want to know why the two constructor is executed. thanks

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
