### ISSUE TITLE
spring boot + mongodb

### ISSUE THREAD

**Issue by SummerXia93** [spring-projects/spring-boot#15154]
-- I am using the springboot 1.5.10 and mongodb 2.0.4 to do my develop;

-- I already build 2 relevant mongo collections.
   e.g. student and teacher collections, while student id list is an attribute of teacher.

-- I want to make this happen: if a student is expired by time and got deleted from its collection,  it will be erased from the list in the relevant teacher too. Like in mysql it will be easy to do.

-- Now I already add the @DBRef annotation on the list attribute of teacher, but when a student got expired and deleted, the element of the list will become null instead of got erased.

Does anyone know how to make the element deleted instead of becoming null?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by wilkinsona** [comment]
Also, please do not open the same issue in [multiple places](https://github.com/ityouknow/spring-boot-examples/issues/73), particularly without making it clear that you have done so. It risks wasting people’s time as they spend time trying to help you without realising that your question has already been answered.

**Comment by SummerXia93** [comment]
Got it! Thank you for the tips.


发自网易邮箱大师
On 11/12/2018 15:02, Andy Wilkinson wrote:

Also, please do not open the same issue in multiple places, particularly without making it clear that you have done so. It risks wasting people’s time as they spend time trying to help you without realising that your question has already been answered.
