### ISSUE TITLE
java configuration CRUD application

### ISSUE THREAD

**Issue by hasindumm** [spring-projects/spring-boot#15196]
- Hi, team i'am very beginner to spring development

- I have  developed CRUD application.for this crud application i used XML configuration.here is my configuration XML code(spring-mvc-crud-demo-servlet.xml)
![spring1](https://user-images.githubusercontent.com/36806761/48623470-be98ff00-e9cf-11e8-9793-5f44667d294f.PNG)
![spring 2](https://user-images.githubusercontent.com/36806761/48623483-c658a380-e9cf-11e8-9d46-a2f3130e8454.PNG)

- And here is my web.xml file
![5](https://user-images.githubusercontent.com/36806761/48624312-12a4e300-e9d2-11e8-89a8-c604d7739f38.PNG)

- Then i have developed a login using spring mvc. but separately and i used java configuration for that not xml configuration.here is java configuration files

1. DemoAppConfig.java
![1](https://user-images.githubusercontent.com/36806761/48623883-09674680-e9d1-11e8-94df-7621a62be093.PNG)

2.DemoSecurityConfig.java
![2](https://user-images.githubusercontent.com/36806761/48624008-6400a280-e9d1-11e8-9800-0de564d8a8a8.PNG)

3.MySpringMvcDispatcherServletInitializer.java
![3](https://user-images.githubusercontent.com/36806761/48624092-901c2380-e9d1-11e8-9834-5a81b4655f23.PNG)

4.SecurityWebApplicationInitilizer.java
![4](https://user-images.githubusercontent.com/36806761/48624114-9d391280-e9d1-11e8-8da0-3f3b54aeb24c.PNG)

those are the all java configuration files that i have for  login.

- Now i want to merge the login to previous CRUD application.But i have  faced problem with configurations.

- I need to know java configuration for previous crud app according to previous mentioned           
 spring-mvc-crud-demo-servlet.xml and web.xml files. and where i should put that java configuration in my login configurations.i'm little bit confused ..plz help me..

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by hasindumm** [comment]
Thank you..so much..
