### ISSUE TITLE
spring-boot-sample-tomcat-jsp project, The Tomcat connector configured to listen on port 8080 failed to start.

### ISSUE THREAD

**Issue by akira32chen** [spring-projects/spring-boot#15194]
I use Intellij to open spring-boot-sample-tomcat-jsp and run the project.
But it appears the error message as below:

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-11-16 21:02:04.567 ERROR 12420 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.
```

I already execute the command to kill the processes, but it seems to do not work. The tomcat port 8080 problems still happen when the project run.

taskkill /f /t /im java.exe

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
