### ISSUE TITLE
Thymeleaf dont wanna show fonts and images from satic/resource

### ISSUE THREAD

**Issue by matijagrdjan** [spring-projects/spring-boot#15288]
Spring boot starts normal and I don't have any error or warning, but when i go to the localhot:8080/ template don't wanna show custom fonts and images. I have menu and table.
this is link to my project 
https://github.com/matijagrdjan/sfg-pet-clinic

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

It looks like this is a simple typo in your project: `resorces` should be `resources`.
