### ISSUE TITLE
Is there any finalize method inside Spring or Jersey?

### ISSUE THREAD

**Issue by River555** [spring-projects/spring-boot#15285]
I implemented a standard web application (processing http transaction with clients)  using Spring Framework(spring boot 2.0.0), Jersey 2.26.
On running the application,when 1st fullGC occurred, many (I think ) releasable objects were not released, and they were released at 2nd fullGC.

I wonder this behavior is related to Java specification about invoking the finalize method.
I never use finalize methods in my application coding.
Would someone konw is there any finalize method inside Spring or Jersey which may cause this?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by River555** [comment]
I'm sorry, this question is not suited here.
