### ISSUE TITLE
2.1.0 RELEASE error, 2.0.5 RELEASE OK.

### ISSUE THREAD

**Issue by tommyonsn** [spring-projects/spring-boot#15290]
> The bean 'myService', defined in class path resource [com/pathweaver/libservice/ServiceConfiguration.class], could not be registered. A bean with that name has already been defined in file [D:\workspace\pathant\libary\target\classes\com\pathweaver\libservice\MyService.class] and overriding is disabled.
Action:
Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

I try 2 modules, call MyService of [Libservice module] at other same level module. 
When use 2.1.0, report error as above.
it's ok when use 2.0.5.

**Comment by wilkinsona** [comment]
As [noted in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding), this is the expected behaviour in Spring Boot 2.1. It looks like `MyService` is being found by component scanning and defining a bean named `myService` while `ServiceConfiguration` has a `@Bean` method that also defines a bean named `myService`. I suspect that's a bug in your application's configuration. If the override is intentional then you should set the property as recommended in the error message.

**Comment by quentinburley** [comment]
This discussion seems related: https://stackoverflow.com/questions/53103991/cant-stat-app-after-updating-springboot-from-2-0-6-release-to-2-1-0-release

and it proposes a workaround:
>>>
add this line to the applicaton.properties file

spring.main.allow-bean-definition-overriding=true
<<<
