### ISSUE TITLE
Bean overriding in spring boot 2.1

### ISSUE THREAD

**Issue by ebussieres** [spring-projects/spring-boot#15326]
I have an issue with bean overriding with spring boot 2.1.0

I have a main application class that we use in src/main/java defined to be package as a war file. The application is currently packaged as a war and deployed on tomcat. I'm also defining a TestBean in that class.

```
@SpringBootApplication
public class Application extends SpringBootServletInitializer {

	@Bean
	public TestBean testBean() {
		return new TestBean();
	}

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(Application.class);
	}

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
```

We also have a main application test class that extends the application class in order to be able to start the application with an embedded tomcat when developping. We also have a bootstrap file in src/test because we're using spring cloud config and we don't want to package it. It's on the classpath of the tomcat in production.

```
public class EmbeddedApplication extends Application {
  public static void main(String[] args) {
    SpringApplication.run(EmbeddedApplication.class, args);
  }
}
```

I have an issue when starting the EmbeddedApplication class telling me that the bean testBean has already been defined. If I declare the TestBean in a Configuration file, everything is working fine.

I don't understand why the testBean seems to be declared twice with that setup. Seems to be a bug to me

A code sample can be found here
https://github.com/ebussieres/issue-spring-boot

Thanks you

**Comment by wilkinsona** [comment]
Thanks for the sample. When you launch `EmbeddedApplication`, you end up with `testBean` declared twice because the definition is found in `EmbeddedApplication` and in `Application`. It's found in `Application` due to component scanning finding the `Application` class that is meta-annotated with `@Component` (`@SpringBootApplication` -> `@SpringBootConfiguration` -> `@Configuration` -> `@Component`).

I can't see any need for the `EmbeddedApplication` class as `Application` already has a main method that will allow it to be run using embedded Tomcat during development. If you need a separate class for a reason that I have missed, you could change it so that it does not extend `Application`.
