### ISSUE TITLE
Kotlin model attribute binding error on comma-delimited value

### ISSUE THREAD

**Issue by thorntonrp** [spring-projects/spring-boot#15323]
[kotlin-binding-error.zip](https://github.com/spring-projects/spring-boot/files/2626854/kotlin-binding-error.zip)

The attached sample application demonstrates a kotlin binding error when the kotlin class is being used from a Spring MVC controller handler method to receive a comma-delimited list from the request. The workaround is to not use Kotlin data classes or multi-argument constructors.

**Comment by philwebb** [comment]
The root cause of the exception is the `ModelAttributeMethodProcessor` class finding the `List` constructor rather than the empty constructor. It looks like `BeanUtils.findPrimaryConstructor` is ultimately delegating to `KClasses.getPrimaryConstructor`. I'm not sure if this is intentional or not, but since both those classes are in Spring Framework I'm afraid you'll need to raise an issue on [their JIRA](jira.spring.io) rather than here.
