### ISSUE TITLE
Consider setting hibernate.dialect.storage_engine=innodb JPA property on MySQL

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/spring-boot#15342]
If we detect MySQL to be in use or it is configured by the user, our JPA setup will use Spring Frameworks default dialect to be configured for Hibernate, which is the `MySQL5Dialect`. This – in contrast to the `MySQL55…` and `MySQL57…` flavors – unfortunately still uses the MyISAM storage engine, which doesn't take part in transactions.

I.e. a standard Boot setup working with MySQL and not configuring a Hibernate database dialect will have transactions broken.

It's pretty complex situation with different stakeholders at play:

1. I wonder why the default storage engine has changed or more specifically, why the `MySQL5Dialect` wasn't changed to default to InnoDB, too. I am assuming backwards compatibility reasons but maybe @vladmihalcea can comment on that. Even more so, the `MariaDB5Dialect` does indeed use InnoDB as default storage engine which subtly breaks the symmetry between the two products.
2. Spring's dialect selection can't really make a better decision right now, as it doesn't know anything about the database version in play. Switching to a more recent dialect flavor would probably break users of previous versions (something 5.0 <= x < 5.5). @jhoeller's opinion would be of interest here.

While I think Boot is not necessarily the best place to solve this issue, I think there's a few things we could do to prevent users from being struck by this:

1. Leave a note on that in the relevant sections of the reference docs.
2. There's a `hibernate.dialect.storage_engine` property, that can be set to `innodb` to enable the storage engine that Boot could configure *unless* the user has configured a custom dialect in the first place.

**Comment by vladmihalcea** [comment]
This setting affect only the schema generation via hbm2ddl, and it's s System property, not a Hibernate configuration property.

It was added to the Dialect version from which MySQL switched the default storage engine to InnoDB.

In reality, I guess this was the preferred storage engine anyway.

**Comment by jhoeller** [comment]
As mentioned on [spring-projects/spring-framework/issues/22326](https://github.com/spring-projects/spring-framework/issues/22326), our `Database` enum mechanism seems rather inappropriate for modern-day purposes, at least with Hibernate.

Hibernate is pretty good at detecting not only the database but also the specific version itself on startup, so I wonder whether selecting a specific dialect upfront is really helpful these days. The main problem is that we can't indicate "MySQL with version detection at runtime" since that is baked into Hibernate's general database detection mechanism, not meant to be triggered for a pre-selected database. From that perspective, we might be better off not setting any dialect upfront in Hibernate's case.

Note that EclipseLink handles this differently, quite aligned with our enum approach: Its `MySQLPlatform` does version detection within the platform that we set from our `Database` enum. In other words, we are not in the business of selecting a specific dialect for a specific MySQL version there, we are rather just saying "MySQL" and leaving the rest up to EclipseLink itself. It'd be ideal if we could do something along those lines for Hibernate as well instead of our current hard-coding of a default dialect version.

**Comment by vladmihalcea** [comment]
@jhoeller Setting the Dialect is not required for Hibernate since it can autodetect it. The `org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl#determineDialect` takes care of that.

**Comment by jhoeller** [comment]
@vladmihalcea same feeling here. It's just a mismatch with our `JpaVendorAdapter` abstraction which suggests that a database vendor can/should be selected upfront, and a mismatch with the way EclipseLink needs to be set up. For a direct match, we'd need a Hibernate `DialectResolver` implementation that is being configured with a specific value from Hibernate's own `Database` enum and calls `database.resolveDialect` on it, hard-coding the vendor but runtime-detecting the version.

Practically speaking, we could make the `Database` enum a no-op in `HibernateJpaVendorAdapter` itself but that'd be a bit odd if the user (or Boot) explicitly selected a database, wouldn't it. Otherwise, Boot could also selectively not set the `Database` enum on its end if it knows that Hibernate is being set up.

**Comment by vladmihalcea** [comment]
@jhoeller I also added the `org.hibernate.dialect.Database` Enum some time ago. You could probably map that to the Spring `org.springframework.orm.jpa.vendor.Database`, right?

**Comment by jhoeller** [comment]
That enum matches quite nicely indeed but there's no `DialectResolver` implementation that picks up a pre-configured `Database` enum name. There's just `StandardDialectResolver` which iterates over all enum values, evaluating the database vendor and the version at the same time. It'd be nice if there was a resolver implementation that picks up a pre-configured database name from a configuration property such as "hibernate.dialect.database", along the lines of "hibernate.dialect" but accepting `Database` enum names such as "MYSQL" instead of a specific dialect implementation class.

**Comment by vladmihalcea** [comment]
Actually, we could add a Jira issue for this. Would you like to create one while providing the reason for it and assign it to me?

**Comment by jhoeller** [comment]
Here we go: https://hibernate.atlassian.net/browse/HHH-13253

**Comment by vladmihalcea** [comment]
Thanks. I'll take care of it.

**Comment by snicoll** [comment]
@odrotbohm Spring Boot 2.2 does not set the dialect by default anymore (see #16172) so I have a feeling that this report is no longer accurate with that version. Do you agree? Anything that would still be needed?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
