### ISSUE TITLE
Document that RestTemplateBuilder's rootUri only applies when String variants are used for specifying the request URL

### ISSUE THREAD

**Issue by ryonday** [spring-projects/spring-boot#15343]
The `RestTemplateBuilder` documentation for the `rootUri()` method states:

> Set a root URL that should be applied to each request that starts with  '/'.

However, the following code does not result in `RestTemplate` expanding the URI:

```
 UriTemplate template = new UriTemplate("/foo?bar={bar}");


this.restTemplate = restTemplateBuilder
            .rootUri(URI.create("http://foo.bar"))
            .build();
.
.
.
URI uri = template.expand("baz");

 RequestEntity<Void> req = RequestEntity.get(uri)
                .accept(MediaType.APPLICATION_JSON)
                .header(accountLinkHeader, accountLinksHeader)
                .build();

String response = restTemplate.exchange(req, String.class);
```

Moreover, the exception received is EXTREMELY ambiguous when this doesn't work. In fact, the Spring exception thrown occludes the initial Apache exception (which states there's no host).

**Comment by ryonday** [comment]
Will open this against the framework.

**Comment by bclozel** [comment]
Hello @ryonday 

The `RestTemplateBuilder` javadoc does point to `RootUriTemplateHandler` - all `UriTemplateHandler` are about expanding a `String` uri template + variables into a proper URI.

Because you're using a `RequestEntity` here, you're taking full control of the request and you're not expanding a URI template. There might be room for improvement in the `RestTemplateBuilder` / `RootUriTemplateHandler` javadoc on the Spring Boot side.

Now about the exception you're seeing, this is something indeed that should be considered in Spring Framework.

**Comment by wilkinsona** [comment]
Re-opening to consider if any improvements to our javadoc could be made.
