### ISSUE TITLE
spring boot test does not load application.properties with PoweMockRunner

### ISSUE THREAD

**Issue by bharukaRupesh** [spring-projects/spring-boot#15350]
Hi,
I have spring boot junit tests which I want to convert to PowerMockRunner. However, the movement I give "PowerMockRunner.class" inside @RunWith, it doesn't load the application.properties file.

can anyone please help me?

@RunWith(PowerMockRunner.class)
@SpringBootTest(classes = TestApp.class)
public class UserSessionServiceTest {
    @Value("${userName}")
    private String userName;
}

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
