### ISSUE TITLE
application.yml with in custom spring boot starter not working

### ISSUE THREAD

**Issue by gouthamkunduru90** [spring-projects/spring-boot#15362]
i am writing a custom spring boot starter which has configurationproperties loaded from application.yml(this yml file has been placed with in the starter src/main/resources). i added the this custom starter in to my spring boot Rest service pom. 
Issue is starter not able to read properties from application.yml so that configurationproperties fields are all null's

**Comment by wilkinsona** [comment]
Only a single configuration file can be loaded from each class path search location. You should not package an `application.yml` file in a starter's jar as it will not be found if the user has an `application.yml` file in their own project. Instead, if your starter needs to provide some default property configuration it should either do that by setting default values in its `@ConfigurationProperties` classes or by using an `EnvironmentPostProcessor` registered in `spring.factories`.

If you have any follow-up questions about the above, please ask on Stack Overflow or Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
