### ISSUE TITLE
Logout doesn't work in some samples

### ISSUE THREAD

**Issue by arnaldop** [spring-projects/spring-boot#1536]
The following samples do not allow for a successful logout.

- spring-boot-sample-web-secure
- spring-boot-sample-web-secure-custom
- spring-boot-sample-web-secure-jdbc

The page shows:

There was an unexpected error (type=Not Found, status=404).
Please contact the operator with the above information.

**Comment by rob-baily** [comment]
I just created a pull request to try and address this.  The issue is as Dave said that a GET was not being accepted.  I changed it to allow GET for logout (using other documentation in Spring Security) and also had to add a permitAll for the logout.  That last part is strange because without the permitAll it appears that logout was not actually logging the user out.  I was getting redirected to the login page but without the "?logout" parameter and then when I logged in I got the login page with the "?logout" parameter so it appears that the logout was having me authenticate again before being able to logout which was very strange,

This is my first attempt at a pull request so forgive any discrepancies and issues with it.

**Comment by dsyer** [comment]
There's a reason /logout only accepts POST by default so I don't want to encourage people to use GET by putting it in the samples. Maybe the reason you are being logged in immediately is that /login is protected and the browser is sending basic auth credentials?

**Comment by rob-baily** [comment]
Yes the reason is mentioned at http://docs.spring.io/spring-security/site/docs/3.2.6.RELEASE/reference/htmlsingle/#csrf-caveats with documentation on how to change it to allow for GET requests.  In regards to what I see as strange behavior i don't understand what you meant by "logged in immediately" as I didn't make any comment in regards to this.  If you want to see the behavior I would recommend applying my change and removing the permitAll() call from logout and you can see what happens when you log out and try to log back in again.  I really think that there is a problem with the default logout processing if you are logging out from a secured session and it would require you to log in if the permitAll is not set.  

In any event, in regards to making it a form, I can do a form and a button based on what is in the gs-securing-web  project.  I was thinking I can do it on top of my other changes and submit a pull request so that people could see the other way if they want or would you prefer it to be a completely separate request?

**Comment by dsyer** [comment]
Sorry I wasn't reading your redirect story closely enough. I'd rather not add a login form to a sample that doesn't already have it, if it's all the same to you (but if there is a sample with a login form, we can start there), but we can add a form for /logout where there is an HTML UI.

**Comment by rwinch** [comment]
@rob-baily Thank you for your feedback. It sounds as though you are having trouble understanding why `logout().permitAll()` is required.

The reason is that security frameworks should not make assumptions or guesses. Imagine the following (real life scenario):
* An administrator authenticates which has root access
* He uses Spring Security's switch user functionality to impersonate a user and allows the user to do some actions within the impersonated session
* In this instance logout might exit the existing user and return to the root user. We would not want to allow this to happen.

The point is that logout simply invokes one or more LogoutHandler implementations which can be implemented by anyone. We don't know what custom implementations are doing nor if anyone should be able to invoke them.

As illustrated by our example, making assumptions can get users in trouble and leads to [security misconfiguration](https://www.owasp.org/index.php/Top_10_2013-A5-Security_Misconfiguration) which is consistently on the top of the OWASP top 10. 

The Spring Security team does feel like it is permissible if you explicitly give the framework consent (i.e. invoke `logout().permitAll()`). Keep in mind that invoking `logout().permitAll()` also allows anyone to view the logout success URL (defaults to /login?logout).

**Comment by rob-baily** [comment]
@rwinch Thank you for reviewing it.  You guys are really helpful and always looking so much appreciated.  I'm still not quite there based on what I have tested so let me run this by you.
* I take the gs-securing-web option and remove the logout().permitAll() call.
* I run the application click the link to login and go to the /login URL.
* I login and get to the /hello resource where it shows me text and the Sign Out button.
* I click the Sign Out button and I am put back to /login and appear to be signed out BUT I do not see the "You have been logged out" button that I see when permitAll() has been used.  I also noticed that I do not have "?logout" as a parameter.
* If I attempt to login again from the page I was just sent to I then get redirected to /login?logout and I see the message "You have been logged out".
Based on this I believe that I am trying to logout from a secured page within the app but it is not being handled quite right without permitAll() being set.  I did this from the project in the Spring Guide so if you can explain what this behavior is I think that might help.  It seems like an issue to me because I thought I am logging out from a secured session already so I don't understand why I would need permitAll() for it to go to the login page with the "?logout" parameter set.

@dsyer The samples have a login form.  I can go ahead and add a logout form as that is easy.  Would you like it done as a completely separate pull or as one built on top of what I did before?

**Comment by dsyer** [comment]
On top is fine probably (easier for you).

I think the `permitAll()` thing is explained by Rob's comment if you study it hard. You *need* `permitAll()` to be able to see the logout success URL as an unauthenticated user.

**Comment by rwinch** [comment]
@dsyer is correct. After you logout you are redirected to a logout success URL (i.e. /login?logout). If you do not grant access to this URL, then a request to /login?logout will likely be restricted and then send the user to the login page (i.e. authentication is required to see the logout success URL).

**Comment by rob-baily** [comment]
@rwinch Well I understand that for best security by default you want to deny everything and only allow what is permitted but it seems like in the default case of setting the logout success to /login?logout that it should be allowed without having to permitAll since the typical case is that the login page (which should already not be required for auth) handles the logout case since by default /login is defined as the login URL.  I guess my issue is really with the default processing so it seems like it would be better to either allow /login?logout to be processed or pick a different default (like /logoutsuccess) so that it is clearer.  I believe that right now in order for the default to actually work everyone would need to do the logout().permitAll() and that is not especially clear from what I have seen.   One thing that confused me is that I had assumed that since /login was OK that passing a parameter /login?logout would also be OK but I saw in the code that there are exact matches for permitting something which is why there could be confusion around this.  In any event I suppose I've spoken my peace on this and you can decide if anything should be done to help clarify it for new users.

@dsyer I submitted the other change and it looks like Phil is probably including it in the next milestone.

**Comment by rwinch** [comment]
Thank you for your feedback. Despite the fact that will not make any changes, it is great to get thoughtful feedback from the community.

**NOTE**: We cannot (even if we wanted to) change things for passivity reasons

> One thing that confused me is that I had assumed that since /login was OK that passing a parameter /login?logout would also be OK but I saw in the code that there are exact matches for permitting something which is why there could be confusion around this.

The fact that you need to do this is documented in the guides at http://docs.spring.io/spring-security/site/docs/3.2.x/guides/form.html#grant-access-to-remaining-resources

The reasoning is that if we are going to guess, we want to guess as exact as possible. This seems quite logical since there is a rule to say anyRequest().authenticated() so we want to be as careful as possible when changing this rule.

Instead of doing the permitAll() on formLogin() and on logout(), you could also specify it in your rules in which case it would be any request to "/login". This is acceptable since antMatcher is precise about how we are matching on that rule. For example, the following will work too:

```java
http
    .authorizeRequests()
        .antMatchers("/login","/logout").permitAll()
        .anyRequest().authenticated()
        .and()
    .formLogin()
        .loginUrl("/login");
```

Note that the following also works:

```java
http
    .authorizeRequests()
        .antMatchers("/secure/**").authenticated()
        .and()
    .formLogin()
        .loginUrl("/login");
```

However, it is not recommended because there is no "catch all" rule to ensure rules aren't missed.

**Comment by rob-baily** [comment]
Thanks for your assistance and guidance!  I've worked a bit with the Spring container but not all of the other modules so it will take me a little time to get into it.  Hopefully having the sample apps work completely will be helpful for others who are trying to build off them.
