### ISSUE TITLE
Application with spring-boot-starter-data-rest and spring-boot-starter-hateoas fails to start

### ISSUE THREAD

**Issue by johnspade** [spring-projects/spring-boot#15383]
[Sample application](https://github.com/johnspade/bean-overriding-problem)

Application with spring-boot-starter-data-rest and spring-boot-starter-hateoas dependencies and annotation @EnableSpringDataWebSupport fails to start.

Spring Boot version: 2.1.1.RELEASE

Output:

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-04 19:18:00.071 ERROR 10464 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'pageableResolver', defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/data/web/config/HateoasAwareSpringDataWebConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

**Comment by wilkinsona** [comment]
Thanks for the sample. I suspect this is related to [DATAREST-1290](https://jira.spring.io/projects/DATAREST/issues/DATAREST-1290) and #14413. Due to the configuration structure in Spring Data REST, it may not be possible for us to back off correctly when you declare your own `@EnableSpringDataWebSupport` annotation. What's your use case for using it? Spring Boot will auto-configure it for you with the right dependencies on the classpath.
