### ISSUE TITLE
JerseyServerMetricsAutoConfiguration should not be tied to ResourceConfig

### ISSUE THREAD

**Issue by zhuchenwang** [spring-projects/spring-boot#15384]
We have the requirement to support multiple Jersey `ResourceConfig`s. The way we are doing is to expose a list of `javax.ws.rs.core.Application` beans and register them as servlets. Now the `JerseyServerMetricsAutoConfiguration` is conditioned on `ResourceConfig` bean. However, in our case, there is no `ResourceConfig` bean exposed in application context. Therefore, the auto configuration is not picked up.

**Comment by wilkinsona** [comment]
The metrics are Jersey-specific and rely on the API provided by `ResourceConfig` to register the `org.glassfish.jersey.server.monitoring.ApplicationEventListener` that, in turn, allows Micrometer's `MetricsRequestEventListener` to record timings for Jersey server requests. Without any `ResourceConfig` beans there is no way for us to hook in Micrometer's metrics.

> We have the requirement to support multiple Jersey `ResourceConfig`s. The way we are doing is to expose a list of `javax.ws.rs.core.Application` beans and register them as servlets

Why are you exposing them as `javax.ws.rs.core.Application` beans rather than `ResourceConfig` beans? There may be some changes that we need to make for that to work, but I can't see how we can achieve what you want without being tied to `ResourceConfig`.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by zhuchenwang** [comment]
`javax.ws.rs.core.Application` is JAX-RS spec which doesn't tie to any implementation. I think `@ConditionOnClass(ResourceConfig.class)` is enough to detect whether Jersey is in the classpath. `@ConditionOnBean(ResourceConfig.class)` is to strict.

**Comment by wilkinsona** [comment]
I disagree that `@ConditionOnBean(ResourceConfig.class)` is too strict. As I said above, we need a `ResourceConfig` to be able to plug in the metrics. Here's the code that does that, using a `ResourceConfigCustomizer`:

https://github.com/spring-projects/spring-boot/blob/ce9626d00fcaf12621278ac0a008813f61cbbff3/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/jersey/JerseyServerMetricsAutoConfiguration.java#L77-L84

If there are no `ResourceConfig` beans, `jerseyServerMetricsResourceConfigCustomizer` won't have anything to customise and there will be no metrics.

If you are aware of a way to gather metrics from Jersey without using `ResourceConfig` then please let us know as I'm not aware of one. Failing that, I think you'll need to expose `ResourceConfig` beans if you want metrics.

**Comment by zhuchenwang** [comment]
In my case, `ResourceConfig` is created dynamically from `javax.ws.rs.core.Application` bean. And it is registered to servlet in my own code. In the same sense, I can inject the `ResourceConfigCustomizer` and customize the `ResourceConfig` created from `javax.ws.rs.core.Application`. However, since there is no `ResourceConfig` bean, the `ResourceConfigCustomizer` is not even there for me to inject.

**Comment by wilkinsona** [comment]
That was the missing piece in the puzzle. Thanks for the extra information.

I'm in two minds about this. While I can see that it would be useful for you to be able to apply the `ResourceConfigCustomizer` yourself, I think your use case is probably an unusual one. Auto-configuring something when, in the majority of cases, it won't be used is something that we try to avoid. Given that you're already doing your own `ResourceConfig` registration rather than relying on `JerseyAutoConfiguration`, you're in a position to configure Micrometer's Jersey integration yourself as well.

Let's see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
We've discussed this and we're in agreement that we don't want to auto-configure the customizer and that you should configure the metrics yourself. Thanks anyway.
