### ISSUE TITLE
ServerResponse.status is invalid in AOP

### ISSUE THREAD

**Issue by linlinyeyu** [spring-projects/spring-boot#15396]
when I use spring boot webflux in AOP,ServerRespose.status is invalid.I set status(401),but it always returns 200,so bad.
the code is follow:
```
@Around("httpPointCut()")
    public Mono<Result> doBefore(ProceedingJoinPoint point) throws Throwable {
        HttpClient httpClient = HttpClientBuilder.create().build();
        String url = suposConfig.getOrigin() + ":" + suposConfig.getPort() + "/api/auth/users/getUserInfoByAccessToken?accessToken=" + cache.get("accessToken", () -> false);
        HttpGet httpGet = new HttpGet(url);
        HttpResponse response = httpClient.execute(httpGet);
        int code = response.getStatusLine().getStatusCode();
        if (code == 401 || code == 400) {
            return ServerResponse.status(401).build().thenReturn(ResponseFormat.response(false));
        }
        return (Mono<Result>) point.proceed(point.getArgs());
    }
```

**Comment by wilkinsona** [comment]
If this is a bug, I think it’s unlikely to be caused by Spring Boot but I can’t be certain with only a code snippet to go on. If you would like us to spend some time helping you to diagnose the problem, please take the time to provide a complete and minimal sample (something we can unzip or git clone and run) that reproduces the problem.

**Comment by linlinyeyu** [comment]
[test.zip](https://github.com/spring-projects/spring-boot/files/2652085/test.zip)
this is a sample,when you request /test/info,it's statusCode always return 200,not 401.

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem isn't AOP, but how you are setting the response's status. You'll see the same problem if you remove the advice and try and set the status directly in your controller:

```
@GetMapping("/info")
public Mono<String> testQuery(@RequestParam("name")String name) {
    return ServerResponse.status(401).build().then(Mono.just("test"));
}
```

This will also produce a 200 response. If you want to control the status of the response, you can use a `ResponseEntity` just as you would in Spring MVC:

```
@GetMapping("/info")
public ResponseEntity<Mono<String>> testQuery(@RequestParam("name")String name) {
	return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Mono.just("test"));
}
```

This will produce a 401 response.

**Comment by linlinyeyu** [comment]
@wilkinsona so the `ServerResponse` can't set the status of the response.Is it a bug?I know `ResponseEntity` can set the status,but I want to unify the form of response with using webflux.
     And in my business project,I have already unified the form,so any suggestions for `ServerResponse`,thanks.

**Comment by wilkinsona** [comment]
No, it's not a bug. As indicated by its package, `org.springframework.web.reactive.function`, `ServerResponse` is part of [WebFlux.Fn](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web-reactive.html#webflux-fn). As its javadoc states, it's intended to be returned by a `HandlerFunction` rather than via a request-mapped method on `@Controller` or `@RestController`. You should use `ResponseEntity` with WebFlux's annotation-based programming model.

If you have any further questions, please follow up on Gitter or Stack Overflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
