### ISSUE TITLE
YAML not parsed correctly when using @PropertySource

### ISSUE THREAD

**Issue by raphw** [spring-projects/spring-boot#15400]
After my last [struggle with a generic configuration](https://github.com/spring-projects/spring-boot/issues/15364) I followed up on one of the work arounds which was using `@PropertySource` to import a configuration per profile instead of using an `application.yaml`. Doing so, I found that the split-up YAML did not work either as Spring (Boot?) does not parse the configuration correctly.

A YAML file such as
```yaml
foo:
      bar: "qux"
```
will result in two properties `foo` with an empty string and a property `bar` with the string value of `qux`.

Is this known or intended? I was very surprised to see this happen. A reconstruction is trivial by simply importing the above file via a `@PropertySource`. I am using Spring Boot 2.1.1.

**Comment by wilkinsona** [comment]
As [noted in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-yaml-shortcomings), you can't load YAML using `@PropertySource`. That's due to Spring Framework not supported it. There's an [open issue](https://jira.spring.io/browse/SPR-13912) that you might want to vote for or comment on.

**Comment by raphw** [comment]
Oh, I overlooked this. Thanks, my bad.
