### ISSUE TITLE
metrics timer

### ISSUE THREAD

**Issue by 595979101** [spring-projects/spring-boot#15405]
I used springboot2.1 actuator to collect Timer data.But at one point the number of calls increased by more than a billion.But that's impossible.Another phenomenon is that this Timer is the only one with problems, and the accident occurred when Prometheus called the Prometheus/Prometheus interface without data. After that, the data exploded and increased for about 5 minutes.Can you help me analyze this problem?thank you
![image](https://user-images.githubusercontent.com/38642570/49650540-76697b80-fa67-11e8-9629-5b024f2395a4.png)

**Comment by wilkinsona** [comment]
Thanks for the report. Spring Boot uses [Micrometer](https://github.com/micrometer-metrics/micrometer) for its metrics. Other than configuring Micrometer, it's not heavily involved in recording metrics so I think you'd be better raising a [Micrometer issue](https://github.com/micrometer-metrics/micrometer/issues) as analysing the problem will require their expertise. If you open a Micrometer issue, please comment here with a link to it so that we can keep an eye on it and help out as needed. If it turns out that the problem is caused by Boot itself we can re-open this issue.
