### ISSUE TITLE
Jetty9 URL rewrite configuration not working

### ISSUE THREAD

**Issue by vlad1918** [spring-projects/spring-boot#15439]
I have a Spring Boot 2.1.0 application with an embedded Jetty 9.4.12 and I want to rewrite the URL request from /rewrite to /rewritten using Jetty9 URL rewrite mechanism. I am able to perform a URL redirect (which responds with HTTP code 302) but not a URL rewrite. This seems like a bug.
Steps to reproduce:
1. Start new spring boot project with Jetty9, jetty-rewrite and starter-web:
```
dependencies {
	compile("org.springframework.boot:spring-boot-starter-web") {
		exclude module: "spring-boot-starter-tomcat"
	}
	compile ('org.springframework.boot:spring-boot-starter-jetty')
	compile ('org.eclipse.jetty:jetty-rewrite')
}
```
2. Configure a simple controller
```

@RestController
public class HelloController {
    @GetMapping(path =  "/redirected")
    public String redirect() {
        return "redirected";
    }

    @GetMapping(path =  "/rewritten")
    public String rewrite() {
        return "rewritten";
    }
}
```
3. Configure bean for Jetty9 RewriteHandler:
```
@Bean
public ConfigurableServletWebServerFactory webServerFactory2() {
	JettyServletWebServerFactory factory = new JettyServletWebServerFactory();
	factory.addServerCustomizers(new JettyServerCustomizer() {
		@Override
		public void customize(Server server) {
			RewriteHandler rewrite = new RewriteHandler();
			rewrite.setRewriteRequestURI(true);
			rewrite.setRewritePathInfo(false);
			rewrite.setOriginalPathAttribute("requestedPath");

			// Working
			RedirectPatternRule rule1 = new RedirectPatternRule();
			rule1.setPattern("/redirect");
			rule1.setLocation("/redirected");
			rewrite.addRule(rule1);

			// Not working
			RewritePatternRule rule2 = new RewritePatternRule();
			rule2.setPattern("/rewrite");
			rule2.setReplacement("/rewritten");
			rewrite.addRule(rule2);

			HandlerCollection handlerCollection = new HandlerCollection();
			handlerCollection.setHandlers(new Handler[] {rewrite, server.getHandler()});

			server.setHandler(handlerCollection);
		}
	});
	return factory;
}

```

4. HTTP call results
/redirect -> HTTP code 302 (and then successfully redirects to /redirected)
/redirected -> HTTP code 200
/rewrite -> **HTTP code 404 (I expect here HTTP code 200 and content from /rewritten)**
/rewritten -> HTTP code 200

**Comment by wilkinsona** [comment]
It appears that the way that Jetty rewrites the request isn't compatible with Spring Framework's `UrlPathHelper.getLookupPathForRequest`. It sees a mixture of `/rewrite` (from `HttpServletRequest.getServletPath()`) and `/rewritten` (from `HttpServletRequest.getRequestURI()`. It ends up using `/rewrite` when `RequestMappingHandlerMapping` is trying to find a mapping that matches. No such handler exists so a 404 is returned.

This isn't something that Spring Boot can control and it looks to me to be a problem in Jetty rather than in Spring MVC. Once the URI has been rewritten I would not expect any evidence of the old URI to be available from the `HttpServletRequest`.
