### ISSUE TITLE
Improve TaskExecution documentation with custom Executor and Spring MVC

### ISSUE THREAD

**Issue by StasKolodyuk** [spring-projects/spring-boot#15447]
Hi!

If you declare any `Executor` in Spring Context it is picked up by `TaskExecutionAutoConfiguration` due to:
```
@Lazy
@Bean(name = APPLICATION_TASK_EXECUTOR_BEAN_NAME)
@ConditionalOnMissingBean(Executor.class)
public ThreadPoolTaskExecutor applicationTaskExecutor(TaskExecutorBuilder builder) {
	return builder.build();
}
```
If using in conjunction with `spring-boot-starter-webflux`, this leads to usage of your custom executor by `WebMvcAutoConfiguration.configureAsyncSupport()` and then by `ReactiveTypeHandler` printing the error.

```
2018-12-11 19:05:10.174  WARN 1612 --- [nio-9015-exec-1] o.s.w.s.m.m.a.ReactiveTypeHandler        :
!!!
Streaming through a reactive type requires an Executor to write to the response.
Please, configure a TaskExecutor in the MVC config under "async support".
The SimpleAsyncTaskExecutor currently in use is not suitable under load.
-------------------------------
Controller:	com.example.executorissue.controller.EchoController
Method:		echo
Returning:	reactor.core.publisher.Flux<java.lang.String>
!!!
```

Maybe it makes sense to use `@ConditionalOnMissingBean(name = APPLICATION_TASK_EXECUTOR_BEAN_NAME)` to allow custom Executors be created in Spring context and not being picked up by `TaskExecutionAutoConfiguration`?

See the example [here](https://github.com/spring-projects/spring-boot-issues/pull/84)

Thanks

**Comment by snicoll** [comment]
@StasKolodyuk your analysis is incorrect as far as I can see and your sample does not match the log that you've provided. A few things:

* Your sample does not demonstrate that your custom `Executor` is picked up by `TaskExecutionAutoConfiguration`. Actually it was designed to not do that and I have no evidence of the  contrary
* That log you gave is based on an MVC app which doesn't match your description
* I have looked at your sample and it is running locally. That log you claim in the `README` doesn't happen 

Please update your sample so that it matches the problem you are describing.

**Comment by StasKolodyuk** [comment]
@snicoll I've updated the example. I've created two tests, please compare the log output.

Sorry for confusion about what's actually going on under the hood.

Let's imagine some custom Executor in context. 
In this case, `TaskExecutionAutoConfiguration.applicationTaskExecutor()` bean is not created due to `@ConditionalOnMissingBean(Executor.class)`:
```
@Lazy
@Bean(name = APPLICATION_TASK_EXECUTOR_BEAN_NAME)
@ConditionalOnMissingBean(Executor.class)
public ThreadPoolTaskExecutor applicationTaskExecutor(TaskExecutorBuilder builder) {
	return builder.build();
}
```

If we look to `WebMvcAutoConfiguration.configureAsyncSupport()` we'll see:
```
if (this.beanFactory.containsBean(TaskExecutionAutoConfiguration.APPLICATION_TASK_EXECUTOR_BEAN_NAME)) {
    Object taskExecutor = this.beanFactory.getBean(TaskExecutionAutoConfiguration.APPLICATION_TASK_EXECUTOR_BEAN_NAME);
    if (taskExecutor instanceof AsyncTaskExecutor) {					 
        configurer.setTaskExecutor(((AsyncTaskExecutor) taskExecutor));
    }
}
```
Due to `APPLICATION_TASK_EXECUTOR_BEAN_NAME` was not created it's not propagated to `RequestMappingHandlerAdapter` where default task executor is created:
```
private AsyncTaskExecutor taskExecutor = new SimpleAsyncTaskExecutor("MvcAsync");
```
This is executor is then passed to `ReactiveTypeHandler` where the error message is logged.

**Comment by snicoll** [comment]
@StasKolodyuk thanks for the update but I am even more confused now. Those tests do not reveal any log for me and that sounds perfectly logical since this is a Webflux application and the log you're referencing is MVC specific (so it isn't even auto-configured in a webflux app).

The update to the sample does not reproduce the issue for me and I wonder why you think it does. 

Having said that, this condition is made for `@EnableAsync` that will pick up your custom executor. If we auto-configure one, we're basically shadowing your configuration. There is a build that lets you easily create an instance that the MVC setup can reuse. Some doc update are in order here.

**Comment by StasKolodyuk** [comment]
@snicoll It turned out that Intellij cached the `spring-boot-starter-web` in the classpath, however it wasn't added in the pom. Updated the example once again :)

Looks like this behavior is reproducible only when both `spring-boot-starter-web` and `spring-boot-starter-webflux` are on classpath

**Comment by StasKolodyuk** [comment]
@snicoll Agree, thanks for help to get it sorted out.
