### ISSUE TITLE
Access static resources using HTTP POST method

### ISSUE THREAD

**Issue by govi20** [spring-projects/spring-boot#15485]
I tried to access the static resource using `HTTP` `POST` method but it is not working. I saw a couple of related questions of `StackOverflow`. 

Here is SO link =>  https://stackoverflow.com/questions/36476638/spring-boot-allowing-post-access-to-static-content

I believe there should be a way to access these resource via `POST` also.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Support for static resource handling is provided by Spring Framework and Spring Boot just auto-configures it for you. I don't believe it's possible to configure the supported methods at the moment as Spring Framework does not provide access to the `ResourceHttpRequestHandler` instances that are created for each `ResourceHandlerRegistration`. Access to the handler is needed so that its `setSupportedMethods` method can be called.

If you would like to pursue this, can you please open a [Spring Framework JIRA ticket](https://jira.spring.io/browse/SPR) and comment here with a link to it.

**Comment by govi20** [comment]
@wilkinsona Done. Thanks! https://jira.spring.io/browse/SPR-17608
