### ISSUE TITLE
spring-boot-sample-web-static can forward subdir/. to subdir/index.html

### ISSUE THREAD

**Issue by karlzheng** [spring-projects/spring-boot#15551]
there is a file  dev/index.html in  the static dir, when I use spring-boot-sample-web-static project, I found that the url: 
http://127.0.0.1:8080/dev/
can't be visited in browser.

(it isn't forward to :  http://127.0.0.1:8080/dev/index.html,  while python SimpleHTTPServer does).

**Comment by wilkinsona** [comment]
Thanks for the report but this is the expected behaviour. [Welcome page support](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-welcome-page) (mapping `/` to `/index.html`) is only supported for the root of the application so `http://127.0.0.1/` will redirect to `http://127.0.0.1/index.html` but `http://127.0.0.1/dev/` will not redirect to `http://127.0.0.1/dev/index.html`.

**Comment by karlzheng** [comment]
> Thanks for the report but this is the expected behaviour. [Welcome page support](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-welcome-page) (mapping `/` to `/index.html`) is only supported for the root of the application so `http://127.0.0.1/` will redirect to `http://127.0.0.1/index.html` but `http://127.0.0.1/dev/` will not redirect to `http://127.0.0.1/dev/index.html`.

1.  Is there a example like "python -m SimpleHTTPServer" which can redirect http://127.0.0.1/dev/  o http://127.0.0.1/dev/index.html. ?
2. is there a simple modify can let this project to be like a python SimpleHTTPServer?
Thx!

**Comment by snicoll** [comment]
As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask questions on StackOverflow.
