### ISSUE TITLE
How to create custom annotation using @KafkaListener to seek from latest offset always. 

### ISSUE THREAD

**Issue by abhishekhbd** [spring-projects/spring-boot#15568]
Is there any example to create custom annotation using @KafkaListener so that it listen from latest offset always.

I want, when I start my app it listen only latest messages. 

I don't want each my listener extends ConsumerSeekAware. I want to make it using aspect. Is it possible?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by snicoll** [comment]
Please note that `KafkaListener` is part of [the `spring-kafka` project](https://github.com/spring-projects/spring-kafka) so asking here for an enhancement is the wrong place anyway.
