### ISSUE TITLE
set custom property when the value is on

### ISSUE THREAD

**Issue by Dylandelon** [spring-projects/spring-boot#15561]
1. When configured in spring boot yml:

my:
  pro: on

Get my. pro's value in the program, it becomes true.

2. When configuring in spring boot yml:

my:
  pro: 'on'
Getting my. pro in the program is on.

2. When configuring in spring boot yml:

my:
  pro: sss
Get my. pro value in the program, sss

that is all. I wonder if this is a normal constraint?

my code:
@Component
@ConfigurationProperties(prefix = "my")
public class MyProperties {
    private String pro;

    public String getPro() {
        return pro;
    }

    public void setPro(String pro) {
        this.pro = pro;
    }

    @Override
    public String toString() {
        return "MyProperties{" +
                "pro='" + pro + '\'' +
                '}';
    }
}

@RestController
public class TestController {

    @Autowired
    private MyProperties myProperties;

    @HystrixCommand(fallbackMethod="getFallback")    // 如果当前调用的get()方法出现了错误，则执行fallback
    @RequestMapping(value = "test1",method = RequestMethod.GET)
    public String test1(){

        return "success:"+myProperties.getPro();
    }

    public String getFallback() {    // 此时方法的参数 与get()一致
        return "fail" ;
    }
}

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
