### ISSUE TITLE
Avoid using @ConditionalOnClass(Flux.class) and similar conditions

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#15574]
The current Spring Boot codebase contains two instances of `@ConditionalOnClass(Flux.class)`:

https://github.com/spring-projects/spring-boot/blob/7946bec11f8b1c6150835f9aebb9a177b4e96723/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/HealthIndicatorAutoConfiguration.java#L83-L85

https://github.com/spring-projects/spring-boot/blob/7946bec11f8b1c6150835f9aebb9a177b4e96723/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/web/reactive/ReactiveManagementContextAutoConfiguration.java#L35-L38

When a Servlet based app depends on a library that transitively pulls in Project Reactor as mandatory dependency, such as Lettuce, the first example will result in `ReactiveHealthIndicatorRegistry` bean registered, which I believe shouldn't be the case in a Servlet app.

The second example is benign and has no consequences, but arguably having `@ConditionalOnClass(Flux.class)` there is needless as it will get shadowed by `@ConditionalOnWebApplication(type = Type.REACTIVE)`.

IMO the conditions that test the presence of Project Reactor on classpath should be avoided due to high likeliness of false positives, unless there's really a valid case for those.

**Comment by bclozel** [comment]
Unless I'm missing something, the first instance in `ReactiveHealthIndicatorConfiguration` is about setting up the reactive infrastructure for any reactive health indicator. I don't know if we can refine the condition here, but in the case of Lettuce, there might be a reactive health indicator to set up for that so we need the infrastructure ready.

Worst case scenario, the application only declares blocking `HealthIndicator` and those are executed on an elastic scheduler. Is there any other downside that I've missed?

Now about the second case; it's true that this `@ConditionalOnClass` might have false positives, but I think that having an auto-configuration class without any `@CondiontalOnClass` is way worse; classpath conditions are cheap and can prevent the class from being loaded if the condition fails. Even with possible false positives, removing that condition will penalize all other cases. The bottom line is: if there's any other safe class that we can use here, less prone to false positives, we should consider it. Do you have any other class in mind?

**Comment by vpavic** [comment]
For Servlet based app, I don't think the choice of Redis driver should influence whether reactive infrastructure should be configured. This is what happens now - if I use Jedis there's no `ReactiveHealthIndicatorRegistry` bean registered.

That's why I think that relying on the presence of Project Reactor on classpath isn't the right thing to do here, but rather to react to the fact that some of the Spring Data's components for reactive Redis have been configured.

**Comment by bclozel** [comment]
Indeed, using Jedis doesn't trigger this piece of infrastructure; but I'm not seeing any downside in enabling that actuator part in case reactive bits are present. Even if the health indicators are not exposed through a web interface, they'll still be executed in a more efficient way.

Setting up a condition on Spring Data doesn't really matter here, since the health indicator usually rely on low-level constructs/drivers. As you said, Reactor is a foundation for reactive libraries and it's the best signal we can pick up here IMO.

The team has discussed that point and we feel that attempting to change that might result in blocking reactive infrastructure in some cases, whereas right now worst thing that can happen is wrapping blocking infrastructure with non-blocking calls.
