### ISSUE TITLE
/logfile error

### ISSUE THREAD

**Issue by xiangtianyu** [spring-projects/spring-boot#15604]
I use my log4j2.xml to record logs, and I want to show logs by /actuator/logfile.
So i set logging.file=/my/path/log.log and logging.config= classpath:log4j2.xml.
But it's strange that when i start my program, log.log can record logs, but when i tried to call localhost:9020/actuator/logfile , a file was download and my log.log was be cleared.What has happened?

the file content:
{
	"description":"file [/my/path/log.log]",
	"file":"/my/path/log.log",
	"filename":"log.log",
	"inputStream":{},
	"open":false,
	"outputStream":{},
	"path":"/my/path/log.log",
	"readable":true,
	"uRI":"file:/my/path/log.log",
	"uRL":"file:/my/path/log.log",
	"writable":true
}

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
