### ISSUE TITLE
Spring Boot Data JPA ignores externalized datasource properties

### ISSUE THREAD

**Issue by chupetoide** [spring-projects/spring-boot#15600]
I have a spring boot app which runs on different environments with the same war and externalized properties on the file system for each environment. It works fine for manually handled properties (I mean packaged properties are overridden with the externalized properties) but It doesn't work for spring.datasource default properties. 

Let's say I have this files:

**classpath: application.properties**
```
app.name=Classpath Name
app.description=Classpath Description
spring.datasource.url=jdbc:h2:file:~/H2/demoClasspath
```

**/var/opt/identicum/rest-api/application.properties**
```
app.name=Filesystem Name
spring.datasource.url=jdbc:h2:file:~/H2/demoFilesystem
```

When I access "app.name" property on runtime it returns "Filesystem Name" so It is ok. But If I access the JPA entities it creates them on the demoClasspath db (local configuration) instead of demoFilesystem.

I've created a [demo app](https://www.dropbox.com/s/tj2unxj812uhg54/spring-boot-jpa-issue.zip?dl=0) with spring boot to reproduce this issue. You can run it with 
```
mvn spring-boot:run
```

You will find this output:
```
2019-01-02 17:13:51.265  INFO 47495 --- [           main] com.identicum.demo.AppStartupRunner      : Property name: Filesystem Name
2019-01-02 17:13:51.266  INFO 47495 --- [           main] com.identicum.demo.AppStartupRunner      : Property description: Classpath Description
2019-01-02 17:13:51.266  INFO 47495 --- [           main] com.identicum.demo.AppStartupRunner      : Datasource url: jdbc:h2:file:~/H2/demoFilesystem
```

That means that configuration is ok but if you check the `~/H2/` folder it contains a demoClasspath file instead of demoFilesystem one. 

**Environment**
Spring Boot Version: 2.1.1
Java Version: 1.8

**Comment by mbhave** [comment]
The url that's used to connect to the database is the value that is bound to the `DataSourceProperties` bean. See [this section](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties) on binding properties from the `Environment` to `@ConfigurationProperties` beans.

It appears that you are using a `PropertyPlaceholderConfigurer` to override the location of `application.properties` and the properties loaded by that are not available during binding. Is there a reason why you need to use that over [`spring.config.location`](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-change-the-location-of-external-properties)?

**Comment by chupetoide** [comment]
This example is a reduced version of my application. I have extended the `PropertyPlaceholderConfigurer` with a custom one to handle encrypted values. I've already tested the configuration with the `spring.config.location` and it works but I can't use the custom configurer. 

Is there any wrong with this configuration?

```xml
<bean id="propertyConfigurer" class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
  <property name="ignoreUnresolvablePlaceholders" value="true" />
  <property name="ignoreResourceNotFound" value="true" />
  <property name="fileEncoding" value="UTF-8" />
  <property name="locations">
    <list>
      <value>file:///var/opt/identicum/rest-api/application.properties</value>
    </list>
  </property>
</bean>
```

Other issue with the `spring.config.location` is that this external property file should be optional. Is there any way to define that as optional ?

**Comment by snicoll** [comment]
> Is there any wrong with this configuration?

Yes. You're doing things at a totally different level. `PropertyPlaceHolderConfigurer` is about replacing a token `${foo.bar}` with an actual value. `DataSourceProperties` doesn't use any of that and is asking the `Environment` the value for the key.

There is [a section in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-customize-the-environment-or-application-context) that explains how to tune the `Environment`. There is also a [dedicated section on encrypted properties](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-encrypting-properties) that refers to the same section.

Even if that was the right abstraction, there is absolutely nothing that ensures this runs before the auto-configuration is processed. Actually, if you put a breakpoint in `DataSourceProperties#setUrl` you will see that the binding is invoked with the content of the `Environment` and then your property placeholder is invoked because you have `@Value` in `AppStartupRunner`.

If you have more questions, please ask on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
