### ISSUE TITLE
Add managed dependency version for hazelcast-hibernate53

### ISSUE THREAD

**Issue by robinroos** [spring-projects/spring-boot#15624]
The following artifact is required to enable Hazelcast as the L2 cache provider for Hibernat versions 5.3+.  Perhaps this could be done for spring-boot 2.1.2.

<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-hibernate53</artifactId>
    <version>1.3.0</version>
</dependency>

**Comment by snicoll** [comment]
@robinroos thanks for the ping, the dependency management was properly updated as part of #15618.

> Perhaps this could be done for spring-boot 2.1.2.

Our upgrade policy prevents to upgrade a dependency to a feature release in a maintenance release of Spring Boot so I am afraid that this is something that we usually don't do. Having said that given that Hazelcast has created a dedicated artifact and we are using Hibernate 5.3 in Spring Boot `2.1.x` it is worth considering at least. 

Let's see what the rest of the team thinks.

**Comment by wilkinsona** [comment]
I don't think we should compromise our maintenance policy here. Hibernate 5.3 went final 7 months ago. It's unfortunate that Hazelcast's official support was released 6 months after that, but it's out of our control. Making an exception here opens the door to other requests to pick up a new feature release of a dependency in a maintenance release and I don't think the benefits outweigh the hassle that will cause.

Boot's dependency managements does not prevent you from using the new module. You can override the `hazelcast-hibernate5.version` property and manage the version of the new `hazelcast-hibernate53` module yourself. That will not be necessary once Spring Boot 2.2 has been released later this year.

**Comment by vpavic** [comment]
To anyone affected or reading this, I'd suggest to drop the use of Hazelcast's Hibernate integration module in favor of Hibernate's own `hibernate-jcache` module. With Hazelcast being a fully capable JCache implementation, that should be by far a more reliable option since it's released by Hibernate team together with the ORM itself.

With that in mind, Spring Boot could even consider dropping dependency management for `hazelcast-hibernateXX` in some future release, and steering users to use the above described arrangement.
