### ISSUE TITLE
Can I use micrometer to send metrics to cloudwatch? There is only aws sdk，but it not support actuator(micrometer). Is there any docs?

### ISSUE THREAD

**Issue by TsingLiang** [spring-projects/spring-boot#15644]
Can I use micrometer to send metrics to cloudwatch? There is only aws sdk，but it not support actuator(micrometer). Is there any docs?

**Comment by spencergibb** [comment]
Check out spring cloud aws

**Comment by TsingLiang** [comment]
Is there a plan to support it in spring boot2?

**Comment by mbhave** [comment]
@TsingLiang Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it).

**Comment by snicoll** [comment]
@TsingLiang this is the third issues you are opening for the same thing (#15631, #15636 and this one). Please stop and review [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc).
