### ISSUE TITLE
Configure Jetty Access Logs - Ignore Paths

### ISSUE THREAD

**Issue by nhomble** [spring-projects/spring-boot#15677]
Could we enhance the jetty access log configuration to set uris to ignore from logging? 

The existing [configuration](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/web/ServerProperties.Jetty.Accesslog.html) doesn't seem to allow any way. Looking at how the request log object is initialized in [the jetty customizer](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/embedded/JettyWebServerFactoryCustomizer.java), I think we could just add the property and set the array there.

My correct workaround is to create my own customizer and cast the RequestLog interface to the NCSARequestLog class. Unless this was by design, I'd like to avoid the blind cast in my configuration.

**Comment by wilkinsona** [comment]
Thus far, we've taken an incremental approach to exposing configuration properties for Jetty's access log. I think it would be good to use this issue to review the configuration properties that we have, the additional properties that `NCSARequestLog` has, and decide which ones we want to expose.

We currently have the following properties:

- `server.jetty.accesslog.append`
- `server.jetty.accesslog.date-format`
- `server.jetty.accesslog.enabled`
- `server.jetty.accesslog.extended-format`
- `server.jetty.accesslog.file-date-format`
- `server.jetty.accesslog.filename`
- `server.jetty.accesslog.locale`
- `server.jetty.accesslog.log-cookies`
- `server.jetty.accesslog.log-latency`
- `server.jetty.accesslog.log-server`
- `server.jetty.accesslog.retention-period`
- `server.jetty.accesslog.time-zone`

`NCSARequestLog` supports the following additional properties:

- `ignorePaths`
- `logDispatch` (deprecated in favour of using `StatisticsHandler`)
- `preferProxiedForAddress`

I think we should add support for both `ignorePaths` and `preferProxiedForAddress`. Flagging for team attention so that we can discuss the properties and agree on which we want to support.

**Comment by nhomble** [comment]
Sounds good @wilkinsona - and I'd be more than happy to follow up with a pr to add the property mappings.

**Comment by wilkinsona** [comment]
We'd like to add both of the missing properties. @nhomble A PR that does that would be most welcome.

**Comment by snicoll** [comment]
Closing in favour of PR #16080
