### ISSUE TITLE
Posting a list via a @RequestParam adds extra [brackets] around the first and last values

### ISSUE THREAD

**Issue by tlvlp** [spring-projects/spring-boot#15715]
**Summary**
When serving and consuming a REST call where a RequestParams is a Collection I get square brackets added to the start of the first value and to the end of the last one.

For example sending "first-topic", "second-topic", "third-topic"
will return "[first-topic", "second-topic", "third-topic]"

Or around the first value if there is only one.
For example sending "first-topic" will return "[first-topic]"

**Tested with**
Not sure if the problem is on the server or consumer side but I'm able to steadily reproducible with Lists and Sets on the below freshly generated, minimal SpringBoot starter project.

**Gradle build script**
```
buildscript {
	ext {
		springBootVersion = '2.1.2.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

**Runnable test app**
```
@SpringBootApplication
public class DemoApplication {
    
    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}

class TopicObject {
    
    private String topicValue;
    
    public TopicObject(String topicValue) {
        this.topicValue = topicValue;
    }
    
    public String getTopicValue() {
        return topicValue;
    }
}

@Service
class RestClient {
    
    @EventListener(ApplicationReadyEvent.class)
    public void subscribeToTopics() {
        
        List<String> topicStrings = Arrays.asList("first-topic", "second-topic", "third-topic");
        
        List<TopicObject> topicObjects = Arrays.asList(
                new TopicObject("first-topic"),
                new TopicObject("first-topic"),
                new TopicObject("first-topic"));
        
        RestTemplate restTemplate = new RestTemplate();
        restTemplate.postForEntity(
                "http://localhost:8080/post-topics?topicObjects={topicObjects}&topicStrings={topicStrings}",
                null,
                ResponseEntity.class,
                topicObjects,
                topicStrings);
    }
}

@RestController
class RestServer {
    
    @PostMapping("/post-topics")
    public void handleSubscriptions(
            @RequestParam("topicObjects") Collection<TopicObject> topicObjects,
            @RequestParam("topicStrings") Collection<String> topicStrings) {
        
        topicObjects.forEach(topic -> System.out.println(topic.getTopicValue()));
        topicStrings.forEach(topic -> System.out.println(topic));
    }
}
```

**I get the following output:**
```
[com.example.demo.TopicObject@1da6ee17
com.example.demo.TopicObject@78d39a69
com.example.demo.TopicObject@3c818ac4]
[first-topic
second-topic
third-topic]
```

**Leading to corrupt database entries, similar to the the one below**
```
> db.subscriptions.find().pretty()
{
        "_id" : "1",
        "topics" : [
                "[first-topic",
                "second-topic]"
        ],
        "_class" : "mypath.Subscription"
}
```

**Comment by wilkinsona** [comment]
Your URI template requires `{topicObjects}` and `{topicStrings}` to be replaced with the values of the `topicObjects` and `topicStrings` variables. They are both `List` instances so the replacement is the result of calling `toString()` on the `List` which results in the `[` and `]` characters at the start and end of the string.

It's not clear how you expect the `TopicObject` instances to be turned into a string and then back into a `TopicObject`. Sending complex objects via request parameters isn't recommended. Instead, I would include them as in the request body.

`topicStrings` should be turned into a `String` of comma-separated values rather than relying on `toString()`. Assuming the use of Java 8 or later, `java.lang.String.join(",", topicStrings)` is a good way to do that.

If you have any further questions, please follow up on Stack Overflow or Gitter.  As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by tlvlp** [comment]
Thanks for the quick reply Andy! 
I seem to have made the wrong assumption that the api is handling the conversion of collection items automatically. Thanks for the clarification!
