### ISSUE TITLE
Clean Code blogpost concerning Spring Boot

### ISSUE THREAD

**Issue by djuelg** [spring-projects/spring-boot#15710]
Hi!

I've calculated some metrics regarding Clean Code for the `spring-boot-project` module and wrote a blogpost about it.
Maybe the results are interesting for your next renovation :)

🎁 [Clean Code: The hard facts and figures](https://craftcodecrew.com/clean-code-the-hard-facts-and-figures/)

Greetings,
Dominik

**Comment by philwebb** [comment]
Thanks for blog post. I wonder what the result would be if test classes were excluded? In the future we'd prefer to hear about this kind of via gitter or twitter since we prefer to keep the issue tracker for bug reports and feature requests. Thanks anyway for letting us know about the article, very interesting.
