### ISSUE TITLE
remove item from list  from manaytomany with one side entity 

### ISSUE THREAD

**Issue by Nesho-Developer** [spring-projects/spring-boot#15711]

**Comment by Nesho-Developer** [comment]
if i have `	@ManyToMany(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinTable(name = "PATIENT_BLOCK_LIST",joinColumns = @JoinColumn(name = "DOCTOR_ID"),
	inverseJoinColumns = @JoinColumn(name = "PATIENT_ID"))
	private List<Patient>  blockedPatients;`
this relation mentioned in this entity only if you try to delete from it 
must  write remove like this `while(doctor.getBlockedPatients().iterator().hasNext()) {
			doctor.getBlockedPatients().remove(doctor.getBlockedPatients().iterator().next());
			doctor = this.save(doctor);
		}`
if seprate iterator from condition give me 
java.util.ConcurrentModificationException
	 java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	 java.util.ArrayList$Itr.next(ArrayList.java:851)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
