### ISSUE TITLE
failed to find org.cloudera.logredactor

### ISSUE THREAD

**Issue by joyang1** [spring-projects/spring-boot#15736]
- Question
When I mvn package spring-boot project, It's always tell me the error:
Failure to find org.cloudera.logredactor:logredactor:jar:1.0.3 in https://repo.spring.io/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced.
I don't want to install  org.cloudera.logredactor locally. 
Can the author tell me the solution?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by joyang1** [comment]
@wilkinsona 
Because this jar is really not in repository(https://repo.spring.io/libs-release).
So I want you help.

**Comment by wilkinsona** [comment]
That message is coming from Maven rather than Spring Boot so this isn't the right place to be asking for help. Also, it's not an error. Maven is telling you that it's going to stop trying to resolve `org.cloudera.logredactor:logredactor:jar:1.0.3` from `https://repo.spring.io/libs-release` for a period of time as it knows it's not there.

If you need some help figuring finding out the URL for a repository that does contain `org.cloudera.logredactor:logredactor` than I'd recommend either posting a question on Stack Overflow or using whatever support mechanisms Cloudera make available.

**Comment by joyang1** [comment]
yeah, I have solved it.
thanks~~~
