### ISSUE TITLE
Spring-boot-maven-plugin 2.1.2.RELEASE build error

### ISSUE THREAD

**Issue by khteh** [spring-projects/spring-boot#15744]
```
[WARNING] The POM for org.springframework.boot:spring-boot-maven-plugin:jar:2.2.0.BUILD-SNAPSHOT is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.springframework.boot:spring-boot-maven-plugin:2.2.0.BUILD-SNAPSHOT: Plugin org.springframework.boot:spring-boot-maven-plugin:2.2.0.BUILD-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.springframework.boot:spring-boot-maven-plugin:jar:2.2.0.BUILD-SNAPSHOT
```
I use spring-boot 2.2.0.BUILD-SNAPSHOT and specify 2.1.2.RELEASE of spring-boot-maven-plugin and bump into this build error. Please advise. Thanks!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
