### ISSUE TITLE
WebsocketContainer missing with Tomcat >= 9.0.13

### ISSUE THREAD

**Issue by sunchezz89** [spring-projects/spring-boot#15746]
After upgrading my local Tomcat i encountered an issue with WebSockets.
I am pretty sure this is a Bug in Tomcat (after 9.0.10), but i guess you should also know about it.

I get the following Exception 
       `Caused by: java.lang.IllegalStateException: Attribute 'javax.websocket.server.ServerContainer' not found in ServletContext
        at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.web.socket.server.standard.ServletServerContainerFactoryBean.afterPropertiesSet(ServletServerContainerFactoryBean.java:117)
`

when i try to access the container with following snippet:

`   @Bean
    public ServletServerContainerFactoryBean createWebSocketContainer() {
        int maxSize = 1024 * 1024 * 16;
        ServletServerContainerFactoryBean container = new ServletServerContainerFactoryBean();
        container.setMaxTextMessageBufferSize(maxSize);
        container.setMaxBinaryMessageBufferSize(maxSize);
        return container;
       }
`

[Demo Project](https://github.com/sunchezz89/spring-boot-tomcat-ws-issue)
The Demo Project does not start on my local machine with following setup:

1. IntelliJ 2018.3
2. Windows 10
3. Tomcat 9.0.13 OR Tomcat 9.0.14 (x64) with jre8

Uninstalling Tomcat and replace it with Tomcat 9.0.10 resolves the issue and the application starts normaly. I don't know what changed in tomcat, but maybe this can be catched (in case, dependency ordering/resolving changed).

Hope this helps.

(I did not test tomcat 9.0.11 and 9.0.12)

**Comment by wilkinsona** [comment]
As far as I can tell, the described behaviour is due to an ordering problem.

Tomcat uses a `ServletContainerInitializer`, `org.apache.tomcat.websocket.server.WsSci`, to set the `javax.websocket.server.ServerContainer` attribute. Spring Framework uses a `ServletContainerInitializer`, `SpringServletContainerInitializer`, to bootstrap the application. Spring Boot plugs into this via its `WebApplicationInitializer` named `SpringBootServletInitializer`. If `WsSci` goes first, the problem does not occur. If `SpringServletContainerInitializer` goes first, the problem occurs.

The ordering described above is out of Spring Boot's control. I suspect it's out of Spring Framework's control too, but they may be able to do something to work around it. https://github.com/spring-projects/spring-framework/issues/22131 appears to be reporting the same problem as has been reported here so we can use that existing issue to continue to track this problem.

**Comment by wilkinsona** [comment]
The change in Tomcat is due to the fix for [this issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=62868). Prior to the change, `ServletContainerInitializer` from Tomcat's `lib` directory would consistently be found (and therefore called) before those in an application's `WEB-INF/lib` directory. After the change, SCIs in Tomcat's `lib` directory are now consistently found and called after those in an application's `WEB-INF/lib` directory.

**Comment by poutsma** [comment]
Not sure if that issue is related, @wilkinsona, as it is fixed in 9.0.13, yet @sunchezz89 still sees a problem on 9.0.14.

**Comment by wilkinsona** [comment]
I believe it is related. Things work fine on Tomcat 9.0.12 and earlier where the fix for the [Tomcat issue](
https://bz.apache.org/bugzilla/show_bug.cgi?id=62868)is not present. On 9.0.13 and later the problem occurs. In other words, the change made in Tomcat 9.0.13 is causing the problem in Spring Framework.

**Comment by poutsma** [comment]
Ah, so [this](
https://bz.apache.org/bugzilla/show_bug.cgi?id=62868) is the cause, not the fix for the problem. That was not clear to me yet.

FWIW, I cannot reproduce the issue with the demo project provided above. Neither with Tomcat 9.0.13 nor 9.0.14.

**Comment by wilkinsona** [comment]
I couldn't either. I did manage to reproduce it with the GraphQL-based projects referenced in 
https://github.com/spring-projects/spring-framework/issues/22131 though.
