### ISSUE TITLE
Start spring-boot application with classLoader

### ISSUE THREAD

**Issue by marcelolx** [spring-projects/spring-boot#15745]
I'm searched a lot for a solution for my case, basically i will start/run my spring boot application in other spring boot application.

How i tried do:

```java
String[] args = { "-Dspring.profiles.active=development",
                "-Dspring.config.location=config/example-db-development.properties,config/example-custom-development.properties",
                "-Dloader.path=test/lib" };

File fatJar = new File("D:/spring-boot-example/test/spring-boot-example-api.jar");

ClassLoader classLoader = new URLClassLoader(new URL[] { fatJar.toURI().toURL() });

Class<?> mainClass = classLoader.loadClass(getMainClassName(fatJar));
Method mainMethod = mainClass.getMethod("main", String[].class);
mainMethod.invoke(null, new Object[] { args });
```
```java
private static String getMainClassName(File fatJar) throws IOException {
        try (JarFile jarFile = new JarFile(fatJar)) {
            return jarFile.getManifest().getMainAttributes().getValue(Attributes.Name.MAIN_CLASS);
        }
    }
```

This started the example project, however, I need to add some dependencies of the example project to the project that should start the same. 
And I'm still having problems for springboot to be able to create beans, for example:

```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vendaPDVControllerImpl' defined in URL [jar:file:/D:/dsv-git/dsv-java/pdv-prototipos/spring-boot-integrador-testes/test/spring-boot-integrador-api.jar!/BOOT-INF/classes!/br/com/sysmo/integrador/api/impl/VendaPDVControllerImpl.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [br.com.sysmo.integrador.api.impl.VendaPDVControllerImpl] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@31f924f5]
```

I do not want to have to add dependencies of the sample project on the project that should start it, and I already looked in the stack overflow for solutions, but found none that solves my problem.

I'd like something like this, but from the classLoader, or another solution that makes it possible to start my application without adding its dependencies to my project:

```
java -jar -Dspring.profiles.active=development -Dspring.config.location=config/example-db-development.properties,config/example-custom-development.properties -Dloader.path=lib example-api-1.00.00.000.jar
```

**Comment by wilkinsona** [comment]
You could probably do this by using `PropertiesLauncher` programatically rather than via `java -jar`. It will create a `ClassLoader` for you based on the jars and directories that you configure it to use. If you need further guidance on this approach, please come and chat on [Gitter](https://gitter.im/spring-projects/spring-boot) or ask a question on Stack Overflow. 
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
