### ISSUE TITLE
When user switching is configured insecurely (allowing switching from an anonymous user), Actuator's `AuthenticationAuditListener` will NPE when exiting the switch

### ISSUE THREAD

**Issue by Darkvater** [spring-projects/spring-boot#15767]
Our application has an anonymous landing page that allows one to impersonate multiple users. The first impersonation works, the second in the same session fails because of an NPE. 

SwitchUserFilter tries to exit the impersonated user before doing the next impersonation. As the previous user is anonymous the originalUser will be NULL (SwitchUserFilter:284 is not executed as obj is a string with value "anonymousUser") and as such the 
audit listener fails with an NPE (AuthenticationAuditListener:106).

This is using spring-boot 1.5.7 and corresponding spring-security 4.2.3 but looking at the code this is still there in the latest 1.5.18 release. 
A potential workaround is to have no audit listener, or a custom one. 

Note: will provide simple example later

**Comment by snicoll** [comment]
@Darkvater the template has a "do not copy/paste" mention so please don't do it. I've edited your comment to remove it.

**Comment by wilkinsona** [comment]
Thanks for the sample. Unfortunately, it's not clear to me how to use it to reproduce the problem. 

Looking at the code, I've figured out that the entry point is http://localhost:8080/landing.html. From there, I can successfully impersonate all three users without an NPE occurring. You've said that it's "crucial that impersonation happens from an otherwise unauthenticated state" but I'm not exactly what you mean by that or how to achieve it. AFAIK, I haven't authenticated. The only thing I have that's provided any state is the JSESSION cookie but deleting that will mean I'm working in a different session and you said in the opening description that "the second in the same session fails because of an NPE".

If you'd like us to spend some more time investigating, can you please take the time to provide the precise steps that must be followed to reproduce the problem.

**Comment by Darkvater** [comment]
Hi wilkinsona, apologies for the unclear instructions.

Steps to reproduce:
* start up your browser and go to http://localhost:8080/landing.html
* open the link "impersonate user1" in a new tab, it will say USER1
* go back to the landing page tab and open the link "impersonate user2" in a new tab, it will say USER2

at this point everything works because a custom authentication audit listener is wired up
* go to your editor and comment out the bean definition at MyApplication:41
* restart the application and try the same steps as previously
* see that when trying to do the second impersonation it will fail and there will be an exception on the server.

**Comment by wilkinsona** [comment]
Thanks. I've reproduced the problem now. It's a bug in Actuator's `AuthenticationAuditListener`. When you switch from being anonymous to a user and then exit that switch, the `targetUser` of the `AuthenticationSwitchUserEvent` will be `null` as the original authentication, `AnonymousAuthenticationToken` that we're switching back to has a principal that is a `String` rather than a `UserDetails`.

**Comment by wilkinsona** [comment]
Having said the above, please note that allowing user switching by an anonymous user is a security risk and ignores the recommendations in the javadoc for `SwitchUserFilter` where it says:

> This filter assumes that the user performing the switch will be required to be logged in as normal (i.e. as a `ROLE_ADMIN` user). The user will then access a page/controller that enables the administrator to specify who they wish to become (see `switchUserUrl`).
> Note: This URL will be required to have appropriate security constraints configured so that only users of that role can access it (e.g. `ROLE_ADMIN`).

We can look at making Actuator's `AuthenticationAuditListener` more robust so that it tolerates an `AuthenticationSwitchUserEvent` with a `null` `targetUser`, but I would strongly recommend updating your security configuration to align with the recommendations quoted above.

**Comment by Darkvater** [comment]
I completely agree with you that it is a security risk. That is why we only have the switch user filter enabled in non-profit environments. It is for our users to be able to impersonate anyone to play around without having to register themselves. 

I have read the javadocs for the filter hence also my original question if we are using the filter correctly ;). It is a very convenient way though to achieve my requirements.
