### ISSUE TITLE
spring websocker, how to implement @sendtouser 

### ISSUE THREAD

**Issue by steveGuRen** [spring-projects/spring-boot#15776]
I want to create a chat in persons who are watching the same video. but I don't know the implementation of @sentTouser in spring. I want to create a similar java anotation  @sentToVideo so that I can just add a method in controller and add this new anotation, and then the method return values can send to the video chat via websocket. Then how to start ? what should I learn in spring ? is there anybody could help me ?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss), we prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
