### ISSUE TITLE
temp location for uploads is not checked or created

### ISSUE THREAD

**Issue by thackel** [spring-projects/spring-boot#15774]
When specifying
```spring.http.multipart.location=${java.io.tmpdir}/subdir/```
i would expect that the directory is either being

- checked for existence and accessibility
or
- created

Currently the multipart upload raises an exception when the directory can not be used:
```
java.io.IOException: The temporary upload location [/tmp/subdir] is not valid
        at org.apache.catalina.connector.Request.parseParts(Request.java:2776) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
[...]
```
It would be nice to know when some setup is wrong (directory not created/accessible) directly after the startup and not when a user tries the to upload data the first time.

Spring Boot 1.5.2

**Comment by wilkinsona** [comment]
@markt-asf Would you consider a change to Tomcat that attempted to create the parent directory before writing the uploaded file to disk?

**Comment by markt-asf** [comment]
I'll note that providing a warning on start-up would require a deeper annotation scan on start-up than is currently performed with the associated negative impact on start-up time.
I'll also note that there may be circumstances (e.g. when running under a security manager or due to file system permissions) where it will not be possible to create the directory even if the container tries to do so.

Given that this could fail anyway, and that the failure may not be visible until the upload is used, I'm not convinced this is worth it. On the other hand, a few lines of code could prevent an issue for some uses cases. I guess I'm +0.

By all means open an enhancement request for this change so the Tomcat community can discuss the request.

**Comment by wilkinsona** [comment]
Looking at this more closely, I don't think there's any way for Spring Boot to easily police this at startup. The location is specified as a `String` and the logic that turns that into a path on the file system isn't completely straightforward and differs between containers. Tomcat and Jetty use the following logic:

 - If the location is null or empty, the temp dir from the servlet context is used.
 - Else, the location is used if it's absolute.
 - Else, the location is used relative to the temp dir from the servlet context.

Assuming that I have read the code correctly, Undertow's logic is different (and a little bit simpler):

- If the location is empty, the temp path from the deployment is used
- Else, the location is used

I think it would be too brittle for Spring Boot to mimic the same logic and check the configuration at startup, particularly given the apparent difference between containers. In short, I think this really needs to be handled at the container level. I've opened https://bz.apache.org/bugzilla/show_bug.cgi?id=63206 to see if there's any appetite in the Tomcat community for changing its behaviour to match Jetty's.

**Comment by timmyz** [comment]
>  I've opened https://bz.apache.org/bugzilla/show_bug.cgi?id=63206 to see if there's any appetite in the Tomcat community for changing its behaviour to match Jetty's.
hi @wilkinsona , i've seen apache accepted your suggestion and make the patch for fix this. when will springboot followup with a new release for it?

>  Fixed in:
> - trunk for 9.0.17 onwards
> - 8.5.x for 8.5.39 onwards
> - 7.0.x for 7.0.94 onwards
> 
> New attribute on Context: createUploadTargets
> Defaults to false

**Comment by wilkinsona** [comment]
We don’t know yet as the new Tomcat versions have not yet been released. You may want to subscribe to https://github.com/spring-projects/spring-boot/issues/9616.
