### ISSUE TITLE
Duplicate CompositeHandlerExceptionResolver implementation

### ISSUE THREAD

**Issue by mhewedy** [spring-projects/spring-boot#15792]
Why spring boot actuator introduced `CompositeHandlerExceptionResolver` since there's a  `org.springframework.web.servlet.handler.HandlerExceptionResolverComposite` doing nearly the same thing.

**Comment by wilkinsona** [comment]
I don't agree with the issue title. `CompositeHandlerExceptionResolver` is not a duplicate of `HandlerExceptionResolverComposite`. As you've said yourself, they do nearly the same thing, but one is not a duplicate of the other. A key difference is that `CompositeHandlerExceptionResolver` looks up the `HandlerExceptionResolver` beans on first-use, rather than requiring them to be configured in advance.

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. This sort of query is more appropriate for chatting on Gitter or, perhaps, a question on Stack Overflow.

**Comment by mhewedy** [comment]
Thanks for clarifications. Will use Gitter second time.
