### ISSUE TITLE
Document limitations with multiple YAML documents within profile-specific files

### ISSUE THREAD

**Issue by neokyle1** [spring-projects/spring-boot#15790]
Spring Boot: 2.1.2.RELEASE
Java: 1.8.0_151

The profile expressions described in the [documentation](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-multi-profile-yaml) do not work. Please see https://github.com/spring-projects/spring-boot/issues/14314 for details.

**Comment by snicoll** [comment]
@neokyle1 thanks for trying to report a problem but "do not work" and a link to a sample that works is not very helpful. 

If you would like us to spend some more time on this, please take the time to provide a complete and minimal sample (something that we can unzip or git clone and run) that reproduces the problem.

**Comment by neokyle1** [comment]
It must have been my project that was causing the issue. I could not reproduce with a fresh project.

**Comment by neokyle1** [comment]
Actually... It looks like the issue is when using expressions in a secondary application-profileX.yml file. I have attached a intellij project dir (windows):
[spring-profile-expressions.zip](https://github.com/spring-projects/spring-boot/files/2804996/spring-profile-expressions.zip)

**Comment by neokyle1** [comment]
Here is a screenshot
![screenshot](https://user-images.githubusercontent.com/10495881/51867121-854e0b00-22ff-11e9-84e1-d2e7a5f5112d.PNG)

**Comment by neokyle1** [comment]
Accidentally Closed.

**Comment by mbhave** [comment]
Thanks for the sample @neokyle1.

The [docs](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-multi-profile-yaml) recommend using YAML documents in a single file for specifying profile-specific properties. Another case where profile-specific YAML files don't work as expected is YAML profile negation. 

I don't know if we should do something about supporting profile-specific yaml files for these cases, especially because the multi-yaml documents work but let's see what the rest of the team thinks.

**Comment by snicoll** [comment]
I think we should clarify the documentation to mention that it isn't supported. The use case above looks quite convoluted to me.

**Comment by mbhave** [comment]
We discussed this on the call today and concluded that using the multi-document syntax within profile-specific YAML files is not something we recommend doing. The cost of implementing this would be quite high and possibly break other things. We'll use this issue to document the limitation.
