### ISSUE TITLE
Autowiring EntityManagerFactory into @Configuration class doesn't work

### ISSUE THREAD

**Issue by arunpmohan** [spring-projects/spring-boot#15811]
We were using spring boot 1.5.10 and our code uses SessionFactory through out. We unwrapped it from entity manager in our configuration class and registered it as a bean to use it across. 
But now when we migrated to spring boot 2.1.2 RELEASE the same autowiring throws a null pointer exception. I have attached a project which shows the problem. Is there anything wrong in this usage or is it a spring bug? You can just run the SampleDataJpaApplication to see the error.
[spring-sample.zip](https://github.com/spring-projects/spring-boot/files/2813904/spring-sample.zip)

Note : If the @Autowiring is done in a `@Component` class then this all works.

**Comment by wilkinsona** [comment]
In Hibernate 5.2, `SessionFactory` was changed to extend `EntityManagerFactory`. This is [mentioned in Hibernate's migration guide](https://github.com/hibernate/hibernate-orm/blob/5.2/migration-guide.adoc#hibernate-entitymanager-merged-into-hibernate-core). As a result, if you declare a `SessionFactory` bean it will disable Boot's auto-configuration of an `EntityManagerFactory` as it is conditional on there being no declaration of an `EntityManagerFactory` bean.

Rather than defining the `SessionFactory` as a bean, I would recommend injecting the `EntityManagerFactory` and unwrapping the `SessionFactory` as needed. If you have any further questions, please follow up on Stack Overflow or Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
