### ISSUE TITLE
spring-boot: tomcat: if management port is different from the app port, the app's access.log goes to /tmp/tomcat.xxxxx.port

### ISSUE THREAD

**Issue by simonso** [spring-projects/spring-boot#1581]
spring-boot 1.1.6
http://stackoverflow.com/questions/23596157/spring-boot-tomcat-access-logs
The issue exists since 1.1
Steps to reproduce
1. in application.properties, define management port = 7081
2. in application.properties, define the app port to be anything but 7081
3. in application.properties, set the server.tomcat.base=/home/mydir
4. Start the spring-boot project with tomcat as the web server
expected: access log goes to /home/mydir
actual: after a few days, the access.log will suddenly appears in /tmp/tomcat.xxxx.port_number
I have cloud deployment that needs to do log rotation. Prefer to centralize everything to one single directory.

**Comment by mdeimel** [comment]
This issue is still reproducible for me on Mac OS X 10.10.1 (Yosemite), using spring-boot-starter-web `1.2.1.RELEASE`.

If I don't set the server and management ports, it logs properly to the `basedir` specified in the properties. If I do change the values the access logs go to very strange folders in the tmp directory, such as `/tmp/prl-1e6aeb63-596a-4be9-b4ec-653c8e6a3c98 logs/access_log.2015-01-26.log`

**Comment by wilkinsona** [comment]
@mdeimel Can you open a new issue please? Your comment's likely to get lost on this issue as it's already closed.
