### ISSUE TITLE
Hibernate spring.jpa.mapping-resources=hibernate.cfg.xml not read after Spring-Boot 2.1.0

### ISSUE THREAD

**Issue by buksvdl** [spring-projects/spring-boot#15824]
Spring-Boot 2.0.8 adds the mappings by creating entities from the *hbm.xml files listed in spring.jpa.mapping-resources=hibernate.cfg.xml, Any release after that ignores the mapping file.

javax.persistence.metamodel.Metamodel metaModel = emf.getMetamodel();
Set<EntityType<?>> entityTypeSet = metaModel.getEntities();

[demo.zip](https://github.com/spring-projects/spring-boot/files/2817693/demo.zip)

**Comment by wilkinsona** [comment]
I don't think the description of the issue is accurate. In Boot 2.1, Hibernate is configured to read the `hibernate.cfg.xml` and does so. The difference in behaviour is due to the [change](https://github.com/hibernate/hibernate-orm/commit/dc49ef6ef4964f2ef840e4b09eda3c821add16cd) the was made to fix [HHH-12871](https://hibernate.atlassian.net/browse/HHH-12871). `ignoreUnsupported` is `true` and the entities found via `hibernate-cfg.xml` have no bindable Java type so they are now skipped.

With Boot 2.1 (Hibernate 5.3), you can restore Hibernate 5.1's behaviour by setting `spring.jpa.properties.hibernate.ejb.metamodel.population=enabled`. However, I don't have the Hibernate expertise to be certain that this is the best thing to do so I would recommend doing your own research if you're also not certain.

**Comment by buksvdl** [comment]
What does that leave us with? Not having used any of the flags in previous releases.
Ours is plain and simple. 
We have mappings and use the EntityType created by Hibernate to get hold of its Attributes and their JavaType.

`EntityType persistEntityType = iceEntityManager.get(persistEntityName);
        Attribute persistAttribute = persistEntityType.getAttribute(attributeName);
        Class persistAttributeJavaTypeClass = persistAttribute.getJavaType();`

Previously this was no problem at all. 
`spring.jpa.properties.hibernate.ejb.metamodel.population=enabled` doesn't work.

In our project there just is no difference between the mapped classes and the annotated @Entity classes. Why should there be a difference?

**Comment by wilkinsona** [comment]
I don't know why there is a difference as I don't fully understand the problem that [HHH-12871](
https://hibernate.atlassian.net/browse/HHH-12871) addresses. If you need some further help, Spring Boot's issue tracker is not the right place to get it. As far as I can tell, the change in behaviour is due to a change in Hibernate. Therefore, you need Hibernate expertise rather than Spring Boot expertise. You can find such expertise on Stack Overflow using the `hibernate` tag or on their [forum](https://discourse.hibernate.org/c/hibernate-orm).
