### ISSUE TITLE
DataSource initialization is executed too late if the DataSource is used in AOP post processor

### ISSUE THREAD

**Issue by lukas-krecan** [spring-projects/spring-boot#15838]
There are three actors in this issue. 
a) schema.sql which needs to be executed before MyBean initialization
b) MyBean, which requires initialized schema (in reality it's Liquibase)
c) AOP interceptor that requires DataSource

If the AOP interceptor depends on DataSource, the order of execution is the following
1) DataSource is initialized
2) MyBean afterProperties is executed (and fails, since schema is not created)
3) schema.sql is executed

If the AOP interceptor does not depend on the DataSource, everything works as expected.

Tested with Spring Boot 2.1.2. Minimalist example of the issue is available here https://github.com/lukas-krecan/datasource-demo. It is distilled version of bug https://github.com/lukas-krecan/ShedLock/issues/121.

I am not sure in which component the bug is (Spring Boot, Liquibase, ShedLock) but it seems to me that it's most likely Spring Boot. If not, please let me know.

AOP interceptor configuration
```java
@Configuration
public class Config {
    /**
     * If this bean is used, schema.sql is executed too late and the application fails.
     */
    @Bean
    public AdvisingBeanPostProcessor proxyScheduledLockAopBeanPostProcessor(DataSource dataSource) {
        return new AdvisingBeanPostProcessor(dataSource);
    }

    /**
     * If this bean is used, schema.sql is executed and the application starts.
     */
//    @Bean
//    public AdvisingBeanPostProcessor proxyScheduledLockAopBeanPostProcessor() {
//        return new AdvisingBeanPostProcessor(null);
//    }

    /**
     * Configures AOP proxy (implementation not needed for the example)
     */
    static class AdvisingBeanPostProcessor extends AbstractAdvisingBeanPostProcessor {
        public AdvisingBeanPostProcessor(DataSource dataSource) {

        }
    }
}
```

The bean depending on the initialized schema.
```java
@Component
class MyBean implements InitializingBean {
    private final JdbcTemplate jdbcTemplate;

    MyBean(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void afterPropertiesSet() {
        // check that the schema was created (simulates liquibase, which does initialization in afterPropertiesSet) fails
        jdbcTemplate.queryForObject("SELECT count(*) FROM myapp.shedlock", Integer.class);
    }
}
```

**Comment by wilkinsona** [comment]
Thanks for the sample.

Generally speaking, injecting dependencies into a bean post-processor is to be avoided as doing so prevents that bean, and anything upon which it depends, from being post-processed. You can see Spring Framework informing you of these when the sample is started:

```
2019-02-04 09:52:48.365  INFO 44371 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-04 09:52:48.385  INFO 44371 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-04 09:52:48.405  INFO 44371 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'dataSource' of type [com.zaxxer.hikari.HikariDataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

The problem you've described here is one symptom of preventing the `DataSource` from being post-processed. The problem occurs because data source initialisation is triggered by a `DataSource` bean post-processor.

I've taken a quick look at ShedLock's code, and I think you'll need to make some changes to how the `LockProvider` is injected into `SchedulerProxyScheduledLockAopBeanPostProcessor`. You could, perhaps, mark the injection point `@Lazy` or, alternatively, inject the `BeanFactory` and look up the `LockProvider` bean when it's first needed.

I'm going to close this one as I don't think there's anything that can be done in Spring Boot. Even if changes were made in how DataSource initialisation is triggered, the current arrangement in ShedLock will still cause problems for anything else that tries to post-process the `DataSource` bean.
