### ISSUE TITLE
Debug mode is not logging web and sql related loggers

### ISSUE THREAD

**Issue by cldsnchz** [spring-projects/spring-boot#15986]
In 2.1, the debug mode (`--debug`) is not logging in debug the `web` and `sql` related loggers, for example: `org.hibernate.SQL`

The issue seems to be in `LoggingApplicationListener`, which is setting in DEBUG the group itself (`web` and `sql`) instead of resolving the loggers in them, as it does for example when logging.level.sql=true is set.

**Comment by wilkinsona** [comment]
Thanks for the report and for the initial analysis. I think you're right. `LoggingApplicationListener.initializeLogLevel(LoggingSystem, LogLevel)`, which is what is called when started with `--debug`, does not take the groups into account so `web` and `sql` are passed as-is rather than being expanded to the logger names that each represents.

**Comment by wilkinsona** [comment]
Closing in favour of #16018.
