### ISSUE TITLE
The for loop in AspectJProxyUtils should add break

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#16010]
When local variable 'foundAspectJAdvice' is set to true, there is no need to continue checking, it should end with break.

![image](https://user-images.githubusercontent.com/13413715/53153501-5d4a8280-35f3-11e9-87d8-5af58aff05ec.png)

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but `AspectJProxyUtils` is part of Spring Framework rather than Spring Boot. There's a chance that the side-effects of calling `isAspectJAdvice` for each `advisor` are important and breaking out of the loop will stop something from working as intended. Can you please open an issue for this [here](https://github.com/spring-projects/spring-framework) and the Framework team will take a look.

**Comment by brucelwl** [comment]
see https://github.com/spring-projects/spring-framework/issues/22449
