### ISSUE TITLE
Add additional auto configuration for jOOQ

### ISSUE THREAD

**Issue by simasch** [spring-projects/spring-boot#16012]
With jOOQ I can supress to add the schema prefix in SQL statements:

```
Settings settings = new Settings().withRenderSchema(false);
```

Or I can change the schema:

```
Settings settings = new Settings()
    .withRenderMapping(
       new RenderMapping().withSchemata(
           new MappedSchema().withInput("db_dev").withOutput("db_prod")));
```

And then pass the settings when creating the DSLContext:

```
DSLContext ctx = DSL.using(connection, MYSQL, settings);
```

Can you please add additional properties to JooqProperties that one can set this in the configuration?

For example:

```
spring.jooq.with-render-schema=false (Default should be true)
spring.jooq.input-schema=db_dev
spring.jooq.output-schema=db_prod
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We don't bind any property to jOOQ's `Settings` class at the moment. The proposal here would introduce binding for `renderSchema` and `renderMapping` with the latter only addressing one specific use case. I think users would find it confusing for some of the properties on `Settings` to be supported and not others. I also don't think that we could offer support for property-based configuration of `renderMapping` that was flexible enough to cover all use cases. As such, I think it would be better handled programatically.

The current auto-configuration will use a `Settings` bean if one exists when creating the `DSLContext`. Have you considered defining such a bean and programatically configuring it to meet your needs?

**Comment by lukaseder** [comment]
Just to provide some input, the third party Gradle code generation plugin generically binds to the programmatic code generation API (which is JAXB annotated) by convention:
https://github.com/etiennestuder/gradle-jooq-plugin

I'm not sure if such a convention based mapping is possible with the `spring.jooq.xyz=abc` notation, but if anything is implemented here at all, for forwards compatibility and maximum flexibility, I think it would have to be convention based as well. Note that `Settings` too are JAXB annotated.

**Comment by simasch** [comment]
@wilkinsona @lukaseder  I understand both of you. 
Personally I don't like a mix of configuration in application.properties and programmatic bean definition.

If we look at the JPA/Hibernate auto-configuration there is also a mix of properties from many places and it's not complete. Also the server auto-configurations for Tomcat, Undertow etc. are not complete.

Concerning compatibility the question is who should provide the starter. Spring or jOOQ?
If it's Spring does I understand that it must be minimal to reduce the effort when migrating to a new jOOQ version. 

At the end it's your decision what to support in auto-configuration and I will be fine with any decision.

**Comment by wilkinsona** [comment]
Looking more closely, we'd end up with properties like the following for configuring a `RenderMapping`:

```
spring.jooq.settings.render-mapping.default-schema=
spring.jooq.settings.render-mapping.schemata[0].input=
spring.jooq.settings.render-mapping.schemata[0].input-expression=
spring.jooq.settings.render-mapping.schemata[0].output=
spring.jooq.settings.render-mapping.schemata[0].tables[0].input=
spring.jooq.settings.render-mapping.schemata[0].tables[0].input-expression=
spring.jooq.settings.render-mapping.schemata[0].tables[0].output=
```

So, in that specific case at least, it's possible. I'm still not sure that we want to open ourselves up to potentially supporting everything on `Settings.

> Personally I don't like a mix of configuration in application.properties and programmatic bean definition.

If you want to avoid a mix, you could define your own `Settings` bean and configure it via your own configuration properties.

> If we look at the JPA/Hibernate auto-configuration there is also a mix of properties from many places and it's not complete. Also the server auto-configurations for Tomcat, Undertow etc. are not complete.

We try to strike a balance, offering configuration properties where it makes sense to do so and providing programmatic configuration as an alternative. That's why we have support for consuming a `Settings` bean that used to create the `DSLContext`. We don't offer configuration properties based support as we're yet to be convinced that it makes sense to do so.

> I'm not sure if such a convention based mapping is possible with the `spring.jooq.xyz=abc` notation, but if anything is implemented here at all, for forwards compatibility and maximum flexibility, I think it would have to be convention based as well.

Unfortunately, convention-based configuration doesn't lend itself very well to providing metadata about the configuration options that are available and their default values. That metadata is generated at compile time based on classes or bean definitions annotated with `@ConfigurationProperties`. If these is an area of jOOQ that's seeing a lot of changes and enhancements, and users of jOOQ and Spring Boot make regular use of a version of jOOQ other than the one against which Spring Boot has been built then taking on property-based configuration is probably not a good idea.

**Comment by lukaseder** [comment]
> If you want to avoid a mix, you could define your own `Settings` bean and configure it via your own configuration properties.

To me, this seems like the most pragmatic choice here

**Comment by simasch** [comment]
> If you want to avoid a mix, you could define your own `Settings` bean and configure it via your own configuration properties.

I agree. I will close the issue. Thanks for your time @wilkinsona and @lukaseder
