### ISSUE TITLE
a request to empty css file return 404 

### ISSUE THREAD

**Issue by wtjperi2003** [spring-projects/spring-boot#16034]
there is a css file whick is empty(no code) in the resources/static repository, and a request to this file, server will return 404. how can I let it return 200?

**Comment by wilkinsona** [comment]
This is by design in Spring Framework. A resource with a content length of 0 is not considered to be readable. Please see https://github.com/spring-projects/spring-framework/issues/21372 for some background information. If you would like to pursue this and would like the current behaviour to be reconsidered, please open a Spring Framework issue as the behaviour is out of Spring Boot’s control. Before doing so, please be aware that it may not be possible to change the current behaviour as I suspect it would regress the fix for https://github.com/spring-projects/spring-framework/issues/21372.
