### ISSUE TITLE
Expose properties to enable conditional logging for Tomcat Access Logs

### ISSUE THREAD

**Issue by amcghie** [spring-projects/spring-boot#16035]
The Tomcat `AccessLogValve` supports conditional logging via two properties:
* `conditionIf`
* `conditionUnless`

Unfortunately these are not yet supported via the `ServerProperties.Tomcat.AccessLog` configuration class.

**Comment by wilkinsona** [comment]
Thus far, we've taken an incremental approach to configuring Tomcat's AccessLogValve. I think it would be good to use this issue to review the properties that we have, the properties that the valve offers, and decide which of them we want to support.

We currently have the following properties:

- `server.tomcat.accesslog.buffered`
- `server.tomcat.accesslog.directory`
- `server.tomcat.accesslog.enabled`
- `server.tomcat.accesslog.file-date-format`
- `server.tomcat.accesslog.max-days`
- `server.tomcat.accesslog.pattern`
- `server.tomcat.accesslog.prefix`
- `server.tomcat.accesslog.rename-on-rotate`
- `server.tomcat.accesslog.request-attributes-enabled`
- `server.tomcat.accesslog.rotate`
- `server.tomcat.accesslog.suffix`

`AccessLogValve` has the following properties that are not currently exposed as configuration properties:

- `checkExists`
- `condition` (the same as `conditionUnless` and provided for backwards compatibility)
- `conditionIf`
- `conditionUnless`
- `encoding`
- `ipv6Canonical`
- `locale`
- `renameOnRotate`

Tomcat's documentation also lists `maxLogMessageBufferSize` but there is no setter for it. It appears to have been removed in https://github.com/apache/tomcat/commit/92ce68ae96dfac3ea3b3cc87f5618207e13a4005. It's not clear to me if that was intentional and the docs are out of date or if the setter should still be there. /cc @markt-asf

**Comment by amcghie** [comment]
I've got a PR ready to submit with the two properties `conditionIf` and `conditonUnless` I'm happy to include the other properties if you would like. Let me know.

Cheers

**Comment by wilkinsona** [comment]
Thanks for the offer. I've added the team attention label so that we can discuss which properties we want to expose. I'm leaning towards all of them other than `condition`.

**Comment by markt-asf** [comment]
Although part of me thinks if no-one has noticed if 5 years we can probably just hard-code it, that does looks like a bug to me. I'll add the getter/setter back.

**Comment by wilkinsona** [comment]
Superseded by #16039.
