### ISSUE TITLE
Investigate Spring 4.1 resource handling support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#1604]
There probably isn't any auto-configuration needed but we might be able to offer additional options in `application.properties`

**Comment by bclozel** [comment]
SPR-12323 is now resolved and is scheduled for 4.2.RC1 by the end of the week.
A new `ResourceResolver` is automatically added if the `"org.webjars:webjars-locator"` library is on path.

I don't think you'd want that library by default in the web-starter, so there's probably nothing to do on Boot's side.

**Comment by bclozel** [comment]
But I thought of some things that could be done for better Resource Handling support: registering automatically a `ResourceUrlEncodingFilter` when Thymeleaf or JSPs are used as templating engines; this filter is used to properly write resource URLs within templates (see `ResourceUrlProvider` in Spring Framework).

Now for other templating engines, this is another problem since you need them to explicitly use `ResourceUrlProvider` to process links - this can be done using helpers (for example, [a Handlebars.java helper](https://github.com/bclozel/spring-resource-handling/blob/master/server/src/main/java/org/springframework/samples/resources/handlebars/ResourceUrlHelper.java)).

Happy to provide a PR for this.
