### ISSUE TITLE
Spring Boot (2.1.3) appears to be re-attempting a failed "insert", in a different section of code

### ISSUE THREAD

**Issue by lfru553ll** [spring-projects/spring-boot#16051]
Spring Boot 2.1.3 (Release)
JDK  1.8.0_191
JUnit 5.4.0

When testing the repository (FooRepository extends from CrudRepository) for a constraint exception (attempting to insert a Foo tuple with non-unique "name" value), it seems like Spring is remembering and rethrowing the exception on  a subsequent call to the repository. Either that, or there is an issue with Hibernate, but I thought that invoking TestEntityManager.flush() in shouldThrowExceptionOnSave() should have resolved that potential issue (i.e., forcing the transaction to commit).

When removeFooTuples() is commented out, the test shouldThrowExceptionOnSave() runs and passes.

When removeFooTuples() is uncommented, the test execution fails with a DataIntegrityViolationException.  This appears to be happening in removeFooTuples(), but the statements logged to the console reference the "insert" attempted in shouldThrowExceptionOnSave().

[files.zip](https://github.com/spring-projects/spring-boot/files/2911493/files.zip)

**Comment by jnizet** [comment]
The Hibernate [documentation about exceptions](http://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#pc-exception-handling) say:

> If the JPA EntityManager or the Hibernate-specific Session throws an exception, including any JDBC SQLException, you have to immediately rollback the database transaction and close the current EntityManager or Session.
> 
> Certain methods of the JPA EntityManager or the Hibernate Session will not leave the Persistence Context in a consistent state. As a rule of thumb, no exception thrown by Hibernate can be treated as recoverable

You're violating this principle in your test: after an exception has been thrown in the test, you try to keep using the entity manager in the `removeFooTuples` method, as if nothing happened.

Removing the tuples is useless anyway, since the DataJpaTests rollback at the end of each test (by default), thus "cancelling" all the inserts that have been made at the beginning of the test.

**Comment by wilkinsona** [comment]
Thank you, @jnizet.
