### ISSUE TITLE
Why choose CGLIB proxying as the default after SpringBoot 2.0

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#16078]
Why choose CGLIB proxying as the default after SpringBoot 2.0 ? What are the advantages? thanks

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by dawi** [comment]
Isn't it a valid question? I am also wondering why the spring team decided to make make cglib proxy the default and was searching for a reference here.
