### ISSUE TITLE
Problems when deploy servel spring-boot projects 

### ISSUE THREAD

**Issue by akunchen** [spring-projects/spring-boot#16116]
I write 2 projects with spring-boot. There are some problems when I deploy them on the server(CentOS 7).See my operations:

- Firstly, I start project A, it works well. 
- Then, I start project B, it works well too.
- But, project A was stopped!
- Then, I restart project A, it works welle, but project B was stopped!

I was confused, who can help me???

**Comment by wilkinsona** [comment]
I suspect you're being affected by CentOS's OOM killer. See [this forum thread](https://centos.org/forums/viewtopic.php?t=64526) for some more details. If that doesn't help, please follow up on Stack Overflow or Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by akunchen** [comment]
You're right! Thanks very much!
