### ISSUE TITLE
Consider disabling auditing by default

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#16110]
Out-of-the-box auditing is backed by `InMemoryAuditEventRepository` which I believe, as already expressed in [#11605 (comment)](https://github.com/spring-projects/spring-boot/issues/11605#issuecomment-358665845), isn't appropriate for production use due to:

- limited storage capabilities
- memory consumption
- not being cluster ready

I would propose to disable this by default and make the whole `AuditAutoConfiguration` conditional on presence of `AuditEventRepository` bean, rather than it having register `InMemoryAuditEventRepository` itself.

This would also be somewhat consistent with the #15039.

**Comment by mrifni** [comment]
Hi, I would like to work on this if possible with some guidance. Please let me know.

**Comment by wilkinsona** [comment]
Thanks for the offer, @mrifini. I think we might need to do a bit of design work until we're ready to implement something here. One option is to do as `@vpavic` suggests. Another would be to make `AuditAutoConfiguration` conditional on a property that's `false` by default. Whatever we do will need to consider #15039 at the same time so that things are consistent. Please leave it with us for now while we figure out what changes we'd like to make.

**Comment by mrifni** [comment]
sure
