### ISSUE TITLE
Cannot scan classpath

### ISSUE THREAD

**Issue by Blackdread** [spring-projects/spring-boot#16218]
Spring version used (but any version should have same issue): 2.0.5.RELEASE
Use java 8

Similar issues:
https://github.com/spring-projects/spring-boot/issues/4375

While using [ClassPath](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/reflect/ClassPath.html) from Guava, it is not possible to find classes once the code is compiled into a jar via spring boot maven plugin.

If I create a simple JavaFx app without Spring and package a runnable jar with default maven plugins (shade/assembly/etc), there is no issue with [ClassPath](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/reflect/ClassPath.html). It will find all classes on class path.

For spring boot app, class loader is "org.springframework.boot.loader.LaunchedURLClassLoader"
Normal app without spring, class loader is "sun.misc.Launcher$AppClassLoader".

ClassPath class is used in [canon-sdk-java](https://github.com/Blackdread/canon-sdk-java/blob/master/camera-framework/src/main/java/org/blackdread/cameraframework/api/constant/ConstantUtil.java), as a  result it cannot dynamically find classes at runtime.
I can solve by manually creating the Set of classes to be used for constants of NativeEnum but it was less error prone to use runtime. (issue [url](https://github.com/Blackdread/canon-sdk-java/issues/4))

EDIT:
Some related discussions:
[one](https://github.com/spring-projects/spring-boot/issues/5338#issuecomment-192327258)
[two](https://github.com/google/guava/issues/2152)

**Comment by wilkinsona** [comment]
Thanks for the report. From a Spring Boot perspective, things have not changed since
https://github.com/spring-projects/spring-boot/issues/5338 and if Guava ClassPath has not addressed its limitations, I would still recommend using something else. It sounds like that may not be possible in your case. Unfortunately that is out of Spring Boot’s control.

You may want to investigate using an alternative packaging format such as a shaded (Maven) or shadowed (Gradle) jar. Alternatively you may be able to nest the classes that need to be found in a jar and use requiresUnpack to have them automatically extracted on launch. If you need further guidance with these suggestions please follow up on Stack Overflow or Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
