### ISSUE TITLE
Add more anchors in the properties appendix

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#16267]
Thanks for adding anchors to the [appendix](https://docs.spring.io/spring-boot/docs/2.2.x/reference/html/appendix.html#integration-properties) (#8237).

This is a big improvement, but I wonder if it could be a bit more granular; for example Integration Properties covers many technologies and properties.

It would be nice if we could jump directly to `rabbitmq` or `kafka` instead of having to scroll past all the other properties.

**Comment by snicoll** [comment]
There are two ways we could fix this issue and both seems to lead on the creation of more tables. If we want to do this in a global fashion, perhaps [our current description](https://github.com/spring-projects/spring-boot/blob/74d00354f52fdd5191dc5d7e1b54b84d370a0fbb/spring-boot-project/spring-boot-docs/src/main/groovy/generateConfigurationPropertyTables.groovy) could have the notion of "sub-sections" so that we could do something like this:

```
.addSection("integration")
    .withSection("spring.activemq").withSection("spring.artemis").withSection("spring.batch") ...
```

That would create one sub-section under the [current integration section](https://docs.spring.io/spring-boot/docs/2.2.0.M4/reference/html/#integration-properties) with the same naming pattern (i.e. "`spring.activemq` properties) and a dedicated anchor.

If we don't want to go down that route, we could split things up a bit and just remove the high-level section and just listing the prefix one by one. In other words, remove the `integration` section and list only the prefixes. Doc output should help us decide what's best probably.

**Comment by garyrussell** [comment]
It is not just the Integration section; I see a similar problem in the Data section with hundreds of properties covering many technologies.

**Comment by Buzzardo** [comment]
It would be good to be able to link directly to a property from other documents. You need not have a heading for each anchor. Inline anchors can go anywhere.

**Comment by wilkinsona** [comment]
I've started working on something for this that will make each individual property linkable.

**Comment by wilkinsona** [comment]
Each property in the 2.4.0 snapshot docs now has an anchor and is a clickable link. For example, [here's `spring.redis.host`](https://docs.spring.io/spring-boot/docs/2.4.0-SNAPSHOT/reference/htmlsingle/#spring.redis.host).

**Comment by garyrussell** [comment]
Sweet - thanks @wilkinsona

**Comment by Buzzardo** [comment]
Very nice. Thanks, @wilkinsona :)

**Comment by philwebb** [comment]
Reopening because I'm afraid on Firefox it doesn't look the best. We might need some doc css updates.

![Screen Shot 2020-09-11 at 5 40 01 PM](https://user-images.githubusercontent.com/519772/92983032-ee8f7d00-f455-11ea-97b2-a3d3564e4cd3.png)

**Comment by philwebb** [comment]
Although I agree, it's a very nice feature!

**Comment by wilkinsona** [comment]
It looks the same in Safari, I'm just less discerning than you. I think the main difference is that there's now a box drawn round each key. I think the CSS does that to any link where the text is monospaced (wrapped in `).

**Comment by wilkinsona** [comment]
https://github.com/spring-io/spring-doc-resources/issues/48 needs to be addressed to fix this. We'll live with it in the meantime.
