### ISSUE TITLE
@MockBean methods cannot be stubbed inside test

### ISSUE THREAD

**Issue by fsw0422** [spring-projects/spring-boot#16324]
```
@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles(profiles = "test")
public class AppTest {

  @MockBean
  private A a;

  @Test
  public void test() throws Exception {
      doReturn(3).when(a).getNumber(any());
  }
}

```
So I am testing the above class and it seems that the MockBean itself is created without any problems. but the stubs inside test is not getting properly setup. if I use `@Testconfiguration` with `@Bean` methods, it works but I do want to stub these behavior dynamically throughout the test just like using plain mockito. are the Mockbean's behavior fixed an cannot be stubbed?

**Comment by wilkinsona** [comment]
You haven't provided enough information to know for sure, but I'd make an educated guess that you're trying to configure behaviour that's relied up during application context refresh. If that's the case, configuring it in a test method is too late as the context will have been created by then. Using a `@Bean` method to create and configure the mock is the recommended approach in this situation.

Assuming that my guess is accurate, we could use this issue to update the documentation.

**Comment by fsw0422** [comment]
@wilkinsona in that case, how do I dynamically stub methods? or even throughout each test? so for each test when I want my mock bean to behave differently, how do I make this happen?

**Comment by wilkinsona** [comment]
I can't answer that without knowing more about what you're trying to do. If you'd like me to spend some more time trying to help you, please spend some time describing the components that you are mocking and how and when they are used.

**Comment by fsw0422** [comment]
```

**Comment by wilkinsona** [comment]
Thank you, @fsw0422. Given that `UpdateEventsListener` only has two dependencies and you want to mock at least one of them, I would unit test it rather than integration testing it.

Aside from the mocking problem, I would also avoid calling methods that do anything from a constructor. As things stand, it looks to me like the thread that calls the constructor will loop in `consumeEvents()` until `stop()` is called. That will block the main thread during application context refresh and prevent your application from starting up fully.

I've opened https://github.com/spring-projects/spring-boot/issues/16333 to improve the documentation. I'm going to close this issue now as there's nothing further to be done in Spring Boot. If you'd like some more guidance on testing and mocking with Spring Boot, please follow up on Stack Overflow or Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by fsw0422** [comment]
@wilkinsona thanx!

**Comment by fsw0422** [comment]
@wilkinsona after fiddling with some other frameworks, it would still be nice to have this feature. I've been using Play Framework and it provides Guice as DI container framework and it stubs perfectly fine in runtime. stubbing is nice because you don't have to create multiple test beans for different behavior or swapping beans in runtime

**Comment by wilkinsona** [comment]
@fsw0422 You can mock things with Spring Boot that are used during application context refresh, you just have to step away from `@MockBean` to do so. Instead, you'd provide a `@Configuation` class that's used by your tests. Te class would provide a `@Bean` method for the mock, preconfigured with whatever expectations you need to be in place during application context.

**Comment by fsw0422** [comment]
@wilkinsona can you change the behavior at the same runtime in the same test?

what I want is something like

**Comment by wilkinsona** [comment]
Yes, you can do that. You'd need to `@Autowired` the mock into your test class and then you can see expectations on it however you want. This is standard Mockito functionality and doesn't really have anything to do with Spring.

**Comment by fsw0422** [comment]
thanks i didn't think of autowiring a mock. I'll try this

**Comment by davebarda** [comment]
I have the same issue, but with a constraint that the bean that is using the post construct is a conditional bean by property, and for some reason if im setting the property using @SpringBootTest or @TestPropertySource(properties = "shouldInitConditionalBean=true")

I get this bean which is depended on my mock stuck in the application context.
shouldn't it create a new context in case of different property?

**Comment by wilkinsona** [comment]
> shouldn't it create a new context in case of different property?

Yes, it should. Please open a new issuing, attaching or linking to a minimal sample that reproduces the behaviour and we’ll take a look.
