### ISSUE TITLE
Open Spring boot source with Eclipse setup

### ISSUE THREAD

**Issue by andresetevejob** [spring-projects/spring-boot#16395]
Hi,

I want to open spring boot source in Eclispe IDE.I read in the doc this step : "For the “Project” click on “+” to add a new setup file. Select “Github Projects” and browser for <checkout>/eclipse/spring-boot-project.setup from your locally cloned copy of the source code. Click “OK” to add the setup file to the list"
How can I do in Eclipse, i find this way to Open the source spring boot,but i dont know how to do

**Comment by wilkinsona** [comment]
The instructions you have found are for developing Spring Boot. They describe how to import the project into Eclipse so that you can modify its source. If that’s what you want to do, please follow the instructions. If anything is unclear, please come and chat on Gitter or ask a question on Stack Overflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. If you are using Spring Boot to develop an application and want to view its source, Eclipse’s Maven or Gradle integration should make the source available automatically.

**Comment by andresetevejob** [comment]
Thanks Andy,
my Goal is to modify source code for contribute to the project Spring boot.


Le dim. 31 mars 2019 à 19:07, Andy Wilkinson <notifications@github.com> a
écrit :

**Comment by andresetevejob** [comment]
what are the links for :
 -chat on Gitter
-Stack Overflow
To post my question related to Spring boot opensource contribution

Le dim. 31 mars 2019 à 19:10, André kouamé <kouameandre43@gmail.com> a
écrit :

**Comment by wilkinsona** [comment]
Spring Boot’s room on Gitter is [here](https://gitter.im/spring-projects/spring-boot).

**Comment by andresetevejob** [comment]
Thanks

Le dim. 31 mars 2019 à 20:16, Andy Wilkinson <notifications@github.com> a
écrit :
