### ISSUE TITLE
Add annotation to support registering Jackson key serializer/deserializer

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-boot#16469]
My use case for using modules in #16463 was to allow registration of a key serializer. 

It would be useful if there was an annotation similar to `@JsonComponent` that supported key serializers and deserializers.

**Comment by philwebb** [comment]
I think we could possibly add a `handle` attribute to `@JsonComponent` so that it could be used for either situation. 

e.g:

```java
@JsonComponent(handle=Handle.TYPES) // the default
```

```java
@JsonComponent(handle=Handle.KEYS) 
```

**Comment by maly7** [comment]
Hi, I'd like to take a shot at this if no one else is working on it. It looks like to add support for this, it would require adding the new handle field to `@JsonComponent` while also modifying the `JsonComponentModule` to conditionally add the component as a key serializer/deserializer based on the field. Does that sound right?

**Comment by koziolk** [comment]
I'm also interested in working on this.

**Comment by philwebb** [comment]
Thanks @maly7 and @koziolk! It looks like @maly7 got there first by a few hours so perhaps he can take a look initially and if it doesn't work our @koziolk can take over.

**Comment by maly7** [comment]
Thanks! I'll try to have a pull request up in the couple of days.

**Comment by maly7** [comment]
Hey @philwebb and @koziolk, I've got everything working fine for serializers, but ran into a bit of a snag with deserializers. When registering a KeyDeserializer, the `addKeyDeserializer` method expects the Class type along with the KeyDeserializer instance. Unlike JsonDeserializer, KeyDeserializer isn't generic, so there doesn't seem to be a way of resolving the type like the JsonComponentModule normally does. So I thought of a couple of options.

One option is to store the type information in the annotation:
```java
@JsonComponent(handle = JsonComponent.Handle.KEYS, handleClasses = {KeyClass.class})
```
and then we can use that information when registering the deserializer.

The other option I can think of is to use the [StdKeyDeserializer](https://fasterxml.github.io/jackson-databind/javadoc/2.3.0/com/fasterxml/jackson/databind/deser/std/StdKeyDeserializer.html) which requires instances to have a key class specified. The key class could then be used in registering the deserializer with the module. 

Personally, I prefer the first option because it doesn't force the usage of StdKeyDeserializer. It's also more flexible in that it would allow someone to use a deserializer that handles multiple classes if they wanted to. What are your thoughts? Do you have any other suggestions?

**Comment by philwebb** [comment]
@maly7 That's a bit of a pain. I think the second attribute you've suggested makes the most sense. It might even be a nice addition for regular serializers where perhaps you want to write `JsonSerializer<BaseClass>` but only register it with a limited number of subclasses.

**Comment by maly7** [comment]
Thanks, @philwebb! Should I go ahead and update `JsonComponentModule` so that when the classes attribute is specified, rather than inferring the type, the serializer/deserializer is registered for those specific classes?

**Comment by philwebb** [comment]
@maly7 Yes please.

**Comment by philwebb** [comment]
Closing in favor of PR #16544
