### ISSUE TITLE
Unable to start application using Infinispan on Client/Server mode with JMX enabled 

### ISSUE THREAD

**Issue by karesti** [spring-projects/spring-boot#16482]
A Spring-Boot application using Infinispan Client/Server with JMX enabled for the Infinispan Client won't start, unless you disable jmx ```spring.jmx.enabled=false```.
Infinispan already registers a bean that is registered by Spring, so we get the following exception on start:
```
org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.infinispan.client.hotrod.RemoteCacheManager@1d67f4e9] with key 'remoteCacheManager'; nested exception is javax.management.InstanceAlreadyExistsException: MXBean already registered with name org.infinispan:type=HotRodClient,name=Default
        at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:625) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jmx.export.MBeanExporter.lambda$registerBeans$2(MBeanExporter.java:551) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at java.base/java.util.HashMap.forEach(HashMap.java:1336) ~[na:na]
        at org.

```
Reproducer [here](https://github.com/karesti/spring-boot-infinispan-jmx)

**Comment by snicoll** [comment]
Thanks for the sample @karesti that's very helpful. The contract is that if a bean in the `ApplicationContext` implements a MBean contract, it will be automatically exposed to the JMX domain.

I can see that `RemoteCacheManager` implements `RemoteCacheManagerMXBean` which makes it a candidate for exposure. There is a little disconnect here IMO. If you're offering a property to expose things to JMX then you either need to make sure to control the exposure in a Spring Boot application or you need to teach Spring Boot what to do and not do.

It also brings some inconsistency from my perspective. Being able to disable JMX for Infinispan is an interesting idea but, as a Spring Boot users, I'd prefer if the starter follows along with whatever `spring.jmx.enabled` does. Right now you are in a situation where your flag is disabled but that MBean is registered anyway if `spring.jmx.enabled` is true.

Having said all that, there's not much we can do about it. If you have beans in the application context that are valid MBeans they will be registered as defined by the contract if JMX is enabled. You can teach us you want otherwise by implementing a `MBeanCustomizer`, I've just submitted a [pull request to your repro project](https://github.com/karesti/spring-boot-infinispan-jmx/pull/1/files) that does that. The app starts fine with that (simplistic) change.

I am going to close this as I don't see a problem in Spring Boot. We can reopen for sure if you feel the support can be improved
