### ISSUE TITLE
org.springframework.security.web.server.authentication.AuthenticationWebFilter

### ISSUE THREAD

**Issue by Gerry-Pan** [spring-projects/spring-boot#16491]
![image](https://user-images.githubusercontent.com/35036729/55731095-27027e80-5a4c-11e9-8282-6329dfb9d3cf.png)
I create MiniServerAuthenticationConverter implements ServerAuthenticationConverter,and override the method convert,but if convert return Mono.error(new AuthenticationServiceException("...")),"this.authenticationFailureHandler.onAuthenticationFailure" can not be invoked
![image](https://user-images.githubusercontent.com/35036729/55731406-bdcf3b00-5a4c-11e9-9250-88ef12b37e85.png)
Then I create a WebFilter like this:
![image](https://user-images.githubusercontent.com/35036729/55731583-0f77c580-5a4d-11e9-9f99-1fafe96b0ca1.png)
I move "onErrorResume" to method "filter(ServerWebExchange exchange, WebFilterChain chain)". 
If “this.authenticationConverter.convert” return Mono.error(...)  or "authenticate(ServerWebExchange exchange, WebFilterChain chain, Authentication token)" return Mono.error(...),"this.authenticationFailureHandler.onAuthenticationFailure" can be invoked.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

Screenshots aren't an ideal way of getting help, so I'd suggest that you take some time to produce a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that you can attach to your stackoverflow question for people to try.
