### ISSUE TITLE
spring data elasticsearch : select field1,field2,count(*) from table order by count(*)

### ISSUE THREAD

**Issue by pgm-rookie** [spring-projects/spring-boot#16496]
My code is like below:

    SearchQuery searchQuery = queryBuilder.addAggregation(
    AggregationBuilders.terms("f1").field("field1").size(Integer.MAX_VALUE).subAggregation(
    AggregationBuilders.terms("f2").field("field2").size(Integer.MAX_VALUE))).build();
    AggregatedPage<AccessLog> aggPage = (AggregatedPage<AccessLog>) this.accessLogRepository.search(searchQuery);
    StringTerms agg = (StringTerms) aggPage.getAggregation("f1");
    //get datas
    List<StringTerms.Bucket> buckets = agg.getBuckets();
    if(!CollectionUtils.isEmpty(buckets)) {
        for(StringTerms.Bucket bucket : buckets){
            StringTerms an = (StringTerms)bucket.getAggregations().asMap().get("f2");
            List<StringTerms.Bucket> ans = an.getBuckets();
            if(!CollectionUtils.isEmpty(buckets)) {
                for(StringTerms.Bucket anBucket : ans){
                    UserActionRankListVO vo = new UserActionRankListVO();
                    vo.setActionName(anBucket.getKeyAsString());
                    vo.setCount((int)anBucket.getDocCount());
                    vo.setMobile(bucket.getKeyAsString());
                    list.add(vo);
                }
            }
        }
    }

I should get all data, add into list and then sort, like this:

    list.sort((v1, v2) -> v2.getCount() - v1.getCount());

How should i do using Spring data elasticseache API or ES JAVA API , like "select field1,field2,count(*) from table order by count(*)" in mysql or oracle , thanks !

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
