### ISSUE TITLE
How  dynamically compile java file in spring boot project?

### ISSUE THREAD

**Issue by javascala** [spring-projects/spring-boot#16506]
JavaCompiler getTask and task.call need options like -encoding UTF-8 -classpath jarpaths,In spring boot project, we know that cannot get jar libs in fat jar
I tried this
` 
for (URL url : ((URLClassLoader) Thread.currentThread().getContextClassLoader()).getURLs()) {
            sb.append(url.getPath()).append(File.pathSeparator);
 }
`
but failed

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
