### ISSUE TITLE
spring-boot-starter-data-jpa Transient is nulled on merge before PrePersist/Update

### ISSUE THREAD

**Issue by kolbma** [spring-projects/spring-boot#16541]
spring-boot-starter-data-jpa: 2.1.4.RELEASE
hibernate: 5.3.9.Final

I call `repository.save(entity)` and depended on the state of the entity a `Transient` value is available in the `PrePersist` or `PreUpdate` method or not available (nulled).

The `Transient` value **should not be nulled** before the Pre-Handlers are called.

The problem is in `DefaultMergeEventListener.entityIsTransient()` before the call of `DefaultMergeEventListener.saveTransientEntity()`.

Because of this there is **no problem** for `Transient`s with entity states when the work is done via `DefaultPersistEventListener` and `DefaultFlushEntityEventListener`.

**Comment by philwebb** [comment]
`DefaultMergeEventListener`, `DefaultPersistEventListener` and  `DefaultFlushEntityEventListener` are all part of Hibernate so it sounds like you'll need to report this [with them](https://issues.jboss.org/projects/HIBERNATE).

I'd suggest taking some time to put together a [ Minimal, Complete, and Verifiable examle](https://stackoverflow.com/help/mcve) before you raise the issue so that they can quickly reproduce it.

**Comment by kolbma** [comment]
Well, I use spring-boot-starter-data-jpa. If it doesn't matter that your products are working, than close your issues without taking care of...

**Comment by philwebb** [comment]
@kolbma The `spring-boot-starter-data-jpa` POM file simply imports Hibernate, but that's a third-party product and we don't have commit rights to their repository. If this is an issue in Spring Boot, we'll happily try to fix it, but it doesn't sound as if there's anything we can do to help.
