### ISSUE TITLE
Investigate Undertow 3 support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16550]
Undertow 3 is [going to be based on Netty](http://lists.jboss.org/pipermail/undertow-dev/2019-April/002318.html) which may impact our current Web MVC/WebFlux detection logic. We'll also need to decide if we support 2.x and 3.x in the same line, or drop 2.x support entirely.

**Comment by wilkinsona** [comment]
Undertow 3 won't have a stable API:

> the 3.x branch will not provide the same level of API compatibility that Undertow has traditionally provided

That'll come in a 4.x release:

> After a short 3.x cycle we are planning on releasing a 4.x that will
provide API stability, in the same way that Undertow 1.x and 2.x have

I'm not sure that we should officially support Undertow 3. Perhaps we should wait for 4, while also tracking 3 so that we can report any problems with the new API before it's declared stable.

**Comment by philwebb** [comment]
I missed that nugget. Yeah, I think we'll have to track 3 but only support 4.

**Comment by wilkinsona** [comment]
It doesn't look like Undertow 3.0 is happening any more. The last commit on the [3.x branch](https://github.com/undertow-io/undertow/tree/3.x) was 17 months ago. I think we can close this one for now and re-open it if the Undertow team's plans change.
