### ISSUE TITLE
@DeleteMapping 405 error

### ISSUE THREAD

**Issue by Lswx2017** [spring-projects/spring-boot#16571]
In my project using Springboot 2.1.2 + Thymeleaf  +webjars+boostrap 4.0+jquery 3.2.1, i hava finished a restful service.The others is ok, but @DeleteMapping is not work.
The error message is :
Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported

There was an unexpected error (type=Method Not Allowed, status=405).
Request method 'POST' not supported.

The key code showed below:
list.html

```html
<button th:attr="del_uri=@{/emp/}+${emp.id}" class="btn btn-sm btn-danger deleteBtn">删除</button>

<form id="delemployeeform" method="post">
    <!-- <input type="hidden" name="_method" value="delete"/> -->
    <input type="hidden" name="_method" value="delete"/>
</form>

<script>
    $(".deleteBtn").click(function(){
        //删除当前员工的
        $("#delemployeeform").attr("action",$(this).attr("del_uri")).submit();
        return false;
    });
</script>
```

EmployeeController.java

```java
@DeleteMapping("/emp/{id}")
public String deleteemp(@PathVariable("id") Integer id){
    employeeDao.delete(id);
    return "redirect:/emps";
}
```

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately a small snippet of HTML and a single controller method aren't enough for us to be able to help you. If you would like us to spend some time helping you to diagnose the problem, please spend some time providing a complete sample that reproduces a problem in the form of a zip file attached to this issue or in a separate repository on GitHub.

**Comment by Lswx2017** [comment]
The project has pushed in
https://github.com/Lswx2017/thymeleafdemos.git

**Comment by wilkinsona** [comment]
Thanks for the sample. You have sub-classes `WebMvcConfigurationSupport` which tells Spring Boot that you want to take complete control over the configuration of Spring MVC. Among other things, taking complete control means that the `HiddenHttpMethodFilter` is no longer auto-configured. As a result, your attempt to delete the employee is handled as a post request.

You can either configure a `HiddenHttpMethodFilter` bean yourself or, and this is what I would recommend, us Spring Boot's auto-configuration instead. To use the auto-configuration you should change `MyMvcConfig` to implement `WebMvcConfigurer` rather than extending `WebMvcConfigurationSupport`. You may also want to review some of your MVC configuration as it duplicates Spring Boot's defaults in places. If you require any further guidance, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by Lswx2017** [comment]
Thx a lot!
