### ISSUE TITLE
Springboot Not Mapping the contextpath when accessing through zuul proxy service.

### ISSUE THREAD

**Issue by Hyerram** [spring-projects/spring-boot#16585]
I recently upgraded our services from spring boot 1.5X version to 2.1X version, Now when I call a swagger URL with the same port number i deployed my service, I could get the response correctly, but when I access the same url with the zuul proxy, i couldn't see the response, It is calling the previous Request URL. 

I deployed my service on https://hostname:port and when accessing this url with swagger https://HostName:port/swagger-ui.html I could get the response correctly.

But when i call it from the Zuul proxy with swagger URL https:hostname:8443/ApplicationName/swagger-ui.html then i see 

```
{
  "timestamp": 1555472542361,
  "status": 404,
  "error": "Not Found",
  "message": "No message available",
  "path": "/user-authentication"
}
```
I saw some blog, saying we need to add context-path, even after adding that property i see the same scenario. Appreciated for the help.

**Comment by wilkinsona** [comment]
This looks like a proxy configuration error rather than a bug but it's impossible to tell without some more information. If you have not done so already, please take a moment to read the [relevant section of the reference documentation](https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server). If, having done that, you believe you have found a bug, please provide a complete and minimal sample that reproduces the problem.

**Comment by Hyerram** [comment]
> This looks like a proxy configuration error rather than a bug but it's impossible to tell without some more information. If you have not done so already, please take a moment to read the [relevant section of the reference documentation](https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server). If, having done that, you believe you have found a bug, please provide a complete and minimal sample that reproduces the problem.
