### ISSUE TITLE
Add profile to spring-boot-parent supporting JDK 9+ dependencies

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-boot#16621]
Is there a way to create a profile in `spring-boot-parent` (manually or automatically applied) that brings in the Java EE libs pulled out of the JDK 11+ (e.g. JAXB) in a managed way?

It would simplify people migrating their apps to Java 9+ by having these libs available.

This sort of thing needs to be a part of Boot 2.1 as well as 2.2 to support users of either version upgrading their version of Java.

**Comment by philwebb** [comment]
@gregturn Can you add a link to the type of change you've been needing to make?

**Comment by gregturn** [comment]
Spring Web Services has [this extra profile](https://github.com/spring-projects/spring-ws/blob/master/pom.xml#L666-L738) to support switching on JDK 11 support, pulling in Java EE libraries that were removed in JDK 11.

Now we don't do it automatically, because Spring Boot itself is built with JDK 11, and the auto-detection algorithms can't distinguish between "built with JDK 11" vs. "built FOR JDK 11", so the profile must be manually activated. When Boot builds, it's broken if Spring WS activates this stuff.

However, Boot may be in the position to switch on such support if it's really at the "top" of the Spring stack.

**Comment by gregturn** [comment]
A commonly cited article for all this stuff is here => https://stackoverflow.com/a/48204154/28214

**Comment by wilkinsona** [comment]
I don't think we can do this in the starter parent, primarily because the additional dependencies that are needed vary depending on the other dependencies that have been used. As far as I know, there's no way in Maven to express that a dependency should be added if a particular JDK is being used and a particular dependency is already present. 

We could do something in Gradle, but there's a better solution on the horizon. Gradle's own metadata format will allow projects like Spring Web Services to express more sophisticated dependency information so that the dependencies that are required to run on Java 11 will be pulled in automatically.

We have a profile in our Web Services sample that show a couple of dependencies that are needed on Java 11:

```xml
<profile>
	<id>java11+</id>
	<activation>
		<jdk>[11,)</jdk>
	</activation>
	<dependencies>
		<dependency>
			<groupId>jakarta.activation</groupId>
			<artifactId>jakarta.activation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
		</dependency>
	</dependencies>
</profile>
```

We also have some [guidance](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9-and-above#jaxb) on the wiki. It's not ideal, but given Maven's limitations, I think this is the best that we can do right now.

**Comment by philwebb** [comment]
I always get a bit confused with Maven profiles, but one thing I was wonder is if it would be worth activating a profile in the starter-parent that could be used by the other starters.

Could we do this in `spring-boot-starter-parent`:

```xml
<profile>
	<id>java11+</id>
	<activation>
		<jdk>[11,)</jdk>
	</activation>
</profile>
```

and this in `spring-boot-starter-data-jpa` (for example)

```xml
<profile>
	<id>java11+</id>
	<dependencies>
		<dependency>
			<groupId>jakarta.activation</groupId>
			<artifactId>jakarta.activation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
		</dependency>
	</dependencies>
</profile>
```

Of course that won't help Gradle and it might make things more confusing overall.

**Comment by wilkinsona** [comment]
As far as I know, a profile declared in a dependency has no effect. For a profile in a pom to have an effect, it has to be declared somewhere that results in it being in the project's effective pom. I've just experimented a bit and Maven's behaviour seems to be what I expected.

**Comment by gregturn** [comment]
Even if it can’t be automatic can it still be used manually?

**Comment by wilkinsona** [comment]
It could, but that's only part of the problem.

AIUI, the profile would need to go in the parent and I don't think that's an appropriate place for it as I tried to explain [above](https://github.com/spring-projects/spring-boot/issues/16621#issuecomment-485691961):

> I don't think we can do this in the starter parent, primarily because the additional dependencies that are needed vary depending on the other dependencies that have been used.

**Comment by philwebb** [comment]
> I've just experimented a bit and Maven's behaviour seems to be what I expected.

I've just done the same experiment to confirm. I'm afraid I don't think there's anything more we can do to help in this area.
