### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by wuyuan0717** [spring-projects/spring-boot#16630]
I have a question, when i used '@EnableCacheing'  in my springboot project, and i added '@Cachable' on a method that has an annotation of '@PostMapping'.Then,
'AbstractHandlerMethodMapping#processCandidateBean' will can`t find the class that has an annotation of '@Cachable' as a handler.However , when i add 'DefaultAdvisorAutoProxyCreator' in my project,the class that has an annotation of '@Cachable' will be handler,but it has two proxies

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
