### ISSUE TITLE
Regression with different case on Column name for same table mapping.

### ISSUE THREAD

**Issue by Rouche** [spring-projects/spring-boot#16654]
Hi, We had a mapping on same table 2 times. (One minimal one full mapping)
One of the column name was different case `@Column(name ="myname") @Column(name ="MYNAME")` 

Spring boot 2.1.3 is working ok.
Spring boot 2.1.4 : Column MYNAME not found

Tryed to incrementally upgrade dependencies (Hibernate, Spring Core, etc) without being able to reproduce with 2.1.3. So i did not find where it comes from unfortunately.
At this point, it would be cool to add a regression note in the Doc to help others.

Reproduce with this project, just execute tests with different case.
https://github.com/Rouche/spring-boot-2.x-bug

**Comment by wilkinsona** [comment]
Thanks for the sample. I've tried to reproduce the problem but have been unable to do so. Looking at the comments in `TestMinimalMDL` it should fail as configured using Spring Boot 2.1.4 and `status` as the column name but it does not do so for me when I run `mvn verify`. Can you please update the sample or provide some more detailed steps so that we can reproduce the problem?

**Comment by Rouche** [comment]
Mmm i just did a fresh clone. `mvn clean install`
Result:
`org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "testmdl0_.STATUS" not found;`

**Comment by wilkinsona** [comment]
Interesting. Unfortuatenly it still doesn't fail for me. Can you please add `debug=true` to `application.properties`, run the build again, and share the output?

**Comment by Rouche** [comment]
Wow this is crazy.
`mvn test` No error
`mvn clean install` Errors in tests

output of both runs are in the repo as `out.txt` and `clean.txt`

**Comment by wilkinsona** [comment]
Thanks. In the two cases, Hibernate generates subtly different SQL to create `TLB_TEST`:

```
2019-04-25 11:46:18.353 DEBUG 14628 --- [           main] org.hibernate.SQL                        : create table TBL_TEST (NUM bigint not null, DESC varchar(255), JOBCODE varchar(255), ORIGIN varchar(255), QTE bigint, DEST varchar(255), DT_TIME timestamp, STATUS varchar(255), TYP varchar(255), USER varchar(255), primary key (NUM))
```

```
2019-04-25 11:48:40.637 DEBUG 6200 --- [           main] org.hibernate.SQL                        : create table TBL_TEST (NUM bigint not null, JOBCODE varchar(255), status varchar(255), DESC varchar(255), ORIGIN varchar(255), QTE bigint, DEST varchar(255), DT_TIME timestamp, TYP varchar(255), USER varchar(255), primary key (NUM))
```

Note the different column ordering and, more importantly, `status varchar(255)` vs `STATUS varchar(255)`

**Comment by Rouche** [comment]
I added output for 2.1.3, debug lines for the create tables seems to not be there. Even with explicit `logging.level.org.hibernate.SQL=debug`

Very weird that you do not get the bug. And even more that 2.1.3 is ok.

**Comment by wilkinsona** [comment]
I just noticed from the output that you were using Windows whereas I was using macOS. I've just tried the sample in a Windows VM and now see the same behaviour as you. `mvn test` works but `mvn clean install` fails.

**Comment by Rouche** [comment]
In my colleagues, one of them was on Mac, with same problem. A bit old laptop i think tough.

**Comment by wilkinsona** [comment]
Which version of Maven are you using in each case?

**Comment by wilkinsona** [comment]
I've made some progress on this and the failure only occurring on Windows has proven to be a red herring.  There are quite a few moving parts in the same including the use of DevTools, default profiles, and particular profiles being active for the failure to occur. I inadvertently had `spring.profiles.active` configured in my global `~/.spring-boot-devtools.properties` file which prevented the default profiles from being active. This, in turn, prevented the problem from occurring. With this configuration removed, the failure now occurs on both macOS and Windows.

This difference in behaviour between `mvn test` and `mvn install` is due to the two using different classpaths. In the `test` case, the services' projects `test-classes` directory is on the classpath. In the `install` case it's the jar file. This difference in the classpath affects the order in which `TestMDL` and `TestMinimalMDL` are processed. When `TestMinimalMDL` goes first `status` is used as the column name when creating the table and the subsequent failure occurs. When `TestMDL` goes first `STATUS` is used as the column name and the subsequent failure does not occur.

When using Spring Boot 2.1.3 the failure does not occur with either `mvn test` or `mvn install`. Hibernate generates the same SQL with 2.1.3 and it does with 2.1.4 but H2 treats it differently. With 1.4.199 (used by Spring Boot 2.1.4) the `status` used to name the column when creating the table results in a failure when using `STATUS` to query the table. With 1.4.197 (used by Spring Boot 2.1.3) the difference in case of `status` and `STATUS` does not matter and the query succeeds.

The change in H2's behaviour is a result of [this change](https://github.com/h2database/h2database/pull/1745) that was made in 1.4.198. While this hasn't been easy to track down, that's largely due to the number of moving parts in the sample and the red herring with Windows. Once I knew it occurred on both Windows and macOS, it didn't take long to identify H2 as the cause.

I don't think this sort of change in a third-part dependency is something that we should document. It would be an almost endless task to document every change in every release of Spring Boot's managed dependencies. The change in H2 was made harder than it might have been as it is not listed in H2's [release notes](http://www.h2database.com/html/changelog.html). You may want to reach out to the H2 team to make sure they are aware of the change in behaviour caused by https://github.com/h2database/h2database/pull/1745 and to see if they can update the release notes to mention the change.

**Comment by Rouche** [comment]
Windows: was 3.6.0, just upgraded to 3.6.1 JDK 1.8.0_211
MacOS: 3.5.4 JDK 1.8.0_181

**Comment by Rouche** [comment]
Wonderfull explanation. Sad this came from so deep.
