### ISSUE TITLE
handler Mappings without Servlet name

### ISSUE THREAD

**Issue by kiddingYang** [spring-projects/spring-boot#16650]
i have two dispatch-servlet , one url mapping /api/* , the other url mapping /app/*
config like above 

```
@Bean
    public ServletRegistrationBean<DispatcherServlet> apiServlet() {
        AnnotationConfigWebApplicationContext applicationContext = new AnnotationConfigWebApplicationContext();
        applicationContext.scan("com.api");
        DispatcherServlet app_dispatcherServlet = new DispatcherServlet(applicationContext);
        ServletRegistrationBean<DispatcherServlet> registrationBean = new ServletRegistrationBean<>(app_dispatcherServlet);
        registrationBean.setLoadOnStartup(1);
        registrationBean.setName("api");
        registrationBean.addUrlMappings("/api/*");
        registrationBean.setMultipartConfig(multipartConfigElement);
        return registrationBean;
    }
```
```
@Bean
	public ServletRegistrationBean<DispatcherServlet> appServlet() {
		AnnotationConfigWebApplicationContext applicationContext = new AnnotationConfigWebApplicationContext();
		applicationContext.scan("com.app");
		DispatcherServlet app_dispatcherServlet = new DispatcherServlet(applicationContext);
		ServletRegistrationBean<DispatcherServlet> registrationBean = new ServletRegistrationBean<>(app_dispatcherServlet);
		registrationBean.setLoadOnStartup(1);
		registrationBean.setName("app");
		registrationBean.addUrlMappings("/app/*");
		registrationBean.setMultipartConfig(multipartConfigElement);
		return registrationBean;
	}
```
its works well, but has one question. if i has an request url /app/test in package com.app 
but i can access by /api/test. It doesn't meet my expectations. i just want /app/test access

can I change some of the configurations for that？

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
