### ISSUE TITLE
Why can browse resources ->templates->x.html without through the controller

### ISSUE THREAD

**Issue by hua2buxie** [spring-projects/spring-boot#16708]
I remember the templates folder 's thymeleaf html file must use the controller ,but I find I can  browse the html without the controller,and the html file in the templates  folder.
![1](https://user-images.githubusercontent.com/17213220/57134410-b5161e80-6dd8-11e9-8654-2242439d8775.png)
![2](https://user-images.githubusercontent.com/17213220/57134444-ceb76600-6dd8-11e9-8850-b90174f45198.png)

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
