### ISSUE TITLE
Allow @ConditionalOnProperty NOT to match if the property value is empty

### ISSUE THREAD

**Issue by dimazig** [spring-projects/spring-boot#16721]
In my opinion `@ConditionalOnProperty` should be behave like `@ConditionalOnExpression("!'${some.property:}'.empty")`

If property is present but value is empty should be equal like there's no property or at least there should be a flag which enables such behaviour

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I'm not sure that we want to introduce any extra complexity to `@ConditionalOnProperty`. We already have the `matchIfMissing` attribute that allows the condition to match if the property isn't set. Having another attribute for `matchIfEmptyValue` would, I think, create some confusion.

Perhaps you can describe the use case that requires the behaviour that you have described?

**Comment by dimazig** [comment]
You don't get me.
for instance I have templated application.properties. It is produced by some CI/CD system. For particular environment I don't want my optional feature to be enabled. So don't set any value. As a result application.properties has a property like that some.property=
So it is present but no value set. My expectation is that my optional bean won't be triggered but ConditionalOnProperty doesn't work like that. It triggers the bean even though there's no value set.

**Comment by wilkinsona** [comment]
We can't change the current behaviour to match your expectation as it would be a breaking change. To provide the behaviour that you want, we would have to add an attribute to `@ConditionalOnProperty` to enable it so that you could opt in and so that existing use of `@ConditionalOnProperty` would be unaffected.

You have a couple of options with what's currently available:

1. Use `havingValue` to restrict the value that the condition will match
2. Set the property value to `false`

If these don't meet your needs then a custom condition may be your best option as I am still not convinced that we want the added complexity of another attribute.

**Comment by dimazig** [comment]
yeah, I understand that it would be a breaking changed so would be great to add an attribute like havingAnyValue=true or processing havingValue="any" or havingValue="*

**Comment by wilkinsona** [comment]
Thanks for the suggestions.

We can't give special meaning to `havingValue` with `any` or `*` so that they match any non-empty value. Someone may already be using the condition where they want to match a property with the exact value `any` or `*`.

As I've said before, I'm also not keen on the additional complexity of adding an extra attribute for your use case. I don't think the requirement is common enough to justify adding complexity for everyone. I think you'd be better writing a custom condition that meets your specific needs. That said, I'll flag this for team attention as the rest of the team may not share my opinion.

**Comment by snicoll** [comment]
I am not keen to introduce further complexity to `@ConditionalOnProperty` either.

**Comment by wilkinsona** [comment]
Thanks again for the suggestion. We've discussed this today and the team's opinion is that we don't want the extra complexity of an additional attribute. To get the functionality that you want, you should write a custom condition as described in the Stack Overflow issue to which you have linked above.

**Comment by wilkinsona** [comment]
Thanks again for the suggestion. We've discussed this today and the team are in agreement that we do not want the added complexity of the additional attribute that would be required to support your use case. Our recommendation is that you write a custom condition to get the behaviour that you want.
