### ISSUE TITLE
Custom MultipartFilter filter does not work.

### ISSUE THREAD

**Issue by JangCool** [spring-projects/spring-boot#16878]
spring boot version : 2.1.1.RELEASE

Hi.

I have an important problem during development and  want to you ask.
As you can see below, i used multipart default settings , file uploading is done well.

application.properties:
```
spring.servlet.multipart.enabled=true
```

upload success log:
```
parameter.get() - {item=A10001, prdNo=100002010, prdNm=nike }  
getString("prdNo") - 100002010  
getStringArray("prdNo") - 100002010  
uploadFiles.length - 2  
```

However, I set it to `javaConfig` instead of using default settings.
As a result, general parameters such as the following and file objects can not be read.
Is the way I set it wrong?
Please answer fast.

application.properties:
```
spring.servlet.multipart.enabled=false
```

```java
@Bean
public MultipartFilter multipartFilter() {
	MultipartFilter multipartFilter = new MultipartFilter();
		multipartFilter.setMultipartResolverBeanName(DispatcherServlet.MULTIPART_RESOLVER_BEAN_NAME);
	return multipartFilter;
}
```

failure log
```
parameter.get() - {}  
getString("prdNo") - null  
getStringArray("prdNo") - {}  
```

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
