### ISSUE TITLE
Make use of @DynamicPropertySource in our integration tests

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16886]
There's a bit of ceremony involved at the moment:

```java
@Testcontainers
@ContextConfiguration(initializers = DataRedisTestIntegrationTests.Initializer.class)
@DataRedisTest
public class DataRedisTestIntegrationTests {

    @Container
    public static RedisContainer redis = new RedisContainer();

    // …

    static class Initializer
            implements ApplicationContextInitializer<ConfigurableApplicationContext> {

        @Override
        public void initialize(
                ConfigurableApplicationContext configurableApplicationContext) {
            TestPropertyValues.of("spring.redis.port=" + redis.getMappedPort())
                    .applyTo(configurableApplicationContext.getEnvironment());
        }

    }
```

It would be nice to be able to do something like this instead:

```java
@Testcontainers
@DataRedisTest
public class DataRedisTestIntegrationTests {

    @Container
    @MapPortToProperty("spring.redis.port")
    public static RedisContainer redis = new RedisContainer();
```

A few thoughts:

- The examples above are JUnit 5. We'd need to consider JUnit 4 as well
- The lifecycle ordering will need to be right so that the container's port is available before the context refreshes
- Setting the port will affect context caching

/cc @bsideup

**Comment by bsideup** [comment]
@wilkinsona 
Take a look at https://github.com/Playtika/testcontainers-spring-boot

Also, there are a few things to consider covering:

- it is very important to also map the host, not just port. It is "localhost" only in ~60% cases
- some containers provide convenient methods like `KafkaContainer#getBootstrapServers`, perhaps we can use a SpEL expression or something

BTW I have a bit crazy idea:
What if Spring Boot implements something like:
```java
@Testcontainers
@DataRedisTest
public class DataRedisTestIntegrationTests {

    @Container
    public static RedisContainer redis = new RedisContainer();

    @PropertyContributor
    static Callable<PropertySource> propertySource = () -> {
        return TestPropertyValues.of(
            "spring.redis.host=" + redis.getContainerIpAddress(),
            "spring.redis.port=" + redis.getMappedPort()
        );
    }
```

This way it can source properties from anywhere, including Testcontainers. WDYT?

**Comment by antkorwin** [comment]
Hi, I think I solved this in my library (here: https://github.com/jupiter-tools/spring-test-redis), maybe it can help you:

```
@SpringBootTest
@RedisTestContainer
class RedisTestContainerTest {

    @Autowired
    private RedisTemplate redisTemplate;

    @Test
    void readWriteValueByRedisTemplate() {
        String key = "test";
        String value = "sabracadabra";
        // Act
        redisTemplate.opsForValue().set(key, value);
        // Assert
        assertThat(redisTemplate.opsForValue().get(key)).isEqualTo(value);
    }
}
```


this code run Redis test container and bind it to default spring boot properties (`spring.redis.host` / `spring.redis.port`)

I use my own `ContextCustomizer`, it provides an ability to start multiple containers and avoids problems with context caching in tests. Also, it provides independence on the test engine (you can use JUnit4 and JUnit5)

Example of executing multiple containers in the one test case:

```
@SpringBootTest
@RedisTestContainer 
@RedisTestContainer(hostTargetProperty = "second.redis.host", portTargetProperty = "second.redis.port")
@RedisTestContainer(hostTargetProperty = "third.redis.host", portTargetProperty = "third.redis.port") 
class MultipleContainerInOneTest {
    ...
}
```
the second container set host/port value in the specified properties, after start application context.


Maybe we can use it as part of the spring boot? I am ready to make a PR here.

**Comment by wilkinsona** [comment]
Thanks for the offer, @antkorwin, but that's not quite what we're looking for here. The use of Redis was just an example and my goal is to provide something that works for any container that's being managed by Testcontainers. That would be something along the lines of the general purpose annotation in my opening description or the property contributor imagined by @bsideup.

**Comment by nosan** [comment]
I have a slightly different approach. Please take a look https://github.com/nosan/spring-boot/commit/6796396ac44d44f5306a6e3263f4e6d3d9b68c30  This commit introduces `@MapToProperty` annotation. This annotation can be applied only to **static** fields. 

Here is a quick example of how this annotation can be used:

```java


class DataRedisTests {

// (1) SpEL. 
	@Container
	@MapToProperty(name = "spring.redis.port", expression = "#this.getFirstMappedPort()")
	@MapToProperty(name = "spring.redis.host", expression = "#this.getContainerIpAddress()")
	static final RedisContainer redis = new RedisContainer();
	
// (2) Suppliers	
	@Container
	static final RedisContainer redis = new RedisContainer();
	@MapToProperty(name = "spring.redis.host")
	static final Supplier<String> host  = redis::getContainerIpAddress;
	@MapToProperty(name = "spring.redis.port")
	static final Supplier<Integer> REDIS_PORT_SUPPLIER = redis::getFirstMappedPort;
	
// (3) Constants	
	@MapToProperty(name = "spring.redis.port")
	static final int port = 6379;

}

```

Please let me know what you think.

**Comment by nosan** [comment]
Btw, maybe it would be nice to have:

```java
	@MapToProperty("spring.redis")
	static final Supplier<Map<String, Object>> properties = () -> {
		Map<String, Object> source = new LinkedHashMap<>();
		source.put("host", redis.getContainerIpAddress());
		source.put("port", redis.getFirstMappedPort());
		return source;
	};

```

**Comment by philwebb** [comment]
The low level property mapping support is quite nice, but I can't help feeling that we should be able to apply these conventions automatically. I wonder if we can provide some pre-supplied mapping conventions that detect well known containers and map them to well known Spring Boot properties.

In other words, can we make it so that this lone will get you `spring.redis.host` and `spring.redis.port` properties:

```java
@Testcontainers
@DataRedisTest
public class DataRedisTestIntegrationTests {

    @Container
    public static RedisContainer redis = new RedisContainer();
```

**Comment by wilkinsona** [comment]
That feels a little bit too magic to me.

**Comment by bsideup** [comment]
@philwebb
as much as I like the idea of having a native support for Testcontainers in Spring Boot Test, I agree with Andy that it is too magical, plus, since only a sub-set of containers will be supported, it can be confusing when somebody will declare a container (especially the generic one) an expect Spring Boot to do the magic without realizing that it is on per-type basis.
`PropertyContributor` looks like a good middle ground here.

@nosan
> `	@MapToProperty("spring.redis")`
> `	static final Supplier<Map<String, Object>> properties = () -> {`

While I understand why you want to do this, most probably you will have more than one container, and the syntactic overhead of defining a few property contributors will overcome the benefit

**Comment by nosan** [comment]
@bsideup 

```java
       @MapToProperty
	static final Supplier<Map<String, Object>> properties = () -> {
		Map<String, Object> source = new LinkedHashMap<>();
		source.put("spring.redis.port", redis.getFirstMappedPort());
		source.put("spring.redis.host", redis.getContainerIpAddress());
		source.put("spring.data.neo4j.uri", neo4j.getBoltUrl());
		return source;
	};

```
`value` attribute can be omitted for a `Map`

**Comment by nosan** [comment]
@philwebb 
It would be nice to support not only `TestContainers`. 
I have a project *embedded-cassandra* and it has `CassandraRule` class which can be used in conjunction with `@ClassRule` to start and stop `Cassandra`.
So with `@PropertyContributor` or `@MapToProperty` I would be able to do:
```java


	@ClassRule
	public static final CassandraRule cassandra = new CassandraRule();

	@MapToProperty("spring.data.cassandra")
	public static final Supplier<Map<String, Object>> cassandraProperties = () -> {
		Map<String, Object> properties = new LinkedHashMap<>();
		Settings settings = cassandra.getSettings();
		properties.put("port", settings.getPort());
		properties.put("contact-points", settings.getAddress().getHostAddress());
		return properties;
	};

```

**Comment by nosan** [comment]
I've updated my approach a bit in my branch:  https://github.com/nosan/spring-boot/commit/ed8c6f491b6b9288b7d7abea50b17bdd77460724

Here is a list of types that can be used with `@MapToProperty`:

```java
//spring=boot
@MapToProperty("spring")
String name = "boot";

//spring[0]=boot, spring[1]=framework
@MapToProperty("spring")
Collection<String> collection =Arrays.asList("boot","framework");

//spring[0]=boot, spring[1]=framework
@MapToProperty("spring")
String[]array={"boot","framework"};

//spring=boot
@MapToProperty("spring")
Callable<String> callable=()->"boot";

//spring-boot.version=2.0.0
@MapToProperty("spring-boot")
Map<String, Object> prefixMap=Collections.singletonMap("version","2.0.0");

//spring-framework.version=5.0.0
@MapToProperty
Map<String, Object> map=Collections.singletonMap("spring-framework.version","5.0.0");

//spring=boot
@MapToProperty("spring")
Optional<String> optional=Optional.of("boot");

//spring=boot
@MapToProperty("spring")
Supplier<String> supplier=()->"boot";

//spring-boot.version=2.0.0
@MapToProperty("spring-boot")
TestPropertyValues prefixValues=TestPropertyValues.of("version=2.0.0");

//spring-framework.version=5.0.0
@MapToProperty
TestPropertyValues values=TestPropertyValues.of("spring-framework.version=5.0.0");

```

`Callable` and `Supplier` will affect context caching. https://github.com/nosan/spring-boot/commit/ed8c6f491b6b9288b7d7abea50b17bdd77460724#diff-0922e2036023ec41bc38b06325940b9dR67

Please let me know what you think.

**Comment by antkorwin** [comment]
@nosan  
I think this looks like something which I proposed earlier in my PR #17030 , at least the implementation based on a similar way.

@wilkinsona  if you select this approach I will be glad to return working on this implementation. Thanks!

**Comment by nosan** [comment]
@antkorwin 
- My approach is based on **static final** fields with various types.
- `ContextFactoryCustomizer` cannot process properties because we have to be sure that the container's port is available before the context refreshes.

Consider the example:
```java
//if we change the order of the annotations then this test will fail
@Testcontainers
@DataNeo4jTest
class DataNeo4jTestIntegrationTests {

	@Container
	static final Neo4jContainer<?> neo4j = new Neo4jContainer<>();

	@DynamicTestProperty
	private static TestPropertyValues setContainerProperties() {
		return TestPropertyValues.of("spring.data.neo4j.uri=" + neo4j.getBoltUrl);
	}

	@Test
	void name() {

	}
}

```

That's why I've done everything in `ContextCustomizer` instead of `ContextCustomizerFactory`. The limitation of this approach is too difficult to implement right the `equals` and `hashCode` for `ContextCustomizer`.

**Comment by philwebb** [comment]
We discussed this again today briefly and came to the conclusion that we need more time to consider all the implications. Unfortunately, we're all pretty stacked up with Spring Boot 2.2 and Spring Framework 5.2 issues so it's going to have to wait until those releases are done.

We also want to discuss with the Framework team to see if such a feature would make more sense in `spring-test`. Since there's already a `@TestPropertySource` annotation, it might be nice if it could be used on a static method (similar to @bsideup's suggestion):

```java
@Testcontainers
@DataRedisTest
public static MyTest {

    @Container
    public static RedisContainer redis = new RedisContainer();

    @TestPropertySource
    static PropertySource propertySource() {
        return TestPropertyValues.of(
            "spring.redis.host=" + redis.getContainerIpAddress(),
            "spring.redis.port=" + redis.getMappedPort()
        );
    }

}
``` 

We'd of course need to check that the `@Container` is setup before the `propertySource()` method is invoked.

We'll try to talk about these ideas at Spring One. There won't be any decisions until then I'm afraid.

**Comment by antkorwin** [comment]
@nosan, annotation ordering  it's a good point,

I fixed a problem with the order of junit5 extensions, but we aren't able to evaluate value of dynamic properties before run context customizer, this can lead to reset a test context cache even if the test cases used the same properties in the dynamic property provider(property contributor) method. 

For example, if we use the dynamic property in the parent abstract class:

```java
public abstract class ParentTest {

	@DynamicTestProperty
	private static TestPropertyValues parentProperties(){
		return TestPropertyValues.of("key=123");
	}
}
```

and extend this class in multiple tests:

```java
@SpringBootTest
class FirstChildTest extends ParentTest {

	@Value("${key}")
	private String key;

	@Test
	void dynamicPropertyFromSuperClass() {
		assertThat(key).isEqualTo("123");
	}
}

@SpringBootTest
class SecondChildTest extends ParentTest {

	@Value("${key}")
	private String key;

	@Test
	void dynamicPropertyFromSuperClass() {
		assertThat(key).isEqualTo("123");
	}
}
```

to avoid running a new application context, in this case, I check the equals of method references of dynamic property provider in  `DynamicTestPropertyContextCustomizer`, and context caching works fine. 

However in some cases, when a property has the same values but defined by different methods, this will bring to creating a new context in the cache, maybe it will be a limitation of this feature. 

I updated my variant of implementation here: https://github.com/spring-projects/spring-boot/compare/master...antkorwin:add-dynamic-test-property

By the way, I can't use the `TestPropertySource` annotation to define a dynamic property because this annotation has a target level `TYPE`. This requires making changes in the Spring Framework.

I hope it will be useful..

**Comment by wilkinsona** [comment]
Following a chat with @sbrannen, I've opened https://github.com/spring-projects/spring-framework/issues/24540 to track this on the Framework side.

**Comment by philwebb** [comment]
The framework issue has now been fixed and you can define dynamic properties as follows:

```java
@DynamicPropertySource
static void containerProperties(DynamicPropertyRegistry registry) {
	registry.add("test.container.ip", container::getIpAddress);
	registry.add("test.container.port", container::getPort);
}
```

We'll use this issue to convert our own tests and add some documentation.

**Comment by wilkinsona** [comment]
I'm not sure how much of a documentation update when need in Boot. The new functionality is now described in [Framework's documentation](https://docs.spring.io/spring/docs/5.2.5.RELEASE/spring-framework-reference/testing.html#testcontext-ctx-management-dynamic-property-sources). Usage in Spring Boot would be identical other than replacing `@SpringJUnitConfig(/* ... */)` with, most likely, `@SpringBootTest`.

I think we should update our tests to use the new functionality. We can do that in 2.2.x.

**Comment by wilkinsona** [comment]
Closing in favour of #20676.
