### ISSUE TITLE
Serve static resource using starter

### ISSUE THREAD

**Issue by dyachkov** [spring-projects/spring-boot#16896]
Hi!

Is it possible to serve the static resources (for example static web-page) using starter? For example, I've created starter, containing controller `/hello/` and want to return some static `index.html` page from it. In another project I've just added that starter as dependency but for understandable reasons I got error when tried `localhost:8080/hello`:
java.lang.IllegalStateException: Could not resolve view with name 'index'.

Are there any workarounds? Or that `index.html` should be in the __depended__ project. If so, are there any alternatives to provide static resources using starter?

Thanks.

**Comment by dyachkov** [comment]
Alright, everything is fine, static resources are in the dependent app classpath. Could be closed.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
