### ISSUE TITLE
Can not pull spring-boot 2.2.0.M3 from central repo.

### ISSUE THREAD

**Issue by QilongZhang** [spring-projects/spring-boot#16890]
i cant see spring-boot 2.2.0.M3 in [central repo](http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-parent/)，how can i pull it via some maven config?

**Comment by lzysuqianqiu** [comment]
you should add spring milestones repositoty

**Comment by QilongZhang** [comment]
> you should add spring milestones repositoty

yes, i guess maybe exists a milestones repository, but i do not know what is it. Can you provide it to me ?

**Comment by lzysuqianqiu** [comment]
<repositories>
        <repository>
            <id>spring-snapshots</id>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <url>https://repo.spring.io/milestone</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-snapshots</id>
            <url>https://repo.spring.io/snapshot</url>
        </pluginRepository>
        <pluginRepository>
            <id>spring-milestones</id>
            <url>https://repo.spring.io/milestone</url>
        </pluginRepository>
    </pluginRepositories>

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
