### ISSUE TITLE
Migrate remaining tests to JUnit 5 where possible

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16942]

**Comment by HaydenMeloche** [comment]
Hey @wilkinsona, I can might be able to tackle this. Is their anything specific to this besides removing all junit4 references and replacing them with their junit5 counterparts?

**Comment by philwebb** [comment]
@HaydenMeloche Unfortunately there's a few things blocking us from migrating entirely. We have a few JUnit 4 specific classes that we need to replace before we can really continue. I think @wilkinsona was planning to look `ModifiedClassPathRunner` first.

**Comment by wilkinsona** [comment]
I was indeed. I made a start yesterday, in fact. I've assigned this issue to me now. Sorry for the confusion.

**Comment by sbrannen** [comment]
@wilkinsona, the new `InvocationInterceptor` extension API coming in JUnit Jupiter 5.5 may actually be sufficient to port the functionality of `ModifiedClassPathRunner` to JUnit Jupiter.

Since JUnit Jupiter 5.5 will most likely be released in time for inclusion in Spring Boot 2.2, you may wish to give the porting a shot now with 5.5 snapshots or the upcoming 5.5 RC1.

If you need any assistance, just let me know.

/cc @marcphilipp

**Comment by wilkinsona** [comment]
Closed by b18fffaf14f9ce3e5651f44745019890e8a899c2.
