### ISSUE TITLE
Provide property to control ConfigureRedisAction

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#16943]
See [Spring Session docs](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-sessiondestroyedevent) and https://github.com/spring-projects/spring-session/issues/124#issuecomment-71490616

Adding a switch for this in `RedisProperties` would be very useful.

**Comment by philwebb** [comment]
I don't think we should add a property to `RedisProperties` since `ConfigureRedisAction` is specific to Spring Session. I think `SessionProperties` would be a better place, probably under a `redis` specific name. Something like `spring.session.redis.configure=` with `NOTIFY_KEYSPACE_EVENTS` and `NONE` as enum options.

We should also make sure that the user can register their own `ConfigureRedisAction` bean if they need to.

**Comment by izeye** [comment]
This seems resolved via #17022.

**Comment by wilkinsona** [comment]
Thank you, @izeye.
