### ISSUE TITLE
Provide a JUnit 5 equivalent of ModifiedClassPathRunner

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16957]
We need this as part of [completing our migration to JUnit 5](/spring-projects/spring-boot/issues/16942). Unfortunately, it isn't possible at the moment. https://github.com/junit-team/junit5/issues/201 is required and there may be some other changes that are needed as well.

**Comment by sbrannen** [comment]
@wilkinsona, the new `InvocationInterceptor` extension API coming in JUnit Jupiter 5.5 may actually be sufficient to port the functionality of `ModifiedClassPathRunner` to JUnit Jupiter.

Since JUnit Jupiter 5.5 will most likely be released in time for inclusion in Spring Boot 2.2, you may wish to give the porting a shot now with 5.5 snapshots or the upcoming 5.5 RC1.

If you need any assistance, just let me know.

/cc @marcphilipp

**Comment by wilkinsona** [comment]
Thanks for the pointer, @sbrannen. Reading through [the commit](https://github.com/junit-team/junit5/commit/bb795075870ca1cd988d93fb359a500c72c0e67f) that introduced the new extension point, I'm struggling to see how it will help with implementing a `ModifiedClassPathRunner` replacement.

A replacement for `ModifiedClassPathRunner` requires the ability to load the test class using a custom class loader. I can't see how that can be achieved with the interception points that are offered and the requirement to always call `proceed` on the given `Invocation`. For example, even without the `proceed` requirement, the signature of `interceptTestClassConstructor` seems to prevents me from loading the test class using a new class loader and returning an instance of it.

What have I missed?

**Comment by sbrannen** [comment]
> What have I missed?

I don't think you overlooked anything.

I overlooked the fact that `ModifiedClassPathTestClass` loads the actual test class by name via the custom `ClassLoader`:

https://github.com/spring-projects/spring-boot/blob/e06325e0296eb2c3d9a762fafa9dfa90117d47cf/spring-boot-project/spring-boot-tools/spring-boot-test-support/src/main/java/org/springframework/boot/testsupport/runner/classpath/ModifiedClassPathRunner.java#L287

At a first pass through the code (viewing it in the browser), it appeared that only the TCCL was being set and reset, which should be achieveable via the new interceptor extension API.

Sorry for the confusion.

You'll indeed have to wait for custom `ClassLoader` support in JUnit Jupiter in order to implement a `ModifiedClassPathRunner` replacement.

**Comment by wilkinsona** [comment]
Closing in favour of #17491.
