### ISSUE TITLE
ConfigurationProperties is override twice in SpringRunner test

### ISSUE THREAD

**Issue by lucasvc** [spring-projects/spring-boot#16982]
Having a _properties_ bean with annotations

```
@Configuration
@PropertySource("classpath:my-module-fancy.properties")
@ConfigurationProperties(prefix = "fancy")
```

When used in a `SpringRunner` test, its values get override twice, even other `@Configration` tries to change the value, it is read again from file before injecting it somewhere else.

This github repo reproduces the issue: [`spring-configurationproperties-overriden-twice`](https://github.com/lucasvc/spring-configurationproperties-overriden-twice).
It happens with spring-boot versions **1.5.20.RELEASE** and **2.1.5.RELEASE**.

**Comment by wilkinsona** [comment]
`FancyProperties` is bound twice as you have exposed it twice as a bean: once via `@Import(FancyProperties)` and once via your `properties` `@Bean` method. As far as Spring Framework is concerned, these a two separate beans (even though you have chosen to reuse the same instance) so post-processing occurs twice and, therefore, configuration property binding occurs twice.

Generally speaking, if you want to modify a bean that's being created elsewhere, that modification should be done using a `BeanPostProcessor`. Your test will pass if you replace your `properties` bean with the following:

```java
@Bean
public static BeanPostProcessor propertiesOverride() {
    return new BeanPostProcessor() {

        @Override
        public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
            return bean;
        }

        @Override
        public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
            if (bean instanceof FancyProperties) {
                ((FancyProperties)bean).getMore().setHowMuch(rule.getCurrent());
            }
            return bean;
        }
        
    };
}
```

Unrelated to your problem, but there are a couple of other unusual things in your sample that you may want to correct:

1. `ReadFancy` is not a configuration class (it has no `@Bean` methods) so it should probably be annotated with `@Component` rather than `@Configuration`.
2. `FancyProperties` is not a configuration class (it has no `@Bean` methods) so `@Configuration` should probably be removed. It can then be switched on via `@EnableConfigurationProperties(FancyProperties.class)`.

**Comment by lucasvc** [comment]
Really thanks for your fast answer @wilkinsona.
Worked like a charm, and makes a lot of sense :)

And thanks for your comment on the _unusual things_, even both classes are part of a bigger project with more code I skipped for the sample, they have helped me to learn a little bit Spring 💋
