### ISSUE TITLE
@Validated don't work on interface

### ISSUE THREAD

**Issue by longscoop** [spring-projects/spring-boot#17000]
Springcloud is used in the project, but returns 404

```java
@Validated
public interface ValidClient {

	@GetMapping("/valid")
	String queryById(@RequestParam("id") @Min(1) @Max(400) Integer id);

}
```

```java
@RestController
public class ValidController implements ValidClient {

	@Override
	public String queryById(@Min(1) @Max(400) Integer id) {
		return "id:" + id;
	}
}
```

Springcloud is used in the project, but returns 404，the Validated don't work on interface ?

**Comment by wilkinsona** [comment]
For the record, `@Validated` should work on interfaces, however, from the information provided, I don't think this has anything to do with `@Validated`. If you are getting a 404 response, your controller method hasn't been called so the point where validation would have been performed will not have been reached.

Since Spring Framework 5.1, request mappings should be found on interfaces due to the changes made in https://github.com/spring-projects/spring-framework/issues/15682. Perhaps you are using a version of Spring Boot that uses Spring Framework 5.0 or earlier?

If you'd like us to spend any more time on this, you'll need to spend some time providing some more information about your problem. Please create a minimal sample that reproduces your problem and share it in a separate GitHub repository or in a zip attached to this issue.

**Comment by longscoop** [comment]
hi @wilkinsona  ,I add GitHub repository  use spring boot 2.1
[](https://github.com/longscoop/spring-boot-validated)

**Comment by longscoop** [comment]
this is GitHub repository  https://github.com/longscoop/spring-boot-validated

**Comment by wilkinsona** [comment]
Thanks for the sample.

The problem is caused by your validation configuration, specifically the `MethodValidationPostProcessor`. `@Validated` beans are proxied so that calls to their methods can be intercepted and validation performed. The configuration of `MethodValidationPostProcessor` determines the type of proxy that is created. Spring Boot's default configuration is to use CGLib proxies all the time. Your configuration results in a JDK-based proxy being used if the validated class implements a single interface. That is the case with your `ValidController` class. A limitation of JDK-based proxies is that annotation information is lost. As a result your `ValidController` is not identified as a `@RestController` so its `@RequestMapping` is ignored and you get a 404 when trying to call it.

You can fix the problem by removing your `@Bean` method for `MethodValidationPostProcessor` and using the auto-configured post-processor instead. Alternatively, you can call `setProxyTargetClass(true)` on your post-processor definition so that it always creates CGLib-based proxies.
