### ISSUE TITLE
springboot project start failure

### ISSUE THREAD

**Issue by ppamos** [spring-projects/spring-boot#17042]

**Comment by ppamos** [comment]
when i start springboot project，it ok .but i can not login in  my Bowser   why?   
![image](https://user-images.githubusercontent.com/48974977/58750849-ad29c700-84c9-11e9-90ba-6ce158e78904.png)
![image](https://user-images.githubusercontent.com/48974977/58750864-cb8fc280-84c9-11e9-8157-9d96a260af27.png)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by ppamos** [comment]
![image](https://user-images.githubusercontent.com/48974977/58751166-a3a25e00-84cd-11e9-97d9-67e2399192af.png)
