### ISSUE TITLE
default User-Agent header to map to spring.application.name

### ISSUE THREAD

**Issue by ckoutsouridis** [spring-projects/spring-boot#17041]
Whether using RestTemplate or WebClientBuilder, would it make sense to use as default `User-Agent` header the value of `spring.application.name`? 

At the moment i am using a "custom" `RestTemplateCustomizer` that is injecting this header. for `RestTemplate` and `defaultHeaders` method for `WebClientBuilder`, but i think it makes sense for the `User-Agent` to be set to `spring.application.name` by default.

**Comment by knoobie** [comment]
That sounds more like a feature, you **don't** want to have enabled as default. (Information disclosure)

**Comment by ckoutsouridis** [comment]
i can understand the information disclosure argument, but it's not that it's empty currently. Depending on the actual http client used, it can be either the JRE version or something like "apache-http-components" which in my opinion is worse than the application name.

If not by default, It would be nice to be able to set/enable via a property.

**Comment by wilkinsona** [comment]
Thanks for the suggestion.

I don't think we should set the `User-Agent` header in HTTP requests to the value of `spring.application.name` by default. While information disclosure is less of a concern for a client, I don't think there's really any good default for `User-Agent`. For example, GitHub encourages you to use your GitHub user id or name of the application as registered with GitHub so that they have a means of contacting you should they identify a problem. Neither of those is likely to have the same value as `spring.application.name`.

I'm less sure about providing a property to enable the behaviour. However, I'm leaning towards it not being worth it as I doubt it would be all that widely used. Furthermore, `WebClient` already provides a nice API for setting default headers via its `Builder` and its `defaultHeader` or `defaultHeaders`. Things aren't quite so straightforward with `RestTemplate`. That could perhaps by tackled via our `RestTemplateBuilder` if we thought it would be of sufficient value.

Let's see what the rest of the team thinks.

**Comment by snicoll** [comment]
`WebClient.Builder` has a `defaultHeader` and adding a similar feature to `RestTemplateBuilder` could be interesting indeed. I don't think we should have a property for this either.

**Comment by philwebb** [comment]
After some discussion we feel like using `spring.application.name` or offering a dedicated property isn't the right approach. Instead, we've opened #17072 to look at adding convenience to `RestTemplateBuilder`.
