### ISSUE TITLE
Dynamic Code Evaluation: Unsafe Deserialization (Spring Boot 2) - how to avoid actuator related fortify issue, or is it a false positive?

### ISSUE THREAD

**Issue by dongdongqin** [spring-projects/spring-boot#17137]
Dynamic Code Evaluation: Unsafe Deserialization (Spring Boot 2) - how to avoid actuator related fortify issue, or is it a false positive?
how to avoid this problem?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by wilkinsona** [comment]
Before posting your own question on Stack Overflow, you may be interested in [this existing question](https://stackoverflow.com/questions/52945590/dynamic-code-evaluation-unsafe-deserialization-spring-boot-2-how-to-avoid-a).

**Comment by dongdongqin** [comment]
thanks for your quick response, i try all kinds of solution. it does not work.  fortify is our standard for software safe. Thus, i try to see the answers from official sites.   It also maybe fortify problems, not actuator problem. thaks again!

**Comment by hungvu2000** [comment]
Hi dongdongqin,

Have you found the solution? I have the same issue but don't know how to fix it.

Thanks and Regards,
Hung Vu
