### ISSUE TITLE
Is it possible to configure log4j2 properties in application.yml?

### ISSUE THREAD

**Issue by mraible** [spring-projects/spring-boot#1717]
Is it possible to put placeholders in log4j2.xml that can be read from application.yml? For example, I'd like to configure to/from addresses, as well as host and port in application.yml:

    <SMTP name="Mail" subject="Error (${hostName})" to="${app.alerts.to}" from="${app.alerts.from}"
    		smtpHost="${mail.host}" smtpPort="${mail.port}" bufferSize="50">
    	<ThresholdFilter level="debug" onMatch="NEUTRAL" onMismatch="DENY" />
    	<PatternLayout>
    		<pattern>%d{dd-MM-yyyy HH:mm:ss,SSS} %5p %m%n</pattern>
    	</PatternLayout>
    </SMTP>

If it's possible to enable/disable this appender based on Spring Profiles (like [this logback example](http://maciejwalkowiak.pl/blog/2012/04/03/application-errors-notification-with-logback/)), I'd love to hear about that too.

**Comment by deepika087** [comment]
Is it now possible to pass custom configs to log4j2 via application.properties ?

**Comment by wilkinsona** [comment]
@deepika087 No, not at the moment (this issue is still open). It is [possible if you use Logback](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-logback-extensions) (Boot's preferred logging framework).

**Comment by kbjp2** [comment]
Same requirement here as well:
I would like to re-use the (encrypted) data-source properties defined in my application.yml to create a JDBC appender through log4j2-spring.xml place-holders. This works fine for logback but I would prefer to use log4j2 because of its better support of asynchronous logging.

**Comment by philwebb** [comment]
We've no plans to support this. Consider using logback or submitting a pull request.

**Comment by wilkinsona** [comment]
Are you referring to [this comment](https://github.com/spring-projects/spring-boot/issues/1717#issuecomment-204975869)? If so, the issue that I was referring to is this issue, not a Log4j issue.

**Comment by thekalinga** [comment]
Ok. Thanks

**Comment by thekalinga** [comment]
There seems to be a **Epic** open against log4j2 for supporting dependency management.

https://issues.apache.org/jira/browse/LOG4J2-1775

As of now, plugins are initialised by log4j2 itself & there is no straight forward way to inject into custom `StrLookup` class. Log4j2 expects the custom plugin that implements `StrLookup` to have no args constructor & there are no additional ways to refer to application context, except using static variables to hold a reference to `Environment` when we receive `ApplicationEnvironmentPreparedEvent`

@wilkinsona If we capture a a static reference to `ConfigurableEnvironment` during `ApplicationEnvironmentPreparedEvent`, can u please let me know if my understanding is correct

1. Do we need to get fresh reference to `ConfigurableEnvironment`, when context is restarted via Spring boot actuator? If I have to, which API should I hook into to get a callback?
2. Do we need to get fresh reference to `ConfigurableEnvironment`, when some properties are updated via Spring cloud bus/actuator? If I have to, which API should I hook into to get a callback?
3. Dereference `ConfigurableEnvironment` during shut down, so that there will not be any memory leaks. If so, which API should I hook into to get a callback?

Thanks again

**Comment by philwebb** [comment]
> Do we need to get fresh reference to ConfigurableEnvironment, when context is restarted via Spring boot actuator? If I have to, which API should I hook into to get a callback?

There's no actuator endpoint provided by Spring Boot to trigger a restart. Perhaps this is a Spring Cloud feature? Regardless, you'd get a new `ApplicationEnvironmentPreparedEvent`.

> Do we need to get fresh reference to ConfigurableEnvironment, when some properties are updated via Spring cloud bus/actuator? If I have to, which API should I hook into to get a callback?

No I don't think so. The `ConfigurableEnvironment` is not itself replaced, only the `PropertySources` that it contains.

> Dereference ConfigurableEnvironment during shut down, so that there will not be any memory leaks. If so, which API should I hook into to get a callback?

Shutdown might be tricky. You might be able to use `ContextStoppedEvent`, but if you just need to protect against memory leaks perhaps using a weak reference to the environment would be enough.

**Comment by thekalinga** [comment]
@philwebb Thanks. I'll give it a try

**Comment by RameshNaiduN** [comment]
Please unsubscribe these mails
    On Tuesday, 27 March, 2018, 2:09:10 PM IST, Ashok Koyi <notifications@github.com> wrote:  
 
 
@philwebb Thanks. I'll give it a try

**Comment by wilkinsona** [comment]
@RameshNaiduN Only you can do that. You need to unsubscribe from this issue and possibly unwatch this repository as well.
