### ISSUE TITLE
AnonymousUserIdSourceConfig returns same userID for all anonymous users.

### ISSUE THREAD

**Issue by NLxAROSA** [spring-projects/spring-boot#1728]
Returns "anonymous" as the userId. This value is returned for all anonymous users. If the UserIdSource is not overridden, this will lead to Connections for different (anonymous) users being assigned to the same userId, ultimately allowing one user to view or even manipulate social profile data of others.

Initially found this while testing spring-social-facebook and spring-social-twitter sample applications. Reproduction path with using either of the sample applications: open two separate browsers (both with cleared history), log in in one and you will also be logged in in the other.

**Comment by habuma** [comment]
The short answer here is that the work for Spring Social's auto-configuration was a starting point and due to higher priority work it was never completed. That said, even before my attention was drawn to these comments, I had set aside this week to work on Spring Social auto-configuration. Hopefully I'll have a better answer for you by the end of the week.

**Comment by habuma** [comment]
Following up: Put simply, the default is, as you stated, to use "anonymous" as the user ID. I acknowledge that this is not ideal, but it represents the easiest thing you can possibly do to get started with Spring Social and Spring Boot. You'll definitely want to override it for any real application.

That said, I've tinkered with a session ID-based user ID source:

```java
@Configuration
public class SocialConfig extends SocialConfigurerAdapter {
	
	@Override
	public UserIdSource getUserIdSource() {
		return new SessionIdUserIdSource();
	}
	
	private static final class SessionIdUserIdSource implements UserIdSource {
		@Override
		public String getUserId() {
			return RequestContextHolder.currentRequestAttributes().getSessionId();
		}
	}
}
```

This works pretty well and I'm considering (1) adding it as the default for auto-configuration and (2) adding SessionIdUserIdSource as an out-of-the-box UserIdSource implementation in Spring Social itself. WDYT?

**Comment by NLxAROSA** [comment]
SessionId will be enough for simple cases, but it's not unique enough to be used to identify a user, especially if it's persisted somewhere in a connection database and subsequently reused (session ids can/will be reused on restarts, different VMs, etc.). UUID would be safest IMO.

**Comment by habuma** [comment]
@NLxAROSA Agreed that it's not unique enough to identify a user. But short of any other information, it's the best you can do by default from auto-configuration. Most likely, you'll need to override it. It's the same balance that Spring Security auto-configuration walks between getting something up and running quickly vs. something that you really want to use in production. 

(Re. Spring Security auto-configuration: Do you really want to secure your app with HTTP Basic authentication and a randomly generated password for a user named "user"? Probably not. But it's a good starting point and you can override to meet your app's specific needs.)

Identifying a user will require integration with the application's security mechanism. The auto-configuration already offers two options: (1) If Spring Security is available--triggered by detecting SecurityContextHolder--then it will use that. (2) If Spring Security is not available, then it will use the session ID strategy. The following snippet is from the auto-configuration that makes that decision (note that the session ID strategy is not yet part of Spring Boot, but is what I'm working with locally right now):

```java
	@Configuration
	@EnableSocial
	@ConditionalOnWebApplication
	@ConditionalOnMissingClass("org.springframework.security.core.context.SecurityContextHolder")
	protected static class SessionUserIdSourceConfig extends SocialConfigurerAdapter {

		@Override
		public UserIdSource getUserIdSource() {
			return new UserIdSource() {
				@Override
				public String getUserId() {
					return RequestContextHolder.currentRequestAttributes().getSessionId();
				}
			};
		}
	}

	@Configuration
	@EnableSocial
	@ConditionalOnWebApplication
	@ConditionalOnClass(SecurityContextHolder.class)
	protected static class AuthenticationUserIdSourceConfig extends
			SocialConfigurerAdapter {

		@Override
		public UserIdSource getUserIdSource() {
			return new SecurityContextUserIdSource();
		}

	}
```

If the application is using any other security mechanism, then it will be up to the developer to plug in their own implementation of UserIdSource--there's no way that we can auto-configure a security mechanism we don't know anything about. 

UUID is an interesting idea. I'll give it some thought. But considering that the session ID strategy is only intended as a default for lack of a real user ID strategy (the JavaDoc should probably make that clear), I'm not sure if it's strictly necessary.

**Comment by habuma** [comment]
The problem with UUID is that I can either create on randomly or create one from a set of bytes.

If I create it from a set of bytes, what bytes should I use that will be the same for the user the next time they use the app? Knee-jerk answer is that I call .getBytes() on the session ID or on some known user ID, but how would that be better than just using the session ID or some known user ID in the first place? 

If I create a random UUID, then I need a place to stow it in between requests so that I don't generate a different UUID for the same user on the next request. Where can I store it? In the session? So the same user could come back later with a different session and have to start all over? I suppose this is still better than using the session ID (which could be recycled later) because even if the session is recycled, the UUID would still be unique. 

For discussion's sake, here's what I've tried...and it works...but obviously the UUID is only good as long as the session is alive:

```java
		@Override
		public String getUserId() {
			RequestAttributes request = RequestContextHolder.currentRequestAttributes();
			String uuid = (String) request.getAttribute("_socialUserUUID", RequestAttributes.SCOPE_SESSION);
			if (uuid == null) {
				uuid = UUID.randomUUID().toString();
				request.setAttribute("_socialUserUUID", uuid, RequestAttributes.SCOPE_SESSION);
			}
			return uuid;
		}
```

At any rate, I'm still of the opinion that the UUID strategy is not intended as anything more than a quick-start option that you'll certainly want to override with a different UserIdSource implementation that's appropriate for your application's security mechanism.

But I'm open to discussion in the matter if anyone has any insight here.

**Comment by NLxAROSA** [comment]
I think this is the best solution. It's secure enough in the case a developer does not provide an own implementation. Also I'm not worried about anonymous users not getting their info back after they lost/switched the session. They should either login (not be anonymous) or a developer should implement some own tracking mechanism that does not require login.
