### ISSUE TITLE
Throwing exception when having multiple `application-*.yml|properties` and `spring.profiles.active` is not set

### ISSUE THREAD

**Issue by akuma8** [spring-projects/spring-boot#17302]
Is it possible to throw an exception at start up when having multiple `application-{profile}.yml|properties` and the property `spring.profiles.active` is not set? I lost 1 hour to understand why my app refused to start, I just forgot to set the desired profile at startup. 
Thanks

**Comment by mbhave** [comment]
We do log the active profiles when the application starts up. For example, if the dev profile is active, you'll see the following in the logs:

`The following profiles are active: dev`

If no profile is active, this is logged:
`No active profile set, falling back to default profiles: default`.

I don't think we can throw an exception because `spring.profile.active` decides if the profile specific file should be processed or not. Having the profile-specific file and not having the profile in the list of active profiles is a valid use-case.

**Comment by akuma8** [comment]
Thanks for pointing out this. In my case: `No active profile set, falling back to default profiles: default` doesn't appear and the application failed to start too quickly. I had to breakpoint here [ClasspathLoggingApplicationListener#onApplicationEvent(ApplicationEvent event)](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/logging/ClasspathLoggingApplicationListener.java#L54) to understand that I have some properties required by some beans and those properties wasn't defined in the default `application.properties`. What is srange is we have any error message for this situation.
