### ISSUE TITLE
@ConditionalOnBean seems to have a bug

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#17300]
I have three annotated beans. I want ConfigB to be created when ConfigC is created, but ConfigB is still created when ConfigC is not created.
Please take a look at my demo. https://github.com/brucelwl/demo

**Comment by philwebb** [comment]
You cannot use `@ConditionalOnBean` on regular condition classes since the ordering is not defined. See [this section of the Javadoc](https://github.com/spring-projects/spring-boot/blob/7405efa326773a69bfc71a06a31d51a9781eb98e/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnBean.java#L53-L56).

**Comment by brucelwl** [comment]
@philwebb Why not judge whether conditional beans are valid beans? verify dependent beans first, as method getBean()

**Comment by philwebb** [comment]
@brucelwl We can't call `getBean()` during the condition evaluation because it will cause early bean instantiation. We must work only with the `BeanDefinition`. The `@ConditionalOnBean` is designed to serve our very specific auto-configuration use-case and I'm afraid we're not going to be able to make it more generally applicable.

**Comment by brucelwl** [comment]
@philwebb Yes, I know that We can't call getBean() during the condition evaluation, I mean, we can recursively verify that the BeanDefinition on which it depends is valid. This principle is the same as getBean (), so we don't have to deal with the sorting problem

**Comment by philwebb** [comment]
@brucelwl I'm afraid I don't really have time to discuss all the details, but we can't reliably determine all the dependencies of a bean until it's created. For example, a `@Bean` method may call another `@Bean` method, or it may interact with the `ApplicationContext` directly. That's why we have `@AutoConfigureBefore` and `@AutoConfigureAfter` annotations in Spring Boot and why we only recommend using `@ConditionalOnBean` in auto-configuration classes.
