### ISSUE TITLE
How to build a jar package like war deploy，just publish jar

### ISSUE THREAD

**Issue by evilThought** [spring-projects/spring-boot#17380]
I want deploy project just upgrade the jar package(the jar package  just only include the code class exclude static resources, dependencies lib jars and properties file.)

I have a spring boot project need to deploy a service on the Linux IOS.
When I Use Spring Boot Maven Plugin(spring-boot-maven-plugin) build project, the jar package was include static resources and dependencies jars, But I want package just only include the code class exclude static resources, dependencies jars and properties file.
So that，How to build only include the code class jar package, But the deployment step looks like Unix/Linux Services chapter (https://docs.spring.io/spring-boot/docs/2.1.6.RELEASE/reference/htmlsingle/#deployment-service)

Thanks

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
