### ISSUE TITLE
When project of spring-boot deploy by WAR,how can i set up this context path at application.yml

### ISSUE THREAD

**Issue by Racooooooon** [spring-projects/spring-boot#17423]
I have a spring-boot project deploy by WAR,and the application.yml is:
`server:`
    `port: 8004`
    `context-path: /appuser`
but its not work.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
