### ISSUE TITLE
Support # in addition to -- as a default comment prefix for Quartz DataSource initialization

### ISSUE THREAD

**Issue by abccbaandy** [spring-projects/spring-boot#17435]
spring boot version : 2.1.6.RELEASE
spring-boot-starter-quartz

https://github.com/quartz-scheduler/quartz/issues/262#issue-361985218

maybe `spring.quartz.jdbc.comment-prefix=#` should be default?

**Comment by wilkinsona** [comment]
The comment prefix is set to `--` by default. We can’t change it to `#` as that will be a breaking change for those relying on it being `--`. If you require a different comment prefix you will have to configure it. Please see #13160 and #13041 for details.

That said, I wonder if we can do better here. Perhaps we could automatically use a different comment prefix based on the database that is being used.

**Comment by philwebb** [comment]
I think we also have the same problem with `DataSourceInitializer`, although it looks like we don't offer a property for `setCommentPrefix` there.

**Comment by wilkinsona** [comment]
A small difference between the two is that the scripts used by `DataSourceInitializer` are typically written by the user and are only intended to be consumed by Boot rather than also by the database itself. That means they can use `--` (the SQL standard) and it should always work.

In the Quartz case, the scripts are out of the users control and were, I imagine, primarily written to be read by the database itself rather than a tool like Boot's DataSource initialization. This is not to say that there's no problem with `DataSourceInitializer`, but I do think it's less likely to be problematic.

**Comment by philwebb** [comment]
I've submitted a PR to framework that will allow us to support both prefixes https://github.com/spring-projects/spring-framework/pull/23289
