### ISSUE TITLE
spring boot doesnot read my yml file

### ISSUE THREAD

**Issue by YanChuanRui** [spring-projects/spring-boot#17438]
Env: Eclipse + sts
I new a Spring Starter Project, I choose `JDBC API, MS SQL Server Driver, Spring Web Starter`.

The first time it creates, errors like this:
Multiple annotations found at this line:
	- Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-resources-plugin:3.1.0:testResources (execution: default-testResources, 
	 phase: process-test-resources)
	- Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (execution: default-resources, phase: 
	 process-resources)

I ignore it.

I add resources in the pom file <project><build>,

        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.yml</include>
                </includes>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*.yml</include>
                </includes>
                <filtering>false</filtering>
            </resource>
        </resources>

Then I add SQL Server thing in src/main/resources/application.yml

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: xxx
    url: jdbc:sqlserver://localhost:1433;DatabaseName=msdb
    username: sa

but I run @SpringBootApplication, it give infos

Description:
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine a suitable driver class

Then I try another way, I create file DatasourceConfig.java, and code it

@Configuration
public class DatasourceConfig {
	@Bean
	public DataSource datasource() {
		return DataSourceBuilder.create().driverClassName("com.microsoft.sqlserver.jdbc.SQLServerDriver").url("jdbc:sqlserver://localhost:1433;DatabaseName=msdb").username("sa").password("xxx").build();
	}
}

and the it works.
I wonder why it can not read my yml file?(change yml to properties doesnot work.)
I wonder why it can not read my yml file?(change yml to properties doesnot work.)
I wonder why it can not read my yml file?(change yml to properties doesnot work.)

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by YanChuanRui** [comment]
I mentioned an error, every project, in pom, even newly created.

Multiple annotations found at this line:
- Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-resources-plugin:3.1.0:testResources (execution: default-testResources,
phase: process-test-resources)
- Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (execution: default-resources, phase:
process-resources)

Isnot this a bug or something

**Comment by wilkinsona** [comment]
Those error messages are produced by m2e in Eclipse and are out of Spring Boot’s control.

**Comment by philwebb** [comment]
@YanChuanRui This is most likely not a bug, it's probably because you added a `<resources>` section to your POM and your IDE is warning that it doesn't know how to deal with that. I suggest you delete those lines and put your `application.yml` in `src/main/resources` as suggested in our documentation. Further questions should be asked on stackoverflow.com.
