### ISSUE TITLE
TraceWebFluxAutoConfiguration fails on ConditionalOnWebApplication.REACTIVE

### ISSUE THREAD

**Issue by AnirudhaDesai** [spring-projects/spring-boot#17495]
**Affects:** \<5.1.5.RELEASE>

---

I need request tracing for a webflux service. We observed that `TraceWebFluxAutoConfiguration` which is responsible for enabling tracing to HTTP requests with Spring Webflux is not instantiated during application startup. The bean creation depends on the following conditions : 

@ConditionalOnProperty(value = "spring.sleuth.web.enabled", matchIfMissing = true)
@ConditionalOnWebApplication(type = ConditionalOnWebApplication.Type.REACTIVE)
@ConditionalOnBean(Tracing.class)
@AutoConfigureAfter(TraceWebAutoConfiguration.class)

On further debugging, it was found that @ConditionalOnWebApplication(type = ConditionalOnWebApplication.Type.REACTIVE) was failing. This can be observed  in `OnWebApplicationCondition` class.  The method `isReactiveWebApplication(context)` evaluates to `false`. For some reason, spring does not consider it to be a reactive web server. `context.getEnvironment()` returns StandardEnvironment when it should presumably be StandardReactiveWebEnvironment and `context.getResourceLoader()` returns AnnotationConfigApplicationContext when it should ideally be AnnotationConfigReactiveWebApplicationContext. 

Digging further, we found that `AbstractReactiveWebInitializer` creates a **non-reactive** AnnotationConfigApplicationContext. This appears to be a bug in spring webflux.  Since we use tomcat to start up spring, it uses `SpringServletContainerInitializer`. `SpringServletContainerInitializer` starts up `AbstractReactiveWebInitializer` because it is a webflux application. This, I assume, is correct. But `AbstractReactiveWebInitializer` creates a non-reactive `AnnotationConfigApplicationContext` which is not expected. This appears to be the issue.  

Versions Used:
1. org.springframework:spring-core:5.1.5.RELEASE 
2. org.springframework.boot:spring-boot-autoconfigure:2.1.3.RELEASE
3. org.springframework.boot:spring-boot-starter:2.1.3.RELEASE
4. org.springframework:spring-webflux:5.1.5.RELEASE
5. org.springframework.cloud:spring-cloud-sleuth-core:2.1.1.RELEASE

**Comment by bclozel** [comment]
Since you're referring to `AbstractReactiveWebInitializer` and you're mentioning "Since we use tomcat to start up spring", I assume that you're packaging your WebFlux application as WAR and using the Servlet container to bootstrap Spring Boot through `AbstractReactiveWebInitializer`.

As [mentioned in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html#howto-create-a-deployable-war-file), Spring Boot does not support WAR deployment for WebFlux applications - see #12455 for more details.

Spring Framework does support that use case, but you can't reuse Spring Boot infrastructure and especially auto-configuration conditions in that context and expect them to work. In order for this infrastructure to work, Spring Boot needs to make some assumptions and in charge of the bootstrapping process.

If I've misread this bug report, please reopen this issue and provide more information.
Thanks!

**Comment by AnirudhaDesai** [comment]
Thanks for the quick response! That helped. I am in fact deploying it as WAR.
