### ISSUE TITLE
version 2.2.0.M4 has issue with HATEOS and Swagger

### ISSUE THREAD

**Issue by jahidakhtargit** [spring-projects/spring-boot#17548]
Hi,
plugins {
	//id 'org.springframework.boot' version '2.2.0.M4'
	id 'org.springframework.boot' version '2.1.6.RELEASE'
	id 'java'
}

Springboot version 2.2.0.M4 has issue with HATEOS and SWAGGER. Both don't work together, lot of run time issues. When change to Springboot version 2.1.6.RELEASE, all the issues disappear.

**Comment by wilkinsona** [comment]
Thanks for the report but, unfortunately, "lot of run time issues" doesn't give us enough information to be able to help you. Can you please describe what those issues are in as much detail as possible, why you think the issues are in Spring Boot rather than Swagger or Spring HATEOAS, and, ideally, provide a minimal sample (either as a zip attached to this issue or in a separate repository) that reproduces the problem.

**Comment by jahidakhtargit** [comment]
Thanks a lot for your response. Actually had to break my head today because of some class loader issue. It's fixed now. The issue was with Swagger, looks like they have fixed in the latest version as below.
compile group: 'io.springfox', name: 'springfox-swagger2', version: '2.9.2'
compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.9.2'

Sorry for creating issue at the wrong place.  You can close the issue. Thanks a lot for your time.

**Comment by wilkinsona** [comment]
Thanks for letting us know.
