### ISSUE TITLE
How can i able to configure LdapTemplate before the ldap authentication starts

### ISSUE THREAD

**Issue by udit0612** [spring-projects/spring-boot#17564]
I am trying to build a multiple ldap "OU" based springboot application where i can get the 
the OU name at the run time through the header but spring security wont allow me to do so?

Can i able to dynamically change the LdapTemplate configuration before the Spring security authentication

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
