### ISSUE TITLE
Is there a way to use spring message brokers without Stompendpoints?

### ISSUE THREAD

**Issue by gdhanav** [spring-projects/spring-boot#17609]
We have a use case to create websocket server. Mobile clients will connect to this websocket server. However mobile clients such as ios & android doesn't have recommended stomp clients. We would like to create a Java websocket server. spring does support websockets but it's heavily coupled with STOMP. we like to use Spring message broker concept here but because of Stomp, we are struck now. Is there anyway to overcome this and enable Spring websocket without STOMP but with Spring message broker concept?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by gdhanav** [comment]
Thank you @wilkinsona . I have posted this question in stackoverflow yesterday.
https://stackoverflow.com/questions/57138290/is-there-a-way-to-use-spring-message-brokers-without-stompendpoints
As I have not received any advise or guidance, I reached out to git hub to get recommendations. Sure, will use stackoverflow.
