### ISSUE TITLE
Formatter conflicts with "Only one statement per line" checkstyle rule

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#17637]
I have the following code:

```java
try (Session session = this.driver.session();
		Transaction tx = session.beginTransaction()) {
		// Do something
}
```

Spring Java Format complains

```
 Formatting violations found in the following files:
 * /Users/msimons/Projects/spring-projects/spring-boot/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/neo4j/Neo4jDriverAutoConfigurationIntegrationTests.java

Run `spring-javaformat:apply` to fix.
```

Fix turns the snippet into

```java
try (Session session = this.driver.session(); Transaction tx = session.beginTransaction()) {
}
```

Checkstyle complains `OneStatementPerLine`.

I have no clue how to format the thing.

**Comment by snicoll** [comment]
@philwebb can you please transfer the issue to the `spring-javaformat` project?

**Comment by michael-simons** [comment]
There are examples where the formatter accepts this style.

`org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfigurationTests#onlyRegisteredOnceWhenThereIsAChildContext`

Difference here: The second autoclosable doesn't depend on the first.

**Comment by philwebb** [comment]
> can you please transfer the issue to the spring-javaformat project?

Apparently not! The GitHub UI doesn't seem to offer it to me. Perhaps it's because it's part of a different organization. I'll do a brute force copy paste.

We actually hit it ourselves (see [this comment](https://github.com/spring-io/spring-javaformat/issues/113#issuecomment-505375432)) and in the end decided that fixing it would take more effort than refactoring the code to use multiple try blocks.

@michael-simons can you use the following form for now?

```java
try (Session session = this.driver.session()) {
    try (Transaction tx = session.beginTransaction()) {
        // Do something
    }
}
```

**Comment by philwebb** [comment]
https://github.com/spring-io/spring-javaformat/issues/136

**Comment by michael-simons** [comment]
> michael-simons can you use the following form for now?

Of course.
