### ISSUE TITLE
How to customise the actuator endpoint id in spring boot 2?

### ISSUE THREAD

**Issue by madhusudhannsn** [spring-projects/spring-boot#17749]
I am trying to upgrade my spring boot apps from 1.5 to 2.1. With boot 1.5, I was able to customise the actuator endpoint id using following

`endpoints.beans.id=springbeans`

https://docs.spring.io/spring-boot/docs/1.5.19.RELEASE/reference/html/production-ready-endpoints.html#production-ready-customizing-endpoints

But I don't see the customisation of the endpoint in spring boot 2 docs. With Spring boot 2, Is there a way that I can  customise the actuator endpoint ids for my actuator endpoints?

**Comment by philwebb** [comment]
I'm afraid this isn't a bug but rather an intentional decision since the ID is now referenced when exposing endpoints.

If you were previously changing it because you wanted to expose it under a different URL you might want to look at the `management.endpoints.web.path-mapping` property as [documented here.](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-customizing-management-server-context-path)

**Comment by philwebb** [comment]
I'll close this one for now, but if there's a specific use-case that we've missed please comment with some more details.
