### ISSUE TITLE
it is get old data when i use @@   get variable in pom.xml,  i think about  this has cache. right?

### ISSUE THREAD

**Issue by FreyJiang** [spring-projects/spring-boot#17747]

**Comment by FreyJiang** [comment]
Eg:<zookeeper.address>aaaa:2181<zookeepe.address/>  old
<zookeeper.address>bbbb:2181<zookeepe.address/>  old
In properties:
zookeeper.address=@zookeeper.address@(this value vill aaaa.2181)

**Comment by mbhave** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by inside-the-sandbox** [comment]
Have you rebuilt the Maven project? Also, checkout the docs: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html
