### ISSUE TITLE
Main server ResourceConfigCustomizers should not apply to management context

### ISSUE THREAD

**Issue by raphw** [spring-projects/spring-boot#17801]
Any `ResourceConfigCustomizer` bean is applied within the `JerseyAutoConfiguration` but also in the `JerseyManagementContextConfiguration`. It is not currently possible to exclude the bean's application in the management context. This can be a relevant problem if the management server runs on a different port.

If a singleton resource is registered in both contexts, this breaks the singleton contract as the API is now reachable via two `ResourceConfig`s on two different ports. 

Therefore, it should be possible to restrict the application of `ResourceConfigCustomizer` to the main server. Currently, it is only possible to register an API exclusively in the management server via `@ManagementContextConfiguration`.

**Comment by mbhave** [comment]
IIRC, the only `ResourceConfigCustomizer` that's required to be applied by the management context is the one that registers the endpoint resources. Instead of marking the customizers as main server only, we should look at applying that configuration without needing to apply all the other customizers.
