### ISSUE TITLE
Way to configure ssl programatically

### ISSUE THREAD

**Issue by sabareeshkkanan** [spring-projects/spring-boot#17816]
We use Cloud config for our configuration as  server.ssl.key-store property takes file location as input I was trying to download this file from the config server and put it locally but I have no idea how to do this before web server starts its configuration. I tried things like @AutoConfigureBefore so on. Any direction on this will be help full and we are using docker swarm, spring boot 2.1.6, Greenwich SR2

**Comment by mbhave** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
