### ISSUE TITLE
Why Spring Boot Maven Plugin repackage provided jars?

### ISSUE THREAD

**Issue by jliu666** [spring-projects/spring-boot#17829]
I mark a dependency provided because it is not necessary when runing, but it was repackaged to fatjar.
I know exclude tag is useful to me. Change default repackage scope to runtime may make fatjar thinner.
And add a scope tag list to configure the plugin is better.

**Comment by philwebb** [comment]
We want to include provided scope dependencies because they are typically jars required to run the the application. Some documentation about this [is in the maven plugin documentation]( https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/exclude-dependency.html). 

The request to support excluding provided scoped dependencies has already been discussed and in issue #8005
