### ISSUE TITLE
Spring-boot + unsatisfied dependency  

### ISSUE THREAD

**Issue by Ponsiva** [spring-projects/spring-boot#17833]
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean found for dependency [java.lang.Throwable]: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: 

I am getting for jdk classes. I am not sure.

SpringBoot Main app class is has following annotation .

@SpringBootApplication
@EnableJpaRepositories("com.XX")
@EntityScan("com.X")
@EnableDiscoveryClient
@EnableFeignClients
@EnablePrometheus
@EnableCircuitBreaker

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
