### ISSUE TITLE
Consider addressing alerts reported by lgtm.com

### ISSUE THREAD

**Issue by jbduncan** [spring-projects/spring-boot#17868]
I learned about a static analysis website called [lgtm.com](https://lgtm.com) some time ago, and I noticed that Spring Boot has an entry on the website where currently [26 alerts](https://lgtm.com/projects/g/spring-projects/spring-boot/alerts) are reported against it, a couple of which seem to be security-related.

I personally think these alerts should be looked into and ideally fixed. What's the Spring Boot team's thoughts on this? :thinking:

(I'm unclear if I should disclose the security-related alerts to https://pivotal.io/security, so I'd love some guidance on this.)

**Comment by wilkinsona** [comment]
Thanks for brining the alerts to our attention.

Unfortunately, tools like lgtm.com are rather notorious for producing false positives. For example, looking through the alerts, all those for potential resource leakage are incorrect as the stream is closed either when an enclosing stream is closed or by the method into which the stream is passed. The information exposure through a stack trace is also a false positive, as are the two zipslip-related alerts where one is in test code and the other is extracting the user's own archive. A number of the alerts about dereferencing a variable that may be null are also false positives due to the tool not understanding what `Assert.notNull` does.

It's not all bad, however. At last one of the alerts was genuine and I have fixed it in https://github.com/spring-projects/spring-boot/commit/ba4c5be2fd81b6cb658fe8099c29147462c3c13a.

> I'm unclear if I should disclose the security-related alerts to https://pivotal.io/security, so I'd love some guidance on this.

Please do report exploitable security vulnerabilities responsibly to https://pivotal.io/security. Before reporting something based on an alert from a tool like lgtm.com, please take some time to verify that the alert is not a false positive and can be exploited.

**Comment by jbduncan** [comment]
@wilkinsona Thank you very much for your quick response!

> ...It's not all bad, however. At last one of the alerts was genuine and I have fixed it in ba4c5be.

I'm glad to hear at least one of the alerts was genuine. I was aware that static analysis tools do produce false positives, so I wasn't sure. :)

> Please do report exploitable security vulnerabilities responsibly to https://pivotal.io/security. Before reporting something based on an alert from a tool like lgtm.com, please take some time to verify that the alert is not a false positive and can be exploited.

Oh oops, I see I made a mistake here! Thank you for clarifying this for me. I'll know to verify and disclose anything security-related responsibly next time. :)
