### ISSUE TITLE
NettyRSocketServerFactory overrides ServerRSocketFactoryCustomizer acceptor

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#17870]
`NettyRSocketServerFactory` [invokes acceptor](https://github.com/spring-projects/spring-boot/blob/ba4c5be2fd81b6cb658fe8099c29147462c3c13a/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/rsocket/netty/NettyRSocketServerFactory.java#L124) after applying the `ServerRSocketFactoryCustomizer` instances which means the `SocketAcceptor` cannot be overridden.

This may be less relevant once gh-17869 is resolved. However, the `ServerRSocketFactoryCustomizer.acceptor` should either be honored (preferred) or not be exposed.

**Comment by bclozel** [comment]
Our `ServerRSocketFactoryCustomizer` is taking directly an `rsocket-java` type, which is both useful (for customizing native configuration) and a limitation (since we're bound to the `RSocketFactory.ServerRSocketFactory` API).

With the `RSocketFactory.ServerRSocketFactory`, setting the acceptor turns immediately the factory into a different type and you don't have access anymore to other options. If we set the acceptor before delegating to customizers, we can't provide them with the `RSocketFactory.ServerRSocketFactory` type anymore.

Also, `ServerRSocketFactoryCustomizer` implementations cannot use in practice the acceptor method as they need to return the same type. For example, this won't compile:

```java
@Bean
ServerRSocketFactoryCustomizer myCustomizer() {
	return (serverRSocketFactory) -> {
		SocketAcceptor acceptor = null;
		return serverRSocketFactory.acceptor(acceptor);
	};
}
```

So in practice, it's impossible to use the customizer to change the acceptor. The acceptor is a central piece of the infrastructure, so I don't think it should be honored in customizers anyway. The preferred way of overriding the acceptor is to create a custom `RSocketServerBootstrap` bean.
