### ISSUE TITLE
http/2 + http basic auth causes webflux response to stall

### ISSUE THREAD

**Issue by neokyle1** [spring-projects/spring-boot#17881]
Spring Boot Version: 2.1.7.RELEASE
Java Version: openjdk 11
OS: OSX
Example Project: [example.zip](https://github.com/spring-projects/spring-boot/files/3508031/example.zip)
Curl Command: curl -v --http2 -u "test:test" 'http://localhost:1234/test'

My HTTP 2 requests seem to stall under specific circumstances. It seems to happen when my output is a flux and I have HTTP Basic security enabled. Using HTTP 1.1 or disabling auth or changing the output from Flux<String> to Mono<List<String>> (via .collectList()) all seem to fix the issue.

My guess is that it has something to due with UserDetailsRepositoryReactiveAuthenticationManager's authenticate method since it switches schedulers.

**Comment by neokyle1** [comment]
It looks like this is not happening in version 2.1.4.RELEASE

**Comment by wilkinsona** [comment]
Thanks very much for the sample. I've reproduced the problem with 2.1.7. As you've noted above, it does not occur with 2.1.4. It does, however, occur with 2.1.5 and 2.1.6.

Spring Boot 2.1.4 uses Reactor Californium-SR6 whereas 2.1.5 uses Californium-SR8. The problem does not occur if I use Spring Boot 2.1.7 but downgrade Reactor by adding the following to `build.gradle`:

```
ext['reactor-bom.version'] = 'Californium-SR6'
```

In short, this appears to be a Reactor or Reactor Netty problem.

@neokyle1 Can you please open a [Reactor Netty issue](https://github.com/reactor/reactor-netty/issues/) so that they can investigate?
