### ISSUE TITLE
ReactiveManagementWebSecurityAutoConfiguration does not back off when oauth2 client configuration present

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-boot#17949]
`ReactiveManagementWebSecurityAutoConfiguration` does not configure `oauth2Login()` even when `spring-security-oauth2-client` is in classpath and properties have been configured. It only configures `httpBasic()` and `formLogin()` for all cases.

The configuration logic should follow the default configuration for `SecurityWebFilterChain` in [`WebFluxSecurityConfiguration.springSecurityFilterChain()`](https://github.com/spring-projects/spring-security/blob/bc38a4a3cca41b8fe6b812b8cb1ce4a4cc42bba9/config/src/main/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfiguration.java#L98).

Related [spring-security#6314](https://github.com/spring-projects/spring-security/issues/6314)

**Comment by philwebb** [comment]
@jgrandja Does this also apply to `ManagementWebSecurityConfigurerAdapter`? Should we try and surface something public in Spring Security itself that will allow us to share that configuration code?

**Comment by philwebb** [comment]
I had an attempt at fixing this in https://github.com/philwebb/spring-boot/tree/gh-17949 but it doesn't feel quite right. Specifically we're now pretty much duplicating `ReactiveSecurityAutoConfiguration` in `ReactiveOAuth2ClientAutoConfiguration`.

I have a feeling that the problem does actually lie in `ReactiveManagementWebSecurityAutoConfiguration` and the `springSecurityFilterChain` it creates. I think that that class should be duplicating [`WebFluxSecurityConfiguration.springSecurityFilterChain()`](https://github.com/spring-projects/spring-security/blob/bc38a4a3cca41b8fe6b812b8cb1ce4a4cc42bba9/config/src/main/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfiguration.java#L98) and doing what `OAuth2ClasspathGuard` does in default configuration.

I also wonder if we need something in `ManagementWebSecurityConfigurerAdapter` for the Servlet setup (although I can't see any OAuth support in `WebSecurityConfigurerAdapter.configure`).

**Comment by mbhave** [comment]
I think the servlet setup is slightly different as you explicitly need to configure `.oauth2Login()` and `.oauth2client()`  which we do in `OAuth2WebSecurityConfiguration`. Since there's an explicit bean of type `WebSecurityConfigurerAdapter` for the OAuth setup, it causes `ManagementWebSecurityConfigurerAdapter` to back off.

The main reason the separate management configurations exist, is for the health and info endpoints. With the default security configuration, we wanted these endpoints to be accessible without authenticating. When OAuth is added to the classpath we secure everything via OAuth, including the health and info endpoints (this was the plan for the reactive case as well but it doesn't behave this way because of this bug).

Whether the change needs to be in `ReactiveOAuth2ClientAutoConfiguration` or `ReactiveManagementWebSecurityAutoConfiguration` depends on if we want the same behavior of opening up `health` and  `info` endpoints even when OAuth is on the classpath. If we do decide that `health` and `info` should be  open, the servlet configuration would need to be updated as well. This might potentially lead to two `WebSecurityConfigurerAdapter`s for the servlet case which is something I'd really like to avoid (as deciding when to back off might become tricky). 

I'm in favor of having everything secured by OAuth once OAuth is added to the classpath without making an exception for the `health` and `info` endpoints. If duplicating `@EnableWebFluxSecurity` feels odd, we should consider doing what Joe suggested above in  `ReactiveOAuth2ClientAutoConfiguration`. Let's see what the rest of the team thinks.
