### ISSUE TITLE
Springboot 2.1.7: qurey zerofill column result without zero

### ISSUE THREAD

**Issue by FuMengAtDJ** [spring-projects/spring-boot#17990]
Springboot version : 2.1.7
driver-class-name: com.mysql.cj.jdbc.Driver

I created my table's key column with " int(8) unsigned zerofill NOT NULL AUTO_INCREMENT"
and DB's data exits 00000001. but when I query this data the result is 1 without zero. 

when I use Springboot version : 2.0.3 with com.mysql.jdbc.Driver, there is no problem by query result "0000001" .
I query this column via Mybatis mapper.xml file like this:
`<result column="article_id" property="articleId" jdbcType="VARCHAR"/>`

How can I get the query result as 00000001 in version 2.1.7 without using  fuction LPAD in mapper.xml file. 
thank you very much. sorry for my poor English.

**Comment by wilkinsona** [comment]
Thank you for the report, @FuMengAtDJ. I would guess this is due to a change in the MySQL JDBC driver. You could try setting `mysql.version` in your pom.xml or build.gradle to downgrade to 5.1.46 (the version used in 2.0.3). If that does not help, please provide details of your MySQL installation and a minimal sample project that reproduces the behaviour you have described as a zip attached to this issue.

It's worth noting that `zerofill` is deprecated in the latest versions of MySQL so migrating to an alternative approach would be a good thing to do regardless. The [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-overview.html) makes these recommendations:

> Consider using an alternative means of producing the effect of this attribute. For example, applications could use the `LPAD()` function to zero-pad numbers up to the desired width, or they could store the formatted numbers in `CHAR` columns.

**Comment by FuMengAtDJ** [comment]
@wilkinsona 
Thank you very much. sir.
I have resolved my problem by setting mysql.version from 8.0.17 to 5.1.46 in pom.xml.

**Comment by wilkinsona** [comment]
Excellent. Thanks for letting us know.
