### ISSUE TITLE
@Import  annotation

### ISSUE THREAD

**Issue by jiangqingmao** [spring-projects/spring-boot#18013]
1. 

```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Documented
@Import({MyImportSimple.class})
public @interface EnableTest {
}
```

2.  

```java
public class MyImportSimple {
    
    @Autowired
    private MyBean myBean;
   
    public MyImportSimple(){
         System.out.println(myBean);   //this why is null ?
    }
 }
```

3. 

```java
@Configuration
public class Config {
    @Bean
    public MyBean myBean(){
        return  new MyBean();
    }
}
```

Above all, I freed the annotations on the startup class. The output  'myBean' object is null, and the  show that they have been registered with the bean container. But the 'MyImportSimple' class plus `@Component` will have value.I don't know why. 

                                                                                       Thank you very much.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
If you do ask this issue on stackoverflow I'd suggest including a complete sample that can be downloaded and run.
