### ISSUE TITLE
When using Netty, an invalid content-type header value causes request to get stuck when compression is enabled

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#18018]
See https://github.com/spring-cloud/spring-cloud-gateway/issues/1111. We should make our predicate more robust by returning false for a malformed mime type in the `Content-Type` header rather than throwing an exception.

**Comment by dreis2211** [comment]
This got me thinking if this should be done for Jetty, Undertow etc. as well, @wilkinsona ? I'm asking because out of interest I was working on a fix as well, but Jetty seems to hang indefinitely - for reasons that I can't explain yet. Can be reproduced by moving the new test from `NettyReactiveWebServerFactoryTests` to `AbstractReactiveWebServerFactoryTests`. Tomcat seems to work out of the box, Undertow seems to work despite having the same MimeType parsing as Netty in `UndertowCompressionConfigurer`. Might be worth a look?

**Comment by dreis2211** [comment]
While I was working on the fix I also tried this for the servlet based tests and got them to run with similar changes as in 3d23277. Is it worth sharing a PR for the servlet based stuff at least?

**Comment by dreis2211** [comment]
Just saw https://github.com/spring-projects/spring-framework/issues/23553 - seems like we had the same problem then ;)
