### ISSUE TITLE
@Aspect Not recognized as a component

### ISSUE THREAD

**Issue by antusen** [spring-projects/spring-boot#18090]
spring boot version 2.1.7

```java
@Aspect
public class LogAspect {
}
```

why do need `@Configuration`? I'm looking at the official website is used `@Aspect`.  `@SpringBootApplication` is scanned by default.

```java
@Aspect
@Configuration
public class LogAspect {
}
```

**Comment by wilkinsona** [comment]
I would guess that, for some reason, AspectJ auto-proxying is not enabled. It should be auto-configured by `AopAutoConfiguration`. Perhaps it isn't enabled as your classpath is faulty due to a jar file being corrupted when it was downloaded? Unfortunately, it's impossible for me to tell without more information about the problem. If you would like us to spend time investigating, please take the time to provide a complete and detailed description of the problem and a minimal sample that reproduces the behaviour that you have described.

**Comment by antusen** [comment]
```java
package com.cn.spring;
@SpringBootApplication
@EnableAspectJAutoProxy(proxyTargetClass = true)
public class WebApplication {
    public static void main(String[] args) {
        SpringApplication.run(WebApplication.class, args);
    }
}
```
pom file add aop dependency
```java
package com.cn.spring.aspect;
@Aspect
public class interFaceInfoAspect {
}
```
No other configuration

**Comment by snicoll** [comment]
@antusen that's not the minimal sample that we need. Can you please turn the code snippets into a complete and minimal sample that reproduces the problem, zip it up, and attach it to this issue? A link to a github repo works as well.

**Comment by mdeinum** [comment]
`@Aspect` isn't an `@Component` and as such not detected as a Spring bean. You need to either add an additional `@Component` (`@Configuration`, like `@SpringBootApplication`) is also an `@Component`) to have it detected or add an `@Bean` method for it. 

Another solution would be to add an additional `@ComponentScan` which detects `@Aspect` annotated beans. Something like `@ComponentScan(includeFilters = { @ComponentScan.Filter(Aspect.class)} )`.

**Comment by antusen** [comment]
Thank you very much @mdeinum
