### ISSUE TITLE
@Component cannot not longer be used on @ConfigurationProperties beans

### ISSUE THREAD

**Issue by Stmated** [spring-projects/spring-boot#18138]
In previous versions I could do:

```
@Component("properties")
@ConfigurationProperties("app")
public class MyAppProperties {
    private String value;
    // getter, setter
}
```
```
@Scheduled(fixedRateString = "#{@properties.getValue()}")
public void method() {
}
```

But this no longer works, since you cannot mix `@Component` and `@ConfigurationProperties`, and there is no "beanName" or such property inside `@ConfigurationProperties`. I tried removing `@Component` and instead relying on bean name being "myAppProperties" but that did not want to resolve either, it seemed.

Is this a bug/area of improvement? Or is this supposed to be solved in some other way moving forward?

**Comment by snicoll** [comment]
@Stmated there is still a bean name of course but it's generated with the prefix and the FQN of the class. If you absolutely want to do it this way you can create the bean yourself, something like

```java
@Bean(name = "properties")
@ConfigurationProperties("app")
public MyAppProperties myAppProperties() { ... }
```

**Comment by Stmated** [comment]
That did work well! But it feels a bit cumbersome to have to expose it through a @Configuration when that is not how it is usually done, and that you're otherwise forced to follow some Magic Auto-Generated Name which I thought was something the framework tried to keep away from.
I guess it'd be somewhat fine if the generated bean name was documented inside @ConfigurationProperties.

**Comment by snicoll** [comment]
@Stmated thanks for the feedback.

> and that you're otherwise forced to follow some Magic Auto-Generated Name which I thought was something the framework tried to keep away from.

Yeah, I am not suggesting in any way you should use the auto-generated name. I suggested above you should take control of the name as shown in the example.


> But it feels a bit cumbersome to have to expose it through a @Configuration when that is not how it is usually done,

FTR, there's nothing unusual in creating a `@ConfigurationProperties` via java config, all features are going to work the same way. This is the first time I am aware someone uses a `@ConfigurationProperties` the way you do. If you want to take control over the name, then what I've mentioned is the way to go I am afraid. As of 2.2 we do scan configuration properties type automatically so adding `@Component` is a problem.

I agree that scanning makes that particular use case more difficult to achieve. Flagging for team attention to see what the rest of the team thinks.

**Comment by spencergibb** [comment]
BTW, Spring Cloud projects create many `@ConfigurationProperties` beans thru java config. Just reinforcing that it isn't unusual.

**Comment by wilkinsona** [comment]
@mbhave has suggested that we may be able to fix this by relaxing the restriction that `@Component` and `@ConfigurationProperties` cannot be used together. Rather than banning the combination outright, we would continue to support it for mutable configuration properties that use method-based binding by ignoring types annotated with both in our configuration property scanning support and relying on component scanning there instead. Users that wish to use the new-in-2.2 immutable configuration property support, would have to use `@ConfigurationProperties` on its own. This would mean that it wasn't possible to control the name of an immutable configuration properties bean. However, that is a limitation for a new feature rather than a new limitation on something that used to work in 2.1.x.
