### ISSUE TITLE
Quartz always starting as jobStoreCMT 

### ISSUE THREAD

**Issue by joseluisbsa** [spring-projects/spring-boot#18171]
Doesn't matter if I put 'JobStoreTX' in 'org.quartz.jobStore.class', the Quartz scheduler always starting as JobStoreCMT.

How can I run as JobStoreTX ?

**Comment by wilkinsona** [comment]
This is standard behaviour for Spring Framework's Quartz support when configured with a `DataSource`. The use of Framework's `LocalDataSourceJobStore`, a `JobStoreCMT` sub-class, ensures that the store participates in any Spring-managed transactions. `JobStoreTX` is intended for use in a standalone environment which does not apply when using Spring as it manages transactions for you. If you need to use `JobStoreTX` you will have to configure Quartz manually rather than using Boot's auto-configuration of Spring Framework's Quartz integration.
