### ISSUE TITLE
YAML lists aren't overwritten properly when using CompositePropertySource

### ISSUE THREAD

**Issue by ewiegs4** [spring-projects/spring-boot#18174]
Using Spring Boot 2.1.8.RELEASE
I recently migrated my application from using a large multi-profile `application.yml` to using an embedded spring cloud config server reading an `application.yml` and various `application-{profile}.yml` files from a remote git repository.

After this migration I noticed that YAML lists that are specified in the `application.yml` but overwritten in one of the profile-specific files were actually being merged together instead of overwritten (like the old behavior described in #9137).

I attempted to isolate the issue, and while I'm not going to pretend to know all the inner workings of the Spring environment and `PropertySource`s, it seems like the issue may stem from the fact that both the `application.yml` and `application-{profile}.yml` are bundled together in the same `CompositePropertySource` and perhaps the two lists are therefore treated as coming from the same source?

Anyways, I could be off base, but I created a minimal application to reproduce the issue:
https://github.com/ewiegs4/yaml-list-test
To run, turn the `git-config` directory into a local git repository and commit the files, then run the Spring Boot application with the `profile1` profile active (I couldn't get the `native` cloud config option to work despite following the documentation exactly).
Expected result: `[item3]`
Actual result: `[item3, item2]`

Note: using a comma-separated list instead of a YAML list seems to allow the override to work correctly, if that helps.

**Comment by mbhave** [comment]
@ewiegs4 Thank you for the sample. Your analysis is correct. The two lists are being merged because the properties from the config server end up in a `CompositePropertySource`. 

I'm not sure if this is something we should deal with in Spring Boot. We can’t really tell from a `CompositePropertySource` alone what the intention is, that is, if the sources in the composite are distinct sources or if they need to be treated as a single source. 

@spencergibb We're wondering if the fix for this should go in Spring Cloud. The property sources that are created from the config server files seem to be distinct property sources. Do you know if the `CompositePropertySource` was used for a specific reason? If not, can Spring Cloud remove the composite in favor of individual property sources?

**Comment by spencergibb** [comment]
each file is it's own property source, similar to how boot does it.

**Comment by ewiegs4** [comment]
So would you like me to log an issue in one of the spring-cloud repositories and reference this issue?

**Comment by spencergibb** [comment]
Spring Cloud Commons is where it would go. At least that's where the composite is. I'm pretty sure there's an existing issue (maybe closed).

**Comment by philwebb** [comment]
I couldn't find a closed issue. I've raised https://github.com/spring-cloud/spring-cloud-commons/issues/611
