### ISSUE TITLE
The SLF4J API need to be drived by spring-boot-starter in spring-boot-starter-webflux

### ISSUE THREAD

**Issue by altus34** [spring-projects/spring-boot#18221]
The SLF4J API is a required dependency of nio-multipart-parser and as such I don't think we should excluded. The version should still be managed by `spring-boot-dependencies` if you import it or extend `spring-boot-starter-parent`.

_Originally posted by @philwebb in https://github.com/spring-projects/spring-boot/pull/18220#issuecomment-531040030_

**Comment by wilkinsona** [comment]
What you've said should happen is, as far as I can tell, exactly what happens when you use Spring Boot's dependency management. 1.7.28 of the SLF4J API is used rather than 1.7.12 that `nio-multipart-parser` depends upon.

If you would like us to spend some more time investigating, can you please take the time to provide a complete and minimal example (zipped and attached to this issue) that shows the problem you have described?

**Comment by altus34** [comment]
Hi,

Here a [sample project](https://github.com/altus34/springboot-issue) to show you how slf4j is not self contain in it's own starter.
Of course in common use case it's totally invisible but I think it'll be better to self contain the slf4j in the spring-boot-starter-webflux but adding and exclusion of slf4j-api in nio-multipart-parser to use the version from the logging-starter.

Regards

**Comment by wilkinsona** [comment]
Thanks for the sample. The things you have highlighted in the README are Maven's standard behaviour.

In the first use case you are using Spring Boot's dependency management so it determines the versions. You've also highlighted `log4j-api`. It is included as a dependency to allow logging that uses the Log4j2 API to be routed into SLF4J and on into Logback.

In the second usecase you are not using Spring Boot's dependency management so Maven determines the version by choosing the one that appears nearest to the root of the dependency graph.
