### ISSUE TITLE
Spring boot version 2.1.8 whether support or not JDK11 AOT

### ISSUE THREAD

**Issue by songzeyang** [spring-projects/spring-boot#18246]
I read the official website of SpringBoot understand support jdk11, But I'm not sure if I support AOT,
thanks

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/) or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
