### ISSUE TITLE
Unable to load several messages.properties

### ISSUE THREAD

**Issue by ask4gilles** [spring-projects/spring-boot#18305]
SB version 2.1.8

Hi,
While using the default ```MessageSourceAutoConfiguration```, I'm not able to load different messages.properties from several jars.

Each messages.properties resides in src/main/resources, so I did not tweak ```spring.messages.basename```

Note that
```org.springframework.boot.autoconfigure.context.MessageSourceAutoConfiguration.ResourceBundleCondition#getResources``` returns the 2 resources correctly though.

Steps to reproduce: run ```com.example.demo.MessageSourceTest``` in attached project.

[demo.zip](https://github.com/spring-projects/spring-boot/files/3641121/demo.zip)

**Comment by wilkinsona** [comment]
Thanks for the report and sample project. This is the expected behaviour for Spring Framework's `org.springframework.context.support.ResourceBundleMessageSource` which is what Spring Boot auto-configures. It uses `java.util.ResourceBundle.getBundle(String, Locale, ClassLoader, Control)` to load `ResourceBundle`s, with one bundle per basename. If you would like a message source that can load multiple bundles per basename, please open a Spring Framework enhancement request. However, I am not sure that it will be accepted as it would make message resolution reliant on classpath ordering which can be brittle and vary from across deployment environments.
