### ISSUE TITLE
GitHub URLs in the published POMs are not valid

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#18328]
For example, the scm URL for `spring-boot-autoconfigure` is:
https://github.com/spring-projects/spring-boot/spring-boot-autoconfigure which isn't a valid URL.

**Comment by philwebb** [comment]
We'll point to the root of the repo

**Comment by wilkinsona** [comment]
Maven automatically appends each project's artifactId to the inherited URL. There's a [long-standing issue](https://issues.apache.org/jira/browse/MNG-3244) to disable this behaviour. It's still open but appears to have been superseded by [MNG-5951](https://issues.apache.org/jira/browse/MNG-5951). MNG-5951 has been fixed in 3.6.0 (and refined in 3.6.1). Unfortunately, we cannot use 3.6.x due to [a bug](https://github.com/mojohaus/flatten-maven-plugin/issues/89) in the flatten plugin.
