### ISSUE TITLE
spring-boot-maven-plugin : generate only *.jar

### ISSUE THREAD

**Issue by zsobolsky** [spring-projects/spring-boot#18340]
running spring-boot-maven-plugin with default configuration produces 2 jars in the ./target directrory.

 -  *.jar.original
 -  *.jar

Is there a way in the configuration of the plugin that only produces the *.jar? I don't find a solution in the docs of the plugin.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
The short answer is there isn't currently a way to disable the `.original` backup. The `target` folder usually contains lots of artifacts so I'm not sure why the additional file would be an issue.

**Comment by zsobolsky** [comment]
ok, thanks for the quick and clear answer.
