### ISSUE TITLE
Clarify that httptrace and auditevents endpoints are enabled by default but that each requires an additional component for them to be auto-configured

### ISSUE THREAD

**Issue by PascalSchumacher** [spring-projects/spring-boot#18352]
The first table in https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints claims that the `httptrace` endpoint is enabled by default.

But I after https://github.com/spring-projects/spring-boot/commit/de128fed20d7ee7f569e7219ba734ec0ea6de4cd this is not true anymore.

Or am I missunderstanding something?

Edit:
I guess the same should be done for `auditevents` (because of https://github.com/spring-projects/spring-boot/commit/07d6eb6397d5362db6917c134f0190d76a0c5fb6).

**Comment by wilkinsona** [comment]
Thanks for the report. The documentation is certainly confusing at the moment. It's tricky. Technically speaking, the endpoint is enabled by default (you don't need to set `management.endpoint.httptrace.enabled=true` to enable it) but you do need to provide a repository for it to use otherwise its auto-configuration will back off.

**Comment by PascalSchumacher** [comment]
Thank you very much! 👍
