### ISSUE TITLE
Upgrade to Prometheus Pushgateway 0.7.0

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#18419]

**Comment by snicoll** [comment]
`PrometheusMetricsExportAutoConfigurationTests` is failing as the `gatewayBaseURL` has changed so need a proper investigation.

**Comment by dreis2211** [comment]
Seems to be caused by https://github.com/prometheus/client_java/pull/491/files.

**Comment by wilkinsona** [comment]
Thank you, @dreis2211.

Rather than always appending `metrics/job/` to the provided base URL, only `metrics/` is appended up front. The, when making the request, `job/` or `job@base64/` is appended followed by the encoded job (URL-encoding for the former and Base64-encoding for the latter). We should update the tests to remove `job/` from the expected URL.

**Comment by wilkinsona** [comment]
Closed by dab69cfbd23314001bdd62679d1ff114b230c194.
