### ISSUE TITLE
Claify ConfigurationPropertiesBean javadoc

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#18487]
`ConfigurationPropertiesBean` seems like it serves two purposes. One is for the `/configprops` report endpoint where it gets all the @ConfigurationProperties beans. At this point, we don't need any of the binding related properties. It is also used by `ConfigurationPropertiesBinder` where it needs to know about the `Bindable` and annotations. The javadoc which says 

```
Provides access to {@link ConfigurationProperties} beans from an {@link ApplicationContext}.
```

makes sense for the first case but doesn't really apply for the second. We should see if we can split some of that logic apart.

**Comment by philwebb** [comment]
I took a quick look at this but I can't find a good way to split it up. The `getAnnotation()` method needs to be public because it's used by the `ConfigurationPropertiesReportEndpoint`. That sort of has a knock on effect because we need to go searching for the factory method etc. Given how near we are to GA I think I might just try to clarify the javadoc.

**Comment by philwebb** [comment]
I've cleaned up the javadoc a bit. We may be able to revisit this again in 2.3 if the class is still too confusing.
