### ISSUE TITLE
BeanInstantiationException: Failed to instantiate []: Specified class is an interface

### ISSUE THREAD

**Issue by izinkevich** [spring-projects/spring-boot#18577]
Hi,

I get error with package org.springframework.boot:spring-boot-starter-data-mongodb:2.1.5.RELEASE

Description:
I have interface Call and class TokBoxCall (implements Call) in the code.
There is default typeKey in the records in Mongo DB (4.0.10): 
"_class":"com.xxxxx.server.data.model.call.TokBoxCall"
However, when I perform reading operations, e.g. callRepository.findById(id), I get Exception:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.xxxxx.server.data.model.Call]: Specified class is an interface
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:119)
        at org.springframework.data.convert.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:64)

Mongo DB version is 4.0.10.
OpenJDK Runtime Environment (build 10.0.2+13-Debian-1)

**Comment by wilkinsona** [comment]
Thanks for the report, but I think this needs to be addressed by the Spring Data MongoDB team. The failure is occurring with `org.springframework.data.convert.ReflectionEntityInstantiator` which is part of Spring Data. Sprign Data MongoDB uses JIRA for issue tracking: http://jira.spring.io/browse/DATAMONGO-2360. Please open an issue there and then comment here with a link to it so that we can follow along.

**Comment by izinkevich** [comment]
https://jira.spring.io/browse/DATAMONGO-2391
