### ISSUE TITLE
Spring boot 2.2.0 cros is abnormal. Switching to 2.1.9 is normal. Why?

### ISSUE THREAD

**Issue by CoxxA** [spring-projects/spring-boot#18662]
<img width="1409" alt="56917217-291e9280-6a78-11e9-8e5e-05ac7a832934" src="https://user-images.githubusercontent.com/26744946/67148431-0906b800-f2d2-11e9-8518-a7fd2821d499.png">

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
