### ISSUE TITLE
Issue using @Transactional annotation above integration test class for multithreading environment

### ISSUE THREAD

**Issue by arakorno** [spring-projects/spring-boot#18683]
Application stack: Spring boot 2.1v+ testcontainers postgresql 1.10.3v+ JUnit 4.12v
When I run the integration test for code which calls JPA repository within a new thread I'm getting data which was populated during starting PostgreSQLContainer and I can't receive data from the script above class test( @Sql(scripts ="data.sql"). But when I remove @transactional annotation above the test I can get data both from SQL script from test and test container.
My question is it possible to get data in multithreading environment from test script without removing @transactional annotation?
Thank you for your answer!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
