### ISSUE TITLE
Drop support for Jetty 9.4.21 and earlier

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#18692]
See #18536

**Comment by dreis2211** [comment]
Do we have some documentation about minimum supported versions in general, @philwebb ? I recently noticed that Spring-Boot apps on Jetty 9.4.14.v20181114 don't work with Spring-Boot 2.2 anymore, for example. Not directly relevant for this issue, but the "earlier" might be less versions than one would think ;)

**Comment by wilkinsona** [comment]
We don't. Generally speaking it is only safe to assume that the version Boot uses by default and later maintenance versions are supported. This could be because Boot relies on a bug fix or because there's been a breaking change in a third-party maintenance release that causes a compatibility problem. You can read this issue as a little more than a reminder to remove the code that tolerates 9.4.21 and earlier.

**Comment by dreis2211** [comment]
That's what I thought as well. The issue reminded me of asking though.

**Comment by philwebb** [comment]
Yeah, this issue was mainly me reminding myself that in we'll be able to drop that reflection code in the Boot 2.3.

**Comment by snicoll** [comment]
Isn't that issue superseded somehow by https://github.com/spring-projects/spring-boot/issues/18842? I see that the related commit [already removed the reflection code](https://github.com/spring-projects/spring-boot/commit/3f0367e2dd4e07bfe8228f47dc20e28bd3b6f8c2).

**Comment by wilkinsona** [comment]
We still have tests that verify compatibility with the older version.
