### ISSUE TITLE
Change the overall application health status in Actuator

### ISSUE THREAD

**Issue by shashank-gupta017** [spring-projects/spring-boot#18701]
We have implemented custom health check actuator in our spring boot application, which has dependencies on RabbitMQ.

If RabbitMQ node is UP, the actuator/health endpoint, returns the response as follows:
```
{
    "status": "UP",
    "details": {
        "rabbit": {
            "status": "UP",
            "details": {
                "defaultExchangeRabbitTemplate": {
                    "status": "UP",
                    "details": {
                        "version": "3.7.15"
                    }
                }
            }
        }
    }
}
```
The expected behavior should be, if RabbitMQ node is down, the actuator/health endpoint should return the response as below. I want to show the overall application health status as UP, even if RabbitMQ health is DOWN.
```
{
    "status": "UP",
    "details": {
        "rabbit": {
            "status": "DOWN",
            "details": {
                "defaultExchangeRabbitTemplate": {
                    "status": "DOWN"
                }
            }
        }
    }
}
```
Currently, the overall application health status also shows as DOWN, if rabbitmq node is unavailable.
```
{
    "status": "DOWN",
    "details": {
        "rabbit": {
            "status": "DOWN",
            "details": {
                "defaultExchangeRabbitTemplate": {
                    "status": "DOWN"
                }
            }
        }
    }
}
```
Is there any way to de-couple the overall application health from downstream health checks. I could not find anything specific in Spring documentation for this scenario.

**Comment by wilkinsona** [comment]
A `StatusAggregator` (or `HealthAggregator` prior to 2.2) bean is used to create the aggregated result for the whole application. However, rather than using custom aggregation, you may be better of using Spring Boot 2.2's support for [health groups](https://docs.spring.io/spring-boot/docs/2.2.0.RELEASE/reference/htmlsingle/#health-groups) and separating the contributions into those that are vital and those that are not.

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
