### ISSUE TITLE
Spring-Boot 2.2.0 process fails to terminate when launched in debug mode

### ISSUE THREAD

**Issue by rmead** [spring-projects/spring-boot#18706]
When running spring-boot 2.2.0 in debug mode in both Eclipse 2019-06 and IntelliJ 2019.2, attempts to terminate the process via the IDE look like they kill the process (per the IDE), however, the java process is still running (verified by ps -ef | grep java).

When running non debug mode in Eclipse, the process can be terminated but Eclipse displays a message stating "terminate failed".

I've tried all sorts of older post options including: -Dspring-boot:run.fork=false -Dfork=false

Running spring at cmd line using mvn spring-boot:run terminates normally with ctrl-c.

I'm using the following core dependencies in my pom:
spring-boot-starter-parent
spring-boot-starter-web
spring-boot-starter-jersey
spring-boot-starter-security

I'm not using any spring plugins in Eclipse. I'm using open jdk 11.0.3+7 on centos 7.

Everything worked normally in spring-boot 2.1.7, 2.1.8 and 2.1.9

**Comment by wilkinsona** [comment]
As it appears you suspected, the problem is occurring because you are running the application via Maven, it is now forking a new JVM by default, and unlike your shell, your IDE is failing to terminate both the parent and child processes.

The correct system property to disable this behaviour is `spring-boot.run.fork=false`. Note that, generally speaking, we recommend invoking your application's main method directly in your IDE and only using `spring-boot:run` on the command line.

**Comment by rmead** [comment]
Thanks for the response.  I didn't realize I had a typo with a : vs a . between spring-boot.run which corrects my issue.

Is there documentation you can point me to explaining recommending invoking main from IDE vs using mvn goal spring-boot:run?  I havent troubleshooted this yet but I've never been able to invoke main() directly without errors.

**Comment by rmead** [comment]
I found the documentation at this link but there is no mention of this in the what's new or release notes for spring-boot 2.2.0 
https://docs.spring.io/spring-boot/docs/current/maven-plugin/usage.html#Running_the_application

**Comment by snicoll** [comment]
@rmead there is an issue for that: https://github.com/spring-projects/spring-boot/issues/18638
