### ISSUE TITLE
How Spring Boot 2.2.0 accept Date params in RequestBody?

### ISSUE THREAD

**Issue by eacdy** [spring-projects/spring-boot#18888]
I want to post a date in request body. Date's format is like `2019-11-11T21:21:21`. 
Sample goes below:
```java
@PostMapping("/test")
    public String test(@RequestBody User user) {
        log.info("user is = {}", user).
        return "hello";
    }
```

```java
public class User {
    private String username;
    private String password;
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private Date regTime;
    // getters and setters ...
}
```

How ever, regTime of the user is always null.

How Can I post a Date params in RequestBody?
Thanks a lot!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
