### ISSUE TITLE
@ServletComponentScan does not work with a component index

### ISSUE THREAD

**Issue by yimlin** [spring-projects/spring-boot#18910]
when ServletComponentRegisteringPostProcessor add @WebServlet, it requires an ScannedGenericBeanDefinition from an ClassPathScanningCandidateComponentProvider.

it works fine without Context-Indexer but wrong with Context-Indexer.
ClassPathScanningCandidateComponentProvider will return an AnnotatedGenericBeanDefinition, when their is an spring.components file.

**Comment by wilkinsona** [comment]
Thanks for the report but, having looked at the code, I don't yet understand why the problem is occurring. The index should be ignored as `@WebFilter`, `@WebListener`, `@WebServlet`, are not annotated with `@Index`. Can you please create a small sample that reproduces the problem and share it with us by zipping it up and attaching it to this issue?

**Comment by wilkinsona** [comment]
Sorry, I see the problem now. The index is used for any `javax.*` annotation.
