### ISSUE TITLE
Support constructor binding on 3rd party classes

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#18935]
We currently don't offer a good way to indicate that constructor binding should be used on a class that isn't under the users own control. See https://github.com/spring-projects/spring-boot/issues/18919#issuecomment-551170295 for details.

**Comment by philwebb** [comment]
We've discussed changing the logic again so that a `@ConstructorBinding` on a type indicates that any nested bind is also a candidate for constructor binding. To offer an escape hatch where constructor binding should not be used we could offer an `exclude` attribute.

**Comment by mbhave** [comment]
It's not clear when someone would want to use `exclude`. Adding `exclude` would more often than not mean that setter binding should be attempted in which case a default constructor is required. Once there's a default constructor along with a parameterized constructor, constructor binding is automatically skipped because it checks for the presence of exactly one constructor that is parameterized. The exclude then does not provide any additional benefit. For this reason, we've decided not to rush into adding the `exclude` attribute till there is a solid use-case for it.
