### ISSUE TITLE
Setting health endpoint cache time-to-live does not actually use CachingOperationInvoker

### ISSUE THREAD

**Issue by temesoft** [spring-projects/spring-boot#18959]
When setting `management.endpoint.health.cache.time-to-live=60s` configuration to specify caching of health endpoint response - it seems not to take an effect in 2.2.0 release version. When requesting health endpoint `ReflectiveOperationInvoker` is being called instead of `CachingOperationInvoker`.

Attached, is a sample spring-boot application with a JUnit test that shows this issue.

[my-app.zip](https://github.com/spring-projects/spring-boot/files/3833480/my-app.zip)

P.S. When switching to use an older version (for example 2.0.3) the health endpoint response is cached correctly.

Thank you
-Dmitriy

**Comment by dreis2211** [comment]
Hi @temesoft . I think I'm on to something. Not a team member, but give me until this morning to try out my idea.

**Comment by dreis2211** [comment]
So here's what I found so far. The problem comes from the fact that `ApiVersion` is treated as a mandatory parameter in `CachingOperationInvokerAdvisor` and thus breaks the caching. One could simply handle `ApiVersion` the same way `SecurityContext` is handled, but that would probably break return wrong results if request A has `ApiVersion.V3` specified and request B has `ApiVersion.V2`. 

This was likely introduced with #17929.

**Comment by snicoll** [comment]
Thank you both. We'll have a look to handle `ApiVersion` so that it doesn't break caching.

**Comment by dreis2211** [comment]
Made a proposal fix in #18961

**Comment by snicoll** [comment]
Closing in favour or PR #18961
