### ISSUE TITLE
@ConstructorBinding not working in Spring boot 2.2.1 

### ISSUE THREAD

**Issue by cheese10yun** [spring-projects/spring-boot#18960]
@ConstructorBinding not working in Spring boot 2.2.1 

```yml
objs:
  aaa: ""
  bbb: ""
```

```kotlin
@ConstructorBinding
@ConfigurationProperties(prefix = "objs")
data class ObjsProperties(
        @field:NotEmpty
        var aaa: String,
        @field:NotEmpty
        var bbb: String
) {
}
```

log 
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.example.kotlinjunit5.AppRunner required a bean of type 'com.example.kotlinjunit5.ObjsProperties' that could not be found.


Action:

Consider defining a bean of type 'com.example.kotlinjunit5.ObjsProperties' in your configuration.


Process finished with exit code 1
```

But it works in other versions.(Spring Boot Version 2.2.0)

Currently only works with version 2.2.1.

**Comment by wilkinsona** [comment]
Thanks for the issue report. I don't think this is related to constructor binding but to the configuration properties bean `ObjProperties` not being created. I suspect that is because we [stopped enabling configuration properties scanning by default in 2.2.1](https://github.com/spring-projects/spring-boot/releases/tag/v2.2.1.RELEASE). The problem should be resolved by adding `@ConfigurationPropertiesScan` to your application alongside `@SpringBootApplication` or adding `@EnableConfigurationProperties(ObjProperties.class)`. If that does not help, please create a complete and minimal sample that recreates the problem and share it with us by zipping it up and attaching it to this issue. We can then re-open it and take another look.

**Comment by cheese10yun** [comment]
> Thanks for the issue report. I don't think this is related to constructor binding but to the configuration properties bean `ObjProperties` not being created. I suspect that is because we [stopped enabling configuration properties scanning by default in 2.2.1](https://github.com/spring-projects/spring-boot/releases/tag/v2.2.1.RELEASE). The problem should be resolved by adding `@ConfigurationPropertiesScan` to your application alongside `@SpringBootApplication` or adding `@EnableConfigurationProperties(ObjProperties.class)`. If that does not help, please create a complete and minimal sample that recreates the problem and share it with us by zipping it up and attaching it to this issue. We can then re-open it and take another look.

@wilkinsona 
Thank you 

```koltin
@EnableConfigurationProperties(ObjsProperties::class)
```
it working

**Comment by sysmat** [comment]
- With 2.2.1 are any braking changes?

- My App with 2.2.0 works fine, but test fails with 2.2.1

**Comment by wilkinsona** [comment]
The only known breaking change is the one I [described above](https://github.com/spring-projects/spring-boot/issues/18960#issuecomment-552820570). If that does not apply in your case, then please open a new issue and attach to it a complete and minimal example of your problem.
