### ISSUE TITLE
How to debug ALL FILTERS in spring boot application?

### ISSUE THREAD

**Issue by rohitkrishna094** [spring-projects/spring-boot#19005]
If I want to debug all security filters, I can use `@EnableWebSecurity(debug = true)`. This will let me see security related filters. However how can I achieve the same for `ALL FILTERS` that are not related to security? 

Essentially, some filter is adding headers to my response and I want to know which filter is doing this. How can I trace this?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
