### ISSUE TITLE
@SpyBean (MockitoPostProcessor) tries to initialize @StepScope Bean out of scope

### ISSUE THREAD

**Issue by elxnis** [spring-projects/spring-boot#19020]
I think this fix https://github.com/spring-projects/spring-boot/commit/52050c173c35e8b96722051031ab55774f524967 for this issue https://github.com/spring-projects/spring-boot/issues/17817 has created another issue.

When I try to use `@SpyBean` on `@StepScope` bean Spring Boot Test is failing with `BeanCreationException`. I use `mockito-inline` to allow spying on proxied class (step scope bean) to stub behaviour. This worked with spring-boot `2.1.7.RELEASE`, but stopped working with `2.1.8.RELEASE` and onwards. 

```
org.springframework.beans.factory.BeanCreationException: Could not inject field: 
step.scope.spy.bean.batch.MyItemWriter step.scope.spy.bean.JobControllerIT.myItemWriter; 
nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'scopedTarget.writer': 
Scope 'step' is not active for the current thread;
consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; 
nested exception is java.lang.IllegalStateException: 
No context holder available for step scope
```

Example code to replicate the issue - https://github.com/elxnis/spring-boot-step-scope-spy-bean-issue

**Comment by wilkinsona** [comment]
Thanks for the sample.

We seem to have competing requirements here. If we don't use the inline mock maker, we need to spy on the proxy's target to avoid the proxy's final methods preventing spying. However, if we spy on the proxy's target, we break step scoping. I think we probably need to revert the fix for #17817 and recommend the use of the inline mock maker instead.

The only alternative that I can think of would be for the creation of the proxy not to make the methods final. I don't know if CGLib makes that possible. Even if it does, it's a change that would have to be made in Spring Framework. In the meantime, it doesn't seem unreasonable to require the use of the inline mock maker as that will allow both of the requirements described above to be satisfied.
