### ISSUE TITLE
Spring boot 2.1.8 -> 2.2.1 Post upgrade error

### ISSUE THREAD

**Issue by WakersDeveloper** [spring-projects/spring-boot#19045]
![image](https://user-images.githubusercontent.com/53740038/69120576-492da600-0add-11ea-9e63-895a46564e48.png)
![image](https://user-images.githubusercontent.com/53740038/69120594-53e83b00-0add-11ea-8dd1-a85edb90742c.png)

The constructor Sort(Sort.Direction, String) is undefined -- error

Tell me how it was changed and how to use it.

**Comment by wilkinsona** [comment]
`Sort` is part of Spring Data. The constructor was removed in [this commit](https://github.com/spring-projects/spring-data-commons/commit/0bf160eb971819ea64bed92c5bc1fa323fd5f2b7#diff-619a11300c3eb30e7397b0c87bf83bddL95) but it wasn’t deprecated so that may have been a mistake (/cc @odrotbohm @mp911de). You should us the static [`Sort.by`](https://github.com/spring-projects/spring-data-commons/blob/a6ba3612ba374864abdcd6842b8e13beaa532df0/src/main/java/org/springframework/data/domain/Sort.java#L123) method instead.

**Comment by odrotbohm** [comment]
Andy is correct. There apparently was an oversight in not deprecating all constructors properly. Most of `Sort`'s constructors had been deprecated since Spring Data JPA 2.0 already. The [reference documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.paging-and-sorting) and [Javadoc](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Sort.html) also explain how to use `Sort` instances these days.
