### ISSUE TITLE
Transaction problem Springboot 2.1.6.RELEASE

### ISSUE THREAD

**Issue by czbphoto** [spring-projects/spring-boot#19064]
Springboot 2.1.6.RELEASE using jpa hibernate 5.4.3.Final
A.a() calls B.b()
a() uses @transactional(propagation = Propagation.REQUIRED)
b() uses @transactional(propagation = Propagation.NOT_SUPPORTED, readOnly = true)
Blocking when high concurrency
Connection pool exhausted
The link is not released until timeout
Subsequent visits can't get the database connection and report an error
How can I solve it?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
