### ISSUE TITLE
Consider providing autoconfiguration for Spring Security authentication with JWT token

### ISSUE THREAD

**Issue by michaelisvy** [spring-projects/spring-boot#19110]
Hi,
first of all thanks a lot for the great work! I'm using Spring Boot every day and loving it.

I recently had to set up serverside authentication with a JWT token using this blog: https://auth0.com/blog/implementing-jwt-authentication-on-spring-boot/

I saw that it takes quite a lot of configuration (I had to create 8 classes / interfaces). 
Would it make sense to create some autoconfiguration for that?

I totally appreciate that there will be a few configuration items that Spring Boot will need to be opinionated on:
- token expiration time
- encryption algorithm
- token prefix
etc.

Great thanks!

**Comment by mbhave** [comment]
@michaelisvy I'm not sure I understand the what auto-configuration you're looking for. Spring Boot has auto-configuration for Spring Security's [client](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2-client) and [resource server](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2-server) support. Could you provide more details on your use case?

**Comment by michaelisvy** [comment]
thanks for the quick feedback.
In [here](https://github.com/michaelisvy/springboot-auth-samples/tree/master/src/main/java/com/auth0/samples/authapi/springbootauthupdated), I tried to write all the Spring Security configuration needed for a "hello world" resource server with JWT token (folders `security` and `user`) (*).
That's 8 classes / interfaces in total.
I was thinking that Spring Boot could have an opinionated configuration for a default JWT token implementation, default expiration time etc. 

(*) based on the auth0 blog [here](https://auth0.com/blog/implementing-jwt-authentication-on-spring-boot/)

Regards,
Michael.

**Comment by rwinch** [comment]
@michaelisvy Thanks for the report.

> I was thinking that Spring Boot could have an opinionated configuration for a default JWT token implementation, default expiration time etc.

Can you help me understand exactly what you are trying to remove?

Spring Security provides multiple implementations of `UserDetailsService`, so I don't believe the code in the [user package](https://github.com/michaelisvy/springboot-auth-samples/tree/master/src/main/java/com/auth0/samples/authapi/springbootauthupdated/user) is necessary.

Spring Security also provides support for [resource servers](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2resourceserver). This means that you should not need [JWTAuthorizationFilter](https://github.com/michaelisvy/springboot-auth-samples/blob/master/src/main/java/com/auth0/samples/authapi/springbootauthupdated/security/JWTAuthorizationFilter.java).

Spring Security does not have plans for supporting Authorization Server side (i.e. JWTAuthenticationFilter) because to do so it would require Spring Security to provide a library/product rather than framework code. See https://spring.io/blog/2019/11/14/spring-security-oauth-2-0-roadmap-update

**Comment by michaelisvy** [comment]
thanks Rob for clarifying!
Originally I was hoping that it could be possible to to provide some easy and default setup in the way that Spring Boot does for Transactions.
I understand that things are a bit more complicated for a Spring Security backend because there are so many choices to be made (OAUTH2 or not, which library to generate JWT tokens, where should users and roles be stored etc).

I'll close my issue.
