### ISSUE TITLE
Regarding jbpm project with spring boot

### ISSUE THREAD

**Issue by testarunsharma** [spring-projects/spring-boot#19145]
Hi Team,
Currently i am trying to Run JBPM  with Spring boot with tomcat(Not jboss) using .bpmn  file. 
I am facing many issues. Could you please help me regarding the below points.
1- How load .BPMN file in spring boot.
2- what are the maven dependency required.
3- how start start process,human task etc.

It will be really helpfule if any one able to share running code including below points
Regards
Arun Sharma

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
