### ISSUE TITLE
BeanDefinitionRegistryPostProcessor doesn't work as expected with SpringBootTest and MockBean

### ISSUE THREAD

**Issue by luchob** [spring-projects/spring-boot#19147]
**Spring boot version:** 2.2.1.RELEASE

**Java version:**
```
$java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```
**OS:** MacOS Catalina 10.15.1

**Sample project reproducing this issue:** [here](https://github.com/luchob/spring-autowire-bug)

**Description:**

We are using the `BeanDefinitionRegistryPostProcessor` to register some bean definitions based on an environment configuration. Everything works fine, as seen in the sample project. But if we use `@SpringBootTest` with a `@MockBean` the beans cannot be wired anymore:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'senko-bean': Unsatisfied dependency expressed through constructor parameter 1: Ambiguous argument values for parameter of type [com.example.demo.TimeProvider] - did you specify the correct bean references as arguments?
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:774)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:226)
```

**How to reproduce:**

1. Clone the sample project
2. Run `./gradlew test` from the projects directory
3. One test passes (without `@MockBean` the other fails).

**Comment by wilkinsona** [comment]
Thanks for the sample.

`@MockBean` is implemented via a `BeanFactoryPostProcessor`, `MockitoPostProcessor`, which needs to determine the name of the bean that should be mocked as you haven't specified it. This requires creation of `DynamicBeanFactory`. Its definition only defines one of the two required constructor arguments so it relies upon `AutowiredAnnotationBeanPostProcessor` to provide the second constructor argument. `AutowiredAnnotationBeanPostProcessor` hasn't been registered at this point as we're post-processing the bean factory which is the step before registration of bean post-processors in the application context refresh process. As a result, refresh fails with the exception you've noted above.

It's not clear to my why you're using a factory bean to provide your dynamically defined beans or why you're only providing one of the two constructor arguments. The problem could be avoided by creating a definition for a `DynamicBean` directly rather than using an intermediate `FactoryBean` or by providing both constructor arguments. Alternatively, you can tell `@MockBean` the name of the bean that you want to be replaced with a mock to avoid it having to create the `DynamicBeanFactory` to determine the type of bean that it produces:

```
@MockBean(name="timeProvider")
```
