### ISSUE TITLE
Non-public property in Saml2RelyingPartyProperties' Registration class

### ISSUE THREAD

**Issue by sbattistin** [spring-projects/spring-boot#19194]
I was trying to use the properties set in the YAML file through the `Registration` class inside `Saml2RelyingPartyProperties` class.

The problem is that the method has only package visibility and is not public.

```
		public Signing getSigning() {
			return this.signing;
		}

-->		Identityprovider getIdentityprovider() {
			return this.identityprovider;
		}

		public static class Signing {
```

P.S. I'm not sure if there is a reason to not make this public.

**Comment by sbattistin** [comment]
I opened this PR if needed: https://github.com/spring-projects/spring-boot/pull/19195

**Comment by wilkinsona** [comment]
As noted on #19195, `@ConfigurationProperties` classes are not considered to be public API. We should use this issue to address the inconsistent visibility of the getters but the result may be that `getSigning()` is made package-private rather than `getIdentityprovider` being made public.

**Comment by woodforda** [comment]
Hi, just a comment regarding use cases for using the internal config properties classes.  I too have stumbled yesterday into this visibility issue.  I have a use case where the powers decreed that all config must be in TypeSafe format (sadly) not yml/properties.    So I have an EnvironmentPostProcessor to add the property sources for the TypeSafe config in the correct order.  So far so good.   My issue comes when I try to let Boot Auto config properties.  Simple primitive bindings work ok.  However, trying to bind an object (like a list of registrations) doesn't work (I end p with a list of a map and later a class cast exception).  I therefore need to transform the properties to the config class in my bean config class.  Sadly, this is not possible due to the visibility.  So now I'm a bit stuck...

**Comment by wilkinsona** [comment]
@woodforda Thanks for the additional use case. That sounds like something isn’t quite right in your environment post-processor. If you map the keys in the same way as Boot does for YAML or properties files, the binding should work without the need for any further transformation. I’d recommend comparing the contents of the property sources when you have equivalent TypeSafe or YAML/properties configuration to help to diagnose the problem.

I’ve opened https://github.com/spring-projects/spring-boot/issues/19199 to straighten out the contradictions in the documentation. Thanks for pointing it out.

**Comment by woodforda** [comment]
@wilkinsona You're welcome.  Yep I understand the issue - just trying to ignore the the invitable - Spring would happily convert all for me but this happens (I assume) as you you populate the property source - the TypeSafe puts, by default, a Map in.  So I would have to write a converter in the TypeSafe world to do it and put the result in the property source.  But would like to avoid coding something that Spring would do out of the box.  However I suspect I have not many choices.   However, not quite the topic of this ticket :) but thanks!

**Comment by snicoll** [comment]
> We should use this issue to address the inconsistent visibility of the getters but the result may be that getSigning() is made package-private rather than getIdentityprovider being made public.

`@ConfigurationProperties` are public across the codebase as far as I know. Marking it package private is a signal for the annotation processor to determine this isn't a property to generate metadata for. In this very case, `Registration` is the value of a Map so no metadata is generated at this point. For consistency, I think it should be flagged public.

That doesn't mean this API is meant to be called directly, as [documented in the reference documentation](https://docs.spring.io/spring-boot/docs/2.2.3.BUILD-SNAPSHOT/reference/html/spring-boot-features.html#boot-features-external-config-typesafe-configuration-properties) (updated).
