### ISSUE TITLE
Cross domain issues

### ISSUE THREAD

**Issue by lichengliang1** [spring-projects/spring-boot#19204]
How can I use OAuth + security to implement single sign on to solve cross domain problems...

as follows：

Access to XMLHttpRequest at 'http://localhost:8090/platform/system/message/newMessage' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
