### ISSUE TITLE
Add Liquibase "tag" property support

### ISSUE THREAD

**Issue by junaid155** [spring-projects/spring-boot#19200]
Please add a new property with name  **tag** in `org.springframework.boot.autoconfigure.liquibase.LiquibaseProperties`. Also update `LiquibaseAutoConfiguration.java` to set tag property in `SpringLiquibase` bean. 

This property will help in generating roll back scripts for particular tags only when user has specified `rollbackFile` property.

**Comment by eddumelendez** [comment]
I can work on this issue :)

**Comment by mbhave** [comment]
Thanks @eddumelendez! I've assigned it to `spring-contributor.`

**Comment by junaid155** [comment]
@eddumelendez  it will be better if we have separate tag property for generateRollbackFile and performUpdate method in SpringLiquibase.java.

**Comment by eddumelendez** [comment]
@junaid155 thanks, but `SpringLiquibase` only offers `tag` property for `generateRollbackFile` and `performUpdate`. The execution depends basically if property `rollbackFile` is set or not. So, I can not have separate properties for each one. 

Now, that you said that I just want to make sure if what you are expecting is a sql file as an output which will be in this case. That means the rollback is not executed automatically. I found this thread #1826 

I think we can set the use cases right here and evaluate them. Otherwise, some questions can raise for different flows. WDYT?

**Comment by junaid155** [comment]
@eddumelendez  Thanks, My major concern is that i want to generate roll back scripts till particular tag only. just like liquibase command `liquibase   rollback=3.0.1 `

**Comment by philwebb** [comment]
Closing in favor of PR #19316

**Comment by snicoll** [comment]
@junaid155 I am looking at the PR and I am very confused how that feature actually works. I am looking at the liquibase forum and I can see some users confused as well. I am not keen to merge the PR as is as I'd like to understand the use case a bit better. 

Would you please rephrase the use cases you had in mind? It looks like to me this is something you'd like to apply once and not a property you'd hardcode in your configuration.

**Comment by snicoll** [comment]
@junaid155 gentle ping for the question above.
