### ISSUE TITLE
Where is the custom tag description file placed in the project?

### ISSUE THREAD

**Issue by baiyapeng** [spring-projects/spring-boot#19344]
In the old way, we put custom taglib description file at WEB-INF/xxx.tld, and JSP files load this file with <%@taglib prefix="xxx" uri="/META-INF/xxx.tld"%>

When we use Spring boot and config the application completely with java code (no web.xml, xxx-servlet.xml etc.), where to put it?

under resources/WEB-INF? or resources/META-INF?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
