### ISSUE TITLE
Autoconfigure Type Converter Implementations on Cassandra Cluster

### ISSUE THREAD

**Issue by michaelmcfadyen** [spring-projects/spring-boot#19374]
_This is in regards to the auto configuration of the cassandra cluster_

The cassandra driver provides an interface named `TypeConverter` that defines how to convert a cassandra type to a java type. There are default implementations for most common java types but the interface is there to allow the user to define their own. These need to be registered with the Cluster Builder.

Currently, this is achievable by providing your own implementation of `ClusterBuilderCustomizer` that adds your custom type converter to the cluster builder. However, can this step be cut out by automatically adding all `TypeConverter` beans to the cluster builder?

**Comment by mbhave** [comment]
@michaelmcfadyen Could you provide a snippet of how you're configuring the `TypeConverter`s on the `Builder` using the customizer? I feel that the customizer is good way to add additional configuration to the `Builder` but in case it turns out that the code for adding the `TypeConverter`s is tedious, we can consider simplifying it.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
