### ISSUE TITLE
Server Sent Events (SSE) stopped working on Spring Boot v2.2

### ISSUE THREAD

**Issue by deeDude** [spring-projects/spring-boot#19405]
In my JS client app I am using [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) web API  to connect to my SSE endpoint. This SSE endpoint uses Spring MVC SseEmitter and it simply creates an instance of the latter and returns it, as you can see below in Kotlin language:

```
var emitter: SseEmitter

@GetMapping("/alerts", MediaType.TEXT_EVENT_STREAM_VALUE)
    fun alerts(): SseEmitter {
        emitter = SseEmitter()
        return emitter
    }
```
This works fine using Spring boot v2.1 and below, i.e., the EventSource client is able to successfully connect to the SSE endpoint. But with Spring Boot v2.2, an HTTP 406 error happens and in the server logs I can see the following exception: `HttpMediaTypeNotAcceptableException ` and the EventSource is unable to recover.

**Comment by wilkinsona** [comment]
@deeDude Thanks for the report. Unfortunately, without knowing some more about your application and the exact request that is receiving a 406 response, it's unlikely that we'll be able to help you. Can you please provide a small sample application that works with Spring Boot 2.1 and fails when upgraded to 2.2 so that we can investigate?

**Comment by deeDude** [comment]
Hi @wilkinsona I actually stumbled accross this [issue](https://github.com/spring-projects/spring-framework/issues/23821) on spring-framework repo. So, I guess I can reuse this [demo](https://github.com/jukkasi/spring-boot-sse) provided by @jukkasi, since the code on that demo it is quite similar to mine. 

As far as I understood by the comments on the aforementioned issue, the developers using spring-boot v2.2 should implement some kind of workaround to mitigate  the `HttpMediaTypeNotAcceptableException`, like, for example, send an event before the timeout occurs? Is this interpretation correct?

Thanks

**Comment by wilkinsona** [comment]
Yes. That’s correct.

**Comment by deeDude** [comment]
> Yes. That’s correct.

@wilkinsona So, this means that spring-boot v2.2 is not backwards compatible?

**Comment by wilkinsona** [comment]
It really depends what you mean by not backwards compatible and there's always a balance to be struck. We don't aim for minor releases for be 100% backwards compatible but for the upgrade to be fairly painless.

The behaviour of Spring MVC has certainly changed in this area in Spring Framework 5.2 (and therefore in Spring Boot 2.2). This was done to [fix an inconsistency and align its behaviour with WebFlux](https://github.com/spring-projects/spring-framework/issues/21972). I can't speak for the Framework team, but I suspect that they made the change in 5.2 as they felt that it was too big a change to make in a maintenance release but one that was working making in 5.x rather than waiting for 6.0.
