### ISSUE TITLE
Ask BackgroundPreinitializer

### ISSUE THREAD

**Issue by dngzs** [spring-projects/spring-boot#19402]
hi, I am relatively stupid. I would like to ask. BackgroundPreinitializer has done some time-consuming operations. Maybe these time-consuming operations have newly created some objects. How does springboot apply these components? Can you tell me about the delay Your precious time

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

This is not a stupid question at all; but I fail to really understand it completely here. We're using the `BackgroudPreinitializer` to parallelize a bit the startup process: using a different thread to initialize heavy components and improve startup time. You can [learn more about it in the source code directly](https://github.com/spring-projects/spring-boot/blob/dabb9b89c7dc541dd64deeaee7e778c3777cbd66/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/BackgroundPreinitializer.java#L94-L99). For more questions, please create a new questions on StackOverflow and feel free to point us to it. Thanks!

**Comment by dngzs** [comment]
Thank you
