### ISSUE TITLE
No JMX mbeans found of springboot2's embeded tomcat.

### ISSUE THREAD

**Issue by ramonli** [spring-projects/spring-boot#19408]
We have upgraded our system to springboot2(springboot-2.2.2+ springCloud-Hoxton.RELEASE), and found that there were no any Tomcat related JMX mbeans. Below is what I got when connect to my local application by jvisualvm:
![image](https://user-images.githubusercontent.com/1152328/71227410-12d08a00-231a-11ea-8ea7-9dce00f3b205.png)

Also I implemented a springboot2(v2.1.1) demo, it was ok, tomcat‘s JMX mbeans works well. The strange thing is there are 2 tomcat.
![image](https://user-images.githubusercontent.com/1152328/71227694-0993ed00-231b-11ea-95db-99fb9c4c329f.png)
![image](https://user-images.githubusercontent.com/1152328/71227395-064c3180-231a-11ea-8a62-6f0ba058a480.png)

As I have implemented a Endpoint to monitor the thread pool of tomcat, which completely depends on JMX of tomcat, now it doesn't work any more. Please help, is there any way to enable the JMX of tomcat with springboot-v2.2.2?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Please make sure to review [the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#jmx-now-disabled-by-default) when upgrading. There is a section that states JMX is now disabled by default.
