### ISSUE TITLE
The created time of the log file never change when rolling file

### ISSUE THREAD

**Issue by kunlk** [spring-projects/spring-boot#19411]
I noticed that the created time of the log file never changed after the jvm started at the first time.

For example, I started my java application at ‎December ‎19, ‎2019, ‏‎6:29:16 PM. The first log app.log generated with the created time : ‎December ‎19, ‎2019, ‏‎6:29:16 PM.

Then on Dec 20, if I restarted java application, the rolling file was named as app.log_2019-12-19-1, the created time sill is December ‎19, ‎2019, ‏‎6:29:16 PM, but it's rolling on Dec 20.  And I would expect the file name should be app.log_2019-12-20-1.

log4j version: spring-boot-starter-log4j2 2.2.1.RELEASE

Can you pls take a look if it's a bug  ?

**Comment by wilkinsona** [comment]
The behaviour will depend on how you have configured Log4j2 and exactly how its support for rolling files has been implemented. Both are out of Spring Boot’s control.

If you would like some help with understanding Log4j2’s behaviour and why it is apparently not behaving as you would expect, please ask a question on Stack Overflow. As with https://github.com/spring-projects/spring-boot/issues/19330, if you do so please include a   [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) so that anyone trying to help you has all the information that they need to do so.
