### ISSUE TITLE
How to pass client cert from client to server in spring boot for mutual ssl authentication

### ISSUE THREAD

**Issue by karnamgit** [spring-projects/spring-boot#19488]
Let me explain the background first;

We have one service(server) which is running on https and having some rest end points .
We have another service(client) which is also running on https.
We need to make rest call from client service to server service by cert authentication. To send certs we have used command line args -javax.net.ssl.keyStorePassword=secret to attach the cert in the rest call. It works fine but this is one of the security vulnerability , because if we do ps command it will show the password .
So want to avoid password passing from cmd line arg .
So looking for simple bootstrp.yml configuration like below;
`javax: net: ssl: keyStorePassword: secret`
javax.**** properties are not defined in the spring boot strap yml config. so it is not allowing this property .
link: https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
through grammatically below is the configuration , and it works fine:

`System.setProperty("javax.net.ssl.keyStore", Thread.currentThread().getContextClassLoader().getResource("client-keystore.jks").getPath()); System.setProperty("javax.net.ssl.keyStorePassword", "secret");`

any best simple configuration techniques apart from command line and programmatic ? appriciate your suggestions/help.

Thanks

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
