### ISSUE TITLE
After Loading the Application context object created through new operator was not loading all the instance variables

### ISSUE THREAD

**Issue by YUVATHA143** [spring-projects/spring-boot#19555]
Hi,

After loading the context  through application.xml. Then autowired annotation is working when the object is created through context. Otherwise if we created component object with new Operator autowired property is not working.

**Comment by wilkinsona** [comment]
>  Otherwise if we created component object with new Operator autowired property is not working.

This is the expected behaviour. If you create the object yourself using `new` then Spring does not know about the object and cannot, therefore, inject dependencies into it.

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
