### ISSUE TITLE
Spring Boot 2.1.10.RELEASE Causes RabbitMQ / AMQP Connection Resets

### ISSUE THREAD

**Issue by brianwyka** [spring-projects/spring-boot#19585]
Issue begins starting in version `2.1.10.RELEASE` of spring boot and corresponding Spring Rabbit / AMQP dependencies.

**These errors repeat themselves in the logs infinitely:**

```txt
Attempting to connect to: [***]
Restarting Consumer@3f954424: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
[AMQP Connection ****:****] An unexpected connection driver error occured (Exception message: Connection reset)
```

These errors begin during server startup.

### Workaround
Downgrading to version `2.1.9.RELEASE` resolves the issue.  I tried figuring out which library upgrade in AMQP / Rabbit caused this, but I was unable to pin it down.

**It may be that the issue was introduced in one of the following library version upgrades:**

- `spring-amqp:2.1.11.RELEASE` > `spring-amqp:2.1.12.RELEASE`
- `spring-rabbit:2.1.11.RELEASE` > `spring-rabbit:2.1.12.RELEASE`
- `spring-integration-amqp:5.1.8.RELEASE` > `spring-integration-amqp:5.1.9.RELEASE`

These are just speculation, but my best guesses at a smoking gun.

**Comment by mbhave** [comment]
@brianwyka Are you seeing the same issue with Spring Boot `2.1.11.RELEASE`? If so, could you provide a small sample that we can run to reproduce the issue?

**Comment by brianwyka** [comment]
Yes, I see the same issue with `2.1.11.RELEASE`.  I don't have a sample unfortunately since this is part of a larger project.  However, here is what we are declaring for dependencies:

Spring Cloud Stream: `Greenwich.SR4`

```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
        </dependency>
```

```yaml
spring:
  rabbitmq:
    ssl:
      enabled: false
    addresses: amqp://guest:guest@localhost:5672
    connection-timeout: 4000
```

**Comment by mbhave** [comment]
@brianwyka I tried reproducing this locally using the example in the [Spring Cloud Stream Reference Docs](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_quick_start) and I was able to see the application connect to my locally running RabbitMQ server. 

I don't think there's much we can do without a sample that reproduces the error. If you're able to extract out the bits of your application that cause this error, it's probably a good idea to raise it in the Spring Cloud Stream Issue Tracker. If it turns out that it is indeed a bug in Spring Boot, we can reopen the issue.
