### ISSUE TITLE
Documentation symlinks for 2.1.x not updated anymore

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#19634]
The symbolic links  on docs.spring.io are not updated properly anymore:

```
21 Jan 11 09:20 2.1.x -> 2.1.12.BUILD-SNAPSHOT
20 Jan 11 09:20 2.1.x-SNAPSHOT -> 2.1.9.BUILD-SNAPSHOT
```

The `2.2.x` seems legit:

```
13 Jan 11 09:20 2.2.x -> 2.2.2.RELEASE
20 Jan 11 09:20 2.2.x-SNAPSHOT -> 2.2.3.BUILD-SNAPSHOT
```

`2.3.x-SNAPSHOT` and `current-SNAPSHOT` points to the Gradle snapshot so something to look at as well:

```
Jan 11 09:20 2.3.x-SNAPSHOT -> 2.3.0.GRADLE-SNAPSHOT
```

**Comment by wilkinsona** [comment]
The 2.1.x problem looks like an alphabetical comparison of `9` and `10`, `11`, `12` rather than numeric. If so a change to the script on the docs server will be needed to fix that one.

The `GRADLE-SNAPSHOT` problem is probably because `GRADLE` is alphabetically after `BUILD`. Deleting the `2.3.0.GRADLE-SNAPSHOT` directory should fix it when the docs are next deployed.

**Comment by snicoll** [comment]
Good catch. I've fixed those by hand for the time being and removed `2.3.0.GRADLE-SNAPSHOT`.

**Comment by wilkinsona** [comment]
I think this has been fixed as part of the autoln stuff on the docs server being rewritten.
