### ISSUE TITLE
Failing to build spring-boot

### ISSUE THREAD

**Issue by Avatair** [spring-projects/spring-boot#19759]
Building of Spring boot fails due to messages:
> Task :spring-boot-project:spring-boot-devtools:checkFormatMain FAILED
> Task :spring-boot-project:spring-boot-properties-migrator:checkFormatTest FAILED
> Task :spring-boot-project:spring-boot-actuator-autoconfigure:checkFormatMain FAILED
> Task :spring-boot-project:spring-boot-autoconfigure:checkFormatTest FAILED

**Comment by wilkinsona** [comment]
Our CI builds (which run those tasks) are all green at the moment, so I suspect the problem is specific to your environment or to changes that you have made. Can you please share some more details about your environment and any changes that you have made to the code prior to running the build?

**Comment by dreis2211** [comment]
If I may add something: Could you check your line endings, @Avatair?

**Comment by Avatair** [comment]
@wilkinsona I downloaded the code and started the build immediately using 'gradlew build' without any changes to the code. JDK 1.8.0_231 is used and the path and java home environment variables are set to it. Also I use Windows 10 with latest updates.

@dreis2211 Line endings are simple LF characters.

**Comment by wilkinsona** [comment]
Thanks for the additional information. We have a Windows CI job that is green so I still believe that the problem is specific to your environment.

How did you download the code? Did you perform a git clone, or download and unpack a source zip from GitHub? I would recommend the former. You may also need to configure Git to handle line ending correctly. Our Windows CI is [configured to use autocrlf](https://github.com/spring-projects/spring-boot/blob/421c464dd8771c735ba63b48456ff2cea90b28f4/ci/pipeline.yml#L38).

If you did use git to clone the source, it would also be useful to know what `git status` shows.

**Comment by Avatair** [comment]
The autocrlf in git configuration seems to have fixed the upper issue :)

I used git clone. The git status reports, that the working tree is up-to-date with master for both cases, by enabling the autocrlf feature or disabling it.

The building is now failing at another place in some unit tests, which might be possibly a side effect of the CRLF correction. I will investigate it now. In case you are interested, these are the failure messages:
RepackagerTests > index() FAILED
    java.io.IOException at TempDirectory.java:211

RepackagerTests > layeredLayout() FAILED
    java.io.IOException at TempDirectory.java:211

**Comment by wilkinsona** [comment]
That's good news. Thanks for letting us know.

Those may be genuine failures. The Windows CI job runs nightly and those tests were added since it last ran. I suspect they're leaking a file. On Windows, that prevents the temp directory from being cleaned up.

**Comment by Avatair** [comment]
Thank you for your help.
