### ISSUE TITLE
Ant smoke tests do not seem to run tests

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#19806]
Hi,

I initially was looking into a warning in the build caused by `spring-boot-smoke-test-ant` not setting `includeantruntime` to false, which could be fixed by the following patch.

```patch
--- a/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-ant/build.xml
+++ b/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-ant/build.xml
@@ -29,7 +29,7 @@
        </target>

        <target name="compile" depends="init" description="compile">
-               <javac srcdir="src/main/java" destdir="build/ant/classes" classpathref="compile.classpath" />
+               <javac srcdir="src/main/java" destdir="build/ant/classes" classpathref="compile.classpath" includeantruntime="false" />
        </target>
```

But when looking a bit further into the smoke test, I noticed that the test `SampleAntApplicationIT` doesn't seem to be run at all. Is this intended? I was trying to dig into this a bit, but couldn't fix this. I have the feeling I'm overlooking something very simple here.

Hopefully you have more luck.

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Well spotted. Thank you, Christoph. The problem is caused by the test task not being configured to use the JUnit Platform. That should have been done by the conventions plugin, but the smoke test applies the `java-base` plugin rather than the `java` plugin and the conventions plugin only reacts to the latter and not the former. This also meant the project was missing out on Spring Java Format and Checkstyle.
