### ISSUE TITLE
Support maven reproducible build feature for repackage

### ISSUE THREAD

**Issue by reitzmichnicht** [spring-projects/spring-boot#20176]
Maven introduced with the latest updates the feature to generate reproducible jars.
https://maven.apache.org/guides/mini/guide-reproducible-builds.html

It would be great if the repackage goal of the spring boot plugin would reuse the property `<project.build.outputTimestamp>` if available and use it for the fatjar timestamp and the zip contents itself.

This is the last obstacle of getting binary equivalent  outputs for building the same git revision.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. It's something that our Gradle plugin already supports so it makes sense to support it with Maven as well.

**Comment by wilkinsona** [comment]
Maven's war plugin does not make use of `<project.build.outputTimestamp>` so we cannot support this for war packaging.

**Comment by Jurrie** [comment]
Sorry for commenting on a closed issue, but I think this needs to be reopened. I believe the maven-war-plugin is fixed because of [MWAR-432](https://issues.apache.org/jira/browse/MWAR-432) and [MWAR-436](https://issues.apache.org/jira/browse/MWAR-436). The most recent version supports `<project.build.outputTimestamp>` as far as I can tell. Is there something else that's holding back this issue? Should I open a different issue instead?

**Comment by wilkinsona** [comment]
@Jurrie Please open a new issue and we can take a look at supporting this with war files now as well.
