### ISSUE TITLE
Error while using spring-boot-starter-data-jdbc with spring-boot-starter-data-redis

### ISSUE THREAD

**Issue by Sonedo** [spring-projects/spring-boot#20215]
**Environment**:
-  kotlin version 1.3.61
- spring boot parent 2.2.4.RELEASE

It's work in case when i use only spring-data-jdbc. I get this error in case when i add redis dependency in maven and run app. 

> Parameter 0 of constructor in com.sonedo.dictionary.service.DictionaryService required a bean of type 'com.sonedo.dictionary.repository.DepartmentRepository' that could not be found.

`interface DepartmentRepository: CrudRepository<Department, Int>`

`@Service
class DictionaryService(
val departmentRepository: DepartmentRepository,
val gradeRepository: GradeRepository
)`

**Comment by wilkinsona** [comment]
I'm pretty sure that this is happening because you haven't given Spring Data enough information to identify whether `Department` and `DepartmentRepository` should be handled by Data JDBC or Data Redis. There should be an info level log message to that effect that recommends adding an annotation (`@Table` in the JDBC case) to your entity.

If that's not the case and you'd like us to spend some more time investigating, please take the time to provide a small sample that reproduces the behaviour you are seeing and we can re-open this issue and take another look.

You may also be interested in https://github.com/spring-projects/spring-boot/issues/19373. It is tracking some possible improvements to the diagnostics in such multi-store scenarios.
