### ISSUE TITLE
@Transactional is invalid; transaction has no effect;

### ISSUE THREAD

**Issue by cielswift** [spring-projects/spring-boot#20261]
spring boot 2.0.7
It seems that aop is not working, but no error can be seen in the method;

this is project https://gitee.com/CielSwift/mplearns-parent.git

access 127.0.0.1:8081/web/test_transaction ;

![image](https://user-images.githubusercontent.com/42295829/75036978-10dba080-54ee-11ea-92c6-7c6564c2e163.png)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by cielswift** [comment]
What? Are you serious? The bean can be obtained from the container, the method is also public, and the controller calls the service, and the @Transaction of the service does not work. Is this not a bug?

**Comment by snicoll** [comment]
> What? Are you serious?

Yes. Sharing your complete project with a transaction manager (mybatis) we don't even handle here feels like a question to me. If you believe you've found an issue in Spring Boot, then we'll need a minimal sample in the form of a small project that reproduces the problem, preferably without the use of mybatis.
