### ISSUE TITLE
Provide a way to customize layers with the Gradle plugin

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#20296]

**Comment by wilkinsona** [comment]
There's no easy and reliable way for us to map from `BootJar`'s `classpath` (a `FileCollection`) to Maven coordinates. There's no guarantee that every jar on the classpath has come from a Maven repository and even for those that have, there's no guaranteed link between the `FileCollection` that represents the classpath and the `Configuration` (from which we could get a dependency graph) that populated it.

The above is the same problem as we had with requires unpack which is why it's configured using a `Spec<FileTreeElement>` which is passed the `FileCopyDetails` for each jar file that's been added to the jar. I think we'll have to do something similar for layer customization with Gradle.
