### ISSUE TITLE
proxyTransactionManagement  

### ISSUE THREAD

**Issue by vishnukanth-chittayala** [spring-projects/spring-boot#20392]
Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$fb062e21] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-03-05 12:40:37 - Tomcat initialized with port(s): 8080 (http)

**Comment by snicoll** [comment]
I can only assume based on the partial description that it is a duplicate of https://github.com/spring-projects/spring-framework/issues/24508

**Comment by vishnukanth-chittayala** [comment]
Yes I modified the title so IAM guessing it became a duplicate so how can I
solve this

**Comment by snicoll** [comment]
@vishnukanth-chittayala please take the time to review the information I provided before commenting. This is a an info message for a start so I don't know what you'd like to fix. The link I provided also states this was fixed in Spring Framework `5.2.4` so the latest Spring Boot version should have that too.

**Comment by vishnukanth-chittayala** [comment]
Thank you so much for your concern Iwill work on it and I will try to solve
issues I will follow the link you provided
