### ISSUE TITLE
Add support for Mongeez

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#2040]
Mongezz is a Document Change Management like Liquibase for RDBMS but for MongoDB.

For more information: http://secondmarket.github.io/mongeez/

**Comment by mkhanal** [comment]
Any updates on this ?

**Comment by philwebb** [comment]
@mkhanal It's not on the immediate roadmap for 1.3 I'm afraid.

**Comment by eddumelendez** [comment]
I am going to work on this.

**Comment by philwebb** [comment]
@olivergierke any experience with Mongeez? @wilkinsona Any concerns about adding this from a platform perspective?

**Comment by olivergierke** [comment]
I am not particularly opposed to this but I don't see much advantage over simply having a component that uses `MongoOperations` to execute what you would write into an XML file in Mongeez. The former even has quite some advantages over the latter:

- Type-checked execution of functionality
- Exception translation
- Support for POJOs (to make sure we create documents that match the application schema and registered custom conversions)

Staying with core Spring Boot means also allows you to use Spring Data repositories for initialization etc. I haven't seen much usage of Mongeez in the wild, probably because most of the Mongo usage we see is on top of Spring Data MongoDB so that this custom solution is sort of obsolete.

**Comment by wilkinsona** [comment]
I have a couple of concerns from a Platform perspective:

 - The last release was in September 2013 and the last commit was in October 2014. That wouldn't be a problem if the project was "finished", but that doesn't appear to be the case. For example, a schema for the XML files is described as work in progress
 - It depends on Mongo Java Driver 2.11.x. We'd need to be sure it works with newer 2.x drivers, and also that it'll continue to work with Mongo 3.0 which we'll want to become the default in Boot at some point.

In terms of the functionality, Mongeez allows you to use discrete changesets so you can migrate a database to the latest content from different starting points. That's quite a valuable addition over rolling your own with `MongoOperations`, imo.

**Comment by olivergierke** [comment]
What if added this as request for enhancement for Spring Data MongoDB? It doesn't look like too much code and maybe we can add a more Java-driven variant (maybe even like Flyway but simpler) of the XML flavor? We could get in touch with the authors of Mongeez an see whether they're interested in contributing.

**Comment by wilkinsona** [comment]
+1 – that sounds like the best of both worlds to me

**Comment by olivergierke** [comment]
I've created [DATAMONGO-1241](https://jira.spring.io/browse/DATAMONGO-1241) for further reference.

**Comment by philwebb** [comment]
Given the comments above I'm going to close this one and we'll go with DATAMONGO-1241 instead. Thanks for the suggestion @eddumelendez.

**Comment by hzpz** [comment]
I would love to see such a feature in Spring Data MongoDB. In the meantime however, Mongeez seems to be doing a good job. So I took the liberty and created a Spring Boot auto-configuration for Mongeez: [spring-boot-autoconfigure-mongeez](https://github.com/hzpz/spring-boot-autoconfigure-mongeez).

**Comment by snicoll** [comment]
Thanks for the pointer @hzpz  - Could you please rename your starter so that it does not start with `spring-boot`. Thanks!

**Comment by hzpz** [comment]
Did I take too much liberty? Care to elaborate? Don't you want me to use `spring-boot` at all or just as prefix?

**Comment by philwebb** [comment]
We've been trying to steer people away from using `spring-boot-starter-*` so that the names remain available for us to use later. A lot of people use content-assist in their Maven/Gradle build and just type the name of the artifact, ideally we don't want different `groups` offering the same starter.

Using `spring-boot` elsewhere in the name is fine.

**Comment by hzpz** [comment]
That's the exact same reason why I used this name ;-) (without the `-starter` part by the way). 

Any advice on how to remove the artifact from Central? It seems like this is not supposed to happen.

**Comment by snicoll** [comment]
@hzpz I just refined the policy. The original intention was not to name a 3rd party artifact `spring-boot` something since that prefix is reserved for the project.

You can't remove an artifact from central but if you rename your github project and push a new release we should be fine as nothing points to the old name. Let us know when you're done and we'll add you to [the list of 3rd party starters](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/README.adoc)

**Comment by hzpz** [comment]
Any objections on releasing the "new" artifact as version 1.0.0?

**Comment by snicoll** [comment]
I don't but I would rename the Github repository as well please.

**Comment by hzpz** [comment]
I did and even updated my comment above: https://github.com/hzpz/mongeez-spring-boot-starter. It seems like GitHub redirects the old name to the new one.
