### ISSUE TITLE
Flyway version not aligned with H2

### ISSUE THREAD

**Issue by gotson** [spring-projects/spring-boot#20405]
In the [`2.2.x` pom](https://github.com/spring-projects/spring-boot/blob/2.2.x/spring-boot-project/spring-boot-dependencies/pom.xml) the version of Flyway is `6.0.8`, while H2 is `1.4.200`.

Flyway explicitly support H2 `1.4.200` only from version [`6.1.0`](https://flywaydb.org/documentation/releaseNotes#6.1.0).

This leads to the following on each startup:
`2020-03-06 14:59:04.604  WARN 25449 --- [  restartedMain] o.f.c.internal.database.base.Database    : Flyway upgrade recommended: H2 1.4.200 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 1.4.199.`

There might be potential side effects that i am not aware of.

Is this intentional?

**Comment by wilkinsona** [comment]
Yes, this intentional.

In each branch of Spring Boot we strive to include the latest maintenance version of third-party dependencies without required a major or minor upgrade. For example, this means that each release of the 2.2.x branch will use the latest 1.4.x version of H2 and the latest 6.0.x version of Flyway available at the time of the release.

It’s unfortunate that Flyway 6.0.x does not recommend using it with the latest 1.4.x release of H2, but that is out of our control. We don’t want everyone to stay on an artificially old version of H2 just for those who are using Flyway and H2 together.

If Flyway 6.0.x is working for you with H2 1.4.200, you can ignore the warning. It is only a recommendation, after all. Alternatively, you can use the h2.version or flyway.version properties to override Spring Boot’s defaults to meet your needs.

**Comment by gotson** [comment]
Thanks a lot Andy for the clarification !
