### ISSUE TITLE
Add list of fixed values in the meta-data

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2054]
It would be nice if the IDE was able to auto-complete the list of possible values for a given key. There are actually two main use cases: `Enums` and "magic" strings (`shell.auth` is an example).

For an enum, we could rely on the fact that the actual `Enum` is on the classpath and parse it but that's not always the case and it seems fragile. 

The Jetbrains team started to define those values on their side which is bad since if we add a new value, they won't know about it and the enum can evolve as well (Spring Boot 1.x can have a 3-values enum while Spring Boot 2.x has 4 values for that enum).

The solution would be to add the list of "known/fixed" values to the meta-data in a `values` field that would be an Object array. We could harvest the enum ourselves but we need to find a way to define the possible values otherwise. Again, I am in favor of an annotation at field level that would complement the meta-data but we could also go with manual meta-data.

**Comment by snicoll** [comment]
@philwebb could you please review this and let me know what you think? (cc @kdvolder)

**Comment by kdvolder** [comment]
Don't attach too much weight to my opinion as I'm probably the least expert on Spring, Beans etc. in this group. But...

The idea of adding 'valueDomain' and 'keyDomain' etc. doesn't feel 'right' to me. Mainly I don't like how it takes out information that I feel belongs to the 'type' of a property, and attaches it as a separate thing to the property itself.

The way I think of it is that "logging.level" property is bound to something more specific than type Map<String,Object>. I.e. it is a map, but a 'specal kind of map'. The information about its 'specialness' should be expressed by augmenting the type the property is bound to rather than adding extra information alongside the type.

I am not sure this really matters, but it might if things are composed in a more complicated,nested way. For example if 'foo' property was bound to a bean where one of the subproperties was a map of logging levels. Let's say for example foo 'Bean' has a 'enable' property of type boolean *and* a 'log' property of type 'logging level map' (however we define what that is) so that these are valid

    foo.enable=true
    foo.log.com.acme=INFO

**Comment by kdvolder** [comment]
Afterthought... 

>  "logging.level" property is bound to something more specific than type Map

Maybe its not the 'map' type itself that is 'more specific' but rather the 'value' and 'key' in the map type.

It seems that for both values and keys you like to be able to be able to express they are either:
  - like an enum
  - like an arbitrary String but with some 'hint' values that have special meaning.

**Comment by kdvolder** [comment]
One more thought. I don't understand quite how 'domainType' would be interpreted. So I'm not sure it is well defined. It seems in the examples we are discussing we have two different interpetations being used. The 'logging.level' seems to be working differently than the 'bar.foos' example.

If 'logging.level' was interpreted in the same way as 'bar.foos' then 

       logging.level.something=INFO 

would be valid, but...

     logging.level.two.parts=INFO

would be invalid. I.e. the 'domainType' for logging.level map is the type of things assigned to values of the map, right? So we'd have to assign things like 'INFO' to the values of the map (rather than nested maps).

I mean... it is not valid to do this right?

    bar.foos.com.acme.name=Acme
    bar.foos.com.acme.counter=1

Problem is... if you can have arbitrary nesting, then how do you know at which of the '.' in the key you are actually starting to navigate into the values of the map rather than navigating the map's nesting levels?

So I guess this means if you are going to use this in content-assist and/or checking, then the metadata will need to somehow tell you that 'bar.foos' map is 'normal' map, but 'logging.level' map is a 'arbitrary nesting map'.

**Comment by snicoll** [comment]
I think there might be a bit of misunderstanding on your end regarding those two use cases.

`logging.level` is a map of _simple_ (i.e. _final_) object. So when you need to auto-complete the value, it's a final value. `logging.level.two.parts` is valid, you're just configuring the `two.parts`. key. You have to combine the `domainType` and the `type` to get the actual value. Read that as "the String-typed values are provided as hints but additional values are acceptable". If you take the `security.headers.hsts` example above, read that as "the values are provided as is and the user should choose one of them".

We can't ask our users to change their model just to _fit_ with the meta-data. They should be able to write whatever POJO design they want (as long as it's supported by the binder, i.e. the thing that injects the configuration values in the pojo). With that in mind, I believe that we have all we need, the real question is regarding the nested use case: should we document in the meta-data the `Foo` type (the value type of the map that isn't annotated with `@ConfigurationProperties`).

You get a point regarding the `domainType` semantic and Yann Ceron from Jetbrains had the exact same feedback. He gave me the example of using the list of possible profiles as a value or a key (we can harvest application-xyz): we would use a special "string" to represent such domain type (i.e. `spring.core.profiles`). Intellij IDEA has already smart completion for Content-type based value and they are "hard-coding" that "domain type" in a file on their own. For that last example, we should obviously try to inject a more dedicated type than String but it's not always possible....

**Comment by kdvolder** [comment]
> I think there might be a bit of misunderstanding on your end regarding
those two use cases.

Very likely :-)

I am sorry to say that after reading your explanation I still don't think I
understand
precisely how these 'nested' or 'non-nested' cases work.

Now I think I am seeing 3 different cases rather than 2:

  - logging.level: map is 'flat' and keys can have '.' in them
  - foo.bars: map contains objects and the '.' in the key navigate the
object's properties
  - arbitrary nested maps: (apparantly these exist as I have seen some
hints in the
    databinding source code, but I don't know of an example)

It might be easier to ask questions and discuss than exchanging emails once
a day.
Would you be willing to try and setup a skype chat sometime to get to the
bottom of it.

> We can't ask our users to change their model just to *fit* with the
meta-data.

Of course, I totally agree. I never suggested otherwise. But when I
implement a 'checker'
or 'content assister' based on the metadata I have to know what it means.
It can't sometimes mean one thing (e.g. nested maps) and other times
another
(flat maps with dots in keys).

So the metadata has to have a well-defined semantics. And to me that means
that
the meta-data can be interpreted so that it defines a kind of 'validation'
function
which decides whether a given 'prop=value' assignment is
to be considered 'valid' based on the metadata.

Kris

**Comment by snicoll** [comment]
alright, let's setup a Skype call next week, I'll ping you offline. I hope I'll be able to convince you by then that the property signature provides a well-defined semantics.

**Comment by philwebb** [comment]
This is a long thread, and I probably haven't understood it all but let me try to recap what problems we have and what we want to solve:

1). Completion for enum values
e.g `WebMvcProperties.messageCodesResolverFormat`. The user can types `spring.mvc.message-codes-resolver-format=<ctrl-space>` and the IDE should provide `prefix-error-code`, `postfix-error-code`.

2) Completion for enum keys in a map
e.g. `JacksonProperties.serialization`. The user can type `spring.jackson.serialization.<ctrl-space>` and the IDE should provide `wrap-root-value, indent-output, ...`.

3) Completion for 'magic' values
e.g. `ShellProperties.auth`. The user can type `shell.auth=<ctrl-space>` and the IDE should provide `simple, spring, key, jaas`.

4) Completion for `logging.level`
The user can type `logging.level.<ctrl-space>` and get the magic value `ROOT`. (we could also perhaps provide auto-complete for all package names on the classpath`.

I think that 4) is special and we should probably ignore it for now. I don't think it's that common and if we were to offer package auto-completion (much like eclipse does with the `import` keyword) we'd need special handling anyway.

Both 1) and 3) seem quite similar except that the source of the values is different. The resulting meta-data is probably identical.

The leaves 2), which I think is quite similar to the "nested property" problem that we already solve. I wonder if we can represent the completion of keys by simply adding additional properties:

```json
{
  "name": "security.headers.hsts",
  "type": "org.springframework.boot.autoconfigure.security.SecurityProperties$Headers$HSTS",
  "description": "HTTP Strict Transport Security (HSTS) mode.",
  "sourceType": "org.springframework.boot.autoconfigure.security.SecurityProperties$Headers"
},
{
  "name": "security.headers.hsts.none",
  "sourceType": "org.springframework.boot.autoconfigure.security.SecurityProperties$Headers$HSTS"
},
{
  "name": "security.headers.hsts.domain",
  "sourceType": "org.springframework.boot.autoconfigure.security.SecurityProperties$Headers$HSTS"
},
{
  "name": "security.headers.all",
  "sourceType": "org.springframework.boot.autoconfigure.security.SecurityProperties$Headers$HSTS"
}
```

The nice thing about this is that the existing IDE code should already be able to deal with these.

I'm tempted to ignore 3) which would just leave use the simpler problem of adding hints for specific types.

**Comment by philwebb** [comment]
I think we should push this back to 1.3 regardless.

**Comment by snicoll** [comment]
I agree with the 1.3 milestone. I think you miss an important use case (explained in [one of my commentes above](https://github.com/spring-projects/spring-boot/issues/2054#issuecomment-68245793))

The thread is getting quite long indeed and I am wondering if having a call with interesting parties wouldn't be the easiest. I can prepare a summary and send an invite.

**Comment by philwebb** [comment]
@snicoll Do we have any existing properties that follow the `Map<String, Foo>` pattern? 

Perhaps a call would be best, but it's going to be difficult for me this week.

**Comment by snicoll** [comment]
In XD/yarn they have that all over the place as far as I understood. That's why I am bringing it here. @jvalkeal does know.

**Comment by snicoll** [comment]
This is finally on master. #3303 will follow-up shortly for the complete solution based on providers.
