### ISSUE TITLE
Impact of @SpyBean on mybaits dynamic proxy

### ISSUE THREAD

**Issue by dngzs** [spring-projects/spring-boot#20555]
hi, ask a question, I am using @SpyBean and found that the mapper interface of the mybatis layer annotated by @SpyBean becomes
org.mockito.internal.creation.bytebuddy.MockAccess, how can I solve this problem and look forward to your reply

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
