### ISSUE TITLE
Update Gradle's layer configuration DSL to remove the double usage of layers

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20563]
The Gradle DSL for layer configuration currently uses `layers` twice:

```
bootJar {
    layers {
        layers "dependencies", "snapshot-dependencies", "application"
        …
    }
}
```

We'd like to simplify this to avoid the repetition of `layers`, hopefully to something like the following:

```
bootJar {
    layers("dependencies", "snapshot-dependencies", "application") {
       …
    }
}
```

**Comment by scottfrederick** [comment]
Unfortunately the suggested syntax does not work because it's not possible to pass a variable-length list of strings followed by a closure. This would require wrapping the list of layer names in an explicit array initializer `[ ... ]`, as in

```
bootJar {
    layers(["dependencies", "snapshot-dependencies", "application"]) {
       …
    }
}
```

This looks error prone, and the failure message provided by Gradle if the `[]` is omitted isn't very helpful.

Instead, we'll go with 

```
bootJar {
    layers {
        layersOrder "dependencies", "snapshot-dependencies", "application"
        …
    }
}
```

**Comment by wilkinsona** [comment]
Thanks, Scott. I agree on not using the `[]` syntax. I wonder if `layerOrder` would read better than `layersOrder`?
