### ISSUE TITLE
POST request with malformed json does not respond badrequest with spring boot 2.2.5

### ISSUE THREAD

**Issue by Tera** [spring-projects/spring-boot#20591]
Hi

With new spring boot version 2.2.5 under kotlin environment, if you perform a POST with a malformed json message, the system fails with an internal server error instead of a bad request error.

This problem affects only spring boot 2.2.5, with 2.2.4 works perfectly

Attaching a simple example project with a simple test to better demonstrate the issue

if you uncomment the line `id "org.springframework.boot" version "2.2.5.RELEASE" ` in build.gradle tests autometically fails

thanks

[TestBadRequest.zip](https://github.com/spring-projects/spring-boot/files/4359184/TestBadRequest.zip)

**Comment by wilkinsona** [comment]
Thanks for the report. The problem is caused by a regression in Spring Framework 5.2.4. It has been [fixed](https://github.com/spring-projects/spring-framework/commit/6df80a8f702e9555069ef4e7cb74fa036ac418e8) in 5.2.5 to which we will [upgrade](https://github.com/spring-projects/spring-boot/issues/20571) in due course.
