### ISSUE TITLE
Missing configuration for connection pool initial size

### ISSUE THREAD

**Issue by diegooliveira** [spring-projects/spring-boot#206]
I'm developing a application trough a slow network access to the database and loading the application was taking very long. Looking in the code I realized that the initialSize is always 10 and I couldn't find a configuration to change that value.

I did used the following parameters without success for the "initialSize".

spring.datasource.minIdle=1
spring.datasource.maxIdle=1
spring.datasource.initialSize=1

**Comment by srik-narisetty** [comment]
What about the other properties spring.datasource.minIdle and spring.datasource.maxIdle. I tried to set up. But, no impact of them.

**Comment by snicoll** [comment]
@srik-narisetty that issue is over a year old so whatever should happen next should happen in a separate issue. You haven't told us much about your setup (spring boot version, connection pool implementation, etc). In any case, please create a StackOverflow issue first unless you think this is a bug in Spring Boot.

**Comment by srik-narisetty** [comment]
Sorry. There is an impact. my bad. I was doing wrong integration testing which initiates pool for each test (i thought its a single context and number of connections to db are increasing more than max active). Thank you so much for your quick reply.
