### ISSUE TITLE
A new project using Spring Initializr does not run in browser

### ISSUE THREAD

**Issue by ksurendra** [spring-projects/spring-boot#20603]
Building a new project downloaded using `https://start.spring.io/` does not run on browser.
I have seen some solutions on stackoverflow which require to make some changes or add, but default/out-of-the-box application does not run.

`http://localhost:8080/`

<img width="674" alt="Screen Shot 2020-03-21 at 11 24 32 PM" src="https://user-images.githubusercontent.com/902972/77242316-329e7500-6bcb-11ea-9432-926285e7ddf4.png">

**STEPS TO REPRODUCE:**

Download new project at `https://start.spring.io/`

![screenshot-start spring io-2020 03 21-17_59_44](https://user-images.githubusercontent.com/902972/77242388-d7b94d80-6bcb-11ea-9ec5-6fcc87ccd2a5.png)

`mvn clean package`

![Screen Shot 2020-03-21 at 6 01 17 PM](https://user-images.githubusercontent.com/902972/77242256-a68c4d80-6bca-11ea-8725-18880642fe04.png)

`mvn spring-boot:run`

<img width="904" alt="Screen Shot 2020-03-21 at 11 19 46 PM" src="https://user-images.githubusercontent.com/902972/77242242-7f358080-6bca-11ea-923f-2f601260adac.png">

**Comment by spencergibb** [comment]
You need to add request mappings or something else. There's no default mapping for the root

**Comment by snicoll** [comment]
That's indeed the defaut error page showing you a 404. There's no mapping for the root by default so that error message is expected. If you have further questions, please follow-up on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
