### ISSUE TITLE
Spring Boot Documentation Duplications

### ISSUE THREAD

**Issue by tamaro-skaljic** [spring-projects/spring-boot#20627]
I'm reading the whole spring boot documentation at the moment and I think this [paragraph](https://docs.spring.io/spring-boot/docs/2.2.5.RELEASE/reference/htmlsingle/#using-boot-maven-plugin) isn't needed because it's explained already [here](https://docs.spring.io/spring-boot/docs/2.2.5.RELEASE/reference/htmlsingle/#getting-started-first-application-executable-jar).

If I find any more things that come to my attention, I'll let you know here.

**Comment by snicoll** [comment]
Thanks for the report. We intend to move what's remaining of the Maven Plugin documentation in #19165 so that section will naturally move. We'll figure out if that duplication makes sense or not.

> If I find any more things that come to my attention, I'll let you know here.

If by here you mean this issue, we prefer that each issue focuses on one thing and one thing only. I am going to close this one now but feel free to raise another if you find something wrong in the reference guide.
