### ISSUE TITLE
Springboot gradle plugin using deprecated features since Gradle 5 

### ISSUE THREAD

**Issue by eirnym** [spring-projects/spring-boot#20724]
SpringBoot gradle plugin (2.2.6-RELEASE is using `Project.afterEvaluate` which is [deprecated](https://docs.gradle.org/6.2.2/userguide/upgrading_version_5.html#calling_project_afterevaluate_on_an_evaluated_project_has_been_deprecated) since Gradle 5 and will be an error in Gradle 7.

Currently we're using Gradle 6.2.2 in our project.

I understand about broad compatibility, but after some point you need to go further.

**Comment by wilkinsona** [comment]
My understanding is that the API itself is not deprecated but calling it after the project has been evaluated is deprecated. Looking at the plugin's three uses of `project.afterEvaluate`, I believe all of them will call the method before the project has been evaluated. If you have seen a deprecation warning that tells you otherwise, please provide a minimal sample that reproduces it so that we can investigate.

**Comment by eirnym** [comment]
The problem was caused by using checkerframework. After we removed it, the problem disapear. Thank you for your time

**Comment by wilkinsona** [comment]
Thanks for letting us know.
