### ISSUE TITLE
Provide a mechanism for customising the auto-configured NimbusJwtDecoders

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#20750]
Inspired by #20747, it looks like it would be useful to provide a mechanism for customising the auto-configured `NimbusJwtDecoder`. The use case in #20747 is to provide a `RestTemplate` to the decoder with custom proxy settings.

**Comment by mbhave** [comment]
I'd initially thought adding a `JwtDecoderCustomizer` would work but that's not the case. We would need a `JwtDecoderBuilderCustomizer` to support customizations. The problem is that the `JwtDecoder` built when using an [issuer location](https://github.com/spring-projects/spring-boot/blob/35ff711dfe5d57d80791c95b4f2b0660f1df6c5a/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/servlet/OAuth2ResourceServerJwtConfiguration.java#L93) isn't built using a builder so that could cause some confusion around what can be customized and what can't.

**Comment by wilkinsona** [comment]
I've just noticed that there also isn't a `restOperations(RestOperations)` method on the `NimbusJwtDecoder.PublicKeyJwtDecoderBuilder`. That makes sense as it doesn't make any HTTP calls. Perhaps #20470 isn't such a good driver for general purpose customization after all?

**Comment by mbhave** [comment]
Yeah, the public key version doesn't need a restOperations. The `issuerUri` one, however, does use one but it doesn't appear to be customizable. Given that, I don't think we should add a general purpose customizer for the `JwtDecoder`.

**Comment by m-kay** [comment]
Customization is only needed in the case if the `JwkSetUriJwtDecoderBuilder` is used, because all the other builders are fully configurable via properties. Therefore I think only a `JwkSetUriJwtDecoderBuilderCustomizer` would be needed as proposed in my branch [gh-20750](https://github.com/m-kay/spring-boot/commits/gh-20750)

**Comment by mbhave** [comment]
Thanks for the proposal @m-kay. It is true that for the customizations that Spring Security currently supports, it is only the `JwkSetUriJwtDecoderBuilder` that needs a customizer. However, creating a `JwkSetUriJwtDecoderBuilderCustomizer` would be misleading because it would not be able to customize the `restOperations` used by `JwtDecoders` which calls the [`JwkSetUriJwtDecoderBuilder`](https://github.com/spring-projects/spring-security/blob/419d7264f98a3347160e80bd1b8e07e2f66aa8d6/oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoders.java#L105) under the hood. I have raised a [Spring Security issue](https://github.com/spring-projects/spring-security/issues/8365) about that. Until then, I don't think we should do anything in Spring Boot as there's a chance that we would back ourselves into a corner.

**Comment by ThomasKasene** [comment]
If we can't get a customizer, perhaps it's possible to inject a `OAuth2TokenValidator<Jwt>` into the bean so we can supply our own custom validators if we need them? This is really cumbersome to achieve with the current setup as far as I can tell, and while I feel like it's due to Spring Security's tightly coupled configuration, maybe Spring Boot can make it less painful?

There's an old issue in Spring Security that describes the problem I'm facing: https://github.com/spring-projects/spring-security/issues/6909
It petitions to add a `getValidator()` to `NimbusJwtDecoderJwkSupport` to make it possible to know what validators have already been registered, but there doesn't seem to be enough traction to get it implemented.

**Comment by m-kay** [comment]
any update on this? 👀

**Comment by wilkinsona** [comment]
@m-kay As you can see above, @mbhave opened https://github.com/spring-projects/spring-security/issues/8365. If you read through that issue, you’ll see that it was closed in favour of https://github.com/spring-projects/spring-security/issues/8882. 8882 remains open and I don’t think we can do anything here without it so this issue remains blocked.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-security/issues/10309 has been scheduled for Spring Security 5.8 so we may be able to do something in this area in 3.0.x. I'm going to assign this issue to 3.0.x serve as a reminder to see what becomes possible. It'll remain blocked until the changes have been made in Security.

**Comment by wilkinsona** [comment]
Some changes we made in Spring Security a couple of days ago so we should be able to do something in Boot now. It may be too late now for 3.1 though.

**Comment by wilkinsona** [comment]
@mbhave there's a new `NimbusJwtDecoder.withIssuerLocation(issuerUri)` method that returns a `JwkSetUriJwtDecoderBuilder`. That means that both `jwtDecoderByIssuerUri` and `jwtDecoderByJwkKeySetUri` could now use a `JwkSetUriJwtDecoderBuilder` which allows `RestOperations` to be configured. We could offer a `JwkSetUriJwtDecoderBuilderCustomizer` now and I think it could be applied consistently. Do you think we should do so?

**Comment by wilkinsona** [comment]
[Possible implementation](https://github.com/wilkinsona/spring-boot/tree/gh-20750) for discussion and review.
