### ISSUE TITLE
Author section contain version number

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#20934]
I'm not sure if this is related to the new docs style sheet or something else, but we now have a version number in the authors list:

![Screen Shot 2020-04-13 at 4 25 45 PM](https://user-images.githubusercontent.com/519772/79170210-93bd0100-7da3-11ea-9dfc-a04f513cda2d.png)

vs

![Screen Shot 2020-04-13 at 4 25 50 PM](https://user-images.githubusercontent.com/519772/79170217-99b2e200-7da3-11ea-9147-d44dd0026600.png)

**Comment by mbhave** [comment]
Depending on the fix, there might be some overlap with #20896.

**Comment by wilkinsona** [comment]
I don't think it's related to the new docs stylesheet as it's been that was since 2.3.0.M1. I believe it's happening because the Gradle Asciidoctor plugin configures the `revnumber` attribute by default.

When `revnumber` is set or inferred from the source document, it's included in the [byline](https://asciidoctor.org/docs/user-manual/#author-and-email). In other words, we're seeing Asciidoctor's standard behaviour here. If we don't like it, we can get rid of it by explicitly setting the `revnumber` attribute to `null`.
