### ISSUE TITLE
Switch docker upgrade script to submit issue rather than pull-request

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#20976]

**Comment by dreis2211** [comment]
May I ask why, @philwebb ? Given that the initial call was made in favor of a PR.

**Comment by mbhave** [comment]
@dreis2211 We discussed this one the team call today. The discussion stemmed from #20680. Since we create issues in targeted milestones now, for PRs that means that we need a branch per milestone. For the docker detection PRs, we currently have `ci-docker-master`, `ci-docker-2.2.x` and `ci-docker-2.1.x`. If we extend PR creation to ubuntu and jdk updates, we would end up with a lot more long running branches in the Spring Boot repo, especially if we had a branch per jdk for each milestone. Additionally, when merging the PR, we'd need to merge with `--ours` strategy.

The benefit of automating the PR doesn't seem to outweigh the hassle of maintaining multiple long running branches combined with a different merge strategy. Since the change is small enough, we decided to switch back to using issues instead.

**Comment by dreis2211** [comment]
Thanks for the update, @mbhave . I hope you didn't take my question as a concern, just wanted to know the reasoning behind it given that we put a bit of effort into the PR solution. ;)

I can only agree with the decision - my initial proposal was issue-based, after all.

**Comment by mbhave** [comment]
It was indeed quite a bit of work to get the PRs working. It's unfortunate we need to switch back to issues but given everything, it seems like the right call.

**Comment by dreis2211** [comment]
I guess we can also remove the branches already, can't we?

**Comment by snicoll** [comment]
Correct, I've just done that. Thanks for the nudge @dreis2211.
