### ISSUE TITLE
spring boot throw java.sql.SQLException: Invalid object name 'BATCH_JOB_INSTANCE'

### ISSUE THREAD

**Issue by pedrosantos81** [spring-projects/spring-boot#21113]
Hi everyone, I m stucked with spring boot in my app , it's dont want to run schema nor tables , only connect to my database SQL Server and query information, so I disabled this line in file application.properties

spring.batch.initialize-schema=never
but doesnt work , I dont know what´s wrong, already configure my datasource, thanks in advance , 
I hope someone can help me, sorry my english is poor.

I am using spring boot 2.2.6
Cheers

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by pedrosantos81** [comment]
Thanks for your reply Wilkinsona, but I thought what I could ask here, like this post: 
https://github.com/spring-projects/spring-boot/issues/17536
It´s for that the reason that posted , thanks in advance friend

Cheers
