### ISSUE TITLE
false positive in autoconfig for inner classes of a configuration that didn't match

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#2122]
> `/autoconfig`  Displays an auto-configuration report showing all auto-configuration candidates and the reason why they ‘were’ or ‘were not’ applied.

In my report, this is negative:  

```
SpringBootWebSecurityConfiguration: [
{
        condition: "OnClassCondition",
        message: "@ConditionalOnClass classes found: org.springframework.security.config.annotation.web.configuration.EnableWebSecurity"
},
{
        condition: "OnWebApplicationCondition",
        message: "found web application StandardServletEnvironment"
},
{
        condition: "OnBeanCondition",
        message: "@ConditionalOnMissingBean (types: org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration;         SearchStrategy: all) found the following [org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration]"
}
],

```

This is positive: 
```
SpringBootWebSecurityConfiguration.ApplicationWebSecurityConfigurerAdapter: [
{
       condition: "OnPropertyCondition",
       message: "matched"
}
],
```

Actually ApplicationWebSecurityConfigurerAdapter is inner static class but never called. 

I think that the report should them also report them as a negative match because of not being applied. Am I missing something?

**Comment by cemo** [comment]
I think this is missed somehow. Any change for 1.2.2?

**Comment by wilkinsona** [comment]
There are quite a few ways to fix this. I've considered removing inner configuration from the report entirely vs marking inner configuration is not matching because the outer class didn't match. I went with the latter in the end. I'm identifying an inner class using the structure of the source string rather than actually tracking the hierarchy of the configuration classes.

@philwebb I'd appreciate it if you could take a look at https://github.com/wilkinsona/spring-boot/tree/gh-2122. In particular, I thought you may have concerns about the performance cost of the extra processing.

**Comment by philwebb** [comment]
@wilkinsona I've pushed the ancestor logic into the `getConditionAndOutcomesBySource` method. That should mean there is no performance impact during evaluation.
