### ISSUE TITLE
Replace PropertiesMergingResourceTransformer with Maven Shade Plugin's built-in PropertiesTransformer

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#21307]
Maven Shade Plugin 3.2.2 added a new [PropertiesTransformer](https://maven.apache.org/plugins/maven-shade-plugin/apidocs/org/apache/maven/plugins/shade/resource/properties/PropertiesTransformer.html) that we can hopefully use in place of our `PropertiesMergingResourceTransformer`.

**Comment by aivinog1** [comment]
@wilkinsona Hello. Can I work on this issue? For me, it's pretty clear.

**Comment by wilkinsona** [comment]
@aivinog1 Yes, please. That'd be great. Please let us know if you have any questions. Note that it may take us a little while to merge a pull request as we won't be able to do so until we've created the 2.3.x branch and development of 2.4 has being on master.

**Comment by aivinog1** [comment]
@wilkinsona Got it, thanks!

**Comment by aivinog1** [comment]
Hello, @wilkinsona. I have done some investigation and I can say that [PropertiesTransformer](https://maven.apache.org/plugins/maven-shade-plugin/apidocs/org/apache/maven/plugins/shade/resource/properties/PropertiesTransformer.html) doesn't suite for an existing class. Because PropertiesTransformer choosing a value from one source or another and don't combine them. So if we start using this transformer it will be breaking change.

My question: what should I do next about this issue? I can provide some unit tests that will prove what I wrote earlier.

**Comment by wilkinsona** [comment]
Thanks very much for investigating, @aivinog1. Unfortunately, that means that we can’t use the Shade plugin’s built-in transformer so we’ll have to stick with our own. Sorry for the wasted effort.
