### ISSUE TITLE
The @ActiveProfiles annotation no longer overrides those defined in property files

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#21302]
`@ActiveProfiles` replaces profiles from `SPRING_PROFILES_ACTIVE` environment variable with its value in 2.3.0.M4, but it appends its value to profiles from the environment variable in 2.3.0.RC1.

I'm not sure if this is an intentional change or more appropriate, but I'm sharing this as I didn't see any explicit mention from [its release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3.0-RC1-Release-Notes) or issue assigned to [its milestone](https://github.com/spring-projects/spring-boot/releases/tag/v2.3.0.RC1).

This can be produced with [`ActiveProfilesTests`](https://github.com/izeye/spring-boot-throwaway-branches/blob/active-profiles/src/test/java/com/izeye/throwaway/ActiveProfilesTests.java) from [this sample](https://github.com/izeye/spring-boot-throwaway-branches/tree/active-profiles).

If the following environment variable is defined, the test will pass with 2.3.0.M4, but it will fail with 2.3.0.RC1:

```
export SPRING_PROFILES_ACTIVE=local
```

**Comment by mbhave** [comment]
#19788 was fixed but #21006 could have introduced something.

**Comment by mbhave** [comment]
`SpringApplication` makes a call to `environment.getActiveProfiles()` which has a side-effect of [setting active profiles](https://github.com/spring-projects/spring-framework/blob/153690e7175b3286c745dac409d413a0cda6b410/spring-core/src/main/java/org/springframework/core/env/AbstractEnvironment.java#L240) if they haven't been set before. At this point, Spring Framework, sets the active profiles from the `spring.profiles.active`. Since the `SpringBootContextLoader` adds them as indexed properties now, those do not override `SPRING_PROFILES_ACTIVE` at this point.
