### ISSUE TITLE
Upgrade to Jna 5.5.0

### ISSUE THREAD

**Issue by mojo2012** [spring-projects/spring-boot#21313]
the jna version 4.5.2 is about 2 years old! It's definitely time to upgrade. Why has this not been done automatically?

**Comment by wilkinsona** [comment]
It hasn't been done automatically as there has not yet been an appropriate time to move to a new major version of JNA. We upgraded to [4.5.0 in Spring Boot 2.0.0.M5](https://github.com/spring-projects/spring-boot/issues/10404) and since then we have kept up-to-date with the latest releases in the 4.5.x line. The natural point to upgrade to a new major version of JNA will be in Spring Boot 3.0 which is not yet planned. We can consider an upgrade in a 2.x release but we would need a compelling reason to do so. In the meantime, you can use the `jna.version` property to use a version of JNA that meets your needs.

**Comment by philwebb** [comment]
We removed JNA as a managed dependency in 2.3 (See #20156). We might be able to upgrade our internal tools to use the newer version.
