### ISSUE TITLE
random port not working for TestNG tests

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#2135]
Use Spring Boot 1.2.0, selecting a random port for integration tests does not work for TestNG based tests. I have converted the `SpringApplicationIntegrationTestTests.java` from JUnit to TestNG. This test fails:

```java
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.embedded.EmbeddedServletContainerFactory;
import org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory;
import org.springframework.boot.test.IntegrationTest;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.support.PropertySourcesPlaceholderConfigurer;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.servlet.DispatcherServlet;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.testng.annotations.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;

@SpringApplicationConfiguration(classes = SpringApplicationIntegrationTestTestsWithTestNG.Config.class)
@WebAppConfiguration
@IntegrationTest({"server.port=0", "value=123"})
public class SpringApplicationIntegrationTestTestsWithTestNG extends AbstractTestNGSpringContextTests
{

	@Value("${local.server.port}")
	private int port = 0;

	@Value("${value}")
	private int value = 0;

	@Test
	public void runAndTestHttpEndpoint()
	{
		assertNotEquals( 8080, this.port );
		assertNotEquals( 0, this.port );
		String body = new RestTemplate().getForObject( "http://localhost:" + this.port
															   + "/", String.class );
		assertEquals( "Hello World", body );
	}

	@Test
	public void annotationAttributesOverridePropertiesFile() throws Exception
	{
		assertEquals( 123, this.value );
	}

	@Configuration
	@EnableWebMvc
	@RestController
	protected static class Config
	{

		@Value("${server.port:8080}")
		private int port = 8080;

		@Bean
		public DispatcherServlet dispatcherServlet()
		{
			return new DispatcherServlet();
		}

		@Bean
		public EmbeddedServletContainerFactory embeddedServletContainer()
		{
			TomcatEmbeddedServletContainerFactory factory = new TomcatEmbeddedServletContainerFactory();
			factory.setPort( this.port );
			return factory;
		}

		@Bean
		public static PropertySourcesPlaceholderConfigurer propertyPlaceholder()
		{
			return new PropertySourcesPlaceholderConfigurer();
		}

		@RequestMapping("/")
		public String home()
		{
			return "Hello World";
		}

	}
}
```

The only way to fix it is to explicitly add the `IntegrationTestPropertiesListener`

``` java
@TestExecutionListeners(inheritListeners = false,
		listeners = {
			        IntegrationTestPropertiesListener.class,
				DependencyInjectionTestExecutionListener.class,
				DirtiesContextTestExecutionListener.class
		})
```

The problem is that the class is package protected, so I cannot reference it. I have tested it with copying the code of the listener and referencing that, and then the unit test is ok.

AbstractTestNGSpringContextTests has the following `@TestExecutionListeners`:
``` java
@TestExecutionListeners({ServletTestExecutionListener.class, DependencyInjectionTestExecutionListener.class, DirtiesContextTestExecutionListener.class})
```

So, or this has to change, or somehow these listeners defined in `AbstractTestNGSpringContextTests` have to be merged with those of `@IntegrationTest` or at the very least `IntegrationTestPropertiesListener` should be made public. In that last case, you might want to add a warning in the docs for TestNG users.

**Comment by philwebb** [comment]
I can't find a way to make things 100% compatible with Spring Boot 1.1.x and I'm not keen to make `IntegrationTestPropertiesListener` public since we are likely to remove it when #1956 is fixed.

Instead I've added a new `@WebIntegrationTest` annotation which is equivalent to `@IntegrationTest + @WebAppConfiguration` but also works with TestNG. I've also added an [example test](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-testng/src/test/java/sample/testng/SampleTestNGApplicationTests.java) which runs as part of the build.

I'm sorry we couldn't find a way to make things "just work", but hopefully you can migrate to the new annotation without too much pain.

**Comment by sbrannen** [comment]
@philwebb, I haven't looked at everything in detail yet, but shouldn't `@WebIntegrationTest` be annotated with `@WebAppConfiguration` as a meta-annotation?

**Comment by sbrannen** [comment]
Also, it appears you need to update the Javadoc for `SpringApplicationContextLoader` regarding `@WebAppConfiguration @IntegrationTest`.

**Comment by philwebb** [comment]
I think if it does that we will be back to not knowing which `@BootstrapWith` will be used. The `WebAppIntegrationTestContextBootstrapper` triggers the `WebDelegatingSmartContextLoader` in the same way as `WebTestContextBootstrapper`.

We also have a different meaning for `value` in `@WebIntegrationTest` vs `@WebAppConfiguration`.

**Comment by sbrannen** [comment]
I just noticed the changes you made to `WebConfigurer`. So yeah, I suppose you wouldn't want `@WebIntegrationTest` be annotated with `@WebAppConfiguration`.

**Comment by sbrannen** [comment]
Regarding `SpringApplicationContextLoader.isAnnotated()`, you might consider using `MetaAnnotationUtils` instead of `AnnotationUtils` since the former is designed especially for such use cases.

**Comment by sbrannen** [comment]
Ahhhh, now I see the _magic_ you've added to `WebAppIntegrationTestContextBootstrapper`.

You're treating in `@WebIntegrationTest` exactly like it were `@WebAppConfiguration`. Clever!

In light of that, I'd recommend that the Javadoc and reference manual are very explicit in pointing out that `@WebIntegrationTest` is a direct replacement for `@WebAppConfiguration`, that they are mutually exclusive, and that an exception will be thrown if both are used (assuming you implement the aforementioned _validation_).

**Comment by sbrannen** [comment]
@philwebb, I haven't checked out your latest changes from GitHub, but based on inspection alone, I assume that your implementation of `WebAppIntegrationTestContextBootstrapper` does not work as you expect for all use cases.

Please note that the _default_ `TestExecutionListener` class names are only used if `@TestExecutionListeners` is *not* present on the test class or one of its superclasses. Thus, since `SampleTestNGApplicationTests` extends `AbstractTestNGSpringContextTests` which is annotated with `@TestExecutionListeners`, `WebAppIntegrationTestContextBootstrapper.getDefaultTestExecutionListenerClassNames()` will not be invoked. Consequently, the `ServletTestExecutionListener` *will* be registered, and the `IntegrationTestPropertiesListener` will *not*.

Please debug `SampleTestNGApplicationTests` to validate these assumptions.

Thanks,

Sam

**Comment by philwebb** [comment]
We've decided to also make `IntegrationTestPropertiesListener` public so you can now either use the new `@WebIntegrationTest` annotation or directly reference the listeners that you need.
