### ISSUE TITLE
JavaScript & CSS not running anymore after update to Spring Boot 2.2.x

### ISSUE THREAD

**Issue by hendisantika** [spring-projects/spring-boot#21395]
JavaScript & CSS not running anymore after update to Spring Boot 2.2.x

It is similiar like #8172 but it's in Spring Boot 2.2.7

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/3713580/81617968-9fd2c780-9410-11ea-804f-81f808c26699.png">

**Comment by mbhave** [comment]
@hendisantika Please provide a minimal sample that we can run to reproduce the issue.

**Comment by hendisantika** [comment]
Oooo.. Sorry for that.
Here's the sample https://gitlab.com/hendisantika/spring-boot-security-thymeleaf.

Thanks

**Comment by mbhave** [comment]
@hendisantika This appears to be happening because of the `CustomWebConfig`. When you add `@EnableWebMvc` in your application it causes Spring Boot's `WebMvcAutoConfiguration` to back off entirely. It doesn't seem like you need to add that annotation or the custom web configuration since static locations will be configured by the `WebMvcAutoConfiguration`. 

Can you try removing `CustomWebConfig` to see if that works for you?

**Comment by hendisantika** [comment]
OK. Let me try first @mbhave

**Comment by hendisantika** [comment]
OK. Its working now after I remove CustomWebConfig Class. So We don't need that anymore in Spring Boot 2.2x @mbhave ?

**Comment by mbhave** [comment]
AFAIK, nothing has changed in this regard for Spring Boot 2.2.x. Adding `@EnableWebMvc` is generally not required and if added it means that the user wants to take complete control of their MVC configuration.

If you have any more questions, please join us on Gitter.

**Comment by hendisantika** [comment]
OIC.

Thank You @mbhave.
