### ISSUE TITLE
Scope of some dependencies has changed from compile to runtime

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#21507]
The scope of `org.springframework.boot:spring-boot-test` has been changed from `compile` to `runtime` from 2.2.x to 2.3. `spring-boot-test` comes as dependency of `spring-boot-test-autoconfigure`.

```
[INFO] +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.2.6.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-test:jar:2.2.6.RELEASE:compile
```

vs

```
[INFO] +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.3.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.3.0.RELEASE:compile
[INFO] |  \- org.springframework.boot:spring-boot-test:jar:2.3.0.RELEASE:runtime
```

This is a breaking change for library developers providing custom test autoconfiguration. For example, using `SpringBootTestContextBootstrapper` to provide additional properties.

`SpringBootTestContextBootstrapper` is considered public API:

> {@link TestContextBootstrapper} for Spring Boot. Provides support for
{@link SpringBootTest @SpringBootTest} and may also be used directly or subclassed.

As a workaround I can change the scope back to `compile` again in our Maven build or include the dependency manually, but the change came as a surprise to us.

**Comment by wilkinsona** [comment]
Thanks, @michael-simons.

This is a side-effect of the build switching to Gradle. `spring-boot-test-autoconfigure` declares `spring-boot-test` as an implementation dependency. That means that none of the types in `spring-boot-test` are part of the API of `spring-boot-test-autoconfigure`. This minimises the size of the compile classpath for Gradle projects that depend on `spring-boot-test-autoconfigure`. Maven doesn't support the same separation of API and implementation dependencies so Gradle maps them to compile and runtime scope respectively which is how the problem has arisen.

If we consider `spring-boot-test` to be part of the API of `spring-boot-test-autoconfigure` we should change to an `api` dependency. If we want to avoid this wrinkle when upgrading, we should change to an `api` dependency. Otherwise, we should stick with an `implementation` dependency so that the compile classpath remains as small as possible.

**Comment by filiphr** [comment]
I don't want to hijack this issue, However, I noticed other places where something like this happens. Please let me know if I should open a new issue.

I noticed that `spring-boot-actuator-autoconfigure` has `spring-boot-autoconfigure` as a `runtime` scope instead of `compile`. In 2.2.x it was a compile dependency. This isn't the only place which is like this.

**Comment by filiphr** [comment]
I don't have the full stacktrace, but since we updated to 2.3 some of our teammates have the following when running the our maven project from IntelliJ.

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available
```

Is it possible that the `runtime` scoped of the different dependencies, to be causing this?

**Comment by wilkinsona** [comment]
>  However, I noticed other places where something like this happens. Please let me know if I should open a new issue.

@filiphr We can expand the scope of this issue as needed. Where you've noticed the dependencies that are affected, it'd be great if you could comment here with the details please.

> Is it possible that the runtime scoped of the different dependencies, to be causing this?

No, I don't think so. A change from compile scope to runtime scope will only affect the compile classpath. It should have no effect on runtime behaviour. If you can share a project that reproduces the missing `importRegistry`, please open a new issue and we'll take a look.

**Comment by filiphr** [comment]
>@filiphr We can expand the scope of this issue as needed. Where you've noticed the dependencies that are affected, it'd be great if you could comment here with the details please.

Thanks. Currently it is only the one I mentioned before. If we see something else we will let you know.

>No, I don't think so. A change from compile scope to runtime scope will only affect the compile classpath. It should have no effect on runtime behaviour. If you can share a project that reproduces the missing `importRegistry`, please open a new issue and we'll take a look.

This is not really easy to reproduce. It sometimes disappears after restarting IntelliJ, reimporting Maven projects several times, etc. It could very much be an IntelliJ bug and how they handle the maven `runtime` scope. If I get more information I will create a new issue and let you know.

**Comment by wilkinsona** [comment]
I've managed to reproduce the problem with he missing `importRegistry` bean. The failure's happening when the context is being closed. It's the attempt to retrieve the application listeners for the `AvailabilityChangeEvent` is failing. This event is new in 2.3 which I think may explain why we've started to see the problem now. I believe it will affect any app where the context fails to refresh or perhaps only those where the refresh attempt fails at a certain point. I've opened https://github.com/spring-projects/spring-boot/issues/21588.
