### ISSUE TITLE
Document how JAVA_OPTS can be used with the buildpack

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#21582]
See https://github.com/spring-projects/spring-boot/issues/21483#issuecomment-634170647

**Comment by fernandezseb** [comment]
Hey, I'd like to take on this task if that's okay.

**Comment by nebhale** [comment]
@philwebb We can do some additional documentation in our buildpacks as well to help with this as well.

**Comment by snicoll** [comment]
We can document something on our side but I wonder if that's a good idea. By the time this issue was created, this was already renamed and the references above are outdated. 

Looking at https://github.com/paketo-buildpacks/bellsoft-liberica/commit/06551eccf11d9b5f58a7adca0b716482ddf614bc#diff-04c6e90faac2675aa89e2176d2eec7d8 it looks like the property to use now is `JAVA_TOOL_OPTIONS`.

**Comment by philwebb** [comment]
@nebhale It does feel like some more user-facing Packeto documentation that we could link to would be very useful.

**Comment by nebhale** [comment]
Yep, first thing on my list either during my downtime this week or just after SpringOne.  The entire Paketo team is adding that as we speak.

**Comment by scottfrederick** [comment]
Paketo buildpacks documentation has been updated, so the Spring Boot docs can now link to the relevant section in paketo.io: https://paketo.io/docs/buildpacks/language-family-buildpacks/java/#runtime-jvm-configuration. 

We should include a disclaimer that the information provided by this link only applies when the Paketo builder and buildpacks are used, and other CNB implementations might work differently.
