### ISSUE TITLE
SpringBoot not registering controllers generated by OpenAPI-generator-maven-plugin.

### ISSUE THREAD

**Issue by pathfinder2104** [spring-projects/spring-boot#21607]
Hi all,

I am facing weird issue, in my case I am generating the controllers using `OpenAPI-generator-maven-plugin`. It is generating code. 

The code is generated in following way:
- intefaces for controller are generated with default methods.
- Implementation of interface is also generated with appropriate annotations. 
- When I run the application and try to call the controller I get 404, those controllers are not registered with Spring Context.

I checked using applicationContext.getBean with controller class name I am not getting anything, but when I use the interface name I get a proxy bean registered and shown as part of interface.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
