### ISSUE TITLE
Latest Spring Boot @Configuration doesn't have property proxyBeanMethods but it's used everywhere in current docs

### ISSUE THREAD

**Issue by UkrainianCitizen** [spring-projects/spring-boot#21638]
Latest Spring Boot `@Configuration` doesn't have property `proxyBeanMethods` but it's used all over latest [https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/) Spring Boot docs ( `@Configuration(proxyBeanMethods = false)`).
See(30 occurences).
* [https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-using-springbootapplication-annotation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-using-springbootapplication-annotation)
* [https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-enabling](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-enabling)
* [https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-enabling](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-enabling)

**Comment by wilkinsona** [comment]
`@Configuration` is part of Spring Framework where the [`proxyBeanMethods`](https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/context/annotation/Configuration.java#L461) attribute is defined and has been since Spring Framework 5.2. I suspect that you have a dependency on a version of Spring Framework prior to 5.2. If you'd like some help figuring out why that is happening, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by UkrainianCitizen** [comment]
@wilkinsona  Thank you for timely response, indeed spring boot I used included <Spring Framework 5.2. By any chance, do you know how this property works in previous version of Spring Framework?

**Comment by wilkinsona** [comment]
In versions of Spring Framework prior to 5.2, `@Bean` methods are always proxied. 
If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
