### ISSUE TITLE
Actuator EndpointWebExtension  issue

### ISSUE THREAD

**Issue by burghategaurao** [spring-projects/spring-boot#21790]
When I am trying to implement actuator EndpointWebExtension for HealthEndpoint, it throws Error as 

Caused by: java.lang.IllegalStateException: Found multiple extensions for the endpoint bean healthEndpoint

So Question is
1. Do Spring support multiple extension for Endpoint?
2. Do Spring supports extension for inbuild endpoint like HeathEndpoint or extension is only supported for Custom Actuator endpoints.

**Comment by wilkinsona** [comment]
A single web extension is supported per endpoint. Spring Boot already auto-configures a `HealthEndpointWebExtension` for the health endpoint so you cannot provide an additional web extension for it. You can replace the auto-configured extension by providing your own bean that is a sub-class of `HealthEndpointWebExtension` as this will cause the auto-configured extension to back off.

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by StarReider** [comment]
> A single web extension is supported per endpoint. Spring Boot already auto-configures a `HealthEndpointWebExtension` for the health endpoint so you cannot provide an additional web extension for it. You can replace the auto-configured extension by providing your own bean that is a sub-class of `HealthEndpointWebExtension` as this will cause the auto-configured extension to back off.
> 
> If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

I have simmilar issue with duplicates.
Caused by: java.lang.IllegalStateException: Unable to map duplicate endpoint operations: [web request predicate GET to path 'health' produces: application/vnd.spring-boot.actuator.v3+json,application/vnd.spring-boot.actuator.v2+json,application/json, web request predicate GET to path 'health/{*path}' produces: application/vnd.spring-boot.actuator.v3+json,application/vnd.spring-boot.actuator.v2+json,application/json] to healthEndpoint (healthEndpointWebExtension)
@EndpointWebExtension(endpoint = HealthEndpoint.class)
public class HealthEndpointWebExtension extends org.springframework.boot.actuate.health.HealthEndpointWebExtension

But in my case there is sub-class of HealthEndpointWebExtension. Despite that fact spring tries to create auto-configured and custom HealthEndpointWebExtension.

**Comment by philwebb** [comment]
@StarReider Our auto-configuration does [use `@ConditionalOnMissingBean`](https://github.com/spring-projects/spring-boot/blob/cc4965ee8ac870de61c1271d9ca96c0ddf1022f9/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/HealthEndpointWebExtensionConfiguration.java#L54) so something unexpected must be going on. Could you please open a new issue and attach a sample project that replicates the problem.

**Comment by H3llK33p3r** [comment]
Hello, same kind of issue on my side. Only @AutoConfigureOrder has solve the issue :(

**Comment by wilkinsona** [comment]
@H3llK33p3r If you would like us to take a look, please open a new issue and attach a sample project that replicates the problem.
