### ISSUE TITLE
Create canonical place in the documentation for WAR deployments

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#2185]
Currently the documentation of how to get a WAR deployment up and running with Boot is spread between [multiple](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-maven-packaging) [places](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-convert-an-existing-application-to-spring-boot).

It would be cool to have a canonical place to be able to point user to that need WAR deployments.

**Comment by MatthewEdge** [comment]
For what it's worth, I agree with this motion. It was definitely a challenge for a newbie to piece together the resources needed for WAR deployments.

As a side note: I think it would also be nice to mention that the repackaging phase of the spring boot plugin, if packaging as a WAR, will automatically do things like move src/main/resources under the WEB-INF folder (or link to where this information resides). Spring Boot was almost nixed from my project because of this missing fact

**Comment by wilkinsona** [comment]
@MatthewEdge It's Maven's war plugin, not Boot's repackaging, that copies files under `src/main/resources` into `WEB-INF/classes`. From the [Maven war plugin documentation](http://maven.apache.org/plugins/maven-war-plugin/examples/adding-filtering-webresources.html):

> The default resource directory for all Maven projects is src/main/resources which will end up in [...] WEB-INF/classes in the WAR
