### ISSUE TITLE
WhiteLabelError

### ISSUE THREAD

**Issue by saurabh2048** [spring-projects/spring-boot#21987]
In my mvc program while I am trying to send the request through @PostMapping I am getting White Label Error (Type= Method Not Allowed, Status=405) but when I am passing through @getMapping it works perfectly. Could you plz solve my  issue 
[Train-mvc.zip](https://github.com/spring-projects/spring-boot/files/4788386/Train-mvc.zip)

**Comment by mbhave** [comment]
@saurabh2048 If you look at the network requests, clicking on the submit button results in a `GET` request and not a `POST`. This is probably because of the `,` before `method="port"` in your `search.jsp`.

For future reference, we prefer to use the issue tracker only for bugs and enhancements in Spring Boot. If you have any questions please ask them on StackOverflow.
