### ISSUE TITLE
Https [ERROR] [o.apache.tomcat.util.net.NioEndpoint:175 ]

### ISSUE THREAD

**Issue by mingyang66** [spring-projects/spring-boot#22065]
[2020-06-23 16:19:53.623] [000-exec-2] [ERROR] [o.apache.tomcat.util.net.NioEndpoint:175 ] : Failed to close channel
java.io.IOException: Broken pipe

**Comment by wilkinsona** [comment]
This is expected behaviour from Tomcat when a client abruptly closes a connection. 
If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
