### ISSUE TITLE
SNAPSHOT Dependency with Spring Boot Starter Parent POM 2.3.1.RELEASE

### ISSUE THREAD

**Issue by bohni** [spring-projects/spring-boot#22083]
I just upgraded our project to use spring-boot-starter-parent:2.3.1.RELEASE

Now the Maven Enforcer Plugin complains about a SNAPSHOT-Dependency
```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-project-rules) @ springboot-shgruppe ---
[WARNING] Rule 0: de.smartics.maven.enforcer.rule.NoSnapshotsInDependencyManagementRule failed with message:
Dependency Management contains SNAPSHOTS:
  0.8.3.BUILD-SNAPSHOT: Dependency {groupId=io.r2dbc, artifactId=r2dbc-proxy, version=0.8.3.BUILD-SNAPSHOT, type=jar}
 Please remove all SNAPSHOT dependencies!
```

Steps to reproduce:
1. Download a fresh zip from https://start.srping.io using Version 2.3.1, Maven and Java
2. Extract zip
3. run `./mvnw help:effective-pom -Doutput=effective-pom.xml`
4. Search in `effective-pom.xml` for `-SNAPSHOT`

Result:
```
      <dependency>
        <groupId>io.r2dbc</groupId>
        <artifactId>r2dbc-proxy</artifactId>
        <version>0.8.3.BUILD-SNAPSHOT</version>
      </dependency>
```

**Comment by wilkinsona** [comment]
Thanks for the report. That's a bug in the R2DBC bom. `spring-boot-dependencies` imports Arabba-SR4. Unfortunately [it contains a BUILD-SNAPSHOT dependency](https://repo1.maven.org/maven2/io/r2dbc/r2dbc-bom/Arabba-SR4/r2dbc-bom-Arabba-SR4.pom). It appears to have been fixed in Arabba-SR5 which we'll pick up in due course. In the meantime you can use the `r2dbc-bom.version` to override the version to Arabba-SR5.
