### ISSUE TITLE
List unconditional configs in the auto-configuration report

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2209]
As of 1.2.0, the auto-configuration report lists only classes that had a condition and whether they matched or not. Some of the classes in my modules should be activated unconditionally, and it would be helpful to list those in the report as well.

**Comment by chrylis** [comment]
Not sure if this should tag along or be its own enhancement request, but also print out the classes that were explicitly excluded. Just spent a good while tracking down a stray `excludes` parameter, which didn't show up in the autoconfig report.

**Comment by wilkinsona** [comment]
@chrylis Please open a separate issue for listing any exclusions

**Comment by wilkinsona** [comment]
@chrylis @cemo I'm in two minds about what will be most useful in the report and would welcome your input.

I have [an implementation](https://github.com/wilkinsona/spring-boot/tree/gh-2209) that will include any auto-configuration classes with no class-level conditions in the report. With Boot's current auto-configurations it lists `PropertyPlaceholderAutoConfiguration`:

```
Unconditional classes:
----------------------

   org.springframework.boot.autoconfigure.PropertyPlaceholderAutoConfiguration
```

This is inspite of it appearing earlier in the report due to the evaluation of the condition on `propertySourcesPlaceholderConfigurer`:

```
   PropertyPlaceholderAutoConfiguration#propertySourcesPlaceholderConfigurer
      - @ConditionalOnMissingBean (types: org.springframework.context.support.PropertySourcesPlaceholderConfigurer; SearchStrategy: current) found no beans (OnBeanCondition)
```

 I could remove a class from the unconditional list when a condition on one of its methods is evaluated, but I don't think this makes sense. My reasoning is that the class may have unconditional bean methods; listing the class explicitly makes it more obvious that those beans will have been created, rather than inferring it from the fact that the condition on `propertySourcesPlaceholderConfigurer` was evaluated.

**Comment by chrylis** [comment]
I think the double-listing is more helpful than trying to filter, especially since I can imagine edge cases if someone uses inheritance on autoconfig classes. This is a debug/troubleshooting report anyway, and it's hard to see how the extra information would hurt.
