### ISSUE TITLE
Request to not remove deprecated functionality in minor releases

### ISSUE THREAD

**Issue by philsttr** [spring-projects/spring-boot#22115]
In Spring Boot 2.1, 2.2 and 2.3, deprecated functionality has been removed.

Removal of deprecated methods is not backwards compatible.  I would expect that backwards incompatibilities are only introduced in _major_ releases according to semantic versioning.

I would like to request that deprecated functionality no longer be removed in minor releases of spring boot.  

I'll be able to keep up with Spring Boot's 6 month release cadence easier if I don't have to worry about backwards incompatibilities being introduced in every minor release.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, @philsttr. We aim for maintenance releases to be drop-in replacements for the previous release and for minor releases to be easy to adopt but possibly with the need for some changes. The most disruptive changes are saved for major releases. This isn't semantic versioning, but it's an approach that's served us well thus far and that we feel strikes the right balance between stability and forward progress.

As part of the move to a 6-month release cadence, we've decided that in release 2.n we will only remove functionality that was deprecated in 2.n-2 rather than in 2.n-1 as we had been doing previously. This will give people the same amount of time as they had under the previous release cadence to adapt to any API changes that we make. The removals in 2.4 (deprecations in 2.2) are being tracked in [this issue](https://github.com/spring-projects/spring-boot/issues/22034).
