### ISSUE TITLE
Excessive out-of-heap memory usage

### ISSUE THREAD

**Issue by JoyfulAndSpeedyMan** [spring-projects/spring-boot#22306]
I now have a Springboot built enreka.The memory I used to run this JAR was 340MB, but the allocated heap Ilooked at through JMC was only 250MB.Or is there something wrong with myconfiguration?I am now using the version of **SpringBoot as V2.3.0release**
#### The environment
* System: win10
* JDK version: JDK 11
  
#### Here is a screenshot of my runtime
Win10 Task Manager:
![image](https://github.com/JoyfulAndSpeedyMan/assets/blob/master/2020-07-11%20143948.png?raw=true)
JMC:
![image](https://github.com/JoyfulAndSpeedyMan/assets/blob/master/2020-07-11%20140455.png?raw=true)

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
