### ISSUE TITLE
Docs should explicit state how @ConfigurationProperties map to command line args and os env vars

### ISSUE THREAD

**Issue by cer** [spring-projects/spring-boot#2234]
Suppose I have an @ConfigurationProperties class such as 

```
@ConfigurationProperties(prefix = "foo.bar")
class BazProperties {

  @BeanProperty
  @Required
  var simple : String = null

  @BeanProperty
  @Required
  var compoundName : Int = 30
}
```

The docs don't appear to explicitly define how this class's properties map to command line args and OS environment variables, e.g. FOO_BAR_COMPOUNDNAME and/or FOO_BAR_COMPOUND_NAME

**Comment by cer** [comment]
I don't think this change is sufficient. It's still vague.

I think the documentation would be greatly improved if you had a specific example. ie. for a given configuration class with prefix xY (and x.y), and various properties, foo and fooBar. here are the possible (a) OS environment variables (b) command line arguments and (c) system properties that map to the arguments. Ironically, you have more detailed documentation of the random.* properties.

**Comment by snicoll** [comment]
Chris, the whole point is that those things are _relaxed_ and we try to be as lenient as we can. As far as I know there is no difference between (a), (b) and (c) except that some OSs prevent some formats.

How about showing what you're after concretely?

**Comment by philwebb** [comment]
I'm glad you pushed for this because I found an anomaly with the way that we were binding camel case properties (see #2304).

I don't thing we should document all possible variations but I've added a table that shows three of the common forms and when they might be used. Feel free to raise another issue if you think we should add some more.

**Comment by cer** [comment]
Great that you added that description to the docs. I think it's helpful.

Perhaps I encountered the anomaly. I had this class:

```scala
@ConfigurationProperties(prefix = "myApp")
class MyAppConfigurationProperties {

@BeanProperty
  var url : String = _

@BeanProperty
  var serverHost : String = _
}
```

As expected, I could specify the url property with -DmyApp.url, -Dmyapp.url, or OS env var MY_APP_URL.

I could  specify serverHost with -DmyApp.serverHost and OS env var MY_APP_SERVER_HOST.
But other variants that I expected to work such as -DmyApp.server.host or -DmyApp.server_host, .. did not -  I can't remember what else I tried.

The trouble with simply saying that the binding is 'relaxed' is that it's a vague description of behavior.

**Comment by philwebb** [comment]
Yeah, it's not the best description and the logic is somewhat hard to decipher. The `RelaxedNames` class does most of the magic but things are further complicated by `@ConfigurationProperties`.

If you find any more that don't bind that you think should please raise an issue. We probably need more tests around this. It's quite hard with the documentation because it would probably take a whole page to document every variation.
