### ISSUE TITLE
Support for additional management port for accessing /actuator endpoint

### ISSUE THREAD

**Issue by dineshv1234567** [spring-projects/spring-boot#22362]
There is support for only one port to access actuator endpoints with the help of this:
management.server.port=<Port>
But no support to add additional port, in case we want to expose 2 ports

**Comment by wilkinsona** [comment]
As with the main server, if you want to configure a second connector you must do so programatically. To have it apply to the separate management context that the actuator uses when running on a separate port, you must use `@ManagementContextConfiguration` and register the class in `spring.factories` rather than having it picked up by classpath scanning. Assuming that you are using Tomcat, your configuration class would look something like this:

```java
@ManagementContextConfiguration(ManagementContextType.CHILD)
class SecondActuatorPortConfiguration {

	@Bean
	WebServerFactoryCustomizer<TomcatServletWebServerFactory> tomcatCustomizer() {
		return (tomcat) -> {
			tomcat.addAdditionalTomcatConnectors(createStandardConnector());
		};
	}

	private Connector createStandardConnector() {
		Connector connector = new Connector("org.apache.coyote.http11.Http11NioProtocol");
		connector.setPort(8082);
		return connector;
	}

}
```

And your `spring.factories` file like this:

```
org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration=example.SecondActuatorPortConfiguration
```

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by dineshv1234567** [comment]
Thank you @wilkinsona . I am using Undertow. Can you please provide createStandardConnector() for that.

**Comment by wilkinsona** [comment]
You'd need to use an `UndertowBuilderCustomizer` bean to add an HTTP listener. If you need some help with that then, as I said above, please follow up on Stack Overflow or Gitter.

**Comment by dineshv1234567** [comment]
@wilkinsona I have posted about this on Github
https://stackoverflow.com/q/62941729/13944037
