### ISSUE TITLE
when i config with log4j2 dev profiles,the logger auto create test file?

### ISSUE THREAD

**Issue by apple987** [spring-projects/spring-boot#22634]
here is the code,when i start application with profile dev ,but  the log file auto create a empty demo-test.log,why this happen?
[demo.zip](https://github.com/spring-projects/spring-boot/files/4993893/demo.zip)
![cdf5a6b01400a8df4bf1fad4c4948fe](https://user-images.githubusercontent.com/21330215/88782082-bf7fbd80-d1bf-11ea-9484-0c32051f8fb5.png)
![66981553d01453da0d76954bbcf9a6d](https://user-images.githubusercontent.com/21330215/88782374-17b6bf80-d1c0-11ea-954b-ee9ec7957fb4.png)
need help thanks!

**Comment by wilkinsona** [comment]
[`log4j2-test.yml` is a well-known file name that Log4j2 will look for a load by default](https://logging.apache.org/log4j/2.x/manual/configuration.html#AutomaticConfiguration). This happens when Log4j2 is first initialised before Spring Boot has an opportunity to customise its configuration based on your configuration in `application.yml`. You can avoid the problem by renaming `log4j-test.yml` so that it's name isn't one that Log4j2 will load by default.

**Comment by apple987** [comment]
ok! thanks a lot
