### ISSUE TITLE
@Validated does not work with @ConstructorBinding

### ISSUE THREAD

**Issue by GabrielBB** [spring-projects/spring-boot#22666]
This works:

```kotlin
@Validated
@ConfigurationProperties("com.google.x")
class MyProperties {
    @URL
    lateinit var url: String
    @NotBlank
    lateinit var userName: String
    @NotBlank
    lateinit var password: String
}
```

This doesn't:

```kotlin
@Validated
@ConstructorBinding
@ConfigurationProperties("com.google.x")
data class MyProperties(
    @URL
    val url: String,
    @NotBlank
    val userName: String,
    @NotBlank
    val password: String
)
```

I'm using `@EnableConfigurationProperties(MyProperties::class)` in the class who reads these properties.

```xml
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.1.RELEASE</version>
    </parent>
```

**Comment by wilkinsona** [comment]
Thanks for the report. Validation isn't working due to the way in which Kotlin handles annotations in a data class and how Hibernate Validator looks for those annotations.

Hibernate Validator looks for constraint annotations on the fields or getter methods for each property but Kotlin is placing them on the constructor parameters. You need to configure [annotation use-site targets](https://kotlinlang.org/docs/reference/annotations.html#annotation-use-site-targets) to tell Kotlin to place the annotations on the fields or the getters. Instructing Kotlin to place them on the fields looks like this:

```kotlin
@field:URL
val url: String,
@field:NotBlank
val userName: String,
@field:NotBlank
val password: String
```

**Comment by GabrielBB** [comment]
Thanks for the quick response. Finally working :D
