### ISSUE TITLE
Disable default security configuration when SecurityFilterChain bean is present

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-boot#22739]
Spring Security is adding an enhancement that allows configuring HTTP security by exposing a `SecurityFilterChain` bean.
In this case, there is no need to extend `WebSecurityConfigurerAdapter`.
See https://github.com/spring-projects/spring-security/issues/8804.

Currently Spring Boot applies a default security configuration when no `WebSecurityConfigurerAdapter` bean is present.
Going forward, it should also check if a `SecurityFilterChain` bean is present before applying a default security configuration.

**Comment by mbhave** [comment]
@eleftherias Would you suggest updating our [smoke tests](https://github.com/spring-projects/spring-boot/blob/0d79bd08a6716991d7be9acbbf7a5772f9d1226a/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-actuator-custom-security/src/main/java/smoketest/actuator/customsecurity/SecurityConfiguration.java#L36) and [auto-configuration](https://github.com/spring-projects/spring-boot/blob/0d79bd08a6716991d7be9acbbf7a5772f9d1226a/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/servlet/SpringBootWebSecurityConfiguration.java#L46) to use the `SecurityFilterChain` bean instead of extending `WebSecurityConfigurerAdapter` too?

**Comment by eleftherias** [comment]
Yes, using the `SecurityFilterChain` bean will be the recommended approach going forward.

**Comment by mbhave** [comment]
Spring Security still needs to make some changes for making `WebSecurity` work with bean style `SecurityFilterChain`. We use `WebSecurity` to configure ignored paths for the Cloud Foundry actuators. Until that's sorted we can't move to the bean style config for our own auto-configurations. We should open a separate issue for https://github.com/spring-projects/spring-boot/issues/22739#issuecomment-669545630 once that's done.
