### ISSUE TITLE
current-SNAPSHOT symlink points to the wrong feature release

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#22778]
Since our move to SemVer in `2.4.x` the scripts that automatically update the symlinks on docs.spring.io are broken.

At the moment `current-SNAPSHOT` links to`2.3.3.BUILD-SNAPSHOT`. It should point to `2.4.0-SNAPSHOT`.

**Comment by trevormarshall** [comment]
The auto-linking script and associated regex can be found in the `genlinks.inc.php` file which is held in the private [spring-docs-www-conf](https://github.com/pivotal/spring-docs-www-conf/blob/master/docs/autorepo_script/genlinks.inc.php) repository. The issue is that it is unmaintained and does not support the updated versioning scheme.

The script runs on a schedule and looks for a `.autoln` file in project's autorepo directory on the docs server. To suspend auto-symlinking that file can be removed.

From my perspective, some options to fix this could be:

1) modify the existing script to support SemVer as well
2) leave existing script as is (it does seem to work..), and add a 2nd job that looks for e.g. `.newautoln` files indicating projects that have changed schemes
3) rewrite from scratch to support old and new schemes

We could also consider some other form of post-build trigger instead of a cron, but keep in mind our many disparate CI systems. 

This is beginning to affect more projects.

**Comment by rwinch** [comment]
FYI...I'm going to put together a Java library to do this

**Comment by rwinch** [comment]
You can find the project at https://github.com/spring-io/autoln

**Comment by wilkinsona** [comment]
With thanks to @rwinch and @trevormarshall, this is now working correctly. At the time of writing `current-SNAPSHOT` points to `2.4.1-SNAPSHOT`.
