### ISSUE TITLE
Making Folder structure and saving in MySql

### ISSUE THREAD

**Issue by HimanshuChugh2** [spring-projects/spring-boot#23031]
Hello,

For my blogging (kind-of) web app i want the user to easily store all the created articles.
so i want to let the user create a folder kind of structure in the database, so that all of the created articles are sorted.
for example, if a user teaches Java in my web app user should have the functionality of making folder and putting the content in them.

like this: 
                            Java
                     /                \
                 android           Web
                /           \
        Chapter 1      Chapter 2
      of android       of android
       /                         \
  "content 1"               "content 2"

Here the user has created folders like "Java/android/Chapter 1 of android" and has put the article "content 1" in it.

So here i want to store the main thing "content" in MySql, and i want the user to see on the frontend that he has stored "content 1" in "Java/android/Chapter 1 of android/content 1".

I am using Java Spring boot.

What should be the functionality of making this folder type structure, please help.
Any suggestions will be appreciated

Thank you in advance

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
