### ISSUE TITLE
Freemarker is configured to prefer filesystem access by default

### ISSUE THREAD

**Issue by halfninja** [spring-projects/spring-boot#23051]
If I write a test that loads a template under `src/main/resources/templates` it works fine. If I then create a template under `src/test/resources/templates` the test then fails as the template loader switches to looking there and only there. It's useful to be able to have a test template to check the behaviour of any custom Freemarker settings.

Ideally it would load from all `templates` resources found on the classpath, not just one.

Project to reproduce the problem (Spring Boot 2.4.0-M2):
https://github.com/halfninja/spring-ftl-bug-repro

Renaming `src/test/resources/templates` causes the test to pass.

**Comment by snicoll** [comment]
So with the help of @jhoeller I've been able to dig into this problem. The core framework support of Freemarker default to look for a single directory if available (see  `preferFileSystemAccess` on `FreeMarkerConfigurationFactory`). In this particular sample, when the test runs in the IDE, a directory is found (`spring-ftl-bug-repro/build/resources/test/templates/`)  so it defaults to that and doesn't use the classpath at all. That explains why the template in the other classpath location isn't considered.

This flag is `true` by default to support templates reloading. In the context of Spring Boot, I am not sure that's what we want. Flagging for team attention to see if the rest of the team agrees.

Also, the notes that I've shared above doesn't qualify for Freemarker at least. Freemarker will ignore `classpath*` style so we may want to revisit this note as well.

**Comment by philwebb** [comment]
The documentation note was added in the fix for #2319

**Comment by snicoll** [comment]
There is actual a property that controls this that was introduced in #2901

@halfninja I've added `spring.freemarker.prefer-file-system-access=false` to `application.properties` in your sample and the test passed. Please add this property in your project (if you still need two templates directories with the same name). We've decided to flip the default value of the property to `false `in `2.4.x` so that this use case you've described works out-of-the-box.
