### ISSUE TITLE
Spring Boot Actuator /health endpoint slow response

### ISSUE THREAD

**Issue by alandwiprasetyo** [spring-projects/spring-boot#23105]
Spring Boot 2.3.0.RELEASE

I use spring boot 2.3.0.RELEASE to build the application. but having a problem in the actuator .. I got a slow response time for checking healthcheck .. what should I do? have to add properties for this case?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Perhaps you should [create a group](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-health-groups) to isolate health indicators a bit more. It is impossible for us to know without more details. If you still need support please ask on StackOverflow.
