### ISSUE TITLE
Document that @ConfigurationProperties beans are not scanned in sliced tests

### ISSUE THREAD

**Issue by MrBuddyCasino** [spring-projects/spring-boot#23210]
**Affects:** 2.2.4.RELEASE

The `@ConfigurationPropertiesScan` annotation does not work in a `@WebFluxTest` and fails to pick up any classes.  Referencing classes explicitly via `@EnableConfigurationProperties` works but shouldn't be required. The project uses Kotlin 1.4.

Here is a minimal test case to reproduce the issue:
https://github.com/MrBuddyCasino/spring-boot-property-binding-bug

**Comment by wilkinsona** [comment]
Thanks for the sample.

`@WebFluxTest` [filters the beans that are registered by scanning](https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/htmlsingle/#boot-features-testing-spring-boot-applications-testing-autoconfigured-webflux-tests) and this filtering excludes `@ConfigurationProperties`-annotated beans. This behaviour isn't specific to `@WebFluxTest` as none (IIRC) of the sliced `@…Test` annotations include `@ConfigurationProperties` beans.

I'm flagging this for team attention so that we can discuss what, if anything, we want to do here. It may be that we decide to change the behaviour or perhaps just make and update to the documentation to clarify the current behaviour.

**Comment by MrBuddyCasino** [comment]
Thanks for the quick feedback. In the meantime, I guess `@EnableConfigurationProperties` is the best workaround for now?

**Comment by snicoll** [comment]
I don't this it is a workaround but what you should be doing the same way you should use `@Import` if you want to add an additional component. The current behaviour is what we expect to happen, see [this comment](https://github.com/spring-projects/spring-boot/issues/21216#issuecomment-620918857) and #16659. 

As for the documentation it [currently states the following](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-testing-spring-boot-applications-testing-autoconfigured-webflux-tests):

> `@WebFluxTest` auto-configures the Spring WebFlux infrastructure and limits scanned beans to `@Controller`, `@ControllerAdvice`, `@JsonComponent`, `Converter`, `GenericConverter`, `WebFilter`, and `WebFluxConfigurer`.
