### ISSUE TITLE
how to set spring.datasource.hikari.data-source-properties.v$session.program=XXX property

### ISSUE THREAD

**Issue by shanlaomao** [spring-projects/spring-boot#23217]
Hello,

How to set spring.datasource.hikari.data-source-properties.v$session.program in application.properties, the '$' character will be automatically deleted?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by shanlaomao** [comment]
Thank you for your reply. I have found the solution. The following configuration is OK:

`spring.datasource.hikari.data-source-properties[v$session.program ]=XXX`

The result of running the program is correct. The only problem is that the spring boot language server prompts an error as follows:

`Can't use '[..]' navigation for property ' spring.datasource.hikari.data-source-properties' of type java.util.Properties`
