### ISSUE TITLE
Enhancement: Add a new status to actuator health check to indicate UP_WITH_CAUTION status

### ISSUE THREAD

**Issue by DanielYWoo** [spring-projects/spring-boot#23239]
Current we have UP/DOWN/UNKNOWN/OUT_OF_SERVICE. But that's not enough in many cases. For example, our service depends on a database and a Redis cluster as cache. When the Redis cluster is not reachable, the current behavior of actuator is to report DOWN, but actually the application performance is downgraded but it still works. We hope there can be a status between DOWN and UP, maybe UP_WITH_CAUTION.

Then the default aggregator health check is to sort all dependencies by this order:
```
DOWN
OUT_OF_SERVICE
UP_WITH_CAUTION
UP
UNKNOWN
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. This feels quite specific to your use case and, therefore, something that would be better handled in your application rather than in Spring Boot itself. Please see [the documentation](https://docs.spring.io/spring-boot/docs/2.3.3.RELEASE/reference/htmlsingle/#writing-custom-healthindicators) for details on how to define and aggregate a custom `Status` and map it to a specific HTTP response code.
