### ISSUE TITLE
Springboo Kafka - @EmbeddedKafka - Transaction not working

### ISSUE THREAD

**Issue by tamilsmani** [spring-projects/spring-boot#23279]
I have configured the @KafkaListener method which runs on transactionally.

I am testing the Kafkalistener method with the Spring boot @EmbeddedKafka server and failed in publishing the message 
and it says

2020-09-14 15:18:58.111 ERROR 51615 --- [quest-handler-0] kafka.server.KafkaApis                   : [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3' for the transactions state topic (configured via 'transaction.state.log.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet.

Could you help to resolve the issue and publish the message to the @KafkaListener method.

Test Class: https://github.com/tamilsmani/kafka-demo/blob/master/src/test/java/com/example/kafkademo/KafkaConfigurationTest.java

Config class: https://github.com/tamilsmani/kafka-demo/blob/master/src/main/java/com/example/kafkademo/KafkaConfiguration.java

**Comment by tamilsmani** [comment]
I am still facing the same issue after removing the hibernate validator & Bump hibernate-validator from 6.0.2.Final to 6.1.0.Final 

Could you help me on this?

<img width="1062" alt="Screenshot 2020-09-14 at 16 16 16" src="https://user-images.githubusercontent.com/39116373/93077335-47edeb00-f6a6-11ea-8a18-487810e21049.png">

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
