### ISSUE TITLE
Add HealthIndicator implementation for ArangoDB for readiness checks

### ISSUE THREAD

**Issue by oliverlockwood** [spring-projects/spring-boot#23282]
We have recently upgraded our microservices platform to use Spring-Boot 2.3 and are making use of the new functionality around liveness & readiness health checks. In general it seems to be working well 👍 

A number of our microservices use ArangoDB as a backing store.  I would like these microservices to include Arango availability in their readiness checks, and this is not currently supported out-of-the-box by `spring-boot-actuator`.

To this end I intend to follow the guidelines at https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#writing-custom-healthindicators

However it occurred to me that this would be potentially useful for the broader Spring community so I thought I would ask whether you would consider a submission of a pull request to `spring-boot-actuator` to add this functionality, or if you would prefer to leave that outside the project.

**Comment by wilkinsona** [comment]
Thanks for the offer of a pull request. We don't any support for ArangoDB in Spring Boot itself, but there is a starter that is maintained by the ArangoDB team which includes a [health indicator](https://github.com/arangodb/spring-boot-starter/blob/bb566943c69f0722c0e0826f413d380f8fde3eec/src/main/java/com/arangodb/springframework/boot/actuate/ArangoHealthIndicator.java). I'd recommend using this starter if it meets your needs. If it doesn't meet you needs, I think any enhancements should be made in the ArangoDB starter rather than us duplicating that effort in Spring Boot itself.

**Comment by oliverlockwood** [comment]
Thanks @
