### ISSUE TITLE
Fix LoggingSystem package tangle

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#23387]
![Screen Shot 2020-09-16 at 11 44 56 PM](https://user-images.githubusercontent.com/519772/93429870-ad90d180-f876-11ea-9d4a-2b93ae80aad8.png)

**Comment by philwebb** [comment]
Caused by #22594

**Comment by philwebb** [comment]
I'm not sure how to fix this one :(

**Comment by wilkinsona** [comment]
Gah!

**Comment by sdeleuze** [comment]
Package tangles are bad, and we should avoid them, but here I think this refactoring just made this previously hidden issue visible to static code analysis.

Reverting those changes would just hide it again, not solve it, with a regression on native image support.

Since I guess we have to live with this package tangle in Boot 2.x timeframe, could we keep the code as it is and solve this properly in Boot 3?

**Comment by philwebb** [comment]
I agree that this was a previously hidden issue, but I hope that we don't need to live with it until 3.x. I tried adding a new `LoggingSystemFactory` interface with an implementation the uses `spring.factories` by default.

@sdeleuze Will you be able to replace `LoggingSystem.SYSTEM_FACTORY` in the native image to do what you need?

**Comment by sdeleuze** [comment]
Thanks I will check this tomorrow.

**Comment by sdeleuze** [comment]
It should be possible to adapt, the main point to clarify is if it will require build time transformations (not supported currently with `reflection` mode) or not. We will discuss that in our tomorrow meeting and check that in practice after `spring-graalvm-native` `0.8.1` release. cc @aclement
