### ISSUE TITLE
`javax.websocket.server.ServerContainer` is missing from ServletContext for pure SpringBoot application

### ISSUE THREAD

**Issue by jfarcand** [spring-projects/spring-boot#2341]
`javax.websocket.server.ServerContainer` from ServletContext is `null` when SpringBoot is used (without Spring WebSocket).  Spring WebSocket shoudn't be required to support it as underlying Tomcat(or Jetty) does exposed it like the Servlet Specification is required. More info [here](https://github.com/Atmosphere/atmosphere/issues/1836), sample [here](https://github.com/henri-tremblay/hipster-atmosphere)

**Comment by philwebb** [comment]
It looks like we could relax the condition on `WebSocketAutoConfiguration`. I've tried with the sample but I'm having a bit of trouble debugging it. The `atmosphere-runtime-native-2.2.3-sources.jar` only appears to include a single java file (`AtmosphereServlet.java`) so it's hard to work out what is going on. Is there an alternative dependency that I can use to test things? Perhaps it would be best to create a lighter atmosphere sample that we could use for testing.

**Comment by jfarcand** [comment]
@philwebb Just replace `atmosphere-runtime-native` with `atmosphere-runtime`. Debug will works much better.

**Comment by philwebb** [comment]
I've relaxed the condition and also added a sample application based on the atmosphere chat sample.

**Comment by jfarcand** [comment]
@philwebb Wow that was fast. Thanks a lot!

**Comment by philwebb** [comment]
@jfarcand I'm not totally convinced that the sample app is the configured in the best way. I've added a `AtmosphereServlet` mapped to `/chat` and a `DispatcherServlet` mapped to `/home`. Ideally I think there should only be a `DispatcherServlet` mapping with it somehow delegating to atmosphere. That way Spring Boot usual `/` mappings would work.

If you have any ideas for better integration let me know.

**Comment by jfarcand** [comment]
@philwebb Let me investigate, but the main issue is to locate `javax.websocket.server.ServerContainer`. If the instance is available, then the integration wil just works as before. BTW WebSocket work well with Tomcat 7, it started failing when Tomcat 8 started to be used.

**Comment by spencergibb** [comment]
@philwebb [ServletWrappingController](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/mvc/ServletWrappingController.html) lets you plug servlets into the request dispatcher.

**Comment by philwebb** [comment]
@spencergibb I tried that approach first but I hit some issues. It looked to me like Atmosphere needed an actual real servlet registration in order to configure itself. I may well have been doing something wrong.

I actually started out looking at https://github.com/Atmosphere/atmosphere-samples/blob/master/extensions-samples/spring/spring-websocket/ for inspiration. Perhaps there is a better way to configure things.

**Comment by spencergibb** [comment]
@philwebb I thought I knew something, you are the man.

**Comment by owahlen** [comment]
@philwebb I still have an issue with atmosphere and spring-boot when deploying on Tomcat 8.0.20 using a WAR file. I get the ERROR: 

*Failed to create comet support class: class org.atmosphere.container.JSR356AsyncSupport, error: null
Switching to BlockingIO*

Note that this does not happen if deploying to the embedded tomcat 8 from Spring Boot.
Is there anything that needs to be configured in the WAR-File?

**Comment by philwebb** [comment]
@owahlen Could you please open a new issue for this and attach the complete stack trace. If you have a [sample application](https://github.com/spring-projects/spring-boot-issues) that we use, that would also be very helpful.

**Comment by owahlen** [comment]
@philwebb Adding a new issue is probably a good idea. However I have looked a bit at the issue and I am not sure if it really is related to spring boot:
The problem is that the class org.atmosphere.container.JSR365AsyncSupport contains the following line in its constructor:
*ServerContainer container = (ServerContainer) config.getServletContext().getAttribute(ServerContainer.class.getName());*

The Attribute resolves to *org.apache.tomcat.websocket.server.WsServerContainer* if the application is deployed as a war file. This class does not implement ServerContainer and the subsequent class cast exception causes my error.

The strange thing is that if the application is not deployed as a war file but started as a spring application the attribute resolves to *org.apache.catalina.core.ApplicationContextFacade*. This works just fine.

Do you think my issue is related to spring-boot or is it an atmosphere issue?

**Comment by jfarcand** [comment]
@philwebb @owahlen https://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/tomcat/websocket/server/WsServerContainer.html This class does implement `ServerContainer` so I'm puzzled. I suspect there is a classloader issue here.

**Comment by owahlen** [comment]
I found the reason for my issues: I have generated the war file using the gradle plugin. It repackages the war file and has added several tomcat-embed*.jar files.
See also http://stackoverflow.com/questions/23530654/websockets-with-tomcat-8-and-spring-4-classcastexception-before-handler-is-invok
I have now added this to my gradle dependencies and (from a first look) it seems to work now:
*providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'*

**Comment by gregturn** [comment]
@owahlen Yeah, that is documented in http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file.
