### ISSUE TITLE
I changed field name in Java Class: but JSON response is more different

### ISSUE THREAD

**Issue by cristian9401** [spring-projects/spring-boot#23454]
Hi

I have SpringBootApplication. For customer request, I changed some field names in my Java Class.
However, when I executed REST API with Postman, I saw that JSON response is more different to my Java Class fields.

I do not khow how to change these values, and it is stopper for my implementation and adjustments project.

Thanks.
![Postman_REST_API_createdocument](https://user-images.githubusercontent.com/4325285/93915090-1dff7e80-fccd-11ea-9e20-c68167f1e19d.png)
![Postman_REST_API_infoevaluacion](https://user-images.githubusercontent.com/4325285/93915419-9bc38a00-fccd-11ea-8c5b-467d89f77696.png)

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
