### ISSUE TITLE
Add dependency management for ojdbcX-production, ojdbcX-debug, ojdbcX-observability, ojdbcX-observability-debug

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#23450]
See: https://www.oracle.com/database/technologies/maven-central-guide.html#flavors for background.
It would be nice if these could be added to the spring-boot-dependencies bom too.

**Comment by wilkinsona** [comment]
Oracle introduced a bom in 19.7 which we [switched to when we upgraded](https://github.com/spring-projects/spring-boot/commit/872ccddd528ec9612b7edbb07be5b54fdce965e1). The pre-established dependencies are pom-only artifacts that are similar to one of our starters but they aren't incIuded in the bom. Rather than us managing their version separately, I'd prefer that Oracle included them in their bom.

**Comment by davidkarlsen** [comment]
I guess that's a fair point!
However Oracle being Oracle I am not sure where to engage with such a request :-)

**Comment by wilkinsona** [comment]
@Kuassim is the PM for Oracle's DB. Kuassi, can you please point us in the right direction to make such a request?

**Comment by Kuassim** [comment]
Let me discuss the implications, if any with, with my colleagues and get back asap.

**Comment by Kuassim** [comment]
After discussing this with the team; we agree to include the flavor POMs to our BOM.
We will implement this as soon as possible.
Thank you, Kuassi

**Comment by wilkinsona** [comment]
That's excellent news. Thank you, @Kuassim and team.
