### ISSUE TITLE
Additional Hibernate properties are not recognized

### ISSUE THREAD

**Issue by mdoninger** [spring-projects/spring-boot#2348]
I have the following problem: 

I have defined the property spring.jpa.hibernate.transaction.jta.platform in my application.properties. However, when the HibernateJpaAutoConfiguration starts, it gets the properties by a call to JpaProperties#getHibernateProperties(), which itself calls Hibernate#getAdditionalProperties(). But in this method, a new Map is created and two properties added (ejb.naming_strategy and hbm2ddl.auto) and all existing properties are discarded. Thus the auto configuration tries to configure the JTA platform, which fails (because we use Hibernate 4.2).

Is this type of property handling intended or is this a bug, meaning that also all existing properties should be in the map which is returned by Hibernate#getAdditionalProperties()?

**Comment by snicoll** [comment]
Is that a custom Hibernate property? If so, the correct prefix for the provider custom properties is `spring.jta.properties`

**Comment by mdoninger** [comment]
I also tried with that, but in that case it doesn't matter, because the method HibernateJpaAutoConfiguration#customizeVendorProperties only gets the map with the 2 properties i mentioned). So either the if clause which checks for the JTA platform property is wrong or the method which returns the Hibernate properties.

**Comment by drumonii** [comment]
I actually noticed this too. 

If you put a breakpoint at the return of `getVendorProperties()`, then you'll see the map doesn't contain user defined hibernate properties. It will only contain, like previously mentioned, either only ejb.naming_strategy or ejb.naming_strategy and hbm2ddl.auto, so max of 2 properties.

I believe this happens because in `getAdditionalProperties` method of`JpaProperties` class, the passed in `Map<String, String> existing` is not merged (`putAll`) with the newly instantiated map `Map<String, String> result`. It simply returns only the `result` map and that is used in `getVendorProperties` of `HibernateJpaAutoConfiguration`. The user defined properties are valid and are picked up in the actuator if you go `/configprops` and look at the `spring.jpa.CONFIGURATION_PROPERTIES`.
