### ISSUE TITLE
spring boot + jpa +Scheduled  transaction error

### ISSUE THREAD

**Issue by romantictravel01** [spring-projects/spring-boot#23588]
I have a project that uses spring boot1.5+spring data jpa. If the method is called in @Scheduled, javax.persistence.TransactionRequiredException: Executing an update/delete query will be generated. If it is called in the controller, it is normal. My service method uses @Transaction annotation
What happened
![image](https://user-images.githubusercontent.com/59325449/95059664-c67cfc00-072b-11eb-8dd5-5ceecc6eb22b.png)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by romantictravel01** [comment]
I think it's a magic problem, come and save me
![image](https://user-images.githubusercontent.com/59325449/95062344-6c7e3580-072f-11eb-8c3b-f22e49ab3d4a.png)
**task**
![image](https://user-images.githubusercontent.com/59325449/95062460-9172a880-072f-11eb-95fd-151ea2c7321f.png)
**service**
![image](https://user-images.githubusercontent.com/59325449/95062843-1958b280-0730-11eb-86a3-5934ed7c6e9e.png)
**dao**
![image](https://user-images.githubusercontent.com/59325449/95062899-2aa1bf00-0730-11eb-9a8a-f427ddf16d83.png)
**error** 
![image](https://user-images.githubusercontent.com/59325449/95062958-43aa7000-0730-11eb-8efc-0581dc6c87ca.png)
**If I add a controller and call it in the controller, the method executes normally**
@RestMapping...
@ResponseBody
public String test(){
    generateTaskService.updateStatus(1,2);
}
Give me some advice

**Comment by wilkinsona** [comment]
@romantictravel01 This isn't the right place to ask for advice. Please use Gitter or Stack Overflow for that. Also, please be aware that Spring Boot 1.5 is no longer support. You should be looking to upgrade to 2.x as soon as you can.
