### ISSUE TITLE
ApplicationReadyEvent not listened to when declaring @ComponentScan for library package.  

### ISSUE THREAD

**Issue by onemorelight-hub** [spring-projects/spring-boot#23587]
@ComponentScan({"com.test.cloud"})
@SpringBootApplication
public class TestClass  {

	public static void main(String[] args) {
		ApplicationContext context = SpringApplication.run(TestClass.class, args);
	}
}

public class TestClass2{

@EventListener(ApplicationReadyEvent.class)
	public void testMethod() {
      .....
      .....
 }
}

Here if I remove @ComponentScan({"com.test.cloud"}) annotation then the testMethod is triggered. But when I use @ComponentScan({"com.test.cloud"}) then the testMethod is not triggered.  
 
 SpringBoot Version: 1.5.10.RELEASE

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
