### ISSUE TITLE
@ResponseStatus no effect????

### ISSUE THREAD

**Issue by startjava** [spring-projects/spring-boot#23589]
@RequestMapping(value = "test4")
    public String test4() throws LoginException {
        System.out.println("public String test4()");
        if (1 == 1) {
            throw new LoginException("xxxxxxxxxxx");
        }
        return "index.jsp";
    }
------------------------------------
@ResponseStatus(value = HttpStatus.UNAUTHORIZED, reason = "11111111111")
public class LoginException extends RuntimeException {
    public LoginException() {
        super();
    }

    public LoginException(String message) {
        super(message);
    }
}
-----------------------------------------------
show result alway response code 500,
and reason = "11111111111" no show !
only show "xxxxxxxxxxx"
------------------------------------------------
but top code in springMVC is ok!
but in spring boot no effect

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
