### ISSUE TITLE
GRPC support for couchbase integration 

### ISSUE THREAD

**Issue by prasannajoshi2121** [spring-projects/spring-boot#23684]
Hi ,

creating this issue as I couldn't find reference for GRPC support with couchbase/nosql integration in documentation . Please let me know if couchbase/nosql integration can be done with GRPC in spring based app ?

As is -  we can generate GRPC code in spring app using existing GRPC library and can interact with other service.
requirement/question - if model classes can be directly streamed to couchbase/nosql database.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

FTR, Spring Boot does not have core support for gRPC.
