### ISSUE TITLE
Rest API to connect openfire and send Data

### ISSUE THREAD

**Issue by lodhipr** [spring-projects/spring-boot#23768]
Hi, there i need your help in developing a Rest API  which will help me in send data to openfire  message . I want to use post command with json data to send a data to particular user , with their secret key of openfire.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
