### ISSUE TITLE
Internal profile-specific properties override external non-profile-specific properties

### ISSUE THREAD

**Issue by axtavt** [spring-projects/spring-boot#2404]
Consider the following external `application.properties`:

    spring.profiles.active=dev
    my.property=external

and the following `src/main/resources/application-dev.properties`:

    my.property=internal

When running the application, `my.property` will resolve to `internal`, whereas documentation clearly states that it should not be so:

> Spring Boot uses a very particular PropertySource order that is designed to allow sensible overriding of values, properties are considered in the the following order:
> ...
> 6\. Application properties outside of your packaged jar (application.properties including YAML and profile variants).
> 7\. Application properties packaged inside your jar (application.properties including YAML and profile variants).

**Comment by philwebb** [comment]
We might need some clarification in the reference docs as we're not really clear on how profiles effect the ordering. I think that this is actually expected behavior. 

Profiles specific config takes precedence over the default config, so in this case the `src/main/resources/application-dev.properties` profile files will override the external `application.properties`. If you move `my.property=external` to an external `application-dev.properties` I believe that it will work.

@dsyer and @wilkinsona might have more input, but I'm somewhat reluctant to change the current behavior.

**Comment by dsyer** [comment]
That is indeed the expected and intended behaviour (so I am also reluctant to change it).

**Comment by philwebb** [comment]
We'll leave this as it is but try to improve the docs.

**Comment by zmitrok** [comment]
Oh I guess I am yet another one who hit this totally expected behavior expecting the opposite :)
