### ISSUE TITLE
OCI image created using CNB 40 years ago

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#24166]
Using Boot 2.4.0 and and Gradle plugin 1.0.10.RELEASE.

https://github.com/asarkar/spring/tree/master/redis-learning

```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
redis-learning             latest              da431f96e6f6        40 years ago        272MB
```

Image created 40 years ago?

**Comment by wilkinsona** [comment]
This is by design. See [this question on Stack Overflow](https://stackoverflow.com/questions/62865594/spring-boot-2-3-0-buildpack-builds-image-with-creation-date-40-years-ago), for example.

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by asarkar** [comment]
@wilkinsona The challenge is differentiating between a question and a problem. This is not documented, and what'd one search for if looking on stackoverflow? Do you've a recommendation?

**Comment by wilkinsona** [comment]
If you're not sure if you have a question or are facing a problem, then opening an issue isn't where we ask people to start. As I [mentioned in your earlier issue](https://github.com/spring-projects/spring-boot/issues/24161#issuecomment-727788897), the Paketo Slack is a useful resource. The https://buildpacks.io website, Stack Overflow, and Google can also be valuable sources of information.

In this particular case, the behaviour is [documented](https://buildpacks.io/docs/reference/reproducibility/) on https://buildpacks.io. Both that link and the Stack Overflow question I linked to above appear in the first handful of results when I Google for [buildpack 40 years ago](https://www.google.com/search?q=buildpack+40+years+ago).
