### ISSUE TITLE
2.4.0 Rest Repositories initializ project reports lots of Beans is not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by yohanndumais** [spring-projects/spring-boot#24322]
I just started using Spring Boot and noticed a lot of INFO messages reporting Bean 'X' of type [Y] is not eligible for getting processed by all BeanPostProcessors. 

I noticed this behavior when I updated from 2.3.5.RELEASE to 2.4.0. 

This repo illustrate the behavior observed : https://github.com/yohanndumais/demo-data-rest
created from spring initializr : [https://start.spring.io/...](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.4.0.RELEASE&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=data-rest)

**Comment by scottfrederick** [comment]
Thanks for the report and the sample. I can reproduce the problem you're seeing. 

The root of the issue is related to configuration of Spring Data Rest. Making a few changes to the sample app removes Spring Boot's auto-configuration of Spring Data Rest from the path and narrows the problem scope.

In the main application class, disable auto-configuration of Spring Data Rest and add a configuration class to [manually configure](https://docs.spring.io/spring-data/rest/docs/current/reference/html/#customizing-sdr.adding-sdr-to-spring-mvc-app)  it: 

```
@SpringBootApplication(exclude = {RepositoryRestMvcAutoConfiguration.class})
public class DemoDataRestApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoDataRestApplication.class, args);
	}

	@Configuration
	@Import(RepositoryRestMvcConfiguration.class)
	public class RestMvcConfiguration {
	}
}
```

With these changes, you should see the same warnings at startup. Removing the `@Import(RepositoryRestMvcConfiguration.class)` eliminates the warnings. 

@yohanndumais Since this is isolated to Spring Data Rest, can you [open an issue with that project](https://github.com/spring-projects/spring-data-rest#reporting-issues) so the team can look into it? You can post a link to that issue as a comment here for reference.
