### ISSUE TITLE
Multiple HttpMessageConverter in HttpMessageConverters 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#2444]
When I was debugging for a culprit,  I have noticed that there is multiple of `StringHttpMessageConverter` and `MappingJackson2HttpMessageConverter` at the end of  `org.springframework.boot.autoconfigure.web.HttpMessageConverters#HttpMessageConverters(boolean, java.util.Collection<org.springframework.http.converter.HttpMessageConverter<?>>)`

```
this.converters = Collections.unmodifiableList(combined);
```

Can someone else also check please?

**Comment by snicoll** [comment]
with what? A vanilla Spring Boot app (which version?) or something that you customized yourself?

**Comment by cemo** [comment]
I downloaded a sample from `start.spring.io`  with Boot 1.2.1 + Actuator + Web modules.

**Comment by wilkinsona** [comment]
The behaviour is intentional and is described in the javadoc:

> Items are added just before any default converter of the same type (or at the front of the list if no default converter is found)

There's also [a test](https://github.com/spring-projects/spring-boot/blob/v1.2.1.RELEASE/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/HttpMessageConvertersTests.java#L69-L87) that verifies the described behaviour. See gh-1293 for details of why this behaviour is necessary.

**Comment by cemo** [comment]
Actually I had searched but could not be successful. Thanks for information.
