### ISSUE TITLE
Problems with Spring boot family. very worried.

### ISSUE THREAD

**Issue by netroby** [spring-projects/spring-boot#24455]
The spring boot family was very awsome, but seems now be a problem.

We use spring boot 1.5.x, and written down million lines of code (almost). and we using as much as more spring component. 
Spring-boot-data-* (elasticsearch, mongo, redis, mysql)

Now we are migrate from our project from traditional dedicated servers to cloud .

We found the software version was newer than we have before.(elasticsearch, Mongo, redis, Mysql)

we know spring-boot was official announce not be continue maintained. 

So how could we gettting fresh drivers for old spring boot component? 

like (elasticsearch, mongo...)

We can not fully upgrade our framework into spring boot 2.x, It's huge problem for rewrite our code.

Too many codes need to be changed. 

We are fast growing. and can not avoid the cost.

I wonder to know are we stupid, we shall not use so much more spring boot component. 

becuase they are too old , lost mantained?

can we using spring boot 2.x component with spring boot 1.5.* ?

Or we can not depends on the spring boot family?

If we just using core spring-boot-web, and development ourself components?

**Comment by philwebb** [comment]
I'm afraid it's not viable for us to maintain branches indefinitely on an open source project such as Spring Boot. It's also not possible to mix Spring Boot 2.x components with Spring Boot 1.5.x.

We strive to provide the best possible service that we can to our users so that they can depend on us, but that also involves some effort to keep on a supported version. I'd recommend looking at the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide) to help you migrate your existing application.

If that's not an option, the `1.5.x` branch is [available](https://github.com/spring-projects/spring-boot/tree/1.5.x) and is under the Apache 2.0 license. You are free to create your own internal fork and attempt to cherry-pick features from 2.x that you want. I suspect this would ultimately end up being more work than migrating your application.
