### ISSUE TITLE
Configuring EndpointHandlerMapping for producing JSON only

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#2449]
I love JSON outputs in our actuator endpoints. This week I have to add `jackson-dataformat-xml` dependency for our business and this is registering a `MappingJackson2XmlHttpMessageConverter`. I want to remove `MappingJackson2XmlHttpMessageConverter` from our EndpointHandlerMapping.
I have currently solved this problem as this:
```
@Component
public class MyEndpointHandlerMappingCustomizer implements EndpointHandlerMappingCustomizer {
 
   static class Fix extends HandlerInterceptorAdapter {
     
      Set<MediaType> mediaTypes = Sets.newHashSet(MediaType.APPLICATION_JSON);
     
      @Override
      public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
         request.setAttribute(HandlerMapping.PRODUCIBLE_MEDIA_TYPES_ATTRIBUTE, mediaTypes);
         return true;
      }
   }

   @Override
   public void customize(EndpointHandlerMapping mapping) {
      mapping.setInterceptors(new Object[]{new Fix()});
   }
}
```

I could not be sure that this is the right approach. Please provide a way to configure or remove a specific `HttpMessageConverter` from `EndpointHandlerMapping`.

**Comment by dhauge** [comment]
Shouldn't it be considered more of a bug that adding a dependency that contributes a ```MappingJackson2XmlHttpMessageConverter``` has a side effect of changing the response format of actuator endpoints from JSON to XML? The XML response doesn't even work correctly for all endpoints out of the box; in particular, the 'RequestMappingEndpoint' produces invalid XML because the keys often start with '/'. Here's the beginning of an example response:
```xml
<LinkedHashMap xmlns="">
   </webjars/**><bean>resourceHandlerMapping</bean><//webjars/**>
   </**><bean>resourceHandlerMapping</bean><//**>
   </**/favicon.ico><bean>faviconHandlerMapping</bean><//**/favicon.ico>
   ...
```

**Comment by wilkinsona** [comment]
I'm wary of changing this in 1.2.x, but for 1.3 I think we can fix this by adding `produces=application/json` to the endpoints' request mappings

**Comment by snicoll** [comment]
ping @bclozel

**Comment by bclozel** [comment]
In my case, I'm specifying the type I want in the file extension (when using a browser): https://spring.io/info.json

Otherwise, :+1: for adding `produces=application/json` in the mapping information. I doubt people are consuming that information with an XML parser.

Now, regarding the global behavior, there's nothing wrong with:
* adding a dependency that will contribute a new `HttpMessageConverter` that knows how to deal with `application/xml` or `text/xml`
* Content negotiation doing its job and selecting `application/xml` because of browsers' `Accept` request headers

**Comment by wilkinsona** [comment]
This is tricker to fix than I had hoped.

In 1.2, the `/env` and `/metrics` endpoints can return everything, or an individual metric/environment entry, for example `/metrics/mem.free`. When a single value is returned, the key isn't returned and you just get the value. This is returned as `text/plain`.

In 1.3, support for using a regular expression to filter what's returned has been added, for example `/metrics/mem.*. This can lead to a response from the same request mapping that's a single primitive value or an object that contains multiple values. The latter should be returned as `application/json` but the former should returned as `text/plain` for compatibility with 1.2.x and because it's not legal JSON. Unfortunately, when the request mapping is marked as producing `text/plain` and `application/json`, `MappingJackson2HttpMessageConverter` happily serialises a primitive into an invalid `application/json` response, for example:

```
curl -i localhost:8080/metrics/mem.free
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Disposition: attachment;filename=f.txt
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Mon, 19 Oct 2015 10:11:47 GMT

140212
```

The behaviour of `MappingJackson2HttpMessageConverter` doesn't feel right to me. I don't think it should claim that it can write an object that produces malformed JSON. What do you think, @bclozel?

**Comment by bclozel** [comment]
Indeed, I thought that kind of behavior was prevented by [AbstractJackson2HttpMessageConverter.canWrite/writeInternal behavior](https://github.com/spring-projects/spring-framework/blob/4338719d98ccc0981fe0e15788c4a9b79b2ac884/spring-web/src/main/java/org/springframework/http/converter/json/AbstractJackson2HttpMessageConverter.java#L167-L187).

So this is actually working:

```java
ObjectMapper mapper = new ObjectMapper();
ByteArrayOutputStream baos = new ByteArrayOutputStream();
mapper.writeValue(baos, new Long(42));
System.out.println(baos.toString());

// writes 42
```

This issue is described [here in jackson databind](FasterXML/jackson-databind#34).
For now, I have no idea how to get around that...

**Comment by bclozel** [comment]
I've discussed this with @sdeleuze and it looks like the "malformed JSON" part is not that clear.
While json.org and jsonlint.com tend to agree on scalar values not being valid JSON, the following works:

```javascript
// in the browser
var mem = JSON.parse("42");
console.dir(mem);
```

Also, with Jackson:
```java
ObjectMapper mapper = new ObjectMapper();
Long value = mapper.readValue("42", Long.class);
System.out.println(value.toString());
```
