### ISSUE TITLE
Problem with handling concurrent POST requests

### ISSUE THREAD

**Issue by a-d-marinin** [spring-projects/spring-boot#24508]
Good Day, I use Spring Boot 2.4.0

Problem: If this servlet receives 2 POST requests at the same time - the servlet will process different RequestHeaders, but the same RequestBody

@PostMapping example:
![image](https://user-images.githubusercontent.com/66466573/102190614-4dd3b200-3ec9-11eb-80a9-cbe2dfdbde56.png)
flowCss():
![image](https://user-images.githubusercontent.com/66466573/102195664-ed943e80-3ecf-11eb-8a36-1f2581233194.png)

First POST bash script:
![image](https://user-images.githubusercontent.com/66466573/102190989-d3eff880-3ec9-11eb-989b-d7d4d509c30b.png)

Second POST bash script (with a different body):
![image](https://user-images.githubusercontent.com/66466573/102191026-e4a06e80-3ec9-11eb-8c99-8009bd0f7618.png)

concurrent start script:
![image](https://user-images.githubusercontent.com/66466573/102191058-f2ee8a80-3ec9-11eb-84ca-65c8db8ce2f7.png)

logs:
1) from IntelliJ IDEA:
![image](https://user-images.githubusercontent.com/66466573/102195136-3c8da400-3ecf-11eb-9192-4729240fedc6.png)
NOTE: [http-nio-8193-exec-1] and [http-nio-8193-exec-2] got different headers (agreenumber, content-lenght), but the same body 
2) from server:
![image](https://user-images.githubusercontent.com/66466573/102196632-38fb1c80-3ed1-11eb-901d-8ae4550b6052.png)

**Comment by bclozel** [comment]
Could you provide more details about this issue? It's really hard for us to understand a problem with screenshots and rebuilding a similar app from those takes a considerable amount of time.

My best guess is that the `mule` object (which is not shown in your screenshots unfortunately) is stored as a class attribute. If this is the case, this means this instance is reused by the controller for concurrent calls. If this is the case, then that's the source of your problem: you should not share state between requests or you risk exactly this type of problems.

If the `mule` instance is not shared between calls, please provide us with a minimal, sample application (something wecan clone or download) so that we can have a proper look.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
