### ISSUE TITLE
Spring Boot 1.5.22 vs 2.0.0 onwards .formLogin().loginPage issue(?)

### ISSUE THREAD

**Issue by nvaraha** [spring-projects/spring-boot#24588]
To keep it simple - if i run https://mkyong.com/spring-boot/spring-boot-spring-security-thymeleaf-example/ code with spring-boot-starter-parent:1.5.22.RELEASE or below, the  .formLogin().loginPage(custom Login) works fine, however if i run the same code with 2.0.0.RELEASE onwards, the login keeps coming back to the same page, even after successful auth. 
I'm using Eclipse latest - Version: 2020-12 (4.18.0) - Build id: 20201210-1552 with sts4/update/e4.15. 
Could there be an issue?

**Comment by snicoll** [comment]
@nvaraha I am not sure why you're reporting a problem with a guide that's hosted elsewhere. Both Spring Boot 1.5 and 2.0 are EOLed I am afraid and there are significant changes in that area since `1.5.x`. 

Please take the time to review the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide) and upgrade your application to a supported version (`2.3.x` or later at the time of writing). If you're still having an issue and you believe this is a bug in Spring Boot then please let us know and we can reopen this issue. If you're looking for support, please ask question on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by nvaraha** [comment]
Absolutely, i just started looking into Spring security little deeper, i saw a significant difference, if it is already documented, i will go through the guide, and ask questions at StackOverFlow. Thanks.
