### ISSUE TITLE
Health mappings should be more relaxed with status values

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2465]
`endpoints.health.mapping.OUT_OF_SERVICE=i-am-a-teapot` works, 
`endpoints.health.mapping.out-of-service=i-am-a-teapot` doesn't.

**Comment by snicoll** [comment]
Weird.  I have fixed #1242 and there is an explicit test for that.

**Comment by snicoll** [comment]
`endpoints.health.mapping` is a `Map<String,HttpStatus>` so there is no enum in the key there. I've added an extra test that demonstrates what you're after works. It does.

I think it makes sense that this map has a `String` since you can always create your own status. Maybe something to "fix" locally in `HealthMvcEndpointProperties` ?

**Comment by philwebb** [comment]
Looks like `HealthMvcEndpoint` needs to do a case insensitive search to get what I want.

**Comment by snicoll** [comment]
Isn't that an entire different problem?

**Comment by philwebb** [comment]
Yeah, the title was wrong but the initial description still stands.

**Comment by snicoll** [comment]
Maybe we need to hava an ad-hoc solution for this because `RelaxedNames` can find `MY_SUPER_STATUS` based on `my-super-status`. Here's the candidates that I get:

```
MY_SUPER_STATUS
MY.SUPER.STATUS
MY__sUPER__sTATUS
MY_-sUPER_-sTATUS
MYSUPERSTATUS
mySuperStatus
my_super_status
my.super.status
my__super__status
my_-super_-status
mysuperstatus
MY__SUPER__STATUS
MY_-SUPER_-STATUS
```

Some of these are pretty crazy so I'd argue that we should probably fix `RelaxedNames` instead.
