### ISSUE TITLE
Spring Boot Jersey Auto Config not work in Servlet 3.1 container

### ISSUE THREAD

**Issue by xfcjscn** [spring-projects/spring-boot#2471]
When annotaion `@ApplicationPath` added on `JerseyConfig` extends `ResourceConfig`, a servlet will be created to serve request by Jersey in `JerseyServletContainerInitializer`. 
In this case, the servlet create by Spring Boot in `JerseyAutoConfiguration` will be ingored. 
The configs under key: `spring.jersey.init` will not take effect.

**Comment by wilkinsona** [comment]
Possible fix: https://github.com/wilkinsona/spring-boot/tree/gh-2471

**Comment by xfcjscn** [comment]
Can I know any plan to merge this change?

**Comment by wilkinsona** [comment]
No plans at the moment. @dsyer, did you have a chance to look at my proposed change?

**Comment by dsyer** [comment]
I didn't yet. Maybe later today. Thanks for the reminder.

**Comment by maxsap** [comment]
I just updated to spring-boot 1.3.1 and I am stuck with this specific issue. The problem is that this only occurs when we redeploy on AWS elastic beanstalk, works fine both as JAR and on local tomcat when deployed as WAR but when redeployed on Elastic Beanstalk we are getting:
"javax.servlet.ServletException: Servlet.init() for servlet com.xxx.xxx.xxx.JerseyConfig threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)"

**Comment by dsyer** [comment]
@wilkinsona LGTM

**Comment by YuanhuiQu** [comment]
@maxsap I am facing the same problem, how did you resolve the AWS beanstalk deployment issue?
