### ISSUE TITLE
possibility to disable event propagation

### ISSUE THREAD

**Issue by GreenRover** [spring-projects/spring-boot#24878]
a possibility to disable event propagation,

this is required to fix the broken "readiness" event propagation of SpringCloudStream.
For further Information see:
spring-cloud/spring-cloud-stream#2083

@wilkinsona You closed the PR #24865 would your prefer argumenst like:
--spring.boot.application.event.supress=context-prepared,started,running

those i would apply in:
https://github.com/spring-projects/spring-boot/blob/6254ad634ecb0dc73034038f82fcde75fb99117a/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L437

and take those affect in:
https://github.com/spring-projects/spring-boot/blob/6254ad634ecb0dc73034038f82fcde75fb99117a/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplicationRunListeners.java

@philwebb you wrote "offer some kind of `SpringFactoriesFilter `" in:  https://github.com/spring-cloud/spring-cloud-stream/issues/2083#issuecomment-76244604
Can you explain some more, sorry i dont understand what you mean.

Best regards Heiko

**Comment by snicoll** [comment]
@GreenRover as Andy mentioned in the PR that he closed, we'd like to continue the discussion on the Spring Cloud Stream issue and then follow-up here if need to be. There is no need to have this conversation in two different places.

**Comment by wilkinsona** [comment]
To be fair to @GreenRover, Phil did say "feel free to open an issue". However I'd still prefer that we keep this discussion in the SCS tracker for now at least. @spencergibb has suggested that the config data API could be used and this would solve the problem in Spring Cloud Stream without requiring any changes in Boot. IMO, that's preferable as it avoids some unnecessary complexity in Boot.

Before anyone opens any more Boot issues, let us reach a conclusion in spring-cloud/spring-cloud-stream#2083 so that we know what, if anything, the issue needs to track.
