### ISSUE TITLE
Since 2.4.2, the Logback charset defaults to UTF-8 rather than the OS's default

### ISSUE THREAD

**Issue by jonesun** [spring-projects/spring-boot#24894]
When I use version 2.4.2, package it into a jar, and run it with cmd: `java -jar demo-0.0.1-SNAPSHOT.jar,` the log output is garbled. But after falling back to 2.4.1, using the same method again, it is completely normal. The attachment is the result comparison:

![use-2 4 1](https://user-images.githubusercontent.com/6612481/105130150-6f0b6c00-5b21-11eb-8788-e1c651f10c30.png)
![use-2 4 2](https://user-images.githubusercontent.com/6612481/105130151-716dc600-5b21-11eb-9cd1-8f49c486cdfc.png)

**Comment by philwebb** [comment]
I wonder if the change we made for #24835 has had some kind of unexpected side-effect. 

@jonesun I assume the last three lines are the issue? Perhaps `logging.charset.console` is has changed somehow. What's your default charset? Are you able to provide a sample application that shows the problem?

**Comment by jonesun** [comment]
this is my demo project [demo](https://github.com/jonesun/demo1)

**Comment by jonesun** [comment]
thank you for your reply. my windows default charset is gbk, and my idea use utf-8

**Comment by jonesun** [comment]
> 我想知道我们对[＃24835](https://github.com/spring-projects/spring-boot/issues/24835)所做的更改是否具有某种意想不到的副作用。
> 
> @jonesun我认为最后三行是问题吗？也许`logging.charset.console`是有所改变。您的默认字符集是什么？您是否可以提供显示问题的示例应用程序？

I just followed your prompt and changed the configuration, it's ok:
```
logging:
  charset:
    console: gbk
```

**Comment by philwebb** [comment]
Reopening because I'd like to dig into why the property wasn't needed before.

**Comment by jonesun** [comment]
@philwebb ok

**Comment by wilkinsona** [comment]
Thanks for the sample, @jonesun. It's allowed to confirm that the fix for #24835 is the problem.

`DefaultLogbackConfiguration` and `LoggingSystemProperties` have different defaults for `CONSOLE_LOG_CHARSET`. The former using `default` (the JVM's default) and the latter used `UTF-8`. In 2.4.1, `LoggingSystemProperties` does affect the logger context. As a result, `CONSOLE_LOG_CHARSET` is unset and its default (the JVM's default charset) is used by the console appender. In 2.4.2, `LoggingSystemProperties` does affect the logger context and, as a result, `CONSOLE_LOG_CHARSET` is set with `LoggingSystemProperties`' default which is `UTF-8`. This is then used by the console appender.

The fix for #24835 was intended to reinstate the lines remove in https://github.com/spring-projects/spring-boot/commit/fb25104151f0e9716f8e589bde144538c9df977d. The lines didn't set `CONSOLE_LOG_CHARSET` so perhaps we've swung back too far in the opposite direction and we should be more selective about the properties that are applied to the logger context. On the other hand, applying only a subset of properties seems inconsistent.

**Comment by philwebb** [comment]
[This line](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L151) should use the `LogbackLoggingSystemProperties` subclass.
