### ISSUE TITLE
Unsupported api 17432576

### ISSUE THREAD

**Issue by Monax111** [spring-projects/spring-boot#24971]
When i updrade spring 2.2.4->2.4.2 and java 8->11 and kotlin 1.3.72->1.4.21 i see very strange error.
```
Execution failed for task ':spring-app-two:bootJarMainClassName'.
> Unsupported api 17432576
```
full log and stacktrace here
 https://scans.gradle.com/s/hp25r33znsncm

**Comment by wilkinsona** [comment]
Thanks for sharing a build scan. In Spring Boot 2.4, Spring Boot's Gradle Plugin requires Spring Framework 5.3 but one of the other plugins you have applied is downgrading to Spring Framework 5.2. This leaves a version of Spring Framework's ASM variant on the classpath that does not understand Java 11 byte code. You can see the dependency problem [in the build scan](https://scans.gradle.com/s/hp25r33znsncm/build-dependencies?dependencies=spring-core&expandAll&focusedDependency=WzAsMCwxNDYsWzAsMCxbMF1dXQ&focusedDependencyView=versions). The downgrade is due to a constraint in one of the dependencies of `ru.tinkoff.top.top-ci-plugin:ru.tinkoff.top.top-ci-plugin.gradle.plugin:1.2` and is out of Spring Boot's control.

**Comment by Monax111** [comment]
Sorry, can you tell me about this conflict more specifically? Task :spring-app-two:bootJarMainClassName use dependency from confihuration classpath for subroject :spring-app-two ? it it's true, i don't see coflict. I see org.springframework:spring-core:5.3.3 in this confihuration. 
![image](https://user-images.githubusercontent.com/17501801/105577546-72a22b80-5d8b-11eb-9cd2-ccd565a12a60.png)
I see Spring 5.2 only for root project classpath
![image](https://user-images.githubusercontent.com/17501801/105577584-9e251600-5d8b-11eb-89b0-959724a60821.png)
But classpath subproject must override it?

**Comment by wilkinsona** [comment]
Sorry, I don't know exactly how Gradle forms the classpath when combining the build script dependencies from the root project and a subproject. However, the failure tells me that the `spring-core` jar from the root project has won as that's what would cause this failure to occur. If you'd like to understand exactly how Gradle forms the classpath in this situation, https://discuss.gradle.org is a good place to ask.

**Comment by Monax111** [comment]
thank you
