### ISSUE TITLE
Sql querries not excecuted spring boot data jpa postgres and hibernate

### ISSUE THREAD

**Issue by helasoui** [spring-projects/spring-boot#25001]
Hello, 

I am trying to build  a crud rest api with spring boot , spring data jpa and psotgresql.
when i run the app , it is launched but the tables are not created and nothing happens no sql is shown in the console.

these are my files:
application.properties
![image](https://user-images.githubusercontent.com/51752515/105893386-51ec0700-6013-11eb-81b2-4a3d551dc140.png)

![image](https://user-images.githubusercontent.com/51752515/105893437-5f08f600-6013-11eb-9215-52de26d85257.png)

controller
![image](https://user-images.githubusercontent.com/51752515/105893462-692af480-6013-11eb-9ce7-169c11667cc6.png)

 Entity:Employee
![image](https://user-images.githubusercontent.com/51752515/105893489-7516b680-6013-11eb-9d54-38c1dc8a1c1d.png)

Repository:
![image](https://user-images.githubusercontent.com/51752515/105893518-7ba52e00-6013-11eb-959b-fd79dd380c82.png)

Pom.xml

![image](https://user-images.githubusercontent.com/51752515/105893609-9677a280-6013-11eb-9eed-01ae6ae9bbaf.png)

![image](https://user-images.githubusercontent.com/51752515/105893629-9d9eb080-6013-11eb-8da8-2d14afe88788.png)

thank you in advance for helping

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

You'll probably get more help if you're able to share a complete project that shows the problem.
