### ISSUE TITLE
Update @IntegrationTest for latest changes in Spring

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#2505]
See https://jira.spring.io/browse/SPR-12710 for discussion. There are some new public methods that will make it possible to refactor `@IntegrationTest` without any reflection hacks.

**Comment by sbrannen** [comment]
See also: https://jira.spring.io/browse/SPR-12721

**Comment by sbrannen** [comment]
You actually will not be able to do away with the reflection hacks for getting the _inlined properties_ from `@IntegrationTest` into the `MergedContextConfiguration`. This part hasn't changed.

However, you will be able to ensure that the same algorithm is used for parsing the inlined properties. To achieve that, you can delete the `extractEnvironmentProperties()` and `asMap()` methods in `SpringApplicationContextLoader` and update its `getEnvironmentProperties()` method as follows:

	// properties.putAll(extractEnvironmentProperties(config.getPropertySourceProperties()));
	properties.putAll(TestPropertySourceUtils.convertInlinedPropertiesToMap(config.getPropertySourceProperties()));

Furthermore, you should now add official support for test `Properties` files configured via `@TestPropertySource`. This can be achieved via `TestPropertySourceUtils.addPropertiesFilesToEnvironment(ConfigurableApplicationContext, String[])`. However, I see that `SpringApplicationContextLoader` does not actually have access to the `ConfigurableApplicationContext`. So this poses a challenge... which we will need to address! I'll keep you posted on that topic.

**Comment by sbrannen** [comment]
Update: to invoke `TestPropertySourceUtils.addPropertiesFilesToEnvironment()` with the application context before it has been refreshed, one option is to override the `postProcessApplicationContext()` method in a custom extension of `SpringApplication` (returned by `SpringApplicationContextLoader.getSpringApplication()`). The only issue there is that `getSpringApplication()` is not currently provided access to the `MergedContextConfiguration` which will be needed by `postProcessApplicationContext()` so that it can invoke:

    TestPropertySourceUtils.addPropertiesFilesToEnvironment(context, config.getPropertySourceLocations())

I guess you could introduce `getSpringApplication(MergedContextConfiguration)` and deprecate `getSpringApplication()`.

Another option would be to register a custom `ApplicationContextInitializer` that invokes `TestPropertySourceUtils.addPropertiesFilesToEnvironment()`.

If you run into any challenges, please just let me know.

**Comment by sbrannen** [comment]
This issue is closely related to #2198.

**Comment by dsyer** [comment]
Duplicates #1956?

**Comment by sbrannen** [comment]
@dsyer,

This part still hasn't been done:

However, you will be able to ensure that the same algorithm is used for parsing the inlined properties. To achieve that, you can delete the `extractEnvironmentProperties()` and `asMap()` methods in `SpringApplicationContextLoader` and update its `getEnvironmentProperties()` method as follows:

	// properties.putAll(extractEnvironmentProperties(config.getPropertySourceProperties()));
	properties.putAll(TestPropertySourceUtils.convertInlinedPropertiesToMap(config.getPropertySourceProperties()));

**Comment by sbrannen** [comment]
The reason the above change is important is that `SpringApplicationContextLoader.extractEnvironmentProperties()` does **not** preserve the ordering or property names; whereas, `TestPropertySourceUtils.convertInlinedPropertiesToMap()` does.

**Comment by sbrannen** [comment]
And here the corresponding [comments in JIRA](https://jira.spring.io/browse/SPR-12710?focusedCommentId=112542&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-112542).
