### ISSUE TITLE
Spring-data IN clause is broken 

### ISSUE THREAD

**Issue by MarcTerrasson** [spring-projects/spring-boot#25108]
Spring-boot version : 2.4.0
r2dbc-postgresql : 0.8.6.RELEASE

Hello Everyone,

I have this issue when I try to retrieve data with IN clause.

```Cannot encode parameter of type java.util.ArrayList```

Here is the query I use.

```
@Query("SELECT id_tpv FROM tpv_vehicule tv INNER JOIN vehicule v ON v.id = tv.id_vehicule WHERE tv.id_tpv IN $1 AND v.immatriculation = $2")
Flux<Long> filterTpvIdsByImmatriculation(List<Long> tpvIds, String immatriculation);
```

This issue is really similar to this one https://github.com/spring-projects/spring-data-r2dbc/issues/361
But it should be fixed in the 2.4.0.

**Comment by wilkinsona** [comment]
Thanks for the report, @MarcTerrasson. Without some more information, it's hard to tell why you believe this to be a Spring Boot issue rather than a Spring Data R2DBC issue. Once Spring Data R2DBC is configured, Spring Boot isn't involved in the query execution. If you think this is a Spring Boot problem, please provide a minimal sample that reproduces the problem and we can take another look. Alternatively, if you think this is a Spring Data R2DBC issue, please [open an issue in the Spring Data R2DBC repository](https://github.com/spring-projects/spring-data-r2dbc/issues/) and close this one.

**Comment by MarcTerrasson** [comment]
Indeed.
Thanks you for your time.

**Comment by wilkinsona** [comment]
https://github.com/spring-projects/spring-data-r2dbc/issues/534
