### ISSUE TITLE
Deprecate our Gradle plugin's integration with Gradle's maven plugin

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#25267]
Hi,

this is sort of related to #24225 but given the impact I think it's worth a dedicated ticket.

The maven plugin is deprecated since 6.x and Boot's Gradle Plugin makes use of it via `MavenPluginAction`...Since the documentation is also kind of "advertising" the usage (it's the first option in the [docs](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#publishing-your-application-maven)) I'm relatively certain that users still use the maven plugin instead of the maven publish plugin. Maybe we could put a little warning in the docs about the deprecation (in earlier Boot releases) or remove the docs completely?

Anyhow - if the plan is to support Gradle 7 this will break the Gradle Plugin as it removed classes like `MavenPlugin`.

In case you wanted to tackle this inside #24225 please ignore me and close the ticket, but when I thought about release notes generation a dedicated ticket made sense in my head.

Cheers,
Christoph

**Comment by wilkinsona** [comment]
Thanks, @dreis2211. The plugin already works with Gradle 7 despite the absence of the `MavenPlugin` class due to https://github.com/spring-projects/spring-boot/issues/24526. We're testing that against 7.0-milestone-1 at the moment. There's still some things to do here, though, and I think we should take a staged approach to this one:

1. Update the documentation to favour the Maven Publish plugin. We can do this in 2.3.x.
2. Deprecate support for the Maven plugin. We can probably do this in 2.5 if we also drop support for Gradle 5 as proposed in #24225
3. Remove support for the Maven plugin. We can do this in 2.7 or when we drop support for Gradle 6 if that happens earlier.

**Comment by dreis2211** [comment]
Ah, I missed #24526 - learned something new. Thanks.

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-projects/spring-boot/issues/25275 to improve the documentation in 2.3.x. Let's use this issue for the deprecation in 2.5. Stage three will then be taken care of as part of our standard deprecation removal sweep in 2.7.

**Comment by wilkinsona** [comment]
I've labelled on hold as we should only do it if https://github.com/spring-projects/spring-boot/issues/24225 makes it into 2.5.

**Comment by wilkinsona** [comment]
On second thought, I don't think we need to wait. We should be discouraging the use of the maven plugin as much as we can at this point.
