### ISSUE TITLE
add configuration for maven-plugin to exclude provided scope dep.

### ISSUE THREAD

**Issue by qrqhuang** [spring-projects/spring-boot#25274]
Let's talk about more about the spring-boot-maven-plugin for provided scope in #8005 .

In out project, there many not useful dependency provider by 2rd SDK. and these dep will stuck application startup.
We use `provided` scope and `999-not-exist` version to exclude them totally.
If `repackage` do not exclude them. We have to exclude manual one by one.
So can configuration for provided exclude be added ?

**Comment by qrqhuang** [comment]
#8005

**Comment by qrqhuang** [comment]
#8005

**Comment by wilkinsona** [comment]
@qrqhuang Plus comment on #8005 rather than opening a duplicate issue. If you do so, please explain why you have dependencies on things that are not useful. If they're not useful to your application, why not exclude them using Maven's standard exclusion mechanism? This will avoid them cluttering up the compile, runtime, and test classpaths in Maven as well as avoiding them appearing in your repackaged jar.

**Comment by qrqhuang** [comment]
I'm sorry .

I've notice that previous issue is closed.  There are some author prefer open a new issue rather than to a closed one. 

I'll append this to that one.
