### ISSUE TITLE
Add CAS autoconfiguration support

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#2530]
CAS (Central Authentication Service) has had integration with spring for a long time. It would be great to add the CasAutoConfiguration.

**Comment by rwinch** [comment]
I think the other thing we need to consider is that there is not Java Configuration support for CAS at the moment. So this is likely being blocked by [SEC-2866|https://jira.spring.io/browse/SEC-2866].

It's not that we don't want to add Java Config DSL for CAS, but more of a lack of resources.

**Comment by eddumelendez** [comment]
Unicorn has added [cas-client-autoconfig-support](https://github.com/Unicon/cas-client-autoconfig-support) project which intent to integrate with spring-boot. I think that could be merged inside the spring-boot project to be supported in a native way after talk with the author.

It is feasible to include this in spring-boot or spring-security projects?

**Comment by kakawait** [comment]
I didn't try [cas-client-autoconfig-support](https://github.com/Unicon/cas-client-autoconfig-support) by myself, but it seems to be not using _Spring Security_ and simply init `Filter` from _Apereo CAS client_.

Can be enough for some use case, but I truly think if something should be integrated to _Spring boot_ should be _Spring Security_ way in order to be compliant with other part of _Spring Security_ autoconfiguration or starter.

**Comment by kakawait** [comment]
As promised here my _cas security spring boot starter_ https://github.com/kakawait/cas-security-spring-boot-starter. Is not yet finished, need to write documentations and tests but you can already tests using provided [sample module](https://github.com/kakawait/cas-security-spring-boot-starter/tree/master/cas-security-spring-boot-sample).

@rwinch if you have 10 min to lost I will be happy to get your review about that starter.

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
