### ISSUE TITLE
I need spring-boot-starter-websocket help document

### ISSUE THREAD

**Issue by tongcheng1993** [spring-projects/spring-boot#25402]
Hi:
Springboot Developer
  I want do a demo for spring-boot-starter-websocket ,but not find help document in sping.io  and the pom.xml of spring-boot-starter-websocket ' s  url is 404 . 
  At last, spring boot is a beautiful tools and thanks to the developer  for their work.

**Comment by wilkinsona** [comment]
Thank you for your kind words about Spring Boot and for getting in touch. It feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).

Before posting a question on Stack Overflow, you may want to read the following links:

- https://docs.spring.io/spring-boot/docs/2.4.3/reference/htmlsingle/#boot-features-websockets
- https://docs.spring.io/spring/docs/5.3.4/reference/html/web.html#websocket
- https://spring.io/guides/gs/messaging-stomp-websocket/

This will hopefully allow you to ask a more focussed question which will make it more likely that someone will be able to help you.
