### ISSUE TITLE
 springboot application log config several log files? how to do ?

### ISSUE THREAD

**Issue by cwtree** [spring-projects/spring-boot#25622]
I want to know how to output different log file by the springboot application config ,not logback.xml,because my project used ctrip.apollo to refresh config automatic,If I use logback.xml to config log,the config auto refresh will be very complicated,so when the springboot can define different log files according to packages.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
