### ISSUE TITLE
@EnableWebMvc disables/ignores spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS

### ISSUE THREAD

**Issue by vertti** [spring-projects/spring-boot#2566]
After setting

```
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS = false
```

in `application.properties` I expect methods in `@RestController`s to correctly serialize dates to human-readable format.

This does not work when application uses `@EnableWebMvc`. Removing that annotation or using `@EnableAutoConfiguration` instead and the serialization works as expected.

I would have expected #1620 to fix this but it does not. JSR310 module is loaded correctly but those serialization settings don't work and dates get serialized as a single long number.

I'm using Spring 4.1.1 and Spring-boot 1.2.1.

**Comment by wilkinsona** [comment]
That's the expected behaviour. Using `@EnableWebMvc` disables the auto-configuration of Spring MVC, including the configuring of its message converters to customise Jackson's serialization.

Why are you using `@EnableWebMvc`?

**Comment by wilkinsona** [comment]
Closing due to lack of response. Please comment again and we can reopen the issue if you're still having trouble.

**Comment by adammaass** [comment]
I'm having a similar issue. Why is this expected behavior? (And what do I do when I want to override the Jackson configuration, but leave most of the auto configuration in place?)

**Comment by wilkinsona** [comment]
It's expected behaviour when you use `@EnableWebMvc` as, by doing so, you're telling Boot that you want to take control of Spring MVC's configuration. That includes configuring its HTTP message converters to (de)serialise JSON in the manner that meets your needs.

If you want to override the Jackson configuration, you can either use the `spring.jackson.*` properties or, if you want more control, declare your own `Jackson2ObjectMapperBuilder` bean.

**Comment by crowmagnumb** [comment]
I am also having problems with this. I am using spring-boot 1.2.1.RELEASE with jackson 2.6.2. I as using the single annotation @SpringBootApplication (which supposedly includes the annotation @EnableAutoConfiguration). I have spring.jackson.serialization.write_dates_as_timestamps = false
set in my application.properties (which I know is being read because I tested with banner = false). And yet java.time.LocalDate is *still* being serialized as an array of integers. I am not using @EnableWebMvc anywhere.

**Comment by wilkinsona** [comment]
@crowmagnumb You have a different problem. This issue is about the case when you _are_ using `@EnableWebMvc`.

If you're looking for some help, please ask a question of Stack Overflow using the `spring-boot` tag. If you think you've found a bug, please open a new issue and providing a sample project that illustrates the problem.
