### ISSUE TITLE
Early random server.port assignment

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#2569]
In spring cloud, waiting for the random server port make registering with `Discovery` a tricky game of getting ordering correct.  See https://github.com/spring-cloud/spring-cloud-config/issues/93

Rather than wait for a `ApplicationListener<EmbeddedServletContainerInitializedEvent>`, could `SocketUtils.findAvailableTcpPort()` be used early and set in `ServerProperties`?  Maybe there could be something pluggable such that `@SpringCloudApplications` could have it randomized early, non-cloud, it remains standard.

**Comment by dsyer** [comment]
That's not the recommended approach. `SocketUtils` is primarily for testing, and isn't safe for production use because it just uses random numbers, and there is no way to reserve the port (so race conditions can occur). The containers use native methods to reserve the port so they are safe to carry out the random assignment.
