### ISSUE TITLE
Support Spring Cloud Gateway to enable netty port bind after routers load

### ISSUE THREAD

**Issue by kdlan** [spring-projects/spring-boot#25803]
reference to https://github.com/spring-cloud/spring-cloud-gateway/issues/2169

this may need spring boot project support

**Comment by wilkinsona** [comment]
Netty, like the other web servers that Spring Boot supports, doesn't start listening until the end of context refresh processing. It's triggered by a `SmartLifecycle` immediately before the `ContextRefreshedEvent` is published. As such, I don't think there's anything for us to do here. If Gateway loads it routes as part of standard refresh processing, they'll all be available before Netty starts listening. Let's see what happens with  spring-cloud/spring-cloud-gateway#2169. We can re-open this issue if it turns out that there's something concrete for us to act upon.
