### ISSUE TITLE
Consider removing the hidden spring.jpa.show-sql=true setting from @DataJpaTest

### ISSUE THREAD

**Issue by gregorriegler** [spring-projects/spring-boot#25841]
This setting is rather hidden, hard to find, and can set you up.
I wanted to disable SQL query logging, but somehow the queries continued to show in the console.
Later I found out that the Annotation enabled the setting `spring.jpa.show-sql` which I had disabled.
Now all my tests use `@DataJpaTest(showSql = false)` to avoid flooding the logs.
But I would prefer if the Annotation did not set it to `true` in the first place.

**Comment by gregorriegler** [comment]
I would have never expected this annotation to override show-sql. I expected it to configure the datasource, repositories and so on - yes. but it would be the last place to search for the reason my queries are logged.
I'm searching my configs and my code for that stuff. show-sql false is the default, so I assume that I must have changed it somewhere. "The Framework would never override such a default", is what I'm thinking. Show-sql is very situational, so it's good to default to false.

It is a thing you have to know, and if you don't, well - good luck finding it.
I recommend asking more people that are not biased, like us both. People who never used it perhaps. People who care about their stdout.

**Comment by wilkinsona** [comment]
We haven't asked anyone, biased or otherwise, for their opinion about the current behaviour. The impression that we have is from people's tweets, discussion on Gitter, etc. If anything, we're more likely to notice and remember the negative comments over the positive ones.

In short, we haven't seen feedback from a broad enough number of people to warrant changing the default so we're going to have to agree to disagree here. Thanks again for the suggestion.

I've opened https://github.com/spring-projects/spring-boot/issues/25843 to document things more prominently.
