### ISSUE TITLE
Configuration of ciphers is ignored for TCP with Reactory Netty

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#25913]
Follow-up of https://github.com/reactor/reactor-netty/issues/1543

There is a new API available, but we need to figure out how we could use it without breaking `protected SslContextBuilder getContextBuilder()`.

**Comment by snicoll** [comment]
We probably need a test that exercises the scenario described in the linked issue as well.

**Comment by Johannes-Rost** [comment]
Hello @snicoll,

my initial description of the reactor-netty-Bug includes the steps neccessary to reproduce the bug for a Spring Boot application: https://github.com/reactor/reactor-netty/issues/1543#issue-827899427 
Actualy the Bug is - from my point of view - a regression between Spring Boot 2.3 and 2.4. I filed it as a reactor-netty-Bug because it was caused by a modification to `reactor.netty.tcp.SslProvider`.

I think that it is very difficult to write an automated test for this error, because you would have to examine the resulting SSL configuration of the netty and this configuration does not provide a suitable interface. 

If I can be of any help, feel free to let me know.
