### ISSUE TITLE
Automatically handle Spring autoconfiguration classes first?

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2594]
I've run into an issue a few times where I have an autoconfiguration class that's `@ConditionalOnBean` provided by the main starters, but I have to manually specify that I should `@AutoConfigureAfter` whichever built-in class for Boot to recognize the bean's presence and activate my own configuration. As an example, I have `spring-boot-starter-redis` included, and this condition fails without explicit ordering:

    @Configuration
    @AutoConfigureAfter(RedisAutoConfiguration.class)
    @ConditionalOnBean(RedisConnectionFactory.class)
    @EnableRedisHttpSession
    public class GallerySessionAutoConfiguration {
    }

Would it be feasible and/or sensical to attempt to prioritize autoconfigurations from the official starters so that downstream autoconfiguration packages would more reliably identify framework-provided beans?

**Comment by wilkinsona** [comment]
> Would it be feasible and/or sensical to attempt to prioritize autoconfigurations from the official starters so that downstream autoconfiguration packages would more reliably identify framework-provided beans?

No, I don't think so. If your use case required your configuration to run _before_ some Spring Boot auto-configuration (so that your auto-configuration can supply your own bean in place of one usually provided by Spring Boot, for example) you'd have the exact opposite ordering requirement, would you not?

I think you should stick with explicitly declaring your requirement to be auto-configured before or after the appropriate Spring Boot classes.
