### ISSUE TITLE
Missing AutoConfigureWebTestClient in "Testing with a running server"

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#26146]
From @amirensit on Gitter:

> Hello
In the example of this [section](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-testing-spring-boot-applications-testing-with-running-server) of spring boot testing documentation, Is there a missing @AutoConfigureWebTestClientor Am I wrong ?

It looks to me like it is missing. Removing it from `WebTestClientSpringBootTestIntegrationTests` causes the tests to fail at any rate. I wonder if the subsequent `TestRestTemplate` example is also missing something.

**Comment by snicoll** [comment]
It's a bit more complicated than that. `@AutoConfigureWebTestClient` is required only if the integration test is not running a web server. When it does, both a `WebTestClient` and `TestRestTemplate` are contributed, via a `ContextCustomizerFactory`.

**Comment by bclozel** [comment]
I'm currently looking into #23067 - I'm commenting here first to make sure that I fully understand the current situation and that this new feature will keep things consistent.

Here's my current understanding:

| Annotations                                                    | Server  | Beans configured                    |
|----------------------------------------------------------------|---------|-------------------------------------|
| `@SpringBootTest`                                              | Mock    |                                     |
| `@SpringBootTest` `@AutoConfigureMockMvc`                      | Mock    | `MockMvc`, `MockMvcWebTestClient`*  |
| `@SpringBootTest` `@AutoConfigureWebTestClient`                | Mock    | `WebTestClient`                     |
| `@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)` | Running | `WebTestClient`, `TestRestTemplate` |


With #23067, I'm thinking about adding a `MockMvcWebTestClient` bean to the context (see second line in the table) if the right dependencies are available. Are we considering here documentation updates only? The situation evolved a lot since the introduction of `@SpringBootTest` so we can reconsider a few choices still for future versions.

**Comment by snicoll** [comment]
I am wondering what would be the harm of configuring things in the first case when a  web environment is detected? It feels a bit odd that we do it when a `RANDOM_PORT` or `DEFINED_PORT` web environment is specified, but not when the default `MOCK` applies...

**Comment by mbhave** [comment]
I'm not sure what we need to document here. `@AutoconfigureWebTestClient` is not required when running with a real server. For the mock case, it is [already present in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.testing.spring-boot-applications.with-mock-environment).

**Comment by mhalbritter** [comment]
2.5.x is out of support and the [2.6.x documentation](https://docs.spring.io/spring-boot/docs/2.6.x/reference/htmlsingle/#features.testing.spring-boot-applications.with-mock-environment) states that this is for WebFlux. Is there more to do here?

**Comment by bclozel** [comment]
I think we're good now, thanks for checking @mhalbritter ! I'm closing this as declined since I can't find an issue that really supersedes it.
