### ISSUE TITLE
How to set Spring active profile while running in WebLogic 

### ISSUE THREAD

**Issue by smworld30** [spring-projects/spring-boot#26219]
I want to set spring active profile in weblogic settings.
I have three properties in src/main/resources. For examp : application-dev.properties , application-qa.properties , application-test.properties.

I dont want to keep spring.profiles.active property in my application.properties file. As I have to change it every time whenever I want to deploy in different server. 

I want to active the profile in weblogic (my deploying server for application). Whats is the way and how to fetch the value in springboot application?

Thanks

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
