### ISSUE TITLE
Issue with 2.2.6.RELEASE

### ISSUE THREAD

**Issue by MuthiahPrabhakaran** [spring-projects/spring-boot#26244]
Hi,

I was using the below parent in the pom.

    <parent>

    <groupId>org.springframework.boot</groupId>

    <artifactId>spring-boot-starter-parent</artifactId>

    <version>2.1.4.RELEASE</version>

    <relativePath /> </parent>

Now, I upgraded to 2.2.6.RELEASE

There is no compilation issue. But, When I try to maven install, I am getting the issue "incompatible types: inference variable T has incompatible bounds" on the code:

        Map<String, List<Map<String, Object>>> response =

        objectMapper.readValue(jsonString, new TypeReference<Map<String, Object>>() {

        });`

If I run the above code in a test case or in java main, it works. But, with maven goals, I couldn't succeed.

**Comment by wilkinsona** [comment]
The problem that you are seeing is due to a change in Jackson 2.10 which means that the bounds of your `TypeReference` now have to match the type of your `response` variable. `Map<String, Object>` and `Map<String, List<Map<String, Object>>>` do not match so the code does not compile. See [this Jackson pull request](https://github.com/FasterXML/jackson-databind/pull/2196) for some more information about the change.

Please note that Spring Boot 2.2.x has [reached the end of its open source support period](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#released-versions). You should upgrade to 2.3.x or later at your earliest convenience.

**Comment by MuthiahPrabhakaran** [comment]
@wilkinsona Thanks. Much appreciate your response, I will upgrade to 2.3.x.
