### ISSUE TITLE
Add actuator endpoint to trigger a heapdump, stored in a configurable storage location

### ISSUE THREAD

**Issue by gberche-orange** [spring-projects/spring-boot#2648]
It would be a great to production-ready feature to support triggering heapdumps to ease diagnosing memory leaks in long running servers without requiring expensive APM agents or profiling agents.

@lhotari has done a great job with its [HeapDumpServlet](https://github.com/lhotari/java-buildpack-diagnostics-app/blob/master/src/main/groovy/io/github/lhotari/jbpdiagnostics/HeapDumpServlet.groovy) which triggers an heapdump, and can be configured to store it on local file system or stream it to an S3-compatible bucket for the cases where the application is running into a container with ephemeral filesystem and/or restricted disk space quota.

It would be great to be able to combine basic triggering of heapDump with cloud-specific storage behaviors, e.g. in encapsulated into spring-cloud. For the case of cloudfoundry, having a riakcs/s3 service bound with a name e.g. "diagnostic-dest", would automatically stream the heapdump to the corresponding bucket. Combining on the fly compression, and [multi-part S3 upload](http://stackoverflow.com/questions/8653146/can-i-stream-a-file-upload-to-s3-without-a-content-length-header) integrated into [spring-cloud-aws](http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_uploading_files) would enable reduced bandwidth usage while keeping JVM RAM and local disk usage low.

See related discussion at https://github.com/cloudfoundry/java-buildpack/issues/70#issuecomment-77381507

**Comment by manubharath** [comment]
Hi Phil.. when can we expect this feature to be available? i.e ability to trigger heapdump on a local directory using an actuator endpoint.

**Comment by snicoll** [comment]
@manubharath the fix version is 1.3 which is the next major release of Spring Boot due in Q3. A PR would obviously speed that up if you'd like to give it a try.

**Comment by philwebb** [comment]
I think we'll probably run out of time to consider this for 1.3

**Comment by cemo** [comment]
+1

**Comment by kelapure** [comment]
+1

**Comment by lhotari** [comment]
I have created a pull request for creating and downloading a heapdump, PR #5670 . I hope to get feedback on the pull request about the current changes. If there is acceptance for the feature and general solution, I'll continue on polishing the code, adding documentation and proper test coverage. 

I have spiked a solution idea for the specific feature of transfering the heapdump to a remote storage location. This in a commit lhotari@68f5af9 . Something like that would allow an application to provide a handler for heapdumps so that the application code could implement the transfering of the heapdump by using any suitable method. I'd first like to get the initial pull request #5670 polished before continuing on additional features.

I've also spiked a solution for providing the heap histogram (`jmap -histo:live`) information parsed as json. That's in https://github.com/lhotari/spring-boot/commit/17248cd76eee005a208a430a48dc5dce54e822e8 . I'll send a separate pull request for that after finishing the first one.

**Comment by jgoldhammer** [comment]
+1

**Comment by drkarl** [comment]
Our application uses a distributed architecture based on microservices, and we deploy each microservice with docker. Kubernetes can kill a bad pod and create a new one with a liveness probe based on the Actuator `/health` endpoint but then we might lose valuable debugging and diagnosing information since the heap dump would be lost in case of a OOM.

I found this issue and since it's open and the PR https://github.com/spring-projects/spring-boot/pull/5670 is closed I thought it was not merged (we're using Spring Boot 1.3.x at the moment) but then I realized it has been merged separately and it's in Spring Boot 1.4.x (at least in 1.4.2.RELEASE if I'm not mistaken).

So first thing is, since this functionality has been added, I think this issue could be closed.

Second thing is a suggestion, I was going to write the heap dump enpoint myself and since we're currently using IBM JVM I thought about injecting a strategy interface bean and have an implementation for IBM JVM that would use `com.ibm.jvm.Dump.HeapDump()` and another implementation for Oracle Hotspot and OpenJDK that used `com.sun.management.HotSpotDiagnosticMXBean`, but since there's already an implementation I'd rather use that, but unfortunately it doesn't inject the implementation of the `HeapDumper` interface, there is a protected method `createHeapDumper()` that returns an instance of `HotSpotDiagnosticMXBeanHeapDumper`, but it's not possible to provide another bean implementation of `HeapDumper`, like an `IBMJavaHeapDumper`, since it's a protected method the only solution would be to extend `HeapdumpMvcEndpoint` and override `createHeapDumper()`.

I think a much cleaner solution would be to inject the `HeapDumper` using Spring DI and by default have it inject the bean `HotSpotDiagnosticMXBeanHeapDumper` which could be replaced by another implementation.

**Comment by wilkinsona** [comment]
@drkarl Thanks. You're right that this issue should have been closed in favour of #5670. I'll do that now.

> since it's a protected method the only solution would be to extend HeapdumpMvcEndpoint and override createHeapDumper()

The method is `protected` specifically for this reason.

> I think a much cleaner solution would be to inject the HeapDumper using Spring DI

I'm not sure it makes much different. You either have to declare your own `HeapDumper` bean or declare your own `HeapdumpMvcEndpoint` bean. There's very little difference in the amount of code that you'd need to write.

**Comment by wilkinsona** [comment]
As noted above, this was delivered by #5670 and is available in Spring Boot 1.4.0.RC1 and later.
