### ISSUE TITLE
Spring Actuator Security with Spring boot

### ISSUE THREAD

**Issue by cristianprofile** [spring-projects/spring-boot#2653]
When I create a web app with spring boot/mvc with spring security and I try to get secure my actuator's endpoints Spring security redirect my actuator context path to context path/login. 

**App Config**

application.yml

```server:
    port: 9090
    contextPath: /pizza
    session-timeout: 10
management:
    port: 9091
    address: 127.0.0.1
    context-path: /manage
    security: 
            enabled: true
            role: ADMIN
```

security config class
 
```
 http.authorizeRequests().antMatchers("/pizzas","/info","/addPizza").hasAnyRole("USER","ADMIN").and()
		.authorizeRequests().antMatchers("/users","/addUser").hasRole("ADMIN").and()
		.authorizeRequests().antMatchers("/static/**","/logout","/login").permitAll();

http.formLogin().loginPage("/login").failureUrl("/login?error").permitAll();
		
http.logout().logoutSuccessUrl("/?logout").deleteCookies("remember-me").permitAll();
```        

Http request redirect to localhost:9091/manage/login.This mapping is obviously wrong because it does not exist. Login page was created at pizza context path which is the context of Spring Boot web app.
 
Which would be the best way to use Spring security configured at my app (pizza) to be used in actuator security?

**Comment by rwinch** [comment]
Thank you for the question.

You cannot use the login page from your main Spring Application within actuator security. The reason is that the cookie is going to be associated with the domain + port + context path of the application. This is part of the [Same Origin Policy](http://en.wikipedia.org/wiki/Same-origin_policy)

This means if you sent the user to localhost:9090/pizza/login and authenticated, when you visited localhost:9091/manage/ the JSESSIONID cookie would not be submitted to the management application which means you would not be seen as authenticated.

In order to authenticate across domains (i.e. different ports in this case) you would need some single sign on (OpenID, CAS, SAML, etc) mechanism.

In order to do this you would need to setup a login page within the management application. To do this you would just need to return an HTML form when /login is requested. However, I'm not really certain how you would do that within the Boot management application. Perhaps @philwebb or @dsyer can elaborate on how one would do that.

Alternatively you could create separate security configuration for the management application that allows authenticating with Basic Authentication. To do this you would create another Security Configuration that looks something like this:

```java
@Order(0)
@Configuration
public class ManagementSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
         http
            .requestMatchers()
                .requestMatchers(request -> "/manage".equals(request.getContextPath()))
                .and()
            .authorizeRequests()
                .anyRequest().hasRole("ADMIN")
                .and()
            .httpBasic();
    }
}
```

This would make sure that if the context root is "/manage" that this security configuration is used. A few points of interest:

* `@Order(0)` makes sure the configuration occurs before your other security configuration since by default any subclass of `WebSecurityConfigurerAdapter` will be ordered at 100. This is important because only the first `WebSecurityConfigurerAdapter` is used (similar to the authorizeRequests() matchers).
* The request matcher is using a lambda for matching on the contextPath. I had thought there was a better way to distinguish Spring Boot application from the main application, but it does not appear that is the case. Perhaps @dsyer knows how this should be done.

**NOTE** You can rewrite your configuration much more concisely as:

```java
 http
    .authorizeRequests()
        .antMatchers("/pizzas","/info","/addPizza").hasAnyRole("USER","ADMIN")
        .antMatchers("/users","/addUser").hasRole("ADMIN")
        .antMatchers("/static/**","/logout","/login").permitAll()
        .and()
    .formLogin()
        .loginPage("/login")
        .failureUrl("/login?error")
        .permitAll()
        .and()
    .logout()
        .logoutSuccessUrl("/?logout")
        .deleteCookies("remember-me")
        .permitAll();
```

**Comment by cristianprofile** [comment]
Thank you very much for your fast and great response. I will give it a try to test it this week at work and I will give you feedback about this approach to add spring security to actuator module in spring boot application.

**Comment by cristianprofile** [comment]
What a great solution for my problem, I have just tested it and it works fine. 1000000000 thanks to help me with this problem. Spring support is amazing, as good as the framework.

**Comment by ccit-spence** [comment]
@rwinch I am working on a similar situation and your answer about a separate security configuration works.  

The only question / concern I would have is that using basic auth technically I can't logout.  Am I wrong?  If I am right, did you find out anything about providing a form for securing the management endpoint.  The rest of the app is public facing in our case. No security otherwise.

**Comment by rwinch** [comment]
I think we would need to ask @philwebb or @dsyer on how to create custom endpoints for the Actuator application.

A workaround you could do is create a login page in the main application that submits to the Actuator host and port. The disadvantage is that the login page may be viewable by the outside world.

**Comment by ccit-spence** [comment]
Let me rethink my strategy on this then.  This is a Spring Cloud based application.  The plan is to deploy without any customer login capabilities initially.  We do plan on implementing later for various services.  

That being said my thought was that it would be more secure having management endpoints on another port.  

I am not 100% against going ahead and implementing the SSO/Oauth portion now.  If someone hits the login page which initially could only be reached by trying to hit a URL that was secured.  Then so be it.  

Does this sound ok?  Are there any security issues with having the endpoints on the same port?  Other than a good password policy.

**Comment by rwinch** [comment]
> That being said my thought was that it would be more secure having management endpoints on another port.

This is true because you setup your firewall to have different rules for the administrative portion. For example, it might only allow access to the administrative portion within your internal network.

> I am not 100% against going ahead and implementing the SSO/Oauth portion now. If someone hits the login page which initially could only be reached by trying to hit a URL that was secured. Then so be it.

If you don't need authentication within the public facing portion of the application there is no need for SSO.

If you are ok with separating the login page for the public facing portion with the administrative portion you are also fine (this is likely a good idea anyways).

**Comment by ccit-spence** [comment]
I will play around with this today/tonight.  Spring Cloud and Zuul add a little more complexity to the mix.  Will try out various scenarios to see what makes the most sense.  This is all on AWS.  I can block IP's to the endpoints via port using security groups.  I want the extra layer of security in case spoofing happened.

> If you don't need authentication within the public facing portion of the application there is no need for SSO.

We don't need it now, we will later.  Typical timeline forcing us to get the app out the door. With minimum viable product.

Will post back my findings.

**Comment by fpmoles** [comment]
What we really need is the ability to have 2 separate providers. We want to tie actuator to LDAP (Active Directory) and tie our application to our existing SSO application. Thoughts?
@rwinch @philwebb

**Comment by rwinch** [comment]
@fpmoles You can slice the application so that the actuator endpoints start with something like `/manage/` then you can use Spring Security to provide different security for each of the slices. See https://docs.spring.io/spring-security/site/docs/current/reference/html/jc.html#multiple-httpsecurity
