### ISSUE TITLE
gradle bootWar generated war exposes classes files

### ISSUE THREAD

**Issue by 95th** [spring-projects/spring-boot#26594]
Spring boot version: 2.4.5 (same version of gradle plugin)

The spring boot generated war file has some spring classes in the war's root which is public by default. When deployed on tomcat, I am able to download these classes. Shouldn't these classes go in the WEB-INF/classes?

Also, It seems these classes are for making the war "executable" using `java -jar warname.war` like a jar file. I don't need that. Is there any way to disable making the war executable like jar?

How do I get rid of these class files from the generated war apart from manually deleting it or moving them into WEB-INF/classes?

![1](https://user-images.githubusercontent.com/22871609/118801897-242b1680-b8bf-11eb-9b97-0b03eecd5449.JPG)
![2](https://user-images.githubusercontent.com/22871609/118801907-27260700-b8bf-11eb-9851-e12edb6084ed.JPG)

**Comment by wilkinsona** [comment]
> Shouldn't these classes go in the WEB-INF/classes?

They need to be in the root of the war file so that they can be found when it is run using `java -jar`.

>  I don't need that. Is there any way to disable making the war executable like jar?

If you don't want your war file to be executable then you should build it using the `war` task rather than the `bootWar` task. You may want to either [just use Spring Boot's dependency management](https://docs.spring.io/spring-boot/docs/2.4.5/gradle-plugin/reference/htmlsingle/#managing-dependencies-dependency-management-plugin-using-in-isolation) or you may want to re-enable the `war` task and disable the `bootWar` task:

```
war {
    enabled = true
}

bootWar {
    enabled = false
}
```

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
