### ISSUE TITLE
Warnings on startup with atomikos starter dependency

### ISSUE THREAD

**Issue by robertvanloenhout** [spring-projects/spring-boot#26656]
I have a spring boot application with postgresql and rabbitmq. I wanted to use a best-effort JTA transaction that contains both a postgres and rabbitmq transaction.
I have added the spring-boot-started-jta-atomikos dependency. When I start my application I receive this warning multiple times:
```
atomikos connection proxy for Pooled connection wrapping physical connection org.postgresql.jdbc.PgConnection@99c4993: WARNING: transaction manager not running?
```

Do I need any additional configuration?

I also get this warning at startup:

AtomikosDataSoureBean 'dataSource': poolSize equals default - this may cause performance problems!

I run with the following settings, but setMinPoolSize is never called
```
spring.jta.atomikos.connectionfactory.max-pool-size: 10
spring.jta.atomikos.connectionfactory.min-pool-size: 5
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
