### ISSUE TITLE
Stored procedure call with schema name "{call {h-schema}INSERT_BAGIDPROCESS(:sUserId,:iClientno,:iSiteno,:sStartdate,:sEnddate)}"

### ISSUE THREAD

**Issue by udaykumar235** [spring-projects/spring-boot#26661]
Hi,

@Modifying
	@Query(value = "{call **{h-schema}**INSERT_BAGIDPROCESS(:sUserId,:iClientno,:iSiteno,:sStartdate,:sEnddate)}",nativeQuery = true)
	int insertRecordsByProcedure(@Param("sUserId") String sUserId,@Param("iClientno") Integer iClientno,
			                     @Param("iSiteno") Integer iSiteno,@Param("sStartdate") String sStartdate,
			                     @Param("sEnddate") String sEnddate);

if i pass dynamic schema name as {h-schema} it is thowing error .if pass static schema name lik EVAS IT IS TAKING..
SO ANY ONE GIVE SOLUTION

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
