### ISSUE TITLE
Resource bundles defined in multiple modules are not merged

### ISSUE THREAD

**Issue by LingCai2001** [spring-projects/spring-boot#26712]
I found a problem loading the internationalized resource file. When I need to load international resource files in multiple jar packages, org.springframework.boot.autoconfiguration.context.MessageSourceAutoConfiguration, which is automatically assembled by springboot, can't be loaded for me. I think it's an error because of module reuse in development; What do you say?
Remarks:
    SpringBootVersion: 2.5.0

**Comment by LingCai2001** [comment]
I hope the government can fix the problem and release a new version of SpringBoot as soon as possible. Thank you.

**Comment by snicoll** [comment]
@LingCai2001 sorry but I am not sure I understood the problem you're describing. Can you please share a small sample that we can run ourselves (no screenshot or code in text please)? You can do so by attaching a zip to this issue or sharing a link to a GitHub repo. Thank you!

**Comment by LingCai2001** [comment]
Wait a moment.Thank you.

**Comment by LingCai2001** [comment]
> @LingCai2001 sorry but I am not sure I understood the problem you're describing. Can you please share a small sample that we can run ourselves (no screenshot or code in text please)? You can do so by attaching a zip to this issue or sharing a link to a GitHub repo. Thank you!

Wait a moment.Thank you.

**Comment by LingCai2001** [comment]
[BugTest.zip](https://github.com/spring-projects/spring-boot/files/6573166/BugTest.zip)
@snicoll For detailed bug recurrence, please refer to the description tag of Maven's parent pom.xml. Thank you!

**Comment by snicoll** [comment]
@LingCai2001 thanks for the feedback and the samples. I understand what you're trying to do now.

The [reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.internationalization) states that:

> Spring Boot looks for the presence of a messages resource bundle at the root of the classpath.

There's no such thing as merging multiple resource bundle files in the classpath. If you remove the resource bundle in your `a` module and restart you'll notice that `http://localhost:8080/b` works now, but `http://localhost:8080/a` does not. We can't really offer that feature: in your case the keys in the files were disjoint but what happens if we have the same key in more than one file?

Having said all of that, I was a bit surprised that it wasn't more prominent in the documentation. @jhoeller, what do you think? Have I missed something?

**Comment by LingCai2001** [comment]
Thank you. I see what you mean; My suggestion is that you can extend one more class to merge resource packages in multiple projects.

**Comment by LingCai2001** [comment]
@snicoll Thank you. I see what you mean; My suggestion is that you can extend one more class to merge resource packages in multiple projects.

**Comment by LingCai2001** [comment]
@snicoll Thank you for your reply.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by snicoll** [comment]
@jhoeller and I discussed and we have no intention of supporting the use case you've described as we're delegating to `ResourceBundle` for this. We agree that making it a bit more explicit in the doc is a good idea so I've opened https://github.com/spring-projects/spring-framework/issues/27038.
