### ISSUE TITLE
Upgrade to Spring Data Fowler

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#2673]

**Comment by wilkinsona** [comment]
An upgrade to RC1 has [broken the CI build](https://build.spring.io/browse/BOOT-PUB-JOB1-2328/test/case/154218551). There appears to be a dependency on Spring Data on Java 8's `java.lang.reflect.Executable` but, looking at the source, I can't see where it's coming from. Any ideas, @olivergierke?

**Comment by olivergierke** [comment]
That's probably a stale local Maven cache. We initially released Spring Data Commons with that reference but rolled that back and effectively re-released it.

@trevormarshall Any chance you re-wipe all Spring Data Commons libraries from the caches? Coordinates `org.springframework.data:spring-data-commons`.

**Comment by jhoeller** [comment]
Hmm, we had a similar problem back in the Spring Framework 4.0 milestone phase, coming from a ternary expression à la `(this.method != null ? this.method : this.constructor)` which the compiler will determine the result type for, putting it into the bytecode. The most common type for those two used to be `AccessibleObject` but as of Java 8 is `Executable` which is a pretty tricky side effect, since it happens when the sources get compiled on Java 8, independent from the target bytecode level. The solution is to avoid such method/constructor ternary expressions specifically and code them as if-else statements instead (which the compiler isn't going to determine a common supertype for).

**Comment by jhoeller** [comment]
See https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/MethodParameter.java#L163 and onwards for the affected code back then.

**Comment by olivergierke** [comment]
That's good to know. We actually had a common method introduced to work with both `Constructor` and `Method` but reverted that in the re-release.

**Comment by trevormarshall** [comment]
@olivergierke caches have been cleared out.

**Comment by wilkinsona** [comment]
`RepositoryRestConfiguration.setBaseUri(URI)` has been deprecated. We should update `RepositoryRestMvcAutoConfigurationTests.testWithCustomBaseUri` and `spring-boot-sample-data-rest` to use `spring.data.rest.basePath` rather than `spring.data.rest.baseUri`.

**Comment by wilkinsona** [comment]
We should also check that we're using the correct version of Jedis, etc.
