### ISSUE TITLE
Out-of-the-box support for status-specific error pages

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2691]
I am replacing the whitelabel error view in my Boot application, and it looks like the `BasicErrorController` either forwards to a registered `ErrorPage`, which needs to have its own controller mapping (at least with Thymeleaf on Undertow) or renders the view named exactly `error`.

Since many applications will want custom error pages for different status codes, but there's little custom logic in most of the standard responses, it would be convenient if `BasicErrorController` rendered `error/${status}` if the template exists before falling back to `error`. That would enable developers to create a custom 404 page, for example, by just defining a `/templates/error/404.html` or equivalent in their preferred engine without needing configuration.

**Comment by chrylis** [comment]
Implementation for equivalent behavior:

```groovy
@Controller
@RequestMapping('/error')
class ErrorPagesHtmlController {

    @RequestMapping('/{status}')
    String errorPage(@PathVariable String status) {
        "error/$status"
    }
}
```

```java
@Bean
public EmbeddedServletContainerCustomizer errorPageCustomizer() {
    return (container -> {
       container.addErrorPages(new ErrorPage(HttpStatus.NOT_FOUND, "/error/404"));
    });
}
```

**Comment by cemo** [comment]
+1

**Comment by snicoll** [comment]
I've started to work on this and I have a few issues:

* There is no single place where we define the location for templates (`classpath:/templates`). Maybe it would make sense to have a `spring.resources.templates-locations` alongside `spring.resources.static-locations` ? That way I could retrieve that property rather than hard-coding it
* The code is doing an hard check on the `error` sub-directory with no way to customize it.
* For each template found, a separate `WebMvcConfigurerAdapter` registers a controller for it. I am not sure I fully understand the cycle yet but it would be better (IMO) to go the general error page and then redirect to the appropriate view. That way we would have access to error attributes.

**Comment by philwebb** [comment]
I'm still reviewing this but I have a feeling we might be able to directly use the `ViewResolvers` rather than scanning for resources.

**Comment by snicoll** [comment]
That wouldn't work for static assets and would be harder to figure out what to do in case of conflicts (static asset and template matching the same status code). But I am happy to see what you propose!

**Comment by philwebb** [comment]
I think I've got something that works. Needs polish and tests.

https://github.com/philwebb/spring-boot/tree/gh-2691-2

**Comment by chrylis** [comment]
Given the nature of the templates, is there a specific design goal behind resolving the templates on-demand per-request instead of caching the views?

**Comment by philwebb** [comment]
@chrylis I assume you mean cache the result of the `TemplateAvailabilityProvider` result. I've opened #5933 for that but I'm not sure it's really worth it. Can you add more context to that issue?
