### ISSUE TITLE
Spring boot live reload not working in vs code

### ISSUE THREAD

**Issue by vipulchakravarthy** [spring-projects/spring-boot#26913]
I'm a newbie to spring boot. I have added spring boot dev-tools dependency for making server auto restart whenever I change something in code. Unfortunately its not working as expected.

System: Mac M1
IDE: vscode

Please find my repo here [https://github.com/vipulchakravarthy/spring-boot-project](url).
Command to run the project, head into demo folder
In mac: ./mvnw spring-boot:run
windows: mvnw spring-boot:run

Any help will be really appreciated. Please find the attached image for reference.

<img width="1296" alt="Screenshot 2021-06-15 at 12 49 35 PM" src="https://user-images.githubusercontent.com/41899503/122024223-dd5d0d80-cde5-11eb-898f-bcfa1d21d71f.png">

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
