### ISSUE TITLE
On Undertow, a custom error page not used for 500 resulting from RuntimeException

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2692]
From an MVC controller method, `throw new RuntimeException()` always causes `BasicErrorController` to render the default error view, even if a specific `ErrorPage` is registered for 500. Throwing a custom exception annotated with `@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)` renders the custom error page specified.

**Comment by chrylis** [comment]
I'm unable to reproduce this in a clean project.

**Comment by chrylis** [comment]
I'm still seeing this in my main project, and the distinction is that a thrown `RuntimeException` from the controller method bubbles a `NestedServletException` all the way up to Undertow. Throwing a `CustomException extends RuntimeException` is handled by Spring before it gets to the container.

**Comment by chrylis** [comment]
Replicated. Undertow-specific bug.

https://github.com/chrylis/spring-boot-2692

**Comment by wilkinsona** [comment]
@chrylis Thanks for the project that reproduces the problem

**Comment by wilkinsona** [comment]
I don't think we can fix this in Spring Boot. The problem appears to be due to the way that Undertow performs its error page routing.

When an annotated exception is thrown the failure is handled via its error code and Undertow successfully maps 500 to `/error/500`. When it's a plain `RuntimeException`, Undertow tries to map the exception first and then tries to map 500. From `ServletInitialHandler`:

```java
    String location = servletContext.getDeployment().getErrorPages().getErrorLocation(t);
    if (location == null) {
        location = servletContext.getDeployment().getErrorPages().getErrorLocation(500);
    }
```
There's no mapping for `RuntimeException` but, rather than returning `null`, the first call to `getErrorLocation` returns the default error page mapping, `/error`. This means that the call to `getErrorLocation(500)` is never made so the request is routed to `/error` rather than `/error/500`. In summary, Undertow's logic is:

1. See if the exception's been mapped
2. See if there's a default error page
3. See if 500's been mapped.

A workaround is to update the application's configuration to map `RuntimeException` to `/error/500` rather than relying on the container's behaviour:

```java
    @Bean
    EmbeddedServletContainerCustomizer errorPageCustomizer() {
        return (container -> {
            container.addErrorPages(
            	new ErrorPage(RuntimeException.class, "/error/500"),
                new ErrorPage(HttpStatus.NOT_FOUND, "/error/404"),
                new ErrorPage(HttpStatus.INTERNAL_SERVER_ERROR, "/error/500")
            );
        });
    }
```

As noted above, this problem doesn't occur on Tomcat. Tomcat's logic is subtly different:

1. See if the exception's been mapped
2. See if 500's been mapped
3. See if there's a default error page

I've opened [UNDERTOW-412](https://issues.jboss.org/browse/UNDERTOW-412). I'd recommend using the workaround described above until that issue's addressed.
