### ISSUE TITLE
How to get spring mvc server response time metric NOT the “http_server_requests_seconds”?

### ISSUE THREAD

**Issue by qianweichun** [spring-projects/spring-boot#27126]
The http_server_requests_seconds metric includes the network traffic time to client, so when the client network is not stable, the http_server_requests_seconds value could be larger than expected.  
I believe it is much more meaningful to get the server side respond time.

**Comment by snicoll** [comment]
I've moved this issue as the Spring Framework issue tracker is not the right place for reporting something against Spring Boot. Getting that information is intentional, if you don't have the client-side instrumented, how else would you know your users are having a slow response? 

If you're interested by the server processing time `@Timed` can be used. If you have further questions, please ask on Stack Overflow.
