### ISSUE TITLE
No load some beans when the property starts with spring.multi....

### ISSUE THREAD

**Issue by reyfren06** [spring-projects/spring-boot#27128]
Hello All, 

I just upgrade to spring boot 2.5.1 and spring cloud. In my project I have implemented the connection to multi-rabbit added more beans for publishing, consumer and listener.  it happened me something curious, when my properties of host, user, pass etc.. start with spring.multirabbit... some beans aren't load hence the @RabbitListener doesn't load fine and my apps doesn't run. 

**multirabbitmq**:
     enabled: true
     publisher:
       enabled: true
       first:
         host: rmqmuldvlsk00.santanderuk.pre.corp

**rabbitmqmulti**:
     enabled: true
     publisher:
       enabled: true
       first:
         host: rmqmuldvlsk00.santanderuk.pre.corp

Changing the name to rabbitmqmulti if it works, Is there something that impacts on the property name? With the previous version 2.3.4.RELEASE this didn't happen.

**rabbitmqmulti**:
    enabled: true
    publisher:
      enabled: true
      first:
        host: rmqmuldvlsk00.santanderuk.pre.corp

**Comment by wilkinsona** [comment]
Spring Boot doesn't provide RabbitMQ multi-broker support and, therefore, doesn't define any configuration properties for it. A change in property prefix from `multirabbitmq` to `rabbitmqmulti` is out of Spring Boot's control and will, presumably, be due to a change in the code that you're using for multi-broker support. You may want to check the library that you are using for multi-broker support and any recent changes that have been made to it.
