### ISSUE TITLE
Customize default resource handler

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-boot#27179]
I want to use the default resource handler that is configured in `spring.web.resources` properties, but add my customization (add an unminify `ResourceResolver`).
I'm using `WebMvcConfigurer` with `addResourceHandlers( ResourceHandlerRegistry registry )`.

Registering a resource handler using `ResourceHandlerRegistry` overwrites the default customization, so if I manually register the resource handler, I loose all the properties customization (compression, cache, etc.).
The important class that customizes the resource handler by default is the private class [ResourceChainResourceHandlerRegistrationCustomizer](https://github.com/spring-projects/spring-boot/blob/fa1eb544c159076389580134540988030b4724ea/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.java#L635).

Currently there is no way to reuse this code.
It would be nice to provide a method to customize the default behavior.

**Comment by cdalexndr** [comment]
Tried to move configuration from properties file to programmatic configuration, but now thymeleaf resource links do not contain version from content version strategy. This is because in `ThymeleafAutoConfiguration`, _resourceUrlEncodingFilter_ has `@ConditionalOnEnabledResourceChain` that requires property configuration.

Workaround: copy-paste code to force create the `ResourceUrlEncodingFilter` bean. Downside is missing future updates from spring for this piece of code...

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I wonder how practical it would be to allow customization of the default resource handler. For example, if you need to add a resolver in a particular position in the `ResourceChainRegistration` I don't think that's something that we could support with some changes in Framework. The same problem would affect `ResourceChainResourceHandlerRegistrationCustomizer` if we opened it up as well.

With that said, I'm not an expect on MVC's resource chain support. @bclozel and the rest of the team may have some better ideas.

**Comment by cmrg-chb** [comment]
I am in the same situation and would like to customize the default `ResourceHttpRequestHandler` . My use case is that I need to replace/overwrite the content-type of the delivered resource (x-gzip for a *.js.gz resource) with (encoding=gzip, content-type=application/javascript) due to a client that is very strict/stubborn (Unity WebGL player).

It would be very easy to do so, if I could replace the default handler, with a subclass that overrides `getMimeType()` and then provide the desired types based on the request path.

Unfortunately I cannot intercept the creation of `ResourceHttpRequestHandler` - if it were created with a factory or provider that is available as a bean, my problem would be solved.

Using Spring Boot 3.x at the moment, it seems that the API has not really been opened much more in this respect. Does anybody know a work around?

**Comment by cmrg-chb** [comment]
PS: there is [this solution](https://stackoverflow.com/a/43333113) to register a custom resource handler for a specific URL/path but as OP mentioned: 

> if I manually register the resource handler, I loose all the properties customization (compression, cache, etc.)
