### ISSUE TITLE
Spring May Create An ApplicationListener with Class Annotated With @Component Twice

### ISSUE THREAD

**Issue by hyn1055543778** [spring-projects/spring-boot#27237]
Firstly, I define my ApplicationListener in META-INF/spring.factories as folllows:
![image](https://user-images.githubusercontent.com/22980467/125183630-b827b780-e24a-11eb-8006-882de9989de6.png)
Secondly, I annotate the ApplicationListener with Annotation @Component as follows:
![image](https://user-images.githubusercontent.com/22980467/125183632-bfe75c00-e24a-11eb-8d75-732dbf9c9724.png)
Thirdly, When I run my application, I get the following results:
![image](https://user-images.githubusercontent.com/22980467/125183645-e3aaa200-e24a-11eb-8d52-3b6d6a4fce14.png)
the output result shows that MyListener has been created twice, which has different reference, which results in this listener is called twice. Is this the expected result? Why a class annotated with @Component can still be instaniated twice.
spring boot version: 2.5.2
my sample code : 
[bug-test.zip](https://github.com/spring-projects/spring-boot/files/6796377/bug-test.zip)

**Comment by snicoll** [comment]
Yes it is the expected behaviour. You are registering two components really, one using `spring.factories` and one by using classpath scanning and flagging the class as being a component. If you have further questions, please follow-up on Stackoverflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by hyn1055543778** [comment]
thank you
