### ISSUE TITLE
Include spring-r2dbc?

### ISSUE THREAD

**Issue by ThomasKasene** [spring-projects/spring-boot#27364]
Probably the Spring Boot team is already keeping track of this internally, but `org.springframework:spring-r2dbc` was introduced in Framework 5.3.9. I can't find any references to it in the Boot dependency management though, and #27163 did not contain anything.

Are there any plans to add it to 2.5.x or will it have to wait until 2.6.x due to the number of breaking changes?

Thanks!

**Comment by ThomasKasene** [comment]
Nevermind, I see it's being pulled in transitively through Spring Data R2DBC...

**Comment by wilkinsona** [comment]
Just to avoid any confusion, `org.springframework:spring-r2dbc` was introduced in Spring Framework 5.3.0. Its version is managed by `spring-framework-bom` which Spring Boot's dependency management imports. As a result, [we've had dependency management for it in Boot since 2.4](https://docs.spring.io/spring-boot/docs/2.4.0/reference/htmlsingle/#dependency-versions-coordinates) where we upgraded to Spring Framework 5.3.
