### ISSUE TITLE
How to cancle table and column alias

### ISSUE THREAD

**Issue by wuguowei19880907** [spring-projects/spring-boot#27507]
I use jpa in spring boot 1.5.10.version.
Default, i found that the sql in console printed with table alias and columns,**_how can i remove the table alias and console alias._**
the hibernate print sql:
`Hibernate: select adminuserd0_.id as id1_9_, adminuserd0_.avatar as avatar2_9_, adminuserd0_.created_at as created_at3_9_, adminuserd0_.deleted_at as deleted_at4_9_, adminuserd0_.disabled as disabled5_9_, adminuserd0_.password as password6_9_, adminuserd0_.phone as phone7_9_, adminuserd0_.real_name as real_name8_9_, adminuserd0_.sex as sex9_9_, adminuserd0_.updated_at as updated_at10_9_, adminuserd0_.username as username11_9_ from sharding_test2.admin_user adminuserd0_ where adminuserd0_.username=?`

the entity file is:
![image](https://user-images.githubusercontent.com/19338820/127136018-d77d7e04-f8bd-4189-a70c-e2dab9ef860e.png)

the Repository file like this:
![image](https://user-images.githubusercontent.com/19338820/127136235-598a084b-d69d-4e37-a738-b961e767204d.png)

i use jpa like this:
![image](https://user-images.githubusercontent.com/19338820/127136147-316c4812-9f4e-4eff-9a8c-91d6a7a02721.png)

@qerub @jkutner @scheerer @rtack @xenoterracide

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
