### ISSUE TITLE
How does the format of spring boot Maven plugin repackage above 1.5.15 become 1. X format

### ISSUE THREAD

**Issue by cnzxc** [spring-projects/spring-boot#27580]
This is a new repackaged format

![image](https://user-images.githubusercontent.com/69956091/128446881-c7dfebd6-81d1-420b-a890-a07d4f8519b7.png)

This is a old repackaged format

![image](https://user-images.githubusercontent.com/69956091/128447153-575cf97f-3e83-41dd-8763-627cf7db4e42.png)
  
  
What can I do to package the new plugin into the old format

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
