### ISSUE TITLE
Circular reference error when invoking `@Bean` method in `@PostConstruct` method

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#27782]
To reproduce it, run `ApplicationTests.test()` with the following sample: https://github.com/izeye/spring-boot-throwaway-branches/tree/minimal

It fails with Spring Boot 2.6.0-M2, but passes with 2.6.0-M1.

This was just an experimental code, not for any real usage. I'm just sharing this behavioral change as it might be a side effect of some unintended changes.

Feel free to close this if it's not an issue.

**Comment by wilkinsona** [comment]
This was intended. It's due to [circular references now being prohibited by default](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6.0-M2-Release-Notes#circular-references-prohibited-by-default). In this case, creating `SampleConfig` requires the `Person` bean to be created and, as the `person()` method is not static, creating the  `Person` bean requires `SampleConfig` to be created.
