### ISSUE TITLE
boot 2.4.6  no message being typed on the console

### ISSUE THREAD

**Issue by wanghwtaiji** [spring-projects/spring-boot#27824]
spring boot 2.4.6中：`spring:profiles:active :test,nacos` and `spring:profiles:active: - prodall group:prodall: - nacos- dev` 。
These two writing methods result in no message being typed on the console
<img width="599" alt="微信图片_20210827144238" src="https://user-images.githubusercontent.com/17980037/131083997-fada6be2-84c1-4af1-9d04-0614d2d83bfb.png">

**Comment by wanghwtaiji** [comment]
https://github.com/wanghwtaiji/springboot-nacos 

Zip and RAR cannot be uploaded.  You need a Nacos or Consul;  It is best to nacos

**Comment by philwebb** [comment]
It's still not clear what issue you're reporting and if it's an issue with Spring Boot, Spring Cloud or some other library. Can you please explain the steps necessary to replicate the problem with the sample and what you mean by "These two writing methods result in no message being typed on the console"?

**Comment by wanghwtaiji** [comment]
This project is registered in NACOS, and there is a corresponding configuration file in the NACOS configuration center. The 'Spring: Profiles: Active: Test, NACOS' I set is ok in 2.3.x, but when using 2.4.x, the console cannot output information, as shown in the picture above.  But if I configure two 'Spring: Profiles :active :test' and' Spring: Profiles :active :nacos', I can print messages again.

**Comment by philwebb** [comment]
This is probably related to configuration processing updates that we made in Spring Boot 2.4 (see the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#config-file-processing-application-properties-and-yaml-files)). I'm not familiar enough with NACOS, but I suspect they might need to make some changes in order to support Spring Boot 2.4. See https://github.com/spring-cloud/spring-cloud-config/pull/1656 for a similar update that was made to Spring Cloud Config Server.

For now, you might want to try setting `spring.config.use-legacy-processing` to `true` as described in https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide.
