### ISSUE TITLE
It is recommended not to initialize the log configuration recursively, which will lead to unnecessary memory occupation

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#27844]
It is recommended not to initialize the log configuration recursively, which will lead to unnecessary memory occupation

When calling the ``LoggingSystem#getLoggerConfigurations`` method, you only need to return the log level configured by the developer, because others are default

For example, I only configured ``logging.level.com.bruce.consumer.controller=debug``, so there is no need to create a LoggerConfig object for ``com.bruce``, Lazy loading is more reasonable

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/log4j2/Log4J2LoggingSystem.java#L275,#L278

![image](https://user-images.githubusercontent.com/13413715/131629835-cdf7d979-93f0-4ac8-9ee1-982246686b3b.png)

However, in the implementation of logback, logback will recursively create logger objects. This is a bad design because it wastes memory. Maybe an issue should also be submitted to logback to optimize this problem.

For example, I only configured ``logging.level.com.bruce.consumer.controller=debug``, so there is no need to create a ``Logger `` object for ``com.bruce``, Lazy loading is more reasonable

@see ch.qos.logback.classic.LoggerContext#getLogger(java.lang.String)

![image](https://user-images.githubusercontent.com/13413715/131631082-b2b5d6d7-fa18-4a94-a15c-f4abe05a92dd.png)

**Comment by philwebb** [comment]
We specifically want logging configurations to be included in the result of `LoggingSystem#getLoggerConfigurations` because it's used by the actuator endpoint. Without them JSON payload would be incomplete. I'm not sure we have an easy way to calculate what the default would be without calling `Configuration.getLoggerConfig(...)`.

All things considered, I think the memory occupation isn't too much of a problem and is a better tradeoff than the maintenance costs of making the code more complex.
