### ISSUE TITLE
Convention for a Webhook prefix?

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2786]
My application needs to receive Webhooks/postbacks from a number of external services, and these kinds of handlers share the common characteristic that they shouldn't be behind Spring Security authentication or CSRF protection. Since these sorts of integrations are common, I'd like to see a prefix, such as `/webhook/**`, that by convention is allocated for their endpoints and exempted from the usual request-level security policies.

**Comment by philwebb** [comment]
It sounds like something that should perhaps be "opt-in" rather than the default.

**Comment by rwinch** [comment]
I don't think this should be something that is automatic. Making assumptions about security is what gets people into trouble.

What happens if someone has webhooks that should require authentication? This is also quite common (i.e. github invokes webhooks on Bamboo that require authentication to trigger a build).

Additionally, you can very easily disable security for those endpoints with only a few lines of code. This makes anything automatic even less appealing to me.

Is there a concrete reason you feel this is a good idea?

**Comment by chrylis** [comment]
The reason for suggesting some sort of convention is that I'm working on at least two autoconfigured components that consume asynchronous postbacks, and even if there's not a built-in rule, a convention for where those endpoints should go would make configuration easier on end-users. (This would be a non-issue if there were a distributed way of disabling CSRF by path, but that's not available now.)

**Comment by rwinch** [comment]
> Spring Security authentication or CSRF protection

If you are trying to disable Spring Security entirely, you can create a configuration like the following:

```java
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.WebSecurityConfigurer;
import org.springframework.security.config.annotation.web.builders.WebSecurity;

@Configuration
public class DefaultDisableSecurityConfig implements WebSecurityConfigurer<WebSecurity> {
	public void init(WebSecurity web) throws Exception {}

	public void configure(WebSecurity web) throws Exception {
		web
			.ignoring()
				.antMatchers("/webhooks/**","/disabled-security/**");
	}
}
```

So long as the above configuration is picked up by a `@ComponentScan` then this `@Configuration` will disable security for any URL that starts with "/webhooks/" or any URL that starts with "/disabled-security/".

**NOTE** We typically do not recommend disabling security for any endpoints. It is better to state that the URL is permitAll since this does not disable other features like Security HTTP Response headers.

**Comment by chrylis** [comment]
public void configure(WebSecurity web) throws Exception {
        web
            .ignoring()
                .antMatchers("/webhooks/**","/disabled-security/**");
    }

Would this actually add to my existing security configuration, or would one or the other win?

> NOTE We typically do not recommend disabling security for any endpoints. It is better to state that the URL is permitAll since this does not disable other features like Security HTTP Response headers.

Does that include anything besides HSTS? The underlying problem is that there's no built-in way to register `permitAll()` or `csrf()` patterns in a modular manner; this issue is sort of the security equivalent to [SPR-12450](https://jira.spring.io/browse/SPR-12450) in that what I'm wanting to do is for a component to be able to add configuration for its own bits (message converters, endpoints) without requiring manual interaction from the client code. My configuration class doesn't have to repeat every `@Bean` in the context, but it does have to repeat all of the security rules required by every module.

**Comment by rwinch** [comment]
> Would this actually add to my existing security configuration, or would one or the other win?

The rules are additive.

> The underlying problem is that there's no built-in way to register permitAll() or csrf() patterns in a modular manner; 

The recommended way to modularize your Spring Security Configuration is to create your own `SecurityConfigurerAdapter` (i.e. [XAuthTokenConfigurer](https://github.com/joshlong/boot-examples/blob/4b14c1634e7cfa0e5ab5313fe5a14121ef7c10f7/x-auth-security/src/main/java/demo/xauth/XAuthTokenConfigurer.java)) implementation and have consumers [apply](https://github.com/joshlong/boot-examples/blob/4b14c1634e7cfa0e5ab5313fe5a14121ef7c10f7/x-auth-security/src/main/java/demo/Application.java#L66) it.

**Comment by rwinch** [comment]
Closing this as having a convention for permitAll is not recommended and we should not guess permissions for users.
