### ISSUE TITLE
Allow endpoint id to contain a "/" for custom mappings

### ISSUE THREAD

**Issue by robpblake-miki** [spring-projects/spring-boot#2790]
I have a scenario where I need to map the default /health endpoint to another URL to fall in-line with existing project standards. In my case this URL is /heartbeat/ping.

I wanted to achieve this by setting the property `endpoints.health.id=/heartbeat/ping` in my `application.properties`. However I am prevented from doing so by the `"@Pattern(regexp = "\\w+", message = "ID must only contains letters, numbers and '_'")"` validation on the `org.springframework.boot.actuate.endpoint.AbstractEndpoint.id` field.

It would be ideal if the id could support sub-paths.

As a work around you can use a `BeanPostProcessor` to manually set the id as part of `postProcessAfterInitialization()`.

**Comment by philwebb** [comment]
We intentionally have quite a strict validation on the ID since endpoints can be exposed over a variety of technologies and we don't want unusual characters causing problems.

I think it would be better if we try to offer additional properties that only effect the MVC mapping of endpoints. Probably changing `EndpointMvcAdapter.getPath()` is the best option here.

**Comment by snicoll** [comment]
See also #3251
