### ISSUE TITLE
Custom static resource mapping

### ISSUE THREAD

**Issue by NullPointerC** [spring-projects/spring-boot#27942]
🙅 Hello, team. I'm a beginner of springboot.
Today,I had a strange problem.I need to upload pictures in my project.
So I configured my custom static resource mapping path.
```
@Configuration
public class MallWebMvcConfigurer implements WebMvcConfigurer {


    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/images/**").addResourceLocations("file:" + Constant.FILE_UPLOAD_DIR);
        registry.addResourceHandler("/webjars/**").addResourceLocations(
                "classpath:/META-INF/resources/webjars/");
        registry.addResourceHandler("/static/**").addResourceLocations("classpath:/static");
    }
}
```
As shown above, I refer to some suggestions on Google.I customized my class to implement WebMvcConfigurer.
Of course, all this is normal.When I correctly upload the picture to the path I set to store the picture.
In postman, see the following
<img src="https://gitee.com/cao_ziqiang/img/raw/master/20210911214528.png">
When I try to access data in result,but I got the following results:
<img src="https://gitee.com/cao_ziqiang/img/raw/master/20210911214744.png">
I tried Google, but the suggestions were generally consistent,They all suggest that I implement WebMvcConfigurer.
And there is no error on the console.
🎁Finally, thank you in advance for answering my questions.^_^

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
