### ISSUE TITLE
Feature Request: Support for CloudFoundry UAA

### ISSUE THREAD

**Issue by pnreddysvu** [spring-projects/spring-boot#2801]
Isn't it good to hava CloudFoundy UAA autoconfigured ? 
Most of the applications need to manage users and user groups. It will be great if Spring boot supports REST APIs to manage users out-of box.

I don't know whether it is in the scope of Spring-boot or not.

**Comment by philwebb** [comment]
I'm not sure if this is something that we should configure out of the box, it seems like using UAA directly is something that only a small subset of Spring Boot apps would need to do.

Perhaps it is something that Spring Cloud might be interested in.

/cc @spencergibb @dsyer

**Comment by spencergibb** [comment]
It would likely go here: https://github.com/spring-cloud/spring-cloud-cloudfoundry

**Comment by dsyer** [comment]
I'd say this is more of a Spring Social feature. There was a Spring Social Cloud Foundry in github a while back (one of the Field Engineers at Pivotal did it I think). Anyway, since Spring Social only gets new features when new people show up wanting to implement and support them, I'd say it's in your hands.

**Comment by philwebb** [comment]
I think this is beyond the scope of what we want to do in Spring Boot itself.
