### ISSUE TITLE
querydsl-codegen-utils:5.0.0 that comes as a part of querydsl-bom is not present in maven central 

### ISSUE THREAD

**Issue by Sachpat** [spring-projects/spring-boot#28035]
Hi Colleagues,

The **com.querydsl:querydsl-bom:5.0.0** comes as a part of SB 2.6.0.M2. However the dependency **com.querydsl:querydsl-codegen-utils:jar:5.0.0** that comes as a part of querydsl-bom is not present in maven central bur rather **com.querydsl:codegen-utils:jar:5.0.0** is. I have created an [issue](https://github.com/querydsl/querydsl/issues/3031) which addresses this. 

Maybe this dependency be excluded from the SpringBoot BOMs? 

Kind regards,
Sachin

**Comment by wilkinsona** [comment]
Thanks for letting us know. We currently import QueryDSL's bom. To fix this, we would have to revert our use of the bom and list all of the dependencies individually instead. Given that dependency management for a dependency that does not exist should not cause many, if any, problems, I'd prefer to wait for the problem to be fixed in QueryDSL. I've subscribed to the QueryDSL issue that you opened so that I can see how it develops. We can re-open this issue if it takes a direction which means that a fix in Boot is unavoidable.

**Comment by Sachpat** [comment]
> Thanks for letting us know. We currently import QueryDSL's bom. To fix this, we would have to revert our use of the bom and list all of the dependencies individually instead. Given that dependency management for a dependency that does not exist should not cause many, if any, problems, I'd prefer to wait for the problem to be fixed in QueryDSL. I've subscribed to the QueryDSL issue that you opened so that I can see how it develops. We can re-open this issue if it takes a direction which means that a fix in Boot is unavoidable.

Thanks :)
