### ISSUE TITLE
Is there any way w.r.t configuration/custom logic  to provide a blacklist the ports in spring boot tomcat server so it will never pick those ports again.

### ISSUE THREAD

**Issue by nagendrababu99** [spring-projects/spring-boot#28192]
Is there any way w.r.t configuration/custom logic  to provide a blacklist the ports in spring boot tomcat server so it will never pick those ports again.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
