### ISSUE TITLE
Suggestions on springframework.asm.ClassReader class verification rules

### ISSUE THREAD

**Issue by kakahu2015** [spring-projects/spring-boot#28504]
I want to encrypt the class bytecode of some compiled core classes in the springboot project, and use the JVMTI monitoring mechanism to decrypt the class. Ordinary java projects have been able to decrypt the jar after the encrypted class can be decrypted normally. It runs, but even if a specific java class is not referenced in the code in springboot, if the directory of the class is in the spring scan path by default, the encrypted class file will be caused by org even if the class file is not referenced by any code. The validation bytecode of .springframework.asm.ClassReader throws an exception, causing the service to stop. Can you provide a configuration for this requirement to ignore certain classes that are not validated?

**Comment by wilkinsona** [comment]
`org.springframework.asm.ClassReader` is part of Spring Framework. To request an enhancement to it, please open a [Spring Framework issue](https://github.com/spring-projects/spring-framework/issues). However, please note that Spring Framework's variant of ASM is closely aligned with the original. Any changes are intended to improve compatibility rather than add new features.
