### ISSUE TITLE
To fully align with ISO-8601, use yyyy-MM-dd'T'HH:mm:ss.SSSXXX as the default logging date format

### ISSUE THREAD

**Issue by Mahoney** [spring-projects/spring-boot#28654]
At present the default logging pattern does not append any timezone / offset information to the time of the event. This makes it impossible to parse back into an instant reliably (e.g. when using a log exporter to push a docker container's stdout to elasticsearch or similar), because the timezone will be system / system property dependent.

Should just be a matter of adding `XXX` to the end of the default for `LOG_DATEFORMAT_PATTERN` in `org/springframework/boot/logging/logback/defaults.xml` & `org.springframework.boot.logging.logback.DefaultLogbackConfiguration`.

A good test is that the result is parseable by `ZonedDateTime.parse`. See [DateConverterSpec](https://gist.github.com/Mahoney/9cd8ec0a0e72300aae8b4a16c95222d0) which shows only `XXX` reliably produces a parseable ISO 8601 string.

**Comment by michael-o** [comment]
No timezones, offsets only. One should not use `Z`, but `XXX` only.

**Comment by wilkinsona** [comment]
As I understand it, `Z` will produce an offset. It is `z` that will not. That said, given our preference for ISO-8601 elsewhere, if we decide to do this I think it makes sense to use `XX` or `XXX` rather than `Z`. I agree that `z` should be avoid.

Flagging for team meeting so that we can discuss whether we want to make this change, and if we do, the timing of it. It feels like something that should possibly wait until 3.x to me.

**Comment by michael-o** [comment]
@wilkinsona , please use `XXX` only. `Z` is RFC and should be burried. Please read [MSHARED-837](https://issues.apache.org/jira/browse/MSHARED-837) how to make it truly extended ISO 8601.

**Comment by michael-o** [comment]
@Mahoney Please change the issue title accordingly.

**Comment by wilkinsona** [comment]
If we're going to add an offset, I wonder if we should go one step further and also use the `T` separator rather than a space. That would fully align with ISO-8601.

Our current format produces timestamps like the following:

```
2022-04-26 11:12:51.001
```

Adding an offset would change this to the following:

```
2022-04-26 11:12:51.001+01:00
```

Fully aligning with ISO-8601 would change this to the following:

```
2022-04-26T11:12:51.001+01:00
```

**Comment by michael-o** [comment]
@wilkinsona Yes, please do so. ISO 8601 clearly says (if you have access to the document): the 'T' can be replaced with a space only if a mutual agreement has been done between parties.

**Comment by wilkinsona** [comment]
We've discussed this today and we're going to add the `T`. We'll make the changes for both Logback and Log4j2.
