### ISSUE TITLE
error in jdk11

### ISSUE THREAD

**Issue by Nonoas** [spring-projects/spring-boot#28901]
I have a error in jdk11

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mainController': Unsatisfied dependency expressed through field 'odrService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OrderServiceImpl' defined in file [D:\MyCode\IDEA\CRM-v200213\target\classes\indi\nonoas\crm\service\impl\OrderServiceImpl.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class indi.nonoas.crm.service.impl.OrderServiceImpl: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.IllegalAccessError-->superinterface check failed: class indi.nonoas.crm.service.impl.OrderServiceImpl$$EnhancerBySpringCGLIB$$776d1e3b (in module CRM) cannot access class org.springframework.aop.framework.Advised (in unnamed module @0x19b6af5f) because module CRM does not read unnamed module @0x19b6af5f

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
