### ISSUE TITLE
Hibernate validation messages broken in spring boot 2.6.1 when setUseCodeAsDefaultMessage set to true

### ISSUE THREAD

**Issue by runningonfumes** [spring-projects/spring-boot#28930]
Configuring the following messageSource breaks hibernate validation messages
```java
@Bean
public MessageSource messageSource() {
	var resourceBundleMessageSource = new ResourceBundleMessageSource();
	resourceBundleMessageSource.setUseCodeAsDefaultMessage(true);
	return resourceBundleMessageSource;
}
```

attached is a simple test case where the defaultMessage is the key, not the expected translation.

If that test is run against spring boot 2.5.7 it is fine, against 2.6.1 it is broken
[demo.zip](https://github.com/spring-projects/spring-boot/files/7676866/demo.zip)
.

**Comment by snicoll** [comment]
Thanks for the report. Spring Boot 2.6 switched to Hibernate Validator but downgrading it to the same version used by Spring Boot 2.5 didn't fix the problem so we'll have to investigate.

**Comment by wilkinsona** [comment]
Thanks for the sample, @runningonfumes. The change in behaviour is an unexpected side-effect of https://github.com/spring-projects/spring-boot/pull/17530. You can restore the previous behaviour by defining your own validator:

```java
@Bean
@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
public static LocalValidatorFactoryBean customValidator() {
    LocalValidatorFactoryBean factoryBean = new LocalValidatorFactoryBean();
    MessageInterpolatorFactory interpolatorFactory = new MessageInterpolatorFactory();
    factoryBean.setMessageInterpolator(interpolatorFactory.getObject());
    return factoryBean;
}
```

To make this easier, we could perhaps introduce a configuration property that allows you to opt out of using the `MessageSource` for validation message interpolation. Flagging for team attention so that we can consider our options.
