### ISSUE TITLE
Jsp default errorview (e.g. error.jsp) does not take precedence over whitelabel error

### ISSUE THREAD

**Issue by hanswesterbeek** [spring-projects/spring-boot#2893]
Ergo: the whitelabel page is shown when it shouldn't be.

[Reproduction here](https://github.com/hanswesterbeek/springboot-jsp-errorview-precedence-problem).

I have created a workaround which comes down to creating the InternalResourceViewer myself and setting its precedence. [Code here](https://github.com/hanswesterbeek/springboot-jsp-errorview-precedence-problem/blob/workaround/src/main/java/demo/DemoApplication.java#L24).

**Comment by pongo710** [comment]
I have the exact same issue.

@hanswesterbeek Thanks for the fix. It also worked for me.

It would be cool to have a "native" solution without overriding the default.

**Comment by snicoll** [comment]
`DefaultErrorViewResolver`  and `InternalResourceViewResolver` have the same order. I wonder if that's related.

**Comment by pongo710** [comment]
I think you are right. I debugged the view resolving and it found the error.jsp but its order was too late. I'm not sure which ViewResolver was before but it was the one showing the whitelabel error page.

**Comment by bclozel** [comment]
I've looked into this and it seems that:

* `BeanNameViewResolver` in `ErrorMvcAutoConfiguration` is set to `Ordered.LOWEST_PRECEDENCE - 10`
* `InternalResourceViewResolver` is set by default to `Ordered.LOWEST_PRECEDENCE`

This is why the whitelabel error page is rendered in place of `error.jsp`. Now switching the order definitely breaks other features, such as defining views a beans. Indeed, if the `InternalResourceViewResolver` can't resolve a template it fails and gives no chances for other resolvers to do their job. That's why it is configured with the lowest priority by default.

I don't think this can be fixed properly - probably a [new JSP limitation we can document](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-jsp-limitations)?

Note that as of Spring Boot 1.4.0, adding a `/WEB-INF/jsp/error/5xx.jsp` template works - see the [reference documentation for more information](http://docs.spring.io/spring-boot/docs/1.4.0.BUILD-SNAPSHOT/reference/html/boot-features-developing-web-applications.html#boot-features-error-handling-custom-error-pages).
