### ISSUE TITLE
Spring Social JdbcUsersConnectionRepository bean not used when provided

### ISSUE THREAD

**Issue by dkakollu** [spring-projects/spring-boot#2894]
Hi when I try to use JdbcUsersConnectionRepository or my own implemented UsersConnectionRepository is not considering in spring boot.

I had defined bean on my spring config with ConnectionFactoryLocator, but still its taking InMemoryUsersConnectionRepository.

```
@Bean
public UsersConnectionRepository usersConnectionRepository() {
    return new JdbcUsersConnectionRepository(source, connectionFactoryLocator(), textEncryptor );
    //return new JpaUsersConnectionRepository(socialUserRepository,
        //  userRepository, connectionFactoryLocator(), textEncryptor);
}
```

**Comment by geowarin** [comment]
If you look at [SocialConfiguration](https://github.com/spring-projects/spring-social/blob/master/spring-social-config/src/main/java/org/springframework/social/config/annotation/SocialConfiguration.java#L87) you can see that all the `SocialConfigurers` are taken in order. The first one having a non null UserConnectionRepository will determine the strategy of the whole social configuration.

This is a bit strange IMHO, especially since all spring boot configurers declare such a repository, it becomes kind of a competition.

This basically forces you to annotate your `SocialConfigurerAdapter` with `@Order` or implement the `Ordered` interface for it to be in first position.

You could also annotate your bean with `@Primary`, it should work too.

It think it would be nice to document the preferred way to do this, it can become somewhat confusing

**Comment by wilkinsona** [comment]
@habuma Can you please offer some input here?

**Comment by habuma** [comment]
The short answer here is that the work for Spring Social's auto-configuration was a starting point and due to higher priority work it was never completed. That said, even before seeing these comments, I had set aside this week to work on Spring Social auto-configuration. Hopefully I'll have a better answer for you by the end of the week.

**Comment by dkakollu** [comment]
Just excluded SocialWebAutoConfiguration :
 @EnableAutoConfiguration(exclude = { SocialWebAutoConfiguration.class })

**Comment by dkakollu** [comment]
Thanks to everyone :+1:

**Comment by habuma** [comment]
This is actually a problem in Spring Social, not in Spring Boot's autoconfiguration of Spring Social. That said, the fact that Spring Boot uses multiple SocialConfigurer's to accomplish auto-configuration results in this problem manifesting itself rather easily. 

There's no good fix for it in Spring Boot (although I suppose I could have all of the SocialConfigurers in auto-configuration override that method to return null). Really the problem should be addressed in Spring Social. I've created https://jira.spring.io/browse/SOCIAL-468 to address this in Spring Social.  In the meantime, I'll look at overriding it with null for the Spring Boot-configured SocialConfigurers.
