### ISSUE TITLE
Support a spring.mvc.async.request-timeout property

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#2900]
Customizing the default timeout property (set to 10 seconds by default) is mandatory for most applications that use async http request, and mandatory for those that will be using the upcoming Spring Framework 4.2 SSE supports.

As you can see in this [sample application](https://github.com/sdeleuze/spring-react-isomorphic/blob/master/src/main/java/io/spring/isomorphic/IsomorphicApplication.java#L41) currently we have to disable Spring Boot autoconfiguration to customize it. Supporting such property would be really useful for async and SSE applications!

**Comment by snicoll** [comment]
Are you going to work on a PR Sébastien?

**Comment by sdeleuze** [comment]
Yes

**Comment by sdeleuze** [comment]
Pull request https://github.com/spring-projects/spring-boot/pull/3236 submitted

**Comment by threecuptea** [comment]
I have needs for this properties.  I like to know how to use it and how to configure it in application context xml.    Is this properties applied to any Spring MVC version?   

I am now getting our application to switch to Spring MVC async using Callable.  Our application is deployed in Tomcat.   That works fine.  However, I just couldn't get one test passed.  Our tests use embedded Jetty 8 server. I traced and found.out that Spring MVC will return 404 Not Found "No mapping request found for HTTP request URI....".  if the async web request execution time is longer than 100ms,   Very similar requests with execution time < 100ms works fine in embedded Jetty 8.   Similar requests with async web request taking longer than 1 second (due to remote Mongodb) work fine in Tomcat.   

According to timeout section in the article
https://spring.io/blog/2012/05/10/spring-mvc-3-2-preview-making-a-controller-method-asynchronous/, 
"You can configure the timeout value (of async web request) through the MVC Java config and the MVC namespace, or directly on the RequestMappingHandlerAdapter. If not configured, the timeout value will depend on the underlying Servlet container. On Tomcat it is 10 seconds and it starts after the initial Servlet container thread exits all the way out."

That seems to match what I experienced.  It did not elaborate how to do that.  That's how I Google and find this properties.
 
Thanks.

**Comment by philwebb** [comment]
@threecuptea Your best bet is to ask on stackoverfolw.com. This issues was for tracking the original feature request to add a property for Spring Boot. It sounds like you're trying to get this to work with standard Spring MVC (i.e. not using Spring Boot).
