### ISSUE TITLE
@Import does not support BeanFactoryPostProcessor implementations

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-boot#29025]
Consider an auto-configuration class that has `@AutoConfigureBefore(HibernateJpaAutoConfiguration.class)` and registers a custom `EntityManagerFactoryDependsOnPostProcessor` using `@Import`.

My custom `EntityManagerFactoryDependsOnPostProcessor` is not created or used.

Sample repo: https://github.com/cdalexndr/spring-issue-29018

**Spring Boot 2.6.1**

**Comment by philwebb** [comment]
@cdalexndr I think I know what's going on here and why `CacheAutoConfiguration` works but yours does not. You have `@ConditionalOnBean(AbstractEntityManagerFactoryBean.class)` declared on `MyCustomBeanEntityManagerFactoryDependsOnPostProcessor` but nothing has defined that bean when `MyConfiguration` imports `MyCustomBeanEntityManagerFactoryDependsOnPostProcessor`.

The `@ConditionalOnBean` only works against bean definitions that have already been defined. This means that the auto-configuration that defines `AbstractEntityManagerFactoryBean` must run before your configuration. With `CacheAutoConfiguration` we have a `@AutoConfigureAfter` for `HibernateJpaAutoConfiguration`. With your example code you have `@AutoConfigureBefore(HibernateJpaAutoConfiguration.class)`. So the order for your code is:

* `MyConfiguration` beans are defined
* `MyCustomBeanEntityManagerFactoryDependsOnPostProcessor` is imported
* `@ConditionalOnBean(AbstractEntityManagerFactoryBean.class)` doesn't match because no `AbstractEntityManagerFactoryBean` has been defined

I think you'll need to rethink your `@AutoConfigureBefore`/`@AutoConfigureAfter` annotations.
