### ISSUE TITLE
Facing error while accessing cassandra data through Solr_query json

### ISSUE THREAD

**Issue by dhiraj-u-kumar** [spring-projects/spring-boot#29035]
Having com.datastax.oss  of version : 4.13.0

Select selectQuery = selectFrom(table).all().whereColumn("solr_query").isEqualTo(literal("{"q":"createdate:[2021-10-15T14:03:37.817Z TO 2021-12-15T07:23:14.025Z]","sort":"updatedate desc", "paging":"driver"}"));

SimpleStatement statement = selectQuery.build()
ResultSet rs = this.session.execute(statement );  --> Giving below exception :

com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Error on shard 12.345.678.90: Field cache is disabled, set the field=updatedate to be docValues=true and reindex.  Or if the field cache will not exceed the heap usage, then place useFieldCache=true in the request parameters.

I am not sure how to address this. 
As the above code was working fine for version : 4.9.0 with the below code
Statement selectQuery = QueryBuilder.select().all().from(table)
                    .where(QueryBuilder.eq("solr_query", "{"q":"createdate:[2021-10-15T14:03:37.817Z TO 2021-12-15T07:23:14.025Z]","sort":"updatedate desc", "paging":"driver"}"))
                    .setConsistencyLevel(ConsistencyLevel.valueOf(consistencyLevelForSolrQueries));
 ResultSet rs= super.getManager().getSession().execute(selectQuery);

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
