### ISSUE TITLE
Lazy load of spring beans

### ISSUE THREAD

**Issue by samucamarques** [spring-projects/spring-boot#29037]
- Question

Is that possible to use the **spring.main.lazy-initialization** property with **config server?**

I have spring-boot microservices running on **k8s**. The properties are loaded from the config server based on the env.

I just can't make it work. To enable lazy init with the property. 
The only way it worked, was setting true on the SpringApplication flag before invoking the method run.

Tested on spring-boot 2.3.12.RELEASE

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
