### ISSUE TITLE
Spring boot 2.6.0 Quartz mysql/mariadb tables are not created

### ISSUE THREAD

**Issue by chrisdev0** [spring-projects/spring-boot#29095]
In spring boot 2.6.1 the creation of the Quartz tables for (at least) mysql and mariadb have stopped working.

The cause is that the **spring.quartz.jdbc.comment-prefix** property isn't used on the way to the runScripts method in DataSourceScriptDatabaseInitializer so the ResourceDatabasePopulator is never configured with these comment-prefixes.

This causes the default comment-prefixes to be used (which is --) and since the org.quartz-scheduler:quartz:2.3.2 dependency mysql/mariadb sql files (in org.quartz.impl.jdbcjobstore) have non -- prefixed comments the results is broken sql.

The exception is then silently ignored (unless debug log level) due to continueOnError being true.

A temporary solution is to extract the .sql-file in the org.quartz-scheduler:quartz dependency, remove the # comments on top and then overriding the schema used to initialize the quartz tables by using the property  **spring.quartz.jdbc.schema**

I've created a small example of the bug here https://github.com/chrisdev0/quartz-bug
run with default profile results in error on startup due to 
`Caused by: java.sql.SQLException: Table 'quartz_bug.qrtz_locks' doesn't exist`
run with workaround profile and it will start since it's using the extracted schema sql file with the comments removed

**Comment by snicoll** [comment]
@chrisdev0 thank you so much for the detailed report and sample. This project is overriding the [datasource initializer](https://github.com/chrisdev0/quartz-bug/blob/65e989f2966b93425af6482cf839e12432f0e9b3/src/main/java/com/example/quartzbug/QuartzBugApplication.java#L20-L23), effectively overriding any property that might have been set. What have I missed?

**Comment by chrisdev0** [comment]
> @chrisdev0 thank you so much for the detailed report and sample.
> 
> Can you share why you've overridden the [integration intializer initializer](https://github.com/chrisdev0/quartz-bug/blob/65e989f2966b93425af6482cf839e12432f0e9b3/src/main/java/com/example/quartzbug/QuartzBugApplication.java#L20-L23)?

Sorry, I forgot to remove that bean when copy pasting from my other project. I've removed that bean in the example now.

**Comment by snicoll** [comment]
I've pushed a fix on my fork but it breaks a protected method and I can see ourselves breaking this some more as new settings are added. `DatabaseInitializationSettings` contains both the scripts and the settings to run them and we want to isolate the former from the actual implementation as we're giving it the scripts to run.

The previous implementation had a way to customize the `DatabaseResourcePopulator`. Adding that would fix the Quartz use case without breaking the API but it wouldn't permit to use this feature by just using the settings and decoupling it from the properties was a goal. 

I am not sure what to do at this point so I've flagged it so that someone else on the team can have a look.
