### ISSUE TITLE
How @Value annotation works internally

### ISSUE THREAD

**Issue by arvindersinghchhabra** [spring-projects/spring-boot#29106]
How @value annotation works internally in spring.

Actually I want to implement the same using custom annotation by providing logic and assign back value to variable field again.

In spring we do

@value(${key})
private String name;

But I want

@CustomAnnotation
private String name;

Here @CustomAnnotation will read value of name variable and perform some logic on name variable value and assign back to name variable.

Appreciate your help !!!!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
