### ISSUE TITLE
Add sorting of interceptors that are added to RestTemplate through the RestTemplateBuilder

### ISSUE THREAD

**Issue by mikitakandratsiuk** [spring-projects/spring-boot#29267]
> Running with Spring Boot v2.4.0, Spring v5.3.1

Currently `InterceptingHttpAccessor` (extended by `RestTemplate`) allows setting the `ClientHttpRequestInterceptor` interceptors. In particular, it performs [sorting](https://github.com/spring-projects/spring-framework/blob/5.0.x/spring-web/src/main/java/org/springframework/http/client/support/InterceptingHttpAccessor.java#L64) with `AnnotationAwareOrderComparator`.

From the other side, when we construct `RestTemplate` via `RestTemplateBuilder`, the interceptors are just [added](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/client/RestTemplateBuilder.java#L631) into the list, but not sorted. Does it make sense to add something like `AnnotationAwareOrderComparator.sort(restTemplate.getInterceptors())` here?

**Comment by wilkinsona** [comment]
> Does it make sense to add something like `AnnotationAwareOrderComparator.sort(restTemplate.getInterceptors())` here?

I'm not sure that it does, unfortunately.

The current implementation honours the order of the interceptors as configured by the user. If we started sorting them via `AnnotationAwareOrderComparator` it could change this ordering and break existing code.

If you want the interceptors to be sorted in a particular way, I think that sorting them prior to calling `RestTemplateBuilder.interceptors(Collection<ClientHttpRequestInterceptor>)` is your best option.

I'll flag this for team attention so that we can consider making a breaking change to the default ordering.

**Comment by wilkinsona** [comment]
We discussed this and decided that we want to retain the flexibility of using the user-provided ordering. That allows us to keep the current behavior while also supporting your requirement as you can order the interceptors using `AnnotationAwareOrderComparator.sort` prior to passing them to the builder. Thanks anyway for the suggestion.
