### ISSUE TITLE
Does a "proper" plugin process exist?

### ISSUE THREAD

**Issue by ja391045** [spring-projects/spring-boot#2927]
I'm trying to find out if there's a "proper" way to share a spring-boot plugin?  

The developers I work with are pretty enthused about using Spring Boot for microservices.  However, from a system's perspective the properties available for embedded tomcat configuration aren't quite enough. (We must use APR/Native connectors in production environments, with only supported SSL Ciphers enabled, and protocols limited to TLS 1.2+, etc.)   So, from a systems requirement, systems admins need to handle the tomcat config once the app leaves the developer's environment.  To that end, I'm in the process of writing of JAR that, when included on the classpath, exposes a host of more server.tomcat.* properties, that allows for multiple connector configurations via application.properties.  That way our sysadmins can write an externalized applications.properties that ensures all the proper security requirements are in place, and the developers can just leave it standard while they write the app.

If I try to merge this expanded tomcat configuration model into spring boot itself, the list of allowed servier.tomcat.* properties would get pretty huge, and I'm not sure if you guys want that.  I mean, it'd break the simplicity of boot.  I could also make a git hub project for something like "spring-boot-tomcat-morecfg", and allow users who want the extra applications.properties options to simply add that to their pom.xml, and configure away.   

So my question is twofold:  Would you want me to try and merge all these configuration options into Spring Boot itself, and if not, is there a some kind of standard "plugin" author process I can follow?

**Comment by snicoll** [comment]
Thanks for a great question.

There are several things that we are trying to iron out:

1. Naming: since all our starters are named `spring-boot-starter-`_something_, community starters were named the same way which lead to very annoying conflict (like two `spring-boot-starter-actuator` for instance). We've started to improve the doc all around and document that in #2537 
2. Config namespaces: in that very same issue we want to document and explain why we don't want community starters to use the `spring`, `security` and `server` root namespace for configuration. In a nutshell, these are "ours" and we may improve/modify them in the future in such a way it could break your things. So the rule of thumb here is to use your own namespace

To answer your question, it really depends how large and reusable it is. In any case, you can start on something on your side and let us know when you're done. 

We should have a "starter/auto-configuration" author process and maybe this very issue would be a good way to track that. Feel free to add more questions in the meantime.

**Comment by ja391045** [comment]
Sounds like things are in flux.  I'll definitely read up all I can, and start out by writing code that is separate.  For instance, instead of spring-boot-starter-tomcat-morecfg, I'll name it spring-boot-contrib-tomcat-morecfg, and I'll start my namespace at contrib.server.*.

Then if the "CONTRIB-TOMCAT-MORECFG" profile is active, I'll arrange it so that this causes the EmbeddedServletContainerFactory to be overloaded with one that understands all the contrib.server properties.  Or something like this.  I'm still bouncing it around in my head.

It can always be reworked as things become more solidified.

**Comment by snicoll** [comment]
I just updated the documentation in https://github.com/spring-projects/spring-boot/commit/960d6eadbac79be22449973a1c2e389aef2993d8. I'll suggest to close this one for now. If you end up doing what we've discussed here, feel free to open a PR and we'll discuss based on the code. Thanks.
