### ISSUE TITLE
org.toml:tomlj:1.0.0 no longer resolving from maven central

### ISSUE THREAD

**Issue by niels1voo** [spring-projects/spring-boot#29357]
As of this morning our gradle builds using the spring boot plugin 2.6.1 started failing due to this dependency going missing from maven central.

https://github.com/tomlj/tomlj/issues/34

**Comment by niels1voo** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/223998/149191129-5d0b839f-98d0-4759-8744-91856ca0e060.png">

**Comment by wilkinsona** [comment]
It's still there as far as I can tell: https://repo.maven.apache.org/maven2/org/tomlj/tomlj/1.0.0/. I suspect you are suffering a problem specific to your environment as our CI builds are also working. Also, please note that in tomlj/tomlj#34 you have linked to a search with the wrong group (`org.toml` rather than `org.tomlj`). A search for `org.tomlj` shows the expected artifact: https://search.maven.org/search?q=org.tomlj.

**Comment by dangoodman5425** [comment]
We also started experiencing the same issue a few hours ago.

Getting the following error when building without using the cached version:

`[17:04:48] #19 15.73    > Could not determine artifacts for org.tomlj:tomlj:1.0.0: Skipped due to earlier error`

**Comment by wilkinsona** [comment]
Without knowing what the earlier error was, I can't really help any further. I still suspect a problem with your access to Maven Central. Our local and CI builds have been able to resolve tomlj without any problems. See [this build scan](https://ge.spring.io/s/mqy2utwlkbc6a/performance/network-activity#download-1039), for example.

If you've eliminated your network as a possible cause, you may want to open [an `MVNCENTRAL` issue](https://issues.sonatype.org/projects/MVNCENTRAL/). Maven Central uses a CDN so it's possible that the problem is location-specific.

**Comment by wilkinsona** [comment]
Depending on the earlier error, this may also be due to a problem with Gradle's plugin portal. There's [some discussion about it and a possible workaround](https://gradle-community.slack.com/archives/CA7UM03V3/p1642006227021300) in their community Slack. The problem's [being tracked](https://status.gradle.com/incidents/nv93msj8q658) on status.gradle.com.
