### ISSUE TITLE
Rename AutoConfigurationReportLoggingInitializer to ConditionEvaluationReportLoggingListener

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#2945]
The report contains information about the evaluation of all `SpringBootCondition`s, not just those on auto-configuration classes. If we make this change, the name of the `ConditionEvaluationReport` bean should be changed at the same time.

**Comment by ssominii** [comment]
You said it should be renamed because 
"AutoConfigurationReportLoggingInitializer" isn't in Auto-Configuration 
class and it contains information about SpringBootCondition.

So I dug the code about it.
The class 'AutoConfigurationReporLoggingInitializer'
implements the interface 'ApplicationContext'.
If some errors occur from the interface,
we can debug and check what functionalities were added
by using 'ConditionEvaluationReport'.

So need to rename'AutoConfigurationReporLoggingInitializer'
to 'ConditionEvaluationReport', right ?

**Comment by wilkinsona** [comment]
We should consider renaming the endpoint as well

**Comment by snicoll** [comment]
@wilkinsona agreed but I didn't find anything that was short and self explanatory enough so I am ready to go with that inconsistency. Flagging for team attention to see what the rest of the team thinks.

**Comment by philwebb** [comment]
For the endpoint we could go with `/conditions`.

**Comment by philwebb** [comment]
@ssominii From your questions I guess perhaps you're considering submitting a pull-request for this? Thanks for the offer, but I think in this case it'll be easier if we just handle the rename ourselves since there are a few other inconsistencies to iron out.

**Comment by snicoll** [comment]
@philwebb Andy and I came to the same conclusion, actually. If three persons came with the same name independently, I guess it's worth exploring. I'll give that a try.

**Comment by snicoll** [comment]
@philwebb @wilkinsona I have a proposal in 91d5e9c

**Comment by wilkinsona** [comment]
Neat. I left a few comments, but nothing major. I like it.
