### ISSUE TITLE
i need help, thanks

### ISSUE THREAD

**Issue by AccountGc** [spring-projects/spring-boot#29534]
In the microservice scenario, the entity class is extracted into a public API for reference by other services:
<dependency>
    <groupId>com.test</groupId>
    <artifactId>api-system</artifactId>
</dependency>

public service, if not introduced，“spring-boot-starter-data-elasticsearch” ，public entity class required @Id etc. Annotation，Is there a solution please ?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
