### ISSUE TITLE
Provide auto-configuration for mustache.java

### ISSUE THREAD

**Issue by jabrena** [spring-projects/spring-boot#29548]
Good afternoon,

I was reviewing the Mustache support for Spring Boot and I notice that the transitive dependency for the starter:

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-mustache</artifactId>
    </dependency>
```

Is this project:
https://github.com/samskivert/jmustache

But reviewing the documentation from Mustache:
https://mustache.github.io/

I noticed that the official Java implementation is:
https://github.com/spullara/mustache.java

Maybe Spring for Spring Boot 3.0 could consider to use the official dependency.

What is your opinion?

Reference:

- https://spring.io/blog/2016/11/21/the-joy-of-mustache-server-side-templates-for-the-jvm

Many thanks in advance

Juan Antonio

**Comment by wilkinsona** [comment]
FWIW, both projects are "official" in that they're listed on https://mustache.github.io. JMustache was [added in October 2010](https://github.com/mustache/mustache.github.com/commit/5bb4e5bc40f16c4b0af927cbdaa22459b9dc03f8) and mustache.java was [added in June 2010](https://github.com/mustache/mustache.github.com/commit/cc02cc3516f69dbf0135447fe94f355178243266). JMustache is listed under Android but the reason for that is unclear.

**Comment by jabrena** [comment]
Good morning @philwebb & @wilkinsona,

The motivation of this issue is about showing the evolution of the main transitive dependency for `spring-boot-starter-mustache`. Maybe in 2015-2016 in the design phase of the `Spring Boot Starter` both libraries could have a similar activity and relevance but now in 2022, both libraries doesn´t have the same pace and this is the point. Said that, I am not saying that `jmustache` doesn`t cover the goals of the `Spring Boot Starter` but it is fact that `mustache.java` has more relevance than `jmustache` in the context of `Mustache` community and maybe it could be a periodical activity to review in the maintenance operations of the different `Spring Boot Starters`:
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.build-systems.starters

I share few links about contributions:

- http://ghv.artzub.com/#repo=jmustache&climit=500&user=samskivert
- https://github.com/samskivert/jmustache/graphs/code-frequency
- http://ghv.artzub.com/#repo=mustache.java&climit=500&user=spullara
- https://github.com/spullara/mustache.java/graphs/code-frequency

@philwebb if you like, I will review more in detail both libraries to identify differences and understand why `mustache.java` is more popular (1.7k stars) vs `jmustache` (0.7k stars)

- What is the github location for the  `spring-boot-starter-mustache`?

Juan Antonio

**Comment by wilkinsona** [comment]
The code for the auto-configuration is part of `spring-boot-autoconfigure` and can be found [here](https://github.com/spring-projects/spring-boot/tree/c820ad01a108d419d8548265b8a34ed7c5591f7c/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mustache). The starter itself is just build system metadata. It can be found [here](https://github.com/spring-projects/spring-boot/tree/c820ad01a108d419d8548265b8a34ed7c5591f7c/spring-boot-project/spring-boot-starters/spring-boot-starter-mustache).

**Comment by vpavic** [comment]
> JMustache is listed under Android but the reason for that is unclear.

Possibly because is uses Java 7 as a baseline, vs mustache.java that requires Java 8.

**Comment by jabrena** [comment]
Hi @wilkinsona many thanks for the links, I will put focus on this package:

- https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mustache

At library level, I will review both libraries in isolation in coming weeks 

@vpavic thanks for the observation, I didn´t enter in that detail.

**Comment by bclozel** [comment]
Moving from one to the other is a breaking change as we're exposing the library types with our configuration.
We should carefully consider this as we might make the 3.0 upgrade harder for a part of our community - the added value must definitely outweigh the migration pain.

**Comment by jabrena** [comment]
Totally agree with you @bclozel, but at least to know the alternatives and efforts around it.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by jabrena** [comment]
Hi, 

I am working in the analysis but I will need more time. 
I try collaborating in my spare time :)

Juan Antonio

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by ben3000** [comment]
Mustache.java [implements template inheritance](https://github.com/spullara/mustache.java), while JMustache [does not](https://github.com/samskivert/jmustache/issues/120). For me, this is a great reason to consider the former implementation.

The [Joy of Mustache article](https://spring.io/blog/2016/11/21/the-joy-of-mustache-server-side-templates-for-the-jvm) went to some lengths to build inheritance support using the JMustache-based starter, but that is no longer relevant now that the [Mustache spec has template inheritance](https://github.com/mustache/spec/blob/master/specs/%7Einheritance.yml) (and Mustache.java has implemented it).

**Comment by wilkinsona** [comment]
This could either be done alongside the existing auto-configuration for JMustache or as a replacement.

**Comment by dagnelies** [comment]
just my 2 cents:

- `jmustache` appears to be used by way more projects (pulled as dependency) than `mustache.java`
- `mustache.java` appears to have a *slightly* larger community (which is weird considering previous point)
- The docs are currently clearly better for `jmustache`
- *IMHO* `jmustache` has a more comfortable API than `mustache.java`
- template inheritance is an optional feature in the specs, a controvertial one at that, so it does not convince me as justification
- "swapping the engine" is likely to break things because `jmustache` also has several custom extensions

So in the end, I'm currently not in favor of such a change. Providing both is also likely to increase confusion and fragmentation, so I'm not really fond of it. My two cents. I'm not affiliated with either.

**Comment by vpavic** [comment]
Perhaps worth noting here is that another Mustache templating engine for Java, [jstachio](https://github.com/jstachio/jstachio) (that is also type-safe and statically compiled), is gaining popularity and maintains its own support for Spring (including Spring Boot starter).

Given the already fragmented market of Mustache templating engines for Java, perhaps Spring Boot reference manual could include a sentence or two to also mention other options and steer users towards researching before deciding on Mustache templating engine that fits their projects the best?

**Comment by ben3000** [comment]
I'm leaning towards jstachio after using it in an application I'm developing. Both jmustache and mustache.java appear stable, but not much development is occurring on them.

I don't find template inheritance controversial; I find it a requirement for any templating tool I adopt, but obviously, others may differ, and that's fine.

**Comment by agentgt** [comment]
Hi guys. I'm the author of JStachio. I would love JStachio as the default mustache implementation for Spring Boot but I think JMustache should remain the default. The only exception is for Spring Boot Native applications to default to it but I am not sure if there is some selection mechanism that detects that.

JStachio requires more build setup than JMustache that I think would impede on the instant gratification of boot.

They can easily switch to JStachio later.

I will let @dsyer chime in if he agrees or not.

I do not recommend Mustache.java at this time. While JStachio is backward compatible with JMustache, Mustache.java is not mainly because it does not handle whitespace consistently, and does not have `-first`, `-last`, its lambdas API is not compatible (no stack access) and
it also is much harder for users to learn as it not as well documented.

Mustache.java is a great implementation I just don't think given the above and how JMustache was used/promoted by @dsyer in the original [The Joy of Mustache: Server Side Templates for the JVM](https://spring.io/blog/2016/11/21/the-joy-of-mustache-server-side-templates-for-the-jvm) that it is the right library to default to.

Finally I plan on updating JMustache to add template inheritance and make it mostly v1.3 complaint with as minimal code changes as possible.

**Comment by dsyer** [comment]
I also think template inheritance is important- it just wasn’t available when we started this journey. Now that it is, I would be very excited to see it in JMustache (and it’s probably a great way for JStachio to build a user base by being more compatible because switching is not so easy until that happens).

If someone published a library providing mustache.java autoconfiguration for Spring Boot I guess it might be interesting to try. There’s no reason IMO to do that in Spring Boot, given the long history of JMustache, until it gets some usage.

**Comment by ben3000** [comment]
Thanks @agentgt and @dsyer; I think updating JMustache to add template inheritance is the best solution given the relative approachability of JMustache over JStachio for users new to Boot and annotation processors.

**Comment by agentgt** [comment]
@ben3000 , @dsyer @dagnelies et al:

JMustache hopefully very soon will have inheritance and with the exception of dynamic names is Mustache v1.3 compliant.

I have tried to make sure not to break API but currently the code is compiled for JDK 9 which given most usage of the library is probably Spring Boot I think is probably OK. 

@samskivert has been super gracious accepting my (often broken) PRs 😄

**Comment by wilkinsona** [comment]
Thanks, all, and @agentgt in particular. Given the new capabilities in JMustache 1.16 I don't expect us to add auto-configuration for mustache.java in the foreseeable future. We'll upgrade to the latest JMustache release in due course.

**Comment by paolopan83** [comment]
Mustache.java is musch easier to use and has more features, this is really a pity

**Comment by agentgt** [comment]
@paolopan83 

> Mustache.java is musch easier to use and has more features, this is really a pity

What particular features are you missing from JMustache that Mustache.java has?

Technically JMustache (and JStachio) has [lambda support with access to the context stack](https://javadoc.io/doc/com.samskivert/jmustache/latest/com.samskivert.jmustache/com/samskivert/mustache/Mustache.Lambda.html). [Mustache.java does not](https://spullara.github.io/mustache/apidocs/com/github/mustachejava/TemplateFunction.html) (well last I checked) but does have support for named partial variables. (aka `{{> *someTemplateNameString }}`).

**Comment by paolopan83** [comment]
My understanding was that with Mustache.Java you can apply custom helper to any object not only fragmen, like this

`{{printDateOfBirth customer}}`

but maybe I am wrong... :D
