### ISSUE TITLE
why Bad Request, status=400 when i upload files?

### ISSUE THREAD

**Issue by nnpa** [spring-projects/spring-boot#29559]
Error
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jan 25 13:54:17 YEKT 2022
There was an unexpected error (type=Bad Request, status=400).

Controller
```
@GetMapping("/uploadtest")
    public String uploadtest(Model model) {
         return "upload";
    }
    
    @PostMapping("/postupload")
    public String postupload(@RequestParam("files") MultipartFile[] images,Model model) {
         return "upload";
    }
```
form
  ```
  <form method="post" action="/postupload" enctype="multipart/form-data">
          <input type="file" name="images" multiple class="form-control" accept=".jpg, .jpeg" >
         <button type="submit" >Upload</button>

    </form>     
```
when i remove @RequestParam("files") MultipartFile[] images the error disappears
why error?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by nnpa** [comment]
https://ru.stackoverflow.com/questions/1374916/%d0%9f%d0%be%d1%87%d0%b5%d0%bc%d1%83-%d0%be%d1%88%d0%b8%d0%b1%d0%ba%d0%b0-bad-request-status-400-%d0%bf%d1%80%d0%b8-%d0%b7%d0%b0%d0%b3%d1%80%d1%83%d0%b7%d0%ba%d0%b5-%d0%ba%d0%b0%d1%80%d1%82%d0%b8%d0%bd%d0%be%d0%ba
