### ISSUE TITLE
Gradle building build-properties under BOOT-INFO rather than META-INF

### ISSUE THREAD

**Issue by orubel** [spring-projects/spring-boot#29602]
Having issues pulling in **buildInfo** in autoconfig as gradle is placing **buildInfo in BOOT-INF** with a META-INF rather than using the root META-INF

![buildInfo-error](https://user-images.githubusercontent.com/274764/151837153-3855d3bf-6830-4bc8-9d76-08021b47ccf0.png)

I just ran across it and have a working example and screenshot.

Am not using a GUI/IDE or devops for builds... purely shell.

Code for testing can be found here: https://github.com/orubel/spring-boot-starter-beapi

Your help on this is greatly appreciated and I apologize ahead of time if this is something that is better sent to stackoverflow.

**Comment by orubel** [comment]
>> Can you please clarify what "Having issues pulling in buildInfo in autoconfig" means?

My apologies. Left in old lib... just fixed.

Well I am trying to create a BuildProperties bean in the autoconfiguration to share the application properties (ie version etc) with the autoconfigurations and other beans

**Comment by philwebb** [comment]
Spring Boot fat jars have a special layout that allows us to embed nested jars and classes into a single executable. The format is documented a little bit [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#executable-jar) but it doesn't go into all the details.

We're trying to take inspiration from the war format where there's a `WEB-INF/lib` and `WEB-INF/classes` folder. In our case `BOOT-INF/classes` contains all the user defined code. When the fat jar is launched we use some custom URL Handler and ClassLoader tricks to bootstrap things. That should mean that you can do `ClassLoader.getResourceAsStream("META-INF/build-info.properties")` from your app and it will find `BOOT-INF/classes/META-INF/build-info.properties` transparently.

> I guess my question is: am I reading that from JAR (because that one is in BOOT-INF)? The build is SHOWING it being in 'demo-application/build/resources/main/META-INF/build-info.properties' but in the JAR it gets put into 'BOOT-INF'

This is by design. Gradle is copying the resource to `build/resources/main/META-INF/build-info.properties` but when we create the packaged jar we move it to `BOOT-INF/lib`.

**Comment by orubel** [comment]
thank you for the correction.
