### ISSUE TITLE
Remove redundant override of requestMappingHandlerMapping from EnableWebMvcConfiguration 

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#29682]
SpringBoot 2.6.3

Redundant RequestMappingHandlerMapping bean configuration, MvcUriComponentsBuilder can work in multiple RequestMappingHandlerMapping

https://github.com/spring-projects/spring-boot/blob/5282d4e0f2f7acb581eae9b884c5d372cec979f5/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.java#L437-L447

**Comment by wilkinsona** [comment]
Thanks, @brucelwl. Is the bean being primary causing a problem for you? While `MvcUriComponentsBuilder` has supported multiple beans since [these changes in Framework 5.1](https://github.com/spring-projects/spring-framework/commit/e6fef9555da4f887eb1cfa37428c97e6d2d430d2), removing `@Primary` may be a breaking change for other reasons. If we're going to do so I think it should be done in 2.7 at the earliest.

**Comment by brucelwl** [comment]
@wilkinsona At present, there are no obvious problems. I just hope that the code of springboot can be more concise and optimized hope

**Comment by wilkinsona** [comment]
Thank you. I'll flag this for team attention to see what everyone thinks about if and when we should make a change here.

**Comment by snicoll** [comment]
I think it's worth aligning with the change in framework in `2.7.x`.

**Comment by wilkinsona** [comment]
Alright, let's tweak this in 2.7. Thanks, @snicoll.
