### ISSUE TITLE
Upgrade to Kafka 3.1.0

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#29700]
spring-kafka 2.8.3 (due Feb 21) will be compatible with this new 3.1.0 Kafka version; the next Boot 2.7 milestone can therefore use it.

https://github.com/spring-projects/spring-kafka/commit/dd64db8ba5fb5d8a41c75d694e19c9ee7a17b240

**Comment by garyrussell** [comment]
2.8.3-SNAPSHOT is available with this change.

**Comment by DRoppelt** [comment]
Seeing that spring-kafka 2.8.X is compatible with spring boot 2.6.X according to the compatibility matrix here: https://spring.io/projects/spring-kafka

Will this change also be compatible with the next spring boot 2.6.X?

Since there are changes to make spring-kafka 2.8.X compatible with 3.1.0, we might have a problem as boot 2.6.X ships 3.0.0?

**Comment by snicoll** [comment]
The change is backward compatible. Both `2.6.x` and `2.7.x` are building against Spring Kafka `2.8.3-SNAPSHOT` and we won't upgrade to Kafka 3.1.0 in `2.6.x`.
