### ISSUE TITLE
Dependencies form a cycle (2.6.0)

### ISSUE THREAD

**Issue by 1715640858** [spring-projects/spring-boot#29813]
This happened when I use spring-boot-starter-parent 2.6.0, but 2.5.9 is ok
```
The dependencies of some of the beans in the application context form a cycle:

   eventManager (field private com.xxx.InfoService com.xxx.EventManager.infoService)
┌─────┐
|  infoService (field private com.xxx.BizService com.xxx.InfoService.bizService)
↑     ↓
|  bizService (field private com.xxx.InfoService com.xxx.BizService.infoService)
└─────┘
```

**Comment by livk-cloud** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes
Take a look at the changelog of springboot 2.6.x

**Comment by snicoll** [comment]
@1715640858 please review the release notes when upgrading to a new feature release of Spring Boot. This [section](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#circular-references-prohibited-by-default) is relevant to what is happening.

You can break the cycle by using `ObjectProvider` or `@Lazy` for instance. Or better yet by rearranging your infrastructure so that there isn't a cycle in the first place). If you have more questions, please follow-up on StackOverflow.

**Comment by 1715640858** [comment]
@snicoll I'm sorry I didn't notice the notes before. Thanks a lot
