### ISSUE TITLE
java.io.IOException: Problem reading font data when using bootBuildImage

### ISSUE THREAD

**Issue by tompson** [spring-projects/spring-boot#29972]
we are trying to switch from using `jib` for creating the docker images to using Spring Boot built in buildpacks with `bootBuildImage` but are having problems in the resulting image when using JasperRerports:

```
Caused by: java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Unknown Source) ~[na:na]
        at java.desktop/java.awt.Font.createFont(Unknown Source) ~[na:na]
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.<init>(SimpleFontFace.java:100)
```

it seems like there are not fonts configured in the resulting docker image - is there a way to add those?

**Comment by scottfrederick** [comment]
The set of packages available in the generated image is determined by the run image in the [builder stack](https://buildpacks.io/docs/concepts/components/stack/). By default, Spring Boot uses the Paketo `paketobuildpacks/builder:base` builder image, which includes the [`base` run image](https://paketo.io/docs/concepts/stacks/#what-paketo-stacks-are-available). The first thing to try is to [configure `bootBuildImage`](url) to use the `paketobuildpacks/builder:full` builder as [shown in the documentation](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#build-image.customization). If the `full` run image still doesn't have everything you need, then you might need to create a custom run image that contains additional packages. 

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. This feels like a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by tompson** [comment]
sorry, was not aware that there is already an option for configuring the buildpack, you can delete this issue, I postet the question to stackoverflow since I am still having troubles configuring the `full` buildpack: https://stackoverflow.com/questions/71239373/java-io-ioexception-problem-reading-font-data-when-using-bootbuildimage
