### ISSUE TITLE
servlet.service() for servlet [dispatcherServlet] in context with path threw exception [ handler dispatch failed; nested exception is java.lang.stackoverflow] with root cause

### ISSUE THREAD

**Issue by ganeshnavdurge777** [spring-projects/spring-boot#29989]
I am getting below exception . 

Version used : 
Spring boot 2. 

**Exception:**

**java.lang.stackoverflow: null**

**servlet.service() for servlet [dispatcherServlet] in context with path threw exception [ handler dispatch failed; nested exception is java.lang.stackoverflow] with root cause.**

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
