### ISSUE TITLE
security password was found in the spring-boot logs

### ISSUE THREAD

**Issue by SperChung-11** [spring-projects/spring-boot#30015]
🐞 Bug report (please don't include this emoji/text, just add your details)

Hi, we found that security password was in the spring-boot logs whichi is unsafe. can you help to remove it for the code ? Thanks.

`org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration.getOrDeducePassword(UserDetailsServiceAutoConfiguration.java:87)-->
Using generated security password: 88f86935-2cd0-47b4-a462-d1dea98eaa14`

**Comment by wilkinsona** [comment]
This is intentional. Please see [the reference documentation](https://docs.spring.io/spring-boot/docs/2.5.x/reference/htmlsingle/#features.security). If you do not want a password to be generated and logged, you should either configure a password for the default user using the `spring.security.user.password` property or you should provide your own security configuration.
