### ISSUE TITLE
DataFetcherExceptionResolver beans are not considered in GraphQlTester slice tests

### ISSUE THREAD

**Issue by JimHosken** [spring-projects/spring-boot#30055]
I believe this is a feature request, as I did not see any facilities in the current spring-graphql-test library to accomplish this.

When testing the Controller layer of our application using GraphQlTester, it would be nice to be able to configure the inclusion of our custom DataFetcherExceptionResolver to validate the error handling capabilities we have configured and to assert the ErrorType / error maps in the response.

**Comment by bclozel** [comment]
Thanks @JimHosken this is a bug in the Spring Boot ˋ@GraphQlTest` support. We are not including all the required types in this sliced test.

**Comment by bclozel** [comment]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem
Spring Boot helps you to write integration tests without involving the entire application context (all beans, live servers, etc.). These ["test slices"](https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/features.html#features.testing.spring-boot-applications.autoconfigured-tests) are supported with annotations that are specific to the "slice" we'd like to test.
For Spring GraphQL applications, we now provide a [`@GraphQlTest`](https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/features.html#features.testing.spring-boot-applications.spring-graphql-tests) slice.

Part of the test slice support is about filtering what kind of beans we should consider when scanning - rejecting the types that are out of scope for this slice and only keeping the relevant ones for what we're testing. For that, we [a `GraphQlTypeExcludeFilter` imported by the test annotation itself](https://github.com/spring-projects/spring-boot/blob/d47b56a40ed2ec29a1b784a3295d960840ccd4fa/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/graphql/GraphQlTest.java#L85).

The problem here is that our `GraphQlTypeExcludeFilter` [currently allows `JsonComponent`, `RuntimeWiringConfigurer`, `Converter.class`, `GenericConverter` beans only](https://github.com/spring-projects/spring-boot/blob/d47b56a40ed2ec29a1b784a3295d960840ccd4fa/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/graphql/GraphQlTypeExcludeFilter.java#L50-L53). The issue reported here shows that other beans should be considered.

We should also include `DataFetcherExceptionResolver`, `Instrumentation` and `GraphQlSourceBuilderCustomizer` as [they are used to set up the GraphQL source](https://github.com/spring-projects/spring-boot/blob/d47b56a40ed2ec29a1b784a3295d960840ccd4fa/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/graphql/GraphQlAutoConfiguration.java#L70-L72).

## Solution
The `GraphQlTypeExcludeFilter` should be updated to also allow those types (i.e. not filter them out). Tests should be added in `GraphQlTypeExcludeFilterTests`. This should be very similar to how `RuntimeWiringConfigurer` components are tested in this class.

The [list of allowed types is also written in the reference documentation](https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/features.html#features.testing.spring-boot-applications.spring-graphql-tests). You should also [update the reference docs accordingly](https://github.com/spring-projects/spring-boot/blob/2.7.x/spring-boot-project/spring-boot-docs/src/docs/asciidoc/features/testing.adoc#auto-configured-spring-graphql-tests). You'll find the file here `spring-boot-project/spring-boot-docs/src/docs/asciidoc/features/testing.adoc` in your local copy.

**Important: because Spring GraphQL support was added in 2.7.x (and is not currently supported in 3.0.x), you need to checkout the `2.7.x` branch and submit a pull request against it.**


## Steps to Fix 
 
- [ ] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by GauthamM-official** [comment]
@bclozel Hi, Shall I work on this?

**Comment by bclozel** [comment]
It doesn't seem you've contributed in the past here; if that's the case, this issue is all yours! Don't hesitate to ask for clarifications here, we're here to help.

**Comment by GauthamM-official** [comment]
Thank you @bclozel. I will post any questions/doubts in this thread.

**Comment by GauthamM-official** [comment]
@bclozel I see that a `LinkedHashSet` is being [used](https://github.com/spring-projects/spring-boot/blob/d47b56a40ed2ec29a1b784a3295d960840ccd4fa/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/graphql/GraphQlTypeExcludeFilter.java#L50-L53). So is there any specific order in which `DataFetcherExceptionResolver`, `Instrumentation` and `GraphQlSourceBuilderCustomizer` are to be added to the set?

**Comment by bclozel** [comment]
No, there is no particular order.

**Comment by GauthamM-official** [comment]
@bclozel Shouldn't the javadoc for `@GraphQlTest` also be updated?

**Comment by bclozel** [comment]
Yes they should. Sorry I forgot to mention that.

**Comment by GauthamM-official** [comment]
@bclozel Added PR, please review.

**Comment by bclozel** [comment]
Cool, thanks @GauthamM-official !
Closing this issue in favor of #30078
