### ISSUE TITLE
when the configuration file in the project exists application.xml, it will fail to start

### ISSUE THREAD

**Issue by GravityMatrix** [spring-projects/spring-boot#30184]
When application.xml and application.yaml exist in the configuration file， the startup fails。

When the application.xml is changed to another name or moved to another directory, the startup is successful。

Found when I use @ImportResource to import xml bean，But even if you don't use it, you will still get an error

case:
[spring-xml-demo.zip](https://github.com/spring-projects/spring-boot/files/8230628/spring-xml-demo.zip)

**Comment by wilkinsona** [comment]
This is the expected behaviour. Spring Boot supports properties files in both `.properties` [and `.xml` format](https://github.com/spring-projects/spring-boot/issues/1777). As a result, your `application.xml` file that is in one of the locations which Spring Boot checks for configuration properties is being loaded as an XML properties file.
