### ISSUE TITLE
An empty default spring.log file is still created when the logging.file or logging.path property is set 

### ISSUE THREAD

**Issue by zibbly** [spring-projects/spring-boot#303]
When the logging.file or logging.path is set Boot log output is written to either the file specified via logging.file or to the spring.txt file in the directory specified by logging.path.

However, a zero byte file is also written to the default Boot log output file - \tmp\spring.txt.

The default log file should not be created if either of the logging.file or logging.path property is set so as to create a Boot log outfile that is something different from \tmp\spring.txt. 

See also Issue #273.

**Comment by jugalps** [comment]
I guess this is still not fixed, I can see that the file `/tmp/spring.log` is still getting created.

**Comment by wilkinsona** [comment]
@jugalps, this issue was closed over a year ago. If you're seeing this problem with 1.2.2.RELEASE, please open a new issue with details of the configuration that's triggering the problem.

**Comment by bmsantos** [comment]
This issue is still happening in 1.3.1 and 1.3.2.

Here's the details of what I was able to find so far:

OSX: When deployed in OSX it works just fine. Only one logback file is generated when using ```logging.file``` in **application.properties**.

RHEL 6.7: When deployed in Linux (Red Hat Enterprise Linux Server release 6.7), the extra file is generated. The best solution I found so far was to remove the logback.xml file from classpath and pass it at command line: ```java -jar spring-boot-app.jar --logging.config=./logback.xml```. This prevents a second jar from being generated.
