### ISSUE TITLE
Document that spring.jpa.hibernate.naming-strategy has default value

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3035]
Please document in [example `application.yml`](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties) that `spring.jpa.hibernate.naming_strategy` property has default value `org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy`.

Also as far I can see setting property `spring.jpa.properties.hibernate.ejb.naming_strategy` doesn't work and you have to use `spring.jpa.hibernate.naming_strategy` property instead (see [HibernateJpaAutoConfigurationTests.testCustomNamingStrategyViaJpaProperties](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfigurationTests.java#L101). I believe that it's also should be documented somewhere, because it's unexpected behavior.

**Comment by thombergs** [comment]
I believe this issue can be closed. Hibernate 4 is no longer supported since Spring Boot 1.5 (see [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#downgrading-to-hibernate-43)).

Thus, both properties `spring.jpa.hibernate.naming_strategy` and `spring.jpa.hibernate.naming_strategy` are no longer relevant. And the [docs](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-configure-hibernate-naming-strategy) have been properly updated to describe the new Hibernate 5 naming strategy properties.

However, while at it, I submitted PR #9763  which makes the current docs a little clearer by mentioning both new properties `spring.jpa.hibernate.naming.physical-strategy` and `spring.jpa.hibernate.naming.implicit-strategy` and the fact that these came with Hibernate 5.

**Comment by wilkinsona** [comment]
Thanks very much, @thombergs
