### ISSUE TITLE
how not generate springboot-start.log?

### ISSUE THREAD

**Issue by SoftwareKing** [spring-projects/spring-boot#30412]
Spring Boot 2.4.8:
`<springProperty scop="context" name="eros_log_path" source="eros.log.path" defaultValue="/logs/test.log"/>`

I found that the business log was printed to springboot-start.log and test.log. I think the business log will only be printed to test.log . how not generate springboot-start.log?
@qerub @jkutner @scheerer @rtack @xenoterracide

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
