### ISSUE TITLE
Actuator - MeterFilter.accept is ignored

### ISSUE THREAD

**Issue by kle-pra** [spring-projects/spring-boot#30496]
-  Spring Boot: `2.6.5` with `spring-boot-starter-actuator`
- ` micrometer-registry-prometheus`: `1.8.4` for exposing prometheus metrics

I think there is a bug with  `MeterFilter.accept.`

The following config ouputs all the metrics even though `MeterFilter.accept `is returning false (hardcoded).

```Java
   @Configuration
public class MetricConfiguration {

    private static final String IGNORED_TAGS[] = {"main-application-class"};


  @Bean
    MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
        return registry -> registry.config()
           //   .meterFilter(ignoreTags(IGNORED_TAGS))
                .meterFilter(accept(t -> false));
    }
}
```
Meanwhile, ignoreTags, if commented in, is working fine (the config is working).

**Comment by mbhave** [comment]
`MeterFilter` is part of the [Micrometer](https://github.com/micrometer-metrics/micrometer/blob/904bc03331a0604eba525dad17db2c422ae6a798/micrometer-core/src/main/java/io/micrometer/core/instrument/config/MeterFilter.java) project. Please create an issue in their issue tracker so that the Micrometer team can take a look.
