### ISSUE TITLE
management.endpoint.health.probes.add-additional-paths has no effect when configuration properties have already created the liveness and/or readiness groups

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#30612]
```
management.endpoint.health.group.liveness.show-details=always
management.endpoint.health.group.readiness.show-details=always
management.endpoint.health.probes.add-additional-paths=true
management.endpoint.health.probes.enabled=true
management.server.port=8081
```

Via @dsyer, with these properties, the probes are not available at `:8080/livez` and `:8080/readyz`. Commenting out the `show-details` properties fixes the problem. The same problem occurs when configuring `management.endpoint.health.group.liveness.include` and `management.endpoint.health.group.readiness.include`.

**Comment by malachispencer** [comment]
I am having a similar problem. My actuator endpoints are using the management port because I need metrics to be on the management port, but I need the health checks to be on the main port. 

`management.endpoint.health.probes.add-additional-paths=true` does not expose liveness at /livez and readiness at /readyz on the main server port.

`management.endpoint.health.group.liveness.additional-path="server:/livez"` does not work either.

However, `management.endpoint.health.group.liveness.additional-path="management:/livez"` **does** work.

**Comment by wilkinsona** [comment]
@malachispencer As far as we know, this should work unless you have configured any `management.endpoint.health.group.liveness.*` or `management.endpoint.health.group.readiness.*` properties. If you have seen behavior that is different to that, can you please share a minimal sample that we can look at?

**Comment by malachispencer** [comment]
@wilkinsona I removed those properties as well as the `show-details` property and it still doesn't work. Here is what I'm trying now (and it's not working):

```
management.server.port=8088

management.endpoints.enabled-by-default=false

management.endpoint.health.enabled=true
management.endpoint.health.probes.enabled=true
management.endpoint.health.probes.add-additional-paths=true
```

**Comment by malachispencer** [comment]
@wilkinsona Is this officially a bug then? Please let me know if there's any workaround for this.

**Comment by ChristianCiach** [comment]
I just wasted an hour on trying to figure out why `/readyz` gave me a 404 just because `management.endpoint.health.group.readiness.include` has been configured.

This issue can be workarounded by setting the additional paths explicitly:
```
management.endpoint.health.probes.add-additional-paths=true
management.endpoint.health.group.liveness.additional-path=server:/livez
management.endpoint.health.group.readiness.additional-path=server:/readyz
```
This looks redundant, but I still have to configure `management.endpoint.health.probes.add-additional-paths=true` because our company internal autoconfiguration library reacts to this property, but not the other two.
