### ISSUE TITLE
Change branching method so PR titles will be visible

### ISSUE THREAD

**Issue by ipanimnim** [spring-projects/spring-boot#30618]
Every popular open-source repository these days lets viewers see what's going on through the PR names. Some repositories do that by specifying the issue name (e.g. [SPARK-28031] foo bar), and some specify the change by some, conversion (e.g. feat: foo bar). In Spring Boot the situation's a little bit different, and I'd like that to change, so it will be easier to understand what's going on. In Spring Boot the names of the commits are viewable only as of the merged source and target branches, as this picture demonstrates:
![image](https://user-images.githubusercontent.com/96628276/162449877-ba88284c-ab2f-4d3a-9d46-5da810042dc4.png)
I'm not exactly sure what has been done here that is so different than other repositories, but for example projects like Apache Spark has a much clearer and organized way of managing Git:
![image](https://user-images.githubusercontent.com/96628276/162450924-3b0ad280-8517-46a7-9610-04b653b576d6.png)
In Spring Boot we cannot see not the original issue, not the subject, and not even the title (!). I think the situation can (easily) get improved.

**Comment by wilkinsona** [comment]
Thanks for the suggestion.

Our approach to commit messages is [described on the wiki](commit message). The expand a bit on what's said in the wiki and the references to which it links, it's our preference to link to an issue in the body of each commit message rather than in the title. We do this to maximise the space that's available to describe the change, trying hard to avoid it being truncated in the GitHub UI. For this reason, we also choose not the include things like `[SQL]` or `[BUG]` in the title.

The commits named `Merge branch "a.b.c" into 2.6.x` are named using Git's standard conventions for forward-merges as we apply a change from a maintenance branch forwards, across any other maintenance branches and into `main`. Our rationale for using forward merges is also [described on the wiki](https://github.com/spring-projects/spring-boot/wiki/Working-with-Git-branches#why-merging-forwards-is-important).

This is an area where things are quite subjective. Both you and the maintainers of Spark prefer their approach, but we prefer ours and we would find switching to their approach to be quite detrimental. Thanks again for the suggestion, though.
