### ISSUE TITLE
Provide a way to expose on which HTTP port the application is running

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3067]
`SpringApplicationLifecycleMXBean` is a way to know (potentially) remotely if a Spring Boot app is started. We could extend this infrastructure (used by the start/stop goals of the maven plugin) to expose a `SpringWebApplicationContextMXBean` that would expose things about the web application. For now we could expose the actual HTTP port.

**Comment by snicoll** [comment]
@philwebb I have a candidate fix for that one. If that looks good to you I'd appreciate if you could merge that before M1 as the STS team will use this feature. Thanks!

**Comment by philwebb** [comment]
I was about to merge this but I'm have second thoughts. Having the main `spring-boot` module expose the server port seems like a fine choice but I'm not sure that it should be directly aware of the management port since that's really a `spring-boot-actuator` concern.

The name `SpringApplicationLifecycleMXBean` is also looking a little dubious if we merge this since it starts to cover lifecycle *and* server attributes.

**Comment by philwebb** [comment]
Although we do have precedent already with the `ServerPortInfoApplicationContextInitializer`.

**Comment by snicoll** [comment]
This is a good point and also something that bugged me a lot. I wonder if all this couldn't be associated with the new `devtools` initiative? If we don't want to do that, we can manage things differently by updating the contract as follows

```
Integer getLocalServerPort();
Integer getLocalPort(String name);
Collection<String> getLocalPortNames();
```

The caller would have to call that with the magic "management" string. But it would also allow custom containers to be managed by the same API.
