### ISSUE TITLE
Add a profile to spring-boot-starter-parent for building a native image from an application

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#30830]

**Comment by snicoll** [comment]
I've added a classifier when the profile is used so that the repackaged archive is no longer the main artifact, see https://github.com/spring-projects/spring-boot/commit/216d156968aa664df64d0d6e1017917044ac8b7a.

This is temporary until an option in the NBT plugin is available, see https://github.com/graalvm/native-build-tools/issues/237.
