### ISSUE TITLE
@RestControllerAdvice @ExceptionHandler Inconsistent behavior with @RestControllerEndpoint

### ISSUE THREAD

**Issue by christophejan** [spring-projects/spring-boot#30899]
Currently, using RestControllerAdvice ExceptionHandler with RestControllerEndpoint give the following result :
1. Webflux using same management port : ExceptionHandler take in account
2. Webflux using different management port : ExceptionHandler take in account
3. Mvc using same management port : ExceptionHandler take in account 
4. Mvc using different management port : ExceptionHandler **ignored**

See tests in attached [demo-exception-handler-rest-controller-endpoint.zip](https://github.com/spring-projects/spring-boot/files/8647342/demo-exception-handler-rest-controller-endpoint.zip)

It seems inconsistent to me.

spring-boot version : 2.6.7

**Comment by wilkinsona** [comment]
Thanks very much for the minimal yet really comprehensive sample, @christophejan. I believe the difference in behaviour that you are seeing is because `org.springframework.boot.actuate.autoconfigure.web.servlet.CompositeHandlerExceptionResolver` does not consider a parent bean factory when finding `HandlerExceptionResolver` beans. We probably just need switch to using `BeanFactoryUtils.beansOfTypeIncludingAncestors(ListableBeanFactory, Class<T>)` instead but I'd like to check with the rest of the team first as my memory's a little hazy.

**Comment by philwebb** [comment]
Closing in favor of PR #31495
