### ISSUE TITLE
Springboot can support multiple protocols  

### ISSUE THREAD

**Issue by 1057105012** [spring-projects/spring-boot#31234]
I don't want to change my controller, but I need to support TCP, UDP, HTTP, and some custom protocols to access my interface. Springboot can provide a simplified solution, which I find quite useful

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
