### ISSUE TITLE
Spring boot and JavaFX

### ISSUE THREAD

**Issue by alrazihi** [spring-projects/spring-boot#31250]
I faced a strange behavior on my app, where i am trying to use javaFX as client interface for spring boot.
I can get the data from the database on the first SCENE but not the other. null in my case.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
