### ISSUE TITLE
Spring-boot repository GitHub for slack integration

### ISSUE THREAD

**Issue by lthoulon-locala** [spring-projects/spring-boot#31265]
Hello.

I'm sorry if this is not the right place to ask for this or if I misunderstood something but it seems I'm unable to add spring boot as a repository to subscribe to using [GitHub for Slack](https://slack.github.com/).

I'm using the following command
```
/github subscribe spring-projects/spring-boot
```

Which is telling me 
```
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
Note: You need to be an organization owner to install the app (or ask one to install it for you).
```

I've been subscribing to other repositories without issues and it's the first time I get such a message so I guess there may be something to activate on your end ?

Again I'm very sorry that this issue doesn't fall into the usual categories.
Thanks

**Comment by mhalbritter** [comment]
Is your question if we want the spring-boot repo integrated in our slack? If yes, I would like to have them separated. I like the GitHub notifications and don't need them in Slack, too.

**Comment by wilkinsona** [comment]
That's my understanding too. To get notifications appearing in Slack is a two-step process:

1. There's an app that needs to be installed in this repository (it's already installed in some other repos such as spring-hateoas)
2. The integration then needs to be enabled in a Slack channel

AIUI, we can do 1 without noticing any difference. It'll just make it possible for people to perform step 2 without it failing because the app hasn't been installed.

Assuming that my understanding is correct, I have no objections to installing the app.

**Comment by mhalbritter** [comment]
Ah, now I get it. I don't have any objections then :)

**Comment by wilkinsona** [comment]
I've added the app to spring-projects/spring-boot. You should be able to subscribe in your Slack workspace now, @lthoulon-locala.

**Comment by lthoulon-locala** [comment]
It works. Thanks a lot.
