### ISSUE TITLE
@Component and @ConditionalOnMissingBean on class ,Beans cannot be created when used together

### ISSUE THREAD

**Issue by liubinduo** [spring-projects/spring-boot#31305]
The column code is as follows

``` java
@Component
@ConditionalOnMissingBean(value = ILogin.class)
public class LoginImpl implements ILogin {
}
```
I'm pretty sure Context doesn't have an instance of ILogin. Why can't LoginImpl be instantiated?

``` java
@RestController
@RequestMapping("login")
public interface ILogin {
    
    @PostMapping
    IRestResponse<?> login(@RequestBody @Validated LoginAccount account);
}
```
When I post ask "/login". return Not Found "/login"

**Comment by liubinduo** [comment]
When I post ask "/login". return Not Found "/login"

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

(Please review the javadoc of `@ConditionOnMissingBean`).

**Comment by liubinduo** [comment]
I think it's a Bug, @Component and @Service annotations can be scanned and registered by @ComponentScan, and @conditiononmissingBean should be able to control.

**Comment by snicoll** [comment]
Component scanning has no notion of reproductible ordering and that'a not the problem here. Supporting this consistently means we'd have to "wait" to apply the condition. Your example is very basic but it would fall apart very quickly if there were two candidates for that type.
