### ISSUE TITLE
Do not auto-configure a ReactiveUserDetailsService when an AuthenticationManagerResolver bean is present

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#31317]
As pointed out in https://github.com/spring-projects/spring-boot/issues/26766#issuecomment-1149546094 we should look at porting #28361 to `ReactiveUserDetailsService`.

**Comment by wilkinsona** [comment]
We handled the change on the servlet side as an enhancement. If we change this in 2.6.x, it'll cause a problem for anyone being a reactive app where there's an `AuthenticationManagerResolver` bean but they're still relying on the `reactiveUserDetailsService` bean being auto-configured. I find it hard to say how likely that is. Flagging for team meeting so that we can consider out options.

**Comment by philwebb** [comment]
We've discussed this and agree that it's really an enhancement and not a bug. There's too much risk in doing this in 2.x so we'll attempt it for 3.0.x.
