### ISSUE TITLE
@RequestParam string data type always null if parameter contains '%' character

### ISSUE THREAD

**Issue by hirofumifudoudou** [spring-projects/spring-boot#31476]
```   
@GetMapping("/path/to/url")
    public List<Entry> getEntries(@RequestParam Optional<String> condition) {
```
if request like this:
```
http://localhost:8080/path/to/url?condition=%ECG%
or
http://localhost:8080/path/to/url?condition=%ECG
or
http://localhost:8080/path/to/url?condition=ECG%
```
I expect value of 'condition' 
"%ECG%", "%ECG", "ECG%" 
respectively.

but variable 'condition' always equals to null.
and remove '%' from parameter:
```
http://localhost:8080/path/to/url?condition=ECG
```
got 'condition' equals to "ECG"

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
