### ISSUE TITLE
MongoDataAutoConfiguration doesn't work with devtools classloader

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3162]
The `MongoDataAutoConfiguration` currently uses:

```
				for (BeanDefinition candidate : scanner
						.findCandidateComponents(basePackage)) {
					entitySet.add(ClassUtils.forName(candidate.getBeanClassName(),
							MongoDataAutoConfiguration.class.getClassLoader()));
				}
```

This causes found beans to be loaded using the wrong classloader. We should load using the context classloader.

It's also worth checking the other spring data configurations.

**Comment by olivergierke** [comment]
I've pushed a [tiny branch](https://github.com/spring-projects/spring-data-examples/commit/11af8406d93e0685ad349a7489e7e60f9a0b66c2) to the Spring Data examples to work on this.

1. Run the `StoreApp` from `rest/starbucks` in debug mode.
2. Have a breakpoint in `BytecodeGeneratingEntityInstantiator.createObjectInstantiator(…)` (the *locally fixed* copy inside the project).
3. `curl http://localhost:8080`

At the breakpoint you should see the generator being used but see an exception (I guess) due to the mismatch of classloaders for instantiator (`ClassUtils.getDefaultClassloader()`) and the one that's been used to load the domain class (see Phil's code snippet above).

**Comment by olivergierke** [comment]
Further diagnose:

- the code above doesn't seem to cause the issue as it's not even executed. There's a `mongoMappingContext` bean in the application context for some reason (I guess it's due to the fact that the repository setup might be run before that particular bean is created and the former already creates a `MongoMappingContext` bean as fallback but that's probably worth another ticket).

- My "fix" to `BytecodeGeneratingEntityInstantiator` causes a `ClassCastException` in `createObjectInstantiator` as `ObjectInstantiator` is loaded with a different classloader than what could be obtained by `ClassUtils.getDefaultClassloader()`.
- with the "fix" I see `ObjectInstantiator` being loaded from `AppClassLoader`, `ClassUtils.getDefaultClassloader()` returning `TomcatEmbeddedWebappClassLoader` with `RestartClassLoader` and `AppClassLoader` as parent chain. This setup creates a `CCE` after an instance of the generated class using a `ByteArrayClassloader` with `TEWCL` as parent.
- without the "fix" the generate instance uses the `BAC`with `ACL` as parent and the cast succeeds, but then the domain type is loaded using `RCL` the instance's class loader is `ACL`.
- I also tried to use the classloader of the domain class (`RCL`) to use to generate the implementation of `ObjectInstantiator` but this then causes the same `CCE` as described in the first bullet and a fallback to the reflection based approach.

**Comment by philwebb** [comment]
See also https://jira.spring.io/browse/DATACMNS-710
