### ISSUE TITLE
Allow MessageSource contributions

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3172]
Talking to @lhazlewood at a meetup and he mentioned that it's currently difficult to contribute resources to the `MessageSource`. A way of finding additional sources, ordering them and creating a composite would be useful.

**Comment by philwebb** [comment]
@lhazlewood Anything comments you can add to this?

**Comment by lhazlewood** [comment]
@philwebb that sounds about right!

I was thinking that a Starter could expose a MessageSource (@Ordered if desired) and there would be a CompositeMessageSource that 'wraps' them all and performs lookup on each, short circuiting after it found the first non-null/empty value for a given i18n key.

In my particular case, I wouldn't need it to be @Ordered because all of my keys start w/ my starter name and that should be sufficient to avoid conflict in my case, e.g. `stormpath.web.`*

http://docs.stormpath.com/java/spring-boot-web/i18n.html

HTH!

**Comment by cemo** [comment]
We have our internal `MessageSourceAutoConfiguration` and its basically searching all `message source files` based on a regex such as `messages/messages-*.properties`. In this way we can successfully create a pluggable system. Here is our dummy implementation: https://gist.github.com/cemo/38d4f65ecb3a71288cfe

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
