### ISSUE TITLE
Deprecate @ServletEndpoint, @ControllerEndpoint and @RestControllerEndpoint

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#31768]
We should decide if we want to deprecate and later remove `@ControllerEndpoint` and `@RestControllerEndpoint` from the actuator. Using them ties the user to WebMVC or WebFlux and they were meant to ease the upgrade path to the weblayer-abstracting `@Endpoint` with `@ReadOperation`, etc.

Getting rid of those would pave the way for https://github.com/spring-projects/spring-boot/issues/20290.

If you're seeing this ticket and object to this idea, please comment, your feedback is very valuable. Please also explain your use case and why this use case can't be solved with `@Endpoint` or `@WebEndpoint`.

**Comment by jeffbswope** [comment]
We have some endpoints where we wanted to be able to include app and/or actuator links in the response. The low friction way we found was to move to `@RestControllerEndpoint` and get the `HttpServletRequest` and use `getRequestURL()` to build them. It was a while ago so I don't know if we missed some way to do that with a `@WebEndpoint` then or added since then...

Or if the idea of those links is an anathema to the endpoint abstraction entirely... they are strange endpoints I won't defend in general so no objections to deprecation, just a data point...

**Comment by mmoayyed** [comment]
We have quite a few `@RestControllerEndpoint` annotations used [here](https://github.com/apereo/cas).

Main use cases that I think would be useful and helpful to support going forward would be:

-  Support the convenience of `@GetMapping`, `@PostMapping`, `@ResponseBody`, etc.

I think most of these could likely be converted and written to conform to the new way of doing this.

- Ability to read the servlet request body in raw form without mapping the request body it to an object, using `HttpServletRequest#getInputStream()`

It might be doable to do this today, but I wasn't able to find an alternative.

**Comment by wilkinsona** [comment]
Thank you, @mmoayyed.

> Support the convenience of @GetMapping, @PostMapping, @ResponseBody

In Actuator endpoint terms, `@GetMapping` is a `@ReadOperation` and `@PostMapping` is a `@WriteOperation`. There's also `@DeleteOperation` which is the equivalent of `@DeleteMapping`.

Can you expand a bit on the need for `@ResponseBody`? The value returned from an endpoint operation is already written to the body of the response.

> Ability to read the servlet request body in raw form … It might be doable to do this today

We don't support this at the moment. Any body is read up front as a source of arguments for the endpoint operation's method parameters. There's an implicit assumption here that the body can be converted into key-value pairs.

**Comment by mmoayyed** [comment]
Thank you Andy. 

The main example that I found for `@ResponseBody` is dealing with exporting data out in form of a zip file. The endpoint creates a zip file `Resource`, and returns it in the form of `new ResponseEntity<>(resource, headers, HttpStatus.OK)` where the header contains content-disposition entries, etc. The endpoint itself is tagged as 

```
@GetMapping(path = "/export", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
@ResponseBody
```

Likewise, the reverse of this operation is handled as an `import` endpoint in the same component that reads the `request.getInputStream()`, and stores the processed data somewhere, returning some http status endpoint. The body could contain on object or a collection of objects (as would be the classical import use case)

**Comment by wilkinsona** [comment]
You can return a `Resource` from a `@ReadOperation` as we do in Boot's `LogFileWebEndpoint`:

https://github.com/spring-projects/spring-boot/blob/35c49afd97dd353020b96df9c537bb44d819ef7e/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/logging/LogFileWebEndpoint.java#L53-L54

I guess a missing piece is the ability to set a `Content-Disposition` header which `WebEndpointResponse` does not allow you to do at the moment.

> Likewise, the reverse of this operation is handled as an import endpoint in the same component that reads the `request.getInputStream()`, and stores the processed data somewhere, returning some http status endpoint

On first impressions, this doesn't sound like something that you'd do as part of operating an app that's running in production so it isn't necessarily something that we'd expect to support in Actuator. Can you expand a bit on the use case please?

**Comment by mmoayyed** [comment]
Sure. I'd have to go back a few steps, so please bear with me. 

This project ships a number auto-starters that control the implementation of a particular repository type. The ultimate build script (put together by an adopter in form of a *overlay*), allows an adopter to include the appropriate starter in their build and let that repository manage their data. I suppose there are scenarios where one would want to take data from one repository in one version, and move it over to another repository in the next version. Let's say JSON to Cassandra, Mongo to DynamoDb, etc. So the import/export operations provide a facility to do that as a point of convenience, behind an actuator endpoint that of course needs to be enabled, protected, used likely once or twice in dev, and then turned off in production as you note. Certainly, it's not something to actively use in production. 

I suppose one could always use native tooling, if and when available, to handle the data migration task, or fall back onto dedicated libraries and frameworks that take care of such things. While all should be better options in theory, (and surely there is nothing stopping the advanced user to play around with such things) they add additional points of complexity and learning curve that in this particular context, a very select group of users would want to deal with. The overwhelming preference generally is to deal with an endpoint that handles such things (IIRC, there is a command-line utility available that does this as well in form a spring shell command, but I digress).

**Comment by frederic-kneier** [comment]
We currently use the management endpoints as a means of providing an internal API that is served on a different port. These annotations allow us to actually provide dedicated endpoints on the management port as well as handling security on these differently.

This way we can provide an Kubernetes ingress for the public API on one port while providing management actions an internal API without ingress on another.

**Comment by wilkinsona** [comment]
Thanks, @frederic-kneier.  Would it be fair to say that you're using an Actuator endpoint as a convenient way of exposing the API on a different port rather than because it's used as part of operating the application in production?

**Comment by frederic-kneier** [comment]
Not entirely, but regarding @ControllerEndpoint and @RestControllerEndpoint I think that is true. It would be ok to use simple @Controller and @RestController annotations if we could specify the actual endpoint/port to be used and if security could be configured based on the endpoint/port. There are still management endpoints that do not match this description, but I think they could be implemented using the normal endpoints / operations.

**Comment by spencergibb** [comment]
We have a few in spring cloud. I'll get details in a bit

**Comment by mmoayyed** [comment]
One other thing that might be useful here: `@RestControllerEndpoint` allows for overloading methods that address different requirements. For example, one could have multiple `@GetMapping` methods that handle different concerns, with different parameters or path variables. This seems more *natural* vs one `@ReadOperation` with 2-3 parameters some marked as selectors and some marked as not. Perhaps the replacement could provide the same programming model.

**Comment by bclozel** [comment]
We have discussed this again earlier today and decided that we should deprecate this for 3.3.0-RC1.
We think that since this was introduced, the `@Endpoint` / `@*Operation` model has evolved quite a bit and that we declined low-level web support feature requests in this area. Right now it seems that the abstraction leaks here and that it prevents us from evolving the implementation.

We don't plan on removing this feature soon - we will honor at least our 2 minor releases policy. In the meantime, we will also gather feedback from the community.

**Comment by spencergibb** [comment]
Spring Cloud Gateway uses `@RestControllerEndpoint` https://github.com/spring-cloud/spring-cloud-gateway/blob/66aa480623a00465ba399e1f16c86e07090ad6ea/spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/actuate/GatewayControllerEndpoint.java#L46

**Comment by bclozel** [comment]
We had a look before scheduling this, and it seems this endpoint would work well with `@ReadOperation` and `@WriteOperation`.

**Comment by johanhaleby** [comment]
I've run into this issue after upgrading to Spring Boot 3.3.0 that I'm not sure how to proceed with. I've been using webflux in Spring Boot 3.2.x and I've implemented a custom actuator endpoint like this:

```kotlin
@Component
@RestControllerEndpoint(id = "api", enableByDefault = true)
class ApiProxyEndpoint {

    @Value("\${management.endpoints.web.base-path}")
    lateinit var managementPath: String

    @Autowired
    lateinit var webHandler: WebHandler

    @RequestMapping("**") // Match all path segments under <management-path>/api/ until the end of the path
    fun apiProxyEndpoint(exchange: ServerWebExchange): Mono<Void> {
        val originalPath = exchange.request.path.toString()
        val apiPathWithoutManagementPath = originalPath.substringAfter(managementPath)
        val updatedRequest = exchange.request.mutate().contextPath("/").path(apiPathWithoutManagementPath).header("X-Api-RootPath" managementPath).build()
        val updatedExchange = exchange.mutate().request(updatedRequest).build()

        return webHandler.handle(updatedExchange)
    }
}
```

The reason for doing this is that I want to expose the [hal-browser](https://github.com/mikekelly/hal-browser) as an actuator endpoint (so that I can browse the API from using the hal-browser from the actuator). What's happening is that when the hal-browser calls a URI (by calling the "api" endpoint in actuator) I redirect all requests to the _actual_ api endpoint (not behind actuator). This endpoint acts as a proxy, just forwarding all requests made to "api" to somewhere else. This has worked great for several years, but since Spring Boot 3.3.0, the `RestControllerEndpoint` has been deprecated and I can't find a way to replace it. I've tried this:

```kotlin
@Component
@WebEndpoint(id = "api", enableByDefault = true)
class ApiProxyEndpoint {

    @Value("\${management.endpoints.web.base-path}")
    lateinit var managementPath: String

    @Autowired
    lateinit var webHandler: WebHandler

    @WriteOperation
    @ReadOperation
    @DeleteOperation
    fun apiProxyEndpoint(exchange: ServerWebExchange): Mono<Void> {
        val originalPath = exchange.request.path.toString()
        val apiPathWithoutManagementPath = originalPath.substringAfter(managementPath)
        val updatedRequest = exchange.request.mutate().contextPath("/").path(apiPathWithoutManagementPath).header("X-Api-RootPath" managementPath).build()
        val updatedExchange = exchange.mutate().request(updatedRequest).build()

        return webHandler.handle(updatedExchange)
    }
}
```

but this doesn't work. The example above will show me this error in the HAL browser:

```json
{
  "timestamp": "2024-06-12T10:23:17.366+00:00",
  "status": 400,
  "error": "Bad Request",
  "requestId": "efc7c7b9-4",
  "message": "Missing parameters: exchange"
}
```

How can I achieve the same thing (i.e. proxying) in Spring Boot 3.3.0 without using the deprecated `RestControllerEndpoint`?

**Comment by wilkinsona** [comment]
It looks to me like your `ApiProxyEndpoint` should be a `@RestController` and use `management.endpoints.web.base-path` to map it to `/actuator/api`. If you're running actuator on the same port as the rest of the application, a standard `@RestController` should be all that you need. If you're running actuator on a separate port, you'll need to use a `@ManagementContextConfiguration` class registered in `META-INF/spring.factories` to define the controller as a bean.

**Comment by johanhaleby** [comment]
@wilkinsona I'm using a different port so I guess I should try the `@ManagementContextConfiguration` path. I'll let you know how it goes. Thank you for your suggestion.

**Comment by rainerfrey-inxmail** [comment]
Unfortunately I only found this ticket after the 3.3 release. Our reason for using `@RestControllerEndpoint` - and on a casual read this seems to have not come up in the discussion - is because we have several custom endpoints that require a JSON object with a couple of nested properties as input. These are actuator endpoints and not regular RestControllers as they serve operational purposes, are accessed on a separate management port and require our operational Basic auth whereas the application uses OAuth2 with a completely separate user base - configured conveniently with the EndpointRequest matchers. The approach to register a regular controller in the management context seems complicated and low-level in contrast, and make configuration and security configuration more complicated and less declarative. Removing this is a functional regression for us. Supporting POJO (and/or records) as input for `@WebEndpoint` would mitigate this for our use case.

**Comment by philwebb** [comment]
@rainerfrey-inxmail Are you able to share a sample application that shows one of your more complicated inputs? It doesn't need to be your production code, just something that gives us an idea of how you're currently using `@RestControllerEndpoint`. We can then consider how we might be able to evolve `@WebEndpoint`.

**Comment by lfvJonas** [comment]
@johanhaleby We are currently having the same issue did you get it to work using the '@ManagementContextConfiguration' method?

**Comment by johanhaleby** [comment]
@IfvJonas I haven't tried yet unfortunately.

**Comment by kschlesselmann** [comment]
@philwebb I second @rainerfrey-inxmail use case. We're synchronizing data between our environments and use actuator endpoints for that.

Right now we have an endpoint like
```kotlin
    @PostMapping
    fun synchronize(@RequestBody model: SynchronizationRequestModel): Mono<ResponseEntity<Void>> =
         …
```
which basically accepts a list of entities that should be synced. It seems that this is no longer possible with `@WebEndpoint` and `@WriteOperation`.

**Comment by chicobento** [comment]
> Unfortunately I only found this ticket after the 3.3 release. Our reason for using `@RestControllerEndpoint` - and on a casual read this seems to have not come up in the discussion - is because we have several custom endpoints that require a JSON object with a couple of nested properties as input. These are actuator endpoints and not regular RestControllers as they serve operational purposes, are accessed on a separate management port and require our operational Basic auth whereas the application uses OAuth2 with a completely separate user base - configured conveniently with the EndpointRequest matchers. The approach to register a regular controller in the management context seems complicated and low-level in contrast, and make configuration and security configuration more complicated and less declarative. Removing this is a functional regression for us. Supporting POJO (and/or records) as input for `@WebEndpoint` would mitigate this for our use case.

We have the same issue. 
Replacing `@WebEndpoint` with `@RestController ` as suggested by @wilkinsona does not work as it also stops the "fake actuator" endpoint from being discovered via the `/actuator` endpoint which we also use for auto-discover of our management interfaces (similar tool as Spring Admin).

> @rainerfrey-inxmail Are you able to share a sample application that shows one of your more complicated inputs? It doesn't need to be your production code, just something that gives us an idea of how you're currently using @RestControllerEndpoint. We can then consider how we might be able to evolve @WebEndpoint.

I can also help providing a minimal app for that but there's nothing fancy there, just:

```java
@RestControllerEndpoint (id = "customer")
@Component
public class CustomerEndpoint {

    @PostMapping ("/{id}")
    public Customer createCustomer(final @PathVariable (value = "id") Integer id, final @Valid @RequestBody Customer customer)
    {
    	return customer;
    }
    public static record Customer(String name, Address address){}
    
    public static record Address(String street){}
}
```
Now you can POST to /actuator/customer/1 with 
```json
{ "name": "cust", "address": {"street": "1"}}
```

And placing a get to /actuator, it returns:

```json
    "customer": {
      "href": "http://localhost:8081/actuator/customer",
      "templated": false
    }
```

There's a limitation where the `templated` will always be _false_ when using RestControllerEndpoint so auto discovery does not not work 100% semantically correct for those endpoints.

**Comment by kschlesselmann** [comment]
@philwebb Any news on this. This is a blocker on our side as well :-(

**Comment by rainerfrey-inxmail** [comment]
> @rainerfrey-inxmail Are you able to share a sample application that shows one of your more complicated inputs? 

Sorry I was otherwise engaged for a couple of weeks. Do you need a runnable application or is code of endpoint and request body sufficient?

**Comment by philwebb** [comment]
@kschlesselmann We've not had a chance to discuss it again yet, but the issue is flagged so we won't forget.

@rainerfrey-inxmail Ideally something that we can run so we can investigate alternative API ideas.

**Comment by gonmmarques** [comment]
Just commenting to follow on the topic, quite interested on the outputs of this.

**Comment by juliojgd** [comment]
@philwebb Maybe this issue should be re-opened to show that there is an active discussion (an a pending one as well)  here?

**Comment by wilkinsona** [comment]
Thanks for the suggestion. This issue was tracking the deprecation which has been done and shipped in 3.3.0-RC1. It doesn't make sense to have an open issue for work that has been completed so it won't be re-opened. Please rest assured that the feedback that people have provided is still very much on our radar and it will all be considered before anything is actually removed.

**Comment by wilkinsona** [comment]
> how are we going to create a custom actuator endpoint with context type as event-stream, since it is not working for both `@Endpoint` and `@WebEndpoint`?

We may consider it as a future enhancement to the `@WebEndpoint` support, but we'd need a compelling use case for event stream responses from Actuator. What's your need for it?

**Comment by talasila-sairam** [comment]
We were actually in the midst of constructing a custom actuator endpoint since we have many circuit breakers and we wanted to send our circuit breaker events to the developer management portal managing bby us. Although we can accomplish the same thing with a controller or rest controller, this isn't what I presume it's meant for. Given that this is management configuration data, it made sense to expose it on the actuator endpoint.

**Comment by johanhaleby** [comment]
We had the same use case as @talasila-sairam before when using Hystrix and Turbine.

**Comment by zxuanhong** [comment]
At present, we still need to pass the body parameter, but @WriteOperation does not support it. I don't know how to migrate either

**Comment by wilkinsona** [comment]
@zxuanhong can you please be more specific? A concrete example of what you're doing with `@RestControllerEndpoint`, as others have shared above, would be useful.

**Comment by spencergibb** [comment]
> We had a look before scheduling this, and it seems this endpoint would work well with @ReadOperation and @WriteOperation.

Can we do complex objects for `@WriteOperation`?

https://github.com/spring-cloud/spring-cloud-gateway/blob/62a13c31e30b7be414576763ceba8108c3cfeb7e/spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/actuate/AbstractGatewayControllerEndpoint.java#L238

![image](https://github.com/user-attachments/assets/6dd2694d-3c84-44c2-894f-765ebcdf9116)

**Comment by wilkinsona** [comment]
I suspect we may have overlooked the inherited post mappings. Apologies. `@WriteOperation` does not support complex objects at the moment so we'd need to address that to allow Gateway to move away from `@RestControllerEndpoint`.

**Comment by zxuanhong** [comment]
@wilkinsona For example, how to migrate @RestControlEndpoint to @WebEndpoint (we need to pass the body parameter)
```
@Component
@RestControllerEndpoint(id = "exporters")
public class ExportersEndpoint {

  @PostMapping(path = "/{exporterId}/enable")
  public CompletableFuture<ResponseEntity<?>> enableExporter(
      @RequestBody(required = false) final InitializationInfo initializeInfo) {
    ...
  }
}
```

**Comment by johanhaleby** [comment]
I also have an issue after upgrading from 3.3.6 to 3.4.0. I'm exposing a hal-browser from the management port in actuator like this:

![image](https://github.com/user-attachments/assets/ea0c4f9c-dce5-4fec-8b76-fad4ae56045d)


I have this endpoint:

```
@Component
@WebEndpoint(id = "hal-browser", enableByDefault = true)
class HalBrowserEndpoint {
    @Value("\${management.endpoints.web.base-path}")
    lateinit var managementPath: String

    @ReadOperation
    fun halBrowserEndpoint(request: ServerHttpRequest): Mono<ResponseEntity<Unit>> {
        val uri = request.baseUri + "$managementPath/browser/browser.html#${request.baseUri}$managementPath/api"
        return Mono.just(ResponseEntity.status(HttpStatus.MOVED_PERMANENTLY).header(HttpHeaders.LOCATION, uri).build())
    }
}
```

When clicking on the "hal-browser" link in 3.3.6 I'm redirected to the hal-browser as expected. However, in 3.4.0 I get this error:

```
{
"timestamp": "2024-12-19T14:27:18.874+00:00",
"requestId": "27a34263-24",
"message": "Missing parameters: request",
"status": 400,
"error": "Bad Request"
}
```

We have to revert to 3.3.6 because of this. The hal browser is really important for us when performing management tasks for our service.

**Comment by lenaschoenburg** [comment]
We also use `RestControllerEndpoint` for a management actuator. This actuator is part of our public API that we can't easily break.

https://github.com/camunda/camunda/blob/9328d9eaec774f5f077361074dbc830c2b854577/dist/src/main/java/io/camunda/zeebe/shared/management/ClusterEndpoint.java

**Comment by denniseffing** [comment]
Chaos Monkey for Spring Boot also uses complex objects in actuator endpoints via ´@RestControllerEndpoint` to configure application assaults. We are currently hesitant about migrating to `@WebEndpoint` because it does not allow complex types. All workarounds (like exposing a `@RestController` instead) induce too many other issues with management endpoint and security configuration for all our users. 

Details about our current actuator endpoints and what they are used for can be found in our documentation: [chaos-monkey-spring-boot/latest > Endpoints](https://codecentric.github.io/chaos-monkey-spring-boot/latest/#endpoints)

**Comment by bclozel** [comment]
We got consistent feedback here about binding complex types on custom actuator web endpoints. We also understand that some developers use the full potential and flexibility of MVC web endpoints.

I think that for the second point, we're not likely to walk back the deprecation notice we declared in 3.3.0. The flexibility and possibilities are just too broad and this currently prevents us from improving things in this part of Spring Boot. Maybe there is a way to solve the problem from the other end: offering a way to easily bind web endpoints on the actuator path, completely separate of the Actuator infrastructure? To be clear, I didn't explore this possibility myself yet.

Now the main point of my comment is the following: I have a draft change that could help with the binding of complex types on actuator web endpoints. I wrote a short section as reference documentation explaining how this would work:

![Image](https://github.com/user-attachments/assets/6b031bea-2924-4562-b46e-4d9dc13a013e)

If you are interested in this particular aspect, would this feature help with your use case and moving off of `@RestControllerEndpoint`? Please share any feedback here, or just a +1 on this comment if you're happy with this direction. If we get enough votes I'll bring that up with the team for further discussion.

Thanks!

**Comment by denniseffing** [comment]
@bclozel This would solve the issue regarding complex objects, thank you. 

However, it will not be possible to expose multiple nested paths via **one** actuator endpoint like we do now. We'd have to  configure multiple actuator endpoints (with their own ID respectively) instead. This would also mean that users who want to use these endpoints (or not use them) would have to change their configuration accordingly and enable/disable multiple actuator endpoints instead of just one.

Definitely an improvement to how it is not but still not ideal for our use case.

**Comment by bclozel** [comment]
@denniseffing I received additional feedback about this and yeah, complex nested objects with full deserialization support is the expectation here from developers. Unortunately deserialization already happened at that point in the actuator support.

I'll try and explore other solutions but so far they're all pointing to the fact that "full" MVC endpoints support is asking too much and prevents much needed improvements in this area.

**Comment by grgrzybek** [comment]
For the record, In Jolokia (jolokia/jolokia@690249013f414ad362d30e295550679347cc7a84) I moved from deprecated `org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar` to `@WebEndpoint` and `org.springframework.boot.web.servlet.ServletContextInitializer`

**Comment by bclozel** [comment]
Given the situation, we don't expect to remove support for `@RestControllerEndpoint` and others in Spring Boot 4.

Instead of expanding `@WebEndpoint` capabilities with more web-specific features (and potentially replicate an entire web framework!), I think we could consider a way to let developers expose functional web endpoints on the management port, since it seems to be the main reason for using actuator in those cases. This would give the full flexibility of the Spring functional web frameworks without the hassle of plugging those in a different application context and server port.

**Comment by wilkinsona** [comment]
I've opened #47313 to track providing the WebMvc.Fn and WebFlux.Fn-based alternatives.

**Comment by bhargavsai007** [comment]
Hi. May I know why we are moving to `@Endpoint` from `@RestControllerEndpoint` ? 
Because I am working on this migrating task and what I observed is even for simple CRUD operations it is creating unnecessary complexity especially due to multiple methods having same signature.

**Comment by bclozel** [comment]
@bhargavsai007 see https://github.com/spring-projects/spring-boot/issues/31768 for rationale. We will tackle #47313 before removing support
