### ISSUE TITLE
repo.spring.io/snapshot is down again

### ISSUE THREAD

**Issue by aurimasniekis** [spring-projects/spring-boot#31773]
Recently quite often the `repo.spring.io/snapshot` repository is going down with all snapshot dependencies being not available. I am not sure what's the deal with JFrog but it's breaking all our CI pipelines and developments. 

If the repository is so unstable would it be fine if we host a local mirror of the repository?

e.g. dependency:
* https://repo.spring.io/snapshot/org/springframework/boot/org.springframework.boot.gradle.plugin/3.0.0-SNAPSHOT/org.springframework.boot.gradle.plugin-3.0.0-SNAPSHOT.pom

**Comment by wilkinsona** [comment]
Sorry for the inconvenience. JFrog are aware of the problem. Please check @springops on Twitter for updates.

**Comment by aurimasniekis** [comment]
This already happened, a few times in the past couple of weeks, maybe some changes should be made because we can't use any of your repository packages when it goes down, and it's not really great when you can't build a project...

**Comment by wilkinsona** [comment]
We've asked JFrog to perform a post mortem so that we can understand why the problem occurred on 6 July and again today.

You've also raised this on [Gitter](https://gitter.im/spring-projects/spring-boot?at=62d44b099a314a3ec4a37602) and [Twitter](https://twitter.com/aurimasniekis/status/1548720698360733696). Taking that as an indication of how critical access to our snapshots and milestones is to your project, you're probably at the stage where, even without the recent outages, investing in your own mirror would be beneficial.

**Comment by aurimasniekis** [comment]
Thanks, @wilkinsona for the summary, yes this morning I did set up a mirror, as it was blocking our pipelines with these downtimes...
