### ISSUE TITLE
How can I use SpringBootTest fast to test 

### ISSUE THREAD

**Issue by zhengzhenning** [spring-projects/spring-boot#31940]
**Versions:**   v2.3.1.RELEASE

**Questions:**
When I run Test in my App,ex:

```
@SpringBootTest(classes = TerminalDataApplication.class)
@RunWith(SpringJUnit4ClassRunner.class)
public class CoordinateDownloadTest {
    @Test
    public void testOrganization() {
        List<District> allDistrictFormGaodeApi = this.getAllDistrictFormGaodeApi();
        System.err.println(allDistrictFormGaodeApi);
        List<OrganizationDTO> organizations = Lists.newArrayList();
        for (District district : allDistrictFormGaodeApi) {
            LoggerUtil.warn(LOGGER, "{}({}) 开始-------", district.getName(), district.getAdcode());
            OrganizationDTO.builder().organizationId(district.getAdcode()).organizationName(district.getName()).gmtCreate(new Date()).build();
            organizations.addAll(organizationBy(district));
            LoggerUtil.warn(LOGGER, "{}({}) 结束-------\n", district.getName(), district.getAdcode());
        }
        LoggerUtil.info(LOGGER, "[组织架构]累计构建:{}个", organizations.size());
    }
}
```
the app is  very slow build ,like this image:
<img width="687" alt="slow" src="https://user-images.githubusercontent.com/29723341/182112151-ecff4f7c-5a6c-48ed-9c64-4651b680497d.png">

I waitting for at least 5~6min when test my method

How I can use SpringBootTest faster In my App?

**Comment by bclozel** [comment]
I think this is related to your application's build, since your IDE is probably busy building the app and launching the tests. You should some more details in the "build" tab in your IDE. Maybe your build can be improved for caching? In any case, this looks like a question that belongs to StackOverflow, if you'd like more assistance.

I'm closing this issue, but we can reopen if you demonstrate that time is being spent in Spring Boot.
Thanks!
