### ISSUE TITLE
spring.groovy.template.configuration.* properties not recognized

### ISSUE THREAD

**Issue by dima767** [spring-projects/spring-boot#3198]
Boot `1.2.4`. Simple app:

```groovy
buildscript {
    ext {
        springBootVersion = '1.2.4.RELEASE'
    }
    repositories {
        jcenter()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("io.spring.gradle:dependency-management-plugin:0.5.1.RELEASE")
    }
}

apply plugin: 'groovy'
apply plugin: 'spring-boot'
apply plugin: 'io.spring.dependency-management'

jar {
    baseName = 'cas-overlay-initializr'
    version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    jcenter()
}


dependencies {
    compile("org.springframework.boot:spring-boot-starter-groovy-templates")
    compile("org.springframework.boot:spring-boot-starter-thymeleaf")
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.codehaus.groovy:groovy")
    testCompile("org.springframework.boot:spring-boot-starter-test")
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.4'
}
```

and `application.properties`

`spring.groovy.template.configuration.use-double-quotes=true`

explodes with this:

```java
Caused by: org.springframework.beans.NotReadablePropertyException: Invalid property 'configuration[use-double-quotes]' of bean class [org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateProperties]: Bean property 'configuration[use-double-quotes]' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
	at org.springframework.beans.BeanWrapperImpl.getPropertyValue(BeanWrapperImpl.java:731)
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:948)
	... 70 common frames omitted
```

according to this bean in `GroovyTemplateAutoConfiguration`:

```java
@Bean
		@ConditionalOnMissingBean(GroovyMarkupConfig.class)
		@ConfigurationProperties(prefix = "spring.groovy.template.configuration")
		public GroovyMarkupConfigurer groovyMarkupConfigurer() {
			GroovyMarkupConfigurer configurer = new GroovyMarkupConfigurer();
			configurer.setResourceLoaderPath(this.properties.getPrefix());
			configurer.setCacheTemplates(this.properties.isCache());
			if (this.templateEngine != null) {
				configurer.setTemplateEngine(this.templateEngine);
			}
			return configurer;
		}
```

it is supposed to work.

**Comment by snicoll** [comment]
See #2840 for a rationale. 

Please don't use our namespace in your own code. `spring.groovy.template` is already managed by `GroovyTemplateProperties` so any attempt to bind to a child of that will fail because it will try to bind to it (instead of your class). 

Just use a namespace of yours for your own customizations. Thanks.

**Comment by dima767** [comment]
Can you please provide an example. In earlier versions I was able to use these props:

```yaml
spring.groovy.template:
  cache: false
  configuration:
    autoIndent: true
    autoNewLine: true
    useDoubleQuotes: true
```

How can I use those in this version?

**Comment by snicoll** [comment]
Oh. That's awkward. Looks like it's not dead code *after all*. Let me reopen #2840.

**Comment by snicoll** [comment]
@wilkinsona that `configuration` map is indeed dead code but it's being used by the auto-config so I guess  the only way we have to fix this is to ignore unknown fields on the auto-config. 

Thoughts?

**Comment by wilkinsona** [comment]
Gross. Rather than ignoring all unknown fields, I'd be tempted to revert https://github.com/spring-projects/spring-boot/commit/326bdf29c23f29562c6b4dca6d8b5530b605fea7 in 1.2.x and then consider a different fix for 1.3. 

For 1.3, I think we should remove the clash by reworking the keys to that two classes aren't trying to share the same configuration namespace.

**Comment by snicoll** [comment]
The problem is that the fix is not only about leaving an unused map but having two IDs pointing to two different types. If we revert `spring.groovy.template.configuration` points to both a `Map` (that is _anything_) and well-known object. We can't really do that either.

I'd really go for the `ignoreUnknownFields` route and like you said revisit this code in 1.3.

**Comment by wilkinsona** [comment]
Agreed, I'd overlooked the problems it'll cause the IDE support if we just revert the change.

**Comment by snicoll** [comment]
@dima767 apologizes for the confusion!

**Comment by dima767** [comment]
Thank you guys!
