### ISSUE TITLE
How to turn off the use of log back

### ISSUE THREAD

**Issue by Xzhengkai** [spring-projects/spring-boot#32091]
It is often not necessary to use logback printing during dev development. How to turn off logback printing logs while in dev environment.
Turn on log back log printing in production environment.
![image](https://user-images.githubusercontent.com/50131687/184828512-53e7e597-7969-4a2d-b348-b6744afce3ba.png)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Xzhengkai** [comment]
Hello, how to solve it?

**Comment by snicoll** [comment]
@Xzhengkai please ask your question on StackOverflow.

**Comment by Xzhengkai** [comment]
Okay, thanks.

**Comment by philwebb** [comment]
For reference this the stackoverflow.com question is at https://stackoverflow.com/questions/73370970/spring-boot-how-to-turn-off-the-use-of-log-back
