### ISSUE TITLE
Embedded Tomcat does not honor ServletContainerInitializers

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-boot#321]
Currently, the embedded Tomcat container does not detect and execute `ServletContainerInitializers`.  This means that dependencies that use them are never called and therefore are unable to contribute to the running application.

The embedded Tomcat container should be enhanced such that it properly notices the `ServletContainerInitializers` on the Application's classpath and executes them.

**Comment by felixbarny** [comment]
@philwebb could you be a bit more explicit what lead you to this design decision? What's problematic about the search algorithm? Where in the boot source code do you disable that feature? Why wouldn't you want the `ServletContainerInitializer` to be executed when you run `java -jar`? Would you consider supporting `ServletContainerInitializer` if some of the issues with it could be resolved? 

Also it's not magical to execute all `ServletContainerInitializer`s. `java.util.ServiceLoader.load(javax.servlet.ServletContainerInitializer)` should do the trick as all implementations of that interface have to be listed in `/META-INF/services/javax.servlet.ServletContainerInitializer`.

Servlet 3.0 made a really good job at defining this interface and the `@Web*` annotations as it makes it possible to write modular extensions to web applications (like [stagemonitor](http://www.github.com/stagemonitor/stagemonitor)) that just have to be on the classpath to be active and that are completely technology agnostic. It's really a pity that boot beaks the spec multiple times (neither `ServletContainerInitializer` nor `@Web*` annotations are supported) which makes these mechanisms useless because they don't work with boot, which is a (btw great) technology that just can't be ignored.

The goal of these servlet 3.0 mechanisms is to enable integration of standardized components without the user having to explicitly configure something. It's sad that boot makes that impossible :(

**Comment by felixbarny** [comment]
friendly ping :wink:

**Comment by dsyer** [comment]
Equally friendly reminder that nothing has changed :-).

**Comment by felixbarny** [comment]
I just want to know more about the reasons about this decision and wether you might overthink it. Did you read my comment from 8 days ago? It would be great if you could answer my questions.

**Comment by dsyer** [comment]
There are lifecycle issues. The servlet context is not available when it is needed from what I remember. I'd be happy to be proved wrong, so please feel free to try it and report back.

**Comment by felixbarny** [comment]
Have you considered using `org.apache.catalina.startup.ContextConfig` as a `LifecycleListener` in `org.springframework.boot.autoconfigure.websocket.TomcatWebSocketContainerCustomizer`? In `ContextConfig#processServletContainerInitializers` there is a `ServiceLoader` that loads all `ServletContainerInitializer`s.

This is my quick and dirty try:

	@Override
	public void customize(ConfigurableEmbeddedServletContainer container) {
		final TomcatEmbeddedServletContainerFactory tomcatContainer = (TomcatEmbeddedServletContainerFactory) container;
		tomcatContainer.addContextLifecycleListeners(new ContextConfig());
	}

Is that a route you are willing to go? Would you consider using ContextConfig as a default `LifecycleListener`?

**Comment by dsyer** [comment]
What does it have to do with web sockets (other than the fact that Tomcat packages its ws support as an SCI)? Isn't that the wrong place to put a customizer? Anyway, I wouldn't rule anything out, but I suspect you will have issues with some SCIs (in particular the one in Spring). Did you try it?

**Comment by felixbarny** [comment]
I'm sorry, I ment `org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory`.
I've tried with spring-boot-sample-web-ui. It's starting and working without problems so far.

**Comment by dsyer** [comment]
Try all the samples, and also try deploying a war file to an existing container. That should shake anything loose that we missed so far.

Of course this is only the Tomcat support and we'd probably have to find a way to do the same with the other platforms, but it's a start if it works.

**Comment by felixbarny** [comment]
Is a way to do a automated integration test for the samples?

**Comment by dsyer** [comment]
Not with a war deployment (as far as I know). But "mvn test" is a good start.

**Comment by felixbarny** [comment]
The spring-boot-samples tests are passing. Deploying the spring-boot-sample-web-jsp war to tomcat did also work. But the tests in `org.springframework.boot.autoconfigure.security.oauth2.SpringSecurityOAuth2AutoConfigurationTests`are failing with the following exception:

```
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:917)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	... 6 more
Caused by: java.lang.IllegalStateException: No SpringApplication sources have been defined. Either override the configure method or add an @Configuration annotation
	at org.springframework.util.Assert.state(Assert.java:392)
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:103)
	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:68)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5156)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more
```

The Javadoc of `SpringBootServletInitializer` states:

```
Note that a WebApplicationInitializer is only needed if you are building a war file and
deploying it. If you prefer to run an embedded container then you won't need this at
all.
```

So we probably have to find a way how to not invoke `SpringBootServletInitializer` in case of a java -jar deployment. Do you have an idea how to do that?
