### ISSUE TITLE
spring boot 2.7.3 - r2dbc-pool

### ISSUE THREAD

**Issue by CallMeSweets** [spring-projects/spring-boot#32148]
Hi,
In spring boot 2.7.3 there is used an r2dbc dependency:
"io.r2dbc:r2dbc-pool:0.9.0" or "io.r2dbc:r2dbc-pool:0.9.1" I don't remember right now. But the problem is that in one of this version is memory leak which was fixed in "1.0.0-RC1". The information might be checked in changelog here: https://github.com/r2dbc/r2dbc-pool/blob/main/CHANGELOG.

Maybe it is a good idea to upgrade r2dbc-pool version to 1.0.0-RC1?

Thanks for response

**Comment by snicoll** [comment]
@CallMeSweets we can't upgrade to a non GA version of a dependency in a GA version of Spring Boot. Our upgrade policy is [available on the wiki](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#third-party-dependencies).

It looks like the leak you mentioned may have been fixed in `0.9.1`. When the R2DBC project releases a new service release for Borca we'll upgrade to it.

**Comment by mp911de** [comment]
You can track the release of Borca-SR2 at https://github.com/r2dbc/r2dbc-bom/issues/61
