### ISSUE TITLE
Clarify table that shows how logging properties are transferred to system properties

### ISSUE THREAD

**Issue by fjakop** [spring-projects/spring-boot#32160]
spring-boot 2.7.2

As stated in the docs at https://docs.spring.io/spring-boot/docs/2.7.2/reference/html/features.html#features.logging.file-rotation the log file rotates on a per day basis and when it reaches 10MB.

This is working fine when configured in application.yaml

```
logging:
  file:
    name: my/path/application.log
```

However this feature stops working when the log file is configured by the environment variable `LOG_FILE`
```
LOG_FILE=my/path/application.log
```

We would expect the same (rotation) behaviour in both cases since the environment variable is the yaml equivalent according to https://docs.spring.io/spring-boot/docs/2.7.2/reference/html/features.html#features.logging.custom-log-configuration.

**Comment by quaff** [comment]
Are you missing `_NAME` suffix?

**Comment by snicoll** [comment]
That looks like an oversight in the documentation to me. Can you try with `LOG_FILE_NAME` as @quaff suggests?

**Comment by philwebb** [comment]
I think the documentation might be a little confusing in this area. The `logging.file.name` property is transferred to a system property named `LOG_FILE` so that it can be referenced in logging configuration files (e.g. `logback.xml`). You can find the code in the [`LogFile` class](https://github.com/spring-projects/spring-boot/blob/b2be1939085903c872d25926b2b595a9a121c746/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/LogFile.java#L90).

It looks like the transfer happens regardless of any existing system property.

You could try setting a `LOGGING_FILE_NAME` environment variable. I think that will map to `logging.file.name` and then get transferred to `LOG_FILE` and be picked up by Logback/Log4j.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by fjakop** [comment]
Thanks for the input, I verified the suggested solution using `LOGGING_FILE_NAME`, this works and is fine for me.

**Comment by wilkinsona** [comment]
Let's see if we can clarify [the documentation](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/features.html#features.logging.custom-log-configuration). The table shows how properties in the Spring environment are transferred to system properties but, judging by this issue, it's easy to misinterpret the "System Property" column as environment variables as they're in `UPPER_CASE`.

**Comment by vivganes** [comment]
I am willing to take this and work on it.  Given that there is a confusion between System property and the Environment variables, would it be good if i add a column with title Environment variable and write the env variables that need to be set for each property in the table?

**Comment by wilkinsona** [comment]
Thanks for the offer, @vivganes. I'm not really sure how best to fix this. Unfortunately, I don't think another column will help overall. Due to the limited width in the documentation, I think an extra column will make the table harder to read.
