### ISSUE TITLE
Support Mockito with @MockBean and @SpyBean in AOT-processed tests

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#32195]
Currently Mockito doesn't work with native tests. See https://github.com/spring-projects-experimental/spring-native/issues/1561 and https://github.com/spring-projects-experimental/spring-native/issues/1063 for more details.

For now, we can disable the `ResetMocksTestExecutionListener`, but it would be nice if we could make Mockito work.

**Comment by sdeleuze** [comment]
FYI there is ongoing work on GraalVM side to make it work, I will try to share up to date news about current status.

**Comment by mhalbritter** [comment]
There's more than just GraalVM supporting this. Currently, using `@MockBean` wreaks havoc even when not using native-image, just enabling AOT mode is enough.

**Comment by mhalbritter** [comment]
We have a smoke test which uses `@MockBean` here: https://github.com/spring-projects/spring-aot-smoke-tests/tree/main/boot/boot-tcf

**Comment by mhalbritter** [comment]
I've [added metadata for Mockito 4.8.1](https://github.com/oracle/graalvm-reachability-metadata/pull/141) to the reachability-metadata repository. However I found no way to get the class mocks from Mockito working, as they all rely on creating classes at runtime. But it works when using the `ProxyMockMaker`, which is able to mock interfaces.

**Comment by sdeleuze** [comment]
Various users (example [here](https://github.com/spring-projects/spring-framework/issues/31705#issuecomment-1837159628)) seems confused about seeing their unit tests broken when using just the AOT plugin, without using GraalVM native images support.

My proposal would either to:
- Update the title of this issue in order to focus on the fact that Mockito support is broken at AOT level as mentioned by @mhalbritter [here](https://github.com/spring-projects/spring-boot/issues/32195#issuecomment-1327403502) and @wilkinsona [here](https://github.com/spring-projects/spring-framework/issues/31705#issuecomment-1829784508).
- Create a different issue focused on the broken AOT support for `@MockBean` and `@SpyBean`.

Since I am not sure we should do something specific for Mockito on native side (should be handled on GraalVM side), I would maybe favor turning this issue into fixing the AOT support, and see later if a dedicated native issue is needed, but of course up to the Boot team to decide.

**Comment by wilkinsona** [comment]
Thanks, @sdeleuze. I've updated the issue's title to focus on the AOT side of things. Once that has been addressed we can consider what's left for general native support of Mockito.

**Comment by wilkinsona** [comment]
@eiswind That's a known issue in Spring Framework: https://github.com/spring-projects/spring-framework/issues/31705

**Comment by eiswind** [comment]
@wilkinsona As always: Thanks for pointing me there.

**Comment by wilkinsona** [comment]
@bloczel another one for Framework please to consider as an enhancement (if it's not already supported) to `@MockitoBean` and `@MockitoSpyBean`.

**Comment by sbrannen** [comment]
I think this issue can be closed as superseded by:

- https://github.com/spring-projects/spring-framework/issues/32925
- https://github.com/spring-projects/spring-framework/issues/32932

**Comment by wilkinsona** [comment]
Thanks, @sbrannen.

**Comment by sbrannen** [comment]
For anyone interested in this issue, please note that Spring Framework 6.2 will support the use of `@TestBean` and `@MockitoBean` in both AOT mode and within a native image. `@MockitoSpyBean` is also supported in AOT mode but not currently within a native image.

- See https://github.com/spring-projects/spring-framework/issues/32933

However, as stated in the [commit](https://github.com/spring-projects/spring-framework/commit/e1c450d253c5b957e918495d39655dc0f68d5bee), `@⁠MockitoBean` has currently only been tested in a
GraalVM native image when mocking interfaces and using Mockito's `ProxyMockMaker`, along with a custom runtime hints.
