### ISSUE TITLE
"commons-io"-dependency is missing in spring-boot-dependencies (2021.0.4)

### ISSUE THREAD

**Issue by maxl2287** [spring-projects/spring-boot#32256]
Hi,

I am currently using Spring boot 2.7.3.
I tried to upgrade from spring cloud dependencies  2021.0.3 to **2021.0.4**.

After this upgrade the commons-io dependency seems to be removed. 

The import of IOUtils fails cause "io"-dir is not found.
`import org.apache.commons.io.IOUtils;`

I have to seperately install the commons-io by myself:

<dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.11.0</version>
 </dependency>

This was working with 2021.0.3

KR
Max

**Comment by wilkinsona** [comment]
Spring Cloud is managed as a number of separate projects in the https://github.com/spring-cloud organization on GitHub. You should use your build system (Maven's dependency:tree or Gradle's dependencyInsight) to determine why commons-io was on the classpath when using Spring cloud 2021.0.3 and why it's no longer there when using 2021.0.4. It may due to change in Spring Cloud itself or one of its dependencies.
