### ISSUE TITLE
Provide `shared` property for `EhCacheManager` in EhCache auto-configuration

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#3229]
It would be good to provide `shared` property for `EhCacheManager` as follows:

https://github.com/spring-projects/spring-framework/blob/master/spring-context-support/src/main/java/org/springframework/cache/ehcache/EhCacheManagerFactoryBean.java#L122

**Comment by snicoll** [comment]
I am not so sure about that. Currently, the cache manager is closed on shutdown of the app. Providing a `shared` option would obviously break that.

**Comment by izeye** [comment]
@snicoll Actually I'm not using shared `EhCacheManager`.

I'm abusing it for integration tests to avoid the following exception:

```
Caused by: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: DefaultConfigurationSource [ ehcache.xml or ehcache-failsafe.xml ]
	at net.sf.ehcache.CacheManager.assertNoCacheManagerExistsWithSameName(CacheManager.java:628)
	at net.sf.ehcache.CacheManager.init(CacheManager.java:392)
	at net.sf.ehcache.CacheManager.<init>(CacheManager.java:270)
	at org.springframework.cache.ehcache.EhCacheManagerUtils.buildCacheManager(EhCacheManagerUtils.java:54)
	at org.springframework.boot.autoconfigure.cache.EhCacheCacheConfiguration.ehCacheCacheManager(EhCacheCacheConfiguration.java:63)
...
```

This is a sample reproducing the problem:

https://github.com/izeye/samples-spring-boot-branches/tree/cache-with-profile-test

You can reproduce by running `samples.springboot.IntegrationTests`.

I'm not sure there's any better alternative to avoid this.

**Comment by snicoll** [comment]
You're not closing the context as you should for some reason. Or you have two set of test configurations so when the second one start, the first one is still active (with the cache manager) and that leads to the failure. I can see why it would be useful for testing purpose though. It's a tough call.

**Comment by izeye** [comment]
@snicoll Sorry for my ignorance.

Closing contexts looks a right answer I'm looking for.

This issue can be closed

as my needs satisfied and it looks violating the philosophy of the cache auto-configuration.

**Comment by snicoll** [comment]
Don't say that ;-)

I think you have a valid case "somehow" still. In a single project, you may have several testing configurations (test classes annotated with `@SpringApplicationConfiguration` or `@ContextConfiguration` and different values for them). Since the test context framework is caching those, you may actually face this issue. 

The "proper" way so far would be to use  `@DirtiesContext` to make sure that the test context framework shuts down stuff that live _outside_ of the application context.

I am closing this one because I think there is yet another way to solve this issue. You can always disable the cache (`spring.cache.type=none`) or use a simple implementation (`spring.cache.type=simple`) so that you're not affected by the single EhCache JVM instance.

My preference would be to disable or use a simple implementation in tests (you don't need ehcache to run for those, right?)

**Comment by izeye** [comment]
@snicoll Thanks for the additional tips! It's better-suited for my case :+1:
