### ISSUE TITLE
sprinboot项目开启，mysql8.0.21连接报错

### ISSUE THREAD

**Issue by tanyixiao** [spring-projects/spring-boot#32497]
2022-09-26 16:56:03.487 ERROR 22504 --- [reate-173516428] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.244.131:3306/myblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false, errorCode 0, state 08S01

com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

why?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by tanyixiao** [comment]
有解决办法吗？

**Comment by wilkinsona** [comment]
@tanyixiao As Brian said, please ask on Stack Overflow. Searching for the MySQL error message will also help you to find a solution.
