### ISSUE TITLE
inject not work in customize auto configure for mybatis 

### ISSUE THREAD

**Issue by wcong** [spring-projects/spring-boot#3256]
Hello,I found inject not work in my Configuration class

I wrote a class named **MybatisAutoConfiguration** to load properties and define bean of mybatis.

In this class,I injected **DataSource** and  **MybatisProperties**,but I got null when I use them to set  properties for mybatis bean.

I think it has something to do with implement of mybatis spring bean

### environment
spring-boot 1.2.3.release
mybatis-spring 1.2.2

### my github repository
[spring-boot-mybatis](https://github.com/wcong/spring-boot-mybatis)

### source code

``` java
@Configuration
@ConditionalOnClass({MapperScannerConfigurer.class, SqlSessionFactoryBean.class})
@EnableConfigurationProperties(MybatisAutoConfiguration.MybatisProperties.class)
public class MybatisAutoConfiguration {

    @Inject
    private DataSource dataSource;

    @Inject
    private MybatisProperties mybatisProperties;

    @Bean
    public SqlSessionFactoryBean makeSqlSessionFactoryBean() throws SQLException {
        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(dataSource);
        return sqlSessionFactoryBean;
    }

    @Bean
    public MapperScannerConfigurer makeMapperScannerConfigurer() {
        MapperScannerConfigurer mapperScannerConfigurer = new MapperScannerConfigurer();
        mapperScannerConfigurer.setBasePackage(mybatisProperties.getBasePackage());
        return mapperScannerConfigurer;
    }

    @ConfigurationProperties("spring.mybatis")
    @Data
    public static class MybatisProperties {
        private String basePackage;
    }
}
```

**Comment by snicoll** [comment]
plenty of things:

* Your auto-configuration class isn't an auto-configuration because it's not registered in `META-INF/spring.factories`
* Said auto-configuration is located in a child package of your application so it's actually being scanner as a "user configuration" (which is not supposed to be)
* You inject the `DataSource` using field injection which requires the context to initialize stuff super early. Yet you had no `@AutoconfigureAfter(DataSourceAutoConfiguration.class)`

In any case, there is a [spring boot auto-configuration for mybatis](https://github.com/mybatis/mybatis-spring-boot) now so I'd suggest to use that. As for other usage questions, please go on stackoverflow. Thanks!
