### ISSUE TITLE
Update docs to final GraalVM 22.3

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#32813]
The `:liberica-nik-download:` in `attributes.adoc` still points to the 22-EA release, and theres

```
NOTE: If you download it manually, make sure to download the NIK 22-EA version, which is based on GraalVM 22.3.
```

in `developing-your-first-application.adoc` which should be removed after GraalVM 22.3 is released.

Please also double-check the SDKman identifier.

**Comment by maciejwalkowiak** [comment]
@mhalbritter SDKMan instructions still reference wrong identifier: `sdk install java 22.3.r17-nik`, while the correct one is `sdk install java 22.3.r17.ea-nik`

**Comment by eddumelendez** [comment]
I think it was on purpose because sdkman doesn't publish Early Access binaries for GraalVM or Liberica NIK and the release for those are next week. Mentioning 22.3 is more like a further reference. But, I could be wrong 😅

With the release happening next week the sdkman identifier looks good but as mentioned need to be double check. 

sdkman published the EA to help developers test Spring Boot 3. If there is a similar scenario in the future please don't heasitate reaching out. I've been managing the java candidates for sdkman so happy to help 🙂

**Comment by mhalbritter** [comment]
@eddumelendez is correct. When I wrote that part of the doc, there was no 22.3 candidate available on SDKman and i guessed the identifier :)

https://github.com/spring-projects/spring-boot/issues/32813#issuecomment-1287914988 contains the correct identifier, thanks for that @maciejwalkowiak !
