### ISSUE TITLE
jackson-datatype-jsr310 not loaded on Auto Configured ObjectMapper when Jackson2ObjectMapperBuilderCustomizer is loaded

### ISSUE THREAD

**Issue by ffroliva** [spring-projects/spring-boot#32845]
Hi,

I have this simple project with:

```java
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
</dependency>
```

I am trying to make `LocalDateTime` to be written in ISO format.

I tried to add `spring.jackson.serialization.write-dates-as-timestamps=false`

but it made no difference.

Looking at `Jackson2ObjectMapperBuilderCustomizer` o noticed that `JavaTimeModule` was not loaded.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/25033371/197296086-a2cc5d7c-1f85-40e3-805a-a200c14c55d7.png">

What am I missing?

As reference here is a simple project.

https://github.com/ffroliva/jackson-load-modules-issue

**Comment by wilkinsona** [comment]
> Looking at Jackson2ObjectMapperBuilderCustomizer I noticed that JavaTimeModule was not loaded

The modules are not loaded until the ObjectMapper has been created by the builder and [is being configured](https://github.com/spring-projects/spring-framework/blob/9410998897edf558a8708d46ce29ee0db546be7c/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L718).

`LocalDateTimeControllerRestTemplateIntegrationTest` is failing because you are creating your own `TestRestTemplate` builder rather than injecting it. This means that it is using Jackson in its default configuration. If you `@Autowired` `TestRestTemplate` into your test, it will be preconfigured to use the auto-configured `ObjectMapper` with the `JavaTimeModule` registered.

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/main/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
