### ISSUE TITLE
How / Can add supoort buildtype/productflavor like Android Project  ?

### ISSUE THREAD

**Issue by CMingTseng** [spring-projects/spring-boot#32874]
Dear Sir

i am a Android Dev. 

now i try to use Spring to do backend .

at Android (application or library type), we can set  buildtype (debug /release ) &  flavor (dev/stage/prod)  at build.gradle 

how set those at spring ? 

i ref gradle doc https://docs.gradle.org/current/userguide/variant_model.html & stackoverflow 

maybe use "gradle variant" ?

so i create a demo  https://github.com/CMingTseng/variant-demo/blob/master/app/build.gradle 

it can not work  !!

https://discuss.gradle.org/t/how-use-set-variant-at-pur-java-springboot-kotlin-project/44096  

the gradle RD say  : variant is for library type 

so i look the project  https://github.com/mswokk/gradle-java-flavours 

it only for  java project  

if i want  "bootjar / bootXXXjar/..." the plugin can not work  <--lost some class

so can let  spring-boot plugin official support buildtype/productflavor ?

THX

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
