### ISSUE TITLE
Spring Boot Actuator does not show http.server.requests in metrics endpoint

### ISSUE THREAD

**Issue by romil-patel-integrella** [spring-projects/spring-boot#32991]
I do have a spring boot project developed using Java 11 in which I am adding the spring boot actuator to use the metrics endpoint to analyze the API response time and codes. I have added the following in pom.xml and in the application.properties file. First I do hit the REST APIs that I have developed which return the required response and when I do check metrics using `http://localhost:8080/metrics` I cannot find http.server.requests in response.  

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.6</version>
		<relativePath/> 
	</parent>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-actuator</artifactId>
	</dependency>

    # Spring Boot Actuator Configurations
    management.endpoints.web.base-path=
    management.endpoint.health.show-details=ALWAYS
    management.endpoints.web.path-mapping.health=/healthcheck
    management.endpoint.metrics.enabled = true
    management.endpoints.web.exposure.include = *

**Comment by wilkinsona** [comment]
Can you please try with 2.6.13, the latest Spring Boot 2.6.x release? If the problem remains and you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by bclozel** [comment]
I think this is a configuration issue.

Your config is auto wiring your filter instance and a filter registration bean instance. That filter registration bean could be the one that registers the filter for metrics instrumentation. This means this registration now registers your filter instead of the metrics one. More, since your filter is already declared as a bean as well, this might mean that the authentication filter is registered three times.

I think you will need to rewrite that configuration and make sure that you're instantiating the authentication filter and the registration within the bean method and only contributing your own registration as a bean. You'll find more information here: https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.servlet.embedded-container.servlets-filters-listeners.beans

Thanks!
