### ISSUE TITLE
Multiple Spring boot apps sharing classpath / class-loader.

### ISSUE THREAD

**Issue by flozano** [spring-projects/spring-boot#3300]
I am looking at how to migrate my current setup to Spring boot and I am blocked by this.

In my current setup, I have several micro service apps. During integration tests, these services share the same class-loader, as I bring them up inside tests.

Pseudocode:
```java
public class MyTest {

	Service1 s1;
	Service2 s2;

	@Before
	public void setUp() {
		s1 = new Service1();
		s2 = new Service2(s1);
	}

	@Test
	public void test1() {
		on(s2).get("/something");
		verify(s1).received("/somethingElse");
	}
}
```

AFAIK Spring boot discovers everything from classpath, therefore having multiple spring boot apps up and running inside same class-loader would therefore be very conflictive. Is there any way to prevent them from colliding or loading the wrong configurations?

BTW I asked this to @joshlong during Spring I/O 15, but I'm not sure I explained properly...

**Comment by snicoll** [comment]
Well, I do think that having several (separated) micro-services within the same project _is_ confusing. If they have different configuration, how do you load it? Let's say you use `spring.config.name` to specify the name of the configuration (`app1.properties`, `app2.properties` instead of the default `application.properties`). This is a process wide setting so you can't change that using a single process.

If you have the same configuration file, my best guess is that you're trying to migrate a set of services to micro-services but you've not done the fully cycle yet. IMO you should have on Spring Boot app with the relevant component scanning to make that working. Ideally a root package that sits on top of `app1`, `app2` and the like.

**Comment by flozano** [comment]
I should have explained better. My current setup involves NO spring boot, so I'm not using any of the current facilities (eg: there's no overriding of "spring.config.name" in my setup).


My setup predates spring boot, and all the facilities for configuration and embedded jetty and such are custom-developed. I want to move them to spring boot and stop maintaining my own, and I found this blocker (for me) during the evaluation to do so.

Each service is on its own project, of course. There's however another project that depends (as in gradle-level dependency) on them and brings them up and down as needed, *for integration testing*. But the projects are independent.

Each micro-service loads only their own namespaced properties. Eg:

in service1's config.properties:
```
service1.jdbc.url=xxx
service1.jdbc.username=yyy
```
in service2's config.properties:
```
service2.jdbc.url=xyz
service.jdbc.username=abcd
```

**Comment by snicoll** [comment]
You wrote a request in the Spring Boot issue tracker so you must be using Spring Boot in one way or the other, right?  :) Seriously, I don't understand what you're trying to do (if you're not using Spring Boot, then we shouldn't discuss here. If you tried to use it and it failed, then you're using it). I am confused.

Let's put the confusion aside, there is no way right now to start several Spring Boot application in the same process for the exact reason I mentioned above. 

I think we could summarize your problem by: I have X  `@SpringBootApplication` annotated  classes on my classpath (X,Y,Z), I start one (X) and component scanning is actually adding others (Y, Z). What's the issue you're seeing?

**Comment by flozano** [comment]
I understand this is not possible in Spring boot right now, so please deal with this issue as a feature request ("run several springboot apps in same JVM").

I wrote it in spring boot because, as I said, I'm trying to move my setup to Spring boot and the exact fact that you pointed out (`Let's put the confusion aside, there is no way right now to start several Spring Boot application in the same process for the exact reason I mentioned above.`) is what's blocking me from moving my setup to spring boot..

During integration test, for my setup to work, X Y and Z actually *are* in the same process, it's not only that X, Y Z are in the classpath, they're in same JVM. This only happens during integration test, which is handled by a project different from X, Y and Z, one that imports all of them and instantiates their main classes as needed.

**Comment by wilkinsona** [comment]
You can run several Spring Boot apps in the same JVM today. That's exactly what happens if you package you apps as war files and deploy them to a servlet container. This works very well as the servlet container uses a separate class loader for each application. This means that each application can only see the dependencies that it needs, and Spring Boot's auto-configuration will configure the right things for you.

I think you have a couple of options:

 - Use a single class loader, but turn off some or all of Boot's auto-configuration. You could either not use `@EnableAutoConfiguration` entirely, or you could use it with the required excludes to ensure that each application is only auto-configured as required.
 - Use one class loader for each application. You could also use a shared parent class loader that contains all of the applications' common dependencies to minimise the memory footprint.

**Comment by flozano** [comment]
Thank you @wilkinsona. I will give it a try again with these hints. Thanks @snicoll also for the time taken to look at the issue.

**Comment by daikaixian** [comment]
can this feature("run several springboot apps in same JVM") be supported now?
I want to replace  the rpc between two microservice as direct call.

**Comment by wilkinsona** [comment]
It's already supported. Please read my [comment above](https://github.com/spring-projects/spring-boot/issues/3300#issuecomment-114048652).

**Comment by flozano** [comment]
It's supported but it was really painful, having to use separate class-loaders and replicate the current assignation configurationArtifact->service (this class contains configuration that I want to load in this service) at the class-loader level (this jar is allowed for this service, this jar is not).

This solution was therefore not suitable for me, but I understand this is consequence of the core design of spring boot, and nothing can be done easily.

I want to revisit this when Java 9 is available, maybe easier with jigsaw.

**Comment by wilkinsona** [comment]
> This solution was therefore not suitable for me, but I understand this is consequence of the core design of spring boot, and nothing can be done easily.

I disagree quite strongly with that. There's nothing about the core design of Spring Boot that stops you from deploying multiple applications in the same JVM. As I said above, that's _exactly_ what happens when you deploy multiple war files that use Spring Boot to a servlet container.

If you specifically want to use the exact same class loader with multiple applications then, yes, that will be difficult. However, I don't think it makes sense to do so. An application is intended to be an isolated unit and sharing a ClassLoader breaks that isolation. Irrespective of the use of Spring Boot, breaking that isolation can lead to class path conflicts.

This is a standard modularity problem on the JVM. The tried and tested solution to that problem is to use separate class loaders. Here's a basic example of how that might look for four Boot apps:

```java
public class MultipleApps {

	public static void main(String[] args) throws Exception {
		launchApp(new File("app1.jar"));
		launchApp(new File("app2.jar"));
		launchApp(new File("app3.jar"));
		launchApp(new File("app4.jar"));
	}

	private static void launchApp(File fatJar, String... args) throws Exception {
		ClassLoader classLoader = new URLClassLoader(new URL[] {fatJar.toURI().toURL()});
		Class<?> mainClass = classLoader.loadClass(getMainClassName(fatJar));
		Method mainMethod = mainClass.getMethod("main", String[].class);
		mainMethod.invoke(null, new Object[] {args});
	}

	private static String getMainClassName(File fatJar) throws IOException {
		try (JarFile jarFile = new JarFile(fatJar)) {
			return jarFile.getManifest().getMainAttributes().getValue(Attributes.Name.MAIN_CLASS);
		}
	}

}
```

**Comment by flozano** [comment]
I was not saying the solution is not good, I just said it was not suitable for me in the specific case I'm handling now: I just happen to have a legacy codebase that is not easy to translate to spring boot because spring boots relies on classpath whereas my legacy stuff relies on explicit inclusion of configuration artifacts and ignored the shared classpath problem. 

> If you specifically want to use the exact same class loader with multiple applications then, yes, that will be difficult. However, I don't think it makes sense to do so.
That is the problem I have - some of the integration tests I have here rely on the fact that you can launch a set of micro-services within the same class-loader. It's a nasty problem and I am not blaming spring boot for not supporting my use-case, just explaining why it's not useful for me.

**Comment by cerebrotecnologico** [comment]
I have a similar problem. I have a spring-boot  app that acts as a small framework for other apps. It provides a couple of JMS queues and a DAO layer to retrieve and store data from a common set of data stores.  The problem is that the original developer of this framework app is scanning all the package "com.mycompany" (rather than com.mycompany.framework) so that it can load the beans of the specific app that may be declared under com.mycompany.myapp1 or com.mycompany.myapp2. 
We only load a single app in the JVM (although it would be great to load more than one), but these apps may share other libraries and sometimes we end up with beans in the context that we don't need. (these may be needed in app1 but not in app2)
So, what would be your advice ?

**Comment by wilkinsona** [comment]
@cerebrotecnologico GitHub issues, particularly closed ones, aren't the right place to ask for advice. Please post a question on Stack Overflow or come and chat on our Gitter channel.

**Comment by LiuXiaoJie** [comment]
@wilkinsona in your example，is it possible to get the four apps applicationContext？as @daikaixian said，I want to replace the rpc between two microservice as direct call.  Look forward to your reply.

**Comment by Izakey** [comment]
@wilkinsona Does each Spring Boot Application's Classloader run in a thread within the JVM's process or does it have a unique process of its own ?

**Comment by Izakey** [comment]
@flozano @snicoll @cerebrotecnologico @daikaixian @wilkinsona Has anyone been able to use this to run multiple Spring Boot apps in single JVM ?
