### ISSUE TITLE
[Different Request, Response Thread] Sring Boot 2.6.1 + MVC + Weclient + Kotlin Coroutines

### ISSUE THREAD

**Issue by sungbo5934** [spring-projects/spring-boot#33029]
Spring boot 2.6.1
Kotlin 1.6.0
mycode

```kotlin
@Controller
class Test{

    @GetMapping(..)
    suspend fun api(): Response {
      System.out.print(Thread.currentthread()) <-- http-nio-port-exec-1
      
      Webclient().post().url().retrieve().bodyToMono()..awaitSingle() // api call
      System.out.print(Thread.currentthread()) <-- reactor-1
      throw Exception() <- example
      
      return Response.builder(suspend fun...)
    }

    @exceptionhadler
    fun..{
       System.out.print(Thread.currentthread()) <-- http-nio-port-exec-2 ?? why!
    }

}
```

It is being developed through coroutine. Currently, spring boot 2.6 version supports the suspend function, but the thread of request and response are different, so MDC and trace cannot be tracked. Could you give me some help?

trace track and Mdc Context

**Comment by sungbo5934** [comment]
title

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
