### ISSUE TITLE
Interface method annoation pointcut not working 

### ISSUE THREAD

**Issue by bigdata-page** [spring-projects/spring-boot#33092]
## Question Description
1. Custom Annoation
```java
@Retention(RUNTIME)  
@Target(METHOD)
public @interface AspectTest {
}
```
2. Defining Inteface Class and Implement Class
```java
public interface AnnotationInterface {
    @AspectTest
    void print();
}

@Component
public class ExampleTwoBean implements AnnotationInterface {
    private static final Logger log = LoggerFactory.getLogger(ExampleTwoBean.class);

    @Override
    public void print() {
        log.info("ExampleTwoBean: print method");
    }
}

```
3. Defining Aspect
```java
@Aspect
@Component
public class AnnotationAspect {
    private static final Logger log = LoggerFactory.getLogger(AnnotationAspect.class);
    @Pointcut("@annotation(package.AspectTest)")
    public void withinMethod() {
        // Do nothing because of just define pointcut
    }

    @Around("withinMethod()")
    public Object around(ProceedingJoinPoint pjp) throws Throwable {
        log.info("Annotation:  start.");
        Object retVal = pjp.proceed();
        log.info("Annotation:  end.");
        return retVal;
    }
}
```
4. Run the SpringBoot Application。
When we invocation the ExampleTwoBean#print function, the poincut not working。

## Expected Result
The log contain: "Annotation:  start." and "Annotation:  end."

## Acutally Result
The log not contain: "Annotation:  start." and "Annotation:  end."

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
