### ISSUE TITLE
[12:05:09 ERROR]: Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.20.0-dev+17-6e931b2

### ISSUE THREAD

**Issue by Qeflod** [spring-projects/spring-boot#33118]

**Comment by Qeflod** [comment]
Hey, I'm creating a server right now and I'm getting an error I don't know what exactly                                                         
   [12:05:09 ERROR]: Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.20.0-dev+17-6e931b2

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
