### ISSUE TITLE
A question of loading command line configuration

### ISSUE THREAD

**Issue by zjg1993** [spring-projects/spring-boot#33183]
![image](https://user-images.githubusercontent.com/20152153/201866576-e3748524-ef1a-4923-9adc-e8ea7e1fb830.png)

When I use the first method, 7779 will be used.
The second way is to report errors.

![image](https://user-images.githubusercontent.com/20152153/201866931-73b224ef-54f4-448c-a197-d55a53b7fefc.png)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
