### ISSUE TITLE
Documentation for nested configuration properties in a native image uses `@NestedConfigurationProperty` too widely

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#33239]
The documentation example looks like this:

```java
@ConfigurationProperties(prefix = "my.properties")
public class MyProperties {

    private String name;

    @NestedConfigurationProperty
    private Nested nested = new Nested();

    // getters / setters...

    public static class Nested {

        private int number;

        // getters / setters...

    }

}
```

In this case, `@NestedConfigurationProperty` isn't required as `Nested` is already nested within `MyProperties`. It would be required if the code were structure like this:

```java
@ConfigurationProperties(prefix = "my.properties")
public class MyProperties {

    private String name;

    @NestedConfigurationProperty
    private Nested nested = new Nested();

    // getters / setters...

}

public class Nested {

    private int number;

    // getters / setters...

}
```

**Comment by mhalbritter** [comment]
Ah, I see. I'll add an example showing when `@NestedConfigurationProperties` is needed.

**Comment by siddhsql** [comment]
Using Spring Boot 3.1.5 I have 3 classes like this:

```
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
public class Foo {
  @NotNull String username;
  @NotNull String password;
}
```

```
import jakarta.validation.constraints.*;
import lombok.Data;

@Data
public class Bar {
  @NotNull String firstName;
  @NotNull String lastName;
}
```

```
@Data
@ConfigurationProperties
@Component
public class Config {
  @NotNull Foo foo;
  @NestedConfigurationProperty @NotNull Bar bar; // note it is missing the initializer
}
```

the expectation was that parsing of `application.properties` should fail but in fact it works. any idea why? also the [documentation](https://docs.spring.io/spring-boot/api/java/org/springframework/boot/context/properties/NestedConfigurationProperty.html) is not very helpful:

>This annotation has no bearing on the actual binding processes, but it is used by the spring-boot-configuration-processor as a hint that a field is not bound as a single value. When this is specified, a nested group is created for the field and its type is harvested.

**Comment by siddhsql** [comment]
this looks like a bug to me:

>the expectation was that parsing of application.properties should fail
(according to the example provided right at the beginning of this issue and
latest documentation) but in fact it works.

in fact it gets doubly confusing because on one hand the documentation says
to use @NestedConfigurationProperty and elsewhere the documentation says: This
annotation has no bearing on the actual binding processes

PS: i do not use SO as my questions are not well received there. i was just
providing feedback for improvement.

**Comment by philwebb** [comment]
@siddhsql If you think you've found a bug then please open a new issue with a sample project that reproduces the issue (ideally without using lombok). I'm not sure why you think the parsing of `application.properties` should fail, we'll need more details if you do open an issue.

> in fact it gets doubly confusing because on one hand the documentation says to use `@NestedConfigurationProperty` and elsewhere the documentation says: This annotation has no bearing on the actual binding processes

You should use the annotation to ensure that the correct meta-data is generated so that IDE auto-completion works. The annotation isn't actually needed for Spring Boot to perform the binding at runtime.

**Comment by siddhsql** [comment]
what does IDE auto-completion have to do with this? could you explain? i
mean auto-completion of what? IDE can auto-complete variables
without annotations.

**Comment by bclozel** [comment]
IDEs use the metadata generated by Spring Boot to provide auto-completion when typing in application.properties files.

Please stop commenting here and provide the requested sample in a new issue.
