### ISSUE TITLE
Failure Analysis for InvalidConfigurationPropertyValueException is skipped when the property is not set

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#33261]
There are a number of places where we throw `InvalidConfigurationPropertyValueException` to indicate that a value should have been set. `WavefrontProperties` does so if the API token has not been set.

The related `InvalidConfigurationPropertyValueFailureAnalyzer` has no effect as it tries to find a property in the environment that matches the one in the exception. If no property is set, the analysis doesn't do anything and the raw exception is thrown.

I don't know what's the best course of action for this is. Invalid and missing are two different things and I am not sure the failure analyzer should be the one deciding which is which.

**Comment by protyay** [comment]
Hey, is anyone looking into this ? If there's not a too strict timeline, I can dive deep. Let me know what's your opinion

**Comment by wilkinsona** [comment]
Thanks for the offer, @protyay. No one is looking at it and you're more than welcome to do so, but we really don't know how to tackle this one yet. As @snicoll said, the best course of action isn't clear so we probably need to spend some time figuring out what needs to be done before anyone can start working on this one. I'll update the issue's labels to reflect this.

**Comment by wilkinsona** [comment]
We seem to have two places where we create an `InvalidConfigurationPropertyValueException` with a `null` value:

https://github.com/spring-projects/spring-boot/blob/126927f462cb8d78ff429ab4ff77f2d26ca65ad2/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/wavefront/WavefrontProperties.java#L142-L145

https://github.com/spring-projects/spring-boot/blob/126927f462cb8d78ff429ab4ff77f2d26ca65ad2/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaStreamsAnnotationDrivenConfiguration.java#L69-L74

In each case, I don't think we're really throwing the right exception.

In the `WavefrontProperties` case, it's not one individual property that has an invalid value but a combination of two properties. `management.wavefront.api-token-type` has been set but `management.wavefront.api-token` has not and setting the former to a value other than `no-token` requires that `api-token` is also set. There are two ways to fix this:

- Correct the value of `api-token-type` and set it to `no-token`
- Set `api-token` with a token of the configured type

In the Kafka Streams case, it's two properties again as neither `spring.application.name` nor `spring.kafka.streams.application-id` has been set. Setting either of them will fix the problem so it's not necessarily the value of `spring.kafka.streams.application-id` that's invalid.

We could update `InvalidConfigurationPropertyValueFailureAnalyzer` to perform analysis when the property cannot be found in the environment (for example by using the value from the `InvalidConfigurationPropertyValueException` and omitting the origin information). I think we could also introduce new exceptions for the two cases above:

1. Some configuration properties are invalid in combination
2. One or more mandatory properties has not been set

For 2, we should perhaps also consider making the auto-configuration back off somehow rather than failing when the property isn't set. I'm not sure if that would be the best behavior here but the way it currently works does feel a little unusual.

**Comment by philwebb** [comment]
We're going to add the fix Andy suggested above and look at adding a different exception type for Wavefront and Kafka.
