### ISSUE TITLE
Make it possible to inherit org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping

### ISSUE THREAD

**Issue by RaviTeja51** [spring-projects/spring-boot#33502]

**Comment by mhalbritter** [comment]
Hello! What's your use case? What do you want to achieve? And what is preventing you from inheriting from `WebMvcEndpointHandlerMapping`?

**Comment by RaviTeja51** [comment]
My use case is to add an interceptor to actuator so that I can have a method call after a Http request. 

I tried to inherit **WebMvcEndpointHandlerMapping** and use **extendInterceptors** but since **WebMvcEndpointHandlerMapping** requires **EndpointMapping**, **Collection<ExposableWebEndpoint>** which are not instantiable

**Comment by mhalbritter** [comment]
I see. I think an easier way would be to register a `jakarta.servlet.Filter`. 

It feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that
other people can find it) or add some more details if you feel this is a genuine bug.
