### ISSUE TITLE
Disable /logfile endpoint if there is no logfile

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3360]
It seems a bit strange at the minute to have this endpoint if it is never going to have any data. It's also not very 12-factor to have a log file so we'd like not to encourage people to use it.

**Comment by joshiste** [comment]
In my original PR #2294 there was a `@ConditionalOnExpression("'${logging.file:}' != '' || '${logging.path:}' != ''")` so the endpoint was only present when a logfile was configured....

**Comment by dsyer** [comment]
Thanks. That seems to have been lost.

**Comment by philwebb** [comment]
I've been trying to keep SpEL conditions to a minimum because they can slow down startup time so I think I just dropped it figuring the extra endpoint wouldn't matter. 

The endpoint implementation returns 404 if the logfile isn't found, is that any different that it being not registered in the first place?

**Comment by dsyer** [comment]
Yes it is - especially if we support hypermedia for the endpoints (it would be strange to be able to discover an endpoint for a resource that didn't exist). Maybe we could set an enabled flag later in the lifecycle if you are worried about conditions.
