### ISSUE TITLE
Native image:gradle nativeBuild error

### ISSUE THREAD

**Issue by huiji121** [spring-projects/spring-boot#33635]
i need help, 
springboot:2.7.7
aot:0.12.1
win10
graalvm11
How can I solve this problem
https://user-images.githubusercontent.com/24616352/209309808-1e0e8af6-75b5-429d-9077-461d89e53077.png

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
