### ISSUE TITLE
How to support reflection

### ISSUE THREAD

**Issue by zhangpan-soft** [spring-projects/spring-boot#33638]
![image](https://user-images.githubusercontent.com/66060154/209642069-ec045a94-df58-4bd8-821f-f8d2d8feb2fc.png)

Therefore, I introduced native and added an annotation

![image](https://user-images.githubusercontent.com/66060154/209642284-7b4de9ea-009c-40a2-a7cd-fe90489ae0cf.png)
![image](https://user-images.githubusercontent.com/66060154/209642323-eb4f91cd-ee49-4b9e-9af7-94ba37279256.png)

However, it reported a cglib error

eg:
![image](https://user-images.githubusercontent.com/66060154/209642448-5369a41f-fa04-4364-bce3-051120d6b0e8.png)

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
Note that `spring-native` should not be used with Spring Boot 3.0.
