### ISSUE TITLE
Allow CONSOLE_LOG_PATTERN and FILE_LOG_PATTERN to be defined in application properties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3367]
See https://github.com/spring-projects/spring-boot/issues/1788#issuecomment-117206572

**Comment by rob-baily** [comment]
@philwebb Thanks for creating this.  Maybe instead of worrying about the xml files we should worry about the default configuration. I'm thinking now if you go to enough trouble to create your own configuration files you can manage setting up things like the conversion pattern even it if means copying them.   

If that is the case do you think it would make sense to modify the DefaultLogbackConfiguration to get access to the environment and have the ability to override the static final variables (CONSOLE_LOG_PATTERN,FILE_LOG_PATTERN) in this class with an environment property?  

If you think trying to set the properties in the xml is better would it make sense to set up a file like defaults-spring.xml that could be included by Spring aware configurations and uses a Spring property for the value of one of these other properties.

Let me know if this makes sense or I am way off base.

**Comment by philwebb** [comment]
`DefaultLogbackConfiguration` was added for performance reasons, it's indented to work in the same way as the logback xml that was provided by Boot 1.1. I think it makes sense to have it consult the environment for these specific properties.

**Comment by rob-baily** [comment]
@philwebb Please review my pull request and see if it makes sense.  I modified the AbstractLoggingSystem loadDefaults() method to pass the LoggingInitializationContext in and now the DefaultLogbackConfiguration uses that to replace its built in defaults with properties when they exist.  Wasn't sure about the best convention for property names so I used logging.logback.consoleLogPattern and logging.logback.fileLogPattern for now.  We can obviously change them if desired.  I was able to add some unit tests as well. :) I modified a couple of existing tests to check the default pattern to ensure it has INFO and then added other tests when the properties are set to not include the level to verify that is not output.
