### ISSUE TITLE
How to support SpringMVC using XML config?

### ISSUE THREAD

**Issue by gencube** [spring-projects/spring-boot#3376]
Most of my company's code are in Spring 3 XML and I am not authorized to change it:
A sample of that can be seen here.
https://github.com/gencube/Spring3mvcxml
Typical deployment is done with WAR file handed to me.
How to I code a Undertow Application to launch and run this project??

**Comment by gencube** [comment]
I am asking this question directed to (spring-boot-sample-undertow):
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-undertow

**Comment by wilkinsona** [comment]
This sort of usage question is better-suited to [Stack Overflow](http://stackoverflow.com/tags/spring-boot) or [Gitter](https://gitter.im/spring-projects/spring-boot). We prefer to keep the issue tracker for bugs and enhancement requests.

That said, you can import XML configuration using [`@ImportResource`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ImportResource.html). However, you may still run into problems due to your dependence on Spring 3. Please give it a try and ask on Stack Overflow or Gitter if you get stuck.

**Comment by gencube** [comment]
Thanks for answering. I asked here since the developer of spring are located here and has an example of Springboot and Undertow.
