### ISSUE TITLE
Speed up BOMR library resolution

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#33824]
BOMR takes a lot of time to look for library updates. Looking for a single version can take up to 17 seconds in my tests. This can be sped up by using multithreaded lookups.

While we're at it, we could improve another thing: right now, BOMR looks for update, and if it finds one, it waits for user input if this update should be applied before continuing looking. This can be improved by first collect all available updates, and then prompt the user. The first phase takes longer but the user can then do something else, and when the long phase is done, the user is asked for all the update choices without further waiting time in between the choices.

**Comment by mhalbritter** [comment]
BOMR library update search now uses 8 threads by default. Running gradle with `--info` now shows which library search took how much time.

**Comment by wilkinsona** [comment]
Unfortunately, I think we should revert this. Using multiple threads to resolve the versions in the way that we do is pushing the limits a bit for what's acceptable client behavior. I learnt this the hard way in the early days of Bomr when I managed to get my IP address blocked due to making too many requests that looked like a scraping tool.

I do like the idea of speeding this up though. I wonder if we could use the [Maven Central Search REST API instead](https://central.sonatype.org/search/rest-api-guide/). The search index lags Central itself a little so we may miss some very recent releases but the benefits may well outweigh that.

**Comment by mhalbritter** [comment]
Ah, looks like I just hit the API in a service degregation:

![image](https://user-images.githubusercontent.com/98899556/212328132-cefcf460-873e-4b33-8606-29051fec899b.png)

So maybe it's usable after all :)

**Comment by mhalbritter** [comment]
Another idea would be to cache the POM files locally with their Etag value. Subsequent requests can then send the `If-None-Match` header with the etag value and when the server responds with a `304 Not modified` we used the cached version. That should save some bandwidth and maybe speed up the requests.

**Comment by mhalbritter** [comment]
There's an update on search.maven.org: https://central.sonatype.org/faq/what-happened-to-search-maven-org/

**Comment by wilkinsona** [comment]
This seems to be OK with 2 threads. We can revisit if it becomes a problem in the future.
