### ISSUE TITLE
Application.properties take precedence over system properties with relaxed names

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3385]
For some reason, if a system property uses a relaxed names it is not taken into account _unless_ no other `PropertySource` defines the value.

See [this sample project](https://github.com/snicoll-scratches/system-property-overriding) for more details.

Note that OS env variables are not affected by this issue. This seems to be a system property specific thing.

**Comment by dsyer** [comment]
It's subtle but I can see why this is broken. When you have 2 properties from different `PropertySources` that have different names (e.g. `THE_NAME` and `the-name`) in the sample app, but resolve to the same bean property (`theName`), they are applied (wrongly) in the order they come out of the `Environment`, so the *second* one wins. The relevant code is in `RelaxedDataBinder.modifyProperties()`. If they both have the same name (e.g. `the-name` and `the-name`) then the correct priority is applied because there is only one `PropertyValue` for that property and its value is pulled from the `Environment`.

**Comment by snicoll** [comment]
There is also the same kind of issues if you set both an OS env variable and a system property. The OS env variable overrides the system properties (which is not what the doc states)

**Comment by dsyer** [comment]
Unfortunately the change in 48009bf doesn't fix this issue because it still makes assumptions about the order of the incoming `PropertyValues`. Re-opened for a bit more thinking time.

**Comment by dsyer** [comment]
See also #3402 for a slightly modified approach that feels simpler to me (albeit not hugely) and seems to pass all the tests.
