### ISSUE TITLE
i want to change my data source config in run time by data user put

### ISSUE THREAD

**Issue by mooEssam** [spring-projects/spring-boot#33851]

**Comment by mooEssam** [comment]
for example i have h2 datasource 
i want to change url or pass or change it to my sql in run time but it seems bit had

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
