### ISSUE TITLE
Logging doesn't work out of the box on JBoss

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#339]
http://stackoverflow.com/questions/20859851/spring-boot-doesnt-work-on-jboss

Perhaps we can fix, or perhaps just documentation.

**Comment by esantana** [comment]
The logging class is created by the jboss/wildfly container. The problem is that spring/spring boot executed on the spring container has a different CDI mechanism, what occurs is that the logging implementation that should be created by the container is not created, and the problem occurs. What I/m doing to work around on this, is creating a class that create the implementation using java assist.

**Comment by ccampo133** [comment]
@davetownsend +1 this solution worked for me!

**Comment by xuuz** [comment]
Dear @davetownsend,
Could you pls let me know where to put jboss-deployment-structure.xml on the project genreate by jHipster? 
Thanks a million in advance!
Hung

**Comment by codacoder** [comment]
@xuuz 

jboss-deployment-structure.xml goes in your application's WEB-INF directory.

**Comment by davetownsend** [comment]
@xuuz - I don't use jhipster, but in a normal boot app, I just put it in the `src` dir and then tell gradle to add in to the generated `WEB-INF` dir.

```groovy
war {
  baseName = 'MyApp'
  from('src') {
    include 'jboss-deployment-structure.xml'
    into 'WEB-INF'
  }
}
```

**Comment by xuuz** [comment]
Thanks @codacoder  @davetownsend , it's worked well now, thanks for your helps.
