### ISSUE TITLE
trace id propagation does not work after defining a RestTemplateBuilder

### ISSUE THREAD

**Issue by kabennett** [spring-projects/spring-boot#33912]
Please see the [stackoverflow](https://stackoverflow.com/questions/75175018/defining-a-resttemplatebuilder-bean-causes-traceid-propagation-across-service-bo) where I explain this issue in detail and how to reproduce it. The organization I work for strictly prohibits me from posting to GitHub, so I apologize about having to post the example code in the stackoverflow issue.

**Comment by scottfrederick** [comment]
@kabennett There is no need to create an issue when you have already posted to StackOverflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Since you are getting help on StackOverflow, let's keep the discussion there. If a problem is identified, we can re-open this with the details.

**Comment by kabennett** [comment]
I am posting it here because simply by declaring a ```RestTemplateBuilder``` bean, micrometer tracing does not propagate the trace id across service boundaries. Isn't that something that would be interesting to this project?

**Comment by kabennett** [comment]
I would never expect that side-effect to happen, and to me it seems like a bug or at least an unintended side-effect.

**Comment by philwebb** [comment]
I've commented on the stackoverflow post.
