### ISSUE TITLE
Spring Boot 3.0.2 Multi-module Use EntityScan does not work

### ISSUE THREAD

**Issue by GavinMoreYoung** [spring-projects/spring-boot#33927]
i donot know how to fix this issues.
i use spring boot 2.7.8, application running , i want upgrade 3.0.2，but i donot how to do.
this is my learning project structure.
![image](https://user-images.githubusercontent.com/12248194/213861780-2360c67b-9284-4d5d-a23c-23b30dfd8f5d.png)

can you tell my how to fixed?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by GavinMoreYoung** [comment]
收到，会尽快给您回复。
