### ISSUE TITLE
Can we keep Kafka Keystore file outside the main project

### ISSUE THREAD

**Issue by amit84g** [spring-projects/spring-boot#33949]
Can we keep Kafka Keystore file outside the main project

Reason: Anytime Keystore certificate expires, we need to re-deploy application each time in respective environment

**Comment by scottfrederick** [comment]
Thanks for getting in touch. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. This feels like a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
