### ISSUE TITLE
Update an existing entity does not work as expected

### ISSUE THREAD

**Issue by pantelis17** [spring-projects/spring-boot#33945]
Hello everyone,

I have just migrate to spring-boot 3.0.2 from spring-boot 2.6.6 and i am facing the following issue:

For some entities, when i try to update them via "save" method then the existing entity is not updated and a new entity (with new id) is added to the table. I am struggling to understand what is happening as everything was working as expected in 2.6.6. I tried to debug the spring code in order to check is persist or merge method is used and the merge method is used as expected.

Any suggesting or something i can try?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
