### ISSUE TITLE
Spring boot does not support automatic creation of database in postgres

### ISSUE THREAD

**Issue by brundabharadwaj** [spring-projects/spring-boot#33957]
Expectation: Auto creation of database in postgres if database doesnot exist
Actual : Unable to create database in postgres automatically.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by bclozel** [comment]
@brundabharadwaj before taking things to StackOverflow, I would advise to read [this section of the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization). If this doesn't help, your StackOverflow question should explain what you're trying to achieve, what you've tried (showing code snippets) and how is this failing.
