### ISSUE TITLE
JSP custom tags support

### ISSUE THREAD

**Issue by vicmosin** [spring-projects/spring-boot#3396]
I am facing some strange issue - once I add custom tag into JSP in the following way:
```
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
...
<t:master>
	<jsp:attribute name="title"><spring:message code="message.text" /></jsp:attribute>
</t:master>
```
the content of the output page is empty... If I remove `<t:master.. />` - work fine. Spring and spring security tags work fine too.

I know there are [limitations](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-jsp-limitations) regarding using JSP within the Spring Boot app, but I follow the suggestions - use only WAR package.

**Comment by wilkinsona** [comment]
Judging by the identical avatars, I see you've already asked this question [on Stack Overflow](http://stackoverflow.com/questions/31166824/custom-tags-within-jsp-and-spring-boot). I'm going to close this so that we can keep the discussion in one place. To increase the changes of someone being able to help you, you should share some code that reproduces the problem. Reading this [advice](http://stackoverflow.com/help/mcve) may help.

**Comment by mmirzaeyan** [comment]
the question on SO in removed
