### ISSUE TITLE
Add classifiers to Managed Dependency Coordinates documentation

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-boot#34060]
A few managed dependencies include one or more `classifier` along with the group ID, artifact ID, and version coordinates, but the classifiers are not included in the [`Managed Dependency Coordinates` section of the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#appendix.dependency-versions.coordinates). 

In the interest of space, we should avoid adding a new column to the table that will be empty for all but a few dependencies. We could add any classifiers to the `Artifact ID` or `Version` column, changing the column title to `Artifact ID (Classifiers)` or `Version (Classifiers)` and putting any classifiers in parenthesis in the appropriate rows in that column.

**Comment by wilkinsona** [comment]
I'm not sure that this is possible, at least not without a change in approach.

We currently use Gradle's variant metadata and dependency constraint metadata to obtain the list of managed versions. This gives us access to the dependency versions that are managed directly in `spring-boot-dependencies` as well as those that are managed in boms that we import but it does not, as far as I can tell, provide any information about classifiers.

To gather information about classifiers I think we'd have to resolve the imported boms ourselves so that we could extract their dependency management and any version constraints. While I think this may be technically possible I'm not sure that the benefit of documenting classifiers justifies the additional complexity.
