### ISSUE TITLE
Clarify what JmsListenerContainerFactory is created by default

### ISSUE THREAD

**Issue by gokhanoner** [spring-projects/spring-boot#3407]
After #3150  and #3390 commits, Jms local transaction works different. in 1.2.4, if there is a JDBC Transaction, it sync transactions internally, as documented, but in 1.2.5 snapshot, this feature is gone.

**Comment by gokhanoner** [comment]
test case for this issue: https://github.com/gokhanoner/spring-boot-3390

Change the active profile, and see the behavior change. JmsAnnotationDrivenConfig  copied from 1.2.5.BUILD-SNAPSHOT.

**Comment by snicoll** [comment]
1.2.5 _is_ released so you don't need to copy anything.

**Comment by gokhanoner** [comment]
OK, I updated the test case as 1.2.5

Now shows the behaviour difference between 1.2.4 and 1.2.5. If that's intentional and the only way to achieve some sort of transaction sync is XA Transactions, than it's OK but please update the documents so users like myself can get a false impression about the supported features.
If not, or this is an issue actually, what is your thought?

**Comment by snicoll** [comment]
My thought at this point is that I pinged two different guys internally to discuss this and I am confused. I am also confused by your sample project actually. I'll have a deeper look at it next week. Thanks.

**Comment by snicoll** [comment]
Okay so I've reviewed this one more time and your sample project does not define any `@Transactional` boundary on the listener. That setup is "abusing" the `JpaTransactionManager` to start the transaction when the incoming message is processed (since the container is requested to use that transaction manager).

For a clean arrangement, the listener container should not be aware of (or configured for) datastore purposes. that's an isolated concern within the listener endpoint implementation. If I add `@Transactional` on your `@JmsListener` method, it works as expected.  

I have clarified the doc in https://github.com/spring-projects/spring-boot/commit/2126c7774af3811fa572af1f9671e5c8265691da
