### ISSUE TITLE
Help with CRUD XML XmlController @PatchVariable and Spring Boot 2 Java 8 Angular

### ISSUE THREAD

**Issue by luismendes070** [spring-projects/spring-boot#34168]
CRUD XML XmlController @PatchVariable and Spring Boot 2 Java 8 Angular
Am I suppose to implement a xml annotation library to patch XML?

https://gist.github.com/luismendes070/905e3202ec714c24cdd17dee5e722acb

https://github.com/luismendes070/curso-angular/blob/master/crud-angular-spring/crud-spring/src/main/java/com/loiane/controller/XmlController.java

[

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
