### ISSUE TITLE
[spring-boot-configuration-processor] Allow use of multiple additional-spring-configuration-metadata.json

### ISSUE THREAD

**Issue by dpalmmna** [spring-projects/spring-boot#34210]
Allow the posibility to configure multiple additional-spring-configuration-metadata.json files. Need arises when having to use hint values defined in dependencies.
When having to import hints from multiple dependencies it could be allowed to use multiple additional-spring-configuration-metadata files found with patter additional-spring-configuration-metadata*.json.

Or allow annotation to provide hint values in java code.

Or if better solution please advise.

**Comment by wilkinsona** [comment]
I am struggling to imagine a situation where a dependency would have a `additional-spring-configuration-metadata.json` file that would be of interest to a consumer. Any hints from the dependency's additional metadata should have been merged into it `spring-configuration-metadata.json` file at compilation time. In other words, consumers should only be interested in `spring-configuration-metadata.json` files.

Can you please explain your requirement in a bit more detail so that we can understand the purpose of the multiple `additional-spring-configuration-metadata.json` files? A concrete example pushed to GitHub or zipped up and attached to this issue would also be useful.

**Comment by dpalmmna** [comment]
[test-spring.zip](https://github.com/spring-projects/spring-boot/files/10754234/test-spring.zip)
 Following test case as example the generated metadata for module2 does not contain all hints

**Comment by wilkinsona** [comment]
Thank you. I now understand what you're trying to do and it looks to me like an attempt to address #18366. While supporting multiple `additional-spring-configuration-metadata.json` files may meet your needs, I'm not sure that it will work for everyone. I'll add a note to #18366 to consider it as an option. I'm going to close this issue as a duplicate as we don't want to make any changes until we've had to time to consider all sides of the problem.
