### ISSUE TITLE
Provide configuration for ignoring routes from being sampled

### ISSUE THREAD

**Issue by braunsonm** [spring-projects/spring-boot#34400]
Right now, you have 3 options for configuring if a trace is reported.
1. Using the probability configuration properties, which only give you control over the percentage reported

2. Using a `ObservationRegistryPredicate`, however there doesn't seem to be a way to ignore any spans which are created as a result of a HTTP request because subsequent spans do not have an http.url attribute you can match on.

3. Providing a custom `Sampler`. However the `shouldSample` method does not receive the final attributes for the span and thus you cannot determine what path the sample is for.

Ideally Spring would provide a way to configure this. The primary use case being to ignore any traces related to `/actuator` since these typically are only for health checks and clutter up the tracing backend.

If there is another method I have not thought of that would work, I'd love to hear it!

**Comment by mhalbritter** [comment]
There's a way, but it's not pretty:

```java
@Configuration(proxyBeanMethods = false)
class MyObservationConfig {
	@Bean
	ObservationPredicate predicate() {
		return (s, context) -> {
			if (context instanceof ServerRequestObservationContext serverRequestObservationContext) {
				HttpServletRequest carrier = serverRequestObservationContext.getCarrier();
				return !carrier.getServletPath().startsWith("/actuator");
			}
			return true;
		};
	}
}
```

**Comment by braunsonm** [comment]
@mhalbritter unfortunately as I mentioned in the original issue that doesn't work. At least it hasn't in my experience.

The first span will be able to get ignored that way but any subsequent observations will still be reported. Inside the predicate there doesn't seem to be a way to get the parent span so you can recursively find out if a new observation is related to a request.

For example with that predicate, we can still see a call with a WebClient or RestTemplate get reported to our trace backend, since they are not from the `HttpServletRequestContext`

**Comment by jonatan-ivanov** [comment]
If you want to prevent a **span** from being reported, you can:
- Write an `ObservationPredicate` and filter out the `Observation`: this will also filter out metrics.
- Write a `SpanExportingPredicate` (see: `SpanIgnoringSpanExportingPredicate`): this will only filter out spans and leaves metrics alone.

You can inject your own sampler but it is for a different use-case, I would go with the options above.

Here's a working example that filters out Observations for actuator on the server (and on the client side): [`CommonActuatorConfig`](https://github.com/jonatan-ivanov/teahouse/blob/d8b32835e34b65091f52769be1f60b9d9ae78564/core/src/main/java/org/example/teahouse/core/actuator/config/CommonActuatorConfig.java#L24-L46)

I'm not sure I get the issue with subsequent spans: with actuator, how do you have any (custom healthcheck)? You can get the parent, there is a `getParentObservation` method.

**Comment by braunsonm** [comment]
@jonatan-ivanov The problem with this solution is the predicate only acts on spans. I know there is a `getParentObservation` method but it is always `null` when a predicate is used to filter out the `ServerRequestObservationContext`.

What you end up getting is a bunch of Spring Security traces that are disconnected (have no parent) which makes a mess when you're using a tool like tempo and trying to query for things. This also means that any custom observation you have in your Spring application still get reported but you can't see the context of why they ran (if they were initiated by a call from a path that was excluded). Yes we do register custom health checks, but this use case goes beyond just ignoring actuator.

**Comment by jonatan-ivanov** [comment]
I'm not sure what you mean that "the predicate only acts on spans". The `ObservationPredicate` acts on `Observation`s the `SpanPredicate` acts on `Span`s. What else should they act on other than `Observation`s/`Span`s?

> I know there is a `getParentObservation` method but it is always `null` when a predicate is used to filter out the `ServerRequestObservationContext`.

Since the `ServerRequestObservationContext` belongs to the `Observation` that belongs to the request that the server received, it has no parent, that's the first `Observation`. What parent should it have?

>What you end up getting is a bunch of Spring Security traces

Now we are talking! :) If you don't want to see the Spring Security spans at all, you can [disable them](https://docs.spring.io/spring-security/reference/reactive/integrations/observability.html#webflux-observability-tracing-disable). If you only want to see them when the Observation of the server request is not filtered out, then similarly you can [disable them](https://docs.spring.io/spring-security/reference/reactive/integrations/observability.html#webflux-observability-tracing-disable) only if they don't have a parent.

**Comment by braunsonm** [comment]
I think we are misunderstanding eachother so I put together a minimum reproducable sample you can play with. 

**What I expect to happen:** Any spans related to a call to `/actuator/health` should not be reported.

**What actually happens:** Any custom observations, spring security observation, or datasource observations etc are still reported but are now disconnected.

From what I gathered from your reply, you are working off the assumption that something like this should work:

```java
@Configuration
public class TestConfiguration {
    @Bean
    ObservationPredicate ignoreActuator() {
        return (s, context) -> ignoreActuatorRecursive(context);
    };

    public boolean ignoreActuatorRecursive(Observation.ContextView context) {
        if (context instanceof ServerRequestObservationContext serverRequestObservationContext) {
            HttpServletRequest carrier = serverRequestObservationContext.getCarrier();
            return !carrier.getServletPath().startsWith("/actuator");
        }

        if (context.getParentObservation() != null) {  // <----- THIS IS NEVER TRUE
            return ignoreActuatorRecursive(context.getParentObservation().getContextView());
        }

        return true;
    }
}
```

This results in the following being reported: 
![image](https://user-images.githubusercontent.com/5280764/223454656-ce8e98db-69c8-4cdb-8584-6cd1910b7e71.png)

The configuration doesn't work for a few reasons:
1. There is never a parent observation on these observations
2. Spring security does not have http.url attributes to match on (and they shouldn't)
3. Any custom observations you might have in your application, like datasources etc will also be reported here unless you add attributes to match the URL on to every single observation (some of which you do not control)

Does this help you at all? This application is running with only that configuration, and the following in the pom:

<details>

```xml
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-observation</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-tracing-bridge-otel</artifactId>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-exporter-zipkin</artifactId>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
			<scope>runtime</scope>
		</dependency>
```

</details>

**Comment by mhalbritter** [comment]
A sample definitely helps, thanks. Can you please share it with us?

**Comment by braunsonm** [comment]
@mhalbritter I did, it has no other changes than the configuration class above. I also provided all the dependencies used. If that isn't enough and you're looking for more let me know..

**Comment by jonatan-ivanov** [comment]
I guess what @mhalbritter is asking is a project we can clone, import to the IDE and debug. What we see is a code snippet above not a sample project. 

I haven't tried to set-up a sample project for this but there is one thing that confuses me, in your snippet I see this:
```java
if (context.getParentObservation() != null) {  // <----- THIS IS NEVER TRUE
```
But then you say:
>There is never a parent observation on these observations

So is there a parent or not. If there is a parent, what is it?

**Comment by braunsonm** [comment]
There is never a parent. `context.getParentObservation != null` is always false (ie it is always null).

**Comment by jonatan-ivanov** [comment]
So the security spans should have a parent. That was my assumption when I tried to provide you a workaround: if they always have a parent, the only scenario when they don't is when their parent is ignored so you can ignore them too so you can do something like:

```java
if (context..getName().startsWith("spring.security.") && context.getParentObservation() == null) {
    return false; // assuming parent is also ignored
}
```

If this assumption does not hold, we need to fix instrumentation in Spring Security.
Let us discuss this internally but could you please try another workaround? Could you please try to use a `SpanFilter` and set `sampled` to `false` for actuator spans?

**Comment by braunsonm** [comment]
The function signature of `SpanFIlter`'s do not allow modifying a sampled state, just adding/removing data from the span. https://github.com/micrometer-metrics/tracing/blob/e76ef15fd01df8d8711c7f3b9ee9003b1bae224f/micrometer-tracing/src/main/java/io/micrometer/tracing/exporter/FinishedSpan.java#L35

**Comment by mhalbritter** [comment]
Sigh. Here's the sample: 
[sb34400.zip](https://github.com/spring-projects/spring-boot/files/10918207/sb34400.zip). Instructions to run are in the readme.

**Comment by jonatan-ivanov** [comment]
@mhalbritter Thank You!

@braunsonm 
>Your assumption does not hold. ALL Observations (ignored or not) do not have a parent set.

I'm sorry I missed that the parent is set after the predicate is tested so the parent will be there but not at the time where you need it in the predicate, I opened an issue to improve this: https://github.com/micrometer-metrics/micrometer/issues/3678

I think not being able to see what request the Spring Security Observations belong to is an issue, I created one for that too: https://github.com/spring-projects/spring-security/issues/12854
Fyi: this does not need any key-values or tags to be set it is enough if the `Context` holds this information since ObservationPredicate can access it.

>Instead I tried using a SpanExportingPredicate but it is never called. 

I missed that `SpanExportingPredicate` was added in `3.1.0-M1`: https://github.com/spring-projects/spring-boot/pull/34002 If you want to use it, either you need to use `3.1.x` or you can do the same what you see in the pull request (you might need to override (an)other bean(s)).

I think I can give you a not so simple workaround:

```java
// This adds the http.url keyvalue to security observations from the root (mvc) observation
// You add an ignoreSpan=true keyValue instead if you want, or something that can signal to the SpanExportingPredicate what to ignore
@Bean
ObservationFilter urlObservationFilter() {
    return context -> {
        if (context.getName().startsWith("spring.security.")) {
            Context root = getRoot(context);
            if (root.getName().equals("http.server.requests")) {
                context.addHighCardinalityKeyValue(root.getHighCardinalityKeyValue("http.url"));
            }
        }

        return context;
    };
}

private Observation.Context getRoot(Observation.Context context) {
    if (context.getParentObservation() == null) {
        return context;
    }
    else {
        return getRoot((Context) context.getParentObservation().getContextView());
    }
}

// This ignores actuator spans but its logic depends on the ObservationFilter above
// Auto-configuration for SpanExportingPredicate was added in 3.1.0-M1
// So either you use 3.1.x or you can add the same to your config : https://github.com/spring-projects/spring-boot/pull/34002
@Bean
SpanExportingPredicate actuatorSpanExportingPredicate() {
    return span -> !span.getTags().get("http.url").startsWith("/actuator");
}
```

This workaround will not be necessary once the Spring Security issue above is fixed.
What do you think about closing this issue in Boot? I think there is not much we can do here.

**Comment by braunsonm** [comment]
Fine with me, in particular I do not think having `http.url` added to specific observations is the correct approach here, as I mentioned custom observations or ones provided by libraries would need to also have an attribute added to them that might have a leaky abstraction.

The micrometer issue you opened I think will solve this when it is completed.

Thanks for your thorough look into this issue.

**Comment by jonatan-ivanov** [comment]
>I do not think having http.url added to specific observations is the correct approach here

That's why I commented that you can use whatever data you want (e.g.: `ignoreSpan=true`), please feel free to use your own key-value, you "just" need to maintain the "contract" between the two components.

**Comment by sibethencourt** [comment]
Hi @jonatan-ivanov I've tried to apply your fix by adding the config from https://github.com/spring-projects/spring-boot/pull/34002 but turns out that the `SpanProcessor` does not have the `@ConditionalOnMissingBean` annotation so I cannot replace it, unless there is some way that I don't know of?

It seems to be precisely the only bean that doesn't have the annotation, is that expected or could be a miss? https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/OpenTelemetryAutoConfiguration.java#L127

**Comment by jonatan-ivanov** [comment]
@sibethencourt If you check where the `SpanProcessor` is used, you will find `SdkTracerProvider`. So you might need to create a `SdkTracerProvider` as well depending on your situation.

This seems intentional to me, if you check how `ObjectProvider<SpanProcessor>` is used:
```java
spanProcessors.orderedStream().forEach(builder::addSpanProcessor);
```
So it supports multiple processors that are additional.

**Comment by sibethencourt** [comment]
Hi, I'm coming back to this because it's getting more complicated for me to filter all the child spans of a particular root trace. 
I wanted to see if there was a way to do it using opentelementry API, and this is what I've found so far:
As @braunsonm mentioned at the beginning Sampler wouldn't work because at that time all the traces are empty.
The only solutions I found would be to use `SpanExportingPredicate` or `SpamFilter`, (I only use opentelementry API so any micrometer option wouldn't work for me).
To be able to filter all the child spans, first I need to keep track of the root.traceId for any trace that I want to filter, and then make sure I also filter all the spans with parent equals any filtered trace. 
So fine, I implemented that, also a mechanism to clean up old traceIds that are too old and I managed to get something together, which seems to do the trick, until... I realized that the `SpanExportingPredicate` receives the child spans first and then at the end receive the root trace 🤦 So now, I don't have any way of knowing if a child span should be filtered because I would only see the root trace when it's too late. I'm sure something must be wrong in my code but couldn't figure out what's going on from here.

Is this by design? Am I doing anything wrong? it seems to complicated for what it should really is 🤔

**Comment by diukarev** [comment]
> Hi, I'm coming back to this because it's getting more complicated for me to filter all the child spans of a particular root trace. I wanted to see if there was a way to do it using opentelementry API, and this is what I've found so far: As [@braunsonm](https://github.com/braunsonm) mentioned at the beginning Sampler wouldn't work because at that time all the traces are empty. The only solutions I found would be to use `SpanExportingPredicate` or `SpamFilter`, (I only use opentelementry API so any micrometer option wouldn't work for me). To be able to filter all the child spans, first I need to keep track of the root.traceId for any trace that I want to filter, and then make sure I also filter all the spans with parent equals any filtered trace. So fine, I implemented that, also a mechanism to clean up old traceIds that are too old and I managed to get something together, which seems to do the trick, until... I realized that the `SpanExportingPredicate` receives the child spans first and then at the end receive the root trace 🤦 So now, I don't have any way of knowing if a child span should be filtered because I would only see the root trace when it's too late. I'm sure something must be wrong in my code but couldn't figure out what's going on from here.
> 
> Is this by design? Am I doing anything wrong? it seems to complicated for what it should really is 🤔

having the same issue filtering all child spans

**Comment by jonatan-ivanov** [comment]
Do you use the OpenTelementry API exclusively like the comment says that you quoted?
If so, I'm not sure what can be done in Spring Boot or in Micrometer, I think you should open an issue in OpenTelemetry instead. If you use Micrometer's Observation API, there are solutions above in the comments.

**Comment by diukarev** [comment]
> Write an ObservationPredicate and filter out the Observation: this will also filter out metrics.
> Write a SpanExportingPredicate (see: SpanIgnoringSpanExportingPredicate): this will only filter out spans and leaves metrics alone.

We need metrics data, so ObservationPredicate is not a variant. 
The problem with SpanExportingPredicate is that it ignores only individual spans. 

And as far as I understand, ObservationFilter will also filter out BOTH metrics AND traces

ps: upt: this is correct. currently there is no easy way to remove children
