### ISSUE TITLE
LiveReload does not work with springmvc-mustache

### ISSUE THREAD

**Issue by hygl** [spring-projects/spring-boot#3442]
LiveReload does not work with springmvc-mustache (https://github.com/mjeanroy/springmvc-mustache) with handlebars.java. It does work with spring-boot-mustache, but I need some of the springmvc-mustcahe features. 

Please have a look at this example project: https://github.com/hygl/spring-boot-mustache-devtools

**Comment by snicoll** [comment]
I think there is a misunderstanding, see [the conversation on Twitter](https://twitter.com/snicoll/status/618757873477263360). I asked you to open an issue regarding the features that prevented you to use Spring Boot's support. We're certainly not going to be able to fix whatever prevents LiveReload to work on that project!

**Comment by dsyer** [comment]
Since springmvc-mustache is nothing to do with this project, I suggest you take it up there and come back to this if you feel there is something blocking in Spring Boot, If, on the other hand, you just want new features in Spring Boot (e.g. whatever feature you like in springmvc-mustache that we don't have here), then please provide more details.

**Comment by hygl** [comment]
Ok, the feature I needed  (default layout) is not provided by jmustache, but by the springmvc-mustache binding with a different mustache implementation (https://github.com/jknack/handlebars.java). Since I want to switch to thymeleaf anyway, I will close this issue.
