### ISSUE TITLE
When using version 3.0.3 of the Spring Boot starter web, the version of Spring Core is 5.3.24 instead of the expected 6.0.5

### ISSUE THREAD

**Issue by anasdallah** [spring-projects/spring-boot#34479]
I'm using Spring Boot 3.0.3 and I've noticed that while the spring-boot-starter-parent dependency has version 3.0.3, the spring-core and spring-web dependencies have version 5.3.24 instead of 6.0.5. I'm using modules where the parent of the parent pom is spring-boot-starter-parent 3.0.3 and the parent of the child poms is the BOM pom file. Why is this happening and how can I ensure that all dependencies use the latest version of Spring Core?

How can I auto-configure the spring-core dependency version to 6.0.5 in my Spring Boot project without manually adding it to the pom.xml file

**Comment by wilkinsona** [comment]
Something is overriding Spring Boot's dependency management and downgrading the versions that would be provided by default. We can't tell why that is happening without seeing all of the relevant pom files.

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please follow up by asking a question on Stack Overflow and include all of the pom files involved so that those trying to help you have all the information needed to do so.
