### ISSUE TITLE
Update expected size of the jar file in the first application getting started documentation

### ISSUE THREAD

**Issue by tehnodev** [spring-projects/spring-boot#34514]
In section [Creating an Executable Jar](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started.html#getting-started.first-application.executable-jar) after "mvn package" command output example is text
```
The file should be around 10 MB in size.
```
Compiled example jar on java 17.0.6 is 17.6 MB, so maybe documentation should state around 18 MB in size

**Comment by wilkinsona** [comment]
Thanks for spotting this. I suspect that documentation was written around Spring Boot 1.0, if not even earlier and things have changed quite a bit since then. One of the most notable changes is that `spring-boot-starter-web` now includes Jackson by default. Other than that, much of the increase is accounted for by various modules increasing in size which all adds up.
