### ISSUE TITLE
Unable to create SAAJ meta-factory when mvn spring-boot:run

### ISSUE THREAD

**Issue by pcgeng** [spring-projects/spring-boot#34512]
Hi Spring Boot Team,

After upgrading spring boot to 3.0.3, we still cannot run the local service with `mvn spring-boot:run`, the log shows `org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name xxx... javax.xml.soap.SOAPException: Unable to create SAAJ meta-factory: Provider com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl not found`.

I have grabbed the error logs and attached here: [error_log.txt](https://github.com/spring-projects/spring-boot/files/10919454/error_log.txt)

**Comment by wilkinsona** [comment]
I suspect that this is due to changes in the JDK rather than Spring Boot. Specifically, `com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl` was part of the JDK in Java 8 but was then removed as part of its modularisation in Java 9. If you've moved from Java 8 to Java 17 as part of your Spring Boot upgrade, you'll need to add a dependency. Various options are discussed in [this question on Stack Overflow](https://stackoverflow.com/questions/47887047/java-com-sun-xml-internal-messaging-saaj-soap-saajmetafactoryimpl-not-found).

If this does not help and you believe that Spring Boot actually is the cause of the problem, please provide a complete yet minimal sample that shows this to be that case. We can then re-open the issue and take another look.

**Comment by pcgeng** [comment]
@wilkinsona Thanks, I will check the solutions.
