### ISSUE TITLE
Configure exception resolver for `@GraphQlExceptionHandler` methods

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-boot#34526]
`@GraphQlExceptionHandler` methods declared in controllers or `@ControllerAdvice` are now supported as of https://github.com/spring-projects/spring-graphql/issues/160 as a built-in feature of `AnnotatedControllerConfigurer`, and this is automatically applied to controller method invocations with no further configuration needed. 

To apply `@ControllerAdvice` exception handling to other (non-controller) `DataFetcher` implementations like `QueryDslDataFetcher`, `QueryByExampleDataFetcher`, and others, it is necessary to [obtain a DataFetcherExceptionResolver](https://github.com/spring-projects/spring-graphql/blob/287dab03e7b4db0f183c736623c0b096a95d86b0/spring-graphql/src/main/java/org/springframework/graphql/data/method/annotation/support/AnnotatedControllerConfigurer.java#L177-L194) from `AnnotatedControllerConfigurer` and [plug that into](https://github.com/spring-projects/spring-boot/blob/bf7c814dac402579e8d17b2b3b1e4e711294a76c/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/graphql/GraphQlAutoConfiguration.java#L91) the `GraphQlSource` builder, and so a small update in the Boot starter is required for this.

**Comment by wilkinsona** [comment]
This change, assuming I have implemented it as intended, seems to break handling of `AccessDeniedException` for which there's no `@GraphQlExceptionHandler` method. Rather than the exception reaching `SecurityDataFetcherExceptionResolver`, `AnnotatedControllerExceptionResolver` aborts the resolution by returning `Mono.error(ex)` because `methodHolder` is `null`:

```java
if (methodHolder == null) {
    return Mono.error(ex);
}
```

Perhaps it wouldn't be a problem if `SecurityDataFetcherExceptionResolver` was called first but it does not appear to be ordered so I can't see how to ensure that `AnnotatedControllerExceptionResolver` goes after it. I'm also not sure that's desirable as it would then prevent a `@GraphQlExceptionHandler` method for `AccessDeniedException` from overriding Security's resolver.

**Comment by rstoyanchev** [comment]
A `DataFetcherExceptionResolver` can leave the exception unresolved and yield to other resolvers, and that's the intent with `Mono.error(ex)`, if we don't find a suitable annotated exception handler, let it pass further down the chain. The contract though says it [should be an empty Mono](https://github.com/spring-projects/spring-graphql/blob/698713ab34c941b759ad91aeab36fc464381e6eb/spring-graphql/src/main/java/org/springframework/graphql/execution/DataFetcherExceptionResolver.java#L57-L61), so that looks like a bug.

`AnnotatedControllerExceptionResolver` is also used at the point of controller method invocation where we know which controller method raised the exception, and at that level we want to propagate the error further. At the level of a `DataFetcherExceptionResolver` however it should return an empty `Mono`. 

I'll reopen https://github.com/spring-projects/spring-graphql/issues/160 to fix this. Thanks for the timely feedback!
