### ISSUE TITLE
Document deprecation of `spring.view.suffix`

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-boot#3458]
I wonder if we can add a note to the reference doc, e.g. at:

http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-customize-view-resolvers

to illustrate the change from:

* `spring.view.prefix` --> `spring.mvc.view.prefix`
* `spring.view.suffix` --> `spring.mvc.view.suffix`

Related to:

https://github.com/spring-projects/spring-boot/issues/3278
https://github.com/spring-projects/spring-boot/issues/3250

**Comment by philwebb** [comment]
I've been trying not to introduce too much history into document. The Spring Framework reference guide suffers a lot from "Since 2.5 ...." type statements which just end up making things harder to read if you're using the latest generation.

That's one of the main reasons I didn't add a "What's New" section either and tried to keep the update instruction in the wiki.

Do you think we need to add that because things break during the upgrade?

**Comment by snicoll** [comment]
For the record, the old values should still work. If they don't please provide a sample project that shows the problem. Besides, those keys are now shown as deprecated in content assistance so I really don't think we should go any further.
