### ISSUE TITLE
Mark Freemarker and spring-boot-starter-freemarker are not Spring Boot 3 compatible yet because using jakarta instead javax.

### ISSUE THREAD

**Issue by damir78** [spring-projects/spring-boot#34637]
The current  spring-boot-starter-freemarker based on spring boot 3.x.x version is not compatible, because the used freemarker 2.3.32 is still using javax.* (for example javax.servlet) instead jakarta.* ( for example jakarta.servlet)
Pls mark Freemarker and  spring-boot-starter-freemarker are compatible with spring boot 3.

**Comment by damir78** [comment]
For example: open Freemarker 2.3.32: https://github.com/apache/freemarker/blob/v2.3.32/src/main/java/freemarker/ext/servlet/HttpRequestHashModel.java

**Comment by wilkinsona** [comment]
FreeMarker isn't solely for web applications which is why `spring-boot-starter-freemarker` does not depend on `spring-boot-starter-web`. Furthermore, you can still use FreeMarker in a Spring Boot 3 web application as shown by our [web FreeMarker smoke test](https://github.com/spring-projects/spring-boot/tree/4d78125bcc19043b406884f85c00924e85e79279/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-freemarker) as you don't have to use its Servlet integration.
