### ISSUE TITLE
Allow changes outside of the classpath to trigger a live reload

### ISSUE THREAD

**Issue by joowh85** [spring-projects/spring-boot#3469]
The devtools's livereload does not working when use the bertramdev asset-pipeline-core.

**Comment by snicoll** [comment]
Hey, can you provide a bit more details? In particular your Spring Boot version, the environment you're using and how you change your files. A sample that reproduces the issue is of course even better.

**Comment by joowh85** [comment]
Sure, 

Here is the my github repository URL.

git@github.com:joowh85/devtools-issues.git

The problem is a Devtools does not detects ${workingdir}/src/assets folder

**Comment by philwebb** [comment]
How are you running your application? Do you start it from the IDE? What are you doing to trigger the reload?

**Comment by joowh85** [comment]
Q1. Do you start it from the IDE? 
Yes, 
I start it from the Intellij IDE and the project launched via main menu -> run-> gradle bootRun.

Q2. What are you doing to trigger the reload?
CTRL+S

Thanks @philwebb.

**Comment by snicoll** [comment]
What does `CTRL-S` for you exactly? Are you an eclipse user by any chance? There is no save action in IJ. Make is actually refreshing the build and that should trigger the livereload (this works for me).

**Comment by joowh85** [comment]
1. Clone the my repository.
 https://github.com/joowh85/devtools-issues

2. Run.

3. Launch the Web browser, http://localhost:8080

4-1. Modify /src/main/resources/index.html

==> Livereload works correctly, and the Web browser will refreshes automatically.

4-2 Modify /src/assets/stylesheets/main.less

==> Nothing happen.

**Comment by snicoll** [comment]
I am not asking for a way to reproduce, ATL-S isn't doing what you think it's doing. In Eclipse, ALT-S runs a compilation update and actually copies updated files to the target location. ALT-S in IJ does "nothing" (since it auto-save by default). "Make Project" is the closest alternative to it. 

If you're confused by that, you could map the shortcut for "Make Project" to "ALT-S". Have you tried that?

**Comment by joowh85** [comment]
Of course the build command will refreshes everything. 
And spend a lot of time.
Is there another solution?

**Comment by snicoll** [comment]
It will only refresh if it has to. But granted, everything works but LiveReload in this case.

**Comment by wilkinsona** [comment]
It works for changes in `src/main/resources` as `bootRun` puts that folder on the classpath. The dev tools watch the classpath for changes and trigger a live reload when required. It doesn't work for changes beneath `src/assets` as this directory is not on the classpath and nor should it be. This directory is only significant due to the use of the asset pipeline which compiles less into css on demand.

Here's a workaround/hack that adds `src/assets` to the classpath when the `bootRun` task runs:

```groovy
bootRun.doFirst {
    sourceSets {
        main {
            resources {
                srcDir "src/assets"
            }
        }
    }
}
```

This is Gradle specific, though. It'd be nice to have a more general purpose solution. For example, we could provide a new property that allows the configuration of paths outside of the classpath that should be watched.
