### ISSUE TITLE
Liquibase 3.4.0 breaks logging management via application.properties

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#3470]
After upgrading Liquibase to 3.4.0 (#3389) I can't manage liquibase logging and I always see the logs in console. When I downgrade to 3.3.5 it's working.

**Comment by wilkinsona** [comment]
Liquibase 3.4 performs some logging during the static initialisation of `ServiceLocator`. This pollutes `LogFactory.loggers` with a `DefaultLogger` before Boot gets a chance to register its custom `Logger` implementation. Ideally, this would be fixed by a change in Liquibase to restore its old behaviour. Failing that, we could resort to using reflection to clear `LogFactory.loggers` once we've configured the service locator.

**Comment by wilkinsona** [comment]
I've opened [CORE-2436](https://liquibase.jira.com/browse/CORE-2436). I'd like to see what the Liquibase team says before deciding how to proceed.

**Comment by wilkinsona** [comment]
CORE-2436 has been assigned to Liquibase 3.4.1. No release date as yet.

**Comment by php-coder** [comment]
It has been released: http://www.liquibase.org/2015/07/liquibase-3-4-1-released.html

**Comment by wilkinsona** [comment]
Unfortunately, the change made for CORE-2436 doesn't fix the problem that I reported. The creation and registration of our custom service locator still causes `LogFactory.loggers` to become polluted.
