### ISSUE TITLE
General Feedback about Service Connections

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#34760]
First of all, thanks for introducing this feature. I already started using it in my [examples](https://github.com/eddumelendez/testcontainers-samples)

Also, sorry for writing all the way in this issue, but I think it would be much better to understand how to proceed instead of opening many issues/PRs

1. 🐛 bug? The only examples I couldn't migrate were related to Yugabyte because of the driver. It's missing [here](https://github.com/spring-projects/spring-boot/blob/d09ac00824296beb0f6bf888701daa9bd41e01df/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration.java#L57-L65)

1. 🆕 I would like to ask if you will introduce `RedpandaServiceConnection`. Redpanda offers a Kafka-compatible API, and it is very fast. I have almost everything to submit a PR, but I want to ask first :)

1. 🔜 🤞🏽 When the time comes, I think adding support for Pulsar would be great. I just created an issue in their repo in case the autoconfiguration support in spring-boot takes longer https://github.com/spring-projects-experimental/spring-pulsar/issues/384
1. ❓ What's the vision of ServiceConnections beyond spring-boot? I mean support in spring-cloud. I think this can be used in spring-cloud-consul, spring-cloud-vault, and spring-cloud-zookeeper. I ask because the Config Data approach offered by those projects could benefit from it. Currently, [system properties](https://github.com/eddumelendez/testcontainers-samples/blob/main/spring-cloud-consul/src/test/java/com/example/springcloudconsul/SpringCloudConsulApplicationTests.java#L29-L30) needs to be added or registered through `@ContextConfiguration(initializers = ...)` which with ServiceConnections could possible be fixed too.

1. ❓ Is `RedisServiceConnection` from `org.springframework.boot.test.autoconfigure.data.redis` instead of `org.springframework.boot.test.autoconfigure.redis`?. Asking for consistency reasons

1. ❓ Given the current state of the art, can we introduce `HazelcastServiceConnection` expecting a `GenericContainer` similar to Redis? Given the approach to introducing those new integrations, the project should be ready to accept them if needed.

If 1, 2, 5, and 6 make sense to you, I can probably help with some or pair with someone else who wants to contribute. I guess a couple of those issues will be fixed by the team 😀 

Once again, thank you so much for adding this feature.

**Comment by quaff** [comment]
> 1. 🐛 bug? The only examples I couldn't migrate were related to Yugabyte because of the driver. It's missing [here](https://github.com/spring-projects/spring-boot/blob/d09ac00824296beb0f6bf888701daa9bd41e01df/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration.java#L57-L65)

Why would you configure jdbc driver manually? It's the responsibility of `java.sql.DriverManager` to load proper driver for specific jdbc url.

**Comment by wilkinsona** [comment]
This is great feedback. Thanks very much, @eddumelendez.

1. Yes, this is a bug. Thanks for catching it. I have opened https://github.com/spring-projects/spring-boot/issues/34777
2. We can certainly consider it. It feels like it's within scope given that Spring Boot supports Kafka and Testcontainers, and Testcontainers has a Redpanda module. If you have the code pretty much ready, please feel free to submit a PR. Alternatively, if you'd prefer not to spend any more time on it just yet, please open a separate issue that we can evaluate before potentially proceeding with a PR
3. +1
4. It's early days but we hope that service connections will be useful in Spring Cloud and beyond. For example, Spring Cloud Bindings may be able to define service connections rather than property sources.
5. Our auto-configuration for Redis depends on Spring Data Redis as it uses `org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory` or `org.springframework.data.redis.connection.jedis.JedisConnectionFactory`. The property prefix (`spring.data.redis`) and package names are intended to reflect this dependency
6. Hazelcast's an interesting one as we lean heavily on Hazelcast's configuration files and have very little in the way of our own configuration properties. It would be good to support service connections with Hazelcast, but I'm not yet sure how that should be implemented. I've https://github.com/spring-projects/spring-boot/issues/34778 so that we can start to explore things. If you have any suggestions, they'd definitely welcome on that issue.

**Comment by eddumelendez** [comment]
Before raising any PR. Does activemq and otlp service connections would be welcome? I think so but just wanted to confirm due to there is no specific testcontainers module but at least for otlp there is an official docker image.

**Comment by wilkinsona** [comment]
Thanks for the offer, @eddumelendez. We're aware of a few places where service connection support is missing. There's the two that you've already mentioned, Apache Artemis, and there may well be others. Pull requests would be welcome if you have the time. Thank you. Just to set expectations, with RC1 being released tomorrow, there's a high chance that any new support won't land until 3.2 now.

**Comment by eddumelendez** [comment]
Great! Yes, maybe we can create a list of those missing. You mean 3.1 next month, right?

So, probably this issue is already done. Please, feel free to close it and thanks for this feature again!

**Comment by wilkinsona** [comment]
After tomorrow's RC1 we will try not to add any new features. It may not be a complete freeze, but we generally only fix bugs, improve the documentation, and amend existing functionality in the RC phase. That means that any new service connection support may have to wait until work in 3.2 begins in the summer once 3.1 has shipped.

> So, probably this issue is already done. Please, feel free to close it and thanks for this feature again!

Thanks for the really timely feedback and your PRs. They're much appreciated.
