### ISSUE TITLE
authentication failed for https://repo.spring.io/libs-milestone/org/springframework/boot/spring-boot-starter-parent/3.1.0-M2/spring-boot-starter-parent-3.1.0-M2-site.xml, status: 401 Unauthorized

### ISSUE THREAD

**Issue by patpatpat123** [spring-projects/spring-boot#34805]
🐞 Bug report (please don't include this emoji/text, just add your details)
Downloaded a fresh Spring Boot 3.1.0-M2 repo from Josh's second favorite place on the web. 

it is just a "nothing-else-but-spring-boot-3.1.0-M2" app. We run maven site ```mvn site``` on it, and observe reproducible 100%

```
[INFO] Rendering site for default locale
Downloading from spring-libs-snapshot: https://repo.spring.io/libs-milestone/org/springframework/boot/spring-boot-starter-parent/3.1.0-M2/spring-boot-starter-parent-3.1.0-M2-site.xml
Downloading from spring-milestones: https://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-parent/3.1.0-M2/spring-boot-starter-parent-3.1.0-M2-site.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/3.1.0-M2/spring-boot-starter-parent-3.1.0-M2-site.xml
authentication failed for https://repo.spring.io/libs-milestone/org/springframework/boot/spring-boot-starter-parent/3.1.0-M2/spring-boot-starter-parent-3.1.0-M2-site.xml, status: 401 Unauthorized
```

Would it be possible to help on this issue please? We run maven site as part of our pipeline

**Comment by mdeinum** [comment]
You shouldn't be using the `https://repo.spring.io/libs-milestone` in your build but `https://repo.spring.io/milestone` instead.

See also [this announcement](https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023) explaining that only `/milestones` and `/snapshots` will be anonymously available. All others are closed for internal use and all other dependencies should be resolved through Maven Central.

**Comment by scottfrederick** [comment]
When selecting a milestone version like Spring Boot `3.1.0-M2`, Spring Initializr will add the Spring milestone repository to the build, with configuration like this in `pom.xml`: 

```
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
```

It appears you have that in your `pom.xml` based on this line in the output: 

```
Downloading from spring-milestones: https://repo.spring.io/milestone/...
```

You also have this line in your output, which appears to be something that was added to the `pom.xml` after it was generated by Spring Initializr: 

```
Downloading from spring-libs-snapshot: https://repo.spring.io/libs-milestone/...
```

As @mdeinum said, the `https://repo.spring.io/libs-milestone` can not be accessed without authentication, as it is not intended to be used externally. That's why you're getting the error `authentication failed for https://repo.spring.io/libs-milestone...`.

**Comment by patpatpat123** [comment]
Thank you @scottfrederick, thanks you @mdeinum, indeed, working now. Sorry for the trouble
