### ISSUE TITLE
how to ignore ping hello command 

### ISSUE THREAD

**Issue by huangmiao** [spring-projects/spring-boot#34806]
![image](https://user-images.githubusercontent.com/5791417/228454258-ddf63367-445c-4259-972d-038e0c24f6ab.png)
l don`t show ping hello command . set observationPredicate interceptor  aval

**Comment by huangmiao** [comment]
l use lettuce trace 
![Uploading image.png…]()

**Comment by scottfrederick** [comment]
Thanks for getting in touch. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. This feels like a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
