### ISSUE TITLE
Order WelcomePageHandlerMapping after WebMvc.fn's RouterFunctionMapping

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#34846]
When using WebMvc.fn, the order of the registered mapping is:

- `RequestMappingHandlerMapping` (order 0, set by Framework)
- `WelcomePageHandlerMapping` (order 2, set by Boot)
- `RouterFunctionMapping` (order 3, set by Framework)

Which leads to the surprising behavior that a `RouterFunction` define a user provided mapping on `/` to render a `index` template will be shadowed by `WelcomePageHandlerMapping` serving this template. In my case, that half broke the rendering by skipping the model attributes that were set in the handler.

After a discussion with the Spring Framework team, we are going to try to improve the consistency between WebFlux (which has `RouterFunctionMapping` before `RequestMappingHandlerMapping `) and  WebMvc (where this is the opposite) if possible (see https://github.com/spring-projects/spring-framework/issues/30278) but we can't change that in a 5.3 or 6.0 patch release.

But I think I would be great if possible to fix Spring Boot 3.0 and potentially 2.7 to have `WelcomePageHandlerMapping` after `RouterFunctionMapping`.

**Comment by wilkinsona** [comment]
I'm not sure that we can change this in a maintenance release for the same reasons that you don't want to re-order `RequestMappingHandlerMapping` and `RouterFunctionMapping` in a Framework maintenance release. With https://github.com/spring-projects/spring-framework/issues/30278 scheduled for Framework 6.1, I think we should schedule this for Boot 3.2.

I wonder if Framework 6.1 could consider introducing relative ordering support rather than relying on the current, rather brittle, absolute values? It's served us very well for Boot's auto-configuration.

**Comment by sdeleuze** [comment]
I will discuss that with the Framework team and let you know if the rest of the team is ok with that.

**Comment by philwebb** [comment]
@sdeleuze Any update from the Framework team?

**Comment by sdeleuze** [comment]
We have discussed this topic in this week Spring Framework team meeting, the follow-up discussion is still ongoing. I will post an update here as soon as we have reach a consensus (should happen shortly).

**Comment by bclozel** [comment]
I've tested successfully the Spring Framework change from spring-projects/spring-framework#30278 - the custom `RouterFunction` for the index page is properly ordered ahead of the welcome page support.

Let's rework this issue as a documentation one to properly document the ordering in the welcome page section of web frameworks.
