### ISSUE TITLE
How to enable jms support?

### ISSUE THREAD

**Issue by zhangpan-soft** [spring-projects/spring-boot#34897]
How to configure native support for jms under spring boot3. x Just like using the spring aot plugin directly Spring aot has plugins that support jms, but when I introduced the aot plugin in spring boot 3. x, native packaging would have issues, and I don't know how to do it

**Comment by scottfrederick** [comment]
Thanks for getting in touch. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. This feels like a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
