### ISSUE TITLE
RandomAccessDataFile failed security scans

### ISSUE THREAD

**Issue by marcuslange** [spring-projects/spring-boot#3490]
![05](https://cloud.githubusercontent.com/assets/2190106/8676893/c07dc58e-2a11-11e5-8453-6c426242eb6b.jpg)

**Comment by wilkinsona** [comment]
This is a false positive. An instance of `RandomAccessFile` is created in the constructor of `DataInputStream` on line 131 and stored in the `file` instance variable. It's then closed in the `close` method on line 201.

**Comment by wilkinsona** [comment]
I should also point out that this is standard behaviour for an `InputStream` in Java. The [javadoc for close()](http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#close()) states that it "releases any system resources associated with the stream". I'm not sure what scanning tool you're using, but perhaps you could suggest an improvement to the developers so that it avoids such false positives?

**Comment by marcuslange** [comment]
Thank you Andy, I'll report this to Veracode.
