### ISSUE TITLE
JarFileArchive failes security scans

### ISSUE THREAD

**Issue by marcuslange** [spring-projects/spring-boot#3491]
![06](https://cloud.githubusercontent.com/assets/2190106/8676963/1b30981c-2a12-11e5-9e2c-d83f72869501.jpg)

**Comment by wilkinsona** [comment]
The code in question is unpacking certain entries in an executable jar file into the configured temporary directory. This happens when a Spring Boot application is first launched. The scan report's rather vague, but I assume it's objecting to the use of `new File(System.getProperty("java.io.tmpdir"))` to create the temporary directory. The only other input in this area of the code is from the zip archive comments that are baked into the binary that's being run. The comments are produced by Spring Boot's build tooling. In neither case is the input what I would call user input, it's input from the developer or operator of the application.

If an attacker has managed to compromise a machine such that they can execute a Spring Boot application with the `java.io.tmpdir` system property configured differently, then there are many easier ways for them to do something malicious.
