### ISSUE TITLE
Support testcontainers lifecycle methods when used as Spring beans

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#35021]
In order to support local development using testcontainers we need to be able to start and stop containers from Spring's lifecycle.

**Comment by quaff** [comment]
`Startable` will be closed by spring since it extends `AutoCloseable`, do we need stop it here?
https://github.com/spring-projects/spring-boot/blob/3b92173a66b1fb58f1fb907cbce9d8ded606f996/spring-boot-project/spring-boot-testcontainers/src/main/java/org/springframework/boot/testcontainers/lifecycle/TestcontainersLifecycleBeanPostProcessor.java#L43-L47
