### ISSUE TITLE
Testcontainers JDBC URL doesn't work with Spring Boot 3.1.0-RC1

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#35109]
Previous to 3.1.0-RC1, tests using Testcontainers JDBC URL like the one below used to work. With 3.1.0-RC1, it doesn't work anymore

```java
@Testcontainers
@DataJdbcTest(properties = { "spring.datasource.url=jdbc:tc:postgresql:15-alpine:///" })
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class PostgresHostLessTest {

	@Autowired
	private JdbcTemplate jdbcTemplate;

	@Test
	void test() {
		var records = this.jdbcTemplate.queryForList("select count(*) from profile");
		assertThat(records).hasSize(1);
	}

}
```

Looks like liquibase and flyway are executing before the container is declared ready.

[This branch](https://github.com/eddumelendez/testcontainers-samples/tree/spring-boot-3.1.0-RC1) contains a lot of examples using JDBC. The snippet above belongs to [this test](https://github.com/eddumelendez/testcontainers-samples/blob/spring-boot-3.1.0-RC1/spring-boot-postgresql-flyway/src/test/java/com/example/springbootpostgresqlflyway/PostgresHostLessTest.java)

**Comment by sivaprasadreddy** [comment]
I bumped into the same issue with both 3.1.0-RC-1 and 3.1.0-SNAPSHOT.

Actually, with the special JDBC URL, one container is spinning up and flyway scripts are applied. But then another container is spinning up without flyway scripts applied and being used with the application.

Here is a reproducer: https://github.com/sivaprasadreddy/spring-boot-testcontainers-service-connection-flyway-issue/blob/main/src/test/java/com/sivalabs/boottcdevmode/domain/ProductRepositoryTest.java

**Comment by wilkinsona** [comment]
@sivaprasadreddy You seem to have duplicated the container configuration. Once in a `spring.datasource.url=jdbc:tc:` property and once in a container declared as a `@Bean`.

**Comment by wilkinsona** [comment]
Thanks, @eddumelendez. I've reproduced the problem. It's caused by `FlywayConnectionDetails` falling back to `JdbcConnectionDetails` so it appears that a Flway-specific URL has been configured. This results in a Flyway-specific `DataSource` being created and used to apply the migrations. The rest of the app then uses `jdbc:tc:postgresql:15-alpine:///` again which results in Testcontainers starting a second container. We need to remove the fallback so that `FlywayAutoConfiguration` uses the main `DataSource` rather than creating its own.
