### ISSUE TITLE
Upgrade to Kotlin 1.8.20 has broken Eclipse classpath

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#35101]
Commit 5c1c0a2b2e40fd78eb218a4180e8add1a4871729 is a relatively simple Kotlin upgrade but it appears to break Eclipse.

The classpath contains items for the `build` directory:

![Screenshot 2023-04-20 at 5 37 39 PM](https://user-images.githubusercontent.com/519772/233514370-aa251e5b-dbd2-40a7-a250-312d95feb3f7.png)

Changing `settings.gradle` to downgrade to 1.8.10 fixes the issue.

**Comment by wilkinsona** [comment]
I suspect this is caused by a combination of Kotlin's Gradle plugin and Buildship. @dsyer reported seeing something similar in a Java project using Boot's AOT plugin. In that case, I suspect a build ship bug as it wasn't deduplicating `bin/main` and `build/classes/main`. The former is the Eclipse-specific equivalent of the latter and only the former is needed.
