### ISSUE TITLE
Jansi version 2.4 not working in Tomcat on Windows10

### ISSUE THREAD

**Issue by leibf2099** [spring-projects/spring-boot#35115]
configure the console appender with `<withJansi>true</withJansi>` in logback .xml file ,Jansi version 2.4 not working in Tomcat on Windows 10, but version 1.8 is ok, why?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
