### ISSUE TITLE
Update a sample to showcase the use of configurationPropertiesValidator

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3513]
Custom validation of `@ConfigurationProperites` would deserve some love. We only have two occurrences of it: one in the code and one simple reference in the doc (sub-text: no test).

**Comment by lucassaldanha** [comment]
Sorry about the duplicated pull request. I rather force push the first one but I was unable to reopen it. I believe that I shouldn't have closed the PR at first... :P

**Comment by snicoll** [comment]
right :)

**Comment by zxkane** [comment]
The sample code looks fine, because the test code only creates a context then registering single configuration.

However it's not the real case when using spring boot application, there are other configurations from boot application, such as **org.springframework.boot.autoconfigure.web.ServerProperties**. The spring framework will try to the custom validator to validate all properties configuration, the runtime *IllegalStateException* will be thrown by framework.

It's easily to reproduce the runtime exception adding below line in the test code,

```java
this.context.register(TestConfiguration.class);
this.context.register(ServerProperties.class);
```

**Comment by snicoll** [comment]
Good catch, thanks!

**Comment by lucassaldanha** [comment]
I've updated my branch with some modifications to avoid this pitfall. 

@snicoll should I open a new PR?

**Comment by snicoll** [comment]
No but I don't like the change. 

Your `supports` implementation should filter what you want to validate instead of doing it in the `validate` method. This may not work as I remember someone complaining about it but I can't find the issue at the moment. Either way I'll have a look, thanks!

**Comment by snicoll** [comment]
It turns out this was a bug that I just fixed in #3581

**Comment by lucassaldanha** [comment]
That's why I haven't used the `support` to filter, because of the #3581 bug.  Nice to see it fixed! I'll update de code to use the `support` method correctly.

**Comment by snicoll** [comment]
what code? Your PR has already been merged. I've taken care of polishing that (amongst other things, check https://github.com/spring-projects/spring-boot/commit/80754d5cc2dd7375d41fda60a80a63be4df098dd

**Comment by lucassaldanha** [comment]
Ops... Good job! :)

**Comment by alwaysastudent** [comment]
How can we configure a validator per ConfigurationProperites ?

**Comment by philwebb** [comment]
@alwaysastudent This issue is closed and we prefer gitter or stack-overflow for questions. I don't think we currently offer a way to do what you'd like.
