### ISSUE TITLE
Spring boot security properties set doen't work

### ISSUE THREAD

**Issue by EdwardsBean** [spring-projects/spring-boot#3517]
I'm customizing security login page,but got problems with `csrf` and `x-frame-options`.
Would it be better if `csrf` and `x-frame-options` disable by default?

If I set
``` 
security.enable-csrf=false
security.headers.frame=false
```

in applicatoin.properties,spring security doesn't apply my setting.
But if I override  `WebSecurityConfigurerAdapter configure()`

```java
    @Override
    protected void configure(HttpSecurity http) throws Exception {
http
                .headers()
                .frameOptions()
                .disable()
                .and()
                .csrf()
                .disable()
...
}
```
It works.

By the way,I'm using spring-boot-starter-parent version of 1.3.0.M1

**Comment by dsyer** [comment]
Disabling security features by default sounds like a bad idea. We try to be a bit conservative, and not make it easy to shoot yourself in the foot. You wouldn't want to sail through to production without knowing about those features, would you?

**Comment by EdwardsBean** [comment]
@dsyer Ok,thanks.But why setttings in properties doesn't work?

**Comment by steve-oakey** [comment]
I also encountered this issue. `SpringBootWebSecurityConfiguration` checks if each property is set and calls the corresponding method on the `HeadersConfigurer`. However, the default for each of headers configs the `HeadersConfigurer` is true (all of the constructors call `enable()`), so the logic in `SpringBootWebSecurityConfiguration` should be reversed.

**Comment by wilkinsona** [comment]
In Spring Security 3 (used by Spring Boot 1.2 and earlier), adding the HSTS header writer has the side-effect of disabling the other default header writers. Spring Security 4 has changed this so that we get both the HSTS header writer and the default headers writers. While we'd ideally like Spring Boot 1.2 to have all the headers by default we can't change it as there's a high likelihood of it breaking existing apps. Spring Boot 1.3 needs to match Spring Security 4's behaviour – defaulting to all the headers being enabled – and allow `security.headers.*` to be used to turn them off.
