### ISSUE TITLE
Provide a Maven goal for running an application using a main class from src/test/java and the test runtime classpath

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#35202]
The `spring-boot:run` goal allows the test classpath to be used and for a custom main method to be specified but this currently doesn't work when using a `SpringApplication.from(...)` main method in `src/test/java`.

I think it's because we have the test dependencies but not our own test classes.

**Comment by snicoll** [comment]
Is this how we want to support this? If we had our test classes, then the main class detection logic will fail as it'll find two classes with a `main` method, isn't it?

Creating a new goal is relatively cheap (although the class hierarchy makes me cringe a bit already) but I don't know how I'd name it. Perhaps an attribute that states we're looking for the "test app"?

**Comment by snicoll** [comment]
(It probably isn't a task btw).

**Comment by snicoll** [comment]
Given #35248, it looks like a `spring-boot:test-run` goal could be an option.

**Comment by wilkinsona** [comment]
I have the beginnings of something in [this branch](https://github.com/wilkinsona/spring-boot/tree/gh-35202). There's a new `TestRunMojo` that, like `StartMojo` and `RunMojo`, extends `AbstractRunMojo`. Unfortunately, this means that the new `test-run` goal suffers from the problems described in https://github.com/spring-projects/spring-boot/issues/35250. It would be good to address those problems rather than adding to them but time is really tight.
