### ISSUE TITLE
Cannot configure actuator through environment variables in native images

### ISSUE THREAD

**Issue by adrien-ben** [spring-projects/spring-boot#35288]
Hi, I am updating some Springboot applications to run in native images.

These applications run on Kubernetes and use actuator's probes to check their status. To avoid exposing the actuator endpoints I change the management server port via the MANAGEMENT_SERVER_PORT environment variable.

Doing so doesn't seem to work in a native image (using native-maven-plugin) the MANAGEMENT_SERVER_PORT is ignored. But for example passing SPRING_PROFILES_ACTIVE works as expected. Also configuring the port by setting management.server.port in the properties file works fine.

Here is a basic example to reproduce the issue https://github.com/adrien-ben/springboot-native-actuator-env-var

**Comment by wilkinsona** [comment]
This is due to the closed-world assumptions that Graal makes when building the native image. Setting the management server port changes the application's beans and, [as described in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.introducing-graalvm-native-images.understanding-aot-processing) changing such properties at runtime with a native image is not supported.

> But for example passing `SPRING_PROFILES_ACTIVE` works as expected

It may change the profiles that are logged as active but it will not affect profile-specific beans.

> Also configuring the port by setting management.server.port in the properties file works fine.

This is the recommended approach. When declared in a properties file, the property can be found at build time and the use of the management server port is baked into the resulting native image. You could also use an environment variable, but it has to be set on the application during AOT processing as part of the native image being built rather than at runtime.

**Comment by adrien-ben** [comment]
Thanks for the answer. I didn't realize setting the port changed application's beans.

Also, setting a default value for `management.server.port` in the properties file then overriding it with  the environment variable `MANAGEMENT_SERVER_PORT` works.

**Comment by snicoll** [comment]
@adrien-ben setting a management port means that we're actually deploying an additional container. There's quite some additional infrastructure involved. Setting a port at build time when AOT runs allows to opt-in for that additional infrastructure.

**Comment by heruan** [comment]
@snicoll is it possible to hint the deployment of an additional container with an AOT processor, and still let the port be defined via an environment variable? I have the same native image on the same pod and I need the actuator on different ports.

**Comment by heruan** [comment]
I have tried with an `EnvironmentPostProcessor` to set the property for AOT, but looks like it's ignored. Since I'm configuring via a library, I cannot use `application.properties` or set the env for the image build command. Losing my head around this 😵‍💫

**Comment by snicoll** [comment]
> is it possible to hint the deployment of an additional container with an AOT processor, and still let the port be later set with an environment variable? I'm running the same native image as multiple instances on the same pod and I need the actuator on different ports.

Yes. The presence of the property is what's triggering the additional infrastructure. The value can then later be changed any of the usual ways. There's a comment above yours from someone who tried and that works. Please follow-up on StackOverflow for further questions.
