### ISSUE TITLE
actuator springboot shutdown 服务静默48小时后发起shutdown请求没有任何反应

### ISSUE THREAD

**Issue by briup01** [spring-projects/spring-boot#35359]
actuator springboot shutdown 服务静默48小时后发起shutdown请求没有任何反应,请问是有什么配置需要配置吗,当服务器48小时没有任何请求进来actuator/shutdown 变成不可用的请求

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/main/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
