### ISSUE TITLE
OtlpAutoConfiguration should check for presence of any`io.opentelemetry.sdk.trace.export.SpanExporter` instance for conditional bean creation

### ISSUE THREAD

**Issue by amithkumarg** [spring-projects/spring-boot#35409]
![image](https://github.com/spring-projects/spring-boot/assets/6676435/c347e5ec-edc7-403b-8367-7519b5750d58)
This `OtlpAutoConfiguration` is not full proof for scenarios where interface is used for `@Bean` creation. Its injecting`OtlpHttpSpanExporter` even though `OtlpGrpcSpanExporter` bean exists.

```
 @Bean
  public SpanExporter otlpExporter() {
    return OtlpGrpcSpanExporter.builder().setEndpoint(otlpGrpcSpanExporterEndpoint).build();
  }
```

**Comment by mhalbritter** [comment]
I'm not sure if I understand.

`org.springframework.boot.actuate.autoconfigure.tracing.otlp.OtlpAutoConfiguration#otlpHttpSpanExporter` backs off if there is a `OtlpHttpSpanExporter` or a `OtlpGrpcSpanExporter` bean already defined.

What is the problem you are observing? Could you maybe create a small sample which helps me to understand the problem?

**Comment by mhalbritter** [comment]
Is the problem that this auto-configuration doesn't back off if you're defining a `SpanExporter` (instead of `OtlpHttpSpanExporter`) yourself?

**Comment by amithkumarg** [comment]
> Is the problem that this auto-configuration doesn't back off if you're defining a `SpanExporter` (instead of `OtlpHttpSpanExporter`) yourself?

Yes that's right.

**Comment by quaff** [comment]
It should be `@ConditionalOnMissingBean(SpanExporter.class)`

**Comment by philwebb** [comment]
The current auto-configuration is designed to provide a `OtlpHttpSpanExporter` unless a user-defined `OtlpHttpSpanExporter` or `OtlpGrpcSpanExporter` is provided. All other `SpanExporter` beans are added to the `SpanProcessor` (see [`OpenTelemetryAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/b92de3404177718212187b2ef4fdc831836c3d8a/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/OpenTelemetryAutoConfiguration.java#L128-L137)).

@amithkumarg In your case I think the problem is your `@Bean` definition method. You currently have:

```java
@Bean
public SpanExporter otlpExporter() {
    return OtlpGrpcSpanExporter.builder().setEndpoint(otlpGrpcSpanExporterEndpoint).build();
}
```

It's best practice to always return the most specific type from a `@Bean` method. This allow Spring to reason about the instances that will be created when the method is actually invoked.

If you change the method to the following, I believe things will work as designed:

```java
@Bean
public OtlpGrpcSpanExporter otlpExporter() {
    return OtlpGrpcSpanExporter.builder().setEndpoint(otlpGrpcSpanExporterEndpoint).build();
}
```

**Comment by amithkumarg** [comment]
Yes, that's how I made it work, but good information with Best Practices when declaring Spring Bean, use specific type instead of interface
