### ISSUE TITLE
There is no way to customize defaultTyping for Jackson ObjectMapper

### ISSUE THREAD

**Issue by stepan-romankov** [spring-projects/spring-boot#3541]
The problem that you either can set enableDefaultTyping for ObjectMapper either use power of Jackson auto configuration, but not both.

**Comment by snicoll** [comment]
ping @sdeleuze

**Comment by sdeleuze** [comment]
@stepan-romankov I am not sure what you mean by "use power of Jackson auto configuration".

As described in the [Spring Boot reference documentation](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-customize-the-jackson-objectmapper), you can register an `ObjectMapper` bean that will be used in your application, so if you are using Jackson just for JSON serialization that should be ok for your use case.

If you are using also Jackson for XML serialization, indeed there is an issue since `Jackson2ObjectMapperBuilder` does not allow to set that property.

Default typing is a useful configuration property for polymorphic type handling, so I think I would be a good idea to add support for it in `Jackson2ObjectMapperBuilder`. Feel free to create an improvement request on [Spring Framework bugtracker](https://jira.spring.io/browse/SPR) for that.

**Comment by stepan-romankov** [comment]
Hi,

By that "use power of Jackson auto configuration" I mean to have ability to
configure ObjectMapper using properties in application.yml


Best regards,
Steve Romankov

On Thu, Jul 23, 2015 at 3:22 PM, Sébastien Deleuze <notifications@github.com

**Comment by sdeleuze** [comment]
I would say that for such advanced feature, the `@Bean` approach is relevant, `application.yml` is more for very widely used properties.

Any thoughts @wilkinsona @snicoll ?

**Comment by wilkinsona** [comment]
@sdeleuze I agree. Given that `defaultTyping` has to be configured with an instance of `TypeResolverBuilder`, the best that we could do would be to allow a class name to be configured and instantiate it using the default constructor which feels a little limited. That said, it would be useful to have the configuration available on `Jackson2ObjectMapperBuilder` so that it can be applied to all the `ObjectMapper` beans in the context, for example those created by Spring Data REST which we pass into the builder's `configure` method.

@stepan-romankov Whlle you can't configure defaultTyping via `application.properties`, you can still make use of auto-configuration by injecting the auto-configured `JacksonObjectMapperBuilder` into your application context and then using it to create an `ObjectMapper`:

```java
@Bean
public ObjectMapper jacksonObjectMapper(Jackson2ObjectMapperBuilder builder) {
    ObjectMapper objectMapper = builder.build();
    objectMapper.setDefaultTyping(new CustomTypeResolverBuilder());
    return objectMapper;
}
```

**Comment by stepan-romankov** [comment]
Hi Andy,

Yes! This is a good walk around. I some how haven't sought that it can be
so easy. So I can continue using spring boot auto configuration for Jackson
along with specific configuration for defaultTypeing. Thanks a lot and
looking forward to see this in config!


Best regards,
Steve Romankov

**Comment by wilkinsona** [comment]
@stepan-romankov 

> looking forward to see this in config

If that's something you'd like to see then don't forget, as requested by @sdeleuze, to [open a Spring Framework JIRA issue](https://jira.spring.io/browse/SPR) to add it to `Jackson2ObjectMapperBuilder`.

**Comment by wilkinsona** [comment]
I've opened [SPR-13569](https://jira.spring.io/browse/SPR-13569). If/when that's implemented there'll be nothing for us to do in Boot other than picking up the new version of Spring Framework.
