### ISSUE TITLE
Consistent Support Period across Spring, Spring Batch and Spring Boot

### ISSUE THREAD

**Issue by DhavalShewale** [spring-projects/spring-boot#35422]
Hi Team,

Can we pls have a consistent support period across Spring, Spring Batch and Spring Boot libraries.

Currently, spring libraries are marked EOL roughly after 24 months, spring batch is marked EOL roughly after 18 months and spring boot is marked EOL after 12 months.

As all libraries are dependent on each other, plus as there can be applications using different flavors of the library its difficult to plan periodic updates.

Can we pls have a uniform EOL support policy for all flavors of spring - Spring, Spring Batch, Spring Boot, Spring Cloud, etc. The support policy should align to the baseline framework i.e. Spring and we should support all flavors for upto 24 months.

Regards,
Dhaval

**Comment by wilkinsona** [comment]
Thanks for the feedback. We have a [uniform EOL support policy](https://tanzu.vmware.com/support/oss). Some projects may offer support that is more generous than is required by the official policy. Framework is one example as you have described above. We cannot offer the same support terms for Spring Boot as the two projects are quite different, in particular due to Spring Boot's extensive dependency management.

Every Spring project that's consumed by Spring Boot should have at least the same support terms as Spring Boot itself does. In this case, the projects you have mentioned all align with this policy. Spring Batch's 5.0.x branch is supported for longer than Spring Boot 3.0.x branch as Spring Batch does not yet have a 5.1.x release planned whereas Spring Boot 3.1.x will GA later this week.
