### ISSUE TITLE
Closing session due to exception for StandardWebSocketSession

### ISSUE THREAD

**Issue by FahrihFatahilah** [spring-projects/spring-boot#35660]
i develop project using spring websocket  ,but there is couple case this error is showing
and i don't know how this error happen

o.s.w.s.h.ExceptionWebSocketHandlerDecorator||ERROR|Closing session due to exception for StandardWebSocketSession[id=, uri=ws://]
    java.lang.IllegalStateException: WebSocketHandler not found for StandardWebSocketSession[id=eb047472-8d50-861a-138e-8c01c9729754, uri=]
        at org.springframework.web.socket.handler.PerConnectionWebSocketHandler.getHandler(PerConnectionWebSocketHandler.java:113)
        at org.springframework.web.socket.handler.PerConnectionWebSocketHandler.handleTransportError(PerConnectionWebSocketHandler.java:91)

what exactly cause of this problem, and how to handle it

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
