### ISSUE TITLE
Array of Array Object to Array of Array Objects maping not working

### ISSUE THREAD

**Issue by suresh-tonne** [spring-projects/spring-boot#35671]
When mapping the Json Array of array Objects to Array of Array Objects, its creating the different array of object on target Or another Array of Object with same array Name on target

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
