### ISSUE TITLE
Not a managed type: class com.suba.entities.configuration.KidsPackage

### ISSUE THREAD

**Issue by SubaSoundaryan96** [spring-projects/spring-boot#35722]
Here I'm trying to connect multiple datasources to my application with two databases (play_activity_service and console_service).
I had already created two configuration files for both play_activity_service and console_service. when I'm running the application it showing the below error

[org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] [] [] [] [] : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userInfoBuilder': Unsatisfied dependency expressed through field 'kidsPackageCache'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kidsPackageCache' defined in file [/home/subasoundar/Projects/play-activity-service/target/classes/com/suba/cache/service/KidsPackageCache.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kidsPackageRepository': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Not a managed type: class com.suba.entities.configuration.KidsPackage

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
