### ISSUE TITLE
Hibernate Schema Validation filter is not working after upgrading to Spring Boot >3 (v3.0.1 - v3.1)

### ISSUE THREAD

**Issue by SteMoeller** [spring-projects/spring-boot#35723]
Hi @all!

I am still missing a working schema filter as the issue here https://github.com/spring-projects/spring-boot/issues/33832 still exists. 

I can see that my schemafilter gets fetched and the method  SchemaFilter getValidateFilter()  is called during startup but the actual doing (calls to "includeTable(Table table)" never happens... 

So the SchemaProvider is called but never the custom schemaFilter classes... 

Last test was against hibernate core 6.2.2.Final which is a direct dependency from spring boot 3.1

I think I found the issue: in SchemaManagementToolCoordinator there is a method buildExecutionOptions which uses a hardcoded DefaultSchemaFilter.INSTANCE and not the configured custom schema filter...

As far as I understand the linked issue and examples from there, the problem is still the same... 

So using Spring boot =>3 does still not work with a custom schema filter...

**Comment by wilkinsona** [comment]
As explained in #33832, the cause of the problem is a bug in Hibernate. It's being tracked by https://hibernate.atlassian.net/browse/HBX-2476 which remains open so it is to be expected that the problem still exists. That said, I do wonder if Hibernate Tools (HBX) is the right project for the issue. It should perhaps be opened against [Hibernate ORM (HHH)](https://hibernate.atlassian.net/jira/software/c/projects/HHH/boards/31). If the problem is important to you and you have a minimal sample with which the Hibernate team can reproduce the problem, please consider opening an HHH issue and commenting here with a link to it.

**Comment by sbarsese** [comment]
@wilkinsona or anyone else - is there a way to pass this problem that is not create/delete the table in pre/post steps?
