### ISSUE TITLE
Spring Boot Actuator documentation misses management.endpoint.env.show-values property

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-boot#35917]
Hi

According to Spring Boot 3 release notes(https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#actuator-endpoints-sanitization):

`Since, the /env and /configprops endpoints can contains sensitive values, all values are always masked by default. This used to be case only for keys considered to be sensitive.`

However Actuator API documentation still shows unmasked values (https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#env):

```
 "properties" : {
      "java.specification.version" : {
        "value" : "17"
      },
```

Moreover it doesn't mention new property `management.endpoint.env.show-values` property that allows to unmask property values.

Another Actuator documentation(https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints) also doesn't mention new property and how to use it.

**Comment by scottfrederick** [comment]
The documentation for the `show-values` property is documented under How-To Guides, Actuator here: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.actuator.sanitize-sensitive-values. I agree this might be a bit hard to find since most other actuator configuration properties are documented under https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.
