### ISSUE TITLE
Could not resolve resources from spring.io 

### ISSUE THREAD

**Issue by michals96** [spring-projects/spring-boot#36042]
Hello,

has anyone faced an issue where gradle build cannot fetch artficats from repo spring io?

Sharing a stracktrace for reference

```
 Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.gradle:gradle-core:3.0.
     Required by:
         project : > cz.habarta.typescript-generator:typescript-generator-gradle-plugin:2.19.577
      > Could not resolve org.gradle:gradle-core:3.0.
         > Could not get resource 'https://repo.spring.io/plugins-release/org/gradle/gradle-core/3.0/gradle-core-3.0.pom'.
            > Could not GET 'https://repo.spring.io/plugins-release/org/gradle/gradle-core/3.0/gradle-core-3.0.pom'. Received status code 401 from server: 
```

The issue has surfaced in last 24 - 36 hours in a several projects that we are working on, we belive it is related to the artifact repository.

**Comment by wilkinsona** [comment]
Anonymous access to repo.spring.io has been restricted. Please see https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023 for details.

**Comment by michals96** [comment]
How come the issue surfaced just now in a few projects at once?

**Comment by wilkinsona** [comment]
After the various brownouts, which perhaps you just happened to miss, the permissions changes were only enforced permanently relatively recently. I would guess that this is the first time since then that you have built the projects without the dependency already being available in a local cache.

As explained in the blog post, you should not be resolving third-party dependencies (in this case a component of Gradle) from https://repo.spring.io. It is the permissions changes that are now in place that are causing the 401 (not authorized) response. It looks like you should be able to use https://repo.gradle.org/artifactory/libs-releases-local instead.
