### ISSUE TITLE
[BUG] The contentLength of ClasspathResource behaves differently in different systems

### ISSUE THREAD

**Issue by zdu-strong** [spring-projects/spring-boot#36065]
![bug](https://github.com/spring-projects/spring-boot/assets/48673442/a44c643c-7467-421c-9a2a-e9891a9b9fd1)

My repository: [https://github.com/zdu-strong/temp_classpath_resource](https://github.com/zdu-strong/temp_classpath_resource)
Environmental requirements:  java v17
Run tests:  ./mvn clean test
Run docker:  docker build .

**Comment by wilkinsona** [comment]
It's due to line endings. Linux uses `\n` but Windows uses `\r\n`. If you clone the repository on Windows such that line endings are converted, the two `\n` characters in the file are replaced with `\r\n`. This makes it two bytes longer.

If you have any further questions, please follow up on Stack Overflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/main/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
