### ISSUE TITLE
Jackson parameter names module

### ISSUE THREAD

**Issue by lpandzic** [spring-projects/spring-boot#3615]
https://github.com/FasterXML/jackson-module-parameter-names

After upgrade to jackson 2.6.0 in a java 8 environment this module can be used to construct classes using non default constructors for classes that have parameter names stored.
I suggest this module be added for JDK 8+ projects.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. The README describes the module as being experimental so I'm a little wary of adding support for it. That said, it does also say that the first official release was 2.4 so it's had some time to harden now.

Either way, if we were add support for registering the module, it probably belongs in Spring Framework's `Jackson2ObjectMapperBuilder`. That's where the JDK 8 datatype module is registered, for example. That do you think, @sdeleuze?

**Comment by sdeleuze** [comment]
I am also not sure this module is mature enough to be included by default yet, and it requires using the `-parameters` javac flag, but as part of our Spring 4 Java 8’s parameter name discovery support, I think this is something to consider at some point.

@lpandzic Could you please create a new issue on [Spring Framework bugtracker](https://jira.spring.io/browse/SPR) since as explained by @wilkinsona, this belongs in Spring Framework `Jackson2ObjectMapperBuilder`?

**Comment by lpandzic** [comment]
Ok, thanks for the info, I'll open the issue in Spring Framework bugtracker.
Just as a disclaimer, I'm the modules author and this note has been left in README.md by Tatu since its creation.
Nowadays it should be stable enough since it's pretty simple actually, most of the support for the module has been done in jackson-core.

**Comment by candrews** [comment]
For reference, the issue created is https://jira.spring.io/browse/SPR-13296
