### ISSUE TITLE
Root endpoint hijacked if Spring HATEOAS (without Spring Data Rest) is on the classpath

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3621]
I upgraded Spring Initializr on Spring Boot 1.3 SNAP and most of my integration tests broke. My root endpoint (that is serving both an HTML and a JSON representation) is now hidden behind the new MVC links endpoint.

I happen to use Spring HATEOAS to generate some HAL-compliant links in the meta-data but I am not using Spring Data REST (so the `NotSpringDataRestHomePageCondition` does not apply). It looks like we should either revisit that condition or disable the endpoint by default.

**Comment by dsyer** [comment]
Note: the problem only applies to API endpoints (not to static HTML). If there is an `index.html` (or other welcome page) then it is always served to browsers, I believe, and the `LinkMvcEndpoint` moves itself to `/links`.

The issue is that the `LinkMvcEndpoint` is (logically) an Actuator endpoint and hence is matched by the `EndpointHandlerMapping`, which in turn is (intentionally) ordered *before* the main `@RequestMapping` `HandlerMapping` (so that users can't inadvertently hide an Actuator endpoint - sort of the opposite of this problem).

I suppose the point of this discussion is that we feel in general that the home page (/) is more important than any other user-defined endpoint, and we shouldn't camp on it in case users want to provide it themselves. It's hard (impossible) to detect `@RequestMappings` in a `Condition` though, so the best way to fix things is probably to use an additional `HandlerMapping` with a higher `@Order` so that the user's endpoint takes precedence. The links endpoint will then completely disappear, unless the user configures its path (`endpoints.links.path`).

> Note: Spring Data REST uses a similar approach with a custom `HandlerMapping` that is lower priority than the user's endpoints to avoid camping on the home page itself.

**Comment by dsyer** [comment]
There's a draft (see https://github.com/dsyer/spring-boot/commit/fabb424d91078820f33047cdcc776343a0a0f01a) of something that works for all existing tests and removes the clunky test for Spring Data REST. Anyone want to do it differently?

**Comment by snicoll** [comment]
That actually fixed my original problem so sounds good to me.

**Comment by philwebb** [comment]
+ HalBrowser

**Comment by philwebb** [comment]
As discussed on the team call we've gone for explicit `/links` and `/hal` endpoints for now, rather than changing `/`. We can review again before RC1 if needed.

**Comment by philwebb** [comment]
Documentation probably needs updating before this can be closed, including docs in `spring-boot-actuator-docs`.

**Comment by snicoll** [comment]
Spring Initializr works fine with current Spring Boot master.
