### ISSUE TITLE
Unhandled exception 'java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by greatdeveloper1** [spring-projects/spring-boot#36222]
HEllo,
After migration an application from 2.6.6 to 2.7.11, and while performing a load test, a nasty error raised , that we never got before:
`"Unhandled exception 'java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached".

Also, i'm using a forkjoinpool as a threapool with a fixed size of 5. 
`

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
