### ISSUE TITLE
Error controller does not process a controller exception anymore

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3623]
No idea if this is a regression in Boot or in Spring Framework at this point.

Consider the following

```
@ResponseStatus(value = HttpStatus.NOT_ACCEPTABLE)
@SuppressWarnings("serial")
private static class NoReasonExpectedException extends RuntimeException {

	public NoReasonExpectedException(String message) {
		super(message);
	}
}
```

and a controller that throws such exception with a dummy message. With 1.2 you get the standard JSON output as expected. With master the controller does not seem to process the request at all (and therefore an empty response is sent).

Seems like `ResponseStatusExceptionResolver` is doing something different in 4.2 now.

**Comment by bclozel** [comment]
This is probably linked to [SPR-11193](https://jira.spring.io/browse/SPR-11193).

In a nutshell: previously, our `ResponseStatusExceptionResolver` would call `HttpServletResponse.sendError` in all cases, thus enforcing servlet error pages and breaking the API contract.

The new behavior:
* `@ResponseStatus(code=HttpStatus.NOT_ACCEPTABLE)` will only call `HttpServletResponse.setStatus`
* `@ResponseStatus(code=HttpStatus.NOT_ACCEPTABLE, reason="some reason")` will call `HttpServletResponse.sendError`

I guess that with the new first case, Boot's `ErrorController` is not called.

As pointed out by Stéphane, [this test case](https://github.com/spring-projects/spring-boot/blob/b6bacd5e8a6d19c800f6dd88249ada91d8da127b/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/BasicErrorControllerIntegrationTests.java#L154-L158) covers only the second use case, not the first.

**Comment by snicoll** [comment]
The first use case is "covered" [now](https://github.com/snicoll/spring-boot/commit/703a681e8d295abf97cb448d143e67fd8b2845f3#diff-5846bf7e76f54b226060f1aafeb125a9R177) - Fails with master, works with 1.2

**Comment by dsyer** [comment]
How do you want to do this then? I don't really know why an empty body is a useful default in Spring. Is there something else we can do to handle the response after the standard `ResponseStatusExceptionResolver`? Must we register a handler for every status code in 4xx?

**Comment by bclozel** [comment]
I've looked into this and I came up with two solutions.

### Adapt Boot behavior to handle those exceptions

In that particular use case, `HttpServletResponse.sendError` is not called, but Spring Framework's `DispatcherServlet.processHandlerException` notices that this exception has been handled but its body is empty, so it sets an attribute on the request with the exception itself `request.setAttribute(EXCEPTION_ATTRIBUTE, ex);`.

With that case, Boot could catch those cases (with a Filter or an Interceptor?) and re-map those responses to the errorController by calling `sendError`.

### Rollback SPR-11193 and clarify javadoc

This example shows some inconsistency in Spring Framework. `@ResponseStatus(code=HttpStatus.NOT_ACCEPTABLE, reason="some reason")` and `@ResponseStatus(code=HttpStatus.NOT_ACCEPTABLE)` are quite different and take opposite code paths. With those changes, applications with annotated Exceptions `@ResponseStatus(code=HttpStatus.NOT_ACCEPTABLE)` will get empty pages instead of container error pages.

I find that telling developers "`@ResponseStatus` is Servlet only, if you want to handle REST exceptions you'd better use `ResponseEntity`" sounds better than "`@ResponseStatus` deals differently with content negotiation and behaves differently depending on its attributes".
So right now I'm leaning towards using `sendError` in any case in `ResponseStatusExceptionResolver` and clearly stating that in `@ResponseStatus` javadoc as it reflects the behavior it had until now anyway and won't break applications.

What do you think @sdeleuze @rstoyanchev ?

**Comment by jhoeller** [comment]
From my perspective, this {{setStatus}} vs {{sendError}} arrangement felt awkward to begin with. I'd rather roll it back towards consistent {{sendError}} usage and recommend {{ResponseEntity}} instead.

**Comment by snicoll** [comment]
:+1:

**Comment by sdeleuze** [comment]
:+1:

**Comment by bclozel** [comment]
I've got a commit [ready for master on my fork](https://github.com/bclozel/spring-framework/tree/SPR-11193). Leaving this open for a while in case someone wants to comment on this.

**Comment by jhoeller** [comment]
Discussing this with Rossen, it seems that we have no choice but to revert the change and go with `sendError` consistently in `ResponseStatusExceptionResolver`. So Brian, could you please apply this to master and re-open / re-resolve SPR-13226 (previously marked as "Works as Designed" but I guess we changed our mind on that one now).

**Comment by bclozel** [comment]
This has been fixed in [SPR-13226](https://jira.spring.io/browse/SPR-13226) and [this commit](https://github.com/spring-projects/spring-framework/commit/80767ff6e9963761aa7e5516090fcda2c5a3bf74).

Thanks!

**Comment by snicoll** [comment]
I'd like to merge the additional test now it has been fixed in the framework.
