### ISSUE TITLE
spring-boot-sample-web-jsp fails to find jsp page when using spring-boot-starter-parent

### ISSUE THREAD

**Issue by andrewwwooster** [spring-projects/spring-boot#3644]
When I download spring-boot-samples and run spring-boot-sample-web-jsp all works well.  I navigate my browser to http://localhost:8080/ and see the correctly rendered jsp page.

However, when based on the comment in spring-boot-sample-web-jsp/pom.xml I switch the parent to:
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.2.5.RELEASE</version>
	<parent>
and re-run with this new parent id, the jsp page is not found.   Debugging confirms that the controller is being invoked, but when it forwards to the jsp the server returns with (type=Not Found, status=404).

**Comment by snicoll** [comment]
Please ask questions on StackOverflow rather than here. I am not sure I understand what you're trying to do. You are probably running the sample from master so changing the parent to 1.2.x in the sample itself is likely to work. 

The comment is not meant to tell you that you have to do that _in the sample_ but that your own application should either inherit from the `spring-boot-starter-parent` or import the `spring-boot-dependencies` BOM. You can try to create a fresh app from start.spring.io and replicate what's in the sample. If that does not work, please ask on stackoverflow and we'll have a look to your project.

**Comment by wilkinsona** [comment]
I can reproduce this following the instructions above, i.e. by changing:

```
<parent>
	<!-- Your own application should inherit from spring-boot-starter-parent -->
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-samples</artifactId>
	<version>1.3.0.BUILD-SNAPSHOT</version>
</parent>
```

To

```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.2.5.RELEASE</version>
</parent>
```

**Comment by wilkinsona** [comment]
The problem's due to `spring.view.*` being renamed to `spring.mvc.view.*` in 1.3. This is [described in 1.3's release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3.0-M2-Release-Notes#property-renames). By changing the version of the sample in master you're trying to use 1.3's configuration with 1.2's runtime.

Changing the parent and version to 1.2.5.RELEASE will work, but you should check out the 1.2.x branch first.
