### ISSUE TITLE
i upgraded spring boot application from 2.7.5 to 3.0.0 but am facing issue that test case are failing 

### ISSUE THREAD

**Issue by dgo312** [spring-projects/spring-boot#36480]

**Comment by dgo312** [comment]
DeliveryOptionsTests » NoClassDefFound javax/servlet/DispatcherType
[ERROR]   PaymentCalculationTests » NoClassDefFound Could not initialize class com.githu...
[ERROR]   TeliaFinanceTests » NoClassDefFound Could not initialize class com.github.toma

**Comment by mhalbritter** [comment]
Looks like you have a dependency in there which uses javax. Spring Boot 3.0 migrated to teh Jakarta namespace. It feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that
other people can find it) or add some more details if you feel this is a genuine bug.
