### ISSUE TITLE
Actuator JMX endpoint output format

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3658]
The actuator JMX endpoints return what seems to be valid JSON at first glance but it isn't.  Endpoints such as the `/beans` one return actual JSON that is parsed as a list. 

It would be nice if the JMX endpoint would return a predictive format. Some users would like the output to be pretty printed as well.

See [this stackoverflow thread](http://stackoverflow.com/questions/31755247/pretty-print-output-of-spring-boot-actuator-jmx-endpoints/)

**Comment by bcalmac** [comment]
I would like to add that the same applies to the CRaSH endpoints. There it would be nice to be pretty-printed by default, because CRaSH is truly interactive.

**Comment by bcalmac** [comment]
I looked at the code and it doesn't seem like this would be an easy/desirable change. BeansEndpoint returns List<Object> and then it's up to WebMVC/JMX/CRaSH to convert the objects to a textual representation. WebMVC picks JSON by default, but JMX and CRaSH just do a toString().

**Comment by edudar** [comment]
Can `javax.management.openmbean.CompositeDataSupport` be considered instead of JSON as natively supported by JMX? The point here is that integration of free-form JSON serialized to string with 3rd-party monitoring/alerting tool is complicated and usually requires custom adoption while native `CompositeDataSupport` usually supported of the box.

**Comment by philwebb** [comment]
This should be fixed as of 2.0
