### ISSUE TITLE
Reference docs should contain a section on how to override dependency properties to upgrade to newer version

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#3695]
If a user want's to use a newer version of a library Boot uses, in Maven she can just set the property defined in `spring-boot-dependencies` and the version will upgraded. This for example will allow users of Spring Boot 1.2.x to use Spring Data Fowler with it (default is Evans).

```xml
<spring-data-releasetrain.version>Fowler-SR2</spring-data-releasetrain.version>
```

I could find this in the reference documentation. A similar (but slightly more involved) way of overriding dependencies is available for Gradle. Would be cool if this was documented, too.

**Comment by wilkinsona** [comment]
I think we've already got this covered (in master at least): http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-customize-dependency-versions

**Comment by snicoll** [comment]
Can we keep this issue open still and rescope it a bit? I couldn't find an obvious section that states why users don't need to specify a version for the versions that we manage. A dedicated section with an obvious title would help.

For instance, I couldn't find a section that explains why Maven users do not need to specify a version in their project (and how it works). Showing in detail how they can import the bom rather than inheriting from the `spring-boot-starter-parent` would help as well.

**Comment by wilkinsona** [comment]
@snicoll I like it

**Comment by olivergierke** [comment]
I agree that while the information is there, it's scattered amongst different sections in the reference docs. +1 on a dedicated section on dependency management for Boot managed libraries somewhere near the first section that discusses Boot + Maven / Gradle interaction, as this is what users will end up finding and might not be aware there's yet another section they could've found and end up thinking that part is missing entirely (just as I did :) )
