### ISSUE TITLE
/hal and /links should not be separate endpoints

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#3696]
`/links` currently serves a HAL-formatted JSON responses providing links to the actuator's other endpoints. `/hal` serves HTML for the HAL browser. I find the name of the `/hal` endpoint confusing as both it and `/links` are related to HAL. Furthermore, the purpose of these two endpoints is the same – to provide information about the actuator's other endpoints – but the former is intended for machine clients and the later for humans. I believe it would be better to provide a single well-known entry point that then uses content negotiation to decide what to send back. I'm not sure that its path should mention hal as that's a detail of the content negotiation and we may want to add other response formats in the future.

I propose:

 - Combine `/hal` and `/links` into a single endpoint that uses content negotiation
 - Don't include "hal" in the new endpoint's path. Sticking with one of the current names, perhaps it should be called "links", although I'm not sure I like that...

**Comment by snicoll** [comment]
I am ok with `/links` but my vote goes for `/actuator` for two reasons:

1. If we decide to set a default `management-path` in a future release of Spring Boot, the obvious choice will probably be `/actuator` (as `/admin` is typically used by applications)
2. If we have a default `management-path` then it totally makes sense to make that stuff the root by default (since it's not stealing the root endpoint anymore)
1. We can name it _the_ `ActuatorEndpoint` and if users decide to set it to the _root_ then it does exactly what it says (`endpoints.actuator.path=/`).

It's of course all theoretical but naming it today `/actuator` will fit nicely with this future plan. And if we decide not to do it, then I think it's still an obvious/acceptable link. It also fit quite well in the "augmented' version when Spring Data REST is used.

**Comment by wilkinsona** [comment]
I've got [a branch](https://github.com/wilkinsona/spring-boot/tree/gh-3696) that combines the `/hal` and `/links` endpoints into a single `/actuator` endpoint.

As things stand, if you configure `management.context-path` the `/actuator` endpoint will move to `/` beneath that path, e.g. `management.context-path=management` will move the actuator endpoint to `/management/`. As things stand, that trailing slash is _required_ – accessing `/management` will result in a 404. This needs to be fixed as the `self` link for `/management/` links to `/management`.

**Comment by wilkinsona** [comment]
A couple of things still need to be addressed:

 - The actuator endpoint needs to serve JSON to a browser when HAL browser isn't available. It currently responds with a 406.
 - The actuator's docs need to be updated to reflect these changes
