### ISSUE TITLE
Liquibase / Long running DB scripts

### ISSUE THREAD

**Issue by janchristian-haddorp** [spring-projects/spring-boot#37082]
DB changes managed by Liquibase are executed on application start. This is totally fine for fast running changes.

Some changes, e.g. adding DB index, can run for a while. If running application on K8s it happens that liveness/readyness checks trigger an application restart. In this case Liquibase causes an end-less loop.

To make it clear this is not a Liquibase issue.

However, is there a pattern how to manage long running scripts with Liquibase? Any examples?
One approach might be splitting the the changes in two groups:
- Execute before application start.
- Or execute while application is already up and running.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
