### ISSUE TITLE
getWriter() has already been called for this response

### ISSUE THREAD

**Issue by 1760793695** [spring-projects/spring-boot#37127]
Why can I only use response.getOutputStream() in a project, when I use response.getWriter(), it always throws exception, but I can use response.getWriter() in a old project, and after i used this outputstream, i can not close it, because if i close it, my controller can not response anything, i think this is to terrible

**Comment by scottfrederick** [comment]
Thanks for getting in touch. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. This feels like a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by 1760793695** [comment]
ok，i move it to stackoverflow，thank you



---Original---
From: "Scott ***@***.***&gt;
Date: Wed, Aug 30, 2023 10:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [spring-projects/spring-boot] getWriter() has already been calledfor this response (Issue #37127)




 
Thanks for getting in touch. As mentioned in the guidelines for contributing, we prefer to use GitHub issues only for bugs and enhancements. This feels like a question that would be better suited to Stack Overflow. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
