### ISSUE TITLE
Starter POM for Reactor

### ISSUE THREAD

**Issue by sleepiejohn** [spring-projects/spring-boot#3713]
Since Spring Boot supports auto configuration for [Reactor](https://github.com/reactor/reactor), wouldn't be easier to get started with a new project with a already defined set of dependencies ?
But due the lack of artifacts and combinations of reactor components, such as, `spring` modules, `stream's` `groovy support`, should we restrict with some basic pom and let user add the complements, or create something like `spring-boot-starter-reactor` for core's, `spring-boot-starter-reactor-spring`, `spring-boot-starter-reactor-net` ?

**Comment by snicoll** [comment]
We're usually against the creation of several starters for the same thing. We create one "base" starter to get you started and ask you to add extra optional dependencies for more _advanced_ feature.

Ping @smaldini @wilkinsona

**Comment by smaldini** [comment]
I understand the concern indeed as we follow a similar policy of "pick it if you need" rather than a monoblock reactor framework module and so far there's only support for a couple features from reactor in the auto config. We're trying to rationalize a few things already for spring 5, but runtime modules like reactor-net would probably still need some kind of support/detection anyway, since it needs a compile time dep on reactor-core and reactive-streams specification and an optional dep on Netty 4, that should probably pulled as well in that scenario.

**Comment by philwebb** [comment]
I think we'll wait until the next release of Reactor and/or Spring 5 before we add this. For now adding the individual dependencies isn't too onerous.

**Comment by bclozel** [comment]
We've added the `spring-boot-starter-reactor-netty` since - this brings both `reactor-core` and `reactor-netty`. We think it's the right granularity for now; we'll see if we'll need more in the future with potential new modules in Spring Framework and Reactor.

Fixed with 0aaea05a4b5e3e3d9f60bcb69fd10bc7512ccfa2
