### ISSUE TITLE
Database connectivity issue

### ISSUE THREAD

**Issue by magadummanjunath** [spring-projects/spring-boot#37176]
Many times auto-configurations in spring boot are not working.Espacially with database. Even after adding dependencies manually this problem is raising.I  reinstlled eclipse but no use.Can anyone help me to solve this problem?

**Comment by scottfrederick** [comment]
Thanks for getting in touch. Unfortunately there is not enough information here for us to be able to help you. 

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. This feels like a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
