### ISSUE TITLE
ConfigurationProperties annotated bean validation occurs before @PostConstruct

### ISSUE THREAD

**Issue by rnavarropiris** [spring-projects/spring-boot#3723]
Bean validation (jsr-303) should occur once the Bean is fully initialized, including `@PostConstruct` annotated actions, but this is not the case currently (`spring-boot` version `1.2.5.RELEASE`)

This minimal example shows the misbehaviour

```java
import javax.annotation.PostConstruct;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class TestConfig {

  @Bean
  @Valid
  public TestProps testProps() {
    return new TestProps();
  }

  @ConfigurationProperties(prefix = "test", ignoreUnknownFields = false, merge = false)
  public static class TestProps {

    @NotNull
    private String value = null;

    @PostConstruct
    private void postConstruct() {
      this.value = "the value is never null after this method!";
    }

    public String getValue() {
      return value;
    }

    public void setValue(String value) {
      this.value = value;
    }
  }
}
```

**Comment by snicoll** [comment]
I am guessing that if validation would occur on a properly ordered `BeanPostProcessor` we would have the guarantee that it is applied before `@Postconstruct`.

**Comment by snicoll** [comment]
`PropertiesConfigurationFactory#doBindPropertiesToTarget` binds and validate if necessary. In a `PostProcessor` scenario, it breaks the semantic because it validates a `@ConfigurationProperties` bean in the `postProcessBeforeInitialization` phase. Ideally it should bind (only) in that phase and, in the `postProcessAfterInitialization` it should validate the bean.

**Comment by snicoll** [comment]
`BeanValidationPostProcessor` has an `afterInitialization` flag that defaults to `false`  so the current behaviour is actually compliant with what you'd get with "regular" Spring (i.e. without `ConfigurationProperties`). Looking around, there does not seem anyone actually using that flag. 

@rnavarropiris did such use case ever work in another arrangement? I am asking because you're the only one complaining at this point....

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
