### ISSUE TITLE
Add a property to customize the layoutUrl of the velocity view resolver

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3732]

**Comment by timcolson** [comment]
A property for the layoutURL would be great. FYI there is also a LayoutKey and ScreenContentKey for the VelocityLayoutViewResolver class too. Are you thinking of another property to pick the viewresolver type?

**Comment by snicoll** [comment]
No. Again, you should not extend from our configuration class. I already replied on your original issue.

**Comment by timcolson** [comment]
Sure, saw the original issue reply. This #3732 is an enhancement to add a property to make the configuration class in #3729 unnecessary, yes?

**Comment by snicoll** [comment]
I haven't looked deeper than that but that's the plan. Maybe that will just now work :)

**Comment by timcolson** [comment]
That would be cool. :-) 

I'm confused a bit I think b/c the default Velocity view resolver is not the LayoutViewResolver, so doesn't Boot also need to pick that resolver... plus set the propert(ies) specific to it?

FYI - VelocityLayoutViewResolver is a nifty little class that injects the main content from one template into a "layout" template as $screen_content. Back when we built it into Velocity, we called it a "double render" since the main template is rendered first, possibly setting the $page_title, then the layout template is rendered.

**Comment by snicoll** [comment]
I changed my mind as I didn't see the benefit of introducing these 3 properties. The code would be confusing IMO because the actual type would change based on the presence of any of those 3 values so I've turned this one in a documentation issue. 

What we've been discussed is basically now documented in the developer guide.

**Comment by timcolson** [comment]
Agree that solution makes sense, and that's why I initially asked about how the prop would change the resolver type.
