### ISSUE TITLE
Bind scope attributes ("contextual objects") to @ConfigurationProperties if available

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3736]
Spring Cloud Stream wants to bind to incoming message payloads with something that is really very similar to `@ConfigurationProperties` (up to now they are using `@ConfigurationProperties` but it isn't fully feature compatible with the old Spring XD `ModuleOptions`). It seems like `@MessageScope` and a way to reference properties (payload and headers) of the incoming message are a natural idiom, but there is no support yet in Boot for dynamically enhancing the `Environment` property sources before binding. The `Scope` API has a natural "name-value" feature (`Object resolveContextualObject(String key)`) and that seems like it might be a fit.

Cc @ericbottard @markfisher

**Comment by snicoll** [comment]
Kind of related, the meta-data is probably "corrupted" since it scans for `@ConfigurationProperties` bean and those would not qualify I suppose.

**Comment by ericbottard** [comment]
@snicoll not sure what you mean. The point of this would really be to use `@ConfigurationProperties` (with their regular props, _e.g._ `name`, and some extra). So the regular generated metadata would definitely be "good".
We would rely on `additional-spring-configuration-metadata.json` to document _e.g._ `nameExpression`.

I really need to work on a small dirty POC to showcase the solution to you guys, this will explain better I hope. Will do asap

**Comment by snicoll** [comment]
My point is that if you bind stuff from a Message it should *not* show up in the generated meta-data (unless I am completely missing what you're trying to do).

**Comment by dsyer** [comment]
I think you are missing something (the message is going to add k-v properties for binding but it won't change the `@ConfigurationProperties` declaration at all). Let's get the prototype and have a look at it.

**Comment by ericbottard** [comment]
Just so we're on the same page, I created a (very ugly) POC of what we may want to achieve:

https://github.com/spring-cloud/spring-cloud-stream/compare/master...ericbottard:DynamicConfigurationProperties?expand=1

Note that this has a number of problems, the biggest one IMO being the use of the ThreadLocal as a means to propagate the Message that we're interested in. This works here, but there is no guarantee (I think) that interception and consumption of the proxyfied properties happen in the same thread.

**Comment by dsyer** [comment]
`ThreadLocal` is used in all `Scope` implementations as far as I know, so it's nothing unusual. What I don't quite understand is the need for SpEL evaluations. What is a simple example of a use case that would use `fooExpression` to resolve a property named `foo`?

**Comment by ericbottard** [comment]
Our canonical example is https://github.com/spring-projects/spring-xd-samples/tree/master/smartgrid-prediction#stream-definition

**Comment by dsyer** [comment]
Wouldn't `foo=#{payload.name}` be a more "natural" Spring idiom than `fooExpression=payload.name`? I'm sure you already thought of that so maybe I'm missing something?

**Comment by ericbottard** [comment]
I think our approach by appending `Expression` comes from the fact that SI has ad-hoc support for this naming strategy in certain places, eg https://github.com/spring-projects/spring-xd/blob/28a9962a871247d74f384f6b98b0c150220a459a/modules/sink/file/config/file.xml#L30 and https://github.com/spring-projects/spring-xd/blob/28a9962a871247d74f384f6b98b0c150220a459a/modules/sink/redis/config/redis.xml#L19

**Comment by dsyer** [comment]
I see. But you wouldn't need it for the feature we are talking about here because you are just binding to bean properties, not to an XML namespace?

**Comment by ericbottard** [comment]
Just to clarify, you're proposing to write the value of a property in a different fashion (here wrapping in `#{}`) rather than name it differently (_e.g._ appending `Expression`), correct? While it seems sensible, I'm worried it may fall short in certain situations (what if I want to write the literal `#{foo}` for example?)

Interesting to see your approach with a new pair of eyes, please continue to braindump.

**Comment by dsyer** [comment]
Well I suggested `'#{foo}` because that is what Spring understands already in `@Value` annotations, so the documentation is already written and people are used to it as a feature. You can declare a String literal in SpEL just using single quotes `#{'foo'}` so there's nothing funky going on.

**Comment by markfisher** [comment]
This discussion has kind of been all over the place, but just to clarify one very important part of this.... the use of "***Expression" that we are concerned about is for those cases where a Message handling component evaluates an expression at runtime (e.g. a counter can derive a name per Message as the key for its count values, perhaps based on a header or something in the payload). In those same cases, the use of the property without "Expression" is for simplifying/optimizing the static cases (e.g. the key for count values will always be "numMessagesReceived" so no need to evaluate an Expression and no need to burden the user with SpEL syntax just to provide a literal value). Of the 2 examples Eric posted above, only the 2nd one falls into that category. The "file" one is simply concatenating stuff upfront at config time and should be handled in the typical way. Many Spring Integration components have some "***Expression" property where they expect an Expression to evaluate against each Message as received. But for cases where evaluation does not need to occur, we can use LiteralExpression internally, and that's what typically happens in the corresponding "foo" case of the SI namespace support (i.e. foo="bar" translates to fooExpression=new LiteralExpression("bar")). This is why earlier I was suggesting we could look at this from the other direction. A naming convention such that if "foo" is provided instead of "fooExpression", the user can provide a literal value (not having to wrap in SpEL syntax) and then internally we create a LiteralExpression. Finally, I want to reiterate my suggestion that we discuss this at SpringOne, where it would be more efficient and less of a distraction from other more urgent work ;)

**Comment by philwebb** [comment]
Looks like this issue might have run its course. There is the new `Binder` code in 2.0 that could perhaps be used. Closing for now.
