### ISSUE TITLE
How is Dispatcher Servlet working?

### ISSUE THREAD

**Issue by quanghao7689** [spring-projects/spring-boot#37401]
In Springboot 3.0
We have registered a servlet ss000Action that extends from HttpServlet and does nothing inside.
Use ServletRegistrationBean to register ss000Action servlet with
```
addUrlMappings("/sp/*")
setLoadOnStartup(1)
```

Create ss0001Filter
Use ServletRegistrationBean to register ss000Action servlet into ss0001Filter used to remove /sp on url.

```
setFilter(ss0001Filter)
addServletRegistrationBeans(ss000Action ())
```

When submitting a url:
`/sp/ss2000 => ss0001Filter => /ss2000 => ss2000 Controller processing => forward :/sp/ss1000`

In the controller I have registered: @RequestMapping(value = "/sp/ss1000"
However, a white screen error is occurring.
Please help me explain why this is so.
Is it because I registered a servlet that overrides the Dispatcher Servlet?
Is there any documentation that explains this?
What to do to solve it?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Your question on StackOverflow should have more detailed code snippets as it's not clear which Servlets are registered and how and what behavior you are expecting.
