### ISSUE TITLE
PaketoBuilderTests#nativeApp() is failing due to a deprecation warning being logged

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#37433]
```
Warning: The USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM environment variable is deprecated and might be removed in a future release. Please refer to the GraalVM release notes.
```

The failures began on July 7 ([3.0.x](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-3.0.x/jobs/run-system-tests/builds/992), [3.1.x](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-3.1.x/jobs/run-system-tests/builds/295), [3.2.x](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-3.2.x/jobs/run-system-tests/builds/45)).

**Comment by scottfrederick** [comment]
These tests started failing because of the GraalVM deprecation mentioned above. This was fixed by Paketo in https://github.com/paketo-buildpacks/native-image/issues/273. Before we could get green builds from this fix, the tests started failing because AOT-generated code is causing compiler deprecation warnings in generated `BeanDefinition` classes: 

```
/tmp/gradle-17837136993385756809/build/generated/aotSources/org/springframework/boot/autoconfigure/task/TaskExecutorConfigurations__BeanDefinitions.java:32: warning: [removal] TaskExecutorBuilder in org.springframework.boot.task has been deprecated and marked for removal
```

This is being tracked in https://github.com/spring-projects/spring-framework/issues/29597. 

The Gradle integration tests generally fail when there are deprecation warnings in the build output, but we selectively ignore some deprecation warnings that we have no control over. It might be possible to selectively ignore these deprecations, or we might have to ignore all deprecations for this test.
