### ISSUE TITLE
Upgrade the managed dependency of h2database

### ISSUE THREAD

**Issue by agoerler** [spring-projects/spring-boot#37445]
The [managed dependency](https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html) of h2database is still on 2.1.214. Please upgrade to a more recent [version of h2database](https://github.com/h2database/h2database/tags) the current version is 2.2.224.

**Comment by bclozel** [comment]
The upcoming Spring Boot 3.2 [is already on the 2.2 generation of h2](https://github.com/spring-projects/spring-boot/blob/77f0828f7f6a2e33fbb84bda1943b17c644e4dca/spring-boot-project/spring-boot-dependencies/build.gradle#L355) and we'll upgrade to maintenance versions.

You're pointing to Spring Boot 3.1 here and we'll stick to 2.1.x there because of [our upgrade policy](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#third-party-dependencies).

Our issue template also mentions the following:

> - Managed Dependency Upgrade
> You DO NOT need to raise an issue for a managed dependency version upgrade as there's a semi-automatic process for checking managed dependencies for new versions before a release. BUT pull requests for upgrades that are more involved than just a version property change are still most welcome.

I'm closing this issue as a result.
