### ISSUE TITLE
bootJar gradle task does not set file permissions within jar to readonly

### ISSUE THREAD

**Issue by dmarsh26** [spring-projects/spring-boot#37494]
bootJar gradle task creates a fat jar with writeable files.

Security scans from stuff like Synk/Sonar fail because of this.

This is my workaround, would be nice for existing bootJar task to do something similar internally.

```
task unzipBootJar(type: Copy) {
	dependsOn bootJar

	from zipTree(bootJar.destinationDirectory.file(bootJar.archiveFileName))
	into layout.buildDirectory.file('/unpacked/dist')
}
task zipDistToSecureBootJar(type: Zip) {
	dependsOn unzipBootJar

	from layout.buildDirectory.file('/unpacked/dist')
	entryCompression = ZipEntryCompression.STORED
	filePermissions {
		user {
			read = true
		}
		other.execute = false
		other.write = false
	}
	dirPermissions {
		user {
			read = true
		}
		other.execute = false
		other.write = false
	}
	include '**/**/*'
	archiveFileName="secure-${bootJar.archiveFileName.get()}"
	destinationDirectory=layout.buildDirectory.dir('/libs')
}
bootJar.finalizedBy zipDistToSecureBootJar
```

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I don't think we should change the default behavior as we're currently relying on Gradle's defaults. I think that's the right thing to do. It means that things behave as expected by those who are familiar with Gradle and also means that any changes made to Gradle in the future will be picked up automatically by the `bootJar` task.

Instead of your workaround, you should be able to configure the permissions when creating the jar:

```
tasks.named("bootJar") {
	fileMode = 0400
	dirMode = 0500
}
```

This correctly sets the permissions for the files and directories in `BOOT-INF/lib` and `BOOT-INF/classes` but it does not work for the loader classes in the root of the jar or for the `classpath.idx` and `index.idx` files. I've opened https://github.com/spring-projects/spring-boot/issues/37496 to address this. Thanks for bringing it to our attention.

**Comment by dmarsh26** [comment]
The scan passes with your suggestion it only seems to be looking at the subdirectories.

**Comment by dmarsh26** [comment]
![image](https://github.com/spring-projects/spring-boot/assets/7771071/4c5fb55c-d27f-4b73-a149-0f2272ff1ad1)
Seems the issue persists, the scan does not always seem to pick up the same item.

**Comment by philwebb** [comment]
@dmarsh26 That scan seems to be looking at a file within a jar. What's the permissions for `BOOT-INF/lib/spring-security-config-6.1.3.jar`? That's the file that the permission should be setting.

Is the scanner somehow looking inside this jar or has it somehow unpacked inside the image? How are you actually creating your images?

**Comment by dmarsh26** [comment]
I'm using grade wrapper with spring boot 3.1. The boot Jar target.

I've now set the jar in docker to chmod 500 so hopefully that fixes it, changing all jars on doesn't seem a solution.

So maybe it's not a problem, waiting to see, previously I tired chmod o-w and it didn't work. I guess maybe the scanner can sudo or something and root would have has write access.

________________________________

**Comment by dmarsh26** [comment]
https://github.com/spring-projects/spring-security/blob/main/config/spring-security-config.gradle

def versionlessXsd = tasks.register("versionlessXsd", CreateVersionlessXsdTask) {
	inputFiles.from(rncToXsd.map { task -> project.fileTree(task.xsdDir) })
	versionlessXsdFile = project.layout.buildDirectory.file("versionlessXsd/spring-security.xsd")
}

tasks.named('processResources', ProcessResources).configure {
	from(versionlessXsd) {
		into 'org/springframework/security/config/'
	}
	from(rncToXsd) {
		duplicatesStrategy DuplicatesStrategy.EXCLUDE
		into 'org/springframework/security/config/'
	}
}

Process resources has dirPermissions, so maybe spring security can be changed, not sure if its sensible. Appreciate that is a different Spring project.
