### ISSUE TITLE
boot 3, /swagger-ui/index.html got 404, v3/api-docs working

### ISSUE THREAD

**Issue by chengtangzheng2021** [spring-projects/spring-boot#37625]

**Comment by chengtangzheng2021** [comment]
one of our spring boot app with boot 3.1.3, java17
/swagger-ui/index.html got 404, v3/api-docs working.
with springdoc-openapi-starter-webmvc-ui 2.2.0
what can cause this?

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by chengtangzheng2021** [comment]
it is a bug, it is not working at some cases

**Comment by wilkinsona** [comment]
Spring Boot isn't responsible for providing `/swagger-ui/index.html` so, if it is a bug, it's very unlikely to be a bug in Spring Boot. You also haven't provided any more information about the problem so we're not going to be able to help you. If you are certain that it's a bug, I would recommend opening an issue against the [Spring Doc project](https://github.com/springdoc/springdoc-openapi). If you do so, please take the time to fully describe the problem and how to reproduce it otherwise it's also unlikely that they will be able to help you.
