### ISSUE TITLE
Resttemplate not pegging http_client metrics

### ISSUE THREAD

**Issue by ajithgg** [spring-projects/spring-boot#37887]
Hi ,

I am using Resttemplate to communicate with other applications. I am not seeing http_client_response metrics pegged in our application. I also tried RestTemplateBuilder and even that did not work. Could you please help me in resolving this issue?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
