### ISSUE TITLE
Auto register Jackson parameter name module if it is on the classpath

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#3804]
As a follow up for #3727, the Jackson module to enable parameter name discovery could be auto-configured.

**Comment by wilkinsona** [comment]
This is going to be taken care of in Spring Framework. See #3615

**Comment by lpandzic** [comment]
I just stumbled upon this issue and I'm sorry to inform you, but no, it's not going to be taken care of in Spring Framework, at least not yet.

Details can be found in [SPR-13296](https://jira.spring.io/browse/SPR-13296). To summarize, the main issue are the [delegating creators](http://www.cowtowncoder.com/blog/archives/2011/07/entry_457.html) in jackson and whether to override them or not.

I've decided to try and tackle this issue in jackson project itself, where this issue will be forced when upgrade to Java 8 happens. For some, that is the least preferable action, since transition to Java 7 has yet to happen.

**Comment by lpandzic** [comment]
> I've decided to try and tackle this issue in jackson project itself, where this issue will be forced when upgrade to Java 8 happens. For some, that is the least preferable action, since transition to Java 7 has yet to happen.

[Discussion on jackson-dev](https://groups.google.com/forum/#!topic/jackson-dev/ZfPM6MLunwM).

**Comment by olivergierke** [comment]
In light of the discussion in SPR-13296: isn't Boot then the much more suitable place for some easily overridable defaulting? It could register the module in some default setup and back off as soon as the user provides one herself?

**Comment by wilkinsona** [comment]
I had missed that the SPR issue had been closed as won't fix. In my original comment I was expecting it to be tackled in Spring Framework and didn't want us to add something that would then be superseded.

I guess we could add something like this to `JacksonAutoConfiguration`:

```java
@Configuration
@ConditionalOnJava(JavaVersion.EIGHT)
@ConditionalOnClass(ParameterNamesModule.class)
private static class ParameterNamesModuleConfiguration {

	@Bean
	@ConditionalOnMissingBean(ParameterNamesModule.class)
	public ParameterNamesModule parametersNameModule() {
		return new ParameterNamesModule(JsonCreator.Mode.PROPERTIES);
	}

}
```

**Comment by olivergierke** [comment]
:+1:

**Comment by snicoll** [comment]
Sounds about right!

**Comment by lpandzic** [comment]
Great! :+1:
