### ISSUE TITLE
CVE-2023-4586: Does Spring Boot enable host name verification with Netty in all cases?

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-boot#38094]
[CVE-2023-4586: Improper Certificate Validation](https://avd.aquasec.com/nvd/2023/cve-2023-4586/) applies to netty 4.x (there is no netty 5 [yet?]) upon which Spring Boot depends.

Netty's documentation for how to enable hostname verification: https://netty.io/4.1/api/io/netty/handler/ssl/SslContext.html#newHandler-io.netty.buffer.ByteBufAllocator-java.util.concurrent.Executor-

I'm trying to find all relevant netty references in Spring Boot to ensure that hostname verification is enabled for each. Some potentially relevant classes I've found include: `ReactorNettyWebSocketClient`, `ReactorNetty2WebSocketClient`, `ReactorNetty2ClientHttpConnector`, `ReactorClientHttpConnector`, `ReactorClientHttpConnectorFactory`, `ReactiveCloudFoundrySecurityService`.

I'm finding it quite difficult to verify if Spring Boot enabled host name verification in all paths. Could Spring Boot please let us know if it does?

I think it would really benefit the community to get a clear statement as to whether CVE-2023-4586 impacts Spring Boot or not.

Thank you!

**Comment by bclozel** [comment]
Thanks for reaching out.

All the classes you've listed use Reactor Netty's `HttpClient`. By default, Reactor Netty is safe in that regard as it enables hostname verification. It is highlighted in the Javadoc for the `secure()` methods [here](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#secure--) and [here](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#secure-java.util.function.Consumer-). Creating a default `HttpClient.create()` does as well.

> I think it would really benefit the community to get a clear statement as to whether CVE-2023-4586 impacts Spring Boot or not.

We can't give a clear statement on that for several reasons.

1. the CVE itself is [considered as a false positive by the Netty team](https://github.com/netty/netty/issues/13665#issuecomment-1782501938). The same "vulnerability" is also applicable with plain Java, if hostname verification is not enabled. The Spring team knows this too well because of [CVE-2016-1000027](https://github.com/spring-projects/spring-framework/issues/24434): once a CVE id is created it's hard to get them updated/re-scored.
2. If applications provide their own `SslProvider` to Reactor Netty, it's the application's responsibility to enable this feature. This is [highlighted in the Javadoc as well](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html#secure-reactor.netty.tcp.SslProvider-)
3. Same applies to dependencies that shade Netty - they're responsible for enabling this feature, unless the application provides an `SslContext`
4. the situation is not clear, as [the original CVE was allocated by Red Hat for the hotrod client](https://www.cve.org/CVERecord?id=CVE-2023-4586) with a 5.3 score, and yet [that same entry is pinned to Netty proper with a 7.5 score by NVD](https://nvd.nist.gov/vuln/detail/CVE-2023-4586).


I'm closing this issue as there's nothing actionable on our side.
