### ISSUE TITLE
App fails to start with a NoSuchMethodError when using Flyway 10.0.0

### ISSUE THREAD

**Issue by aspan** [spring-projects/spring-boot#38164]
Flyway 10.0.0 has removed the following methods from FluentConfiguration

licenseKey
undoSqlMigrationPrefix
cherryPick

**Comment by wilkinsona** [comment]
Thanks for the report.

The fix for this is low-risk and straightforward (it's just a matter of replacing some method references with lambdas) so it's tempting to apply it in 3.0.x or possibly even 2.7.x and later. We'll discuss it as a team.

**Comment by wilsonrf** [comment]
Do you have plans to apply this fix also for spring-boot 3.0.X and 3.1.X?
Thank you in advance.

**Comment by wilkinsona** [comment]
Those fixes are already in place (https://github.com/spring-projects/spring-boot/issues/38266, https://github.com/spring-projects/spring-boot/issues/38267) and will be released shortly.

**Comment by wilsonrf** [comment]
Thank you @wilkinsona

**Comment by gsant07** [comment]
@wilkinsona  Is this fix release yet ? I am upgrading springboot from 2.7.x to 3.0.0 and flyway to 9.22.3 with java 17 and get this error only when starting the application . I was using mysql db 5.7 version before. Should i upgrade the DB as well ? 

_The following method did not exist:

    'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.placeholderSeparator(java.lang.String)'
 
Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration and org.flywaydb.core.api.configuration.FluentConfiguration_

**Comment by wilkinsona** [comment]
@gsant07 please don't duplicate comments across issues. It's a waste of everyone's time.
