### ISSUE TITLE
how to config undertow request timeout 

### ISSUE THREAD

**Issue by shizuniao** [spring-projects/spring-boot#38426]
springboot version: 2.3.4
undertow version: 2.3.4

I am seeking guidance on configuring the HTTP request handling timeout for a Spring Web application. Upon reviewing the code, I only found the configuration server.undertow.no-request-timeout. However, its description states, "Amount of time a connection can sit idle without processing a request, before it is closed by the server." This configuration does not seem to fulfill my requirement for setting an HTTP request timeout.

I am looking for information on whether there exists a specific configuration related to http request timeout in the context of Spring Web or any alternative approaches that can effectively achieve the desired HTTP request processing timeout.

Your assistance or insights into configuring the HTTP request handling timeout in a Spring Boot application would be highly appreciated.

Thank you for your attention and support.

**Comment by wilkinsona** [comment]
Spring Boot 2.3.x is no longer supported. Furthermore, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it). Defining exactly what you mean by request timeout in that question would also make it easier for people to answer.
