### ISSUE TITLE
Spring Boot 3.2.0 new warning about `DelegatingWsConfiguration is not eligible for getting processed by all BeanPostProcessors`

### ISSUE THREAD

**Issue by josephearl** [spring-projects/spring-boot#38542]
After upgrading to Spring Boot 3.2.0 our services that use `spring-boot-starter-web-services` now log a new warning on startup:

logger_name: `org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker`
level: `WARN`

> Bean 'org.springframework.ws.config.annotation.DelegatingWsConfiguration' of type [org.springframework.ws.config.annotation.DelegatingWsConfiguration$$SpringCGLIB$$0] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). The currently created BeanPostProcessor [annotationActionEndpointMapping] is declared through a non-static factory method on that class; consider declaring it as static instead.

**Comment by wilkinsona** [comment]
As indicated by the error message, the problem lies in the signature of `annotationActionEndpointMapping` method on `org.springframework.ws.config.annotation.DelegatingWsConfiguration` (the method should be `static`). `DelegatingWsConfiguration` is part of [Spring Web Services](https://github.com/spring-projects/spring-ws). Please raise an issue there.
