### ISSUE TITLE
Wh Spring Boot choose Jackson over Gson as the default serialization?

### ISSUE THREAD

**Issue by junuuuuuu** [spring-projects/spring-boot#38562]
Hi, I wasn't sure if I should post this as an issue, but I'm really curious.

After doing some research on Gson and Jackson, I personally believe that the Spring Framework chose Jackson as the serialization/deserialization default for the following reasons.

- Better performance of Jackson according to the benchmarks
- Jackson is more general purpose because it also supports xml

Do you think there are other reasons as well?

**Comment by wilkinsona** [comment]
You were right not to be sure. Unfortunately, this isn't the right place to ask questions such as this. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

Spring Boot predates Spring Framework's support for GSON so it wasn't an option to begin with. Since then, we have seen no reason to change the default.
