### ISSUE TITLE
@PathVariable throw an error after ignoring value in Spring Boot 3.2.0.

### ISSUE THREAD

**Issue by tangllty** [spring-projects/spring-boot#38621]
jdk: openjdk 17
springboot: 3.2.0
mybatis: 3.0.3

If the parameter name of `@PathVariable` is the same as the parameter name of the url, `value` can be ignored.

But when I upgraded from 3.1.5 to 3.2.0, the program throws the following error

**Name for argument of type [java.lang.String] not specified, and parameter name information not found in class file either.**

This is the normal code before I upgraded.

![image](https://github.com/spring-projects/spring-boot/assets/58468628/df47801e-55fa-40d7-9cb3-3ebbb2807562)

Code: https://github.com/tangllty/tang-boot/blob/master/tang-system/src/main/java/com/tang/system/controller/dict/SysDictDataController.java#L58-L61
Repository: https://github.com/tangllty/tang-boot/
WebSite: https://github.com/tangllty/tang-boot

**Comment by bclozel** [comment]
I think this is due to https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#parameter-name-discovery

You should have gotten WARN logs with Spring Boot 3.1.x about this. Please compile your code with the `-parameters` compiler option. See also https://github.com/spring-projects/spring-framework/issues/31675
