### ISSUE TITLE
Consider disabling logback packaging data in stack traces by default

### ISSUE THREAD

**Issue by laech** [spring-projects/spring-boot#38668]
Logback from v1.1.4 has packaging data in stack traces [disabled by default](https://logback.qos.ch/manual/configuration.html#packagingData), due to calculating them are rather expensive.

However Spring Boot has it [enabled by default](https://github.com/spring-projects/spring-boot/blob/b5de38787c6abd4fc6522aa006b3d460ae23ffc5/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L235), perhaps we should change that to be disabled by default as well to align with upstream recommendation?

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Spring Boot has always had packaging enabled, either because it was Logback's default or, for consistency with Boot's previous behavior, because we've overridden that default. While we could change the default in the next minor release, we haven't seen any performance data that suggests it's necessary to do so. If you have such data then please do share it with us.

**Comment by laech** [comment]
Hi Andy, I have not captured any data myself, and this is the original logback ticket with some comments on why it was disabled by default: https://jira.qos.ch/browse/LOGBACK-730

**Comment by wilkinsona** [comment]
Thanks. A couple of the people there were affected due to using JRuby or OSGi, neither of which is common in a Spring Boot application. Until we've heard of it causing real world performance issues in Spring Boot, I am tempted to leave packaging data enabled as I think the information it provides is useful.

**Comment by philwebb** [comment]
I agree, I think we should leave this enabled unless we can find a real-world reason not to. It's been invaluable in our own issue tracker to identify things like mismatched framework jar versions.
