### ISSUE TITLE
Not able to use @Value($"some-key-in-application.properties") in Implementation classes.

### ISSUE THREAD

**Issue by punitjain9615** [spring-projects/spring-boot#38755]
Hi there,

I'm creating one interface and creating one implementation of that interface. But 

```java
class AImpl implements A{
@Value("$some-key")
public String someKey;
}
```

If i define the key value in application.properties and use it here it's giving me null value of someKey.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
You might want to try `@Value("${some-key}")`
