### ISSUE TITLE
Spring Boot 3.2.0 - Could not find or load main class org.springframework.boot.loader.JarLauncher

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects/spring-boot#38824]
Application working fine with Spring Boot v3.1.6 **fails** to start with **Spring Boot v3.2.0** with the below error

`could not find or load main class org.springframework.boot.loader.JarLauncher`

No other change except the Spring Boot version upgrade. Thanks

**Comment by syedyusufh** [comment]
Working as expected --> https://docs.spring.io/spring-boot/docs/3.2.0-SNAPSHOT/reference/html/executable-jar.html#appendix.executable-jar.launching.manifest

**Comment by philippn** [comment]
A tip for anyone who stumbles about this issue because his custom Docker image is not starting up anymore:

The name of the launcher class referred to in the docker entrypoint has changed from `org.springframework.boot.loader.JarLauncher` to `org.springframework.boot.loader.launch.JarLauncher` with 3.2.
