### ISSUE TITLE
management role check inconsistent

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#3883]
I am not sure where this issue is coming from. Reproduced with `1.2.5.RELEASE` and `master`

Assume this very simple boot app

```
@SpringBootApplication
@EnableGlobalMethodSecurity(securedEnabled = true)
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Configuration
    static class SecurityConfig extends GlobalAuthenticationConfigurerAdapter {

        @Override
        public void init(AuthenticationManagerBuilder auth) throws Exception {
            auth.inMemoryAuthentication().withUser("user").password("user").roles("USER").and()
                    .withUser("hero").password("hero").roles("USER", "HERO");
        }

    }
}
```

If I try to access `/env` with any of those two users, it won't work because the required role is `ADMIN`. If I change that via configuration (`management.security.role=HERO`) and log in has  the `hero` user I can get in.

But If I change my config as follows, I can get in with whatever user (i.e. whatever role assigned to it)

```
@SpringBootApplication
@EnableGlobalMethodSecurity(securedEnabled = true)
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Configuration
    static class SecurityConfig extends WebSecurityConfigurerAdapter {

        @Override
        protected void configure(AuthenticationManagerBuilder auth) throws Exception {
            auth.inMemoryAuthentication().withUser("user").password("user").roles("USER").and()
                    .withUser("hero").password("hero").roles("USER", "HERO");
        }

    }
}
```

**Comment by rwinch** [comment]
In terms of Spring Security's behavior this is expected.

In the first instance you are only configuring authentication. In the second instance, `WebSecurityConfigurerAdapter`s  is overriding authorization with the `configure(HttpSecurity)` method. This means authorization is mapped to [any request](https://github.com/spring-projects/spring-security/blob/4.0.2.RELEASE/config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java#L325) a user must be authenticated.

Note that Spring Boot still specifies rules for Security, but they are only invoked if a user's defined rules do not happen first. So if you added `@Order(Ordered.LOWEST_PRECIDENCE)` to your `SecurityConfig`, then boot should still see the authorization rules provided by Boot.

One caveat is that configuring authentication with the protected method is intended to isolate authentication to that specific `WebSecurityConfigurerAdapter` (this is why the method is protected). This means that Boot will still be using the global authentication for it's purposes since it uses its own `WebSecurityConfigurerAdapter` (i.e. if you didn't configure anything then it will use the default generated username / password).

Honestly, I'm not sure what the intent behind Boot's configuration is (i.e. should it take precedence over user defined configuration by default or not?). To my understanding it is "backing out of the way" if you provide your own `WebSecurityConfigurerAdapter`. This is probably a better question for @dsyer.

PS: You can simplify the first configuration to be:

```java
@SpringBootApplication
@EnableGlobalMethodSecurity(securedEnabled = true)
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
    
    // consider reading https://spring.io/blog/2013/07/11/spring-security-java-config-preview-readability/
    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        // @formatter:off
        auth
            .inMemoryAuthentication()
                .withUser("user").password("user").roles("USER").and()
                .withUser("hero").password("hero").roles("USER", "HERO");
        // @formatter:on
    }
}
```
