### ISSUE TITLE
Question for RabbitAnnotationDrivenConfiguration

### ISSUE THREAD

**Issue by UncleJuJu** [spring-projects/spring-boot#38840]
`@Configuration
@EnableRabbit
@ConditionalOnMissingBean(name = RabbitListenerConfigUtils.RABBIT_LISTENER_ANNOTATION_PROCESSOR_BEAN_NAME)
protected static class EnableRabbitConfiguration {

}`
I don't know why need add this @interface 
`@ConditionalOnMissingBean(name = RabbitListenerConfigUtils.RABBIT_LISTENER_ANNOTATION_PROCESSOR_BEAN_NAME)`
if miss this bean, then `EnableRabbitConfiguration` will create, but why need `EnableRabbitConfiguration`? 
`EnableRabbitConfiguration` for what thing?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
