### ISSUE TITLE
used springboot3.1.x aop

### ISSUE THREAD

**Issue by yqxqls** [spring-projects/spring-boot#38851]
springboot3.0 使用aop不正常,例如：@Pointcut("within(@org.springframework.stereotype.Repository *)" +
            " || within(@org.springframework.stereotype.Controller *)" +
            " || within(@org.springframework.web.bind.annotation.RestController *)")
使用此切面,在springboot2.x是没问题的,在3.0，使用@Value注解获取yaml的值一直报Null

**Comment by bclozel** [comment]
> springboot3.0 uses aop abnormally, for example: 
> ```
> @pointcut("within(@org.springframework.stereotype.Repository *)" + " || within(@org.springframework.stereotype.Controller *)" + " || within(@org.springframework.web.bind.annotation.RestController *)")
> ```
> Using this aspect, there is no problem in springboot2.x. In 3.0, using @value annotation to get the value of yaml always returns Null.

Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
