### ISSUE TITLE
MySQL dependency artifactId error!

### ISSUE THREAD

**Issue by ikun-01** [spring-projects/spring-boot#38921]
![Snipaste_2023-12-24_20-02-13](https://github.com/spring-projects/spring-boot/assets/67815316/952197d3-fd8f-4326-89e3-22e57d79cd1a)

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by ikun-01** [comment]
![image](https://github.com/spring-projects/spring-boot/assets/67815316/dcc0f5f9-79e5-493d-855e-4007e53e9e9e)
Spring boot defined MySQL dependency error

**Comment by bclozel** [comment]
Your screenshots show different artifact coordinates. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#mysql-jdbc-driver
