### ISSUE TITLE
Provide a way to further customize underlying ClientHttpRequestFactory components

### ISSUE THREAD

**Issue by ciscoo** [spring-projects/spring-boot#39035]
I could not find a way to further modify the `PoolingHttpClientConnectionManagerBuilder` (or `HttpClientBuilder`) that Spring Boot creates without essentially duplicating Spring Boot defaults and then applying customizations.

Spring Cloud OpenFeign had properties which further customized the client. For example, to configure the [pool connection policy](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/clientconfig/HttpClient5FeignConfiguration.java#L81).

Ideally, I would like to declare a customizer bean of some sort:

```java
@FunctionalInterface
public interface PoolingHttpClientConnectionManagerBuilderCustomizer {
	
	void customize(PoolingHttpClientConnectionManagerBuilder connectionManagerBuilder);
}
```

Or if there were some static factory method that created a base `PoolingHttpClientConnectionManagerBuilder` that I could use and then further customize as needed.

Alternatively, you could provide more configuration properties like the Feign project, but I think that would quite the added overhead since they would different per HTTP client.

**Comment by philwebb** [comment]
I think we'd need some changes to `org.springframework.boot.web.client.ClientHttpRequestFactories` to be able to support this and I'm not sure how to do that in a generic fashion.

We currently have static `get` methods that accept `ClientHttpRequestFactorySettings`, I guess we'd need to also accept some kind of customizer, but it's hard to see what the interface could be since we'd ideally like to keep it generic.

Flagging for team attention to see if anyone has any bright ideas.

**Comment by scottfrederick** [comment]
I think #38920 is related, in that both issues involve finer-grained customization of the underlying HTTP client being used by RestTemplate, RestClient, or WebClient after Spring Boot has applied any auto-configuration.
