### ISSUE TITLE
how to build generate git info documentation out of date

### ISSUE THREAD

**Issue by alexisgayte** [spring-projects/spring-boot#39278]
This documentation is not working anymore with gradle 8.5 and java 17:

https://docs.spring.io/spring-boot/docs/3.2.2/reference/htmlsingle/#howto.build.generate-git-info

Cf issue : https://github.com/n0mer/gradle-git-properties/issues/225

This project ( gradle-git-properties ) seems dead.

**Comment by wilkinsona** [comment]
https://github.com/n0mer/gradle-git-properties/issues/225 looks like a problem that only happens when using Gradle's configuration cache. Unfortunately, supporting Gradle's configuration cache can be quite difficult and may not be something that a plugin maintainer wants to do. Does it work for you without it?

**Comment by alexisgayte** [comment]
yes it does.

For information the property is :
`org.gradle.configuration-cache=true`

I just wanted to warm you with regard to the doc.

Thanks for your quick turn comment.

**Comment by wilkinsona** [comment]
I don't think there's a better alternative for Gradle, unfortunately, but please do let us know if you're aware of one. Beyond that, given that the error makes it clear that the problem's caused by the configuration cache, I don't think there's anything for us to do here. Regardless, thanks for bringing the current situation to our attention.

**Comment by alexisgayte** [comment]
For Information this plugin is work for me :

"io.hndrs.gradle:gradle-git-properties-plugin:1.0.0"

https://plugins.gradle.org/plugin/io.hndrs.git-properties

Wondering if there is a way to let this ticket accessible for people?
