### ISSUE TITLE
Parallel Calls for child level tables from parent repo itself

### ISSUE THREAD

**Issue by amrit9326** [spring-projects/spring-boot#39522]
Hi Team ,

We're using JPA + Hibernate with our Hana database. Below is the db model as such..

*
Vehicle {
     sales
     financial
     maintenance
}
*

Now the repository is at Master entity Vehicle and when I'm try to access the vehicle with id  vehicleRepository.findById(id), all the associated child tables query are being sent in sequence. Is there any way to fire it in parallel.

Please check dynatrace calls as below

![image](https://github.com/spring-projects/spring-boot/assets/38880261/7f5f1f40-47c5-428e-8d5e-6e5646548c2c)

The yellow blocks can be seen which shows the query is being sent in parallel.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by amrit9326** [comment]
Hi @wilkinsona ,

I tried finding any property at all the blogs but didn't find any jpa or hibernate properties which springs provided to make the calls in parallel from parent level where the child tables query in sequential could be avoided. Could it be consider enhancement or something which could make this possible.

**Comment by wilkinsona** [comment]
As you're using JPA, the database calls are being made by Hibernate and are out of Spring Boot's control. I don't know for certain if Hibernate supports parallel query execution. Someone on Stack Overflow may be able to help you there. If it doesn't support it, you would have to make a feature request to the Hibernate team.
