### ISSUE TITLE
Using Java 8/Hibernate5 LocalDate

### ISSUE THREAD

**Issue by neblina-software** [spring-projects/spring-boot#3952]
While spring boot is using hibernate 4.2, it is imposible to use Java 8 date and time types.

Date() it is already obsolete in java 8.

Any fix for this issue?

@Type(type="LocalDateType")

https://github.com/neblina-software/balerocms-enterprise/blob/master/src/main/java/com/neblina/balero/domain/Blog.java

Please, read this link:

https://hibernate.atlassian.net/browse/HHH-8844

Regards!

**Comment by olivergierke** [comment]
I am not quite sure what the ticket is all about really as it basically describes the current, obvious state but I wonder what you were expecting Boot to change?

Hibernate 4.2 doesn't support Java 8 date time types out of the box but Spring Data JPA adds dedicated JPA 2.1 `AttributeConverter` implementations for non-time-zoned JSR-310 types by converting them to a `Date`. An example of this can be found [here](https://github.com/spring-projects/spring-data-examples/tree/master/jpa/java8#support-for-jdk-8s-datetime-types-in-the-auditing-sub-system).

Generally speaking, you could also upgrade the Hibernate version of your Boot app to a a newer one by setting the `hibernate.version` property to e.g. the current `5.0.1.Final`. The Spring Data examples have a branch to do that and it generally works. However, depending on the JPA features you use, you might run into upgrade issues, as quite a few things have changed in Hibernate 5 (e.g. the way the `@GeneratedValue` is interpreted by default on identifiers).

That said, I don't think Boot is going to raise the default dependency version of Hibernate to 5.0 for the 1.3 release (someone from the team correct me if I am wrong) for two major reasons:

- As a user you can already upgrade to it if you want
- Forcing users into 5.0 might force users into breaking apps due to some significant changes in Hibernate 5.

So as we want to ship very recent dependency libraries by default, we also want to make sure user apps don't break with a Boot release. And as you always can upgrade at your desired pace yourself, there's no strong need to raise the dependency version ourselves.

**Comment by neblina-software** [comment]
> Generally speaking, you could also upgrade the Hibernate version of your Boot app to a a newer one > by setting the hibernate.version property to e.g. the current 5.0.1.Final. The Spring Data examples have > a branch to do that and it generally works. However, depending on the JPA features you use, you might > run into upgrade issues, as quite a few things have changed in Hibernate 5 (e.g. the way the > @GeneratedValue is interpreted by default on identifiers).

Thanks! Very Useful!

So, you are sentencing the user to use Java 7

>That said, I don't think Boot is going to raise the default dependency version of Hibernate to 5.0 for the > 1.3 release (someone from the team correct me if I am wrong) for two major reasons:

> As a user you can already upgrade to it if you want
> Forcing users into 5.0 might force users into breaking apps due to some significant changes in Hibernate 5.

Regards!

**Comment by olivergierke** [comment]
> So, you are sentencing the user to use Java 7.

I am not sure what brings you to the conclusion but it's wrong. Use 7, use 8, use the Hibernate version you want. I really don't get the point. What exactly were you asking for?

**Comment by abdsabri** [comment]
@olivergierke Thanks for the clarification, however I tried to set `<hibernate.version>5.0.1.Final</hibernate.version>` however it crashes on runtime. Any idea what's necessary to use 5.0.1 with the final version of spring boot? Do I have to create my own entity manager for example?
```Caused by: java.lang.NoSuchMethodError: org.hibernate.internal.CoreMessageLogger.debugf(Ljava/lang/String;II)V```

**Comment by olivergierke** [comment]
Are you setting any other dependencies explicitly. The Spring Data examples have [a branch that's running on Hibernate 5](https://github.com/spring-projects/spring-data-examples/blob/hibernate-5/jpa/pom.xml) with a few SQL adaptions and the version changed to `5.0.1.Final`.

**Comment by neblina-software** [comment]
@abdsabri I tried to set <hibernate.version>5.0.1.Final</hibernate.version> and it crashes too, to use the new features in Java 8 and hibernate, hibernate released a series of patches. What features do you want to use? and @olivergierke thanks for the references.

**Comment by neblina-software** [comment]
@olivergierke i think you can replace **joda-time** with **hibernate-java8**. I successfully my compilation here:

https://github.com/neblina-software/balerocms-enterprise/blob/master/pom.xml

**Comment by snicoll** [comment]
Hibernate 5 works with Spring Boot but there's still a few areas we need to improve (see #2763). If you need to use java 8 date and time, you need to add `hibernate-java8` to your classpath. Either way, Stackoverflow is a better place for that kind of discussion.
