### ISSUE TITLE
Upgrading gradle project to Spring boot 3.1.8 from 2.4.8 : When bootJar is disabled, gradle build command generated artifact name has -plain added to it in spring boot 3

### ISSUE THREAD

**Issue by SabeetaBhandari** [spring-projects/spring-boot#39523]
Compare gradle packaging in springboot 3.1.8 and springboot 2.4.8, **when bootJar is disabled**

When the spring boot version is '2.4.8' -> The artifact generated is 'artifactname.jar'
When the spring boot version is '3.1.8' -> The artifact generated is 'artifactname-plain.jar'

Notice the '-plain' classifier in artifact name after the upgrade. 

It seems when bootJar is disabled, the generated jar doesn't have -plain in the artifact name in spring boot 2.4.8.
But when I upgrade springboot to '3.1.8', the artifact name is changed.

I know we can solve this by adding **classifier= ''** under jar task. But this extra step was not needed in spring boot 2.4.8 version.
This needs to be documented. I couldn't find any documentation related to it, exactly which version has this change. 

Here is the reproducer code for this : https://github.com/SabeetaBhandari/gradle-packaging-test

**Comment by wilkinsona** [comment]
It has been this way [since Spring Boot 2.5](https://github.com/spring-projects/spring-boot/issues/23797) when it was documented [in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#gradle-default-jar-and-war-tasks). It's also documented in the [plugin documentation](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#packaging-executable.and-plain-archives).
