### ISSUE TITLE
Upgrade 2.7.x to 3.2.x. dialect.getSequenceNextValString replacement

### ISSUE THREAD

**Issue by zoroglu** [spring-projects/spring-boot#39537]
I'm upgrading to Spring Boot 3.2.2
**dialect.getSequenceNextValString** is deleted.
I'm just not sure how to replace it.

```
import org.hibernate.dialect.Dialect;

Dialect dialect = dialectResolver.resolveDialect(new DatabaseMetaDataDialectResolutionInfoAdapter(connection.getMetaData()));
PreparedStatement preparedStatement = connection.prepareStatement(dialect.getSequenceNextValString(sequenceName));
```

**Comment by scottfrederick** [comment]
Thanks for getting in touch. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. This feels like a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
