### ISSUE TITLE
Tracing in Feign client is broken since 3.2.1

### ISSUE THREAD

**Issue by najibk** [spring-projects/spring-boot#39653]
Hello,

~~Starting spring boot version 3.2.1, tracing is disabled by default, I have to explicitly set management.tracing.enabled=true, not sure this is the wanted behavior, at least it doesn't seem to be documented.~~

This is probably related to https://github.com/spring-projects/spring-boot/issues/38641

Edit : upon further investigation, it seems it's only affecting feign client, traceparent header is not propagated in http calls like in version 3.2.0

**Comment by wilkinsona** [comment]
If the problem's specific to Feign client, I suspect there won't be anything that we can do about it here but it's hard to say without knowing more. When you change the Spring Boot version, are you also changing the Spring Cloud version? If you are not then it may be a Boot problem and we'll need a minimal reproducible example so that we can investigate further.

**Comment by najibk** [comment]
here's a simple reproducer, there's a unit test that fails with spring boot 3.2.2 and not 3.2.0
https://github.com/najibk/spring-feign-micrometer

**Comment by mhalbritter** [comment]
Add `@AutoConfigureObservability` to your `@SpringBootTest` and the traces are propagated in tests, too. See https://github.com/spring-projects/spring-boot/issues/38641.
