### ISSUE TITLE
@ConditionalOnProperty  MatchIfMissing attribute not working as expected

### ISSUE THREAD

**Issue by hannah23280** [spring-projects/spring-boot#39692]
Spring boot version: 3.2.2

Scenario: Even though my application.properties did have **power.level** property,  but the bean is still created, which should not be the case, given the matchIfMissing being set to true. Is this a bug?
```
@AutoConfiguration
public class SuperHeroConfig {

    @Bean
    @ConditionalOnProperty(name = "power.level",matchIfMissing = true)
    public String powerLevel(){
        return "0";
    }
}
```
Below is application.properties
```
power.level=3
```

**Comment by wilkinsona** [comment]
No, this is the expected behavior. You have not set `havingValue` so its default behavior applies:

>  The string representation of the expected value for the properties. If not specified, the property must not be equal to `false`

Combined with `matchIfMissing = true` this means that the condition will match if `power.level` is missing or it has a value other than `false`. In other words `matchIfMissing = true` applies in addition to `havingValue` not instead of it.

**Comment by wilkinsona** [comment]
Sorry. There was a typo in my comment which I have now corrected. It will __not__ match because `power.level` has a value of `1` when it's required to be `0`.
