### ISSUE TITLE
@Required annotation does not work with @Configuration/@Bean bean creation

### ISSUE THREAD

**Issue by pedorro** [spring-projects/spring-boot#3981]
In a simple Spring Boot application, given the following class and bean creation code, the `@Required` annotation is not handled correctly:

```java
    @Configuration
    public class MyClassConfig {
    
        public static class MyClass {
            private String str = "str";
    
            @Required
            public void setStr(String str) {
                this.str = str;
            }
        }
    
        @Bean
        public MyClass myClass() {
            return new MyClass();
        }
    }
```

The required field 'str' of class 'MyClass' is not set during bean creation, but no exception is thrown during application startup.  

This happens because the `shouldSkip()` method of `RequiredAnnotationBeanPostProcessor` is returning true for this bean.  When I force that method to return false by changing values in a debugger, then the expected `BeanInitializationException` is thrown during startup.

As a further wrinkle, it turns out that even if the required field is set during bean creation, when I force the check to be done, it still throws the same `BeanInitializationException`, even though the field is getting set.

So it seems like the check mechanism is broken when instantiating beans using the non-XML @Bean notation and the work-around was to just skip that check.  Is this true?  And if so, are there any plans to enable that feature in the future?

**Comment by philwebb** [comment]
This appears to be a limitation of the `@Configuration` class model. Unlike XML, the `@Bean` method is entirely responsible for calling setters. 

If you step up one stack from the `shouldSkip()` breakpoint to `postProcessPropertyValues()` you should see that `pvs` is empty. I think since we have no XML definition of the property values to set this will always be the case.

You could raise this on the [Spring JIRA](https://jira.springsource.org/spr) since this is really a core framework concern.

**Comment by jatinhchanchlani** [comment]
Hi,
Is this issue resolved

**Comment by snicoll** [comment]
> You could raise this on the Spring JIRA since this is really a core framework concern.

@jatinhchanchlani not that we are aware of but there is nothing we can do here.
