### ISSUE TITLE
Memory increases with 3.2.3

### ISSUE THREAD

**Issue by clucca-gb** [spring-projects/spring-boot#39838]
After migrating 3.2.2 to 3.2.3,  in our apis memory started to rise until the pods fell:

![Captura de Tela 2024-03-06 às 10 35 25](https://github.com/spring-projects/spring-boot/assets/107067354/809ef05e-d052-475c-8308-a9d4ea5b7c66)

With 3.2.2:

![Captura de Tela 2024-03-06 às 10 35 34](https://github.com/spring-projects/spring-boot/assets/107067354/f2d33ef4-e88f-4d31-873d-79235f43545f)

In our tests it appears to be a problem related to aws.

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, without some more information we won't be able to diagnose the problem. It looks like your application contains a memory leak. I find that the best way to analyse a memory leak is by taking a series of heap dumps and then compare them looking for an increasing number of a particular type of object being retained in the heap. 

Due to the risk of a heap dump containing secrets, such analysis is often best done by you. Alternatively, if you're confident that the heap does not contain any information that should not be public, you could share them with us here and we can take a look.

**Comment by bclozel** [comment]
> In our tests it appears to be a problem related to aws.

What do you mean? Do you have data showing more memory consumed by Spring Boot classes? Did you attach a memory profiler to the application?

Please provide more information - right now this report isn't actionable for us.

**Comment by clucca-gb** [comment]
Thanks for the answer.
We are trying to find more detailed information about this issue.

**Comment by clucca-gb** [comment]
Regarding what I said about AWS, we noticed that only in apis we use spring-cloud-aws (latest version 3.1.0) this problem occurred with the springboot update.

**Comment by clucca-gb** [comment]
Hello!
I came back here with more details.
Under analysis with the new relic observability tool:
![image](https://github.com/spring-projects/spring-boot/assets/107067354/53bbb919-2ade-4dcd-a168-b533e24ab060)
The class with the possible problem was identified:
![image](https://github.com/spring-projects/spring-boot/assets/107067354/5ccfe563-9781-4f43-9278-7319b610a94b)
with the help of heapdump tool we compared both versions and found this scenario:

v3.3.2
![image](https://github.com/spring-projects/spring-boot/assets/107067354/44ca5ed2-d804-45cf-8db6-a9751749bd30)
v3.3.3
![image](https://github.com/spring-projects/spring-boot/assets/107067354/c354c78e-9289-4e6b-94b0-df22c8d23877)
![image](https://github.com/spring-projects/spring-boot/assets/107067354/5e9c545c-1bb1-4738-8bd7-c82da8373bf1)

**Comment by wilkinsona** [comment]
Thanks for the additional details. Spring Boot 3.2.3 upgraded to Undertow 2.3.12.Final. I suspect that it contains a regression that is causing the memory leak. Please try using Spring Boot 3.2.3 with Undertow downgraded to 2.3.10.Final which is the version used by Spring Boot 3.2.2. You may also want to try Undertow 2.3.11.Final to narrow things down further.

**Comment by Tythor** [comment]
Hi @clucca-gb, are you passing in an executor to the Undertow servlet like this?
```java
@Bean
public UndertowDeploymentInfoCustomizer undertowDeploymentInfoCustomizer() {
   return deploymentInfo -> deploymentInfo.setExecutor(new CustomExecutor());
}
```
Using Undertow in the default configuration did not cause problems for me until I switched to using a different executor.

**Comment by clucca-gb** [comment]
@Tythor  Hello!
Yeah, it is! 
I'll try to understand if it's possible to remove it.

**Comment by zhlian94** [comment]
Hi, 
I would like to add on my finding from my tech stack.
1.	leaking happened to server threads, as many as 200 (display one hundred, and boots default allow 200 as max). these server threads are managing the POST requests “/instances” from API services.
 
![image](https://github.com/spring-projects/spring-boot/assets/29045107/400612dc-2053-468d-8438-620824fd0c41)


2. these leaking threads lock memory and shown as memory leaks but not root cause indeed, if you see this leaking memory such as Byte objects leak(biggest), HttpClient leak, NioEndpoint leak.
 
![image](https://github.com/spring-projects/spring-boot/assets/29045107/9e3a3bc6-fae9-43ef-91db-52243d4d0940)

3. Use Dynatrace profiling tool to check memory allocation, first check ThreadPoolExecutor pool, look for CloseableHTTPClient.execute, I could not find them visually 
 
![image](https://github.com/spring-projects/spring-boot/assets/29045107/ee0468a9-88a5-4a63-90d9-6bcddb101fbc)

4. continue to check FastThreadLocalRunnable which is referenced by each worker in ThreadPoolExcutor above, I could not find CloseableHTTPClient.execute either.
 
![image](https://github.com/spring-projects/spring-boot/assets/29045107/712c1fdf-43cb-47f7-821e-f19610ac6785)

5. Given FastThreadLocalRunnable worker to manage all concurrent threads and the parallel threads are self-managed, who are going to manage the server threads in ThreadPoolExecutor? Given the finding that no CloseableHTTPClient is implemented, any leftover in thread local could make the server threads leak. Or If CloseableHTTPClient is implemented, how to manage reference from server worker to FastThreadLocalRunnable pool? Seems the thread leaks involved a dilemma in design and not resolved and leave it as leak hole.
Hope these feedbacks help designers and help to resolve the leak quicker. 
I intend to disable POST on boots server threads to stop thread leaking as temporary solution. I would like to hear your opinions.
Regards

**Comment by wilkinsona** [comment]
That's good news. Thanks, @clucca-gb. Please open an [Undertow issue](https://issues.redhat.com/projects/UNDERTOW/issues/UNDERTOW-1908?filter=allopenissues) so that they can investigate why configuring a custom executor as you have done now causes a memory leak. I'll close this issue for now as I don't think there's anything we can do about this in Spring Boot.

**Comment by wilkinsona** [comment]
@zhlian94 your problem appears to be unrelated. As far as I tell you're using Tomcat, not Undertow, and are perhaps using a Reactor Netty based WebClient too. If you'd like some help investigating why your application appears to be leaking memory, please ask on Stack Overflow to begin with.
