### ISSUE TITLE
Cannot extract spring-boot-autoconfigure-1.2.5.RELEASE.jar under ext4

### ISSUE THREAD

**Issue by mlaccetti** [spring-projects/spring-boot#3983]
I'm trying to create a fat jar, and everything is failing.  Gradle fails, tried it with the OS unzip, same problem:

```
error:  cannot create org/springframework/boot/autoconfigure/mobile/DeviceDelegatingViewResolverAutoConfiguration$DeviceDelegatingViewResolverConfiguration$ThymeleafViewResolverViewResolverDelegateConfiguration.class
        File name too long
```

How did this file even come to life without breaking the 255 char limit most filesystems have?

**Comment by wilkinsona** [comment]
The 255 character limit in ext4 is for the file name. The pathname is unlimited in length. In this case the file name, `DeviceDelegatingViewResolverAutoConfiguration$DeviceDelegatingViewResolverConfiguration$ThymeleafViewResolverViewResolverDelegateConfiguration.class` is 148 characters long. We build Boot on Windows, Linux and OS X without problem so, whatever the problem is, it would appear to be specific to your environment,

**Comment by mlaccetti** [comment]
Guess it is some random part of running it under a Docker container in a Virtualbox VM, then.  Weird.  I'll just filter it out in Gradle for now, and move along.

**Comment by UookaFreelance** [comment]
I'm having the exact same issue, any idea what is causing it?

**Comment by mlaccetti** [comment]
Encrypted home directory was breaking long paths.



On Mon, May 23, 2016 at 6:05 AM -0700, "UookaFreelance" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm having the exact same issue, any idea what is causing it?

-

**Comment by UookaFreelance** [comment]
Yup that was it, thanks a mill.
