### ISSUE TITLE
@Autowired Field Injection

### ISSUE THREAD

**Issue by faspeee** [spring-projects/spring-boot#39849]
Hi! 

I am working in an existing project and I saw that this project uses field injection, is this a bad practice? and it is advisable to remove them and use construction injection?

Thx!!

**Comment by mhalbritter** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
