### ISSUE TITLE
Rationalize spring data auto-configuration packages

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4002]
We currently have some oddness with some `*DataAutoConfiguration` class inside top level packages and some in `org.springframework.boot.autoconfigure.data.*`.

Mongo is a good example where `MongoDataAutoConfiguration` should probably move.

Redis is another example where the auto-configuration depends on Spring Data.

**Comment by hzpz** [comment]
I am maintaining a third party [starter for Mongeez](https://github.com/hzpz/mongeez-spring-boot-starter) which depends on `MongoDataAutoConfiguration`. Since this class moved in Spring Boot 1.3.0, using it results in `java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy` (see [issue #4](https://github.com/hzpz/mongeez-spring-boot-starter/issues/4)).

What is the right way to fix this? If I change the import, the starter will only work with Spring Boot > 1.3.0.

**Comment by philwebb** [comment]
@hzpz I think this is probably due to the `@AutoConfigureBefore`/`@AutoConfigureAfter` annotations on `MongeezAutoConfiguration`. Unfortunately I can't think of an easy way to fix it (unless we moved the classes back). I'm afraid the only option I can think of is create a new version of your starter specifically for 1.3. Sorry :(

**Comment by wilkinsona** [comment]
@hzpz I think you might be able to use the `name` attribute on `@AutoConfigurationBefore/After` to avoid the problem that Phil has described. You should be able to list the fully-qualified name of `MongoDataAutoConfiguration` both before and after it moved and the sorter will hopefully just ignore the one that's not there.

**Comment by philwebb** [comment]
Ahh, good point @wilkinsona. I forgot we added support for that!

**Comment by hzpz** [comment]
Thank you both for the quick answers! I will try what you suggested @wilkinsona.

**Comment by hzpz** [comment]
Using the `name` attribute on `@AutoConfigureBefore` works as promised. New release of the starter supports both Spring Boot >= 1.3.0 and < 1.3.0. Thanks again!

**Comment by wilkinsona** [comment]
Phew! Thanks for letting us know.

**Comment by snicoll** [comment]
:+1:
