### ISSUE TITLE
Can't download the project

### ISSUE THREAD

**Issue by jc-corrales-guerrero** [spring-projects/spring-boot#40136]
I can't download the project via github because there are files with names that are too long, and when trying to download it via .zip file, there's an error that says "invalid file" and it aborts the procedure. How can I download this project into my local machine?

**Comment by scottfrederick** [comment]
Please see the [Working with the Code](https://github.com/spring-projects/spring-boot/wiki/Working-with-the-Code) section on the wiki, especially the last section that covers Windows. 

As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. This feels like a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
