### ISSUE TITLE
Two different GET methods in the same controller with different parameters

### ISSUE THREAD

**Issue by alitariqnet** [spring-projects/spring-boot#40140]
I was creating the backend for Angular Tour of Heroes App and I ran into this problem. Don't you think that spring-boot should recognize them differently due to the number and/or type of their parameters? I think this can be enhanced in future releases.
![image](https://github.com/spring-projects/spring-boot/assets/75094670/919153c9-9a70-4ed4-be10-b1d4f8f82e36)
![image](https://github.com/spring-projects/spring-boot/assets/75094670/ee25a1c8-3b92-452d-aa7c-3010cdf849aa)

**Comment by nahidshahin** [comment]
No, form url point of view, GET:/heroes and GET:/heroes?id=123 is same because url param is not mandatory.

**Comment by bclozel** [comment]
This is by design - the `@*Mapping` annotation needs to described what the requests should look like to be mapped there. Checking the actual method signature is only done as a second step when invoking the handler.

`@GetMapping(params = "id")` should solve the problem here. For further questions, please use StackOverflow.
