### ISSUE TITLE
@Scheduled method not triggered on start of daylight savings time

### ISSUE THREAD

**Issue by ropoman** [spring-projects/spring-boot#40154]
I am in CEST timezone. The server was running fine for several days until on March 31st the two following scheduled methods were not called:

@Scheduled(cron = "0 30 3 * * ?")
@Scheduled(cron = "0 0 19 * * ?")
These were NOT CALLED on March 31st, but on April 1st everything was working again

@Scheduled(cron = "0 0 * * * ?")
This was called every hour

		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.2</version>

**Comment by mdeinum** [comment]
You are on a very old version of Spring Boot, one which uses Spring 5.3.3, Spring Boot 2.4.x has been out-of-support for quite some time. Try the newest version to see if the issue has been resolved. DST issues have been fixed in Spring 5.3.7, 5.3.16 and 5.3.17. 

Related: 
* https://github.com/spring-projects/spring-framework/issues/28430
* https://github.com/spring-projects/spring-framework/issues/28095
* https://github.com/spring-projects/spring-framework/issues/28245

**Comment by bclozel** [comment]
As mentioned by Marten, please [use a supported Boot version](https://spring.io/projects/spring-boot#support). [Spring Framework 5.3.x still has OSS support](https://spring.io/projects/spring-framework#support), but you should first test against the latest maintenance version.

I'm closing this issue for now but we can reopen it if you provide a sample application that demonstrates the problem with the latest maintenance version of Spring Framework.

Thanks!
