### ISSUE TITLE
Why do I turn on the virtual thread, the stress test throughput is much lower than the platform thread

### ISSUE THREAD

**Issue by zjypyj** [spring-projects/spring-boot#40155]
- Question
springboot3.2  spring.threads.virtual.enabled=true

I wrote an interface for inserting data into MySQL, and then tried to perform stress testing using JMeter. The actual throughput was much lower than the platform's threads. What could be the reason for this?

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In this case, there are many things that could be going on - maybe unlocking the concurrency at the web layer unveiled a bottleneck in your database connection pool? In any case, you will need to profile your application to better understand the behavior and act accordingly. This doesn't seem to be a Spring Boot bug, so I'm closing this issue.
