### ISSUE TITLE
Unify X-Forwarded for server properties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4018]
Issue #3881 and #3802 are asking for x-forward header support for Undertow and Jetty. We already have support for Tomcat and #3782 switched it on by default.

Interestingly `ProxyPeerAddressHandler` from Undertow includes the following warning:

> This should only be used behind a proxy that always sets this header, otherwise it is possible for an attacker to forge their peer address

I'm guessing this is because it doesn't have white-list support like the Tomcat version.

Undertow also doesn't allow customization of the header fields, so `portHeader` properties would be useless.

Perhaps we should consider a single `proxyPeerAddress` boolean property that enables forward headers and default it to off.

**Comment by philwebb** [comment]
@dsyer @wilkinsona @rwinch Thoughts?

**Comment by dsyer** [comment]
It seems like the tomcat support is better. Can we just switch off this feature by default in non-tomcat containers?

**Comment by wilkinsona** [comment]
As noted above, Undertow doesn't appear to offer any configuration and is at risk of address forgery. Jetty's [ForwardedRequestCustomizer](http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/server/ForwardedRequestCustomizer.html) is configurable in terms of the headers it looks for but doesn't offer any address filtering so it's also vulnerable to address forgery. In short, this feels like an area where there isn't sufficient common ground between the containers to provide configuration that works across all of them. 

I think we should add `server.undertow.*` and `server.jetty.*` configuration that's appropriate for those containers alongside the existing `server.tomcat.*` properties. The functionality should be disabled by default in Undertow and Jetty. I could also be convinced to disable it by default in Tomcat again.

**Comment by philwebb** [comment]
My initial thoughts were to add specific `server.undertow.*`, `server.jetty.*` and `server.tomcat.*` properties for fine-grained control but also add a single "switch on with sensible defaults" option:

```
server.proxy-peer-address=true
```

I think we should change Tomcat so that it's opt-in so that all containers behave in the same way.

**Comment by wilkinsona** [comment]
Sounds good to me

**Comment by dgomesbr** [comment]
Undertow should support that https://issues.jboss.org/browse/UNDERTOW-297

**Comment by rwinch** [comment]
I wonder if ensuring this is enabled by default in cloud environments would make sense though?

Alternatively, we could provide our own filter that wraps the request and ensures we have a consistent experience across all containers.

**Comment by philwebb** [comment]
@rwinch I'm not sure that we have a consistent way to detect all "cloud" environments so it's hard to see how we could do that. My preference is still the simplest option of making it opt-in.

**Comment by spencergibb** [comment]
spring-cloud-connectors is where to do 'something' based on which cloud environment you're in.

**Comment by rwinch** [comment]
To elaborate on my suggestion. It sounds as though there is inconsistencies in what is supported by each container. Perhaps it would be nice to provide a Filter that provides a consistent experience.

If we can provide a consistent experience across application containers, then something within the Spring portfolio could activate the custom Filter in cloud environments. Whether it is Boot's auto configuration within a cloud profile or Spring Cloud connectors, I'm not certain.

**Comment by dsyer** [comment]
I'm really against the opt-in option for the tomcat case which works really well. I could just about accept activating it with a profile, but really since it doesn't do harm on its own I'd rather just keep it.

If we fee like all containers have to be equal (why?) then it looks like we need a `Filter`.

**Comment by philwebb** [comment]
With the exception of `internalProxies` which seems to be unique to Tomcat, each container does offer a way to support x-forward headers.

The problem is that Undertow explicitly calls out that enabling the support should _only_ happen when running behind a proxy server:

> "This should only be used behind a proxy that always sets this header, otherwise it is possible for an attacker to forge their peer address"

When we switched Tomcat to enable x-forward support by default (#3782) I think we assumed that the `internalProxies` setting would protect us from forged headers. I guess that's still true although I don't know for sure.

I don't particularly like the idea of Tomcat behaving differently to Undertow and Jetty but I guess that's not such a big deal as long as we don't enable it by default for Undertow.

@rwinch Is there any way to spoof `request.getRemoteAddr()`? This seems to be what's matched against the `internalProxies`:

```java
        final String originalRemoteAddr = request.getRemoteAddr();
        ...
        if (internalProxies !=null &&
                internalProxies.matcher(originalRemoteAddr).matches()) {
        ...
```

**Comment by rwinch** [comment]
@philwebb 

> When we switched Tomcat to enable x-forward support by default (#3782) I think we assumed that the internalProxies setting would protect us from forged headers. I guess that's still true although I don't know for sure.

This is only somewhat true. It limits the attack surface to an internal network. For example, if the server is hosted on `192.168.56.1` and you have access to a machine within the internal network (i.e. `192.168.56.102` or anything that matches `internalProxies `), then they could forge the client IP address to be `127.0.0.1` with:

```bash
$ curl 192.168.56.1:8080 --header "x-forwarded-for: 127.0.0.1, 192.168.56.1"
```

If the server is restricting access at the application layer by ensuring the client IP address is the loopback interface this would bypass the constraint. One could argue this is bad practice, but it [does happen in the wild](http://blog.ircmaxell.com/2012/11/anatomy-of-attack-how-i-hacked.html).

> @rwinch Is there any way to spoof request.getRemoteAddr()?

Yes, but with some limitations. Generally attackers can forge a source IP address (what determines the original value of `request.getRemoteAddr()`). However, the response will be returned to the forged IP address. One way attackers can read the response is if they are in the same subnet as the forged source IP address.

All this said, I think it is best to have something enable the `x-forwarded-*` support vs provide it for all environments by default. This could be done with Spring Boot having a custom profile, Spring Cloud Connectors, etc. Personally, I like the idea of Spring Boot having a profile for it because it does not limit users to Spring Cloud Connectors.

**Comment by philwebb** [comment]
Thanks @rwinch!
