### ISSUE TITLE
SpringBoot 3.2.4 is pulling docker.io/paketobuildpacks/builder-jammy-tiny:latest for native image while recommended is gcr.io/paketo-buildpacks/java-native-image

### ISSUE THREAD

**Issue by KafkaProServerless** [spring-projects/spring-boot#40420]
Hello team, 

As of today, with SpringBoot 3.2.4 and the newly released JDK22, in the process of building a native image, this image is pulled by docker:
```
Pulling builder image 'docker.io/paketobuildpacks/builder-jammy-base:latest' 100%
[INFO]  > Pulled builder image 'docker.io/paketobuildpacks/builder-jammy-base@sha256:a913462b288209172cb7626c2ded55843002a7aa1a6bc87e9af52be1ab5511fc'
[INFO]  > Pulling run image 'docker.io/paketobuildpacks/run-jammy-base:latest' 100%
[INFO]  > Pulled run image 'docker.io/paketobuildpacks/run-jammy-base@sha256:8431203470391fc58454b71bdb917f53c20f403892fbb447f4ea5265a8d7cf49'
```

However, from the packeto team, to build a native image, this image is preferred:

https://github.com/paketo-buildpacks/java-native-image

Would it be possible to consider switching to this recommended image instead?
Thank you

**Comment by scottfrederick** [comment]
`paketobuildpacks/builder-jammy-base:latest` is a [CNB builder](https://buildpacks.io/docs/for-platform-operators/concepts/builder/), and `paketo-buildpacks/java-native-image` is a [CNB buildpack](https://buildpacks.io/docs/for-platform-operators/concepts/buildpack/). These two things do not perform the same function and are not interchangeable.

The Spring Boot Gradle plugin will default to using `paketobuildpacks/builder-jammy-tiny:latest` when the GraalVM Native Image plugin is applied to the project, and to `paketobuildpacks/builder-jammy-base:latest` otherwise. The Spring Boot Maven plugin will default to the `tiny` builder when the `native` profile is active, and to the `base` image otherwise. 

Both the `base` and `tiny`  builders include the `paketo-buildpacks/java` and `paketo-buildpacks/java-native-image` buildpacks. The `java-native-image` buildpack should be detected automatically when the build is configured [according to the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#native-image.developing-your-first-application).  

If you have follow-up questions, please post to [Stack Overflow](http://stackoverflow.com/). If you feel this is a genuine bug please provide additional information and we can re-open the issue if necessary.
