### ISSUE TITLE
升级springboot3.x + maven，在使用多环境配置时会多了native和nativeTest两个环境，请问如何去掉呢

### ISSUE THREAD

**Issue by Yuqn** [spring-projects/spring-boot#40437]
springboot2.x升到springboot3.x + maven，原本是创建了dev、prod、test环境配置，项目转到springboot3.x之后会多了native和nativeTest两个环境，请问如何去掉呢？

![image](https://github.com/spring-projects/spring-boot/assets/92110217/8d5ac206-f716-4c20-bfdc-f290d2062e9e)

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by yijianhanxiao** [comment]
就是在idea中创建SpringBoot3.x项目之后，idea中的maven侧边栏会显示native、和nativeTest，但是我pom.xml文件中profiles属性中并没有添加这两个环境名称
![image](https://github.com/user-attachments/assets/8fef0abe-6322-4bbd-8bef-2801db31329d)
