### ISSUE TITLE
Demo application exits immediately on Ubuntu 22 (WSL)

### ISSUE THREAD

**Issue by saeidalidadi** [spring-projects/spring-boot#40455]
I am running the Demo application of Spring Boot on Linux Ubuntu WSL but when executing the start command with `gradle  bootRun` 
the application starts and exits immediately without any error. 

```
Java openjdk version "17.0.9" 2023-10-17
Linux Ubuntu 22 on WSL
SDKMan last version
```
![spring-boot-error](https://github.com/spring-projects/spring-boot/assets/2406828/704d333d-0171-4536-b79a-725599317da0)

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In this case the application is probably missing a web server dependency. Please provide more information on your StackOverflow question to get help (build file, web controller, application properties...)
