### ISSUE TITLE
Some auto-configuration still use Ordered

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4056]
While the proper way to order auto-configurations is to use `@AutoConfigureOrder`, some are still using `Ordered`, for instance `org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration`, `org.springframework.boot.autoconfigure.web.ServerPropertiesAutoConfiguration` and `org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration`

**Comment by wilkinsona** [comment]
`ErrorMvcAutoConfiguration` and `ServerPropertiesAutoConfiguration` both implement `EmbeddedServletContainerCustomizer`. I suspect, but don't know for certain, that it's the customizer that needs to be ordered rather than the configuration class. This confusion could be avoided by moving the `EmbeddedServletContainerCustomizer` implementation into a named static inner class that's exposed as a `@Bean`, rather than overloading the configuration class's responsibilities.

`DataSourceTransactionManagerAutoConfiguration` appears to be `Ordered` for its own purposes. It looks like it should use `@AutoConfigureOrder` instead.
