### ISSUE TITLE
In Spring Boot version 3.2.5 tables are not auto generating under defined DB name although DB mentioned in properties file is created.

### ISSUE THREAD

**Issue by ShubhMehrotra** [spring-projects/spring-boot#40591]
I switched to version 3.2.5 just a few weeks ago and I am facing one issue with my entity class ,tables are not creating in DB even though all the configuration details are correctly mentioned in application.properties file and spring app is able to made a connection with the db and creating the  db with name mentioned in the properties file .

**Comment by wilkinsona** [comment]
Thanks for the report. Unfortunately, it doesn't contain enough information for us to be able to help you. You've mentioned an entity class so I guess that you're using JPA and Hibernate. Were you previously relying on Hibernate to create tables for you or using something else such as Flyway or Liquibase or a schema.sql script that's no longer running?

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by ShubhMehrotra** [comment]
Hi Andy you are partially correct I am using the JPA & Hibernate for table creation and previously also I was using the same but that was working fine but now when I switched to version 3.2.5 I am facing this issue. For more clarification I am attaching the zip file of source code below .
[Test.zip](https://github.com/spring-projects/spring-boot/files/15186629/Test.zip)

**Comment by wilkinsona** [comment]
Thanks for the sample. Unfortunately, it doesn't reproduce the behavior that you have described. The `address` table is not created when using Spring Boot 3.1.x and it is not created when using Spring Boot 3.2.x. This is because the `Address` entity is in the wrong package. To be found by default it must be in the same package or a sub-package of your main application class. Alternatively, you can use `@EntityScan` to scan to scan additional packages.

If you have any further questions, please follow up on [Stack Overflow](https://stackoverflow.com). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/main/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by ShubhMehrotra** [comment]
Hi Andy I have tried with @EnityScan too but its not working and mone more thing upto version 3.1.x its working fine no matter wherever the entity class is defined by default only it took it and create the tables . If you want then I can attach the screenshots too ,Your response are truly appreciable .

**Comment by philwebb** [comment]
@ShubhMehrotra Screenshots aren't that helpful I'm afraid. We'll need a sample that works with 3.1 but fails with 3.2.
