### ISSUE TITLE
setReadTimeout can't be set via Reflective factory on JettyClientHttpRequestFactory

### ISSUE THREAD

**Issue by fml2** [spring-projects/spring-boot#40635]
https://github.com/spring-projects/spring-boot/blob/8b8e263835206d50200abf1aced10be62c6fbfb7/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/client/ClientHttpRequestFactories.java#L394

The above line (in the Reflective factory) tries to find and invoke the `setReadTimeout` method with a parameter of type `int`. However, some of the used factories, e.g. the Jetty one, have other parameter types of this method. Jetty has `long` ([here](https://github.com/spring-projects/spring-framework/blob/168276aaab14456cfcc1b0bd440a26e0682f8f90/spring-web/src/main/java/org/springframework/http/client/JettyClientHttpRequestFactory.java#L93)) and `Duration` ([here](https://github.com/spring-projects/spring-framework/blob/168276aaab14456cfcc1b0bd440a26e0682f8f90/spring-web/src/main/java/org/springframework/http/client/JettyClientHttpRequestFactory.java#L102)).

Hence the readTimeout parameter can't be set via the Reflective factory if the real factory is the Jetty one.

IMO the code should look for "setReadTimeout" methods with different parameters (at least `int`, `long` and `Duration`), and call the first one found.

**Comment by scottfrederick** [comment]
None of Spring Boot's built-in request factory implementations (`HttpComponentsClientHttpRequestFactory`,  `JettyClientHttpRequestFactory`, `JdkClientHttpRequestFactory`, ` SimpleClientHttpRequestFactory`, `OkHttp3ClientHttpRequestFactory`) use this `Reflective` class for setting properties. When Jetty is being used for the client connection, the read timeout is set here using the Jetty `setReadTimeout` method that takes a `long`: 

https://github.com/spring-projects/spring-boot/blob/8b8e263835206d50200abf1aced10be62c6fbfb7/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/client/ClientHttpRequestFactories.java#L263

If you are somehow jave a `ClientHttpRequestFactory` implementation with Jetty that goes through the `Reflective` code path, can you show us an example of what you're doing?

**Comment by fml2** [comment]
Yes, I do have such a path. We create a RestTemplate using the RestTemplateBuilder. We'd like every request sent by the template to be wrapped by a BufferingRequest (in order to be able to log the request before it's sent), but the nested request should be created as configured by other factories. Hence we use this:

```
restTemplateBuilder
    .requestFactory(() -> new BufferingClientHttpRequestFactory(ClientHttpRequestFactories.get(ClientHttpRequestFactorySettings.DEFAULTS)))
```

This form of the "requestFactory" method uses `Reflective`.

**Comment by mhalbritter** [comment]
Reproducer here: 
[sb-40635.zip](https://github.com/spring-projects/spring-boot/files/15246872/sb-40635.zip)

**Comment by mhalbritter** [comment]
The `ClientHttpRequestFactory` we support have the following signatures:

HttpComponentsClientHttpRequestFactory
- setConnectTimeout int
- setConnectTimeout Duration
- no setReadTimeout

JettyClientHttpRequestFactory
- setConnectTimeout int
- setConnectTimeout Duration
- setReadTimeout Duration
- setReadTimeout long

JdkClientHttpRequestFactory
- no setConnectTimeout
- setReadTimeout Duration
- setReadTimeout int

SimpleClientHttpRequestFactory
- setConnectTimeout int
- setConnectTimeout Duration
- setReadTimeout Duration
- setReadTimeout int

OkHttp3ClientHttpRequestFactory
- setConnectTimeout int
- setConnectTimeout Duration
- setReadTimeout Duration
- setReadTimeout int


We can fix this bei either preferring the `Duration` accepting methods or by getting the `setReadTimeout` fixed in `JettyClientHttpRequestFactory` to also accept an integer.
