### ISSUE TITLE
Export SBOM contained in native-image

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#40630]
GraalVM's `native-image` [has a feature](https://www.graalvm.org/latest/security-guide/native-image/#software-bill-of-materials) where it can create a SBOM on native image build time and embed it. You can then use the `native-image-inspect` to extract the SBOM from the native image.

The GraalVM team would be open to expose an API in the `graal-sdk` to get the SBOM  directly without the need of the `native-image-inspect`. We could add support for that in our actuator SBOM endpoint.

**Comment by mhalbritter** [comment]
@fniephaus Would it be possible to expose the embedded SBOM via a standard Java mechanism, e.g. a readable resource on the classpath or some custom URL scheme? Then we wouldn't need to add the dependency on the GraalVM SDK and it would work right now with Boot 3.3.0-RC1.

**Comment by fniephaus** [comment]
@mhalbritter I think that's technically feasible. Can you give an example or two how SBOMs are otherwise accessible via classpath/modulepath or a custom URL scheme?

**Comment by mhalbritter** [comment]
Sure. Take a look [at this documentation here](https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints.sbom).

**Comment by mhalbritter** [comment]
Native images now expose their SBOM under `META-INF/native-image/sbom.json`. We should take a look if it makes sense to automatically discover them.

**Comment by fniephaus** [comment]
The new SBOM on classpath feature is available in EA build 19 of Oracle GraalVM:

```bash
sdk install java 23.ea.19-graal
```
If you add `--enable-sbom=classpath` to the build arguments, the native image should contain a SBOM based on the static analysis under `META-INF/native-image/sbom.json`. Feel free to give this a go and let us know if there's any problem :)

**Comment by mhalbritter** [comment]
Until Spring Boot adds built-in support, here are the steps to get that working with the current Spring Boot version:

1. Add the flag
```gradle
graalvmNative {
    binaries {
        main {
            buildArgs.add("--enable-sbom=classpath")
        }
    }
}
```

2. Make the SBOM known to Spring Boot:

```properties
management.endpoint.sbom.additional.native-image.location=optional:classpath:META-INF/native-image/sbom.json
```

**Comment by mhalbritter** [comment]
GraalVM 23 has been released and it contains the SBOM feature.

**Comment by mhalbritter** [comment]
With this implemented, all you need to do is

```gradle
graalvmNative {
    binaries {
        main {
            buildArgs.add("--enable-sbom=classpath")
        }
    }
}
```

and Spring Boot will expose the SBOM with the `native-image` id.

**Comment by mhalbritter** [comment]
We have to see if we can find out the GraalVM version used, as `--enable-sbom=classpath` only works with Graal 23 and above.

**Comment by blaghed** [comment]
Hi @mhalbritter , thanks for the approach with `management.endpoint` above.

In case you are still following this ticket:

### 1) GraalVM Version

> We have to see if we can find out the GraalVM version used, as `--enable-sbom=classpath` only works with Graal 23 and above. I'll investigate.

Does that really matter? The location is `optional:classpath`, so wouldn't this return the sbom if it exists and not have the endpoint if it doesn't exist? Or is there more to the behaviour here?

### 2) Usage of Actuator

The suggested workaround is great, but it relies on the Spring Boot application having the Web + Actuator natures applied to them.
Would it make sense instead to add some special "input" to the Spring Boot Args that would result in it printing the sbom instead of it running the full application?

E.g.:
```bash
$ my-app --sbom
{ sbom contents here, or !=0 exit code if not found } 
```
```bash
$ my-app <nothing, or anything else>
(normal application being executed, whatever it may be)
```

Might be tricky to prevent collision of the `--sbom` argument with anything else that may have been devised by the many users, but then a `-Dspring.native.sbom.print=true`, or having this as a configurable behaviour, or whatever else you feel is most appropriate could be used alternatively.

**Comment by mhalbritter** [comment]
Hi,

1) To automatically pass `--enable-sbom=classpath` to GraalVM when building the native image, we need to find out the native image version used. Because only GraalVM >= 23 supports `--enable-sbom=classpath`.

2) We could maybe add SBOM printing to the `-Djarmode=tools` feature. Please open a new issue for that, if that would be interesting for you.

**Comment by blaghed** [comment]
Thank you for the suggestion, that would fit perfectly -- #45954
