### ISSUE TITLE
Ensure `devtools` works with Spring Loaded 

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4067]
When https://github.com/spring-projects/spring-loaded/issues/139 we should look at something similar to #3095

**Comment by snicoll** [comment]
I just asked @aclement for help.

**Comment by aclement** [comment]
I'd start with trying to load `org.springsource.loaded.SpringLoaded` - if it loads check the class loader that loaded it - if loaded via the agent route that might be indicated by the class loader being null (or it might be a named one that otherwise indicates 'system'). If that doesn't work maybe check if initialization has occurred. In `org.springsource.loaded.agent.SpringLoadedAgent` there is a method `public static Instrumentation getInstrumentation` which will throw an `UnsupportedOperationException` if instrumentation is OFF. (or if you don't want to look for exceptions, check the value of the field `private static Instrumentation instrumentation` in that type - is it null? If so the agent is off)

**Comment by snicoll** [comment]
Spring Loaded does not support Spring Framework 4.2 so we'll wait for that first.

**Comment by wilkinsona** [comment]
Superseded by #7978
