### ISSUE TITLE
Why is the configuration of SpringBoot reading incorrect?

### ISSUE THREAD

**Issue by aiYunS-love** [spring-projects/spring-boot#40912]
I need to hide my IP address. I set this IP in the environment variable of Mac and refer to this IP address in yml, but I can't read the correct address. It seems that I have read the previous old address.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
