### ISSUE TITLE
HttpMessageConverters should distinguish between server and client converters

### ISSUE THREAD

**Issue by poutsma** [spring-projects/spring-boot#40925]
Unless I am mistaken, `HttpMessageConverters` is used on both client and server to provide a default set of message converters. In the process of determining those defaults, the `RestTemplate` [is used](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/http/HttpMessageConverters.java#L197). This has the unfortunate consequence that framework converters written to only be used on the client-side are also registered on the server. Specifically, the [`AllEncompassingFormHttpMessageConverter` is set up](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/http/HttpMessageConverters.java#L154).

The end result of the above is that Spring MVC (when used with Boot) is capable of writing forms on the server side, which does not make any sense. In Framework, we distinguish between converters [for the client side](https://github.com/spring-projects/spring-framework/blob/6a8f0d6d7d4379860e0197f321f0784f8b46e5df/spring-web/src/main/java/org/springframework/web/client/DefaultRestClientBuilder.java#L382) and [server side](https://github.com/spring-projects/spring-framework/blob/6a8f0d6d7d4379860e0197f321f0784f8b46e5df/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java#L890). I suggest that Spring Boot should make the same distinction.

**Comment by wilkinsona** [comment]
> In the process of determining those defaults, the RestTemplate [is used](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/http/HttpMessageConverters.java#L197)

That shouldn't be the case in a servlet-based web app. When `org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport` is on the classpath, its default converters are used rather than those of `RestTemplate`:

https://github.com/spring-projects/spring-boot/blob/d26881acb42161aae2af854d4c93df83d7dfef81/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/http/HttpMessageConverters.java#L184-L201

MVC [includes an instance of `AllEncompassingFormHttpMessageConverter` by default](https://github.com/spring-projects/spring-framework/blob/fc54cf443098d5705cf2e05f28e86e5b64730239/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/WebMvcConfigurationSupport.java#L895) so Boot does too. Unless I've missed something, if a distinction is to be made here, it should be made in Spring MVC and Boot will then pick up that change automatically.

**Comment by poutsma** [comment]
You are correct; I was mistaken. We are—mistakenly I'd argue—registering the `AllEncompassingFormHttpMessageConverter` on the server side.
