### ISSUE TITLE
In 3.2.3+ , the auto-configured reactiveNeo4jTransactionManager may caused a failure due to multiple TransactionManager beans

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#40953]
Forward port of issue #40895 to 3.3.x.

**Comment by yangyaofei** [comment]
please see this issue https://github.com/spring-projects/spring-data-neo4j/issues/2931

the `transactionManager` in [neo4j Neo4jDataAutoConfiguration.java](https://github.com/spring-projects/spring-boot/blob/8ea6d3c92ead011af1e8980272b2e1d8502bab4e/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/neo4j/Neo4jDataAutoConfiguration.java#L113) will not create when using `spring-data-jpa` because in `JpaBaseConfiguration` the `transactionManager` for jpa will be created and then pop out error in neo4j show in issue below.

If I create a `transactionManager` for neo4j, the jpa will throw error when using like `saveAndFlush`.

I think (may not right or elegant) maybe disable `Neo4jTransactionManager` bean and make it in `Neo4jTemplate` bean is a way, or warp `Neo4jTransactionManager` into some container to prevent it extend from `TransactionManager`.
