### ISSUE TITLE
Using 'eureka aware' RestTemplate completely breaks devtools reload

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-boot#4097]
I have a trivial app that uses a trivial microservice which it talks to via a 'RestTemplate' that automagiclaly uses the hostnames in its url to resolve services on Eureka.

When I change anything, even just trivial changes to hello-worldish string messages in unrelated controller, the RestTemplate breaks on reload. So it seem devtools reload is completely useless if I use a 'magic' RestTemplate to resolve services from Eureka.

Sample projects: https://dl.dropboxusercontent.com/u/9031956/projects.zip

To reproduce. Import the projects into STS (or however you want to run them I suppose :-) as 'existing eclipse projects).

From the boot dashboard, launch them all.

Open http://localhost:8080/date

It should show something like "It is now Mon Oct 05 14:36:32 PDT 2015".

Make an edit, pretty much anywhere in the project. For example change the message String in the totally unrelated 'TestController' to whatever.

Let devtools do its reload thing.

Reload the page at http://localhost:8080/date

It now spouts unintelligible garbage like this:

        There was an unexpected error (type=Internal Server Error, status=500).
        Error creating bean with name 'ribbonLoadBalancer' defined in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ILoadBalancer]: Factory method 'ribbonLoadBalancer' threw exception; nested exception is java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3479abc4 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6819413b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]

**Comment by dsyer** [comment]
I noticed this too. It seems like a thread pool wasn't shut down cleanly. Maybe something we can fix in Spring Cloud (don't know, cc @spencergibb)?

**Comment by spencergibb** [comment]
Maybe related to https://github.com/spring-cloud/spring-cloud-netflix/issues/571?

**Comment by ccit-spence** [comment]
@spencergibb This is the same problem I have encountered that I mentioned within Gitter.  Any change even a simple ```println``` will cause the problem.

**Comment by wilkinsona** [comment]
`DynamicServerListLoadBalancer` uses a static variable, `_serverListRefreshExecutor`, to store an executor. It also registers a shutdown hook to call shutdown on this executor. DevTools runs shutdown hooks as part of the restart process. This leaves `DynamicServerListLoadBalancer` with a shutdown executor which refuses to accept any more tasks.

**Comment by wilkinsona** [comment]
`DynamicServerListLoadBalancer` can be fixed with some reflective hackery to null out the executor while the shutdown hooks are being run. That then reveals a similar problem with `NFHttpClient`. 

`NFHttpClient has a static executor that's an instance of `com.netflix.utils.ScheduledThreadPoolExectuorWithDynamicSize`. Unfortunately this executor registers its own shutdown hook that calls `shutdown` directly. This means that we can't use the same reflective hack to stop the hook from shutting down the executor.

These problems, along with those encountered in gh-4279, are making me question whether running shutdown hooks during restart is a good idea.

**Comment by philwebb** [comment]
We'd need to find another way to trigger context shutdown if we don't trigger shutdown hooks.

**Comment by wilkinsona** [comment]
> We'd need to find another way to trigger context shutdown if we don't trigger shutdown hooks.

That feels like a more tractable problem than dealing with every library's use of shutdown hooks.

I'm sure there's an edge case or several that I've overlooked, but injecting the application context into `RestartConfiguration` and then passing that to `Restarter.restart()` so that `close()` can be called in place of calling the shutdown hooks fixes the problem in this issue, albeit with breaking API changes to `Restarter`.

**Comment by philwebb** [comment]
Breaking API changes are fine in the `Restarter` I think. Feels like a somewhat internal API.
