### ISSUE TITLE
Properties read from traditional application.properties files are not trimmed

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#4106]
The property values read from traditional `application.properties` configuration files are not trimmed. This can lead to undesired/strange behaviours at runtime:
- @ConditionalOnProperty annotation perform a simple _equals_ between the expected and received value (without type conversion). A property value set to `'true '` (notice the space at the end) is likely to fail the condition
- developers must/should trim the injected string values themselves

Not trimming values out of properties files is error prone (you can't blame a user if they forgot a blank at the end of the line - they don't see it). It may be acceptable for XML files however: value is between start/end markers so the blank is visible.

Proposition is to update the `PropertiesPropertySourceLoader` so it automatically trims values read from `.properties` files.

**Comment by wilkinsona** [comment]
We've discussed this and decided that there's no way that we can safely trim properties as we have no way of knowing whether or not it was intentional.

If you have a problem where developers are leaving trailing whitespace in a properties file and you know that you never want such trailing whitespace, I would recommend configuring your editor to remove it automatically.

**Comment by lunarcloud** [comment]
At least add a warning!
This ran us crazy trying to figure out why some people saw an error and others didn't, only to find out it was because of-what most editors show as-invisible characters!

**Comment by lunarcloud** [comment]
Nevermind. My issue was with the logging properties reader, not the generic property reading.
