### ISSUE TITLE
Spring boot not working well with spring-mvc ecosystem components

### ISSUE THREAD

**Issue by tenstriker** [spring-projects/spring-boot#4109]
Please see details on following stackoverflow page.

http://stackoverflow.com/questions/32994150/spring-boot-how-to-use-both-resteasy-jax-rs-and-spring-mvc-controllers/33001732#33001732

What I am asking is more elegant solution.

I read following: 
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-auto-configuration

Which says @EnableWebMvc is to take complete control over mvc components which is not I am looking for. I was just trying to hook additional components to MVC.

**Comment by wilkinsona** [comment]
The section you have linked to already explains what to do:

>  If you want to keep Spring Boot MVC features, and you just want to add additional MVC configuration (interceptors, formatters, view controllers etc.) you can add your own `@Bean` of type `WebMvcConfigurerAdapter`, but without `@EnableWebMvc`.

I'm not sure how we could document this any more clearly. If you have any suggestions, or even better a pull request, please let us know.

**Comment by tenstriker** [comment]
Yes I did saw that but I couldn't find any examples how to implement that for HandlerAdapters, Interceptors, MessageConverter. I found some example here but it doesn't work for my scenario which is to have spring mvc work alongside resteasy jaxrs
https://github.com/spring-projects/spring-boot/issues/2870

In general, there should be examples for each of these common customization use cases like there are on core spring reference documents.

**Comment by wilkinsona** [comment]
> In general, there should be examples for each of these common customization use cases like there are on core spring reference documents.

Spring Boot builds on top of Spring Framework. The Spring Boot documentation is intended to describe how Spring Boot works, not how Spring Framework works. Where Spring Boot does things differently, or we think there's something that you need to be aware of, we aim to cover that in the documentation. Where it's standard Spring MVC, you should refer to the Spring Framework documentation. The alternative would be for Spring Boot to duplicate all of Spring Framework's documentation which just isn't practical.

Taking each of your requested examples in turn:

> MessageConverter

Searching the documentation for `MessageConverter` quickly leads to [this](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-message-converters):

> If you need to add or customize converters you can use Spring Boot’s `HttpMessageConverters` class:
> …
> Any `HttpMessageConverter` bean that is present in the context will be added to the list of converters. You can also override default converters that way.

> Interceptors

Searching the documentation for `Interceptors` quickly leads to [this]:

> If you want to keep Spring Boot MVC features, and you just want to add additional MVC configuration (interceptors, formatters, view controllers etc.) you can add your own `@Bean` of type `WebMvcConfigurerAdapter`, but without `@EnableWebMvc`.)

That's pretty clear, to me at least, that you should use the standard Spring MVC mechanism of overriding [`addInterceptors` on `WebMvcConfigurerAdapter`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurerAdapter.html#addInterceptors-org.springframework.web.servlet.config.annotation.InterceptorRegistry-).

> HandlerAdapters

This is the only one that isn't explicitly mention in the Spring Boot docs. However, again, that's because it's standard Spring MVC. If you want to add your own `HandlerAdapter` to the context just declare it as an `@Bean` and it'll get picked up automatically.

If you have specific amendments that you'd like to propose for the documentation, a PR would be gratefully received.

**Comment by tenstriker** [comment]
Spring-resteasy has it's own following set of beans that works with spring-mvc. How I am supposed to convert all those to @Bean. I tried importing it as @ImportResource as I described on my stackoverflow question but it doesnt work.

resteasy.deployment
resteasy.registry
resteasy.dispatcher
resteasy.providerFactory
resteasy.spring.bean.processor
abstract.resteasy.handlerMapping
resteasy.handlerMapping
resteasy.handlerAdapter
resteasy.exception.handler
resteasy.no.resource.found.view
reateasy.error.view.resolver

**Comment by wilkinsona** [comment]
Sorry, but "it doesn't work" isn't very informative.

The REST Easy documentation [describes what to do](https://docs.jboss.org/resteasy/docs/3.0.13.Final/userguide/html_single/#RESTEasy_Spring_Integration), albeit in XML. The Java equivalent of the necessary XML is `@ImportResource(classpath:springmvc-resteasy.xml)`. That should be all that's necessary. No need to reconfigure the dispatcher servlet or to use `@EnableWebMvc`.

Your own answer to your question on Stack Overflow mentions a Scaled-based object mapper but it's not at all clear how that relates to integrating RESTEasy with Spring Boot. In short, after all of this, I don't really know what the problem is that you're trying to solve.

It looks like your just looking for some help with RESTEasy and Spring Boot. This isn't the right place to get that help. [As described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. I'd recommend reading [StackOverflow's advice on asking questions](http://stackoverflow.com/help/asking), in particular on how to provide a [minimal complete verifiable example](http://stackoverflow.com/help/mcve) and either updating your existing question or asking a new one.
