### ISSUE TITLE
Git instant properties cannot be coerced following git-commit-id Maven plugin upgrade

### ISSUE THREAD

**Issue by zdu-strong** [spring-projects/spring-boot#41109]
1. In 3.2.6, it works fine.
Repository:   [https://github.com/zdu-strong/Temp-Test-Spring-Boot-Good-Work.git](https://github.com/zdu-strong/Temp-Test-Spring-Boot-Good-Work.git)
Required environment: java v21
Run command:     ./mvn clean test
<img width="1280" alt="image" src="https://github.com/spring-projects/spring-boot/assets/48673442/2bc349f8-68be-46bb-9240-4e1e3aacbff5">

2. In 3.3.0, it works badly.
Repository:   [https://github.com/zdu-strong/Temp-Test-Spring-Boot-Bad-Work.git](https://github.com/zdu-strong/Temp-Test-Spring-Boot-Bad-Work.git)
Required environment: java v21
Run command:     ./mvn clean test
<img width="1280" alt="image" src="https://github.com/spring-projects/spring-boot/assets/48673442/74ec8af7-0fa6-4688-a647-6474e44b68cf">

**Comment by philwebb** [comment]
Thanks very much for the report. This is due to a change in the `dateFormat` generated by the `git-commit-id-maven-plugin`. Until we fix it, you can work around it by setting `dateFormat` in your plugin configuration:

```xml
<plugin>
    <groupId>io.github.git-commit-id</groupId>
    <artifactId>git-commit-id-maven-plugin</artifactId>
    <configuration>
        <verbose>true</verbose>
        <generateGitPropertiesFile>true</generateGitPropertiesFile>
        <failOnNoGitDirectory>true</failOnNoGitDirectory>
        <dotGitDirectory>
            ${project.basedir}/.git</dotGitDirectory>
        <offline>true</offline>
        <dateFormat>yyyy-MM-dd'T'HH:mm:ssZ</dateFormat>
    </configuration>
</plugin>
```

We'll need to update [this code](https://github.com/spring-projects/spring-boot/blob/df087fad9ec4a8dd6bc51a007d80a6cad9bc86d8/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/info/GitProperties.java#L117) to use the new format and fallback to the old one if it doesn't work.

**Comment by zdu-strong** [comment]
Thank you very much for your help!
