### ISSUE TITLE
Properties file precedence - issue while switching to JAVA 8

### ISSUE THREAD

**Issue by nsdiv** [spring-projects/spring-boot#4111]
Hi,
Found an issue while switching from JAVA 7 to JAVA 8. The order of profile properties that are defined in both yml and properties file is switched.

The working sample is posted here, with steps to reproduce:
https://github.com/nsdiv/spring-boot-java8-java7-prop-loading

Specifically, we're using spring boot version 1.2.3.RELEASE, but can reproduce this issue in 1.2.6.RELEASE as well

**Comment by shrisha** [comment]
Another sample (with less dependencies) that demonstrates the issue: https://github.com/shrisha/spring-boot-config-precedence

**Comment by dsyer** [comment]
It's pretty unusual to use properties and yaml files in the same project and with profile specific overrides for the same profile in both. So I think this is an edge case (hence I marked as "enhancement") but we can fix it because it is all to do with the ordering of supported file extensions (using a plain `HashSet`: https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/env/PropertySourcesLoader.java#L202).

**Comment by shrisha** [comment]
thanks for the quick fingers, @dsyer!
