### ISSUE TITLE
Springboot connection database password acquisition error

### ISSUE THREAD

**Issue by DreamToffee** [spring-projects/spring-boot#41287]
The password obtained by Springboot when connecting to the database is not the password in my configuration file, which has caused my database connection to fail continuously,I am using the SQL Server database
![Uploading 4818a8d6-f164-433a-a77e-6cac9aa7e1f2.png…]()
![Uploading c9488516-dce7-40d7-8d5f-20167eda5660.png…]()

**Comment by DreamToffee** [comment]
![Uploading 4818a8d6-f164-433a-a77e-6cac9aa7e1f2.png…]()

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

In this case, another properties file or an environment variable is probably changing this confirmation property. Please ask a question on StackOverflow and add a minimal sample application that people can use to reproduce the problem.

**Comment by wilkinsona** [comment]
@DreamToffee, please do not open duplicate issues, you can comment on an issue after it has been closed. https://github.com/DreamToffee/springProblem.git from #41288 shows that you need to quote the password to avoid YAML's type conversion.

**Comment by DreamToffee** [comment]
@wilkinsona Based on your reminder, I successfully connected to the database, which indeed was my issue. I deeply apologize for any inconvenience this may have caused you, and I greatly appreciate your assistance.
