### ISSUE TITLE
Spring Boot Webflux, cannot get PreAuthorize to work on Spring Security (in Kotlin)

### ISSUE THREAD

**Issue by dreamstar-enterprises** [spring-projects/spring-boot#41290]
Please see here >>

https://stackoverflow.com/questions/78698990/spring-webflux-preauthorize-not-working-work-using-kotlin

**Comment by scottfrederick** [comment]
As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. [Stack Overflow](http://stackoverflow.com/) is the appropriate place for this question, please don't cross-post questions to GitHub issues.

**Comment by dreamstar-enterprises** [comment]
Hi Scott, 

Thanks for the prompt response. If this doesn't work though, is this not a 'bug', and request for an 'enhancement'. 
Seems like a thin line...?

**Comment by scottfrederick** [comment]
It's hard to tell yet if this might be a bug or enhancement. There are several projects involved here, including Spring Boot, Spring Security, and Spring Framework. Posting a question to StackOverflow with the right tags gets the most number of eyes on the problem across projects instead of just the Spring Boot maintainers who monitor this GitHub project. If it can be narrowed down to an issue in one of these projects, then we can either re-open this issue or create a new one in the appropriate project. 

Posting a question to StackOverflow and then opening an issue risks duplication of effort as people might try to help without noticing someone else already helping on anther site. Spring project teams are small and we can't afford this kind of duplicated effort, so we strongly discourage cross-posting.

**Comment by dreamstar-enterprises** [comment]
Thanks Scott.

I did some more testing, and my conclusion is that this does seem to be a bug:
I could get it to work in one scenario, but not many others.

https://stackoverflow.com/questions/78698990/spring-webflux-spring-security-preauthorize-not-working-work-using-kotlin
