### ISSUE TITLE
spring-boot-maven-plugin includes "provided" scope dependency in JAR

### ISSUE THREAD

**Issue by ghost** [spring-projects/spring-boot#413]
With JAR packaging & spring-boot-maven-plugin, dependency with scope "provided" ends up in repackaged JAR.

I'm under impression that this should not be the case?

Should ResolutionScope be something else in RepackageMojo?

**Comment by gordon00** [comment]
Too bad, it would have been useful in GWT context.
When you use GWT, you have to add GWT dependencies that are needed only by the maven-gwt-plugin to procuce some javascript files. (They have to be project dependencies, not plugin dependencies)
In classic maven war project , you just set provided scope to few "root" gwt dependencies and that's it.
Here, you have to browse all gwt dependency branch to add them into "excludes" xml element. So boring... that does not match maven provided scope spirit... don't you agree ?

**Comment by wilkinsona** [comment]
@koscejev That's an interesting suggestion, thanks. I'd you like us to consider it, can you please open a separate issue so that it doesn't get forgotten in this closed issue?

**Comment by koscejev** [comment]
@wilkinsona no problem: #13289

**Comment by jeacott1** [comment]
I wound up here for a slightly different reason. I have a standalone primary spring boot executable jar, and a plugin jar (also with a spring-boot parent starter) that depends on the primary as provided scope, and is dynamically loaded at runtime.
I wanted to include the build-info in the jar file so I thought I'd just use the  spring-boot-maven-plugin build-info goal, but alas my plugin includes everything in the primary project as well as all its own dependencies. the docs for the build-info dont say anything about repackaging or otherwise affecting the build, so I'd thought (naively) that it wouldn't. alas I was wrong. :(  
imo violating a basic tenant of a basic maven directive isn't a good idea at all. you could very easily wind up with multiple versions of jars in the same env if not very careful.

**Comment by wilkinsona** [comment]
> you could very easily wind up with multiple versions of jars in the same env if not very careful

I don't believe that can happen. Can you please explain how it could?

**Comment by wilx** [comment]
Here is a scenario that I have. I have dependencies that have dependencies like `javax.annotation:javax.annotation-api` and other that already use `jakarta.annotation:jakarta.annotation-api`. These two overlap and I would like to know which one is actually used so, ideally, I would be able to declare one as provided and use the other internally.

**Comment by wilkinsona** [comment]
Those two dependencies contain the same classes so you should exclude one rather than using provided scope. In Boot 2.2, we moved to the Jakarta-named artifacts so I'd recommend `jakarta.annotation:jakarta.annotation-api` there. If you're using Boot 2.1, the javax-named artifact is probably the one to keep.

**Comment by vananiev** [comment]
I fix related issue with maven runtime dependency with maven profiles (I add release and debug profiles).

**Comment by chanseokoh** [comment]
As a workaround, one could use Spring Boot's [`<excludes>`](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/html/#repackage-example-exclude-dependency) to exclude dependencies. However, note that it still includes all the transitive dependencies, so you should identify and list them too. (See #22891 and #13289 for more details.)

**Comment by chanseokoh** [comment]
Correction: #22981, not #22891.
