### ISSUE TITLE
Has the loading order of springboot3 beans changed?

### ISSUE THREAD

**Issue by developwbperson** [spring-projects/spring-boot#41560]
Hello，Everyone.

After upgrading Spring Boot from 2. x.x to 3.2, we found that the loading order of beans had changed.

Our project utilizes Spring Security and has multiple filter chains.

Due to Spring Security 6, the Security filter chain has become a Bean object

In the previous URL matching rules, the @Order value for/aa/** was 1, the @Order value for/bb/** was 2, the @Order value for/v1/** was 3, and the @Order value for/** was 4

After the upgrade, the loading order of the URL mentioned above has been changed to 3, 1, 4, 2.

This has affected our security's URL matching rules.

Has anyone encountered this problem?

I am grateful for any suggestions.

Thanks

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
