### ISSUE TITLE
'builder(org.springframework.web.service.invoker.HttpClientAdapter)' is deprecated and marked for removal

### ISSUE THREAD

**Issue by Hagsn3** [spring-projects/spring-boot#41915]

**Comment by Hagsn3** [comment]
please help me

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Also see https://docs.spring.io/spring-framework/docs/6.1.x/javadoc-api/org/springframework/web/service/invoker/HttpClientAdapter.html

**Comment by Hagsn3** [comment]
I understand. Thank you very much
