### ISSUE TITLE
3.4.0-M3 hibernate log Database info output issue

### ISSUE THREAD

**Issue by leshalv** [spring-projects/spring-boot#42017]
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/0888150b-1194-452c-a87c-027eba48e025">

**Comment by wilkinsona** [comment]
I doubt that this is a Spring Boot problem and is more likely to have been caused by the upgrade to Hibernate 6.6. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by quaff** [comment]
It's introduced by https://github.com/hibernate/hibernate-orm/commit/55108d0740d3d46502659ed8098b02fede4abbe5

See https://hibernate.atlassian.net/browse/HHH-18224

**Comment by quaff** [comment]
FYI: I created https://github.com/hibernate/hibernate-orm/pull/8840 to improve database connection info.
