### ISSUE TITLE
Context not propagated in a reactive programming, OpenTelemetry context is not available

### ISSUE THREAD

**Issue by tadlakha9** [spring-projects/spring-boot#42031]
We are facing an issue with spring boot 3.3.1, TraceContext is not propagated while calling one microservice with another via retrofit.

```
java.lang.NullPointerException: Cannot invoke "io.micrometer.tracing.Span.context()" because the return value of "io.micrometer.tracing.Tracer.currentSpan()" is null
```

**Our Observation**

When we call an api in microservice 1, `tracer.currentSpan().context()` is available after calling another microservice via retrofit, TraceContext would not get propagated and a new context with new traceId would get started.

Sample projects
- https://github.com/tadlakha9/micro1
- https://github.com/tadlakha9/micro2

**Comment by philwebb** [comment]
Spring Boot doesn't provide any integration with Retrofit and it looks like this might be a general issue rather than a Spring Boot bug. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. 

I would suggest posting a question on [Stack Overflow](http://stackoverflow.com/) or asking in the Micrometer Slack. I'm afraid we don't really have the expertise to help you here.

Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by tadlakha9** [comment]
Its not more specific to Retrofit, actually when we call an api, we get the tracer with currentSpan later currentSpan got lost in between. We have similar issue in the past as well.

- https://github.com/spring-projects/spring-boot/issues/34622#issuecomment-1474042560
- https://github.com/spring-projects/spring-boot/issues/38615

**Comment by philwebb** [comment]
This is not a Spring Boot bug IMO. You have no micrometer integration with the OKHttp3 client being used by Retrofit. I think you need something like this in your `RetrofitConfig`:

```java
    @Bean
    public Retrofit retrofit(ObservationRegistry registry) {
        OkHttpClient client = new OkHttpClient.Builder()
        		.addInterceptor(OkHttpObservationInterceptor.builder(registry, "test").build())
                .addInterceptor(tracingInterceptor)
                .build();

       ....
```

**Comment by jonatan-ivanov** [comment]
Sorry for being a bit late but we have a working [Retrofit with OKHttp sample](https://github.com/micrometer-metrics/micrometer-samples/blob/211d05fd8d46cb7d0372168ef1dc0b7c1c06d276/micrometer-samples-boot3-retrofit/src/main/java/com/example/micrometer/RetrofitApplication.java) you might be able to use to create your own configuration.
