### ISSUE TITLE
Missing @NestedConfigurationProperty in Saml2RelyingPartyProperties

### ISSUE THREAD

**Issue by alexanderankin** [spring-projects/spring-boot#42065]
Shouldn't these have the nested annotation on them?

https://github.com/spring-projects/spring-boot/blob/fa686bb593f2a3b85497546d3995c4050501ef61/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/saml2/Saml2RelyingPartyProperties.java#L60-L74

total diff below, more than happy to submit a PR:

<details><summary>diff</summary>

```diff
--- ~/.config/JetBrains/IntelliJIdea2024.2/scratches/scratch_77.java	2024-08-30 12:11:07.746279448 -0400
+++ ~/.config/JetBrains/IntelliJIdea2024.2/scratches/scratch_78.java	2024-08-30 12:13:48.885056426 -0400
@@ -23,4 +23,5 @@
 
 import org.springframework.boot.context.properties.ConfigurationProperties;
+import org.springframework.boot.context.properties.NestedConfigurationProperty;
 import org.springframework.core.io.Resource;
 import org.springframework.security.saml2.provider.service.registration.Saml2MessageBinding;
@@ -61,10 +62,14 @@
 		 * Assertion Consumer Service.
 		 */
+		@NestedConfigurationProperty
 		private final Acs acs = new Acs();
 
+		@NestedConfigurationProperty
 		private final Signing signing = new Signing();
 
+		@NestedConfigurationProperty
 		private final Decryption decryption = new Decryption();
 
+		@NestedConfigurationProperty
 		private final Singlelogout singlelogout = new Singlelogout();
 
@@ -72,4 +77,5 @@
 		 * Remote SAML Identity Provider.
 		 */
+		@NestedConfigurationProperty
 		private final AssertingParty assertingparty = new AssertingParty();
 
@@ -258,8 +264,11 @@
 		private String metadataUri;
 
+		@NestedConfigurationProperty
 		private final Singlesignon singlesignon = new Singlesignon();
 
+		@NestedConfigurationProperty
 		private final Verification verification = new Verification();
 
+		@NestedConfigurationProperty
 		private final Singlelogout singlelogout = new Singlelogout();
```

</summary>

**Comment by wilkinsona** [comment]
From [the documentation](https://docs.spring.io/spring-boot/specification/configuration-metadata/annotation-processor.html#appendix.configuration-metadata.annotation-processor.automatic-metadata-generation.nested-properties):

> The annotation processor automatically considers inner classes as nested properties … You can use the `@NestedConfigurationProperty` annotation on a field to indicate that a regular (non-inner) class should be treated as if it were nested.

All of the fields above are of types that are inner-classes so `@NestedConfigurationProperty` isn't needed. Those properties, which are all nested beneath `Registration`, don't appear in the [documentation appendix](https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.security) (or the metadata from which the documentation is derived) due to https://github.com/spring-projects/spring-boot/issues/9945.
