### ISSUE TITLE
Actuator endpoints with jackson-dataformat-xml dependency

### ISSUE THREAD

**Issue by poznachowski** [spring-projects/spring-boot#4215]
Having simplest scenario with springboot-web and actuator [1.3.0.M5], when jackson-dataformat-xml dependency is added to the project, actuator endpoints try to serialize themselves in xml format using browser. In several cases they fail: i.e. /autoconfig endpoint:

>This page contains the following errors:
>
>error on line 1 at column 365: error parsing attribute name
>Below is a rendering of the page up to the first error.
>
>OnBeanCondition@ConditionalOnMissingBean (types: >org.springframework.boot.actuate.audit.AuditEventRepository; SearchStrategy: all) found no beans

Using curl they are returned properly in JSON format.
Can i force these endpoints to return JSON from the browser as well ?

**Comment by wilkinsona** [comment]
> Can i force these endpoints to return JSON from the browser as well ?

Not without convincing your browser to send a different accept header. The default expresses a preference for XML so that's what the actuator produces.

The actuator has been implemented with the intention of producing JSON. Where the documentation mentions the response format it specifically says it'll be JSON. I think we need to constrain the actuator's request mappings to tell Spring MVC that they produce `application/json`.

**Comment by cemo** [comment]
duplicates #2449. You can close either one @wilkinsona. I had also provided a workaround by the way.

**Comment by cemo** [comment]
I also agree with you to consider these issues as a bug.

**Comment by wilkinsona** [comment]
@cemo Thanks. I'll dup this one against your issue
