### ISSUE TITLE
Report produced by ConditionReportApplicationContextFailureProcessor is always empty in a failed test

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#42185]
There are no outcomes because the report on the context that failed was [already discarded by Spring](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L640) since it was a singleton bean instance. To reproduce just look at any failed `@SpringBootTest` where the context refresh fails and look for the empty condition evaluation report on stderr:

```
============================
CONDITIONS EVALUATION REPORT
============================

Positive matches:
-----------------

    None

Negative matches:
-----------------

    None

Exclusions:
-----------

    None

Unconditional classes:
----------------------

    None
```

**Comment by wilkinsona** [comment]
I don't think this feature has ever worked.

We had a problem in 2.x where `SpringBootDependencyInjectionTestExecutionListener` would catch the failure and then call `org.springframework.test.context.TestContext.getApplicationContext()` so that it could get and output the report for the context. Because the context had failed to refresh, all this did was to trigger another attempt at creating the context which would also fail. This double refresh was fixed in https://github.com/spring-projects/spring-boot/issues/24888 with the hope that the new `ApplicationContextFailureProcessor` would allow us to implement a proper fix such that the condition report would be output upon test failure.

https://github.com/spring-projects/spring-boot/issues/31793 started using the new API. Unfortunately, as Dave's noted above, it doesn't work. By the time `ConditionReportApplicationContextFailureProcessor` is called, the context's singletons have been destroyed so `ConditionEvaluationReport.get(configurableContext.getBeanFactory())` ends up creating a new empty report. Failure processors either need to called earlier (before singleton destruction) or we need to somehow implement some additional callback so that we can get the report earlier and hold it till we need it.

**Comment by wilkinsona** [comment]
> Failure processors either need to called earlier (before singleton destruction) or we need to somehow implement some additional callback so that we can get the report earlier and hold it till we need it.

It's Framework that creates and calls the processor instances so I think both of these are out of our control. We can't make Framework call them any earlier and implementing an additional callback won't help as Framework won't call it.

@sbrannen I'm not sure how we missed this originally, but it appears that the `ApplicationContextFailureProcessor` SPI doesn't meet Boot's needs, unfortunately. It's called too late (after singleton destruction) for us to be able to retrieve the `ConditionEvaluationReport` from the context so we end up creating a new one that's empty. I think we could avoid the problem by moving away from the `ApplicationContextFailureProcessor` SPI and using our own callback mechanism instead but I think that may leave the SPI without its primary user which seems a shame. Do you think there's anything that could be done on the Framework side to make the processor SPI more useful?

**Comment by dsyer** [comment]
Maybe `ApplicationContextFailureProcessor` could have another callback (with no-op default implementation) so it has access to the `ApplicationContext` before it is refreshed (then it can stash the report earlier)?

**Comment by sbrannen** [comment]
> I'm not sure how we missed this originally, but it appears that the `ApplicationContextFailureProcessor` SPI doesn't meet Boot's needs, unfortunately.

Oh. That is indeed very unfortunate.

> It's called too late (after singleton destruction) for us to be able to retrieve the `ConditionEvaluationReport` from the context so we end up creating a new one that's empty. I think we could avoid the problem by moving away from the `ApplicationContextFailureProcessor` SPI and using our own callback mechanism instead but I think that may leave the SPI without its primary user which seems a shame. Do you think there's anything that could be done on the Framework side to make the processor SPI more useful?

When/where exactly do you need such a hook/callback to capture the required state -- something _before_ or _within_ `ConfigurableApplicationContext#refresh()`?

**Comment by wilkinsona** [comment]
It would have to be within `refresh` as we need to be able to work with the bean factory and the context won't allow us to access the bean factory until refresh has begun. Unfortunately, I don't think this is straightforward due to how the context is created and refreshed. `SpringBootContextLoader` does so either through a call to `SpringApplication.run` or by calling the application's own main method. In either case, this means that there's little opportunity for the test framework to get involved as far as I can tell.

**Comment by sbrannen** [comment]
> It would have to be within `refresh`

That's what I feared.

> Unfortunately, I don't think this is straightforward due to how the context is created and refreshed. `SpringBootContextLoader` does so either through a call to `SpringApplication.run` or by calling the application's own main method. In either case, this means that there's little opportunity for the test framework to get involved as far as I can tell.

Yep, that's my gut feeling as well.

The `SmartContextLoader` API doesn't provide any way for the TestContext framework (`DefaultCacheAwareContextLoaderDelegate` specifically) to register any additional callback that could be invoked _during_ `refresh()`.

So, it sounds like changes to `ApplicationContextFailureProcessor` won't help.

Though, perhaps @jhoeller has some ideas?

**Comment by wilkinsona** [comment]
We're happy enough with 1 as we think the verbose output is better than no output, and definitely better than the current output that's incorrect. 2 is a minor detail and we don't feel that it has to be resolved for this to be worth fixing.
