### ISSUE TITLE
I am getting this issue when trying to run my springBoot service

### ISSUE THREAD

**Issue by Sumitbashetwar** [spring-projects/spring-boot#42290]
SpringBoot version 2.7.18 and gradle version 7.6.3 

java.lang.NoSuchMethodError: org.springframework.boot.configurableBootstrapContext org.springframework.boot.context.event.ApplicationEnvironment PreparedEvent.getBootstrapContext() at org.springframework.boot.env. EnvironmentPostProcessorApplicationListener.onApplicationEnvironment PreparedEvent (environmentpostprocessorapplicationlistener.java:101) at org.springframework.boot.env. EnvironmentPostProcessorApplicationListener.onApplicationEvent (environmentpostprocessorapplicationtistener.java:87) at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokelistener(simpleapplicationeventmulticaster.java:176) at org.springframework.context.event.SimpleApplicationEventMulticaster.invokelistener(simpleapplicationeventmulticaster.java:169) at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(simpleapplicationeventmulticaster.java:143) at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent (simpleapplicationeventmulticaster.java:131)

at org.springframework.boot.context.event.Event PublishingRunListener.environment Prepared(eventpublishingruntistener.java:74) at org.springframework.boot.SpringApplicationRunListeners.environment Prepared(springapplicationrunlisteners.java:54)

at org.springframework.boot SpringApplication.prepareEnvironment (springapplication.java:325) at [org.springframework.boot.SpringApplication.run](https://org.springframework.boot.springapplication.run/)(springapplication.java:296)

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Sumitbashetwar** [comment]
Thanks for the reply 
But have you faced any issue like this 
Thanks
