### ISSUE TITLE
Credential about mongodb3.x

### ISSUE THREAD

**Issue by pkaq** [spring-projects/spring-boot#4274]
MongoDB’s default authentication method is a challenge and response mechanism (SCRAM-SHA-1). Previously, MongoDB used MongoDB Challenge and Response (MONGODB-CR) as the default.

but in line 176 of "MongoProperties.java" still use MongoCredential.createMongoCRCredential and I can't change it expect I override it and change this function.

**Comment by wilkinsona** [comment]
This change is already being discussed in #4237. Note that Spring Data MongoDB's default supported version of Mongo is 2.x so that's what Boot aims at by default too. We'd welcome some feedback on #4237 as the Boot team lack's the Mongo expertise to know if it's definitely the right change to make given that we need it to work with 2.x as well.

**Comment by pkaq** [comment]
wll it provide a way to config authentication method；such as some property

**Comment by wilkinsona** [comment]
You can see the change in the PR that I linked to (#4237). It is proposing to replace `MongoCredential.createMongoCRCredential` with `MongoCredential.createCredential`, irrespective of the version of Mongo that's being used.

**Comment by dsyer** [comment]
I think you can always use a URI (containing credentials) with both versions of Mongo even without any changes to Spring Boot.

**Comment by snicoll** [comment]
Indeed.
