### ISSUE TITLE
Add property to opt out of Liquibase analytics feature

### ISSUE THREAD

**Issue by freddiN** [spring-projects/spring-boot#43067]
The latest liquibase version offers a new configuration option to switch off the newly added analytics feature.
There is currently no way to set this within Spring Boot besides from having a global environment variable "LIQUIBASE_ANALYTICS_ENABLED" set to false.
My suggestion for would be to make this configuration option accessable similar to the other liquibase settings via the spring.liquibase.XYZ prefix, e.g. spring.liquibase.analytics=true/false

Details on the matter from liquibase:
https://docs.liquibase.com/analytics/home.html

**Comment by mhalbritter** [comment]
Hello!

I don't see a setter method on `SpringLiquibase` or `Liquibase` which we could use to disable analytics.

What should Spring Boot do in case you set `spring.liquibase.analytics=false`?

**Comment by wilkinsona** [comment]
Analytics are [new](https://github.com/liquibase/liquibase/commit/2c2170ec0be7c47f0684037d27a6488eb5f4d3f1) in Liquibase 4.30 and 3.4.0 will ship with 4.29.2 so there's nothing we can do here at the moment. The Liquibase Maven Plugin [offers a property](https://github.com/liquibase/liquibase/blob/eda7f7d96fc3e3ead0d1424d86118a2c18fffac6/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java#L724) but the [Gradle Plugin](https://github.com/liquibase/liquibase-gradle-plugin) doesn't appear to have an equivalent option. As @mhalbritter points out, there also doesn't appear to be a configuration option to disable analytics when using Liquibase programatically either.

@freddiN please open a Liquibase issue asking for a setting that's similar to the Maven plugin's `liquibase.analytics.enabled` to be added to `SpringLiquibase` and comment here with a link to it so that we can subscribe. As and when that feature lands in Liquibase and we have upgraded to it, we can consider providing a property for it or you could set it programmatically using a `SpringLiquibaseCustomizer` bean.

I'm going to close this one for now as it isn't actionable until a change has been made in Liquibase and we don't know if that will happen.

**Comment by Marax** [comment]
@wilkinsona when spring boot updates to liquibase 4.30 will this spy feature be disabled by default? Asking if I should keep in mind to check back on this when I'll be updating spring.

**Comment by wilkinsona** [comment]
Even assuming that it becomes configurable, I expect that we'll align our default with Liquibase's default. Assuming that Liquibase's default doesn't change, that would mean that analytics will be enabled by default.

**Comment by freddiN** [comment]
Issue created at liquibase: https://github.com/liquibase/liquibase/issues/6501

**Comment by lalo-mx** [comment]
Workaround:

`System.setProperty("liquibase.analytics.enabled", "false");`

**Comment by virtual-machinist** [comment]
Since version 4.31.0 there exists a property `liquibase.integration.spring.SpringLiquibase#analyticsEnabled`, but there's no easy way to set it ATM.

I imagine there may be more such features coming in the future that will not be immediately supported in Spring Boot, so I propose at least making the `org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration.SpringLiquibaseCustomizer` inner class public, so that we may have better workarounds than setting system properties.
