### ISSUE TITLE
DynamicPropertyRegistry in testcontainers still working in 3.4 version

### ISSUE THREAD

**Issue by francisco-bru** [spring-projects/spring-boot#43268]
In [this](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#dynamic-properties-with-testcontainers) point of 3.4 Release notes mention that:

> Support for defining dynamic properties by injecting a DynamicPropertyRegistry has been deprecated and attempting to do so will now fail by default.

But it still seems to work and the release [documentation](https://docs.spring.io/spring-boot/reference/testing/testcontainers.html#testing.testcontainers.dynamic-properties) still mentions DynamicPropertyRegistry as a mechanism for dynamic properties with test containers.

**Comment by wilkinsona** [comment]
It's support for injection into a `@Bean` method that has been deprecated. In other words, instead of the approach described in https://docs.spring.io/spring-boot/3.3/reference/features/dev-services.html#features.dev-services.testcontainers.at-development-time.dynamic-properties, you should now use the approach described in https://docs.spring.io/spring-boot/reference/features/dev-services.html#features.dev-services.testcontainers.at-development-time.dynamic-properties.

`@DynamicPropertySource` methods, a Spring Framework feature, are unaffected. I've updated the release notes to hopefully make it clear that it's injection into `@Bean` methods that's affected by the deprecation.
