### ISSUE TITLE
Recieving error " Error: Unknown argument(s):  gov.faa.ime.helloworld.HelloWorld" 

### ISSUE THREAD

**Issue by TasMot** [spring-projects/spring-boot#43621]
In order to avoid making all developers on the team install and configure "c" build tools, I am trying to utilize the ability to do the build inside of a "build" container. 
If I set this parameter "<BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>" to false, it does pass and builds a container, but without native mode. 
Running on Windows 11 Pro
Build 22621.ni_release.220506-1250

I execute the build in Intellij Ultimate:
IntelliJ IDEA 2024.3.1.1 (Ultimate Edition)
Build #IU-243.22562.218, built on December 18, 2024

Runtime version: 21.0.5+8-b631.28 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 32

Also try the build in ConEmu  230724 [64bit]

$ mvn --version
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\Program Files\Maven
Java version: 21.0.5, vendor: Oracle Corporation, runtime: C:\Program Files\GraalVM
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

This is a Hello World, so just trying to get it working. The one complication is that I like Logback, so it involves some reflection, but I think I have that resolved (even though it is not pretty).

The build-image-no-fork step fails with status code 51.

The entire project is attached (twice because I wasn't sure it uploaded the first time). Any help getting it to build would be appreciated.

Thanks! 

[HelloWorld.zip](https://github.com/user-attachments/files/18261915/HelloWorld.zip)
[HelloWorld.zip](https://github.com/user-attachments/files/18261930/HelloWorld.zip)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
