### ISSUE TITLE
1.3.0.RC1 breaks property filtering in resources

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#4380]
I'm using Maven Properties inside application and other properties, for example my build properties look like this

```
info.build.artifact = ${project.artifactId}
info.build.name = ${project.name}
info.build.version = ${pom.version}
info.build.date = ${build-date}
```

Until Spring Boot using maven resource filtering i end up with with the correct info:

```
info.build.version = 0.0.1-SNAPSHOT
info.build.date = 2015-11-03 17:18
```

With RC1, nothing gets resolved, result looks exactly the same.

I have setup a demo, look at https://github.com/michael-simons/resourcesError

To reproduce the error, change version to RC1.

**Comment by snicoll** [comment]
Duplicates #3092

**Comment by michael-simons** [comment]
Sorry, didn't see that. Thanks a lot.

So it's either   

```
<useDefaultDelimiters>true</useDefaultDelimiters> 
```

or updating all properties to use @?

**Comment by snicoll** [comment]
to be clear `@` is documented as the only filtering token since 1.2.0 (which is a while back) but we made the mistake of not adding that `useDefaultDelimiters`. 

What I am trying to say is that we fixed that in RC1 but the documented feature since 1.2.0 is that `@` should be used (or a custom configuration).

That being said, you are right. This is the default config coming from the parent after all, feel free to update to whatever setup works for you.

**Comment by michael-simons** [comment]
Thanks, Stéphane. I didn't notice that while updating to 1.2, my mistake.

To be honest, i had the problem in the related issue, therefor i was using that configuration https://github.com/michael-simons/resourcesError/commit/ce0d87e032f4c9ecfa42a002ef77ba66fcdd83f9, so i like the change!!

I guess i'll use the "right" way, that is not messing with the default delimiters. Works for me now.

**Comment by snicoll** [comment]
That's what we would recommend yes. Thanks for the feedback!
