### ISSUE TITLE
Add how-to log to file but not console

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4388]
Document various logging things including how to get file without console.

**Comment by pmvilaca** [comment]
Another useful thing would be a guide how to configure a new append and at the same time log to console appender that is configured by spring-boot (without need to reconfigure it). Assuming that there is a better way to do this with logback-spring.xml instead of creating a logback.xml and import the base.xml file.

**Comment by philwebb** [comment]
@pmvilaca There's not really a better way than defining your own `logback.xml` or `logback-spring.xml`. Feel free to open another issue if you think there's a further clarification that we should add to the docs.

**Comment by pmvilaca** [comment]
sure @philwebb 

I'll be working on that soon, so if I found some problem or something that would be good to be documented, I'll open a new issue.
