### ISSUE TITLE
Resource bundle not found from MessageSourceAutoConfiguration in integration test

### ISSUE THREAD

**Issue by MichaelF25** [spring-projects/spring-boot#4438]
I am just refactoring a spring boot application (using 1.2.7.RELEASE) in order to break it up into two applications. So my updated project structure looks like this:

* common (shared stuff, including a resource bundle for I18N)
* app1
* app2

With this changed structure the resource bundle is not found by spring boot's `MessageSourceAutoConfiguration` class within my `WebIntegrationTest`.
However if I try to debug this behaviour inside my IntelliJ IDE, everything works fine - same situation if the tests are ignored during the build and the application is started.

I've provided a sample reduced to the absolute minimum demonstrating this issue. `mvn verify` fails, but it works with debugger and executed as standalone jar. Seems like some class loading issue.

Sample project: https://github.com/MichaelF25/spring-boot-messagesource-bug

**Comment by MichaelF25** [comment]
Updated the sample and remove the dependency to REST assured. Now it's a pure spring boot based project demonstrating this issue.

**Comment by snicoll** [comment]
Yep, I had a look to it yesterday already and I am quite confused. No idea where that is coming from for now.

**Comment by philwebb** [comment]
Pretty interesting issue this one. It turns out that Maven uses `MANIFEST.MF` file to define the test classpath. You can read about why [here](http://maven.apache.org/surefire/maven-surefire-plugin/examples/class-loading.html). It seems that such entries aren't exposed via `URLClassLoader.getURLs()` so Spring's `PathMatchingResourcePatternResolver` can't find them.

I've raise [SPR-13685](https://jira.spring.io/browse/SPR-13685) and I have a fix but it's doubtful that it will make it into Spring 4.2.x as it's quite a risky change.

In your case can you try adding `useManifestOnlyJar=false` and `useSystemClassLoader=true` to your Maven build to see it that solves things?

**Comment by philwebb** [comment]
I'll close this one here since it's really a Spring Framework issue. Please track SPR-13685.
