### ISSUE TITLE
Improve SessionAutoConfiguration to support other SessionRepository implementations 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#4508]
@rwinch Current implementation of `SessionAutoConfiguration` is tightly coupled with Redis. Please provide some abstraction to provide other implementations such as `MapRepository` or a custom implementation.

**Comment by rwinch** [comment]
@cemo Thanks for the report.

I think this is somewhat blocked by the release of Spring Session 1.1 since this is the release we added [@EnableSpringHttpSession](http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/#api-enablespringhttpsession) support.

Can you outline a little more concretely how you would expect this to behave? This will help to ensure we are on the same page.

**Comment by shakuzen** [comment]
Related to #3811. I think the idea would be to implement something similar to the current caching auto-configuration, as @snicoll suggested. Perhaps the backing repository could be directly chosen with a property like `spring.session.repository.type` that uses an enum. Of course the desired backing store could be auto-detected based on the environment in the absence of this property.

**Comment by snicoll** [comment]
Duplicates #5158
