### ISSUE TITLE
Adding @EnableHypermediaSupport prevents spring.jackson.* properties from working on _halObjectMapper

### ISSUE THREAD

**Issue by KamikaZeeFu** [spring-projects/spring-boot#4556]
Configuration via spring.jackson.* properties will not be applied to the ObjectMapper used by Hateoas if  I add @EnableHypermediaSupport with type HAL to the application's main class .
Removing the annotation will configure the ObjectMapper as expected.

The specific error was serializing JodaTime's DateTime with `spring.jackson.serialization.write_dates_as_timestamps=false`.

If required, I can cook up a sample repo to illustrate this issue.
This is oviously not a major issue, as adding the annotation is not necessary when using spring boot, but it is still an irritating issue.

**Comment by wilkinsona** [comment]
As [described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-hateoas), this is by design:

> You can take control of Spring HATEOAS’s configuration by using @EnableHypermediaSupport. Note that this will disable the ObjectMapper customization described above.

By using `@EnableHypermediaSupport` you're telling Spring Boot to back off and that you will configure Spring HATEOAS yourself. That includes configuring its `ObjectMapper`.
