### ISSUE TITLE
The environment post processor that handles application.properties is always added to the end of the list

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-boot#4595]
I've written a custom `EnvironmentPostProcessor` to use company wide default in various apps.
The code looks like:

```java
@Order(Ordered.LOWEST_PRECEDENCE)
public class MyFrameworkPropertyDefaultsPostProcessor implements EnvironmentPostProcessor {

    private static final String DEFAULT_MY_FRAMEWORK_PROPERTIES = "defaultMyFrameworkProperties";
    private static final String DEFAULT_MY_FRAMEWORK_PROPERTIES_LOCATION = "/config/myFramework-application.yml";

    private YamlPropertySourceLoader propertySourceLoader = new YamlPropertySourceLoader();

    @Override
    public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {
        Resource myFrameworkDefaults = new ClassPathResource(DEFAULT_MY_FRAMEWORK_PROPERTIES_LOCATION);
        String[] profiles = environment.getActiveProfiles();
        load(environment, myFrameworkDefaults, null);
        if (profiles.length > 0) {
            for (String profile : profiles) {
                load(environment, myFrameworkDefaults, profile);
            }
        }
    }

    private void load(ConfigurableEnvironment environment, Resource resource, String profile) {
        try {
            PropertySource<?> propertySource = propertySourceLoader.load(DEFAULT_MY_FRAMEWORK_PROPERTIES, resource, profile);
            if (propertySource != null) {
                environment.getPropertySources().addLast(propertySource);
            }
        } catch (IOException e) {
            // ignore
        }
    }
}
```

This `MyFrameworkPropertyDefaultsPostProcessor` kicks in nicely but the application defined properties (`application.properties`) are added after the defaultMyFrameworkProperties resulting that I cannot override the company wide defaults if needed.
Note: I've added `@Order(Ordered.LOWEST_PRECEDENCE)` to my `EnvironmentPostProcessor` but this does not seem to have affect to get it added as last.

As @wilkinsona mentioned on gitter this looks like a bug. The environment post processor that handles application.properties is always added to the end of the list.

**Comment by snicoll** [comment]
As far as I can see `PropertySourceOrderingPostProcessor` runs with highest precedence and add indeed the default properties last. Changing the order isn't probably a good option as we rely that this is done as early as possible. 

Maybe we should find a way to flag a `PropertySource` in a special way so that we add the default right before or something. WDTY @wilkinsona ?

**Comment by wilkinsona** [comment]
The bug that I want to fix here isn't in `PropertySourceOrderingPostProcessor`, it's in `ConfigFileApplicationListener`. It loads `EnvironmentPostProcessors` using `SpringFactoriesLoader` and then adds itself to the end of the returned list. That's wrong. It needs to add itself to the list and then sort it so that any ordering of the post processors is honoured.

**Comment by marceloverdijk** [comment]
Thanks @wilkinsona I can confirm this works using 1.3.1 build snapshot!
