### ISSUE TITLE
Could not disable actuator endpoints security when running on a different port

### ISSUE THREAD

**Issue by sawano** [spring-projects/spring-boot#4624]
Given a secure web application with non-secure management endpoints running on a different port I am no longer able to access the endpoints after upgrading to Spring Boot 1.3.0.

I.e. an application.yml as:
```json
server:
  port: 8080

management:
  port: 8081
  context-path: /manage
  security:
    enabled: false

security:
  user:
    password: my-password
```

would expose endpoints at localhost:8081/manage and it works in 1.2.7. After changing Boot version to 1.3.0 then the endpoints are no longer available.

I added some example code that illustrates the problem: https://github.com/sawano/spring-boot-actuator-management-issue. If the Boot version is changed to 1.2.7 then all tests passes.

One thing I did notice is that an ```EndpointHandlerMapping``` is never injected into ```ManagementWebSecurityAutoConfiguration``` but I am not sure if it is part of the issue.

**Comment by snicoll** [comment]
Thanks for the sample!

**Comment by snicoll** [comment]
So it looks like things go south as soon as we add `management.port`. The underlying issue is that security is not disabled properly anymore and any attempt to access an endpoint redirects to the error page for some reason and that one is not found

```
➜  http http://localhost:8081/manage/env
HTTP/1.1 404 Not Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Length: 0
Date: Fri, 27 Nov 2015 10:01:03 GMT
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
WWW-Authenticate: Basic realm="Spring"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

If I remove the `context-path` (and only that), then the error page is found now and we get this

```
➜  http http://localhost:8081/env
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Fri, 27 Nov 2015 10:07:56 GMT
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Transfer-Encoding: chunked
WWW-Authenticate: Basic realm="Spring"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

{
    "error": "Unauthorized",
    "message": "Full authentication is required to access this resource",
    "path": "/env",
    "status": 401,
    "timestamp": 1448618876103
}
```

**Comment by sawano** [comment]
Thank you guys for the quick response to this. Really appreciate it!

**Comment by snicoll** [comment]
There's a [typo in the error controller](https://github.com/spring-projects/spring-boot/commit/2de48a35ab56022aa29b042fd5baea207a9580b3#diff-f5ba9b23eec76c87f1730448ba3e443bR46). Check `BasicErrorController` for the `@RequestMapping` value to use

**Comment by dsyer** [comment]
Fixed in 6ec7674

**Comment by idanh** [comment]
@dsyer, We're experiencing the exact same issue with Spring Boot 1.3.1, Jetty 9. 
When running embedded jetty, everything works as expected.

When running in a jetty container, the exact issue occurs.
When removing the ```management.port```, the endpoints register successfully.

We are not using spring-security nor our application is secure at the spring level.
The issue happened after upgrading to 1.3.1 from 1.2.x

Could you please help us solve this? this has now became a major issue for us.
Thanks!

**Comment by dsyer** [comment]
Since this issue is marked as closed I suspect you are experiencing some other kind of problem. Note that if you run in an external container there is no support for a separate `management.port` (it makes no sense to start an embedded server from within a container app).

**Comment by idanh** [comment]
@dsyer Firstly, Thank you very much for the fast response and as we are dealing with a production issue.

I agree that it makes no sense to start an embedded server from within the container, yet before the upgrade we did have a separate management port different from our application port. 
For us, it help us separate our concerns and configure our firewall correctly.
Nothing changed on our side of the configuration except from upgrading spring version to 1.3.1.

For the problem itself, when removing the management port and letting it work on the application port, everything works as expected. We already tried to add a Jetty connector for our management port without success. 

It seems possible that this bug is related as I can replicate the same problem on our side.
Could you please guide us on how to solve this (either if it's related or not)? Or is it now impossible to have separate management port when Jetty is not embedded?

Thanks again,

**Comment by dsyer** [comment]
I'm surprised it was ever possible to have a separate management port in a non-embedded server. If you want to discuss that feature please start a new issue (this one is not really relevant).
