### ISSUE TITLE
Embedded/NonEmbedded DataSourceAutoConfiguration is confusing

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#4634]
In `DataSourceAutoConfiguration` we have two mutually exclusive conditions that check the presence of a connection pool. If a connection pool is found, we run in the "non embedded" scenario. But the tomcat connection pool can provide a connection to H2 (which is embedded).

In the end the auto-configuration report shows that we run in non embedded mode (while the underlying data source is embedded). We should probably rename these conditions.

**Comment by kbastani** [comment]
Some feedback:

I've run into complications with this in the past while deploying a Spring Boot application to CF with an H2 driver for tests and a MySQL driver for cloud profile on the class path. Even with specifying a valid JDBC connection using CF environment variables, with details to connect to a user provided service's MySQL binding, H2 was auto-configured and connection details to MySQL ignored. The problem with this is that everything looks normal and the application starts up fine, seemingly connected to the attached MySQL user provided service.

This only happens with user provided database services on CF. If a service binding is a registered service broker in Cloud Foundry, then a registered service instance will contain a `MySQL` tag and CF cloud connector auto-reconfiguration will correctly connect to MySQL instead of H2.

Developers will experience this if following this guide and using H2 for testing in a similar scenario: https://spring.io/blog/2011/11/04/using-cloud-foundry-services-with-spring-part-2-auto-reconfiguration/

The workaround is simple enough, define your own data source bean for the cloud profile.

**Comment by snicoll** [comment]
Kenny, I am not sure I understand how it's related to this particular issue. Can you please clarify?

**Comment by kbastani** [comment]
Ah thanks @snicoll. I misunderstood the problem statement. I'll follow up with you on other channels on the issue I encountered.

**Comment by philwebb** [comment]
Outcome: Rename `NonEmbeddedDataSourceCondition`.

**Comment by snicoll** [comment]
Actually, looking at the documentation I think I start to understand when those weird names came from. It seems that the code used to completely separate embedded support from "production" support (there are [two separate sections](http://docs.spring.io/spring-boot/docs/1.3.0.RELEASE/reference/htmlsingle/#boot-features-configure-datasource)). Maybe we added connection pooling in a consistent manner _after_. Anyway, just a reminder that we should rework the documentation as well.

**Comment by snicoll** [comment]
`NonEmbeddedDataSourceCondition` -> is a connection pool available?
`EmbeddedDataSourceCondition` -> is an EmbeddedDatabase available?

Here are the cases:

* A connection pool is available with no embedded database: `NonEmbeddedConfiguration` is applied
* A connection pool is availble with an embedded database: `NonEmbeddedConfiguration` is applied and the `EmbeddedConfiguration` isn't applied with the following reason: _existing non-embedded database detected_
* A connection pool is not available with no embedded database: no data source is created
* A connection pool is not available with an embedded database: `EmbeddedConfiguration` is applied (`NonEmbeddedConfiguration` is not applied because no data source available)
