### ISSUE TITLE
Load application properties in ../conf/

### ISSUE THREAD

**Issue by michaeltecourt** [spring-projects/spring-boot#4642]
In order to ship Spring Boot apps as classic "posix" tar.gz archives, it would be cool if  Spring Boot picked-up application properties files in `../conf/`.

    .
    ├── bin -> application.jar 
    └── conf -> application.properties, logback-spring.xml...

PR #4641

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Unfortunately, I'm not keen on changing the default. I think adding another location will be confusing, particularly given that we'd then support both `config/` and `/conf/`. If you're building a posix tar.gz archive, I'd recommend configuring your application with a custom `spring.config.location` so that it'll look in the `conf` directory.

**Comment by michaeltecourt** [comment]
No problem thank you for your time !
