### ISSUE TITLE
Issue with reloading static resources in spring-boot 1.3.0

### ISSUE THREAD

**Issue by koziolk** [spring-projects/spring-boot#4692]
It seems like static resources located under "resources/static" folder are not reloaded automatically in spring-boot 1.3.0 and they was in 1.2.7.

To reporoduce this issue please take a look at sample project: https://github.com/koziolk/spring-boot-reload

**Comment by wilkinsona** [comment]
@koziolk The default has changed in 1.3.0. This [entry is the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#spring-bootrun-resources) describes how to re-enable 1.2's behaviour. There's also some background information in [this issue](https://github.com/spring-projects/spring-boot/issues/4227) have some more information.

I'll close this issue now in the hope that the above resolves your issue. If it doesn't, please let me know and I'll re-open it so that we can investigate.

**Comment by koziolk** [comment]
@wilkinsona  Thanks, I somehow missed this part of documentation. We can close this issue.
