### ISSUE TITLE
pre-init problems?

### ISSUE THREAD

**Issue by vongosling** [spring-projects/spring-boot#4771]
My `DataSource` auto-config class can not be autowired, such as following:

```java
@Configuration
@ConditionalOnClass(DGroupDataSource.class)
@EnableConfigurationProperties(DProperties.class)
public class DAutoConfiguration{

    @Autowired
    private DProperties properties;

    @Bean(initMethod = "init")
    @ConditionalOnMissingBean
    public DDataSource dDataSource() throws Exception {
        DDataSource dDataSource = new DDataSource();
        dDataSource.setDbGroupKey(properties.getGroup());
        dDataSource.setAppName(properties.getApp());
        return dDataSource;
    }
```

I debug from `AbstractApplicationContext`, found my BFPP using `beanFactory.getBeanNamesForAnnotation(EnableHsfProvider.class);` 
this method will scan my mybatis interface(I using mybatis `MapperFactoryBean`) and init mybatisSessionFactory.this result in the `DDataSource init`, but at this moment,properties have not be autowired.how can i fix this problems?

I have post another issue in this,https://github.com/spring-projects/spring-boot/issues/4711.I supposed at first my BFPP problem,but later,when i get deeper into spring inner class debugging,i found this problem.

**Comment by snicoll** [comment]
I think #4711 sum it up already. 

> All of that said, you're still calling getBean during BeanFactoryPostProcessor creation. Generally speaking, that's not a good idea as it'll cause that bean and all of its dependencies to be created very early in the lifecycle of the application context. I

That `getBeanNamesForAnnotation(EnableHsfProvider.class);` in a BFPP is still a problem as you found out yourself. Because of this very early initialization, things have not been fully post-processed yet.  There is also a Mybatis auto-configuration available so you might just as well use that.

If you get stuck, please ask on Stack Overflow. It's a better place for Q&A and we prefer to use GitHub issues purely for tracking bugs and enhancements.

**Comment by vongosling** [comment]
thank you very much.I fixed this problem by implementing ApplicationContextInitializer add manually registering my BFPP finally.hope to help someone who happen with some problems as me~
