### ISSUE TITLE
<testResources> ignored on junits?

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#4774]
I must be going wrong somewhere - but when i add snippet below and run a junit, i am not seeing the classpath getting updated to include the directory. Eg. I am doing a `getClass().getResource("..")` and getting a NPE. I was doing the same flow in standard spring apps with no issues, and only noticed after migrating to boot.

Is test resource supported when running `mvn surefire:test`  ?  Eg. I have some stub results that I used only in junits, and prefer to package next to the code that is leveraging rather then another folder.

```
<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration> </configuration>
            </plugin>
      
        </plugins>
                
        <!-- support for eclipse and maven junit -->
        <testResources>
            <testResource>
                <directory>${project.basedir}/src/test/java</directory>
                <excludes>
                    <exclude>**/*.java</exclude>
                </excludes>
            </testResource>
				
        </testResources>
                  
    </build>

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by snicoll** [comment]
Here [is the link to the SO issue](http://stackoverflow.com/questions/34274595/testresources-ignored-on-junits).
