### ISSUE TITLE
Servlet input stream gets consumed if Content-Type is application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by DavidBiesack** [spring-projects/spring-boot#4782]
My Spring Boot 1.3.0-RELEASE web app is a simple Dispatcher servlet that reads the request body and processes it. See attached [MyServletApplication.java](https://github.com/spring-projects/spring-boot/files/63440/MyServletApplication.java.txt)

When called via a `POST`, if no `Content-Type` is passed, something (Spring?) sets the `Content-Type`
to `application/x-www-form-urlencoded`. (I know that [`curl(1)`](http://linux.die.net/man/1/curl) will set the `Content-Type` to `application/x-www-form-urlencoded` if it is not set with `-HContent-Type=` and the command line uses `-d` to supply a request body. But when called directly via RestTemplate or non-curl cases that do not set a `Content-Type`, it still gets set somewhere in the call chain to  `application/x-www-form-urlencoded`.)

Inside the Apache Catalina servlet engine that Spring Boot runs, the `Request` class makes the following test in `parseParameters()`
```Java
        if (!("application/x-www-form-urlencoded".equals(contentType))) {
            success = true;
            return;
        }
```
For other `Content-Type` values, `Request` returns here and there is no problem

However, if the `Content-Type` matches `application/x-www-form-urlencoded`, `Request` continues:
```Java
    try {
       if (readPostBody(formData, len) != len) {           
            parameters.setParseFailedReason(FailReason.REQUEST_BODY_INCOMPLETE);
            return;
        }
    } catch (....)
```
which will consume the body by calling `readPostBody`. So in my case, even though my servlet does *nothing* other than call `request.getInputStream()` and try to `read()` from it, it is already too late - the runtime `Request` had already read the input and does not buffer or unread it.

The culprit in this case is `OrderedHiddenHttpMethodFilter(HiddenHttpMethodFilter).doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain)` line 70 which is looking for the `"_method" `query parameter.

I was able to disable the filter by adding
```Java
@Bean
public FilterRegistrationBean registration(HiddenHttpMethodFilter filter) {
    FilterRegistrationBean registration = new FilterRegistrationBean(filter);
    registration.setEnabled(false);
    return registration;
}
```
This works in this case, but also means this Boot web app (or others like it) can't use `HiddenHttpMethodFilter`.

**Comment by wilkinsona** [comment]
> RestTemplate or non-curl cases that do not set a Content-Type

RestTemplate will set the content type to `application/x-www-form-urlencoded` if you `POST` a `MultiValueMap` and have it configured with a `FormHttpMessageConverter` (which it has by default).

> I was able to disable the filter

This is a reasonable approach to take. Boot deliberately allows you to tell it to get out of the way when its defaults don't suit your needs. You may also want to consider changing the filter's mappings so that it isn't applied to your custom servlet but is still used with Boot's dispatcher servlet.

> This works in this case, but also means this Boot web app (or others like it) can't use HiddenHttpMethodFilter.

Correct. If you want to be able to read the body of a request that contains request parameters yourself then you can't use `HiddenHttpMethodFilter` in front of your servlet. As described above, you may want to configure the filter differently so that it runs in front of Boot's dispatcher servlet but not in front of your custom servlet. Also, it's worth noting that when the content type is `application/x-www-form-urlencoded`, there's no need to read and parse the body yourself. All of the parameters will be available via the request's `getParameterMap()` method.

**Comment by DavidBiesack** [comment]
I'm using `RestTemplate` to `POST` but I'm not using a `MultiValueMap`. I'm calling
```Java
public <T> T execute(String url, HttpMethod method, RequestCallback requestCallback,
			ResponseExtractor<T> responseExtractor, Object... urlVariables) 
```
My `RequestCallback` does the following:
```Java
            @Override
            public void doWithRequest(final ClientHttpRequest request)
                    throws IOException {
                final HttpHeaders headers = mapHeaders(script.getRequestHeaders());
                request.getHeaders().putAll(headers);
                if (requestStream != null)
                    Binary.copy(requestStream, request.getBody());
                ;
            }
```

This is a generic library I'm writing. I do allow passing headers but in this specific case, I'm not passing any headers, and the request body is binary or text, not a `MultiValueMap`. Not sure where `application/x-www-form-urlencoded` gets set. I see a `FormHttpMessageConverter` get instantiated but don't see any of its methods executed (in either the client calling the endpoint, or in the servlet).

**Comment by wilkinsona** [comment]
@DavidBiesack Sorry, but it's difficult to offer any more guidance without seeing some more of the code. This issue tracker's also not really the best place to continue this discussion. If you'd like some more help please post a question of Stack Overflow or join us on [Gitter](http://gitter.im/spring-projects/spring-boot). In either case, sharing a [minimal example](http://stackoverflow.com/help/mcve) will make it much more likely that someone will have the time to help.

**Comment by DavidBiesack** [comment]
here is a minimal example, as a sh archive

save and run
```
    sh echo-servlet.sh.txt
    cd echo-servlet
    gradle test
```

this shows the failure - the unit test performs a POST with just a request body and does not set Content-Type; this fails as the request body is read before the service method runs. 

In `EchoServletApplication.java` set `ENABLE_HIDDEN_METHOD_FILTER` to false to disable the filter and then the test now runs cleanly.

[echo-servlet.sh.txt](https://github.com/spring-projects/spring-boot/files/68642/echo-servlet.sh.txt)

**Comment by wilkinsona** [comment]
Sun's `HttpURLConnection` sets the `Content-Type` header to `application/x-www-form-urlencoded` if it hasn't already been set: http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/net/www/protocol/http/HttpURLConnection.java?av=f#611. I'd recommend either setting the content type explicitly or using a different HTTP client.

**Comment by DavidBiesack** [comment]
Thanks for tracking that down @wilkinsona . I do have a workaround for my service by disabling the `HiddenHttpMethodFilter` . Perhaps disabling the filter creates a condition where `HttpURLConnection` does not enter that code branch.

**Comment by vy** [comment]
@wilkinsona, in [HRRS](https://github.com/vy/hrrs), I am having a similar problem while `HrrsFilter` tries to record the input stream of `POST` requests of type `application/x-www-form-urlencoded`. (I wrap the original `InputStream` in `HrrsFilter`.) I tried disabling `HiddenHttpMethodFilter` as detailed in the bug report, but did not work in my case. (I can imagine due to the age of the post.) Do you have any ideas about how to solve this issue? BTW, you can view my example Spring Boot project [here](https://github.com/vy/hrrs/tree/master/examples/spring).
