### ISSUE TITLE
spring-boot app war deployment in Tomcat , existing app fails.

### ISSUE THREAD

**Issue by winkumar** [spring-projects/spring-boot#4795]
In my tomcat contain existing spring web app (It not use spring boot), Now I developed new app use spring boot, when i deploy new spring boot app, my existing spring app not working,(It shows somthing ClassNotFound Exception). My new spring boot app is working. I am using maven build tool.
thanks.

**Comment by snicoll** [comment]
As we've already asked in the _four_ other issues that you've raised in this area, please use Stack Overflow for general usage questions. We prefer to use GitHub issues for bugs and enhancements. If you do post to Stack Overflow, feel free to update this issue with a link to the reposted question (so that other people can find it).

**Comment by winkumar** [comment]
sorry, i cant able to post questions Stack Overflow.

**Comment by philwebb** [comment]
@winkumar Why not?

**Comment by winkumar** [comment]
I think my Stack Overflow account blocked, I got following response "Sorry, we are no longer accepting questions from this account", Now i am working production part , this time i face deployment issue, how to solve.

**Comment by philwebb** [comment]
PS. Please don't provide the answers above here, this issue really does belong on stack overflow.
