### ISSUE TITLE
Include maven site/javadoc as  endpoint intolerant boot app

### ISSUE THREAD

**Issue by cforce** [spring-projects/spring-boot#4815]
Would be great to have a setting/Starter that automatically can publish maven site &javadoc as part of the microservice via endpoint . Maybe involved prerequisites: spring boot maven plugin to add Ressource patheä for site/ and javadoc folder, spring boot web Starter to provide Server for static Ressource,  spring boot actuator docs to give it a nie Homepage in spring boot World.  Endpoint could the be on/offen via actuator endpoint cfg

**Comment by cforce** [comment]
Its an enhancement-feature

**Comment by snicoll** [comment]
I am not sure what you expect Spring Boot to do here. It's mostly a build pipeline problem with Boot serving static assets. The most "complicated" part would be to actually generate that content and I am not sure we should be dealing with this. 

Unless I misunderstood what you're asking for maybe?

**Comment by philwebb** [comment]
I agree with @snicoll that this is getting too much into the territory of the build system. I'm also not keen to add functionality that ties us too much with Maven since we want to remain build system agnostic.

It should be possible to develop a Maven plugin to do what you want, but I'm not convinced it should be part of Spring Boot. As long as the plugin puts the assets in the right place, Spring Boot will happily serve them. I would suggest trying to develop your own solution here.

**Comment by cforce** [comment]
I am surpised you argue that way, because the spring boot maven plugin already is tied to maven and uses e.g project.artifact and project version from build system . Why can't this not placed there also as part of this maven plugin?

**Comment by wilkinsona** [comment]
We supply Maven and Gradle plugins that are specifically designed for building and running Spring Boot apps. The functionality that you are requesting isn't specific to Spring Boot so it doesn't make sense for Spring Boot to provide it. A general purpose plugin that can copy the site and javadoc to a configurable location will do the job, without being coupled to Spring Boot.
