### ISSUE TITLE
problem on building package

### ISSUE THREAD

**Issue by Thiru-M** [spring-projects/spring-boot#4824]
Hi, 
I am getting an issue while i do mvn package 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
1:compile (default-compile) on project spring-boot-sample-undertow: Fatal error
compiling: invalid target release: 1.8 -> [Help 1]

can any one help me to resolve it,,

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Thiru-M** [comment]
Thanks i have solved the issue,
