### ISSUE TITLE
Multiple target package

### ISSUE THREAD

**Issue by 984767343** [spring-projects/spring-boot#4848]
We are working on a spring boot project, and the application will be assembled to almost 200+ packages(war) to our different customers.

Almost 98% if the features are same between different customers(that's why we use the same project), the main difference resides in the database configuation and the content of some pages.

We are using `maven` as the build tool, this is the structure:

```
app
	src/main
		java
		resource
			config
				application.properties
				application.client1.properties
				application.client2.properties
		webapp
			WEB-INF
				tiles-definitions.xml
				tiles
					layout
						classic.jsp
					partial
						header.jsp
						footer.jsp
						home.jsp
				client1
					home.jsp
```
					
As shown, `application.properties` hold the common properties, and the `app.xx.properties` will hold the custom properties.

For the web pages, the application use the `WEB-INF\tiles` by default, but there maybe some unique feature in the page for some customers, so we put these pages in a different fold to override the default page.

It seems that I can use `maven-assembly-plulgin` to make it, however I found that it will cause the pom.xml too large to maintain,think about 200+ `execution` in the file:

![image](https://cloud.githubusercontent.com/assets/16457917/12013633/46009480-ad56-11e5-8492-8064a2ea0c32.png)

Any other suggestion?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
