### ISSUE TITLE
Same configuration work different between using properties and yaml

### ISSUE THREAD

**Issue by apachemaven** [spring-projects/spring-boot#4849]
I tried to disable the `whitelabel` feature in spring boot, and I want to display my own error page, so I set the following configuration `application.properties`:
```
server.error.whitelabel.enabled=false
server.port=3000
```

While it works, but once I change my configuration to `application.yaml`(of course I removed the `application.properties`, and make a clean re-build)

```
server: 
  error:
    whitelabel:
      enable: false
  port: 3000
```

The spring boot whitelable page display again.

**Comment by snicoll** [comment]
you wrote `enable` instead of `enabled` in the YAML file. Is that a typo in the description or you made that mistake in your yaml file as well?

Having said that, it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by apachemaven** [comment]
:+1: 

I am f.. too stupid, I have check many times,but did not find that. Thanks.
