### ISSUE TITLE
Property placeholder delimeter should be better documented after switching only to @...@

### ISSUE THREAD

**Issue by dharezlak** [spring-projects/spring-boot#4851]
In comparison to Spring Boot Maven Plugin 1.2.x the 1.3.1 has the useDefaultDelimiters property set to false, which means that in application.properties files only @ characters can be used for property filtering. This should be reflected by the documentation at http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-placeholders-in-properties.

**Comment by snicoll** [comment]
That was the whole point of that change in 1.3. I think you misunderstood what the section you referenced is all about. 

That section explains you can use any value of the `Environment` using a placeholder. This is not the intended to reference things that are filtered by Maven but rather thing you can use regardless of the build tool (or whether filtering is enabled).

Previously, Maven matches the same syntax which means that we could inadvertently replace something that was meant to be a "Spring" placeholder. That's why we changed the syntax to `@@` for Maven-based properties. See [here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-maven) and [here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-short-command-line-arguments) for more reference.

**Comment by dharezlak** [comment]
Thanks, somehow I missed this in the release notes.
