### ISSUE TITLE
Config metadata not generated from interface

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#4862]
If you have a `@ConfigurationProperties` class that implements an interface it could (should) be able to rely on the interface to document the properties. Currently this isn't supported.

**Comment by snicoll** [comment]
We only look for field javadoc, we never looked at method javadoc so it's not related to interfaces at all. 

We also don't want to look at method javadoc as this is the place for regular API documentation and since we want a dedicated documentation for configuration keys, we also need a different mean to collect it.

The only thing that would work is a dedicated annotation. Any other idea?

**Comment by snicoll** [comment]
@dsyer I am closing this one (see above). Feel free to reopen if I missed anything.
