### ISSUE TITLE
Exclude ManagementWebSecurityAutoConfiguration, but /health still uses Security.isEnabled()

### ISSUE THREAD

**Issue by khong07** [spring-projects/spring-boot#4870]
Hi,

I don't want to use `spring-boot-actuator-security` (spring boot 1.3.0)  approach in my application but my own security config. So I exclude `ManagementWebSecurityAutoConfiguration`. All Endpoints are ok except `heatlh`.

Looking into the code, I found these lines in `EndpointWebMvcManagementContextConfiguration`

``` java
    @Bean
    @ConditionalOnBean(HealthEndpoint.class)
    @ConditionalOnEnabledEndpoint("health")
    public HealthMvcEndpoint healthMvcEndpoint(HealthEndpoint delegate) {
        Security security = this.managementServerProperties.getSecurity();
        boolean secure = (security != null && security.isEnabled());
        HealthMvcEndpoint healthMvcEndpoint = new HealthMvcEndpoint(delegate, secure);
        if (this.healthMvcEndpointProperties.getMapping() != null) {
            healthMvcEndpoint.addStatusMapping(this.healthMvcEndpointProperties.getMapping());
        }
        return healthMvcEndpoint;
    }
```

The security shouldn't be managed in  `ManagementWebSecurityAutoConfiguration` ?
Why the check `security.isEnabled()` is only for `health` and not other endpoints?
There's probably the same problem with `CrshAutoConfiguration` (I'm not sure).

**Comment by kuipercm** [comment]
I have the same questions. This is a very confusing point when you want to use your own security configuration. This `security.isEnabled()` check is troublesome:
- the `Security security = this.managementServerProperties.getSecurity();` almost always returns a valid Security object when you provide your own security, because the class `org.springframework.security.config.http.SessionCreationPolicy`, which is used in the conditional for creating the security object in the first place, is on the classpath.
- A `Security` instance is by default initialized with the `enabled` parameter set to true.
So unless you do something specific with this `enabled` parameter, the `boolean secure` will always be set to true, leading to a situation in which the only way to get the extensive form of the /health endpoint is by providing a principal, which you may or may not want (depending on your own configuration).

As @khong07 asked, why is this check added for the health endpoint but no for other endpoints?
I'd like to add: how do I get around it?

**Comment by philwebb** [comment]
The `HealthEndpoint` is somewhat special since the content changes depending on if a request is authenticated or not. See [this section](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-health-access-restrictions) of the docs for a summary.

The log here is that you often want to perform a health check, but it might not always be wise to expose too much information.

Do you have a sample application that shows what you've got so far. Perhaps we can add something to the auto-configuration to detect it. The other option might be to provide your own `HealthMvcEndpoint` and set `endpoints.health.enabled` to `false` to disable ours.

**Comment by kuipercm** [comment]
A code sample might be a little difficult, but I will try to come up with something that is both brief and still makes sense enough to be a real situation.

In the mean time, I understand that the HealthEndpoint is special and I fully agree with the approach to give it two "modes": an open mode (up/down) and a restricted mode (detailed health info). I think this is a very useful approach actually.

The issue is more with the implementation of it: basically the current setup is that the restricted mode is a little "short circuited". If I understand the code correctly, the check for creating a Security instance in the ManagementServerProperties is done based on the presence of a class on the classpath. Having this class present doesn't mean I actually use security at all, it just means I have a library. The HealthMvcEndpoint does assume however that in that case (having the class on the classpath) I want to have the open form of the endpoint when I don't provide credentials. I can however at that time have no security configuration at all, but will still require credentials for this endpoint (which I actually cannot provide...) I don't think that that is correct.

**Comment by philwebb** [comment]
Did you have any luck coming up with a sample?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kuipercm** [comment]
Hi,
Sorry, no I haven't found the time yet to create an example.

I was also under the impression that my explanation above would trigger you have a look at the code and make new considerations about the implementation. A code sample will demonstrate that it doesn't work as expected, but that's also clear from looking at the current implementation (see [security object creation conditional](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/ManagementServerProperties.java#L78) and [security object initalization default] (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/ManagementServerProperties.java#L160). This in conjunction with [the construction of the mvc endpoint](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/mvc/HealthMvcEndpoint.java#L72) leads to the fact that the endpoint should always be accessed with a Principal to get all health details (see also [the security check](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/mvc/HealthMvcEndpoint.java#L178)).

**Comment by philwebb** [comment]
Possibly also related to #5750

**Comment by dwelch2344** [comment]
@philwebb Yeah, basically the same issue I was posting about. It would be nice to have some sort configurable strategy or criteria to cover various cases.

**Comment by nwoike** [comment]
Similarly I have overridden my management configuration settings using `@Order(ManagementServerProperties.ACCESS_OVERRIDE_ORDER)` on a custom `WebSecurityConfigurerAdapter` but the `HealthMvcEndpoint` is executing the following role check that doesn't align to my security requirements (no role requirement).

```java
private boolean isSecure(Principal principal) {
	if (principal == null || principal.getClass().getName().contains("Anonymous")) {
		return false;
	}
	if (isSpringSecurityAuthentication(principal)) {
		Authentication authentication = (Authentication) principal;
		String role = this.roleResolver.getProperty("role", "ROLE_ADMIN");
		for (GrantedAuthority authority : authentication.getAuthorities()) {
			String name = authority.getAuthority();
			if (role.equals(name) || ("ROLE_" + role).equals(name)) {
				return true;
			}
		}
	}
	return false;
}
```
I have been forced to add a fake role to all authenticated management users to get this working for the time being.

Note that in 1.4.0.RELEASE there is an additional defect already fixed in the master: 

```java
String role = this.roleResolver.getProperty("role", "ROLE_ADMIN");
```
The `role` property was changed to `roles` in 1.4.x so you have to leverage the deprecated property value for this to work.

**Comment by wilkinsona** [comment]
For the problem described in the opening description, you can solve it by using `management.security.enabled=false` rather than excluding `ManagementWebSecurityAutoConfiguration`. For more sophisticated configuration that's been discussed in the comments, this is a duplicate of #5750.
