### ISSUE TITLE
Listen ip address

### ISSUE THREAD

**Issue by JonattanV** [spring-projects/spring-boot#4904]
Hello, 
I use the following dependencies "org.springframework.boot: spring-boot-starter-security" and "org.springframework.security.oauth:spring-security-oauth2".

It works well if I open https://localhost:8443/oauth/token
```json
response {
  "access_token": "...
}
```
But to make the request with the IP address https://192.168.1.55:8443/oauth/token get the following message:
```xml
<oauth>
<error_description>
Full authentication is required to access this resource
</error_description>
<error>unauthorized</error>
</oauth>
```

which could be the reason thanks!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
