### ISSUE TITLE
Provide a way to disable spring-boot-maven-plugin:start

### ISSUE THREAD

**Issue by php-coder** [spring-projects/spring-boot#4922]
I'm using TravisCI for building my project and [it always executes mvn install -DskipTests=true before running tests to install project’s dependencies](https://docs.travis-ci.com/user/languages/java#Dependency-Management). This means that `spring-boot-maven-plugin:start` will be executed twice. I'm looking for a way to not run my application twice. I've found `skip` option but unfortunately it doesn't affect `start` goal.

Could you add support for `skip` option to the `spring-boot-maven-plugin:start`?

**Comment by mjustin** [comment]
I also have a need for a skip option for the start goal.  I have Cucumber functional tests which execute during the functional-test step of the Maven lifecycle.  Therefore, I run the spring-boot:start goal during my pre-integration-test phase, and spring-boot:stop goal during my post-integration-test phase.

However, I sometimes want to skip spinning up and tearing down the server.  For instance, if I'm skipping tests, I would like to be able to tell Maven not to spin up the Spring Boot server.  The other scenario I've run across is when there's some issue with starting up the app due to local issues (perhaps it could be due to a CI server not having all the infrastructure needed to starting up the app, or something weird with my local network), but I still want to run the "verify" Maven goal.

The workaround now is to open the pom, and comment out the section that starts & stops the app.  This works locally (though is a bit of a pain), but wouldn't work in the CI environment scenario I mentioned.  Other similar plugins I've used allow me to skip the app startup (e.g. the Tomcat plugin allows passing in the system property "maven.tomcat.skip", per https://tomcat.apache.org/maven-plugin-2.2/tomcat7-maven-plugin/run-mojo.html).

Note that if I skip starting the Spring Boot app, it is a requirement that the "stop" goal does not error due to no app running.  In other words, the "stop" goal should also be skippable, and should also not fail with an error if the start goal is skipped.

**Comment by php-coder** [comment]
In my case, problem with TravisCI occurs when you're trying to test on different databases. In this case you will create database in `before_script` section but the build fails because Spring Boot application will start during `mvn install` that occurs before executing of `before_script` (and hence it can't find database, because it wasn't created yet).

The only workaround that I see is to use maven's profiles but in this case you need to always specify profile.

**Comment by snicoll** [comment]
I am ok to add a `skip`attribute but you'll need to enable it anyway via some kind of condition (i.e. profile). The only upsideI see is that we can map it to a command-line attribute and then you can skip it via a system property.

Right now, you can move the execution to a profile and you'll get pretty much the same experience (-Dfoo.bar=true vs. -PmyProfile). Am I missing something?

**Comment by mjustin** [comment]
I think the profile execution makes sense for php-coder's use case (since the workflow described is known ahead of time, and it makes sense to move it to a profile).  I think having a command-line attribute (ala tomcat:run) is still very useful to support the case don't know ahead of time that you'll be skipping the startup (unexpected local issues and you just want to verify or install, or the like).

**Comment by snicoll** [comment]
fair enough.

**Comment by mjustin** [comment]
Is there a system property for this test flag that was added that can be passed in from the command line?

**Comment by snicoll** [comment]
Nope, you can create your own

```
<properties>
  <run.it.skip>false</run.it.skip>
</properties>
```
