### ISSUE TITLE
spring.resources.cache-period

### ISSUE THREAD

**Issue by kingslay** [spring-projects/spring-boot#4931]
I have set spring.resources.cache-period: 3600 in application.yml. but after run the booRun
the debug show 
 "spring.resources.cache-period" -> "'spring.resources.cache-period' from 'refresh'"
"spring.resources.chain.html-application-cache" -> "'spring.resources.chain.html-application-cache' from 'applicationConfig: [classpath:/application.yml]'"
and the "spring.resources.cache-period"  value is 0.

**Comment by kingslay** [comment]
i have create a META-INF/spring-devtools.properties file. 
resources.cache-period= 3600

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Having said that, please make sure to actually write a question when you create the thread. From what I understand you're trying to set a given cache period and when you run your application with devtools it got overridden to 0 (which is IMO a sensible default in a Dev environment so I am not sure what the problem is).
