### ISSUE TITLE
documentation of AutoConfiguration classes

### ISSUE THREAD

**Issue by hareesh996** [spring-projects/spring-boot#4975]
I was doing some examples on spring boot, in between i was getting exception via HibernateJpaAutoConfiguration class, saying that datasource is not setup, its type is NONE. Finally I resolved by seeing the AutoConfiguration Report, and then I excluded HibernateJpaAutoConfigurtion class. 
It would be better if we have documentation of the AutoConfiguration class that explains the dependencies of it. So that we can exclude AutoConfiguration classes which are actually not needed for us.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. The auto-configuration classes are already [listed in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#auto-configuration-classes). Each entry in the list links to the source code so that you can see what it does and what it depends upon. We don't want to include that information directly in the documentation as it would inevitably get out of sync with the code.
