### ISSUE TITLE
Fix unusual Flyway binding

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4995]
Around line 119 of `FlywayAutoConfiguration`, the following:

``` java
flyway.setLocations(this.properties.getLocations().toArray(new String[0]));
```

should be removed when [SPR-13749](https://jira.spring.io/browse/SPR-13749) is fixed

**Comment by wilkinsona** [comment]
I don't think we can remove this is in 1.3.x as the SPR issue is targeted at 4.3 RC1. We'll need to tackle this in 1.4.

**Comment by snicoll** [comment]
We aren't going to "fix" SPR-13749 at all I am afraid so this one will have to stick up to 2.0 when we'll remove the `@ConfigurationProperties` binding of 3rd party classes (at least not mixing them with a regular POJO in the same namespace).

**Comment by philwebb** [comment]
Pretty sure #12322 will fix the collection copy issue. It's still a bit funky that we bind to a properties and to the `Flyway` instance.

**Comment by snicoll** [comment]
Yeah, perhaps we should use this issue to replicate the properties in our own code. Ideally, a different namespace for the 3rd party object would have been better but it's bit late for that.

**Comment by wilkinsona** [comment]
I tried that once and it was pretty horrendous. It might be worth revisiting now that we have the property mapper. IIRC, the main concern was keeping our properties in sync with Flyway's.

**Comment by philwebb** [comment]
Re-purposed this issue to just fix the location binding which we probably no longer need to do manually.

**Comment by snicoll** [comment]
> Re-purposed this issue to just fix the location binding which we probably no longer need to do manually.

I am not sure I understood the re-purposed scope of this issue. The manual binding is there to make sure that `{vendor}` placeholders are going to be resolved. Because our properties object is on the same namespace as the `Flyway` object, here's what happens if you run an app with the following property

```
spring.flyway.locations=classpath:db/vendors/{vendor},classpath:db/changelog
```

First we create the `Flyway` object and we resolve that String according to the target `DataSource`. We then return that object. Because binding happes on `spring.flyway` and `Flyway` has also a `setLocations` method. We bind again with the raw string above. If we remove `SpringBootFlyway` the raw string overrides the resolved one.

The first binding is not strictly necessary but we make sure that the locations exist, if necessary. IMO, the only way to fix this issue is to bind the `Flyway` object to another namespace (or stop binding it at all like we do for `Liquibase`.

Considering that we've concluded it would be a lot of work, I am not sure what's left here.

**Comment by philwebb** [comment]
Originally I thought we could just drop the direct `setLocations` call because the binder will now work with arrays. We can't quite remove all the code unfortunately since we still want to validate locations. We can't shift that logic to the setter because we actually check if no locations have been set at all.

The most we can do is remove one call to setLocations.
