### ISSUE TITLE
Disable session on embedded http server

### ISSUE THREAD

**Issue by celiovasconcelos** [spring-projects/spring-boot#5027]
*Spring Boot 1.3.2*

I want to tuning my application.
Does these properties able to disable the session mechanism completely?

```
server.session.persistent=false
server.session.timeout=0
```

If not, how to do this?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by lhanson** [comment]
https://stackoverflow.com/q/35014150/80144
