### ISSUE TITLE
Adding Additional Configuration Properties to RabbitAutoConfiguration

### ISSUE THREAD

**Issue by coreyjv** [spring-projects/spring-boot#5031]
In our environment there are a number of configuration properties that we set on a `com.rabbitmq.client.ConnectionFactory` that are not exposed via `RabbitAutoConfiguration` and `RabbitProperties`. This prevents us from using the `RabbitAutoConfiguration`. The properties that we're interested in are `automaticRecovery` and `networkRecoveryInterval`.

I can submit a PR with the changes (as well as any other properties you may want to expose through the auto-configuration) but I wanted to ask prior to submitting the PR.

**Comment by snicoll** [comment]
ping @garyrussell

**Comment by philwebb** [comment]
@coreyjv They sound like sensible additions to me. A PR would be most welcome, thanks! Please also remember to sign the CLA if you haven't already.

**Comment by coreyjv** [comment]
Thanks @philwebb. One followup question. Would it be possible to expand the scope of this PR to include other `com.rabbitmq.client.ConnectionFactory` settings like [Client Properties](https://www.rabbitmq.com/releases/rabbitmq-java-client/current-javadoc/com/rabbitmq/client/ConnectionFactory.html#setClientProperties(java.util.Map)) or would you prefer another issue be created?

**Comment by garyrussell** [comment]
Spring AMQP is not compatible with RabbitMQ auto recovery.

Spring AMQP has had its own recovery mechanism (that predated the (now) inbuilt recovery) on day 1.

The problem is that the listener container consumers terminate when the connection is lost; when rabbit recovers the consumers, there is no code using them so they just sit idle.

To avoid this problem, the container physically closes its channels when the connection is lost, effectively disabling auto recovery (on the consumer side).

Changing Spring AMQP to use the native recovery will need a complete rewrite of the listener container (which we are considering for a release next year).

There might be some benefit to auto recovery on the producer side, but Spring AMQP's solution there is to configure a `RetryTemplate` (from `spring-retry`) into the `RabbitTemplate`.

**Comment by coreyjv** [comment]
Hi @garyrussell --

Thanks for providing this insight I appreciate it. I understand that Spring AMQP is not compatible with RabbitMQ auto recovery, however I was hoping to include this functionality in a RabbitMQ specific class (`RabbitConnectionFactoryBean`) which is used by the Spring Boot `RabbitAutoConfiguration`. 

Just so I'm clear are you saying these changes won't be accepted or is further discussion needed?

Thanks!

**Comment by wilkinsona** [comment]
@coreyjv `RabbitAutoConfiguration` auto-configures a number of Spring AMQP features. As such, it isn't appropriate for it to enable the configuration of RabbitMQ functionality that doesn't work as expected with Spring AMQP.

**Comment by coreyjv** [comment]
Thanks for the clarification @wilkinsona. It seems a bit odd to me that we have a `RabbitAutoConfiguration` which configures a connection using a `RabbitConnectionFactoryBean` but we can't use any Rabbit specific features. 

Have there been any thoughts to pushing AMQP compliant configuration to `AmqpAutoConfiguration` and `AmqpConnectionFactoryBean` classes and allowing Rabbit specific configuration in its classes?

Please feel free to close this issue (and the other one) if these additional configuration options will not be integrated.

**Comment by wilkinsona** [comment]
> It seems a bit odd to me that we have a RabbitAutoConfiguration which configures a connection using a RabbitConnectionFactoryBean but we can't use any Rabbit specific features.

I think @garyrussell already explained the reasons for that above. It's a limitation of the current Spring AMQP implementation.

> Have there been any thoughts to pushing AMQP compliant configuration to AmqpAutoConfiguration and AmqpConnectionFactoryBean classes and allowing Rabbit specific configuration in its classes?

Having logic that's Rabbit-specific in a class that doesn't mention Rabbit in its name might just confuse things further.

I think I'm now a bit confused about what the original purpose of this issue was. Can you share what you're currently configuring manually and how you're using Rabbit and Spring AMQP (assuming that you're using the latter at all). From what @garyrussell has said above, I'm guessing that you're not using the listener container as it doesn't work as expected with RabbitMQ's recovery mechanism.

**Comment by coreyjv** [comment]
Thanks for asking for additional clarification @wilkinsona. In our producer code we configure an instance of `com.rabbitmq.client.ConnectionFactory` and set the `automaticRecoveryEnabled` and `networkRecoveryInterval` as necessary and then it's wrapped in a `org.springframework.amqp.rabbit.connection.CachingConnectionFactory`. 

It's essentially identical to what the `RabbitAutoConfiguration` does but we also set those two properties mentioned above.

**Comment by garyrussell** [comment]
Ah, so you are only using part of Spring AMQP  - specifically, the `CachingConnectionFactory`.

I don't really have major issues with exposing those properties on the FB (in Spring AMQP) and via Boot here, but we would have to be very careful with the Javadoc to explain that those settings are not appropriate for the (current generation) Spring AMQP Listener Container.

However, since you have a work-around (define your own beans), I think I would prefer deferring this until we implement the next generation listener container that can use the auto recovery feature.

**Comment by coreyjv** [comment]
Thanks @garyrussell for providing your feedback. I think based on this it makes sense to close this issue since you intend to implement this feature in the next generation listener container and we can get by for now with configuring our own `@Bean`s

**Comment by garyrussell** [comment]
Thanks.

**Comment by shakuzen** [comment]
New container type added in #9055
