### ISSUE TITLE
How to use multiple xml configuration files?

### ISSUE THREAD

**Issue by richardmz** [spring-projects/spring-boot#5034]
In sample spring-boot-sample-xml, only using one xml configuration file.
How to use multiple configuration files at the same time?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by wilkinsona** [comment]
Hint: the `run` method is overloaded and there's another variant that allows you to pass in an array of configuration sources:

```
public static ConfigurableApplicationContext run(Object[] sources, String[] args)
```

**Comment by richardmz** [comment]
Thank you :)
