### ISSUE TITLE
Spring boot cannot start with two or more DataSources

### ISSUE THREAD

**Issue by quaso** [spring-projects/spring-boot#5104]
DataSourceInitializer init method fails, because it works only if there is just one DataSource bean in the context>

`if (this.applicationContext.getBeanNamesForType(DataSource.class, false, false).length > 0) {
  this.dataSource = this.applicationContext.getBean(DataSource.class);
}`

Either change condition in if clause to "== 0" or handle org.springframework.beans.factory.NoUniqueBeanDefinitionException prope

**Comment by vavrekm** [comment]
Found workaround solution - exlude autoconfiguration of Datasources:

`@EnableAutoConfiguration(exclude = { DataSourceAutoConfiguration.class, DataSourceTransactionManagerAutoConfiguration.class, HibernateJpaAutoConfiguration.class })`

Also discussed here:
http://stackoverflow.com/questions/27843788/resource-annotation-no-qualifying-bean-of-type-javax-sql-datasource-is-define

**Comment by wilkinsona** [comment]
I'm pleased to hear that you've found a workaround. An alternative that you might like to consider is to mark one of your `DataSource` beans as `@Primary`.

Also, you may be interested to know that the general situation will improve in 1.4.0.M2 when https://github.com/spring-projects/spring-boot/issues/2784 is implemented. It will mean that the initialiser backs off when there are multiple `DataSource` beans to choose from rather than failing as it currently does.

**Comment by ddsdggsg** [comment]
May I ask how to use/config two or more Datasource?
I just want to use JDBCtemplate (from datasource),
is there any sample project ?Thanks...a lot^^
