### ISSUE TITLE
Add an option to the `run` task to copy resources as they change when devtools is present

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#5136]
We want devtools to work as smoothly as possible. Right now, devtools only monitor the classpath which means that you have to update it to trigger a change. This confuses a lot of people and in particular front-end dev that are used to _only_ change their files.

When a project is running in a development environment, its working directory is usually the root of the module holding the code. All IDEs have settings to make sure that it is the case. We could add an option that does the following:
- Watch for `${user.dir}/src/main/resources/templates` and trigger a LiveReload refresh when thing changes there (maybe we need to be smart to avoid refreshing the browser too often
- Add `${user.dir}/src/main/resources/static` to the list of resources Spring MVC uses to serve static assets

Of course, both of these can be reconfigured by the user. We should inspect the environment and react accordingly.

**Comment by philwebb** [comment]
I think this issue is somewhat unique to IntelliJ since Eclipse automatically copies the assets and triggers a reload.

**Comment by wilkinsona** [comment]
Not just, IntelliJ. It also applies if you're trying to work on the front end of an app using `mvn spring-boot:run`. The story with Gradle is a bit better as you can use `./gradlew bootRun` and `./gradlew build -t` to have your changes continuously built and the classpath auto-updated.

**Comment by rstoyanchev** [comment]
Right and aside from not wanting to feel unique in this context :) ... another part of this is the change in behavior that comes with the upgrade 1.2 to 1.3.

**Comment by snicoll** [comment]
> I think this issue is somewhat unique to IntelliJ since Eclipse automatically copies the assets and triggers a reload.

I don't think that's a fair statement. In Eclipse you have to save and you're used to that because you _need_ to do it (so it's part of the workflow). IJ doesn't need to do anything (inspections, errors, etc  are shown to you live). Devtools is distributive in this workflow because you have to update the classpath and that's not something an IJ user does while coding.

**Comment by snicoll** [comment]
> Devtools is distributive in this workflow because you have to update the classpath

Actually, let me take that back. When you debug an app and you want to hot swap things you have to invoke "make project" as well so Devtools is no different in that area. I think the one thing that matters is resources that do not require a restart. It would be nice if those one were handled in such a way that we don't need to update the classpath.

**Comment by snicoll** [comment]
Alright, let's focus on the Spring Boot Maven plugin here. I've created [IDEA-151817](https://youtrack.jetbrains.com/issue/IDEA-151817) to improve the user experience in IntelliJ IDEA.

We discussed internally and what we could do is add an option in the `run` goal of the `spring-boot-maven-plugin` to watch the `resources` directory and copy files when they change using the filtering rules of the Maven project. If we manage to do that, it would be safe to enable that by default when devtools is present. That way we would improve the developer experience for those who are not using an IDE.

**Comment by snicoll** [comment]
After having poked in the `maven-resources- plugin` codebase, this seems quite challenging:

* There is an abstraction of most concepts, yet the `maven-resources-plugin` has obviously tuning options that we would have to replicate/retrieve/apply in our own customizations
* The shared workflow is to take a `Resource` (a regex pattern with some filtering options and a target output) and "process it". We, on the other hand, have an event that a certain file has been changed and we need to do the reverse work (find back the resource to which this file belongs to, figure out if filtering should be applied and apply it.

It looks like a significant amount of work that may lead to new issues (especially users having resource filtering customizations). What do you think @wilkinsona ?

**Comment by wilkinsona** [comment]
I think it sounds rather risky, particularly for this fairly late stage of 1.4. My feeling is that we should either accept that this is a limitation that comes with using Maven or tackle it early in 2.0.

**Comment by philwebb** [comment]
Agreed. Let's push this back to 2.0.

**Comment by xak2000** [comment]
I'm a gradle user (not maven) and run into this problem right now.

I spent several hours, I read all the docs but all I found is only that:
> You can also start your application via the supported build plugins (i.e. Maven and Gradle) as long as forking is enabled since DevTools need an isolated application classloader to operate properly. Gradle and Maven do that by default when they detect DevTools on the classpath.

After that I tried another several hours to make this work without any success.

What I want is just call `gradle bootRun` (with `runtime('org.springframework.boot:spring-boot-devtools')` in my `build.gradle`) and after that if I change my `src/main/resources/static/style.css` from my **notepad** :) (not an IDE!) - I can press `F5` in my browser and see the result.

This doesn't work. But documentation is somehow misleading. It says "You can" but I cannot. :)
Another not very clear thing for me is what is `forking` in the context of build tools and how to enable it? The documentation says `as long as forking is enabled`. I googled `gradle enable forking` but not found anythihg.

This problem is also actual even when I run my application from Eclipse (STS). In this case reloading of static resources works, but only if I edit them in Eclipse (or ALT-TABbing to Eclipse and press F5 on the project after edit the file in another editor). Why I need another editor if I run the IDE? Because editing html/less/js in Eclipse sucks. There are plenty of other lightweight editors for this and they all working much better than Eclipse. Eclipse is just for Java code.

So, I think this issue is very important for any frontend or (backend+frontend, like me) developers.

And fix the docs please to prevent futher headaches of other developers. Make clear that reloading of static resources doesn't work when you run project from commandline using `gradle bootRun` or `maven boot:run`.

---
Also, @wilkinsona wrote:
> The story with Gradle is a bit better as you can use `./gradlew bootRun` and `./gradlew build -t` to have your changes continuously built and the classpath auto-updated.

Thanks you, @wilkinsona! This can be a temporary workaround for my current problem! I just tried and it works!

**Comment by xak2000** [comment]
For any developer, who found this issue, I found a way to make your developer's experience better:

The best way I found for now to make decent development experience using spring-boot and Eclipse is to run the server project from inside Eclipe (Run As -> Spring Boot App) and install [this plugin](https://github.com/psxpaul/EclipseJava7Refresher) into Eclipse. This plugin monitors the filesystem for external changes (using Java7 API, which Eclipse doesn't use on Linux systems) and Eclipse updates the classpath when you change any resource file even from external editor. It just makes "Window->Preferences->General->Workspace->Refresh using native hooks or polling" option work on Linux system. Without this plugin eclipse doesn't update the classpath on external file changes until you manually hit the "Refresh" project.

This way you have autorestart of spring-boot app on any class-file changes and also any external change of html/less/css/js is instantly visible.

---
The other and simplier way to make external changes of resource visible is to run the project using `gradle bootRun` and set
```
bootRun {
	addResources = true
}
```
in your `build.gradle` file.

But unfortunately class changes doesn't work this way. When you edit `.java` files from Eclipse, it puts `.class` files not into gradle's `build` folder, but into it's own `bin` folder. So I think `spring-boot-devtools` doesn't see the changes because of this.

**Comment by highdali** [comment]
Why doesn't devtool just load resources into `build` directory ? Devtool just monitor real source directory(`src/...`). But I want to pre-process resources(babel, sass compile...) before these are loaded. Of course, I place resources into source directory. but how can i capture the change of these files? For devtools, pre-process looks like *change*. And change of content looks like *change* too. Of course I can move these resource other temporary directory. so it can be preprocessed. and these come back into original directory.(change again?). In this case i have to maintain two type of file.(original and pre-processed). Option helps we to choose the monitoring directory is needed. For all of fussy case, devtool should monitor a build(output) directory.

**Comment by snicoll** [comment]
@highdali we don't use the tracker for questions (and devtools doesn't do what you've described unless you set the `addResources` flag). Join us on Gitter or ask on StackOverflow if you have more questions.

**Comment by highdali** [comment]
ok. but `addResources` flag does not solve this problem.
There are resources just do not want to load itself. (pre-process is required) between modify and load.(devltool just reload the raw resource)

**Comment by RichardBradley** [comment]
If you want "hot" reload without needing to rebuild the project (for example, for files edited outside of your IDE, such as by `npm`), I found that adding a "file:" entry to the `spring.resources.static-locations` will do that, i.e.

```
spring.resources.static-locations[0]=file:my-module/src/main/resources/public/
spring.resources.static-locations[1]=classpath:/public/
```

This will have no effect on live servers, as they do not have a "src" directory.

**Comment by spencergibb** [comment]
@RichardBradley and could easily get put in a config file with a profile that is only active during development.

**Comment by mkpaz** [comment]
Guys, please, just mention this issue in the official docs. This phrase "When devtools is running, it detects change when you recompile your application and automatically refreshes it. This works for not only resources but code as well" is somewhat misleading and unclear. The key is **recompile**, so one'll need an IDE. The entire thread explains everything. I would not have lost several hours if I've found it earlier.

**Comment by snicoll** [comment]
@mkpaz I believe the [doc is pretty clear](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart) (with several round of polishing in that area). If you feel differently, I am happy to review a PR that improves it.

**Comment by philwebb** [comment]
This feature is a nice idea but currently I don't think we can justify the amount of time needed to implement it. This feels like it's more in the domain of build tools.
