### ISSUE TITLE
Change webAppDir in gradle bootRun

### ISSUE THREAD

**Issue by jackysee** [spring-projects/spring-boot#5154]
I would like to change the webapp directory from default `src\main\webapp` to `src\main\webapp\dist`. For the war plugin, it can be configured by `project.webAppDir = 'src\main\webapp\dist`. For the spring boot gradle plugin, the `bootRun` task would still expose `src\main\webapp` directory as static. How can I change it to `src\main\webapp\dist`?

**Comment by wilkinsona** [comment]
It's serving from `src/main/webapp` as that's one of the common document roots that's understood by `AbstractEmbeddedServletContainerFactory`. I'd urge you to stick with the conventional location.

If you want to customise it, you'll need to call `setDocumentRoot`. Something like this:

```
@Bean
@Profile("bootRun")
public EmbeddedServletContainerCustomizer documentRootConfigurer() {
	return new EmbeddedServletContainerCustomizer() {

		@Override
		public void customize(ConfigurableEmbeddedServletContainer container) {
			container.setDocumentRoot(new File("src/main/webapp/dist"));
		}
	};

}
```

Note that I've used `@Profile` so that this configuration doesn't happen by default. You'll then need to activate the `bootRun` profile when you run `bootRun`. For example, in your `build.gradle`:

```
bootRun {
	args '--spring.profiles.active=bootRun'
}
```

In the future, can you please ask this sort of question on Stack Overflow? As [described in the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bug reports and enhancement requests. You may want to use the `spring-boot` which is monitored by the Spring Boot team and the broader Spring Boot community.

**Comment by rijine** [comment]
@wilkinsona  is it possible to configure it in build.gradle file?
