### ISSUE TITLE
Spring-boot + redis. Use @CacheConfig.

### ISSUE THREAD

**Issue by succour** [spring-projects/spring-boot#5156]
I use @CacheConfig annotation on my controllers and config them cacheNames differently:
first controller:
![1](https://cloud.githubusercontent.com/assets/4241950/13072286/62a66a7a-d4d3-11e5-9667-2d6ac80afebd.png)

the second:
![2](https://cloud.githubusercontent.com/assets/4241950/13072399/1342bb2c-d4d4-11e5-9932-3dec7f7b36fb.png)

when I request the first controller method, I get the redis cache like this:
![3](https://cloud.githubusercontent.com/assets/4241950/13073022/92d4d7d2-d4d7-11e5-8874-b31620a62889.png)
when I request the second controller method, I get the same redis cache. 
It seems like that the "roleGroups~keys" didn't generate, and I get the same result with different requests.

Is it my problem or not?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Shurlormes** [comment]
Hey, Did you solve this problem? @succour 
I have the same problem
