### ISSUE TITLE
Launch script overrides working directory

### ISSUE THREAD

**Issue by praseodym** [spring-projects/spring-boot#5164]
The [launch script changes the working directory to the JAR directory](https://github.com/spring-projects/spring-boot/blob/81fdc99fb0c2a74936069d45a8d41f273a939de0/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L217-L218). When configuration files in the working directory (or in config/) are required, this will break the application.

**Comment by wilkinsona** [comment]
Looked at another way, changing the current behaviour will break anyone who's relying on being able to position files relative to the jar file. We'll discuss it, but I don't think that we can change this. Whatever we decide, the documentation should be improved.

You can always use a custom script if you don't like the current behaviour.

**Comment by praseodym** [comment]
I agree. Introducing a variable to set the working directory could be a good compromise.

**Comment by wilkinsona** [comment]
We consider it to be a best practice for executable jars to be launchable from any directory and to pick up the same configuration and we don't want to introduce a property that makes it easy for people to do otherwise. If you really want to change the behaviour, a custom launch script should be used.

We'll use this issue to update the documentation to clearly describe the current behaviour.

**Comment by praseodym** [comment]
Fair enough, thanks!

**Comment by vpavic** [comment]
@praseodym one possible solution for your situation would be to simply create a symlink to ```.conf``` file next to ```.jar``` file. This would allow you to have ```.conf``` file in the desired directory without modifying launch script.

**Comment by bobtiernay-okta** [comment]
This breaks command line applications that expect the current working directory to be that of the user, not the `lib/` dir. I don't understand what the technical limitation is to supporting the current behavior and having this be overridable at the plugin level. Care to explain?

**Comment by bobtiernay-okta** [comment]
It just seems very unintuitive to change the CWD and not have the ability to allow a user to change that . It basically makes this very useful script unusable for command line applications. That seems like a major downside if you ask me.

> particularly when there's always the option of using your own script entirely.

That seems disingenuous, as I know I can always use my own script. The argument can be made the other way as well: "if it's too complex to ignore an option, use your own script"

**Comment by wilkinsona** [comment]
> That seems disingenuous,

What's disingenuous about wanting to avoid the complexity of providing multiple ways of achieving the same thing?

> "if it's too complex to ignore an option, use your own script"

Using your own script wouldn't allow the option to be ignored as it would still be in Boot's documentation.

**Comment by bobtiernay-okta** [comment]
> What's disingenuous about wanting to avoid the complexity of providing multiple ways of achieving the same thing?

You're basically saying "if this feature doesn't work for you, don't use it" which is not very helpful and doesn't add to the conversation. The reason I'm using Spring Boot in the first place is to help my productivity.  I realize that using or not using a technology is always an option. Stating obvious fact is disingenuous imo.

> Using your own script wouldn't allow the option to be ignored as it would still be in Boot's documentation.

Not everything in Spring Boot is documented. I only know that it changes the CWD by inspecting the implementation. All that is required is to change the implementation slightly so that the customization script can influence the decision to change the CWD. The upside is that you can support an entire class of applications that rely on not changing the CWD.

**Comment by wilkinsona** [comment]
We discussed this when the issue was raised and decided not to make the requested change. Since you commented, I've merely been attempting to make sure that the reasons for us making that decision are clear. I fail to see how that is disingenuous.

> Not everything in Spring Boot is documented. I only know that it changes the CWD by inspecting the implementation.

In this case it is documented as that was the [result](https://github.com/spring-projects/spring-boot/commit/a6b1f4ce6379ce01f5fdb3b24c95704980e25ce1) of this issue.

> The upside is that you can support an entire class of applications that rely on not changing the CWD.

We don't dispute the upside. However, as I tried to explain above, there's a downside to providing another configuration option and we believe that downside outweighs the upside.

**Comment by bobtiernay-okta** [comment]
Fair enough. I respect that even if I can't understand it myself. That said, updating the documentation to state this deficiency I think would help save others from investing in this feature only to find out late in the game it's not going to work.

Anyway, I apologize for coming across strong.  I really appreciate all the work that you guys do on the Boot team. Sincerely, thanks for creating such an amazing project!
