### ISSUE TITLE
debug spring boot in intellij IDEA 

### ISSUE THREAD

**Issue by yarinkos** [spring-projects/spring-boot#5174]
Hi,
i followed some of the tutorial how to dubug spring but application in intelliJ.
i tried to run the main method in debug mode,the springboot:run task  in debug mode,and nothing worked for me.
maybe you can guide me step by step how to debug such project in the most "straightforward" way ?

IDEA 14 ultimate edition

Thanks :)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

When you do, you may want to give a bit more details as "nothing worked for me" isn't going to help anyone. It's not even clear if you're after some way of debugging the app or "hot reload" code via Devtools or the debugger.
