### ISSUE TITLE
Why is my WebApplicationInitializer not loaded

### ISSUE THREAD

**Issue by dickerpulli** [spring-projects/spring-boot#522]
I have a really simple Spring-Boot application and I wonder why my WebApplicationInitializer is not recognized by SpringServletContainerInitializer?

At application startup in console everythings looks fine, but there is no System.err-output from the Initializer. Also, if I set a breakpoint inside the onStartup method it is never reached.

Did I miss anything?

Thanks.

My classes:

``` java
package de.tbosch.web.springboot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan
@EnableAutoConfiguration
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
```

``` java
package de.tbosch.web.springboot;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;

import org.springframework.web.WebApplicationInitializer;

public class Initializer implements WebApplicationInitializer {

    @Override
    public void onStartup(ServletContext servletContext) throws ServletException {
        System.err.println("------------------------------------");
    }

}
```

Details: https://github.com/dickerpulli/playground/tree/master/web/spring-boot

**Comment by mschipperheyn** [comment]
If this is true, the documentation seems extremely misleading. http://docs.spring.io/autorepo/docs/spring-framework/4.1.x/javadoc-api/org/springframework/web/WebApplicationInitializer.html states that WebApplicationInitializers are detected automatically, speaks of a 100% code based approach etc. Never mentions this caveat. Is there some kind of recipe available here?

**Comment by wilkinsona** [comment]
@mschipperheyn Sorry that you've found the documentation misleading. Unfortunately, you're looking at the documentation for Spring _Framework_ and this issue is for Spring _Boot_. The latter takes a more opinionated view of the world than the former. One of those opinions is that `WebApplicationInitializers` are not supported when running your application as an executable jar. They are, however, supported when you deploy a Spring Boot war to a servlet container. I've just looked in the [reference guide](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/) and it looks like we haven't done a good job of documenting this. I've opened https://github.com/spring-projects/spring-boot/issues/4643 so that we can improve Spring Boot's documentation.

**Comment by XiHaHa** [comment]
the problem is solved?

**Comment by philwebb** [comment]
@XiHaHa This issue has been closed since 2015. If you have a problem or a question please ask on stackoverflow.com.

**Comment by mohamad-z** [comment]
I think SpringBootServletInitializer is the equivalent of WebApplicationInitializer in boot projects and it should work in spring-boot
