### ISSUE TITLE
launch.script can't stop app in supervisor

### ISSUE THREAD

**Issue by tietang** [spring-projects/spring-boot#5273]
`org/springframework/boot/loader/tools/launch.script`

supervisor need to get APP PID that is running, but "sh spring-boot-app-exec.jar run" get two process, one is shell process, another is spring-boot-app process, but supervisor got a shell process, when executing stop command in supervisor, can't stop spring-boot-app process.

supervisor *.conf

`command= sh spring-boot-app-exec.jar run`

I add "exec" to "org/springframework/boot/loader/tools/launch.script" before "$command"  , it works!

 `$command` to `exec  $command`

```
run() { 
  pushd "$(dirname "$jarfile")" > /dev/null
  exec $command
  result=$?
  popd
  return "$result"
}
```

**Comment by wilkinsona** [comment]
I don't think we want to make the proposed change. Using `exec` significantly changes the semantics of the script as it replaces the shell with the command that's being run. For example, when run in a non-interactive shell, it will terminate when `exec` fails, rather than running the remainder of the script.

Why do you need to use `sh spring-boot-app-exec.jar run` as the command? You could make the jar itself executable and use `spring-boot-app-exec.jar` as `run` is the default action.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
