### ISSUE TITLE
Add support for object mapping framework 

### ISSUE THREAD

**Issue by arana198** [spring-projects/spring-boot#5275]
Generally in an API design you convert DO to DTO using java. Usually this process is manual and very time consuming.  I would like an automated tool added to Spring Boot by default (preferably **MapStruct** - it's lightweight and object mapping is done at compile time. It's very easy to use and understand, and is the quickest with very rich features compared to all other similar framework out there).

**Comment by wilkinsona** [comment]
@arana198 What would you expect Spring Boot to do to make using an object mapping framework easier? Put another way, what do you currently have to do when using MapStruct that you think Spring Boot could do for you?

**Comment by arana198** [comment]
The easiest thing that could be done is to add the framework to Spring Boot by default and create an annotation that will in background do MapStruct configuration?

This is an example:

`@Mapper(componentModel = "spring")
public interface UserMapper {

    @Mappings({
            @Mapping(target = "id", source = "userId")
    })
	UserBO userToUserBO(final User user);
}`

The componentModel = "spring" indicate we are using Spring Dependency injection. And at compile time it creates an implementation class.

But I guess (for MapStruct) you could just manually add the dependency as there's not much configuration to do. Maybe this will be more suitable for Object Mapping frameworks like Orika where there's a lot configurations that you have to do before you can get started with mapping the object at runtime.

**Comment by wilkinsona** [comment]
> The easiest thing that could be done is to add the framework to Spring Boot by default

Not everyone will want to use MapStruct (or any mapping framework), so I don't think adding it by default is appropriate. We could add dependency management for it, but we only do that for components for which we provide some auto-configuration.

>  and create an annotation that will in background do MapStruct configuration?

The only part of your example that doesn't look to be application-specific is `@Mapper(componentModel = "spring")`. That's not enough to warrant us doing anything in Spring Boot.

> But I guess (for MapStruct) you could just manually add the dependency as there's not much configuration to do. 

Agreed.

> Maybe this will be more suitable for Object Mapping frameworks like Orika where there's a lot configurations

Can you provide an example? Looking at the [Orika User Guide](http://orika-mapper.github.io/orika-docs/index.html) the vast majority of the configuration appears to be application and domain specific. The only exception to that which I could see is with building the `MapperFactory`. However, the builder API looks to be a much better fit than using `application.properties` as the configuration references lots of rich types rather than just scalar values.

**Comment by arana198** [comment]
I'll close the issue as I haven't actually added Orika myself. Maybe when I do and if I feel there's a lot of configuration that maybe Spring Boot can help then I will raise an issue :)
