### ISSUE TITLE
JarFile does not support urls of the form "jar:file:///my.jar!/path"

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-boot#5287]
following works and have test for it

```
File file = new File("...");
new URL("jar:" + file.toUri() + "!/2.dat").openStream();
```

However if the url string is created like this
```
File file = new File("...");
new URL("jar:" + file.toPath().toUri() + "!/2.dat").openStream();
```
it breaks because now on *nix the file uri is of the form `file:///path/to/my.war` instead of `file:/path/to/my.war`

Jetty 9.3 actually now uses `Path` instead of `File` internally and thus the resources from a war cannot be loaded.

--
working on PR

**Comment by valery1707** [comment]
Due to this bug all files in `webapp` directory does not accessible from executable `.war` under Jetty `9.3.x`.

When [detecting jar entry name](https://github.com/spring-projects/spring-boot/blob/d938224/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/JarURLConnection.java#L76) variables will be contains this values:
* `url`: `jar:file:///F:/project-0.1.0-SNAPSHOT.war!/index.html`
* `jarFile`: `F:\project-0.1.0-SNAPSHOT.war`
* `url.getFile()`: `file:///F:/project-0.1.0-SNAPSHOT.war!/index.html`
* `jarFile.getUrl().getFile()`: `file:/F:/project-0.1.0-SNAPSHOT.war!/`
* `spec`: `!/index.html`

In [JarURLConnection#connect](https://github.com/spring-projects/spring-boot/blob/d938224/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/JarURLConnection.java#L106) will be searched `!/index.html` which is not exists.

Downgrade to Jetty `9.2.15.v20160210` fix the problem - files will be accessible.
