### ISSUE TITLE
Force Spring Boot to use Tomcat server

### ISSUE THREAD

**Issue by poznachowski** [spring-projects/spring-boot#5350]
I use default Tomcat embedded container. However, in some of my tests I use Wiremock (using Jetty underneath). This, probably makes my integration tests run against Jetty server, not Tomcat. Any way to force Spring Boot to stick with Tomcat ?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Having said that, you could define an empty `TomcatEmbeddedServletContainerFactory` `@Bean` in your test config to force Tomcat.

**Comment by poznachowski** [comment]
Thank you. Re-posted question:
http://stackoverflow.com/questions/35844784/how-to-force-spring-boot-to-use-tomcat-server-in-integration-tests
