### ISSUE TITLE
Spring boot does not allow for Absolute paths for server.ssl.key-store when using tomcat 7

### ISSUE THREAD

**Issue by lsamayoa** [spring-projects/spring-boot#5377]
Spring boot does not allow to use absolute paths for ssl certificates because the [AbstractEndpoint][AbstractEndpoint].setKeyStoreFile inside tomcat does a relative path adjustment and since we never send the raw path, it will always do the adjustment (we send the url of the file so it will always begin with the protocol, file: in my case because of this [line][Bug Line]).
This is because of this specific line, where we turn the filepath given into a url [Bug Line][Bug Line].

[Bug Line]: https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/embedded/tomcat/TomcatEmbeddedServletContainerFactory.java#L343
[AbstractEndpoint]: https://searchcode.com/codesearch/view/36485209/

**Comment by lsamayoa** [comment]
This is only true for Tomcat 7.

**Comment by wilkinsona** [comment]
What version of Tomcat 7 are you using? I believe you may need 7.0.66 or later.

**Comment by lsamayoa** [comment]
You are correct. I was using version 7.0.55.
Version 7.0.65 still have that relative path check.
Version 7.0.66 of tomcat does not contain that line.

**Comment by rvijaykumar** [comment]
Could anyone suggest, am getting the similar issue with Tomcat.

SEVERE: Failed to load keystore type JKS with path /tmp/tomcat.5161001577291191019.9091/file:/tmp/tmp.Qjqu0t4Sof/key.p12 due to /tmp/tomcat.5161001577291191019.9091/file:/tmp/tmp.Qjqu0t4Sof/key.p12 (No such file or directory)

The boot strap script set a temp location for the key.p12 file at /tmp/tmp.Qjqu0t4Sof/key.p12. But for some reason tomcat is looking  here /tmp/tomcat.5161001577291191019.9091/file:/tmp/tmp.Qjqu0t4Sof/key.p12 

Am using <tomcat.version>8.0.33</tomcat.version> with Spring boot 1.3.5

It fails only during Resource lookup. If i use the FileInputStream it works fine.

**Comment by snicoll** [comment]
@rvijaykumar this issue is closed and we don't use the tracker for questions. Please ask them on StackOverflow or join us on Gitter.
