### ISSUE TITLE
when deployed Spring Boot war in tomcat where should application.yml file should be placed?

### ISSUE THREAD

**Issue by talasila66** [spring-projects/spring-boot#5387]
When using spring boot, mvc war file has been build and deployed in stand alone tomcat.Curretly application.yml is located at $CATALINA_HOME/webapps/demo/WEB-INF/classes/application.yml

Can I move the same to $CATALINA_HOME/conf/Catalina/localhost/dmo.yml ?

In general without using spring boot my configuration file will be located at $CATALINA_HOME/webapps/demo/META-INF/context.xml which can be moved to $CATALINA_HOME/conf/Catalina/localhost/demo.xml

Is the same is possible for application.yml also? Then How?

This will help while re-deploying application war file in tomcat,my config file will be backed-up automatically.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Having said that `spring.config.location` is what you're after, [check the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files)

**Comment by talasila66** [comment]
Thank you I posted the same Thread in stack over flow when deployed Spring Boot war in tomcat where should application.yml file should be placed? waiting for the reply
