### ISSUE TITLE
How to make Spring Boot,Spring Data JPA implement the multi database distributed transaction？

### ISSUE THREAD

**Issue by yuchao86** [spring-projects/spring-boot#5399]
How to make Spring Boot,Spring Data JPA implement the multi database distributed transaction？

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Having said that `spring.config.location` you could start looking at [this sample](https://github.com/snicoll-demos/demo-multi-entity-managers)
