### ISSUE TITLE
Package classes under same package into a single jar, not spererate jars 

### ISSUE THREAD

**Issue by thefallentree** [spring-projects/spring-boot#5420]
Hi,

We are using gradle multiple projects layout, and also using spring-boot plugin to generate final deployable jar files.

However, spring is packing all the subprojects into a individual jar inside the main application jar, which seems unnecessary, is there anyway to tell spring-boot to *flatten* classes in direct subprojects (not the external dependencies because there sure can be issues) into the main jar?

Thanks

**Comment by snicoll** [comment]
>  which seems unnecessary

Why is that? What is the problem exactly?

**Comment by spencergibb** [comment]
The boot team spent a ton of effort to **not** flatten the jar because of the problems that causes.

**Comment by thefallentree** [comment]
as I stated, we merely want to flatten classes under our own namespace, which we would love to use this as a tool to expose and solve subtle conflict (all that flatten can expose) in the compile phase, not through runtime

**Comment by thefallentree** [comment]
Also, what is the story of merging resources between multiple jar? It is very unsettling when we found that apparently spring resources can be load across jars. How would it solve merge conflict?

**Comment by snicoll** [comment]
What conflict are you talking about? It's up to you to have the same resource in different modules and you'll have to manage that conflict in the "flatten" phase anyway. I really don't see what that would bring.

**Comment by thefallentree** [comment]
That's what I was talking about,  flatten process solve the conflict early,
while current jar in jar approach will leave that to runtime behavior
changes.  Which is not really a "conflict solving" issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by thefallentree** [comment]
@snicoll What feedback do you require from me?

**Comment by snicoll** [comment]
I honestly don't understand the problem. 

> there sure can be issues

Which ones? So far you haven't shown any. It would be nice to understand the problem you're trying to solve rather than asking for a technical change. Maybe we could offer a better alternative or confirm that Spring Boot shouldn't be doing it. It would make this issue evolve in one way or the other.

**Comment by wilkinsona** [comment]
@thefallentree If you want to package all of your own code into a single jar, you should structure your Gradle projects accordingly. For example, you could create an aggregator project that combines all of your subprojects into a single jar and then have you project that uses the Boot plugin to create the deployable jar depend on the aggregator project rather than the individual subprojects.

**Comment by philwebb** [comment]
I'm closing this issues since I don't see any obvious changes that we should make in Spring Boot. The current solution appears to be working well for most people and anything more exotic really falls under the realm of the build tool.

As @wilkinsona mentions above there are certainly things that you can to with Gradle here.

**Comment by thefallentree** [comment]
@wilkinsona <https://github.com/wilkinsona> can you give some concrete
example on this aggregration task of gradle? Could this be something to do
with the Jar task? Leaf project could have a jar task that somehow combine
all dependent projects outputs?

**Comment by wilkinsona** [comment]
@thefallentree Sorry, I don't have such an example to hand. It's really a Gradle question rather than being anything that's specific to Spring Boot.
