### ISSUE TITLE
Using repositories with Spring Batch does not commit save() statements

### ISSUE THREAD

**Issue by markash** [spring-projects/spring-boot#5428]
Good day,

I am trying to re-use my repositories written as part of a core module in a batch module in a multi-module maven Spring Boot project. No matter what I do, the Repository.save() methods do not commit the changes to the database.

Is there a way to overcome this or must I re-configure the database connection and re-write the JPA entities in the batch module?

Kind regards,
Mark P Ashworth

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
