### ISSUE TITLE
Get org.hibernate.LazyInitializationException in integration test

### ISSUE THREAD

**Issue by SlimFancy** [spring-projects/spring-boot#5436]
I'm trying to write integration test for Spring Boot application. I have `Product` and `GalleryImage` domain model. They are in one-to-many relationship.

```
public class Product {
    ......
    @OneToMany(mappedBy = "product")
    private List<GalleryImage> galleryImages;
    ......
}
```

I have a integration test as below:

```
    @Test
    public void testProductAndGalleryImageRelationShip() throws Exception {
        Product product = productRepository.findOne(1L);
        List<GalleryImage> galleryImages = product.getGalleryImages();
        assertEquals(1, galleryImages.size());
    }
```

However, this test gives me a `LazyInitializationException`. I searched on Google and StackOverFlow, it says that the session is closed after `productRepository.findOne(1L)`, since `galleryImages` are lazily loaded, so  `galleryImages.size()` gives me this exception. 

I have tried to add a `@Transactional` annotation on the test, but it's still not working.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
