### ISSUE TITLE
FilePermission exception when running a test

### ISSUE THREAD

**Issue by scampi** [spring-projects/spring-boot#5449]
I want to run a test using the Spring framework. I followed the directions in http://spring.io/guides/tutorials/bookmarks/ for testing my REST service, but I am getting the following error:

```
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "./config/application.properties" "read")
```

**Comment by wilkinsona** [comment]
Can you explain why you think this is a problem with Spring Boot? Without a complete stacktrace, it's impossible to tell how Spring Boot is involved. It looks like you're running in an environment with a security policy that is denying read access to `./config/application.properties`. If so, that's a problem with you environment rather than with Spring Boot.

**Comment by scampi** [comment]
Hello @wilkinsona thanks for replying. I found out today that some code I am depending in my test needed some policy permissions.
Sorry about opening this issue.
