### ISSUE TITLE
maven filter not work in 1.3.3.RELEASE

### ISSUE THREAD

**Issue by wushp** [spring-projects/spring-boot#5456]
demo project:
https://github.com/wushp/examples/tree/spring-boot-ask
------------------------------------------------------------------------------------
my usage:
i want to use the  variable in "src/main/resources/setting-${env}.properties" to replace the variable in "src/main/resources/application.properties"

1.using 1.2.7.RELEASE
i used "mvn clean install -Pprd".it works fine~

2.using 1.2.7.RELEASE
i used "mvn clean install -Pprd".it fails to replace the variable.

please help  sir~

**Comment by wilkinsona** [comment]
You need to use `@` rather than `${}`. This is [described in the release notes for 1.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering).

In the future, please use Stack Overflow for this sort of question (you can use the `spring-boot` tag). We prefer to keep GitHub issues for bugs and enhancements.

**Comment by wushp** [comment]
SORRY~
