### ISSUE TITLE
Migrating from 1.2.7 to 1.3.0 changes the loading order of application.properties

### ISSUE THREAD

**Issue by mishadoff** [spring-projects/spring-boot#5495]
We migrated from spring-boot 1.2.7.RELEASE to 1.3.0.RELEASE what caused changing loading order for `application.properties` file. 

Here is minimal project to reproduce the issue https://github.com/mishadoff/spring-boot-properties-order
and here is a small prelude how we using that:

It is multipom project, which basically has two components: framework and plugins. We package each dependency to framework and use plugin jars as pluggable via loader_path options, so for example to start framework we run

```
java -Dloader.path=plugins/a/target/a-0.0.1.jar -jar framework/target/framework-0.0.1.jar
```

If we want to run b plugin, we just switch to it and do not rebuild components

```
java -Dloader.path=plugins/b/target/b-0.0.1.jar -jar framework/target/framework-0.0.1.jar
```

Even more, we can plugin a and b together.
Take into account, every jar contains its own application.properties file

Now, how to reproduce

1. build a project `mvn clean install` 
2. run it with some plugin `java -Dloader.path=plugins/a/target/a-0.0.1.jar -jar framework/target/framework-0.0.1.jar`
3. go to http://localhost:8080/env, scroll down and check app.name property, it's value "Framework"

Now switch spring boot version in top level pom from 1.2.7 to 1.3.0 and repeat actions above, the value for app.name property is "Plugin A"

We solved this issue, by introducing plugin specific properties files, but probably root cause is deeper.

**Comment by philwebb** [comment]
The root cause of your issue is fix #3048, however, multiple `application.properties` files on the classpath aren't really supported.

If you look at `ConfigFileApplicationListener` you can see that `DEFAULT_SEARCH_LOCATIONS` has a `classpath:` entry and not `classpath*`. The `loadIntoGroup` method calls `Resource resource = this.resourceLoader.getResource(location);` and _only_ deals with a single result.

I think you're best option is the approach you've taken of having plugin specific files rather than trying to subvert the use of `application.properties`.
