### ISSUE TITLE
Authentication for Actuator endpoints is broken when using OAuth2 to protect all the endpoints

### ISSUE THREAD

**Issue by pmvilaca** [spring-projects/spring-boot#5536]
We're facing an issue with Actuator endpoints security configuration.

When the `@EnableResourceServer` is used, somehow the security config for actuator endpoints is broken.

I've discussed this with @dsyer on spring-security-oauth gitter and we tried a few things but we just get it working with a weird workaround. (by injecting a AuthenticationManagerBuilder in a configuration class and add the inMemoryAuthentication with the username and password that we want)

You can find a sample application to reproduce the problem here:

https://github.com/pmvilaca/spring-boot-oauth2-actuator-issues

**Comment by dsyer** [comment]
Clarification: user wants to enable OAuth2 token authentication for all non-actuator endpoints, but keep the actuator behind the standard HTTP basic. You can get most of the way there by setting `management.context-path=/admin` and excluding `/admin/**` from the resource server security configuration. (I think that's what the sample app does.) It falls down though because the right filters are applied, but there is no `AuthenticationProvider` that can validate the user's credentials. Something has switched off the AM configuration in Spring Boot (and only @rwinch will know what that is, and what we can do about it).

**Comment by rwinch** [comment]
@pmvilaca Thanks for the report. @dsyer Thanks for cc'ing me on this.

This is expected behavior from a Spring Security & Spring Boot standpoint. 

Spring Boot ensures that it only is configured if nothing else has configured authentication. This is done by in [DefaultInMemoryUserDetailsManagerConfigurer](https://github.com/spring-projects/spring-boot/blob/v1.3.3.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/AuthenticationManagerConfiguration.java#L165) by checking to see if an other classes have configured security's authentication mechanism.

When Spring Security OAuth is applied the `ResourceServerConfiguration` [adds an AnonymousAuthenticationProvider](https://github.com/spring-projects/spring-security-oauth/blob/2.0.9.RELEASE/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configuration/ResourceServerConfiguration.java#L120) before Spring Boot's `DefaultInMemoryUserDetailsManagerConfigurer` is invoked.

This means that Spring Boot will no longer configure the authentication.

**Comment by pmvilaca** [comment]
Thanks for your explanation @rwinch 

What do you think that will be the best solution for this problem? 

* Assume that this is the expected behaviour and that we need to add the Authentication Provider that is missing?
* Review the actuator security config in order to avoid this (maybe not rely on the spring security auto configuration and configure its own security config)?
* Review the OAuth configuration classes in order to give us the possibility to change the order before any execution of the `ResourceServerConfiguration`

Regarding the last point, I tried to change the order of that configuration class by injecting `ResourceServerConfiguration` in my configuration class and override the order in a PostConstruct method ( @dsyer suggestion) but the `init()` method (the method that is adding the `AnonymousAuthenticationProvider` is executed with the original order (3 -  before executing my PostConstruct method)

```
// Workaround suggested by Dave Syer to get the ManagementWebSecurityAutoConfiguration running before
// ResourceServerConfiguration to avoid breaking the Actuator configuration
@PostConstruct
public void overrideOrderOfResourceServerConfiguration() {
    resourceServerConfiguration.setOrder(ManagementServerProperties.BASIC_AUTH_ORDER + 1);
}
```

**Comment by rwinch** [comment]
@pmvilaca I'm not sure I understand the full context of why Spring Security OAuth is doing what it is. Perhaps @dsyer might elaborate on that.

It might as simple as [removing the global configuration](https://github.com/spring-projects/spring-security-oauth/blob/2.0.9.RELEASE/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configuration/ResourceServerConfiguration.java#L117-L122) and adding the `AnonymousAuthenticationProvider` in [HttpSecurity specific configuration](https://github.com/spring-projects/spring-security-oauth/blob/2.0.9.RELEASE/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configuration/ResourceServerConfiguration.java#L125) which would look something like this:

```java
@Override
protected void configure(HttpSecurity http) throws Exception {
    http.authenticationProvider(new AnonymousAuthenticationProvider("default"));
    ...
}        
```

**Comment by pmvilaca** [comment]
Thanks again @rwinch 

If that works, it looks like a very good solution but you're the best guys to decide on this one. Let's wait for @dsyer feedback

**Comment by philwebb** [comment]
Sounds like this isn't a bug so I'll close for now. Feel free to re-open if needed.

**Comment by PedroAlvarado** [comment]
I applied the changes suggested by @rwinch via a classpath patch with good results. That is, HTTP basic honored for actuator endpoints and OAuth2 token authentication honored for everything else.  See this [gist](https://gist.github.com/PedroAlvarado/1ab59d055046f0506488bb24825f82f4). 

I'd like to request that we consider making this change.

**Comment by dsyer** [comment]
That's a change in spring security oauth, so please raise an issue there. It should be easy to make, but I'm not sure yet why it was implemented the way it was. If I think it was a mistake we can just change it.

**Comment by PedroAlvarado** [comment]
I've opened an issue in spring-security-oauth per the conversation above. @philwebb, at this point it makes sense to close this issue.

**Comment by wilkinsona** [comment]
@PedroAlvarado Thanks.

**Comment by narup** [comment]
This is great, I have a same issue right now. Thanks
