### ISSUE TITLE
Improve Kotlin support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#5537]
Placeholder issue for things we can do to improve Kotlin support
## @Value

Using `@Value("${thing}")` is a pain because you need to escape `$` (e.g. `@Value("\${thing}")`. Perhaps a different key like `@Value("#{thing}")`.
## Open Classes

Open classes are a pain, can we use a classloader to remove `final`.
Also all `@Bean` methods

_perhaps we can use a custom bean classloader_
## Default constructor arguments with `@Autowired`

Give a constructor with a default param:

```
open class Foo @Autowired constructor(val restTemplate: RestOperation = NoOpRestOperation());
```

Kotlin will create multiple constructors, this makes Spring fall over because there's multiple annotated constructors. A method to be smart about which to pick would be nice.
## Main method

`@JvmStatic` is needed for main methods. Check if we can find them automatically. Also the name of the class is a bit mad `ThePackageKt` so perhaps we can replace it with something nice.
## Add Kotlin Module

Look at Jackson for an example.

**Comment by wilkinsona** [comment]
## Gradle plugin

Our plugin applies the Java plugin automatically. That doesn't make sense when you're building a pure Kotlin project and leads to unnecessary noise as the Java-related tasks are still run as part of the build:

```
./gradlew classes
:compileKotlin
:compileJava UP-TO-DATE
:processResources
:classes
```

**Comment by philwebb** [comment]
If looks like `@Value` might already support `#{...}` expressions as an alternative to `${...}`.

**Comment by jkschneider** [comment]
We will want reified extension functions for the `RestOperations` interface. There are probably similar better-typing gains to be made elsewhere.

**Comment by jkschneider** [comment]
## Spring HATEOAS

Extension functions to improve the transformation of objects and collections of objects into `Resource` and `PagedResources`, respectively. Also better link generation for `Resource` and `PagedResources`.

**Comment by sdeleuze** [comment]
Thanks for creating this issue @philwebb 👍, I am especially interested by removing the need for the `open` qualifier.

Maybe we could discuss Monday with the team if they would be ok to automatically register Kotlin Jackson module in `Jackson2ObjectMapperBuilder` if it is in the classpath like we do for various other modules (I could add this to Spring Framework 4.3 easily).

@jkschneider Good idea about Spring HATEOAS. Be aware that I also plan to experiment on allowing to specify relations thanks to annotations + regular data classes, see https://github.com/spring-projects/spring-hateoas/issues/401 for more details. Nothing specific to Kotlin, but that will make it easier to deal with data classes in both Kotlin and Java.

**Comment by sdeleuze** [comment]
@philwebb [SPR-14108](https://jira.spring.io/browse/SPR-14108) + [related pull request](https://github.com/spring-projects/spring-framework/pull/1024) for Jackson Kotlin module automatic registration submitted for inclusion in Spring Framework 4.3.

**Comment by sdeleuze** [comment]
I have [just merged](https://github.com/spring-projects/spring-framework/commit/1f9a9cf404e452cf25fbe21931e0b35ef61dff1f) Jackson Kotlin module automatic registration, so it will be available in `4.3.0.RC1` upcoming release tomorrow and then in Spring Boot `1.4`.

About `@Value` I did a quick test some times ago, and I dont remember `#` was supported out of the box as a dropin replacement for `$`, I think only `@Value("#{config['foo']})` and `@Value("\${foo}")` were. That's why I described in [this StackOverflow answer](http://stackoverflow.com/questions/33821043/spring-boot-change-property-placeholder-signifier/33883230#33883230) how to customize `${...}`  to something else. Is there a better solution available out of the box?

About extensions, [Kotlin Primavera](https://github.com/marioariasc/kotlinprimavera) contains some examples of Kotlin extensions applied to Spring (I am sure there a lot of others to imagine even more useful).

I have tried to reproduce the "Default constructor arguments with `@Autowired`" described above in [this test project](https://github.com/sdeleuze/kotlin-autowired-constructor) but did not succeed. Any chance someone send a PR on this test project to show how to reproduce this issue?

You can find bellow some issues from Kotlin bugtracker related to Spring:
 - [Parent issue for Spring Framework support](https://youtrack.jetbrains.com/issue/KT-6380)
 - [Allow specifying array annotation attribute single value without arrayOf()](https://youtrack.jetbrains.com/issue/KT-11235) (target : Kotlin 1.1)
 - [Add quick fix for "Spring @Configuration/@Component annotated classes or @Bean annotated methods should be open"](https://youtrack.jetbrains.com/issue/KT-11098) (fixed)
 - [Callable reference with expression on the left hand side](https://youtrack.jetbrains.com/issue/KT-6947)
 - [Infer type parameter to upper bound when no bounds can be inferred from arguments](https://youtrack.jetbrains.com/issue/KT-11658)
 - [Spring: package name(s) in `AnnotationConfigApplicationContext()` call are not resolved](https://youtrack.jetbrains.com/issue/KT-11658)

**Comment by jkschneider** [comment]
@lkogler - Hadi Hariri suggested you might be interested in this effort.

**Comment by jkschneider** [comment]
@sdeleuze Sent a PR for "Default constructor arguments with `@Autowired`". Adding `required=false` was a valid workaround as of some pre-1.0 release, but no longer works.

Thanks for putting together all of the links!

@philwebb or @sdeleuze if you could create a spring-kotlin project in [spring-projects](https://github.com/spring-projects) and give me commit access, I'll start pouring in the work I have here.

**Comment by sdeleuze** [comment]
@jkschneider As a first step I have created the [`spring-kotlin`](https://github.com/sdeleuze/spring-kotlin) in my own `sdeleuze` account. Maybe we could both of us (and any interested people) contribute anything useful for building Spring + Kotlin applications, including documentation. When the project will be mature enough, we will evaluate moving it to https://github.com/spring-projects.

I already gave you the push rights, please sign the CLA as explained in the README. I will setup the build process using http://build.spring.io and publish the snapshots in https://repo.spring.io/snapshot/ as soon as we have the first bits committed.

Does it sound ok for you?

**Comment by spencergibb** [comment]
@sdeleuze He's signed the CLA for spring cloud previously.

**Comment by jkschneider** [comment]
@sdeleuze thanks, sounds like a plan!

**Comment by nfrankel** [comment]
I'm interested as well, and have just signed (again?) the CLA - just to be sure.

**Comment by sdeleuze** [comment]
Nice :-)

**Comment by jkschneider** [comment]
@sdeleuze Regarding the default finality problem, what do you think about a Lombok-style annotation-processor hack to strip final from the bytecode at annotation-processing time? It isn't ideal in the sense that it requires a plugin (Eclipse) or non-default setting (IntelliJ), but...

Otherwise, I'm not sure where we would put a custom ClassLoader such that all entry points would be covered (main, servlet initialization, test, etc.).

**Comment by sdeleuze** [comment]
Honestly I really would like to avoid using Lombok-style annotation-processor hack, since IMO one of the main Kotlin advantage is to avoid this kind of non standard code that require special support in IDE and build tools.

I would rather try to experiment with custom bean classloaders, reflection and eventually JDK dynamic proxies to see if we can do something here. Only Spring need to extend these classes for technical reasons, the end user code don't have to, so even if I am not a reflection guru, I think it is worth to try that way.

**Comment by cemo** [comment]
@sdeleuze 
:+1:  for
 > avoid using Lombok-style annotation-processor hack

**Comment by wilkinsona** [comment]
Thinking aloud: I wonder if JetBrains would consider an enhancement to Kotlin that allows an annotation to make a class open, perhaps via a meta-annotation?

**Comment by sdeleuze** [comment]
@wilkinsona The question has been forwarded to the Kotlin team at JetBrains

**Comment by mikegehard** [comment]
Thank you all in advance for pushing this stuff forward!

**Comment by sdeleuze** [comment]
@jkschneider I have merged your PR in [kotlin-autowired-constructor](https://github.com/sdeleuze/kotlin-autowired-constructor) to reproduce the issue you described , and indeed I got an error, but an `@Autowired annotation requires at least one argument` one likely because Kotlin generates the default constructor annotated with `@Autowired, and Spring has nothing to autowire on this one so it raises this error.

That said, I am not sure this should be seen as a bug. `@Autowired` purpose it to instantiate constructor parameters, and there is a conflict with Kotlin default constructor arguments that try to do the same. I tend to think that Kotlin default arguments should not be used on `@Autowired` annotated constructors, mixing both is not something I would recommend anyway.

For now, I think I would be in favor to just add some documentation about that behavior (in the [additional tips section of my Kotlin + Spring Boot blog post](https://spring.io/blog/2016/02/15/developing-spring-boot-applications-with-kotlin#additional-tips) for example).

Any thoughts?

**Comment by sdeleuze** [comment]
See [SPR-14165](https://jira.spring.io/browse/SPR-14165) about supporting Kotlin nullable information in Spring MVC.

**Comment by sdeleuze** [comment]
I have created an issue on Kotlin bugtracker to find a workaround to the annoying mandatory `open` qualifier for `@Service` , `@Repository` , `@Bean`  and `@Configuration` classes and methods. Feel free to vote for it and add your comments. https://youtrack.jetbrains.com/issue/KT-12149

**Comment by wendigo** [comment]
Is this really a problem? We've been developing Spring Boot applications on top of Kotlin for a couple of months and we've just adjusted :) Changing this behaviour right now, after 1.0.0 was released is not really a good idea.

**Comment by sdeleuze** [comment]
I think exposing such technical detail to the user is a real issue at least for me, it gives a feeling that using Spring + Kotlin is not "natural" IMO. In any case, if we find a solution it won't break your application, it will just make Spring + Kotlin working without `open` and allow you to have less verbose code if you want to.

**Comment by jkschneider** [comment]
@sdeleuze If you haven't already, you can read through the long [discussion here](https://discuss.kotlinlang.org/t/classes-final-by-default/166?page=2) on the Kotlin forums. Eventually, Andrey Breslav answered with a [blog post](https://discuss.kotlinlang.org/t/a-bit-about-picking-defaults/1418) on it that outlined why it is unlikely to change on their side. In spite of the great points he makes here, I think there is virtually no risk to opening classes and methods we know need to be open after an initial pass of the Kotlin compiler.

**Comment by sdeleuze** [comment]
As discussed on Kotlin Slack, I have made some experiments about using `spring-aspect` and/or AspectJ ([see this branch](https://github.com/sdeleuze/geospatial-messenger/commit/894758a83b29c08a167fe52bc2aa2ef75b37dd2a)), but it seems that this approach can't be used everywhere (especially on Spring Boot configuration) and has big drawbacks regarding IDE and build tool integrations. That's not something I want to promote as the default solution.

As an alternative, I tried to update my `geospatial-messenger` sample app in order to use interface + JDK dynamic proxies ([see this commit](https://github.com/sdeleuze/geospatial-messenger/commit/ff2e3abe0048e625d5497c47cb89153c4dc1eb5d)) and found the result quite convincing. It removes the need to use `open` on `@Repository` and `@Service` beans. Spring Boot configuration still requires `open` at class and function level, but that's less annoying to me because this is not the core of the app functionalities, and JetBrains seems open to discuss the addition of a `allopen` keyword that could be added on `@Configuration` classes in order to avoid specifying `open` for each function of the class.

Given the price to pay in term of IDE and build tool configuration (the kind of things I hate with lombok) for other solutions, that seems to be a good tradeoff IMO.

For people still wanting to remove `open` on CGLIB proxies, be aware that someone at JetBrains made an experiment with a [Kotlin compiler plugin](https://github.com/yanex/AutoOpen) (no IDEA, Gradle or Maven plugin available) and it seems @jkschneider made some progress in using kapt for doing the similar operation.

**Comment by jkschneider** [comment]
I think I should have been more explicit about what an annotation processor solution would NOT require. Lombok requires manual IDE config because the code it generates needs to be picked up by the IDE for code completion for other source code. The solution here only requires the bytecodes to be modified prior to execution, so would not require similar manual config. As far as the build tool goes, one or more of the Spring Gradle plugins could add the appropriate kapt dependency when necessary.

**Comment by snicoll** [comment]
The annotation processor is pretty transparent indeed and supported properly by the IDE but I wonder to which annotation it would be supposed to react. I haven't used kotlin much myself but it feels to me it is still a lot of setup to workaround a language decision...

**Comment by sdeleuze** [comment]
@snicoll I think the initial idea was to open classes annotated by `@Component ` (directly or transitively).

@jkschneider Good point, indeed bytecode modification is only required for running the app, not compiling it. But I think we should be careful with such bytecode manipulation and limit the scope where it applies.

For example, while that looks like an handy solution for simple apps, what would be the result of such bytecode modification in a multi-module application where you have your `@Repository` and `@Service` classes in another module than your application? I guess the IDE will allow you to extend these classes (since it will use the bytecode not the sources) even if that was not necessarily your intent.

Based on my experiment and your last comment, maybe a good compromise would be to enable such bytecode modification only on `@Configuration` classes (directly or transitively) by default. That would means that `@Configuration` files are `open` by default (since we have not way to avoid that), but let the core of your application (`@Repository` and `@Service`) `final` by default in compliance with Kotlin mindset, and encourage people to use interfaces + JDK dynamic proxy, which I think is a good practice. The plugin could have an option to modify the scope of the modification to allow use specifying `@Component` instead of `@Configuration` if they prefer (I would not recommend that).

Any thoughts?

**Comment by sdeleuze** [comment]
I have created a Spring + Kotlin FAQ : https://github.com/sdeleuze/spring-kotlin/blob/master/README.md#spring--kotlin-faq

@wilkinsona @philwebb Do you think we could do something to avoid the current CGLIB proxies by default behavior as soon as JDBC is used (see https://github.com/sdeleuze/spring-kotlin/blob/master/README.md#where-this-configuration-problem-configuration-class-foo-may-not-be-final-error-message-come-from)?

**Comment by jnizet** [comment]
I started working with Kotlin and Spring-boot for just one week, and the biggest pain point for me, not directly related to Spring-boot, but still, is Mockito. 
Many Mockito matchers (like any()) return null, and that is a problem with null-safe Kotlin arguments. 
I used [mockito-kotlin](https://github.com/nhaarman/mockito-kotlin) to try circumventing these problems, but it's based on Mockito 2.0.52-beta, which is incompatible with the version of Mockito used by Spring-boot.
As a quick workaround, I just used my own adapted version of mockito-kotlin, but that's something I would really want to avoid.

**Comment by sdeleuze** [comment]
Good news, it seems Kotlin team [is going to provide a solution](https://youtrack.jetbrains.com/issue/KT-12149) to allow CGLIB proxies without having to open the class and all its functions.

**Comment by sdeleuze** [comment]
The long awaited solution the the `open` class and functions is now available thanks to the new `kotlin-spring` plugin, see [this blog post](https://blog.jetbrains.com/kotlin/2016/12/kotlin-1-0-6-is-here/) for more details. I have updated https://github.com/sdeleuze/spring-boot-kotlin-demo to use it, and it works well (be sure to have IDEA Kotlin 1.0.6+ plugin to get it working).

I will update http://start.spring.io/ shortly.

**Comment by sdeleuze** [comment]
You can use [this link](https://jira.spring.io/issues/?filter=15463) to track Kotlin related issues in the upcoming Spring Framework 5.0.

**Comment by sdeleuze** [comment]
@wilkinsona @bclozel It seems Spring Boot `TestRestTemplate` can't leverage the Kotlin extensions I added in Spring Framework 5 [RestOperationsExtension](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/kotlin/org/springframework/web/client/RestOperationsExtension.kt) because it does not implement `RestOperations`. Do you think it could implement it in Spring Boot 2.0 or should I contribute a `TestRestTemplateExtension`?

**Comment by snicoll** [comment]
We won't go back implementing `RestOperations` if that's what you're asking. If we want to follow along, we'll probably have a kotlin theme in 2.0 as we'll do whatever is the best option. What is your recommendation?

**Comment by sdeleuze** [comment]
I think just providing a `TestRestTemplateExtension` similar to what I did on [`RestOperationsExtension`]( https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/kotlin/org/springframework/web/client/RestOperationsExtension.kt) would be fine.

**Comment by sdeleuze** [comment]
Following [Spring Framework 5 Kotlin support](https://spring.io/blog/2017/01/04/introducing-kotlin-support-in-spring-framework-5-0) announcement, and after a few weeks developing [a real Spring Boot + Kotlin reactive web application](https://github.com/mix-it/mixit/), I have tried to summarise what features Spring Boot 2.0 could provide to improve Kotlin support:
 - Integrate the great work @bclozel did in [spring-boot-web-reactive](https://github.com/bclozel/spring-boot-web-reactive) especially the `RouterFunction` beans support he recently introduced
 - Support for JUnit 5 to allow using `@BeforeAll` / `@AfterAll` [with non static methods](https://github.com/spring-projects/spring-boot/issues/6402#issuecomment-274432520)
 - [Provide an alternative to @Value("\\${foo}") for Kotlin projects](https://github.com/spring-projects/spring-boot/issues/8061)
 - [Provide TestRestTemplateExtensions for Kotlin projects](https://github.com/spring-projects/spring-boot/issues/8062)

**Comment by sdeleuze** [comment]
Spring Boot 2.0 now provides following Kotlin features:
 - #11235 Kotlin 1.2+ support leveraging Spring Framework 5.1 and Spring Data Kay
 - #11711 Make Boot Gradle plugin setting `kotlin.version` based on `kotlinPluginVersion`
 - #8062 `TestRestTemplate` extension
 - #10511 `runApplication<FooApp>()` top level function
 - #10511 #9486 `kotlin-maven-plugin` plugin management
 - #11716 #10154 #10511 Manage Kotlin dependencies for `kotlin-reflect`, `kotlin-runtime`, `kotlin-stdlib`, `kotlin-stdlib-jdk7`, `kotlin-stdlib-jdk8`, `kotlin-stdlib-jre7`, `kotlin-stdlib-jre8`
 - #7101 Ignore Kotlin annotations when creating test context cache key
 - Junit 5 support to allow using `@BeforeAll` / `@AfterAll` without companion objects
 - **TBD** I will add a last PR before `2.0.0.RC2` with a Spring Boot Kotlin reference documentation.

The only outstanding issue missing is IMO opinion #8762 the `@ConfigurationProperties` binding for immutable Kotlin classes, it is likely too late now for inclusion in 2.0 but it would be a very nice feature to support in Spring Boot 2.1, I still plan to provide a PR for that. #10712 Null-safety annotation on Spring Boot APIs would also be a good fit for 2.1.

On [start.spring.io](http://start.spring.io/) side a lot of work has been done with @snicoll for Kotlin support:
 - Support for Kotlin 1.2 for Gradle and Maven projects
 - Link with Kotlin pre-selected via https://start.spring.io/#!language=kotlin 
 - `-Xjsr305=strict` compiler flag
 - Java 8 bytecode generation
 - `kotlin-reflect` and `kotlin-stdlib-jdk8` dependencies
 - `kotlin-spring` plugin enabled
 - Add version range support for Kotlin version

The remaining outstanding issue needed before Spring Boot 2.0 release from my POV is the lack of `jackson-module-kotlin` dependency for web projects (see #11133 for history of this tricky topic) which makes JSON REST webservices broken out of the box. We print messages in logs at startup and this will be mentioned in the documentation, but not including it in generated project is something that really puzzles me. I will discuss that with @snicoll and @wilkinsona.

After all the work done for Spring Boot 2.0, and given the fact that missing features have their own issues, maybe we should close this general purpose issue?

**Comment by philwebb** [comment]
Thanks for the summary @sdeleuze, I'll close this one.
