### ISSUE TITLE
Using multiple embedded databases requires a lot of manual configuration exclusions

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#5541]
If multiple embedded `DataSources` are declared, one needs to explicitly disable the `DataSourceAutoConfiguration` and `DataSourceTransactionManagerAutoConfiguration` as can be seen [here](https://github.com/spring-projects/spring-data-examples/blob/master/jpa/multiple-datasources/src/main/java/example/springdata/jpa/multipleds/Application.java#L41). They fail as they rely on unique `DataSource` instances to be present.

Can we let the simply opt out of being applied if multiple `DataSource`s are present?

**Comment by wilkinsona** [comment]
> on needs to explicitly disable the DataSourceAutoConfiguration and DataSourceTransactionManagerAutoConfiguration as can be seen here

AFAIK, that isn't strictly accurate. You can use multiple datasources as long as one of them is marked as `@Primary` without excluding either `DataSourceAutoConfiguration` or `DataSourceTransactionManagerAutoConfiguration`. You can see this in action in @snicoll's [demon application](https://github.com/snicoll-demos/demo-multi-entity-managers).

That said, I expected this to be further improved by #2784 so that you could choose not to have a primary datasource and everything that worked with a single datasource would back off. That's not the case, though. @snicoll did you discover something that meant that using `@ConditionalOnSingleCandidate` wouldn't work in `DataSourceTransactionManagerAutoConfiguration`?

**Comment by olivergierke** [comment]
I see. The point here is that making one `DataSource` the primary one can be a source of errors as you could `@Transactional` (without an explicit qualifier) by accident and thus run transactions on the "wrong" one. In the scenario I have here, both `DataSources` should be treated equally and not referring to one explicitly is rather considered an error.
