### ISSUE TITLE
Review class names, particularly those related to testing

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5562]
From @olivergierke:

> Plus, I am starting to get lost in `@SpringBootApplication`, `@SpringBootConfiguration`, `@SpringApplicationConfiguration`, `@ContextConfiguration` and `@SpringApplicationTest`.

@dsyer and I discussed this a bit on Slack

- `@SpringBootApplication` and `@SpringBootConfiguration` – explained nicely by their javadoc in my opinion
- `@SpringApplicationConfiguration` – we both thought this might better named `@SpringApplicationTestConfiguration`
- `@ContextConfiguration` – not much we can do about this as it's a Spring Framework class, but we both think the name is unfortunate as it's not clear that it's related to testing without seeing the FQCN

Some other classes that Ollie didn't mention:

- `SpringApplicationContextLoader` – similarly, this might be better named `SpringApplicationTestContextLoader`
- `@IntegrationTest` and `WebIntegrationTest` – deprecated in favour of `SpringApplicationTest` so will stop adding to any confusion in the future

**Comment by philwebb** [comment]
We can't change `@SpringBootApplication` since it's so widely used. We could perhaps drop `@SpringBootConfiguration` and only support auto-find of `@SpringBootApplication`. I'm not totally convinced that's a good idea.

`SpringApplicationConfiguration` was named for parity with `@ContextConfiguration`. I agree it's pretty confusing and I'd like to test the work `Test` into it. What about `SpringApplicationTestConfiguration`?

**Comment by philwebb** [comment]
Another option might be to just drop `@SpringApplicationConfiguration` and recommend `@SpringApplicationTest` in combination with `@ContextConfiguration`.

**Comment by wilkinsona** [comment]
> What about `SpringApplicationTestConfiguration`

+1. That's what Dave and I came up with too

**Comment by philwebb** [comment]
I've made a few refinements.
