### ISSUE TITLE
Bind controller params to a command object bean

### ISSUE THREAD

**Issue by anthofo** [spring-projects/spring-boot#5567]
Given the following code : 

```
@RestController
class MyController {
     @RequestMapping(...)
     public void test(Container container) { ... }
}

class Container {
    String val;
}
```

I cannot bind request params directly to a bean : 
`http://.../myController?container.val=foo` or `http://.../myController?val=foo` does not work (val is null)

With spring MVC we should be able to bind params to a command objects if I'm right ?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
