### ISSUE TITLE
How to run Sprint Boot app that has `bootRepackage.enabled = false` #5564

### ISSUE THREAD

**Issue by paulvi** [spring-projects/spring-boot#5589]
How to run Sprint Boot app that has `bootRepackage.enabled = false` #5564

For current code at https://github.com/szjug/monolith the resulted shadow jar is like

`bootRepackage` is actually building jar with nested jar, isn't it? And there is no other provided build option inside spring-boot-gradle-plugin.

![spring-boot-shadow](https://cloud.githubusercontent.com/assets/1614482/14280025/c28c8b26-fb62-11e5-93ac-43ddf29f7819.PNG)

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
