### ISSUE TITLE
Replace FixedWindowRollingPolicy in file-appender.xml

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-boot#5590]
The base logging file `file-appender.xml` uses the `FixedWindowRollingPolicy`. I have [read on the JIRA of logback](http://jira.qos.ch/browse/LOGBACK-266?focusedCommentId=13299&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13299) that it probably should be considered deprecated and replaced by `SizeAndTimeBasedFNATP`

**Comment by wilkinsona** [comment]
The referenced Logback issue says:

> I am tempted to mark FixedWindowRollingPolicy as deprecated by [1] and move on. Is there a use case covered by FixedWindowRollingPolicy and not SizeAndTimeBasedFNATP? I should ask on the mailing list. I'll post a message on the logback-user list asking for user opinion.

I'm not sure that this temptation ever came to anything. As of 1.1.7, the documentation still describes `FixedWindowRollingPolicy` with no mention of it being deprecated. This class itself isn't deprecated either. Note that this doesn't mean that we shouldn't move to `SizeAndTimeBasedFNATP` but we'll need a reason other than deprecation for doing so.

**Comment by wimdeblauwe** [comment]
http://logback.10977.n7.nabble.com/Is-FixedWindowRollingPolicy-useful-to-anyone-td12033.html also has a comment that:

> SizeAndTimeBasedFNATP should be used in preference to FixedWindowRollingPolicy.

**Comment by bedag-moo** [comment]
The problem with the FindexWindowRollingPolicy is that, for performance reasons, it enforces an upper limit for the number of logfiles. The default limit is 7 files, and this limit can not be increased beyond 20 without subclassing. If the size of logs exceeds this limit, old logfiles are deleted.

That is, Spring Boot's default file logging configuration will keep 80 MB logs, and deletes everything older than that. This seems an unexpected and dangerous default, even more so because the Spring Boot reference manual does not mention this behavior. 

(It is entirely reasonable for Spring Boot to support limiting the size of log files, but I don't think it should do so by default)

**Comment by wilkinsona** [comment]
We don't have any plans to change this, however we'd consider merging a pull request if someone would like to contribute something.

**Comment by philwebb** [comment]
Closing in favor of PR #6352
