### ISSUE TITLE
Streamline support for Flyway and Liquibase with @DataJpaTest

### ISSUE THREAD

**Issue by rburgst** [spring-projects/spring-boot#5716]
Currently it is not clear how a `@DataJpaTest` can be configured to also apply liquibase migrations. We are building our database with Liquibase and therefore, the migrations are necessary to have a correct DB schema. 
A search through the documentation (and google) didn't initially bring anything up.

**Comment by wilkinsona** [comment]
I was going to suggest, as a temporary measure at least, that you use `@ImportAutoConfiguration` on a nested `@TestConfiguration` class to pull in `LiquibaseAutoConfiguration`:

```
@TestConfiguration
@ImportAutoConfiguration(LiquibaseAutoConfiguration.class)
static class Foo {

}
```

However, that doesn't work as the `DataSource` created by `@DataJpaTest` isn't available in the context when the auto-configuration's conditions are being evaluated so it doesn't match:

```
LiquibaseAutoConfiguration did not match
   - @ConditionalOnClass classes found: liquibase.integration.spring.SpringLiquibase (OnClassCondition)
   - matched (OnPropertyCondition)
   - @ConditionalOnBean (types: javax.sql.DataSource; SearchStrategy: all) found no beans (OnBeanCondition)
```

I believe that is happening because multiple `@ImportAutoConfiguration` annotations are involved, but each is considered in isolation. This leads to the configuration being applied in the wrong order, specifically `LiquibaseAutoConfiguration` is being processed before the test `DataSource` has been auto-configured.

**Comment by wilkinsona** [comment]
You can annotated the test class with `@ImportAutoConfiguration(LiquibaseAutoConfiguration.class)`, for example:

```java
@RunWith(SpringRunner.class)
@DataJpaTest
@ImportAutoConfiguration(LiquibaseAutoConfiguration.class)
public class SomeDataJpaTests {

}
```

This works because all of the `@ImportAutoConfiguration` annotations are, directly or indirectly, on `SomeDataJpaTests` so they're considered as a whole and the ordering is correct.

I think we should consider importing `LiquibaseAutoConfiguration` automatically or providing an option on `@AutoConfigureTestDatabase` to run database migrations with Flyway or Liquibase.

**Comment by rburgst** [comment]
Thanks the 

```
@DataJpaTest
@ImportAutoConfiguration(LiquibaseAutoConfiguration.class)
```

did the trick!

**Comment by snicoll** [comment]
```
@DataJpaTest
@ImportAutoConfiguration(FlywayAutoConfiguration.class)
``` 

worked for me as well (with regards to #5766)
