### ISSUE TITLE
RFC 6902 style patch operation not working anymore

### ISSUE THREAD

**Issue by florind** [spring-projects/spring-boot#5742]
I have just upgraded from 1.4.0.M1 to 1.4.0.M2 and I noticed that the RFC6902 style patch operations don't seem to work for me anymore. I'm getting now

> Could not read an object... nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1034E:(pos 0): A problem occurred whilst attempting to set the property 'payment': Type conversion failure

The data structure like this:

```
@Data
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonIgnoreProperties(ignoreUnknown = true)
@EntityListeners(AuditingEntityListener.class)
@Entity(name = "POLICY_BUNDLE")
@NoArgsConstructor
public class PolicyBundle  implements Identifiable<Long> {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Embedded
    @Valid private Payment payment;

    @Embeddable @Data
    public static class Payment {
        public enum PaymentFrequency {Monthly, Quarterly, Yearly}
        @NotNull private String price;
        @NotNull private PaymentFrequency frequency;
    }
}
```

and the PATCH operation is
```
[
    {"op":"add","path":"/payment","value":{"price":"EUR 19.00","frequency":"Monthly"}}
]
```

Now I am seeing that `org.springframework.expression.spel.support.StandardTypeConverter::convertValue` catches a ConversionException with message `org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.domain.policy.PolicyBundle] to type [@javax.persistence.Embedded @javax.validation.Valid com.domain.policy.PolicyBundle$Payment]` and rethrows a SpelEvaluationException that bubbles up eventually into the error above.
This could be indirectly related to the Spring Data REST project though...

**Comment by wilkinsona** [comment]
@flordind A few things have changed between Boot M1 and M2, notably Spring Data Hopper M1 to Spring Data Hopper SR1 and Hibernate 4.3 to Hibernate 5.1, so it's not immediately obvious to me what might be causing this. Can you please provide a small sample project that illustrates the problem so that we can track it down?

**Comment by florind** [comment]
@wilkinsona there you go: https://github.com/florind/spring-boot-rfc6902

**Comment by wilkinsona** [comment]
@florind Thanks. The test also fails with Spring Boot M1 and Spring Data Hopper SR1 so it would appear  to be a regression in Spring Data REST that was introduced between Hopper M1 and Hopper SR1. Can you please raise a [DATAREST issue](https://jira.spring.io/browse/DATAREST) so that the Spring Data team can investigate?

**Comment by florind** [comment]
Opened https://jira.spring.io/browse/DATAREST-813.

**Comment by wilkinsona** [comment]
Thanks. I'm going to close, for now at least. If it turns out that something needs to change in Boot we can re-open this issue.
