### ISSUE TITLE
Property binding and @autowired not working

### ISSUE THREAD

**Issue by ByteFlinger** [spring-projects/spring-boot#5743]
I am trying to create a spring-boot app to talk to an ldap server using spring-ldap however I have run into an issue in which my property bindings are not taking effect.

I went ahead and created a project which more or less reproduces the issue, it can be found here https://github.com/ByteFlinger/boot-binding-issue

If you compile the project and run in the following manner

java -jar build/libs/binding-issue-0.0.1-SNAPSHOT.jar --issue.url="hello" --issue.userDn="value" --operation1

You can see that the userdn value is printed as null when it creates the bean and you get a NPE when you try to access the autowired service.

In my case I actually have a few ApplicationRunner, all wired in the same manner and some work fine while others will cause this issue. I also noticed that if I move all of them under a sub package, the ones that were working before stop working.

Given that some will work while others not I don't quite see where I am making a mistake somewhere.

**Comment by wilkinsona** [comment]
This is a bit complicated, but the root cause of the problem is that you are using `@ConfigurationProperties` on your `SpringApplication` `@Configuration` class and that class declares a `TransactionProxyFactoryBean`.

When configuration properties are first processed, a conversion service is created. Part of creating this conversion service is to look for `Converter` implementations in the context that have been annotated with `@ConfigurationPropertiesBinding`.  To find all the converters, all of the configured bean definitions are examined. `TransactionProxyFactory` bean is problematic as it needs to be created to determine what type of bean it will return. There's then a chain of bean creation which goes `proxyFactoryBean -> otherService -> service -> contextSource`. When `contextSource()` is called, `userDn` is `null` as all of this is happening before configuration properties are processed and injected.

Using `@ConfigurationProperties` on a `@Configuration` class is very unusual and isn't recommended. Configuration properties classes are intended to be POJOs that provide a type-safe way of accessing configuration. I'd recommend moving the properties out into a new `IssueProperties` class and then injecting an instance of `IssueProperties` into `SpringApplication`. You should also annotated `SpringApplication` with `@EnableConfigurationProperties(IssueProperties.class)`.
