### ISSUE TITLE
MimeMappings is missing entry for .ICO (useful for favicon.ico)

### ISSUE THREAD

**Issue by philippn** [spring-projects/spring-boot#5764]
Hi there,

I noticed that in Chrome when I'm accessing the favicon.ico directly, it just shows some gibberish (i.e. the encoded data) instead of the icon.

After tracking this down a bit, I have found that this is probably due to the content-type header not being set. It can be fixed using

    @Component
    public class MyEmbeddedServletContainerCustomizer implements EmbeddedServletContainerCustomizer {

	/* (non-Javadoc)
	 * @see org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizer#customize(org.springframework.boot.context.embedded.ConfigurableEmbeddedServletContainer)
	 */
	@Override
	public void customize(ConfigurableEmbeddedServletContainer container) {
		MimeMappings mappings = new MimeMappings(MimeMappings.DEFAULT);
		mappings.add("ico", "image/vnd.microsoft.icon");
		container.setMimeMappings(mappings);
	}
    }

It would be useful if this was added to the default MimeMappings though. Thanks in advance!

**Comment by philippn** [comment]
It should be noted that there seems to be some confusion about the actual media type to use (image/x-icon vs. image/vnd.microsoft.icon).

See also http://stackoverflow.com/questions/1444975/if-i-serve-favicon-ico-as-image-vnd-microsoft-icon-instead-of-image-x-icon-wi

**Comment by wilkinsona** [comment]
The default mime mappings are the union of those that are configured by default on Jetty, Tomcat, and Undertow. None of those have a mapping for `.ico`, so Boot doesn't have one either.

Not saying that we can't add one, but that's the rationale for it not being there at the moment.

**Comment by philippn** [comment]
I have further investigated the question which mime type is correct. And it seems there is no definite answer on that one, so as far as I'm concerned this issue can be closed.

**Comment by wilkinsona** [comment]
Thanks for following up

**Comment by naumanshah03** [comment]
Apologize bumping up this issue.

I'm looking to apply Mimetype for **favicon.ico** (i.e .ico extension) as **image/x-icon**. What could be the right approach to doing it?

**Comment by wilkinsona** [comment]
@naumanshah03 There's an example in the [description of this issue](https://github.com/spring-projects/spring-boot/issues/5764#issue-150094428). It's for Spring Boot 1.x. For 2.x, you'd use a `WebServerFactoryCustomizer<ConfigurableServletWebServerFactory>` rather than an `EmbeddedServletContainerCustomizer`.

If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
