### ISSUE TITLE
Hybrid Mobile App using Spring Social displays Whitelabel Error Page

### ISSUE THREAD

**Issue by gibrancastillo** [spring-projects/spring-boot#5769]
I developed a hybrid mobile app using the ionic framework (AngularJS, Apache Cordova, Nodejs, etc). When I deploy or run the hybrid app in a mobile device (android or iOS) via ionic view and I do Facebook aggregation, everything works on the backend but the app (front-end) does not send referer attribute in the HTTP Header.
The front-end after successfully doing Facebook Login and getting OAuth2 toke displays a white page that says: Whitelable Error Page This application has no explicit mapping for /error, so you are receiving this as a fall back.
There is some security around that, not sure what yet, but that is the reason the Facebook Spring Social code in my backend (a java .jar file running on Spring Boot) does not redirect back to AngularJS API in mobile device (front end) is failing.
I was reading here https://spring.io/guides/tutorials/spring-boot-oauth2/ but this is for a Web App using Spring Social. I am using Spring Social in a hybrid app. Any idea on how I can resolved this issue? To make the referer attribute dynamic and to be send in the HTTP Header?
I follow the instructions here https://spring.io/…/2013/11/01/exception-handling-in-spring…
I added to my application.properties file 
server.error.whitelabel.enabled=false
and in Facebook app --> Settings --> Advance tab --> Valid OAuth redirect URIs
I enter
http://<IPaddress> 
http://<IPaddress>/callback
http://<IPaddress>/fb/callback
http://<IPaddress>:8080/fb/callback
but now I get the same Whitelable Error Page This application has no explicit mapping for /error, so you are receiving this as a fall back. randomly
Any ideas?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by gibrancastillo** [comment]
I will
