### ISSUE TITLE
devtools: liveReload is disabled if auto restart is disabled

### ISSUE THREAD

**Issue by wiwiwa** [spring-projects/spring-boot#5770]
I need livereload, but I don't need auto restart. So I disabled auto restart in `application.yaml` with `spring.devtools.restart.enabled=false`.

With this property,  Bean `classPathFileSystemWatcher` won't be created. So no files is scanned.

Tested on spring boot v1.3.1

Hope a fix.

Thanks.

**Comment by wilkinsona** [comment]
Rather than switching off restart entirely, you should exclude the paths from triggering a restart. This will still allow the to trigger a live reload. Please refer to the [documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart-exclude) for further details.

**Comment by wiwiwa** [comment]
ok, thanks for your advise

**Comment by metyl** [comment]
I face the same issue, so the question is how to **disable** auto **restart** (default VM HotSwapping is enough for me) but **keep reload** with LiveReload working or in other words, how to manually configure dev tools the same way as it is done for JRebel or Spring Loaded.

**Comment by wilkinsona** [comment]
@metyl The link in [my comment above](https://github.com/spring-projects/spring-boot/issues/5770#issuecomment-213424753) explains how to do that. If you have further questions please ask on Stack Overflow or Gitter.
