### ISSUE TITLE
Use @ResponseStatus to set response status in error controller

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#5774]
See https://jira.spring.io/browse/SPR-14203

Suggestion from @rstoyanchev:

> what about checking what the current response status is? If it is 200, 500 (or not set) look for an `@ResponseStatus` annotation

**Comment by rstoyanchev** [comment]
After some more thought, some questions came up, so let me experiment a little and I will report here.

**Comment by rstoyanchev** [comment]
Everything works fine with `@ResponseStatus` annotated exceptions. `DefaultErrorAttributes` is also a `HandlerExceptionResolver` at highest priority and it saves the exception in a request attribute.

However if the exception is not annotated there is no easy way to associate it with a status code it seems and combine that with Boot's error details.

You might think about an `@ExceptionHandler` that sets the response status either through a `ResponseEntity` or an `@ResponseStatus` on the exception handler method but that won't give you error details because something needs to call `response.sendError`, not just send the response status. 

In 4.2. we tried to change how `ResponseStatusExceptionResolver` works in this regard and had to revert it, see discussion under #3623.

So I see a few options: 1) we document that an `@ExceptionHandler` method can call response#sendError, 2) we find some way to express it (e.g. by through an HttpStatus return value), or 3) we provide some way to associate Exception types with status codes in Boot.

The challenge with 2) is a confusing array of options between with ResponseEntity and `@ResponseStatus` on the method (which simply set the status) vs returning HttpStatus which would result in a call to sendError.

So currently I lean towards 1) or more likely 3) but may be there are other ideas. Another reason for leaning towards 3) is that the goal is specifically to use Boot's error handling mechanism and that's when this customization is needed.

**Comment by philwebb** [comment]
See also #2691

**Comment by philwebb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
