### ISSUE TITLE
@WebMvcTest does not work with Thymeleaf views

### ISSUE THREAD

**Issue by mihkels** [spring-projects/spring-boot#5801]
I used latest Spring Boot 1.4-BUILD-SNAPSHOT and wanted to test controller with @WebMvcTest that returns HTML page. 

```java
@Controller
public class DemoController {

    @RequestMapping("/")
    public String hello() {
        return "index";
    }
}
```

Test for this controller looks similar to this:

```java 
@RunWith(SpringRunner.class)
@WebMvcTest
public class DemoControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    public void openingStartPageReturnsWelcomePage() throws Exception {
        mockMvc.perform(get("/").accept(MediaType.TEXT_HTML_VALUE))
                .andExpect(status().isOk()).andExpect(content().string(Matchers.containsString("Hello World")));
    }
}
```

It seems that it does not work because the view is always empty string when running this test.
I wrote a simple sample application that can be viewed here: [@WebMvcTest problem example](https://github.com/mihkels/webmvctestproblem )

**Comment by roberthunt** [comment]
`@WebMvcTest` is part of the new 'Test Slicing' being introduced in Spring Boot 1.4 and is designed to setup a narrow slice of the application context to make testing single concepts easier. In this case it's setting up the MVC components but not any view layer (which might be by design, you'll have to ask the Spring guys)

You can bring in Thymeleaf quite easily though by adding this to your test:

`@ImportAutoConfiguration(ThymeleafAutoConfiguration.class)`

**Comment by mihkels** [comment]
Thanks tried and worked perfectly. I consider this issue solved.
I think there should be example in documentation with auto configuration import and mention which auto configurations are included by default.
