### ISSUE TITLE
How to setting default transaction timeout (30s)

### ISSUE THREAD

**Issue by hongphu8790** [spring-projects/spring-boot#5846]
I have tested with `@Transaction` by using native query (SELECT... FOR UPDATE SKIP LOCK) but no luck.
After 30s, although does not exit function with `@Transaction` but transaction finished and release lock.

Please help me config default transaction timeout (30s).

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
