### ISSUE TITLE
RestTemplate should (be able to) pass the session along

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-boot#5892]
As spring session enables us to create distributed services that access the session in a single place, it should be easy to pass this session around, so you can make calls to other backend services on behalf of the user.

I have investigated a while and it seems like the best way currently is to use the RestTemplate methods that allow to pass a HttpEntity and set the cookie header yourself like this:

```
HttpHeaders headers = new HttpHeaders();
headers.add("Cookie", "SESSION=" + session);
ResponseEntity<UUID> exchange = restTemplate.exchange(url, HttpMethod.GET,new HttpEntity<Void>(headers), UUID.class);
```

This is error prone because you could easily forget to set the header and it is cumbersome to do this for each call. (The worst thing is to have to use exchange all the time)

So it would be nice to have a Spring-Session enabled RestTemplate that passes the session to the called service if a session exists.

Is that something worth considering? Or am I missing something that makes this easier?

**Comment by wilkinsona** [comment]
@pcornelissen It's an interesting suggestion, but I don't think that Spring Boot is the right place to tackle it. An [issue in the Spring Session repository](https://github.com/spring-projects/spring-session/issues) would be a better place. /cc @rwinch

**Comment by alwaysastudent** [comment]
@pcornelissen - what happened next ?

**Comment by pcornelissen** [comment]
I just added the session ID everywhere where it's necessary, but recently I explored the RequestCallback which you can pass into execute method, which may be a way to have less code duplication, but there is no way to define something on the instance level for every call sadly...
Or you can create your own ClientHttpRequestFactory but no support from spring-session as far as I know.

**Comment by alwaysastudent** [comment]
I wish we had support for header propagation implicitly with `RestTemplate` and `FeignClient` like it has for oauth2  in likes of `OAuth2RestTemplate` and `OAuth2FeignRequestInterceptor`.

In the world of micro services where you deal with a lot of service to service calls, all the services would need to share a particular request context and to behave in a preferred manner (oauth2, i18N, A/B  testing profile etc). What might be an efficient way to achieve this, other than to have every service use some custom code to propagate the some custom headers  ? Since this situation is not specifically related to security, it is not clean to use JWT as a carrier of these information either. Any advise ?

CC @wilkinsona @dsyer
