### ISSUE TITLE
use thymeleaf Messages ERROR in spring-boot-starter-thymeleaf 

### ISSUE THREAD

**Issue by snice** [spring-projects/spring-boot#5927]
in index.html and index.properties
index.html
`<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org"
	xmlns:layout="http://www.ultraq.net.nz/web/thymeleaf/layout">
<head>
<meta charset="UTF-8" />
<title>测试thymeleaf</title>
</head>
<body>
	<p th:text="#{test}">fsd</p>
</body>
</html>`
index.properties
`test=hello`

but after running,as follows
`??test_zh_CN??`

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by njwangchuan** [comment]
hi,i have the same question，and i find the question in 

http://stackoverflow.com/questions/36545667/spring-boot-thymeleaf-not-finding-message-properties.

the answer do not solve my question and quite different from the guideline 

http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#using-texts
