### ISSUE TITLE
disable logback ConsoleAppender in Spring Boot not work

### ISSUE THREAD

**Issue by coffeesweet** [spring-projects/spring-boot#5978]
I want disable logback ConsoleAppender in Spring Boot (1.3.3.RELEASE),but not work, i search in issues and do it same. https://github.com/spring-projects/spring-boot/issues/1612

the "2016-05-17 12:22:57.651  INFO 8892 --- [           main] com.zhangyue.helloworld.App              : ===============================" out in console all the time

Attach :
src: [logtest.zip](https://github.com/spring-projects/spring-boot/files/267413/logtest.zip)

![43216537-8930-408b-b8d5-3568bd4461c8](https://cloud.githubusercontent.com/assets/982472/15311264/89a88f46-1c2b-11e6-8dc2-e7f2662b8d79.jpg)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Your sample project imports `base.xml` which imports `console-appender.xml`. Try importing `defaults.xml` instead.

```
<include resource="org/springframework/boot/logging/logback/defaults.xml" />
```

**Comment by coffeesweet** [comment]
thank you , i will take it to Stack Overflow.

but ,i use <include resource="org/springframework/boot/logging/logback/defaults.xml" /> and not work fine as before.
you can try. 

thank you ! 谢谢！

**Comment by coffeesweet** [comment]
sorry,it's my mistake,i puted the logback.xml into a src-package;
now i put it into classpath root path,it's work fine!

Thank you very much!
