### ISSUE TITLE
Change the default JDBC connection pool to Hikari

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6013]
2.0 gives us an opportunity to re-evaluate the default connection pool. We currently use Tomcat JDBC. That's a bit awkward when a war's deployed to Tomcat (`tomcat-jdbc` is always on the classpath). There's also some evidence that HikariCP performs much better.

**Comment by benelog** [comment]
As you may know, DBCP2 is default connection pool library from Tomcat 8.0.
(
https://tomcat.apache.org/tomcat-8.0-doc/jndi-datasource-examples-howto.html#Database_Connection_Pool_%28DBCP_2%29_Configurations

> The default database connection pool implementation in Apache Tomcat relies on the libraries from the Apache Commons project. The following libraries are used: 
>
> *  Commons DBCP
> *  Commons Pool

)
It is repackaged into `org.apache.tomcat.dbcp.dbcp2`.

I wondering about why tomcat-jdbc is not default connection pool even in Tomcat. The reason can be helpful to the choice of Spring Boot 2.0. I guess that it is because of DBCP2's reliability and stability.

**Comment by brettwooldridge** [comment]
@wilkinsona HikariCP would be honored to become the default pool in sprint-boot.  If any issues turn up in your test suites, please let me know.

**Comment by snicoll** [comment]
@nekperu15739 we don't use the tracker for questions. Please join us on Gitter or ask on stackoverflow (but quickly there is a `spring.datasource.type` property for that).

**Comment by nekperu15739** [comment]
@snicoll  i forgot, without define spring.datasource.type on the app

**Comment by wilkinsona** [comment]
It looks like `DataSourceBuilder` was missed:

```java
private static final String[] DATA_SOURCE_TYPE_NAMES = new String[] {
			"org.apache.tomcat.jdbc.pool.DataSource",
			"com.zaxxer.hikari.HikariDataSource",
			"org.apache.commons.dbcp2.BasicDataSource" };
```

**Comment by nekperu15739** [comment]
I think that magic that comes with DataSourceConfiguration using the conditionals comes with the problem of not have the ability of reorder the pool preference.

**Comment by snicoll** [comment]
Good catch @wilkinsona, thanks!
