### ISSUE TITLE
On `SpringApplication.run()`, the created Spring context is not started

### ISSUE THREAD

**Issue by mbogoevici** [spring-projects/spring-boot#6021]
The current behaviour is illustrated by the example here:

https://github.com/mbogoevici/gh-issues/tree/master/auto-start-test

By running the example, it can be observed that the bean `SimpleLifecycle` which is a `Lifecycle` bean is not started by default. This is because `SpringApplication.run()` will perform a `refresh()` on the bootstrapped context, but not a `start()`. Calling `start()` explicitly will cause the beans to be started. 

This impacts applications in the following ways:
- applications using `Lifecycle` (but not `SmartLifecycle`) beans will not see them started;
- applications using `SmartLifecycle` beans with `isAutoStartup()` set to false will not see them started either;

A workaround is for application writers to call `start()` explicitly on the created context in the main method, but that would just create boilerplate code.  As discussed with @snicoll, there is a reasonable expectation that all beans would be started by default, but the question that remains to be answered is whether the solution to this belongs to Spring Boot or the Spring Framework itself. One suggestion in that case would be to expand `ConfigurableApplicationContext` with an option  for `isAutoStartup()` - not sure if making it a full `SmartLifecycle` makes sense, in the light of `Phased`, but maybe it does).

Additionally, there are a couple of things that Boot itself could still manage:

- while automatic start may be the default behaviour, there are cases when an application may not want to be automatically started - so Boot can provide a property to control that;
- actuator endpoints for `start` and `stop`, allowing the lifecycle to be managed externally. An example could be a Spring Cloud Stream application that could stop consuming messages temporarily (e.g. in rolling upgrade or scaling scenario) while remaining started - e.g. retaining cached information for data enrichment; generally speaking though, I think that it would be good to be able to start and stop applications externally (more granular control than shutdown)

**Comment by philwebb** [comment]
I think we need input from @jhoeller for this one. AFAICT Spring Boot behaves exactly the same as a regular servlet based Spring application started with a `ContextLoaderListener`.

**Comment by snicoll** [comment]
It was my plan to have a chat with Juergen when he's available. I'll report here when I know more but I agree we're not dong anything special.

**Comment by snicoll** [comment]
The [javadoc of `Lifecycle`](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/Lifecycle.html) has this in **bold**: 

> This interface does not imply specific auto-startup semantics. Consider implementing SmartLifecycle for that purpose.

To answer the elements that you raised:

> applications using Lifecycle (but not SmartLifecycle) beans will not see them started;

This is working as advertized: if you want a bean to start automatically on startup, you **must** implement `SmartLifecycle` and make sure `autoStartup` is `true` (this is the default value)

> applications using SmartLifecycle beans with isAutoStartup() set to false will not see them started either;

You lost me, that's exactly what [the javadoc of `autoStartup` states](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/SmartLifecycle.html#isAutoStartup--). You sound like it is a problem (it isn't IMO).

It got me a few times, but the idea of `start` is that you call it explicitly at the time you want to start the component (and `SmartLifecycle` is a way to let the container do that for you). You also have a callback on the context that **forces** every beans in the context to start. 

> As discussed with @snicoll, there is a reasonable expectation that all beans would be started by default

My take was that I didn't understand the difference between `Lifecycle` and `SmartLifecycle` and I felt (without looking at the code) it was a bit inconsistent. So I got caught one more time, what can I say? It's not ok that all beans would be started by default, what's the point of `isAutoStartup` then?

Let's take another example: let's say that you have a JMS listener and you want to start listening on its destination at a very specific point in time (programmatically). The way to do this (since it's a `SmartLifecycle`) is to set its `autoStartup` flag to `false`. If we changed anything here (or in Spring Framework) that bean would be started as well and that's not what the user want. From that perspective, the change you've made on your side is incorrect as it breaks the semantic of the `autoStartup` flag.

I'd say that the name (`SmartLifecycle`) may be a bit unfortunate because it may feel like a bit "an internal" interface. It isn't.

Conclusions:

* If you want a component to start automatically, implement `SmartLifecycle`. That's what the framework ask you to do. If you have an old component that is using `Lifecycle`, it never was started by default so you need to upgrade it
* If you want to start certain components at a given point of time, `Lifecycle` is exactly what you should be using. If you want it to be configurable, chose `SmartLifecycle` and use the `autoStartup` flag
* It is _not_ okay to call `start()` on the context as it _forces_ all lifecycle beans to be "force" started (including user-defined beans that you are not supposed to touch)

Given the following above, I don't think we should do anything in Boot actually. I am happy to look at the specifics in your project though.

**Comment by mbogoevici** [comment]
Okay, I'm happy to discuss further if you want, as I feel that the discussion is going in the wrong direction - maybe it was my fault of not explaining the issue correctly. I would have been happy to provide some clarification. I didn't complain about how `Lifecycle` or `SmartLifecycle` work, which I understand. 

My point was this: from a pure Spring perspective, everything is working correctly in the example. Unfortunately, I am afraid that for a Spring Boot user that simply executes `new SpringApplication(MyContext.class).run()` it will be not very intuitive that there are beans in their application that they must started manually afterwards. Sure they can call `start()` on the context, but it's not what we show them in tutorials and demos, and goes against the idea that things should be simple. 

I provided an example to show how things are now, which is ok for web apps, but can make things complicated for writers of messaging/integration applications.

My suggestion was to simplify this (by default), by also starting the context - and allowing to disable that behaviour too, if users have strong needs for observing `isAutoStartup()`. Also, providing start/stop actuator endpoints should help in the latter case (it would be a good complement for your JMS example). But, if you disagree, I understand your position.

> It is not okay to call start() on the context as it forces all lifecycle beans to be "force" started (including user-defined beans that you are not supposed to touch)

I don't understand what you mean here. Calling `start()` on a context is the way to signal all `Lifecycle` and `SmartLifecycle` beans that are not `autoStartup` that they can start working. Applications can repeatedly call `start()` and `stop()` on their contexts. I was trying to look for an example in the reference documentation, but I could only find this http://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/htmlsingle/#context-functionality-events - see Table 6.7. 

If you mean that it's not okay to call `start()` indiscriminately like we do now, that much I can agree with, which was my intent with opening the issue. I still believe that this can be simplified for the general case.

**Comment by snicoll** [comment]
>  it will be not very intuitive that there are beans in their application that they must started manually afterwards. 

Well, that's **exactly** what the intended behaviour is. I already provided links to the documentation that explains that. 

> I don't understand what you mean here. Calling start() on a context is the way to signal all Lifecycle and SmartLifecycle beans that are not autoStartup that they can start working.

That's one way to see it but I don't agree with that. The point I was trying to make in my previous comment is that it's not your call to make. You shouldn't force "all SmartLifecycle beans that are not autoStartup that they can start working". Because you don't know all of them and you can't figure out if that's an appropriate time to do so. I am sure that for your use cases you have a set of well-defined beans that should start processing when the application starts, so make sure it is a `SmartLifecycle` and if you can't do that, define a `SmartLifecyle` infrastructure of some kind that will start them. 

If you still disagree, let's have a conversation offline and report the outcome here.

**Comment by mbogoevici** [comment]
> If you still disagree, let's have a conversation offline and report the outcome here.

Yes and yes :)

**Comment by jhoeller** [comment]
Let me second Stéphane's comments here: `Lifecycle` is only really a general uniform signature, not implying a startup contract with the container. `SmartLifecycle` can ask for an auto-startup signal, so any component wanting to receive such a signal should simply implement that extended interface. Regular `Lifecycle` beans can auto-start in other callbacks such as `afterPropertiesSet` or `afterSingletonsInstantiated` or in an event, or simply wait for manual start signals. A general Spring `ApplicationContext` does not rule into this through enforcing an early `start` on `refresh`. Now, a Spring Boot application or other special kind of Spring application may automatically trigger `start` after `refresh` in its own bootstrap logic... but I'd really rather recommend for all such beans to implement `SmartLifecycle` which also supports a startup phase and a lazily completing stop operation.

**Comment by mbogoevici** [comment]
Thanks for weighing in.

Based on the follow up with Stephane, and Juergen's comment, I agree with the conclusion here is that on a `SpringApplication.run()` only `SmartLifecycle` beans will be started (which is the expected outcome of a `refresh()`) - and everything else should be left to the application developer.
