### ISSUE TITLE
messages.properties not working with mustache template 

### ISSUE THREAD

**Issue by Alwan** [spring-projects/spring-boot#6047]
Greetings,

messages.properties not working with mustache template.

the attached project is example. If you replace mustache starter with thyemleaf it will work fine.
[sample-spring-boot-i18n.zip](https://github.com/spring-projects/spring-boot/files/284402/sample-spring-boot-i18n.zip)

Regrads

**Comment by wilkinsona** [comment]
Built-in support for `MessageSource` is a feature of Thymeleaf that JMustache doesn't have. It's expected behaviour that this won't work out of the box with a mustache template.

You could include a [JMustache Lambda](https://github.com/samskivert/jmustache#lambdas) in the model produced by your controller that looks things up from a `MessageSource`.
