### ISSUE TITLE
Setting out of bound HTTP status in ContentCachingResponseWrapper blocks thread and prints no warning

### ISSUE THREAD

**Issue by abhijitsarkar** [spring-projects/spring-boot#6052]
Wrapping the response with a `ContentCachingResponseWrapper` and setting the HTTP status to out of bound value causes the thread to hang until it times out. No warnings are logged in the application logs. I found this the hard way when I mistakenly set the HTTP status to 6 and spent several hours trying to troubleshoot the issue.

To reproduce the problem, extract the attached zip file, navigate to the base directory and run `./gradlew clean bootRepackage && java -jar ./build/libs/poc-1.0-SNAPSHOT.jar`. Then issue a curl request `curl -v "http://localhost:8080"`

Using Spring Boot version 1.3.5.RELEASE.
[poc.zip](https://github.com/spring-projects/spring-boot/files/285825/poc.zip)

**Comment by bclozel** [comment]
Hi @abhijitsarkar 
Looking at your repro project, it seems that this issue is not strictly related to Spring Boot nor Spring Framework, but rather the behavior of the container.

The response is correctly dispatched to the container and we're getting no exception from the container.

It seems that tomcat thinks that the response should have no body and just leaves the connection open (because of the keepalive option): 
```
$ curl http://localhost:8080/ -vvv
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 6
< Server: Apache-Coyote/1.1
< Date: Fri, 27 May 2016 08:21:21 GMT
* no chunk, no close, no size. Assume close to signal end
<
^C
```

On the other hand, Jetty is writing that response:
```
$ curl http://localhost:8080/ -vvv
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 006 006
< Date: Fri, 27 May 2016 08:42:12 GMT
< Content-Type: application/json;charset=UTF-8
< Content-Length: 45
<
* Connection #0 to host localhost left intact
Stranger{"message":"Hello","body":"Stranger"}%
```

Note that not only that HTTP makes no sense, but I'm also questioning the code dealing with `objectMapper` and appending content to the response body. I encourage you to ask a question on StackOverflow, we'll be happy to assist you in finding a better way to achieve what you're trying to do (which is not clear at all here).

In the meantime, if you think that behavior is not right, you should take it to the Tomcat developers; but given the situation, I don't know if Jetty or Tomcat is showing the best behavior.

Thanks for this report!

**Comment by abhijitsarkar** [comment]
@bclozel What I don't understand is why the `ContentCachingResponseWrapper` has no validation on the status code, where the status code is a known range. Kicking this issue to Tomcat seems like blaming the JDK for a NPE. A public API is responsible for it's own data validation.

As for the manipulation of the response body as shown in the poc is just, a proof of concept to demonstrate the issue. For the actual use case, we want to wrap the response from several microservices and insert a `meta` payload meant for tracking and debugging. If you still think there's a better way to do that, I'll be glad to open a thread on SO.
Thanks for your response.

**Comment by wilkinsona** [comment]
>  A public API is responsible for it's own data validation.

The API in question here is the Servlet API.

`ContentCachingResponseWrapper` subclasses `HttpResponseWrapper` which is part of the Servlet API and `setStatus(int)` is declared on the Servlet API's `HttpServletResponse` interface which `HttpResponseWrapper` implements.

**Comment by abhijitsarkar** [comment]
How does extending from the `HttpResponseWrapper` preclude defensive programming in `ContentCachingResponseWrapper`? Does no one override `toString`, `equals` or `hashCode` in their classes? It appears that the following couple lines will do the job:

```
public void setStatus(int statusCode) {
    super(HttpStatus.valueOf(statusCode).value());
}
```

**Comment by bclozel** [comment]
Doing so would break the Servlet contract which [allows container specific HTTP status codes](http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletResponse.html#setStatus-int-).

Also, your use case sounds a lot like [Spring Cloud Sleuth](http://cloud.spring.io/spring-cloud-sleuth/).

**Comment by abhijitsarkar** [comment]
I see, didn't know non-standard codes were allowed. I'll take a look at Sleuth to see if it fits our use cases.
Thanks for your response.
