### ISSUE TITLE
can I convert String to Boolean in @ComponentScan::lazyInit?

### ISSUE THREAD

**Issue by gxthrj** [spring-projects/spring-boot#6065]
In application.properties:
`app.lazy_init=true`

and in main class ：
```
@ComponentScan(lazyInit = "${app.lazy_init: false}")
public class Main(){...}
```

but the lazyInit is boolean , how can I convert String to Boolean in @ComponentScan::lazyInit?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
