### ISSUE TITLE
getAutowireCapableBeanFactory.Autowire() method not working in Spring Boot Applications.

### ISSUE THREAD

**Issue by aroradeepak001** [spring-projects/spring-boot#6112]
I am getting handle over the ApplicationContext from a Spring Boot App, I am trying to inject beans into it from outside, But its not working out  :(.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
