### ISSUE TITLE
DefaultInMemoryUserDetailsManagerConfigurer Question

### ISSUE THREAD

**Issue by whgibbo** [spring-projects/spring-boot#6143]
Hi,
Would I be right in thinking that the when I create my AuthenticationProvider, that the DefaultInMemoryUserDetailsManagerConfigurer is disabled ?

If so, would there be a way to enable this or would I have to implement my own ?

Thanks

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
