### ISSUE TITLE
URL Mappings problems with embedded Tomcat and Tomcat Server

### ISSUE THREAD

**Issue by pvlastaridis** [spring-projects/spring-boot#6144]
I even tried it on the small startup [guide ](http://projects.spring.io/spring-boot/) with Hello world mapping and although I get on localhost:8080/ the "hello world" response on the tomcat server if i run war 'boot' I get a 404 @ localhost:8080/boot or localhost:8080/boot/. Please help.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by pvlastaridis** [comment]
Phil just a take a second look at this please. I believe its a bug. Just use the small startup guide mentioned above and do a mvn package and then deploy the  original war on a tomcat server should the mappings be playing on both cases only with the difference that on tomcat you add the war name
