### ISSUE TITLE
WebMvcAutoConfiguration and EndpointWebMvcAutoConfiguration should back off if there is no DispatcherServlet

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#6146]
It doesn't make a lot of sense to have all those beans in the context if there is no dispatcher, and the logs it generates confuses people. It's a corner case, but it isn't hard to implement, and it makes using Spring Boot to host non-Spring apps much cleaner.

**Comment by bclozel** [comment]
Currently `WebMvcAutoConfiguration` and `EndpointWebMvcAutoConfiguration` have a `@ConditionalOnClass({ DispatcherServlet.class })`.

Knowing that `DispatcherServletAutoConfiguration` will register a `DispatcherServlet` bean for you if none is already registered, I don't know what we could do to avoid those two other auto-configurations being triggered.

What did you have in mind?

**Comment by dsyer** [comment]
I was thinking `@ConditionalOnBean` as well.

**Comment by bclozel** [comment]
So you think we should add another constraint to `DispatcherServletAutoConfiguration`? Because if we don't, having that class on the classpath will always create a Bean with it.

**Comment by bclozel** [comment]
I see. If the `DispatcherServletAutoConfiguration` is ignored, then indeed other beans are created even if no DispatcherServlet has been configured.

**Comment by bclozel** [comment]
I've just submitted #6212 - which is failing at the moment, on purpose.

Those changes are actually more involved that it looks. Adding a new `@ConditionalOnBean(DispatcherServlet.class)` on MVC configurations changes the deal for our testing infrastructure.

For example, the `@AutoConfigureWebMvc` annotation (used by `@WebMvcTest`) loads the following auto-configuration classes:

```properties
# AutoConfigureWebMvc auto-configuration imports
org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureWebMvc=\
org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration,\
org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration,\
org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration,\
org.springframework.boot.autoconfigure.hateoas.HypermediaAutoConfiguration,\
org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration,\
org.springframework.boot.autoconfigure.mustache.MustacheAutoConfiguration,\
org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration,\
org.springframework.boot.autoconfigure.web.HttpMessageConvertersAutoConfiguration,\
org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration
```

In order to trigger the configuration of the MVC infrastructure, we'd need to introduce both `ServerPropertiesAutoConfiguration` and `DispatcherServletAutoConfiguration`.

So I'm re-adding the "for-team-discussion" label as I think this change deserves more thinking.

**Comment by bclozel** [comment]
After discussing that change with the whole team, it seems that this is not possible after all. There are many cases where `DispatcherServlet`s are created without being registered as beans (e.g. traditional war deployment).
