### ISSUE TITLE
tomcat-embed-el:compile dependency even for war packaging with spring-boot-starter-tomcat:provided

### ISSUE THREAD

**Issue by pompeyjoe** [spring-projects/spring-boot#6156]
Created a new Spring Boot app as per:

http://docs.spring.io/spring-boot/docs/current/reference/html/getting-started-first-application.html

Changed packaging to war and marked spring-boot-starter-tomcat as provided as per:

http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file

When I run mvn dependency:tree, I get:

```
[INFO] \- org.springframework.boot:spring-boot-starter-tomcat:jar:1.3.5.RELEASE:provided
[INFO]    +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.0.33:provided
[INFO]    +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.0.33:compile
[INFO]    +- org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:8.0.33:provided
[INFO]    \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.0.33:provided
```

Why is tomcat-embed-el still coming through as a "compile" dependency?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

(Hint: you're probably using `spring-boot-starter-validation`).
