### ISSUE TITLE
Add Spring Boot starter for Spring Shell

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#6170]
Currently using Spring Shell with Spring Boot requires quite some boilerplate plumbing code. However, someone has created a custom Spring starter that all the nice bits and pieces to make building a Spring Shell app as easy as any other Spring Boot app:

https://github.com/linux-china/spring-boot-starter-shell

**Comment by wilkinsona** [comment]
That’s a very unusual third-party starter as it doesn’t contain any auto-configuration. It just gives you a custom run method that calls a bunch of boilerplate around a call to `SpringApplication.run`. It’d would need to be rewritten if we were to include it in Boot. Also, adding Spring Shell support to Boot would make it part of the Platform and we’ve decided that we don’t want to do that.

**Comment by olivergierke** [comment]
Is there any suggestion on how to actually deal with the issue of running Spring Boot based shell apps? There's a ticket in the Spring Shell bug tracker but I guess they don't want to add Boot specific integration either.

Right now, everyone is sort of copying some boilerplate code around to make two Spring framework ecosystem projects together, which is — independently of which solution we'll eventually come up with — definitely not a situation we want our users to be in, is it?

**Comment by wilkinsona** [comment]
There's some overlap in functionality between Spring Boot and Spring Shell. Specifically, Spring Shell's `Bootstrap` class and Spring Boot's `SpringApplication` class which both configure and refresh an application context. Spring Shell's `Bootstrap` class makes some assumptions about how the context will be configured, in particular requiring the use of XML configuration. That's a bit of an anti-pattern in Boot.

After a cursory look over the Shell code, I think a good step in the right direction would be to rework its Bootstrap class so that it's more amenable to reuse / extension. That would hopefully reduce the amount of boilerplate that was being copied around, without introducing a dependency on Boot (although I'm not sure that would actually be a bad thing for Spring Shell to do as an option).

**Comment by olivergierke** [comment]
I guess I was thinking of it as weird as it's the other way round for most Spring projects. Boot depends on them, not them on Boot. I'll take your suggestions forward to the Shell team. I guess most of what you describe stems from a time when Boot wasn't even around yet. Maybe it's time for a re-architected Shell 2.0 taking a more modern approach.

**Comment by snicoll** [comment]
> I guess I was thinking of it as weird as it's the other way round for most Spring projects. 

Spring shell is bootstrapping the context. That's really not what most Spring projects do.
