### ISSUE TITLE
Upgrade to Hibernate 5.2 cause Attempt to resolve foreign key metadata from JDBC metadata failed to find column mappings for foreign key

### ISSUE THREAD

**Issue by bestwu** [spring-projects/spring-boot#6186]
Spring Boot 1.4.0.BUILD-SNAPSHOT  Upgrade to Hibernate 5.2.0  cause Attempt to resolve foreign key metadata from JDBC metadata failed to find column mappings for foreign key([detail](http://stackoverflow.com/questions/37676463/attempt-to-resolve-foreign-key-metadata-from-jdbc-metadata-failed-to-find-column/37676671)).
This is a Hibernate bug [https://hibernate.atlassian.net/browse/HHH-10802](https://hibernate.atlassian.net/browse/HHH-10802).

Upgrade to Hibernate 5.2.0 is not good,I think.

**Comment by wilkinsona** [comment]
The fix versions on the Hibernate issue (5.2.1 and 5.1.1) are interesting. I was under the impression that 5.2 essentially replaced 5.1 and 5.1 wasn't going to be maintained. If 5.1 is going to be maintained, I think we should strongly consider using. It doesn't require Java 8 and, having lived with it for a few days, moving to Java 8 for such a widely used dependency now feels too aggressive

Unfortunately, dropping back to 5.1 doesn't look like it'll help with this specific issue and would require our RC to wait for Hibernate 5.1 and Spring Framework 4.3.1.

**Comment by snicoll** [comment]
`5.1.1` was due in March 9th and `5.2.1` is due in June 29th. I guess they are going to be co-released and that's definitely after our current RC. We can have a CI goal on 5.2.x and stick with 5.1 that is more aligned with our own system requirements. In any case, we integrate with a gazillion of libs now so delaying our RC for that issue seems a bit overkill. 

On the other hand, Spring Framework `4.3.1` brings several important changes regarding Hibernate 5.2 support (remember: Hibernate 5.0 and 5.1 doesn't work anymore due to a binary incompatible change on the Hibernate side). If we go with `4.3.0` we have no other choice to stick with 5.2

**Comment by wilkinsona** [comment]
9th March? Ouch.

Despite the fix version on the Hibernate issue, an answer to the Stack Overflow question says that 5.1.0 is not affected so it could be an option once Spring Framework 4.3.1 is out. I'm still leaning towards using a version of Hibernate that works with Java 7 out of the box.

**Comment by wilkinsona** [comment]
We're going to drop back to Hibernate 5.0.x (see #6198).
