### ISSUE TITLE
@Lazy annotation not honored with a service implementing the interface HealthIndicator

### ISSUE THREAD

**Issue by lquerel** [spring-projects/spring-boot#6187]
If I put this service in a package scanned by my springboot app. The service is not really created as expected (see annotation @Lazy). 

```
@Service
@Lazy
public class LazyService {
    public LazyService() {
        System.err.println("LAZY SERVICE CREATED");
    }
}
```

With the same app, if I implement the interface HealthIndicator on this service then the service is created. 

```
@Service
@Lazy
public class LazyService implements HealthIndicator {
    public LazyService() {
        System.err.println("LAZY SERVICE CREATED");
    }

    public Health health() {
        return Health.up().build();
    }
}
```

Why ? Sounds like a bug/limitation.

Tested on: SpringBoot 1.3.5

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
