### ISSUE TITLE
java.lang.ClassCastException: DTOObject cannot be cast to DTOObject

### ISSUE THREAD

**Issue by rajadileepkolli** [spring-projects/spring-boot#6205]
I receive this error when I enabled caching in my project that uses Spring Boot 1.4.0.M3 and various others Spring products

I have raised the same question in stackover flow 
http://stackoverflow.com/questions/37977166/java-lang-classcastexception-dtoobject-cannot-be-cast-to-dtoobject

Exact error is  

> java.lang.ClassCastException: com.learning.securedapp.domain.Permission cannot be cast to com.learning.securedapp.domain.Permission

Can you point what is wrong in my project , when I remove cache it is working as expected

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

This [section of the doc](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-known-restart-limitations) will help as well.
