### ISSUE TITLE
DefaultErrorAttributes vulnerability?

### ISSUE THREAD

**Issue by natzcam** [spring-projects/spring-boot#6207]
Internal IT security has informed me of a vulnerability in my server using SpringBoot. I believe this will happen also on exceptions when 'path' is reflected.

Details below:

The request string used to detect this flaw was :

`/<script>cross_site_scripting.nasl</script>.asp`

The output was :

HTTP/1.1 401 Unauthorized
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Set-Cookie: JSESSIONID=DFB28986B383FC2E852B205ADCCC8744; Path=/; HttpOnly
WWW-Authenticate: Basic realm="Realm"
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 22 Jun 2016 06:47:50 GMT
Connection: close

`{"timestamp":1466578070684,"status":401,"error":"Unauthorized","message"
:"Full authentication is required to access this resource","path":"/<scr
ipt>cross_site_scripting.nasl</script>.asp"}`

Note that this XSS attack may only work against web browsers
that have "content sniffing" enabled.

**Comment by wilkinsona** [comment]
I do not believe that there is a vulnerability here.

When the browser explicitly requests `text/html`, the requested path isn't reflected in the response. The only alternative is that the browser will serve a response with a `Content-Type: application/json` response that does reflect the requested path. You have shown an example of this above. I'm not aware of any browser, even going as back as far as IE 7, that will perform content sniffing on a response with a `Content-Type: application/json` header.

If you can show otherwise, please do not comment on this issue, but email details to `security@pivotal.io`.
