### ISSUE TITLE
thymeleaf  and  Jsp  error

### ISSUE THREAD

**Issue by suxg003** [spring-projects/spring-boot#6208]
Hello 

thymeleaf  and Jsp  Can co exist？  My  think exist，Is there any other way？

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by suxg003** [comment]
Thank you for your reply, has been referred to http://blog.csdn.net/lifuxiangcaohui/article/details/47060231 to solve this problem. But springboot on the To Jsp GitHub still has a Bug for the spring.mvc.view.prefix should be spring.mvc.view.suffix, spring.view.suffix to spring.view.prefix on it!
