### ISSUE TITLE
Consider moving BasicAuthorizationInterceptor to Spring Framework

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6237]
[`BasicAuthorizationInterceptor`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/web/client/BasicAuthorizationInterceptor.java) has been introduced recently and is generally useful outside of Spring Boot. I am wondering why it wasn't added to the framework in the first place. We could also remove [this duplicated code](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/TestRestTemplate.java#L119-L140) in the process.

ping @rstoyanchev @philwebb

**Comment by ahood12** [comment]
Hey Stephane, 

The location of the BasicAuthorizationInterceptor class seems to be: 

 org.springframework.http.client.**support**.BasicAuthorizationInterceptor

instead of: 

org.springframework.http.client.BasicAuthorizationInterceptor

which is where the import statement is pointing. This was giving me issues when I tried to run my application with the 1.4.0-SNAPSHOT version this morning.

**Comment by snicoll** [comment]
@ahood12 it wasn't when I applied that commit. The location was changed after and I've already fixed it (see https://github.com/spring-projects/spring-boot/commit/669da59b4a60d47421a315bc70ac398238ef8f11). Just update to the latest snapshot and you should be fine. Thanks!

**Comment by ahood12** [comment]
Ah that works. I'll do that real quick. Cheers!
