### ISSUE TITLE
If we set spring.thymeleaf.cache=true, it will be true whether add spring-boot-devtools or not

### ISSUE THREAD

**Issue by mrleoyoung** [spring-projects/spring-boot#6252]
I found that:
If we set spring.thymeleaf.cache=true, it will always be true whether add spring-boot-devtools or not. 
1, In /env endpoint, `applicationConfig:[classpath:/application.properties]` have `spring.thymeleaf.cache=true`. but `refresh` have `spring.thymeleaf.cache=false`
2, In java code, `@Value("${spring.thymeleaf.cache}") private String springThymeleafCache;`. we get true
3, In my IDEA, it acts like the cache value is true. And I have to make my thymeleaf templates dir not in excluding resources to trigger a restart to see the new content in templates. It is inefficient. 

So my question is: if we use spring-boot-devtools, those settings should be set by the devtools, not use  value in application.properties. In my test, it's not.

Spring Boot version is 1.3.5.RELEASE

Please help, thanks.

**Comment by mrleoyoung** [comment]
PS: Spring Boot version is 1.3.5.RELEASE

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by mrleoyoung** [comment]
I think it is a bug.  spring-boot-devtools should override the settings in application.properties. If so, we can only set spring.thymeleaf.cache=true in application.properties. and it will act like false in dev environment, and act like true in production environment. That's what we want.

Please check it, many thanks.

**Comment by snicoll** [comment]
No it isn't. It changes the default only if you haven't provided a value yourself. If we did, it means that you have no way to control that configuration when you use devtools.

**Comment by wilkinsona** [comment]
true is the default. If you don't set it at all in application.properties you'll get the behaviour that you want.

**Comment by mrleoyoung** [comment]
@snicoll @wilkinsona I got it. Thank you very much.
