### ISSUE TITLE
Spring boot jdbctemplate disorder

### ISSUE THREAD

**Issue by superluo** [spring-projects/spring-boot#6319]
when I save "地球" into mysql with sprnig boot(1.3.3),i get result from msyql is '??',could you tell where am i wrong ,thanks a lot.
1、url: jdbc:mysql://ip/ads_messages?useUnicode=true&amp;characterEncoding=UTF-8
2、mysql charset is utf-8 and project charset is utf-8

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by superluo** [comment]
thanks
