### ISSUE TITLE
Actuator endpoints can be accessed by users without role ADMIN

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#6326]
This sample is a simple webapp with security. Credentials has been customized but role ADMIN has not been set up. User just have a role USER and he is able to access to actuator endpoints.

Spring Boot version 1.4.0.RC1

Sample: https://github.com/eddumelendez/boot-actuator-no-admin

**Comment by vpavic** [comment]
Well, this is by design IMO. The default user will have management roles added automatically.

See the docs on [Actuator Security](http://docs.spring.io/spring-boot/docs/1.4.0.M3/reference/htmlsingle/#boot-features-security-actuator) and [```ManagementWebSecurityAutoConfiguration:127```](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/autoconfigure/ManagementWebSecurityAutoConfiguration.java#L127).

**Comment by wilkinsona** [comment]
@eddumelendez This is working as designed, although not for the reason suggested by @vpavic.

You have configured your application with a `WebSecurityConfigurerAdapter` that uses the default order (100). This has higher precedence than the auto-configured management security (Ordered.LOWEST_PRECEDENCE - 10) so you have indicated that you want to take complete control over the actuator's security. If you want to configure authentication but otherwise keep the management security configuration you should use a `GlobalAuthenticationConfigurerAdapter` instead.

**Comment by eddumelendez** [comment]
Thanks @wilkinsona to clarify this.
