### ISSUE TITLE
Combining @SpringBootTest and @DataJpaTest leads to confusing error

### ISSUE THREAD

**Issue by PWebb-Resmed** [spring-projects/spring-boot#6345]
The problem seems to occur in 1.4.0.M3 and 1.4.0.RC1, prior to M3 there's a totally different error.

I have a new application and a unit test, it works when running with the deprecated @SpringApplicationConfiguration , but not with the @SpringBootTest annotation.  See the basic attached zip file.
[test.zip](https://github.com/spring-projects/spring-boot/files/351176/test.zip)

**Comment by snicoll** [comment]
@PWebb-Resmed that project is a bit weird. You are combining a `@DataJpaTest` with a regular `SpringBootTest` that must start the servlet container. 

So in one hand you're saying: "spring boot please only start the persistence layer and nothing else please because I want to focus on that" and on the other you're saying "start the container with that class and instead of mocking the MVC part, make sure to force the container to start".

I've removed `@DataJpaTest` and your project runs fine (with our without the `classes` attribute). I've also removed `@SPringBootTest` and let `DataJpaTest` instead. Works fine as well.

`TL;DR` that project is invalid. But maybe we could do something to throw a different error?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
