### ISSUE TITLE
integration test for code spring boot app having mq and ldap

### ISSUE THREAD

**Issue by sachkk76** [spring-projects/spring-boot#6364]
Question : How do I write Integration test using SpringJUnit4ClassRunner to  test JMS source which listens to MQ and MQ endpoints are obtained from LDAP. This is spring boot app. I know there is embedded active-mq, do we have embedded ldap? Any example would be helpful 

I have spring boot application which is JMS source - 
1. Its listens to Mq queue
2. MQ queue destination are on LDAP so I have JNDI code to get connection details from to LDAP  using properties
initialContextFactory=com.sun.jndi.ldap.LdapCtxFactory
providerUrl=ldap://some url
queueConnectionFactory=somefactory
queue=testq

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
