### ISSUE TITLE
Add support for Apache Ignite

### ISSUE THREAD

**Issue by lgscofield** [spring-projects/spring-boot#6373]
The spring official has provided support for hazelcast, why not consider the Apache ignite will also join and support it

**Comment by snicoll** [comment]
@lgscofield no particular reason I am afraid. Thanks for reporting this.

**Comment by vpavic** [comment]
I haven't used Ignite myself but AFAIK it can be used as 2nd level cache for Hibernate and it also provides implementation of Spring's ```CacheManager```. So Boot's auto-configuration support could be quite similar with the one provided for Hazelcast.

**Comment by snicoll** [comment]
I know what it does @vpavic and we could do that. But given the JCache support is covered , I am asking @lgscofield what he had in mind.

**Comment by lgscofield** [comment]
@snicoll I just saw spring support hazelcast, and I looked carefully at the paper: http://www.gridgain.com/resources/benchmarks/ignite-vs-hazelcast-benchmarks
I mean, maybe Apache ignite performance is better than hazelcast

**Comment by snicoll** [comment]
@lgscofield that doesn't answer my question. Ignite is JSR-107 compliant so you can use it _right now_. The industry is moving to that as a common base for caching so having support for the proprietary Ignite API in Boot needs some reasons. If  you don't have any, I'd suggest to use what we have right now. 

Is there a problem with that? Or are you looking for dependency management for Apache Ignite in Spring Boot? Please clarity the scope of your request.

**Comment by lgscofield** [comment]
All right, thank you for your kind reply and solve my question. I'm just a suggestion, not a problem. But it is true that I want to replace hazelcast with Ignite in practical applications, the advantages of Ignite really make me very much.

**Comment by sri420** [comment]
We have considered to use Apache Ignite as IMDG (In memory Data Grid) for our micro services which are based on Spring Boot after doing a lot of research on its features. But, we just came across the list of supported caching providers's in Spring Boot's documentation and  I did not see Apache Ignite in that. 

 I know Ignite supports JSR-107 but, still since it is not explicitly mentioned in the supported caching provider it seems to be a concern for us.

It would be better if Spring Boot adds support for it sooner. 

Since we intend on using it along with Spring Boot and Spring Cloud , we would like to know if there is any specific reasons for not endorsing it.

**Comment by snicoll** [comment]
> I know Ignite supports JSR-107 but, still since it is not explicitly mentioned in the supported caching provider it seems to be a concern for us.

Why? Spring Boot advertizes it fully supports JSR-107. Ignite is a JSR-107 compatible broker. There shouldn't be any concern since we do what you're asking there.

> It would be better if Spring Boot adds support for it sooner.

We do. It's a JSR-107 implementation so we do. If you need some kind of "official" answer, here goes.

The reason why it's not listed there is because we don't provide dependency management for it. There is nothing wrong with Ignite as far as I know but I am not keen to provide dependency management for it since it also has some proprietary APIs that we don't support (and that I don't feel like supporting since we have JSR-107).

**Comment by sri420** [comment]
Thanks for your response. I wasn't aware it had some proprietary APIs. Anyway, I hope that as long as it is JSR-107 compliant, supports our requirements and works fine with Spring Boot/Spring Cloud, it should not be a concern to go with it.

**Comment by devozerov** [comment]
Hi Stephane,

Could you please clarify what proprietary API do you mean? Ignite do have it's own extended API which goes far beyond JSR-107. But as far as I know this holds for other caching providers as well. This is the reason why JSR-107 has "unwrap" methods in various interfaces (e.g. http://static.javadoc.io/javax.cache/cache-api/1.0.0/javax/cache/Cache.html#unwrap(java.lang.Class).

Regards,
Vladimir.

**Comment by philwebb** [comment]
@devozerov I think we simply mean that we'd rather not add it as a managed dependency because we don't directly call any `org.apache.ignite` classes for our code. Generally speaking, we only try to add managed dependencies for code that we directly support. In the case of Ignite, we'd rather support it via `JSR-107`, rather than any needing any direct integration.

**Comment by gembin** [comment]
Why ignite support is declined?  It is `JSR-107` compliant.

**Comment by snicoll** [comment]
We already replied to that question. Twice (https://github.com/spring-projects/spring-boot/issues/6373#issuecomment-254216032 and https://github.com/spring-projects/spring-boot/issues/6373#issuecomment-254856785)
