### ISSUE TITLE
Provide dependency management for OkHttp 3

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6385]
Clients that are auto-detected for which we have no dependency management are:
- ~~Netty~~
- ~~OkHttp 2~~
- OkHttp 3

**Comment by philwebb** [comment]
Perhaps after 1.4, but we decided to hold off for now.

**Comment by altro3** [comment]
Hi! What about this issue? Are you planning add okHttp3 to BOM file in version 2.2.0?

I see, this library already uses in your some projects - https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/spring-webflux.gradle.
```
testCompile("com.squareup.okhttp3:mockwebserver:3.13.1")
```
I need it for the same reason :-) - for testing WebFlux client.

**Comment by wilkinsona** [comment]
@altro3 Assuming you are not using the mobile UI, you can see above and to the right that the issue is currently assigned to the 2.2.x milestone so, yes, the current plan is to include dependency management in 2.2.

**Comment by altro3** [comment]
thank! I just clarified, because The issue, as I understand it, has been hanging for a long time, but for the first time I decided to test WebClient and, unfortunately, neither in Spring-test nor spring boot test there are no ready-made convenient Mock servers, only MockRestServiceServer, which is well suited to restTemplate. I saw that people from the project We bFlux use okhttp for testing
