### ISSUE TITLE
Restore DataSourceProperties get...() methods in a deprecated form

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6406]
See https://twitter.com/making/status/754890439291908096 and commit 762097ef2982d0ed807388a350ddcfa740a9078a

**Comment by snicoll** [comment]
Just to be clear, the methods are still there but instead of computing something, they now return the "raw" property (so if no property is defined, that returns `null`). The Javadoc has been updated.

I am OK to restore the previous logic and mark those as deprecated but then we can't have an accessor on the raw property anymore. If you look at the description of #1436, I don't see how we could do it any other way.

From an upgrade standpoint now, this may come as a surprise indeed, in particular for those having to support 1.3 and 1.4 at the same time so maybe we should revert 762097e altogether?

**Comment by making** [comment]
I did't intend to revert. Adding release note should be fine.
According to this refactoring, apps which used `DataSourceProperties#getXxx` could have NPE and should use `DataSourceProperties#determineXxx` instead.

**Comment by snicoll** [comment]
@making that comment was for @philwebb who thought (I think) that the method were removed. Your tweet sounds like you couldn't compile when you upgraded...

**Comment by philwebb** [comment]
I want to keep the `determine` methods, but I think we should keep the old `get` methods in a deprecated form. I've got a local branch just building now.

**Comment by snicoll** [comment]
Just to make sure I inderstand. We're going to remove those methods in 1.5 so there will be no way we can generate meta-data for those. I think we should reconsider this.

**Comment by philwebb** [comment]
@snicoll I think we need a migration path and I don't like the idea of reverting 762097e altogether. I'd suggest the following:

* 1.4 - Deprecated but working to give people a chance to move to the new methods.
* 1.5 - Throw `UnsupportedOperationException` to fail hard.
* 2.0 - Reintroduce the simple `get` form.

Does that work?

**Comment by snicoll** [comment]
Sorry but no :)

I don't think I am fine with that. Every single time I've seen a design where `@ConfigurationProperties` was managing the configuration _and_ something else, some design issues happened in some form. I am not saying this is the case here but `@ConfigurationProperties` must be designed in a way that properties are exposed as regular Javabean properties. We need to lead by example here.

The "mistake" we've done was to add logic in the getter and I think we're going down a path of patching things to workaround that (and only that). 

If you deprecate the property, you should expect the meta-data to state that `spring.datasource.url` (for instance) is deprecated. It's not. IMO (and @making says so himself), it's an upgrade path that might caught users by surprise but that's why we have release notes. Flagging the getter (= the property) as deprecated is _really_ wrong IMO.

**Comment by philwebb** [comment]
I forgot that `@Deprecated` would also update the meta-data.

**Comment by philwebb** [comment]
OK, we'll go with dumb getters and some release note updates.
