### ISSUE TITLE
Spring Boot 1.3.3: java.util.zip.ZipException: invalid stored block lengths

### ISSUE THREAD

**Issue by stevendick** [spring-projects/spring-boot#6443]
We are having a weird error that is only re-producible on one of our customer's servers.

Our app loads Groovy scripts at runtime as part of its execution.

The Groovy files are inside a JAR file inside the deployed Spring Boot WAR file (1.3.3).

On the problematic server, the client gets the following error:

    Caused by: java.util.zip.ZipException: invalid stored block lengths
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at java.io.Reader.read(Unknown Source)
        at org.springframework.util.FileCopyUtils.copy(FileCopyUtils.java:180)
        at org.springframework.util.FileCopyUtils.copyToString(FileCopyUtils.java:232)
        at org.springframework.scripting.support.ResourceScriptSource.getScriptAsString(ResourceScriptSource.java:102)
        at ch.hedgesphere.core.groovy.script.ClasspathScriptSource.getDelegatingScriptClassFromPath(ClasspathScriptSource.java:93)
        at ch.hedgesphere.core.groovy.script.ClasspathScriptSource.create(ClasspathScriptSource.java:80)
	... 92 common frames omitted

Now by the time the code gets to this point, it has already successfully loaded other Groovy scripts from the same JAR file.

We've confirmed the WAR file is not corrupt by checking the MD5 and the ops team have successfully manually unzipped the file in question and that worked OK.

I don't yet have confirmation on the OS version (it is Windows) or Java version (probably at least 1.8.0_45).

I don't see any open bugs in Java related to unzipping.

I did see Spring Boot had a zip-related bug last year, but that does not look related.

I'm interested in any ideas on what else we can check since the client is not terribly happy with the suggestion to kill the server and replace it :-)

**Comment by wilkinsona** [comment]
How are you deploying the war file? Is it being run as an executable war or are you deploying it to a container? If it's the latter, is the container unpacking the war as part of deployment? If it is, have you checked that the unpacked jar file that was inside the war file has not been corrupted?

**Comment by stevendick** [comment]
We are not using a container. I suspect the WAR file is being executed via the https://github.com/kohsuke/winsw Windows service wrapper (that's what we recommend)

**Comment by wilkinsona** [comment]
I'm not sure what else to suggest. It's difficult without being able to reproduce the problem or at least knowing more about the circumstances in which it occurs.

I notice `ZipInflaterInputStream` in the stack trace. One thing that you could try is not compressing the Groovy script in the jar as `ZipInflaterInputStream` is only used for reading compressed entries. You might have to jump through a few hoops to build such a jar, but it would help to narrow down the possible causes of the problem.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by naurinjamil1** [comment]
Hi, 
when trying to deploy a spring-boot app(.jar file) that uses LiquiBase 3.5.3 in cloud, I keep running into the following error ::

27/03/18 12:52:19.538 [APP/20-0] ERR    Caused by: liquibase.exception.UnexpectedLiquibaseException: java.util.zip.ZipException: invalid block type
27/03/18 12:52:19.538 [APP/20-0] ERR            at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:107)
27/03/18 12:52:19.538 [APP/20-0] ERR            at liquibase.servicelocator.ServiceLocator.<init>(ServiceLocator.java:44)
27/03/18 12:52:19.538 [APP/20-0] ERR            at liquibase.servicelocator.ServiceLocator.<clinit>(ServiceLocator.java:31)
27/03/18 12:52:19.538 [APP/20-0] ERR            ... 21 more
27/03/18 12:52:19.538 [APP/20-0] ERR    Caused by: java.util.zip.ZipException: invalid block type
27/03/18 12:52:19.538 [APP/20-0] ERR            at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
27/03/18 12:52:19.538 [APP/20-0] ERR            at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
27/03/18 12:52:19.538 [APP/20-0] ERR            at java.util.jar.Manifest$FastInputStream.fill(Manifest.java:470)
27/03/18 12:52:19.538 [APP/20-0] ERR            at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:404)
27/03/18 12:52:19.538 [APP/20-0] ERR            at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:438)
27/03/18 12:52:19.538 [APP/20-0] ERR            at java.util.jar.Attributes.read(Attributes.java:388)
27/03/18 12:52:19.538 [APP/20-0] ERR            at java.util.jar.Manifest.read(Manifest.java:219)
27/03/18 12:52:19.538 [APP/20-0] ERR            at java.util.jar.Manifest.<init>(Manifest.java:73)
27/03/18 12:52:19.538 [APP/20-0] ERR            at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:97)

Can anyone please guide towards a workable solution ?

**Comment by wilkinsona** [comment]
It looks like the jar file of one of your dependencies is corrupted. If you have any further questions, please ask on Stack Overflow or Gitter. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by naurinjamil1** [comment]
Hi, 
Yeah I have asked the question on Stack Overflow as well, right [here](https://stackoverflow.com/questions/44966112/java-util-zip-zipexception-invalid-block-type). Is using a 
 different version of liquibase a probable work-around?
Thanks again, 
Naurin
