### ISSUE TITLE
@AutoConfigureMockMvc shouldn't default to printing interactions by default

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#6444]
Printing the output every interaction with the preconfigured `MockMvc` instances is not a good idea as it pollutes the output in test runs significantly, even if the test succeeds so that logs in CI runs get polluted by all that unnecessary output.

I can certainly see the appeal to default to print when developing test cases, but test cases are hopefully executed way more often in scenarios where nobody is even looking at the output (on the command line, in CI environments).

Of course the default can be tweaked easily bit it feels like there'll be quite a lot of occasions where `@WebMvcTest` is used in combination with `@AutoConfigureMockMvc(alwaysPrint = false)` which sort of indicates that that would've been the better default.

**Comment by wilkinsona** [comment]
> logs in CI runs get polluted by all that unnecessary output.

I think you're looking in the wrong place for a solution to this problem. If you don't want the output to appear in the CI server's logs then configure your build system so that it captures sys out in the test reports but doesn't output it to the console/logs. This is the default for Gradle and I think it provides the best of both worlds:

 - When you run a test in your IDE you get all the diagnostic information you want directly available in the console
 - When you run a test on the command line or on CI the output is hidden but still available in the test reports should you need it

**Comment by olivergierke** [comment]
In know, I know. The thing is, that this then still pollutes the output and the stuff I might actually really want to see. I simply think that writing to `Standard.out` behind a user's back has never been a good idea in the first place.

**Comment by philwebb** [comment]
@rwinch may have an opinion on this.

**Comment by philwebb** [comment]
I personally quite like the printing, but I wonder if we need a way to configure it globally. Ultimately the `@AutoConfigureMockMvc` attributes get mapped to `Environment` properties. We could find a way to set `spring.test.mockmvc.always-print=false` as the default for people that prefer things that way.

**Comment by philwebb** [comment]
I've added #6455 to see if we can find a way to allow global configuration. I don't agree that printing interactions by default is a bad idea and I'd rather leave that as it is.

**Comment by philwebb** [comment]
You can now disable printing for all tests by adding an `application.properties` in `src/test/resources` containing:
```
spring.test.mockmvc.print=none
```

**Comment by olivergierke** [comment]
Thanks, Phil!
