### ISSUE TITLE
Third Party PropertySourcesPlaceholderConfigurer

### ISSUE THREAD

**Issue by tde-desc** [spring-projects/spring-boot#6457]
We're currently facing a problem regarding PropertySourcesPlaceholderConfigurer. Our current application uses Swagger 2 for api documentation, including its PropertySourcesPlaceholderConfigurer-Bean from SwaggerCommonConfiguration. Meanwhile our  application defines its own PropertySourcesPlaceholderConfigurer-Bean to load a .yaml and a .properties. 

Unfortunatly ConfigurationPropertiesBindingPostProcessor only allows one PropertySourcesPlaceholderConfigurer-Bean which results in our Properties not being injected. How is this scenario supposed to work?

**Comment by wilkinsona** [comment]
If you know that something's already creating a `PropertySourcesPlaceholderConfigurer` (either Boot or Spring Fox) then why do you need to create your own?

As an aside, and as the lead of Spring REST Docs I'm probably biased here, this is an excellent example of the risk of using something like Spring Fox. It alters the runtime configuration of your application purely so that its HTTP API can be documented. In my opinion, a documentation tool should be passive and leave your application unchanged at runtime.

**Comment by tde-desc** [comment]
Thank you for your reply so far.

> If you know that something's already creating a `PropertySourcesPlaceholderConfigurer` [...]

Well, the startup process fails silently due to the mentioned problem. There's no error message or anything indicating it. Instead `ConfigurationPropertiesBindingPostProcessor` considers some system-propertysources as defaults, surprisingly ...

> [...] why do you need to create your own?

We don't necessarily have to create our own, but we need to register our `PropertySouces` somewhere. Considering this experience we might be lucky to have only **one** third party library creating its own `PropertySourcesPlaceholderConfigurer`. If we used multiple APIs instantiating there own `PropertySourcesPlaceholderConfigurer` the situation would be even worse ...

> this is an excellent example of the risk of using something like Spring Fox.

What exactly do you mean by "something like Spring Fox"? I agree to your point regarding it shouldn't alter runtime configuration but I'm still wondering how the implementation around `PropertySourcesPlaceholderConfigurer` etc. is supposed to be intuitive. Maybe we're using it wrongly? How should APIs inject their configuration if not by `PropertySourcesPlaceholderConfigurer`?

**Comment by snicoll** [comment]
@tde-desc there are many ways you can inject your own configuration. You can post-process the `Environment` with an `EnvironmentPostProcessor`, see [the doc](http://docs.spring.io/spring-boot/docs/1.4.0.RC1/reference/htmlsingle/#howto-customize-the-environment-or-application-context)

**Comment by tde-desc** [comment]
@snicoll I'll have a look at your point, while customizing "environment"-specific functionality seems quite manipulative to me to be honest. Maybe I'm not quite used to spring-boot... In any case I'm still wondering how your suggestion is addressing the mentioned problem regarding having multiple APIs with their own `PropertySourcesPlaceholderConfigurer`. Or is this just bad style? And if so: Why is it failing silently?

**Comment by wilkinsona** [comment]
> What exactly do you mean by "something like Spring Fox"?

I mean something that changes the runtime behaviour of your application when there shouldn't be any need for it to do so. If you add a tool to generate some documentation and it affects you application's runtime behaviour, the tool is doing something wrong.

Spring Fox is registering a `PropertySourcesPlaceholderConfigurer` and setting `ignoreUnresolvablePlaceholders` to `true` (the default is `false`), but not actually registering any of its own property sources. I can't see much point in it doing that, and it's rather unfriendly given that there's typically only a single `PropertySourcesPlaceholderConfigurer` bean, particularly in a Spring Boot app.

>  but I'm still wondering how the implementation around PropertySourcesPlaceholderConfigurer etc. is supposed to be intuitive. Maybe we're using it wrongly?

In Spring Boot, I'd expect a single `PropertySourcesPlaceholderConfigurer` per application context. This is why Boot uses a condition to switch its auto-configured one off if something else provides one.

> How should APIs inject their configuration if not by PropertySourcesPlaceholderConfigurer?

I think Stephane's already answered this above. In addition to using an `EnvironmentPostProcessor`, you could also consider just declaring your configuration using the existing support for [externalized configuration](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config). It's pretty configurable in terms of both what file names it will look for and where it will look for them.

> Instead ConfigurationPropertiesBindingPostProcessor considers some system-propertysources as defaults, surprisingly ...

I don't think that's surprising. All of Spring Boot's documentation talks about binding the `Environment` to `@ConfigurationProperties` beans. It looks for a single `PropertySourcesPlaceholderConfigurer` in the context. If it finds one, it uses its `PropertySources` which, by default, are the same property sources as the `Environment` has. If it doesn't find a single `PropertySourcesPlaceholderConfigurer` then it falls back to using the `PropertySources` from the `Environment` directly.

>  I'll have a look at your point, while customizing "environment"-specific functionality seems quite manipulative to me to be honest

All of Spring Boot's configuration binding is built on top of the environment. If you want to add custom properties to a Spring Boot application, it's the most powerful way to do so.

I think there's a couple of things we can consider here:

1. Logging a warning when we find multiple `PropertySourcesPlaceholderConfigurer` beans and have to ignore them both
2. Look if it's possible to honour one configurer that's been marked `@Primary`

**Comment by tde-desc** [comment]
> In Spring Boot, I'd expect a single `PropertySourcesPlaceholderConfigurer` per application context.

I agree and I'm wondering whether there's a possibility to integrate `PropertySourcesPlaceholderConfigurer` in spring-boot in a way that the described problem cannot occur. Otherwise I always have to consider whether the API I'm developing might be a part of another spring-boot-application. If so, I'm not allowed to use `PropertySourcesPlaceholderConfigurer` (even though it would just work inside my API).

**Comment by dilipkrish** [comment]
Open to suggestions from you guys on how best to handle it. However a couple of things to consider:
- `EnvironmentPostProcessor` is a spring boot construct. So that is not a solution for non-boot apps. 
- [springfox](http://springfox.io) supports JDK 6+, 3.2.6 and up, so whatever the solution, it needs to work for that range.

While the offender in question here is the eagerly registered `PropertySourcesPlaceholderConfigurer`, It should be perfectly legal to use [PropertyPlaceholderConfigurer](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/beans/factory/config/PropertyPlaceholderConfigurer.html)'s that are namespaced (using placeholderPrefix, placeholderSuffix) with the `ignoreUnresolvablePlaceholders` to true. I don't believe all your suggestions ☝️ address that.

> Spring Fox is registering a PropertySourcesPlaceholderConfigurer and setting ignoreUnresolvablePlaceholders to true (the default is false), but not actually registering any of its own property sources.

The reason being it comes with [default values](https://github.com/springfox/springfox/blob/master/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L69-L70) that [can be overridden](http://springfox.github.io/springfox/docs/current/#customizing-the-swagger-endpoints). This is required for a library to _just work_! 

Is the solution may be to use `PropertyPlaceholderConfigurer` instead? In which case, is that something that spring boot should consider as well. At least IMO it should; because `PropertyPlaceholderConfigurer` is not deprecated and libraries/ user apps should be able to use it. 

Also  ["multiple propertyplaceholderconfigurers"](https://www.google.com/search?client=safari&rls=en&q=multiple+propertyplaceholderconfigurer+spring&ie=UTF-8&oe=UTF-8) in spring mvc is a [known problem](http://stackoverflow.com/questions/686635/is-it-possible-to-have-multiple-propertyplaceholderconfigurer-in-my-applicationc) that has been around for a while.

> It alters the runtime configuration of your application purely so that its HTTP API can be documented. In my opinion, a documentation tool should be passive and leave your application unchanged at runtime. 

SpringBoot does all sorts of things to alter the runtime configuration a.k.a "magic" :) so that comment seems a little unfair. 

Lastly, IMO  [springfox](http://springfox.io) is not just a documentation tool  its more than that 😉 It think springfox often gets conflated with `swagger-ui` which _IS_ a _poor_ documentation tool.

**Comment by wilkinsona** [comment]
> Also "multiple propertyplaceholderconfigurers" in spring mvc is a known problem that has been around for a while.

Indeed. That's why I'd recommend only using one. That said, and after some discussion between @snicoll and Juergen, I think there's some room for improvement in Boot.

> SpringBoot does all sorts of things to alter the runtime configuration a.k.a "magic" :) so that comment seems a little unfair.

I did start my initial comment about Spring Fox by saying I was probably biased. The difference is that Spring Boot is intended to configure your runtime for you – that's one of the main reasons for using it – on the other hand I'd expect a tool like Spring Fox to be as unobtrusive as possible and not to change runtime behaviour. Hopefully some improvements in Boot can help it to do that.

**Comment by dilipkrish** [comment]
> Hopefully some improvements in Boot can help it to do that.

And thats why I like the spring platform! :metal:

**Comment by snicoll** [comment]
We've added a warning in d7e1ccc. As for this particular use case, I'd strongly recommend not to use `PropertySourcesPlaceholderConfigurer` but rather a `PropertyPlaceholderConfigurer` and make sure that `ignoreUnresolvablePlaceholders` is enabled. The latter can resolve against many local properties without impacting the `Environment`.

If you want to go through the `Environment`, you need to register a `PropertySource` in the context before it is refreshed: `ConfigurableApplicationContext#getEnvironment()` returns a `ConfigurableEnvironment` which allows for registering a `PropertySource`.
