### ISSUE TITLE
Unable to promote Spring Boot 1.4 to central due to Sonatype constraints

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6495]
> Last Sync Errors: Missing: no javadoc jar found in folder '/org/springframework/boot/spring-boot-docs/1.4.0.RELEASE' Dropping existing partial staging repository.

Root cause seems to be that the `-docs` jar now contains code. Before it was pretty much empty.

**Comment by wilkinsona** [comment]
Sorry, that's my fault :(

**Comment by philwebb** [comment]
@wilkinsona I don't think it was your fault. It's a pretty crazy Maven rule that only happens when pushing to central. We've always had a `.jar` and we even have a `-sources.jar`, but the rule only kicks in if the `.jar` actually contains `.class` files.

I wish those central rules were available for us to run before we do a promotion.

**Comment by david-cheng** [comment]
暂时不需要

At 2016-08-12 14:38:06, "Phil Webb" <notifications@github.com> wrote:


@wilkinsona I don't think it was your fault. It's a pretty crazy Maven rule that only happens when pushing to central. We've always had a .jar and we even have a -sources.jar, but the rule only kicks in if the .jar actually contains .class files.

I wish those central rules were available for us to run before we do a promotion.
