### ISSUE TITLE
Thymeleaf 3 integration with spring boot 1.4.0.RELEASE is not working when there are custom thymeleaf beans 

### ISSUE THREAD

**Issue by rajadileepkolli** [spring-projects/spring-boot#6500]
We are using Thymeleaf in our application and we are letting spring auto configuration do everything for loading web content and we also need to send email to users therefore created custom bean as below to read content from mails folder to process email

```
	@Bean
	public ClassLoaderTemplateResolver emailTemplateResolver() {
		ClassLoaderTemplateResolver emailTemplateResolver = new ClassLoaderTemplateResolver();
		emailTemplateResolver.setPrefix("mails/");
		emailTemplateResolver.setSuffix(".html");
		emailTemplateResolver.setTemplateMode("HTML5");
		emailTemplateResolver.setCharacterEncoding("UTF-8");
		emailTemplateResolver.setOrder(1);

		return emailTemplateResolver;
	}
```

We were able to process both web content and email when we use default version provided by spring boot 1.4.0 i.e. Thymeleaf 2.1.5 , however as stated in another issue that Thymeleaf 3 is supported in 1.4.0 we tried to upgrade to 3.0.1 RELEASE by specifying as properties in POM.xml as suggested

             <thymeleaf.version>3.0.1.RELEASE</thymeleaf.version>
            <thymeleaf-layout-dialect.version>2.0.1</thymeleaf-layout-dialect.version>

When we run the application spring boot is unable to process webcontent instead looking into mails folder for processing. 

This is the error we get
 An error happened during template parsing (template: "mails/greeting.html")

Here is the simple minimum code to replicate the issue in [github](https://github.com/rajadileepkolli/springbootthymeleaf3/)

Could you please let me know how to make both webcontent and mails content process using thymeleaf 3 .

**Comment by zhanhb** [comment]
Add a property `spring.thymeleaf.templateResolverOrder=0` can solve your problem. But I don't know why the application performs different actions between on thymeleaf 2.1 and 3.0. Hope this helps to find the bug.

**Comment by bclozel** [comment]
This behavior can be explained with the fact that the `ClassLoaderTemplateResolver` you're defining is throwing exceptions when it's not finding the template with the given name. Since in your case that resolver is ordered at `1`, it's called before the default one (which has no order by default).

Thymeleaf 3 is a complete rewrite of all `Template{Resolver,Resource}` implementations and provides a new property `setCheckExistence` (see [thymeleaf issue](https://github.com/thymeleaf/thymeleaf/issues/419)).

Here's a workaround for you:

* as mentioned by @zhanhb, you can set the order of the auto-configured template resolver. You can set it to `1` with `spring.thymeleaf.templateResolverOrder=1` so it's called after the one you've defined.
* then define your own resolver and set its order and that new attribute like this:

```java
@Bean
public ClassLoaderTemplateResolver emailTemplateResolver() {
	ClassLoaderTemplateResolver emailTemplateResolver = new ClassLoaderTemplateResolver();
	emailTemplateResolver.setPrefix("mails/");
	emailTemplateResolver.setSuffix(".html");
	emailTemplateResolver.setTemplateMode("HTML5");
	emailTemplateResolver.setCharacterEncoding("UTF-8");
	emailTemplateResolver.setOrder(0);
	emailTemplateResolver.setCheckExistence(true);
	return emailTemplateResolver;
}
```

This way, you custom resolver can try resolving the template and if it fails, it will pass the execution to the next resolver in the chain.

Now on the Boot side, we can:

* make that `setCheckExistence` available in `ThymeleafProperties`; but this is a Thymeleaf 3+ only property
* we could set that property to `true` by default, thus allowing multiple resolvers in the chain; but as mentioned in [the Thymeleaf issue, this can cause some performance penalty](https://github.com/thymeleaf/thymeleaf/issues/419). I'd say it's probably the best choice here, since not doing so will prevent all other resolvers in the chain from being called.

**Comment by rajadileepkolli** [comment]
@bclozel  it worked thanks for the quick response
