### ISSUE TITLE
Getting absolute path of properties/yml file

### ISSUE THREAD

**Issue by hoeckxer** [spring-projects/spring-boot#6504]
For administrative reasons, we want to log the absolute path of the `application.yml`/`application.properties` file that was used to load the `Environment`. I've been searching for a while, but I can't really find an easy straight-forward way to do this. Application events seemed the most intuitive way (especially the `ApplicationEnvironmentPreparedEvent` ), but I can't resolve it for sure in any of the events.
Is there any way to easily resolve this (taking into account the various properties that can be used to specify a `config-file location` (e.g. `spring.config.name` & `spring.config.location`).

**Comment by philwebb** [comment]
The `Environment` abstraction provides a view over a number of different sources so there's no real guarantee that any single `application.properties`/`application.yml` file is the ultimate source of truth. For example, you can add to the `Environment` using system properties and command line flags.

The only way that I can think to support this would be to change `YamlPropertySourceLoader` and `PropertySourcesLoader` in the `org.springframework.boot.env` package so that they add `PropertySource` implementations that also track the source file. Even then, it won't entirely solve your problem since those files are often loaded from inside the JAR (i.e. there is no absolute path).

We'd be happy to look at a pull-request if you have ideas for changes that would help you.
