### ISSUE TITLE
Using VisualVM to connect via JMX

### ISSUE THREAD

**Issue by hoeckxer** [spring-projects/spring-boot#6506]
I'm trying to get my head around how the JMX connection of spring boot works. I've gone through all documentation I could find, but I still don't really understand how it works. From what I can tell, JMX is enabled by default, and I can connect to the VM using VisualVM on the same machine. 
When I set the property spring.jmx.enabled to false, I can still connect to the VM? I would've expected this to not be the case.
I'm trying to setup a connection to a remote VM, but I'm not sure which port I should use to connect to it, as I can't find it in the documentation. My ultimate goal is to be able to specifically set the JMX port, since I'm within a corporate environment, and the ports that we can use are fairly limited. From what I understand of JMX, it finds a dynamic port when you connect. Because of firewalls this isn't acceptable, so I tried to follow these instructions on stackflow:
http://stackoverflow.com/questions/29412072/how-to-access-spring-boot-jmx-remotely

They don't seem to have any effect (which makes sense, since it's an old post), but can somebody tell me how to achieve the same goal?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

(This has nothing to do with Spring Boot. If you want to connect via JMX to a remote instance, you need to configure the VM with additional properties. Checking [the official doc](http://docs.oracle.com/javase/7/docs/technotes/guides/management/agent.html) should help).

**Comment by mhaefele** [comment]
To be fair, there are springboot docs here:  http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-jmx.html

Is there a chance to add more information to those?  (maybe the same official doc as above?)
