### ISSUE TITLE
Provide support for running a Spring Boot application packaged as a fat jar via Maven

### ISSUE THREAD

**Issue by lithium147** [spring-projects/spring-boot#6515]
Enhancement

Currently spring boot maven plugin starts/runs the application as follows:

```
java [main-class] -cp [deps-from-pom]
```

But this is not right as it should run the jar/war.  The whole point of spring boot is to provide an executable jar/war.  It does this very nicely, so why not run the jar from the plugin, as follows:
`java -jar [artifact]`

Following advantages:
- closer to what happens in a production environment
- when jar is included into another project, don't need to repeat the main-class
- when jar is included into another project, don't need to repeat all the dependencies
- when multiple apps are included in a pom, don't end up with swamp of deps from all apps

**Comment by snicoll** [comment]
That's one way to see it for integration tests and I agree it will be better. However:

* I disagree we should do that for `run`. Other plugins don't work that way and it's closer to what happens in the IDE (which is something we strongly want to promote). 
* Having `run` relying on `repackage` is a mistake IMO
* You are assuming a fat jar is going to be created and that might not be the case.
* Moving to a situation where we start a new process will broke properties that are available on the plugin (`fork` comes to mind). Supporting both will make things quite complicated

I didn't get any of your last three points. 2 and 3 looks invalid to me (for one you should never use a repackaged jar as a module dependency). With that in mind, what is the use case for 4?

**Comment by lithium147** [comment]
Number 3 is indeed invalid.
I contend that the rest are still valid.
Here is the use case:
project m1 -> spring boot pom -> m1 uber jar
project m2 -> spring boot pom -> m2 uber jar
project tests -> pom with dependencies on m1 and m2 jars
- spring boot start m1, spring boot start m2
- run some tests
- spring boot stop m1, spring boot stop m2

The aim of project tests is to run cross component tests to prove the components are communicating together correctly.

So in project tests, it needs to know the main class for both m1 and m2, so this must be duplicated from those projects.  But the main class is already defined in the manifest of the jar, so why does it need to be given again?

**Comment by snicoll** [comment]
The feature that you are describing isn't supported at the moment. Adding the two projects to "project tests" make them available in the classpath (I guess that was your point 4?) so what you're looking after really is a way to specify the dependency of a spring boot fat jar and run that (i.e. not add it at all to the dependencies section). That wasn't obvious at all from the original description.

**Comment by wilkinsona** [comment]
Given that the app is launched with `java -jar`, starting one or more of them feels like a general Maven problem rather than one that's specific to Spring Boot. As far as I can tell, Maven's exec plugin doesn't support forking, but you could do it using the Ant Run plugin as Ant definitely does allow a process to be forked. Stopping the process is a different matter as stopping "nicely" is specific to Spring Boot. In that case the logic in `StopMojo` could be quite useful. Given that it would appear to make sense to do something for stop, having a matching start goal of some sort would appear to make sense.

I'm not sure about how this should appear to a user. In some ways using the same goals would be nice, but on the other hand a number of the properties don't make sense once you're running ready-built jars.

I guess I'm leaning towards separate goals that, ideally, can be configured with one or more dependencies that are the apps which they should run using `java -jar`.

**Comment by wilkinsona** [comment]
We’re cleaning out the issue tracker and closing issues that we’ve not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
