### ISSUE TITLE
springboot is taking more time for the first request

### ISSUE THREAD

**Issue by shyamjumberi** [spring-projects/spring-boot#6551]
Hi ,
I have developed a micro service using springboot 1.3.5 version.For initial request it is taking more time. How to reduce the processing time .

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

(Hint: the `DispatcherServlet` is initializer on first hit. You could upgrade to 1.4 and use the `spring.mvc.servlet.load-on-startup` property to force it to load on startup).
