### ISSUE TITLE
Problem with rabbit consumers on tests when using @MockBean

### ISSUE THREAD

**Issue by michelzanini** [spring-projects/spring-boot#6570]
Hi,

We recently migrated one application to use Spring Boot 1.4 and replaced some integration tests to use @MockBean.

After this, we start having some trouble on our tests that are testing rabbit queues consumers.

Every test that has a @MockBean will cause the ApplicationContext to refresh.
Every time the context refresh, the @RabbitListener will get an additional consumer (the consumer count will increase by one).

For example, let's say I have the following:

```
@Bean(name = LISTENER_FACTORY)
  public SimpleRabbitListenerContainerFactory listenerContainerFactory() {
    SimpleRabbitListenerContainerFactory factory = new SimpleRabbitListenerContainerFactory();
    
    factory.setConnectionFactory(this.connectionFactory);
    factory.setConcurrentConsumers(1);

    return factory;
  }

@Bean
  public Queue queue() {
    return new Queue(QUEUE, true);
  }

@RabbitListener(
      id = MessagingConfig.QUEUE, 
      queues = MessagingConfig.QUEUE, 
      containerFactory = MessagingConfig.LISTENER_FACTORY
  )
  public void consume(String request) {
    
  }
```

And tests that use @MockBean like:

```
@RunWith(SpringRunner.class)
@SpringBootTest
public abstract class Test {

  @MockBean
  private MyBean myBean;

  @Test
  public void test1() {
    
  }

}
```

For every test that runs with @MockBean, there is an ApplicationContext refresh, every time that happens, the concurrent consumer count on "queue" will increase by one.

The reason why we have problems with this in an Integration test is because we are testing with a real rabbit instance, and waiting to get a message from a consumer, but now, because lots of concurrent consumers are created, the test fails.

I have created a sample project to attach here.
If you run all tests in the project, and keep an eye on the concurrent consumer count in the queue, will see that for each of the 10 tests, the count will increase as they execute.

I am not sure the problem is with Spring Boot or Spring AMQP.

Thanks.

[demo2.zip](https://github.com/spring-projects/spring-boot/files/403693/demo2.zip)

<img width="761" alt="consumer-count" src="https://cloud.githubusercontent.com/assets/4479787/17436258/c72f40be-5b0d-11e6-9401-49f6898eec94.png">

**Comment by wilkinsona** [comment]
Your ten test classes each mock a different bean. This difference in the configured beans prevents Spring's test framework from reusing the same context for each test class. As a result, you see ten application contexts being refreshed when the tests run. Each of the ten contexts is kept open due to the test framework's context caching. Combined, this means that you end up with 10 consumers connected to Rabbit when the last class of tests is running.

The behaviour described above is expected and I think it's also worth nothing that there's nothing specific to `@MockBean` here. The same behaviour would happen with any setup where each test class changed the application context in some way (using `@TestPropertySource` with different properties for example).

You can avoid the problem by using adding `@DirtiesContext` to `Demo2ApplicationTests`. This will prevent the context from being cached and ensure that there's only one consumer connected at any time.

**Comment by maciejwalkowiak** [comment]
@michelzanini I had similar issue and I since I did not want my tests to take ages with `@DirtiesContext` I solved it by using anonymous queues during tests. You can have a look at full sample with description here: https://github.com/maciejwalkowiak/spring-boot-spring-amqp-java8-lombok-sample
