### ISSUE TITLE
Ability to sanitize all keys in /env from a particular property source

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-boot#6587]
https://github.com/spring-cloud-incubator/spring-cloud-vault-config/issues/27

Spring Cloud Vault Config uses vault to store encrypted values and load them into the spring environment. Since all values are encrypted, it would be useful to blank the values of every key in an entire property source. The current workaround is to use the key matching.

**Comment by joshiste** [comment]
I did a similar request in  #2922

**Comment by wilkinsona** [comment]
@joshiste Thanks for the pointer.

@spencergibb What about https://github.com/spring-cloud/spring-cloud-commons/issues/45?

**Comment by spencergibb** [comment]
@wilkinsona, @dsyer said to open an issue here since there's not really a way for an external property source to tell the `/env` actuator to sanitize all keys.

**Comment by wilkinsona** [comment]
@spencergibb So we're circling back around to Phil's suggestion in #2922?

> Perhaps we should offer some strategy so that Spring Cloud can add it to change the sanitize rules

And you'll then make use of whatever we provide for any property sources where sanitisation for the whole source makes sense?

**Comment by spencergibb** [comment]
Yes, sounds like a plan.

**Comment by philwebb** [comment]
@spencergibb We're going de-scope this for now since we want to focus on 2.0 issues. If you've got something specific in mind and you can put together a pull-request we can try to get it back into 1.5.

**Comment by spencergibb** [comment]
OK

**Comment by aantono** [comment]
@here Can someone comment as to why not using EnumerablePropertySource implementation and instead extend regular PropertySource is not a good solution for this use case?  To my understanding both Spring and Boot are very good and checking for the type of property source and only list the keys if they are from an EnumerablePropertySource.  The Environment functionality is not really impacted, because it uses direct getProperty calls to fetch the values.  Am I missing something?

**Comment by wilkinsona** [comment]
@aantono Being able to enumerate the keys in a property source is very useful for other purposes

**Comment by aantono** [comment]
@wilkinsona In general, totally agree that being able to enumerate properties is a helpful thing to have.  When it comes to looking at a secret sensitive data set, what could be the possible good reason for being able to do so, besides viewing those in the `/env` endpoint?

**Comment by wilkinsona** [comment]
@aantono Configuration binding via `@ConfigurationProperties` relies on property sources being enumerable. See `PropertySourcesPropertyValues`, for example.

**Comment by pbetkier** [comment]
Would you like some help maybe? I'm interested in this because at our company we implemented exactly this feature when running on Spring Boot 1.x. We did it by subclassing the `EnvironmentEndpoint` and overriding the `invoke()` method to modify the results map before responding. Now with changes to `EnvironmentEndpoint` in Spring Boot 2.x that's harder.

I think we could introduce a configurable predicate to `Sanitizer` that would decide should a given entry be sanitized `(String key, Object value, PropertySource<?> source) -> boolean`. By default a key-based would be used, but one could configure a different predicate, e.g. checking the property source. Not sure if we should include the value as the parameter.

Another option would be to make an interface out of `Sanitizer` to get full control over the sanitization process, e.g. change the asterisks placeholder. It seems unnecessary to me though.

What do you think? I could work on the PR when we agree on how the solution should look like.

**Comment by philwebb** [comment]
@pbetkier I think having a the ability to plug-in extra strategies would be quite nice. I'd probably we should make a `PropertySanitizeFilter` interface (or some other name) that has a single `match` method that returns a `boolean`. This would align with other `*Filter` types in the framework.

Users could then register one or more `PropertySanitizeFilter` beans to extended the default functionality.

If you have time to prototype something a PR would be most welcome!

**Comment by pbetkier** [comment]
@philwebb Ok great. I should be able to work on this next week.

I see that the `Sanitizer` is also used in a different context, for sanitizing `/configprops`, and it currently has a separate configuration there. Not sure if it makes more sense to keep them separated or to turn `Sanitizer` into a shared bean. I'll propose some solution so we discuss can the details on the PR. I think it'll be easier.

**Comment by mbhave** [comment]
Closing in favor of PR #11264.
