### ISSUE TITLE
why war can't deploy on tomcat 7.0.65 cause filter error

### ISSUE THREAD

**Issue by Areii** [spring-projects/spring-boot#6591]
**My Configuration:** 

@Bean
public Filter authFilter() {
        return new AuthFilter();
    }

**My Filter:** 

public class AuthFilter implements Filter {
    @Resource
    private StringRedisTemplate stringRedisTemplate;
    @Resource
    private UserService userService;

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
       //XXXX
        chain.doFilter(request, response);
    }

    @Override
    public void destroy() {

    }
}

**I package the project to a war and deploy on tomcat and then :**
One or more Filters failed to start. Full details will be found in the appropriate container log file

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Areii** [comment]
@wilkinsona if I add a filter use `@Bean or @Component` and in my filter I also use `@Resouce UserService userService`  to do some business，I package the project to a war and deploy on tomcat8.5.4.It failed to start.I don't know that it's a bug or not.can you help me ?

**Comment by wilkinsona** [comment]
@Areii As I said above, it's best to ask questions on Stack Overflow. If you do, please provide a minimal example that reproduces the problem. If it turns out to be a bug, we can always open a Boot issue.
