### ISSUE TITLE
FailureAnalyzer for NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by kelapure** [spring-projects/spring-boot#6612]
One of the most common startup failures for Spring Applications is the `org.springframework.beans.factory.NoSuchBeanDefinitionException`.

There are multiple causes for this exception ranging from Spring Beans not annotated correctly to the incorrect spring profile being in effect.

A [failure analyzer](http://docs.spring.io/spring-boot/docs/1.4.0.M1/api/org/springframework/boot/diagnostics/FailureAnalyzer.html) that analyzes and introspects the classpath to suggest possible candidates for injection when this exception is thrown will considerably improve the debugging and onramp of application developers with the spring frameowork.

The _NoSuchBeanDefinitionFailureAnalyzer_ will give clues and hints on which classes could potentially be Spring beans that could be injected with some work on the developers part.

This is a Feature enhancement only applicable for SpringBoot 1.4+ projects

**Comment by techlogix** [comment]
Completely agree Rohit, we spent 2-3 hours just finding and annotating beans during a migration effort. This feature enhancement would help fortune 500 companies

**Comment by wilkinsona** [comment]
I wonder if we could use the auto-configuration report to find beans that would have matched and to describe why they weren't available.

**Comment by kelapure** [comment]
Absolutely. Most of the time the beans exist but are not candidates for injection due to various filter.  We basically need to look at all the candidate beans for an injection that were filtered and report on those.

**Comment by snicoll** [comment]
Reusing the auto-configuration report is brilliant but we'll have to update it a bit to make that work (or live with the limitation). The biggest problem I can see right now is that if we have several methods with the same name and different arguments only one entry is recorded for them all. The culprit is in `SpringBootCondition` that generates a String with the form `classname#methodname` with no discriminant whatsoever for the arguments.

Granted, several `@Bean` method with the bean name is weird (for one, you'd have to give a different name via the annotation or associate a custom `BeanNameGenerator` to the context. Regardless, it would be nice if the contract would be a bit stronger so that we now exactly what ends up in the report rather than parsing a String and guessing.

I am working on a prototype ignoring those limitations for now, we can certainly revisit that once we have something in place.

**Comment by snicoll** [comment]
I've requested [an improvement in Spring Framework](https://jira.spring.io/browse/SPR-14627) to be able to handle cases where a qualifier was required.

**Comment by btiernay** [comment]
I actually created something like this in my project as well. I think the `FailureAnalyzer` feature is extremely useful. Hopefully one day this will be a thing of the past for Spring Boot applications:

https://www.reddit.com/r/programming/comments/3izji8/longest_stacktrace_i_have_ever_seen_in_java/

**Comment by philwebb** [comment]
@snicoll I tweaked some things so you might want to review commit b450fec when you're back.
