### ISSUE TITLE
spring.jackson.date-format configuration does not affect serialization of Date 

### ISSUE THREAD

**Issue by pavelfomin** [spring-projects/spring-boot#6642]
I'm having an issue similar to a one described by @csavory in https://github.com/spring-projects/spring-boot/issues/2225 - if I add a WebConfig that extends `WebMvcConfigurerAdapter` then my date format specified for jackson in application.properties is not taking effect:
```
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
spring.jackson.serialization.write_dates_as_timestamps=false
```
I'm using boot spring boot 1.4.0. Example of failing test case is at https://github.com/pavelfomin/spring-boot-rest-example (`branch feature/actuator-only`):
```
mockMvc.perform(get("/info"))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType(JSON_MEDIA_TYPE))
    	.andExpect(jsonPath("$.build", isA(Object.class)))
    	.andExpect(jsonPath("$.build.version", isA(String.class)))
    	.andExpect(jsonPath("$.build.artifact", is("spring-boot-rest-example")))
    	.andExpect(jsonPath("$.build.group", is("com.droidablebee")))
    	.andExpect(jsonPath("$.build.time", isA(String.class)))
    	;
```
The `build.time` field is expected to be formatted according to `spring.jackson.date-format`. If I comment out `@Configuration` in [WebConfiguration](https://github.com/pavelfomin/spring-boot-rest-example/blob/feature/actuator-only/src/main/java/com/droidablebee/springboot/rest/config/WebConfiguration.java) which extends `WebMvcConfigurerAdapter` then the test case passes.

How to reproduce:
 - `git clone --branch feature/actuator-only https://github.com/pavelfomin/spring-boot-rest-example.git`
 - `mvn clean test` 
 - test fails

The test run results in the following error:
```
Expected: is an instance of java.lang.String
     but: <1471056396151L> is a java.lang.Long
```
 - comment out `@Configuration` in WebConfiguration
 - `mvn clean test` 
 - test passes

**Comment by wilkinsona** [comment]
Your web configuration class is annotated with `@EnableWebMvc` which [as documented](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-auto-configuration) allows you to "take complete control of Spring MVC". Taking complete control means Boot no longer configures Spring MVC's Jackson-based HTTP message converter.

You should remove the `@EnableWebMvc` annotation, or configure the HTTP message converters manually.

**Comment by hatavan83** [comment]
I have the same problem when I config jackson with "spring.jackson.default-property-inclusion=non_empty". Jackson cannot auto config by application.property in Spring MVC, it only effect when I add spring-boot-starter-data-rest to dependency
The root cause is here http://stackoverflow.com/questions/32654854/the-spring-jackson-serialization-inclusion-environment-setting-does-not-seem-to

**Comment by zhaozhi406** [comment]
hatavan's solution is easy and directly, but it's not the root cause, though  add spring-boot-starter-data-rest in your classpath solve the problem; the root cause is that when spring boot init default MappingJackson2HttpMessageConverter it does'n use the Jackson2ObjectMapperBuilder instance which created by JacksonAutoConfiguration, this is because Jackson2ObjectMapperBuilderCustomizerConfiguration has an order(0) priority.

**Comment by wilkinsona** [comment]
@zhaozhi406 The root cause in this issue was the use of `@EnableWebMvc` and the solution is to remove it. I understand that you are trying to help, and thank you for that, but adding Spring Data REST and doing what you propose on Stack Overflow should not be necessary so you may be misleading people.

The order on the customiser is 0 to allow user-provided customisers to go before and after it. It will have no effect on what does and does not use the auto-configured ObjectMapper.

If you have found a situation where what you have described on Stack Overflow is necessary, please open a new issue with a small sample that reproduces the problem. What you are doing should not be necessary so there may be a bug that we should fix.

**Comment by VariabileAleatoria** [comment]
I'm having the same Issue without having `@EnableWebMvc` on my WebMvcConfigurer
