### ISSUE TITLE
Make @AutoConfigureMockMvc only print interactions on failures

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#6653]
# Yes this is a duplicate, but please reconsider

This is a duplicate of @olivergierke request in #6444 This is something that @philwebb and I have discussed in person but I hadn't created a ticket for it.

# Description 

Spring Boot should not enable logging by default. As #6444 points out this is a lot of extra noise in the logs. The logs of [pivotal-cla](https://github.com/pivotalsoftware/pivotal-cla) (a fairly small project) go from 507B to 24M! Even if there is a useful log in the output, I am going to have a terrible time finding it. 

**NOTE** When using the HtmlUnit support all the JavaScript and the CSS for each page is also getting logged for every request!

What's more is the performance impact of all the IO is significant even in a small project. This means my build is drastically slowed down.

# Possible Solutions

Please consider making LOG_DEBUG the default. Another option (perhaps more long term) is to only include the logs on test failure by defeault.

**Comment by wilkinsona** [comment]
> Even if there is a useful log in the output, I am going to have a terrible time finding it.

The problem is that if the interactions aren't printed you're never going to find it. If your CI build fails you're then left trying to reproduce the failure locally or committing a change to enable printing and hoping it happens again on CI.

I haven't seen anything here to change the [opinion that I expressed in #6444](https://github.com/spring-projects/spring-boot/issues/6444#issuecomment-234534923). I still believe that printing by default and an appropriately configured build will provide the best of both worlds.

**Comment by rwinch** [comment]
This is like saying Boot should enable all logging for tests so that the developer doesn't need to re-run their test if they have a failure.

Developers are responsible for providing an assertion that has a description that contains the information the need in the event there is a failure. It would be great if Boot could automatically provide additional information when the test fails, but it should not be logging everything to the console when the test passes.

**Comment by philwebb** [comment]
> Please consider making LOG_DEBUG the default. Another option (perhaps more long term) is to only include the logs on test failure by default.

I'd like to focus this issue on the suggestion above rather than going round again on #6444. There's now an easy way to switch all test to use global logging and I think that approach should work well for most users.

If we switch to debug logging by default, it's almost a hidden feature. At least with the current situation it's easy to see what's going on and _if_ the amount of output becomes a problem it's hopefully not too hard to work out how to switch it off. With off by default users need to know that there's something to switch on.

**Comment by philwebb** [comment]
If we can get the print on failure to work, it would be worth getting into 1.4. I'll target it as such but no promises that it wont slip.
