### ISSUE TITLE
Why spring boot web project will ignore the request path behind the comma character

### ISSUE THREAD

**Issue by wangjunling** [spring-projects/spring-boot#6659]
Question
In the resource/public have a test.html
![image](https://cloud.githubusercontent.com/assets/8435518/17687017/0678df84-63a4-11e6-8c65-db3177f2ac1f.png)

When I start the project, I can directly access the HTML at http://localhost:8080/test.html.

But after I write a controller
`
 @RequestMapping(value = "/test", method = RequestMethod.GET)`
`@ResponseBody`
` public Result list(HttpServletRequest request) {`
       ` logger.info("uri: "+request.getRequestURI());`
        `return new Result().success();  `
`}
`
Here, I continue to visit http://localhost:8080/test.html, the program will go to the controller, rather than direct access to the HTML, console printing:
`uri: /test.html`

That is my visit to the test. The HTML blocked by the spring, or if I change the path of the controller to/test1 / test/abc, visit http://localhost:8080/test.html, spring is not intercept.
That is to say, the spring will bring my ignore after commas in the path of the request, would you please tell me why this is, can we change?

Enhancement

spring-boot 1.3.6.RELEASE
jdk8

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
