### ISSUE TITLE
Bean created by @MockBean still has its fields autowired

### ISSUE THREAD

**Issue by WildDev** [spring-projects/spring-boot#6663]
The following code taken from the doc doesn't work as expected:

```java
@RunWith(SpringRunner.class)
@WebMvcTest(TestController.class)
public class TestControllerTest {

    @MockBean
    private TestValidator testValidator;

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    public void test() throws Exception {
        // no-opts
    });
}
```
... where's the mocked bean is:

```java
@Component
public class TestValidator implements Validator {

    @Autowired
    private TestRepository testRepository;
    ...
}
```

during test startup it fails:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'testController': Unsatisfied dependency expressed through field 'testValidator': Error creating bean with name 'com.example.TestValidator#0': Unsatisfied dependency expressed through field 'categoryRepository': No qualifying bean of type [com.example.TestRepository] found for dependency [com.example.TestRepository]: expected at least 1 bean which qualifies as autowire candidate for this dependency. 
```

Java: 1.8.0_65
Spring Boot: 1.4.0.RELEASE & 1.4.1-BUILD-SNAPSHOT
Maven: 3.3.3

[Test project on GitHub](https://github.com/WildDeveloper/mockbean)

**Comment by wilkinsona** [comment]
Thanks for the sample.

I don't think this has anything to do with `@MockBean`. The problem is that you're using `@WebMvcTest` but with a bean that autowires a Data JPA repository. Data JPA repositories aren't created when using `@WebMvcTest.

Rather than mocking `TestValidator`, is there any reason why you can't mock `Validator` instead? You'd have to change the injection point in `TestController`. Alternatively, you may be able to avoid the problem by using constructor injection instead of field injection (I suspect you'd need to provide a no-args constructor, though).

I guess we could look at disabling autowiring for beans created using `@MockBean` so that if it's a mock created from a class (rather than from an interface) no attempt is made to inject anything into it.

**Comment by WildDev** [comment]
@wilkinsona ,

> I don't think this has anything to do with @MockBean. The problem is that you're using @WebMvcTest but with a bean that autowires a Data JPA repository. Data JPA repositories aren't created when using `@WebMvcTest.

yes, but there is any controller interacts with the database either via service layer or whatever else. In order to test a controller it is necessary to mock its dependencies anyway. Data JPA repository shouldn't be autowired at all since it is just a dependency of the dummy object.

I will try your suggestion but IMAO, the `@MockBean` annotation should behave the same like Mockito's `@Mock` annotation does - it just makes a dummy object without any nested dependencies resolved.

**Comment by wilkinsona** [comment]
> Will try your suggestion but IMAO, the @MockBean annotation should to behave exactly like Mockito's @Mock does

In terms of how the mock is created, that's exactly what `@MockBean` does. However, we have to do more than `@Mock` – the mock has to be added to the application context so that it can be injected. It's the fact that's it's a bean in the application context that means that an attempt is made to inject its fields.

**Comment by WildDev** [comment]
@wilkinsona , then it behaves rather like a stub that not always sufficient for the testing

**Comment by snicoll** [comment]
Looks like a rephrased clone of #6658

**Comment by WildDeveloper** [comment]
@snicoll , has nothing with the [#6658](https://github.com/spring-projects/spring-boot/issues/6658) at all

**Comment by snicoll** [comment]
Yeah, @wilkinsona just told me. The complaints look alike :)

**Comment by SingleShot** [comment]
I experience this same problem when the unit under test's dependencies are plain old Spring beans that themselves have autowired dependencies. If the dependencies are interfaces, no problem, they mock fine. But if classes, the mocking does not work and requires the dependencies of the dependency to be wired in.

The "workaround" for this is to provide `@MockBean`s for dependencies of the dependency, and dependencies of the dependency's dependencies and so on down, which is pretty ugly. Another is to only use interfaces for your dependencies - which I prefer - but you don't always have that luxury when the dependency is not in your control. Of course, I could wrap it in my own interface but that's extra code that I wouldn't need if `@MockBean` behaved like Mockito class mocking from the standpoint of not needing to provide dependencies to the mock.

For me - someone trying to port a legacy (and very messy) Spring app over to several Spring Boot apps, getting this fixed is important. Thanks.

**Comment by snicoll** [comment]
Fixed in https://github.com/spring-projects/spring-boot/commit/0e00a49dcc246893fcaf1c7a0497fac6dcbc7454

**Comment by StasKolodyuk** [comment]
I experience the same issue for `@SpyBean`

**Comment by wilkinsona** [comment]
@StasKolodyuk That's to be expected. Unlike a mock, a spy is a wrapper around a "proper" bean. For the bean that's being spied upon to work properly it needs to have its dependencies injected.

**Comment by StasKolodyuk** [comment]
@wilkinsona That makes sense, thank you!

**Comment by hinotori** [comment]
Sorry for the intrusion, but i'm facing the same issue yet. Using spring-boot 1.5.2. 
Do you know when this bug will be fixed?

Thanks

[logerror.txt](https://github.com/spring-projects/spring-boot/files/890834/logerror.txt)
![20170403_131948](https://cloud.githubusercontent.com/assets/128736/24621767/0b945612-1879-11e7-94ba-6ff677f045b4.jpg)
![20170403_131931](https://cloud.githubusercontent.com/assets/128736/24621766/0b9380b6-1879-11e7-8c76-beef8b756350.jpg)

**Comment by snicoll** [comment]
@D0rmouse this issue was closed almost 2 years ago. If you have a usage question please ask on StackOverflow with a link to a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the behaviour you're experiencing. The description you shared is vague and we won't be able to help you effectively without more details. If you believe you've found a bug in Spring Boot, please create a separate issue with a link to a minimal sample.

**Comment by D0rmouse** [comment]
@snicoll Thanks for your response. I don't need usage help, just giving you a heads-up that `@MockBean` has wiring issues in the described situation. Stub implementing our business service interface wired by our rest controller does not have this issue.
I'll see if I can create a minimal setup to reproduce this and create a separate issue.
