### ISSUE TITLE
spring data rest / doesn't work if static index.html present

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-boot#6668]
sample project

https://github.com/xenoterracide/jpademo

SO question
http://stackoverflow.com/q/38966467/206466

`curl -H "Accept: application/json" http://localhost:8080` should return 

```
{
  "_links" : {
    "persons" : {
      "href" : "http://localhost:8080/persons{?page,size,sort}",
      "templated" : true
    },
    "profile" : {
      "href" : "http://localhost:8080/profile"
    }
  }
}
```

but instead returns

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    <p>Hello</p>
</body>
</html>
```

this very old bug makes me think this should be possible https://jira.spring.io/browse/DATAREST-56, and also that it should work out of the box, since `text/html` and `application/json` aren't the same type. the default should be the static content, but the spring data rest should be in the list of available for content type and registered for the `application/json`. 

I read this https://spring.io/blog/2013/05/11/content-negotiation-using-spring-mvc and related, but for the life of me I have no idea what I'd register to get it to include Spring Data's HAL view.

As a side note I've actually been trying to do this with Neo4j, if that matters with a workaround implementation.

**Comment by wilkinsona** [comment]
There are two handler mappings involved here. Spring Data REST's `DelegatingHandlerMapping` with an order of `LOWEST_PRECEDENCE - 100` and the handler mapping for Spring MVC's `ViewControllerRegistry` with an order of 1. The latter is involved because we have auto-configured a view controller to handle the welcome page forwarding of requests to `/` to `index.html`.

Due to their ordering, the handler mapping that forwards to `index.html` is called before Spring Data REST's mapping gets a chance. No consideration is given to the `Accept` header so we'll happily serve a `text/html` response to a request that only accepts `application/json`.

Changing the order is not sufficient to fix the problem. A browser will typically use an accept header like `Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`. The `*/*` means that it will happily accept anything. If Data REST's `DelegatingHandlerMapping` goes first this means that we'll always serve `application/json` to the browser making it impossible to access the welcome page.

It looks like we need to keep the mapping for the welcome page before Data REST's `DelegatingHandlerMapping`, but only perform the forward to `index.html` if the request's accept header indicates that `text/html` is an acceptable response content type. That would require us to use something other than Spring MVC's view controller registry for the forward, perhaps something like this:

```java
private final class WelcomePageHandlerMapping extends SimpleUrlHandlerMapping {

    private WelcomePageHandlerMapping() {
        ParameterizableViewController controller = new ParameterizableViewController();
        controller.setViewName("forward:index.html");
        setRootHandler(controller);
        setOrder(0);
    }

    @Override
    public Object getHandlerInternal(HttpServletRequest request)
            throws Exception {
        for (MediaType mediaType : MediaType
                .parseMediaTypes(request.getHeader(HttpHeaders.ACCEPT))) {
            if (mediaType.includes(MediaType.TEXT_HTML)) {
                return super.getHandlerInternal(request);
            }
        }
        return null;
    }
    
}
```

@bclozel Do you have any better ideas?

In the meantime, the problem can be avoid by moving Spring Data REST to somewhere other than `/`. using `spring.data.rest.base-path`.

**Comment by bclozel** [comment]
@wilkinsona I can't think of a better way to handle that.
We could improve Spring MVC and provide a variant of the `SimpleUrlHandlerMapping` that handles only if one of the media types accepted by the client are compatible with the ones specified for that mapping. But it would look a lot like a watered down version of `RequestMappingHandlerMapping`.

If you think anything can be improved in Spring Framework please let me know - but in the meantime, what you describe is probably the best solution.
