### ISSUE TITLE
Logback configuration is reinitialized for each context created in the application

### ISSUE THREAD

**Issue by mbogoevici** [spring-projects/spring-boot#6688]
Originally observed in https://github.com/spring-cloud/spring-cloud-stream/issues/605. See https://github.com/spring-cloud/spring-cloud-stream/issues/605#issuecomment-240601729 for some details related to that.

To summarize: `LoggingApplicationListener` executes for each additional context created within the application via `SpringApplication.run()`. In the case of Logback, `initializeSystem` eventually leads to a `stopAndReset` on the `LoggerContext` every time it runs. The effects are not noticeable if using standard Boot configuration mechanisms, as the configuration will be re-applied identically every time. This prevents, however, applying customized configuration on the loggers (e.g. via an additional `ApplicationListener`).

An example application that shows this happening is as simple as: https://github.com/mbogoevici/gh-issues/tree/master/test-listeners

**Comment by wilkinsona** [comment]
The tricky thing here is that we don't know that we're going to be in a child context during the very early phases of SpringApplication initialisation. When either `ApplicationStartedEvent` or `ApplicationEnvironmentPreparedEvent` is published there's no application context and nothing we can look at to see if there's a parent.

**Comment by gmarziou** [comment]
Hi,

I experienced same issue with an application that uses `logback-spring.xml` to configure console or file appenders and logstash appender added programmatically because it requires dynamic properties from my application.

It works well on app startup, but when I modify log level in `logback-spring.xml` the `LoggerContext` is reset and only the static configuration from `logback-spring.xml` is reloaded and so the logstash appender is no longer used.

I could not find any Spring event fired when logback reconfigures so I added a `LoggerContextListener` that adds logstash appender on reset event as shown in the log below:

<details>
<summary>Log after changing log level in logback-spring.xml</summary>
~~~
18:57:04,904 |-INFO in ReconfigureOnChangeTask(born:1471969999958) - Detected change in configuration files.
18:57:04,904 |-INFO in ReconfigureOnChangeTask(born:1471969999958) - Will reset and reconfigure context named [default]
18:57:04,904 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Worker thread will flush remaining events before exiting. 
18:57:04,909 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Queue flush finished successfully within timeout.
18:57:04,911 |-INFO in net.logstash.logback.appender.LogstashSocketAppender[LOGSTASH] - Defaulting maxMessageSize to [8192]
18:57:04,911 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Attaching appender named [LOGSTASH] to AsyncAppender.
18:57:04,911 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Setting discardingThreshold to 102
18:57:04,911 |-INFO in com.example.LogbackLoggerContextListener@1eed657 - Added Logstash Appender
18:57:04,904 |-INFO in ReconfigureOnChangeTask(born:1471969999958) - Detected change in configuration files.
18:57:04,904 |-INFO in ReconfigureOnChangeTask(born:1471969999958) - Will reset and reconfigure context named [default]
18:57:04,904 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Worker thread will flush remaining events before exiting. 
18:57:04,909 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Queue flush finished successfully within timeout.
18:57:04,911 |-INFO in net.logstash.logback.appender.LogstashSocketAppender[LOGSTASH] - Defaulting maxMessageSize to [8192]
18:57:04,911 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Attaching appender named [LOGSTASH] to AsyncAppender.
18:57:04,911 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_LOGSTASH] - Setting discardingThreshold to 102
18:57:04,911 |-INFO in com.example.LogbackLoggerContextListener@1eed657 - Added Logstash Appender
18:57:04,913 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/C:/projets/gh-issues/test-logback-reload/target/classes/logback-spring.xml] 
18:57:04,913 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 5 seconds
18:57:04,914 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
18:57:04,914 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
18:57:04,914 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:57:04,915 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.example] to INFO
18:57:04,915 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
18:57:04,915 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
18:57:04,915 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
18:57:04,915 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@144d9e1 - Registering current configuration as safe fallback point
~~~
</details>

You can see it in my [minimal project](https://github.com/gmarziou/gh-issues/tree/master/test-logback-reload), I need to cleanup code a little. I'm wondering whether there could be a better way to do it with Spring and in a less logback specific way.

**Comment by wilkinsona** [comment]
Suggestion from @dsyer: we might be able to set a property on the `LoggerContext` to mark that we've already set things up and we can leave it alone

**Comment by wilkinsona** [comment]
@gmarziou That's a different problem as there's no application context hierarchy involved. If, I've understood things correctly Logback is reloading its configuration, but not of your programmatic configuration has any effect. That sounds like standard Logback behaviour to me. We could perhaps plug something into Logback that fires an event on configuration reload or calls any beans that implement a particular interface but that would be an enhancement rather than a bug fix. Please open a new issue if you'd like us to look into that some more.

**Comment by gmarziou** [comment]
Thanks @wilkinsona , I will dig further before opening an issue, in particular I want to check beahvior when configuring logging from application properties either locally or from Spring Cloud Config server.
