### ISSUE TITLE
trust store configuration for REST client

### ISSUE THREAD

**Issue by leoz68** [spring-projects/spring-boot#6704]
Questions:

I am new to Spring Boot. I set up a Spring boot web to consume an existing RESTful service. The existing RESTful service is secured by HTTPS with self-signed certificate. When I use RestTemplate in Spring Boot to call the existing service, I always get SSL handshake exception. I know it is caused by self-signed cert. I import the cert into my local trust store. The problem is I don't find an solution in Spring boot documentation to configure the trust store in applications.properties. Spring boot documentation only mentions how to configure key store and trust store to make service itself to be SSL secured. I can't find how to configure Spring boot client application to set up trust store. I can only hard code the location as below to make it work. I know I also can pass the property in Java arguments. Do you have any better solution to looking up trust store in application.properties and specify the file location like classpath: for client application?

static
	{
		System.setProperty("javax.net.ssl.trustStore", "C:\\spring-boot-wks\\keystore\\cacerts");
		System.setProperty("javax.net.ssl.trustStorePassword", "changeit");
	}

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
