### ISSUE TITLE
MongoProperties ignores spring.data.mongodb.uri if any other spring.data.mongodb.* is set

### ISSUE THREAD

**Issue by bitsofinfo** [spring-projects/spring-boot#6739]
Spring boot 1.4

I have an app with the following configuration

```
spring.data.mongodb.uri: "mongodb://10.11.22.11:27017/mydb"
spring.data.mongodb.username: "myuser"
spring.data.mongodb.password: "123"
```

`MongoProperties` (at this line https://github.com/spring-projects/spring-boot/blob/0de5988c0e2cb7d8521fc7fa5dec4f1b6886c9d5/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/MongoProperties.java#L200)

Assumes that if username/password are set, then it just ignores what is in the URI, then this results in host/port being null and defaulting to localhost:27017

I have a use case where I don't want to specify the the username/pw in the URI because they are encrypted separately. It would be nice if this block of code was smart enough to maybe piece this all together? 

This may or may not be considered a "bug" since putting everything in the URI seems to correct the issue, but that was not entirely clear that this was "one or the other". Perhaps an enhancement for consideration or documentation update.

 (or better logging of what is going on? this was a bit maddening to figure out)

related: https://jira.spring.io/browse/DATAMONGO-1478

**Comment by philwebb** [comment]
I think we should fail hard if the URI is set when `username`/`password` are also set.

**Comment by philwebb** [comment]
@bitsofinfo We'll use this report to make the failure more explicit. If you'd like the `username`/`password` to be added to the URL please raise another issue and we can consider what's involved.

**Comment by bitsofinfo** [comment]
@philwebb what do you mean by uname/pw added to the URL? That is already supported.

**Comment by wilkinsona** [comment]
> Or do you mean added automatically if this combination is present?

Yes.

**Comment by philwebb** [comment]
@wilkinsona or @snicoll I think I need another pair of eyes on this. The logic in `MongoProperties` is confusing me.

**Comment by snicoll** [comment]
> that was not entirely clear that this was "one or the other". Perhaps an enhancement for consideration or documentation update.

Agreed, that config of your work as follows:

```properties
spring.data.mongodb.host=10.11.22.11
spring.data.mongodb.port=27017
spring.data.mongodb.database=mydb
spring.data.mongodb.username=myuser
spring.data.mongodb.password=123
```

I am wondering if blowing up if those two are set wouldn't be a good option. I am a bit nervous to do that in a bug fix release but we could give that a try for 1.5? In the meantime, I'll improve the documentation.

**Comment by snicoll** [comment]
@wilkinsona @philwebb looks like 98ab295 is better suited for 1.5 but I want to double check. Maybe it is ok to apply that in 1.4.1?

**Comment by philwebb** [comment]
My vote would be for 1.5

**Comment by nicolas-nannoni** [comment]
Just a note on that change: it may break some integration test configurations depending on how they were setup. Using an embedded MongoDB (auto-configured via `EmbeddedMongoAutoConfiguration`)  sets the `port` property of `MongoProperties` to a random port if it was initially `port=0` or absent. Therefore, up till 1.4.x, overriding the port (and only that) to `0` would force the `MongoProperties` to use the embedded Mongo port, and it would ignore in the tests any `uri` otherwise defined.

With 1.5+, if `spring.data.mongodb.uri` is set otherwise (in the main `application.yml` for instance), the tests would not start and give `java.lang.IllegalStateException: Invalid mongo configuration, either uri or host/port/credentials must be specified` because `port` is set to a specific random value (when `MongoProperties.createMongoClient()` is called) together with some value in `uri`. Simply overriding the `uri` using `0` as port does not work either as `EmbeddedMongoAutoConfiguration` forcefully sets the `port` property regardless.

A more lenient check on `uri` in `MongoProperties.createMongoClient()` (`this.uri != null && !this.uri.isEmpty()`) could allow overriding `spring.data.mongodb.uri` to an empty string in integration tests and not have to change the main application configuration. Or is there something that I missed?

**Comment by wilkinsona** [comment]
@nicolas-nannoni Thanks for the analysis. That's an interesting, and unwanted, side-effect. Can you please open a new issue so that we can see what we can do about it?

**Comment by nicolas-nannoni** [comment]
Created issue #8219. Thanks for looking into that.
