### ISSUE TITLE
Provide an option to unpack BOOT-INF/classes and WEB-INF/classes

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6742]
It would provide a way to avoid the problem described in #6709

**Comment by tkvangorder** [comment]
I would like to add a second use case that really needs to have the classes at the root level of the .jar file. We have a legacy integration test project that has dependencies on both our rest web services and our rest clients. This project now fails when compiling our integration tests because it cannot find any of the classes from our rest web services project.

**Comment by wilkinsona** [comment]
That's not a good use case for what's proposed in this issue. Instead, you should build the repackaged executable jar with a classifier so that the normal jar can be used as a dependency.

**Comment by dsebastien** [comment]
Thanks a lot for the pointers @wilkinsona. I've stumbled upon this while trying to write some "integration" tests for my simple single-module project. It took me a while to understand why I was getting the class not found errors :)

**Comment by wilkinsona** [comment]
We’re cleaning out the issue tracker and closing issues that we’ve not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
