### ISSUE TITLE
Improve docker support - separate dependency jar

### ISSUE THREAD

**Issue by osiegmar** [spring-projects/spring-boot#6804]
It is very easy to build docker images from Spring Boot applications. Unfortunately every new version of an application results in a new, huge docker image - because of fat-jars.

It would be very helpful if the Spring Boot gradle/maven plugins would provide a way to build two jar files - one jar file with all dependencies and the other jar file with the application itself. If a new application version has no dependency changes, the new docker image would be very small.

In the meanwhile, this is one way to work around this issue: 

http://bsideup.blogspot.de/2015/04/spring-boots-fat-jars-vs-docker.html

**Comment by snicoll** [comment]
I surely didn't understood the question since [we already do what you wrote](http://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/repackage-classifier.html).

**Comment by osiegmar** [comment]
No, the repackage classifier generates a application-only jar (good) and a fat-jar with application & dependencies (bad). That doesn't help to reduce the layer size of docker images.

I'd like to have something like:

app-dependencies.jar - that contains only BOOT-INF/lib/ directory
app.jar - that contains only BOOT-INF/classes/ and org/springframework/boot/loader/ directories

**Comment by caneraydinbey** [comment]
+1

**Comment by philwebb** [comment]
We've had similar requests in the past and I think I may have even read a blog post about this at one point. At this point I'm not keen to complicate our build plugins for this use-case. Since we have Maven, Gradle and even an Ant plugin the maintenance burden for us becomes quite high.

I think the best approach in this case is to post-process your Spring Boot fat jar as part of your docker build process. Another option might be something like [capsule](https://github.com/puniverse/capsule) which downloads dependencies as they are needed.

We'll try to think some more about docker after we get Spring Boot 2.0 finished, but for now I'm afraid we're not going to have time to tackle this.

**Comment by wilkinsona** [comment]
I suspect that this is the blog post that Phil was recalling: http://bsideup.blogspot.co.uk/2015/04/spring-boots-fat-jars-vs-docker.html

**Comment by philwebb** [comment]
Also https://www.infoq.com/news/2016/08/fatjars-woes-at-hubspot

**Comment by emersonf** [comment]
Also https://accenture.github.io/blog/2016/10/28/smart-java-docker-containers.html
