### ISSUE TITLE
@SpringBootTest loading context multiple times in boot 1.4 version

### ISSUE THREAD

**Issue by gkprasad0308** [spring-projects/spring-boot#6838]
I have two spring boot main classes in my application like `App.java` and `AppFit.java`, in first one I excluded the second one and I will use fitnesse only for my fitnesse test cases and fitnesse works fine. My junit test cases suppose to use `App.java` (since I mention in my test case to load that) but some reason it is loading first App and then `AppFit` is loading which is leading to fail my test cases.

Here is my sample code,

```java
@Profile(value = { "h2", "orcl" })
@SpringBootApplication
@ComponentScan(basePackages = "com.myapp.*", excludeFilters = @ComponentScan.Filter(type = FilterType.REGEX, pattern = "com.myapp.application.fitnesse.*"))
@EntityScan(basePackages = "com.myapp.domain.*")
@EnableJpaRepositories(basePackages = "com.myapp.repo)
@PropertySource("classpath:/application.properties")
public class App extends SpringBootServletInitializer
{
}
```

```java
@Profile(value = { "fit" })
@SpringBootApplication
@ComponentScan(basePackages = "com.myapp.*")
@EntityScan(basePackages = "com.myapp.domain.*")
@EnableJpaRepositories(basePackages = "com.myapp.repo)
@PropertySource("classpath:/application.properties")
public class AppFit 
{
}
```

And my base test case where in all my test cases extends this,

```java
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(classes=App.class)
public class BaseTest{
}
```

by the way I have mentioned the active profile in my `application.properites` as `h2`.

I am struggling with this problem from last two days,If you can provide the solution that would really great!

Regards
Kri

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Slahser** [comment]
I got the same problem : 

the annotation run app several times, 

and there is `spring-boot-maven-plugin` suggested to use `pre-integration-test`& `post-integartion-test`.

so you can see the plugin instance contains several instance runs in your console... 

and i know this issue is closed so i`m finding other way to solve it..
