### ISSUE TITLE
Avoid loading test jar from ide

### ISSUE THREAD

**Issue by fernandofederico1984** [spring-projects/spring-boot#6854]
Hello I have a spring boot application that runs fine from command line. However when I run it from the ide (intellij) it fails on every http request. The problem I'm having is that from the ide a test jar (scoped as test in maven) conflicts with the hk2 jar that I have in my app.

I can't exclude hk2 classes from the test jar as it is shaded.

Of course it also happens in my tests. So my question is how do I guarantee that spring boot loads only the production jars and not the test jars. I'm afraid that my Test might no be testing the correct binary.

Having integration tests that executes the compiled application is a solution however I would like to run it from the ide without recompiling the code every time.

The test jar is testcontainers postgres 1.1.5

Thanks

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
