### ISSUE TITLE
take a long time startup  on centos

### ISSUE THREAD

**Issue by kanouken** [spring-projects/spring-boot#6873]
java -jar myproject.jar  

it will cost  about 5 mins to startup  

at follow step

`2016-09-13 16:27:01,427 [INFO] org.springframework.boot.context.embedded.AbstractFilterRegistrationBean.configure(AbstractFilterRegistrationBean.java:271)
Mapping filter: 'webStatFilter' to urls: [/*]`

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Before posting your own question, I'd recommend reading [this one](http://stackoverflow.com/questions/25660899/spring-boot-actuator-application-wont-start-on-ubuntu-vps/25669300#25669300) to see if you have the same problem and following some of the steps that are discussed for diagnosing the problem (for example, taking a thread dump when it's stuck for 5 minutes).
