### ISSUE TITLE
@JsonTest with Swagger config fails to load context

### ISSUE THREAD

**Issue by dturanski** [spring-projects/spring-boot#6879]
spring-boot 1.4.0.RELEASE - Encountered this bug working with a client and was able to reproduce it with a simple example.  

see https://github.com/dturanski/swagger-demo/tree/master/src/main/java/com/example

**Comment by wilkinsona** [comment]
That looks like a misuse of `@JsonTest` to me. It's intended for testing components that are interested purely in JSON serialisation and should be used on its own, rather than alongside `@SpringBootTest`. There's an [example test class] in one of the samples that demonstrates the intended usage of `@JsonTest`.

I think we should fail fast if someone uses `@JsonTest` and `@SpringBootTest` at the same time.

**Comment by wilkinsona** [comment]
@dturanski You also need to restructure your app a little so that slices of it can be tested individually. All of the different slices `@JsonTest`, @DataJpaTest`, etc use your main application class. If that main class directly configures something that's not part of a slice, things won't work as expected. Moving the configuration of Swagger out into a separate configuration class fixes the problem. I've opened [a pull request](https://github.com/dturanski/swagger-demo/pull/1) that hopefully shows what I mean.

**Comment by dturanski** [comment]
@wilkinsona  Re 'misuse'. I mentioned that and we studied the sample. In this case, the intention was not to test JSON serialization. The developer felt that the JSonTester would be nice for validating responses in an existing MockMVC Test. 

Re 'structure'.  The actual app has Swagger in a separate config, as this did originally. I merged it into the main class since the problem is the same.

**Comment by wilkinsona** [comment]
> The developer felt that the JSonTester would be nice for validating responses in an existing MockMVC Test.

Then you should use `@WebMvcTest` combined with `@AutoConfigureJsonTesters`.

**Comment by dturanski** [comment]
I think you're saying @JsonTest without @SpringBootTest, etc. still fails with the single config? Interesting. I'm saying, with the original annotations, the result was the same.  Anyway, we will try your suggestion. Thanks!

**Comment by wilkinsona** [comment]
> I think you're saying `@JsonTest` without `@SpringBootTest`, etc. still fails with the single config? 

Correct.
