### ISSUE TITLE
SLF4JBridgeHandler is removed after (POST) /refresh

### ISSUE THREAD

**Issue by adam-balazs** [spring-projects/spring-boot#6885]
Spring-boot v1.3.5.RELEASE

We just started to use spring cloud config and i've realized that after a `(POST) /refresh` request every logging using JUL goes to the void. I did some debugging and i saw the LoggingSystem.cleanUp() get's called after the context got refreshed which removes the JUL bridge.

**Comment by philwebb** [comment]
I think that's probably a Spring Cloud issue, I've raised https://github.com/spring-cloud/spring-cloud-commons/issues/131.

**Comment by philwebb** [comment]
@dsyer or @ssi-hu-adam-balazs Do you have a sample application we can try?

**Comment by dsyer** [comment]
Any app with spring-boot-starter-actuator and spring-cloud-starter-config. Just set up an endpoint to log to JUL, hit /refresh and hit the endpoint and see no logging. It was @wilkinsona who helped me get the other bits working, so he might have some insight as well. It seems like maybe the /refresh cycle shuts down the JUL logging because it creates an `ApplicationContext` and then closes it, like a good citizen (the close calls `cleanUp()` with nothing to re-initialize it). So it will have other side effects probably, not just JUL.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by wilkinsona** [comment]
The logging system is only cleaned up when a root context is closed. Spring Cloud needs to ensure that any context it creates and closes during the refresh cycle is a child context to avoid triggering premature cleanup of the logging system.
