### ISSUE TITLE
DefaultLogbackConfiguration hardcodes PatternLayoutEncoder

### ISSUE THREAD

**Issue by kryger** [spring-projects/spring-boot#6894]
My use case: instead of logging plain text, format the logs as JSON to be consumed and extracted by Graylog. The [Logback JSON encoder](https://github.com/logstash/logstash-logback-encoder) offers an encoder that does this transparently.

My hope was that it would be easy to substitute the encoder used in Boot's default ConsoleAppender, sadly it turned out not to be the case:
- `PatternLayoutEncoder` is [hardcoded inside `DefaultLogbackConfiguration`](https://github.com/spring-projects/spring-boot/blob/10012cfddc5479ee9a5cbe98bfe4f76483965bd1/spring-boot/src/main/java/org/springframework/boot/logging/logback/DefaultLogbackConfiguration.java#L117-L122) so there's no way to use a different `Encoder`
- it's not possible to retrieve the `ConsoleAppender` from the root `Logger` and change its `Encoder` at a later stage, initialisation fails due to an NPE somewhere in Logback's internals *(I had no time to investigate this in detail, apologies)*
<details>
<summary>simplified encoder replacement code</summary>
<pre>
        LogstashEncoder jsonEncoder = new LogstashEncoder();
        jsonEncoder.setContext(loggerContext);
        ConsoleAppender<ILoggingEvent> consoleAppender = (ConsoleAppender<ILoggingEvent>) root.getAppender("CONSOLE");
        consoleAppender.setEncoder(jsonEncoder);
        // also tried different combinations of ctxt.reset(), appender.start(), etc. to no avail
</pre>
</details>
- we ended up resetting the `LoggingContext` and creating a brand new ConsoleAppender with the JSON Encoder, the downside is that there doesn't seem to be an easy way to apply our existing Spring Boot "logging.level..." config to this new appender

Enhancement proposal: I thought it would be in spirit of Spring Boot to allow easy substitution of the encoder used (preferably through a flag/property), even if - admittedly - it could mean stretching the "default" in `DefaultLogbackConfiguration` a bit.

----------

Happy to give it a stab after hearing project maintainers' opinion (and hints and pointers, ideally!)

**Comment by wilkinsona** [comment]
I don't think we really want to try to get into configuring an encoder via properties. Our intention is that you want this level of customisation then you should use `logback.xml` or `logback-spring.xml`. There are a [number of files](https://github.com/spring-projects/spring-boot/tree/master/spring-boot/src/main/resources/org/springframework/boot/logging/logback) that you can include to avoid having to replicate all of the configuration.

If anything needs to be improved, then I think it should be in the structure and make up of those files rather than in `DefaultLogbackConfiguration`.

@kryger Can you please take a look at a file-based approach and see if it meets your needs?

**Comment by kryger** [comment]
Thanks for the suggestion, I hadn't considered XML configuration as was an existing application needing new functionality, it turned out it was quite easy to achieve using logback-spring.xml. Gist for anyone interested: https://gist.github.com/kryger/aa9e25999f17683f3bd1cec1256ddbbe

Closing as my problem's solved and the feature

**Comment by wilkinsona** [comment]
Excellent. And thanks for sharing the Gist so others can see what you did 👍
