### ISSUE TITLE
Merge SecurityFilterAutoConfiguration in SecurityAutoConfiguration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#6905]
There's no real reason to have `SecurityFilterAutoConfiguration` to run if `SecurityAutoConfiguration` is excluded. Right now, to exclude security completely both these auto-configuration should be excluded (see #6861). It would be nicer to have only the latter to exclude.

This also simplifies the code quite a lot.

**Comment by rwinch** [comment]
I agree it would be ideal if there was only a single AutoConfiguration to exclude, but this poses some problems.

This is related to the changes for #3703 which requested that we always set the order property of the Spring Security Bean. Specifically, we need to ensure that `SpringBootWebSecurityConfiguration` is ran before `SecurityFilterRegistrationConfiguration` because `SecurityFilterRegistrationConfiguration` is conditional on a `Bean` that *may* be created by `SpringBootWebSecurityConfiguration`

When discussing this with @dsyer his recommendation was to create a separate Auto Configuration so that we could control the ordering.

**Comment by snicoll** [comment]
That's no longer relevant now the security auto-config overhaul has been done.
