### ISSUE TITLE
ResourceHandlerRegistrationCustomizer  missing in Spring 1.4.0

### ISSUE THREAD

**Issue by stavsap** [spring-projects/spring-boot#6989]
i have upgraded to Spring 1.4.0 from 1.3.5, and my Class that extends WebMvcAutoConfigurationCustomizer don`t have default constructor anymore and requires constructor with other classes, one of them is ResourceHandlerRegistrationCustomizer that is missing from spring packages. i cant find it anywhere... and can`t make build.

this is my current dependencies in gradle

dependencies {
         compile('org.springframework.boot:spring-boot-autoconfigure')
	compile('org.springframework.boot:spring-boot-starter-data-jpa')
	compile('org.springframework.boot:spring-boot-starter-web')
	compile group: 'com.jcraft', name: 'jsch', version: '0.1.53'
	runtime('org.postgresql:postgresql')
	runtime('com.h2database:h2')
	testCompile('org.springframework.boot:spring-boot-starter-test') 
}

please advise

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Before posting on Stack Overflow, please see [this existing question and answer](http://stackoverflow.com/questions/38790681/cannot-extend-webmvcautoconfigurationadapter-in-spring-boot-1-4/38794234#38794234).

**Comment by stavsap** [comment]
it seems as ResourceHandlerRegistrationCustomizer interface is private in static class EnableWebMvcConfiguration what result in crippling the ability to extend the WebMvcAutoConfigurationCustomizer class without providing null for ResourceHandlerRegistrationCustomizer. is such ability deprecated in 1.4.0?

**Comment by wilkinsona** [comment]
Please read the question and answer on Stack Overflow. It explains what you should do. If you have further questions then please ask them on Stack Overflow.

**Comment by stavsap** [comment]
the link provided helps and solves some issues, thank you
