### ISSUE TITLE
Tidy up the dependency management for Reactor

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7028]
Spring Framework 5's `spring-web-reactive` module uses `reactor-core` 3.0.2.RELEASE but our dependency management provides 2.0.8.RELEASE. The other modules seem to be being phased out so we need to figure out what to do with those too. Spring Framework 5 still depends on some of them (`reactor-net`, for example). We probably also need to start providing dependency management for `reactor-netty`.

**Comment by wilkinsona** [comment]
@rstoya @smaldini Can you please bring us up to speed on the versions of the various Reactor modules and how they're being used now and will be used in the future by Spring Framework 5?

**Comment by wilkinsona** [comment]
@garyrussell @artembilan This is likely to affect Spring Integration too.

**Comment by snicoll** [comment]
We decided that reactor will provide a similar bom as what we have for spring framework. We should get going on this IMO. @smaldini any ETA for that?

**Comment by smaldini** [comment]
I planned to address that concern before M4 to leave some time to organise ourself in terms of IPC modules and extra addons. Do we need to anticipate it over the next week or so?

**Comment by bclozel** [comment]
By the next milestone, Spring Framework will only depend on Reactor 3.0+ - the remaining dependency on `reactor-net` should disappear with [SPR-14531](https://jira.spring.io/browse/SPR-14531).

**Comment by wilkinsona** [comment]
Thanks, @bclozel.

@rstoyanchev Would it be possible to tackle SPR-14531 early on in your M3 development work? I'd really like to get Boot and the Platform's dependency management updated as there are too many unknowns in terms of compatibility at the moment.

**Comment by smaldini** [comment]
@wilkinsona I will make sure I'll sync with @rstoyanchev to close on a timely fashion (we already did outline the pieces of work last week)

**Comment by rstoyanchev** [comment]
@wilkinsona I've [had a branch](https://github.com/rstoyanchev/spring-framework/commit/33393828f3dc7f0d063824b0314f87106d37c755) with complete changes but not all tests passing since late M2. We're talking `reactor-core` 3.0+ indeed but also `reactor-netty` -- a new module replacing `reactor-net` -- which is at version 0.5.1. You can see the exact dependency changes in my branch. There is also a 3rd dependency on `reactor-codec` but that will most likely go away.

Stephane and I are discussing changes to the TCP client so still need go through one or two iterations but should be able to complete this for M3. It's definitely high on my priority list.

**Comment by artembilan** [comment]
When time comes, we definitely will fix our Reactor 2.0 story to the appropriate fixes in SF for Reactor 3.0:
https://jira.spring.io/browse/INT-4125.

Everything rest in Spring Integration is already based on Reactor 3.0, BTW.
