### ISSUE TITLE
Unable to connnect Multiple DataBases through application.yml

### ISSUE THREAD

**Issue by HariKiran9** [spring-projects/spring-boot#7047]
My requirement needs a multiple datasources and i have configured with in application.yml. I am using Spring-Boot with JHispster in the project. i am using Spring-Boot's @ConfigurationProperties(prefix = "spring.datasource.mydb1.hikari") with multiple @ConfigurationProperties(prefix = "spring.datasource.mydb2.hikari") but unable to connect to the second Data Base.
Sample application.yml
spring:
          datasource:
                mydb1:
                       primary: true
                        url: DataBase URL1
                        name:
                        username: myusername1
                        password: mypassword1
                mydb2:
                     url: DataBase URL2
                     name:
                     username: myusername2
                     password: mypassword2

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
