### ISSUE TITLE
Upgrade to javax.jms:javax.jms-api 2.0.1

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7049]
Spring Framework 5.0 compiles against the JMS 2.0 API, so we should align our dependency management.

**Comment by wilkinsona** [comment]
Active MQ doesn't support JMS 2.0 (see [AMQ-5383](https://issues.apache.org/jira/browse/AMQ-5383)). While the coordinates of the JMS API jar have changed between 1.1 and 2.0 and, therefore, we could provide dependency management for both, I'd prefer not to do so. The alternative would be to drop auto-configuration for ActiveMQ until it supports JMS 2.0.

Artemis supports 2.0 so we'd still have some JMS support.

@snicoll what do you think?

**Comment by snicoll** [comment]
I have had hoped that the donation of HornetQ to Apache would finally clear the air and we'd have one open source JMS broker to work with. Turns out that [ActiveMQ is still an active project while being on the same umbrella](http://activemq.apache.org/how-does-activemq-compare-to-artemis.html). 

I'd be in favour of removing activemq which is a strong and personal preference. I am sure lots of our users won't be happy about. On the other hand, we're certainly not bothered by that and [Spring Framework 5](https://spring.io/blog/2015/06/10/feedback-welcome-spring-5-system-requirements) still relies on 1.1 so I'd stick with that as well.

**Comment by wilkinsona** [comment]
Based on https://jira.spring.io/browse/SPR-13793 we need to upgrade the JMS API to 2.0. Furthermore, a 1.1-compatible broker will work with the 2.0 API so there's no need to remove our ActiveMQ support.
