### ISSUE TITLE
@SpringBootTest and autowiring MockMvc (#2)

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#7112]
This is a followup to #6008. While the resolution to that added a note *to the `@WebMvcTest` section*, the place I as a user was rereading was section 40.3, describing "You can use the `webEnvironment` attribute". Additionally, the Javadoc for `WebEnvironment` suggests that the default behavior of `@SpringBootTest`, with no parameters or extra configuration, is to generate a MockMvc setup if the Servlet API is on the classpath. Adding `@WebMvcTest` results in a bootstrapper conflict.

From a pragmatic/performance standpoint, not-Web-by-default probably makes sense, but carrying the `WebEnvironment` on the `@SpringBootTest` annotation implies that that annotation is sufficient to kick off a Web environment. Since it is not, both the main doc section on `@SpringBootTest` and the Javadoc should note that, and I'd like to suggest adding a boolean flag to `@SpringBootTest` to invoke the same effect as adding `@AutoConfigureMockMvc` or otherwise clarifying the annotation's API to make the additional requirement logically visible from the source.

**Comment by wilkinsona** [comment]
>  Additionally, the Javadoc for WebEnvironment suggests that the default behavior of `@SpringBootTest`, with no parameters or extra configuration, is to generate a MockMvc setup if the Servlet API is on the classpath

It sounds like you're confusing a mock servlet environment – which is the term used in the javadoc – with `MockMvc`. The latter can be used to test a web application that's running in the former.

> From a pragmatic/performance standpoint, not-Web-by-default probably makes sense, but carrying the `WebEnvironment` on the `@SpringBootTest` annotation implies that that annotation is sufficient to kick off a Web environment.

It is sufficient and that is exactly what happens. For example, anything that is `@ConditionalOnWebApplication` will be active.

Perhaps we could avoid some of the confusion by updating the description of `MOCK` in [section 40.3](http://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/htmlsingle/#boot-features-testing-spring-boot-applications) to mention that it can be used in conjunction with `@AutoConfigureMockMvc` if you want to use `MockMvc` for testing?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kpdonn** [comment]
I was confused by this in the same way the other day. Eventually I figured it out because `@AutoConfigureMockMvc` is documented in the testing section but it took a while. I think there are two reasons it's easy to miss:

1. `@AutoConfigureMockMvc` is only mentioned in the section of the documentation that is about testing specific slices of an application. I skipped over those sections the first few times I was going through the documentation because I knew I wanted to be testing my full app (minus the overhead of running the real servlet container) instead of just a slice.

2. It's not clear from the documentation what the point of `@SpringBootTest(webEnvironment=WebEnvironment.MOCK)` would be if you aren't using `MockMvc` with it. That made me assume that it would configure it by default. Even now I don't really understand what I would be gaining over `@SpringBootTest(webEnvironment=WebEnvironment.NONE)` if I wasn't using `MockMvc`.

I definitely think adding a note in 40.3 `MOCK` description about needing `@AutoConfigureMockMvc` to use `MockMvc` would help a lot.

**Comment by wilkinsona** [comment]
> Even now I don't really understand what I would be gaining over @SpringBootTest(webEnvironment=WebEnvironment.NONE) if I wasn't using MockMvc.

Any beans that are `@ConditionalOnWebApplication` will not be created if you use `WebEnvironment.NONE`
