### ISSUE TITLE
New fat jar layout introduces problems to traditional classpath resource locating

### ISSUE THREAD

**Issue by holgerstolzenberg** [spring-projects/spring-boot#7118]
We recently upgraded from spring-boot `1.3.7` to `1.4.1`. In our project we use WRO4J to process static LESS and JS resources that are located via classpath.

Using the Spring Boot Gradle plugin with `bootRun` no problem occured during development. But then the app broke when deployed as finally build fat jar on the staging environment.

It took me quite some time to figure out the problem, because all resources where there until I noticed that the application specific JS and LESS where not part of the minified resources.

In the end it relates to the new fat jar layout with the `BOOT-INF` directory. This causes the classpath resources to have different locations for development and packaging. This is something I do not really like as it forces me to maintain to different URLs of the same resource in the WRO4J config. The following example showcases that:

Spring Boot 1.3.x
```groovy
'ep' {
  css('classpath:static/app/app.less')
  js('classpath:static/app/**.module.js')
  js('classpath:static/app/**.js')
}

app {
  groupRef('libs')
  groupRef('ep')
}
```

and now with Spring Boot 1.4.1
```groovy
'ep-dev' {
  css('classpath:static/app/app.less')
  js('classpath:static/app/**.module.js')
  js('classpath:static/app/**.js')
}

'ep-prod' {
  css('classpath:BOOT-INF/classes/static/app/app.less')
  js('classpath:BOOT-INF/classes/static/app/**.module.js')
  js('classpath:BOOT-INF/classes/static/app/**.js')
  }

app {
  groupRef('libs')
  groupRef('ep-dev')
  groupRef('ep-prod')
}
```

There are also some issues with WRO4J classpath locators as a URI like `classpath:**/static/app/app.less` might help but did not work (for me).

In the end this is no real issue but I think it is worth a discussion to think about the fact that the classpath locations differ for
`gradle bootRun` and `java -jar xyz.jar`.

**Comment by wilkinsona** [comment]
It's hard to say what's happening without knowing how the `classpath:…` configuration is being used. Given that you're referencing resources via the class path, which is the recommended approach, the changes in the layout between 1.3 and 1.4 should not have had any effect.

In 1.3, resources were packaged in `/static` and the root of the jar was on the class path. In 1.4, resources are packaged in `/BOOT-INF/classes/static` and `/BOOT-INF/classes` is on the class path. This means that `classpath:static/…` points to the same resources in both cases. If that's not the case then there's a bug in whatever's performing the resource resolution.

Rather than me speculating and guessing any further, can you please provide a small example that illustrates the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
