### ISSUE TITLE
Improve analysis of Tomcat connector start failures by using new throwOnFailure attribute

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7130]
Tomcat 9 [now includes](http://svn.apache.org/viewvc?view=revision&revision=1763769) an attribute that means that a connector start failure will result in an exception being thrown. We should catch that exception and use it to throw a specific exception that can then be analysed.

**Comment by mbhave** [comment]
@wilkinsona I wasn't able to get hold of the bind exception even after setting `throwOnFailure` to `true`. For the primary connector, we set `bindOnInit` to false so something like a `BindException` will be thrown on `start` instead of `init`. However, even though `connector.start()` [throws a `LifecycleException`](https://github.com/apache/tomcat/blob/d7a770acf8761c42958b56d6ce4864e32f8a9957/java/org/apache/catalina/util/LifecycleBase.java#L438) when the flag is set, [it is caught and logged](https://github.com/apache/tomcat/blob/d7a770acf8761c42958b56d6ce4864e32f8a9957/java/org/apache/catalina/core/StandardService.java#L227) by `addConnector`.

**Comment by wilkinsona** [comment]
That's a shame. I should have looked more closely at the change when it was made. I've opened [another Tomcat issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=63358) to see if a change can be made for this scenario as well.

**Comment by wilkinsona** [comment]
https://bz.apache.org/bugzilla/show_bug.cgi?id=63358 has been fixed and will be included in Tomcat 9.0.20.

**Comment by wilkinsona** [comment]
This is no longer blocked as Tomcat 9.0.20 has been released and we have upgraded to it.
