### ISSUE TITLE
Load Configuration run-time from dynamoDB

### ISSUE THREAD

**Issue by nitin02** [spring-projects/spring-boot#7139]
As shown in the below documentation there are several ways to externalize Configuration,

http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html 

However, I am dealing with a special case where spring boot config needs to load from AWS dynamoDB i.e loading all Config from dynamoDB instead of using the default application.properties / application.yml (or any other property source file).

How can one achieve this?

I can see that `ConfigFileApplicationListener ` is the place where this loading happens. Is there any way to override this and use one's own custom logic for ingesting properties or is there any other better way?

If there is a way directly through Netflix Archaius (https://github.com/Netflix/archaius/wiki/Dynamo-DB), it would be very helpful.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Also, you might want to have a look to [Spring Cloud Netflix](https://cloud.spring.io/spring-cloud-netflix/)

**Comment by nitin02** [comment]
Referencing the question here:

http://stackoverflow.com/questions/39972254/spring-boot-load-configuration-run-time-from-dynamodb
