### ISSUE TITLE
StatsDMetricWriter generates invalid StatsD messages when incrementing negative deltas

### ISSUE THREAD

**Issue by KamikaZeeFu** [spring-projects/spring-boot#7165]
Hi,

when using statsD export in a spring cloud app the StatsDMetricWriter will generate invalid messages for counters.
The root issue is that counters reported by servo/netflix components are reset periodically, for example a `counter.foo.error` with a value of 2 might be followed by a `counter.foo.error` with a value of 0.
The metric collection logic will (correctly) calculate a delta of -2.
This delta value will be passed to the `StatsDMetricWriter` which will in turn pass this to the `StatsDClient`.

This is a problem with a statsD backend that is strict (i.e. counters only ever increase).
Messages with negative counter values cannot be parsed by Telegraf (a statsD backend) for instance, resulting in many error messages.

My proposed fix would be to reject negative counter values in `StatsDMetricWriter.increment()`.

**Comment by philwebb** [comment]
@dsyer Is this sensible?

**Comment by KamikaZeeFu** [comment]
I ran some further tests and it seems to be mainly the telegraf backend that doesn't support decreasing counters. 
I also filed an issue with them but until they fix it the negative counters remain a problem for me. 

Those counters from spring cloud Netflix behave differently than all the standard counters spring boot offers

**Comment by dsyer** [comment]
Negative increments should be impossible in Spring Boot as well, so ignoring them is probably not going to solve any problems. Since `counter.foo.error` is probably not an actual metric from Spring Cloud, maybe you could help move this forward by providing a sample app that misbehaves, so we can see the problem in action?

**Comment by KamikaZeeFu** [comment]
Sure thing, as I said, the misbehaving counters originate from spring-cloud-netflix, using any netflix component together with actuator will trigger the issue.

Demo Project:
https://github.com/KamikaZeeFu/boot-7165

**Comment by dsyer** [comment]
Thanks. I'll have a look. You can fix it by switching off the servo config (`spring.metrics.servo.enabled=false` or exclude it from the classpath).

**Comment by wilkinsona** [comment]
I was about to fix this by rejecting negative increments, but that doesn't make sense. StatsD supports negative delta to a counter as shown by its `decrementCounter(String)` method which is equivalent to calling `count(String, long)` with a value of -1.

Given that the problem is actually with Telegraf, fixing it in a StatsD writer doesn't make sense as a general purpose solution. If it's appropriate in your specific situation to suppress negative increments, then you can do so by providing a bean that's a custom `StatsDMetricWriter` subclass that overrides `increment(Delta)`.
