### ISSUE TITLE
How to stop log output, when compile app.jar to an execute file, logging.file doesn't work

### ISSUE THREAD

**Issue by wanggang1987** [spring-projects/spring-boot#7188]
Hi guys
        
Thanks for great work on spring boot. It's really wonderful. I have a question about spring boot log:

 I add 
```
<plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
		<version>1.3.3.RELEASE</version>
		<configuration>
			   <executable>true</executable>
		</configuration>
</plugin>
```
in my pom file , and compile it with `mvn clean install package spring-boot:repackage`
And in my project there is a logback-spring.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<include resource="org/springframework/boot/logging/logback/base.xml"/>
	<appender name="dailyRollingFileAppender" class="ch.qos.logback.core.rolling.RollingFileAppender">
		<File>logs/website.log</File>
		<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
			<!-- daily rollover -->
			<FileNamePattern>logs/website.log-%d{yyyy-MM-dd}</FileNamePattern>
			<!-- keep 30 days' worth of history -->
			<maxHistory>1000</maxHistory>         
		</rollingPolicy>
		<encoder>
			<Pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{35} - %msg %n</Pattern>
		</encoder>
	</appender>
	<root>  
		<appender-ref ref="dailyRollingFileAppender" />  
	</root>  
</configuration>
```

I upload it to AWS server, and start it by `service app start`
Then i got 2 log files:`/var/log/website.log` and `log/website.log`

I tried to add `logging.path=/dev/null` to disable `/var/log/website.log` out put, but it doesn't work.

Please have a look and help.

**Comment by philwebb** [comment]
When you run as a service the initialization script will redirect output to `/var/log/<appname>.log`. Most people have their application log to sysout, then rely on this redirect.

Since you want to control logging yourself you will need to disable the redirection. I think you can do this by adding the following to your Maven config:

```
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<embeddedLaunchScriptProperties>
			<logFolder>/dev/null</logFolder>
		</embeddedLaunchScriptProperties>
	</configuration>
```

If that doesn't work, you may need to write a custom your own custom launch script that doesn't redirect stdout to the log. 

See [this section of the docs](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#deployment-script-customization) for details.

**Comment by wanggang1987** [comment]
@philwebb Thanks for your help,  have tried embeddedLaunchScriptProperties ,but it doesn't work.
And i will write a new launch script.
