### ISSUE TITLE
Create H2 TCP server auto-configuration

### ISSUE THREAD

**Issue by bilak** [spring-projects/spring-boot#7190]
will send PR

**Comment by bilak** [comment]
Help with test welcome.

**Comment by wilkinsona** [comment]
We intend H2 to be used as an in-memory database and mostly just during development and typically wouldn't expect remote clients to be connecting to it.

Can you please describe your use case for H2's TCP server and why you think it might be generally useful to Spring Boot's users?

**Comment by bilak** [comment]
@wilkinsona I'm using h2 for more than development and it's useful to have it started while starting microservice. There are few requests on web where people are asking to start tcp server at spring application start. And for me it's annoying to use web console. I'd better use separate tool that will connect to tcp server if possible.

**Comment by philwebb** [comment]
Boot starting the database server seems a little unusual to me. For all other databases we expect that the server is running already. It's still not clear to me exactly what the use case is for this.

**Comment by bilak** [comment]
The only use case which I have currently is service which run inside docker. For the possible smallest docker image I'd like to use h2 database because it's lightweight and docker doesn't need any additional layer for db installation (mysql, postgre, ...). So I can only extend some JDK container.  In case I want to control data in database (if something went wrong) I have open tcp port and I can connect to it. As I said I don't like the h2 web console so this case is better for me.

**Comment by wilkinsona** [comment]
That feels like an edge case to me, and something that won't be of general interest to Boot's users. I don't think we should add auto-configuration for H2's TCP server.

**Comment by philwebb** [comment]
Me too I'm afraid. Thanks for the suggestion all the same.

**Comment by tpischke** [comment]
Too bad, I need this too.

**Comment by bedag-moo** [comment]
Use Case: When using H2 as in-memory database during development, it can be helpful to connect to the database using DBVisualizer or IntelliJ's SQL console to verify the state of the database. This is admittedly a rather rare case, and it is reasonably easy to bootstrap H2 and register the DataSource by hand, but it would be nicer if we could just set an application property for the desired port :-)

**Comment by andreysaksonov** [comment]
why ban H2 in production? it is faster and more feature-rich than derby (aka javadb) which I saw zillion times in production

**Comment by robdbirch** [comment]
Yes, I would so enjoy this feature. It would be so easy just to refresh the database tool in IntelliJ and double click on the table to see the data. The H2 console is a royal pita, constantly going to the browser, constantly hitting connect, constantly select tables,  constantly forgetting to clear and existing query, then clearing the previous query, reselecting the table again, re-hitting run, click, click, click, type, type ... Why do using the tools need to be as verbose as using Java?  If I could use the IntelliJ database tool in IDE and hit hit the refresh and pleasantly db browse by double click table, which will automatically read table and display, no going to the browser, no need for clearing of query, ability to save queries. Never leaving the IDE and a much more productive for development db browsing experience. Though actually letting any other db browser tool connect is h2,  would be an improvement. On the plus at least H2 does have a console tool. There seems to be many threads in Stackoverflow and snippet hacks on other developers web sites that may have worked at one time. I don't believe its as niche as mentioned. As for any poor soul that would attempt use H2 in production, that's there choice, please don't try to protect and hinder the rest of us because what some insane thing might be done. It's not like you're giving out AR-15's. :)
