### ISSUE TITLE
Bug report: IDE can not suspend on breakpoints after upgrade to Spring Boot 1.4.1

### ISSUE THREAD

**Issue by eyakcn** [spring-projects/spring-boot#7194]
I hava two existing project which was using 1.4.0, after upgrade to 1.4.1, the IDE such as IntelliJ and Eclipse can not debug any more.

I tried to downgrade to 1.4.0 and everything is OK, I can debug under both IDE.

I don't understand why?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
