### ISSUE TITLE
How to use remote elasticsearch instead of embedded one

### ISSUE THREAD

**Issue by tarunendra** [spring-projects/spring-boot#7220]
I want to use external elasticsearch running instead of using embedded one. i tried enabling couple of properties in application.properties but that didn't work.

I can see elasticsearch running and I'm able to do things with that but somehow my spring application is not connecting to that one, below configuration I give.  

spring.data.elasticsearch.properties.http.enabled=true
spring.data.elasticsearch.properties.host = localhost
spring.data.elasticsearch.properties.port = 9300

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
