### ISSUE TITLE
WebServicesAutoConfiguration has unuseful conditionals

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#7244]
Spring Boot 1.4.1

In particular, `ServletRegistrationBean` is covered by `@ConditionalOnMissingBean(WsConfigurationSupport.class)`.

However, `WsConfigurationSupport` does not provide a `ServletRegistrationBean`. This auto-configuration is therefore useless if you need to override something not exposed by `WsConfigurer`.

**Comment by OrangeDog** [comment]
As a workaround, you can add `@Import(WebServicesAutoConfiguration.class)` to bypass the conditionals.

**Comment by wilkinsona** [comment]
The user providing a `WsConfigurationSupport` bean, either by subclassing it or, more usually, using `@EnableWs` is the signal for Spring Boot's auto-configuration to back off as the user wants to take control of the configuration. That includes the configuration of the message dispatcher servlet. In short, the behaviour you're seeing is intentional and useful for some.

Rather than unconstructively describing something as useless (a common theme in the issues you've raised), perhaps you could describe what you're actually trying to do?

**Comment by OrangeDog** [comment]
I'm trying to minimise my configuration.
I need to override a single bean from `WebServicesAutoConfiguration`.
However, I then need to copy-paste (or actually, just do the workaround) the `ServletRegistrationBean` from the auto-configuration.

I don't see any reason why the automatic addition of `@EnableWs` and `ServletRegistrationBean` should be tied together like this.

**Comment by philwebb** [comment]
Without the `@ConditionalOnMissingBean(WsConfigurationSupport.class)` there would be no easy easy way for a user to _not_ register the `messageDispatcherServlet`. We could go for specific bean names I suppose (much like we do in `DefaultDispatcherServletCondition`) but that would add complexity.

I think I prefer the current situation, even if it does involve some copy/paste for the `messageDispatcherServlet` registration.
