### ISSUE TITLE
1.4.1 doesn't honor server.port

### ISSUE THREAD

**Issue by smallufo** [spring-projects/spring-boot#7252]
It works In 1.4.0
```
mvn spring-boot:run -Drun.profiles=prod -Dserver.port=8091 
```
It listens port 8091 , but after upgrading to 1.4.1 , it doesn't work , I have to change to  :  

```
mvn spring-boot:run -Drun.profiles=prod -Drun.jvmArguments='-Dserver.port=8091' 
```

It works.

**Comment by snicoll** [comment]
You are probably using devtools and devtools does not work unless the JVM is forked. As a convenience, we detect this now and we make sure to fork the process. That's why the system property of the maven process isn't available anymore. 

You can override that behaviour by adding `<fork>false</fork>` to the Spring Boot's plugin configuration.

**Comment by smallufo** [comment]
But , why `-Drun.profiles=prod` is able to pass , but `-Dserver.port=xxx` unable ?

**Comment by snicoll** [comment]
If you have questions @smallufo please ask them on stackoverflow. The former is read by the Spring Boot maven plugin and the latter by the spring boot application.
