### ISSUE TITLE
Create Tomcat JDBC pool when DataSource bean is ready

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#7255]
Before invoking `getConnection()` for the first time, Tomcat JDBC pool is not created.

It would be nice to create Tomcat JDBC pool when `DataSource` bean is ready.

This is a sample project: https://github.com/izeye/spring-boot-throwaway-branches/tree/jdbc-mysql

This is the coordinate of the test showing this issue: https://github.com/izeye/spring-boot-throwaway-branches/blob/jdbc-mysql/src/test/java/com/izeye/throwaway/ApplicationTests.java#L38

**Comment by snicoll** [comment]
> It would be nice to create Tomcat JDBC pool when DataSource bean is ready.

Why? What's the actual problem you're facing?

**Comment by izeye** [comment]
@snicoll If not, the first request will be responded slowly due to the cost of the pool creation.

**Comment by izeye** [comment]
@snicoll May I open a PR for this issue?

**Comment by snicoll** [comment]
Of course Johnny, thanks a lot for your efforts!

**Comment by izeye** [comment]
@snicoll Thanks! I will give it a try 😄

**Comment by snicoll** [comment]
@izeye while you're doing this, it would be interesting to see if other connection pools we support exhibit the same issue. I don't think that's the case but if we do this for tomcat JDBC, we should do it for others. An alternative would be to offer a boolean flag to initialize the pool early. Maybe that already exists and we can just document that?

**Comment by izeye** [comment]
@snicoll Okay. Although I'm not familiar with the other JDBC connection pools, I'll try to check them all. In the meantime, I'll create a PR first to be reviewed if the approach I took is right for you.

**Comment by shakuzen** [comment]
From my memory, HikariCP exhibits this same behavior as well.

**Comment by izeye** [comment]
@snicoll I checked both HicariCP and DBCP2 with the following tests:

https://github.com/izeye/spring-boot-throwaway-branches/blob/jdbc-mysql-with-web-with-hikari/src/test/java/com/izeye/throwaway/ApplicationTests.java
https://github.com/izeye/spring-boot-throwaway-branches/blob/jdbc-mysql-with-web-with-dbcp2/src/test/java/com/izeye/throwaway/ApplicationTests.java

and they all have the same behaviour with Tomcat JDBC connection pool.

I'm curious why this is default because I think a connection pool is better to be ready with its initial size before the first request. Am I missing something?

**Comment by philwebb** [comment]
Having discussed this a little we're not sure that we should change the default behavior. The fact that all pools work in the same way suggests that we'd be going against the grain if we tried to prepare the pool early.

I think if early pool population is required it should probably be done on a per application basis.

**Comment by izeye** [comment]
@philwebb Thanks for the feedback. Is it okay if it was opt-in, not default? I still think it's useful for initial requests, especially for time-constrained applications.

**Comment by philwebb** [comment]
@izeye We're a little reluctant to add it in general. It feels like we'd be working against the pool implementations. Even if the first request is processed a little faster, whenever the pool needs to be expanded you'll face the same type of delay. @snicoll or @wilkinsona might want to comment further but I think I'd rather not add something to Boot that we'll need to support.

I wonder if some of the pool implementations might want to look at this kind of support.

**Comment by izeye** [comment]
@philwebb Okay, I agree with the point that this belongs to pool implementations.

Thanks for the quick response!

**Comment by snicoll** [comment]
Thanks for your work again Johnny, much appreciated!

**Comment by shakuzen** [comment]
@philwebb I don't think there is any way for the pool implementations to know when Spring Boot (or anything else) is done setting properties on the `DataSource` object for it to be able to achieve this. There is no `afterPropertiesSet()` type method. Even if there were, @izeye's proposed implementation would be changed from calling `getConnection()` to the new `afterPropertiesSet()` method, I would imagine.

> Even if the first request is processed a little faster, whenever the pool needs to be expanded you'll face the same type of delay.

This depends on the access and pool configuration. HikariCP, for example, acts as a fixed-size pool by default, so upon first request it will create the 10 (default) max connections - though the first request will only have to wait for the first connection to be ready. The only time a delay would be experienced after this point due to connection creation is if all the connections are borrowed with calls to `getConnection()` waiting and a connection reaches its max lifetime. In this scenario, generally speaking, only the first request to the application is taking longer while a DB connection is established.
