### ISSUE TITLE
How can I add my custom type converters to SpringBoot？

### ISSUE THREAD

**Issue by zjcscut** [spring-projects/spring-boot#7260]
config custom converters by using XML properties like this：
```
<mvc:annotation-driven conversion-service="factoryBean" />
<bean class="org.springframework.context.support.ConversionServiceFactoryBean" id="factoryBean" >
    <property name="converters">
        <list>
            <bean class="com.mvc.convertor.MyConvertor" />
        </list>
    </property>
</bean> 
```
Here 'com.mvc.convertor.MyConvertor' implements org.springframework.core.convert.converter.Converter.
And how can I make this work by using SpringBoot？
Thanks!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
