### ISSUE TITLE
spring boot mail chinese filename's attachment was send error

### ISSUE THREAD

**Issue by lilaizhencn** [spring-projects/spring-boot#7305]
now i used spring boot 1.4.1 ,now i have a task ,send chinese fileName's attachment( .xls file),but received a attachment is  tcmime.xxx.xxx.xxx.bin，so i google , MimeUtility.encodeWord and MimeUtility.encodeText maybe resolve this question , but these method also can't resolve my question.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
