### ISSUE TITLE
Spring boot launch script isRunning() function does not consider processes in defunct state

### ISSUE THREAD

**Issue by dvdb** [spring-projects/spring-boot#7332]
The current implementation of the isRunning() function in the lauch.script, considers a process to be running only depending on the exit status of ps. A defunct process will therefore be considered running.

A possible solution for this problem is suggested [here](http://unix.stackexchange.com/questions/13622/how-to-list-only-non-defunct-processes).

**Comment by philwebb** [comment]
I guess we could use some `grep` magic but it doesn't seem that clean. Have defunct processes caused you an issue, or was this just an observation?

**Comment by dvdb** [comment]
We run our spring boot application as an init.d service on a linux platform. 
Because the process was in defunct state, we were not able to stop or restart the service the normal way.  
Only after we manually deleted the pid file we could restart the service.  

This only happened once and probably it's rare to end up in a defunct state, but it would be nice if the launch script would handle this correctly.

**Comment by philwebb** [comment]
We can't find a particularly good way to deal with this that will be portable across Linux distributions. The `grep` magic is likely to introduce problems.

Since you're targeting a specific linux platform, I'd suggest adding a custom `launch.script` that's based on ours. You can find details of how to do that [here](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment-script-customization).
