### ISSUE TITLE
How spring-boot integrate starter package such as spring-data-rest

### ISSUE THREAD

**Issue by evilband7** [spring-projects/spring-boot#7371]
I'm digging for how spring-data-rest was integrated into spring boot.

I wanna know how it work. 
Any possible configuration file in META-INF ?

In the future I may create spring boot module to use in a company and I need to understand this.

best regards

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
