### ISSUE TITLE
Make @ConfigurationProperties use setters when present

### ISSUE THREAD

**Issue by abhijitsarkar** [spring-projects/spring-boot#7428]
Because `@ConfigurationProperties` sets fields directly in most cases, there's no way to set a default value using setters. This is a bummer because for optional values, it's often very useful to set a default. The other option would be to make it smarter so that it can handle Java 8 `Optional` fields. Currently, it can't, so the coder is forced to put ugly null checks everywhere.

**Comment by kartoffelsup** [comment]
1. Please don't use Optional fields.
2. Couldn't you set the default value in the field? i.e. `private String foo = "bar";` and for Optionals, use an Optional getter. 
```java
private String foo; 

public Optional<String> getFoo() { 
    return Optional.ofNullable(foo);
}
```

**Comment by abhijitsarkar** [comment]
`private String foo = "bar"` only works for trivial defaults. Besides, I believe I'd tried it and either the value was overwritten during binding or the binding didn't happen. Either way, it didn't work.

**Comment by wilkinsona** [comment]
That sort of default should definitely work. We use it in numerous places throughout Spring Boot's codebase. Here's one example: https://github.com/spring-projects/spring-boot/blob/20d7dd574785075d5341ece495908bf1e2a2e9c7/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java#L126.

Can you provide a sample that shows the behaviour that you're seeing and that also illustrates how you'd like things to work?

**Comment by snicoll** [comment]
> Because @ConfigurationProperties sets fields directly in most case

If you mean field injection, we actually never do that with `@ConfigurationProperties`

**Comment by abhijitsarkar** [comment]
Here's an [example](https://github.com/abhijitsarkar/feign/blob/feign-java-boot/feign-core/src/main/java/name/abhijitsarkar/feign/core/model/FeignProperties.java) where I was using `postConstruct` to set valid values. Based on this discussion, I guess I could've set the values against the fields too. Like I said, I thought I'd tried that but it was almost 6 months ago and I could be wrong.
That said, this sort of field level default doesn't work for anything other than simple cases. For example, if I've an `Integer` field (age perhaps) and I want to limit it to a min (18) and a max (150), I can't do it at the field level. It's also not possible to set field defaults if the class subclasses from one that I don't have the source code for. 

I think it'll be very beneficial if `@ConfigurationProperties` checks first if the class has setters and if yes, use those instead of setting fields directly.

**Comment by snicoll** [comment]
So, for the second time, we don't set any field directly. `@PostConstruct` is invoked before the binding to the environment takes place but you should have seen that with a simple debugging session.

>  I don't know how to do logic like "if Boolean value is null, set true else if not null, use value provided" at field level.

Well, you could certainly have that logic in the `getter` even though we've done that in the past and we're not doing it anymore because it makes it hard to track what was specified and what was "determined". That's why we have `determineXYZ` in various configuration properties bean (see `DataSourceProperties` for instance). But if you intend to convey a default (and not something that was computed, what is wrong with

```java
public boolean getFoo() {
  return (this.foo != null ? this.foo : true);
}
```

As for the age thing, see #3723.

> I think it'll be very beneficial if @ConfigurationProperties checks first if the class has setters and if yes, use those instead of setting fields directly.

We always use setters and we never set fields directly, there's probably enough context now to close this one as invalid. Feel free to requalify properly the issue if that doesn't help.

**Comment by abhijitsarkar** [comment]
> So, for the second time, we don't set any field directly. 

The [doc](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-typesafe-configuration-properties) would disagree with you no matter how many times you say it.

> The getters and setters are **advisable**, since binding is via standard Java Beans property descriptors, just like in Spring MVC. They are mandatory for immutable types or those that are directly coercible from String. As long as they are initialized, maps, collections, and arrays need a getter but **not necessarily a setter since they can be mutated by the binder**. If there is a setter, Maps, collections, and arrays can be created. Maps and collections can be expanded with only a getter, whereas arrays require a setter. **Nested POJO properties can also be created (so a setter is not mandatory)** if they have a default constructor, or a constructor accepting a single value that can be coerced from String. Some people use Project Lombok to add getters and setters automatically.

> what is wrong with

```
public boolean getFoo() {
  return (this.foo != null ? this.foo : true);
}
```

What's wrong is that this logic gets evaluated every single time the method is called.

**Comment by snicoll** [comment]
So what that doc states is basically the following:

* If you have a collection you don't need a setter as long as the collection is initialized. The binder will use the getter to have a reference to the collection and will call `add` on it (that's the "not necessarily a setter since they can be mutated by the binder"). If the collection is `null` we need to setter to `set` the collection instance
* Nested POJO isn't a scalar value, it's about creating a nested configuration properties if you will (like `server.tomcat` has a `Tomcat` inner class in `ServerProperties`). Again, if you have a nested object (no property sets `server.tomcat`) and that nested object is initialized, you don't need a setter as we'll use the getter to retrieve the reference of the object to navigate to.

I don't  remember the intend of the "advisable" part there, maybe @dsyer remembers? The binder can be configured to use field binding or getter/setter binding. We always use the latter, I don't know what else I could tell you. You should probably have a debugging session in your own code to figure out when the setter is actually invoked. You'll realize it's invoked twice and probably not in the order you expect.
