### ISSUE TITLE
Add starter for Apache Kafka

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7443]
Now that #6961 is merged, we might want to add a sample (and maybe a starter?).  We don't need starters for everything and it looks like a single addition of `spring-kafka` would work in the "standard" case.

ping @garyrussell

**Comment by garyrussell** [comment]
@snicoll I'd be happy to provide the java code for a sample for kafka. However, I see the amqp sample has docker configuration; I don't have time to get up to speed on docker so if that's required, it will require some collaboration. 

I can't speak to the starter question but yes, all you need to do is add the spring-kafka pom to the CP.

**Comment by dsyer** [comment]
Is it still the case that you need the kafka server jar even on the client if you need to create a topic? If so then there are sort of 2 sets of use cases (admin, and no admin; huge scala-runtime dependency, and nice lightweight client library). We probably need to have a view on what the most common requirement is and put that in the starter (hopefully the more lightweight option).

**Comment by garyrussell** [comment]
Yes; interaction with ZK is required to create topics (if you want to control the number of partitions programmatically).

We are considering adding a `spring-kafka-admin` project so it can be optional (we don't currently add the broker jars at all to the CP); the spring-cloud-stream binder will eventually delegate to that rather than rolling its own topic creation. cc/ @mbogoevici 

There is a broker property `auto.create.topics.enable=true` where the broker will create the topics with the number of partitions controlled by `num.partitions`.

So you only need the scala stuff on the CP if you need to customize the number of partitions.

My inclination is to not support it out of the box in boot 1.5 and perhaps add `spring-kafka-admin` as an option in 2.0.

**Comment by mbogoevici** [comment]
Agree with what @garyrussell said. I wouldn't add the broker+scala deps to all Kafka applications. We might remove the broker dependency as a starter default in Spring Cloud Stream 2 as well - we had it for historic reasons for the 0.8 client support and we can't just remove dependencies now, but we support the option not to create topics at all via framework - this might be preferred scenario in production anyway, as well as for cloud-hosted brokers or when security comes into play (e.g. Kerberos). 

My preference would be to can have some `@ConditionalOnClass` auto-configuration option that can add the `spring-kafka-admin` API beans when they will actually exist (after extracting that functionality from Stream), but leave the inclusion of the actual library to the user. We can still manage its dependency, I suppose.

**Comment by snicoll** [comment]
Actually, this is a single dep so a starer isn't necessary. I've added an entry on start.spring.io. Let's revisit the sample once we can include the embedded support.
