### ISSUE TITLE
Move to pure Asciidoctor for documentation

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#7447]
We currently use Asciidoctor with the docbook5 backend. We'd like to drop Docbook and, instead, produce HTML and PDF documentation straight from Asciidoctor. We'll lose the multi-page HTML documentation, but we're happy to live with that.

**Comment by philwebb** [comment]
We also currently spit out EPUB.

**Comment by wilkinsona** [comment]
Asciidoctor can do EPUB directly too

**Comment by wilkinsona** [comment]
[Here's a branch](https://github.com/wilkinsona/spring-boot/tree/gh-7447) that drops Docbook. I haven't done any fine-tuning of the output but I think it's already pretty good in all three formats.

**Comment by philwebb** [comment]
Is the generated HTML anywhere we can look at? I think we should consider this for 2.0 but leave 1.5.x as it is.

**Comment by wilkinsona** [comment]
All three formats are available here: http://docs.spring.io/spring-boot/docs/asciidoctor/

**Comment by wilkinsona** [comment]
A few things that aren't quite right with the HTML:

- Tabs in code blocks result in an 8-space indent (vs 4 in the current docs)
- Code blocks don't wrap by default
- Some languages don't have syntax highlighted (properties, for example)
- This table is messed up: http://docs.spring.io/spring-boot/docs/asciidoctor/html/#test-auto-configuration
- Version number doesn't appear at the start of the doc
- Footer is empty

**Comment by bclozel** [comment]
FYI, the online version is not displayed correctly because the HTML body element is missing `class="book toc2 toc-left"`.
This is due to one of our **wonderful** scripts running on the server and adding/removing things in the served content. I wouldn't be surprised if other issues are linked with that. We should look at a locally generated doc to identify issues we can deal with.
For other issues, we'll have to ping Trevor (he is aware of that through another channel) and probably fix those scripts...

**Comment by snicoll** [comment]
Closing in favour of PR #12611
