### ISSUE TITLE
When I changed the version of Spring boot from 1.3.8 to 1.4.0 my tests throw an error

### ISSUE THREAD

**Issue by LucasHCruz** [spring-projects/spring-boot#7451]
After upgrade my version of spring boot from 1.3.8 to 1.4.0++ my integration test doesn't find the `Application.class`

My sample application is: https://github.com/LucasHCruz/stack40664101
And Travis is: https://travis-ci.org/LucasHCruz/stack40664101

To recreate the error just run: `mvn clean install -P integration`

**Comment by philwebb** [comment]
This is due to the change in layout of executable jars in Spring Boot 1.4. Application classes are now packaging in `BOOT-INF/classes` so `mp-schedule-integration-test` can no longer see classes in `mp-schedule-ws`.

You can use a classifier as [described here](https://github.com/spring-projects/spring-boot/issues/6792#issuecomment-243564648) if you really want your integration tests to load classes from your main jar.
