### ISSUE TITLE
Hazelcast client version for dependency management

### ISSUE THREAD

**Issue by neilstevenson** [spring-projects/spring-boot#7452]
In the _&lt;dependencyManagement&gt;_ section of `spring-boot-dependencies`, there is a section for Hazelcast server
```
<dependency>
  <groupId>com.hazelcast</groupId>
  <artifactId>hazelcast</artifactId>
  <version>${hazelcast.version}</version>
</dependency>
```
There should also be one for Hazelcast client,
```
<dependency>
  <groupId>com.hazelcast</groupId>
  <artifactId>hazelcast-client</artifactId>
  <version>${hazelcast-client.version}</version>
</dependency>
```

A Hazelcast client connecting to a Hazelcast server is a common topology, so should be easy to support.

Ordinarily you would want `${hazelcast.version}` and `${hazelcast-client.version}` to match. As they can have independent versions, it would be beneficial to allow them to be easily different.

**Comment by dbrimley** [comment]
+1

**Comment by neilstevenson** [comment]
Happy to fix if someone can assign the issue to myself

**Comment by neilstevenson** [comment]
Currently `hazelcast-client` has a dependency on `hazelcast` (server), but this could change in the future.

**Comment by wilkinsona** [comment]
We can certainly add dependency management for Hazelcast's client, but, given that it has the same release cycle as `hazelcast`, its version should be controlled by the same property. Splitting them will add complexity and make it too easy to end up with mis-matched versions.

**Comment by neilstevenson** [comment]
@wilkinsona  Can we set one from the other ?
```
<hazelcast-client.version>${hazelcast.version}</hazelcast-client.version>
```
?

They will usually change in step but don't need to. 
This gives the simplication that only one version is specified, but two are present

**Comment by snicoll** [comment]
It should also be noted that we have no auto-configuration for Hazelcast client (see #4918). I am certainly not keen to be able to mix and match versions of that jar, sounds like a mistake to me. Can you clarify why you'd want to do this?

**Comment by vpavic** [comment]
@snicoll Even though there's no auto-config for Hazelcast client mode, it might be worth noting that it's pulled in transitively if one uses [Hazelcast's Hibernate support modules](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-dependencies/pom.xml#L83-L84) so it can result in a mismatch of core and client versions of Hazelcast since core is provided by Boot's dependency management and client is not. Although there's a pending ticket to make that dependency optional: hazelcast/hazelcast-hibernate#22

The version property should be shared since core and client have the same release cycle as @wilkinsona notes.

**Comment by snicoll** [comment]
Sold, thanks for the additional info @vpavic
