### ISSUE TITLE
Allow EndpointMBeanExportAutoConfiguration to work with GSON 

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7466]
Whilst looking to merge #6579 I noticed that `EndpointMBeanExportAutoConfiguration` has a hard dependency on Jackson's `ObjectMapper`. It would be nice if we could abstract that so that GSON can also be used.

**Comment by wilkinsona** [comment]
This is a bit more involved that it appears. `ObjectMapper` appears in the API of several public classes. This is what I have thus far: https://github.com/wilkinsona/spring-boot/tree/gh-7466

We'd also need to update `ConfigurationPropertiesReportEndpoint` so that it can use GSON which is considerably more involved as we rely on Jackson's custom serialisation capabilities quite heavily.

**Comment by philwebb** [comment]
Since nobody is actually asking for this perhaps we should just make it more obvious in the docs that Jackson is required (at least for now). PR #6579 has jackson annotations on some of the data classes which is what made me notice it.

**Comment by philwebb** [comment]
It's a lot of work so for now we'll leave this.
