### ISSUE TITLE
@DataJpaTest override default Spring Boot Test Context

### ISSUE THREAD

**Issue by huhuhong** [spring-projects/spring-boot#7501]
Question
Below is my Application as OAuth2 Authorization Server and Resource Server as well
```
@SpringBootApplication
@EnableAuthorizationServer
@EnableResourceServer
public class Application {
}
```

and i'm spiting my unit test into Controller (Using @SpringBootTest]) and Domain (Using @DataJpaTest)

The problem here is when i execute Domain Unit with @DataJpaTest, by default it always bootstrap with Application.class above and throw exception as below:

```
No qualifying bean of type 'java.util.List<org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerConfigurer>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

Is there anyway i can provide my own Application Test Context with @DataJpaTest instead of bootstrap with the default Application.class?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

(Hint: `DataJpaTest` is going to look for a `SpringBootConfiguration` in the package of your test up to the root. Usually it will find your `@SpringBootApplication`. If the latter enables stuff like in your case, it is likely to break slicing. Move that to a `SecurityConfig` separate class or redefine a `@SpringBootConfiguration` for those tests). See [the doc](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-detecting-config)

**Comment by huhuhong** [comment]
Thanks.
