### ISSUE TITLE
about undertow could support multi-connectors(http & https)

### ISSUE THREAD

**Issue by hao0111** [spring-projects/spring-boot#7511]
hi, i am try to use undertow container ,but i can't find support multi-connectors(http & https) with undertow container. If tomcat container could support multi-connectors,then undertow container only use http or https one of them?Thank U for Ur help

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
