### ISSUE TITLE
Cannot use @ConditionalOnBean and @AutoConfigureAfter in the application module

### ISSUE THREAD

**Issue by nicolaferraro** [spring-projects/spring-boot#7514]
Following http://stackoverflow.com/questions/40805258/how-to-make-a-configuration-conditional-on-another-configuration/40807595, I wrote a small application showing the different behavior of `@ConditionalOnBean` and `@AutoConfigureAfter` in the application module.

The code is here: https://github.com/nicolaferraro/spring-boot-bug.

There are 3 auto-configuration classes `A1`, `A2` and `A4` that are dependent on another configuration class named `B`. While the beans created by `A1` and `A2` are being put in the application context, the bean created by `A4` is not. The only difference is the module where they are located (dependent module vs. application module) and the `spring.factories` file that is not needed for the application package (adding it has no effect).

The exception:
```
Field a4 in org.example.app.Application required a bean of type 'org.example.app.BeanA4' that could not be found.
	- Bean method 'beanA4' not loaded because @ConditionalOnBean (types: org.my.B; SearchStrategy: all) did not find any beans
```

The bean of type `org.my.B` is correctly found for `A1` and `A2`, but not for `A4` in the application module. Seems that `@AutoConfigureAfter` has no effect in the main module and the configuration is evaluated too early.

I've created another configuration named `A3`, similar to `A4` but NOT conditional on `B`, to show that it gets evaluated correctly.

To run the application:
```
mvn clean install
cd spring-boot-bug-app
mvn spring-boot:run
```

**Comment by wilkinsona** [comment]
`A4` isn't an auto-configuration class so `@AutoConfigureAfter` has no effect. It's being picked up by component scanning.

Normal configuration classes are, by design, processed before any auto-configuration classes so `A4` and is processed and its conditions evaluated before `B` has been processed. As mentioned in the javadoc of `@ConditionalOnBean`, it's strongly recommended that you only use it on auto-configuration classes to avoid this kind of problem.

You may be interested in this university session that @snicoll and I gave at Devoxx earlier this month which explains in detail how auto-configuration works: https://www.youtube.com/watch?v=uof5h-j0IeE
