### ISSUE TITLE
How to add ServletRegistrationBean into embeded servlet container?

### ISSUE THREAD

**Issue by z2xlong** [spring-projects/spring-boot#7515]
Hi, I'm a newbie of spring boot 1.4, is there anyway to add ServletRegistrationBean into embedded servlet container and external tomcat simultaneously?

My code as follows:
```
@SpringBootApplication()
public class DemoApplication extends SpringBootServletInitializer {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

       @Bean
    public ServletRegistrationBean apiServlet(DispatcherServlet dispatcherServlet) {
        ServletRegistrationBean servlet  = new ServletRegistrationBean(dispatcherServlet);
        servlet.setName("api");
        servlet.addUrlMappings("/api/*");

        return servlet;
    }

    @Bean
    public ServletRegistrationBean soaServlet()  {
        ServletRegistrationBean servlet = new ServletRegistrationBean(new MyServlet());
        servlet.setName("soa");
        servlet.addUrlMappings("/soa/*");

        return servlet;
    }
}
```
I can deploy the war  to external tomcat and works fine, but failed to run main function directly or run the command `mvn spring-boot:run`, how to fix it? thanks in advance.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
