### ISSUE TITLE
How can I controller the order of beans?

### ISSUE THREAD

**Issue by jearton** [spring-projects/spring-boot#7532]
I want to initialize ZBean before ABean. How to do that? Here is my code, It dose not work!

```
@Component
public class ZBean implements DisposableBean, Ordered {
    public ZBean() {
        System.out.println("init");
    }

    @Override
    public void destroy() throws Exception {
        System.out.println("destroy");
    }

    @Override
    public int getOrder() {
        return Ordered.HIGHEST_PRECEDENCE;
    }
}

@Component
public class ABean implements Ordered {

    public ABean() {
        System.out.println("init");
    }

    @Override
    public int getOrder() {
        return Ordered.LOWEST_PRECEDENCE;
    }
}
```

**Comment by code-4-fun** [comment]
Annotate ZBean with`@DependsOn("ABean")`

**Comment by Antergone** [comment]
How to User ```@Order``` instantiation prioritized。

**Comment by jearton** [comment]
@code-4-fun It's not flexsible. I expect that ZBean is always the first initialized bean. Whatever how many other beans.

**Comment by jearton** [comment]
@code-4-fun Assuming that ZBean is in a dependent jar which can not see other beans, how to do that?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by code-4-fun** [comment]
Oh, I misunderstood the question then. I don't think `@Order`can control bean initiation order. I have seen it mostly being used while configuring PostProcessors and Configuration components. On the same concept, I tried this which works... 
[Sample Test](https://gist.github.com/code-4-fun/290d9e79e8d0d5fa41f117999bce2e56)

Yeah, Stack Overflow would be the right place for such issues.

**Comment by jearton** [comment]
Thanks a lot.

**Comment by jearton** [comment]
Thanks a lot.

**Comment by jearton** [comment]
Thanks a lot.
