### ISSUE TITLE
Error occurred while add a custom Listener : check whether you have multiple ContextLoader* definitions in your web.xml

### ISSUE THREAD

**Issue by Leo-Lei** [spring-projects/spring-boot#7546]

**Comment by Leo-Lei** [comment]
I have a class 
```java
public class MyContextListener extends org.springframework.web.context.ContextLoaderListener
```

and register it as below:
```java
@Configuration
public class ApplicationConfiguration {

    @Bean
    public ServletContextListener listener(){
        return new ContextDestroyListener();
    }
}
```

But get the following error:
```
java.lang.IllegalStateException: Cannot initialize context because there is already a root application context present - check whether you have multiple ContextLoader* definitions in your web.xml!
```

I just want to use the custom ContextLoaderListener, rather than the default ContextLoaderListener. But get this error.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
