### ISSUE TITLE
spring-boot:repackage does not exclude Devtools by default for war packaging

### ISSUE THREAD

**Issue by psabharwal123** [spring-projects/spring-boot#7556]
Bug report

As per http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/maven-plugin/repackage-mojo.html default value for excludeDevtools is true; However, when trying to repackage my war using 'mvn clean install spring-boot:repackage' devtools is still included in the repackaged war

**Comment by wilkinsona** [comment]
What version of Spring Boot are you using?

**Comment by psabharwal123** [comment]
1.4.2.RELEASE

**Comment by wilkinsona** [comment]
Thanks. Looks like it works for jar packaging but not for war packaging.

**Comment by easonlin404** [comment]
@wilkinsona  Looks like it just a misunderstanding.  I tested repackaged war by setting `excludeDevtools  `  `true `was work in 1.4.2.RELEASE version.

As per [6186262e](https://github.com/spring-projects/spring-boot/commit/6186262ecc205664016e39e4a7d0eba2646b5531) commit, now 1.5.x switch the default value of `excludeDevtools` from `false` to `true`.

**Comment by psabharwal123** [comment]
@easonlin404 so you are saying that in 1.4.2.RELEASE the default is false? if so how doe it work for jar and not war?

**Comment by wilkinsona** [comment]
Let me clarify the situation here as I see it. When `excludeDevtools` is `true` (either because you've set it explicitly in 1.4 or because it's the default in 1.5) it works for `jar` packaging but does not work for `war` packaging.

@psabharwal123 If you believe that Devtools is being excluded by default with a jar when using 1.4, please provide a sample that reproduces that behaviour. As far as I can tell, that is not the case.

**Comment by psabharwal123** [comment]
you are right and that sums it up quite well

**Comment by snicoll** [comment]
It doesn't work because it's already present in the original jar and the repackage doesn't remove it.

**Comment by snicoll** [comment]
@psabharwal123 there is a workaround for `war` packaging:  set the scope of the dependency to `provided` and it won't be packaged when `excludeDevTools` is `true`.
