### ISSUE TITLE
Cross-Origin Request Blocked: 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by moon16** [spring-projects/spring-boot#7584]
Is it possible to enable CORS filters in Spring boot 1.3.0 using 
endpoints.cors.allowed-origins=http://example.com
endpoints.cors.allowed-methods=GET
I am new to this so doesnr have that much idea on this.
I have enabled cross origin request by enabling actuators in gradle build file and adding the mentioned cors properties in application.properties.
When I try to request from frontend(angularjs) it is giving error:
Chrome:
XMLHttpRequest cannot load http://localhos:<port>/manage/health. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhos:<port>' is therefore not allowed access.
Firefox:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhos:<port>. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
