### ISSUE TITLE
Optimize startup time: Thymeleaf

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#7591]
Observations from benchmarks:

* Thymeleaf depends on groovy, but it should be optional in a spring app (I never seem to need it)

* The layout dialect isn't so useful in TL 3, and it has a cost of initialization, so it should be optional.

* Thymealeaf's `SpringTemplateEngine` has a static initializer (or it triggers one in `SpringStandardDialect`) which unconditionally creates a Jackson `ObjectMapper` if it's on the classpath. The problem is really that it's a static initializer, so it can't be deferred. (But I will try the background pre-initializer thread and report back.)

UPDATE: groovy only comes in as a dependency of the layout module, so we can kill two birds with one stone by removing the layout.

**Comment by dsyer** [comment]
Update: Removing Thymeleaf has a noticeable effect on the benchmarks, but pre-instantiating a `SpringTemplateEngine` doesn't. It's the same for the `Validator` FWIW, i.e. only removing it from the classpath helps (it was already eagerly initialized by the existing listener)

**Comment by danielfernandez** [comment]
Is this Thymeleaf 3.0? What is the specific `static` block causing the performance impact? I would like to have a look and see if we can improve that for you.

The `StandardJavaScriptSerializer` is being initialized at instatiation time in `StandardDialect`, but not inside a `static` block (at least not in TL3)...

**Comment by dsyer** [comment]
Yes, it was TL3 (you can see the apps in the benchmark in my github repo). It's still a mystery though, about the static initializer, and why it shows up in profiling. Calling it early in a background thread has no effect. The Jackson piece is pulled in unconditionally by `StandardDialect` when it instantiates a `StandardJavaScriptSerializer`, and there was s a static instance of the former in `SpringTemplateEngine`. It's possible that making the initializer lazy would open up a faster path for a spring app to start, but I didn't try that.

**Comment by danielfernandez** [comment]
I've cloned your `spring-boot-startup-bench` repository and made some tests using your `PetclinicBenchmark.*`, made the initialisation of the `SpringStandardDialect` instance not a `static` variable in `SpringTemplateEngine`, and also tried lazily initialising the conversion service and the expression object factory inside `SpringStandardDialect` as `volatile` variables… but I have seen no variation at all in benchmark times :(

I will nevertheless devote some effort in profiling the startup process for Thymelef 3.0.4, see if there is anything that could be improved there without impacting other aspects of performance.

**Comment by dsyer** [comment]
Thanks for trying that. Obviously it's not the fact that it's static that's an issue, but because it's static it makes it hard to customize the behaviour (e.g. to make it lazy). What change did you make exactly, and I'll give it a try as well?

**Comment by danielfernandez** [comment]
These are the changes: https://github.com/danielfernandez/thymeleaf-spring/commit/0e65de797f9478b7d0d124561be789855fe55dae

Note that these changes do not modify the way Jackson is initialised. Given the Jackson part was non-static, I left it with no changes. I was trying to attack the `static SpringStandardDialect` variable in `SpringTemplateEngine` and also some `static` blocks in some dependencies further downstream. But none seem to affect.

**Comment by danielfernandez** [comment]
I've done some changes to the way things are initialised in `StandardDialect` and `SpringStandardDialect`.

From my profiling, I've noted that a large part of the time taken by initialisation of the template engine object was in fact due to programmatic class loading. Thymeleaf does a bit of this using `Class.forName(...)` and similar methods for things that can go from validating the version of Spring it is being used with to determining whether certain capabilities can be enabled or not depending on optional dependencies.

However, most of these operations were performed at instance creation of the Standard dialects (actually, of auxiliary structures offered by the Standard dialects) without that being completely necessary. Not that it harmed — but their corresponding *getter* methods were being called only during template engine initialisation (at first template execution), so they could perfectly be delayed until that point.

If interested, check https://github.com/thymeleaf/thymeleaf/commit/74dce31e1aa075175f71275b69b826da15c09a06 and https://github.com/thymeleaf/thymeleaf-spring/commit/a4b38ed9429fe2d19e3db17c6d19976a1332df29

These changes are already in Thymeleaf `3.0.4-SNAPSHOT`. See http://www.thymeleaf.org/faq.html#use-snapshot

After doing this, a small benchmark I specifically created for timing the time it took to create `SpringTemplateEngine` instances showed *huge* improvements. Basically it went from 50secs to 0.7secs. First template processing execution suffered, of course, but execution time was just moved from one operation to the other with no net damage, so it seems like a good tradeoff. And initialisation is much faster.

However, I must say that I tried your benchmark and I didn't see a really *significative* improvement, as it went from this:

```
Benchmark                           Mode  Cnt  Score   Error  Units
PetclinicBenchmark.devtoolsRestart  avgt   10  1.640 ± 0.119   s/op
PetclinicBenchmark.explodedJarMain  avgt   10  5.413 ± 0.093   s/op
PetclinicBenchmark.fatJar           avgt   10  7.408 ± 0.195   s/op
PetclinicBenchmark.noverify         avgt   10  6.506 ± 0.174   s/op
```

...to this:

```
Benchmark                           Mode  Cnt  Score   Error  Units
PetclinicBenchmark.devtoolsRestart  avgt   10  1.577 ± 0.100   s/op
PetclinicBenchmark.explodedJarMain  avgt   10  5.169 ± 0.056   s/op
PetclinicBenchmark.fatJar           avgt   10  7.061 ± 0.113   s/op
PetclinicBenchmark.noverify         avgt   10  6.181 ± 0.153   s/op
```

I haven't profiled PetClinic proper again, but maybe there are other parts of the infrastructure keeping from further improvement. It would be nice to know if you still detect any time wells still imputable to Thymeleaf using `3.0.4-SNAPSHOT`. If so, maybe there is something specific to the way the engine is being configured in PetClinic, and I can revisit that specific scenario…

**Comment by dsyer** [comment]
Awesome! That looks like a pretty useful change to me (it's all about shaving a few hundred milliseconds here and there - nothing dramatic in my experience so far).

**Comment by dsyer** [comment]
I don't see any change in my benchmarks with 3.0.4-SNAPSHOT, so I'm not sure if the changes are live yet, or if you cancelled it out with another change, or maybe I actually need to do more customization (not just update the thymeleaf version)?

**Comment by danielfernandez** [comment]
No, that's probably normal, given my results too. My observed variations could be just oscillations due to OS load. I'll have to do some petclinic-specific profiling and see what is going on. Instantiation of `SpringTemplateEngine` should be now very fast but... maybe the boot autoconf, or PetClinic itself is doing something else with Thymeleaf besides just creating the engine objects.

**Comment by danielfernandez** [comment]
I've profiled the startup of the PetClinic application by running the `PetClinicApplication` class in your benchmark repository from IntelliJ, asking the IDE to profile it with YourKit.

I enabled CPU profiling, and took a snapshot after the startup process finished. I did this using both Thymeleaf 3.0.2.RELEASE and Thymeleaf 3.0.4-SNAPSHOT.

However, Looking at the CPU profiling results, the amounts of time taken for Thymeleaf initialisation, with both versions of Thymeleaf, were very small compared to the total times for the whole PetClinic.

As an example, see what filtering by `"thymeleaf"` does look like in the 3.0.4-SNAPSHOT YourKit snapshot:

<img width="1135" alt="screen shot 2017-01-18 at 23 31 20" src="https://cloud.githubusercontent.com/assets/1492299/22085969/d7f7a16a-ddd6-11e6-89c3-b5fbafcfbe85.png">

Quite a small amount of the total seems to go into Thymeleaf, apparently. Note this search basically selects Spring Boot's Thymeleaf autoconfiguration artifacts, which we could consider *triggers* of all Thymeleaf initialisations inside PetClinic.

IMO this is consistent with not seeing differences in the benchmark between one version of Thymeleaf and the other.

I can send you the snapshots via email if you want to examine them (YourKit format), there may very well be something I'm missing. Also, if you have other profiling results showing Thymeleaf taking a more significative amount of time in the startup process, could you please send those to me?

**Comment by dsyer** [comment]
The evidence is described in the README of the benchmarks project: replacing Thymeleaf with Mustache saves a few hundred milliseconds (which is a big deal). I never really know how to interpret the profiler results - at best they seem to be suggestive - so I agree there is no value in the data you pasted above. I have found that profiling startup is extremely hard because it happens so fast (profilers like a long running process for building up statistics).

**Comment by dsyer** [comment]
After doing some more measurements I don't think Thymeleaf is costing very much (as long as Jackson is not present, and especially with the new 3.0.4 snapshots). I'll open a new issue for Jackson.
