### ISSUE TITLE
spring boot maven package exec jar read exclude properties

### ISSUE THREAD

**Issue by hao0111** [spring-projects/spring-boot#7597]
Using spring-boot-maven plugin package jar,i want to read application.properties which is not in fat-jar ,there is the under directory with fat-jar.But i found it does not work,fat-jar startup don't read application.properties!!!

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by hao0111** [comment]
I see,thank you for your help
