### ISSUE TITLE
Upgrade to Hibernate Validator 5.3.4.Final

### ISSUE THREAD

**Issue by lpandzic** [spring-projects/spring-boot#7598]

**Comment by snicoll** [comment]
OK for some reason things have changed there regarding EL requirements. Samples are failing with `5.3.4.Final`

**Comment by snicoll** [comment]
`spring-boot-sample-hibernate52` fails because Hibernate 5.2 brings `javax.enterprise:cdi-api` which itself brings `javax.el:el-api:jar:2.2` that does not contain that class. But `org.glassfish:javax.el:jar:3.0.0` does. If I add the latter then the sample works properly.

`spring-boot-sample-war` fails because `spring-boot-starter-tomcat` is excluded and by doing so the EL API isn't available.

`spring-boot-samples-data-jpa` works because Hibernate 5.0 doesn't bring the el-api at all. And that sample has `spring-boot-starter-web` which brings what's necessary. 

I am not sure how to fix this. For sure, Hibernate 5.2 that brings an EL api that isn't compatible with Hibernate Validator looks really weird to me.

**Comment by philwebb** [comment]
Raise [HHH-11370](https://hibernate.atlassian.net/browse/HHH-11370) to see if the `cdi-api` dependency was intentional or not.
