### ISSUE TITLE
Review and rephrase ConfigurationProperties requirements in the doc

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#7620]
Several users are confused about what they can't or cannot use with `@ConfigurationProperties`. The fact it is a component and that the default constructor is autowired now makes it worse if they don't realize we do not support "constructor injection" (in the sense of the environment). 

See http://stackoverflow.com/questions/41080705/how-to-configure-external-configuration-beans-in-spring-boot/ for instance. We have others (the advisable word for getter/setter should definitely be removed and replaced by a more exhaustive example).

**Comment by deinspanjer** [comment]
I think one solid example would go a long way toward reducing confusion.  If you search the docs for the final keyword, you will see that almost all the code snippets use that keyword (which is of course good general practice), but since it is problematic in this case, I think the example would be most useful if it actually showed a small complete bean along with setters and comments that indicated how they were needed.

**Comment by snicoll** [comment]
That's what I intended to do. Thanks for the feedback.
