### ISSUE TITLE
Switch SkipSslVerificationHttpRequestFactory to opt-in

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7629]
We have `SkipSslVerificationHttpRequestFactory` to disable SSL for the CF security. We should check that this is needed and that it doesn't open us up to MitM attacks.

**Comment by mbhave** [comment]
@dsyer @philwebb The `SkipSslVerificationHttpRequestFactory ` was only meant to be used for the `RestTemplate` that talks to the UAA and CC when validating the token for actuators on CF. We made the assumption that the CC and UAA servers can be implicitly trusted because we get their URLs from the VCAP environment. I'm not sure how it makes us susceptible to MitM attacks but I'm happy to discuss.

**Comment by dsyer** [comment]
That sounds pretty scary to me still. It's inviting an attack through the environment abstraction (any app that sets `vcap.application.cf_api` in the command line, or system properties, or via a config service is vulnerable). Can't we just make the default setting "secure" and provide a scary opt out for the YOLOs?

**Comment by snicoll** [comment]
Closing in favour of the PR #7655
