### ISSUE TITLE
logback.xml reloading not working in 1.4.2.RELEASE

### ISSUE THREAD

**Issue by dgillespie81** [spring-projects/spring-boot#7644]
In the latest spring boot (1.4.2 at time of writing) reloading of logback.xml (using scan="true" in logback.xml) is broken.  This is similar to a previous issue found in 1.2.0 and resolved in 1.2.1:

https://github.com/spring-projects/spring-boot/issues/1592

I have attached a zip file containing two projects that are identical save for the boot version (1.4.2 vs 1.2.1).  logback.xml configuration is successfully reloaded in 1.2.1 but not in 1.4.2.

[logback.zip](https://github.com/spring-projects/spring-boot/files/651562/logback.zip)

**Comment by wilkinsona** [comment]
Thanks for the sample. How are you running the two apps and how are you changing the `logback.xml` file such that it works with 1.2.1 but does not work with 1.4.2?

**Comment by dgillespie81** [comment]
We're running then with the gradle bootRun task of the spring boot plugin eg.

gradlew clean build bootRun

HelloController has a trace level logging statement:

logger.trace("Greetings from Spring Boot!");

By default both projects have the hello package logger configured at Error level so this log won't show.  Change this to Trace whilst running - the 1.2.1 version will pick this up after the configured scan period (10 seconds) and several logger invocations.  1.4.2 will not.

**Comment by wilkinsona** [comment]
I assume that you are changing `logback.xml` in `src/main/resources`? This only works with 1.2 because `bootRun` adds `src/main/resources` to the classpath. This [changed in 1.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#bootrun-resources). With the default configuration in 1.3 and later, you need to change the `logback.xml` in `build/resources/main/`. Alternatively, as described in the release notes linked to above, you can configure `addResources = true` on the `bootRun` task.
