### ISSUE TITLE
Integrating Log4j2 , I canont see the HTTP Request in Spring boot which can be seen in default logback config root debug 

### ISSUE THREAD

**Issue by SanjayGautam** [spring-projects/spring-boot#7690]
**Question**

I configured the log4j2 as provided, I use to see the HTTP request 

GET /iotlogger/gaugeLogs/gaugeLogsPage?pageNumber=1 HTTP/1.1
Host: localhost:9999
Content-Type: application/json
Authorization: Basic Xsdsdsdsdsdsdsds
Cache-Control: no-cache
Postman-Token: 28668000-aa51-e5b7-1f77-46688806db26

I see all the other logs , I see that blogs tells about the log4j-jcl , but i dont see it any more 

can any one help ? I dont see file rolling too

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
	<Properties>
		<Property name="log-path">applogs</Property>
	</Properties>
	<Appenders>
		<Console name="Console">
			<PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n" />
		</Console>
		<RollingFile name="iot-logger-appender-rolling" filename="${log-path}/guage-geo.log"
			filepattern="${log-path}/%d{YYYYMMddHHmmss}-fargo.log">
			<PatternLayout pattern="%d{YYYY-MM-dd HH:mm:ss} [%t] %-5p %c{1}:%L - %msg%n" />
			<Policies>
				<SizeBasedTriggeringPolicy size="10KB" />
			</Policies>
			<DefaultRolloverStrategy max="10" />

		</RollingFile>
</Appenders>
	<Loggers>
		<Root level="debug">
			<AppenderRef ref="Console" />
			<AppenderRef ref="iot-logger-appender-rolling" />
		</Root>

	</Loggers>
</Configuration>

```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
