### ISSUE TITLE
Repository interface saves only last object instance when in a for loop and bulk insert changes objects before saving 

### ISSUE THREAD

**Issue by RbkGh** [spring-projects/spring-boot#7693]
I am iterating over a list of objects and saving one object at a time after each loop.What i found is that only the last object is always saved when using the MongoRepository interface.

for instance 
`for(int i=0;i<=objectList.size();i++){
repositoryInterface.save(objectList.get(i));
}`
In this case,only the last object is saved when there are about 3 objects in objectList.

Again,if repositoryInterface is used to save all the objectList in one query,
say,repositoryInterface.save(objectList),
only the last changes to the last object in objectList is persisted for all three objects in objectList.
For instance,

```
List<Book> books = new ArrayList<>();
Book book0 = new Book();
book0.setBookName("Book0");
book0.setBookNumber(0);

books.add(book0);

Book book1 = new Book();
book1.setBookName("Book1");
book1.setBookNumber(1);

books.add(book1);

for(int i=0;i< books.size();i++){
switch(i){
case 0 :  
books.get(0).setBookNumber(00);
break;
case 1 :
books.get(1).setBookNumber(11);
break;
default:
System.out.println("nothing per this example");
}
}

repositoryInterface.save(books);
//now checking the mongo database,what is inserted is {bookName:"Book1",bookNumber:11},{bookName:"Book2",bookNumber:11} instead of  {bookName:"Book1",bookNumber:00},{bookName:"Book2",bookNumber:11}
```

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
