### ISSUE TITLE
Check @AutoConfigureBefore/@AutoConfigureAfter classes are actually auto-config

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7697]
See https://github.com/spring-projects/spring-boot/issues/6865#issuecomment-262257489

**Comment by mbhave** [comment]
@philwebb In that case, should we fail hard if `@AutoConfigureOrder` is applied to a non-autoconfiguration class also?

**Comment by philwebb** [comment]
@mbhave Yeah, I think we should fail in the same was as #6865 (`IllegalStateException`).

**Comment by snicoll** [comment]
@mbhave asked a very pertinent question (https://github.com/spring-projects/spring-boot/issues/6865#issuecomment-265606400) and I can't find the answer. We surely can't scan all `@Configuration` candidates to see if an order has been set on them by mistake. So I understand that the thing that we want here is that the annotation refers to a class that is not an auto-configuration.

To be clear, that wasn't my original request (I can see that annotation being used on a users's `@Configuration`). But I guess the annotation name is good enough to indicate how it should be used.

**Comment by wilkinsona** [comment]
> Also AutoConfigureSorter does not load the Class as it uses ASM so if we want to check if the class is actually on the classpath

I don't think we need to do that. We just need to know if it's configured by the `Class<?>` attribute and, if it is, check that it's listed as an auto-configuration class in `spring.factories`.

**Comment by snicoll** [comment]
OK I've some hacks in 62addb2 - I am not super happy about the code and I think it is probably too late for 1.5 to do this, failing hard post RC1 seems a bit gross.

Also the case of `@ImportAutoConfiguration` is not really clear. It looks like we are allowed to add a `Class` has an `auto-configuration` using that annotation even if said class isn't an auto-config. That's what we do in the tests and they break now since they use `@AutoConfigureAfter`.

**Comment by philwebb** [comment]
I'm dropping this from 1.5 as it's a relatively minor enhancement that I don't think we really need to get in. We can revisit again towards the end of 2.0.
