### ISSUE TITLE
How can i get the package name with a class has @SpringBootApplication 

### ISSUE THREAD

**Issue by zxj19951029** [spring-projects/spring-boot#7698]
I'm coding a starter,in my starter ,i will scan project class.But i need to get start-up class package name.
Or get a set of the project class

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by zxj19951029** [comment]
I'm sorry.You are right! 
It's real not a bug!
