### ISSUE TITLE
v1.5.0,  could Spring data using Neo4j and MongoDB?

### ISSUE THREAD

**Issue by beanstt** [spring-projects/spring-boot#7761]
Working with spring-data to manage two data-stores Mongo,Neo4j. (correct me if I am wrong but there is no spring-data cross data store support for these two, which mean I will use different domain entities for each store)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
