### ISSUE TITLE
Cannot enable JMX for EhCache

### ISSUE THREAD

**Issue by searhiy** [spring-projects/spring-boot#7767]
I configured ehcache using appropriate annotations, and tried to enable JMX for EhCache in Spring Boot.

This is my configs:

```java
@Configuration
public class EhcacheConf {

    @Bean
    public CacheManager getEhCacheManager(){
        return getEhCacheFactory().getObject();
    }

    public EhCacheManagerFactoryBean getEhCacheFactory(){
        EhCacheManagerFactoryBean factoryBean = new EhCacheManagerFactoryBean();
        factoryBean.setConfigLocation(new ClassPathResource("ehcache.xml"));
        factoryBean.setShared(true);
        return factoryBean;
    }

    @Bean
    public ManagementService managementService() {
        return new ManagementService(getEhCacheManager(),
                mbeanServer(),
                true,
                true,
                true,
                true,
                true);
    }

    @Bean
    public MBeanServer mbeanServer() {
        MBeanServerFactoryBean mBeanServerFactoryBean = new MBeanServerFactoryBean();
        mBeanServerFactoryBean.setLocateExistingServerIfPossible(true);
        return mBeanServerFactoryBean.getObject();
    }

}
```

application.yaml

```yaml
spring:
    cache:
      type: ehcache
      ehcache:
        config: classpath:ehcache.xml
endpoints:
  jmx:
    domain: quiz
    unique-names: true
```

But it doesn't work for me. Could you please add some new property, i.e. `spring.cache.ehcach.jmxenable=true`, or explain how this should work. 

In The Internet a lot of examples with Spring Core. But no one tried it with SpringBoot.

Thanks!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by searhiy** [comment]
@snicoll 
Thank you for your reply. Here is Stack Overflow question: http://stackoverflow.com/questions/41359550/how-can-i-register-jmx-support-for-ehcache-in-spring-boot
