### ISSUE TITLE
Deprecate InMemoryMetricRepository

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7777]
We don't auto-configure it in 2.0, should we deprecate it?

**Comment by snicoll** [comment]
Good call, I forgot to mention that. I vaguely remember that we decided in 2.0 that the user has to be explicit as to wich strategy we want to use rather than providing in memory out of the box. 

So I don't think we should deprecate it. But us configuring an extra bean is 1.5 is probably not so smart after all. I am sure @dsyer remembers the context.

**Comment by dsyer** [comment]
If it's true that `InMemoryMetricRepository` is only there to support Java 6,7 clients in 1.5, then for sure we should deprecate and eventually remove it (because Java 8 is a pre-requisite for Boot 2.0) I think that's the case, but let's be sure that the feature set of the buffer-based storage solution is the same.

**Comment by wilkinsona** [comment]
I think we need to figure out #8064 before we can tackle this

**Comment by wilkinsona** [comment]
The move to Micrometer-based metrics removes the need to `InMemoryMetricRepository` entirely.
