### ISSUE TITLE
Exception when use spring data mongodb when ``Aggregation.unwind()`` to abstract class

### ISSUE THREAD

**Issue by ashraf-revo** [spring-projects/spring-boot#7791]
this is the exeption
org.springframework.data.mapping.PropertyReferenceException: No property amountData found for type Amount! Traversed path: Product.amount.

i have problem when i unwind abstract class by saying it don't have this property    this real but the class which extend this abstract class have the required property 

this is the sample code which show this problem  https://github.com/ashraf-revo/Issue

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
