### ISSUE TITLE
Add a HowTo OAuth + Actuator Security

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7860]

**Comment by mbhave** [comment]
This doesn't seem to be a widely adopted use case and since we're going to revisit security in 2.0, we can consider adding it then. 
```
[[howto-secure-actuator-when-using-oauth]]
=== Actuator Security and OAuth
By default all sensitive actuator endpoints are secured and require the authenticated user to have one of the roles
defined under `management.security.roles`.
If you use OAuth to secure your application, the value of the `authorities` key in the response from the `UserInfoEndpoint`,
will be used as roles, by default.
If you want to map roles to a different key or decide the role based on other user attributes, you can define a bean of
type `AuthoritiesExtractor` in your configuration, e.g.

[source,java,indent=0,subs="verbatim,quotes,attributes"]
----
	@Bean
    	public AuthoritiesExtractor oauthAuthoritiesExtractor() {
    		return new AuthoritiesExtractor() {
    			@Override
    			public List<GrantedAuthority> extractAuthorities(Map<String, Object> map) {
    				ArrayList<GrantedAuthority> grantedAuthorities = new ArrayList<>();
                    // ... logic to obtain roles for the user
    				if (map.get("user").equals("admin")) {
    					grantedAuthorities.add(new SimpleGrantedAuthority("ROLE_SUPERUSER"));
    				}
    				return grantedAuthorities;
    			}
    		} ;
    	}
----
```
Note: The configuration will be different if the `token-info-uri` is used since the `AuthoritiesExtractor` is not used in that case.

**Comment by snicoll** [comment]
@mbhave actually I would merge this in `1.4.x` even. @bclozel and I have a talk where we demonstrate _exactly_ that. I would move the code snippet to a real class with an include though (see `src/main/java` in `spring-boot-docs` for more details).

**Comment by mbhave** [comment]
@snicoll This was specifically for 1.5 because there is an Mvc interceptor which now checks roles. even after spring security. For 1.4, we wouldn't need the `AuthoritiesExtractor` since access would be checked by spring security (if the pattern matches). We decided to move this to 2.0.0 because it seemed like the documentation was getting too complex depending on whether the user had a `user-info-uri` or `token-info-uri` configured as the `AuthoritiesExtractor` gets used only in the former case. If you have something in mind that should be documented in 1.4, I'm happy to discuss.

**Comment by mbhave** [comment]
Closing this since we don't have the Mvc interceptor anymore.
