### ISSUE TITLE
static resources not loading when using GetMapping without parameter

### ISSUE THREAD

**Issue by Alwan** [spring-projects/spring-boot#7893]
Greetings, 

I'am using the new annotation (`GetMapping) without parameter and my CSS resources not loading in all controllers 

example 

```java
@Controller("admin")
public class AdminController {
    @GetMapping
    private String index(){
	return "/admin/index";
    }    
}
```

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
@Alwan You might want to provide a sample if you ask on stackoverflow to show exactly what problem you're having.
