### ISSUE TITLE
How to use hibernate @DynamicUpdate with springboot data-jpa?

### ISSUE THREAD

**Issue by w17731138318** [spring-projects/spring-boot#7909]
my English is poor.
see code:
SuserRepository:
public interface SuserRepository extends JpaRepository<Suser,Long>{
}
SuserService:
public Suser save(Suser suser){
    return suserRepository.save(suser);
}
Suser：
@Entity
@SelectBeforeUpdate(true)
@DynamicUpdate(true)
public class Suser implements Serializable {
……
}

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
