### ISSUE TITLE
springboot path suffix  to intercept

### ISSUE THREAD

**Issue by yumemor** [spring-projects/spring-boot#7917]
## demand：
`http://127.0.0.1/8080/get` 404
`http://127.0.0.1/8080/get.action` 200
`http://127.0.0.1/8080/style.css` 200

## code

```java
@Bean
public ServletRegistrationBean getServletRegistration(DispatcherServlet  dispatcher){
    ServletRegistrationBean registrationBean = new ServletRegistrationBean(dispatcher);
    registrationBean.getUrlMappings().clear();
    registrationBean.addUrlMappings("*.action");
    return registrationBean;
}
```

## result
`http://127.0.0.1/8080/get` 404
`http://127.0.0.1/8080/get.action` 200
`http://127.0.0.1/8080/style.css` 404

## describe
How to access to a static resource？

![image](https://cloud.githubusercontent.com/assets/11767814/21764647/287bf4a4-d69f-11e6-9e55-ff652f25483c.png)

> static resource in webapp can access

How to solve？

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

That said, it looks like `style.css` is in a folder named `css` so it's URL would be http://127.0.0.1:8080/css/style.css
