### ISSUE TITLE
Exception mapped into non-JSON response

### ISSUE THREAD

**Issue by michal-marciniec** [spring-projects/spring-boot#7963]
## Description
Version: Spring Boot 1.4.3.RELEASE
Having a custom Filter with `doFilter` method annotated with `@Transactional` can lead to returning non-JSON response from an endpoint. 
#### Details
My repository throws an exception when no result is found. This exception should be mapped by a global exception mapper to a specific JSON response. However, throwing this exception violates JPA transaction (due to programmer's mistake), therefore `javax.persistence.RollbackException` is thrown, which is also translated on the backstage to a JSON response. Finally, those two JSON responses are **concatenated** and non-JSON response is returned from the endpoint, which should never happen.

## Steps to reproduce
1. Download [Reproduction project](https://github.com/spring-projects/spring-boot/files/701605/nonjson-repro.zip)
2. Run `gradlew bootRun`
3. GET `http://localhost:8080/api/game/190`

### Actual result
`{"message":"from handler"}{"timestamp":1484222492583,"status":404,"error":"Not Found","exception":"com.bug.exceptions.GameNotFoundException","message":"Game not found","path":"/api/game/190"}`
Two JSON responses concatenated into one **non-JSON**.

### Expected result
Valid JSON response (e.g. one of concatenated ones).

**Comment by bclozel** [comment]
Hi @michal-marciniec,

Annotating your `Filter` with `@Transactional` is not a great idea and can lead to issues. In that case, your filter is invoked twice and dispatches twice the request/response pair to the filter chain.
It means it's writing twice to the response which is not reset between calls (and can't be fully reset since it's already committed).

I've looked into our codebase and it doesn't seem we can protect against that situation; but your Filter implementation can be improved to avoid dispatching the request/response twice:

```java
if(!response.isCommitted()) {
	chain.doFilter(request, response);
}
```

Again, `@Transactional` around a filter execution might create a lot of other issues and I'd look into redefining the boundaries of your transaction.

Thanks for this report!
