### ISSUE TITLE
Question：how to use some of the XML attributes ？

### ISSUE THREAD

**Issue by ExtremeYu** [spring-projects/spring-boot#7975]
Question

![image](https://cloud.githubusercontent.com/assets/16620268/21921016/fcb61ba2-d99f-11e6-8c53-4e01e5b24fd8.png)
![image](https://cloud.githubusercontent.com/assets/16620268/21921020/054e42f8-d9a0-11e6-84a5-579b9877af24.png)
![image](https://cloud.githubusercontent.com/assets/16620268/21921030/0f9a0c06-d9a0-11e6-9dda-b7ac4cbc7e4d.png)
I don't know how to configurate the attributes showing the pictures,help help help help

**Comment by ExtremeYu** [comment]
spring boot recommend the @Configuration  but i don't know how to use ref,constructor-arg,map and etc........

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
