### ISSUE TITLE
how to speed up first request in springboot + jersey?

### ISSUE THREAD

**Issue by dragontree101** [spring-projects/spring-boot#7989]
i use spring-boot and jersey， and i request same api some times，
i found my first request speed is very slow(about 1s )，and other requests are very fast (about 10 ms),  i think may be in the first request， jersey need to load and init some classes.

i want to know how to let the jersey path load or init step into spring-boot load, and speed up the first request time? 

thanks!

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
