### ISSUE TITLE
Support @ContextHierarchy with @SpringBootTest

### ISSUE THREAD

**Issue by stojsavljevic** [spring-projects/spring-boot#8000]
Hi,

I'm starting my application using Fluent builder API with something like:

```
new SpringApplicationBuilder().sources(ParentCtxConfig.class)
                .child(ChildFirstCtxConfig.class).sibling(ChildSecondCtxConfig.class).run(args);
```
So, I have root context with two child contexts.

I want write integration tests respecting that hierarchy. What should be the best way to achieve that?

I assume that I should annotate my test with `@ContextHierarchy` annotation. I tried to pair it with other annotations like `@SpringBootTest` but nothing seems to work.

I'm using Spring Boot 1.4.3.
Thanks!

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

If you do post on Stack Overflow, please take the time to provide some more details. "Nothing seems to work" doesn't tell people who want to help you very much at all. The more time you spend making it easy for people to help you, the more likely it is that they will have the time to do so.

**Comment by stojsavljevic** [comment]
Sorry for the inconvenience.

My feeling was that context hierarchies are not supported in Spring Boot test since I can't find any documentation nor relevant example.
I posted a question on [Stack Overflow](http://stackoverflow.com/questions/41693685/context-hierarchy-in-spring-boot-based-tests).

Thanks for your time!

**Comment by wilkinsona** [comment]
Thanks. The question on Stack Overflow is much more helpful. Let's move the discussion over there. We can re-open this if it turns out that something needs to change in Spring Boot.

**Comment by wilkinsona** [comment]
Thanks to the sample that you provided on Stack Overflow, I now have a clear picture of what you're trying to do. The `loadContext` method of `SpringBootContextLoader` does not consider a parent context so the hierarchy doesn't get set up.
