### ISSUE TITLE
Add a Spring Framework 5 sample

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8012]
It would be nice to support Spring Framework 5 with Spring Boot 1.5 (although we might not be able to add a sample until it's GA).

**Comment by wilkinsona** [comment]
I'm not sure how this is going to work without Spring Framework 5-compatible versions of all the other projects. Without them, there'll be too many caveats. My feeling is that doing this will either produce a flawed result or will take too much time if we do it properly. I don't like the former and the time for the latter would be better spent on 2.0.

**Comment by snicoll** [comment]
I think the effort of trying to see what breaks is really interesting. It's on my todo for this week. I am -1 for a sample, this becomes official that we support this combination and like Andy said, I don't see how we could defend such position.

**Comment by wilkinsona** [comment]
From what I've seen with the Platform, there's no way we can officially support this given the current and planned state of all of the projects upon which we depend. If we go with the flawed result with many caveats we'll waste valuable time supporting people who stumble upon an unsupported combination. The more I think about this, the more I am convinced that even @snicoll's planned effort to see what breaks will be a waste of valuable time.

**Comment by philwebb** [comment]
We're not going to try and support Spring 4 with Boot 1.x

**Comment by jhoeller** [comment]
An interesting outcome of Stéphane's efforts: Our usual suspects - in their current production releases - are effectively compatible with Spring Framework 5.0 M4 already. Partly because they're explicitly testing for it in a CI build (like Spring Security), partly because we're simply keeping all key contracts in place, in particular between 4.3 and 5.0. So if we need "Spring Framework 5 compatible versions", we largely mean "with a reactive story"... whereas for traditional purposes, a core upgrade works so far already.

We've seen a lot of people doing an isolated framework upgrade back at Spring Framework 4.0's launch, hanging on to older versions of Spring Security etc... and I'm sure we're going to see some such efforts again with Spring Framework 5.0. From my perspective, it's better to know what they'll run into than to just leave them on their own. This is primarly about non-Boot scenarios of course, with people assembling their own stack, but it may happen with some Boot 1.5 users as well... and that's not a bad thing in my book if things have a chance of working for them. We're not going to officially support it but we need to be prepared for somebody trying it, and I don't want us to just tell them to stop.

Our recommendation for use with Spring Framework 5.0.x is certainly the then-latest Boot 2.0 milestone and the dependencies coming with it. It's like with JDK 9 and our intentions to make it a Spring-5-only topic: I nevertheless expect people to try Spring Framework 4.3 on JDK 9 even if we don't officially support it, and I'm applying some measures to make it work for them in that branch (like Objenesis 2.5 and CGLIB 3.2.5 upgrades), in particular for `-target 1.8` applications running on JDK 9 in classpath mode.
