### ISSUE TITLE
Rethink web application detection in SpringApplication

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#8017]
In pre 2.0 versions, `SpringApplication` would auto-detect the type of the application by checking the classpath:

* if `javax.servlet.Servlet` (comes with any Servlet container) and `org.springframework.web.context.ConfigurableWebApplicationContext` (comes with `spring-web`) are present, this is considered as a web application and a `AnnotationConfigEmbeddedWebApplicationContext` is used
* otherwise, this is not considered as a web application and a `AnnotationConfigApplicationContext` is used instead

This detection mechanism is no longer possible since we've got to support the following use cases:

Application | dependencies
------------ | -------------
Spring MVC + Tomcat | `Servlet` impl, `spring-web`, `spring-webmvc`
Jersey + Tomcat | `Servlet` impl, `spring-web`, `jersey-server`
Spring WebFlux + Tomcat | `Servlet` impl, `spring-web`, `spring-webflux`, `reactor-core`
Spring WebFlux + Netty | `spring-web`, `spring-webflux`, `reactor-core`, `netty-*`
Spring MVC + Tomcat + use of reactive `WebClient` | `Servlet` impl, `spring-web`, `spring-webmvc`, `spring-webflux`, `reactor-core`, `netty-*`

To solve this issue we should know:
* Add a new `WebApplicationType` for `REACTIVE`
* Update the detection mechanism with the new type

**Comment by wilkinsona** [comment]
I think the first two are relatively simple. I think we could update the detection to require the absence of `spring-web-reactive`. The third and fourth can just look for the required dependencies being available. The fifth is where things get tricky as it could be falsely detected as either combination three or combination four.

We have the problem today where we incorrectly start a web app due to some dependencies, and use `setWebEnvironment` on `SpringApplication` as an escape hatch. I think we may need to change the `setWebEnvironment(boolean)` method on `SpringApplication` to take an enum. Values could be something like `NONE`, `SERVLET`, and `REACTIVE`.

To help people migrate we could deprecate `setWebEnvironment(boolean)` in 1.5 and introduce the new enum-based method in 1.5 but only with `NONE` and `SERVLET`. We can then add the new value to the enum in 2.0.
