### ISSUE TITLE
Any way to replace Status.UP with Status.HAPPY?

### ISSUE THREAD

**Issue by donahchoo** [spring-projects/spring-boot#8020]
I'm trying to integrate Spring Boot Actuator with my companies existing infrastructure.  To do this I need to be able to customize the status message.    For instance if the app is up and running correctly I need to return a 200 and a plain text body of "HAPPY" from the health actuator endpoint.

Is such customization currently possible?  Since the Status class is final I can't extend it, but I think that would work.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by donahchoo** [comment]
Unfortunately no one has answered yet...  http://stackoverflow.com/questions/41731256/spring-boot-actuator-have-a-customized-status-as-plain-text
