### ISSUE TITLE
A PrefixMetricWriter is not auto-configured when using Java 8

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8064]
With Java 6 or 7, a `PrefixMetricWriter` is available (it's `InMemoryMetricRepository`). With Java 8, there's no `PrefixMetricWriter` available as `InMemoryMetricRepository` is replaced with `BufferMetricReader` but no writer equivalent. We only have two `PrefixMetricWriter` implementations: one is `InMemoryMetricRepository` and the other is `RedisMultiMetricRepository`.

@dsyer can you please offer some pointers on how to straighten this out?

**Comment by dsyer** [comment]
We only ever really advertised `CounterService` and `GaugeService` as user-facing APIs, so those are the ones that should be used for writing metrics. Maybe expecting to be able to `@Autowire` a `PrefixMetricWriter` is unreasonable to start with?

Irrespective of whether we keep the `@Bean`, it seems like maybe the prefixy bits of `InMemoryMetricRepository` should be rescued if possible, so that the feature is available at least (without having to go to Redis), but that's a different question?

**Comment by wilkinsona** [comment]
Thanks, @dsyer.

> Maybe expecting to be able to @Autowire a PrefixMetricWriter is unreasonable to start with?

I don't think it's unreasonable but perhaps I've missed something? It's hard to tell as `PrefixMetric` doesn't appear anywhere in the reference guide.

A concrete example would be trying to declare a `PrefixMetricGroupExporter`. With Java 6 and 7 I can do that with a single bean:

```java
@Bean
public PrefixMetricGroupExporter prefixMetricGroupExporter(PrefixMetricReader reader, PrefixMetricWriter writer) {
    return new PrefixMetricGroupExporter(reader, writer, "foo");
}
```

That blows up with Java 8 as there's no `PrefixMetricWriter`. A similar situation exists with `RichGaugeExporter` as it too needs a `PrefixMetricWriter`.

It seems broken that you upgrade to a newer JDK and things get harder to configure.

**Comment by jboverfelt** [comment]
Happened to see this issue as the opener of #7687 - I can say that I use the PrefixMetricWriter facilities in a production application that will soon be upgraded to Java 8. It's nice to have an API to clear our metrics by prefix in response to certain events. Consider this a vote for keeping that ability in some way.

**Comment by wilkinsona** [comment]
This will be addressed by the move to Micrometer-based metrics in 2.0
