### ISSUE TITLE
Custom Launcher not found - Spring Boot 1.5.0.M1

### ISSUE THREAD

**Issue by jjroldan1** [spring-projects/spring-boot#8065]
Using the LayoutFactory feature that will be released in 1.5 I have created my own Layout and connected it to the spring boot maven plugin. But I am having problems when I define a custom launcher in the layout:

`	@Override
	public String getLauncherClassName()
	{
		return "com.mycompany.CustomLauncher";
	}`

If I include my custom launcher in the boot application sources, it gets repackaged to BOOT-INF/classes, and when I try to run the JAR it fails with a ClassNotFound exception. 

I have been reading the Repackager code but I cannot find any hook that allows to selectively exclude a given class from the repackaging sequence. If I override the getRepackagedClassesLocation method in my layout then the boot main class is not accessible instead when I run the JAR.

Is there any way that I can force the launcher out of the BOOT-INF/classes repackaging?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
