### ISSUE TITLE
Introduce an enum for web environment on SpringApplication

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8077]
The introduction of Web Flux support in 2.0 will mean that we have a second kind of web application. As described in #8017, this makes `setWebEnvironment(boolean)` on `SpringApplication` insufficient. I think we need an enum. In 1.5, it'd only have two values: `NONE` and `SERVLET`. In 2.0 we can add `REACTIVE` or `WEB_FLUX` or whatever we want to call it. We'd then deprecate `setWebEnvironment(boolean)` in favour of a new method that takes the new enum.

We already have a `WebEnvironment` enum in the testing support with a different meaning so I think we may need another name. I wonder if it could be `WebApplication` with a corresponding `setWebApplication(WebApplication)` method on `SpringApplication`. `WebApplication` ties in quite nicely with `@ConditionalOnWebApplication` and could also complement more specific variants of that condition in 2.0 such as `@ConditionalOnServletWebApplication` and `@ConditionalOnReactiveWebApplication`.

**Comment by bclozel** [comment]
I've tried something along those lines in #8017 (taking from your advice). Happy to align that with you for 1.5.

**Comment by wilkinsona** [comment]
I wish I'd noticed that earlier… I've just finished a prototype of what I described above for 1.5: https://github.com/wilkinsona/spring-boot/tree/gh-8077. Naming aside, it looks like it aligns quite nicely with what you tried in 2.0.

**Comment by bclozel** [comment]
Great, it looks actually better. In my branch, the enum is hidden under `SpringApplication`, but making it a first class citizen aligns nicely with the testing support. Once it's in master I'll rebase my work on top of it.

I was about to ask the team to have that in 1.5 and deprecate `isWebEnvironment()` so that we can get rid of it in 2.0.

:shipit:

**Comment by snicoll** [comment]
:shipit:

**Comment by philwebb** [comment]
A lot of these deprecations could happen in 2.0 itself. We don't necessarily need to get them into 1.5.0

**Comment by bclozel** [comment]
Shall we then schedule this for 2.0.0.M1? 

This part is required by #8017 in order to add the `REACTIVE` variant to the enum. We can always change the enum name before the milestone release if we feel like it.

**Comment by wilkinsona** [comment]
> Shall we then schedule this for 2.0.0.M1?

Yeah, I think we should

**Comment by bclozel** [comment]
I temporarily rebased my changes against your commit and it seems a couple of tests are now failing in `ResourceServerTokenServicesConfigurationTests`.

It seems the `EmbeddedWebApplicationContext` is never used and the container is never started. I don't know why, all those tests are marked as `web(WebApplication.NONE)` (this is consistent, since they were marked as `web(false)` previously).
