### ISSUE TITLE
How to initialize MongoDB with script file and Spring Boot?

### ISSUE THREAD

**Issue by LucasHCruz** [spring-projects/spring-boot#8109]
Hi,

I need to initialize a Mongo DB with some script file like Spring do with JPA and `import.sql` file.. but how?

Can someone help me?

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by LucasHCruz** [comment]
[Stack Overflow link](http://stackoverflow.com/questions/41880235/execute-mongodb-script-on-spring-boot-start)

Thanks for reply!!!
