### ISSUE TITLE
Investigate OnValidatorAvailableCondition performance

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8110]
See timings in #7939

**Comment by wilkinsona** [comment]
I found it interesting that it's slower with the Freemarker sample than the Actuator sample. My guess is that that's because of a race with the background preinitializer. The Actuator sample takes longer to startup overall so the background preinitializer has made more progress by the time the validator condition is evaluated.

**Comment by wilkinsona** [comment]
Changing `BackgroundPreinitializer` so that `ValidationInitializer` goes first reduces the time for `OnValidatorAvailableCondition` to ~90ms (from ~130ms) for the Freemarker sample. The Actuator sample remained roughly the same at ~70ms.

**Comment by philwebb** [comment]
I wonder if there's a faster way to do the detection. Perhaps we can look at the `services` file.

**Comment by wilkinsona** [comment]
Thanks to the fix for #7598 which means that Hibernate Validator does not blow up in the absence of an EL provider, I think we may be able to just check for the presence of the `META-INF/services/javax.validation.spi.ValidationProvider` file on the classpath. We already do that so I think we may be able to get rid of `OnValidatorAvailableCondition`.

Have a missed something, @snicoll?

**Comment by snicoll** [comment]
Nope. As we've discussed if another EL implementation is on the classpath and breaks, there is something to be fixed in the build of the related app.
