### ISSUE TITLE
spring boot neo4j, if the string property of the domain object inputted long number string,the exception"argument type" happened 

### ISSUE THREAD

**Issue by gaurence** [spring-projects/spring-boot#8159]
when debug, the issue will be like this:
Failed to invoke method 'setCellPhone'. Expected argument type: class java.lang.String actual argument type: class java.lang.Long

note:  the cellPhone is String, but input is number.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
I'd suggest that you also try to provide a sample application if you post your question on stackoverflow.com.

**Comment by gaurence** [comment]
got it. thanks!
