### ISSUE TITLE
Add property liquibase.login-timeout

### ISSUE THREAD

**Issue by androidfred** [spring-projects/spring-boot#8177]
AS A
Developer using Spring and Liquibase

I WANT
A property liquibase.login-timeout= (same as spring.datasource.tomcat.login-timeout= but for Liquibase connections)

SO THAT
If MySQL initialization isn't complete by the time the app attempts to establish a db connection for Liquibase, the app can wait for a specified amount of time before failing to initialize.

MISC
This can be an issue when using Docker compose and plausibly any other solution where the whole stack is initialized at the same time.

**Comment by snicoll** [comment]
I am not keen to bring such complexity there. If you need to tune the `DataSource` beyond the basic settings offer by the auto-configuration, you can create your own `DataSource` any way you like and flag it with `@LiquibaseDataSource` so that the auto-configuration finds it. 

```java
@LiquibaseDataSource
@Bean
public DataSource yourDataSource() { ... }
```

I'll flag this one for team attention to see what the team thinks.
