### ISSUE TITLE
MongoProperties uri and host/port validation conflicts with EmbeddedMongoAutoConfiguration when having uri set

### ISSUE THREAD

**Issue by nicolas-nannoni** [spring-projects/spring-boot#8219]
Affects Spring Boot 1.5.1.

In integration tests, using an embedded MongoDB (auto-configured via `EmbeddedMongoAutoConfiguration`)  sets the `port` property of `MongoProperties` to a random port if `spring.data.mongodb.port=0` or was absent. Therefore, up till 1.4.x, overriding the port (and only that) to `0` would force the `MongoProperties` to use the embedded Mongo port, and it would ignore in the tests any `uri` otherwise defined.

With 1.5+, if `spring.data.mongodb.uri` is set otherwise (in the main `application.yml` for instance), the tests would not start and give `java.lang.IllegalStateException: Invalid mongo configuration, either uri or host/port/credentials must be specified` because `port` is set to a specific random value (when `MongoProperties.createMongoClient()` is called) together with some value in `uri`. Simply overriding the `uri` using `0` as port does not work either as `EmbeddedMongoAutoConfiguration` forcefully sets the `port` property regardless.

Possible solutions? 
* A more lenient check on `uri` in `MongoProperties.createMongoClient()` (`this.uri != null && !this.uri.isEmpty()`) could allow overriding `spring.data.mongodb.uri` to an empty string in integration tests and not have to change the main application configuration. 
* Avoiding setting the `port` property in `EmbeddedMongoAutoConfiguration` if it is unset initially and replace the port part in the `uri` instead when a `uri` is provided.

**Comment by pacey** [comment]
Just to let you know that we are also having trouble with the changes added to 1.5, but for our production code. We connect out mongo cluster giving the full uri, but because the port is null the if on line 110 in EmbeddedMongoAutoConfiguration.java is triggered and a random port is generated. This is problematic as when the mongo client is built we have a port and uri set and we get the exception `java.lang.IllegalStateException: Invalid mongo configuration, either uri or host/port/credentials must be specified`.

Because that if now includes the null check, we can't do anything to make it work :(

**Comment by wilkinsona** [comment]
@pacey Are you using embedded Mongo in production?

**Comment by pacey** [comment]
Nope, just for tests.

**Comment by wilkinsona** [comment]
@pacey In that case, I am confused.

> but for our production code

> EmbeddedMongoAutoConfiguration.java is triggered

`EmbeddedMongoAutoConfiguration` should be switched off in the absence of embedded Mongo. Perhaps you are saying that it's a problem with the testing of your production code?

**Comment by snicoll** [comment]
Regardless, a sample would be cool.

**Comment by pacey** [comment]
@wilkinsona @snicoll Apologies :) This was happening because our dependency on embedded mongo was at `compile`, when it should have been `testCompile`. My bad.

**Comment by michelzanini** [comment]
This problem is also affecting me.
I am going to attach a sample project here to help explain the issue.

Basically, I can't figure a way of testing with embedded mongo on a random port after 1.5.1.
The test I wrote on this sample project does not pass on 1.5.1, but, if changed to 1.4.x, it does pass.

So maybe you could help suggesting a work around, or maybe fix this on 1.5.2?

[mongo-setup.zip](https://github.com/spring-projects/spring-boot/files/801413/mongo-setup.zip)

**Comment by snicoll** [comment]
This is a regression introduced while fixing #6739

**Comment by snicoll** [comment]
I guess we should rather have a completely different path when `local.mongo.port` is set. After all, embedded mongodb is starting so we want to connect to that (otherwise, why would it be there in the first place?). The previous code worked a bit as a side effect anyway.

**Comment by Fabrice-Deshayes-aka-Xtream** [comment]
i confirm this is a regression which prevent me to upgrade my application from spring boot 1.4.0 to 1.5.1 :-(
