### ISSUE TITLE
Duplicate javax.validation.ValidatorFactory Beans on 1.5.1

### ISSUE THREAD

**Issue by lpborges** [spring-projects/spring-boot#8223]
Hi, I'm trying to migrate a application from Spring Boot 1.4.4 to 1.5.1 and found a problem using a third party library.
The problem is that the lib use a `@Inject javax.validation.ValidatorFactory`, and Spring Boot 1.5.1 now have 2 beans of this type, and none is `@Primary`. (from the /beans actuator):

```json
{
  "bean":"validator",
  "aliases":[],
  "scope":"singleton",
  "type":"org.springframework.validation.beanvalidation.LocalValidatorFactoryBean",
  "resource":"class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]",
  "dependencies":[]
},
{
  "bean":"mvcValidator",
  "aliases":[],
  "scope":"singleton",
  "type":"org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean",
  "resource":"class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]",
  "dependencies":[]
}
```

This generate the follow exception:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cz.jirutka.validator.collection.CommonEachValidator': Unsatisfied dependency expressed through field 'factory'; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'javax.validation.ValidatorFactory' available: expected single matching bean but found 2: mvcValidator,validator
```

One solution could be mark one of this beans as `@Primary`.

**Comment by dthume** [comment]
If possible, it would make life a lot simpler (for me at least) if `@Primary` was _not_ used to resolve this, but rather `@Qualifier` or `@Resource(name=...)`. We've been bitten a few times during upgrades by new `@Primary` beans being added (the most recent being a Jackson `ObjectMapper`), and while we've managed to work around the issues, it has eaten up a considerable amount of time trying to maintain compatibility between different versions of Spring Boot (which we strive for in library code since we have too many Spring Boot based services to force them all to upgrade in tandem).

**Comment by snicoll** [comment]
The `ObjectMapper` is primary since the beginning in Spring Boot (I guess you're referring to a regression introduced by HAL and/or Spring Data REST). I already said to @lpborges on Gitter that I am not convinced that marking it `@Primary` was a good option. We do provide a nice customization if  `javax.el` isn't on the classpath. We still need to figure out what to do with the one provided by Spring MVC.

**Comment by snicoll** [comment]
OK I've tried to fix this and that does not work. After a quite deep analysis I understand now what is going on. This was actually [raised already](https://jira.spring.io/browse/SPR-12194) by @wilkinsona 

The problem is that the MVC validator returns a `org.springframework.validation.Validator` but the default implementation _is also_ a `javax.validation.ValidatorFactory`. When we check if a `ValidatorFactory` bean is present, the answer is no since the only thing we know is the bean factory type (`org.springframework.validation.Validator`). So we create the bean. 

At runtime if we try to inject and `ValidatorFactory`, it might blow up because the thing that was exposed as a `org.springframework.validation.Validator` is actually a `ValidatorFactory` as well. As a matter of a fact, `LocalValidatoryFactoryBean` which is a public API of the framework and the default in MVC land, does _exactly_ that.

So our current infrastructure does not allow us to figure out that when we decide to create the bean. In the end, we end up with two `ValidatorFactory`. 

There are a couple of things that we could do:

* Avoid exposing the `ValidatorFactory` at all. The problem is that it's a signal for other auto-config (like enabling validation in Couchbase and that auto-configuration suffers the exact same problem)
* Find a way to override the method signature that Spring MVC provides for our default config. That way the proper type will be exposed and the conditions will work
* Craft a specific "Is a JSR 303 validator is available" and use that instead of `@ConditionalOnBean(Validator.class)`. But I have no idea how we could implementation such condition

I like the second option but I have no idea if that's doable.

**Comment by rstoyanchev** [comment]
I guess you could override the `mvcValidator` bean declaration [around here](https://github.com/spring-projects/spring-boot/blob/923393d5af80077c558b5b1bdc5cc882a12334a0/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration.java#L353) in the `WebMvcAutoConfiguration`. Then return a `org.springframework.validation.Validator` wrapper around the validator created from `super`, enough to comply with the method signature but otherwise "hiding" the `ValidatorFactory` and `javax.validation.Validator` interfaces. The wrapper would also have to implement and delegate lifecycle methods like `InitializingBean`, `DisposableBean`, etc

**Comment by snicoll** [comment]
I don't think that's helping. So far users have relied on the fact that this validator is actually also a JSR-303 one so we would remove that feature from them. I think the only sane way is to be able to tell what it really is rather that hiding what i can do (because it's doing it now so changing that is a backward incompatible change).

**Comment by snicoll** [comment]
Maybe I misunderstand how all this works but if a user is currently tuning this in a MVC config and expect that to be exposed as a standard validator? If we stop exposing it, any use case where it is customised at that level will break. 

Am i missing something? Thanks!

**Comment by rstoyanchev** [comment]
There could be situation like that indeed, although again the `@Bean` returns a Spring `Validator`. The Boot Validator auto config overlaps in purpose with that from Spring MVC. Unless we want to explicitly allow for both to co-exist as standard bean validators (e.g. differently configured for web tier vs other parts of the application) then why not encourage more explicitly use of Boot's Validator auto config in a Boot application?

**Comment by snicoll** [comment]
okay looks like a valid way out to me. Let me try to translate that to code. Thanks!

**Comment by snicoll** [comment]
@rstoyanchev @bclozel I have pushed something that fixes the issue but creates another problem. 

In short, Spring Boot now always exposes a `Validator` via the `getValidator()` method of the configurer. If there is a `javax.validation.Validator` in the context already we reuse that (so we are promoting our general validation auto-configuraton story. If there isn't any, then we do what Spring MVC does by default. 

The reason why we always expose a `Validator` now is because we wrap that in an object that only exposes Spring's `Validator` interface. That way, we avoid the situation where we have two beans of that type in the context. That is solving this issue.

However, there is a regression. Previously, if a user had a `WebMvcConfigurer` that returns something for `getValidator()` we would use that as the validator. Now that throws an exception because the one boot provides has also an opinion about that.

I am not sure how I could fix that. Perhaps I should look for the presence of Spring's `Validator` in the context?

**Comment by rstoyanchev** [comment]
Indeed the use of `WebMvcConfigurer` to wrap or supply the the `Validator` puts you on equal footing with other configurer's. For this I thought it might be more appropriate to override the `@Bean` declaration of `mvcValidator`. You would then be in a position to see if a validator was provided and if so to wrap it, or it wasn't to supply it:
````java
@Bean
public Validator mvcValidator() {
	Validator validator = getValidator();
	if (validator == null) {
		// wrap...
	}
	else {
		// supply...
	}
	return validator;
}
````

**Comment by snicoll** [comment]
Good point @rstoyanchev, thanks!

**Comment by matthewsommer** [comment]
I'm trying to upgrade from Spring 1.5.1 to 1.5.2 and am getting an exception below. I've attached the full stack trace.

Regarding requestMappingHandlerAdapter, I'm using that to get the redirectURL from requests. Maybe I'm getting something related to this issue: https://github.com/spring-projects/spring-boot/issues/8760

[Spring1.5.2ValidatorStackTrace.txt](https://github.com/spring-projects/spring-boot/files/908340/Spring1.5.2ValidatorStackTrace.txt)

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appConfig': Unsatisfied dependency expressed through method 'setContentNegotationStrategy' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webMvcConfig': Unsatisfied dependency expressed through field 'requestMappingHandlerAdapter'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Circular reference involving containing bean 'org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'requestMappingHandlerAdapter' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mvcValidator' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.validation.Validator]: Circular reference involving containing bean 'org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'mvcValidator' threw exception; nested exception is java.lang.NullPointerException

**Comment by snicoll** [comment]
@matthewsommer that exception seems unrelated to this issue. Please create a separate issue with a sample to reproduce

**Comment by Dr4K4n** [comment]
I previously had the same issue than the thread author, my boot application didn't know which `javax.validation.ValidatorFactory` to use after upgrading to 1.5.1.
I fixed this by providing my own ValidatorFactory bean:
```
    @Bean
    @Primary	
    public ValidatorFactory getValidatorFactory() {
        return new LocalValidatorFactoryBean();
    }
```

Now, when I upgraded to 1.5.4, I had the same problem again. I fixed it by simply removing above method again.
