### ISSUE TITLE
org.springframework.boot.orm.jpa.EntityScan on Spring Boot 1.5.0-snapshot

### ISSUE THREAD

**Issue by darkmanAmazigh** [spring-projects/spring-boot#8231]
Hi and thank you for this great work, 

The EntityScan class has removed from SpringBoot 1.5.0-SNAPSHOT,
When i change to 1.3.0-SNAPSHOT version, EntityScan exist.

i must add another dependancy to use EntityScan with SpringBoot 1.5.0-SNAPSHOT ?

Thank you

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by wilkinsona** [comment]
In addition to what @snicoll just said, the answer is in the release notes: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#entityscan

**Comment by snicoll** [comment]
I was about to write that. You're too fast @wilkinsona :)

**Comment by darkmanAmazigh** [comment]
http://stackoverflow.com/questions/42109977/org-springframework-boot-orm-jpa-entityscan-on-spring-boot-1-5-0-snapshot

**Comment by darkmanAmazigh** [comment]
with 1.4.0-SNAPSHOT i have no problem

my declaration is like
@EntityScan("fr.cc.suivireco.productionmanagement.dataaccess.api")

**Comment by darkmanAmazigh** [comment]
Ok, thank you,

my eclips not propose me the new import for entityscan, i do no why !!
this new import work fine 
import org.springframework.boot.autoconfigure.domain.EntityScan;
