### ISSUE TITLE
Spring-boot-test: Mock beans are carried on between test cases

### ISSUE THREAD

**Issue by robertofpaf** [spring-projects/spring-boot#8242]
We are experiencing a problem with @SpringBootTest test cases with Spring Boot 1.4.3: we have 3 separate test classes, two of them are using a mocked version of a bean using the @MockBean annotation and the third should use the regular implementation of the bean.

When running the tests manually from the IDE they work as expected but when run by gradle in the build process all the tests (including the one that doesn't mock it) are using the mocked version of the bean.

So it looks to me that when @MockBean is used the application context is not cleaned when the test class is over (if I would mock manually the bean I would revert to the previous state in an @After or @AfterClass method).

I've now worked it around by instructing gradle to use a different JVM for every test class but I believe the Spring Boot testing framework should take care of similar situations itself.

**Comment by snicoll** [comment]
That inconsistency looks weird to me. Could you please share a sample that reproduces what you're experiencing?

**Comment by robertofpaf** [comment]
Here a test application that reproduces the issue: [testcase.zip](https://github.com/spring-projects/spring-boot/files/763584/testcase.zip)
Just run ./gradlew build and you'll see one test failing as it's getting null from the mock instead of the hardcoded value from the service implementation.

One thing I've noticed is that this happens only if the test cases access the application using feign/hystrix. With a TestRestTemplate this doesn't happen so I'm not anymore sure is it a spring-boot-test problem or a feign/hystrix one at this stage...

**Comment by snicoll** [comment]
What happens is that the feign client in `IntegrationTest` is invoking the server started by `HelloControllerTest`. So the reason why the mock is created is because you're calling the wrong server. I don't know enough about Feign to help you configure your test properly but I'd advise to ask on stackoverflow.

You can add `@DirtiesContext` on `HelloControllerTest` and you'll see feign in `IntegrationTest` trying to connect to a server that isn't there anymore.
