### ISSUE TITLE
Spring-data-elasticsearch and jest for cloud provider

### ISSUE THREAD

**Issue by javadev** [spring-projects/spring-boot#8250]
Question

Please help me integrate spring-data-elasticsesrch with jest cloud provider in heroku.

I changed url, but my data only stored locally.

Kind regards, Valentyn

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
