### ISSUE TITLE
How to debug a spring-boot app with gradle, vaadin and IntelliJ?

### ISSUE THREAD

**Issue by rpomeroy** [spring-projects/spring-boot#826]
Can someone document now to easily use this in junction with IntelliJ Idea to debug a spring-boot app?   Surely I'm not the only guy on the planet using Vaadin+Spring-boot+Gradle+Idea!  

Then again...

https://github.com/Muhuru-Bay-Microgrid/muhuru-bay-dashboard

**Comment by snicoll** [comment]
There is a spring boot support in Vaadin and Devtools support. Any vaadin-specific feature (`devmode`) should be asked on the vaadin forum.

**Comment by adkins2010** [comment]
@pcornelissen , I think that this document isn't there any longer.  Clicking on the link only takes you to the top and doesn't snap at any subsection.  I haven't found where it instructs the user on how to debug a gradle bootrun from IntelliJ.

**Comment by pcornelissen** [comment]
I'm using maven, so I have no experience with that. But if you want to debug you can just run the application class with the main method in debug mode for example in your IDE. I use that all the time and it works great.

**Comment by drumaddict** [comment]
I am surprised to find out that there's no standard instruction anywhere on how to debug a gradle Spring Boot project from Intellij.

**Comment by pcornelissen** [comment]
You should be able to just start the application using the main method in debug mode

**Comment by drumaddict** [comment]
Update: Finally got it to work. Starting the main application doesn't work for me because I configure the environment in my gradle script.

 The first step is to set up a normal debug configuration that runs gradle's `bootRun` task. The key is to make the application listen to port 5005 when it starts, instead of launching immediately. To do that one has to apply the gradle application plugin in `build.gradle` and then apply these JVM vars:
` apply plugin: 'application' `
`applicationDefaultJvmArgs = ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005" ]`
In my case, I apply the JVM vars in `dev` environment, but I will possibly use a dedicated `debug` profile for debugging. Note that gradle does not support profiles out of the box, one needs to set them up.

Second step is to set up a Remote run configuration from Intellij. The defaults are sufficient. This remote configuration attaches the debugger on port 5005 and starts the application that listens on the same port.

Extra tip: The gradle's `bootRun` run configuration has to be launched first, then the remote must follow.
The remote one  can be configured to automatically launch the bootRun configuration before it starts itself with `Before launch :` feature.

Hope this helps.


![image](https://user-images.githubusercontent.com/323951/34093332-48eba718-e3d0-11e7-9a25-dc367ade9512.png)

![image](https://user-images.githubusercontent.com/323951/34093347-61ff14f6-e3d0-11e7-8e8c-5adf65df7a29.png)
