### ISSUE TITLE
Disable autoconfiguration

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-boot#8265]
```
import org.springframework.boot.*;
import org.springframework.boot.autoconfigure.*;
import org.springframework.web.bind.annotation.*;

@RestController
@SpringBootApplication
public class Example {

    @RequestMapping("/")
    String home() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(Example.class, args);
    }

}
```

I don't need any filters, any security, I want that after Spring received request and checks routing it will call _home_ method. I want to start from scratch and add features as I need it.

Is there a way to configure Spring Boot to achieve that?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by raderio** [comment]
[Disable all modules in Spring Boot hello world application](http://stackoverflow.com/questions/42188038/disable-all-modules-in-spring-boot-hello-world-application/42188145)
