### ISSUE TITLE
Static Content 404 error

### ISSUE THREAD

**Issue by eonie** [spring-projects/spring-boot#8266]
When i using Spring Boot 1.4.3, I can visit static content directly by default configration,  but after upgrade to Spring Boot 1.5.1, the same url show me a 404 error, i need to add the static path by override `addResourceHandlers`.
``` java
@Configuration
public class WebConfig extends WebMvcConfigurerAdapter {
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/doc/**")
                .addResourceLocations("file:~/doc/")
                .setCacheControl(CacheControl.maxAge(1, TimeUnit.HOURS).cachePublic());
        registry.addResourceHandler("/static/**")
        .addResourceLocations("classpath:static/")
        .setCacheControl(CacheControl.maxAge(1, TimeUnit.HOURS).cachePublic());
    }
    

}
```
Here is my code[https://github.com/eonie/springboot-mvc-test](url), thanks if someone could help me.

**Comment by wilkinsona** [comment]
Thanks for the sample. It works for me with both 1.4.3.RELEASE and 1.5.1.RELEASE. In the README you have said to visit http://localhost:8080/static/index.html. That produces a 404 in both cases. Visiting http://localhost:8080/index.html works in both cases. This is the expected behaviour as, by default, static resources are mapped to `/**`. If you want them to only be available beneath `/static` you can set the `spring.mvc.static-path-pattern` property to `/static/**`.

**Comment by eonie** [comment]
Thanks for you help, now i'm know the behaviour and how to change it .
