### ISSUE TITLE
@WebFilter support @Order 

### ISSUE THREAD

**Issue by sdcuike** [spring-projects/spring-boot#8276]
Hi, I do something in order to `@WebFilter` support `@Order` [here](https://github.com/sdcuike/spring-boot-practice/commit/f873e3f60bee678c3c661000cea71df0c3b78030)

But, due to

```java
private void org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ListableBeanFactory beanFactory)

protected  Servlet org.springframework.boot.web.servlet.ServletRegistrationBean.getServlet()

protected String org.springframework.boot.web.servlet.DelegatingFilterProxyRegistrationBean.getTargetBeanName()
```

method  access privilege，implement are not elegant。

So，method  access privilege above this method， can public or protect。

**Comment by wilkinsona** [comment]
In my opinion, supporting `@Order` on `@WebFilter` doesn't really gain you very much. The former is a Spring concept and the latter is from the Servlet API. The Servlet spec doesn't provide a way to order filters when they're registered using annotations. Spring Boot's support for `@WebFilter` is in line with that.

 If you are in a position to annotate your class with `@Order` then you're also in a position to use `@Component` rather than `@WebFilter`. At that point ordering will be supported as you've indicated that it's a Spring-managed component so the concept of ordering makes sense.

Can you please describe that problem that you're trying to solve, rather than the difficulty that you're having in solving it?

**Comment by sdcuike** [comment]
I want order filter  ，but not implement this：[https://github.com/sdcuike/spring-boot-practice/blob/master/src/main/java/com/sdcuike/practice/web2/WebComponent2Config.java](https://github.com/sdcuike/spring-boot-practice/blob/master/src/main/java/com/sdcuike/practice/web2/WebComponent2Config.java)

**Comment by wilkinsona** [comment]
Thanks. Just to confirm, you want to use `@WebFilter` because it lets you configure the filter without using `FilterRegistrationBean` and you also want to control the order?

**Comment by sdcuike** [comment]
yes，thanks

**Comment by chainkite** [comment]
+1, as `@Component` cannot support `urlPatterns` in @WebFilter

**Comment by philwebb** [comment]
@chainkite You can configure `urlPatterns` using a `FilterRegistrationBean`

**Comment by philwebb** [comment]
I don't think that we should support `@Order` with `@WebFilter`. As @wilkinsona mentioned the Servlet spec doesn't provide a way to order filters and I don't think we should support something that works in the embedded mode but not when deployed to a regular servlet container.

**Comment by wilkinsona** [comment]
>  I don't think we should support something that works in the embedded mode but not when deployed to a regular servlet container

That's a very compelling argument not to do this. I think the confusion that would cause greatly outweighs the few lines of code that it would save.

**Comment by sdcuike** [comment]
Thanks for answer

**Comment by hongsir** [comment]
thank you very much!

**Comment by fssrepository** [comment]
What about this?

@WebFilter(Constants.FORM_BASE + "/login/check")
public class LoginFilter extends UsernamePasswordAuthenticationFilter {
