### ISSUE TITLE
@LastModifiedDate in spring doesn't update efter updating an entity , why ? 

### ISSUE THREAD

**Issue by menaalkass** [spring-projects/spring-boot#8298]
public class WorkItem {
	@Id
	@GeneratedValue
	private long id;

	@Column(nullable = false, updatable = false)
	@CreatedDate
	private Date createDate;

	@Column(updatable = true)
	@LastModifiedDate
	private Date lastModifiedDate;

	@Column(nullable = false, updatable = false)
	@CreatedBy
	private String createdBy;

	@Column(updatable = true)
	@LastModifiedBy
	private String lastModifiedBy;

when I'm updating this entity lastModifiedDate still with date of saving with out new updating, I'm using Mysql as database program

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
