### ISSUE TITLE
Update Spring Cloud OpenShift Deployment

### ISSUE THREAD

**Issue by cmoulliard** [spring-projects/spring-boot#8349]
The Spring-Boot cloud deployment of [OpenShift](http://docs.spring.io/spring-boot/docs/current/reference/html/cloud-deployment.html#cloud-deployment-openshift) relies on the version 2 of the OpenShift platform which has been turned into a Docker/Kubernetes platform since version 3.x

I would like to suggest that we update the documentation to describe how we can build/package a spring boot application using the 
- Fabric8 Maven plugin (docker builder & openshift/kubernetes client) able to push the Spring Boot Uber jar file - Docker image to the platform and run it as a service

**Comment by wilkinsona** [comment]
I'd prefer that we take the same approach as was recently taken for documenting the deployment process for Elastic Beanstalk. We deliberately didn't cover lots of the technical specifics, preferring to link out to Beanstalk's own documentation, so that there's a better chance that the documentation will remain up-to-date. Is there something similar that we could link to in OpenShift's documentation?

**Comment by cmoulliard** [comment]
Yes. As the Fabric8 Maven plugin will use the S2I (Source to Image) Build process to push a binary the compiled project, we can refer to the OpenShift documentation for the generality [process](https://docs.openshift.com/enterprise/3.2/dev_guide/builds.html#overview) & just explain how to use the maven plugin to build & deploy on OpenShift `mvn fabric8:deploy`.

Here is a quickstart that we propose to the developers/architects to package/deploy a SpringBoot application on the [paas](https://github.com/obsidian-toaster-quickstarts/rest_springboot-tomcat#openshift-online)

**Comment by wilkinsona** [comment]
Closing in favour of #10609.
