### ISSUE TITLE
'jpaContext' bean creation error.

### ISSUE THREAD

**Issue by spdeepak** [spring-projects/spring-boot#8352]
Hi, The code I've written can be seen here. https://bitbucket.org/spdeepak/hospital-booking-system/src

I get the below error when I run my test. 

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jpaContext': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.Set<javax.persistence.EntityManager>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
`

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by keertimalav** [comment]
'java.util.Set<javax.persistence.EntityManager>'
