### ISSUE TITLE
No Complete status since 1.4 for health check 

### ISSUE THREAD

**Issue by pvpkiran** [spring-projects/spring-boot#8394]
The health check monitoring url `/internal/mon/health` provided by spring boot actuator doesn't display complete status since 1.4

Prior to 1.4 this url used to give a complete status of all the database connections. But after 1.4 I just get this over all status {"status":"UP"}

But If I disable the authentication

`management.security.enabled= false`
then I get the complete status.
Is it possible to get the complete status with authentication enabled.

But with version < 1.4 this works with security enabled.

Thanks

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
