### ISSUE TITLE
Update `@RestClientTest` to work with `WebClient`

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#8404]
If WebFlux is on the classpath it would be cool if `MockRestServiceServer` could be configured with a `WebClient`instred of a `RestTemplate`.

Since both will be on the classpath (`RestTemplate` is in a shared module), the annotation should probably have an attribute to indicate a preference. Not sure that both can be used at the same time though.

```java
@RestClientTest(useWebClient=true)
```

An enum will be better but I can't find good names for the values (`REST_TEMPLATE` is pretty gross).

This currently requires some changes in Spring Framework, I've [created an issue](https://jira.spring.io/browse/SPR-15286)

**Comment by mickaeltr** [comment]
Hello,

Does anyone has any update on this one?

I was about to migrate my code to `WebClient` [as recommended](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/client/RestTemplate.java#L75), because `RestTemplate` / `OAuth2RestTemplate` are in maintenance mode… but the lack of testing support makes it inconvenient in the end.

Using [`MockWebServer`](https://github.com/square/okhttp/tree/master/mockwebserver) is an option, but it's not as elegant as `RestClientTest`.

Thanks

**Comment by wilkinsona** [comment]
The Spring Framework team have declined [the issue that was blocking this one](https://github.com/spring-projects/spring-framework/issues/19852). Their [recommendation](https://docs.spring.io/spring-framework/docs/5.2.6.RELEASE/spring-framework-reference/web-reactive.html#webflux-client-testing) is to use `MockWebServer. Given that's the situation, there's nothing that was can do here.

**Comment by mickaeltr** [comment]
Thanks for the insight @wilkinsona

**Comment by jbotuck** [comment]
Can you have the slice autoconfigure a webclient and an okhttp server?

**Comment by philwebb** [comment]
@jbotuck Please ask questions on stackoverflow.com or gitter.im. We prefer to keep the issue tracker for bugs/enhancements only.

**Comment by jbotuck** [comment]
Sorry if I'm having trouble navigating this. This wasn't a question as much as a feature request. The current issue concludes with : won't support a test slice for webclient since the spring mock Web server doesn't support webclient

I'm here to ask for a test slice that uses okhttp mock server instead.

This might be worthy of its own GitHub issue, but as you saw, I tried that already.
