### ISSUE TITLE
ObjectPostProcessor is a required bean, ensure you have used @EnableWebSecurity and @Configuration

### ISSUE THREAD

**Issue by erhsuresh** [spring-projects/spring-boot#8414]
I have an exsting Spring MVC 4.2.0 app and trying to migrate to spring boot 1.5.1. If I start my war with java -jar filename.war, I am getting `ObjectPostProcessor` is a required bean exception.

Kindly find the attached POM and log files. If I run the same app without any of my application components, it works fine. If I try to include all my components, its not working.

At the same time, if I deploy the war file in to tomcat webapp folder, it works fine. Issue only when you start the app by java -jar file.war.

Please help me to resolve this issue. Thanks.

Regards,
Suresh.H
[log.txt](https://github.com/spring-projects/spring-boot/files/802485/log.txt)

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
I suspect this is a configuration issue but If you think you've actually found a bug, please provide a sample that replicates the issue.
