### ISSUE TITLE
 set autoReconnect=true, can't work.

### ISSUE THREAD

**Issue by carvendy** [spring-projects/spring-boot#8415]
Question
    throw 
 com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 235,873,616 milliseconds ago.  The last packet sent successfully to the server was 235,873,629 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

  set autoReconnect=true, can't work.

Bug report

    why ? 

Enhancement

     I think maybe use mutil datasource，can' work .

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
