### ISSUE TITLE
Using @ContextConfiguration(initializers=…) disables finding of @SpringBootConfiguation class

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#8483]
`SpringBootTestContextBootstrapper` returns an unchanged array of configuration classes when the merged config contains any context initializer classes. This means that you can't use `@ContextConfiguration(initializers=…` without then also providing your `@SpringBootConfiguration` class as well.

There may well be a good reason for this, but I can't think of what it may be. Some sniff testing suggests that removing the restriction doesn't do any harm. It's been there since the support for finding the `@SpringBootConfiguration` class [was introduced](https://github.com/spring-projects/spring-boot/commit/90950cfb1c1575313b364054e264ab69035ac6b5)

**Comment by philwebb** [comment]
I think the logic here was that the configuration class should _only_ search for the `@SpringBootConfiguration` if the user hasn't defined anything. With the `containsNonTestComponent(classes)` and `mergedConfig.hasLocations()` checks it's pretty obvious the user has defined their own config.

The `!mergedConfig.getContextInitializerClasses().isEmpty()` is there because the `ApplicationContextInitializer` _could_ register configuration. Of course, it also might not! I think I was just being super cautious.

In hindsight, I don't think it's likely that a `ApplicationContextInitializer` will be registering the main configuration. Even if it does, it would be pretty easy to "fix" by just adding a nested `@Configuration` class.

**Comment by philwebb** [comment]
Question is do we want to change this in 1.5.x or not?

**Comment by wilkinsona** [comment]
It's not a huge deal as you can just do this:

```java
@SpringBootTest(class=MyApplication.class)
@ContextConfiguration(initializers=MyInitializer.class)
```

However, I think the risk is pretty low of changing it and the current behaviour does feel a bit like a bug. I think I'm leaning towards changing it in 1.5.3.

**Comment by philwebb** [comment]
Yeah, it feels like using an `ApplicationContextInitializer` to initialize the `ApplicationContext` is much more likely than using it to register the main `@Configuration`.
