### ISSUE TITLE
Multiple 'org.springframework.validation.Validator' beans are exposed as of Spring Boot 1.5

### ISSUE THREAD

**Issue by okohub** [spring-projects/spring-boot#8495]
Hello,

Looks like there are more than one org.springframework.validation.Validator type beans in context when using spring-boot-starter-web

First one is coming from: jsr303Validator, that is defined in 
```org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration```

Second one is coming from: mvcValidator,  that is defined in 
```org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration.EnableWebMvcConfiguration#mvcValidator```

Thanks!

You can check test in sample project: https://github.com/okohub/validatorproblem

**Comment by snicoll** [comment]
Yes. How is that a problem? The JSR303 validator exposes a standard `javax.validation.Validator` which is the type that you should inject. If you want the `mvcValidator`, just qualify it but behinds the scenes (in your project) this is the same bean.

There is nothing we can do as Spring MVC exposes a mvc validator. If you do not want such validator to be bound automatically, exclude the `ValidationAutoConfiguration`.

**Comment by snicoll** [comment]
relates to #8481

**Comment by kappmeier** [comment]
We got the same when upgrading from 1.4 to 1.5. Validator has not been used before, so as a quick workaround we could solve this by setting

`@EnableAutoConfiguration(exclude = {ValidationAutoConfiguration.class})`

**Comment by snicoll** [comment]
I've considered various options and flagging the validator used in auto-configuration `@Primary` seems like the only option I have left.

**Comment by snicoll** [comment]
@philwebb do you want to investigate other options? Anything that'd avoid flagging ours `@Primary` is worth a shot IMO.

**Comment by philwebb** [comment]
@snicoll I wanted to have a look at other options, I just haven't managed to find the time yet.

**Comment by snicoll** [comment]
@philwebb gentle ping

**Comment by philwebb** [comment]
@snicoll I've left this one quite late :/

What about something like this: https://github.com/philwebb/spring-boot/commit/58674e6eecdfff83ab116042de25d762f3a114b3

The `ValidationAutoConfiguration` could define a validator bean with an alias of `mvcValidator`, we then add a condition on `EnableWebMvcConfiguration.mvcValidator` to skip it if such a bean name exists.

I think it almost works except there is the case of a `WebMvcConfigurer` implementing a `getValidator` method. I'm wondering if we could check that no validator has been defined using that method and throw an exception if one has. Using `WebMvcConfigurer` is a bit odd anyway in Boot since `ValidationAutoConfiguration` can't detect it. We could just chuck out a message telling people to register an `mvcValidator` bean instead of using a `WebMvcConfigurer` (which is more idiomatic Boot anyway).

**Comment by snicoll** [comment]
The idea is very interesting but some changes will definitely break other stuff. I've added a few comments on the commit.

I think if we do this, we should simply reject the case of someone configuring a `Validator` using `WebMvcConfigurer`. Like you said, registering a bean is more idiomatic). I also remembers that @rstoyanchev had the same idea.

**Comment by rstoyanchev** [comment]
Since Boot extends DelegatingWebMvcConfiguration you already know if a Validator is registered through WebMvcConfigurer. The current implementation already [checks for a Validator](https://github.com/spring-projects/spring-boot/blob/56c68ca6cf45b5166b51617e8d72952f160f595f/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.java#L412) registered that way.

+1 for Boot taking over the mvcValidator declaration.

**Comment by snicoll** [comment]
@philwebb I've  squashed and pushed your work https://github.com/snicoll/spring-boot/commit/5d43c9ff34245d6af882c1efa623f4b7b3a20b22 - see comments

**Comment by snicoll** [comment]
@okohub when we tried to fix this, we broke 1.5.3 and we're working on a fix for 1.5.4. We spent countless of hours on this and I am still not sure at this point what could be the right way to do this. 

You've attached a sample that demonstrates the problem but you haven't described what you are concretely doing in your app. So far we've seen two people reporting this issue and @kappmeier said a workaround is to disable `ValidationAutoConfiguration`. 

I am thinking now marking the validator created by auto-config `@Primary` but this can lead to other regressions if you've defined a Spring Validator `@Primary` yourself. I don't want to do a 1.5.5 because we broke the release again.

An "'mvc` Validator is provided but others can be added. What is your use case to inject the Spring's `Validator` by type in your project?

**Comment by abelsromero** [comment]
> So far we've seen two people reporting this issue and @kappmeier said a workaround is to disable ValidationAutoConfiguration.

Count 3! :hand:

I went ahead and disabled `ValidationAutoConfiguration`.

**Comment by ericjturley** [comment]
We've been watching this issue and waiting for a fix as well.
We were at boot 1.5.1, and can't upgrade to 1.5.2 without a fix or workaround

**Comment by snicoll** [comment]
Please give 1.5.4.BUILD-SNAPSHOT a try. We're about to release it.

**Comment by ericjturley** [comment]
Just changed it to 1.5.4.BUILD-SNAPSHOT, but doesn't fix it for us.
We get:
`Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.validation.SmartValidator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

**Comment by ericjturley** [comment]
Actually, looks like it fixed it. 
I *thought* I needed to inject a `SmartValidator`, but apparently I was incorrect. Changing it to a `Validator` works.

**Comment by snicoll** [comment]
Thanks (no you shouldn't inject that interface it's an internal of the framework). 


@abelsromero could you please test the snapshot?

**Comment by abelsromero** [comment]
> @abelsromero could you please test the snapshot?

:+1:   Upgraded from 1.5.2 and it works perfectly without `ValidationAutoConfiguration`.

**Comment by snicoll** [comment]
That's not what I am asking you. Disabling the auto-configuration is not something you're meant to do. Can you please remove that and check if the snapshot works for you? If that doesn't I'd like to know why. Thanks.

**Comment by abelsromero** [comment]
I meant removing the @EnableAutoConfiguration. Apologies for the confusion.

**Comment by dromerop** [comment]
any news about this? tried with 1.5.1, 1.5.3 and 1.5.4 and validation still not works.

**Comment by wilkinsona** [comment]
@dromerop This issue is closed and we believe that the problem has been fixed. "still doesn't work" doesn't tell us very much. If you have a problem related to validation with 1.5.4, please open a new issue with a sample that reproduces the problem.
