### ISSUE TITLE
How to load property files from external directory?

### ISSUE THREAD

**Issue by GreatJohnny** [spring-projects/spring-boot#8499]
Hi,
      I have some config files ,sharing with other system. So, I want to synchronize these files by Git before the application startup each time. The application is been archived to Spring-boot JAR file. 

  First of all ,I made an experiment . I tried to load the logback config file:logback.xml from the external directory. According to the springboot doc :http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/loader/PropertiesLauncher.html . I add the _load.path_ param to the startup command.
_java -Dloader.home="./" -Dloader.path="sds_ser/" -Djava.security.egd=file:/dev/./urandom -jar service-0.0.1-SNAPSHOT.jar --spring.profiles.active=test_

   The _sds_ser_ is the directory of the logback.xml. Which along with the service-0.0.1-SNAPSHOT.jar.But startup failure,the logback.xml could not be found!

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
