### ISSUE TITLE
I would like to have all the internal Springboot log messages directed to log4j so that the messages follow my log4j properties,but it is invalid.

### ISSUE THREAD

**Issue by zshzj** [spring-projects/spring-boot#8541]
`<dependency>`
           ` <groupId>org.springframework.boot</groupId>`
        `<artifactId>spring-boot-starter</artifactId>`
       `<exclusions>`
          `  <exclusion>`
              `  <groupId>org.springframework.boot</groupId>`
               ` <artifactId>spring-boot-starter-logging</artifactId>`
            `</exclusion>`
        `</exclusions>`
   ` </dependency>`

    `<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-log4j</artifactId>
        <version>1.3.8.RELEASE</version>
    </dependency>`

> **_logging.config=file:/data/log/report-log4j.properties_**

> start up springboot,it outputs.

> log4j:WARN No appenders could be found for logger (org.springframework.web.context.support.StandardServletEnvironment). log4j:WARN Please initialize the log4j system properly

_**but,report-log4j.properties in classpath,it is success**_

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by zshzj** [comment]
@snicoll Thinks 
see [http://stackoverflow.com/questions/42668924/springboot-logging-config-invalid](url)

pls help me
