### ISSUE TITLE
Confusing error message when trying to render a template as a static web page

### ISSUE THREAD

**Issue by berlin-ab** [spring-projects/spring-boot#855]
Starter web applications should be able to return html files without any templating dependency.

![screen shot 2014-05-13 at 11 30 30 am](https://cloud.githubusercontent.com/assets/87432/2959521/bf4f619e-dab3-11e3-8b8e-16099ee6712a.png)
![screen shot 2014-05-13 at 11 30 36 am](https://cloud.githubusercontent.com/assets/87432/2959523/c128698e-dab3-11e3-896f-933c24a3dfee.png)
![screen shot 2014-05-13 at 11 30 45 am](https://cloud.githubusercontent.com/assets/87432/2959525/c2e49c52-dab3-11e3-8a9a-c6576daf2aa6.png)
![screen shot 2014-05-13 at 11 30 52 am](https://cloud.githubusercontent.com/assets/87432/2959526/c579e030-dab3-11e3-95e6-593dc2f0221b.png)

**Comment by jjwilliams** [comment]
So I hate to beat a dead horse here, but I am a Spring Boot new guy, coming from old Spring (its been 2+ years) and am running into this issue using Freemarker. Is there some configuration properties I need to set? Do I put the .html file in /templates or /static? From the error messages I receive it seems like /templates:

Circular view path [greeting]: would dispatch back to the current handler URL [/greeting] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)

**Comment by snicoll** [comment]
That does not seem to be the same issue to me. The exception message is pretty clear IMO: it tells you that because freemarker is active (sub-text: you added the dependency), then it expects some templates to be found in `src/main/resources/templates` (or wherever your resources directory of your project is). You html template must be put in `/templates` but given the exception message, that directory does not even exist.

Does that make sense?

**Comment by bclozel** [comment]
Fixed in 1.3.x, but this error is still logged - see #2001 for the remaining parts to be fixed.
