### ISSUE TITLE
Spring Batch using Boot with MongoDB throws Cannot determine embedded database driver class for database type NONE

### ISSUE THREAD

**Issue by roshantiwary** [spring-projects/spring-boot#8550]

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Spring Batch requires to store the job details in a database so we try to get one.
