### ISSUE TITLE
Support configuring multiple basic auth users

### ISSUE THREAD

**Issue by sslavic** [spring-projects/spring-boot#8556]
Currently (Spring Boot 1.5.2) one can configure single basic auth user with username and password via security.user.name and security.user.password configuration properties defined in any property source (e.g. from Vault).
To be able to expire a user and have it replaced by new one with zero downtime, please support configuring multiple users.

**Comment by wilkinsona** [comment]
If you want to configure multiple users you should do so programatically rather than via `application.properties`. You can provide an `AuthenticationManager` `@Bean` as [described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-change-the-authenticationmanager-and-add-user-accounts).
