### ISSUE TITLE
Make ReactiveWebServerFactory a functional interface

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8559]
We currently have this:

```java
WebServer getWebServer(HttpHandler httpHandler);
WebServer getWebServer(Map<String, HttpHandler> handlerMap);
```

It would be nice to unify to a single method.

**Comment by bclozel** [comment]
Those signatures exist because of [this part of the WebFlux infrastructure](https://github.com/spring-projects/spring-framework/blob/1b2dc36/spring-web/src/main/java/org/springframework/http/server/reactive/HttpHandlerAdapterSupport.java#L49-L69). You can compare it more or less to mapping Servlets on context paths.

We could use the Map variant in all cases, but it would either 1) wrap that single handler for no good reason in all cases or 2) require us to unpack the map, and extract a single handler mapped to `"/"` and use the first variant under the covers.

Note that unlike Servlet mappings, we only check if the request path starts with the context path value, so there is no such thing as patterns like `"/*"` or `"/foo/*.html"`.

Right now only the first is really used in our auto-configuration, but the second is supported by WebFlux so I don't see why we should totally ignore that support at the factory level. If anything, we can remove the second for now and wait for enhancement requests — I just thought it would be a better idea to leave it here to trigger that kind of discussion.

In your opinion, are there pieces of Boot infrastructure that we should register in separate handlers? To me, this mechanism could be used if we create `HttpHandler` adapters to 3rd party libraries (a bit like the h2 console?), without requiring a hard dependency on the annotation or functional programming model in webflux.

**Comment by philwebb** [comment]
I'm not sure on the best solution here, I was mainly interested in aligning `ServletWebServerFactory` and `ReactiveWebServerFactory` as much as possible. It looks like ultimately we can only have a single `HttpHandler` so I'm not sure how it's best for beans to register with the server.

In the servlet work we have the `ServletContextInitializer` where beans can register servlets, filters etc.

Since ultimately you can only register one `HttpHandler`, I think that should be our interface. I wonder if perhaps `CompositeHttpHandler` should be extracted in Spring to its own top level class? Perhaps the map variants could then be removed from `HttpHandlerAdapterSupport`.

Actually, you could even hide `CompositeHttpHandler` behind a static method on `HttpHandler`:

```java
Map<String, HttpHandler> handlers = buildHandlersMap();
HttpHandler handler = HttpHandler.of(handlers);
```

**Comment by rstoyanchev** [comment]
The request to support contextPaths came indirectly via Spring Cloud, see some [comments on the ticket](https://jira.spring.io/browse/SPR-14726). If you don't see a way to make use of this then perhaps we should discuss what this feature means to those who need it and what it looks like in Boot.

/cc @dsyer, @spencergibb

**Comment by rstoyanchev** [comment]
Just to elaborate for those who aren't familiar, currently in WebFlux it is possible to install two or more applications (e.g. each with its own set of DispatcherHandler, handler mappings, etc) at different contextPaths. This is in the same JVM, on the same runtime, similar to running multiple war applications on a Servlet container.

**Comment by philwebb** [comment]
Sorry @rstoyanchev, I don't think my original description was all that clear. I wasn't arguing that supporting `contextPaths` was a bad idea, but rather it might work better if it wasn't the responsibility of the adapter classes to support them.

If we simplify the adapter to only accept a single `HttpHandler`, then our `ReactiveWebServerFactory` becomes simpler. The adapter implementations in Spring Framework also become simpler.

The task of creating a composite `HttpHandler` could move to the interface itself. So you can write this:

```java
HttpHandler myHandler = ...
return new TomcatHttpHandlerAdapter(myHandler);
```

or this:
```java
Map<String, HttpHandler> handlers = new LinkedHashMap<>();
handlers.put("/foo", fooHandler);
handlers.put("/bar", barHandler);
return new TomcatHttpHandlerAdapter(HttpHandler.of(handlers));
```

I pushed a sketch of the idea [here](https://github.com/philwebb/spring-framework/commit/67c683158159349c7909ea7180c71c4d3ab7890b).

**Comment by philwebb** [comment]
Regardless of the suggested framework changes we'll go with a single `HttpHandler` method. If we need to compose multiple items we'll use `HttpHandlerAdapterSupport`

**Comment by rstoyanchev** [comment]
@philwebb, thanks for the suggestion. Looks like a fine refactoring to me removing the need for the base `HttpHandlerAdapterSupport` and the resulting noise in constructors of sub-classes. I will process the PR.

I'm still interested in discussing whether the support for contextPath's as implemented currently is something that Boot can take advantage of and whether it is what Spring Cloud is looking for?

**Comment by philwebb** [comment]
@rstoyanchev I don't yet have a good feel for that. After we've got the basics working we'll need to involve the wider team and see what's missing.
