### ISSUE TITLE
Extract common server features

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8573]
The reactive/servlet server implementations and factories are currently copy/paste. It might be possible to extract common elements.

**Comment by snicoll** [comment]
Not sure if that's the right place to report that but WebFlux doesn't log the server being used on startup and that confuses users.

**Comment by wilkinsona** [comment]
We have server-specific logic to document the port. I guess it must be missing for Netty.

**Comment by philwebb** [comment]
I've raised #8681 for the port issue.

**Comment by bclozel** [comment]
@philwebb I've partially addressed that in #11500.

A few things to consider here:

* I've created new packages in `spring-boot-autoconfigure/.../web/embedded/{undertow,jetty,tomcat}` to hold the common reactive+servlet configuration part  for each server, extracting what was previously inner static classes.
* I've added for each server an interface, like `spring-boot/.../web/embedded/undertow/ConfigurableUndertowWebServerFactory`. Those are not factories per se, but I couldn't find a way to properly insert them in the class hierarchy. I didn't find the need to abstract things more or create a parameterized interface for that, since we don't really want that code to be considered as extendable.

I guess once you've reviewed/polished #11500, this issue can be closed.
