### ISSUE TITLE
Trigger LiveReload when a static resource changes

### ISSUE THREAD

**Issue by jamesdanged** [spring-projects/spring-boot#8596]
Hi, I am trying to trigger an automatic LiveReload with the Spring Boot Devtools when one of my static resources changes, eg a *.js or *.css file under the /public directory. 

I can get LiveReload to work with java class changes when I recompile the whole project. And I can also set the property
   `spring.devtools.restart.additional-paths=./public`
to trigger a full server restart when one of those resources changes. But the restart is much slower than a reload.

Could this be exposed as an application property?

**Comment by philwebb** [comment]
The livereload server should get triggered when you change `/public` files. The relevant code is in `LocalDevToolsAutoConfiguration.java` in the `onClassPathChanged` method. You could try a breakpoint on that method to ensure that it's being fired.

If that doesn't help, can you please provide a sample application along with the steps that you expect should trigger a reload.

**Comment by jamesdanged** [comment]
Thanks for the response. That helped me isolate it. It will live reload correctly if my files are in 
    <project root>/target/classes/public 
but not if they are in 
    <project root>/public
even though both can be served by spring boot.

**Comment by wilkinsona** [comment]
In addition to setting the additional paths property, you should also set `spring.devtools.restart.exclude` to match the same path. As [explained in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart-additional-paths), this will cause the additional path to trigger a reload rather than a restart.

**Comment by jamesdanged** [comment]
The `event.isRestartRequired` check seems to distinguish between class files and resource files, so it seems I don't need to set the `spring.devtools.restart.exclude` property. I just checked that with debug breakpoints too. Thanks for your help.

**Comment by kgdngitfk** [comment]
hi,during develop,that static resources such as .html .css files have changes,it mush recompile so that the changes take effect . how to make static resources changes take effect without restart or recompile?
I have set the property spring.resources.static-locations=file:xxx/src/main/resources/static which is an absolute path in Windows, but no use,Thanks

**Comment by snicoll** [comment]
@kgdngitfk this issue is closed and we don't use the tracker for questions. Please ask on StackOverflow or Gitter. Reading [this section of the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-restart) should also help (you have to update the classpath).
