### ISSUE TITLE
Spring-boot 1.5.2 initializes messageDispatcherServlet automatically 

### ISSUE THREAD

**Issue by PradeepKanagaraj** [spring-projects/spring-boot#8597]
Hi 

I have upgraded my RestFul webservice with springboot 1.3.7 to springboot 1.5.2.

After the upgrade i am see MessageDispatcherServlet  is getting initialized and breaking the request. 
dispatcherServlet is the main servlet in my project and all the request are driven through it. 

Can you help me out why MessageDispatcherServlet  is getting initialized in spring boot 1.5.2 and mapping to my URL .

Can you help me out how to stop this mapping during MessageDispatcherServlet  initialization .

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
