### ISSUE TITLE
Remove duplicate uninstallUrlStreamHandlerFactory

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8622]
We have them peppered all over our tests, perhaps we can do it at the factory level.

**Comment by wilkinsona** [comment]
The changes made in https://github.com/spring-projects/spring-boot/commit/b71daac58a5cc6193b2a9f0ceb700490f248639f failed on Bamboo and Jenkins, but build fine locally. This is because triggering the underlying problem depends on the order in which the tests are run.

Both Tomcat and our `JasperInitializer` that's used in Jetty's JSP support call `URL.setURLStreamHandlerFactory`. If a factory has already been set an `Error` is thrown. Tomcat fails in such cases, whereas our `JasperInitializer` swallows the error and continues. This means that if Tomcat gets in first the tests will all pass. If Jetty gets in first, tests that use Tomcat will fail.
