### ISSUE TITLE
Auto-configure WebClient

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8630]
We need a `WebClient` story to replace `RestTemplate` in the reactive world.

**Comment by snicoll** [comment]
I gave some thoughts to that one. If we want to make things consistent, we probably need a `WebClientBuilder` that takes the converters and other things Spring Boot may auto-configure in the future. It is then a matter of updating `@AutoconfigureWebClient`

**Comment by bclozel** [comment]
`WebClientBuilder` is probably the best choice here.
Now about converters, we're in the process or reworking that bit in Framework, since we noticed that sharing an `ObjectMapper` instance between encoders/decoders can involve a lot of configuration. We should probably wait for [SPR-15247](https://jira.spring.io/browse/SPR-15247) to be fixed before we start writing code in the message encoders/decoders auto-configuration, for both client and server.

**Comment by joshiste** [comment]
Please also take the WebTestClient into account.

I expected, that the WebTestClient uses the autoconfigured `ObjectMapper` from the application context, but it doesn't.

Currently adding a new Jackson module to the WebTestClient is a bit tedious and renders the preconfigured WebTestClient useless.

my current solution:
```java
    @Autowired
    private ObjectMapper mapper;

  ...

        webClient = WebTestClient.bindToServer()
                                 .baseUrl("http://localhost:" + port)
                                 .exchangeStrategies(ExchangeStrategies.builder().defaultCodecs((configurer) -> {
                                     configurer.jackson2Decoder(new Jackson2JsonDecoder(mapper));
                                     configurer.jackson2Encoder(new Jackson2JsonEncoder(mapper));
                                 }).build())
                                 .build();
```

**Comment by bclozel** [comment]
Oops - I think this one is duplicates by #9577 and #9522 - those are already solved and documented.
