### ISSUE TITLE
Why context path is not getting added with failureUrl and defaultSuccessUrl in spring security?

### ISSUE THREAD

**Issue by jachuchl** [spring-projects/spring-boot#8633]
@Override
    protected void configure(HttpSecurity http) throws Exception {

        http
          .authorizeRequests()
            .antMatchers("/logout","/user-registration","/login","/login-error").permitAll()
            .anyRequest().authenticated()
            .and()
        .formLogin().loginPage("/login").failureUrl("/login-error")
            .defaultSuccessUrl("/home") 
            .and().logout().logoutSuccessUrl("/logout").and().csrf().disable();
    }

My context path is "http://localhost:8080/flasher" but it is redirecting to http://localhost:8080/login-error in case of authentication error not to "http://localhost:8080/flasher/login-error"

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
