### ISSUE TITLE
Log4j2 plugins lookup issue

### ISSUE THREAD

**Issue by mnovoseltsev** [spring-projects/spring-boot#8637]
Hi team, 
I have recently faced the following issue with log4j2 custom plugins using Spring Boot 1.5.1/1.5.2. 

**Circumstances to reproduce:** 

1. Any Log4j2 Plugin in jar dependency compiled with annotation processing disabled, so that Log4j2Plugins.dat file is not provided;
2. Jar file with plugin installed into local maven repo. jar file created with shade plugin or maven-jar plugin;
3. Spring Boot application packaged as a fat jar with mentioned above dependency;
4. Log4j2 starter used instead of default logback;
5. Log4j2 configuration file uses custom plugin from mentioned above jar dependency;
6. Log4j2 config file has valid package property provided according to https://logging.apache.org/log4j/2.x/manual/plugins.html documentation.

**Expected result**: Log4j2 plugin is loaded on time when starting application using
```java -jar <application.jar>```
**Actual result**: 'main ERROR Console contains an invalid element or attribute "SomeCustomPluginName"' error on startup.

**Notes**: 

- Everything works fine when running application from IDE or maven spring boot plugin.
- Everything works fine also when running as a war.
- Tested only with Tomcat embedded environment.

_Is it a bug or intended behaviour for Spring Boot custom classloader for embedded containers?_

Here is you can find sample app to reproduce given issue with steps to reproduce documented - `https://github.com/mnovoseltsev/log4j2-springboot-plugins-issue`

**Comment by wilkinsona** [comment]
Thanks for the sample and detailed instructions.

Unfortunately, I don't think there's anything we can do about this in Spring Boot. It doesn't work as Log4j2 is making some assumptions about the form that a jar URL will take that doesn't hold true when using a Spring Boot fat jar.

The URL for your package is found successfully by `ResolverUtil.findInPackage`:

```
jar:file:/Users/awilkinson/dev/temp/log4j2-springboot-plugins-issue/sample-app/target/sample-app-0.1-SNAPSHOT.jar!/BOOT-INF/lib/log4j2-plugin-holder-0.1-SNAPSHOT.jar!/log4j2/plugin
```

Things go wrong straight after that when the URL is manipulated. It becomes `/Users/awilkinson/dev/temp/log4j2-springboot-plugins-issue/sample-app/target/sample-app-0.1-SNAPSHOT.jar` so the resolver ends up looking in the outer jar rather than the inner jar.

I think this could be avoided if, instead of manipulating the URL, they opened a connection to the URL, cast it to a `JarURLConnection`, and then called `getJarFile()`. That will return the nested jar file that contains your custom plugin's classes. It would also avoid the need for any Spring Boot-specific logic.

If you'd like to pursue this, please open an issue against Log4j2. If you link to this issue here, I'll keep an eye on it and offer my help if it's needed.

**Comment by mnovoseltsev** [comment]
Thank you a lot for the good explanation and fast answer. Here is I created an improvement task for Log4j2 project - https://issues.apache.org/jira/browse/LOG4J2-1852. Unfortunately, they do not have issue management on github, so I am not able to link it properly.

**Comment by wilkinsona** [comment]
Thanks. I'm watching LOG4J2-1852.

**Comment by arakelian** [comment]
Thanks @mnovoseltsev for reporting this issue, and in particular, for the detailed comment that included the note about "Log4j2Plugins.dat".  

That was the key to crafting a workaround for me.

My Log4J2 plug was located in a Gradle project, and I changed the build.gradle as follows:
```
plugins {
	id 'java'
	...
	id 'org.inferred.processors' version '1.2.3'
}

dependencies {
	processor 'org.apache.logging.log4j:log4j-core:2.8.2'
}
```

The added the Log4J2 annotation processor to my build, and caused it to generate the aforementioned .dat file, which was then added to the META-INF classpath.

Log4J2 then no longer require packaged scanning to find my Plugin, and picked it right up.
