### ISSUE TITLE
Migrate JMustache reactive view support in Boot master

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#8648]
The Mixit application is currently using a reactive view infrastructure implementation for JMustache, [see those 3 classes](https://github.com/mix-it/mixit/tree/master/src/main/java/org/springframework/web/reactive/result/view/mustache) (how tiny!).

Given we've got the same support included in Boot for MVC and the many requests @sdeleuze is getting for that to be eternalized in some project, I'd be in favor of migrating those in Boot proper.

**Comment by philwebb** [comment]
+1

**Comment by sdeleuze** [comment]
Open questions to be discussed:
 - `BiConsumer<Map<String, Object>, ServerWebExchange> modelCustomizer` support
 - Provide by default super useful extensions like i18n, see https://github.com/mixitconf/mixit/blob/master/src/main/kotlin/mixit/web/ModelCustomizer.kt#L24-L27

**Comment by philwebb** [comment]
@sdeleuze Seem sensible, any reason we wouldn't want it?

**Comment by sdeleuze** [comment]
Well, I am strongly in favor of integrating a way to add custom`Mustache.Lambda` and provide by default the i18n one.

But I would like to see if `HandlerFilterFunction` could be used as a functional equivalent to `@ControllerAdvice` for integrating custom `Mustache.Lambda like shown on https://spring.io/blog/2016/11/21/the-joy-of-mustache-server-side-templates-for-the-jvm in order to see if `modelCustomizer` is required or not.

I will check that with @poutsma and send you a feedback.

**Comment by sdeleuze** [comment]
Ok so after some experiments and work with @poutsma I confirm that we don't need this `modelCustomizer`. In latest Spring Framework 5 snapshots, `HandlerFilterFunction` now can be used to customize globally the model attributes.

As a consequence, I have removed it from https://github.com/mixitconf/mixit/tree/master/src/main/java/org/springframework/web/reactive/result/view/mustache and you don't need it in Spring Boot as well.

I still think providing by default an `i18n` `Mustache.Lambda` is a good idea, so my proposal would be to add it by default (maybe in Spring MVC alternative as well).
