### ISSUE TITLE
How are the custom class loaded in spring boot stream. 

### ISSUE THREAD

**Issue by vishukadam** [spring-projects/spring-boot#8664]
How are the custom class loaded in spring boot stream. I trying to create Spring boot Task which launches spring batch(custom batch using xml configuration). 
But it dose not load "org.springframework.validation.beanvalidation.LocalValidatorFactoryBean" which is one of the dependency in in custom spring batch and is in the class path of custom jar.

Please share life cycle of spring bean creation in spring boot

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
