### ISSUE TITLE
Spring Batch Task Event Listener

### ISSUE THREAD

**Issue by vishukadam** [spring-projects/spring-boot#8665]
Hi, 
I am trying to create Spring Boot Task(version 1.5.2) which invokes conventional spring batch.
i.e. I had already written spring batch application using Spring Batch(xml based). Now i am trying to invoke this spring batch from Spring Task. I had written listeners for reader, processor and writer. How can do the same in spring boot task. I am aware that I need to write (stream)sink and  @EnableTaskLauncher. How I configure the listeners for the read, processor, writer and error. I am using Kafka.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
