### ISSUE TITLE
Not able to find Application name when executing as Service.

### ISSUE THREAD

**Issue by tpulimoottil** [spring-projects/spring-boot#8668]
I have created a Spring boot application and executing the same as a an init.d service.

Tutorial Followed : https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-initd-service

I have multiple symlink created in the same machine and provided different application names like worker-node1, worker-node2, worker-node3, worker-node4 etc so that i can run multiple instances of the same application in the same machine as independent processes. 

I tried to access the application name by getting _spring.application.name_, but it doesn't seem to be working. How do i get the application name of an executable service from code?

Any help on this regard would be helpful.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by tpulimoottil** [comment]
Hi,
Thank-you for the reply. I have posted the question in stack overflow.

http://stackoverflow.com/questions/42848929/spring-boot-how-to-get-application-name-in-spring-boot-executable
