### ISSUE TITLE
@JsonTest - Add support for specifying @JsonView to JacksonTester.write(...)

### ISSUE THREAD

**Issue by ilya40umov** [spring-projects/spring-boot#8672]
I'm writing a JsonTest for my DTO object. The DTO has a couple JsonViews declared on it. Naturally, I would like to be able to test json serialization for each view in my JsonTest. Current API does not allow specifying a particular view for JacksonTester.write(...) 

For now, I ended up with a following hack to be able to set view on per test method basis:
```
public void useView(Class<?> view) {
        ObjectMapper objectMapper = (ObjectMapper) Whitebox.getInternalState(jacksonTester,
                "objectMapper");
        objectMapper = objectMapper.setConfig(objectMapper.getSerializationConfig().withView(view));
        Whitebox.setInternalState(jacksonTester, "objectMapper", objectMapper);
}
```

I would prefer to avoid creating a different test class for each DTO&View combination(so that I could configure the mapper in test setUp).

I'm also aware that I could test the behavior of my JsonViews in MVC tests, but since there is a type of test specifically dedicated to serialization to/deserialization from JSON, it makes more sense to test JsonViews in it.

**Comment by philwebb** [comment]
Nice idea. I wonder if it might be better to offer a callback interface that would any `ObjectMapper` settings to be customized. I'm thinking something like:

`json.write(item, (o) -> o.withView(Foo.class))`

Actually, rather than updating all the `write`/`read` methods we could perhaps make that a higher level concern:

`json.customize((o) -> o.withView(Foo.class)).write(item)`

The `customize` method would return a new `JacksonTester` instance. This would prevent the potential explosion in new method signatures.

**Comment by philwebb** [comment]
We should really do this in 2.0.0, but since it's such a nice addition I'm tempted to try in 1.5.x.
