### ISSUE TITLE
Hibernate validator dependecies

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-boot#8677]
Spring boot web version 1.5.2.RELEASE contain hibernate validator dependency, but I had that dependency in .gradle, so when I upgrade spring version to 1.5.2 and run project, validation not worked, and there wasn't any warnings. Please add warnings if there a 2 validation dependencies.

**Comment by wilkinsona** [comment]
I don't see why two Hibernate Validator dependencies would cause a problem, particularly as Spring Boot's dependency management should ensure that you're using a compatible version. How did you identify that it wasn't working? Can you provide a small sample that shows the problem?

> Please add warnings if there a 2 validation dependencies

There isn't really anything wrong with having two dependencies on Hibernate Validator so I don't think it's appropriate to issue a warning (and, if it were appropriate, it would be something that I'd expect Maven or Gradle to do rather than Spring Boot).

**Comment by raderio** [comment]
> How did you identify that it wasn't working?
I've deleted line with dependency for hibernate validator, after this validation is working

**Comment by raderio** [comment]
It was
```
compile group: "org.springframework.boot", name: "spring-boot-starter", version: "1.5.2.RELEASE"
compile group: "org.springframework.boot", name: "spring-boot-starter-web", version: "1.5.2.RELEASE"
compile group: "org.hibernate", name: "hibernate-validator", version: "5.2.4.Final"
```

**Comment by wilkinsona** [comment]
Spring Boot 1.5 uses Hibernate Validator 5.3. You've downgraded the version of Hibernate Validator to 5.2 which may well be why it didn't work (I can't tell for certain as you haven't provided anything that reproduces the problem). We recommend that you don't specify a version on a dependency for which Spring Boot provides dependency management. That includes all three of the dependencies that you've listed above.
