### ISSUE TITLE
About TomcatEmbeddedServletContainerFactory(Jetty...) SSL keystore and truststore config 

### ISSUE THREAD

**Issue by ivorzhou** [spring-projects/spring-boot#8692]
Question

I want my spring boot webapp use http protocol, but I need trust some CA Cert, so I add CA Cert to truststore file, and add config in application.properties as below,It does not work.

#server.port=8080
#server.ssl.key-store=file:/etc/cas/thekeystore
#server.ssl.key-store-password=changeit
#server.ssl.key-password=changeit

server.ssl.trust-store=classpath:truststore.jks
server.ssl.trust-store-password=changeit

I think key-store feature is not always with trust-store feature

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by ivorzhou** [comment]
Ok,I have fork the cloudfoundry-certificate-truster project and add the feature for app level trust store config
https://github.com/ivorzhou/cloudfoundry-certificate-truster
