### ISSUE TITLE
Designing Data Access Layer and Service Layer with Spring Boot

### ISSUE THREAD

**Issue by alvamen** [spring-projects/spring-boot#8695]
I'm trying to implement the layers of a web application, so I wanted to ask you if you can suggest me a tutorial or any advice about how to design and build the Data Access Layer and the Service Layer

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
