### ISSUE TITLE
OracleDataSource.dataSourceName: set it to DataSourceProperties' name property

### ISSUE THREAD

**Issue by robin-a-meade** [spring-projects/spring-boot#8700]
`oracle.jdbc.pool.OracleDataSource` and `oracle.ucp.jdbc.PoolDataSourceImpl`  both have a 'dataSourceName` property.

It would be nice if this property was set by the `DataSourceProperties` `name` property. Similar to how you set the `user` property using the `username` property in #6027.

I configure my Oracle DataSource using this approach:

```java
@Configuration
public class FooDataSourceConfig {

  @Bean
  @Primary
  @ConfigurationProperties("app.datasource.foo")
  public DataSourceProperties fooDataSourceProperties() {
     return new DataSourceProperties();
  }

  @Bean
  @Primary
  @ConfigurationProperties("app.datasource.foo")
  public DataSource fooDataSource() {
     return fooDataSourceProperties().initializeDataSourceBuilder().build();
  }
}
```

with these application.properties:

```java
app.datasource.foo.type=oracle.ucp.jdbc.PoolDataSourceImpl
app.datasource.foo.username=<username>
app.datasource.foo.password=<password>
app.datasource.foo.url=jdbc:oracle:thin:@//localhost:1521/servicename
app.datasource.foo.name=Foo
# Oracle UCP Specific Properties
app.datasource.foo.connectionFactoryClassName=oracle.jdbc.pool.OracleDataSource
app.datasource.foo.maxPoolSize=20
app.datasource.foo.minPoolSize=5
app.datasource.foo.maxIdleTime=5
app.datasource.foo.validateConnectionOnBorrow=true
app.datasource.foo.maxStatements=10
app.datasource.foo.fastConnectionFailoverEnabled=true
```
I expected the resulting DataSource `@Bean` to have its `dataSourceName` property set to "Foo".

**Comment by snicoll** [comment]
That would mean we would have an explicit support of the oracle data source that we don't support at the moment. I am not keen to do this (the reason we're using the trick you referenced is because we do support Hikari). 

I'll flag this one for attention to see what others think.

**Comment by philwebb** [comment]
Adding an additional `aliasFor` doesn't seem too bad to me. I don't want to deal with the Oracle Maven repository dance but if we can add support without needing the Oracle jars then I'm not against adding this.

**Comment by snicoll** [comment]
> Adding an additional aliasFor doesn't seem too bad to me

That's not going to fix anything, we don't have a "name" property in that class so we would need to introduce it and providing a `name` property doesn't have much sense at that level I am afraid. If we provide a property for name, why not for a gazillion of other things?

**Comment by snicoll** [comment]
Considering the state of affairs, this request is not related to #6027 even though it may look like it on surface. The `name` property is only use for the embedded builder and can't be used where the aliases are being applied without adding a property that wouldn't be used otherwise.

Also, the link you make between `name` and `dataSourceName` is not straightforward, especially given how the property is being used at the moment. We do not support the oracle data source but you are free to expose it in your own config using the builder. 

This [section of the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-a-datasource) has all that you need. The specific bits you would have to write would be something along the lines of:

```java
@Bean
@ConfigurationProperties("app.datasource")
public OracleDataSource dataSource(DataSourceProperties properties) {
    OracleDataSource ds =  (OracleDataSource) properties
             .initializeDataSourceBuilder().type(OracleDataSource.class).build();
     ds.setDataSourceName(properties.getName());
     return ds;
}
```
