### ISSUE TITLE
Fat jar works for embedded Jetty and Tomcat but not for Undertow

### ISSUE THREAD

**Issue by bjorntj** [spring-projects/spring-boot#8764]
I am trying to create a executable fat jar instead of war files for my Spring Boot projects , where I use JSF and Primefaces.
My test project works fine using either Jetty or Tomcat but Undertow complains about not finding the resources for the Primefaces theme I use..

I have included a test project... 
[undertow_test.tar.zip](https://github.com/spring-projects/spring-boot/files/875770/undertow_test.tar.zip)

**Comment by bjorntj** [comment]
btw, this test project works when running as java -jar jarfile but not when I run it as gradle bootRun, any pointers what I need to do to make it work using gradle bootRun?

**Comment by wilkinsona** [comment]
Thanks for the sample, but it's left me a bit confused. It appears to be using Jetty but you said the problem was with Undertow. I get a failure with `bootRun` when I try to access `http://localhost:8080`. The index appears to work fine with `java -jar`. If I switch to Undertow I see the same failure as Jetty with `bootRun` and it doesn't work with `java -jar` either with a different failure to the one seen with `bootRun`.

Can you please clarify the problem that you're reporting? I don't want to waste time diagnosing something else.

**Comment by bjorntj** [comment]
Yes, forgot to change the dependency back to undertow, so yes, my problem is when using undertow and using java -jar. bootRun does not work on either and as I mention in my comment above, I am not sure how to make this project wok using bootRun, but perhaps you have some ideas?
And yes, the error is different when using bootRun. When using bootRun, is seems that it does not find the static resources in the web_resources jar file at all.

**Comment by wilkinsona** [comment]
There are two things going on here. Firstly, your resources are in the wrong place. They're in `src/main/resources/META-INF/resources/resources` but they should be in `src/main/resources/META-INF/resources`. Secondly, things don't work with `bootRun` due to #8525 which is fixed in 1.4.6 and 1.5.3 snapshots.

If I move your resources to the right location and use 1.5.3.BUILD-SNAPSHOT things work fine with Undertow using both `bootRun` and `java -jar`.

**Comment by bjorntj** [comment]
ok, the placement is just copied from the example project from Primefaces using their theme but I guess I do not need to follow this... 
Thx... :)
