### ISSUE TITLE
How to use application.yml !

### ISSUE THREAD

**Issue by dingwenxiang0** [spring-projects/spring-boot#8777]
I am learning spring boot. 
I following spring-boot-sample-activemq.
When i use application.properties configs. The application run success and well.
but when i switch to application.yml. then i cant start my application.
**All code like spring-boot-sample-activemq. just change properties to yml.**

the error tell me:

```
Field jmsMessagingTemplate in sample.activemq.provider.Provider required a bean of type 'org.springframework.jms.core.JmsMessagingTemplate' that could not be found.
	- Bean method 'jmsMessagingTemplate' not loaded because Ancestor org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration did not match


Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.jms.core.JmsMessagingTemplate' in your configuration.
```

I tried to read the yml property. that is success.
and i check the error. i found maybe yml dont support Autowried.

next it is my yml config(**application.yml in src/main/resources/config** ):
`spring:
  activemq:
    in-memory: true
    broker-url: tcp://192.168.2.174:61616
    pool:
      enabled: true
my:
  queue: FirstQueue`

OK. done. plz help me . thank you and good day

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by dingwenxiang0** [comment]
.... you are so fast!
