### ISSUE TITLE
Support jOOQ's SQLDialect enum names for the spring.jooq.sql-dialect property

### ISSUE THREAD

**Issue by lukaseder** [spring-projects/spring-boot#8794]
As can be seen in [this Stack Overflow question](http://stackoverflow.com/a/43167379/521799), users are expected to use what appears to be a PascalCase version of the jOOQ `SQLDialect` enum name, rather than the actual enum name itself:

These seem to work:

```
spring.jooq.sql-dialect = Postgres
spring.jooq.sql-dialect = Oracle
```

This one doesn't:

```
spring.jooq.sql-dialect = ORACLE
```

That might be a bit surprising to some users. Would it make sense to support the enum names in their proper case as well?

**Comment by wilkinsona** [comment]
As you mentioned in the comments, the question on SO suggests that `jooq.sql-dialect` doesn't work which is to be expected as it should be `spring.jooq.sql-dialect`. The enum should work fine in its proper case and I'd expect a failure for a value can't be mapped to the enum rather than it being silently ignored. Have you observed behaviour that's at odds with that?

**Comment by lukaseder** [comment]
Thanks for the quick reply. I'm sorry, I might have jumped a bit too quickly. Perhaps, the issue was really just a user error.

I'll close this and will come back in case there is more info on that question.
