### ISSUE TITLE
if use @WebFilter, how i define filter's order

### ISSUE THREAD

**Issue by justkuai** [spring-projects/spring-boot#8811]
i'm try to use @order, but it not work

```
@WebFilter(urlPatterns = "/*", filterName = "CommonFilter")
@Order(1)
public class CommonFilter implements Filter {//..}



@WebFilter(urlPatterns = "/*", filterName = "AuthFilter")
@Order(2)
public class AuthFilter implements Filter{//..}
```

however order is any number, but AuthFilter is first  forever...........

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
