### ISSUE TITLE
Issues using hateos with defferedresult

### ISSUE THREAD

**Issue by umangsingh123** [spring-projects/spring-boot#8815]
This is related to spring hateos.
I have a rest webservice which returns a deferred result object .Now as part of maturity we need to enable this service with hypermedia.
Now when I try creating/ adding links to the resource . It gives a illegal state exception.
I started researching on this issue and understand that hateos doesn't support defferedresult .Is this true and if yes what is the way around

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
