### ISSUE TITLE
Provide opinionated Spring Boot Gradle Plugin

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#8821]
It would be nice if Spring Boot could bring to the build what it has to applications. An opinionated view which allows getting started with minimum fuss. This could be solved by providing an opinionated Gradle plugin and a base plugin that requires additional configuration. 

This would also better align with Boot's goals which [states](http://docs.spring.io/spring-boot/docs/1.5.x/reference/htmlsingle/#getting-started-introducing-spring-boot)

> We take an opinionated view of the Spring platform and third-party libraries so you can get started with minimum fuss. 

This also aligns with Gradle's conventions of using [base plugins](https://docs.gradle.org/current/userguide/standard_plugins.html#sec:base_plugins).

So something like this provides lots of options:

```
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot-base'
apply plugin: 'io.spring.dependency-management'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }
}


dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

And this provides something more concise:

```
apply plugin: 'org.springframework.boot'

version = '0.0.1-SNAPSHOT'

dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

I think this could even be taken further by adding support for things like `integrationTest` task which would allow separating the integration tests from the unit tests.

**Comment by wilkinsona** [comment]
Gradle doesn't really promote the split between a plugin and a base plugin. Its own documentation says that they're only "listed here for completeness" and "that they are not yet considered part of Gradle's public API". It doesn't feel like a concept that's ready for us to build upon.

When the Boot team discussed the new need to apply the dependency management plugin explicitly, we did discuss the possibility of offering two plugins, but we rejected it due to the added complexity that it would introduce. We foresaw two main problems:

1. Having two Spring Boot plugins raises confusion about which one you might be using and complicates support as we'd have to start asking people
2. With two plugins the option becomes rather all or nothing. Inevitably, people will want some of what a more opinionated plugin does but not all of it. They're either left unsatisfied by the approach or we have lots of plugins offering different combinations which would exacerbate the first problem

A key part of Spring Boot's approach that wasn't quoted above is to "be opinionated out of the box, but get out of the way quickly as requirements start to diverge from the defaults". Auto-configuration does a great job of this as you can move individual parts of it out of the way by providing your own beans. Offering two separate Gradle plugins wouldn't offer that level of control and would be more akin to only offering all of Boot's auto-configuration or none of it.

Rather than providing a second plugin that's more opinionated, I'd prefer to build upon the current approach of providing conventions. For example, we currently set the encoding of all Java compilation tasks to UTF-8 but only if no encoding has been configured. We could do something similar for source compatibility, for example.

**Comment by philwebb** [comment]
I'm not too keen to put too go too far down the opinionated route for Gradle. We've been burnt in 1.x by trying to do too much and I don't think we should rush in add more features in 2.x.

I think Andy's point about "all or nothing" and not having a sensible back-off strategy is particularly relevant.

With our current 2.x solution it's pretty easy to see what's happening and it's pretty easy to work out what you'd need to do if you didn't want a specific feature. Adding a "full" and "lite" version of the plugin makes things quite hard to document and explain.

I'd like to close this one for now and see how things pan out in 2.0. Let's open new issues for any new conventions that we should support (for example the source compatibility suggestion) and take them on one at a time.

After 2.0 is out we should review how easy people are finding the plugin to use. It's going to be easier to add this kind of support later than it is to take it out if we think it's wrong.
