### ISSUE TITLE
@SpringBootApplication not available in version 1.5.2

### ISSUE THREAD

**Issue by minhnguyen84** [spring-projects/spring-boot#8861]
@SpringBootApplication is not available in version 1.5.2.

How can we replace it?

Thank you

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

With that said, it sounds like Maven or Gradle has corrupted a jar while it was being downloaded. Clearing the cache should help.
