### ISSUE TITLE
the project "spring-boot-sample-web-jsp" can't run?

### ISSUE THREAD

**Issue by Subfire** [spring-projects/spring-boot#8862]
in my computer:
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [sample.jsp.SampleWebJspApplication]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class org.springframework.boot.web.support.SpringBootServletInitializer,

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Subfire** [comment]
ok, got it. i'm so sorry, all is from my newbie. i found the problem is result for this dependency:
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-tomcat</artifactId>
	<scope>provided</scope>
</dependency>

if run the application through the main, will have this problem, but if use "mvn spring-boot:run", everything is ok. what's difference between use main or mvn command? this may need more knowledge about Mave or Spring/Spring Boot, keep learning...
