### ISSUE TITLE
MethodValidationPostProcessor does not respect spring.aop.proxy-target-class

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8869]
Similar to #8434 the `PersistenceExceptionTranslationPostProcessor` currently always sets `proxyTargetClass` to `true`.

**Comment by snicoll** [comment]
Good catch!

**Comment by hbrands** [comment]
The associated commit addresses MethodValidationPostProcessor, but not PersistenceExceptionTranslationPostProcessor, so the issue in question isn't solved.

**Comment by snicoll** [comment]
Rename to `MethodValidationPostProcessor` so that the commit links to the proper issue. I've created #8887 for the original request

**Comment by cosmotron** [comment]
I'm not sure this is the correct process, but I've got a question about the fix for this in commit a00b695. I'm wondering if there is an expected place in an auto configured context where an `Environment` bean would be created such that that `MethodValidationPostProcessor` can be created without exception.

**Comment by philwebb** [comment]
@cosmotron I'm not sure I understand the question. The `Environment` isn't a bean. It's created early [by `SpringApplication`](https://github.com/spring-projects/spring-boot/blob/4bf1640198b439aa7e1e36ef9688ba12da08fe1c/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L348) before the context is even loaded.
