### ISSUE TITLE
Duplicate properties in the meta-data with lombok

### ISSUE THREAD

**Issue by zhanhb** [spring-projects/spring-boot#8886]
Get more than one statement in META-INF/spring-configuration-metadata.json when Annotate ConfigurationProperties class with lombok.Getter lombok.Setter

Here is a test project
https://github.com/zhanhb/configuration-processor-lombok-test

**Comment by AlexFalappa** [comment]
I created another testcase showcasing the issue at https://github.com/AlexFalappa/spring-boot-testcase2

@zhanhb, from my experiments a workaround is to make sure the `lombok` dependency in the `pom.xml` comes after the `spring-boot-configuration-processor` one.

**Comment by bluebilt** [comment]
@AlexFalappa The suggested workaround does not seem to work in our project

**Comment by AlexFalappa** [comment]
@bluebilt then something more involved is going on in the `spring-configuration-processor`...

**Comment by snicoll** [comment]
Looks like Lombok is quite painful in this scenario, see [this stackoverflow thread](http://stackoverflow.com/questions/29193806/specifying-order-of-annotation-processors)

What happens here is that lombok has already ran and has generated the thing that we are auto-detecting ourselves. So we first create a property because the getter/setter is there and then we check if lombok types are set somewhere (they are). And we generate the property again.

It would be so much easier if we could guarantee that lombok has to run first. That way, all the lombok specific code in our codebase could go away. Unfortunately, that does not seem to be possible.

**Comment by snicoll** [comment]
@bluebilt please report this issue in [the STS tracker](https://github.com/spring-projects/spring-ide/issues). Adding the logs and what you are doing should help.

**Comment by AlexFalappa** [comment]
@snicoll you may want to have a look at [this MapStruct issue](https://github.com/mapstruct/mapstruct/issues/510) where they faced and solved a similar issue.

At [this comment](https://github.com/mapstruct/mapstruct/issues/510#issuecomment-272423337) one of the lombok developer seem to explain why the annotation processors dependency order in the pom.xml apparently avoids the problem.

After that MapStruct's @gunnarmorling references a SPI made in collaboration with lombok devels to solve the issue.

Hope it helps

**Comment by snicoll** [comment]
@AlexFalappa thanks. I have a fix, about to push.
