### ISSUE TITLE
Passing 3 path variables to the request mapping method ?

### ISSUE THREAD

**Issue by areddy7021** [spring-projects/spring-boot#8922]
How to pass 3 path variables to the controller request mapping method in spring boot ?

I came across this https://jira.spring.io/browse/SPR-6741 but not sure whats the fix in spring boot ?

I have tried passing 2 path variables , it is working fine and the application just got migrated from spring mvc to spring boot and we started facing this issue with the 3 path variables on the get operation.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
