### ISSUE TITLE
how to define java version 1.8 when using spring boot without the parent pom

### ISSUE THREAD

**Issue by Shirman** [spring-projects/spring-boot#8937]
Hello kind man,I'm confused about how to define java version to 1.8. 
Accroding to reference,i can use spring boot without the parent pom but the property java.version don't work.So how to do can solve my problem.Thank you very much.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
