### ISSUE TITLE
Dependency for Servlet 3.1 APIs comes from tomcat-embed-core-8.5.6.jar, not the clean APIs jar.

### ISSUE THREAD

**Issue by ludoch** [spring-projects/spring-boot#8943]
It seems that the Servlet APIs dependency is coming from transitive dependency from:

>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
>
which is adding a dep on tomcat-embed-core.jar. This jar contains the APIs, but also tomcat APIs which conflict with some App Engine specific needs for tomcat.utils.* classes.

For App Engine applications using Spring Boot, one must exclude the tomcat-embed-core artifact:
>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.tomcat.embed</groupId>
          <artifactId>tomcat-embed-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
>
and add the official Servlet 3.1 APIs which do not pollute the application classpath with undesired classes:
>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <type>jar</type>
    </dependency>
>

**Comment by snicoll** [comment]
Sorry I am not following. App engine apps are war right? In that case you should exclude the whole `spring-boot-starter-tomcat` altogether anyway (see [the doc](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-maven-packaging)

Also, still on the idea you are building a war, the servlet api is already provided by the container so you shouldn't have to bundle it at all.

**Comment by ludoch** [comment]
You are correct for excluding spring-boot-starter-tomcat (and yes, 3.1 api are provided also with GAE).
Now, it cloud be easier to make the stater-web providing the apis, even if we exclude the stater-tomcat as these APIs should be shared/used with all the use cases: tomcat, Jetty, or random target like GAE.

**Comment by philwebb** [comment]
We've tried to enhance the web experience for embedded deployment targets because we feel like these are most common and it's the method that we most want to promote. The problem with making it easier to use provided APIs is it either makes the embedded route more difficult, or we need to present a choice to the user.

Since we're trying to be opinionated out of the box, I quite like our current setup. There's a little work involved in configuring provided dependencies, but it's not too hard and our defaults work well for most users.
