### ISSUE TITLE
JsonAutoDetect cannot be resolved to a type when upgrading to Spring Boot 1.5.x

### ISSUE THREAD

**Issue by Rankel** [spring-projects/spring-boot#8969]
Hello,

I re-open the issue [8963](https://github.com/spring-projects/spring-boot/issues/8963), i tried suggestions and it doesn't seem to works for me, [Here is the sample application](https://github.com/Rankel/testapp).

Thank you

**Comment by wilkinsona** [comment]
Thanks for the sample. It builds fine for me, even after clearing Jackson from my local Maven cache. Whatever your problem is, it isn't being caused by Spring Boot so, sorry, but there's nothing we can do here.

As a final suggestion, I'd double-check that the copy of `jackson-annotations-2.8.0.jar` in your local Maven cache isn't corrupted.

**Comment by Rankel** [comment]
Deleting cache from the folder fixed my issue! Thank you!
