### ISSUE TITLE
User-defined Validator bean should not be used as the `mvcValidator`

### ISSUE THREAD

**Issue by jonhkr** [spring-projects/spring-boot#8979]
Hi,

`@Valid` Annotations in controller are not working since I upgraded to `1.5.3`.

I use them like this:
```Java
public String method(@Valid @RequestBody Pojo pojo);

@Data
class Pojo {
    @NotBlank
    public String name;
}
```

**Comment by snicoll** [comment]
@jonhkr we've indeed changed something tricky in that area. Can you please share a sample?

**Comment by philwebb** [comment]
See also #8976

**Comment by jonhkr** [comment]
I was struggling to find the error since in my sample application I didn't have any custom validator implemented and marked as `@Component`.

This issue is a duplicate of #8976  (Thanks @philwebb for pointing that out).

**Comment by snicoll** [comment]
Can you share the app @jonhkr please?

**Comment by jonhkr** [comment]
Sure, https://github.com/jonhkr/spring-validation-sample

**Comment by snicoll** [comment]
Thanks. For the record `http post :8080/test Accept:application/json Foo=bar` breaks with `1.5.2.RELEASE` and silently (and wrongly) works with `1.5.3.RELEASE`

**Comment by rajadilipkolli** [comment]
https://github.com/rajadilipkolli/jcart/blob/master/jcart-admin/src/main/java/com/sivalabs/jcart/admin/config/WebConfig.java#L49_L55 this piece of code is causing me validation error after upgrading to 1.5.3
Can you help me how to solve this

**Comment by jonhkr** [comment]
@rajadilipkolli The issue is that if you have an implementation of the `Validator` interface in the context, the default validator won't be registered.
I see you have some validator implementations such as https://github.com/rajadilipkolli/jcart/blob/master/jcart-admin/src/main/java/com/sivalabs/jcart/admin/web/validators/RoleValidator.java.

That probably is what is causing the issue for you. In my case I had just one validator annotated with `@Component`, so it was easy for me to work around the issue by just removing the validator.

You can try registering the bean manually by adding this to your configuration:

```Java
@Bean
public Validator jsrValidator() {
        LocalValidatorFactoryBean factory = new LocalValidatorFactoryBean();
        factory.setValidationMessageSource(messageSource);
        return factory;
}

```

**Comment by dozherel-ucop** [comment]
Same problem here...  1.5.3 isn't working for me due to "validator" error.  Please fix it. it's minor build shouldn't be any  refactoring needed. Thanks.

**Comment by snicoll** [comment]
@dozherel-ucop agreed. Could you please provide a bit more detail than "validation error". I want to make sure your use case is covered as well. A sample would be ideal (if it's not the same as the one posted earlier https://github.com/spring-projects/spring-boot/issues/8979#issuecomment-296702045)

**Comment by snicoll** [comment]
@rajadilipkolli I am not sure I got that but the idiomatic way to do that with Spring Boot is to register a bean in the context for this. Just move that bean definition in a regular `@Bean` and let me know if that fixed your issue.

**Comment by snicoll** [comment]
@jonhkr your sample is a bit weird on a second look. You are providing a `Validator` but that validator does not support any class. And does not throw any exception. The real problem here is that it is now being used as the MVC validator and I guess that's not what you want. You probably have defined a validator for a very specific need and you do not expect it to be used at the web layer.

@philwebb an unwanted side effect of 1.5.3 is that it picks a Spring's `Validator` in the context and use it as the MVC validator but that's probably not what the user wants. And it's a too wide side effect to add in an maintenance release IMO.

**Comment by rajadilipkolli** [comment]
@snicoll  , after removing override and replacing with `@Bean` now I get  below error 
`Caused by: java.lang.IllegalStateException: Found unexpected validator configuration. A Spring Boot MVC validator should be registered as bean named 'mvcValidator' and not returned from WebMvcConfigurer.getValidator()`

**Comment by snicoll** [comment]
You didn't remove the override if you get that message. Please create another issue as you're problem is not the one described in this issue. When you do share a sample please.

**Comment by jonhkr** [comment]
@snicoll Yes, the validator on the sample is empty. It is just to show that if you have a custom validator registered as a bean the MVC validator is not registered.
That was the problem in my application, I had a custom validator annotated as `@Component` and since 1.5.3 the MVC validator was not being registered.

**Comment by snicoll** [comment]
Okay thanks but I that sample does not illustrate the problem then. What is the "mvc validator" for you. The one that's created by default? Can you please clarify your description?

**Comment by rajadilipkolli** [comment]
@snicoll  when I have removed override and added `@Bean` it didn't worked but when I changed the name of method to any other name or explicitly mentioned bean name it started working.

**Comment by snicoll** [comment]
@rajadilipkolli please stop commenting on this unrelated issue and create a separate one.

**Comment by jonhkr** [comment]
Yes it does, it shows that if you have a custom validator registered as a bean (the `TestValidator` in the sample) the default "mvc validator" (the `LocalValidatorFactoryBean`) is not registered.

For example, if the sample was a real application the `TestValidator` would have some logic in it, and it would require that both `TestValidator` and `LocalValidatorFactoryBean` be registered in the context as beans.

**Comment by snicoll** [comment]
> Yes it does

It doesn't show the actual effect (you could have customize the mvc validator with something that's no longer applied. I can't guess unless you explain what you mean). 

> it would require that both TestValidator and LocalValidatorFactoryBean be registered in the context as beans.

Sorry you lost me. Rather than me trying to fix what I think is the problem, can you join the #spring-boot Gitter room and we can chat about the problem.

**Comment by snicoll** [comment]
The problem is a cascading effect trying to accommodate with others requirements.  In the MVC layer we attempt to alias "any" `Validator` to `mvcValidator`. The main goal is to alias the one that was configured via auto-configuration` but the side effect is that any Validator bean defined by the user will be aliased as well. 

I think we shouldn't alias anything unless we are sure it is the bean we've created via auto-configuration. This would require some extra magic that might bring extra regressions.

`WebMvcAutoConfigurationTests#validatorWhenUserDefinedSpringOnlyShouldUseDefined` exercices the issue we're describing here. IMO we shouldn't replace the mvc default validation just because someone has created a Validator bean in their context: anyone upgrading to 1.5.3 with such setup will see MVC validation go away in favour of that single validator bean. It would be less surprising if such bean was named `mvcValidator` IMO

**Comment by dozherel-ucop** [comment]
I'm not looking into detail on this one. I just rolled back to 1.5.2
The error I'm getting is:

Caused by: java.lang.IllegalStateException: Found unexpected validator configuration. A Spring Boot MVC validator should be registered as bean named 'mvcValidator' and not returned from WebMvcConfigurer.getValidator()
	at org.springframework.util.Assert.state(Assert.java:70) ~[spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]

And we do have code like jonhkr posted in his example.

Thanks,
Danil

**Comment by dozherel-ucop** [comment]
In my case we do not have any 
`public Validator`  beans in project.

**Comment by snicoll** [comment]
@jonhkr this issue has been fixed a new `1.5.4.BUILD-SNAPSHOT` with the fix is available. Would you be so kind to test it on your project please? 

If you need instructions to add the necessary snapshot repo, you can create an empty app from start.spring.io. Thanks!

**Comment by dozherel-ucop** [comment]
I've checked 1.5.4.BUILD-SNAPSHOT it looks good.
Thanks,
Danil

**Comment by snicoll** [comment]
Thanks. @jonhkr your problem is completely different so I'd appreciate if you could check anyway.

**Comment by jonhkr** [comment]
@snicoll I've tested with `1.5.4.BUILD-SNAPSHOT` and it is working nicely, thank you.
