### ISSUE TITLE
Enable database initializers when an embedded database is detected

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#8981]
We currently expose database initializers for Spring Batch, Spring Session and Spring Integration JDBC. While the first two are mandatory, the latter is only really required if you start using some of the features.

While working on #8881, we realized that having them enabled by default can be a bit nasty (especially for Spring Integration) so it is disabled now by default.

I think the other two should probably have a mode. Or they should only be enabled automatically if an embedded datasource is detected.

**Comment by vpavic** [comment]
Even though automatically enabled database initializers are helpful to get things up and running quickly I agree that this is somewhat nasty and not desirable in serious environments where you'd want to be explicit and fully in control of schema creation. IMO Spring Boot defaults should align with that approach.

Enabling database initializers for an embedded datasource sounds nice and it's also consistent with approach used for `spring.jpa.hibernate.ddl-auto`, where `create-drop` will be used for embedded and `none` otherwise.

**Comment by snicoll** [comment]
Let's reuse the code we use for Hibernate's ddl-auto flag. And perhaps we should use an enum rather than an enum? (`ALWAYS`, `EMBEDDED`, `NEVER`).

**Comment by philwebb** [comment]
See also #9048 for another initializer bug.

**Comment by snicoll** [comment]
@philwebb any reason you linked that issue to this one? I don't get how they are related.

**Comment by philwebb** [comment]
@snicoll I just linked them so we're aware that we'll likely need to touch that code for another reason as well. I thought it might effect the design.

**Comment by snicoll** [comment]
Also, I think we should revisit the `initializr.enabled` part. The schema attribute in the parent namespace feels really weird. I took a different approach with Quartz with `initialize-schema` at the same level. I think we should go that route for others as well.

**Comment by snicoll** [comment]
Closing in favour of PR #9752
