### ISSUE TITLE
use spring session Serializer issue

### ISSUE THREAD

**Issue by lorgine** [spring-projects/spring-boot#8987]
when i use spring session,and i use like this
@RequestMapping("/test1")
	public String t(HttpServletRequest request) {
		TTT t = new TTT();
		t.setA((new Date()).toString());
		request.getSession().setAttribute("ttt", t);
		return "1";
	}
	@RequestMapping("/test2")
	public String t2(HttpServletRequest request,HttpSession session) {		
		//HttpSession session=request.getSession();
		Object object=session.getAttribute("ttt");
//		return object.toString();
		if(object!=null){
			return ((TTT)object).getA();
		}
		else {
			return "123";
		}
		//return ((TTT)(request.getSession().getAttribute("ttt"))).getA();
		//return "1";
	}

	public static void main(String[] args) {
		ConfigurableApplicationContext application= SpringApplication.run(Test3Application.class, args);		
	}

	public class TTT implements Serializable {
		/**
		 * 
		 */
		private static final long serialVersionUID = -5892678613003835381L;
		private String a;

		public String getA() {
			return a;
		}

		public void setA(String a) {
			this.a = a;
		}
	}

and i pop error, 
Tue Apr 25 11:55:26 CST 2017
There was an unexpected error (type=Internal Server Error, status=500).
Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.StreamCorruptedException: invalid stream header: 35303030

and when i set  
	@Bean("springSessionDefaultRedisSerializer")
	public RedisSerializer<Object> redisSerializer(){
		return new Jackson2JsonRedisSerializer<Object>(Object.class);
		//return new PpdRedisSerializer();
	}
it can save session to redis,but when i get session,i can't use it like this
((TTT)(request.getSession().getAttribute("ttt"))).getA();

there is anyway to resolve it? thank you.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
