### ISSUE TITLE
GridFSBuckets

### ISSUE THREAD

**Issue by inuitdu59** [spring-projects/spring-boot#9031]
Hello,

I didn't find any solution to retrieve an instance of GridFSBucket automatically, I mean without recalling mongo parameters already specified inside an application.yml file.
I prefer not to use the old solution through GridFSTemplate. 
So my question is, which is a solution to get a bean of GridFSBucket (@Autowired does not run) or simply MongoDatabase instance ?
Thanks.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
