### ISSUE TITLE
Spock 1.0 currently in dependency management has problems running Spring Boot tests

### ISSUE THREAD

**Issue by lievendoclo** [spring-projects/spring-boot#9043]
Spock 1.0 throws errors when testing integration tests with Spring Boot, 1.1 has fixed this. The dependency needs to be upgraded.
1.1 is currently in RC stage, but having a dependency that has issues isn't that great either.

**Comment by wilkinsona** [comment]
IIRC, we only have an opinion about the version of Spock due to the support for it in the CLI's test command. I'd quite happily see the testing support removed from the CLI in favour of people moving to a "proper" build system when someone starts to care about tests. A side-effect of that would be that we would no longer care about the version of Spock. At that point we could remove dependency management and we would no longer be exposed to its relatively slow release cadence and relatively long release candidate phase.

**Comment by lievendoclo** [comment]
That would be fine for me as well, as I have to manage the version anyway. At least if the version isn't managed by Spring I get an exception from Maven or Gradle that it can't find the version though the import of the BOM.

**Comment by philwebb** [comment]
+1
