### ISSUE TITLE
integrate SpringBoot and oauth2.0,need help

### ISSUE THREAD

**Issue by xiezhaofeng** [spring-projects/spring-boot#9069]
I am in the integration of springboot and auth2.0 when the occurrence of 401, is Unauthorized, the information is Bad cred entials, I am a novice, need your help, because I can not see where there is a configuration problem. Thank you.

```
Example Address: [git@github.com: xiezhaofeng / auth2.git](url)
[Curl：`curl] -H "Authorization: Basic YjRlYjI1MzExODRlNjZjNzI2YjE6Njc5MGFmZTIxMGNkNzg2NmQ0NmQ3YjM0YjAwOGQ3NzIzZGNkMDBmMg==" http://localhost:8080/oauth/token -d "grant_type=password&scope=read&username=bill&password=abc123"`
or 
`curl http://localhost:8080/oauth/token -d "grant_type=password&username=bill&p                                                                                                                                                                                               assword=abc123"`
```

```
Error message: `{"timestamp": 1493782683124, "status": 401, "error": "Unauthorized", "message": "Bad cred entials", "path": "/ oauth / token"}`
```

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
