### ISSUE TITLE
How do we Configure SpringBoot to use Grizzly as a server instead of Tomcat for Rest Based Applications

### ISSUE THREAD

**Issue by rahulrsingh09** [spring-projects/spring-boot#9122]
Please help

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by rahulrsingh09** [comment]
Already asked but to no avail ,Please help 

http://stackoverflow.com/questions/43796104/integrate-a-spring-boot-application-to-run-with-grizzly-and-jersey
