### ISSUE TITLE
AgentAttacher does not work on JDK9

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#9139]
`AgentAttacher` is attempting to locate the tools classloader to attach an agent at runtime. There is no tools.jar on JDK9 so we'll have to look for another option.

There is a test failing with JDK9 at the moment

```
JvmUtilsTests.getToolsJar:35 » IllegalState Unable to locate tools.jar
```

**Comment by wilkinsona** [comment]
It looks like it was [added in support of Spring Loaded](https://github.com/spring-projects/spring-boot/commit/77bac876ce8e164b652b92ca8bc6ee705e92a4a5). I think we can get rid of it in 2.0.

**Comment by AlanBateman** [comment]
See JEP 220 (http://openjdk.java.net/jeps/220) for the details on the changes to the run-time image in JDK 9. Note that the changes have been in JDK 9 since late 2014 to give as many tools as possible time to adjust to not have rt.jar and tools.jar.

See also JEP 261 (http://openjdk.java.net/jeps/261) for the policy on the modules to resolve when running code on the class path. In this case, the jdk.attach module exports an API and so will be resolved by default when the main class is loaded from the class path (includes executable JARs). This means that the types in jdk.attach will be visible by default, you don't need to specify any special command line options.

As this is Spring Boot then check out the "Deploying Agents in Executable JAR file" section and the Launcher-Agent-Class JAR file attribute in the java.lang.instrument spec (http://download.java.net/java/jdk9/docs/api/java/lang/instrument/package-summary.html)

**Comment by snicoll** [comment]
`AgentAttacher` has been removed as part of #7978
