### ISSUE TITLE
java.lang.IllegalStateException: Unable to load cache item

### ISSUE THREAD

**Issue by Josie-zou** [spring-projects/spring-boot#9154]
Question

I build a project with spring boot, and use nginx as the reverse proxy.But when I sent a request to my server， it returned the “504”.Then I debuged it and found it catched the exception of  'java.lang.IllegalStateException: Unable to load cache item' when it handled servlet request.
my spring boot version is 1.4.1

Bug report

java.lang.IllegalStateException: Unable to load cache item

java.lang.NoClassDefFoundError: org/springframework/cglib/reflect/FastClassEmitter$2

Enhancement

The request do sent to the controller  ,and it broke when it began to execute the service method.At first I guessed if other file was used by two process, but it caught exception when it begin to execute the service method.I am really confused why it broke the request and returned nothing,help me please, thx

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
