### ISSUE TITLE
Property override fails with @ContextHierarchy and @PropertySource/@TestPropertySource

### ISSUE THREAD

**Issue by andriusvelykis** [spring-projects/spring-boot#9234]
I am building a complex context hierarchy of configurations with attached properties via `@PropertySource`annotations. Some of the properties clash but I expected the properties coming from the child context configuration to override the ones in the parent configuration, as they would be 'the last ones'. However, the parent configuration properties are taken instead. Also, this fails even when I tried to override these properties using `@TestPropertySource(child.properties). The reproducible example is outlined below.

Consider a parent configuration with property source:
```java
@Configuration
@PropertySource("classpath:parent.properties")
public class ParentConfiguration {
}
```
And `parent.properties` file with contents:
```
myprop=parent
```

Now we have an analogous child configuration with property source:
```java
@Configuration
@PropertySource("classpath:child.properties")
public class ChildConfiguration {
}
```
And `child.properties` file with contents:
```
myprop=child
```

Now if we package everything in a `@SpringBootTest`:
```java
@RunWith(SpringRunner.class)
@ContextHierarchy({
  @ContextConfiguration(classes = ParentConfiguration.class),
  @ContextConfiguration(classes = ChildConfiguration.class)
})
@SpringBootTest
public class PropertySourceOverrideTest {

  @Value("${myprop}")
  private String myProp;

  @Test
  public void testPropertyOverride() {
    assertThat(myProp).isEqualTo("child");
  }
}
```

This fails with `myProp` being equal to `"parent"`. Is this expected behaviour? Intuitively, I would expect child context configuration to 'override' clashing parts of the parent configuration.

---

As a further step, I would try overriding the property using `@TestPropertySource` as below to make sure my `child.properties` take over.
```java
@RunWith(SpringRunner.class)
@ContextHierarchy({
  @ContextConfiguration(classes = ParentConfiguration.class),
  @ContextConfiguration(classes = ChildConfiguration.class)
})
@TestPropertySource("classpath:child.properties")
@SpringBootTest
public class PropertySourceOverrideTest {

  @Value("${myprop}")
  private String myProp;

  @Test
  public void testPropertyOverride() {
    assertThat(myProp).isEqualTo("child");
  }
}
```

However, this also fails with the `myProp` value being `"parent"`.

When attempting to debug, it appears that the properties are being listed in the order of the hierarchy, i.e. parent ones before the child ones.

**Comment by wilkinsona** [comment]
We don't do much with `@ContextHierarcy` in Spring Boot – it's largely handled by Spring Framework – so I suspect this may not be a problem in Spring Boot itself. @andriusvelykis To help us to pinpoint that cause, can you please assemble the various snippets of code above into an application and test that we can easily unzip/clone and run and be sure that we're investigating exactly what you are reporting.

**Comment by andriusvelykis** [comment]
@wilkinsona no problem - I have attached a Gradle project with test files: [context-hierarchy-property-override.zip](https://github.com/spring-projects/spring-boot/files/1001191/context-hierarchy-property-override.zip)

**Comment by wilkinsona** [comment]
Thanks. I can see now that this is the expected behaviour as documented on [`AbstractApplicationContext.setParent`](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/support/AbstractApplicationContext.html#setParent-org.springframework.context.ApplicationContext-) and [`ConfigurableEnvironment.merge`](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/env/ConfigurableEnvironment.html#merge-org.springframework.core.env.ConfigurableEnvironment-). To get the behaviour that you want you need to given the property sources in the parent and the child the same name. One way to do that is with the `name` attribute on `@PropertySource`.

**Comment by andriusvelykis** [comment]
Thanks - I was aware of the functionality when you explicitly merge the context hierarchies. But is there documentation of the behavior when they are not merged? And, in particular, the case when `@TestPropertySource` does not take precedence?

**Comment by wilkinsona** [comment]
>  I was aware of the functionality when you explicitly merge the context hierarchies. But is there documentation of the behavior when they are not merged?

Sorry, I don't understand the question. AFAIK, there's no concept of merging context hierarchies. When I hierarchy is created the contexts in the hierarchy have their environments merged as described in the two links in my comment above. 

> And, in particular, the case when @TestPropertySource does not take precedence?

`@TestPropertySource` should take precedence as described in its javadoc. In the case of your sample, it does take precedence but is only added to the parent context's environment. This means that the property is found in the child context's environment from `parent.properties`. That strikes me as a little odd, but I'm not sure if it is intentional. I'd recommend that you pursue this with the Spring Framework team as Spring Boot isn't involved.
