### ISSUE TITLE
Reconsider default static locations in ResourceProperties

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-boot#9240]
As seen in #8485, `spring.resources.static-locations` lists classpath and servlet locations as default values. This was causing the leaking of the whole classpath as static resources.

This has been fixed by overriding the `ResourceLoader.getResourceByPath(String path)` method in the reactive application context, a similar approach taken in #7880.

We can see a reactive web application as an application with no `ServletContext` and still keep this fix in place. In that case, `"/"` is still listed in the default values for static locations, and we're keeping the concept of Servlet resources in the context of non-servlet based applications.

On the other hand, we could revisit the `ResourceProperties` keys and separate those values in different keys, like `spring.resources.static-locations` and `spring.resources.servlet-locations`. We would still have to combine both locations lists when configuring Servlet-based applications.

**Comment by bclozel** [comment]
I've got a draft proposal in https://github.com/bclozel/spring-boot/commit/554d033029.

It moves the servlet locations to their own, dedicated configuration key:

* `spring.resources.static-locations=/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/`
* `spring.resources.servlet-locations="/"`

There are next to no behavior changes, since:
* MVC applications will still consider both servlet and static locations for Favicon and resource handling.
* Reactive web apps will only consider the static locations.
* Even if Spring Boot developers did override the `static-locations` configuration key with the `"/"` servlet location, we won't leak resources thanks to #8485 

Note: the default value for `static-locations` in our reference documentation wasn't listing the servlet location...

**Comment by wilkinsona** [comment]
I wonder if `META-INF/resources` should be moved from the general locations to the servlet-specific locations? It's the servlet spec that requires resources to be served from `META-INF/resource` (in jars in `WEB-INF/lib`).

I was going to propose a different name for `servlet-locations`, but while thinking about a new name to propose something here, I find myself wondering if splitting into two properties is the best thing to do. If you're writing a servlet-based app and you want to completely change the static resource locations, you now have two properties that you need to update rather than one. If you wanted to configure a single location you'd have to set on property to be empty.

I wonder if it would be better for the default to vary depending on whether you're building a Servlet-based web app or a WebFlux-based web app. That may not be the cleanest solution in terms of the implementation, but I think it makes most sense from the user's perspective.

**Comment by bclozel** [comment]
@wilkinsona Totally agree. Not the cleanest indeed, especially from a documentation point of view. This is the kind of behaviour that we're trying to avoid in most cases — but here it might be the best choice. Depending on what others think, I can rewrite that commit to do that.

**Comment by wilkinsona** [comment]
Did we not settle on making all of the static-locations be class path-based and then using something else to decide whether or not the servlet context should also be used to resolve static resources?

**Comment by bclozel** [comment]
So we're tentatively trying the following:
* remove the servlet location from the `static-locations` default value
* automatically configure that location it if we're starting a Servlet application
