### ISSUE TITLE
logback logs location with external properties

### ISSUE THREAD

**Issue by solairerove** [spring-projects/spring-boot#9243]
So, what's the issue. 

According to reference, `logging.path` property in `application.properties` maps to `${LOG_PATH}` in `logback-*.xml` file. It's working good with absolute `/var/logs` and relative `logs` paths. But when i get external property in such way:
![image](https://cloud.githubusercontent.com/assets/9396988/26093381/5c053140-3a1e-11e7-94e7-f52323397aca.png)
with `java -jar *.jar --external.config=*.properties` i have an issue, cause of starting logback first. 

So property is not defined in such way. To resolve it, i get new variable `${LOG_HOME:-logs}` in logback and use `java -DLOG_HOME=/path/to/logs -jar *.jar --external.config=*.properties`. The last working enough.

Is there some other fabulous way to resolve it through properties?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by wilkinsona** [comment]
This is, essentially, the same question: http://stackoverflow.com/questions/43890001/spring-boot-not-listening-to-external-logging-level-properties/43916761#43916761

**Comment by solairerove** [comment]
oh, i see. thanks.

**Comment by solairerove** [comment]
There is solution for somebody like me):
`java -jar *.jar --spring.config.location=*.properties`
![image](https://cloud.githubusercontent.com/assets/9396988/26094340/47843b90-3a22-11e7-8f17-807497da4fbd.png)
![image](https://cloud.githubusercontent.com/assets/9396988/26094359/615499f2-3a22-11e7-9e8d-57c2817f4828.png)
