### ISSUE TITLE
the Profile can't work ,how can I do?

### ISSUE THREAD

**Issue by Acctina** [spring-projects/spring-boot#9260]
```
  @Profile("default")
    @Bean
    static public PropertySourcesPlaceholderConfigurer defaultPropertySourcesPlaceholderConfigurer() {
        PropertySourcesPlaceholderConfigurer p = new PropertySourcesPlaceholderConfigurer();
        Resource[] resourceLocations = new Resource[] { new ClassPathResource("core.properties") };
        p.setLocations(resourceLocations);
        return p;
    }
```

```
@Profile("prod-admin")
   @Bean
   static public PropertySourcesPlaceholderConfigurer prodAdminPropertySourcesPlaceholderConfigurer() {
        PropertySourcesPlaceholderConfigurer p = new PropertySourcesPlaceholderConfigurer();
        Resource[] resourceLocations = new Resource[] { 
                new ClassPathResource("core.prod-admin.properties") };
        p.setLocations(resourceLocations);
        return p;
    `}
```

prod-admin.properties  use `jdbcUrl=jdbc:mysql://192.168.0.68:3306/admin`
and core.properties use       `jdbcUrl=jdbc:mysql://192.168.0.68:3306/dev`
when i run project with  command   `mvn spring-boot:run -Dspring.profiles.active=prod-admin 2>&1`
but ,that just use dev database.  I hope i can use admin database,
how can I do for it?

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
Rather than trying to configure a `PropertySourcesPlaceholderConfigurer` I'd recommend just using the standard properties files. You can use `application.properties` and `application-prod-admin.properties` in your case.
