### ISSUE TITLE
BeanPostProcessor called twice for spy beans when using Mockito 2

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#9268]
There's been a [ticket](https://jira.spring.io/browse/DATAREST-1075) reported against Spring Data REST, that a [spy bean](https://github.com/mduesterhoeft/mockito2-event-handler-bug/blob/c6f5017b8922d7672b38b4de325a8ecb132cc4b7/src/test/java/com/example/mockito2eventhandler/ThingRestIntegrationTest.java#L26-L27) gets handed to a `BeanPostProcessor` twice: once for the target bean, once for the spy created for that when Mockito 2 is used. This causing trouble for SD REST as the `BeanPostProcessor` registers the instance for event submission twice now.

I've consulted with Jürgen and he expressed that usually a `BPP` shouldn't be called twice for the same logical bean (name).

**Comment by olivergierke** [comment]
One thing I was thinking is that it might be caused by failing to recognize that the instances are logically the same bean as Mockito 2 uses ByteBuddy to create the proxy.

**Comment by dreis2211** [comment]
```

**Comment by dreis2211** [comment]
Hey,

I hope you don't mind me adding something similar to this issue, which could be also related to this. If not, please ignore this or open another issue.

I have a `@TestConfiguration` class with one @Bean that is included in the `@SpringBootTest` classes field. The bean is a spy which partially stubs some things but uses the real object for everything else.
```
	@TestConfiguration
	static class TestConfig {

		@Autowired
		private SomeDependency someDependency;

//		@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS) // Fixes the issue
		@Bean
		public SomeClass someClass() {
			// Create a spy to maintain the normal functionality you would lose by
			SomeClass someClass = spy(new SomeClass(someDependency));

			// Mock something ...


			return someClass ;
		}

	}
```

The configuration above fails under Mockito 2 saying something like this:
```
'someClass' is expected to be of type 'com.example.dreis.SomeClass' but was actually of type 'com.sun.proxy.$Proxy175'
```

When adding `@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)` I can force it to work, but there seems to be an underlying issue caused by creating the Spy. Unfortunately, I'm currently failing to create a minimal example to reproduce the issue and can't share the actual project.

If necessary I will try to create one.

Cheers,
Christoph

**Comment by philwebb** [comment]
@dreis2211 That looks unrelated to this issue (in fact it might not even be a Spring Boot bug since you're using `spy` directly and not making use of `@SpyBean`). If you do think it's a Spring Boot bug and you can recreate it in a sample, please open a new issue.

**Comment by dreis2211** [comment]
@philwebb Fair enough. As said, I'm fine with it being unrelated. Will try to reproduce it in a minimal example. Though the documentation claims one could use Mockito 2 in 1.5.x. Maybe enhancing the documentation could help. E.g. changing 
```
By default, Spring Boot uses Mockito 1.x. However it’s also possible to use 2.x if you wish.
```
to something that states "Full support of Mockito's 2.x cannot be guaranteed though".

**Comment by philwebb** [comment]
@dreis2211 I'm not saying there isn't a bug, just that it might not be in Spring Boot. The snippet you attached doesn't have much Spring Boot specific code in it.

**Comment by wilkinsona** [comment]
This isn't a bug in Spring Boot. See [this comment on the Spring Data issue](https://jira.spring.io/browse/DATAREST-1075?focusedCommentId=151875&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-151875) for details.
