### ISSUE TITLE
@EnableWebSecurity together with the management.security.enabled=false causes unexpected behavior

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#9270]
According Spring Boot [Reference Manual](http://docs.spring.io/spring-boot/docs/1.5.3.RELEASE/reference/htmlsingle/#howto-switch-off-spring-boot-security-configuration), if we want to disable Boot Security in the application we should just declare `@Configuration` with the `@EnableWebSecurity`.

Of course,  Actuator’s security is still enabled by default.
So, we decided to switch it off as well via `management.security.enabled=false`.
But we end up with the fact that the default `WebSecurityConfigurerAdapter` is applied. In that case we get:
```
public MissingCsrfTokenException(String actualToken) {
	super("Could not verify the provided CSRF token because your session was not found.");
}
```

The test-case to reproduce/play:
```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT
		, properties = "management.security.enabled=false"
)
public class DisableSecurityTests {

	@LocalServerPort
	protected int port;

	@Test
	@SuppressWarnings("rawtypes")
	public void testHealthEndpoint() throws Exception {
		TestRestTemplate testRestTemplate = new TestRestTemplate();
		ResponseEntity<Map> response = testRestTemplate.getForEntity("http://localhost:" + this.port + "/health", Map.class);
		assertEquals(HttpStatus.OK, response.getStatusCode());
		assertTrue(response.hasBody());

		Map health = response.getBody();

		assertEquals("UP", health.get("status"));
		assertTrue(health.containsKey("diskSpace"));
	}

	@SpringBootApplication
	@EnableWebSecurity
	static class HttpSourceApplication {

	}

}
```
You can comment out or `properties` or `@EnableWebSecurity` to see behavior change.

More info is here: https://github.com/spring-cloud-stream-app-starters/http/issues/8

Thanks

**Comment by mbhave** [comment]
@artembilan could you expand a little bit on what the security model looks like in your case? Do you intend to switch off security completely for your application OR turn off the default basic auth security provided by Boot and write your custom security configuration? 

In the first case, you can just set the flags `management.security.enabled` and `security.basic.enabled` to `false`. `@EnableWebSecurity` should be used if you want to write your own `WebSecurityConfigurerAdapter` otherwise it will use the default `WebSecurityConfigurerAdapter`.

**Comment by artembilan** [comment]
Hello, @mbhave !

Than you for feedback!

Well, if you take a look to the linked issue, you'll figure out that the story is about Spring Cloud Stream Application Starter - HTTP Source. Our goal there to make it unsecured by default. And make that only for regular application interaction. The management should be secured by default, indeed.
The problem that we can't have `application.properties` in that application since there is no guarantee (by Boot) which one will be picked up from classpath. Since security is enabled in Boot by default, we found only one way to disable conditionally on our internal `@Configuration` with the `@EnableWebSecurity`. And see, we did that according the same Spring Boot documentation.

If end-user decides to make that app secured, it is just enough for him/her to turn on our own configuration property to `true`. Everything rest relies on the standard Boot configuration for the security.

Yes, we don't provide our own security implementation to the app, but would like to disable it by default without `application.properties`.

If you think `EnvironmentPostProcessor` with conditional switching on `security.basic.enabled = false` is much sufficient there, I won't mind go that way. But let me know if I still can can read the property from the environment there relaxed binding way. We didn't do that from the day first because are afraid a bit that it is too early in the `EnvironmentPostProcessor` to consult environment for the provided properties.
Here I mean, that we want to add `security.basic.enabled = false` to the environment only if there is provided by end-user.

> otherwise it will use the default `WebSecurityConfigurerAdapter`

Yes, I realized that. So, Spring Boot documentation misled us to the idea "if want to disable security in Spring Boot, use `@EnableWebSecurity`". Therefore this ticket should be treated as documentation bug.

Does that all make sense to you?

**Comment by mbhave** [comment]
Thanks for the explanation, @artembilan! I think what you have in the [PR](https://github.com/spring-cloud-stream-app-starters/http/pull/9/files) makes sense. You're essentially providing custom security which always disables the security for the application. The management endpoints will still be secure because of the `ManagementWebSecurityAdapater`. If explicitly disabled by the user, management security will also be turned off. In the PR, I wonder if doing
```java
@Override
protected void configure(HttpSecurity http) throws Exception {
    http.authorizeRequests().mvcMatchers("/**").permitAll();
}
```
might be better. 

Like you said, we can update the documentation to indicate that if you add `EnableWebSecurity` without providing your own `WebSecurityConfigurerAdapter`, it will use the default one. Hope that makes sense.
