### ISSUE TITLE
SpringBoot @Import import additional configuration construct error due to NULL args

### ISSUE THREAD

**Issue by regardfs** [spring-projects/spring-boot#9272]
I have two Packages: serviceCore and serviceApp:

# serviceCore:
**serviceCoreProperities.class:**
```
package serviceCore
import ...
@ConfigurationProperties(prefix="service")
@Validated
public class serverProperities {
private String username;
....
}
```

**serviceCoreAutoConfiguration.class:**

```
package serviceCore
import ...
@Configuration
@EnableConfigurationProperties(serviceCoreProperities.class)
public class serviceCoreAutoConfiguration {
...
}

```
It performed well and everything goes fine.
BUT !!!! 

# serviceApp:
**serviceAppAutoConfiguration.class:**
```
package serviceApp
import serviceCore.serviceCoreAutoConfiguration
@Configuration
@EnableConfigurationProperties
@Import(serviceCoreAutoConfiguration.class)
public class ...
```
When @Import(serverProperities.class) in serviceConfigAutoConfiguration, it return :

> Binding to target serverProperities{username=null,.....}
> Property: username;
> Value: null
> Reason: must not null

I got confused by this error, Everything seems fine under serviceCore, but return error in serviceAppAutoConfiguration, Why?

**Comment by regardfs** [comment]
Might anyone could help me ? I had got stuck at this for about 5 hours.

**Comment by bclozel** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Your sample code only shows bits of code and refers to unknown bits like `serverProperities`. Could you create a question on StackOverflow with enough context so that we can reproduce what you're seeing?

Thanks!

**Comment by regardfs** [comment]
@bclozel , Ok , but, i post this question: http://stackoverflow.com/questions/44062703/springboot-import-additional-configuration-construct-error-due-to-null-args but no one answered me, i suppose response would be fast in git issues....
