### ISSUE TITLE
SpringBootTest with Conditional

### ISSUE THREAD

**Issue by httpdigest** [spring-projects/spring-boot#9275]
Hi there,

I was just trying to execute a SpringBootTest conditionally, based on the environment in which the test is running (i.e. am I currently on an external developer machine without access to a company LDAP and other services) or am I trying to build on a continuous integration server which does have access to all of the internal services. The external developer should of course be able to build and execute all other tests with some integration tests which need access to other services ignored.

I was trying to use the Spring `@Conditional` for this, but it does not seem to be picked up. The test class is specified like so:
```Java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@Conditional(OnInternCondition.class)
```
The OnInternCondition is just an implementation of `org.springframework.boot.autoconfigure.condition.SpringBootCondition`.

Is it somehow possible to achieve what I want? I am also not able to use JUnit's `assumeThat` precondition, since those are executed before each test after the whole application context with the beans needing access to internal services has already been started.

Thanks!

BTW. I am using version 1.5.3.RELEASE of Spring Boot.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Your question isn't really directly related to Spring Boot. It's more about Spring Framework's testing support and JUnit.
