### ISSUE TITLE
Spring boot pool always use same oracle session

### ISSUE THREAD

**Issue by josebertus** [spring-projects/spring-boot#9345]
Hi, sorry for my english

i have a spring boot connection like:

**application.yml**

plsql:
  poolowner: AMA_ADMON
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    connectionProperties: v$session.program=[PWPx - Desarrollo]; v$session.module=Web Proveedores; v$session.osuser=[PoolCon PWP]; v$session.action =Entorno Desarrollo
    url: jdbc:oracle:thin:@10.101.7.15:1521:SIAMA
    username: AMA_ADMON
    password: inicio    
    initial-size: 5
    maxActive: 5

**@SpringBootApplication

...**

	@Bean(name = "plsqlDataSource")
	@Primary
	@ConfigurationProperties(prefix = "plsql.datasource")
	public DataSource plsqlDataSource() {
		
		
	    System.out.println("*************** inicializamos el datasource ********************");	
		return DataSourceBuilder.create().build();
	}

when i run the app, database create 5 inactive sessión, but when i getConnection to execute statement i always use the same session from database, the others four are not use never.

Can you help me please ?

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
