### ISSUE TITLE
getting forbidden error on accessing actuator if management port different from application port using custom spring security

### ISSUE THREAD

**Issue by dushyanthbn** [spring-projects/spring-boot#9358]
Question

Getting forbidden error while accessing actuator running on different port other than application port using custom spring security

application.properties file
----------------------------------------
management.security.enabled=false
management.context-path=/manage
management.port=8085

server.context-path=/lnhcverifyhcp
server.port=8090

Bug report

spring boot version - 1.3.3.RELEASE

Getting forbidden error on accessing actuator url's

-->

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
