### ISSUE TITLE
Could not load TestContextBootstrapper 

### ISSUE THREAD

**Issue by ELLIEbleu** [spring-projects/spring-boot#9388]
after I run  SampleFlyApplication ，I got  the  errors, which is "Could not load TestContextBootstrapper 
[null]. Specify @BootstrapWith's 'value' attribute or make the default boot...." ,I don't know why  occur 
these problem .

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
