### ISSUE TITLE
Separate timezone for integration tests

### ISSUE THREAD

**Issue by fedorbutovets** [spring-projects/spring-boot#9390]
We are using Spring Boot 1.5.2.RELEASE. We need to run our integration tests in multiple timezones and Spring context should be in zone X and test should be in zone Y. In previous version of Spring Boot (1.3.x) it was easy to do because there were two contexts one for server and one for test. Our current is to use something like this `LocalTime.now(timeZone)` in our tests. Is there any way to run server in zone X and tests in zone Y?

**Comment by wilkinsona** [comment]
>  In previous version of Spring Boot (1.3.x) it was easy to do because there were two contexts one for server and one for test

Can you explain what you mean here please? An example of what you were doing in 1.3 that worked and that no longer works in 1.5 would be useful.

**Comment by bitsal** [comment]
Before we switch to new Spring Boot we started app server as a separate process and run integration tests against it. It allowed us to configure any timezone for integration tests and UTC e.g. for app server, just to simulate real production use case. By this, we caught many timezone issues that our app had.

Now with Spring Boot 1.5.2 and the fact that we switched to using `@SpringBootTest` everything is running in the same JVM and there is no way (probably I am wrong) to configure separate time zone for tests and the app because both of them use the same Spring context.

**Comment by wilkinsona** [comment]
Thanks for the clarification. It feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by bitsal** [comment]
@wilkinsona Why can't it be an enhancement proposal? Spring guys know better the product than StackOverflow people. Please consider it as an enhancement proposal.

**Comment by fedorbutovets** [comment]
This question on StackOverflow https://stackoverflow.com/questions/44326962/separate-timezone-for-integration-tests

**Comment by wilkinsona** [comment]
I don't think this is something that Spring Boot can enhance as it doesn't do anything with the time zone. How a time zone is set and used depends on whatever library you're using to deal with dates and times. Tricking two bits of code running on the same JVM to think they're in different time zones, if it's even possible, will depend on what that code is and what capabilities it has.

I think you should expand your question on Stack Overflow to include a lot more detail about the code/libraries you are using to work with dates, times, and time zones. Someone who's familiar with those libraries may then be able to offer you some suggestions.

**Comment by bitsal** [comment]
ok, thank you

**Comment by fedorbutovets** [comment]
Is it possbile to run tests as we did before versions 1.4? How can we run 2 separate java apps one for application and another one for tests? Previously we used `org.springframework.boot.test.SpringApplicationConfiguration` annotation (it was removed and we had to migrate to `org.springframework.boot.test.context.SpringBootTest`). Do we have any way to do it using version 1.5.x?

**Comment by wilkinsona** [comment]
@fedorbutovets Please use Stack Overflow or Gitter for questions.

**Comment by bitsal** [comment]
of course, we will
How to find out what does this breaking change suggest to use instead of old one SpringApplicationConfiguration? Any direction where we can find it?

**Comment by wilkinsona** [comment]
AFAIK, there's no breaking change here in terms of the testing supports functionality. It's just the programming model that's changed. Those changes are [described in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#test-utilities-and-classes). 

This is the last time that I am going to answer a question in this issue. As I've asked more than once already, _please_ use Stack Overflow or Gitter for questions.

**Comment by bitsal** [comment]
@wilkinsona ok, thanks
