### ISSUE TITLE
Set CacheControl for static resources from properties file

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-boot#9432]
Currently, we can set the max-age of static resources by setting `spring.resources.cache-period` configuration property. Setting this property makes `WebMvcAutoConfiguration` call `ResourceHandlerRegistration.setCachePeriod()`. I'd like to have a set of properties (`spring.resources.cache-control.*`) that become arguments to `ResourceHandlerRegistration.setCacheControl()`. For example:

```properties
spring.resources.cache-control.must-revalidate=true
spring.resources.cache-control.public=true
spring.resources.cache-control.stale-while-revalidate=900
# etc..
```

The only way to set CacheControl right now is to implement `WebMvcConfigurerAdapter.addResourceHandlers(ResourceHandlerRegistry)`, but this removes some useful default autoconfigured functionality, such as setting VersionResourceResolver, AppCacheManifestTransformer, etc.

**Comment by bclozel** [comment]
Indeed, we could do that. This gives more insight into what the configuration is actually doing vs. providing a single integer and relying on conventions (`-1` no caching support, `0` no-cache, `>0` max-age).

But we'd probably need to remove `spring.resources.cache-period`, otherwise you could get conflicting configuration keys.

On the Spring Framework side, we could align with that and deprecate in 4.3.x / remove in 5.x the `setCachePeriod` variants of [ResourceHandlerRegistration](https://github.com/spring-projects/spring-framework/blob/v4.3.10.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/ResourceHandlerRegistration.java) and [WebContentGenerator](https://github.com/spring-projects/spring-framework/blob/v4.3.10.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/support/WebContentGenerator.java), which aren't mirrored anyway in the new spring-webflux module.

**Comment by bclozel** [comment]
The configuration keys described by @imgx64 would work, with one caveat.

`CacheControl` has 4 static methods to help avoid building a Cache-Control header with incompatible options (`max-age`, `no-cache`, `no-store`: pick one, or none). This means that at the `CacheControlProperties` level, we would have to enforce that.

**Comment by bclozel** [comment]
We've decided to both keep `spring.resources.cache-period` and add `spring.resources.cache-control.*` configuration keys.

We should get a `CacheControl` instance out of `ResourceProperties` and make sure that any conflicting configurations values (setting both `cache-period` and `cache-control`) should throw an exception.

This means the framework should keep both configuration paths for now.
