### ISSUE TITLE
Protected autoconfiguration

### ISSUE THREAD

**Issue by SirWayne** [spring-projects/spring-boot#9436]
We would like to (re)use the auto configuration classes for the bean creation.
In some cases (e.g. cloud environment) we create the properties object manually.

E.g. for the monogo db bean:
```
        @Bean
        MongoDbFactory mongoDbFactory(MongoClient mongoClient,
                ApplicationContext applicationContext) throws Exception {
            final MongoProperties mongoProperties = ...
            return new MongoDataAutoConfiguration(applicationContext, mongoProperties).mongoDbFactory(mongoClient);
        }
```
But for RabbitMQ, DataSource and Redis the classes are protected.
see 
`RabbitConnectionFactoryCreator().rabbitConnectionFactory(config)`
or
`RedisAutoConfiguration`

Can you please change the scope to `public`, that we can reuse the auto configuration classes?

**Comment by wilkinsona** [comment]
I think we need to take a step back here. You approach of instantiating `MongoDataAutoConfiguration` and then calling one of its methods is unlikely to work reliably. A `@Configuration` class has a well-defined lifecycle that's controlled by the application context. You are creating one and calling it outside of that lifecycle which could lead to all sorts of problems.

Rather than opening things up and encouraging problems such as the one described above, we'd actually like to [move in the opposite direction](https://github.com/spring-projects/spring-boot/issues/5334). As that issue suggests, we're not opposed to exposing public API. However, we'd like to do so carefully: probably by extracting the logic into a class that is specifically intended to be public and has been designed for extension.

If you'd like to pursue this, can you please provide a more detailed described of your use case and the logic that you'd like to be able to reuse?

**Comment by SirWayne** [comment]
I create a own `@Configuration`, to create some beans for different environment e.g locally you get all information for host, port etc. from properties file, but in cloud foundry you get some information from JSON. The idea was only to overwrite the properties like RabbitProperties,MongoProperties etc. and create the bean with the auto configuration classes.

**Comment by wilkinsona** [comment]
Rather than trying to overwrite the properties and use the auto-configuration classes manually. I would recommend manipulating the `Environment` using an `EnvironmentPostProcessor`. Note that Spring Boot already has one for dealing with CloudFoundry's service information. Please see [this section of the documentation](http://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#cloud-deployment-cloud-foundry-services). You may also be interested in the [Spring Cloud Connectors project](https://github.com/spring-cloud/spring-cloud-connectors) that, I think, already does what you're trying to do.

I'm going to close this issue as we do not want to open up our auto-configuration classes unnecessarily, and I think there are better approaches to solving the problem that I now understand you to have. If you'd like some more help with solving that problem, then please ask on Stack Overflow or Gitter.
