### ISSUE TITLE
Problem with spring security and ldap library

### ISSUE THREAD

**Issue by fne** [spring-projects/spring-boot#9440]
Hello

I'm trying to set spring security via ldap but still have the same issue when i started my spring boot app :+1: 
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/directory/server/core/partition/Partition

I used the spring ldap guide but it no longer works.

I am using the last release 1.5.4.

Best regards

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
