### ISSUE TITLE
using redis throw Java.lang.ClassCastException

### ISSUE THREAD

**Issue by AngryCapricorn** [spring-projects/spring-boot#9444]
when I use the spring-boot-starter-data-redis version 1.5.3.RELEASE to provide the second level cache of Mybatis, if cache hit, then throw Java.lang.ClassCastException. but if I remove spring-boot-devtools, it woks well

**Comment by wilkinsona** [comment]
We'll need some more details to be able to diagnose your problem. Can you please read [this section of the documentation](http://docs.spring.io/spring-boot/docs/1.5.3.RELEASE/reference/htmlsingle/#using-boot-devtools-customizing-classload) as it my solve your problem. If it does not, please provide a small sample that reproduces it.

**Comment by AngryCapricorn** [comment]
this is my simple [https://github.com/AngryCapricorn/rediscache](url)
run the app, view localhost:8080/userinfo, if use devtools. it will throw an error

**Comment by wilkinsona** [comment]
As explained in the documentation that I linked to above, DevTools uses two separate ClassLoaders: the app class loader and a restart class loader. The classes in your application (`rediscache` module) are loaded by the restart class loader so that they can be quickly reloaded as you make changes.

In your `RedisCache` class, you're creating a `JdkSerializationRedisSerializer` without specifying a `ClassLoader`. As a result, it uses the app class loader. This means that you end up with a `User` loaded by the app class loader being cast to the `User` type loaded by the restart class loader.

To fix the problem you need to specify a class loader when you create the serializer. For example:

```
RedisSerializer<Object> serializer = new JdkSerializationRedisSerializer(getClass().getClassLoader());
```
