### ISSUE TITLE
“/actuator” endpoint not available

### ISSUE THREAD

**Issue by ManuZiD** [spring-projects/spring-boot#9451]
I created a simple sample project, with only spring-web and spring-actuator. I'm not able to call the `/actuator` endpoint in this project. Only thing I get is that 404 error:

`There was an unexpected error (type=Not Found, status=404).
No message available`

In the logs I can't see anything about this. I activated the `management.security.enabled=false` in the `application.properties` to avoid the security issues.

In other projects with the same spring, spring-web and spring-actuator version I reach the `/actuator` endpoint but I can't see differences.

Here is a GitHub link to the sample project: https://github.com/ManuZiD/mzd-actuator

Any suggestions would be nice. Thanks in advance.

Spring Boot Version: 1.5.4.RELEASE

Question on SO: https://stackoverflow.com/questions/44473626/spring-actuator-actuator-endpoint-not-available

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by ManuZiD** [comment]
Thanks for response @wilkinsona. On SO i got an answer. I need the hateoas dependency too. I didn't expect that but now it works. Please apologies for this wrong placed "issue".
