### ISSUE TITLE
How to install spring boot 2.0.0 M1 ?

### ISSUE THREAD

**Issue by appsolutegeek** [spring-projects/spring-boot#9452]
Hi,

can anyone tell me how i can install the new spring boot CLI (milestone release - beta)

I checked sdkman (recommended) and its not available, and I also checked BREW (I am on a MAC OS X) and doesn't seem to be available either.

Can anyone help ?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
