### ISSUE TITLE
Use Kotlin's bom to provide dependency management for Kotlin

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9486]
Thanks to @sdeleuze, it [looks like Kotlin is going to provide a bom](https://youtrack.jetbrains.com/issue/KT-18398#comment=27-2228116). As part of our Kotlin story in 2.0, we should import the bom in `spring-boot-dependencies`.

**Comment by sdeleuze** [comment]
I would suggest renaming this issue to "Provide dependency management for Kotlin", add for the moment `kotlin-reflect`, `kotlin-stdlib`, `kotlin-stdlib-jre7` and `kotlin-stdlib-jre8` artifacts to dependency management (enough for most use cases) since it is needed for #10511. If a Kotlin BOM is released before 2.0 GA (see [KT-18398](https://youtrack.jetbrains.com/issue/KT-18398), I have recently highlighted again the priority of that issue to Kotlin team) we will switch to the BOM, else staying with that for now will help most Kotlin developers to avoid mixing different versions of Kotlin artifacts (occurs frequently with `kotlin-reflect`).

**Comment by sdeleuze** [comment]
@wilkinsona Damned it seems we almost got it for Boot 2.0 but that will be for Boot 2.1 ;-) Could you please have a look to https://github.com/cy6erGn0m/kotlin-bom/blob/master/kotlin-lang/pom.xml, @cy6erGn0m would like some feedbacks and I prefer to ask to the real expert on that topic!

**Comment by wilkinsona** [comment]
Kotlin has a bom in 1.3 so we should be able to do this in 2.2.

**Comment by wilkinsona** [comment]
As shown by this issue being assigned to the 2.2.x milestone, we intend to upgrade to Kotlin 1.3 in Spring Boot 2.2.

**Comment by snicoll** [comment]
> However, Spring Boot appears to be overriding that version

The Spring Boot parent and dependency management sets a version for Kotlin, yes. You can easily override that [as described in the documentation](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#managing-dependencies-customizing)

**Comment by sdeleuze** [comment]
@oliemansm Spring Boot plugin is expected to leverage the Kotlin version defined with the `kotlin.version` property, and Gradle plugin even directly uses the version of the Kotlin plugin.

**Comment by oliemansm** [comment]
Thanks all

**Comment by ilya-g** [comment]
@wilkinsona Note that Kotlin will have bom only starting from 1.3.20, which hasn't been released yet. Although you can try the eap version, which has been published recently: 
https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-bom/1.3.20-eap-25
https://dl.bintray.com/kotlin/kotlin-eap/org/jetbrains/kotlin/kotlin-bom/1.3.20-eap-25/

**Comment by sdeleuze** [comment]
After discussion with @mp911de I have created [KT-30042](https://youtrack.jetbrains.com/issue/KT-30042) to ask Coroutines artifacts to be added in the `kotlin-bom` since most Coroutines are on library side and use a different version scheme (currently Coroutines `1.1.1` is designed to work with Kotlin `1.3.21`).
