### ISSUE TITLE
Plans to add a `boot-starter-restclient` starter pom ?

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#9488]
Hi there,

Do you have plans to add a `spring-boot-starter-restclient` starter pom that would pull the dependencies required to build a rest client without the servlet container ?
It would ideally pull at least stuff like:

- org.springframework:spring-web
- Jackson

Sincerely,

/Bertrand

**Comment by snicoll** [comment]
I don't think we don't. We do have a `spring-boot-starter-json` now so that should help. Let's see what the rest of the team thinks.

**Comment by philwebb** [comment]
I'm not too keen on adding a dedicated starter for this. Hopefully the new `spring-boot-starter-json` dependency will help with the Jackson side, and that just leaves a single `spring-web` dependency to add.

**Comment by asarkar** [comment]
Actually, I've had the need for consuming REST services without going full web several times. We've some `CommandLineRunner`s that do data processing, and the regular `spring-boot-starter` is good enough for those. Except it doesn't come with a REST client so I've been using the Netflix Feign client or Apache HTTPClient or both.

**Comment by bclozel** [comment]
"Just" adding `spring-web` and jackson wouldn't be a great choice, since using the JDK HTTP client is hardly a good default.

Also, `AsyncClientHttpRequestFactory` has been deprecated in Spring 5.0 in favor of the new `ClientHttpConnector` and the `WebClient` itself. I suspect many applications will use those (even if they're not reactive themselves). This new HTTP client is part of `spring-webflux` (i.e., not `spring-web`), so there's already a starter for that.

In my opinion, creating a starter for `RestTemplate` right now would certainly send the wrong signal, especially in Boot 2.0.

**Comment by asarkar** [comment]
> creating a starter for RestTemplate right now would certainly send the wrong signal

@bclozel, I agree. I mentioned `RestTemplate` because that's the prevalent HTTP client in Spring Boot pre 2.0, but I did say "The same argument applies for the new reactive web client."

As for `spring-webflux`, I believe it has more than just the `WebClient`. The point I'm trying to make is that we should have the choice to include or not include a web server (or Netty-ish server, same thing).

**Comment by philwebb** [comment]
At least for the moment I don't think we should proceed with directly adding a client starter. We can reconsider post 2.0.
