### ISSUE TITLE
Debug Logs:Cleared thread-bound request context

### ISSUE THREAD

**Issue by harishkadamudi** [spring-projects/spring-boot#9503]
Have configured Eureka Server in a Standalone mode and I have enabled Spring Security and Have couple of Clients connecting to it.
Clients are successfully able to connect to Eureka Server, When I look at Eureka Server logs I see lots of Log being logged, like 16:57:31.538 [http-nio-8846-exec-9] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Bound request context to thread: org.apache.catalina.connector.RequestFacade@1a23671d
16:57:31.540 [http-nio-8846-exec-9] DEBUG o.s.b.w.f.OrderedRequestContextFilter - Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@1a23671d

What are these?

Have attached sample logs along with this ticket. Would like to know Is that something I a missing to configure or Should i turn off simply.

This is a concern as file Log file size is growing rapidly.

I had created this issue in wrong place https://github.com/spring-cloud/spring-cloud-netflix/issues/2036

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by harishkadamudi** [comment]
Thanks.
here is the link https://stackoverflow.com/questions/44524146/springboot-heartbeat-excessive-loggin
