### ISSUE TITLE
AutoConfigureJsonTesters isn't ordered correctly

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9515]
Take the sample from https://github.com/spring-projects/spring-hateoas/issues/551 and update the annotations to:

```java
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureJsonTesters
public class DemoApplicationTests {
```

Auto configuration doesn't happen due to:

```
JsonTestersAutoConfiguration.JacksonJsonTestersConfiguration#jacksonTesterFactoryBean:
      Did not match:
         - @ConditionalOnBean (types: com.fasterxml.jackson.databind.ObjectMapper; SearchStrategy: all) did not find any beans (OnBeanCondition)
```

This is probably an auto-configuration ordering issue.

**Comment by philwebb** [comment]
Workaround:

```java
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureJsonTesters
public class DemoApplicationTests {
    @Autowired
    private ObjectMapper mapper;
    private JacksonTester<Entity> json;
    @Before
    public void setup() {
        JacksonTester.initFields(this, mapper);
    }
    @Test
    public void serializeInstant() throws IOException {
        Entity value = new Entity();
        value.setInstant(Instant.ofEpochSecond(0, 1));
        json.write(value)
            .assertThat()
            .extractingJsonPathNumberValue("$.instant")
            .isEqualTo(1e-9);
    }
}
```

**Comment by snicoll** [comment]
I must be missing something obvious. I've changed the auto-config with

```java
@AutoConfigureAfter({ JacksonAutoConfiguration.class, GsonAutoConfiguration.class })
public class JsonTestersAutoConfiguration {
```

And I get the same error. At the same time, I can see that the `ObjectMapper` is produced as expected:

```
  JacksonAutoConfiguration.JacksonObjectMapperConfiguration#jacksonObjectMapper matched:
      - @ConditionalOnMissingBean (types: com.fasterxml.jackson.databind.ObjectMapper; SearchStrategy: all) did not find any beans (OnBeanCondition)
```

I really don't get why that doesn't work.

**Comment by wilkinsona** [comment]
The ordering change that @snicoll attempted has no effect as the auto-configuration is considered in two separate batches:

1. `DemoApplicationTests` -> `@AutoConfigureJsonTesters` -> `@ImportAutoConfiguration`
2. `DemoApplication` -> `@SpringBootApplication` -> `@EnableAutoConfiguration`

This first batch considers `JsonTestersAutoConfiguration` in isolation so the ordering constraints have no effect and, because the `DemoApplicationTests` batch is processed first, there will never be an auto-configured `ObjectMapper` available.
