### ISSUE TITLE
org.hibernate.MappingException: No Dialect mapping for JDBC type: -9

### ISSUE THREAD

**Issue by mr-dragon** [spring-projects/spring-boot#9562]
![image](https://user-images.githubusercontent.com/25114117/27362410-e2a57d1e-5660-11e7-8b6f-2b62e2f6f6e0.png)

java.sql.Types

`    public static final int NVARCHAR = -9;`

Type not supported by NVARCHAR

application.properties settings dialect does not take effect

```
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2008Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
```

Why can I set this property on the Internet while I set it up?

![image](https://user-images.githubusercontent.com/25114117/27363306-3f4bb79a-5666-11e7-8c21-f1027e0fe345.png)

How to configure problems that do not support database types?

Ask God for help,  Thank you

**Comment by mr-dragon** [comment]
```
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>1.5.4.RELEASE</version>

The Internet is set up in version 1.4.0.RELEASE
But I do not use the same version, because the database type is not the same? Online is mysql, I use the sql server

```

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
