### ISSUE TITLE
Why maven plugin exclude dependencies did not use fuzzy match

### ISSUE THREAD

**Issue by stayfool** [spring-projects/spring-boot#9576]
This is my situation:
 I want to remove dependencies when packaging my application. and then submit my application to storm,  the dependencies have been add to storm library.
But the maven plugin exclude filter is exact match, so I must to add every dependency to the plugin exclude configuration.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by stayfool** [comment]
@snicoll I think this feature can be enhanced to fuzzy matches or regular matches

**Comment by snicoll** [comment]
This was already requested and we've declined. See, for instance, #6139

**Comment by stayfool** [comment]
@snicoll I got it
