### ISSUE TITLE
Why was the RelaxedDataBinder class deleted?

### ISSUE THREAD

**Issue by taolive** [spring-projects/spring-boot#9591]
Why was the RelaxedDataBinder class deleted?
in Spring boot V2.0.0.BUILD-SNAPSHOT

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/) or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).
