### ISSUE TITLE
Dev null 

### ISSUE THREAD

**Issue by prabhatpankaj** [spring-projects/spring-boot#9594]
I run spring java project in aws server  in port 8080 and then I redirect port 8080 to port 80 using apache2 reverse proxy .

After running this 
spring-boot:run 

My IP address is acceptable .

But when I exited from shell . Then port 8080 get close.

So my doubt is what is the >/dev/null equivalent command to run the server even after exit from aws console in this seniaro ...

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
