### ISSUE TITLE
How to validate List of Objects in Spring Rest Controller

### ISSUE THREAD

**Issue by sandeeprajub4u** [spring-projects/spring-boot#9627]
@RequestMapping(value="/create", method=RequestMethod.POST)
public boolean createTest(@Validated(XYZ.class) @RequestBody List<Test> data)
public boolean updateTest(@Validated(ABC.class) @RequestBody List<Test> data)

How to validate the list of same objects with different Validated groups?

We followed the solution as per stackoverflow but the CollectionValidator does not have any details of groups
https://stackoverflow.com/questions/34011892/spring-validation-for-requestbody-parameters-bound-to-collections-in-controller/36790509#answer-36790509

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
