### ISSUE TITLE
Integrate BotMill framework

### ISSUE THREAD

**Issue by darrelGapstar** [spring-projects/spring-boot#9642]
Question : 

Hi. Is there a possibility to inject the fb-BotMill framework (https://github.com/BotMill/fb-botmill) to a spring boot Application ??

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
