### ISSUE TITLE
How to use MockRestServiceServer twice in one test case?

### ISSUE THREAD

**Issue by zhanjiejun** [spring-projects/spring-boot#9649]
I called two different rest API in one method, and want to mock two server in one test case, what should i do?
```
@Autowired
private RestTemplate restTemplate;

@Test
public void test() {
	MockRestServiceServer mockServer1 = MockRestServiceServer.createServer(restTemplate);
	mockServer1.expect(requestTo(containsString("/testAAA"))).andExpect(method(HttpMethod.GET))
			.andRespond(withSuccess(JSONObject.toJSONString(response1), MediaType.APPLICATION_JSON_UTF8));

	MockRestServiceServer mockServer2 = MockRestServiceServer.createServer(restTemplate);		
	mockServer1.expect(requestTo(containsString("/testBBB"))).andExpect(method(HttpMethod.GET))
			.andRespond(withSuccess(JSONObject.toJSONString(response1), MediaType.APPLICATION_JSON_UTF8));

	// test
}
```

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
