### ISSUE TITLE
Not able to plug-in a custom cache manager via shared library to Spring Boot Service

### ISSUE THREAD

**Issue by bsridhar123** [spring-projects/spring-boot#9651]
I am trying to add caching behaviour to the services using Spring @cacheable annotation and by using a  custom cachemanager as part of configuration.

I want to use the the custom cachemanager as part of a shared library so that all services can use them accordingly.

I want to enable/disable caching at runtime by plugging in a NoOpCacheManager if caching behaviour is to be switched off and a actual cachemanager when caching is turned on.

My custom configuration class works fine when used within the service project. But, when I make it a shared library and reference it in the service the caching behaviour does not work.

So, I have a shared library which is now referenced by my service. I want to use the shared library to so that I can change the cacheManager strategy by changing to some other cache manager without impacting the service client.

But, now caching does not work.

I am not sure if some other cache configuration is getting configured automatically or not.

Within the same service it works, but not as a shared library. 

I want to understand if I need to exclude some cache configuration classes or configure my configuration before some other configuration is getting created.

I have shared a repository with the projects I am using for this issue to be reproduced.

https://github.com/bsridhar123/cache-demo-repo

- It includes the **cachedemo-service** project which references the shared library where-in I have my custom cache manager logic.

- The **caching-component** which is the shared library containing my custom cacheManager bean.

- **Configuration-Service which is the Spring Cloud Config based Config service** which manages configuration from a file system folder.

- The file system folder(hello-repo)  where I have my configuration used by my service.

Can you please help me on this.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
