### ISSUE TITLE
ActiveMQConnectionFactoryConfiguration not correctly passing through properties to ActiveMQConnectionFactory

### ISSUE THREAD

**Issue by pivotaljohn** [spring-projects/spring-boot#9667]
The ActiveMQ auto-configuration does not properly pass along custom configuration to the underlying `ActiveMQConnectionFactory`. 

- `PooledConnectionFactory` only supports post-construction configuration.
   - `org.apache.activemq.pool.PooledConnectionFactory#setProperties()` constructs a brand new underlying `ActiveMQConnectionFactory` based on the passed-in properties.
   - `org.apache.activemq.pool.PooledConnectionFactory#getProperties()` makes a defensive copy, styming attempts to set configuration by modifying the returned object.
- `ActiveMQConnectionFactoryConfiguration` (via `ActiveMQConnectionFactoryFactory`) presumes to create the underlying `ActiveMQConnectionFactory` so that it can set `username`, `password`, and `brokerUrl`.

This is captured in these two test cases (intended for `ActiveMQAutoConfigurationTests`):

```java
@Test
public void customActiveMQConnectionFactoryPoolConfigurationFromProperty() {
	load(EmptyConfiguration.class, "spring.activemq.pool.enabled:true",
				  "spring.activemq.pool.configuration.properties.nonBlockingRedelivery:true",
				  "spring.activemq.pool.configuration.properties.producerWindowSize:10");
	PooledConnectionFactory pooledConnectionFactory = this.context
				  .getBean(PooledConnectionFactory.class);
	ActiveMQConnectionFactory connectionFactory = (ActiveMQConnectionFactory)
				  pooledConnectionFactory.getConnectionFactory();
	assertThat(connectionFactory.isNonBlockingRedelivery()).isTrue();
	assertThat(connectionFactory.getProducerWindowSize()).isEqualTo(10);
}

@Test
public void customActiveMQConnectionFactoryPoolConfigurationFromProperties() {
	load(EmptyConfiguration.class, "spring.activemq.pool.enabled:true",
				  "spring.activemq.pool.configuration.properties:sendTimeout=5000\ncheckForDuplicates=true");
	PooledConnectionFactory pooledConnectionFactory = this.context
			.getBean(PooledConnectionFactory.class);
	ActiveMQConnectionFactory connectionFactory = (ActiveMQConnectionFactory)
				  pooledConnectionFactory.getConnectionFactory();
	assertThat(connectionFactory.getSendTimeout()).isEqualTo(5000);
	assertThat(connectionFactory.isCheckForDuplicates()).isTrue();
}
```

Note: If inside `ActiveMQConnectionFactoryConfiguration.PooledConnectionFactoryConfiguration#pooledJmsConnectionFactory` one naively calls `PooledConnectionFactory#setProperties()`, `ActiveMQAutoConfigurationTests` successfully, but the fact that a new `ActiveMQConnectionFactory` is caught by `JmsAutoConfigurationTests`.

**Comment by snicoll** [comment]
The problem is that we bind `PooledConnectionFactory` directly to the environment and that object is not exposing regular Java Bean properties. I am wondering if these two properties you set there can be set in a different way.

I suspected passing that as broker url parameters should work but it doesn't. We probably need a `spring.activemq.properties.*` object that we own so that things can be specified that way.

**Comment by pivotaljohn** [comment]
**Binding ActiveMQConnectionFactory properties explicitly:**
I'm interpreting this option as that as expanding `ActiveMQProperties` to include _all_ properties on the `ActiveMQConnectionFactory`.  This gets a little tricky as there are four flavors (+`ActiveMQSslConnectionFactory`, `ActiveMQXASslConnectionFactory`, `ActiveMQXAConnectionFactory`).

Looking at the history of these classes:

- [`ActiveMQConnectionFactory`](https://github.com/apache/activemq/commits/master/activemq-client/src/main/java/org/apache/activemq/ActiveMQConnectionFactory.java) — four (4) new properties added since 2013.
- [`ActiveMQSslConnectionFactory`](https://github.com/apache/activemq/commits/master/activemq-client/src/main/java/org/apache/activemq/ActiveMQSslConnectionFactory.java) — two (2) new properties in the same timeframe.
- [`ActiveMQXAConnectionFactory`](https://github.com/apache/activemq/commits/master/activemq-client/src/main/java/org/apache/activemq/ActiveMQXAConnectionFactory.java) — one (1) new property in the same timeframe.
- [`ActiveMQXASslContextFactory`](https://github.com/apache/activemq/commits/master/activemq-client/src/main/java/org/apache/activemq/ActiveMQXASslConnectionFactory.java) is relatively brand-spankin'.

At what velocity does the cost of maintenance outweigh the improved AppDev's UX?

**Binding to ActiveMQConnectionFactory directly:**
From what I've been hearing, sounds like there's been a history of 3rd parties changing their API in the same way that Apache did with `PooledConnectionFactory`.  True?

FWIW, `PooledConnectionFactory` changed from JavaBean properties to this  [in ActiveMQ-5.9 circa Q4 2013](https://github.com/apache/activemq/commit/b66559ee079bd55bfc49daae6b95b79706147fbe#diff-58e20f824cdb279fca47446bc444f57f).

----

I'm game to put in the PR.  I'm leaning towards binding ActiveMQ*ConnectionFactory properties explicitly.

Thoughts?

**Comment by pivotaljohn** [comment]
Agreed that these belong in the top-level of `ActiveMQProperties`.

I wonder if we want to enumerate the configurable properties in `ActiveMQProperties` (instead of a `Properties`).  That way the developer doesn't have to sift through setter-injectors to find configuration properties.  They'd also get the auto-completion support.

Looking through prior art, seems like this decision has gone both ways.

**Comment by snicoll** [comment]
Not really, we never exposed the whole set of a properties object AFAIK (except a few well-known hibernate properties). I'd go with the properties for now, it's better than what we have today and that might still land on 1.5 (an exhaustive list wouldn't).

If ActiveMQ decided not to do it, I don't think we should.

**Comment by snicoll** [comment]
I think I have a quite good overview of the problem. Our auto-configuration support for ActiveMQ is quite inconsistent I am afraid.

* If pooling isn't used then the only configuration properties that are available are the handful one in `ActiveMQProperties` (subtext: anybody willing to configure advanced stuff will not use the auto-configuration)
* If pooling is used, we expose the `PooledConnectionFactory` to `spring.activemq.pool.configuration` for some reason. The pooling options can therefore be changed but the settings of the underlying `ActiveMQConnectionFactory` cannot
* Worse, a `spring.activemq.pool.configuration.properties` is exposed (because it is a valid property for the binder) and providing options there as no effect as explained already in this issue)

That last point makes it quite obvious that we shouldn't expose `PooledConnectionFactory` to the environment. Doing so in 1.5.x is unlikely so we'll have to push that to 1.5

So there are two issues that are a bit tangled:

* `spring.activemq.pool.configuration.properties` is the only "advertized" way to tune the `ActiveMQConnectionFactory` and it does not work
* There is no way to provide advanced configuration for ActiveMQ. 

Here is a list of actions to solve this

* Stop binding `PooledConnectionFactory` to the environment and provide explicit properties for the remaining bits (and not `properties` of course). That is doable in `1.5.x` still 
* We could offer a `spring.activemq.properties` of our own that will work in all cases but that feels inferior experience compared to the rest of Spring Boot
* Or, we can add a bunch of properties in  `ActiveMqProperties`  and bind the factory ourselves

I am wondering what the rest of the team things. @pivotaljohn is that a fair summary of the situation?

**Comment by pivotaljohn** [comment]
Well articulated, @snicoll; all your points match my understanding.

A bit of color (if even necessary):

- if we offered a pass-through `spring.activemq.properties`, that "inferior experience," involves hunting down some 30 possible properties (some of which themselves are nested properties, e.g. RedeliveryPolicy, PrefetchPolicy...).  I found this hunt challenging: I could not find a complete and centralized list of all the properties for `ActiveMQConnectionFactory`.
- the scope of maintenance — including the various `*Policy`s nested properties — roughly 50 properties in total.

**Comment by wilkinsona** [comment]
Binding the factory ourselves sounds like the right thing to do, however the prospect of keeping in sync with roughly 50 properties in total doesn't fill me with joy. It does look achievable though. We could probably write some tests to check that we've exposed everything.

Alternatively, I wonder if we can identify some regularly used configuration settings that we should be support via configuration properties, and then provide a customiser callback interface that can be used to tune the rest? Even if we try to support everything the callback is probably a good idea in case someone wants to use a slightly different version of ActiveMQ than the default and it introduces a new option.

**Comment by snicoll** [comment]
Alright, the customizer is implemented. I'll have a deeper look at the properties and try to extract a sensible list. I've also created #9837 to figure out what to do with the pooling part.
