### ISSUE TITLE
Give special treatment for CSS files in DevTools LiveReload

### ISSUE THREAD

**Issue by mhjam** [spring-projects/spring-boot#9668]
From livereload.com:

> Even cooler, when you change a CSS file or an image, the browser is updated instantly without reloading the page.

It looks like the DevTools LiveReload server does not support this. I changed a CSS file in my project (where I am using DevTools) and the browser got triggered to reload the whole page. I would expect it to just load the updated CSS file.

If this should already work I would appreciate a hint about where to look for a potential configuration problem. Otherwise, please see it as a feature request.

**Comment by philwebb** [comment]
I'm guessing that this support depends on a complete `path` being sent in the [`server-to-client` reload request](http://livereload.com/api/protocol/). We're currently quite dumb about what we send, there's just a single `LiveReloadServer.triggerReload()` method and it doesn't take any arguments.

I think if we extracted data from `ClassPathChangedEvent` we might be able to trigger a change for a specific file. I'm not sure what we should do if two files are changed at the same time, I guess we'd just trigger a full reload as we currently do.

**Comment by philwebb** [comment]
It's a little involved, but if anyone is interested in contributing a fix for this they'd need to:

* Change `LiveReloadServer.triggerReload()` to take an optional `path` String argument 
* Update `Connection.triggerReload` to send a different payload
* Update `OptionalLiveReloadServer` to mirror `LiveReloadServer`
* Change `onClassPathChanged` in `LocalDevToolsAutoConfiguration.LiveReloadConfiguration` to inspect `ClassPathChangedEvent` and determine if a single path can be deduced. It might be hard to work out what the actual path is that the remote server sees since we're only dealing with local files. I guess this might not matter if the browser plugin just looks at the extension.

**Comment by luka-zitnik** [comment]
Ah, I knew I should have picked an older issue. @tomello, I'm sorry. Admins, whatever you decide is best..

**Comment by tommelo** [comment]
Hey @luka-zitnik no worries mate!
I'm not sure if my changes could fix this issue...

**Comment by luka-zitnik** [comment]
@tommelo :) they seem alright to me. You've made a different approach, so, let's see what Phillip says.

**Comment by philwebb** [comment]
> it might be hard to work out what the actual path is that the remote server will see (since we're only dealing with local files). Looking at the [live reload code](https://github.com/livereload/livereload-js/blob/03b09762e930f6c6c67ee270c208d1c11de0247f/src/reloader.coffee#L78-L91), that might not matter.

It turns out that the path does matter because it gets passed to the `reload` method. Given that we can't easily tell how a local resource is actually mapped to the server I think this feature is going to be too hard to implement in a consistent manor.
