### ISSUE TITLE
SpringBoot - Atomikos - Warning of missing transaction in latest 2.0.x snapshot

### ISSUE THREAD

**Issue by manuel-sousa** [spring-projects/spring-boot#9673]
When a repository has a method findBy... spring boot outputs the warning bellow on initialization
```
2017-07-03 17:29:56.147  WARN 29034 --- [           main] c.a.icatch.jta.TransactionManagerImp     : This method needs a transaction for the calling thread and none exists.
Possible causes: either you didn't start a transaction,
it rolledback due to timeout, or it was committed already.
ACTIONS: You can try one of the following: 
1. Make sure you started a transaction for the thread.
2. Make sure you didn't terminate it yet.
3. Increase the transaction timeout to avoid automatic rollback of long transactions;
   check http://www.atomikos.com/Documentation/JtaProperties for how to do this.
```

To reproduce this I cloned the spring-boot repo and used the sample `spring-boot-sample-jta-atomikos` adding `findByUsername` (diff bellow)

```
$ git diff
diff --git a/spring-boot-samples/spring-boot-sample-jta-atomikos/src/main/java/sample/atomikos/AccountRepository.java b/spring-boot-samples/spring-boot-sample-jta-atomikos/src/main/java/sample/atomikos/AccountRepository.java
index 6b88cb4..477710a 100644
--- a/spring-boot-samples/spring-boot-sample-jta-atomikos/src/main/java/sample/atomikos/AccountRepository.java
+++ b/spring-boot-samples/spring-boot-sample-jta-atomikos/src/main/java/sample/atomikos/AccountRepository.java
@@ -19,5 +19,5 @@ package sample.atomikos;
 import org.springframework.data.jpa.repository.JpaRepository;
 
 public interface AccountRepository extends JpaRepository<Account, Long> {
-
+    public Account findByUsername(String username);
 }
```

**Comment by wilkinsona** [comment]
I presume you must have also called that method somehow to trigger the warning? Can you please provide a complete sample that reproduces the warning?

**Comment by manuel-sousa** [comment]
After adding any findByMethod this error shows up just by doing `mvn spring-boot:run` at startup, in this case just using the sample and adding that method should show up the warning.

From what i could tell this happens while searching/creating named queries for these methods.

The repository methods do work later when called so i don't know if there's any other side effect besides the warning output.

**Comment by wilkinsona** [comment]
Thanks for the additional explanation. I don't think this has anything to do with Spring Boot specifically so it'll need to be addressed elsewhere.

During the processing of the `findByUsername` method, Spring Data JPA calls `EntityManager.createNamedQuery(String)` to look up a named query. This fails as a query with the given name hasn't been defined. As a result, Spring Data JPA will create a query based on the method name.

As part of the lookup failing, Hibernate attempts to mark the current JTA transaction as rollback only. There isn't one, which, per the JTA specification, causes an `IllegalStateException` to be thrown. Unfortunately, in addition to throwing the `IllegalStateException`, Atomikos also logs the warning message mentioned above.

I can see two possible ways to fix this:

1. Update Spring Data JPA so that it performs the look up of the named query in a transaction. There's obviously a cost to this and I don't know what other, unwanted side-effects it may have. @olivergierke would know more. It's also a general change for an Atomikos-specific problem.
2. Change Atomikos so that it doesn't log the warning message (which, without the exception stack trace, isn't helpful as it doesn't tell you which method was called without a transaction or what called it)

A workaround for the log message would be to set to level of the `com.atomikos.icatch.jta.TransactionManagerImp` logger to `ERROR` but that would lose other, more useful, warning messages.

**Comment by wilkinsona** [comment]
I just checked if the same problem occurs with 1.5 and it does not. The reason for that is a chance in Hibernate. Spring Boot 1.5 uses Hibernate 5.0 while Spring Boot 2.0 uses Hibernate 5.2. Both attempt to mark the current transaction as rollback only, but Hibernate 5.0 is much more defensive.

In Hibernate 5.0 it checks for an active Hibernate transaction and, if there is an active transaction, it marks it roll back only. If there's no Hibernate transaction it looks for JTA being configured and if it is, and the status of the transaction manager is not STATUS_NO_TRANSACTION is marks the transaction rollback only.

In Hibernate 5.2 it attempts to mark the transaction rollback only no matter what, relying on the `IllegalStateException` if there's no transaction active.

**Comment by manuel-sousa** [comment]
@wilkinsona first of all thanks for your work and assistance. I had also followed the problem to that method but wasn't sure if it would be a spring data issue, atomikos, or something in between. This was the reason i reported here and since it was easily reproducible with a sample.

Yes this didn't happen in 1.5 but i lacked the skills to relate it to hibernate. 
With no visible side effects later on i'll just ignore the message. I was more worried that something might be failing to be created, despite stuff working.

**Comment by nniesen** [comment]
I logged [HHH-12571](https://hibernate.atlassian.net/browse/HHH-12571) because as far as I can't tell, they should not be calling javax.persistence.EntityTransaction#setRollbackOnly if there is not an **active** transaction.
