### ISSUE TITLE
How  to inject value from application.properties to  other annotation?

### ISSUE THREAD

**Issue by toplinuxsir** [spring-projects/spring-boot#9686]
for example , in applicaton.properties I have :
```
datetime_pattern=yyyy-MM-ddTHH:mm:ss
```

, I hava controller class , want to inject the `datetime_format` to annotation `@DatetimeFormat`

```java
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
 
import java.time.LocalDate;
 
@RestController
@RequestMapping("/api/datetime/")
final class DateTimeController {

    @Value("${datetime_pattern}")
    private String datePattern
 
    @RequestMapping(value = "date", method = RequestMethod.POST)
    public void processDate(@RequestParam("date") 
                            @DateTimeFormat(pattern=datePattern) LocalDate date) {
        //Do stuff
    }
}
```
But error occur : annoatation paramter must be a compile time constant.
How to ?
Thanks !

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.
