### ISSUE TITLE
The file can not be read, Use jar package when starting

### ISSUE THREAD

**Issue by Caratacus** [spring-projects/spring-boot#9697]
> Hi, first of all, thanks for contributing to such a good project, there is now a problem that bothers me when I need to read the resource file under the resource can not read, use jar package when starting

![image](https://user-images.githubusercontent.com/20453060/27958862-8b6c918c-6357-11e7-83d0-e9e6dcfaca4b.png)

> When I use the `.war` start the way everything is normal

> war maven pom.xml 

```
          <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>xls</nonFilteredFileExtension>
                        <nonFilteredFileExtension>xlsx</nonFilteredFileExtension>
                        <nonFilteredFileExtension>p12</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>
```

> I want to start with `java -jar`, Now what do I need to do?

> spring boot `version 1.4.4`

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by Caratacus** [comment]
@wilkinsona  Sorry, [See question in Stack Overflow](https://stackoverflow.com/questions/44972358/spring-boot-the-file-can-not-be-read-use-jar-package-when-starting)
