### ISSUE TITLE
Upgrade to a version of Thymeleaf that's compatible with recent breaking changes in Spring Framework

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9727]
@danielfernandez Thank you for [keeping](https://github.com/thymeleaf/thymeleaf-spring/commit/b1240eaa987d79e302ecebaf76ccb161d0c2bbfd) [pace](https://github.com/thymeleaf/thymeleaf-spring/commit/91c19ecf05815955d0b90a406e5940f0d2b2adaa) with Spring Framework 5's recent API changes. We have Boot 2.0 M3 planned for next week (20 June) that will use Spring Framework 5.0 RC3. It'd be great if we could update to a new Thymeleaf release that's compatible with the latest changes in Spring Framework. Does that fit with any plans that you may have for a new release of Thymeleaf's Spring 5 integration? I believe that Spring Framework 5.0 RC3 is due on 18 June.

**Comment by danielfernandez** [comment]
Yes, this should have happened at least a couple of weeks ago (having boot depend on a Thymeleaf snapshot is bad, of course), but we had an infrastructure issue, really sorry for that.

Anyway, there should be a new Thymeleaf version before the week ends, I just wanted to try a couple minor modifications before that.

**Comment by gregturn** [comment]
@danielfernandez I have been testing my code against 3.0.7-SNAPSHOT. My server code has both Spring WebFlux and Spring Cloud Stream, resulting in two `ConversionService` beans getting registered.

This unfortunately breaks `ThymeleafReactiveView.renderInternal()` where it expects to fetch 0 or 1 of such beans. What is the best of course of action to resolving such an issue?

**Comment by danielfernandez** [comment]
@gregturn  See thymeleaf/thymeleaf-spring#149

**Comment by danielfernandez** [comment]
All changes at the Thymeleaf side are done, so I've been tempted to release Thymeleaf `3.0.7.RELEASE` today, compiling thymeleaf-spring5 against Spring `5.0.0.BUILD-SNAPSHOT`… but I've seen that at least one signature of a class thymeleaf-spring5's code depends on was changed only 3 days ago (`RequestPath`), so I believe it will be probably better to wait until 18 July for `5.0.0.RC3` so that I can compile against the same RC milestone that Boot `2.0.0.M3` will be based upon, which should be much safer.

I should be able to release Thymeleaf quickly after Spring's RC goes public, so I hope that's OK for you too.

**Comment by wilkinsona** [comment]
@danielfernandez Sounds great. FWIW, I think waiting for RC3 is the right thing to do; I wouldn't recommend releasing against a snapshot.

**Comment by danielfernandez** [comment]
Yes, of course. However in this case being the dates quite tight and Boot managing the versions of these dependencies (and `RC2` not being an option due to API changes), I thought about the possibility of trusting the signatures would remain stable until `RC3`. But anyway, as I said I was just 'tempted' ☺️

**Comment by wilkinsona** [comment]
@danielfernandez Just in case you weren't already aware, Framework RC3 was released this morning.

**Comment by danielfernandez** [comment]
@wilkinsona Yup. Thymeleaf 3.0.7 is in the oven ;)

**Comment by danielfernandez** [comment]
Thymeleaf `3.0.7.RELEASE` has just been published, along with thymeleaf-spring5 `3.0.7.RC1` :)

**Comment by wilkinsona** [comment]
@danielfernandez Thank you!
