### ISSUE TITLE
How to use Spring Boot to serve static content located in folder outside the workspace?

### ISSUE THREAD

**Issue by sachinavinaw** [spring-projects/spring-boot#9739]
Hi there.

I was trying to load image located at d:/images/profile/avtar.jpg in spring boot application ( spring v1.3.1) 

I found many solutions, one of them is [Here](https://stackoverflow.com/questions/21123437/how-do-i-use-spring-boot-to-serve-static-content-located-in-dropbox-folder)

I added these lines in :
 `public class SecurityConfiguration extends WebMvcConfigurerAdapter {
...
}`

`@Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/profile/**").addResourceLocations("file:///d:/images/profile/");
    }`

and jsp code snippet:
`<img src="<c:url value="profile/avtar.jpg" />" alt="" class="mCS_img_loaded">`

Still it shows 404 error.
Can anyone help me?

Thanks in advance.

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
