### ISSUE TITLE
Autowired service is null in SpringBoot class

### ISSUE THREAD

**Issue by alexandroscgb** [spring-projects/spring-boot#9754]
Hi. I think I have an easy one.
I have the SpringBoot class, the usual one

```java
@EnableAutoConfiguration
@EnableJpaRepositories(basePackages = { "co.com.jupiter.auctions.repositories" })
@SpringBootApplication(scanBasePackages = { "co.com.jupiter.autctions" })
```

and as an attribute, I have an autowired service that is null when tried to be used.
`@Autowired
private static ProfileService profileService;`

This profileService in turn uses other autowired components. I tried to use this service inside this SpringBoot class initialization, and also inside the main method of this SpringBoot class. In both cases, this service is null.

I bet it has something to do with the lifecycle of SpringBoot, and the whole purpose of what I'm trying to do is to initialize certain parameters into memory once, just once, when the app initializes. This autowired goes to the database.

How could I do this if in this part of the SpringBoot app, dependency injection has not injected services yet?

When I do this in a controller, it works, services are already injected, but in a controller, it would go the database every time a request is done to this controller.

Thanks.

**Comment by philwebb** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/
spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that 
other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by philwebb** [comment]
This does sound like a liefecyle issue rather than a bug. Perhaps you're trying to access beans too early. I'd suggest providing a sample application if you ask on stackoverflow.com so that people can see exactly what you're trying to do.

**Comment by alexandroscgb** [comment]
Thank you, you're right. I didn't think this thoroughly. This should be on stackoverflow.
