### ISSUE TITLE
[Question] How to custom create an annotation like @Value

### ISSUE THREAD

**Issue by regardfs** [spring-projects/spring-boot#9759]
Question:
Hi, I use Etcd as distributed key/value configuration store, and I have finish all basic code and I want to use Etcd key/value like `@Value` annotation, for example `@EtcdValue("/a/b/c")`

I have defined the @interface as bellow:
> @Target({ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER, ElementType.ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface EtcdValue {
      etcdValue();
}

and I am confusing about next step, it seems I need a class with method like 

> @Before("@within(com.exmaple.etcd.config.EtcdValue)")
public void before(Method method) {}

Could u guys could give some clue about how to fulfill this US?Thanks a lot

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
