### ISSUE TITLE
How to continue the interrupted batch job after application started

### ISSUE THREAD

**Issue by deanwong** [spring-projects/spring-boot#9769]
Question

My batch task was triggered by end user, so I do not want to execute all batch jobs when application startup (with spring.batch.job.enabled=false), 
but i hope there is a solution to deal with this situation:
When application started spring-batch frw could continue the interrupted batch job caused by app restart or or exceptional interruption.

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
