### ISSUE TITLE
Upgrade to bean validation 2.0

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-boot#9784]
Bean validation 2.0.0.CR3 has been released: http://beanvalidation.org/news/2017/07/12/bean-validation-2-0-cr3-submitted-to-final-approval-ballot/

This version has been submitted to final approval ballot, so it should be pretty much what 2.0 will be. It has a number of very useful features (including new annotations and the ability to use annotations on elements of generic containers) that would be great to have available in Spring Boot 2.0.

**Comment by wilkinsona** [comment]
It looks like things were in [good shape from the Framework's perspective](https://jira.spring.io/browse/SPR-13482) with beta 2.

@jhoeller Have you had a chance to test against Hibernate Validator 6.0 CR3? I noticed that you're still compiling against 5.4.1 so I'm guessing there's some manual testing involved here?

**Comment by candrews** [comment]
Bean Validate 2.0 has been released: http://beanvalidation.org/news/2017/08/07/bean-validation-2-0-is-a-spec/
Hibernate Validator 6.0 final: http://in.relation.to/2017/08/07/and-here-comes-hibernate-validator-60/

**Comment by jhoeller** [comment]
For full Bean Validation 2.0 compatibility from the core framework perspective, we had https://jira.spring.io/browse/SPR-15839 to fix still which I'll commit later today. I've also ran the tests against Hibernate Validator 6.0.1 and all seems to be good there.

As for building against Hibernate Validator 5.4.1 by default, that's for Bean Validation 1.1 compatibility: BV 2.0 forces us to declare {{getClockProvider()}} on {{LocalValidatorFactoryBean}}, referring to the new {{ClockProvider}} interface as a return type and therefore potentially breaking at runtime against BV 1.1 (e.g. when annotation detection code does {{getDeclaredMethods()}} on {{LocalValidatorFactoryBean}}). Since we don't really care about that new method and don't expect anyone to call it against our decorator, the easiest way out is to keep building against BV 1.1 and simply not declare that method.

I'll try to reduce that Bean Validation 1.1 build dependency to the {{spring-context}} module. All higher-level modules with Bean Validation integration should be able to compile and run their tests against Hibernate Validator 6 and Bean Validation 2.0, also providing us woth places to put BV 2.0 specific tests.

**Comment by wilkinsona** [comment]
Thanks, @jhoeller. Looks like we can make this upgrade in M5.

**Comment by candrews** [comment]
FYI, Hibernate Validator 6.0.2 has been released: http://in.relation.to/2017/08/22/hibernate-validator-602-final-out/
