### ISSUE TITLE
Welcome page(classpath:/static/index.html) not being resolved for / uri in webflux project

### ISSUE THREAD

**Issue by bijukunjummen** [spring-projects/spring-boot#9785]
For a webflux project(using 2.0.0.M2) the welcome page in `classpath:/static/index.html`  is not getting resolved for root uri `/` and returns a 404 status. 

However it is served out if I access `/index.html` explicitly.

**Comment by mikaelhg** [comment]
A workaround:

```kotlin
@Configuration
class ApplicationRoutes {

    @Value("classpath:/static/index.html")
    private lateinit var indexHtml: Resource

    @Bean
    fun mainRouter() = router {
        GET("/") {
            ok().contentType(TEXT_HTML).syncBody(indexHtml)
        }
    }
}
```

**Comment by ilya-medvedev** [comment]
Hi!

Question on stackoverflow contains workaround: https://stackoverflow.com/questions/45147280/spring-webflux-how-to-forward-to-index-html-to-serve-static-content

**Comment by sivaprasadreddy** [comment]
Why not have **addViewControllers(ViewControllerRegistry registry)** method in **WebFluxConfigurer** similar to **WebMvcConfigurer**?

**Comment by wilkinsona** [comment]
@sivaprasadreddy `WebFluxConfigurer` is part of Spring Framework.

**Comment by bclozel** [comment]
Waiting for [SPR-17389](https://jira.spring.io/browse/SPR-17389).

**Comment by jan-peremsky** [comment]
@bclozel 
The commit 525e03d3b5e33494e80e5efb8c26ed80547c1676 affects spring boot applications defining their own explicit welcome pages via explicit `RouterFunction` bean.
This is because the `WelcomePageConfiguration` has no `@ConditionalOnXXX` annotation so it effectively overrides/supersedes any welcome page configuration provided in the application because it is processed prior to the `RouterFunction` defined in the app.
And if the explicit welcome page is rendered from a template with an explicit model `ServerResponse.ok().render("index", model)` it is not rendered correctly.

`@Order` annotation has to be used on the explicit welcome page `RouterFunction`.

If this behavior is intentional, it should be at least documented. Otherwise it is a bug.

**Comment by bclozel** [comment]
@jan-peremsky See #21909

**Comment by xJoeWoo** [comment]
> @bclozel
> The commit [525e03d](https://github.com/spring-projects/spring-boot/commit/525e03d3b5e33494e80e5efb8c26ed80547c1676) affects spring boot applications defining their own explicit welcome pages via explicit `RouterFunction` bean.
> This is because the `WelcomePageConfiguration` has no `@ConditionalOnXXX` annotation so it effectively overrides/supersedes any welcome page configuration provided in the application because it is processed prior to the `RouterFunction` defined in the app.
> And if the explicit welcome page is rendered from a template with an explicit model `ServerResponse.ok().render("index", model)` it is not rendered correctly.
> 
> `@Order` annotation has to be used on the explicit welcome page `RouterFunction`.
> 
> If this behavior is intentional, it should be at least documented. Otherwise it is a bug.

Totally agreed!

`RouterFunction` bean method is marked `@ConditionalOnMissingBean(RouterFunction::class)` in my util library. It collects custom routers and transform them into Spring's `RouterFunction`. 
Now all projects that depends on util library got 404 due to no routers were registered! `@Order(0)` was useless, `@ConditionalOnMissingBean` had to be removed for now.

Will next update fix the pollution of  `RouterFunction`?

**Comment by bclozel** [comment]
@xJoeWoo See #21909

**Comment by xJoeWoo** [comment]
@bclozel Thanks! Is there any clues about the release time of new version?

**Comment by bclozel** [comment]
The scheduled release dates are available on GitHub. See https://github.com/spring-projects/spring-boot/milestone/173

**Comment by cdprete** [comment]
Hello.

Is there a reason why the welcome page support is added only if the path matches `/**` and not if it matches what's configured for `spring.webflux.static-path-pattern`?

**Comment by bclozel** [comment]
@cdprete there might be a reason but it's been few years so I can't recall.

**Comment by cdprete** [comment]
> [@cdprete](https://github.com/cdprete) there might be a reason but it's been few years so I can't recall.

@bclozel I'm asking because I would like to expose something under `/api-docs` but I would like to avoid the workarounds present online.
Especially considering that for the servlet environment it works...

**Comment by bclozel** [comment]
@cdprete You can create a new issue requesting that change and we'll look into it.

**Comment by cdprete** [comment]
> [@cdprete](https://github.com/cdprete) You can create a new issue requesting that change and we'll look into it.

Done: https://github.com/spring-projects/spring-boot/issues/47384
