### ISSUE TITLE
Can RequestMapping set default ResponseStatus?

### ISSUE THREAD

**Issue by steventong** [spring-projects/spring-boot#9789]
When I use PostMapping, I will give a CREATED response status together by ResponseStatus annotation. The same as DeleteMapping, PutMapping, ect.

So, is there any way to set the default response status at different requestMapping?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
