### ISSUE TITLE
NonWebEnvironment is not working with Spring AMQP

### ISSUE THREAD

**Issue by Pyohwan** [spring-projects/spring-boot#9838]
Hello.
I am using Spring boot 1.5.4 with Spring AMQP.
I want non web environment and configured setWebEnvironment(false) in SpringApplication.
But, found out this message on console.
```
Started DemoApplication in 3.436 seconds (JVM running for 3.952)
```
JVM is not killed.
I think, @RabbitListener causes some problems. this listener executed every 1 second.
How to setWebEnvironment(false) configuration work? 

attached simple project zip file. (you need to connect rabbitMQ server)

[nonWebEnvironmentNotWorking.zip](https://github.com/spring-projects/spring-boot/files/1167389/nonWebEnvironmentNotWorking.zip)

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
