### ISSUE TITLE
actuator is  unusual,please help me!

### ISSUE THREAD

**Issue by SoberChina** [spring-projects/spring-boot#9877]
Hello everyone:
      My project add the actuator,spring boot version is 1.5.3 is unusual,but in version 1.4.3 is ok，What's the difference about actuator?
1.4.3：
![image](https://user-images.githubusercontent.com/10227558/28653395-e804eefe-72bf-11e7-9ecd-3a9f80f962e1.png)
1.5.3：
![image](https://user-images.githubusercontent.com/10227558/28653441-21ed4fd0-72c0-11e7-903e-9ddf7254bb2a.png)
thanks!

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
