### ISSUE TITLE
jacksonHttpMessageConverter lowercase field

### ISSUE THREAD

**Issue by pxzxj** [spring-projects/spring-boot#9887]
i expect to return a json string of User Object in the controller,so i user the @ResponseBody annotation,
User class has a field USERNAME, it converts to lowercase 'username' in Response json str; can anybody tell me why

Controller:
     @RequestMapping(value="/hello")
    @ResponseBody
    public User index(Map<String,Object> map){
    	User user = new User();
    	user.setUSERNAME("john");
        return user;
    }

User Class:
public class User {
	private String USERNAME;

	public String getUSERNAME() {
		return USERNAME;
	}

	public void setUSERNAME(String uSERNAME) {
		USERNAME = uSERNAME;
	}
	
}

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
