### ISSUE TITLE
Oracle stored proc call is not working from 1.4.x onward 

### ISSUE THREAD

**Issue by abhineet27** [spring-projects/spring-boot#9888]
After I upgraded spring boot from 1.3.x to 1.4.x or even 1.5.x oracle stored proc call is failing with the error: PLS-00306: wrong number or types of arguments where as same code works with 1.3.x version.
I have a dependency to ojdbc6 11.2.0.3. Is there any change or library I have to include to make this work ?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by abhineet27** [comment]
@wilkinsona as suggesgted I have put this on stackoverflow. https://stackoverflow.com/questions/45366858/oracle-stored-proc-call-is-not-working-from-spring-boot-version-1-4-x-onward
