### ISSUE TITLE
Could not configure spring.mail.properties using OS env variables

### ISSUE THREAD

**Issue by pluttrell** [spring-projects/spring-boot#9902]
SpringBoot does a great job of treating environment variables such as `spring.mail.host` and `SPRING_MAIL_HOST` as the same thing. But for the JavaMail properties, it just uses the exact environment variable. So `SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLES` is passed directly to the JavaMail API, which doesn't respond to the uppercase+underscore version but works fine with the lowercase+dots version `spring.mail.properties.mail.smtp.starttls.enable`.  

This wasn't a problem before because users just needed to make sure and use only the lowercase+ dotted version in the environment variable name. It appears that `sh` was recently changed to stop passing environment variables with dots in them. This bit us as we're using the [openjdk-jre-alpine docker images](https://hub.docker.com/_/openjdk/) which along with the JRE 8u131 upgrade included a newer version of Debian. I've reported this issue to the github repo for the openjdk docker image images as [issue 135](https://github.com/docker-library/openjdk/issues/135) and it appears that they are switching to bash to avoid it.

I thought I'd also propose an enhancement to SpringBoot. Perhaps it can convert all JavaMail properties to the lowercase+dot version as to avoid this issue from impacting users who might try the uppercase+underscore version. I think this behavior would be a logical default as it would match what the JavaMail API requires.

**Comment by snicoll** [comment]
Unfortunately I don't think it is. That `spring.mail.properties` map is a convenience to access to library specific properties that we don't expose ourselves. We shouldn't mess with the contract of `Map` for sure: we don't know the semantics of the key and cannot afford to apply relaxed binding on it. 

Having said that, the issue is real and applies to other areas where we exposed advanced options. I'll flag this for team attention.

**Comment by philwebb** [comment]
There doesn't seem to be particularly sane way to come up with a global rule for putting environment variables into Maps. One person might want lowercase and dots, another might prefer that things are passed in unchanged.

I'd probably prefer that this kind of problem is solved using an entry in `application.properties` that references the actual environment variable needed. So something like this in `application.properties`:

```
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_SSL:false}
```

Then set `SMTP_SSL` as an environment variable.

The other option would be to use `-D` arguments to the JVM since these do support dots.

**Comment by wilkinsona** [comment]
Perhaps we could use an annotation on the binding target (getter for the map, for example) that provides a hint to the binder about how keys should be formatted?

**Comment by philwebb** [comment]
Worth investigating perhaps, although it still adds complexity that I'm not entirely comfortable with.

**Comment by wilkinsona** [comment]
Agreed. There's no guarantee that the format required by a third-party library will be something to which we can map an environment variable. We'd probably be setting an expectation that it would work when we can't guarantee that it will.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. As described above, we don't think we can fix this in a way that'll work for everyone. Our recommendation is the approach that Phil [described above](https://github.com/spring-projects/spring-boot/issues/9902#issuecomment-318848482).

**Comment by pluttrell** [comment]
@wilkinsona @philwebb Thank you for considering this a few months ago. I understand that we can't know in advance _globally_ what requirements a particular API might have. However having implemented the suggested solution and been bit by this issue yet again today, I'd like to point out a couple of things and suggest that this be re-considered on a more localized basis: Just the JavaMail auto configuration.

Regarding @philwebb's suggestion to add a line such as the following to the `application.properties`, where I've used the uppercase+underscore version as the environment variable: 
```
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:false}
```
Consider the following:

1. We, and I think most users, would not like to limit our operators from supplying any valid JavaMail options directly to Spring. As such this means manually mapping all possible options anywhere we use Spring's JavaMail support. According to the [latest JavaMail release docs](https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html) there are currently 53 supported options. Perhaps SpringBoot should set these automatically as part of the auto-configuration.
1. This requires that we choose a default value for each possible option. If improperly chosen, operators could waste quite a bit of time trying to debug their SMTP configuration - a notoriously difficult thing to do, especially since the configuration needs pass through our app, into Spring, into JavaMail. Some of the default options provided by the API are straight forward, others are not, for example we really don't want `mail.smtp.auth.ntlm.domain` defaulted to anything.
1. This does not provide a way to *not* set a value. Other then the few values that we intend to set, we really want all of the JavaMail's default values.
1. This results in SpringBoot adding *both* the uppercase and lowercase version to the `properties.properties` map within the `spring.mail-org.springframework.boot.autoconfigure.mail.MailProperties`. Based on the docs and my observations, only the lowercase+dot options are used by the JavaMail API. This could lead to a negative DX (developer experience) as anyone viewing the properties through the `/configprops` actuator endpoint might incorrectly assume that the values are being used. 

I would like to request that we re-open this ticket and consider an option that just fixes the JavaMail auto-configuration. Here is what I propose:

1. Since the JavaMail API doesn't respond to the uppercase versions, SpringBoot should not set them.
1. Since the JavaMail API requires the lowercase+dot version, I propose that SpringBoot converts the uppercase+underscore version to the lowercase+dot version when building the `properties.properties` map within the `spring.mail-org.springframework.boot.autoconfigure.mail.MailProperties`. 

This will resolve all of the issues I've mentioned above, improve DX as no user will need to any extra configuration (or property translation) in order to get a fully functioning JavaMail service out of the box.

**Comment by wilkinsona** [comment]
The arguments made by @pluttrell are rather compelling. Rather than the annotation the acts as a hint that I suggested above, perhaps we can confine the complexity to `MailProperties` or the auto-configuration that consumes it. However, knowing exactly what to map and how it should be mapping at that point is rather tricky.

> There doesn't seem to be particularly sane way to come up with a global rule for putting environment variables into Maps. One person might want lowercase and dots, another might prefer that things are passed in unchanged.

On second reading, I'm not sure that I agree with that. A key feature of `@ConfigurationProperties` is that configuration can come from a number of different sources and the binding hides the different configuration forms from you. IMO, it would be beneficial for that to apply to the keys in a `Map` property too. If the keys were converted into Boot's canonical key format it would allow a configuration properties class to make assumptions about the keys and to, if necessary, more easily map them into another format.

**Comment by snicoll** [comment]
I've already had that request to show keys in canonical format in the env endpoint (kebab case). It isn't possible AFAIK.

**Comment by wilkinsona** [comment]
Looking more closely at the Java mail properties, I can't see any way to map to them as their formatting is inconsistent. Take these three properties for example:

- `mail.smtp.ssl.socketFactory`
- `mail.smtp.auth.digest-md5.disable`
- `mail.smtp.localaddress`

`socketFactory`, `digest-md5`, and `localaddress` are using three different ways of separating two words in part of the name of a property. This inconsistency means that I can see no general purpose way in which the properties can be mapped to the required format. The only solutions that I can see would require enumerating some or all of the properties so that the formatting idiosyncrasies can be handled. I don't think we should do that.

**Comment by snicoll** [comment]
Sorry @pluttrell but I don't think we should implement this. To mitigate with this decision, [I've created a demo](https://github.com/snicoll-demos/demo-custom-environment-post-processor) that I think provides an acceptable solution.

As explained in the README, the idea is to use an `EnvironmentPostProcessor` to map OS env properties (for instance) to the target properties the mail API expects. Given the structure of those options as @wilkinsona indicated, I don't think it is crazy to do that.

Back to your concerns:

1. I don't think we should expose 53 options from the mail API given the surface area in Spring Boot, the popularity of this feature and how likely users will actually use each of them
2. The solution above does not force you to set a default value
3. In the solution above, if a matching env variable is not set, no property is set
4. This solution allows you to use whatever prefix you want and, for the reason you exposed here, I'd strongly recommend to use something specific and not pretend it is "almost the same thing" as the standard property (it isn't).
