### ISSUE TITLE
spring.profiles.active=${activeMode}

### ISSUE THREAD

**Issue by yyblove** [spring-projects/spring-boot#9927]
when I use `spring.profiles.active=${activeMode}` in `application.properties`
then I have 2 file 
```
applicaiton-default.properties
application-release.properties
```
I start program from idea,I want spring-boot use applicaiton-default.properties, when  `${activeMode}` is not set value. 
what should I do ?

**Comment by yyblove** [comment]
i use spring-boot 1.5.6.RELEASE

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
