### ISSUE TITLE
@Secured is not working with @Valid

### ISSUE THREAD

**Issue by Pyohwan** [spring-projects/spring-boot#9937]
SecurityConfig
```java
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(securedEnabled = true, jsr250Enabled = true)
public class SecurityConfig extends WebSecurityConfigurerAdapter {
...
```

Controller example
```java
@RestController
@RequestMapping("/api/board")
public class BoardRestController {

    @PostMapping("")
    @Secured("ROLE_USER_01")
    public FreePostWriteResponse addFreePost(
            @Valid @RequestBody FreePostForm form,
            Device device) {
```

I didn't login so my authority is ROLE_ANONYMOUS.
I expect AccessDenied exception when request '/api/board', but Voter is not working.
If remove @Valid, occured AccessDenied exception.
Why @Secured is not working with @Valid?

**Comment by Pyohwan** [comment]
https://stackoverflow.com/questions/28923360/how-to-make-preauthorize-having-higher-precedence-than-valid-or-validated#comment46118507_28923360

**Comment by wilkinsona** [comment]
@Pyohwan It looks like your Stack Overflow link already answers your question. If not, please ask a question of your own on Stack Overflow explaining what is still unclear (so it's not a duplicate). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
