### ISSUE TITLE
how do you update incrementally when deploy jar to Linux ?

### ISSUE THREAD

**Issue by ghs0223** [spring-projects/spring-boot#9959]
When I deploy the executable jar package to linux. When I modified the file locally and how to deploy incrementally to Linux, it was too big to update the entire jar package each time. How did you do that, thx?

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
