### ISSUE TITLE
 How to add Interceptor for static resources?

### ISSUE THREAD

**Issue by wcnjeusr** [spring-projects/spring-boot#9976]
I want to add interceptor for static resources,but it seems to be invalid.
the only effective interceptor is ConversionServiceExposingInterceptor and ResourceUrlProviderExposingInterceptor,related to WebMvcConfigurationSupport.getInterceptors method.
Version:1.5.6.RELEASE

**Comment by wilkinsona** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
