### ISSUE TITLE
Downgrade to Gson 2.8.0 due to show-stopper bug in 2.8.1

### ISSUE THREAD

**Issue by sudr** [spring-projects/spring-boot#9991]
Spring Boot 1.5.6.RELEASE upgraded to Gson 2.8.1 which is the latest release. But it has a show-stopper bug when serializing/de-serializing null values for date fields.

Please see here: 
https://github.com/google/gson/issues/1096

Opening this issue so Spring Boot can account for this bug in Gson either with a downgrade in the next release or an update to a fixed version of Gson is one is available.

**Comment by wilkinsona** [comment]
Thanks for bringing this to our attention. Given that the Gson team haven't rushed to release 2.8.2 it's difficult to agree that, generally speaking, this issue is a showstopper. If it is for you, then you can downgrade to 2.8.0 by overriding `gson.version` in your pom.xml or build.gradle.

We have a semi-automated process for upgrading to new releases of our dependencies. We'll pick up the next release of Gson in due course.
